### ISSUE TITLE
Refactoring suggestion: org.eclipse.smarthome.core.id

### ISSUE THREAD

**Issue by dvanherbergen** [eclipse/smarthome#1004]
The bundle org.eclipse.smarthome.core.id could be merged into other bundles as it only contains 2 classes:

* InstanceUUID : this could be added to org.eclipse.smarthome.core bundle.
* UUIDResource : this could be added to the org.eclipse.smarthome.io.rest bundle. As it already depends on this bundle for the RestResource class, this would be a good place for it IMHO.

Moving these files would also allow the use of the InstanceUUID in a setup without REST, which currently is not possible.

**Comment by kaikreuzer** [comment]
Sorry, this was specifically designed as an optional feature as not all solutions want this.

**Comment by maggu2810** [comment]
@dvanherbergen The package imports for the rest stuff is already marked optional. So it should already working without in a setup without REST. Isn't it?
