### ISSUE TITLE
Remove /rest/setup resource

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1013]
The ThingSetupManager has been marked deprecated and since the `/rest/setup` url is closely related to this class, it should be considered deprecated as well.
In order to be able to remove it, we will have to refactor the Paper UI to use other REST resources instead.

**Comment by cdjackson** [comment]
Currently, the only way to provide a thing a name is to link an item to the thing - if this is deprecated there's currently no solution to this until #710 is implemented (I think?).

**Comment by kaikreuzer** [comment]
Absolutely correct. So it is time to implement #710 soon :-)
@sjka Might you be volunteering?

**Comment by sjka** [comment]
just a note: #710 has been implemented & merged.
