### ISSUE TITLE
Remove "Group" administration from Paper UI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1014]
The Paper UI has its own notion of a "Group", which somehow resembles a room and which is an item with a special "home-group" tag. These are no general ESH concepts at all and thus I would pledge for removing these parts from the UI.
Concretely, I know of the following places:
- main menu entry
- Inbox approval pop-up
- manually adding a Thing
- editing a Thing

I would be ok to keep the "Control" UI to render tabs for different groups based on the "home-group" tag.

**Comment by maggu2810** [comment]
I am fine with removing something that is not well defined.
But what is the current replacement for?

**Comment by kaikreuzer** [comment]
See https://github.com/eclipse/smarthome/pull/1019#issuecomment-183245341
