### ISSUE TITLE
Basic UI - Duplicate events for rollershutters

### ISSUE THREAD

**Issue by StephanReuter** [eclipse/smarthome#1020]
I'm having some issues with the current openHAB2 Beta2 (and also in the Beta1 before) with controlling the blades of my shutters. Using the BasicUI, e.g. UP/DOWN events for the blades are almost always sent twice when using the smartphone (iPhone6). Depending on the time difference between the two identical events, the blades move one step (delta time of ca. up to 100ms) or two steps (delta approx. greater 300ms).

Using the BasicUI on OSX/Ubuntu/Win7 does not sent the events twice. Further, using the classic UI on the smartphone, the problem is also not existing.

**Comment by kaikreuzer** [comment]
@resetnow Could you check that behaviour on iOS?
