### ISSUE TITLE
Problem creating Basic-UI from source

### ISSUE THREAD

**Issue by s-simma** [eclipse/smarthome#1031]
Hi,
I would like to play a little bit with the Basic-UI.
I made some chnages in the ..web-src/smarthome.less file. Run "grunt" after this. The compressed result goes into the ..web folder as smarthome.css. So far ok.

Then i made a clean install from inside the "openhab-distro" folder. But this process does not create a new "org.eclipse.smarthome.ui.basic-0.8.0-SNAPSHOT.jar" file. (old one from 2.2.2016  remains).

So i went into the folder itself an started "mvn clean install". Here i get the error: "..missing package org.eclipse.smarthome.core.events 0.0.0". This package is not installed in the eclipse IDE ?

So maybe someone can help me, how to make changes in the Basic-UI stylesheet available to karaf web container.
i would be grateful for any help.

**Comment by maggu2810** [comment]
If you change an Eclipse SmartHome bundle you have to build the Eclipse SmartHome bundle(s). :wink: 
openhab-distro just uses Eclipse SmartHome bundles, but does not build them.

I am not familiar with the current state of the openHAB stuff at all, but you can checkout the smarthome repo and build the Basic UI after your changes.
After that you can use your running Karaf container and update the currently installed Basic UI bundle with the bundle:update command (https://karaf.apache.org/manual/latest/commands/bundle-update.html).

**Comment by s-simma** [comment]
@maggu2810 
Uff, it took such a long time to compile the openhab-distro, and i thout it compiled the HOLE twice.
thank's a lot.

**Comment by s-simma** [comment]
@maggu2810 
I tried to do a "mvn clean install" in the smarthome folder
-> gives me marven build error .......
moved into "....../extensions/ui/org.eclipse.smarthome.ui.basic folder". "mvn clean install"
-> gives me error "package org.eclipse.smarthome.core.events 0.0.0 required but not found" (i can't find it either)
Is there another way to build the ...ui.basis... JAR file ?

**Comment by maggu2810** [comment]
```
I tried to do a "mvn clean install" in the smarthome folder
-> gives me marven build error .......
```

If the build of the whole repository results in a build error, then create an issue please.
