### ISSUE TITLE
Oh2 startup: binding refresh should be started after item loading

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1038]
Refresh service of bindings should be started after the items are loaded. If not, the risk is that items could be first set only at the time of the second refresh cycle, that is several minutes (hours ?) after OH2 startup for certain bindings.

**Comment by kaikreuzer** [comment]
In what way is this issue related to ESH? ESH does not define any kind of startup orders, so I tend to close the issue here.

**Comment by lolodomo** [comment]
Sorry i don't know what component is managing the startup process.
Where should I create this issue ? Openhab distro ?

**Comment by kaikreuzer** [comment]
As I do not know, what a "refresh service" is (does it serve ice cream?), I cannot really answer. My suspicion is that this rather needs to be addressed in specific bindings and not anywhere in the framework.

**Comment by lolodomo** [comment]
I mean the exexute method called on a regular time for each binding implementing this feature.

There is no easy way to fix that on the binding side.

**Comment by kaikreuzer** [comment]
I assume that the bindings where you have observed the problem have simply missed to overwrite `channelLinked()` in their Thing handler - within this method, a refresh can be triggered.

**Comment by lolodomo** [comment]
If it can be better handled by pure 2.0 bindings, that is a good point but the problem is in fact with 1.x bindings.

**Comment by kaikreuzer** [comment]
Then ESH is completely out of the game here :-)
Best discuss it on a specific binding on the openHAB 1 repo (possibly https://github.com/openhab/openhab/issues/4038?) and we can see what options there are.
