### ISSUE TITLE
Introduce trigger channels for things, which allow modelling of buttons and remote controls

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1043]
Currently, all channels on a Thing are supposed to be linked to an item and thus they inherently carry some state and are a potential entity to be displayed in the UIs.

For wall-buttons, remote controls, etc. this usually does not make sense. Their buttons rather represent the very same as switch widget on a UI, i.e. they are just a mean to operate some item (e.g. a light bulb).
To properly model this, we should introduce a new kind of channel. The idea is to be able to use such new channels directly as triggers for rules (without the need to have any item/link) for them. Alternatively (this is how openHAB 1 works), links could be created to existing items (which would be the equivalent of wiring the button to a lightbulb - the trigger channel must send commands to the item in this case).

**Comment by maggu2810** [comment]
What differs such channels from other ones?
So, if I can use a channel (a wall-button) as a trigger, why do I need to create an item so use a light channel as an output?
I do not know, if we open using channels directly where we stop?
Using channels as a source but not sink, make that sense?

Could you give more details how you think this could be modelled?

Will a channel emit commands or state updates?
Will a channel consume commands or state updates?

**Comment by kaikreuzer** [comment]
> What differs such channels from other ones?

The main difference is that they do not have a state, but only issue events.

> why do I need to create an item so use a light channel as an output?

You do not, that's the idea of using it as a trigger for rules only. The option to link them to an existing "light" item would actually be something like a "simple, hard-wired rule", which does not have to go through the rule engine itself.

> Using channels as a source but not sink, make that sense?

Yes, this is one way you could think of them.

> Will a channel emit commands or state updates?
> Will a channel consume commands or state updates?

I think in the first place, they will only send events like PRESSED, LONG_PRESSED, DOUBLE_PRESSED, RELEASED or something like this (to be specified). These would be the "output" values of the rule trigger module.
For the option to directly wire such a channel to an existing item, such a link would need some configuration (I like speaking of certain "profiles"), which convert the events like PRESSED to according commands like ON or UP.

> Could you give more details how you think this could be modelled?

We will have to discuss this together - I only wanted to capture the requirement in a first step.
I think it would need something like an "eventDescription", which is similar to the "stateDescription" of the regular channels.

You can get an idea of this requirement by looking at the [configuration options of the openHAB EnOcean binding](https://github.com/openhab/openhab/wiki/EnOcean-Binding#rocker-switches): Depending on the "parameters" and the associated item type, the "PRESSED" events are converted to different kinds of commands with different behaviors. This is what the suggested "profiles" should imho provide.

**Comment by maggu2810** [comment]
> You can get an idea of this requirement by looking at the configuration options of the openHAB EnOcean binding: Depending on the "parameters" and the associated item type, the "PRESSED" events are converted to different kinds of commands with different behaviors. This is what the suggested "profiles" should imho provide.

I have already done something similar for the other OH1 binding (perhaps you know):
https://github.com/maggu2810/aleoncean-openhab-binding/blob/master/doc/converter/index.md

**Comment by kaikreuzer** [comment]
Yes, I remember that we discussed these concepts already long ago for openHAB 1 - it is time to get them implemented in the core runtime :-)

**Comment by phxql** [comment]
Hey, I'm currently working on the triggers. My proposal:

* Create a new class `TriggerChannel` which has a `TriggerChannelUID`
* Create a new enum `TriggerEventType` with values `PRESSED`, `RELEASED`, `LONGPRESS_RELEASED`.
* Create a new class `TriggerEvent` which has fields `TriggerEventType`
* Add a new method in the `BaseThingHandler` called `emitTriggerEvent(TriggerChannelUID, TriggerEvent)`
* This emitted event can be used in the ruleengine to trigger rules
* This emitted event can be used in the profiles to trigger item updates

In the XML definition it could be something like this:

```
<event-channels>
	<event-channel id="button_1" eventTypeId="button_1" />
	<event-channel id="button_2" eventTypeId="button_2" />
</event-channels>

<event-channel-type id="button_1">
	<label>Button 1</label>
	<description>Description of Button 1</description>
</event-channel-type>
```

Questions to clarify: 
* Do we need more values in `TriggerEventType`?

What do you think?

**Comment by cdjackson** [comment]
I have a few suggestions to see if it can be better aligned with ZWave...  There are two things here - more possible triggers -:

* Double press
* Tripple press

There might be others, but I think these two should be standardised at least since they seem like they should be needed in many bindings/devices (definately ZWave)...

The other issue is timing. Currently in ZWave scene triggers, they provide a time value along with a trigger type - so we might have a 'scene' that is DOUBLE_CLICK(3 seconds). This would be passed to the rule so that it can be read and used in the rule. The idea is that this can be used to provide a light ramp rate (for example).

Maybe this is considered ZWave specific, but I would suggest we could add a generic ```properties``` member that can store this sort of implementation specific data and could be read out in the rule?

**Comment by phxql** [comment]
The `properties` will be a map from String -> Object?

**Comment by cdjackson** [comment]
> The  properties  will be a map from String -> Object?

Yes, that was my thought anyway. Maybe there's a better solution, but this would be consistent with other 'properties' within ESH.

**Comment by rtvb** [comment]
> https://github.com/eclipse/smarthome/issues/1043#issuecomment-225809944 : 
> Questions to clarify:
> 
> * Do we need more values in `TriggerEventType`?
> 
> What do you think?

@kaikreuzer mentioned this issue in a Community thread about [Simulation of Astro events](https://community.openhab.org/t/simulate-astrobinding-events-in-oh-2/11594/6).

So if these kind of events are to be supported, an event type like **STARTED** or **FINISHED** should be available. 

Thinking even further, you might also consider types like PAGEUP, PAGEDOWN, HOME, END etc. Much like a keyboard. :)

**Comment by phxql** [comment]
A keypress on a keyboard could be modelled as `PRESSED` and `RELEASED`, with the keycode stored in the `properties` map.

**Comment by kaikreuzer** [comment]
@phxql I don't think we should try to come up with an exhaustive list of possible events. Modelling every button on a keyboard/remote control imho does not make sense - instead it should imho be possible to send any kind of String as an event, like it is e.g. done as a ["regular" channel in the Harmony binding](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.harmonyhub/ESH-INF/thing/thing-types.xml#L60) right now.
Similar to the [state descriptions](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#state-description), the bindings should have a chance to declare their possible events either statically in the XML or dynamically through a Java implementation.

In order to minimize the number of variations that people might come up with such triggers, we could define system trigger channel types (as we have for regular channels as well), e.g. for pressed/releases standard use cases.

**Comment by kaikreuzer** [comment]
@cdjackson I would refrain from adding properties/parameters to those trigger events. After all, we do not have properties on state updates or commands either, so that I would like to keep the concepts as similar as possible. After all, these channels are supposed to be a equivalent to UI control widgets, which also do not send any further properties.

@phxql I am not sure we should introduce new elements "event-channel" and "event-channel-type" in the XML. Why not simply say these are channels as well? The only thing we would have to change is the channel-type definition to e.g. say that this is not linked to items, but that it can send trigger events according to a list of given profiles. A default "raw" profile (with which we can start) would mean that it only emits the raw events (according to an optionally given trigger-description).

Note in this context that we might have other kinds of channels added in future, e.g. there is already the discussion around having [an "audio-sink" channel for speaker devices](https://github.com/eclipse/smarthome/issues/1200).

**Comment by phxql** [comment]
Okay, so `TriggerEvent` contains a `String` field which denotes the event.

In the XML:

```xml
<channels>
    <channel id="button_1" typeId="button_1" />
    <channel id="button_2" typeId="button_2" />
</channels>

<channel-type id="button_1" type="event">
    <label>Button 1</label>
    <description>Description of Button 1</description>
    <events>
        <event value="PRESSED" />
        <event value="RELEASED" />
        <event value="DOUBLE_CLICK" />
    </events>
</channel-type>
```

Something like this?

**Comment by kaikreuzer** [comment]
Let me have a try. Currently the documentation says
```xml
  <channel-type id="channelTypeID" advanced="{true|false}">
    <item-type>Dimmer</item-type>
    <label>String</label>
    <description>String</description>
    <category>String</category>

    <tags>
      <tag>String</tag>
      ...
    </tags>

    <state min="decimal" max="decimal" step="decimal" pattern="String" readOnly="{true|false}">
      <options>
        <option value="String" />
        OR
        <option value="String">String</option>
        ...
      </options>
    </state>
  </channel-type>   
```

Let's try to come up with something usable for a few different examples.

Homematic wallbutton:
```xml
  <channels>
    <channel id="button_1" typeId="button" />
  </channels>

  <channel-type id="button" advanced="{true|false}">
    <!-- if the trigger channel emits different kinds of event values, I'd suggest we use our existing type system from org.eclipse.smarthome.core.library.types.*, this makes it easier to map them to commands through profiles in a second step. -->
    <trigger-type>String</trigger-type>
    <label>Button</label>
    <description>Description of Button</description>
    <category>wallswitch</category>

    <event>
      <options>
        <option value="PRESSED">pressed</option>
        <option value="RELEASED">released</option>
        <option value="DOUBLE_PRESSED">double pressed</option>
      </options>
    </event>
  </channel-type>   
```

Astro sunrise event:
```xml
  <channels>
    <channel id="sunrise" typeId="trigger">
      <label>Sun rise</label>
      <description>Triggers at the moment of the sun rise</description>
      <category>wallswitch</category>
    </channel>
  </channels>

  <!-- this should be a default system trigger - no need to have this defined per binding -->
  <channel-type id="trigger" advanced="{true|false}">
    <!-- "none" means that there is actually no value associated with the event. All there is is a "fired!" event. -->
    <trigger-type>none</trigger-type>
  </channel-type>   
```

Leapmotion "circle" gesture event:
```xml
  <channels>
    <channel id="circle" typeId="increaseDecrease">
      <label>finger circle gesture</label>
      <description>Changes a level incrementally by moving a finger in a circle left or right</description>
      <category>gesture</category>
    </channel>
  </channels>

  <!-- this should probably also be a default system trigger - no need to have this defined per binding -->
  <channel-type id="increaseDecrease" advanced="{true|false}">
    <trigger-type>IncreaseDecrease</trigger-type>
  </channel-type>   
```

@kgoderis @gerrieg @marcelrv As you are all implementing bindings that need this feature (or are at least impacted by it): Please feel free to join the discussion as well!

**Comment by kgoderis** [comment]
@kaikreuzer Yes, indeed, I have some bindings that could benefit from the concept:
 - KNX; a direct mapping of some KNX Telegrams / DPT can made onto <event><options>, I think
 - Helios; some Helios have a built-in keyboard, and emits a Key_Pressed / Key_Released event, but cfr the discussion on properties of the events, these events emitted by the device contain the value of the key that was pressed. Attaching properties will avoid defining a channel for every single button on the device

That being said, for me the benefit of the concept is that we do not have to track the state of a physical button anymore (that was the first reason to have those artificial Items). However, how would you go about integrating these event-channels in the UI? How would we trigger the events from the ESH/OH UIs? If there is no intention to have a mechanism to display the events/channels themselves, I think it should still be possible to link these channels to a regular/placeholder Item in order to display a state, or the event itself. Some physical (even stateless) switches have an interface of some kind that denotes the state of a switch. For example, my Basalte KNX actors typically underline the name of a switch on the display to denote it has been switched on. So, you would typically want to display the state in the ESH/OH UI as well, to keep the two of them in sync.

Kai, if you consider the Sonos binding, using Player Items to control and depict the state of the player, how would that be dealt with in the concept?

**Comment by gerrieg** [comment]
For the Astro binding, isn't every channel-type with a DateTime item-type (with a value in the future) automatically a trigger without the need for a extra definition? 

example:
```
DateTime Sunrise  "Sunrise [%1$tH:%1$tM]"  { channel="astro:sun:home:rise#start" }
```
rule:
```
when
    Item Sunrise received event
then
```
or rule with an offset, so that the event fires 3 minutes before
```
when
    Item Sunrise received event with offset -3m
then
```

**Comment by kaikreuzer** [comment]
@kgoderis:

> However, how would you go about integrating these event-channels in the UI? How would we trigger the events from the ESH/OH UIs?

You do not trigger triggers, see https://github.com/eclipse/smarthome/issues/1043#issuecomment-184598078: "The option to link them to an existing "light" item would actually be something like a "simple, hard-wired rule""
This is exactly the same way as it works in OH1: You have one item that represents the light and you have the "actuator" channel linked to that item as well as the wall-button "trigger" channel (and to allow those "simple rules", we will need the profiles that were briefly discussed above as well).

> if you consider the Sonos binding, using Player Items to control and depict the state of the player, how would that be dealt with in the concept?

The player has a state and we have the according item type for it. I don't see any need for "pure" triggers in that situation, i.e. no need to change anything. Or am I missing your point?

@gerrieg:

>  isn't every channel-type with a DateTime item-type (with a value in the future) automatically a trigger without the need for a extra definition?

Good point, but you are actually missing something very important: This idea is fully independent of any binding (and thus Thing/Channel discussions). Yes, we can say that EVERY DateTime item could be interpreted as a trigger. So all we need to do is to define a trigger module type for the rule engine that allows the user to select a DateTime item (and maybe an offset).

**Comment by cdjackson** [comment]
> @cdjackson I would refrain from adding properties/parameters to those trigger events.

Ok, but how can we make use of information that different systems might provide? We could handle these different bits of information as different items, but then we have an issue with ensuring consistency unless we have some sort of "structure" item that can group data together.
Alternatively, we could try and encode the value into a string or integer, or even json encode the data to a string, in order to allow the provide the different data components, but this is just a bodge to me.

I would have liked to have seen some sort of clean way to handle scenes and triggers that allowed concepts from different systems to be used.

**Comment by feens** [comment]
@kaikreuzer I guess my question, as an end user is this: with triggers, how would I go about handling something like a double (or triple) tap from an actual item (i.e. a dimmer switch).  My expectation would be to a have a rule such as "Item Dimmer_Kitchen received command DoubleTap".  Is that the end goal of these trigger channels? I guess I wouldn't really think of DoubleTap as channel but as an event.

**Comment by kgoderis** [comment]
> However, how would you go about integrating these event-channels in the UI? How would we trigger the events from the ESH/OH UIs?
> You do not trigger triggers, see #1043 (comment): "The option to link them to an existing "light" item would actually be something like a "simple, hard-wired rule""
> This is exactly the same way as it works in OH1: You have one item that represents the light and you have the "actuator" channel linked to that item as well as the wall-button "trigger" channel (and to allow those "simple rules", we will need the profiles that were briefly discussed above as well).

I think I am lost here. My question was rather : if these event-channels represent a button as you mention in the example, how is that button then integrated/rendered/.... in for example the BasicUI? Since the idea is not to have an Item anymore, and since .sitemaps are driven by Items, .....

**Comment by kaikreuzer** [comment]
@cdjackson:
> Alternatively, we could try and encode the value into a string or integer

Yes, this is my suggestion (see e.g. for [remote controls](https://github.com/eclipse/smarthome/issues/1043#issuecomment-226436416)). If you have more complex content, this might also be discussed for the profiles, which I see as a second step. But in this feature, I do not see parameterized events, since with the same right you can also ask for parameterized commands and states for the other channels - and such a discussion is definitely out of scope here (but feel free to open a separate one about it).

@kgoderis:
> how is that button then integrated/rendered

Not at all and that's the whole point here. I guess you also do not have your KNX wall-buttons rendered in your UI, but rather the lights&shades that you are controlling with them. See again [the link] I already mentioned above: These are usages to "control a roller shutter" and "to control a dimmer", but the device itself is NOT a shutter or a dimmer, but a rocker. The rocker itself does neither exist as items on its own right, nor does it appear in any UI.

@feens: There is no "tap from an [...] item". As explained to @kgoderis, the concept is really meant to only make available what is possible since the beginning in openHAB 1. So with such trigger channels + profiles in place, there is in the best case no need to have any rules. If one wants to have custom logic and work with the "raw event data", we could come up with rules like "On event DoubleTap of Channel123" or similar.

**Comment by maggu2810** [comment]
I added some rockers to my system recently.
I have to encode
* up pressed
* up released
* down pressed
* down released

For that I created two channels, one for up and one for down.
The item-type is set to switch, so I have on for pressed and off for released.

To use the rockers to switch other stuff on or off, I would like to leave it to the user if he want to use the pressed or released event and also if the up or down is used to switch it on / off.

For an easy setup, I created a rule template (something similar to on-off-on-pressed).
If you create a rule from template, you have to define two switch inputs (already filtered to switch items thanks to the recently added context filter in the Paper UI), one for 'turn on' and one for 'turn off' and at least one switch output - the device that should be turned on or off.

I already think about using another template for on-off-on-released or if I add a configuration to that rule template, which the user can use to configure special modes.

I think it is correct that there is no real use case for the items of a rocker, as we do not need to "see" the rocker in an UI.

What do you think should be the channel for a rocker`I think the four different states are valid for a lot of rockers, at least if you want to bind it to a roller shutter, you could be interested in pressed + release and up + down events (start moving up on up pressed, stop on released (up/down), start moving down on down pressed).

**Comment by kaikreuzer** [comment]
What you have done with the rule templates sounds very much like the "profiles" - i.e. a mechanism that translates the raw events into commands for existing items.

> What do you think should be the channel for a rocker

I think this can depend on the rocker and its configuration. Many rockers are designed in a way that they switch one functionality only (i.e. pressing top for ON/UP and bottom for OFF/DOWN). But many (e.g. my KNX wall-switches) can be configured to either work as a rocker (Wippe) or as two individual buttons (Taster). So the first would correspond to one channel only), while the second configuration corresponds to two channels (because two individual functions can be controlled). And again, I would not want to limit what events the rockers are allowed to send. I have seen so many different devices having different outputs that there is simply no single solution (toggle, pressed/released, up/down/stop, shortpress/longpress, etc.).

**Comment by kaikreuzer** [comment]
FTR, here is some initial code for the further discussion: https://github.com/eclipse/smarthome/pull/1936 (thanks @phxql)

**Comment by dominicdesu** [comment]
Just wondering, should this ticket be closed?
