### ISSUE TITLE
Create test for PR 1037

### ISSUE THREAD

**Issue by marinmitev** [eclipse/smarthome#1045]
https://github.com/eclipse/smarthome/pull/1037
extend the Groovy test AutomationIntegrationTest.groovy
\smarthome\bundles\automation\org.eclipse.smarthome.automation.integration.test\src\test\groovy\org\eclipse\smarthome\automation\integration\test\AutomationIntegrationTest.groovy
and check not only for rule state when bundle disappears but also to check for existing module types from ModuleTypeRegistry

**Comment by kaikreuzer** [comment]
Implemented in https://github.com/eclipse/smarthome/pull/1066
