### ISSUE TITLE
Wrong approach for handling the bundles providing automation resources - host and fragments

### ISSUE THREAD

**Issue by adimova** [eclipse/smarthome#1046]
We use "bundle.getEntry" to check if a bundle is a provider of automation resources. This method searches only the contents of this bundle for the entry. Then we check if this bundle is a fragment, and if it is, we do not process it. So, if the host does not contain automation resources then it will not be processed; the fragment will not be processed either - as a result these resources will never be loaded.
Also if the host is processed before all it's fragments have been installed, some fragment bundles that are providers will not be processed.

**Comment by kaikreuzer** [comment]
@adimova Are you working on a fix for this?

**Comment by adimova** [comment]
yes
