### ISSUE TITLE
Missing response for newly created rules without UIDs

### ISSUE THREAD

**Issue by adimova** [eclipse/smarthome#1047]
When someone creates a rule without providing the UID using the RuleRegistry or REST, he will not receive the auto-genereted UID

**Comment by danchom** [comment]
I think this is not a bug, it is architectural problem. The Rule class does not have a setUID() method. The uid can be set through the constructor only. In the RuleEngine the addRule() returns a new added rule object (which has uid property), but its caller the RuleRegistry.add(Rule) which is inherited from Registry interface does not return added object.
May be Rule.setUID() method has to be added?

**Comment by adimova** [comment]
Can we extend the functionality of RuleRegistry with method requestUniqueID() ?

**Comment by kaikreuzer** [comment]
I would also be open to discuss whether Registry.add() should return the added element.

**Comment by adimova** [comment]
yes, fixing the return type of the Registry.add() method will be the best solution, but all implementations  of the Registry interface will need to be fixed then

**Comment by kaikreuzer** [comment]
I think almost all of them extend AbstractRegistry, so we can change it in there.

**Comment by danchom** [comment]
For me it is best solution too.

**Comment by marinmitev** [comment]
I also like the idea to return the added rule

**Comment by danchom** [comment]
The returned rule may have additional changes. For example if the added rule is specified by templateUID, the returned rule will have triggers, conditions and actions in case when the template is available in the rule engine

**Comment by adimova** [comment]
So, you propose REST to return the rule object, not only the UID

**Comment by kaikreuzer** [comment]
In a proper REST style, it should actually return the url of the created element (which in this case will contain the UID as well).

**Comment by danchom** [comment]
I'm not sure about to change the REST API. I think the UID is enough. In the most cases the rule object will not be needed.

**Comment by adimova** [comment]
last to clarify, which will be the return type of add(), key or element?

**Comment by kaikreuzer** [comment]
From http://www.ietf.org/rfc/rfc2616.txt:
```
   The Location response-header field is used to redirect the recipient
   to a location other than the Request-URI for completion of the
   request or identification of a new resource. For 201 (Created)
   responses, the Location is that of the new resource which was created
   by the request.
```
So we should imho definitely fill the location header field.
The body of the response can imho remain empty. Alternatively, I would vote for returning the full rule entity back.

> which will be the return type of add(), key or element?

The element as we do not even know what the key is within the AbstractRegistry.

**Comment by adimova** [comment]
i'm ok with that

**Comment by kaikreuzer** [comment]
Any volunteer to create a PR for this?

**Comment by adimova** [comment]
I will do the fix

**Comment by danchom** [comment]
What will be the fix here?
1) Is the Registry.add(E) method will be changed to return a value (an added element)?
2) fill the location header of response of create rest request?
or both?

**Comment by kaikreuzer** [comment]
Imho both, because we need 2 and this cannot be done without 1.

**Comment by danchom** [comment]
+1
