### ISSUE TITLE
Depandences between ConfigDescriptionParameter and com.google.common.collect was added.

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#1052]
The automation module does not depend from google collections because:
1) google collection duplicates java collections and when something can be done by default lib a new third party lib is not needed.
2) third party lib has a third party support
3) third party lib can depend of other unknown libs. I don't know min java version where the third party lib can be run.
The automation module uses ConfigDescriptionParameter as part of its module definition and therefore it starts depend from google collections.
I propose to do following change in the ConfigDescriptionParameter:

```
  private static final Set<String> UNITS = ImmutableSet.of("A", "cd", "K", "kg", "m", "mol", "s", "g", "rad", "sr", "Hz", "N", "Pa", "J", "W", "C", "V", "F",
      "Ω", "S", "Wb", "T", "H", "Cel", "lm", "lx", "Bq", "Gy", "Sv", "kat", "m/s2", "m2v", "m3", "kph", "%", "l", "min", "h", "d", "week", "y");
```

with this constant definition:

```
private static final Set<String> UNITS = Collections
      .unmodifiableSet(new HashSet<String>(Arrays.asList("A", "cd", "K", "kg", "m", "mol", "s", "g", "rad", "sr", "Hz", "N", "Pa", "J", "W", "C", "V", "F", "Ω",
          "S", "Wb", "T", "H", "Cel", "lm", "lx", "Bq", "Gy", "Sv", "kat", "m/s2", "m2v", "m3", "kph", "%", "l", "min", "h", "d", "week", "y")));
```

and remove import of com.google.common.collect package.

**Comment by kaikreuzer** [comment]
Yes, this should be fixed! Will you create a PR for it?

**Comment by danchom** [comment]
Yes I will. 10x
