### ISSUE TITLE
Things with parameter groups are in longer showing in paperUI

### ISSUE THREAD

**Issue by marcelrv** [eclipse/smarthome#1055]
With recent build, things with parameter groups are no longer possible to edit the configuration parameters.

In the browser console the following error is displayed.
possibly related to PR https://github.com/eclipse/smarthome/pull/964

note: for the same item, parameter edit it was working without problems, in earlier builds. In habmin the item edit remains working fine (incl showing the parameter right grouping).

```
angular.min.js:102 TypeError: Cannot read property 'name' of undefined
    at Object.getRenderingModel (services.min.js:893)
    at controllers.min.js:1964
    at getOne (services.min.js:645)
    at n.$scope.getThingType (controllers.min.js:1960)
    at controllers.min.js:1976
    at getOne (services.min.js:645)
    at n.$scope.getThing (controllers.min.js:1972)
    at new <anonymous> (controllers.min.js:1994)
    at Object.e [as invoke] (angular.min.js:36)
    at w.instance (angular.min.js:75)
```

**Comment by cdjackson** [comment]
Not sure if this is related, but someone on the ZWave test thread reported the following last night -:

>All ZWave parameters have disappeared from PaperUI. They're available in HabMIN and yesterday or the day before they were in PaperUI, now nothing.

I've not had the chance to look at this and as I'm not routinely using PaperUI I've not seen it myself...

**Comment by kaikreuzer** [comment]
I just tried the very latest openHAB 2 build - I was also not seeing any parameters until I cleaned my browser cache. Then it all appeared miraculously:

<img width="1186" alt="screen shot 2016-02-18 at 14 42 23" src="https://cloud.githubusercontent.com/assets/3244965/13144972/0441552c-d64e-11e5-950b-6a8c5018edb8.png">

Could you try to do the same?

**Comment by marcelrv** [comment]
@kaikreuzer I can see them when I add a very new thing (like what you do)
but once saved, I try to edit the same item and it gives same error behaviour.

btw, cleared the browser cache, as well as tried with the developer mode with 'disable cache' selected.

**Comment by kaikreuzer** [comment]
Ok, I can reproduce the very same.

**Comment by marcelrv** [comment]
Thanks! Indeed fixed
