### ISSUE TITLE
Bundle load order in Karaf

### ISSUE THREAD

**Issue by s-simma** [eclipse/smarthome#1059]
Hi,
Does somebody know how the load order of bundles in the ADDON folder is managed ?
What about ESH itself ?
e.g
org.openhab.io.transport.mqtt-1.9.0-SNAPSHOT should be loaded before the MQTT bundle is loaded.

**Comment by kaikreuzer** [comment]
ESH has nothing to do with Karaf - and there is no strict order defined. Please discuss such questions in the openHAB community; although in this case the answer is the very same: There is no order defined, it all is sorted out by the availability of the services within the bundles.

**Comment by s-simma** [comment]
thanks,
I'm asking, because after clearing the cache folder, and starting openhab i get a lot of warnings and sometime errors from karaf. If i "logout" form Karaf and start again, there are no warnings (as all the modules are cached already). I'm running openhab on an embedded device (not i7). And I think this is not related to openhab itself.
