### ISSUE TITLE
ThingType.hasConfigDescriptionURI() could be removed

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1062]
This method does not bring any additional value as long as we say that `getConfigDescriptionURI()` returns null, if no such description exists.

See https://github.com/eclipse/smarthome/pull/1060#discussion_r53432145.

@sbussweiler, @sjka Any opinion on that?

**Comment by sjka** [comment]
Apart from it being an incompatible change when removing it, I don't have any strong feelings about this method. In addition, I don't see a need to distinguish "missing" from "none" cases, which would have been the only reason to keep it I can see.
So, okay from my side to remove it.

**Comment by sbussweiler** [comment]
The result and the meaning is the same. There is no reason to keep this method.

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/eclipse/smarthome/pull/1660
