### ISSUE TITLE
paperUI parameter configuration dropdowns missing label

### ISSUE THREAD

**Issue by marcelrv** [eclipse/smarthome#1064]
In paperUI the labels for the parameters with dropdowns are missing.

![screenie](https://cloud.githubusercontent.com/assets/5871213/13174090/b4ea8fc0-d701-11e5-9554-8aac1014232e.png)

**Comment by kaikreuzer** [comment]
Yep, I have seen this as well.

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/eclipse/smarthome/pull/1072, thanks!
