### ISSUE TITLE
Test Failure: Eclipse SmartHome Automation Integration Tests

### ISSUE THREAD

**Issue by lep4fish** [eclipse/smarthome#1070]
Results of mvn clean install:

[build_log.txt](https://github.com/eclipse/smarthome/files/138830/build_log.txt)

**Comment by kaikreuzer** [comment]
Same here: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/lastCompletedBuild/testReport/

@danchom: Could you have a look, please?

@lep4fish: For the time being, simply run the build without tests, i.e. `mvn -DskipTests=true clean install`.

**Comment by sjka** [comment]
+1 (just ran into the same issue when building it locally)

**Comment by danchom** [comment]
I've added following bundles:
            <bundle>
              <id>org.eclipse.smarthome.io.console</id>
              <level>3</level>
              <autoStart>false</autoStart>
            </bundle>
            <bundle>
              <id>org.eclipse.smarthome.automation.sample.extension.json</id>
              <level>2</level>
              <autoStart>true</autoStart>
            </bundle>
into integration test pom, but the sample extension json bundle is not installed.
How to add bundles into the test environment?

**Comment by kaikreuzer** [comment]
@danchom I took me a while to figure out how to fix it. The important line was this one: https://github.com/eclipse/smarthome/pull/1080/files#diff-69335bce34557b6bb4e3f412da52bd56R5

**Comment by lep4fish** [comment]
Thank you! Everything is working properly now.

On Tue, Feb 23, 2016 at 3:27 AM, Kai Kreuzer <notifications@github.com>
wrote:

> Closed #1070 <https://github.com/eclipse/smarthome/issues/1070> via #1080
> <https://github.com/eclipse/smarthome/pull/1080>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipse/smarthome/issues/1070#event-561456284>.
>



-- 
Larry

cell: 408 623-5422
email: lep4fish@gmail.com
