### ISSUE TITLE
Rollershutter problem

### ISSUE THREAD

**Issue by s-simma** [eclipse/smarthome#1071]
Hi,
Thank's for implementing the state value display for the rollershutter in the Basis-UI.
Here the problem is the same as with the Dimmer item.

If you set the state value from inside a BINDING and you are currently on the page with the rollershutter item, the value (left to the buttons) is shown correctly.
Refreshing the page or reentering the page will force the state value to either 0 or 100. 
It is simple to reproduce this problem. You can use the the simple test binding from the issue #977 (which is for the Dimmer item).

In the classic-UI the state value shows only 0 or 100. The aktual value is never shown.

**Comment by kaikreuzer** [comment]
Is this now a replacement for #977 or another issue?
Is there a way to simply reproduce it by sending updates through console commands?

**Comment by s-simma** [comment]
Rollershutter and Dimmer have exactly the same problem.
All other (String, Number, Selection,Contacts) work as expected.
You can only reproduce the problem if you set the state values from inside a binding. And I am sure this affects ANY binding that set state values for either rollershutter or dimmer.

In #977 (last post) i attached a zip-file with a simple binding, created from skeleton (only a few lines of code i put into it to repruduce the problem). Could you please have a look into it ?

I hardly can believe, that i'm the only person who want's to display the real status values from a physical rollershutter or dimmer. Are there any other binding which sets state values for rollershutter or dimmer ?

OpenHAB2 is great. It's running rock solid. Realy phantastic job.

**Comment by s-simma** [comment]
@kaikreuzer 
I think there are two problems.
1) If the state channel (rollershutter, dimmer) is updated, events for the UI's are generated independent, if the item state itself can be updated or not. Therefore, if you stay on the page with the item (rollershutter, dimmer), the state is reflected correct, and after page refresh you get the old value.

2) In the thing-types.xml the assigned type to this channel is:
<item-type>Number</item-type>  ????
But if you use "thing.updateState(...)", where state can only be (as far as i can see) of type Decimal or String you get the following:

........s.c.internal.items.ItemUpdater:84
Received update of a not accepted type (DecimalType) for item Light_SF_Living_1D

It seems to be, as if "DecimalType" can not be casted to "Number".

**Comment by kaikreuzer** [comment]
> Received update of a not accepted type (DecimalType) for item Light_SF_Living_1D

What item type is your `Light_SF_Living_1D`?

**Comment by s-simma** [comment]
Dimmer Light_SF_Living_1D

**Comment by kaikreuzer** [comment]
Then the message is correct - DecimalType is not accepted by dimmers, you have to send PercentType in your updateState call.

**Comment by s-simma** [comment]
@kaikreuzer 
With the magic word "PercentType" rollershutter and dimmer can now reflect their actual state.
Thank you very, very much !!

**Comment by kaikreuzer** [comment]
Thanks for your feedback, good to know that this works now.
So what is left in this issue? (1) from https://github.com/eclipse/smarthome/issues/1071#issuecomment-187943659?

**Comment by s-simma** [comment]
both #977 and #1071 are fully soved. nothing open.
