### ISSUE TITLE
Code in timers doesn't have access to items

### ISSUE THREAD

**Issue by feens** [eclipse/smarthome#1074]
I've created a timer, and when it's run it fails when trying to access any items (which I can confirm are created by executing the same code outside of a timer).

Here's an example rule I'm running (simplified for testing):

```
    import org.joda.time.*

    var Timer tOutdoorLights

    rule "React to sunset"
    when
        Time cron "0 0 16 * * ?"   // Every day 16:00 hours, evaluate sunset
    then
        sendCommand(Switch_Outside, ON) // this works
        tOutdoorLights = createTimer(now.plusMinutes(1)) [|
                logInfo("Sunset", "running timer")
                sendCommand(Switch_Outside, ON) // this throws an exception
        ]
    end
```

And here's the error (truncated for brevity...I can post more if needed):

```
2016-02-22 14:18:58.475 [ERROR] [org.quartz.core.JobRunShell         ] - Job DEFAULT.2016-02-22T14:18:58.468Z: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: [ | {
  logInfo(<XStringLiteralImpl>,<XStringLiteralImpl>)
  sendCommand(<XFeatureCallImplCustom>,<XFeatureCallImplCustom>)
} ] threw an unhandled Exception: 
java.lang.RuntimeException: The name '<unkown>' cannot be resolved to an item or type.
```

**Comment by kaikreuzer** [comment]
Hm, I actually cannot reproduce the problem. I have just added a demo rule to the openHAB distro (see https://github.com/openhab/openhab-distro/pull/142) and this works as expected. I cannot make out any real difference to your rule. Could you have a try with mine? If this works for you, will can start digging for the differences...

**Comment by feens** [comment]
I went and updated my version (I was using the latest as of my bug report) yesterday and tried again and it seems to work now.  Odd...but I'm glad it's at least working.

**Comment by kaikreuzer** [comment]
Glad to hear, thanks for the feedback!
