### ISSUE TITLE
Thing label and group cannot be updated from PaperUI

### ISSUE THREAD

**Issue by satish-nikam** [eclipse/smarthome#1077]
ESH PaperUI shows edit button to change thing settings, but when you change label text and select some other group (using checkbox), and then click on save, ESH fails to save these changes. Though PaperUI shows success message "Thing updated".

This does not work with current OpenHAB2 snapshot also.

**Comment by kaikreuzer** [comment]
The label updates work again through https://github.com/eclipse/smarthome/pull/1054 (not yet available on OH2, but soon).
The groups selection will be removed with https://github.com/eclipse/smarthome/pull/1019, so no need to update this.
