### ISSUE TITLE
The uniqueness of Rule IDs is not guaranteed

### ISSUE THREAD

**Issue by adimova** [eclipse/smarthome#1079]
We do not prevent the possibility of adding a rule with ID thru the RuleProvider and adding a rule with the same ID thru the RuleRegistry.add()

**Comment by kaikreuzer** [comment]
That's imho not a bug, that's our definition.
We said that we do not have any technical pre-cautions that would prevent having different RuleProviders providing rules with the same ids. RuleRegistry.add() is only relevant for the ManagedRuleProvider and if no rule with the id exists in it, it can be added there.
A solution should rather make sure that alternative rule providers use a proper rule id prefix, which avoids collisions.
