### ISSUE TITLE
TTS Interfaces

### ISSUE THREAD

**Issue by kdavis-mozilla** [eclipse/smarthome#1081]
Define the TTS interfaces discussed in #584

**Comment by kdavis-mozilla** [comment]
A hopefully accurate summary of the current idea for the TTS interfaces to be put in the package `org.eclipse.smarthome.io.voice.tts`:

```Java
public interface TTSService {
           /**
            * Obtain the voices available from this TTSService
            *
            */ @return The voices available from this service
            public Set<Voice> getAvailableVoices();

           /**
            * Obtain the audio formats supported by this TTSService
            *
            */ @return The audio formats supported by this service
            public Set<AudioFormat> getSupportedFormats();

           /**
            * Returns an AudioSource containing the TTS results. Note, one can only
            * request supported Voices and AudioFormats or an exception is thrown.
            *
            * @param text The text to convert to speech
            * @param voice The voice to use for speech
            * @param requestedFormat The audio format to return the results in
            */ @return AudioSource containing the TTS results
            public AudioSource synthesize(String text,
                                          Voice voice,
                                          AudioFormat requestedFormat) throws Exception;
}

public interface Voice {
       /**
        * Globally unique identifier of the voice, must have the format
        * "prefix:voicename", where "prefix" is unique to the organization
        * creating the voice.
        *
        * @return A String uniquely identifying the voice globally
        */
        public String getUID();

       /**
        * The voice label, usually used for GUI's or VUI's
        *
        * @return The voice label, may not be globally unique
        */
        public String getLabel();

       /**
        * Locale of the voice
        *
        * @return Locale of the voice
        */
        public Locale getLocale();
}
```

The classes/interfaces `AudioSource` and `AudioFormat` are defined by issue #584 

@kaikreuzer @hkuhn42 If there is anything I missed here, feel free to chime in.

**Comment by kaikreuzer** [comment]
lgtm, thanks. The `throws Exception` will have to become more detailed later on, as a package I would suggest to remove the `.tts` and directly go with `org.eclipse.smarthome.io.voice` - where we can then put the SST and other interfaces as well.

**Comment by kdavis-mozilla** [comment]
@kaikreuzer The package `org.eclipse.smarthome.io.voice` sounds fine to me, and I agree that the `Exception` will have to become more detailed.  

@hkuhn42 Is this OK with you?

**Comment by hkuhn42** [comment]
@kdavis-mozilla looks good to me, too.

**Comment by kdavis-mozilla** [comment]
Awesome!

**Comment by kdavis-mozilla** [comment]
@hkuhn42 Just so we don't get our signals crossed. I'll start working on this and submit a pull request, early next week, to your fork which you can review and then make pull request to here.

**Comment by ghys** [comment]
Hi,
As discussed with Kai [here](https://github.com/openhab/org.openhab.ui.habpanel/pull/51) I would like to hijack this issue (as it is still open) to start some discussion about a simpler interface for external TTS services which simply accept text and take care of the audio playback themselves. They might even not offer the ability of controlling the voice or format.

In "my" case this would pave the way for a "SSE TTS Service" similar to #2313, which would let the web GUI synthesize the received text using the HTML5 text synthesis API (http://caniuse.com/#feat=speech-synthesis).

Newbie here, but here's a first 2AM try as some food for thought (please excuse the lack of coding standards):

```java
public interface TTSService {
           /**
            * Perform TTS with the default voice and format.
            * Returns an AudioSource containing the TTS results, or null if the service
            * handles the audio playback itself, and no audio stream is returned.
            *
            * @param text The text to convert to speech
            * @return AudioSource containing the audio or null if the playback
            *         is already taken care of
            */
            public AudioSource synthesize(String text) throws Exception;
}

public abstract class ExternalTTSService implements TTSService {
            /* Send the text to the service (which will perform the playback itself) */
            public abstract void speak(String text);

            @Override
            public AudioSource synthesize(String text) throws Exception {
                 speak(text);
                 return null;
           }
}

/* The current TTSService interface methods are moved to this abstract class */
public abstract class LocalTTSService implements TTSService {
            public abstract Set<Voice> getAvailableVoices();

            public abstract Set<AudioFormat> getSupportedFormats();

            public abstract AudioSource synthesize(String text,
                                          Voice voice,
                                          AudioFormat requestedFormat) throws Exception;

            public abstract Voice getDefaultVoice();

            public abstract Format getDefaultFormat();

            @Override
            public AudioSource speak(String text) throws Exception {
                /* Use the default voice and format */
                return synthesize(text, getDefaultVoice(), getDefaultFormat());
            }
}
```

Of course the current code would have to ignore the playback part if the service doesn't return an audio stream (and detect non-LocalTTSServices and bypass the voice/format configuration)...
Does it even make sense?

**Comment by kaikreuzer** [comment]
As we have an TTSService interface, I'd like to close this issue.
@ghys Regarding the requirement for external TTS services: Is this something you'd still want to pursue (just asking as your comment is 1.5 years old already, sorry for never having answered it...)?
If so, I'd suggest to open a dedicated issue for it with a better matching title and we can pick that up again.
