### ISSUE TITLE
ESH Paper UI - Missing Icons and Things' Controls

### ISSUE THREAD

**Issue by iakko** [eclipse/smarthome#1091]
Hello there,

I've just installed the Offline Distro version of OpenHAB2 and I've disabled the OpenHAB2 Paper UI while it doesn't support the _/control_ pannel which is very usefull to me.

The ESH Paper UI is running, but I'm experiencing some issue:

- I'm not able to control Things due missing controls:

![eshpaperui_missingthingscontrols_note](https://cloud.githubusercontent.com/assets/1287801/13292812/8910ccbe-db1d-11e5-928d-3521ff9bbc5e.png)

- Seems like some UI elements are missing, like icons on action buttons:

![eshpaperui_missingiconsonthings_note](https://cloud.githubusercontent.com/assets/1287801/13292820/92ec8214-db1d-11e5-81ce-a7242b9c759a.png)

![eshpaperui_missingiconsongreenbuttons_note](https://cloud.githubusercontent.com/assets/1287801/13292821/92f200f4-db1d-11e5-9324-4c146dc62592.png)

Do someone know why?

Thanks.
IP

**Comment by maggu2810** [comment]
The items has not been part of ESH because of the missing CQ.
The CQ has been approved, but the PR to add the md-icons is still missing.
See e.g.: https://github.com/eclipse/smarthome/pull/1003

**Comment by iakko** [comment]
Thank you @maggu2810. Is there a way to resolve this?

**Comment by maggu2810** [comment]
I am hope that the PR for the md icons is coming soon.
Another thing you can do is to edit the openHAB Paper UI fragment (e.g. the constants.js) and reactivate the control again.

**Comment by kaikreuzer** [comment]
> I'm not able to control Things due missing controls

You will have to manually create items and they will be shown on the control view.
For having items automatically be available for things, you can help on https://github.com/eclipse/smarthome/issues/1039.
