### ISSUE TITLE
Channel configuration updates

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1103]
I don't seem to be able to update channel configuration (although I'm sure this worked recently).

Below shows the PUT request -:
![image](https://cloud.githubusercontent.com/assets/1041475/13380216/8ff89a6e-de35-11e5-926a-7f44ed44268a.png)

And this is the response -:

![image](https://cloud.githubusercontent.com/assets/1041475/13380218/a5a079ae-de35-11e5-9a56-14e11cac9ff2.png)

This clearly shows the channel parameter request goes out with config_scale = 1, but returns with config_scale=0.

The channel config is defined as follows -:
```xml
        <config-description>
            <parameter name="config_scale" type="integer">
                <label>Scale</label>
                <description>Select the scale for temperature readings</description>
                <default>0</default>
                <options>
                    <option value="0">Celsius</option>
                    <option value="1">Fahrenheit</option>
                </options>
            </parameter>
        </config-description>
```

To me, everything looks fine - the type is an int in all cases, the values look correct, but it's not updated.

If I look in the update method ([ThingResourceL320](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java#L320)) and follow through the code, it's unclear how this can update the channel configuration. It updates the label and the thing configuration, but not the channel configuration...

Below is the relevant code -:
```java
        // ask whether the Thing exists at all, 404 otherwise
        Thing thing = thingRegistry.get(thingUIDObject);
        if (null == thing) {
            logger.info("Received HTTP PUT request for update at '{}' for the unknown thing '{}'.", uriInfo.getPath(),
                    thingUID);
            return getThingNotFoundResponse(thingUID);
        }

        // ask whether the Thing exists as a managed thing, so it can get updated, 409 otherwise
        Thing managed = managedThingProvider.get(thingUIDObject);
        if (null == managed) {
            logger.info("Received HTTP PUT request for update at '{}' for an unmanaged thing '{}'.", uriInfo.getPath(),
                    thingUID);
            return getThingResponse(Status.CONFLICT, thing, locale,
                    "Cannot update Thing " + thingUID + ". Maybe it is not managed.");
        }

        // only process if Thing is known to be managed, so it can get updated
        thing.setBridgeUID(bridgeUID);
        updateConfiguration(thing, getConfiguration(thingBean));

        // Update the label
        thing.setLabel(thingBean.label);

        // update, returns null in case Thing cannot be found
        Thing oldthing = managedThingProvider.update(thing);
        if (null == oldthing) {
            return getThingNotFoundResponse(thingUID);
        }
```

As above, I thought this worked previously using the same calls, but maybe not, or maybe I'm doing something wrong?

**Comment by kaikreuzer** [comment]
I doubt that this has ever worked before, see https://github.com/eclipse/smarthome/pull/1087#issuecomment-188844414

**Comment by cdjackson** [comment]
Hmm - ok, I guess I must have thought it worked based on default values being added during initial instantiation...

**Comment by xsnrg** [comment]
@kaikreuzer @teichsta  Any updates on this and #1087 ?  This is breaking temperature settings for us silly folk across the pond using F.

**Comment by kaikreuzer** [comment]
Still waiting for @teichsta to respond...

**Comment by xsnrg** [comment]
@teichsta <ping>

I know you guys are busy, but this one is really a usability problem.  Any thermostats with setpoints, any devices that report temperature, etc are affected. It isn't just a conversion that is not available.  Most z-wave devices over here come factory default to use and report in F and changing the actual device to use C may not be possible.

**Comment by kaikreuzer** [comment]
I assume that this is solved meanwhile through https://github.com/eclipse/smarthome/pull/1286.
