### ISSUE TITLE
Ensure that Map transform kept same behaviour than in OH1

### ISSUE THREAD

**Issue by clinique** [eclipse/smarthome#1107]
Following discussion raised [here] (https://community.openhab.org/t/fixed-mios-binding-1-8-not-working-in-openhab2/6439/38) and decision taken [here](https://community.openhab.org/t/esh-changes-behavior-of-map-transform-from-return-to-return-original-value/6991/5)  - transformations must keep returning empty string rather than non transformed on error.

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/eclipse/smarthome/pull/1114
