### ISSUE TITLE
Ability to sort items in subfolders broken

### ISSUE THREAD

**Issue by clinique** [eclipse/smarthome#1124]
In OH1 it was possible to store icons in subfolders like this : 
/webapps/images/icon1.png
/webapps/images/icon2.png
..
/webapps/images/uvindex/uv-0.png
/webapps/images/uvindex/uv-1.png
/webapps/images/uvindex/uv-2.png
....

The DSL allowed items to have <"uvindex/uv"> as icon description.

This was quite convenient to sort families of icons.

Question so are :
- was I the only one to do this ?
- is this behaviour suitable ?

**Comment by clinique** [comment]
A small change in IconServlet seems to work very fine : 
 
```
private String getCategory(HttpServletRequest req) {
        // In order to handle /icon/test/wifi.png
        // String category = StringUtils.substringAfterLast(req.getRequestURI(), "/");
        String category = StringUtils.substringAfter(req.getRequestURI(), "/");
        category = StringUtils.substringAfter(category, "/");
        category = StringUtils.substringBeforeLast(category, ".");
        return StringUtils.substringBeforeLast(category, "-");
}
```

**Comment by kaikreuzer** [comment]
See the definition here: https://www.eclipse.org/smarthome/documentation/features/ui/icons.html
Slashes are not officially supported and you were rather tricking the system.

> was I the only one to do this ?

I assume so.

> is this behaviour suitable ?

No, it is against the definition that the string should actually refer to a category.

I would hope you are ok to live without this "feature" in future...?

**Comment by clinique** [comment]
Ok - I'll find another way then. Let's close this issue.
