### ISSUE TITLE
Basic UI: valuecolor attribute in sitemap not taken into account

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1135]
The valuecolor attribute seems to not be talen into account by Basci UI.
Example:
```
			Text item=BatterieInterDuwi visibility=[BatterieInterDuwi<100] valuecolor=[<=18="red",<=30="orange",==100="green"]
```
PS: visibility attribute is apparently correctly taken into account

**Comment by resetnow** [comment]
Just to clarify, I have seen this but I was kind of busy last week and hopefully will be able to provide a fix after the weekend.
