### ISSUE TITLE
Basic UI: bad switch state for a dimmer item

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1137]
Here is my item:

```
Dimmer LampeChambre "Lampe chambre [%d %%]" <slider> {mios="unit:house,device:510/service/Dimming1/LoadLevelStatus", autoupdate="false"}
```

and here is my sitempa:

```
Switch item=LampeChambre
```

When I switch to ON with Basic UI, the switch is displayed as ON shortly and then quickly to OFF again. The icon is displayed as light on.
Here is the logs,

```
14:32:16.188 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'LampeChambre' received command ON
14:32:16.423 [INFO ] [marthome.event.ItemStateChangedEvent] - LampeChambre changed from 0 to 100
```

If I reopen the page, the state is ON as it should.
PS: no such issue with Classic UI.
PS2: no problem if the item is defined as switch (and not dimmer)

**Comment by s-simma** [comment]
You use autoupdate = "false". That means your binding (device) should reflect the actual state value. Are you shure this is true ?. But in your log i can't see an entry for that. Mybe you should switch to Debug level.
...try to remove the autoupdate="false"
At least for me the Dimmer item in the Basic-UI is working correctly (under all conditions).

**Comment by lolodomo** [comment]
autoupdate="false" means I let the binding update the item state and it is what happening as you can see in the logs (dimmer is set to 100). The UI should take into account this state update and apparently it does not.
What is important to note is that my item is a switch and not a slider in my sitemap (the item is a dimmer in my item file).
My idea is that basic UI is not considering a dimmer value > 0 as a ON switch.

**Comment by s-simma** [comment]
For the same physical dimmer i I have created 2 items.
Switch Light_SF_Living_1S
Dimmer Light_SF_Living_1D
But both items are assigned to different groups.
In the sidemap i only use groups. And this works.
Mybe you should try to define 2 items and use the switch item in the sidemap.

**Comment by lolodomo** [comment]
I decided to use only one item due to kai's remark that it is sufficient (no reason to have several items) and because with Paper UI you can link only one item to a channel.

By the way, I am not looking for a workaround (defing a switch item and a dimmer item will certaibly work), I am just declaring an issue, something not working that should work.

**Comment by feens** [comment]
I've noticed the same issue with my dimmers.

**Comment by resetnow** [comment]
My best guess is it's somehow related to the binding used for the dimmer. I don't have any “bindable” dimmers in my actual smarthome configuration so when I test BasicUI, it works as excepted. Also, BasicUI not updating the dimmer value means there was no event from the SSE event source, or it was ill-formed. Take a look at javascript console while trying to reproduce the bug — are there any errors?

**Comment by lolodomo** [comment]
I tested again this issue and good news the problem has disappeared.
