### ISSUE TITLE
ChannelUID should be included in REST interface

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1151]
Currently, the channelUID is not included in the REST interface. It can of course be derived from the thingUID and the channelTypeUID, but I wonder if it wouldn't be better to explicitly provide the channelUID to avoid any potential problems with this assumption in future (as we had with thing UID in the past).

Just a thought...

**Comment by maggu2810** [comment]
Which REST functions do you refer to?
IIRC: The item channel link resource does contain channel UID.
IMHO we should add the channel UID where necessary. And we should never extract information from a UID.

**Comment by kaikreuzer** [comment]
I guess he means the /things uri and the ChannelDTO specifically.
The ChannelDTO was "out of sync" with Channel anyhow, so I fixed this in #1152. I for the moment kept the "id" field in the DTO nonetheless as I do not know what impact its removal could have on the Paper UI. We can potentially remove it once we are sure that it is not used by any client.
