### ISSUE TITLE
Hue: Initial state fetch

### ISSUE THREAD

**Issue by sja** [eclipse/smarthome#1159]
This is a Bug in the Hue binding: The initial state of a Lamp is not fetched after adding it.

Reproduce:
1. Remove Hue Bulb Things.
2. Bulbs are re-discovered, appear in inbox
4. Call /rest/inbox/(hue-bulb-thinguid)/approve
5. Call /rest/items/(hue-bulb-itemname)

Then the state is NULL, after pollinterval (default 10s) there should be a non-NULL state, but thats not the case. I guess, that there is no handler queued after ItemAddedEvent.

**Comment by kaikreuzer** [comment]
How do you create your item and link? inbox/approve only creates you the thing.

**Comment by sja** [comment]
No, it creates items, too

**Comment by kaikreuzer** [comment]
Ok, if the parameter `enableChannels` is true, which is currently used as a default if not specified, indeed...

**Comment by sja** [comment]
Ok, so I have to fix this. While stepping through the code I noticed, that the initial state is fetched and the state is correctly updated if delayed by my breakpoint at [HueLightHandler.java:345](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java#L345). So this seems to be a timing issue. 
Fixing this would not be the complete solution because it seems that the LightHandler is not added to the polling job of the bridge.

Any best practises to "delay" or decouple the timing/synchronization problem?
