### ISSUE TITLE
Paper UI should update Thing when leaving edit mode

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1168]
When editing a Thing, the Paper UI currently only sends an update of the configuration.
Since the Thing now also contains a label (and further infos in future), an update to /rest/things should also be sent, see https://github.com/eclipse/smarthome/pull/1090#issuecomment-193801823

It probably makes sense to treat these two features (thing details and thing config) separately. It would be ideal if the UI could determine, what has been changed by the user and then send the according requests - so sometimes only a thing update and sometimes only a config update.

**Comment by satish-nikam** [comment]
Just verified..I am able to update thing label. Thanks a lot.
