### ISSUE TITLE
BasicUI charts don't load when using switch items mappings=

### ISSUE THREAD

**Issue by shorty707** [eclipse/smarthome#1174]
using a switch item with mappings the charts do not switch/load automatically to the user selection but only after user selected something and refreshed f5 manually to show the chart

**Comment by resetnow** [comment]
Can you provide an example sitemap?

**Comment by triller-telekom** [comment]
If this one is related to #640 I am wondering if it is fixed by now, because #640 is closed.

@shorty707 Could you please provide your example sitemap so we can verify that the reload issue is gone in your case?

**Comment by resetnow** [comment]
I'm 99% sure it's fixed since there was a pull request specifically for this feature and I use it myself with charts.

**Comment by sjka** [comment]
okay, I'll close it then. We can still re-open it in case of the unlikely 1% 😉
