### ISSUE TITLE
ChannelUIDs mismatched after thing type changed

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1175]
There seems to be a mismatch somewhere with channelUIDs after the thing-type is changed.

If I have a thing called zwave:device:xxx:node1, with type zwave:device, and I change it's type to zwave:new_type, then the thing name remains the same (zwave:device:xxx:node1) but channels now are called zwave:new_type:xxx:node1.

Somewhere, this is screwed up since I can't set a link to zwave:new_type:xxx:node1 - only to a channel with a name based on the thing name, not the thing type (ie zwave:device:xxx:node1). I actually think this is how it should be (ie the channel UID is based on the thing name, and not the thing type) but at the end of the day I don't mind (it would be less consistent, but it's not the end of the world).

This is consistent in both HABmin and PaperUI.  I can change HABmin to use the channel UIDs based on channel type, and the link works ok (ie no error - which is arguably another bug!) but if I look in the channels list in the thing, there will be no linked items.

When my binding starts, I get the channels based on channel-type, and the only way to get a linked item into the channel is to use a channel UID that uses the thing name, not thing type...

I will see if I can find where this issue lies, but question for you @kaikreuzer - should the channel UID be based on the thing name, or the thing-type name? 
Since I've changed Z-Wave to use this feature, I need to get it fixed quite quick :(

**Comment by cdjackson** [comment]
Another symptom - the UIs (class/basic at least) show no items for devices that have had a type change - PaperUI/HABmin show there are channels linked...

Since I suspect I didn't explain this issue well above, here's an image below -:

![image](https://cloud.githubusercontent.com/assets/1041475/13729200/ac3fe496-e927-11e5-9aaa-02fb4a3c30ee.png)

This shows that PaperUI is linking a `zwave:device:home:node44:meter_watts` while the binding thinks the channelUID is `zwave:popp_123665_00_000:home:node44:meter_watts`.

To further explain it, I added a log entry to the REST interface that prints out the same message as in the link manager - you can see the channelUID is not so unique!

```
2016-03-13 14:41:00.264 [DEBUG] [.r.c.l.ItemChannelLinkResource:83   ] - Adding linked item 'zwave_popp_123665_00_000_home_meter_watts' to channel 'zwave:device:home:node44:meter_watts'.
2016-03-13 14:41:00.265 [DEBUG] [.c.t.internal.ThingLinkManager:317  ] - Adding linked item 'zwave_popp_123665_00_000_home_meter_watts' to channel 'zwave:popp_123665_00_000:home:node44:meter_watts'.
2016-03-13 14:41:00.267 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element zwave_popp_123665_00_000_home_meter_watts -> zwave:device:home:node44:meter_watts to ManagedItemChannelLinkProvider.
```

**Comment by cdjackson** [comment]
The translation in the UID occurs in the ThingLinkManager change listener -:

```java
        public void added(ItemChannelLink itemChannelLink) {
            ChannelUID channelUID = itemChannelLink.getUID();
            Thing thing = thingRegistry.get(channelUID.getThingUID());
            if (thing != null) {
                Channel channel = thing.getChannel(channelUID.getId());
                if (channel != null) {
                    ThingLinkManager.this.addLinkedItemToChannel(thing, channel, itemChannelLink.getItemName());
                }
            }
        }
```

The above call to thing.getChannel() with the channelId returns the channel which has a different UID than it was called with.... In any case, this just explains the log above with the changing UID - it doesn't explain why we need to use a different channel UID in the binding, and in the UI.

IMHO, the UID should be the same, and I think it should be related to the thing name, not the thing type. This would make naming consistent, and also allow retention of channels (or at least their names if something else in the system doesn't delete them) when the thing type is changed.

**Comment by kaikreuzer** [comment]
> should the channel UID be based on the thing name, or the thing-type name? 

Clearly it should be based on the Thing UID and hence have no reference to the thing type (as this is now dynamic). Will help to analyze tonight, if you haven't found the location of the bug yourself by then!

**Comment by cdjackson** [comment]
I think the issue is in ThingFactoryHelper. When the channels are created, they use the ThingTypeUID. I’ve just changed this to the getThingTypeUID for the thingUID which returns the UID based on the thingUID to see if this solves the issue. Clearly this isn’t the final fix (if it works at all!) but it does create the correctly named channels. If it works, we’d need a new method, or new derivation of the name as thingUID.getThingTypeUID() is a) wrong, and b) deprecated - so a new method, doing the same thing butwith a correct name might be the solution…

I’ll let you know what I find anyway...

**Comment by cdjackson** [comment]
Yep - the above seems to fix the problem - I'll have a think about how to do it 'properly' and generate a PR for discussion...

**Comment by cdjackson** [comment]
See #1177

**Comment by kaikreuzer** [comment]
And see #1181.

**Comment by cdjackson** [comment]
This is now fixed.
