### ISSUE TITLE
Remove R5 dependencies org.osgi.framework.namespace and org.osgi.framework.wiring

### ISSUE THREAD

**Issue by adimova** [eclipse/smarthome#1191]

**Comment by adimova** [comment]
These dependencies should be removed for compatibility with R4

**Comment by splatch** [comment]
R4 is quite old (2009) and spec moved forward since then. Even R5 (2012) is not fresh. Is there any particular reason to not stick with R5?

**Comment by marinmitev** [comment]
the code should be backward compatible with OSGi R4 because it is used in other projects which are still using R4 frameworks

**Comment by splatch** [comment]
@marinmitev In such case it should cause upgrade in projects relying on older version and not downgrade smarthome to legacy version.

**Comment by maggu2810** [comment]
@splatch As I am not using such an old version, I am fine with using a more recent version.

But there is no downgrade. If you have a look at the developer guidelines SmartHome have to support R4. So this has been a target from the beginning and has been violated.

**Comment by splatch** [comment]
@maggu2810 In such case I have nothing to say. You are stick with quite old versions, but if that's baseline then .. meh. :+1:
