### ISSUE TITLE
handleCommand() triggers handleUpdate()?

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1202]
When a ThingHandler implements both handleCommand() and handleUpdate(), then sending a command to an Item linked to a relevant channel will first trigger handleCommand(), some logic is executed, consequently that Item is updated afterwards, and because of that, the ThingHandler's handleUpdate() is called. Is that behaviour we want? How to deal with this? how to differentiate?

Consider the following output from the KNX 2.0 binding as an example: 

2016-03-16 20:57:14.197 [INFO ] [arthome.event.ItemCommandEvent:43   ] - Item 'knxswitch' received command OFF
**2016-03-16 20:57:14.198 [DEBUG] [.c.thing.internal.ThingManager:336  ] - Delegating command 'OFF' for item 'knxswitch' to handler for channel 'knx:ip:ip1:ga_1_5_1'
2016-03-16 20:57:14.199 [TRACE] [.k.h.KNXBridgeBaseThingHandler:675  ] - Writing a KNX telegram to '1/5/1' with dpt '1.001'
2016-03-16 20:57:14.223 [DEBUG] [.k.h.KNXBridgeBaseThingHandler:698  ] - Wrote value 'OFF' to datapoint 'command DP 1/5/1 knx:ip:ip1, DPT main 0 id 1.001, low priority'
2016-03-16 20:57:14.223 [DEBUG] [.c.thing.internal.ThingManager:336  ] - Delegating command 'OFF' for item 'knxswitch' to handler for channel 'knx:ip:ip1:ga_1_5_0'
2016-03-16 20:57:14.223 [TRACE] [.k.h.KNXBridgeBaseThingHandler:675  ] - Writing a KNX telegram to '1/5/0' with dpt '1.001'
2016-03-16 20:57:14.245 [DEBUG] [.k.h.KNXBridgeBaseThingHandler:698  ] - Wrote value 'OFF' to datapoint 'command DP 1/5/0 knx:ip:ip1, DPT main 0 id 1.001, low priority'
**2016-03-16 20:57:14.249 [INFO ] [smarthome.event.ItemStateEvent:43   ] - knxswitch updated to OFF
**2016-03-16 20:57:14.250 [DEBUG] [.c.thing.internal.ThingManager:386  ] - Delegating update 'OFF' for item 'knxswitch' to handler for channel 'knx:ip:ip1:ga_1_5_1'
2016-03-16 20:57:14.252 [TRACE] [.k.h.KNXBridgeBaseThingHandler:675  ] - Writing a KNX telegram to '1/5/1' with dpt '1.001'
2016-03-16 20:57:14.275 [DEBUG] [.k.h.KNXBridgeBaseThingHandler:698  ] - Wrote value 'OFF' to datapoint 'command DP 1/5/1 knx:ip:ip1, DPT main 0 id 1.001, low priority'
2016-03-16 20:57:14.276 [DEBUG] [.c.thing.internal.ThingManager:386  ] - Delegating update 'OFF' for item 'knxswitch' to handler for channel 'knx:ip:ip1:ga_1_5_0'
2016-03-16 20:57:14.276 [TRACE] [.k.h.KNXBridgeBaseThingHandler:675  ] - Writing a KNX telegram to '1/5/0' with dpt '1.001'
2016-03-16 20:57:14.297 [DEBUG] [.k.h.KNXBridgeBaseThingHandler:698  ] - Wrote value 'OFF' to datapoint 'command DP 1/5/0 knx:ip:ip1, DPT main 0 id 1.001, low priority'
**2016-03-16 20:57:14.299 [INFO ] [s.event.ItemStateChangedEvent :43   ] - knxswitch changed from NULL to OFF

**Comment by maggu2810** [comment]
I think that is expected behaviour.
For the common use case the most bindings, there exists real physical devices. The devices reports the current state or the binding could request the current state from the device. It is also possible to set / change the state of the devices.
A command should trigger a action that is send to the device, e.g. ON => the binding will send "switch on" to the device.
A received state update from the Eclipse SmartHome system should not trigger an action of the device. It is slightly wrong to handle such a state update, because the state is hold by the device.
The only thing I assume you can do, is to check if the state is correct and send the correct one if it is wrong.
But we should still differ between states that informs about a situation and a command that triggers an action.

But I don't know how this is handled on the KNX bus.

If you post an update and receive updates and would assume that the one that posts it also receive the updates he posted itself.

**Comment by kgoderis** [comment]
I will try to summarise how it is done on the KNX bus. 

In the KNX world devices see the bus as a kind of shared memory space whereby they can write data to a given location (e.g. the Group Address), and that other devices can listen for. Through configuration, only the device(s) writing or reading that address know about its existence, and can decode what the data is meant to mean. Devices have hooks (Object Functions) that you can attach these Group Addresses to, and in the documentation of the device it is indicated wether that hook is Read, Write or Transmit purposes. So, writing data to a Group Address that is hooked to a device Object Function that does not have the Read flag will do exactly nothing, as the device will ignore it. When it is Transmit, then the device will periodically write a value to the address to report for example a state of that Object Function. 

So, in the KNX world, when something is flying over the bus, you do not know a priori if this is a command or status update. It is partially solved by manufacturers by providing Object Functions that are meant to be written (e.g. to trigger something), complemented by other Object Functions that are Read or Transmit and only intended to report a state. So typically, if you flip a switch by sending a binary 1 value to a group address 1/5/0 for example, there might be a subsequent message on the bus, from the switch, to address 1/5/1 that reports that the state of the switch is now 1. This is however not common behaviour.

Therefore, the KNX binding does handleCommand() (for commands from ESH towards the bus), as handleUpdate() for anything that is flying over the bus itself (e.g. bus towards ESH). Since you can have Items with multiple channels, for example each time a channel that is linked to a given KNX Group Address, there is no way anymore to distinguish what is coming from the knx bus and what is coming from the "ESH bus", as the core logic interconnects the channels through the item itself. 

Imagine an Item with 2 channels; 1 for "commands", 1 for capturing state updates; each channel is linked to a KNX group address

1. send Command to an Item -> handleCommand()
2. write the command on the  KNX bus, twice (once for every channel linked to the item)
3. the item gets updated -> handleUpdate() via the "ESH bus" (and then, that update itself is written again to the KNX bus, as the channels get updated)
4. the knx device, in the best case, reports the state, to a Group Address linked to one of the channels 
5. the item gets updated -> handUpdate(), but this trigger an update of the other channel as well

Since the KNX protocol is pretty much connection-less, you can not distinguish stuff you send yourself, and similar/same stuff that was put by another device on the bus. So, having the binding track what is has sent itself is not fool proof.

Getting back to your comment, how can one distinguish between updates coming from the ESH bus, and those coming from the KNX bus?

**Comment by maggu2810** [comment]
I added a reply to the autoupdate thread. It is realted to this one, so I hope it is okay, to refer to the forum entry here.
Just a short excerpt: I don't think you should send the update reported on the ESH bus to the KNX bus (if I understand the bus correctly). Not your ESH system does hold the correct state of the KNX addresses, the state of the KNX addresses is reported to the ESH system.

**Comment by kaikreuzer** [comment]
Discussion continued at https://www.eclipse.org/forums/index.php/t/1075677/
