### ISSUE TITLE
Propolsals for changes in Automation engine API

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#1210]
1)	Type of Input/output defaultValue property is better to be changed from Object to String. In this way the default value will be presented in same way as default value of ConfigDescriptionParameter. Also the rule engine does not know what kind of object to create. Conversion from string to object has to be served by the handler because it knows how to handle this value.
2)	At the moment, types of inputs and outputs are defined as fully qualified names. I’m not sure if it usable for the people which does not know java (i.e. javascript developer defining rules through the JSON definition). The proposal is the type to be just a string and validation to be based on equality of input and output as strings. 
3)	Configuration (which contains values for configuration properties) of Module, Rule, RuleTemplate at the moment is defined as Map(String, Object). Our proposal is the configuration values to be presented as Map(String, String). In that way configuration property value will be presented in the same way as default value of configuration property.  Also the configuration values will be easily serialized/deserialized.

**Comment by kaikreuzer** [comment]
1) Ok, this is then indeed inline with ConfigDescriptionParameter
2) This was actually my idea from the beginning - the type would be just a string "marker", such as "event", "state" or whatever, that is used for being able to match modules. The only place where we currently assume to have FQCNs is the connection validator, so this should be easy to adapt.
What we are losing though is the possibility to work with inheritance - so having an input accepting "event" and an output issuing a "stateEvent" simply wouldn't work. Can we live with this? Or shall we keep FQCN as an option, i.e. if we find a class for that name, we use the current validation and if not we fall back to string compare?
3) We designed the module configurations to be identical to other ESH configurations (using the `Configuration`class). So changing it would mean changing `Configuration` as well and I do not really see this as an option.

**Comment by danchom** [comment]
2) I think we don't have a high profit of validation based on isAssignableFrom instead of string compaction. When a "stateEvent" is produced the type of an output can be Event again. There is also  a label and description which can describe the type of event.  I'm not sure if a user will decide to connect input to output based on the internal hierarchy of java classes. 

3) Our configuration property values will have following 4 types again: boolean, integer, float and text (depending of the types defined in their module types), but they will be set as their string representation. The benefits are:
- defined value type (String) - will be easily serialized / deserialized
- equal presentation as defaultValue of configuration property
- improve accuracy of configuration values - internal presentation of float is as BigDecimal, but when create a bigDecimal from float the accuracy can be lost, which is not same when the bigDecimal is created from string. (i.e new BigDecimal(0.3) != new BigDecimal("0.3"))

**Comment by BenediktNiehues** [comment]
+1 for
>  Or shall we keep FQCN as an option, i.e. if we find a class for that name, we use the current validation and if not we fall back to string compare?

Be aware that we have several generic handlers in place which make use of the class hierarchy for their inputs (e.g. CompareConditionHandler). If we won't support this any longer, this would not work anymore.

**Comment by danchom** [comment]
@BenediktNiehues  for general case we can use '*' , which means all types

**Comment by sjka** [comment]
regarding normalization of configuration values, I have created #1423. Hopefully it helps in your case too...

**Comment by kaikreuzer** [comment]
1+2 are implemented, 3 is continued on #1472, so I close this issue.
