### ISSUE TITLE
IDE Broken

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1225]
This morning it seems an update to the IDE went through, and it seems to break everything!  The start tasks fail, and if I try and reload the TP I get the following errors -:

![image](https://cloud.githubusercontent.com/assets/1041475/13898409/18a69310-edc8-11e5-994b-f5bceeedf8b6.png)

![image](https://cloud.githubusercontent.com/assets/1041475/13898526/0b1805c2-edcc-11e5-927a-cb7fe0ed3d8a.png)

**Comment by kaikreuzer** [comment]
It looks as if this is the OH2 IDE, so this issue tracker is probably the wrong place for it.

You seem to use some completely outdated target platform file. The latest is [here](https://github.com/openhab/openhab-distro/blob/master/launch/openhab.target) and as you can see, it only references 4 repositories (and their content resolves nicely for me).

**Comment by cdjackson** [comment]
Hmmm - sorry. I thought I'd put it in the OH2 repo. It seems that the IDE doesn't keep up to date automatically - or at least not very well.....
