### ISSUE TITLE
ConfigStatusMessage / Provider

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1237]
How are config status messages provided to the UI? There doesn't seem to be much doc I can find and it doesn't look like it appears in the REST interface. Does this still require adding to the REST interface or am I missing something?

**Comment by kaikreuzer** [comment]
Please better ask questions in the forum or directly on PRs that have dealt with this topic, e.g. https://github.com/eclipse/smarthome/pull/1150.

**Comment by cdjackson** [comment]
Sorry - I did search for this but didn’t find anything and thought it needed to be added.
