### ISSUE TITLE
Extend composite module type

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#1247]
At the moment configuration properties of child modules can refer configuration properties of composite module. The composite configuration property value  is set as child configuration property value. 
The functionality of composite module type has to be extended to permit composite configuration property to configure part of child configuration property. In that way a complex child configuration property can be configured by more then one simple configuration properties of composite module.

For example:
if  a composite module type have properties:
name
sir-name

child module can configure message property in following way:
message: "Hello ${name}  ${sir-name}."
or
debug: "{level:'warn', name:${name}, sir-name:${sir-name}}"

**Comment by kaikreuzer** [comment]
I am not sure if I fully understand the suggestion, so let me repeat it with my own words:
Currently, a module in a complex type can only have a configuration value like `${a}` and you would like to allow also `${a} and ${b}`?

**Comment by danchom** [comment]
At the moment config property of composite type can be referred by configuration properties of child modules and in this way the composite configuration value  is set as configuration value of child modules.
We want to extend this functionality with an option where the composite config value is used as part of child configuration value. The child configuration value will be some kind of pattern where the composite config value will be used in. In that way this 'pattern' can be configure with more then one composite configuration properties.
For example:
```
  {  
     "uid":"Logger",
     "label":"",
     "description":"",
     "configDescriptions":[  
        {  
           "name":"message",
           "type":"TEXT",
           "defaultValue":"Default message",
           "required":true
        }
     ]
  },
  {  
     "uid":"CompositeLogger",
     "configDescriptions":[  
        {  
           "name":"compositeMessage",
           "type":"TEXT",
        }
     ],
     "inputs":[  
        {  
           "name":"compositeInput",
           "type":"java.lang.String",
        }
     ],
     "children":[  
       {  
           "id":"currentImplementation",
           "type":"Logger",
           "configuration":{  
              "message":"$compositeMessage"
           }
        },
        {  
           "id":"newFeature",
           "type":"Logger",
           "configuration":{  
              "message":"{$compositeMessage}. Data received: {$compositeInput}"
           }
        }
     ]
  }
```

In that way we can configure predefined JavaScripts or to define complex JSON structure which is used as configuration property value.

**Comment by danchom** [comment]
The other option is to use same patter for defining reference ${refName} in both case:  the old one when entire value is replaced) and in the new one when part of the value is replaced.
For example:

```
  {  
     "uid":"Logger",
     "label":"",
     "description":"",
     "configDescriptions":[  
        {  
           "name":"message",
           "type":"TEXT",
           "defaultValue":"Default message",
           "required":true
        }
     ]
  },
  {  
     "uid":"CompositeLogger",
     "configDescriptions":[  
        {  
           "name":"compositeMessage",
           "type":"TEXT",
        }
     ],
     "inputs":[  
        {  
           "name":"compositeInput",
           "type":"java.lang.String",
        }
     ],
     "children":[  
       {  
           "id":"currentImplementation",
           "type":"Logger",
           "configuration":{  
              "message":"${compositeMessage}"
           }
        },
        {  
           "id":"newFeature",
           "type":"Logger",
           "configuration":{  
              "message":"${compositeMessage}. Data received: ${compositeInput}"
           }
        }
     ]
  }
```
