### ISSUE TITLE
plugin.xml_gen files

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1271]
After compiling with Maven, I can see that few files are marked by git as modified:
* bundles/model/org.eclipse.smarthome.model.items.ui/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.items/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.persistence.ui/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.persistence/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.rule.ui/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.rule/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.script.ui/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.script/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.sitemap.ui/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.sitemap/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.thing.ui/plugin.xml_gen
* bundles/model/org.eclipse.smarthome.model.thing/plugin.xml_gen

Sould these files be ignored by git ?

**Comment by maggu2810** [comment]
Yes, and they are part of the gitignore file in the Eclipse SmartHome root repository path.

https://github.com/eclipse/smarthome/blob/8c0dbdb6ba0a860f04d4ee4e4480199db6a50e92/.gitignore#L7

**Comment by lolodomo** [comment]
Apparently it does not work.

**Comment by maggu2810** [comment]
It is working at least on my machines.
What about the other developers, does gitignore work as expected on your machines?

**Comment by lolodomo** [comment]
Reading https://git-scm.com/docs/gitignore I would try to replace */plugin.xml_gen by **/plugin.xml_gen ?

**Comment by maggu2810** [comment]
Yes, two "*" seems to make more sense. Can you test and create a PR?

**Comment by maggu2810** [comment]
Or simple "plugin.xml_gen" without a wildcard and directory separator at all.

**Comment by lolodomo** [comment]
Just updating the file .gitignore is not enough. Even if I put a full path without wildcard, the file is still in state "modified" for git.
Maybe the problem is more that the file is already in git ? Should we suppress all plugin.xml_gen files from git ?

**Comment by lolodomo** [comment]
When I run a "git diff" on one of these files, the message displayed let me know the only difference is LF vs CRLF. So maybe these files appear as "modified" only on a Windows platform and not on a Linux platform.

**Comment by maggu2810** [comment]
> So maybe these files appear as "modified" only on a Windows platform and not on a Linux platform.

Okay, this could be a reason I never see it.

But Git should be able to handle added files that are ignores (and not display modifications). I hope I will find some time to look at this issue. But have no time until the end of the week.

**Comment by kaikreuzer** [comment]
Does maybe some special git setting help (like the one described in http://stackoverflow.com/a/7180812)?

**Comment by lolodomo** [comment]
I close this issue because the problem seems to have disappeared.
