### ISSUE TITLE
How to get hold of ThingTypeUID in discovery?

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1272]
I just noticed that ThingUID.getThingTypeId() was depreciated. I use this function in the discovery piece of a binding, where a device/hardware related string is converted in a ThingUID, which I used getThingTypeId() upon later on. (basically, I used the ThingTypeID to set .withLabel() on a DiscoveryResult object

It is replaced with Thing#getThingTypeUID() instead, I presume because of the functionality that allow the change the type of thing at runtime.

How to enrich discovery results with the thing type information?

**Comment by kaikreuzer** [comment]
It is still possible to put the ThingType in your ThingUID of the discovery result, so your binding can rely on this fact and get it out from there again.
So maybe it isn't fully correct that the method has been deprecated, but this was done not to make people think they can rely on this in general. Maybe we could offer another method for retrieving the "second segment" of a ThingUID for your purpose. For the moment, just continue to use getThingTypeUID and all is fine.
@sjka What do you think?

**Comment by kgoderis** [comment]
On a separate note, related to this, I saw that ChannelUID.getThingTypeId() was removed altogether. What is the alternative approach here?

**Comment by kaikreuzer** [comment]
Get ThingUID, then get Thing from registry and ask for its type.

**Comment by sjka** [comment]
@kaikreuzer I deliberately marked it as deprecated because we made the conscious decision to drop the semantic of the second element. If a binding still relies on it: fine by me. But no other entities within the stack must do that. Especially no clients/UIs. 

The DiscoveryResult actually _is_ enhanced: You can use DiscoveryResultBuilder.withThingType(...) to pass a ThingTypeUID and read it back via DiscoveryResult.getThingTypeUID() later on. Or I didn't get your question right...

**Comment by kaikreuzer** [comment]
Ok, I missed that there is now a `DiscoveryResult.getThingTypeUID()`.
@kgoderis I assume this answers your question then?

**Comment by kgoderis** [comment]
@kaikreuzer @sjka  err... I need it here:

DiscoveryResult discoveryResult = DiscoveryResultBuilder.create(thingUID).withProperties(properties)
                    .withBridge(bridgeUID).withLabel( [here]).build();

the ThingUID is derived from a string returned by the remote device. Since there is no way to change the label on the DiscoveryResult after is has been built, it is rather a catch-22 I guess.

**Comment by kaikreuzer** [comment]
I am not sure, if I can follow you... So you are constructing the label from the thingType, which is a part of the thingUID?
So why can't you derive the label directly from the according sub "string returned by the remote device"?

**Comment by kgoderis** [comment]
Yes of course, but it means copying algorithms over as it implies string manipulations etc - it is not very beautiful
