### ISSUE TITLE
Lifx bindings stuck INITIALIZING forever

### ISSUE THREAD

**Issue by hadees** [eclipse/smarthome#1280]
For some reason some of the LIFX bulbs are getting stuck in the `INITIALIZING` state forever.  It seems to happen more often when they already exist rather than just adding them.

```
lifx:colorlight:D073D5003FBE (Type=Thing, Status=INITIALIZING, Label=Original 1000, Bridge=null)
lifx:colorlight:D073D5004280 (Type=Thing, Status=ONLINE, Label=Original 1000, Bridge=null)
lifx:colorlight:D073D50066D2 (Type=Thing, Status=INITIALIZING, Label=Original 1000, Bridge=null)
lifx:colorlight:D073D5006772 (Type=Thing, Status=INITIALIZING, Label=Original 1000, Bridge=null)
lifx:colorlight:D073D5023BD6 (Type=Thing, Status=ONLINE, Label=Original 1000, Bridge=null)
lifx:colorlight:D073D5115204 (Type=Thing, Status=INITIALIZING, Label=Color 1000, Bridge=null)
lifx:colorlight:D073D51157DF (Type=Thing, Status=INITIALIZING, Label=Color 1000, Bridge=null)
```

Following @kaikreuzer 's [advice](https://community.openhab.org/t/lifx-bindings-stuck-initializing-forever/8547) I ran `log:set DEBUG org.eclipse.smarthome.binding.lifx` in the console and [grabbed my logs](https://gist.github.com/hadees/9ad23dc86ebe522194c9) of the incident. 

I'm not sure the items will help or not.

```
Living (Type=GroupItem, Members=0, State=NULL, Label=null, Category=null)
lifx_colorlight_D073D5003FBE (Type=GroupItem, Members=0, State=NULL, Label=Original 1000, Category=null, Tags=[thing])
lifx_colorlight_D073D5004280 (Type=GroupItem, Members=0, State=NULL, Label=Original 1000, Category=null, Tags=[thing])
lifx_colorlight_D073D50066D2 (Type=GroupItem, Members=0, State=NULL, Label=Original 1000, Category=null, Tags=[thing])
lifx_colorlight_D073D5006772 (Type=GroupItem, Members=0, State=NULL, Label=Original 1000, Category=null, Tags=[thing])
lifx_colorlight_D073D5023BD6 (Type=GroupItem, Members=0, State=NULL, Label=Original 1000, Category=null, Tags=[thing])
lifx_colorlight_D073D5115204 (Type=GroupItem, Members=0, State=NULL, Label=Color 1000, Category=null, Tags=[thing])
lifx_colorlight_D073D51157DF (Type=GroupItem, Members=0, State=NULL, Label=Color 1000, Category=null, Tags=[thing])
ntp_ntp_local (Type=GroupItem, Members=0, State=NULL, Label=Local Time, Category=null, Tags=[thing])
```

**Comment by kaikreuzer** [comment]
@kgoderis Could you have a look?

**Comment by kgoderis** [comment]
Yep - Not sure what is really going on, maybe a clash between the handler code and discovery service

**Comment by hadees** [comment]
@kgoderis let me know if you need additional details

**Comment by kaikreuzer** [comment]
@kgoderis I have the same effect right now. It used to work, but after a restart, I can still see the network runnable sending out polling requests, but the handler simply does not receive anything back.

**Comment by kaikreuzer** [comment]
Oh well, in my case the reason was that my computer suddenly was in a different network than the bulb.
Nonetheless, in this situation I would expect the status to go to OFFLINE.
Maybe the simplest solution is to always first set it to OFFLINE after initialize() has been called?

**Comment by kgoderis** [comment]
Fixed with https://github.com/eclipse/smarthome/pull/1363
