### ISSUE TITLE
BasicUI: special characters break levels in navigation

### ISSUE THREAD

**Issue by shorty707** [eclipse/smarthome#1293]
if the "label" of a group / frame has a " & " character the UI is broken and a click will not open the next level.
this might be true for other characters then & 

#![bugund](https://cloud.githubusercontent.com/assets/13987575/14120021/4164c4ee-f5f1-11e5-88e8-9b5944642da4.JPG)

**Comment by kaikreuzer** [comment]
@resetnow Could you have a look?

**Comment by resetnow** [comment]
#1302
