### ISSUE TITLE
Hue Binding unable to detect if username in configuration is null

### ISSUE THREAD

**Issue by shry15harsh** [eclipse/smarthome#1294]
There is the following code in `HueBridgeHandler.java`
```
public void onNotAuthenticated(HueBridge bridge) {
        String userName = (String) getConfig().get(USER_NAME);
        if (userName == null) {
            createUser(bridge);
        } else {
            try {
                bridge.authenticate(userName);
            } catch (Exception e) {
                handleAuthenticationFailure(e, userName);
            }
        }
    }
```
userName is a Java String here. When it is a null string, the condition (`userName == null`) is not true. It should be handled as (`userName.trim().equals("") || userName == null`).

Without it, this code was not working for me and I was not able to link Hue Bridge even after pressing the Link button.

**Comment by tavalin** [comment]
The conditions on your suggested fix would need to be the other way round.  With your suggestion, if userName does happen to be null then userName.trim() would throw a NPE before you've checked if the variable is null.

**Comment by shry15harsh** [comment]
Sorry, I wrote that by mistake. Yes, it should be (`userName == null||userName.trim().equals("")`).

**Comment by kaikreuzer** [comment]
> When it is a null string, the condition (userName == null) is not true

I guess what you mean is "when it is an EMPTY string". My question would be: How can it potentially happen to be an empty string? In general, the username needs to have 10+ chars, so an empty string is in no valid value anyhow.
I assume you get an empty string by deleting the user name in the Paper UI, right? The correct fix would imho be to make sure that the Paper UI deletes this config value (instead of setting it to a null string).

**Comment by shry15harsh** [comment]
I mean empty string. It is by default an empty string. Empty String is a valid value when user does not have/know authenticated username. In such a case, hue creates a new user on the Hue bridge and returns the hash value of username which is then stored in the configuration.

Also, username can be set to empty string using Rest API which may be a common case when developing applications over Openhab.

**Comment by maggu2810** [comment]
Just to follow the code (I cannot look at the Hue spec etc. ATM).
If an empty string is a valid value and we check for that, why do we need to call trim? A string containing whitespaces differs from an empty one. Didn't it?
Also I would prefer to call isEmpty if we want to check for an empty string.

**Comment by shry15harsh** [comment]
Yeah right. isEmpty should be used. I should have considered that scenario.

**Comment by kaikreuzer** [comment]
This is solved through https://github.com/eclipse/smarthome/issues/1301, since the userName is now correctly set to null instead of an empty string.
