### ISSUE TITLE
Basic UI shows openHAB as title when non-existing sitemap name is passed as argument

### ISSUE THREAD

**Issue by satish-nikam** [eclipse/smarthome#1300]
Minor change requested: When we pass non-existing sitemap name as argument in basic app URL (e.g. http://127.0.0.1:8080/basicui/app?sitemap=xyz), it correctly lists all available sitemap, but the title of this page is shown as "openHAB BasicUI" and says "Welcome to openHAB!". It should be replaced by "Smarthome BasicUI" and "Welcome to Smarthome".

**Comment by resetnow** [comment]
As far as I understand, Eclipse Smarthome is not meant to be used as a standalone product but is a framework which is used by OpenHAB. While it would be nice to change  this line accordingly I'm currently not aware of any other solutions based on ESH.

**Comment by kaikreuzer** [comment]
> I'm currently not aware of any other solutions based on ESH

Well, there are, see https://www.eclipse.org/smarthome/index.html#references.
So it is correct that openHAB must not be mentioned in any code in ESH itself, because it is an independent framework.

Instead of "Smarthome BasicUI" and "Welcome to Smarthome", I would even rather suggest to change the texts to "Basic UI" and "Welcome".

**Comment by hfanieng** [comment]
> Well, there are, see https://www.eclipse.org/smarthome/index.html#references.
So it is correct that openHAB must not be mentioned in any code in ESH itself, because it is an independent framework.

Interesting information. The link to Yetu is broken - is this project still active?

**Comment by resetnow** [comment]
#1305

**Comment by kaikreuzer** [comment]
> The link to Yetu is broken - is this project still active?

No, they went out of business - I will have a replacement to be listed there soon...

**Comment by kaikreuzer** [comment]
Implemented with #1305, thanks!

**Comment by maggu2810** [comment]
Why has this one been reopened? Is there something missing?

**Comment by kaikreuzer** [comment]
No, my mistake, I meant to close it.
