### ISSUE TITLE
Enhancement request: Provide "add all" or "approve all" option in the inbox

### ISSUE THREAD

**Issue by satish-nikam** [eclipse/smarthome#1307]
Enhancement request: Provide "Add All" or "Approve All" option in the inbox.

This is useful when discovery enabled binding discovers lots of devices and user need to add each one individually. Adding all of them with a single button click is very convenient.

**Comment by kaikreuzer** [comment]
The problem with such a feature is that the user also provides a label for the thing upon approval and in future possibly also a location (and maybe more). I do not see a good way to do this as a bulk operation.

**Comment by satish-nikam** [comment]
hmm..I agree...seems no good way to implement this in generic way.
