### ISSUE TITLE
Test failure(s): unexpected state

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1308]
Unexpected state in core thing test:
https://gist.github.com/maggu2810/0e449195ea7761fdfdb7bec03bc9bc22

**Comment by maggu2810** [comment]
Similar (expected state) for the Hue binding:
https://gist.github.com/maggu2810/1eabd3be39c36fd91fdae20d937c9e65

**Comment by kaikreuzer** [comment]
@sjka When having a look, please pull #1310 as this fixes the rest of the tests.

**Comment by maggu2810** [comment]
#1315 contains changes for the Hue binding only.
Does this solve the error reported in the first comment (unexpected state in the core.thing test), too?

**Comment by maggu2810** [comment]
Ah, okay, let's refer #1314 here, too.
