### ISSUE TITLE
Hue Color Temperature is updated to 0 every time

### ISSUE THREAD

**Issue by shry15harsh** [eclipse/smarthome#1318]
Whenever Hue updates the value of color temperature, it is updating it wrong because of wrong formula in `toColorTemperaturePercentType` method in `LightStateConverter.java`
`int percent = (lightState.getColorTemperature() - MIN_COLOR_TEMPERATURE) / COLOR_TEMPERATURE_RANGE;`
The correct formula should be
`int percent = (int) Math.round(((lightState.getColorTemperature() - MIN_COLOR_TEMPERATURE) * 100.0 )/ COLOR_TEMPERATURE_RANGE);`

**Comment by maggu2810** [comment]
Thanks for investigation. Can you create a PR with a fix?

**Comment by shry15harsh** [comment]
Yes, of course. :)

**Comment by kaikreuzer** [comment]
Fixed through https://github.com/eclipse/smarthome/pull/1323.
