### ISSUE TITLE
Introduce configurable transition time for LIFX

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1332]
The new LIFX implementation behaves different to the previous version in the sense that it seems to change the colors of the bulbs with no transition time. This leads to a rather "rough" effect that is unpleasant for the eye, especially when sending many changes quickly one after the other (like when moving around on the color wheel).

It would be nice if there would be a configurable transition time for the bulbs (with a default probably around 100ms or whatever the official LIFX app is using as well).

Note that Philips hue also changes the colors with some transition time, so this feature would also make it much nicer to operate hue and LIFX bulbs together within a scene.

@kgoderis Is this hard to add? I would hope that it is just some value that you need to pass on to the messages that you send out to the bulbs, right?

**Comment by kgoderis** [comment]
@kaikreuzer I need to revisit the API in order to answer that.

**Comment by kgoderis** [comment]
Fixed with https://github.com/eclipse/smarthome/pull/1363

**Comment by polarathene** [comment]
@kgoderis Any reason the transition time is not configurable? In some cases I may want to run a light effect over several hue bulbs and instant changes of state(0 transition time) or more drawn out smooth transitions can be desirable depending on the effect. Advice on how to approach this if transition time is not configurable?

**Comment by kgoderis** [comment]
@polarathene There was a PR  after this one that made it configurable, see https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/thing-types.xml#L19

**Comment by polarathene** [comment]
@kgoderis Is that only for LIFX? I had a look at the hue binding and there doesn't appear to be a `thing-types.xml`. I think they're similar but Hue has that file for each of the different bulb types? [This is mine](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/LCT001.xml) according to Paper UI.

Phillips Hue was mentioned in the issue description, but the transition time seems fixed, any chance to add support for it? I'm happy to create PRs if some guidance could be given on how to go about it, still figuring out openHAB platform, haven't really gotten to dive into becoming familiar with the codebase yet. I know that transition time is supported with Hue as I've adjusted it with a nodejs package in the past.

**Comment by kgoderis** [comment]
LIFX only AFAIK
