### ISSUE TITLE
Editing thing label clears various configuration properties

### ISSUE THREAD

**Issue by satish-nikam** [eclipse/smarthome#1340]
I see that the issue #1313 is closed, but I still see similar issue when editing thing label. I edited the thing label. The PaperUI says "Thing Updated", but it clears all my configuration properties. I have one string type, one integer type and one options (dropdown) properties.

**Comment by kaikreuzer** [comment]
That does not sound good, I would assume that I introduced this bug through https://github.com/eclipse/smarthome/pull/1286.

@sjka As this sounds rather critical, do you have a chance to look into it?

**Comment by satish-nikam** [comment]
This still not working in all cases. I see issues in following cases:
- If I edit only label, label is updated correctly, I get the message "Thing Updated", but the label at top still shows old value. It shows new value only after refreshing screen
- In addition to label, if I edit some other configuration property, then I get message "Thing Updated". But label is not updated at all, it only updates other property, even after refreshing the page it shows old label.

**Comment by sjka** [comment]
I cannot reproduce the observed behavior. Are you sure you fetched the latest changes & rebuilt (at least) the PaperUI bundle via maven?

**Comment by satish-nikam** [comment]
I tested with latest code, built with mvn and still see this issue. It may be due to my custom binding also. But the same binding code base works well with older ESH build (around 3 weeks back).

I debugged this little bit and found that multiple thing update events are fired. First with new label value, and second one with old label value overwriting the new label.
