### ISSUE TITLE
Rule module configuration page broken

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1346]
When adding a new rule module to a rule, the windows seems to display configuration properties from not only the chosen module type, but from others as well, see this example for a Script Action:

![bildschirmfoto 2016-04-08 um 14 28 59](https://cloud.githubusercontent.com/assets/3244965/14383594/75f93468-fd96-11e5-99cb-d8dec5718a72.png)

There should clearly not be multiple groups "Others" and the first group shows the parameters of a post command action, not the script action.

**Comment by maggu2810** [comment]
Have seen this this morning, too.
