### ISSUE TITLE
RaspBee-binding: Add support for RaspBee bridge

### ISSUE THREAD

**Issue by fatihboy** [eclipse/smarthome#1352]
**RaspBee** (https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/raspbee/?L=1) is a shield which brings ZigBee connectivity to Raspberry Pi. The shield allows direct communication with ZigBee PRO devices like Philips Hue, XBee Series 2 and others.

Please add binding to control compatible devices over RaspBee bridge

**Comment by sjka** [comment]
With https://github.com/eclipse/smarthome/pull/1353#issuecomment-251192073 I guess we can close this issue too.
