### ISSUE TITLE
BasicUI: special characters break levels in navigation 

### ISSUE THREAD

**Issue by shorty707** [eclipse/smarthome#1366]
the previously opened issue now even got worse
https://github.com/eclipse/smarthome/issues/1293

currently even more characters break the navigation

for eg: 
21.5°C
the degree symbol seems to break it

**Comment by shorty707** [comment]
@resetnow maybe you can have another look?

**Comment by shorty707** [comment]
![basic](https://cloud.githubusercontent.com/assets/13987575/14438344/edfe377e-0025-11e6-9ca0-c9e7a322a32a.JPG)

for me this breaks actually all my "rooms" and I can not access the "second level" of the room groups

**Comment by shorty707** [comment]
```
07:32:17.246 [WARN ] [ternal.render.AbstractWidgetRenderer] - Cannot escape path '10.04. 06:25 (Wohnzimmer)' in URL. Returning unmodified path.
07:32:17.346 [WARN ] [ternal.render.AbstractWidgetRenderer] - Cannot escape path '20.9°C | 58% RH |  Hell: 4 Lux' in URL. Returning unmodified path.
07:32:17.372 [WARN ] [ternal.render.AbstractWidgetRenderer] - Cannot escape path '19.5°C | Hell:1 %' in URL. Returning unmodified path.
07:32:17.416 [WARN ] [ternal.render.AbstractWidgetRenderer] - Cannot escape path '19°C | Hell:2 %' in URL. Returning unmodified path.
07:32:17.422 [WARN ] [ternal.render.AbstractWidgetRenderer] - Cannot escape path '18.5°C | Hell:1 %' in URL. Returning unmodified path.
07:32:17.426 [WARN ] [ternal.render.AbstractWidgetRenderer] - Cannot escape path '21°C | Hell:2 %' in URL. Returning unmodified path.
07:32:17.571 [WARN ] [org.eclipse.jetty.util.UrlEncoded   ] - java.lang.NumberFormatException: !hex 37
07:32:17.577 [WARN ] [org.eclipse.jetty.util.UrlEncoded   ] - java.lang.NumberFormatException: !hex 38
07:32:17.578 [WARN ] [org.eclipse.jetty.util.UrlEncoded   ] - java.lang.NumberFormatException: !hex 38
07:32:17.593 [WARN ] [org.eclipse.jetty.util.UrlEncoded   ] - java.lang.NumberFormatException: !hex 38
07:32:17.604 [WARN ] [org.eclipse.jetty.util.UrlEncoded   ] - java.lang.NumberFormatException: !hex 38
```

**Comment by resetnow** [comment]
Well, this time it doesn't work in a different way :) I'll look into that.

**Comment by shorty707** [comment]
strange thing is that I **think **it happend **before **I switched to a new OH2 nightly build

**Comment by xsnrg** [comment]
It has been happening for me for about a week.

**Comment by shorty707** [comment]
ok ... I would vote for a critical tag ;-)

**Comment by resetnow** [comment]
@shorty707 did you by chance notice if this issue was present after #1302?

**Comment by shorty707** [comment]
@resetnow no sorry - I skipped a few nightlys

I can confirm that the "warnings" on log from above have been there for a long time but had no effect and the UI still worked.
but which build caused the ui to break i dont know...sorry

**Comment by shorty707** [comment]
@resetnow @kaikreuzer 
there must have been updates in ESH this night that have massive impact to the current build

any values on basicUI that are "calculated" by a rule (like the "room values" as a concated item (see above) now are blank until the rule fires the next time while already looking the page!
hence basic UI is fully blank when accessing it

**Comment by yphyph01** [comment]
Hi,

I confirm the same issue with accent caracters (é, è, ...) in chrome 
Navigation from any group with those accent caracters in their label is not working. You click on your group but no action ...
I've experienced the issue with the build #226, not resolved in #229 BUT I've not experienced this isse with the Beta2 build. Unfortunatly, I have not tested other intermediate bulds.

Regards

**Comment by resetnow** [comment]
So I just tried d814d25184b2a7548e5d88d0fb67dd560b349faa and this revision doesn't have this problem, I am able to navigate through multiple levels with all sorts of unicode characters.

![screenshot from 2016-04-12 21-58-02](https://cloud.githubusercontent.com/assets/2057191/14471978/25f085ec-0102-11e6-929f-fed01eec5e6d.png)

**Comment by resetnow** [comment]
It appears the problem only exists if a <i>value</i> contains special symbols, so my previous comment is not correct.

Thanks for reporting this bug! #1373
