### ISSUE TITLE
POST request for thing addition gives 500 if same UID exists already

### ISSUE THREAD

**Issue by shry15harsh** [eclipse/smarthome#1368]
If a thing is already added and if we try to add the same thing again by sending the POST request to `/things`, it gives a 500 error. If we try again then the response is 200 and the thing is added.

What is happening here is, if we try to add the same thing again the old thing is removed first (according to the method `addThingSafely` in `ThingSetupManager` class) but before it adds the new thing, it is sending back 500 error somehow.

When we retry the request, it creates the thing because the old thing has been removed in the previous step.

I am trying to figure out what is wrong there. Anyone has a clue?

**Comment by sjka** [comment]
Just tried to reproduce it, but I get a "409: Conflict" on the second try when the thing already exists. Do you happen to have some logs which you could share here?

**Comment by sjka** [comment]
Oh, I just noticed: You are adding the thing via the PaperUI, I assume... It's using the deprecated ThingSetupManagerResource (i.e. POST /rest/setup/things), and not the "proper" rest API (i.e. POST /rest/things). That one indeed doesn't do a duplicate check and therefore raises an IllegalArgumentException, leading to the described behavior. 
However, as it's in the process of getting dropped and replaced (see #1013), I don't think it's worth spending any efforts in fixing it.

**Comment by shry15harsh** [comment]
Oh, I was indeed using the deprecated API. Though adding through /rest/things (after adding the thing) giving me 500 error and not 409.

Logs are here http://pastebin.com/GLXPFqxZ

**Comment by sjka** [comment]
According to the line numbers in your stacktrace, you are working on a state about 4-5 months old. There indeed was no check if the thing already existed...
Update your codebase an you will be fine.

**Comment by shry15harsh** [comment]
You're right. Actually I was using older Openhab2 build. Now they have changed it to Openhab2-addons and distro (which runs on Java 8 and has lot of change), so did not update the runtime.

Though, as according to the latest code, addThingSafely method ensures that thing is removed first and then added. I wonder how come you get 409 error, you should get successful response with the thing added, right?

**Comment by sjka** [comment]
> I wonder how come you get 409 error

That's how:

```java
        if (thingUID != null) {
            // check if a thing with this UID already exists
            Thing thing = thingRegistry.get(thingUID);
            if (thing != null) {
                // report a conflict
                return getThingResponse(Status.CONFLICT, thing, locale,
                        "Thing " + thingUID.toString() + " already exists!");
            }
        }
```

(see https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java#L127)

**Comment by shry15harsh** [comment]
Oh, it is already checked at ThingResource. Thank you very much for all the clarification. :)
