### ISSUE TITLE
Test failure(s): automation.integration.test

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1370]
Short log:
```text
assert that a rule from json file is added automatically(org.eclipse.smarthome.automation.integration.test.AutomationIntegrationJsonTest)  Time elapsed: 0.053 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "ItemSampleRule"
     but: was "ItemSampleRuleWithReferences"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.Assert$assertThat.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:169)
	at org.eclipse.smarthome.automation.integration.test.AutomationIntegrationJsonTest.assert that a rule from json file is added automatically(AutomationIntegrationJsonTest.groovy:170)

assert that a rule from json file is added automatically with resolved module references(org.eclipse.smarthome.automation.integration.test.AutomationIntegrationJsonTest)  Time elapsed: 0.07 sec
asserting that the host-fragment support works correctly(org.eclipse.smarthome.automation.integration.test.AutomationIntegrationJsonTest)  Time elapsed: 6.397 sec

Results :

Failed tests: 
  AutomationIntegrationJsonTest.assert that a rule from json file is added automatically:170 
Expected: is "ItemSampleRule"
     but: was "ItemSampleRuleWithReferences"
```

Long log: https://gist.github.com/maggu2810/e480760fdd5db034512654c75a272239

**Comment by maggu2810** [comment]
Problem exists in commit ID: f2022ef8787772ea46cb0eb6b4cacc5ca5292bff
Will test the previous one.

**Comment by maggu2810** [comment]
The build of 989201cc1cb092cf3e9d1d3933921020f8869455 succeeded on my machine.
So it could be caused by #1317

**Comment by maggu2810** [comment]
It seems to work on Hudson, I know. But then there is something unstable now.

**Comment by vilchev** [comment]
Hi @maggu2810 
thanks and sorry! The integration test that I added for the new feature was showing optimization of an already existing Rule template `ItemSampleRule` - so the new rule(`ItemSampleRuleWithReferences`) and the old one(`ItemSampleRule`) had quite the same tags.. The new `ItemSampleRuleWithReferences` have all tha tags that `ItemSampleRule` have plus one additional `references` to point out the difference.

Failing Test is getting the rules by tag - which both Rules had. So the first rule that was added would win

Please try it with the PR that I just did with fix for the failing test

**Comment by maggu2810** [comment]
Thanks, you solved it.
