### ISSUE TITLE
documentation todos

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1382]
I have read some documentation on https://www.eclipse.org/smarthome/documentation/
IMHO there is some stuff not up-to-date.
Instead of create a issue for every stuff, I would like to collect them first.

To do:
- Paper UI documentation update (e.g. IIRC missing minify has implemented)

I assume it is solved by an update of the documentation:
- Binding: FS Internet Radio: https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/README.md
- Binding: NTP: https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.ntp/README.md
- Binding: Sonos: https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/README.md

**Comment by rtvb** [comment]
I have started updating the Sonos documentation:

#1598
