### ISSUE TITLE
Hue binding new Aura; new modelID (LLC014)

### ISSUE THREAD

**Issue by 3sr3v3r** [eclipse/smarthome#1391]
I added a new LivingColors Aura to my setup which wasn't discovered by the binding.
Turns out the lamp has a new modelID LLC014 (instead of LLC007).

Is (not yet) in the hue developers documentation as supported light but works without a problem and identical to my other Aura lights.

**Comment by kaikreuzer** [comment]
Note that all currently unsupported lights will start working once #673 is fully implemented and merged.

For the time being, feel free to create a PR that adds XML files for the mentioned devices - as you seem to own them, you are the best person to test that it is working :-)

**Comment by kaikreuzer** [comment]
#673 is now merged and hence this model should now be supported out of the box as well.
