### ISSUE TITLE
Hue binding not supporting LivingWhites (modelid LWB001)

### ISSUE THREAD

**Issue by Max-1968** [eclipse/smarthome#1397]
i've started testing openhab2 (daily snapshot April 17th) - Althought I've connected several LivingWhites (modelid LWB001) bulbs to my bridge and can control these fine using the hue app these are not recognized by the hue binding. Looking at smarthome/extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/ it seems these indeed are not considered which is corrected according to API description, although they in fact can be connected to the bridge and controlled by it. Thus please add LWB001 to the supported devices (same capabilites as the "white" bulbs LWB006).
Please not that the same seems to be the case for modelid LWB002 and LWB003, however I can not test these modelids as I only have LWB001.

**Comment by kaikreuzer** [comment]
Note that all currently unsupported lights will start working once https://github.com/eclipse/smarthome/pull/673 is fully implemented and merged.

For the time being, feel free to create a PR that adds XML files for the mentioned devices - as you seem to own them, you are the best person to test that it is working :-)

**Comment by kaikreuzer** [comment]
This is by now supported through the new generic types for hue.
