### ISSUE TITLE
Use Xtext web as a potential replacement for the Designer

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1402]
Since Xtext 2.9.2, there is an initial support for web-based DSL editors, see https://www.youtube.com/watch?v=QtW6WBJztPw.

This would be a huge gain over the current Designer, since
- it does not require to build and maintain an RCP application for different platform
- there is no problem with transferring the file from a desktop to the runtime instance (see https://github.com/eclipse/smarthome/issues/619)
- the editor has direct access to all installed add-ons (e.g. rule actions), so it is easy to solve https://github.com/eclipse/smarthome/issues/997

**Comment by kaikreuzer** [comment]
@chriskn told me that he successfully prototyped this feature and it seems as if there should be no blockers regarding the implementation of such a feature for the runtime.

A remaining question is, where this web editor should be built in. There are imho several options:

1. Build a new simple UI specifically for the textual configuration support.
Pros: easy to provide as an option, UI can be designed specifically for that purpose (with a file explorer, etc.)
Cons: Yet another UI, which might duplicate some features from other UIs and which makes it more difficult for the users to know what to do where

2. Add it to the Paper UI
Pros: It is the existing "admin" UI in ESH and thus the most natural place
Cons: Paper UI is designed for "touch"/mobile support, while text editing really only makes sense for PC use. Paper UI is meant to be "graphical/easy" administration, the textual files are so far the "non UI option" for the system configuration, so from a functional view, it does not really fit to the Paper UI. Furthermore, it isn't easily possible to add it as an optional feature, hence it has to be "baked in" and the code would be within the Paper UI even for solutions that do not support any textual configuration.

3. Only offer the runtime side and leave the UI to the solution
For openHAB, I could e.g. imagine that support is added in HABmin, but this is nothing that can be moved to ESH directly.
Pros: No decision needed at ESH
Cons: No UI available in ESH to demo this feature (possibly (1) could be done in a simplistic way to mitigate this issue)

What do you think? @cdjackson, what is your opinion regarding a possible HABmin integration?

**Comment by maggu2810** [comment]
I agree with your cons for point 2.

For point 1 and 3 this means, offer the runtime side for both, but differ in the UI (no one for 1, add one for 3).
I would prefer to add a **simply** one (or if someone have time, it could be as good as possible) but at least one, that could be used as a showcase what is possible.
Other solutions are free to not use the simply one and add a more extended version (e.g. as part of HABmin, etc.).

**Comment by chriskn** [comment]
In order to use the web feature we should update to Xtext 2.10 because this version includes multiple bug fixes regarding the web integration. 

Furthermore, the lanugae server protocol (LSP: https://github.com/Microsoft/language-server-protocol) is currently in implementation for Xtext. LSP will allow a generic integration of frontends. Likely LSP will be used in further versions of Xtext for web integration. In my opinion it makes sense to wait until the hole web api is more stable.

**Comment by SuperOok** [comment]
For Rules and Scripts, the textual DSL makes sense. But for items and sitemap I sometimes thought that some other representation might make more sense. Especially the items are a long list of unconnected entries. Maybe some table or forms-control would give a better overview? How about employing EMF Forms? It has a web-renderer via RAP...

**Comment by kaikreuzer** [comment]
@SuperOok Please note that this issue is about supporting the existing config files and only replace the complexity of the RCP Designer by a small web-based addon on the runtime.

If people are looking for UIs for configuration, they can have a look at the Paper UI and HABmin.

**Comment by sjka** [comment]
superseeded by #3898
