### ISSUE TITLE
Philips Hue lights thing by type and not by model id

### ISSUE THREAD

**Issue by shry15harsh** [eclipse/smarthome#1403]
Currently, Hue Philips lights are categorized as different things on the basis of model id. But different models have same number and type of channels and they are exactly same for Eclipse Smarthome. Philips Hue Bridge also gives us the type of light and we can use that for creating things. This way we have less number of lights definitions and it will be more generic for the binding.

Please tell me if the current implemented approach solves some problem which I'm not seeing.

Philips Hue Supported lights, their types and model ID. [Supported Lights of Philips Hue](http://www.developers.meethue.com/documentation/supported-lights)

**Comment by kaikreuzer** [comment]
I guess what you are asking for is exactly https://github.com/eclipse/smarthome/pull/673?

**Comment by kaikreuzer** [comment]
If I am wrong, feel free to re-open this issue :-)
