### ISSUE TITLE
Jue library used in Philips Hue binding is not outdated

### ISSUE THREAD

**Issue by shry15harsh** [eclipse/smarthome#1415]
In Philips Hue Binding jue library by Q42 is used. From their Github page, I got to know that this library is not under maintenance for over a year now. It is already behind official Philips Hue API.

Are you planning to change the library in future?

**Comment by kaikreuzer** [comment]
To be exact, we use a a fork of that library, which has been fixed, whenever we needed a change in the library: https://github.com/qivicon/Jue/commits/get-new-lights-with-serial-number

As long as all works as expected, there is imho no reason to change anything. After all, it is based on the hue HTTP API and this is not likely to change.

**Comment by shry15harsh** [comment]
That's great. :)
