### ISSUE TITLE
"osgi.os" cannot be used to identify the OS

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1416]
The "say" console command currently uses the system property "osgi.os" to determine the OS the stack is running on. This property is usually set on Eclipse-based products, but e.g. not within a Karaf instance.

It therefore cannot be used to reliably determine the OS.

My suggestion is to completely remove the platform specific information from the services and rather make them all optional extensions (i.e. extract the Mac TTS service from the io.voice bundle).

**Comment by kaikreuzer** [comment]
@kdavis-mozilla & @tilmankamp I just looked at extracting the MacTTSService implementation and wondered, if you already have further evolved the concept of how the say command should actually be implemented. At the moment, the TTSService still creates the audio stream and outputs it by itself.
As discussed, the TTSService should usually only create the stream which we would then hand over to an AudioSink. Do you already have an adapted say command in place for which you could create a PR?
How would we integrate "old-school" TTS services, such as MacTTS or also the 1.x services like MaryTTS into such a new setup?

**Comment by kdavis-mozilla** [comment]
@kaikreuzer Yes we have an implementation [TTSServiceMacOS.java](https://github.com/mozilla/smarthome/blob/vaani/bundles/io/org.eclipse.smarthome.io.voice/src/main/java/org/eclipse/smarthome/io/voice/internal/TTSServiceMacOS.java) that creates a stream and hands it over to an AudioSink. We also have an adapted say command [SayConsoleCommandExtension.java](https://github.com/mozilla/smarthome/blob/vaani/bundles/io/org.eclipse.smarthome.io.voice/src/main/java/org/eclipse/smarthome/io/voice/internal/extensions/SayConsoleCommandExtension.java)  We've also integrated MaryTTS too [TTSServiceMaryTTS.java](https://github.com/mozilla/smarthome/blob/vaani/bundles/io/org.eclipse.smarthome.io.voice/src/main/java/org/eclipse/smarthome/io/voice/internal/TTSServiceMaryTTS.java).

I think there are one or two issues that have to be addressed before we can do a pull request. But we should be able to do one next week.

**Comment by kaikreuzer** [comment]
Cool, sounds great - I will wait for your contribution then!

**Comment by kaikreuzer** [comment]
@kdavis-mozilla I think I will do the extraction of the MacTTS service into its own bundle anyhow right now - it seems unrelated to your work (and you would have to tear it out of io.voice as well).

Please also note that the MaryTTS service will have to be contributed to openHAB 2 (and not ESH) due to license issues.
