### ISSUE TITLE
Adding advanced channels for a thing

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1426]
I added a discovered thing (Sonos Play 5) and want to add the advanced channels using the Paper UI.

I cannot find the advanced channels anymore.

**Comment by maggu2810** [comment]
Hm, I don't see the "show more" button regardless of advanced mode is enabled in the Paper UI or not.

```html
			<md-button class="showmore" ng-init="showAdvanced = false" ng-click="refreshChannels(showAdvanced=!showAdvanced)" ng-show="isAdvanced">{{showAdvanced ? 'show less' : 'show more'}}</md-button>

```

**Comment by maggu2810** [comment]
It seems that there is no "advanced" attribute anymore on the REST interface...

using "channel types" REST API:
```
  {
    "parameters": [],
    "parameterGroups": [],
    "description": "Play the given URI",
    "label": "Play URI",
    "tags": [],
    "UID": "sonos:playuri"
  },
```

Using the things REST API:
```
      {
        "linkedItems": [],
        "uid": "sonos:zoneplayer:RINCON_...:playuri",
        "id": "playuri",
        "channelTypeUID": "sonos:playuri",
        "itemType": "String",
        "defaultTags": [],
        "properties": {},
        "configuration": {}
      },
```

**Comment by maggu2810** [comment]
The method that does the filter is using the thing type REST API.
This contains the advanced parameter.

```
      {
        "description": "Play the given URI",
        "id": "playuri",
        "label": "Play URI",
        "tags": [],
        "properties": {},
        "advanced": true,
        "typeUID": "sonos:playuri"
      },
```

So, we need to change the checkAdvance method OR / AND we add the advance boolean flag to the channel DTO.

WDYT?

**Comment by aounhaider1** [comment]
Yes, I also noticed it and fixed it. But it was part of another commit that has not yet made it to smarthome repository. see https://github.com/qivicon/smarthome/blob/things-rest/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js#L504

**Comment by aounhaider1** [comment]
I will create a pull request for that today.

**Comment by maggu2810** [comment]
I already fixed it myself. See #1427
