### ISSUE TITLE
Paper UI: Rule page refresh after add

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1429]
If a new rule is added the rules page that shows the list of rules needs to be refreshed.
The new rule is not shown after manual page load is triggered.

**Comment by aounhaider1** [comment]
I could not reproduce this. The list is updated after adding a new rule.

**Comment by maggu2810** [comment]
Started with 0 rules.
My Chrome shows me a POST to "/rest/rules" with the rule payload.
After that an immediate GET to "/rest/rules" is called that response is []
Calling "/rest/rules" again, shows me the newly added rule.

The current implementation seems to be timing dependent.
I tested this with a Raspberry Pi 2 B at the moment.

**Comment by HeNiNnG** [comment]
Yes, I can confirm this behavior.

**Comment by aounhaider1** [comment]
I could not reproduce this issue. But I have made the two calls (create and get) completely synchronous here https://github.com/eclipse/smarthome/pull/1460. I hope it resolves the issue.

**Comment by maggu2810** [comment]
Thanks @aounhaider1. It makes sense to keep it synchronous.
If there is still some wired behaviour I will reopen this one.
