### ISSUE TITLE
ConfigDispatcher overwrites any properties set in ConfigAdmin for a service.pid

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1438]
If a cfg file is processed by ConfigDispatcher, where at least one property is specified, any other property that might already be set in the config admin for this service.pid is lost.

**Comment by kaikreuzer** [comment]
@lolodomo: I have reformulated this issue, since the extension mgmt is not an ESH feature, but a specific OH2 service, but the problem is actually a general one that needs to be solved.
