### ISSUE TITLE
Include Legacy 1.x Bindings with no effect without enabling access to remote repositories

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1439]
That could be obvious for developer but certainly not for the final user.
I dscovered that if I want to see in Paper UI 1.x bindings, I have first to enable "Include Legacy 1.x Bindings" in the extension management service. Ok for that. But to really see 1.x bindings, you have to enable another setting named "Access Remote Repositories". If this setting is required to have access to 1.x bindings, I thing it should be automatically enabled when you enable "include 1.x bindings".

**Comment by kaikreuzer** [comment]
Note that this is not an ESH feature, this is purely OH related, so I am closing this here.

(Side note: I actually tried it the way you suggest, but this approach also has problems: You would not be able to ever go back to "offline" mode again, as long as you use legacy addons, althrough you only need to switch to "online" whenever you want to install or update something)
