### ISSUE TITLE
Exposing jsonpath libs

### ISSUE THREAD

**Issue by tavalin** [eclipse/smarthome#1445]
I'm working on a binding downstream in OH that needs to use the jsonpath libraries which are already used in the ESH jsonpath transformation bundle.  This issue is to discuss the best way to expose those libraries so that they are contained in one place and other bundles don't have to include them in their bundle.

**Comment by maggu2810** [comment]
I would prefer to use some separate OSGi bundles, so we do not have stuff multiple times bundled in different ones.

I looked at the lib directory of transform.jsonpath and see the asm package.
It contains net.minidev.asm and org.objectweb.asm, but only the first package is named in the about.html. The ow2 asm package is perhaps used by net.minidev.asm and are bundled because of this, too. But IMHO we should not (and perhaps must not) bundle something without naming it in the about.html.

@clinique Have you created the asm-1.0.2 jar or has this been taken from somewhere else?

One side note: In e.g. OH2 the org.objectweb.asm bundle is already present as separate bundle and the classes exist now twice.

@kaikreuzer As the three JAR files "json-smart-2.2", "asm-1.0.2" and "json-path-2.0.0" are part of the lib folder and so part of the ESH repo, the usage should already be granted. Correct?
What needs to be done, to split them off?

There are already non-Eclipse p2 repositories part of the target platform.
Can we create a p2 repo somewhere (github.io?) that contains such third party libraries?

**Comment by kaikreuzer** [comment]
> the usage should already be granted. Correct?

Correct.

> Can we create a p2 repo somewhere (github.io?) that contains such third party libraries?

Shall we move that into a separate branch in our ESH repo? For all 3rd party libs for which there are CQs and we have full approval, I think we should also host them directly within the project.

**Comment by clinique** [comment]
@maggu2810  AFAIR I directly took the jar from Maven ([http://mvnrepository.com/artifact/net.minidev/asm/1.0.2](url)

**Comment by maggu2810** [comment]
@kaikreuzer 
If it is a separate branch of the main repo, it will checked out with the whole history all the time. I would prefer to create a separate one that history could be cut off some time. Or using a non-historicized location at all.
Can you have a look at git@github.com:maggu2810/org.eclipse.smarthome.thirdpartyrepo.git and run p2:site on a cloned location? This will generate a p2 repo in target/repository with the declared artifacts. (We could consume p2 locations, maven artifacts, etc. see https://github.com/reficio/p2-maven-plugin).
So we can easily create a p2 repo with all necessary bundles and host the generated one somewhere (the generator pom could be part of the official ESH tree).

@clinique 
It seems that the creator of that bundle also packages this one http://mvnrepository.com/artifact/org.ow2.asm/asm/5.0.2 (version needs to be checked) into their own bundle. The about.html refers to their sources and the binary contains also other ones. IANAL but perhaps this need to be documented anywhere.

**Comment by maggu2810** [comment]
@kaikreuzer 
If we name the branch "gh-pages" (see https://github.com/maggu2810/org.eclipse.smarthome.thirdpartyrepo/tree/gh-pages), we can run a simply 
```
mvn clean p2:site
git add .
git commit -s -m "..."
```
for a new p2 site.

Use a p2 repository browser and point it to: http://maggu2810.github.io/org.eclipse.smarthome.thirdpartyrepo/target/repository

WDYT?

**Comment by kaikreuzer** [comment]
Yes, I am using a gh-pages branch for jUPnP and jmDNS, too.
But we can do that within the main ESH repo, can't we? If we do not want to keep the history, we can at any time force push an update of that branch.

**Comment by maggu2810** [comment]
Sure, we can.

I just wanted to use use another official repository to reduce the traffic (don't know if it is complicated to get another official one). A fetch of the repository will download the gh-pages branch to.
So we will download all the jars if we fetch the repository.
If we build ESH using the Eclipse IDE or Maven the JARs are downloaded from the p2 site again.
So the JARs are downloaded at least twice.
If someone does not to change the p2 repo, I do not see any reason why he needs to clone all that stuff (normally you fetch all branches of a repo).

But normally I do not need to worry about that traffic myself. So, if we can live with this, it is okay for me, too.

How do you create your p2 repos? What do you think about using the p2-maven-plugin?

**Comment by kaikreuzer** [comment]
> So we will download all the jars if we fetch the repository.

That's right, but this is currently the case as well - so we do not get worse.
If our p2 repo grows in size, we can see to setup a separate repo - but for now, I would go the easy way with the repo we have in place.

> How do you create your p2 repos? What do you think about using the p2-maven-plugin?

Never used this - I am so far using Tycho (see [here](https://github.com/jupnp/jupnp/blob/master/distribution/pom.xml)). But the p2-maven-plugin sounds good to me, so feel free if you have good experiences with it.

**Comment by tavalin** [comment]
Before this is closed off can someone provide a quick explanation of what is/will be needed to use the jsonpath libs in a bundle?

**Comment by maggu2810** [comment]
If #1450 is merged, the bundles are part of the target platform and the Eclipse IDE will handle it themselves (while developing).
If you need it at runtime in some OSGi environment the respective bundles needs to be available at runtime.

**Comment by kaikreuzer** [comment]
Or to put it simple for a binding developer: Add an import-package in your manifest and that's it :-)

**Comment by maggu2810** [comment]
With the latest merges this one is solved now. Correct?

**Comment by kaikreuzer** [comment]
You should also merge https://github.com/openhab/openhab-distro/pull/205, so that @tavalin has a chance to adjust his binding after re-resolving the new target platform of OH2 :-)

**Comment by maggu2810** [comment]
I have seen the PR but missed that it waits for merging.

**Comment by kaikreuzer** [comment]
But I agree that this issue can now be closed - thanks!
