### ISSUE TITLE
 REST api support to "create Group Switch/Item" and to configure Group Items "properties like - function , type , members".

### ISSUE THREAD

**Issue by smartalyse** [eclipse/smarthome#1465]
# **Description** :

There should be a REST api support to "create Group Switch/Item" and to configure Group Items "properties like - function , type , members".

function: Groups functions ( Currently default is "equality" ) , this will be customized group function name.  

---

In current implementation , I can add group switch using following item file. group switch properties like "function" , "State" , "Type" could be assigned through item file.
## Example Item file

group:switch:OR(ON,OFF) zigbeegroup [ "zigbeegroup" ]

switch Sw1 "s1 sw" (zigbeegroup) { channel="lzigbee:switch:OnOFF" }
switch Sw2 "s2 sw" (zigbeegroup) { channel="zigbee:switch:OnOFF" }
switch Sw3 "s3 sw" (zigbeegroup) { channel="zigbee:switch:OnOFF" }

---

There should be a  REST api to create the group switch like above one.

**Comment by triller-telekom** [comment]
This is possible since [a while](https://github.com/reitermarkus/smarthome/commit/8fa8889501258fdf0ee7f07be96952420f0cbd32)

Just `PUT` this
```
{
  "type": "Group",
  "name": "TestSwithGroup",
  "label": "MySwitchGroup",
  "groupType": "Switch",
  "function": { 
    "name": "OR",
    "params": ['ON', 'OFF']
  }
}
```

onto `http://localhost:8080/rest/items/TestSwitchGroup` to create the group `TestSwitchGroup`.

@kaikreuzer @sjka This issue can be closed.
