### ISSUE TITLE
Paper UI: switch to reduced channel list after linking a channel

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1474]
I click n "Show more" to get the full list of channels. Then I link a channel to an item. "Channle linked" is dispayed and immediately my list of channels is reduced. "Show less" is still displayed while the list is still reduced.
I have to click on "Show less" then "Show more" to get again my full list of channels.
Linking a channel to an item should not change the list of channels, either reduced or full.

**Comment by kaikreuzer** [comment]
As all this code changes dramatically with #1288, I would suggest to close it - if after merging #1288 there are still problems, please re-open.
