### ISSUE TITLE
New Categories - Proposal

### ISSUE THREAD

**Issue by FrankZimmer** [eclipse/smarthome#1475]
I 'dd like to start a discussion for new categories! Feel free to add yur ideas here

My Proposal
- NOISE --> e.g. Netatmo *db
- TILT
- SOIL MOIST / MOISTURE

**Comment by triller-telekom** [comment]
I have included Noise and Moisture in #3629 but I don't know what you understand by the term "Tilt".

**Comment by triller-telekom** [comment]
MOISTURE and NOISE are now included with #3629, see [here](https://www.eclipse.org/smarthome/documentation/concepts/categories.html).

@FrankZimmer can you please explain what you mean by "TILT"? if it is not important anymore, please close this issue. Thanks.

**Comment by FrankZimmer** [comment]
Thanks to @triller-telekom
