### ISSUE TITLE
"Integers" sent in configuration now include scale

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1477]
If I send a configuration value of -2, it is now received as a BigDecimal of -2.0, which is not equal to -2.  This seems to have changed recently (in the last week or two) - prior to this it was received without the scale setting and the change broke a load of comparisons in ZWave.

Given that comparisons of BigDecimal checks the scale, it's annoying that integer config types are not marshalled without the scale.

Maybe this is unavoidable, in which case feel free to close, but I thought I'd raise it in case others also experience problems with this change.

**Comment by kaikreuzer** [comment]
Can you confirm that the config value is declared as an integer and not as a decimal?
I would have thought that [this test](https://github.com/eclipse/smarthome/pull/1423/files#diff-5e38bc0bc2283f77cf75e3a4d2bb168aR52) covers your use case - I fully agree that if you compare it against -2, it should be true.
@sjka Could you have a look, please?

**Comment by cdjackson** [comment]
This is the definition. The actual number is -232323 as you can see below. This has changed in the past week or so.

```
            <parameter name="controller_exclude" type="integer" groupName="actions">
                <label>Exclude Devices</label>
                <description>Puts the controller into Exclusion mode.</description>
                <advanced>true</advanced>
                <default>0</default>
                <options>
                    <option value="-232323">send</option>
                </options>
            </parameter>
```

**Comment by maggu2810** [comment]
Don't know which commit and why the scale has been added, just about the comparison:
If the scale does not matter for the one that consumes the BigDecimal, I would prefer to use compareTo instead of equal.

**Comment by maggu2810** [comment]
Don't know which commit and why the scale has been added, just about the comparison:
If the scale does not matter for the one that consumes the BigDecimal, I would prefer to use compareTo instead of equal. Just if this helps you in some way.
Last but not least, we should not add a scale.

**Comment by kaikreuzer** [comment]
>  I would prefer to use compareTo instead of equal

That's a very valid point!

> Last but not least, we should not add a scale.

What exactly are the reasons against it? It seem to be a valuable piece of information.

**Comment by maggu2810** [comment]
>> Last but not least, we should not add a scale.

> What exactly are the reasons against it? It seem to be a valuable piece of information.

I have meant "we should not increase the scale". If the user sets "2" we should not set the BigDecimal to "2.0". There is no reason to increase the scale.

**Comment by kaikreuzer** [comment]
> There is no reason to increase the scale.

Yes, fully agree.

**Comment by sjka** [comment]
I have created a binding with a Thing's config param like you pasted above. When I now configure it via the PaperUI, this is what I see:

the paperui sends a request with payload

    {controller_exclude: -232323}

the ThingResource.updateConfguration() receives in configurationParameters

    {controller_exclude=-232323.0} //Double

and turns it into via normalizeConfiguration(configurationParameters, thing.getThingTypeUID()) into

    {controller_exclude=-232323} //BigDecimal

So, apparently the paperui sends it in a correct format, but the jersey stack somehow converts it into a Double. To be honest, I have no idea yet why that is. However, the normalization actually (correctly) "fixes" the wrong double and turns it into a BigDecimal with a scale of zero (which is what we want for integers).

@cdjackson what is the actual issue now? That the request initially receives a double? Or is there a place where no normalization happens so it stays a double? Please help me to understand what's going on...

PS: While analyzing this, I saw that neither bindings nor service configurations were using the normalization yet. For those, I created #1737. However, it looks like we are talking about Thing configuration here, correct?

**Comment by cdjackson** [comment]
@sjka sorry - I missed your comment.

The issue is still there - as I said in the initial report, this can be worked around, it just seems wrong that when I define something as an Integer in the configuration, that I get a Decimal (ie it arrives with decimals).

I just confirmed that if I set a value in HABmin, it is sent as (for example) 1800, but when it is passed into the thing handler ```handleConfigurationUpdate```, it is 1800.0. Given that I expected this to be an Integer, I use ```Integer.parseInt```, and this throws an exception.

This never used to be the case - as reported above, this changed in early May.

If the decision is that all data is now passed as BigDecimal rather than Integer, then we should make that clear in the documentation - I don't overly mind either way, but to me it doesn't seem correct when I define configuration as Integer.

**Comment by cdjackson** [comment]
@sjka said ->

> However, the normalization actually (correctly) "fixes" the wrong double and turns it into a BigDecimal with a scale of zero (which is what we want for integers

So this is a change from what was previously done in the config - previously we received Integers. If this is now confirmed that we will always get BigDecimal (which I would agree is more consistent with the configuration store) then I'm fine with this.

I don't however agree that the normalisation is working in this instance, since I still see the scale and ```.0``` on the end of the number.

**Comment by triller-telekom** [comment]
I have just created a `thing` with an integer parameter like this:
```
<parameter name="interval" type="integer" min="1" max="86400">
            <label>Integer</label>
            <description>Integer value.</description>
            <default>23</default>
</parameter>
```

Inside `public void handleConfigurationUpdate(Map<String, Object> configurationParameters) ` of my `ThingHandler` the parameter is represented as a `BigDecimal` and I see `23` with `scale 0`. There is no `23.0` here. is that what you were expecting and this bug can be closed @cdjackson ?

**Comment by cdjackson** [comment]
Yes, if it's now returning no scale, then this is what I would expect. I've not looked at this for a long time so not sure when this was fixed, but if it's fixed, then we can close - thanks.
