### ISSUE TITLE
Existing Hue Bridge stays in UNINITIALIZED (HANDLER_CONFIGURATION_PENDING)

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#1480]
With #1156, a new required configuration parameter was introduced, leading to existing Hue Bridges to stay in UNINITIALIZED (HANDLER_CONFIGURATION_PENDING) state.

My suggestion would be to fill missing required parametes with defaults (if there are defaults at all...) in ThingManager.isInitializable() in the same way as done in ThingFactoryHelper.applyDefaultConfiguration() for newly created things. In that way we could mitigate such migration cases in future too.

**Comment by maggu2810** [comment]
Cannot have a look at the code at the moment, so I don't know in which function this should be placed, but to use the default if there is no value sets, sounds good to me.

**Comment by kaikreuzer** [comment]
+1, sounds like a valid solution for the problem.

**Comment by sbussweiler** [comment]
Please have a look at #1482.
