### ISSUE TITLE
Offer "create item" option when creating a new link

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1490]
When in "advanced" mode, linking a channel shows a list of available items. This list should be extended to also offer the possibility to directly create a new item.
This will probably require https://github.com/eclipse/smarthome/issues/1488.

**Comment by aounhaider1** [comment]
Should the channel be automatically linked to newly created item or should the new item be just shown in the list of items?

**Comment by kaikreuzer** [comment]
This depends on how you are able to design the user flow - in general, the link should be created at the end (after the item has been created), because this was the original intention of the user here.
