### ISSUE TITLE
advanced attribute for channel-group-type ignored by Paper UI

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1497]
Could we have an attribute "advanced" for channel group type that will lead to masking/unmasking the channel group in Paper UI ?

**Comment by lolodomo** [comment]
Looking at the XSD it seems that it is already available.
To be checked whether Paper UI considers or not this attribute correctly.

**Comment by lolodomo** [comment]
I can confirm 2 things:
- you can define an "advanced" attribute for a channel-group-type
- this attribute is ignored by Papar UI

**Comment by lolodomo** [comment]
Can someone points the source file in charge of displaying the channels in Paper UI ?

**Comment by lolodomo** [comment]
The issue could be in the following JavaScript function that does not consider the advanced property on the group itself:
https://github.com/eclipse/smarthome/blob/e04e30e682d60c14f311a642fa2f61eaea31f36f/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js#L439

**Comment by lolodomo** [comment]
@resetnow : could you explain how is built $scope.thingType because when this function is called
https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js#L496
thingType.channelGroups[i].advanced inside the function seems to be always false even if advanced was set to true on the channel group type.

Additionally, the fuinction checkAdvance is wrong because it does not care about the flag on the channel group type but only the flag on the channel types.
https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.configuration.js#L502

**Comment by lolodomo** [comment]
Finally, the reason was that advanced was missing in ChannelGroupDefinitionDTO. Adding it makes my Paper UI fix working.

Just remains now to fix the function "checkAdvance".

**Comment by resetnow** [comment]
@lolodomo sorry, I didn't write any of PaperUI code so I'm not quite familiar with it.

**Comment by lolodomo** [comment]
Sorry for the mismatch. How is the main author of Paper UI ?

**Comment by resetnow** [comment]
Check git blame

**Comment by maggu2810** [comment]
The main author is @aounhaider1 
As @resetnow already stated a `blame` should manifest it. Or a simply `git log extensions/ui/org.eclipse.smarthome.ui.paper/`

**Comment by lolodomo** [comment]
I close this issue because the general wish is to consider only the advanced flag on channel types (not channel group types).
