### ISSUE TITLE
mDNS discovery not worling ?

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1501]
I am trying to implement a mDNS discovery service for the Freebox binding.
In Eclipse IDE, when running openHAB; I see no call to my createResult method but I can see this error:
```
2016-05-11 12:39:50.763 [DEBUG] [s.i.t.m.internal.MDNSActivator:27   ] - mDNS service has been started.
osgi> 
!ENTRY org.eclipse.equinox.ds 1 0 2016-05-11 12:39:50.777
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.io.transport.mdns. The reference is: Reference[name = MDNSClient, interface = org.eclipse.smarthome.io.transport.mdns.MDNSClient, policy = dynamic, cardinality = 0..1, target = null, bind = setMDNSClient, unbind = unsetMDNSClient]
2016-05-11 12:39:51.047 [DEBUG] [.i.t.m.internal.MDNSClientImpl:37   ] - mDNS service has been started
```
Is it a bug and a reason why my class is not called ?

Except declaring my class FreeboxServerDiscoveryParticipant that implements MDNSDiscoveryParticipant, shall I instanciate or register something ?

**Comment by tavalin** [comment]
Did you create the xml file to register your discovery service? See [here ](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/OSGI-INF/ZonePlayerDiscovery.xml)for an example.

**Comment by lolodomo** [comment]
Thank you a lot, I forgot that step.
That is clearly something to mention in the Eclipse Smarthome documentation: http://www.eclipse.org/smarthome/documentation/development/bindings/discovery-services.html

**Comment by kaikreuzer** [comment]
Well, it is mentioned in the very first line there: "and register it as an OSGi service"
For a tutorial, I would agree to better describe step by step on how to get there.
