### ISSUE TITLE
REST API ui missing /rest from uri

### ISSUE THREAD

**Issue by xsnrg** [eclipse/smarthome#1515]
In the last few builds, the UI for the REST interface has been missing /rest from any of the "try it" samples.  This can be seen by going to any of the endpoints in a browser, and looking at the request.  If you execute using the button, you will get a 404.  

The REST API itself appears to be okay.  Hitting the proper URL manually works.

Additionally, if you do this test from localhost, you will only see /rest missing, and everything else appears normal.  If you hit the URL remotely however, the landing page has an error button at the bottom of the page that when expanded looks like the below, mentioning unable to open swagger.json.

```
{
    "schemaValidationMessages": 
[
        {
            "level": "error",
            "message": "Can't read from file https://<hostname>:8443/rest/swagger.json"
        }
    ]
}
```

Discussion here:  https://community.openhab.org/t/rest-api-not-running/10618

**Comment by maggu2810** [comment]
Should IMHO be already solved with #1504
Have you tried the recent ESH code base?

**Comment by xsnrg** [comment]
Great news!   Then we just need @kaikreuzer  to push a current stable ESH build to OH2 and we can close this after the nightly OH2 build.  Not sure how I missed #1504 .  I did a search as to try to not duplicate

**Comment by maggu2810** [comment]
I assume the issue is already closed for ESH but perhaps open for the openHAB-distro.
But if you want to ensure that my changes are working, I am happy to wait until you confirm that it is working.
As I don't know if @kaikreuzer has a special plan for a stable builds (could I break OH if I trigger one), I will wait for him.

**Comment by kaikreuzer** [comment]
I usually trigger stable builds only, when I am sure that I can be at the computer a few hours later to do emergency fixes if necessary - I now just triggered a stable build :-)
Next nightly openhab distro should hence contain it.

**Comment by xsnrg** [comment]
Thanks guys.  I will verify it tonight after the OH nightly and close this ticket if it looks good.

**Comment by xsnrg** [comment]
Looks much better, thanks!
