### ISSUE TITLE
Eclipse SmartHome system locale

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1516]
If no locale is explicitly set (e.g. REST API and internally functions) the Eclipse SmartHome framework is using the system settings.

See also: http://www.oracle.com/technetwork/articles/javase/locale-140624.html#using

Should the framework offer functions getLanguage, getCountry and getVariant that are using esh.language, esh.country and esh.variant properties that fallback to user.language, user.country, and user.variant system properties if unset?
Should we use a "simple" setDefault to set the system locale?
The properties could be set and stored by the configuration admin or the ESH cfg mechanism.
org.eclipse.smarthome.core.i18n.i18nprovider:esh.language=en
org.eclipse.smarthome.core.i18n.i18nprovider:esh.country=US

**Comment by maggu2810** [comment]
With the correct config description in the ESH-INF directory this should be possible to set e.g. in the Paper UI, too. Correct?

**Comment by kaikreuzer** [comment]
Yes, correct.

**Comment by kaikreuzer** [comment]
Is your use case to be able to change the default locale during runtime and through a UI?
If not, the `-Duser.language=xx -Duser.country=XX` would imho be just fine.

Even if you require to change it at runtime, why not simple use `Locale.setDefault()`?

**Comment by maggu2810** [comment]
Yes, I would prefer to make it changeable during runtime

Locale.setDefault -Duser... are JVM wide settings. As a collection of bundles and not a product, I would prefer there is no need to set the locale globally for the whole OSGi runtime.
If someone wants to use a global setting that affects all bundles, this would be fine.
But I see no reason, why we should affect all the other bundles that people could run in that container, too.

We need to store the value persistent, so config admin is a good catch (IMHO).
Using setDefault or my proposal doesn't make a bit different, but the example (#1519) allows a separate language for the ESH framework that leaves other stuff untouched.

**Comment by kaikreuzer** [comment]
Ok, if you have the requirement to have another level of locale definition between system and ui, I am fine with your approach. For me personally, the system (or rather jvm) locale would be enough.
