### ISSUE TITLE
Missing support for fragment bundles in org.eclipse.smarthome.core.internal.i18n.ResourceBundleTracker

### ISSUE THREAD

**Issue by adimova** [eclipse/smarthome#1527]
Currently the tracker does not check if a bundle is a fragment or a host. A resource packed in a fragment bundle can also be visible through it's host. As a result:
- if the fragment is installed before the host, a single resource will be tracked twice, and associated both with the host and the fragment
- if the fragment is installed after the host, the resource will be tracked once, but will be associated only with the fragment - and cannot be used by the classes of the host.

**Comment by kaikreuzer** [comment]
Would it be possible to cover this by tests e.g. in https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/internal/i18n/I18nProviderOSGiTest.groovy?

**Comment by adimova** [comment]
Solved with #1607
