### ISSUE TITLE
Registration of multiple ManagedProvider services can break the AbsractRegistry logic

### ISSUE THREAD

**Issue by adimova** [eclipse/smarthome#1528]
The current implementation of org.eclipse.smarthome.core.common.registry.AbstractRegistry.addProvider method expects that there will be a single ManagedProvider. However, there is no way to enforce that: 
- a Provider service does not have to be registered with the ManagedProvider objectClass, so ServicePermission-s cannot be used.
- The Provider and ManagedProvider interfaces are in the same package, so PackagePermission-s cannot be used either.

As a result, anyone that has permissions to implement and register a Provider service, can also implement the ManagedProvider interface, and replace the current ManagedProvider in the AbstractRegistry.

**Comment by danchom** [comment]
As I remember we have defined to have only one managed provider. If they are more then one, the first one wins.

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/eclipse/smarthome/pull/1532
