### ISSUE TITLE
[BUG] digitalSTROM Binding : Rollershutters showing wrong position

### ISSUE THREAD

**Issue by hmerk** [eclipse/smarthome#1530]
@MichaelOchel 

Rollershutters are showing 0% if completely closed and 100% if open.
This behaviour leads to wrong usage of icons in Basic- and Classi-UI.

To proof, just add [%s] to a Rollershutter irem label in .items file.

**Comment by msiegele** [comment]
Ok, thanks. We will have a look at it in the next few days.

Michael Ochel and Matthias Siegele
