### ISSUE TITLE
[BUG] Discovered Things don't come online if defined via .items file

### ISSUE THREAD

**Issue by hmerk** [eclipse/smarthome#1540]
I tried a fresh install of openHAB2-SNAPSHOT305 and even verified within my IDE (updated with git pull in every repo a couple of minutes ago):

When defining things in the .things file like
**_sonos:PLAY1:RINCON_B8E937BDB4D401400
wemo:insight:Insight-1_0-221443K1200202
Bridge digitalstrom:dssBridge:dssBridge1 [ ipAddress="dss.local.",  userName=”dssadmin”, password=“dssadmin”, sensorDataUpdateIntervall=”180”]_**
these things never come online. IDE log-file e.g. says
_**2016-05-19 15:34:59.859 [DEBUG] [.e.s.b.s.i.SonosHandlerFactory:79   ] - Creating a ZonePlayerHandler for thing 'sonos:PLAY1:RINCON_B8E937BDB4D401400' with UDN 'null'**_

Using PaperUI inbox for thing-creation works smoothly, things come online straight away.

So I guess, this happens to all bindings using UPnP or MDNS discovery.

**Comment by kaikreuzer** [comment]
This works for me. I think the problem is that you have incomplete thing definitions.

Your log says "Creating a ZonePlayerHandler for thing 'sonos:PLAY1:RINCON_B8E937BDB4D401400' with UDN 'null'", which points at the problem: You need to define the config parameter "udn" - this is NOT derived from the ThingUID, which you might have thought. So have a try with this definition instead:

```
sonos:PLAY1:mySpeaker [ udn="RINCON_B8E937BDB4D401400" ]
```

**Comment by hmerk** [comment]
Ups, sorry for that, I should have read the instructions of SONOS binding better.
It is working here as well.

So there still is an issue within digitalSTROM binding, cause it's log says 
_**2016-05-19 16:35:08.540 [INFO ] [nt.ThingStatusInfoChangedEvent:43   ] - 'digitalstrom:dssBridge:303505d7f8001820000003f4' changed from OFFLINE (CONFIGURATION_ERROR): No username or password is set to generate Application-Token. Please set user name and password or Application-Token. to UNINITIALIZED (HANDLER_INITIALIZING_ERROR)**_
but this entries exist, as you can see in my firts post.

I will close this issue and open a new one for the digitalSTROM binding.

**Comment by hmerk** [comment]
@Kai,
OMG, that was a tricky one. digitalstromBinding is working was well, Just a typo in the documentation
Bridge digitalstrom:dssBridge:dssBridge1 [ ipAddress=**"**dss.local.**"**, userName=**”**dssadmin**”**, password=**“**dssadmin**”**, sensorDataUpdateIntervall=**”**180**”**]
I did not see the difference between **"** and **”**
That's why it just said username and password missing....

**Comment by kaikreuzer** [comment]
Glad to hear that it's working!
FTR, I have updated the Sonos documentation as well, see https://github.com/eclipse/smarthome/pull/1543/files

**Comment by hmerk** [comment]
Thanks,
created a PR for digitalSTROM binding and will create another one for WeMo Binding as well, as I had some mistakes in the documentation there.
