### ISSUE TITLE
Discovery result: avoid flooding the logs

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1548]
Would you like to consider replacing this INFO log by a DEBUG log ?
This could avoid flooding the logs.
```
13:16:55.892 [INFO ] [smarthome.event.InboxUpdatedEvent   ] - Discovery Result with UID 'freebox:net_interface:fb:fe80__4c77_d956_9a9b_38e5' has been updated.
```

**Comment by kaikreuzer** [comment]
No, we are logging all events the same way and thus they all are INFO level.
But it is easy to filter those out in your logging configuration - I just did that for openHAB, see https://github.com/openhab/openhab-distro/pull/212.
