### ISSUE TITLE
Website is not available when started in eclipse

### ISSUE THREAD

**Issue by ChristophRathfelder** [eclipse/smarthome#1551]
After setting up the IDE following the instructions documeted on the getting started guide shows loading the different bindings within the console window. Anyhow opening the website http://localhost:8080 leads to an 404 error page: 

HTTP ERROR: 404
Problem accessing /. Reason: 
    ProxyServlet: /
Powered by Jetty:// 

I did not receive any error messages, such for me it is unclear how to acceess the OpenHab/Smart Home WebUI.

**Comment by maggu2810** [comment]
There is no redirection configured in the ESH configuration.
If you want to visit the Paper UI you have to use the correct URL:
Can you try: http://127.0.0.1:8080/ui/index.html

**Comment by ChristophRathfelder** [comment]
I still can not access it. Enterting the URL provided by you ends up in the following Jetty 404 error:

Problem accessing /ui/index.html. Reason:
    ProxyServlet: /ui/index.html

Since it is a jetty error, I assume the jetty bundle is started, so it is not a problem of accessing the Web server.
Might it be a problem of Windows and Mac?

**Comment by maggu2810** [comment]
@ChristophRathfelder Does your path of your cloned repo (the path you used to install the IDE using the Eclipse Installer) contains whitespaces or any other special characters?

It should work with the default launch configuration.

Here a log from my system:
https://gist.github.com/maggu2810/89477dd03fcf10776e2c64484c79da9a

**Comment by maggu2810** [comment]
I assume you missed to start a Maven build (command line).
This is necessary for the Paper UI as it fetches a lot of third-party dependencies using Maven only.

**Comment by ChristophRathfelder** [comment]
I tried to run maven from the command line with different targets.
After several tries mvn compile worked.
In Eclipse several projects showed errors, so I need to perform a clean.
After that the Smart Home Runtime could be started. An also mapping the paperUI to /ui was listet, see the attached log.
Anyhow Openiing http://127.0.0.1:8080/ui/index.html from internal and external web browser still results in a 404 error of jetty.

The basicUI (http://127.0.0.1:8080/basicui/app) can be accessed.




[log.txt](https://github.com/eclipse/smarthome/files/302443/log.txt)
