### ISSUE TITLE
Show Thing detail view after creation

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1557]
When creating a new Thing (either manually or through inbox approval), the Paper UI currently shows a toast "Thing added SHOW THING".

From my experience, you almost always click on "SHOW THING" (if you are fast enough), so I tend to say that it would make sense to automatically switch to the thing detail page.

What we might need is a better "back" button on that page, though. It only shows the "X" at the top right, which rather implies a "cancel" action. Maybe we could have a "left arrow" besides the round "edit" button? What do you think?

**Comment by aounhaider1** [comment]
But where should the user be redirected when back button is pressed? If we navigate to last page then the thing creation page will be opened again which does not seem correct.

**Comment by maggu2810** [comment]
> From my experience, you almost always click on "SHOW THING" (if you are fast enough), so I tend to say that it would make sense to automatically switch to the thing detail page.

IIRC some time before a redirect has been used after a thing has been created.
I am happy that the page is not changed anymore and I can add multiple things.
I don't like that the "new thing" page is opened automatically.

**Comment by maggu2810** [comment]
But perhaps my usage differs from the most other ones :wink:

**Comment by aounhaider1** [comment]
Maybe we can increase the time of the toast in this specific case, and also, is it possible to know the order of creation of things? Because if we have a lot things then it makes sense to show user the things that are created recently on top?

**Comment by kaikreuzer** [comment]
> But where should the user be redirected when back button is pressed? 

It should imho just do the very same thing as the "x" at the top right corner (which can then probably be removed).

> I don't like that the "new thing" page is opened automatically.

Hm, ok, so we need to further discuss this. What I have seen is that newbies do not see the toast and then wonder that nothing really happens - especially that they cannot continue to select channels they want to use etc. Also for myself when doing demos it is awkward  having to quickly navigate to the toast to go to the created thing.

If the regular use case is rather "bulk operations" where you approve/create many things in a row, I agree that this can be tedious. Is there any good UX concept for solving this?

**Comment by maggu2810** [comment]
The current situation to stay on inbox/search is not optimal.

Normally I go to configuration, things.
There I see the list of available things.
Then I press on "+" and add the thing.

My personal preference is to return to the list of things after the thing has been added.
There I see the list of things, see the new thing, can press on the thing to configure it or I can add a new one.

But perhaps you are right and normally you add a thing, configure it, add another thing.
I add a thing, another thing, another thing and after all are added I start to configure them.

WDYT about return to the list of things and highlight the newly added one and show the highlighted ones on the top of the list.
But there is no concept about that highlighting ATM.

**Comment by kaikreuzer** [comment]
> WDYT about return to the list of things 

Sounds like a good compromise to me!

> highlight the newly added one

@aounhaider1 Do you have any good idea/suggestion on how this could be achieved?

**Comment by aounhaider1** [comment]
We can store the newly added things in the local storage and remove them when user clicks on them. But that means that if a user has the same page open on two different devices he will see two different lists.

**Comment by kaikreuzer** [comment]
Sounds fine to me, I would even expect that these are different lists, as he only added the thing in the one browser. How exactly would the "highlighting" look like? Some kind of "glowing" effect would be cool ;-)

**Comment by aounhaider1** [comment]
Should same behaviour be applied when a thing is approved from inbox?

**Comment by maggu2810** [comment]
:+1:

**Comment by kaikreuzer** [comment]
This has meanwhile been implemented.
The inbox behavior has not changed - it stays on the inbox after approval. I think this is ok as it is.
