### ISSUE TITLE
RuleRegistry contains two entries after creating a rule based on template

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1561]
The "create rule by template" feature is broken - the rule registry contains two entries with the same ruleid afterwards which causes all kinds of problems.

This bug has been introduced by https://github.com/eclipse/smarthome/pull/1500 - @danchom could you please have a look?

**Comment by danchom** [comment]
Yes, I will debug it.

**Comment by danchom** [comment]
Fixed by PR #1579
