### ISSUE TITLE
System channel type: low battery

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1578]
I have used a custom battery low channel type until now and want to move to the system channel type one (system.low-battery).
My custom one and the system provided one differs in the state description.
The system provided one does not set a state description at all.
I set the read-only flag to true for the "low battery" channel.

I assume the low-battery flag is set by the device and should not be changeable by an UI etc.
Is there any reason to not set the state description with read-only indication?

**Comment by maggu2810** [comment]
@kaikreuzer If you are fine that the low battery system channel is read only, I will create a PR for that. But if you are against that, then I do not need to do any implementation.

**Comment by kaikreuzer** [comment]
Yes, I am absolutely fine with defining it as read-only!

**Comment by markusjw** [comment]
Wouldn't this make sense for the other two system channels as well?

**Comment by maggu2810** [comment]
I think so :wink:

**Comment by kaikreuzer** [comment]
Me too :-)
