### ISSUE TITLE
Strange xml example in thing-types documentation

### ISSUE THREAD

**Issue by chrisschauer** [eclipse/smarthome#1580]
I'm wondering about the documentation on:
https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/bindings/thing-definition.md

I don't understand the following line:
```
    <state min="12" max="30" step="0.5" pattern="%d °C" readOnly="false">
```

There is a step with 0.5 and a pattern defined "%d" (decimal integer). I find this a little confusing because pattern with %d returns only a integer.

I think it should work with:

```
    <state min="12" max="30" step="0.5" pattern="%.1f °C" readOnly="false">
```

**Comment by maggu2810** [comment]
IMHO it should work with both, but the second one makes more sense.
Can you fix this?

**Comment by kaikreuzer** [comment]
Sounds right, so why don't you create a PR for it?

**Comment by chrisschauer** [comment]
i'm just creating the PR :-)
