### ISSUE TITLE
Rule trigger / action / condition all mixed up

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1590]
If I use the Paper UI to create a trigger, condition and action all module types are shown.

![rule-action](https://cloud.githubusercontent.com/assets/204670/15703901/23ead8e4-27e8-11e6-9af5-d5c484b320c7.png)

![rule-condition](https://cloud.githubusercontent.com/assets/204670/15703908/26135d80-27e8-11e6-8f1b-347a86f9858a.png)

![rule-trigger](https://cloud.githubusercontent.com/assets/204670/15703909/29034370-27e8-11e6-9a9f-acafbef442e8.png)

**Comment by maggu2810** [comment]
After switching between different branches I want to response of [http://localhost:8080/rest/module-types?type=action](http://localhost:8080/rest/module-types?type=action) to see if it is a bug of the Paper UI or another one.
Now it seems to be working (also in the Paper UI).

Don't know what has been wrong previously.

**Comment by maggu2810** [comment]
This bug has been introduced by 3dd817ea4ec37880b6315d141b520a5d068b7e49 (#1586).

**Comment by aounhaider1** [comment]
I have a question about ModuleTypes, is it possible to get the type of module from ModuleTypes? e.g. I can request modules of specific types by specifying type in the request but can I separate the modules based on the type field after I get all the modules ?

**Comment by maggu2810** [comment]
I am interested to.
I used the REST API to get a list of all modules and don't find a way to sort them by type.
I think the module type should be added.
Or is there any use case to get all modules (without limit to a special type) if we don't know the type of an object of the result collection?

**Comment by kaikreuzer** [comment]
Not yet possible, but tbd, see point 1 in https://github.com/eclipse/smarthome/issues/1483.
@danchom Can you already estimate when you will work on this?

**Comment by maggu2810** [comment]
How is this related to point 1.

In both cases we can build a list that contains all module types (triggers, collections, actions). The point is that the returned collection misses the information about the type.
Can't this be solved by using a DTO that contains all the current information and a field (module-type) that contains an enum value (ACTION, TRIGGER, CONDITION)?

**Comment by kaikreuzer** [comment]
> How is this related to point 1.

Well, if you have a specific call getTriggers, you don't need an additional attribute about the type in the result since you already know that they all are triggers, don't you?

**Comment by maggu2810** [comment]
I don't think that @aounhaider1 points to the need of the additional attribute.
Using an attribute "/rest/module-types?type=action" or a separate REST endpoint "/rest/module-types/action" doesn't make much different (in both cases action must be spelled correctly, but okay, it is perhaps "safer").
If you have a look at the result (and this is what we are talking about -- IMHO), it is the same for both mechanism and in both cases I know that the result are actions.

I assume the question is about the use case of "/rest/module-types" without any attribute (e.g. call "/rest/module-types" and work with the result instead of using three different calls).

This method returns all module-types but there is no way know get the module-type back from the result.
So, is there any use case to get all module-types if we can't read back the specific module-type from the result.

@aounhaider1 Is that your question?

**Comment by kaikreuzer** [comment]
> I assume the question is about the use case of "/rest/module-types" without any attribute

Point 1 in #1483 is about replacing this call by individual endpoints. If this is nothing you consider valid, you should veto on #1483.

**Comment by maggu2810** [comment]
I don't think I have written something against the usage of a different endpoint above.
I give up, perhaps @aounhaider1 is able to write it in a more readable / understandable way.

**Comment by aounhaider1** [comment]
Yes @maggu2810 that was my question. Currently, we have endpoint 'rest/module-types', we can get all the module-types if we do not specify any 'type' in the argument. The response from this will have all the module-types (triggers, actions, conditions) but it is not possible to segregate these module-types on the client side.i.e. we cannot separate triggers, actions, conditions in separate arrays as there is no type attribute inside the JSON response. Would it make sense to add a type attribute to the JSON response so we just do one request to endpoint 'rest/module-types', get all the module-types and segregate them ourselves?

**Comment by kaikreuzer** [comment]
Sorry, if I don't make myself clear, but I can only repeat my statements above.
The plan of #1384 is to REMOVE the /rest/module-types endpoint and rather have /rest/trigger-types instead. So on the JSON response your will ALWAYS KNOW that it is a trigger, because you requested exactly this.

If you REQUIRE a single call for all types, please VETO on #1384.

**Comment by kaikreuzer** [comment]
The originally reported issue is imho solved since a while.
