### ISSUE TITLE
Switch control of color channel bug

### ISSUE THREAD

**Issue by Liamj001** [eclipse/smarthome#1593]
I have a Switch item linked to the color channel of a LIFX bulb. It works correctly, but seconds after switching the bulb on the binding sends an HSB value and thus the Switch item is set to UNDEF and the sitemap toggle shows OFF.

**Comment by lolodomo** [comment]
When this issue is fixed, issue #866 should be checked again. Probably a very similar problem if not the same.

**Comment by polarathene** [comment]
@lolodomo Please refer to [my response](https://github.com/eclipse/smarthome/issues/866#issuecomment-227646618) on #866 . I only have Hue not LIFX, but your bug might be a config issue? The solution I provided does not trigger any problems with any of the controls.

**Comment by kgoderis** [comment]
Should be fixed with https://github.com/eclipse/smarthome/pull/1788
