### ISSUE TITLE
It seems items added programmatically to GroupItem are not persisted in mapdb

### ISSUE THREAD

**Issue by satish-nikam** [eclipse/smarthome#1596]
I am using GroupItem.addMember() method to programmatically add item to the group switch. This works fine and I am able to operate group switch from Basic-UI. I also see group members using REST API. 

But when I restart ESH, I do not see these members at all. REST API also returns empty json array for GroupItem members. It seems group item members are not persisted in mapdb.

**Comment by kaikreuzer** [comment]
Items are only persisted when you call ItemRegistry.update(yourItem).

**Comment by satish-nikam** [comment]
I already have following code:
groupItem.addMember(memberItem);
itemRegistry.update(groupItem);

Do you mean I need another update call as follows?
itemRegistry.update(memberItem);

**Comment by kaikreuzer** [comment]
Yes, the membership is actually stored within the member, not within the group - so the member has to be persisted.

**Comment by satish-nikam** [comment]
I tried registry update for individual member as you suggested, but still facing same issue.

**Comment by kaikreuzer** [comment]
ok, let's reopen it then.

**Comment by sjka** [comment]
You missed to set the inverse reference on the member, i.e. `o.e.sh.core.items.ActiveItem.addGroupName(String)`.
