### ISSUE TITLE
[Classic Icons] Missing icon for television

### ISSUE THREAD

**Issue by rtvb** [eclipse/smarthome#1599]
Every icon has an neutral version and optionally a version per state. For television, only the states are in the repo: `television-on` and `television-off`. The neutral `television` should be added.

Related to:
https://github.com/eclipse/smarthome/tree/master/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/icons

**Comment by rtvb** [comment]
Needs modification of `_iconcopy` script:

https://github.com/eclipse/smarthome/blob/master/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/icons/_iconcopy

**Comment by maggu2810** [comment]
Can you create a PR to fix this?

**Comment by maggu2810** [comment]
Sorry, wrong button

**Comment by rtvb** [comment]
Solved

**Comment by ollie-dev** [comment]
The television icons are still not fully ok - there is a typo in the name "televison-off.svg" and "televison-off.png".

**Comment by rtvb** [comment]
I will submit a PR
 
 
Op Wo jun 8 2016, om 23:07 schreef Ollie:
> The television icons are still not fully ok - there is a typo in the
> name "televison-off.svg" and "televison-off.png".
> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>
 

Links:

  1. https://github.com/eclipse/smarthome/issues/1599#issuecomment-224728105
  2. https://github.com/notifications/unsubscribe/AAiI8jesDENd3DfAfEEmrygKPckem944ks5qJy8VgaJpZM4Is0h9
