### ISSUE TITLE
[Sonos] LED channel not working

### ISSUE THREAD

**Issue by rtvb** [eclipse/smarthome#1612]
The LED channel is not working. It doesn't receive the status of the setting if it is modified through the Controller app. It isn't set through the UI.

**main.things:**
```
Thing sonos:PLAY1:living [ udn="RINCON_B8E937B435380xxxx", refresh=60]
```
**sonos.items**
```
Group Sonos_Living "Sonos PLAY:1" <player> (All)
Switch Sonos_Living_LED "LED [%s]" <switch> (Sonos_Living) { channel="sonos:PLAY1:living.led" }
```

**bundle:list**

    194 | Active   |  80 | 0.8.0.201605311814    | Sonos Binding

**Comment by kgoderis** [comment]
You have a typo in the Switch item definition

channel="sonos:PLAY1:living:led" it should be

**Comment by rtvb** [comment]
:(

Working now. Thanks.
