### ISSUE TITLE
Default switch icon

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1614]
Would it be possible to change the default switch icon to have a really visible difference between ON and OFF states ? Maybe having a different color would be perfect.

**Comment by kaikreuzer** [comment]
I am all for it - I actually much preferred the old "bulb" instead of a wall switch...
Any suggestions for a good generic icon (as a bulb is not necessarily appropriate in all cases)?

**Comment by digitaldan** [comment]
I also agree, it doesn't much look like a switch at all.  I would opt for something less like a physical light switch (like a simple circle or square that's empty for off, filled for on).  The "text" icon is probably also worth looking at,  I had to go through and set icon='" everywhere I had a text item (it's huge, white and looks out of place on a sitemap).

**Comment by kaikreuzer** [comment]
@reitermarkus As you are the icon design specialist, do you have suggestions for good alternatives?

**Comment by reitermarkus** [comment]
Maybe a green and red power-button symbol?
![Switch Icons](https://cloud.githubusercontent.com/assets/1309829/15808725/742efc14-2b7f-11e6-869c-e8fedbb74ce3.png)

What kind of devices are you using the switch icon for? I think every switch belongs to something, so maybe we should be creating icons for those things, too.

**Comment by kaikreuzer** [comment]
I like the power-buttons!

> What kind of devices are you using the switch icon for?

The "switch" icon is mainly used as a fallback when all we know is that we deal with something switchable and the user didn't specify a more fine-grained category. As you have covered the list of categories with the icon set, I think we are fine in this regard (and new stuff should first be added to the list of categories and then to the iconset).

**Comment by digitaldan** [comment]
>Maybe a green and red power-button symbol, or simply a green/red circle?
I like the power button as well!  I would suggest using black/silver/grey for 2 reasons, one is that I think it looks better, my opinion ;-) , and two,  I know several people who are colorblind, so red and green may not mean much.

**Comment by kaikreuzer** [comment]
I think we should go for the colors as the whole icon set is colorful and not shades of grey. We should rather introduce additional greyish icon sets then (btw, the [KNX KUF one](https://github.com/OpenAutomationProject/knx-uf-iconset) is waiting to be integrated as well!).

**Comment by rtvb** [comment]
![](http://i.stack.imgur.com/rVrPi.jpg)

**Comment by kaikreuzer** [comment]
@rtvb This would suggest that the icon itself is a toggle, which it isn't.

**Comment by rtvb** [comment]
A toggle would make a clear distinction between states. I have been
experimenting with some flat icons and liked the visual effect.
 
 
Op Ma jun 6 2016, om 21:05 schreef Kai Kreuzer:
> @rtvb[1] This would suggest that the icon itself is a toggle, which
> it isn't.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>
 

Links:

  1. https://github.com/rtvb
  2. https://github.com/eclipse/smarthome/issues/1614#issuecomment-224056222
  3. https://github.com/notifications/unsubscribe/AAiI8iACtD8z_m0VPRx67jW1-qz1QG6bks5qJG-GgaJpZM4IuWz9

**Comment by digitaldan** [comment]
I will also add while it should visually represent the switch state, it should not look so my like a UI switch that the user confuses it for the actual widget he/she was suppose to push.

**Comment by reitermarkus** [comment]
I also agree that it shouldn't look like a UI toggle as it would be redundant.

**Comment by kaikreuzer** [comment]
So I'd suggest to use https://github.com/eclipse/smarthome/issues/1614#issuecomment-223842588 for a start. @reitermarkus, would you create a PR for it?

**Comment by reitermarkus** [comment]
Ok, I have created one here: https://github.com/eclipse/smarthome/pull/1637

**Comment by reitermarkus** [comment]
@digitaldan, what would you suggest for the text icon?

Maybe simplyfying it would help.

![Text Icon](https://cloud.githubusercontent.com/assets/1309829/15892763/d0bfe788-2d7b-11e6-8f51-7099747f5e4e.png)

**Comment by kaikreuzer** [comment]
@digitaldan What would you suggest for the "text" icon? I agree that the current icon looks weird besides most "text" widgets, but I have no good suggestion either...

**Comment by digitaldan** [comment]
Sorry to have forgotten about this!   The text widget is difficult, unlike a switch widget which by its nature is on or off (forgetting a multivalue pushbutton type), a text item may convey temperature, geolocation, security status, or any infinite amount information. So the icon would almost certainly never really match what the content of what the text means.  Also b/c text is so often used ( I'm assuming) throughout a sitemap, the icon is seen frequently, but doesn't really  mean anything.  So this is all a very long way of saying how do we minimize the visibility of it?  White background with black is a very high contrast icon, so it's going to stand out on black (like the android clients) .  If we were using just png's I would suggest to make the text grey (so it works for both white and black backgrounds),  reduce the amount of lines to three and remove the border.  The background would then be transparent.  Do SVG's have transparency ?  This is of course my unprofessional opinion ;-)

**Comment by digitaldan** [comment]
Also I'm ok @reitermarkus if we use the image you provided (thanks for doing that) and let users do their own customization .

**Comment by kaikreuzer** [comment]
> I would suggest to make the text grey, reduce the amount of lines to three and remove the border.

Something like this maybe?

<img width="122" alt="screen shot 2016-06-27 at 18 24 27" src="https://cloud.githubusercontent.com/assets/3244965/16387280/7c6c4f50-3c94-11e6-88df-11678216b44d.png">

**Comment by digitaldan** [comment]
How about 
![lines4](https://cloud.githubusercontent.com/assets/1903737/16388899/339a8f92-3c50-11e6-8baf-e6a4f1f8a53c.png)

Yes it has 4 lines, but I realized 3 was tough to tell what it was :-)

**Comment by kaikreuzer** [comment]
> I realized 3 was tough to tell what it was

Well, that was all the purpose of it :-)

Your icon instead clearly looks like a written text paragraph, which very often is inappropriate as an icon as you explained above.

**Comment by digitaldan** [comment]
thats fair :-)  I guess my intent is to minimize it as much as possible (blend in), the three straight lines looks like something I would be expected to drag to re-order list items which is common on IOS, on android this looks like the "hamburger" menu icon (like when selecting sitemaps).  I am also aware of how much time we are talking about a little text item, so let us choose something quick ;-) @reitermarkus   would you care to weigh in ?

**Comment by reitermarkus** [comment]
First of all, the border wasn't part of the icon anyway, it was just to show the dimension of the icon. 

> Do SVG's have transparency?

Yes. Also, different background colors on different devices/UIs are the exact reason why icons shouldn't be black/white.

> a text item may convey temperature, geolocation, security status, or any infinite amount information

I think the `text` icon should be considered a placeholder, because there is always a *thing* that is described by the displayed text, and there almost certainly will be a way to depict this *thing*.

For the examples you mentioned:
- temperature: a thermometer
- geolocation: a map or a pin
- security status: a lock or a keypad

**Comment by kaikreuzer** [comment]
> I think the text icon should be considered a placeholder

Yes, I think we all agree. So this placeholder icon should try to imply as little meaning as possible. So which one is the most suitable in this regard?

**Comment by reitermarkus** [comment]
I think we should get rid of it completely. There is already a discrepancy between

```java
Text item=Internally_A_String
```

and


```java
Text item=Internally_A_Number
```
A text item which is internally a number shows up blank by default. So why does `text` even need an icon when `number` doesn't have one? The label and text itself should be enough information already. The label is text, the text is text, so it should be clear that the sitemap item is a text item.

**Comment by digitaldan** [comment]
@reitermarkus I would be ok with that, this is also what I have done on my system (set image="") to all text items.

**Comment by kaikreuzer** [comment]
I am not too happy with the visual appearance, if there is no icon at all - to me the UI then looks somewhat broken; so I would prefer some kind of "meaningless placeholder", so that the UI at least pleases the eye :-)

**Comment by lolodomo** [comment]
@reitermarkus : would it be possible to have a different color, probably grey, for a non defined item ?
switch.png would be gey, switch-on.png would be green (as it is) and switch-off.png would be red (as it is).

**Comment by rtvb** [comment]
Re: https://github.com/eclipse/smarthome/issues/1614#issuecomment-229085863

OH1 had the option to use a `<none>` icon in a `.items` file. Why not default to this icon for Text and Number type items?

Or instead of <none> provide <default> as an alternative?

Personally, I actually like every item having an icon. So instead of using 'none' I should opt for a 'number' icon. Being visually distinguishing from 'text' or simply just an alias of the 'text' icon. In Basic UI a number type item without explicit icon in the definition shows a broken item (since 'number' is provided to the ui and that isn't available).

**Comment by lolodomo** [comment]
I close this issue as we have now the issue #4849 for the missing number icon.

**Comment by lolodomo** [comment]
Closed
