### ISSUE TITLE
Philips Hue Binding: Please add support for lamp Osram Lightify Classic B40

### ISSUE THREAD

**Issue by joergkling** [eclipse/smarthome#1616]
This is a dimmable lamp for socket E14, white with changeable color temperature. 

Technical type in Hue-App: Classic B40 TW - LIGHTIFY

The configuration should be similiar to LIGHTIFY PAR16 TW

Details:
		"18": {
			"state": {
				"on": true,
				"bri": 51,
				"ct": 370,
				"alert": "none",
				"colormode": "ct",
				"reachable": false
			},
			"type": "Color temperature light",
			"name": "Schlafzimmer Bettlampe",
			"modelid": "Classic B40 TW - LIGHTIFY",
			"manufacturername": "OSRAM",
			"uniqueid": "84:18:26:00:00:07:e9:00-03",
			"swversion": "V1.04.12"
		},

http://www.osram.co.uk/osram_uk/products/led-technology/lightify/lightify-home/lightify-lamps/lightify-classic-b-tw/index.jsp

**Comment by joergkling** [comment]
I assume this issue can be linked with #673 or #1652.

**Comment by afuechsel** [comment]
#1652 replaces #673 but is meant to introduce generic thing types. So the mentioned Osram bulb should be supported out-of-the-box with the new thing-type _hue:color-temperature-light_. Unfortunately there is still some "special-handling" for Osram Par16 50 in the code, we should check, if this is really necessary and hopefully get rid of it.

**Comment by joergkling** [comment]
As far as I know, the Osram stuff is needed because with standard HUE commands they wouldn't switch of properly (stay on a minimal dimm level). However, since the intoduction of the fix there have been new software versions for the Osram bulbs, so there is a chance that the workaround is not needed anymore. Also I wonder if it is the Par16 bulb only which needs this fix or other Osram bulbs as well?

I am travelling this week but happy to do some testing next week.

**Comment by kaikreuzer** [comment]
This should now be supported with https://github.com/eclipse/smarthome/pull/1652.
Please check whether the same workaround is needed for the B40 as it is needed for the Par16. It should be easy to add this.
Optimistic as I am, I assume it is NOT required. If this assumption is false, please re-open this issue.

**Comment by joergkling** [comment]
Happy to confirm that the lamp is now fully working with the new binding. Thanks for the great work!

**Comment by kaikreuzer** [comment]
Cool, thanks for the feedback!

**Comment by afuechsel** [comment]
Does it mean, we could just remove the special handling even for OSRAM PAR16 TW?

**Comment by kaikreuzer** [comment]
No, it only means the B40 does not have the same firmware bug as the PAR16.
