### ISSUE TITLE
Rule JSON template documentation wrong

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1624]
I assume the rule template documentation is not correct.

https://github.com/eclipse/smarthome/blob/884f1d6/docs/documentation/features/rules.md#rule-templates
vs.
https://github.com/eclipse/smarthome/blob/884f1d66bfe836e8710ff9d8e007b700a54c6eef/bundles/automation/org.eclipse.smarthome.automation.sample.extension.json/ESH-INF/automation/templates/SampleTemplateDefinitions.json

* configDescriptions + name instead of configuration + key
* inputs instead of input

@marinmitev As you have written the documentation could you have a look at?

I tried today to create a rule template using the documentation and it does not work.
This evening I tried to use the samples as a base and the template is working.

**Comment by marinmitev** [comment]
done

**Comment by maggu2810** [comment]
Thanks @marinmitev 
One additional question.

The documentation contains a list "Supported Java Types The java types supported in the input/output objects are".
The available event trigger demonstrates that also other types are possible (and necessary).
https://github.com/eclipse/smarthome/blob/884f1d66bfe836e8710ff9d8e007b700a54c6eef/bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/EventTriggersTypeDefinition.json#L37

Does the list mean that for every member we do not use the full qualified name?
And if we use the full qualified name, we can use every class?

**Comment by danchom** [comment]
I think this is an old list. We have to remove it. The type of input/output is defined by string and it is used for validation of connection. It is done in following way:
1) if the input type and the output type are equal as string the connection is accepted
2) if the input type is "*" and the output type is any the connection is accepted
3) if the input type and the output type are strings representing full qualified names which can be loaded and the input type is  assignable from output type the connection is accepted

**Comment by maggu2810** [comment]
Thanks for explanation @danchom 
So, I think this change should be added to #1624.
Will merge this then.

**Comment by marinmitev** [comment]
description added  and squashed the commits
