### ISSUE TITLE
Events logged in events.log and openhab.log

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1628]
In OH2, ItemStateChangedEvent are logged twice, in events.log and in openhab.log.
In OH1.x, they were only logged in events.log.
Is it the expected behaviour ?

Is there a setting to have events only logged in events.log ?

**Comment by maggu2810** [comment]
The logging settings of the openHAB-distro are not related to Eclipse SmartHome.
Please report such problems to the relevant project.
