### ISSUE TITLE
Support option filtering

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1632]
The [config descriptions](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-configuration-descriptions) support filter criteria.

The Paper UI should support this (for a few cases for the start):

- Filtering item lists by type or tags:
If the context "item" is given, the Paper UI currently shows the full list. By defining a filter like
```
<filter>
  <criteria name="type">Switch,Dimmer</criteria>
  <criteria name="tag">Light,Heating,Volume</criteria>
  <criteria name="tag">Alarm</criteria>
</filter>
```
this list should only show items with `(type=Switch OR type=Dimmer) AND (tags contains Light OR tags contains Heating OR tags contain Volume) AND (tags contains Alarm)`.

**Comment by maggu2810** [comment]
If my reading is correct the same config description is used for rules (automation API), too.
So I assume this "configurationDescription" should give us only a list of Switch items.

```
            {
                "name":"itemname_out",
                "type":"TEXT",
                "context":"item",
                "filterCriteria":[
                    {
                        "name":"type",
                        "value":"Switch"
                    }
                ],
                "label":"item name output",
                "description":"The switch item for the output.",
                "required":true
            }
```

Correct?

**Comment by kaikreuzer** [comment]
Correct, actually the rule editor is my main use case for requesting this feature.
