### ISSUE TITLE
Default sitemap parameter for Classic UI not saved properly

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1633]
If I set a default sitemap for Classic UI using Paper UI => Configuration => Services => Classic UI (Configure button), then when I open Classic UI from the dashboard, it opens on my specific sitemap.
If I restart OH2, the setting is again set to _default rather than my specific sitemap.

PS: the same setting is apparently working for Basic UI.

**Comment by maggu2810** [comment]
Does it work if you remove that line?
https://github.com/openhab/openhab-distro/blob/72e5a7c/distributions/distribution-resources/src/main/resources/runtime/etc/services.cfg#L17

**Comment by kaikreuzer** [comment]
I would tend to say yes, this looks like a remainder from older setups that should be removed!

**Comment by lolodomo** [comment]
I can confirm that commenting this line in runtime/etc/servies.cfg solved the issue.

**Comment by kaikreuzer** [comment]
Great, thanks for the feedback!

**Comment by lolodomo** [comment]
If I want to force a default sitemap inside my config files and avoid using Paper UI, I assume I can just use this line but can I put it somewhere in conf/services directory ? In addons.cfg file for example ?

**Comment by kaikreuzer** [comment]
The best file to add this line in OH2 would probably conf/services/runtime.cfg.

**Comment by lolodomo** [comment]
OK thank you for the advice and the fix.
