### ISSUE TITLE
Automation: multiple triggers

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1641]
I don't know if my understanding of the rule engine is correct.

If I add two trigger to a rule, I assume it is executed 
* if the first trigger matches
* if the second trigger matches

Is this correct?

I add two item state changed event trigger to a rule, one for ITEM_SWITCH_0 and one for ITEM_SWITCH_1.
The rule is only triggered for one of both.

@danchom, @marinmitev: Is this a bug or is my understanding wrong?

**Comment by maggu2810** [comment]
The rule looks like:

```text
{
  "enabled": true,
  "status": {
    "status": "IDLE",
    "statusDetail": "NONE"
  },
  "triggers": [
    {
      "id": "trigger_1",
      "label": "Item State Change Trigger",
      "description": "This triggers a rule if an items state changed",
      "configuration": {
        "itemName": "SWITCH_IN_0"
      },
      "type": "ItemStateChangeTrigger"
    },
    {
      "id": "trigger_2",
      "label": "Item State Change Trigger",
      "description": "This triggers a rule if an items state changed",
      "configuration": {
        "itemName": "SWITCH_IN_1"
      },
      "type": "ItemStateChangeTrigger"
    }
  ],
  "conditions": [],
  "actions": [],
  "configuration": {},
  "configDescriptions": [],
  "uid": "rule_3",
  "name": "T",
  "tags": []
}
```

The function "internalCreate" of "GenericEventTriggerHandler" looks if there is already a handler for "ruleUID + module.getId()". A new one is only created if there is no one.
The module.getId() returns the ID of the module itself, but not the ID that is used in the rule  (not trigger_1 or trigger_2 but itemStateChangeTriggerID).
So there will not be two handlers created but only one.
I assume this is not correct.

**Comment by maggu2810** [comment]
The ID of the children of CompositeTriggerType (of all composite types) needs to be unique.

**Comment by danchom** [comment]
Hi Markus,
1) Your understanding is not right. Each one of the triggers can trigger the rule. There is OR relation between triggers. Your use case is close to CEP (complex event processing) which is not supported by the Automation module. May be you can implement it with condition, where the state of one switch will be get from the system (through the ScriptCondition) when the other triggers the rule. The conditions are related with AND between them.

**Comment by maggu2810** [comment]
1) This is what I mean :wink: Perhaps my spelling was wrong.

I think my example is rather simple and easy to reproduce.

* Create two switch items
* Create a rule with two composite triggers of the same type, e.g. the ESH "ItemStateChangeTrigger" (https://github.com/eclipse/smarthome/blob/90e1804/bundles/automation/org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/EventTriggersTypeDefinition.json#L45)
* the first ItemStateChangeTrigger is using the first switch item
* the second ItemStateChangeTrigger is using the second switch item

The rule is triggered only by one item.

Both composite trigger has a unique ID.
The child of the first composite trigger, the ItemStateChangeTrigger has the same ID as the child of the second composite trigger. So the same handler is used and because of that the last configuration wins.

**Comment by kaikreuzer** [comment]
Sounds very much like a bug to me.

**Comment by danchom** [comment]
Ok I understand now.I'll check it

**Comment by danchom** [comment]
Fixed  by #1641

**Comment by maggu2810** [comment]
> Fixed by #1641

Fixed by #1683 :wink: (#1641 points to the issue itself and not to the PR).

**Comment by DM-Kang** [comment]
Hello guys! I have a question.
If I add 2 or more conditions in my Rule, there is also OR Relation between conditions, right?
Can I make AND or another Relation between conditions?

**Comment by kaikreuzer** [comment]
@DM-Kang Conditions are always AND, so a rule is only executed if all conditions are met.

**Comment by danchom** [comment]
@DM-Kang if you want OR relation between conditions you just split the rule into two rules.

**Comment by danchom** [comment]
Fixed
