### ISSUE TITLE
Sonos does not work any more

### ISSUE THREAD

**Issue by s-simma** [eclipse/smarthome#1642]
I do the openhab2 configuration by use of text-editor. My configuration worked fine with
earlier snapshots. With the latest one my Sonos does not work any more.

What does work:
---------------
1. Remove Player configuration from "demo.things"
2. PaperUI -> Inbox -> Search for Sonos
3. Add a found player as Thing (RINCON_000E5851B1C401400)
4. PaperUI -> Control
5. Change Volume,Play/Pause -> ok
6. If you change Play,Pause,Volume in the Sonos-App states are NOT reflected in PaperUI->Control

What does NOT work any more:
-------------------
1. in demo.things
sonos:zoneplayer:SonosOffice [udn="RINCON_000E5851B1C401400", refresh=60]

2. in demo.items
Player SonosOfficeCont "Sonos Office" <soundvolume> (gSonosPlayer,gFF_Office) {channel="sonos:zoneplayer:SonosOffice:control"}

-> Player is not "ONLINE" (it is shown as "UNINITIALIZED" in PaperUI->Things).
-> Players not available at all, are shown as "ONLINE" (already mentioned my KaiKreuzer)

If you put the Player-Control to the sitemap -> play/pause gives following warning:
09:46:13.476 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate command 'PLAY' for item 'SonosOfficeCont' to handler for channel 'sonos:zoneplayer:SonosOffice:control', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.

With other words, it is no longer possible to define the Sonos-System in the "things/items-file by use of a text-editor" (i hope this is a bug) ?

**Comment by kaikreuzer** [comment]
Please see https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/README.md#supported-things

There is no thing type "sonos:zoneplayer" anymore, instead you have to e.g. define a "sonos:PLAY1". This should make it all work for you again, please confirm.

**Comment by s-simma** [comment]
@kaikreuzer 
thanks for info. Now Sonos works as it did before.

**Comment by kaikreuzer** [comment]
perfect!
