### ISSUE TITLE
openHAB exposed to mDNS only on IP v6

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1655]
It looks like openHAB is exposed only on one interface.
My RPI2 has a IP v4 interface and a IP v6 interface.
```
avahi-browse --all
+   eth0 IPv6 openhab                                       _openhab-server._tcp local
+   eth0 IPv6 openhab-ssl                                   _openhab-server-ssl._tcp local
...
```
On my Android tablet, I installed an application that browse domains and openHAB is not discovered, probably because the tablet uses only a IP v4.

**Comment by lolodomo** [comment]
It probably have a link with #577

**Comment by lolodomo** [comment]
Can someone help me to identify the class implementing this feature ?

**Comment by maggu2810** [comment]
I assume this is really the same as #577.
The mDNS Service needs some work. Interfaces that are not up on startup are completely not used etc.
You need to have a look at org.eclipse.smarthome.io.transport.mdns
I think there are more classes involved.
See my comment here:
https://github.com/eclipse/smarthome/issues/577#issuecomment-219017195

**Comment by kaikreuzer** [comment]
Let's close this as a duplicate.

**Comment by lolodomo** [comment]
After searching and studying the source code, I understand now that it is not exactly the same error but the root cause is the same.
The feature I mention in this issue is implemented by service MDNSAnnouncer which references the service MDNSService. The problem is in service MDNSService.

**Comment by kaikreuzer** [comment]
So shall I reopen this issue, because there are different fixes required?

**Comment by maggu2810** [comment]
I assume both fixed needs the same base implementation to get notified for interfaces that receives a new IP addresses.

**Comment by lolodomo** [comment]
Yes I think one correction should fix the 2 issues at the same time.
Keep this one closed.
I will reference the 2 issues in my future PR.
