### ISSUE TITLE
Add possibility to specify dayOfWeek in configurations

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1665]
A regular use case for rules is to choose the days of the week (i.e. only weekdays, not weekend).
We are lacking a suitable context in the config descriptions.

My suggestion is to add a new context "dayOfWeek", which will then make the Paper UI render a selection of one of the 7 days. If the config parameter is "multiple=true", it should render checkboxes, where multiple days can be chosen. The encoding (i.e. the value or the parameter) should be MON, TUE, WED, THU, FRI, SAT, SUN. The UI itself should render localized labels (which can be a 3 letter shortcut as well, if this makes the appearance nicer).

**Comment by maggu2810** [comment]
Should this be evaluated by the module handler and break the rule execution is the current day of week does not fit to the configuration in the rule?

**Comment by kaikreuzer** [comment]
Well, this is not specifically about rules, but a requested feature for config descriptions.
It then depends on the service, which is using this in its config on how it will handle it.
I envision a Condition-Module, which will simply evaluate in "false", if the current day of week is not within the configured list. Does this make sense?

**Comment by maggu2810** [comment]
A condition module that simply evaluates to false if it is the wrong date / time make really sense.

But why not using a condition that has (multiple) cron syntax in its configuration?
Sure, it is not such simple for the user, but that is something that could be solved by the UI that generates the correct one if "only on Monday" is chosen.
But we can handle a lot of date / time configuration with that condition.

**Comment by kaikreuzer** [comment]
> But why not using a condition that has (multiple) cron syntax in its configuration?

Well, you would shift the declaration of what kind of configuration should be presented for the user to the UI implementation, completely dismissing the concept of our config descriptions. Note that we already have support for time, day, month, etc., so adding dayOfWeek is a natural addition, which can be used in other situations as well (e.g. a Thing or a service configuration).

**Comment by kaikreuzer** [comment]
> A condition module that simply evaluates to false if it is the wrong date / time make really sense.

FTR: Initial version implemented with https://github.com/eclipse/smarthome/pull/2858
