### ISSUE TITLE
Designer URLs dead

### ISSUE THREAD

**Issue by sja** [eclipse/smarthome#1669]
I cannot download the nightly builds of the Designer. All links seem to be dead.
Example:
`http://eclipse.org/downloads/download.php?file=/smarthome/nightly-snapshots/eclipsesmarthome-incubation-0.9.0-SNAPSHOT-designer-macosx64.zip`

I don't know how to fix this. I tried it for some days and different times of the day.

**Comment by maggu2810** [comment]
Please retry...

**Comment by sja** [comment]
Amazingly fast, @maggu2810 ! What was the problem?

**Comment by maggu2810** [comment]
I just started the publish nightly job again.
The previous job succeeded, too.
Don't know why the zip files have not been available.
