### ISSUE TITLE
RuleEngineImpl.runStartupRules masks errors

### ISSUE THREAD

**Issue by weswitt** [eclipse/smarthome#1670]
If an arbitrary exception is thrown during the execution of a startup rule the details of the exception are not logged, leaving the user mystified as to what actually happened.

Here is the current code:

                } catch (ScriptExecutionException e) {
                    if (!e.getMessage().contains("cannot be resolved to an item or type")) {
                        logger.error("Error during the execution of startup rule '{}': {}",
                                new Object[] { rule.getName(), e.getCause().getMessage() });
                        executedRules.add(rule);
                    } else {
                        logger.debug("Execution of startup rule '{}' has been postponed as items are still missing.",
                               rule.getName());
                    }
                }

The following would be better:

                } catch (ScriptExecutionException e) {
                    logger.error("Error during the execution of startup rule '{}': {}",
                            new Object[] { rule.getName(), e.getCause().getMessage() });
                    if (!e.getMessage().contains("cannot be resolved to an item or type")) {
                        executedRules.add(rule);
                    } else {
                        logger.debug("Execution of startup rule '{}' has been postponed as items are still missing.",
                               rule.getName());
                    }
                }

**Comment by maggu2810** [comment]
I am fine with that change, but perhaps there has been some reasons of the filter.
Can you create a PR?
I think we can omit the creation of an Object array and using the variable arguments function.

**Comment by kaikreuzer** [comment]
>  but perhaps there has been some reasons of the filter.

Yes, clearly there was. If `getMessage().contains("cannot be resolved to an item or type")`, there simply is no error and thus it must not be logged. The rule engine will simply try to re-run the rule whenever a new item appears.

**Comment by kaikreuzer** [comment]
> there simply is no error

Let me precise this: This situation regularly happens at startup when the rule does not have any problem - and thus no error must be logged. If the rule is buggy, this situation might of course also occur and in that case the error would be swallowed. The debug logging happens in this case, which should be fine when debugging your system.
