### ISSUE TITLE
Designer cannot open Projects/Folders

### ISSUE THREAD

**Issue by sja** [eclipse/smarthome#1674]
Ok, I can start the Desginer (OS X), but if I try to open the conf-folder, I get the following error: 
    
    An error occurred while opening the configuration folder
          Resource '/config' is not open.

[Screenshot](https://www.dropbox.com/s/ovc6iannbdz3y71/Screenshot%202016-06-14%2020.45.32.png?dl=0)

The same project can be opened with the old Designer.

**Comment by kaikreuzer** [comment]
Try a clean designer install or manually delete the workspace folder, which has been created within the .app folder.

**Comment by sja** [comment]
I do always clean installs. After downloading I replace the App in /Applications and this contains the workspace.

I deleted this workspace, but nothing changes. The startup take a lot of time (1-2 Minutes). All fat Eclipse installations I have are up in <20 seconds.

I walked through the settings of the Designer and noticed, that on all ESH specific menu entries, like 'Sitemap' or 'Rules', which have a 'Template' sub-entry, I get the Error message 'The currently displayed page contains invalid values.' [Screenshot](https://www.dropbox.com/s/vvbzx39oh2cqg3l/Screenshot%202016-06-15%2009.29.11.png?dl=0)

I also notices, that after an unsuccessful try of opening my conf-folder, my group-definitions form the .items-file are loaded. So the error seems to occur while loading my files.

My config is not very much, I pasted it here: https://gist.github.com/sja/fae96ad6e2c317510a20b18ab7ebdce3

**Comment by maggu2810** [comment]
> My config is not very much, I pasted it here: https://gist.github.com/sja/fae96ad6e2c317510a20b18ab7ebdce3

I will give it a try.

**Comment by maggu2810** [comment]
No probs here, see log: https://gist.github.com/maggu2810/4cf2bf1d5d1799e67d1a6d7952ad0ff7

**Comment by sja** [comment]
Hm, strange. How do you get those logs? Are there any files in $HOME which are accessed which I can delete?

**Comment by maggu2810** [comment]
> How do you get those logs?

The log is written to the stdout. I don't know if there is an additional one.
I started the Designer using the command line and there has the messages been written to.

**Comment by sja** [comment]
I'm sorry, this sounds like a noob problem, but I neither get it correctly imported to Eclipse to start the Designer from there, nor I get it running from console.
I deleted the workspace which is located at _/Applications/Eclipse SmartHome Designer 2.app/Contents/MacOS/workspace_ and this is recreated on launching the app again. But the problem stays.
I see a binary at _/Contents/MacOS/SmartHome-Designer_ but that is not startable - seems like some parameters are missing.

**Comment by sja** [comment]
RIGHT after sending this text I got an idea. I launched it from the maven target folder and that version works! Sorry for the noise, but strange behaviour. Can't wait to get the text configs replaced to obsolete the Designer.

**Comment by kaikreuzer** [comment]
ok, glad to hear that it works!

> Can't wait to get the text configs replaced to obsolete the Designer.

They will definitely stay (as an option), but you might be interested in https://github.com/eclipse/smarthome/issues/1402 as a replacement for the Designer!

**Comment by h9nry** [comment]
i'm having exactly the same issue but the comment did not really help me to get it resolved. which file do i have to execute?
