### ISSUE TITLE
Rules : Access restriction: The type UnDefType is not accessible due to restriction on required project config

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1675]
This happens on declaring

`import org.eclipse.smarthome.core.types.UnDefType 
`
in a .rules file

I use this in clauses like

`if(TeslaScheduledDeparture.state == UnDefType.UNDEF || TeslaScheduledDeparture.state == UnDefType.NULL) { ...}`

Is there an alternative to checking the .state of an Item?

**Comment by kaikreuzer** [comment]
Fixed through https://github.com/eclipse/smarthome/pull/1703
