### ISSUE TITLE
Set state of a channel to null

### ISSUE THREAD

**Issue by s-simma** [eclipse/smarthome#1685]
Is it possible to set the state of e.g. a "CONTACT" from inside a binding to "NULL" or "undefined" ?

updateState(new ChannelUID(getThing().getUID(), CHANNEL_STATE), null); -> thows an exception during runntime.

I can only manage to set it to "OPEN" or "CLOSED".
This would be very helpfull to show that a sensor is no longer sending data (e.g. battery emtpty)

**Comment by maggu2810** [comment]
You should use UnDefType.NULL or in this case better UnDefType.UNDEF

**Comment by s-simma** [comment]
thanks for your help, works great.
