### ISSUE TITLE
Integer config parameter is stored as decimal

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1692]
If a service is configured through the Paper UI (and therefore through the REST API), numbers are sent in JSON always as double, i.e. an integer 1 becomes 1.0.
The REST API then stores this value as a BigDecimal with 1 decimal digit, so that it is not regarded as an integer anymore.

A concrete problem with this behavior is described here: https://community.openhab.org/t/change-homekit-setting-in-paperui/11407

**Comment by cdjackson** [comment]
I suspect this is a duplicate of #1477

**Comment by kaikreuzer** [comment]
I seem to enter only duplicates today :-/
Thanks for pointing it out!
