### ISSUE TITLE
Problem with Maven dependencies resolution

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1695]
When I try to compile with Maven a particular bundle, I got dependencies issue.
For example, for org.eclipse.smarthome.io.transport.mdns, a command "mvn clean package" ends with:
```
[INFO] Resolving dependencies of MavenProject: org.eclipse.smarthome.io:org.eclipse.smarthome.io.transport.mdns:0.9.0-SNAPSHOT @ F:\dev\openhab2-master\git\smarthome\bundles\io\org.eclipse.smarthome.io.transport.mdns\pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.smarthome.io.transport.mdns 0.9.0.qualifier
[ERROR]   Missing requirement: org.eclipse.smarthome.io.transport.mdns 0.9.0.qualifier requires 'package org.eclipse.smarthome.config.discovery 0.0.0' but it could not be found
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.smarthome.io:org.eclipse.smarthome.io.transport.mdns:0.9.0-SNAPSHOT @ F:\dev\openhab2-master\git\smarthome\bundles\io\org.eclipse.smarthome.io.transport.mdns\pom.xml: See log for details -> [Help 1]
[ERROR]
```
If I try to compile from the root point of the project, I think it is working.
I tried to remove my .m2/repository but it changed nothing.

**Comment by kaikreuzer** [comment]
Could you try if "mvn clean install" makes a difference?

**Comment by lolodomo** [comment]
Same result :(

**Comment by kaikreuzer** [comment]
> compile with Maven a particular bundle

Ah, I didn't read that carefully enough.
When compiling a single bundle, you must have already compiled all its dependencies at least once.
So make sure to run mvn clean install from the repo root once.

**Comment by lolodomo** [comment]
Ok thank yo. After a full compilation, now I can compile a particular bundle.
