### ISSUE TITLE
BaseThingHandler.channelLinked() should be empty

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1696]
The default implementation

```
    public void channelLinked(ChannelUID channelUID) {
        // can be overridden by subclasses
        // standard behavior is to refresh the linked channel,
        // so the newly linked items will receive a state update.
        handleCommand(channelUID, RefreshType.REFRESH);
    }
```

break all existing bindings/handler implementations. That being said, should it not rather be an abstract method, and leave it to the implementing Handler how to deal with newly linked channels?

**Comment by kaikreuzer** [comment]
Please find the related discussion at https://github.com/eclipse/smarthome/issues/1658.

Can you you please elaborate a bit on why it "breaks all existing bindings"?

**Comment by kgoderis** [comment]
We can group the discussions, but as far as I noticed, the handleCommand() in the bindings are not necessarily written in such a fashion that they can handle new types of Commands. Some do use a simple switch statement to differentiate between the Command types passed on, with a default option to drop the Command received, but others (at least in my case) there is an automatic mapping of the Command or State to a datatype of some kind that is relevant for the piece of hardware. (Like for example in the KNX binding). The side effect of this is that the binding tries to push a "REFRESH" value to the hardware. It is not a problem to revisit all the bindings and do some changes to the code, but I was not aware of this change (cfr #1658) nor that it was documented....

That being said, maybe some bindings do want to handle the channelLinked in a different way than via a handleCommand(), e.g. my suggestion to make it empty or abstract.

**Comment by maggu2810** [comment]
There are other default implementation already (e.g. handeRemoval, initialize, ...), so I don't see any reason, why we should not be allowed to have one for channelLinked.

The refresh type is used in the example here
* https://www.eclipse.org/smarthome/documentation/development/bindings/how-to.html#handling-commands-and-updating-the-state

I think a binding have to check the commands it receives and if a binding consumes the commands it receives without further processing in the handleCommand method, the binding implementation needs to be fixed.

**Comment by kgoderis** [comment]
@kaikreuzer that is not what I wrote : It is obviously documented, but I was not aware that a change in documentation was advertised. I mean, if documentation get changed, unless re-reading that documentation from time to time there is no way to be aware of changes. And after doing so many bindings, it is not something I visit / read up...

**Comment by maggu2810** [comment]
Hm, it has been part of the documentation from the beginning: 7f104697
But I think that does not matter, you have not been aware of it and so it is rather annoying that the bindings are broken now.
But I still think it is correct that the base implementation triggers a refresh so the items gets a state.
And I also think a binding needs to check the command it receives. Rules etc. could post commands to items and so to channels and a binding can't rely on the type of the command.

**Comment by kgoderis** [comment]
@maggu2810 Indeed, it does not matter, it is ok in itself, I will review the whole lot. I started binding dev well before Jul 2014.... ;-)

**Comment by kgoderis** [comment]
@kaikreuzer @maggu2810 FYI the documentation link you rightfully pointed out is not in sync with https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/bindings/thing-handler.md (which is the document I was mentally referring to). I think it is part of the confusion at my side
