### ISSUE TITLE
Bridge configuration does not show all options in PaperUI

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#1699]
The bridge configuration for Homematic contains configuration options for "gatewayAddress" and "callbackHost". Both entries are not visible in the PaperUI configuration:
![homematicbridge](https://cloud.githubusercontent.com/assets/616792/16178002/329f6644-363d-11e6-9851-78852fa6c348.png)
This problem seems to be caused by the configuration in `ESH-INF/config/thing/bridge.xml`. Both settings contain a subtag named "context". If I remove the subtag both settings appear in PaperUI.
BTW: same happens withe Hue bridge configuration. Setting "ipAddress" is also not visible.

This problem seems to be quite new. With openHAB 2.0 Beta 3 everything is OK. But not in the latest nightly builds.

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you have a look?

**Comment by aounhaider1** [comment]
Can you please provide the xml that you are using for this bridge?

**Comment by MHerbst** [comment]
This is the bridge.xml contained in the Homematic Add On. Parameters "gatewayAddress" and "callbackHost" are not shown.
[bridge.xml.txt](https://github.com/eclipse/smarthome/files/323988/bridge.xml.txt)
