### ISSUE TITLE
MapDB storage backend

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1702]
Caused by the recent changes, that properties are transient and so no longer persisted (#1682) I have a look at the esh storage.mapdb bundle.

There is one storage database (storage.mapdb) and all the maps are created in this backend.
[Here](https://github.com/eclipse/smarthome/blob/bb0b5f6/bundles/storage/org.eclipse.smarthome.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/MapDbStorage.java#L47) a new storage service is created.

I do not find any methods that removes such a storage service again.
Is this by intention?
Shouldn't the [storage interface](https://github.com/eclipse/smarthome/blob/bb0b5f6a68aafbbae72b38d34412c93b0a6f8c86/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/storage/Storage.java#L19) provide a method to remove the storage.

If someone want at least remove the whole content of the storage (without removing it or rely that the db is such clever and remove empty ones itself) shouldn't we add a clear function?

The function getKeys returns a key set and if my reading is correct, that is not documented.
So a simple loop over the return value of getKeys and a remove will result in a CME, correct?
Should we change the getKeys of the mapdb storage to create a new collection that contains all keys?

**Comment by kaikreuzer** [comment]
> properties are transient and so no longer persisted (#1682) 

This isn't fully correct - properties are still persisted, it is just that bindings themselves do not persist changes anymore.

> I do not find any methods that removes such a storage service again.
> Is this by intention?

I simply assume that nobody needed such a feature yet and it sounds dangerous ;-)

> shouldn't we add a clear function?

Feel free.

> The function getKeys returns a key set and if my reading is correct, that is not documented.

What do you mean by "not documented"? The interface has:

```
    /**
     * Gets all keys of this Storage.
     * 
     * @return the keys of this Storage
     */
    Collection<String> getKeys();
```
but I agree that this should actually rather be a Set than a Collection.

> Should we change the getKeys of the mapdb storage to create a new collection that contains all keys?

No idea what the MapDB implementation exactly returns upon a map.keySet(), but yes, it probably is safer to return a copy.

**Comment by maggu2810** [comment]
> What do you mean by "not documented"? 

I would like to say, that it is not documented that the returned collection is a **view** and so it is dangerous to use the returned collection while changing the storage.
