### ISSUE TITLE
FirmwareUpdateService thread pool is created even though not in use

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1706]
I just noticed that threads are spawned for a FirmwareUpdateService thread pool, altough my default installation neither has any firmware providers nor bindings that support firmware updates.

In such a situation I would not expect a thread pool to be created, because it requires unnecessary system resources.

**Comment by kaikreuzer** [comment]
@tomhoefer Could you please have a look?

**Comment by tomhoefer** [comment]
sure... will change ti

**Comment by triller-telekom** [comment]
@sjka @kaikreuzer This issue was fixed in in the referenced PR #1906. Please close it.
