### ISSUE TITLE
Text doesn't wrap in frame

### ISSUE THREAD

**Issue by pabloNZ** [eclipse/smarthome#1721]
I have a xslt transformation for my weather binding which can produce text strings which extend well past the frame bounds.

Neither the frame title nor the frame itself will wrap the text so it is visible in its entirety on smaller width screens. Larger screens can display the text, but it crops it, so is not particularly appealing visually. 

![4d12e28716a31eadde9ef03a5e8a8bdbdf98c412_1_690x160](https://cloud.githubusercontent.com/assets/11846547/16244798/d1e14874-3851-11e6-889f-be8d19f5e00b.JPG)
![8936a2241c88f8e00383c224316f7491346dba8c_1_557x500](https://cloud.githubusercontent.com/assets/11846547/16244797/d1e0895c-3851-11e6-8416-64f93751157b.JPG)
![c4ce4e88752dfb16bb45b66bf8f77aa60a308ff7](https://cloud.githubusercontent.com/assets/11846547/16244801/d3e07488-3851-11e6-86cf-df02410213c9.JPG)
![e091a2cc4fb5ce1a712752d5e80f8833785f00ba_1_513x500](https://cloud.githubusercontent.com/assets/11846547/16244799/d1f0a260-3851-11e6-8fce-7da90ca99aad.JPG)

**Comment by kaikreuzer** [comment]
@resetnow Could you have a look, please?

**Comment by resetnow** [comment]
Yes, it does look bad. What is the desired behaviour here, though? I can clip all the labels to the viewable area and make them end with an ellipsis like this:

![screenshot from 2016-06-22 19-18-03](https://cloud.githubusercontent.com/assets/2057191/16274388/77f2f92e-38b6-11e6-9a41-8e61c1561146.png)

Would it be ok?

**Comment by pabloNZ** [comment]
How will that look with the frame title? As it is now the frame title gets cut off also (see last pic attached above). This makes it difficult to relate the frame data if you haven't used the sitemap much before.

In some ways as a user i'd prefer to be able to make it either wrap, or end with ellipsis. But I feel like having a random frame being taller than the others will mess with the simple style of the basic UI. 

*shrug*

**Comment by resetnow** [comment]
#1797

**Comment by resetnow** [comment]
I assume this can be closed?

**Comment by kaikreuzer** [comment]
I'd say so.
