### ISSUE TITLE
Module configuration must be done by Configuration object.

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#1724]
At the moment module configuration (set configuration values to the module) is done by the Map<String, Objects> containing configuration id as key and configuration value corresponding to this key.
The configuration values has to be passed to the module as Configuration object.

**Comment by kaikreuzer** [comment]
This change broke the REST API (RuleResource) - since configurations cannot be (de)serialized anymore.
In the file system parser, you have implemented the Configuration(De)serializer classes to deal with that, but you missed the REST API.
