### ISSUE TITLE
Thread pool 'items' rejected execution of class org.eclipse.smarthome.core.items.GenericItem$1

### ISSUE THREAD

**Issue by rtvb** [eclipse/smarthome#1743]
I installed the latest nightly today and my log file is flooded with this message:

    16:23:48.536 [WARN ] [rthome.core.common.ThreadPoolManager] - Thread pool 'items' rejected execution of class org.eclipse.smarthome.core.items.GenericItem$1

Known issue? Or new bug?

**Comment by kaikreuzer** [comment]
new bug...

**Comment by rtvb** [comment]
What would you need from me to debug?
 
Groet, Robert
 
 
Op Za jun 25 2016, om 18:21 schreef Kai Kreuzer:
> new bug...
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
>
 

Links:

  1. https://github.com/eclipse/smarthome/issues/1743#issuecomment-228553752
  2. https://github.com/notifications/unsubscribe/AAiI8k7CItslBdBurY0YKvUy9uOavEW7ks5qPVWggaJpZM4I-WuC

**Comment by kaikreuzer** [comment]
Good question, I just tried to reproduce it, but I do not see such logging.
I assume you have many startup rules that might be long running?

**Comment by kaikreuzer** [comment]
This should hopefully be fixed with https://github.com/eclipse/smarthome/pull/1744.
