### ISSUE TITLE
mDNS discovery: weird things in class MDNSDiscoveryService

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1745]
There are weird things in the class MDNSDiscoveryService.

First, why addServiceListener is called inside startBackgroundDiscovery while it is already called inside setMDNSClient ? The result is that the JmDNS instance stores this class twice and so serviceAdded is called twice for example.

Second, I see that nothing is done in method serviceResolved. When JmDNS is calling serviceAdded, the service info attached to the event has not full info (like TXT record) while it has when serviceResolved is called. I don't know if we have to move the code from serviceAdded to serviceResolved, or just duplicate it.
For the Freebox binding, I would like to use one information present in the TXT record to build the thing uid. This info is unknown when serviceAdded is called but known when serviceResolved is called.

Finally, the method initializeParticipants is apparently never used. Can we suppress it ?

**Comment by lolodomo** [comment]
If I correctly understand OSGi declaration, referencing MDNSClient as static in MDNSDiscoveryService service makes sure that the bind method (setMDNSClient) will be called before every else and so before startBackgroundDiscovery is called.
Is it true ?

**Comment by kaikreuzer** [comment]
> The result is that the JmDNS instance stores this class twice and so serviceAdded is called twice for example.

I would expect the addServiceListener method to be clever enough to notice that it already has the same instance as a listener and thus does not add it a second time.

The [code in JmDNS](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/JmDNSImpl.java#L949) also seems to do so, although it looks fishy that it tests for the listener, but adds the status object... So this might actually be rather a but in JmDNS.

> I don't know if we have to move the code from serviceAdded to serviceResolved

If serviceResolved is always called, I think it makes sense to move the code there, yes.


> Finally, the method initializeParticipants is apparently never used. Can we suppress it ?

Yes, this is indeed outdated.

> My feeling is that we should called addServiceListener and removeServiceListener only in setMDNSClient
> I tested the different changes I mentioned and it is working well.

Then you didn't test the deactivation of the background discovery, since this is the feature why the code is there in startBackgroundDiscovery and stopBackgroundDiscovery. If background discovery is deactivated, the implementation MUST NOT find any mDNS services anymore. Imho the clean way to do so is to unsubscribe as a listener. A hacky option might be to simply not create DiscoveryResults in that situation.

**Comment by lolodomo** [comment]
As I understood, serviceResolved is not always called, only if resolution is possible.So having the code in serviceAdded and in serviceResolved is I think the best solution.

Ok I will keep all existing calls to addServiceListener, hoping a fix in JmDNS library in the future. But until this fix, even after background discovery is disabled, one listener will still be registered ! So in serviceAdded/serviceResolved, I will do a check that background discovery is enabled.

For my information, how the user can disable the background discovery ? I thought it was something hardcoded.

**Comment by maggu2810** [comment]
> For my information, how the user can disable the background discovery ? I thought it was something hardcoded.

Configuration property, see here:
https://github.com/eclipse/smarthome/blob/0d7a5c0/bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/AbstractDiscoveryService.java#L342

**Comment by lolodomo** [comment]
And this configuration property can be changed dynamically while OH is running and the change is correctly handled (meaning the background discovery is stopped) ?

**Comment by maggu2810** [comment]
It is not openHAB specific but "normal" OSGi service behaviour.

If the configuration is changed on runtime this method is called:
https://github.com/eclipse/smarthome/blob/0d7a5c0/bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/AbstractDiscoveryService.java#L354

**Comment by lolodomo** [comment]
@maggu2810 : thanks for the explanations.

**Comment by lolodomo** [comment]
PR #1745 fixed this issue.

By the way I opened an issue in JmDNS project.

**Comment by kaikreuzer** [comment]
Thanks, and I already fixed it today: https://github.com/jmdns/jmdns/pull/86

**Comment by lolodomo** [comment]
@kaikreuzer : cool.
Will remain to update the library used in openHAB.
When new library is included in the nightly builds, let me know and I will enable traces to check that all is ok.

**Comment by kaikreuzer** [comment]
The new lib might take a moment - last release is a couple of months old already; if my time allows, I will do a new release by the end of this week, let's see.
