### ISSUE TITLE
tmpfs lost memory on each build (npm)

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1758]
After a lot of builds I run into a "no space left on device" error.
I looked at the space usage of my mount points and realized that the space of /tmp (a tmpfs) is 100% used.
I have 87 directories starting with "npm-".
79 of them have a size of 50MB (79 * 50M = 3950M).

We should have a look at the npm's maven plugin configuration if there is a clean up option.

**Comment by maggu2810** [comment]
@kaikreuzer I assume this will also consume a lot of tmp space on the HIPP.
I remember that a few days ago the tmp of the Eclipse infra went out of space.

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you check this?

**Comment by aounhaider1** [comment]
This seems to be a npm issue (https://github.com/npm/npm/issues/6761). However, I noticed that tmp files are not even created if I use a local npm.i.e. set npm global flag to false (npm set global=false --local).

**Comment by maggu2810** [comment]
We are using Maven, so I would prefer that all temporary stuff for one build run should be stored into the build directory (target) instead of TMPDIR.
target is cleaned up on the clean phase.

So, can't we use the plugin "installDirectory" configuration and set it to a subdir of project build directory?
https://github.com/eirslett/frontend-maven-plugin/issues/18

**Comment by hakan42** [comment]
In another project of mine, I used the Environment Injector plugin ( https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin ) to set the variable

```
npm_config_tmp=${WORKSPACE}
```

as a Build Environment step. This caused those file to be moved from /tmp to the workspace itself where the normal workspace cleanup helps keeping things tidy.

**Comment by maggu2810** [comment]
IMHO we need a solution for the Maven build regardless if Jenkins is used or it is build on the command line on a workstation.
If the usage of "${project.build.directory}/npm" for temporary directories (e.g. npm_config_tmp or the some for the plugin configuration) then I would prefer to use it.

**Comment by maggu2810** [comment]
Perhaps interesting for someone: https://gist.github.com/phillipgreenii/7c954e3c3911e5c32bd0

**Comment by maggu2810** [comment]
Further links:
* https://gist.github.com/phillipgreenii/7c954e3c3911e5c32bd0
* https://github.com/npm/npm/issues/6855

I will create a PR soon.
