### ISSUE TITLE
Errors in Eclipse Smart Home projects

### ISSUE THREAD

**Issue by mathieubrochard** [eclipse/smarthome#1760]
Hi everyone,

I have installed the Eclipse Smart Home development tools by following the [documentation](http://www.eclipse.org/smarthome/documentation/development/ide.html).
When I launch the Eclipse IDE, I have a lot of errors in the Smart Home projects.

![eclipse_smart_home](https://cloud.githubusercontent.com/assets/10001635/16410257/f39b471a-3d21-11e6-9553-a54256ac1001.jpg)

I tried to clean all the projects according to the documentation but it didn't work.

I'm using **Eclipse Neon** and I have installed the development tools using the **Eclipse Installer by Oomph**.
I'm running **macOS 10.11.5** with **Java 1.8.0_91**

**Comment by davidgraeff** [comment]
@mathieubrochard Atleast Openhab2, an implementation of Eclipse smarthome is not compatible to eclipse neon (something with missing dependencies) and eclipse mars has to be used. This may be the problem here, too.

**Comment by maggu2810** [comment]
@davidgraeff If I am not wrong, openHAB supports the usage Eclipse Neon in its IDE setup: https://github.com/openhab/openhab-distro/commit/dac835719a856699f5472b0105ee6f0dbf5f2f20

**Comment by maggu2810** [comment]
@mathieubrochard Are you sure you have followed the steps 8 and 9?
Has the model generation been succeeded?

Can you try to manual trigger the model generation?
Project: org.eclipse.smarthome.model.codegen
File: Generate All Models.launch
Richt click
Run As: Generate All Models

After that (copy console if it fails) you should clean and rebuild all bundles.

**Comment by MHerbst** [comment]
@mathieubrochard I have just installed it in my Neon environment. After the Eclipse workbench finished its automatic work I executed Help/Perform Setup Tasks to execute the necessary model generaton. Then most projects were OK.
There seems to be a little problem with the delivered launch configuration. When I tried to start the openHAB runtime the first time it did not run because of a problem with mapdb. After editiing the launch configuration and adding all required plugins the runtime started.

**Comment by maggu2810** [comment]
It seems to me that you are mixing openHAB and Eclipse SmartHome here.
Eclipse SmartHome does not contain an openHAB runtime.

The setup files for Eclipse SmartHome and the openHAB distro differs, too.
So, please report the openHAB stuff to the openHAB issue tracker and the Eclipse SmartHome one here. :wink: 

Or do I miss-understand something?

**Comment by MHerbst** [comment]
Oh you are absolutely right. Should wear my reading glasses :-).  I wil remove the last paragraph.

**Comment by mathieubrochard** [comment]
Hi all, thanks for your responses.
I just followed these steps [here](http://www.eclipse.org/smarthome/documentation/development/ide.html).
I don't understand why you are talking about openHAB, what is the relation with Smart Home?

Thanks.

**Comment by maggu2810** [comment]
@mathieubrochard openHAB is an open source project that is based on the Eclipse SmartHome framework. It is not an Eclipse project but contains much more bindings. The Eclipse SmartHome is more a framework and not a product on itself, so the most people are using openHAB and the openHAB IDE instructions. But if you want to be independent of openHAB and develop / fix / improve stuff of the Framework, you should IMHO use the Eclipse SmartHome  IDE instructions that you already tried to use.

You should use the current stable release for the Eclipse IDE, so "Neon" is the correct one.
I am using Neon for my Eclipse SmartHome development on Linux machines.
It should be working.

Perhaps we can have a look at your problem step by step.

**Comment by mathieubrochard** [comment]
@maggu2810 Alright thanks for your explanations.
I will completely reinstall the Eclipse SH development environnement and will note all the suspicious messages.

**Comment by maggu2810** [comment]
Use "Neon" on step 3.
If step 8 and step 9 are done and there are still errors, please report it here.

**Comment by mathieubrochard** [comment]
So, here some news:

* I deleted the smarthome folder (created by the Eclipse Installer by Oomph).
* I deleted the .p2 folder (in my home directory)
* I reinstalled all the stuff according to the Eclipse Smart Home documentation
* After Eclipse launched, I did Help -> Perfom setup task
* I did Project -> Clean

It's working now 👍 
Did on macOS El Captain and Eclipse Neon.

**Comment by maggu2810** [comment]
Good news. Happy coding :wink:
