### ISSUE TITLE
No 'SPI-Provider' Manifest header. Skipping bundle

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1766]
I get the errors here below for the LIFX and Sonos bindings when running the latest snapshot

```
2016-06-28 18:24:36.781 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - Bundle Considered for SPI providers: org.eclipse.smarthome.binding.sonos
2016-06-28 18:24:36.781 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - No 'SPI-Provider' Manifest header. Skipping bundle: org.eclipse.smarthome.binding.sonos


2016-06-28 18:29:38.277 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - Bundle Considered for SPI providers: org.eclipse.smarthome.binding.lifx
2016-06-28 18:29:38.277 [INFO ] [g.apache.aries.spifly.dynamic.bundle] - No 'SPI-Provider' Manifest header. Skipping bundle: org.eclipse.smarthome.binding.lifx
```

**Comment by maggu2810** [comment]
That is not an error, it is an information.
Also this is not related to any ESH binding but to the openHAB runtime.
A bundle scans all other ones and informs about that one. As you can see the log message is written by Apache Aries (not available in the Eclipse SmartHome project at all).

**Comment by kgoderis** [comment]
@maggu2810 @kaikreuzer Sonos and LIFX are ESH bindings, and coincidently with this messages, these are the only bundles that fail to load in my setup whatever I do

**Comment by maggu2810** [comment]
The INFO message is produced by http://aries.apache.org/modules/spi-fly.html
So, if you want to get rid of the message, change the logger, stop the bundle org.apache.aries.spifly.dynamic.bundle (on Karaf: `bundle:stop org.apache.aries.spifly.dynamic.bundle`) or don't install it in your runtime.

The message is not produced by and there is no relationship to Eclipse SmartHome.

If you use install a bundle that contains a service tracker that logs "foo" for every new loaded service, it's is also not a issue if the services that are loaded but of the bundle that contains that noise service tracker.

IMHO the only correct place is the openHAB-distro if you want to get rid of the SPI Fly stuff at all.
But as this is already something that has been discussed before (christmas or new year if I remember correctly) I don't think it will be changed without someone that is willing to create a PR (and do it for every Karaf bump).

**Comment by kaikreuzer** [comment]
@maggu2810 Is this the discussion you refer to? https://github.com/openhab/openhab-distro/issues/16
I do not remember anything Aries specific besides that...

But the question indeed is: Why is this bundle at all installed/active - but this is something to discuss at openhab-distro indeed.

**Comment by kgoderis** [comment]
@maggu2810 the messages themselves are ok, I just noticed them and coincidently the LIFX and Sonos bundles were not loaded. e.g. Does one have to do with the other? From you answer I deduct that this is should not be the case, so I will further investigate why these binding refuse to load with the latest snapshot

**Comment by maggu2810** [comment]
> the messages themselves are ok, I just noticed them and coincidently the LIFX and Sonos bundles were not loaded

@kgoderis Ah, okay. No, that **should** not be related. :wink:

**Comment by maggu2810** [comment]
@kaikreuzer No, I refer to the service scanning discussion (it has not been the SPI Fly one, but also stuff like the Whiteboard extender and  META-INF/service scanning):
https://github.com/openhab/openhab-distro/issues/10

**Comment by kaikreuzer** [comment]
FYI: https://twitter.com/schneider_chris/status/748423161834770433
