### ISSUE TITLE
QueueingThreadPoolExecutor : Thread pool 'items' exhausted, queueing tasks now

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1767]
@kaikreuzer After your submission of the new QTPE class, I get the above WARN message pretty fast and very often when I start up the runtime.

After a while the runtime breaks down with  a

> java.lang.OutOfMemoryError: Java heap space

It seems to me that a lot of things are being queued here, but the queue is not being cleared or processed?

**Comment by kaikreuzer** [comment]
> but the queue is not being cleared or processed?

Which would mean that some queued jobs are not terminating.
Might be interesting to do a thread dump (using jstack on the command line) of such an situation.

**Comment by kgoderis** [comment]
Ah... After a bit of testing and study I come to the conclusion that when .items are processed with a lot of Items in them, the queuing mechanism is activated by https://github.com/eclipse/smarthome/blob/1257c94e1752a6caf5f8227efa7155d2ac824880/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java#L219 flooding the executor. There are after all only 5 threads in that pool, maybe a bit too little for larger installations like mine.

I did not see the OutOfMemory error anymore, but increased the JVM parameters
