### ISSUE TITLE
RefreshType.REFRESH Commands issued before Bridge Handler is initialised?

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1768]
In the (experimental) KNX 2.0 Binding I log the following line

`2016-06-28 18:06:29.950 [WARN ] [ding.knx.handler.KNXBaseThingHandler] - KNX bridge handler not found. Cannot handle command without bridge.`

when I start up the runtime. It is specific for the KNX binding, but is only issued when a Thing receives a Command, which it will ignore when the BridgeHandler is not present. As it seems, a RefreshType.REFRESH is issued to Things before the BridgeHandler is fully initiliazed.

Suggestion would be to have the default implementation of the ChannelLinked() check if the BridgeHandler exists before doing the handleCommand() call. This assumes that a Bridge is necessary for a Thing in order to operate, which AFAIK is the case for all current bindings that use the Bridge/Thing pattern

**Comment by maggu2810** [comment]
The lifecycle for bridge and thing handler relationship needs to be changed and I think we already agreed about this one.
Please have a look at this issue: https://github.com/eclipse/smarthome/issues/1479
