### ISSUE TITLE
RulesJvmModelInferrer :  Duplicate field WARNings

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#1769]
With the latest snapshot, when starting the runtime I see a massive amount of messages like:

`2016-06-28 18:07:51.982 [WARN ] [.rule.jvmmodel.RulesJvmModelInferrer] - Duplicate field: 'BathroomKidsSonosVolume'. Ignoring 'org.eclipse.smarthome.core.library.items.DimmerItem'.`

**Comment by lolodomo** [comment]
It is a duplicate of #1574.

**Comment by kaikreuzer** [comment]
FTR: I have just fixed an issue (https://github.com/eclipse/smarthome/issues/2095), which caused these messages - yours might have been due to the same root cause.
