### ISSUE TITLE
RawType base64-encoded value is written to log file every time state changes

### ISSUE THREAD

**Issue by dominicdesu** [eclipse/smarthome#1798]
Hi,

whenever an item changes, the ItemStateChangedEvent is logged (on info level), containing the old and the new state of an item:
`itemName + " changed from " + oldItemState.toString() + " to " + itemState.toString();`

If a RawType item has changed, the toString method of the RawType outputs its Base64-encoded value:
`PortableBase64.getEncoder().encode(bytes);`

This is not really nice as I don't need the binary file in my log file and this can increase the size of the log file quite fast.

**Comment by kaikreuzer** [comment]
I agree, this should be avoided.
It would be nicest to implement RawType.toString() so that it comes up with something short like "binary content", but as the toString method is also used to have a full string representation from which types can be reconstructed again, this won't work.
So the better fix is probably to change the toString method of the item events in a way that they behave differently for RawTypes.

**Comment by thhart** [comment]
> but as the toString method is also used to have a full string representation from which types can be reconstructed again, this won't work

Can you explain this further please. Sorry for being this direct but IMHO it is not very good design to have a full Base64 encoding nor a full data return in a toString() method.

**Comment by maggu2810** [comment]
IIRC:
Currenty every type should have a static method valueOf(String) that returns an instance of that type.
The instance should be equal to the one the toString method is called to receive the string.
So `Type.valueOf(type.toString()).equals(type)` should be true all the time.

**Comment by maggu2810** [comment]
I think there are two options:
We could create a static function that returns a simplified string of the state for debugging purpose etc.
It can then skip the value encoding for RawType
```java
    protected String getSimpleStateString(final State state) {
        if (state instanceof RawType) {
            return "<skip-raw-type-encoding>";
        } else {
            return state.toString();
        }
    }
```
This method could be used in [Group]ItemStateChangedEvent or whenever a message is logged.

Okay, but that does not look good as a static method does need to decide how a state should be logged and not the state class itself.

> Currenty every type should have a static method valueOf(String) that returns an instance of that type.
The instance should be equal to the one the toString method is called to receive the string.
So Type.valueOf(type.toString()).equals(type) should be true all the time.

For the first step we could (for the transition phase)
* change the Type interface to define two methods `toStringFull()` and `toStringSimple()`
* `toStringSimple()` should return a simplified string that does not need to contain the whole state (e.g. for RawType the first bytes + "...")
* `toStringFull()` behaves similar as the current `toString()` method (full string representation of the internal type)
* `toString()` logs a message + stack trace that one of the other methods should be used (e.g. info or debug level) AND returns the value of `toStringFull()`
* [Group]ItemStateChangedEvent could be changed to use `toStringSimple()`

If this has been done and all usages of `toString()` has been changed to full or simple (no code is broken in this time as toString() works as before just log some info to change the usage), we could use the refactor mechanism of the IDE to change toStringSimple to toString again (if this is what we want).

WDYT?

**Comment by kaikreuzer** [comment]
I agree that option 1 is not really clean as we have some special handling in the event class for a certain type. Nonetheless, I wonder if we could say that RawType qualifies to be treated exceptionally - then we can consider this option to be the simplest way to solve the issue.

For option 2, I am not sure if we manage to reach everyone that relies on the current toString() behavior; planning to change it some time in the future means a backward compatibility breaking change, which I would like to avoid. Woudn't it be also an option to reduce it to introducing a new method Type.toSimpleString() and use this in the event class, while keeping toString() untouched?

**Comment by maggu2810** [comment]
> Woudn't it be also an option to reduce it to introducing a new method Type.toSimpleString() and use this in the event class, while keeping toString() untouched?

Sure. It is only about that toString is the convenient method for logging (e.g. slf4j calls toString() implicitly etc.).

> For option 2, I am not sure if we manage to reach everyone that relies on the current toString() behavior; planning to change it some time in the future means a backward compatibility breaking change, which I would like to avoid.

We can use a very long transition phase and state that toString should not be used serialization if the whole internal information should be kept.
How is it different from all the other methods that are marked deprecated to remove them in e.g. after a new major release?

**Comment by kaikreuzer** [comment]
> How is it different from all the other methods that are marked deprecated to remove them in e.g. after a new major release?

Well, most of the others were introduced as part of new APIs that were still under development and thus changed. The behavior of toString() is the same since the first commit in 2010 and thus has been a stable since the very beginning. Hence I feel that the risk is much higher to do changes to this, in comparison to changing newly introduced classes that not many people are anyhow familiar with yet.

**Comment by maggu2810** [comment]
I have done some changes on my working copy, but know I don't know how to proceed.
Let's assume there is a full and a simple string generation method (we don't neet to care is toString() is the same as full or not, I just want to use clear names here).

At which places we do need a full string and where is a simple sufficient?
Does an Event require, that the one that receives the event is able to create a type that is equal to the data in the event?

Here some usages:
* at org.eclipse.smarthome.core.items.events.ItemEventFactory.createStateChangedEvent
* at org.eclipse.smarthome.core.items.events.ItemEventFactory.createStateEvent
* at org.eclipse.smarthome.core.items.events.ItemStateChangedEvent.toString
* at org.eclipse.smarthome.core.items.events.ItemStateEvent.toString
* at org.eclipse.smarthome.model.rule.jvmmodel.RulesJvmModelInferrer$1$2.accept
* at org.eclipse.smarthome.model.script.interpreter.ScriptInterpreter.getStateOrCommand

The question is where can we use the simple version?

**Comment by kaikreuzer** [comment]
> Does an Event require, that the one that receives the event is able to create a type that is equal to the data in the event?

Up to now, yes. E.g. the UIs get the event stream and dynamically update their views without the need to do any further requests to the server. The PaperUI also supports this for the image item type already.

We hence must make sure that the "payload" of the events is complete. So the following occurences need the full information:
- org.eclipse.smarthome.core.items.events.ItemEventFactory.createStateChangedEvent
- org.eclipse.smarthome.core.items.events.ItemEventFactory.createStateEvent

while 
- org.eclipse.smarthome.core.items.events.ItemStateChangedEvent.toString
- org.eclipse.smarthome.core.items.events.ItemStateEvent.toString
could be simple.

The ones in rules/scripts probably are not applicable to raw types at all (you won't script an image...), but in general these should be the full version as well.

**Comment by sjka** [comment]
with #2230 being merged this once is fixed, or did I miss anything?
