### ISSUE TITLE
paperUI does not show all config properties

### ISSUE THREAD

**Issue by marcelrv** [eclipse/smarthome#1802]
In the current OH nighties I'm getting empty parameters:
![image 5](https://cloud.githubusercontent.com/assets/5871213/16570821/3aa52000-424e-11e6-8422-1032cb305f01.png)

in the REST interface & in habmin2 these seem to be visible like earlier.

![image 6](https://cloud.githubusercontent.com/assets/5871213/16570841/bcd4a78a-424e-11e6-8c6c-ad7f2fdccf8c.png)

no errors in console outside of these (but they appear for both the visible config parameters as for the blank ones)

**Comment by aounhaider1** [comment]
Can you please provide the config-description of the thing? I am unable to reproduce this issue using normal things.

**Comment by marcelrv** [comment]
sure
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.max/ESH-INF/thing/thing-types.xml
