### ISSUE TITLE
Wrong method name in RuleTempalte

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#1830]
The method RuleTempate.getConfigurationDescription(), which returns a list of ConfigurationDescription objects, should be renamed to RuleTempate.getConfigurationDescriptions() as in the  Rule.getConfigurationDescriptions().
On the other hand in the JSON API for ConfigurationDescription we are using configDecriptions field.
We can rename then into getConfigDescriptions() methods. What do you think?

**Comment by maggu2810** [comment]
If we return a collection I assume it is okay (at least for me) to use the plural in the method name.
So, okay for me.
