### ISSUE TITLE
Thing detail page should show Thing label

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1832]
The label is currently not displayed on the detail page:

<img width="657" alt="screen shot 2016-07-08 at 12 13 57" src="https://cloud.githubusercontent.com/assets/3244965/16684476/865aac36-4505-11e6-8f3e-31fc1307d6db.png">

I would suggest that it should look similar to the thing list entry:

<img width="811" alt="screen shot 2016-07-08 at 12 15 00" src="https://cloud.githubusercontent.com/assets/3244965/16684491/9f2d4016-4505-11e6-9fc8-72b23431fbad.png">

i.e. have the label be the first line in bold and have the type (here "Hue Bridge") in a small font underneath (the thing id is already shown in the page header, so no need to repeat it here).

**Comment by aounhaider1** [comment]
Should I display something like "no label" or "unknown" when a thing does not have a label?

**Comment by kaikreuzer** [comment]
What do we show in the thing list? Probably nothing - so I would do it the same way here.
