### ISSUE TITLE
xml <thing-type/channels/channel>: Allow optional channels

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#1836]
Hi,
I feel the need that a <thing-type> described in the ESH-INF directory of an addon should allow to define channels, which are optional (may be created dynamically or may be absent). At the moment you can do this:
```
<thing-type>
  <channels>
    <channel id="0" typeId="0"/>
  </channels>
</thing-type>
```
and I propose to allow something like this:
```
<thing-type>
  <channels>
    <channel id="0" typeId="0" optional="true" />
  </channels>
</thing-type>
```

This should have the effect, that the framework does not auto generate such a channel if a corresponding thing is created. The UI on the other side should list those channels.

I have a lengthy forum post with a use-case located here: https://www.eclipse.org/forums/index.php/m/1737460/#msg_1737460

Please close this issue, if this does not belong here.

**Comment by kaikreuzer** [comment]
> Please close this issue, if this does not belong here.

Yes, for architectural discussions, the forum is the right place for now.
