### ISSUE TITLE
BasicUI requires manual reload to reflect actual item status

### ISSUE THREAD

**Issue by fivesails** [eclipse/smarthome#1842]
I set up openHAB on a VM with the following details:
OS: Debian GNU/Linux 8.5 (jessie)
Java: Oracle Java
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

openHAB: openhab-offline-2.0.0-SNAPSHOT from 2016-07-01

openHAB ist connected to KnX in tunnel mode.

Some items are defined for testing purposes:
`Switch Test_Multi_OR_Input_1                      "Input 1"               { knx="12/0/10" }`
`Switch Test_Multi_OR_Input_2                      "Input 2"               { knx="12/0/11" }`
`Switch Test_Multi_OR_Input_3                      "Input 3"               { knx="12/0/12" }`
`Switch Test_Multi_OR_Output_openHABRule           "Output openHAB Rule"   { knx="12/0/25" }`

Everything works fine with the ClassicUI.
With BasicUI the browser window has to be reloaded manually to reflect changes.

Therefore my 2 questions:

What is the current development status of BasicUI?

I was searching GitHub, but couldn't find the sources for the UI, could you give me a URL?

Thank you in advance,

Erik

**Comment by maggu2810** [comment]
> I was searching GitHub, but couldn't find the sources for the UI, could you give me a URL?

Is this what you are looking for:
https://github.com/eclipse/smarthome/tree/master/extensions/ui

**Comment by kaikreuzer** [comment]
Apart from https://github.com/eclipse/smarthome/issues/1166, status updates work well in the Basic UI, so if nothing happens, it must be due to your configuraiton.

**Comment by fivesails** [comment]
First of all, thank for your replies!

> Apart from #1166, status updates work well in the Basic UI, so if nothing happens, it must be due to your configuraiton.

My configuration for the BasicUI is


        org.eclipse.smarthome.basicui:defaultSitemap=fasan
        org.eclipse.smarthome.basicui:iconType=svg
        org.eclipse.smarthome.basicui:enableIcons=true
        org.eclipse.smarthome.basicui:condensedLayout=true
        org.eclipse.smarthome.basicui:capitalizeValues=false


I don't see what of the above could lead to a misconfiguration of the BasicUI and at the same time ClassicUI working fine.

**Comment by kaikreuzer** [comment]
I just tested it with openhab-offline distro 401 and the demo packaging. Having two browser windows side by side, I switch something in the Classic UI and the toggle switches in the Basic UI, so all looks fine.
Is it maybe browser specific? I used Chrome for testing.

**Comment by fivesails** [comment]
First, I thought the browser might be a point (I was using Safari 9.11 on Mac OS X 10.11.5). However, latest tests with openhab-offline distro 403 and Chrome (v 51.0.2704.106 (64-bit) on the above mentioned OS), lead to the same result. I will do more testing and will post the results.
