### ISSUE TITLE
Group functions for rollershutters show wrong value

### ISSUE THREAD

**Issue by hazzeh** [eclipse/smarthome#1845]
There is a "bug" for the group functions (MAX/MIN/AVG..) for rollershutters I think.
Or is it by design?
When using group functions, for example MAX, the group value will be in decimal, not percent.
items:
Group:Rollershutter:MAX gBlinds "Blinds"

rest:
{
  "members": [
    {
      "link": "http://localhost:8080/rest/items/blind1",
      "state": "59",
      "type": "RollershutterItem",
      "name": "blind1",
      "label": "Blinds",
      "tags": [],
      "groupNames": [
        "gBlinds"
      ]
    }],
  "groupType": "Rollershutter",
  "link": "http://localhost:8080/rest/items/gBlinds",
  "state": "0.59000000",
  "type": "GroupItem",
  "name": "gBlinds",
  "label": "Blinds",
  "category": "rollershutter",
  "tags": [],
  "groupNames": []
}

If it is a bug, I've got a fix here: https://github.com/hazzeh/smarthome/tree/decmaltype_for_rollershu

**Comment by kaikreuzer** [comment]
Looks indeed like a bug to me, happy to accept your fix as a PR!

**Comment by maggu2810** [comment]
Could this be related to #1514?

**Comment by hazzeh** [comment]
Yes, it seems to be the same problem. My PR makes the same change for RolleshutterItem as #1514 did for DimmerItem.
