### ISSUE TITLE
IDE Tooling error

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#1848]
I'm getting the following error when the IDE starts. It's causing some significant issues in the IDE (eg inability to set breakpoints!).

![image](https://cloud.githubusercontent.com/assets/1041475/16715783/a1942ddc-46e1-11e6-9ea5-fc9f53a1add2.png)

This started today when I ran all the various updates (ie resynced all repos and ran the setup tasks) and I've not managed to get rid of it. I've also tried a fresh install and it's still there. Some things online seem to indicate issues with groovy versions?

**Comment by cdjackson** [comment]
Another error during save - again - with a clean install.

![image](https://cloud.githubusercontent.com/assets/1041475/16716041/d6a213ac-46e8-11e6-9fd7-a18920ea9599.png)

**Comment by kaikreuzer** [comment]
Just to be clear: This is a completely clean install of the ESH IDE (not OH2) using the Eclipse Installer and Eclipse Neon as a base?

**Comment by cdjackson** [comment]
This was a fresh install of the IDE and I ticked ESH and OH2 distro’s. Do you want me to move this under OH2?

**Comment by kaikreuzer** [comment]
Well, yes, if this issue is NOT about https://www.eclipse.org/smarthome/documentation/development/ide.html, then better report it at openhab-distro. Would be interesting though if the same happens for the ESH IDE.

**Comment by cdjackson** [comment]
Well, I used the instructions on that page, but I ticked the boxes in the openHAB2 github section. This includes ESH…

**Comment by cdjackson** [comment]
I just installed the ESH runtime and it's got the same issue, so reopening...

**Comment by maggu2810** [comment]
Hm, interesting.
I tested the IDE installation two days ago and it worked for me.
See: https://www.eclipse.org/forums/index.php?t=msg&th=1078937&goto=1737544&#msg_1737544

**Comment by cdjackson** [comment]
Maybe it's an issue at my end, but I upgraded my existing IDE, and then did two fresh installs (one for OH2 and one for ESH) and they all do the same thing. It is unusable really as it won't save files without errors and wont set breakpoints.

All the errors seem to be related to SubMonitor issues such as the following.

https://github.com/groovy/groovy-eclipse/issues/172

**Comment by maggu2810** [comment]
Have you choosen Neon and a Java 8 on your fresh installation?

**Comment by maggu2810** [comment]
FYI: It makes a difference if you are using Eclipse SmartHome IDE setup or openHAB + ESH.
There are different setup files (instructions for the Installer):
* https://github.com/eclipse/smarthome/blob/master/targetplatform/EclipseSmartHome.setup
* https://github.com/openhab/openhab-distro/blob/master/launch/openHAB2.setup

**Comment by kaikreuzer** [comment]
I have just installed the ESH IDE from scratch and everything works smoothly, so I very much assume it is a local problem with your system, @cdjackson. Try to also start with a clean bundle pool, maybe you have some corrupted jar file in there. Make sure to use Neon, not Mars.

**Comment by cdjackson** [comment]
Strange - this initially started on an existing system when the setup tasks were run but two clean installs have done the same. Do you know if there's a common area where the bundles are stored (on a Mac) that I could/should purge.

Thanks.

**Comment by kaikreuzer** [comment]
> Do you know if there's a common area where the bundles are stored

Yes, the bundle pool that I mentioned above. You choose it on the first page of the installer:

<img width="810" alt="screen shot 2016-07-11 at 09 26 52" src="https://cloud.githubusercontent.com/assets/3244965/16722842/a46f989e-4749-11e6-8fb7-0e05cd8f5450.png">

**Comment by cdjackson** [comment]
Thanks.

**Comment by jspuij** [comment]
For anyone bumping into this: The default version in the installer on OSX seems to be Mars. Reinstalling (a.t.m.) Oxygen solved the problem. Maybe this should be a bit clearer on this page: http://docs.openhab.org/developers/development/ide.html. Saves a reinstall.
