### ISSUE TITLE
Documentation automation schema

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1862]
Perhaps I am wrong, but I assume at least the visibility of the module-type schema is outdated:
https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/rules/ModuleTypes_schema.json

**Comment by danchom** [comment]
Yes it should be updated. 
@Ani please update the json schema.

**Comment by danchom** [comment]
It is fixed by PR #1987
