### ISSUE TITLE
Hue binding: things remaining in INITIALIZING state

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1869]
When starting OH, I noticed that my hue bridge thing is ONLINE (as expected) but my hue light things remain in INITIALIZING state.

HueLightHandler:initialize looks really weird to me. If run when the bridge is in state INITIALIZING, it will apparently set the thing state to INITIALIZING ! At my knowledge, a binding should only set state to ONLINE or OFFLINE.
And there is probably rare cases while state is not set at all in this method.
And finally just a remark, this binding does not implement bridgeStatusChanged.

**Comment by lolodomo** [comment]
In HueBridgeHandler:onConnectionResumed, just after setting state to ONLINE, there is a loop on all things to call initialize. I think this code should be suppressed and replaced by implementing bridgeStatusChanged on HueLightHandler.

**Comment by kaikreuzer** [comment]
> If run when the bridge is in state INITIALIZING, it will apparently set the thing state to INITIALIZING

You are right, that looks buggy. The code seems to assume that it is only called if the bridge is either ONLINE or OFFLINE. Something that is only true once #1479 is implemented.

**Comment by lolodomo** [comment]
If you want, I can provide a fix, I think that is easy to fix.

**Comment by kaikreuzer** [comment]
Will it also fix the issue that you have reported?

**Comment by lolodomo** [comment]
What other issue ? #1863 ?
I propose to fix this issue, that is the initialization of the binding. I will just fix the initialize method, add the method bridgeStatusChanged and change the method onConnectionResumed.

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/eclipse/smarthome/pull/1870
