### ISSUE TITLE
ThingHandler.channelLinked() not called for all channels after handler initialization

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1871]
The [documentation](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-handler.html#channel-links) reads:

> The channelLinked method is called, even if the link existed before the handler was initialized. It will be called only after the initialized method has been executed successfully

According to https://github.com/openhab/openhab2-addons/issues/1125, this does not seem to be the case anymore.

Related to this, the JavaDoc of 'ThingHandler.channelLinked()' is not very helpful and it should imho contain the same information as the documentation.

**Comment by kaikreuzer** [comment]
@sbussweiler Can you take that into the scope when working on https://github.com/eclipse/smarthome/issues/1479?

**Comment by sbussweiler** [comment]
@kaikreuzer I can do...
