### ISSUE TITLE
hue binding does not support switchable sockets anymore

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1874]
Since the switch to generic types, the hue binding does not support switchable sockets thus as [this one](http://www.philips.de/c-p/6916531PH/livingwhites-adapter) anymore.

See https://community.openhab.org/t/hue-power-socket-dimmer-not-longer-supported-as-thing/12453.

**Comment by kaikreuzer** [comment]
@afuechsel I assume this is a regression caused by https://github.com/eclipse/smarthome/pull/1652.

**Comment by afuechsel** [comment]
As I have no such device, I have no clue why it is not working. Can you give some more details, how it was previously configured? What was the thing type of this device?

**Comment by foxytocin** [comment]
Hi,
it was automatically configured with paper ui. In the past it was shown up in the inbox.

In the items file i used it as dimmer item. Because the socket has two modes. There is an switch on the backside where you can switch between on/off or dimmer mode for the device.

**Comment by afuechsel** [comment]
@foxytocin what was the thing type of the discovered thing?

**Comment by foxytocin** [comment]
Can check this on weekend. Because i'am away from my installation.

**Comment by kaikreuzer** [comment]
It seems the Philips documentation isn't complete :-/
The plug has the type "Dimmable plug-in unit", see [here](https://community.smartthings.com/t/updated-as-of-march-24-2016-hue-lights-groups-scenes-oh-my/36105/165).
PR #1913 adds this.

**Comment by afuechsel** [comment]
well, should we think about a fallback mechanism if we get an unsupported type? But fallback to what?

**Comment by kaikreuzer** [comment]
No idea - you already print out a log message as a fallback - I guess, this is the best we can do.
