### ISSUE TITLE
Lazy activation of esh.core.thing.xml

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#1876]
The lazy activation of core.thing.xml breaks the runtimes based on Bnd.

The core.thing.xml bundle contains no public class, so it will not be activated on the first usage -- as there is no one.
It also does not contain any DS -- if my reading of some comments is correct, a DS could also lead also to an activation.

It seems "Peter Kriens" and "Neil Bartlett" agreed that it is okay to not activate such bundles:
* https://groups.google.com/forum/#!topic/bndtools-users/QosyuwVcwVw
* https://github.com/bndtools/bnd/issues/141

I know we used the lazy activation for the models again, as it is needed by Eclipse RCP application.
But do we need a lazy activation for core.thing.xml?

**Comment by kaikreuzer** [comment]
sorry, I must have added that accidentially.
But I hope bnd is fine with lazy activation for any bundle that exports a package or contains a DS component?

**Comment by maggu2810** [comment]
I will have a look at if one of these guys can give us more information about that topic.
