### ISSUE TITLE
[HUE] Binding setup via UI?

### ISSUE THREAD

**Issue by polarathene** [eclipse/smarthome#1893]
To setup a HUE Bridge, the binding needs to be installed and then openHAB needs to be restarted with the user pressing the pairing button on the bridge to authenticate with openHAB so it can control HUE bulbs. 

Is the restart of openHAB required or would it be possible to trigger the pairing/authentication via UI button in config instead? If restarting of openHAB is required, likewise would it not make sense to have a UI button in PaperUI to trigger this? 

I imagine the latter can be setup with a button that triggers a rule/script to restart openHAB, though sounds like a useful feature to have by default? Some sort of pairing UI(with waiting/success/failure visual status) I would assume would be useful for more than just the HUE binding.

**Comment by kaikreuzer** [comment]
Please discuss issues around openHAB at https://community.openhab.org/ and only enter bug reports here if a bug in ESH has been identified.
Afaik, there is no need to restart openHAB either, the binding simply keeps trying until the user has pressed the pairing button on the bridge.
