### ISSUE TITLE
Use OSM for editing a location item in Paper UI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1922]
A location item is rendered with an OSM map in the Paper UI. If the item is editable, currently the user has to manually edit the coordinates.
It would be nice if he could click on the map, which then opens full screen and he could chose a location directly on the map.

**Comment by sjka** [comment]
addressed by #3730

**Comment by htreu** [comment]
Since we can not support OSM maps in ESH directly, how should we proceed here?

**Comment by kaikreuzer** [comment]
With https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/notes.md#paper-ui-location-support in place, this can be closed, thanks.
