### ISSUE TITLE
Paper UI: configuration parameters missing

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1927]
Using offline snapshot 426, editing thing configuration, some of the parameters are missing.
I first thought it was all parameters I have set in my thing files but there is no absolute logic in fact.

**Comment by kaikreuzer** [comment]
See also https://community.openhab.org/t/new-install-openhab2-zwave-port-path-missing/12686

**Comment by maggu2810** [comment]
@kaikreuzer Thanks for an example that could be used for analysing.

**Comment by kaikreuzer** [comment]
The example to reproduce is given in https://community.openhab.org/t/new-install-openhab2-zwave-port-path-missing/12686 - it happens with the Z-Wave binding.
The parameter definition in there is
```
			<parameter-group name="port">
				<context>communication</context>
				<label>Port Configuration</label>
				<description></description>
			</parameter-group>

            <parameter name="port" type="text" required="true"
                groupName="port">
                <label>Serial Port</label>
                <description>Set the serial port used to access the Z-Wave stick</description>
                <default></default>
            </parameter>
```

**Comment by maggu2810** [comment]
I have already seen it. That you I said thanks, that you have given one (I really want to say thanks and not blame you that you should add one).. :wink:

**Comment by kaikreuzer** [comment]
Ah, ok :-)
