### ISSUE TITLE
Paper UI: no channels for hue things

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1928]
With offline distro 426, sometimes Paper UI does not display any channels for my hue things.
My things and items are defined in config files.

**Comment by kaikreuzer** [comment]
Please analyze this in more detail and post an example things-file with which it can be reproduced.
Is it specific to hue? Does it happen for other things as well? What does "sometimes" mean?

**Comment by lolodomo** [comment]
I think I have seen that only with hue things.
If I start several times OH2, sometimes hue things have channels displayed in Paper UI, sometimes not.
I will give you my thing file later today but it is basic with a bridge and 2 lights.

**Comment by lolodomo** [comment]
With offline distribution 430, I am not able to reproduce this issue. That's weird.
My hue things even always initializes correctly.

**Comment by lolodomo** [comment]
I was finally able to reproduce the issue but it seems to be a consequence of issue #1926.
If I have not the exception, the channels are present. When I have this exception (not often), the channels are missing.

**Comment by kaikreuzer** [comment]
Ok, thanks. So let's see if a fix of #1926 solves this as well.

**Comment by sjka** [comment]
@lolodomo did it?

**Comment by lolodomo** [comment]
I will check again but yes I think this issue is gone. I will close it myself before the end of week.

**Comment by lolodomo** [comment]
Ok, this issue is not reproduced. Fix #1926 certainly fixed it. I close the issue.
