### ISSUE TITLE
Default thing name

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1939]
Could it be possible to have a default thing name when not defined in the config files ?
For my NTP and astro things, I defined no name in my config files.
After starting openHAB, sometimes my NTP thing has no name, sometimes it has "NTP Server" as name.
My astro thing has sometimes no name, sometimes "Astro sun data"..
The behavior should be always the same.

**Comment by maggu2810** [comment]
This could be related to #1550

**Comment by kaikreuzer** [comment]
Very likely, so I'd suggest to close this as duplicate.

**Comment by lolodomo** [comment]
I added a name in my config file ;)
