### ISSUE TITLE
Enhancement proposal for UPnP transport service (GENA subscription)

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1941]
I would suggest to add 2 methods in interface UpnpIOParticipant: onSucceededSubscription and onFailedSubscription.
Of course, class UpnpSubscriptionCallback should be adjust in consequence to trigger these new methods.

These changes would allow any binding using the UPnP transport service to be informed if a GENA subscription failed or succeeded.

**Comment by kaikreuzer** [comment]
Ok for me, but I would suggest to call the methods onSubscriptionSucceeded and onSubscriptionFailed.
Feel free to create a PR for it.

**Comment by lolodomo** [comment]
I changed my mind a little, I think all this should be managed by the transport UPnP service and what we need is just a new method indicating if a service subscription is active or not.
So I propose now to add this method to the UpnpIOService interface:
```
    /**
     * Indicate whether a GENA subscription is active
     * 
     * @param participant - the participant of the subscription
     * @param serviceID - the UPNP service we want to check subscription
     */
    public void isSubscriptionActive(UpnpIOParticipant participant, String serviceID);
```
This change will not require any change in the bindings using the transport UPnP service.

**Comment by lolodomo** [comment]
The UpnpIOParticipant interface is actually used by 3 bindings:
- Wemo in eclipse smarthome repo
- Sonos in eclipse smarthome repo
- Samsungtv in openhab2-addons repo

If I change the interface to add a new method, these 3 bindings will have to be updated. How can I schedule the changes in the 2 repo without breaking the nightly builds ?

Finally I would like to add just a new method named onSubscriptionResultReceived with the subscription as parameter and a boolean indicating whether the subscription was established or not.

**Comment by kaikreuzer** [comment]
> How can I schedule the changes in the 2 repo without breaking the nightly builds ?

You can prepare a PR for the openhab2-addons repo and I will make sure that I merge it as soon as the ESH changes are released to be included in openHAB. (see e.g. https://github.com/openhab/openhab2-addons/pull/1140 where the same is done).

**Comment by kaikreuzer** [comment]
> Finally I would like to add just a new method named onSubscriptionResultReceived with the subscription as parameter and a boolean indicating whether the subscription was established or not.

@kgoderis Is that approach ok for you?

**Comment by kgoderis** [comment]
@lolodomo For my understanding, onSubscriptionResultReceived is same as `public void isSubscriptionActive(UpnpIOParticipant participant, String serviceID)` you mentioned before, or is rather meant to be a callback?

@kaikreuzer I am ok with this, but independently from this I would try to look into the jupnp http time-out issue, and see if we should not add some time-out parameter to the method to add subscriptions, and feed that time-out equally to downstream to the mechanism that actually makes the http call

**Comment by lolodomo** [comment]
@kgoderis : you're right, that is the same idea. In fact, I hesitated between two implemntation options and explained the two in the discussion:
- option 1: just adding a new method in the UPnP service; the bindings should call this method when they want to know if a subscription is active or not.
- option 2: enhancing the UpnpIOParticipant interface to add a new notification method. The bindings will be immediately notified when a subscription is estabilshed or failed.

Option 1 is the easiest to implement (only one file to modify) and avoid to update the different bindings. The new method can be used or not by each binding.
Option 2 is the best I thing but requires to update the 3 existing bindings using this interface (the change is minor, just implement the new interface method).

I am now in favor of option 2.

**Comment by kgoderis** [comment]
@lolodomo me too. For the other 2 bindings just provide a standard implementation of the method that does nothing at all. That's 2 lines of code ;-)

**Comment by lolodomo** [comment]
Let's go for option 2.

I will wait for the merge of my PR #1957 before proposing a PR for this enhancement.

**Comment by lolodomo** [comment]
Ok, I have implemented the updated API and used it in the Sonos binding to restart the GENA subscriptions when tey failed. It works well.
I will provide a PR when my pending PR for Sonos binding is merged.

Of course, this should not prevent from searching what's wrong in jupnp.

**Comment by lolodomo** [comment]
Enhancement done and merged.
