### ISSUE TITLE
Sonos binding: cannot play a Spotify album as Sonos favorite

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1945]
Using the "favorite" channel, I can play a Spotify track set as a Sonos favorite but I cannot play a Spotify album set as a Sonos favorite.
This could be due to the fact that few services like Spotify require that the content of the favorite to be put in the queue.

**Comment by kgoderis** [comment]
When initially developing the binding the Spotify service was not yet available on Sonos. In fact, few services were, and so I did not spend much time on that. If you could propose a PR for this.....

**Comment by lolodomo** [comment]
Ok, I fixed this one too, there was just a little thing to change in playFavorite.
With the fix, all favorite that is a container object will be "injected" in the queue.

I will try to test with all kinds of things in favorite.

I will provide a new PR fixing this issue as soon as my previous PR is merged.

**Comment by lolodomo** [comment]
PR #1957 will fix this issue.

**Comment by kaikreuzer** [comment]
fyi, it is better to say "fixes #1945" in a comment on #1957, because this will enable the github "auto-close" feature and will also automatically add a link here.

**Comment by lolodomo** [comment]
PR fixing this issue is now merged.
