### ISSUE TITLE
DiscoveryServiceRegistry: expose DiscoveryService timeout

### ISSUE THREAD

**Issue by ivivanov-bg** [eclipse/smarthome#1947]
Currently when a DiscoveryService is registered a timeout in seconds is specified.

This timeout however is not accessible at service use time (for eg. to show some loading indicator to the end-user).

It will be good to have a method created in the DiscoveryServiceRegistry to retrieve the maximum discovery step timeout (as there might be more than one service available) by thingTypeUid (or binidngId)

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/eclipse/smarthome/pull/1964.
