### ISSUE TITLE
Text type configuration not working

### ISSUE THREAD

**Issue by thhart** [eclipse/smarthome#1948]
I have created a config-description as seen below, unfortunately it looks like only integer configuration is working currently, when I want to configure my thing only the "poll" parameter is working:

![paper ui - mozilla firefox_144](https://cloud.githubusercontent.com/assets/2632538/17298759/97ca3aea-580b-11e6-9ab5-d82b789869bb.png)

```
<config-description uri="thing-type:camera:camera">
        <parameter name="poll" unit="s" type="integer">
            <label>Poll time:</label>
            <description>Interval of image being refreshed in seconds</description>
            <default>5</default>
        </parameter>
        <parameter name="urlSnapshot" type="text" required="true">
            <label>Snapshot Url:</label>
            <description>Url for receiving the camera snapshot</description>
            <default>http://ip/image.jpg</default>
        </parameter>
        <parameter name="urlVideo" type="text" required="true">
            <label>Video Url:</label>
            <description>Url for receiving the camera video. ..TODO..</description>
            <default>http://ip/image.mjpg</default>
        </parameter>
</config-description>

```

**Comment by lolodomo** [comment]
It has been fixed recently.
Do you use a very recent distribution ?

**Comment by thhart** [comment]
I use the development environment under Eclipse, I tried to update all git resources but I am not quite sure about the Runtime itself, how to check the correct version/build and update the Runtime?

**Comment by kaikreuzer** [comment]
For the ESH IDE, please see https://www.eclipse.org/smarthome/documentation/development/notes.html#paperui-development-jshtml on how to work on the latest Paper UI sources.
If you are on the OH2 IDE, please make sure that you have reloaded the target platform. It should show a version from Aug 1 for the ESH bundles:

<img width="458" alt="screen shot 2016-08-02 at 11 29 50" src="https://cloud.githubusercontent.com/assets/3244965/17323964/7b5705ac-58a4-11e6-800c-b353d695da0a.png">
