### ISSUE TITLE
Breaking API Change in #1933

### ISSUE THREAD

**Issue by chr-fritz** [eclipse/smarthome#1951]
The PR #1933 removes the method `withMessageKey()` and introduces the new method `withMessageKeySuffix()`. This breaks the compatibility with the ESH version 0.8.0. Better would be to set the method `withMessageKey()` deprecated and remove them in a later version.

**Comment by tomhoefer** [comment]
Even if we would introduce withMessageKey again then the corresponding message could not be translated. For this reason bindings for ESH 0.9 should be adopted to the new operation.

**Comment by kaikreuzer** [comment]
Which sounds fine for me as there are hardly any bindings out there yet that use the pretty new config status feature.
