### ISSUE TITLE
Sonos binding: currenttitle channel temporarily reset when changing radio station

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1954]
A little bug: when a new radio is selected, the title channel is reset and only set later, maybe when the polling job is run ?

**Comment by ivivanov-bg** [comment]
Is the title channel updated at all?

From what I've seen - playing radio (through TuneIn in Sonos App) neither the currenttitle nor the currenttrack channels are updated.

I have even created a small fix for this.

**Comment by lolodomo** [comment]
Yes I can see the currenttitle channel set with the station name and the station frequency. Just that after a change of station, the channel is set to empty during a certain time.
currenttrack channel looks good for me.

**Comment by lolodomo** [comment]
currenttrack channel is immediately updated and contains as first part what will be set later in currenttitle channel.
There is something in the code relative to opmlurl, an undocumented binding parameter.  When set, the binding uses this URL to get station info but apparently do it not too often. By the way, this option is not set in my case and I don't understand its need.

**Comment by lolodomo** [comment]
This opmlurl is in a certain way provided by the factory when the handler is created.
So the problem is in the parse of the result of this query. The info are correctly retrieved but the title variable is not correctly set.
Should be easy to fix.

**Comment by ivivanov-bg** [comment]
In my setup - the opmlUrl is not provided (It's set to null) so the information has to be retrieved by the UPnP services the player provides. And the only way to do this is using the code above.

I'm not sure if it's related to the radio stations which are been played (even though I have tried few local stations for Sofia, Bulgaria but also some German stations as well and the result was always the same:

The song metadata (provided by the radio station) was in the `StreamContent` field of the `CurrentTrackMetadata` and the name of the radio station was in the `Title` field of the 'CurrentUriMetadata`

The behavior was the same for Play1 and Play3 devices.

**Comment by lolodomo** [comment]
I have done nothing and I can tell you that opmlurl is set in my case. It is retrieved by the handler factory like that:
```
    protected void activate(ComponentContext componentContext) {
        super.activate(componentContext);
        Dictionary<String, Object> properties = componentContext.getProperties();
        opmlUrl = (String) properties.get("opmlUrl");
    };
```
I assume this is defined somewhere in a config file of the OH2 distribution. Are you using a standard distribution ?

In fact, the problem was that the title was set and then imlmediately reset in updateTrackMetaData. I fixed that by replacing:
```
                if (!currentTrack.getTitle().contains("x-sonosapi-stream")) {
                    title = currentTrack.getTitle();
                }
```
by
```
                if (!currentTrack.getTitle().contains("x-sonosapi-stream")) {
                    title = currentTrack.getTitle();
                } else {
                    title = stateMap.get("CurrentTitle");
                }
```

@ivivanov-bg : you're right, in case opmlurl is not set, currenttrack and currenttitle will not be set. And the station name could be retrieved even without requesting through opmlurl but that is apparently not implemented. Current implementation with opmlurl provides more information.

**Comment by lolodomo** [comment]
This setting is defined in file runtime/etc/services.cfg:
```
org.eclipse.smarthome.binding.sonos:opmlUrl=http://opml.radiotime.com/Describe.ashx?c=nowplaying&partnerId=IAeIhU42&id=%id&serial=%serial
```

**Comment by ivivanov-bg** [comment]
I guess with the latest change both cases will be addressed

**Comment by lolodomo** [comment]
My change will only fix the current implementation using Opml URL.
Your case is another issue or maybe more a feature request that is not yet implemented in the binding. Please enter a new issue/request in this case.

**Comment by lolodomo** [comment]
PR fixing this issue is now merged.
