### ISSUE TITLE
Move "system" service configuration on a page of its own

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1971]
Currently, the Configuration->Services menu is a collection of all kind of different services in the runtime, which makes sense as a generic mechanism to allow any kind of extensions.

What I notice from a solution perspective though is that the "system" tab is rather difficult to find and not well usable as it is an aggregation of many small services with a few parameters only.
From a user perspective, the "system" configuration is something that should stand out as it is the place where all global/system-wide settings are done.

I would therefore suggest to move "system:" services away from Configuration->Services to a new menu entry "Configuration->System" (any better name suggestions welcome. Maybe "General"?) as a first entry under "Configuration".

Furthermore, the different parameters of services should be directly listed (and not only appear after pressing "Configure" on the different services). I would suggest to render full-width cards with all properties for each service as a simply list (one under the other). There is no need to have "expert mode" for these system settings.

**Comment by cdjackson** [comment]
Since changes are being suggested here (although I guess this is mainly looking at PaperUI) can I further suggest that a “services/types” interface is added to allow grouping of services in the same way as is added for extensions. Maybe this should be a separate issue, but I thought I’d add this comment as it is an issue related to the way that the UI presents the services.

**Comment by kaikreuzer** [comment]
Hm, the services are already grouped through their category (like [here](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/OSGI-INF/localeprovider.xml#L18)), so what exactly are you requesting?

**Comment by cdjackson** [comment]
Yes, they are grouped - that’s fine and understood - but there is no information about the groups. So, we have (from memory) a group id of ‘system’, and ‘ui’, but the user interface must interpret these and display something nicer. I’m suggesting adding a /types endpoint that would provide {type: “system”, label: “System”} which could be i18n.  This is how it’s done in Extensions (take a look at the extension API).

**Comment by kaikreuzer** [comment]
Well, this would be a much bigger change as it requires a bigger infrastructure underneath (with interfaces to be implemented etc.).

> but the user interface must interpret these and display something nicer

No, the Paper UI shows them as they are - good enough for now :-)

> Maybe this should be a separate issue

Yes, please!

**Comment by cdjackson** [comment]
> No, the Paper UI shows them as they are - good enough for now :-)

Ok - so HABmin also does the same (I capitalise it), but it just seems better to treat this in a standard way.

I'll open a separate issue.
