### ISSUE TITLE
Things appear as ONLINE in Paper UI while the associated binding is not installed

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#1974]
For example, I have things defined in my config files for Sonos devices.
The Sonos binding is not yet installed.
But my 2 things appear as ONLINE in Paper UI.

**Comment by kaikreuzer** [comment]
What does the console show if you do a "smarthome:things"? Are they shown ONLINE as well?

**Comment by lolodomo** [comment]
These things are not listed when using the console command.
It looks like Paper UI is considering by default a status ONLINE while the default should UNINITIALIZED.

**Comment by kaikreuzer** [comment]
> These things are not listed when using the console command.

That's not possible - this means they do not exist.

> It looks like Paper UI is considering by default a status ONLINE while the default should UNINITIALIZED.

No, it does not. See here an entry for a Thing for which no binding is installed:

<img width="1152" alt="screen shot 2016-08-05 at 11 36 25" src="https://cloud.githubusercontent.com/assets/3244965/17432733/05d7af5c-5b01-11e6-97ed-d931e2ea5634.png">

**Comment by lolodomo** [comment]
In fact, my binding was automatically reinstalled at each startup !
Finally, that is not so clear for me how to "definitively" uninstall a binding.
I have now the strange feeling that it the binding was set one day in my file addons.cfg, it will always be installed even if you suppress it from addons.cfg and run a bundle:uninstall.
@kaikreuzer : what command has to be run to uninstall a binding and be sure that it will not be installed again at next startup ?

**Comment by cdjackson** [comment]
If you uninstall the binding (using the uninstall command) in the console, then it won’t start again at the next restart. Karat will maintain the state of bindings that are running, logging states etc. I think if you just stop if, it will restart next time.

**Comment by lolodomo** [comment]
It is not what I am seeing now !
I probably missed something...

**Comment by kaikreuzer** [comment]
You should uninstall the feature, not only the bundle (`feature:uninstall ...`)
