### ISSUE TITLE
Do not persist changes to a Thing when done from the Thing handler itself

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#1977]
As discussed [here](https://www.eclipse.org/forums/index.php?t=msg&th=1079343&goto=1739523&#msg_1739523), we suggest to allow Thing handlers to do dynamic changes to the Thing structure during runtime, indifferently whether where the Thing definition came from (DSL, database, etc.).
These changes should NOT be persisted, since it is assumed that the handler does them upon every start anyhow.

**Comment by sjka** [comment]
The way it is currently implemented, all changes end up in the objects that the `ThingRegistry` holds in memory and these are then either persisted or not. Even if we prevent the `ThingHandler` to inform the `ManagedThingProvider` about the updates, then when at any later point in time a legitimate update happens which indeed _should_ be persisted, these changes that the `ThingHandler` did earlier get persisted as well. #1682 is based on this wrong assumption too.

Therefore, the only chance I see is to clearly separate two forms of a `Thing`: the persisted one and the in-memory one. Whenever a change is made that should be persisted, the Thing from the `ManagedThingProvider` should be taken, merged with the desired change and be written back to the database. Such changes will trigger the re-creation of a `ThingHandler` and therefore it can do all transient changes again. All those changes coming from the `ThingHandler` should go only to the in-memory version in the `ThingRegistry` and must not trigger an update in the `ManagedThingProvider`.

However, this would be kind of fragile: If anybody made a change leading to the situation that accidentally a thing is going to be persisted which also includes any transient changes, we end up in a huge mess...

Therefore I'd rather suggest to soften this requirement a little: Let's allow changes to `Thing`s regardless of their `Provider`. The `ThingManager`should take care to not throw any exceptions anymore on a write attempt to a DSL based `Thing`. And bindings need to handle both situations gracefully, that their changes are there or not (which includes that the `ThingBuilder` must allow to remove `Channel`s). Keep in mind that users always have the ability to define something that conflicts with what the binding might want to do, e.g. manually define `Channel`s which the `ThingHandler` actually wants to create itself.

@kaikreuzer @maggu2810 @cdjackson @abinmathewabraham WDYT?

**Comment by kgoderis** [comment]
> Therefore I'd rather suggest to soften this requirement a little: Let's allow changes to Things regardless of their Provider. The ThingManagershould take care to not throw any exceptions anymore on a write attempt to a DSL based Thing. And bindings need to handle both situations gracefully, that their changes are there or not (which includes that the ThingBuilder must allow to remove Channels). Keep in mind that users always have the ability to define something that conflicts with what the binding might want to do, e.g. manually define Channels which the ThingHandler actually wants to create itself.

That sounds ok as a way forward. It does makes sense for ThingHandlers to be able to steer the usage and mix in of Channels, just for consistency reasons wrt the actual hardware.

**Comment by kaikreuzer** [comment]
+1 from me.
