### ISSUE TITLE
Wemo binding: Docs: Motion Sensor Example

### ISSUE THREAD

**Issue by ms777** [eclipse/smarthome#1981]
under Full Example / demo.items, the line
`Switch MotionSensor  { channel="wemo:Motion:Sensor1:state" }`
should be replaced by
`Switch MotionSensor  { channel="wemo:motion:Sensor1:motionDetection" }`

under Full Example / demo.things, it might be helpful to add a line
`wemo:motion:Sensor1  [udn="Sensor-1_0-221337L11xxxxx"]`

**Comment by kaikreuzer** [comment]
Could you or @hmerk create a PR for it?

**Comment by hmerk** [comment]
Done with PR #2013
