### ISSUE TITLE
Proposal for tests for the FSInternetRadio binding

### ISSUE THREAD

**Issue by m-memova** [eclipse/smarthome#1993]
I would like to implement some tests for org.eclipse.smarthome.binding.fsinternetradio. I think I would create one test class for the DiscoveryParticipant and one for the Handler. I will use a mocked HttpServlet so I will be able to check if  the channels are updated properly when a certain command is given. 
Since I am new to ESH and OSGi, any comment/advice will be greatly appreciated. 

@paphko, as a initial contributor, what do you think?

**Comment by paphko** [comment]
Hi @m-memova,
Tests are always a good thing to have :-)
Your proposed tests would definitely be a good starting point. Then we could easily add further tests when reasonable. Right now, I don't have any further test scenarios in mind which would be reasonable with a mockup.

**Comment by m-memova** [comment]
Hello everyone,
while I was implementing the tests, I noticed some things in the code. They are not bugs but I made some changes in the binding's code that I think can be considered as minor improvements. I made a PR for them:
#2348
@paphko can you take a look and let me know if you are OK with those changes?
Regards,
Mihaela
