### ISSUE TITLE
audio / voice refactoring: old files remaining

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2001]
The PR #1882 does not clean up old files completely.
There are still remaining files left:
* https://github.com/eclipse/smarthome/tree/6be3a45/bundles/io/org.eclipse.smarthome.io.audio
* https://github.com/eclipse/smarthome/tree/6be3a45/bundles/io/org.eclipse.smarthome.io.voice

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/eclipse/smarthome/pull/2002
