### ISSUE TITLE
FirmwareUpdateServiceOSGiTest still broken

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2023]
It seems #2004 does not solve all problem.

Log attached: [log.txt](https://github.com/eclipse/smarthome/files/428346/log.txt)

**Comment by tomhoefer** [comment]
This should be fixed once #2008 is merged. If required I can provide an additional PR to fix this issue...

**Comment by maggu2810** [comment]
Ah, thanks. Perhaps someone who can test the firmware stuff can give his agreement, that #2008 is fine.

**Comment by tomhoefer** [comment]
maybe @sjka can give his agreement since we are already using this feature

**Comment by sjka** [comment]
As #2008 is merged I assume we can close this one too, right? 
At least I haven't seen this bug again since then.

**Comment by maggu2810** [comment]
It seems so. Thanks for the reminder.
