### ISSUE TITLE
Paper UI - Items are overlapping

### ISSUE THREAD

**Issue by markusjw** [eclipse/smarthome#2024]
In Paper UI, the Number item representation in an item list is overlapping with the next list entry (see Screenshot).

![2016-08-22 paper ui overlap bug](https://cloud.githubusercontent.com/assets/19324427/17851294/80be8bb0-6861-11e6-9d21-8c7b01fae62e.png)

This occurs in the daily version of 2016-08-17, but not in the on of 2016-06-16.

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you please have a look?

**Comment by aounhaider1** [comment]
Can you please provide some more details on how to reproduce this? What browser are you using? And which two things are overlapping (and their xml) ?

**Comment by markusjw** [comment]
The problem occurs for each writeable Number item (which shows a slider and has therefore several lines). The slider is overlapping with the following item in the list. In the screenshot, each visible slider belongs to the item above it. "Change mode" is an Enum item and has no slider.

Firefox and Chrome show the same result. IE does not work at all, as you know.

This is the thing xml:
[2016-08-22 Paper UI overlap bug - thing xml.txt](https://github.com/eclipse/smarthome/files/432479/2016-08-22.Paper.UI.overlap.bug.-.thing.xml.txt)

Thanks for checking.

**Comment by aounhaider1** [comment]
@markusjw can you please check if https://github.com/eclipse/smarthome/pull/2043 solves this issue for you?
