### ISSUE TITLE
404 when accessing Configuration->System

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2026]
Using the latest OH2 build, the Paper UI shows an "ERROR 404 - Not found" when accessing the System configuration and it seems that it stops rendering the page (at least it leaves an empty box with no configuration parameters at the end).

Looking at the javascript console, I see

```
catcher.js:197 GET http://localhost:8080/rest/config-descriptions/system:persistence 404 (Not Found)
```

This probably occurs when no configuration has been set yet. I think the Paper UI should silently ignore such a situation and still make it possible to submit a configuration for it.

P.S.: I see another 404 for http://localhost:8080/ui/fonts/Roboto-LightItalic.woff. This is probably unrelated, but should be fixed as well.

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you please have a look?

**Comment by aounhaider1** [comment]
The fonts should be available if npm install is successful. Can you please check if npm install is throwing any errors? Its working fine for me.

**Comment by kaikreuzer** [comment]
@aounhaider1 `web/fonts/Roboto-LightItalic.woff` is included in build.properties bin.excludes, therefore it is not available in the binary build. This was done to reduce the size of the Paper UI and this font has not been used before. If we now need it, please remove it from the exclusion list, if we can live without that font, please adapt the code.
