### ISSUE TITLE
Paper UI: Disable Dimmer item when read-only

### ISSUE THREAD

**Issue by markusjw** [eclipse/smarthome#2039]
Items with type Dimmer that are also configured as read-only should not be editable in the Control view.
Maybe there should not even be a slider.
See #1587

**Comment by kaikreuzer** [comment]
I'd agree. @aounhaider1, could you please have a look?

**Comment by aounhaider1** [comment]
Are you sure, you are on latest master? This should be working already, as it was implemented in https://github.com/eclipse/smarthome/pull/2007.

**Comment by markusjw** [comment]
I noticed this in a daily version of openHAB. And from the title I could not see that #1976 addresses the same issue. We can close this then.
