### ISSUE TITLE
Paper UI: Thing config page does not load completely

### ISSUE THREAD

**Issue by markusjw** [eclipse/smarthome#2040]
For things with a higher number of configuration parameters (tested with around 50), the configuration editing page has serious problems.
(For a thing with about 15 config parameters, there was no problem.)

When opening it first, only an empty page header is shown:
![2016-08-24 paper ui config view bug](https://cloud.githubusercontent.com/assets/19324427/17935513/e5bda350-6a1b-11e6-8d93-7ca67e5f0a62.png)

When refreshing the page once, it loads completely with some delay, but it does not show any values.
Further refreshing does not help.

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you please have a look and try to reproduce?

**Comment by aounhaider1** [comment]
@markusjw I was unable to reproduce the issue with 89 different parameters. The problem might be because of some specific combination of parameters. Can you please provide the complete config file of the thing?

**Comment by maggu2810** [comment]
@markusjw Have you seen the message of @aounhaider1?

**Comment by aounhaider1** [comment]
He sent me the description this morning. I am able to reproduce the issue with that. However, I have a question about context. Is it possible to have a parameter with context=time and type=integer?
