### ISSUE TITLE
Allow specifying location while approving things from Inbox

### ISSUE THREAD

**Issue by aounhaider1** [eclipse/smarthome#2045]
Should we allow optionally specifying thing's location while approving it from Inbox?

**Comment by sjka** [comment]
good idea, imho

**Comment by maggu2810** [comment]
Okay for me.

If the location string still something product specific?
IIRC we don't define ATM if it is an item name, a human readable string etc.

If it is not product specific, but limit by the ESH framework to some specific type, we should define it before it is used in to much places.

**Comment by sjka** [comment]
> If the location string still something product specific?
> IIRC we don't define ATM if it is an item name, a human readable string etc.

I'm not aware this has changed

You can already edit the location field as part of the thing editing page. So offering a "string" field would not make the situation much worse than it is. Apart from it being more convenient to actually fill it out.
