### ISSUE TITLE
Paper UI: rule handling

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2049]
If a new rule is added using the Paper UI a post method is done to path /rest/rules and the payload contain the rule.
The response header contains the key "location" to the "path" of the newly created rule.

* The Paper UI does not use this URL to fetch the rule (perhaps a modified one IIRC we have a autoconnection feature) and to add it to its rule storage. Instead it loads the whole list of all rules again.
IMHO this could be improved.

* If a new rule has been added an event is submitted (SSE / eventsource), so the PaperUI is aware of this change. But also in this case the PaperUI ignores the event and does not load this rule. If more then one user control the system using the PaperUI I would expect that a new rule is added to my list without forcing a refresh as in the old days without ajax and all the async stuff.

**Comment by sjka** [comment]
@aounhaider1 could you please have a look?
