### ISSUE TITLE
NPE in HttpUtil when accessing a https url

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2059]
There are reports about NPEs in HttpUtil, since it had been changed to use the Jetty client library, see https://community.openhab.org/t/getting-a-npe-from-a-https-request/13610

**Comment by kaikreuzer** [comment]
@svilenvul Could you please check?

**Comment by svilenvul** [comment]
OK, I will take a look

**Comment by svilenvul** [comment]
I have found the problem, I have missed to configure Jetty HttpClient to perform https requests. PR will follow soon.
