### ISSUE TITLE
Paper UI: rollershutter widget

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2060]
The control buttons of the rollershutter are not centered anymore.
Tested commit id: f77110576a1b91d7241039e7270c787d557420bb

Browser: Firefox 48.0

![rollershutter-big](https://cloud.githubusercontent.com/assets/204670/18044021/c92fd312-6dcb-11e6-840f-cd10cb60ee5f.png)
![rollershutter-small](https://cloud.githubusercontent.com/assets/204670/18044020/c92f9190-6dcb-11e6-86ea-7bb000f07898.png)

**Comment by maggu2810** [comment]
Another question: Why is there a degree character in front of the position?

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you please check?

**Comment by aounhaider1** [comment]
The degree character is probably with minimum value of the slider. It will be fixed once https://github.com/eclipse/smarthome/pull/2043 is merged.
