### ISSUE TITLE
Thing updates are not reflected in the PaperUI

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#2091]
having fixed #2089, I noticed that thing updates (e.g. label changes) are not reflected in the PaperUI. I had to refresh the page in order to see them.
I saw that the PaperUI is not listening to `smarthome/things/*/updated` events yet (unlike for items, where it does it already). Wouldn't it make sense to do so for Things?

**Comment by sjka** [comment]
@aounhaider1 wdyt?

**Comment by aounhaider1** [comment]
Actually this should not happen. Currently, View thing is being loaded with a force update from the rest endpoint instead of serving from local storage. 
However, listening to thing updates can potentially improve the number of requests sent to the server.
