### ISSUE TITLE
Replace Apache HttpClient 3.x with Jetty #1864 breaks UTF-8 usage in contentType header

### ISSUE THREAD

**Issue by hmerk** [eclipse/smarthome#2097]
With Apache HttpClient, one could use the following string for setting Http contentType header:
String contentHeader = "text/xml; charset=\"utf-8\"";
which is used/needed in WeMo Binding, see #2073

Jetty does not support setting the charset.

@svilenvul as you created #1864 can you have a look into this. Thanks!

**Comment by svilenvul** [comment]
@hmerk 
I am not sure, that I understand this correctly. Do you mean that the request created by the HttpUtil#executeUrl() does not have the correct contectType header? I have prepared a simple [test case](https://github.com/svilenvul/smarthome/blob/2097-jetty-failed-request/extensions/binding/org.eclipse.smarthome.binding.wemo.test/src/main/groovy/org/eclipse/smarthome/binding/wemo/test/WemoHttpCallOSGiTest.groovy) for that and it seems to be ok. (the test can be run in Eclipse only)
