### ISSUE TITLE
Bug in ConnectionValidator (Throwing IAE in the wrong place) when starting the org.eclipse.smarthome.automation.sample.extension.java

### ISSUE THREAD

**Issue by vilchev** [eclipse/smarthome#2103]
When starting the sample.extension.java demo 

AirConditionerSwitchOnRule  is in NOT_INITIALIZED (HANDLER_INITIALIZING_ERROR) State with the following error logs:

osgi> 15:01:44.245 INFO  s.event.RuleStatusInfoEvent[:43] - AirConditionerSwitchOnRule updated: NOT_INITIALIZED (CONFIGURATION_ERROR): Validation of rule AirConditionerSwitchOnRule has failed!  Invalid Connection "currentTemperatute" :  Output with name "currentTemperatute" not exists in the Action with ID "AirConditionerRuleTrigger"
15:01:44.245 INFO  s.event.RuleStatusInfoEvent[:43] - AirConditionerSwitchOnRule updated: NOT_INITIALIZED (HANDLER_INITIALIZING_ERROR): 
 Validation of rule AirConditionerSwitchOnRule has failed!  Invalid Connection "currentTemperatute" :  Output with name "currentTemperatute" not exists in the Action with ID "AirConditionerRuleTrigger"

**Comment by marinmitev** [comment]
There is a need of clarification that the rule action has correct configuration for the input which refers to existing trigger output. The problem is in the connection validator logic
Additional small issue is the typo error "currentTemperatute" instead of "currentTemperature"
