### ISSUE TITLE
Incorrect overriding of properties in org.eclipse.smarthome.config.dispatch.internal.ConfigDispatcher

### ISSUE THREAD

**Issue by petarnv** [eclipse/smarthome#2109]
In ConfigDispatcher files are processed as listFiles() method ordered them and this order is never guaranteed(https://docs.oracle.com/javase/7/docs/api/java/io/File.html#listFiles()), i.e. the order can be alphabetical or some other order, which may cause the latest value for a property to be overridden by another value of the same property.

I have made a PR with tests for this: https://github.com/eclipse/smarthome/pull/2108

This behavior can be seen in the following ignored tests:
1) properties for the same local PID in different files must be overridden in the order they were last modified
2) properties for the same global PID in different files must be overridden in the order they were last modified
3) local PID is overridden by global PID in different file, if the file with the global one is modified last
4) global PID is overridden by local PID in different file, if the file with the local one is modified last

**Comment by maggu2810** [comment]
I have replied to #2108 about this topic

**Comment by kaikreuzer** [comment]
Afaics, this has been addressed in https://github.com/eclipse/smarthome/pull/2108.
