### ISSUE TITLE
No update of the configuration on delete of a property in a configuration file in org.eclipse.smarthome.config.dispatch.internal.ConfigDispatcher 

### ISSUE THREAD

**Issue by petarnv** [eclipse/smarthome#2111]
On delete the file should be processed and the configurations should be updated, but in ConfigDispatcher, when file is deleted, it is only processed, but not updated. An update happens only when new content is added, but not when it is deleted.

I have made a PR with tests for this: https://github.com/eclipse/smarthome/pull/2108

This behavior can be seen in the following ignored test: 
"configuration is updated when configuration files are modified"

**Comment by kaikreuzer** [comment]
According to https://github.com/eclipse/smarthome/pull/2108#issuecomment-259146138, this is the expected behavior.
