### ISSUE TITLE
Auto format (correct indent) the entire .sitemap document

### ISSUE THREAD

**Issue by phieber** [eclipse/smarthome#2115]
It would be really helpful to have an auto indent function in Designer (Eclipse).
Version 0.8 doesn't have this functionality.
As an Eclipse user, I am used to press Strg+Ctrl+F

**Comment by sjka** [comment]
There are formatters for all the DSLs (e.g. [ItemsFormatter.xtend](https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/formatting/ItemsFormatter.xtend)) and as far as I can see they were added more than a year ago. I just tried it out and it seems to work for me. 
What version/build were you using? And in which DSL didn't it work?

**Comment by phieber** [comment]
The DSLs are working fine. They get indented properly.
I was referring to the fact that if I screw up the formatting for whatever reason (copy paste/..), I cannot easily reformat it properly in one shot. I am using the latest build (v0.8, I suppose).

**Comment by sjka** [comment]
Shift+Cmd+F works fine on MacOS, so I guess it must a problem with the key bindings for Windows then.

**Comment by phieber** [comment]
Tried it once more and it works with .items but not with .sitemap files. Can you confirm this on MacOS? I am using the Linux version.

**Comment by sjka** [comment]
argh, I missed that: There IS a formatter for sitemaps too, but it's not doing anything useful:
[SitemapFormatter.xtend](https://github.com/eclipse/smarthome/blob/9609214/bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/formatting/SitemapFormatter.xtend)

**Comment by kaikreuzer** [comment]
Note that there is already an issue for this: https://github.com/eclipse/smarthome/issues/645
According to it, @planger has it on his to-do list, but not much has happened in the past year...
