### ISSUE TITLE
Config description builder should use i18n

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#2116]
Currently I don't think there's any way to internationalise the config descriptions. The builder should provide i18n versions of its functions in the same way the config status provider does.

**Comment by sjka** [comment]
I'm not sure if I really get your question. You are aware of `ConfigDescriptionProvider.getConfigDescription(URI, Locale)` and the [ConfigI18nLocalizationService](https://github.com/eclipse/smarthome/blob/master/bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/i18n/ConfigI18nLocalizationService.java)? What is it that you are missing? Help me understand...

**Comment by cdjackson** [comment]
Sorry - I should have been clearer that this is to do with the builder, for defining configuration description programatically.

If I want to create a config description using the builder -:

```java
ConfigDescriptionParameterBuilder
    .create(ZWaveBindingConstants.CONFIGURATION_DOORLOCKTIMEOUT, Type.INTEGER).withLabel("Lock Timeout")
    .withDescription("Set the timeout on the lock.").withDefault("30").withGroupName("thingcfg")
    .build()
```

how does this get internationalised? Can I still describe this somewhere so that the i18n file is used? I don't think so, but maybe I'm wrong?

On the other hand, the ```ConfigStatusMessage.Builder``` has methods to pass a key rather than a string. Possible a ```withLabelKey``` method to replace the existing ```withLabel``` method?

Maybe I've missed something and the current system allows this?

**Comment by sjka** [comment]
Ah, I see. Thanks for the detailed explanation. No, there I also have no idea. @tomhoefer anything we have missed?

**Comment by tomhoefer** [comment]
As far as I know currently you can only use the ```ConfigI18nLocalizationService#getLocalizedConfigDescriptionParameter``` to internationalize a config description parameter. 

Do you require additional operations ```withLabelKey``` and ```withDescriptionKey``` that should replace the current operations ```withLabel```and ```withDescription``` or should the builder be extended by the new operations?

**Comment by cdjackson** [comment]
I agree that this can be done. But I was thinking that it made sense to have a consistent interface where i18n is supported more natively. In the ZWave binding, I’ve effectively had to implement a number of methods to allow me to use i18n and it seems to make sense to make it easier to use. I believe the status provider has this (if I remember correctly).

**Comment by tomhoefer** [comment]
@cdjackson can you share the link to the repository for the ZWave binding?

**Comment by cdjackson** [comment]
It’s in the openhab organisation on github - it’s a separate zwave repo so easy to find, but am on my mobile - if you can’t find it I can provide the link tonight.

**Comment by maggu2810** [comment]
https://github.com/openhab/org.openhab.binding.zwave

**Comment by tomhoefer** [comment]
Because the ```ConfigDescriptionProvider``` is responsible for the translation we cannot avoid to use the ```ConfigI18nLocalizationService``` in the ```ZWaveConfigProvider```.

First of all you have to create the parameters as follows:

```
ConfigDescriptionParameterBuilder
    .create(ZWaveBindingConstants.CONFIGURATION_DOORLOCKTIMEOUT, Type.INTEGER).withLabel("@text/thing-type.config.<binding-id>.<thing-type-id>.<parameter-name>.label")
    .withDescription("@text/thing-type.config.<binding-id>.<thing-type-id>.<parameter-name>.description").withDefault("30").withGroupName("thingcfg")
    .build()
```

Then you should provide i18n properties files under ESH-INF/i18n containing the messages:
```
thing-type.config.<binding-id>.<thing-type-id>.<parameter-name>.label=My label
thing-type.config.<binding-id>.<thing-type-id>.<parameter-name>.description=My description
```

Pls check also the rules for creating such i18n keys here: https://www.eclipse.org/smarthome/documentation/features/internationalization.html

If you like then I can also provide a minor PR to provide the @text prefix for the properties to be internationalized

**Comment by cdjackson** [comment]
Sure - I understand how to use i18n, that's not the issue, and I already use it extensively in ZWave. My point was to enhance the API to provide better support in a similar way to provided by the config status API.

I guess this isn't something that you consider is needed so I'll close this.

**Comment by tomhoefer** [comment]
It would be feasible if we change the config description provider interface

**Comment by cdjackson** [comment]
Ok - it’s no problem. I just thought it would make it easier for others and be more consistent, but if it’s not so easy it’s really not a priority :)
