### ISSUE TITLE
bug Rule : Script interpreter couldn't be obtain

### ISSUE THREAD

**Issue by igorrobertifoc** [eclipse/smarthome#2117]
I have the same problem posted on
https://github.com/eclipse/smarthome/issues/1393.
and discussed on
https://community.openhab.org/t/intermittant-rule-issue/11663/8

it seem that rules, when are updated ( or refreshed by the system ), the "old" version stay on memory and generate the error :Script interpreter couldn't be obtain

my test.items
```
Number Scena  "Scena" <scena>
String VoiceCommand
```
my test.rules
```
rule testVoice
when
Item VoiceCommand received command
then
var String command = VoiceCommand.state.toString.toLowerCase

if (command.contains("luce relax") {
    Scena.sendCommand(1)
}
if (command.contains("luce lettura") {
    Scena.sendCommand(2)
}
if (command.contains("accendi luce") {
    Scena.sendCommand(0)
}
if (command.contains("spegni luce") {
    Scena.sendCommand(4)
}   
end
```
With openhab android is necessary just speak to generate the error

**Comment by igorrobertifoc** [comment]
Just an information can maybe help, I installed the new rules manager V2 (maybe some conflict)

**Comment by kaikreuzer** [comment]
After a looong, loooong debugging session, I hope I have finally tackled the problem!

**Comment by igorrobertifoc** [comment]
Goooood! Bravo!
where it was the problem just to know?

Thank you

**Comment by maggu2810** [comment]
You can have a look at #2125
