### ISSUE TITLE
Item initialization / item channel link handling

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2121]
This issue should continue the non-topic discussion started here: #2087 

@maggu2810 (https://github.com/eclipse/smarthome/pull/2087#issuecomment-244746937)

> Hi @sbussweiler,
I see a lot of
```text
Received update for non-existing item: Item '...' could not be found in the item registry
```
now.
After that messages, I see
```text
Enabling channel item provider.
```
and all the
```text
Item '...' has been added.
```

> That is a little bit confusing.

> I need to inspect if the updates are generated by my handlers or the framework itself.

> If them are generated by my handlers:
My thing handlers call `updateState(channelIdWithoutGroup, state);` so if the framework tries to update items, it already knows the item names that are linked to the channels and tries to delegate that updates but the items does not yet exist.
If the item is created I would assume that a refresh is called, so the thing handler is able to send the status update of the channel linked to that item again (we added this to the framework some time ago, see #1677). But if I look at the item state it is NULL.

@kaikreuzer (https://github.com/eclipse/smarthome/pull/2087#issuecomment-244875272)

> @maggu2810 Upon some analysis, I would assume that these log messages are due to https://github.com/eclipse/smarthome/pull/2096 (and not due to this PR). In #2096, I introduced a small delay before the ChannelItemProvider creates its items. The ThingManager assumes that if there is a link, the referenced item MUST exist as well and thus it sends events for it.
I am not sure how to solve this best; we currently cannot technically guarantee that items are always loaded/created before any link is loaded/created. The solution might also be related to the discussion in https://github.com/eclipse/smarthome/issues/1896, i.e. when we can be sure that all stuff is fully loaded after startup.

**Comment by maggu2810** [comment]
@kaikreuzer Thank you for the response.
I assume also if the startup is done completely we cannot assume that all items has been created.
IIRC the ChannelItemProvider (correct me if I am wrong) service can be deactivated and is so an optional feature.
If this is correct, a channel item link exist but the item is not available as long as it is created by some other logic / by the user / ...
Can't we send a refresh command to an item (perhaps only ones a link exist for) if the item has been created?

**Comment by sjka** [comment]
on a first look, I think the root cause lies within the ´AbstractLinkRegistry.getLinkedItems(UID)´ method. Although it claims that it returns items (or better: the names of the linked items), it actually only returns the pointers to the items without checking if they actually exist.
However, changing this should be done carefully. Also we need to think about the semantics of ´ThingHandler.channelLinked(ChannelUID)´, i.e. whether it makes sense to call this once only the link is there, or if this should only be called once the links AND the corresponding item are there.

**Comment by kaikreuzer** [comment]
> If this is correct, a channel item link exist but the item is not available as long as it is created by some other logic 

This is correct, but this situation could also be considered to be an inconsistent system setup and thus a warning log message about it might be adequate.

> Can't we send a refresh command to an item (perhaps only ones a link exist for) if the item has been created?

This is what '[BaseThingHander.channelLinked()](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java#L195)' does as a default. But `channelLinked` is also called by the framework as soon as a link is created (and it currently does not check, whether the linked item exists as well). This could be changed, but that would mean that the ThingManager needs to track items AND links and check do the respective calls only as soon as both are present - not too nice code, I guess.

**Comment by maggu2810** [comment]
> or if this should only be called once the links AND the corresponding item are there.

I think so.

>> Can't we send a refresh command to an item (perhaps only ones a link exist for) if the item has been created?

> This is what 'BaseThingHander.channelLinked()' does as a default. 

Really? I need to check it again, but it does not fit to my observation yesterday.

> If the item is created I would assume that a refresh is called, so the thing handler is able to send the status update of the channel linked to that item again (we added this to the framework some time ago, see #1677). But if I look at the item state it is NULL.

My binding stores the last set channel state and calls updateStatus on a refresh command using the last stored channel state.
So, if the refresh command is send on "link" AND on "item creation" I would expect that the state of the item is not NULL but the one the channel updates before too.

**Comment by maggu2810** [comment]
I modified the Yahoo Weather binding.
* disable the automatic refresh
* return a fixed number on refresh for every channel

```diff
diff --git a/extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java b/extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java
index e2741e8..64cc634 100644
--- a/extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java
+++ b/extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java
@@ -81,7 +81,7 @@ public class YahooWeatherHandler extends ConfigStatusThingHandler {
             refresh = new BigDecimal(60);
         }
 
-        startAutomaticRefresh();
+        // startAutomaticRefresh();
     }
 
     @Override
@@ -112,22 +112,19 @@ public class YahooWeatherHandler extends ConfigStatusThingHandler {
     @Override
     public void handleCommand(ChannelUID channelUID, Command command) {
         if (command instanceof RefreshType) {
-            boolean success = updateWeatherData();
-            if (success) {
-                switch (channelUID.getId()) {
-                    case CHANNEL_TEMPERATURE:
-                        updateState(channelUID, getTemperature());
-                        break;
-                    case CHANNEL_HUMIDITY:
-                        updateState(channelUID, getHumidity());
-                        break;
-                    case CHANNEL_PRESSURE:
-                        updateState(channelUID, getPressure());
-                        break;
-                    default:
-                        logger.debug("Command received for an unknown channel: {}", channelUID.getId());
-                        break;
-                }
+            switch (channelUID.getId()) {
+                case CHANNEL_TEMPERATURE:
+                    updateState(channelUID, new DecimalType("1"));
+                    break;
+                case CHANNEL_HUMIDITY:
+                    updateState(channelUID, new DecimalType("2"));
+                    break;
+                case CHANNEL_PRESSURE:
+                    updateState(channelUID, new DecimalType("3"));
+                    break;
+                default:
+                    logger.debug("Command received for an unknown channel: {}", channelUID.getId());
+                    break;
             }
         } else {
             logger.debug("Command {} is not supported for channel: {}", command, channelUID.getId());
```


```text
10:16:13.287 DEBUG o.e.s.b.y.h.YahooWeatherHandler[:66] - Initializing YahooWeather handler.
10:16:13.288 INFO  s.event.ThingStatusInfoEvent[:43] - 'yahooweather:weather:0554128d' updated: ONLINE
10:16:13.293 INFO  s.e.ThingStatusInfoChangedEvent[:43] - 'yahooweather:weather:0554128d' changed from INITIALIZING to ONLINE
10:16:13.294 DEBUG o.e.s.c.i.items.ItemUpdater[:76] - Received update for non-existing item: Item 'yahooweather_weather_0554128d_temperature' could not be found in the item registry
10:16:13.295 INFO  smarthome.event.ItemStateEvent[:43] - yahooweather_weather_0554128d_temperature updated to 1
10:16:13.296 DEBUG o.e.s.c.i.items.ItemUpdater[:76] - Received update for non-existing item: Item 'yahooweather_weather_0554128d_humidity' could not be found in the item registry
10:16:13.296 INFO  smarthome.event.ItemStateEvent[:43] - yahooweather_weather_0554128d_humidity updated to 2
10:16:13.296 DEBUG o.e.s.c.i.items.ItemUpdater[:76] - Received update for non-existing item: Item 'yahooweather_weather_0554128d_pressure' could not be found in the item registry
10:16:13.297 INFO  smarthome.event.ItemStateEvent[:43] - yahooweather_weather_0554128d_pressure updated to 3
10:16:13.538 DEBUG o.e.s.c.x.o.XmlDocumentBundleTracker[:126] - Reading the XML document '/ESH-INF/thing/thing-types.xml' in module 'org.eclipse.smarthome.binding.yahooweather'...
10:16:13.559 DEBUG o.e.s.c.a.i.AutoUpdateActivator[:29] - AutoUpdate binding has been started.
10:16:13.594 DEBUG o.e.s.c.x.o.XmlDocumentBundleTracker[:177] - Create an empty XmlDocumentProvider for the module 'org.eclipse.smarthome.binding.yahooweather'.
10:16:13.665 DEBUG o.e.s.c.c.r.AbstractRegistry[:192] - Provider 'org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider' has been added.
10:16:13.671 DEBUG o.e.s.m.t.i.GenericThingProvider[:790] - ThingHandlerFactory added org.eclipse.smarthome.binding.yahooweather.internal.YahooWeatherHandlerFactory@591f3f91
10:16:13.673 DEBUG o.e.s.c.c.r.AbstractRegistry[:192] - Provider 'org.eclipse.smarthome.model.thing.internal.GenericThingProvider' has been added.
10:16:13.866 DEBUG o.e.s.c.c.r.AbstractRegistry[:192] - Provider 'org.eclipse.smarthome.model.item.internal.GenericItemProvider' has been added.
10:16:14.356 DEBUG o.e.s.c.t.i.ChannelItemProvider[:159] - Enabling channel item provider.
10:16:14.379 INFO  smarthome.event.ItemAddedEvent[:43] - Item 'yahooweather_weather_0554128d_humidity' has been added.
10:16:14.382 INFO  smarthome.event.ItemAddedEvent[:43] - Item 'yahooweather_weather_0554128d_pressure' has been added.
10:16:14.385 INFO  smarthome.event.ItemAddedEvent[:43] - Item 'yahooweather_weather_0554128d_temperature' has been added.
```

```text
osgi> smarthome items list yahooweather_weather_0554128d_humidity
yahooweather_weather_0554128d_humidity (Type=NumberItem, State=NULL, Label=Humidity, Category=Humidity)
```

The refresh command is not executed on item creation, too.
Or am I missing something.

**Comment by kaikreuzer** [comment]
Ok, so in this case it is the handler that creates the channel state updates and the problem is that `ThingHandlerCallback.stateUpdated` does not check for the existence of the item, before posting the event. Again, it assumes that if the link exist, the item must exist.

> The refresh command is not executed on item creation, too.

No, as I said, it is called upon link creation (by ThingLinkManager.informHandlerAboutLinkedChannel), but only "if the thing isn't initialised", so I assume that the links are already there, before your handler goes ONLINE.
