### ISSUE TITLE
Thing Status enhancements

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2127]
Does it make sense to allow the control of things that status is not online?

**Comment by kaikreuzer** [comment]
Definitely YES! Because OFFLINE might be an outdated status and it is possible to reach them.
Why did you enter this issue? Is is currently NOT possible to control them?

**Comment by maggu2810** [comment]
> Because OFFLINE might be an outdated status and it is possible to reach them.

What do you mean with outdated status? The Paper UI is using SSE to keep track of the events and already adds / removes stuff in certain views if some information changes. Or do you mean a thing handler does not set the status correctly?

> Why did you enter this issue?

Hm, because I don't see any reasons to be able to control actuators if the handler states that he cannot talk to the devices.

**Comment by kaikreuzer** [comment]
> Or do you mean a thing handler does not set the status correctly?

I mean you never know whether your device is reachable or not if you use radio. In many cases, the ONLINE/OFFLINE status is only set by a handler, if it (un)successfully sent a command to the device over radio. successful->ONLINE, otherwise->OFFLINE. But if you send the next command 5 minutes later, you have no clue whether you can reach it or not. So you have to try it out.
And no, especially on 868MHz with its duty cycle, you do not do a "ping" over air every 10 seconds...

**Comment by maggu2810** [comment]
If a thing handler don't know if a device is online or offline this is a pain but is in responsible of the handler and there needs to be found a way to handle that. But I don't think that the user should see a offline device that could be controlled.

**Comment by maggu2810** [comment]
Wouldn't make another state sense, "unknown (offline or online)" and keep an offline to mark devices offline?

**Comment by kaikreuzer** [comment]
Think of the label "OFFLINE" as "failed communicating with it 10 minutes ago". The status can NEVER be up-to-date, all it tells you is something about the past. Believe me, I had many such discussions in the past already, all with the same result...

**Comment by maggu2810** [comment]
I still need to think about, but at the moment I would still prefer if the thing handler could then use two different offline states (offline_weak, offline_strict, or something similar).
The weak variant could be used if no real online / offline could be detected.
The weak strict could be used where the handler really knows that the device is not reachable.
For example all devices that are accesses directly by an USB connection could be set to offline_strict if the USB connection is not available. We already knows that also a command will not make the device online.
If the handler access the network information of your OS with events the handler is aware that there is currently no connection available and the devices could not be reached at all.
Binding using wireless connections will (perhaps) not make any usage of offline_strict but the framework should IMHO (at least at this time) provide a way that user interfaces or other thing status consumer could differ between an "offline but perhaps online after interaction" and an "offline the device is not accessible at all".

**Comment by kaikreuzer** [comment]
Let's speak about "Status", not "State" here.
I don't think we should introduce different OFFLINE statuses, but we could define new sub-statuses for OFFLINE, if you think this is worthwhile.
Btw, I would also suggest to introduce a new Thing status like UNKOWN, which should be the one set by the framework as soon as the handler is initialized and as long as the handler did not yet figure out whether it should be ONLINE or OFFLINE (as it might take a while to wait for a response). Currently, it is not defined which status the thing has in that situation.
