### ISSUE TITLE
Synchronization in Automation RuleEngine

### ISSUE THREAD

**Issue by marinmitev** [eclipse/smarthome#2131]
Please see the comments here
https://github.com/eclipse/smarthome/pull/2102#issuecomment-244394912

RuleEngine.java has several blocks with `synchronized (this) ` which can be optimized by using separate locks - one for the map containing rules, another for the map containing rule statuses

**Comment by danchom** [comment]
I'm not agree about that. One lock grantees that each rule (in the rule engine) has corresponding status.

**Comment by marinmitev** [comment]
ok, lets not complicate the things. I will close the issue
