### ISSUE TITLE
Don't show option keys in control UI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2134]
If a channel type define state options, they currently appear like this in the control UI:

![screen shot 2016-09-07 at 10 34 05](https://cloud.githubusercontent.com/assets/3244965/18306562/b56b5bf8-74ec-11e6-9bea-3cd97dca1a81.png)

I would prefer to only show their label text, i.e. None, Alert, Long Alert in this example.

**Comment by aounhaider1** [comment]
Should it be same on other places like item/thing dropdowns as well?

**Comment by kaikreuzer** [comment]
No, not for parts that the user might have defined by himself (what he does for item & thing names).
