### ISSUE TITLE
Paper UI: empty control panel

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2152]
Using snapshot 464, when I click on "Control" in Paper UI, nothing is displayed, I just got an empty frame. Sometimes, I can see the display of controls during a very short time and then they disappear for ever.
Either with Firefox on my PC or with Chrome on my Android tablet.
This was working for me in older snapshots.

**Comment by kaikreuzer** [comment]
It only shows Things there, if they have enabled channels.
It works fine for me and I am not aware of any bug reports.

If you really have a reproducible case, please provide exact details including log messages of the Paper UI.

**Comment by lolodomo** [comment]
I have of course several things (defined in files) and several channels linked to items.
I have disabled the simple mode.
I noticed no exception in the logs relative to Paper UI.
In older snapshots, it took a lot of time to display all my things and I got a message from the browser asking me if I want to continue the script (something like that).

**Comment by kaikreuzer** [comment]
So can you reproduce it in the demo setup with simple mode activated as well? If not, try to find out what makes the difference!

**Comment by lolodomo** [comment]
@kaikreuzer : where can I find traces produced by Paper UI to debug this issue ?
What are the recent changes with the Control frame ?
Is there something changed relative to a timeout ? I ask this question because when it works in the recent past, it takes several seconds to display the content of the frame.

**Comment by kaikreuzer** [comment]
I'd like to forward these questions to @aounhaider1, the master of the Paper UI ;-)

**Comment by maggu2810** [comment]
@lolodomo You can open the developer console of your browser and have a look at.
Some time ago I realized that e.g. the thing type definitions (loaded by the control page) of the Z-Wave binding have a size of 1.5 MB -- the transfer of such a big content and parsing etc. has been caused the delay on my system. At least this delay could be identified by the developer console of the browser.
But perhaps your problem is another one, just FYI.

**Comment by lolodomo** [comment]
I am mo more alone.

https://community.openhab.org/t/control-screen-paper-ui-only-show-things-split-second/14174

**Comment by lolodomo** [comment]
I have now installed snapshot 480 and the problem seems to have disappeared.
