### ISSUE TITLE
Layouting issues on Smartphones

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2153]
While testing the Paper UI on a smartphone, I came across many issues regarding the layout (mainly due to the constraint space). Although smarthome support might not be the top priority, I think we should try fix the most obvious issues there. Here are some screenshots:

Overlaying:
![screenshot_2016-09-09-16-07-22](https://cloud.githubusercontent.com/assets/3244965/18420197/344d533a-786d-11e6-81f3-146cb9e995f5.png)

Too much excessive white space:
![screenshot_2016-09-09-16-07-46](https://cloud.githubusercontent.com/assets/3244965/18420198/34640120-786d-11e6-87f5-e48c9e8f3046.png)

Button overlaying:
![screenshot_2016-09-09-16-07-57](https://cloud.githubusercontent.com/assets/3244965/18420201/3473e8a6-786d-11e6-9b29-fbb35fbb5e03.png)

Font size too huge for descriptions:
![screenshot_2016-09-09-16-08-43](https://cloud.githubusercontent.com/assets/3244965/18420200/3473df78-786d-11e6-83b5-0eca2916a72e.png)
![screenshot_2016-09-11-22-06-04](https://cloud.githubusercontent.com/assets/3244965/18420199/3473a508-786d-11e6-9878-13d9f277e78b.png)

**Comment by aounhaider1** [comment]
```Font size too huge for descriptions```
Do you mean size of just the headings or overall size of the text?

**Comment by kaikreuzer** [comment]
Definitely the headings and I think even the rest can be a bit smaller. It should somehow be easily visible where the one thing type info ends and the next one starts.
