### ISSUE TITLE
Basic UI: Colorpicker button short press not working

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2154]
@resetnow I just noticed that when using a Colorpicker in the Basic UI, no command is sent if I press up/down buttons short. I would expect them to send ON/OFF. A long press works (which sends INCREASE/DECREASE).

Could you have a look, please?

**Comment by resetnow** [comment]
On a singe press the colorpicker buttons are supposed to send a single INCREASE/DECREASE command, which they don't do for some reason. I'll fix it a bit later. Regarding ON/OFF, wouldn't it be more logical from UX standpoint to send INC/DEC instead? These buttons look like ones used in setpoint and setpoint doesn't act as on/off.

**Comment by kaikreuzer** [comment]
> Regarding ON/OFF, wouldn't it be more logical from UX standpoint to send INC/DEC instead?

No, it used to be like that in the Classic UI from the beginning. And if a INC/DEC is wished, you can do so by a long press. But VERY often (if not most of the time) you simply want to turn the light on or off, so this imho makes a lot of sense. Btw, most physical wall switches that also operate as dimmers behave in a similar way.
For setpoint, this wouldn't really make sense, since you hardly ever want to set it to min or max.

**Comment by resetnow** [comment]
OK, got it

13 сент. 2016 г. 20:53 пользователь "Kai Kreuzer" <notifications@github.com>
написал:
