### ISSUE TITLE
INCREASE/DECREASE not working for LIFX

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2155]
@kgoderis While preparing a demo, it appeared to me that my LIFX Color 1000 did not react on any INCREASE/DECREASE commands to the color channel. I didn't yet debug myself, but is this a known issue?

**Comment by kgoderis** [comment]
It is a bug indeed. We simple forgot to include in the handleCommand() switch() statement

**Comment by wborn** [comment]
Should increase/decrease on the color channel change colors or brightness?

I would think colors because the command is send to that channel for a reason, i.e. like changing the color slider in Paper UI. But when I look at the Hue implementation for some reason brightness is increased/decreased.

**Comment by kaikreuzer** [comment]
It should change the brightness, just like ON/OFF should turn the light on and off.
