### ISSUE TITLE
org.eclipse.smarthome.core.audio : who is responsible for closing (Input)Streams?

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#2160]
Not really an issue, for now, but with respect to the Audio... API, which class is responsible for properly closing InputStreams after usage? As far as I can see, this does not happen at all

**Comment by kaikreuzer** [comment]
The consumer, i.e. the AudioSink should make sure that it is closed.

The only existing implementation of an AudioSink in ESH is the AudioPlayer and this imho correctly closes the input stream, see https://github.com/eclipse/smarthome/blob/master/extensions/io/org.eclipse.smarthome.io.javasound/src/main/java/org/eclipse/smarthome/io/javasound/internal/AudioPlayer.java#L91.

I therefore close this issue.
