### ISSUE TITLE
Modify org.eclipse.smarthome.automation.core to use DS

### ISSUE THREAD

**Issue by vilchev** [eclipse/smarthome#2180]
By now automation.core module was activated through BundleActivator. Dependencies were tracked by implementing ServiceTrackers.

Extract ModuleTypeRegistry, RuleEventFactory, RuleRegistry, TemplateRegistry as declared components

**Comment by vilchev** [comment]
RuleRegistryImpl is tracking **TemplateProviders** via ServiceTracker
  
```
@Override
public void modifiedService(ServiceReference reference, Object service) {
  TemplateProvider provider = (TemplateProvider) bc.getService(reference);
  templateUpdated(provider.getTemplates(null));
}
```


Here implementation uses **modifiedService** to be notified when the TemplateProvider service has been modified (templates from that TemplateProvider have been edited).

Along with **bind**, **unbind** methods from **Event strategy** ( one of the strategies for accessing services ) there is **updated** which can be used in this particular case:

> 
> • bind – The bind method is called to bind a new service to the component that matches the
> selection criteria. If the policy is dynamic then the bind method of a replacement service can be
> called before its corresponding unbind method.
> • updated – The updated method is called when the service properties of a bound services are mod-
> ified and the resulting properties do not cause the service to become unbound because it is no
> longer selected by the target filter.
> • unbind – The unbind method is called when the SCR needs to unbind the service.



I can find that **updated** is supported in OSGi R4.3, but cannot find info for it in OSGi R4.2.

**Comment by danchom** [comment]
As I remember, we have changed to use modified service method because the providers (especially script provider) to have opportunity to update supported module types (same with templates). I'm not sure if this functionality is still needed.  For me bind and unbind is enough to introduce module types and templates from providers. But if the  supper of OSGi R4.2 is not requirement, the updated can be used too.
Kai what do you think?

**Comment by vilchev** [comment]
In OSGi R4.2

**Bound Service Replacement**

> If an active component configuration has a dynamic reference with unary
> cardinality and the bound service is modified or unregistered and ceases to
> be a target service, SCR must attempt to replace the bound service with a
> new target service. SCR must first bind a replacement target service and
> then unbind the outgoing service. If the dynamic reference has a mandatory
> cardinality and no replacement target service is available, the component
> configuration must be deactivated because the cardinality constraints will
> be violated.
> 
> If a component configuration has a static reference and a bound service is
> modified or unregistered and ceases to be a target service, SCR must deacti-
> vate the component configuration. Afterwards, SCR must attempt to acti-
> vate the component configuration again if another target service can be
> used as a replacement for the outgoing service.

It seems service modified case is handled with the bind/unbind (if dynamic strategy is used) and deactivate/activate of the component (if static strategy is used). 

So it seems, to me, that it would work. However, if we put the **updated** in the component xml (To gain benefit from it (from OSGi R4.3+)), would it still run in R4.2. Best case scenario(in R4.2 case) is our **updated** to not be called at all. 

But is it possible **updated** definition in the xml to cause runtime problems in R4.2, because it is not recognised key word?

**Comment by vilchev** [comment]
Just checked that Prosyst framework 7.5.* (R4.2) handles the **updated**, only the component namespace must be declared in v1.2.0

<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.2.0"
