### ISSUE TITLE
channelLinked not called by the thing manager

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2183]
At startup, sometimes the thing manager is running this strange sequence for a thing in a very short time:
- initialize()
- dispose()
- initialize()

In this case, channelLinked on the thing handler seems to not be called for the linked channels.

**Comment by kaikreuzer** [comment]
Please note that https://github.com/eclipse/smarthome/pull/2087 is in the pipeline to be merged. This is supposed to solve such issues - I'd suggest you re-test this once it is merged.

**Comment by lolodomo** [comment]
Ok I will but please note that I can see that issue even without a bridgr thing. The astro binding is not using bridge.

**Comment by kaikreuzer** [comment]
#2087 is not only about bridges, but about the whole handler lifecycle.

**Comment by lolodomo** [comment]
The sequence dispose followed by initialize looks like a call by the thing manager to thingUpdated ? I could check that.

**Comment by lolodomo** [comment]
I answer to myself (previous message): no, it does not a call to thingUpdated that trigger this init sequence ... and this issue.

**Comment by kaikreuzer** [comment]
I'd assume that with https://github.com/eclipse/smarthome/pull/2087 this does not occur anymore. If you still see a problem, feel free to re-open.
