### ISSUE TITLE
Paper UI: unable to unlink a channel

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2184]
My thing is defined in a .things file.
Using Paper UI, I am able to link not yet linked channels to items but then I am unable to unlink it. Clicking the button, nothing happens, no messages logged.

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you check?

**Comment by aounhaider1** [comment]
I am unable to reproduce this issue. I used this channel in demo thing:
```{
Channels:
String:foo
}```
everything works fine in this scenario. Can you please share your channels that you defined in your thing? 
Note that links created in advanced mode cannot be unlinked in normal mode.

**Comment by lolodomo** [comment]
Misunderstanding :  I am not defining channels in my .things file, I am just linking a channel already defined by the binding (XML file).
But my astro thing is defined in a file astro.things and the item the channel is linked to is fefined in a .items file.
I am using the advanced mode in Paper UI (simple mode deactivated).

**Comment by aounhaider1** [comment]
It might be that you are trying to unlink the item whose link is defined in .items file. However, PaperUI should display an error message. https://github.com/eclipse/smarthome/pull/2204 should fix that.

**Comment by lolodomo** [comment]
No, I used an item that is linked to nothing in my .tems file.
I will provide my data later.

**Comment by lolodomo** [comment]
Hre is an extract of my .items file:
```
DateTime Debut_Jour2 "Lever de soleil 2 [%1$tH:%1$tM]" <clock> (GMeteo)
```
Here is my astro.things file:
```
Thing astro:sun:local "Astro" [ geolocation="48.123456,5.123456", interval=300 ]
```
Using Paper UI, I link channel "astro:sun:local:set#start" to item Debut_Jour2.
Then I try to unlink channel "astro:sun:local:set#start". Impossible.

**Comment by aounhaider1** [comment]
Are you using Firefox?

**Comment by lolodomo** [comment]
Yes
