### ISSUE TITLE
Removing an item from the console or Paper UI fails

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2185]
If I suppress an item from my .items file and restart openHAB, the item is still present. Is it expected ?
Then if I try to remove it from the console, I get a success message but the item is still here:

```
openhab> smarthome:items remove Debut_Jour2
1 item(s) removed successfully.
openhab> smarthome:items | grep Jour
Debut_Jour2 (Type=DateTimeItem, State=2016-09-18T19:56:00.000+0200, Label=Start time, Category=null)
Debut_Jour (Type=DateTimeItem, State=2016-09-18T07:34:00.000+0200, Label=Lever de soleil, Category=clock, Groups=[GMeteo])
Fin_Jour (Type=DateTimeItem, State=2016-09-18T19:59:00.000+0200, Label=Coucher de soleil, Category=clock, Groups=[GMeteo])
openhab> smarthome:links | grep Jour
Debut_Jour -> astro:sun:local:rise#start
Fin_Jour -> astro:sun:local:set#end
Debut_Jour2 -> astro:sun:local:set#start
openhab>
```

**Comment by lolodomo** [comment]
When I try to delete it from Paper UI, I can see this message:
```
10:59:13.560 [INFO ] [thome.io.rest.core.item.ItemResource] - Received HTTP DELETE request at 'items/Debut_Jour2' for the unknown item 'Debut_Jour2'.
```
But then the item is not removed.
Remember that this item is no more in my .items file ... but was in the past.
Strangely, its label has changed after I suppress it from my .items file.

**Comment by kaikreuzer** [comment]
Are you sure you have the [simple linking mode](https://community.openhab.org/t/items-things-and-their-names/11001/9?u=kai) deactivated?

**Comment by lolodomo** [comment]
Yes, just checked.

**Comment by kaikreuzer** [comment]
It might actually be active nonetheless, if you try to switch it through the Paper UI. There was just a fix 3 days ago about that: https://github.com/eclipse/smarthome/pull/2173

**Comment by lolodomo** [comment]
Is there a console command to remove a link ? Maybe it fails because of there is a channel linked to it ? I created another issue, I cannot delete this link with Paper UI.

**Comment by kaikreuzer** [comment]
> Is there a console command to remove a link ? 

At least to clear all links from the database: "smarthome:links clear"

**Comment by lolodomo** [comment]
I am running snapshot 480.
The simple mode is disabled by a setting in my runtime.cfg file:
```
org.eclipse.smarthome.links:autoLinks=false
```
I just consult the setting in Paper UI but do not change it.

**Comment by lolodomo** [comment]
I suppressed my mapdb files and restart OH and now channel link and item are gone.
But there is apparently a real issue.

**Comment by DavidR1953** [comment]
I had a similar problem in that I could not delete an Item, even though the console reported success, but I have never used .items files.
When I deleted the link in PaperUI, it deleted both the Item and the Link!
So success, but concerning.

**Comment by kaikreuzer** [comment]
I would hope that this has been fixed by https://github.com/eclipse/smarthome/pull/3639. If it still occurs, please feel free to re-open.
