### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by float2net** [eclipse/smarthome#2186]
An error is given when I tried to build the souce:
`Failed to load p2 metadata repository from location http://hstaudacher.github.io/osgi-jax-rs-connector/5.3.0:`

it seems the link 'http://hstaudacher.github.io/' is invalid ?

**Comment by kaikreuzer** [comment]
If you try http://hstaudacher.github.io/osgi-jax-rs-connector/5.3.0/content.jar, you will see that it is valid. I assume you just had some temporary issue, in general the build works as you can see on our Hudson at https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/
