### ISSUE TITLE
Item resolution broken in Designer

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2190]
Items are not resolved in the Designer, i.e. when trying to use content completion e.g. in sitemaps, no proposals show up.

**Comment by mhilbush** [comment]
The items list in the lower left of the designer window also is not populated with items.  Could this be another symptom of the above problem?

**Comment by kaikreuzer** [comment]
Yes, other symptom of the same root cause.

**Comment by rkoshak** [comment]
I'm also not having any of my Items identified in my Rules. Actions are also not recognized in Rules (below is a screenshot showing createTimer and logInfo . Hovering over the error it says "The method logInfo(String, String) is undefined".

![image](https://cloud.githubusercontent.com/assets/6385096/19365584/aa9a385e-9150-11e6-8728-563bbf16f3ac.png)

**Comment by J-N-K** [comment]
This is broken since commit 0b3f1f3d04e1cc552bb3b5e3f086d397293fbbe9 (#1828), I guess the ModelParser needs to be enabled in the Designer. However I didn't find out how to do so.

**Comment by kohlsalem** [comment]
I installed yesterday the latest snapshot of the designer - and my rules look pretty much like the image posted by rkoshak. 

@kaikreuzer , since this seems to be an open issue for quite a while now, and Highlightig/Check/TypeAread are the only reasons to use the Designer, can i conclude this part of the project to be dead? Since more and more functionality moves into the GUI, i would understand that, I'm just curious....

**Comment by kaikreuzer** [comment]
@kohlsalem I would love to see this fixed myself, but I don't know how to do it (at least without spending quite some amount of time, which I simply do not have) and nobody else came up with a fix yet either. 

So please help finding people that are deep in Eclipse RCP and Xtext and that are willing to give a hand here!

**Comment by sjka** [comment]
no in-depth Xtext knowledge was needed. Just some unhappy services...

**Comment by kaikreuzer** [comment]
Re-opening as I still have issues with the rule resolution:

![screen shot 2017-01-23 at 16 09 16](https://cloud.githubusercontent.com/assets/3244965/22209302/5426e478-e186-11e6-979c-536df5676495.png)

**Comment by sjka** [comment]
Yes, indeed, I can confirm that rules are still awfully broken. Will have a look too.

**Comment by sjka** [comment]
As it turned out there was a package imported twice in they dynamically created project, leading to an invalid manifest which could not resolve any classes except those from the JRE. I have created #2891 in order to prevent this. Could you please check if that solves your issues?

**Comment by ThomDietrich** [comment]
Somewhat related question: How complicated would it be to export what's special about the Designer as an eclipse ide plugin?

**Comment by kaikreuzer** [comment]
> Could you please check if that solves your issues?

Not entirely. The error markers still appear when opening a rule and are greyed our shortly after. So it's a good step forward, but not yet there.

> How complicated would it be to export what's special about the Designer as an eclipse ide plugin?

You mean like https://github.com/eclipse/smarthome/issues/630? To much effort and and it wouldn't solve any concrete issue.

**Comment by ThomDietrich** [comment]
@sjka I can confirm that the problems are not entirely solved yet.
The good news: Item resolution is working again and valid rules are without shown errors once again. 

In the following screenshots you can see the "greyed out error markers" @kaikreuzer was mentioning before. Any chance you could have yet another look? Thanks ;)

![grafik](https://cloud.githubusercontent.com/assets/2870104/22666683/e1a23d6e-ecb9-11e6-9648-7a12eb9bfac1.png)

![grafik](https://cloud.githubusercontent.com/assets/2870104/22666701/fa8fdbe2-ecb9-11e6-8f67-c679304fdf5c.png)

**Comment by sjka** [comment]
I just had another look at it (sorry it fell off my desk...). I _think_ I figured out the reason for the greyed out markers: The script and model runtimes trigger another validation, interfering with the same resources that are displayed in the editors. So while in #2873 the items runtime bundle was necessary to fix the item resolution, the rules and script runtime should not have been added. I will propose a fix for it.

**Comment by kaikreuzer** [comment]
I think we will live with this greyed out validation markers and not put further effort in the designer, see https://dev.eclipse.org/mhonarc/lists/smarthome-dev/msg00146.html.
If anybody out there would like to work on it, feel free to do so and we can re-open the issue.
