### ISSUE TITLE
PaperUI: Locale settings does not work properly

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2192]
Test environment: openHAB 2.0 b4 on a Raspberry PI 
Browser: Chrome 53 on Windows 10

I have played a bit with the locale settings options and discovered some problems. This is what I did.
In a previous setting I have set the language explicitly to "en" and country to "US".

Now I entered an invalid language under _Configuration/System_:
![image](https://cloud.githubusercontent.com/assets/616792/18646093/54611adc-7eb0-11e6-827b-76a4471097ec.png)
After pressing the "Save" button, nothing happened. So I pressed the button a second time and the Locale was set to "enxx_US":
21:31:32.615 [INFO ] [ore.internal.i18n.LocaleProviderImpl] - Locale set to enxx_US

Note: sometimes it works with the first press of the Save buttons, sometimes it is necessary to press the button two times to save the changes

Without leaving the locale settings I tried to set language back to "en":
![image](https://cloud.githubusercontent.com/assets/616792/18646179/b558907c-7eb0-11e6-9d73-5fc796d31d3e.png)
The save button disappeared. When I change the locale to a value that is different from "en" the save button gets visible. 
After switching to another page and then back to _Configuration/System_ I could change the language back to "en". This time the first press of the "Save" button worked.
Apparently the current value is compared with the value that was valid when entering this page and not with the value that was stored.

BTW: I would be fine if the language and country would be checked for correctness before enabling the "Save" button :-).

**Comment by kaikreuzer** [comment]
Not sure if this might be solved through https://github.com/eclipse/smarthome/pull/2173 already or not.
@aounhaider1 Could you please analyze this? Thanks!

**Comment by aounhaider1** [comment]
Wrong enabling/disabling of Save button should (already) be fixed by https://github.com/eclipse/smarthome/pull/2173

Requiring two clicks to submit form behaviour should be fixed by https://github.com/eclipse/smarthome/pull/2198
