### ISSUE TITLE
Strange errors on setup SmartHome development environment

### ISSUE THREAD

**Issue by float2net** [eclipse/smarthome#2200]
I met strange errors on setup SmartHome development environment, I followed this page:
https://www.eclipse.org/smarthome/documentation/development/ide.html
at step 8 has error:
![image](https://cloud.githubusercontent.com/assets/4687104/18677564/b7d0cf50-7f8b-11e6-970e-44913b8a3a8d.png)
then I choose 'proceed' and it ends with Error:
 'cannot find or load main class: org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher'
![image](https://cloud.githubusercontent.com/assets/4687104/18678326/416d7522-7f8e-11e6-88e6-771f907b244e.png)
also I attached a screen shot on project codegen's manifest file errors:
![image](https://cloud.githubusercontent.com/assets/4687104/18678363/5c5c9cfa-7f8e-11e6-9430-2e2658c509ac.png)
and target platform preference page error indications:
![image](https://cloud.githubusercontent.com/assets/4687104/18679486/60509b64-7f92-11e6-9668-c44b9d85b0d4.png)

Please help me find the reason and remedy, thanks.

**Comment by triller-telekom** [comment]
@float2net Have you tried this again with the latest version? In our team we have set up the development environment a couple of weeks ago on several systems, i.e. Mac and Linux without problems. Can you try it again with the latest version?

**Comment by sjka** [comment]
I assume this is obsolete by now.
