### ISSUE TITLE
Sonos binding: why calling updateMediaInfo() every minute ?

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2214]
@kgoderis & @R-Edelhoff : I have a question for you because I discovered something a little strange I don't really understand. It concerns the call to updateMediaInfo() every minute (by default). What is used in return to the call to getMediaInfo is only CurrentURI and CurrentURIMetaData. But these information are already provided in (pseudo) real time through the event subscription (but not used): AVTransportURI and AVTransportURIMetaData.
Do I miss something ? Is there a reason to not rely on event subscription ?
In fact, the track data are already updated when receiving CurrentTrackMetaData from the event subscription. Perect.
My feeling is that we should consider AVTransportURI and AVTransportURIMetaData being notified in real time rather than CurrentURI and CurrentURIMetaData being set only every minute. And then calling updateMediaInfo() every minute is useless.

**Comment by kgoderis** [comment]
@lolodomo I think this is an artefact from the reverse engineering effort I did a looooong time ago. ;-) Yes, if we can get the same info from 2 new event subscriptions, that we should go that way instead. Can you propose a PR ?

**Comment by lolodomo** [comment]
Yes I will. My current feeling after a short analysis of the code yesterday is that the change to do is very simple but then it will require a lot of testing.

**Comment by lolodomo** [comment]
I studied more in depth the current code and the change to do is more important as I first imagined.
I will probably not be able to propose a change soon. But I keep it in my TODO list.

**Comment by lolodomo** [comment]
Fix now merged.
