### ISSUE TITLE
Smarthome.git does not give me permissions to create a new branch for a pull request

### ISSUE THREAD

**Issue by gauranggunde** [eclipse/smarthome#2217]
Hello,

I would like to create a pull request for a binding extension. I tried to create a new branch and then push the changes to it. However, the git smarthome repo says permission denied. Please help ASAP. Thanks.

**Comment by tavalin** [comment]
You need to create your own fork of the repository, then create a branch in your own fork. Then you can create a pull request from your branch in your fork back to the smarthome repository.

**Comment by gauranggunde** [comment]
Thanks for the prompt reply. I forked the smarthome repo to create a local one and will create a pull request shortly. :)
