### ISSUE TITLE
Automation Demos

### ISSUE THREAD

**Issue by plamen-peev** [eclipse/smarthome#2220]
1. There should be a module type demo bundle, which shows how to define module types, create handlers for them and how to create a handler factory. It also should contains a group of commands which will be used to trigger the rules created from this module types.
   I think that following module types should be defined.
   A ConsoleTrigger, that is triggered by event with specified topic, passed as configuration property, and fills its output with value that is event property.
   A CompareCondition, which compares, by given operator, value from it's input with given constraint value.
   A ConsolePrintAction which prints the UID of the created rule, it's action UID and the output of the rule's trigger.
   A composite module type which wraps the condition.
2. There should be a bundle that defines a rule, using json file,  which uses described above module types.  It also should define a template and create a rule  using this template.
3. There should be a bundle that shows how to create a rule, using the Java API, which uses described above module types. It also should register a rule by using the template from paragraph 2.

**Comment by danchom** [comment]
I think the automation demos are too complex and not clear at the moment.  For example JSON demo defines handlers and JSON definitions of moduletypes, templates and rules. The java demo defines other motule types, handlers, templates, and providers and rules.  
There are different customers of automation module and they have different interest in use of the engine. For example one who is only interested to create rules and templates through the JSON definition can be confused of handlers presented in json demo.
We propose following changes in demos:
1) org.eclipse.smarthome.automation.sample.extension.moduletype  containing:
1.1) JSON definition of ConsoleTrigger, CompareCondition and ConsolePrintAction module types.
1.2) composite module type over the defined module types
1.3) handlers and handler factory for these module types.
1.4) console commands which will triggered the console trigger

2)  org.eclipse.smarthome.automation.sample.extension.json containing:
2.1) JSON definition of rule. The rule has to use module types defined in module types demo.
2.2) JSON definition of template. The template has to use module types defined in module types demo.
2.3) JSON definition of rule by template. The rule will use template definition from 2.2)

4)  org.eclipse.smarthome.automation.sample.extension.java containing:
4.1) Create and register rule by the RuleRegistry interface. The rule has to use the modules defined above.
4.2) Create a template by template registry.
4.3) Create and register rule using the rule template above.

5) The rest demo will not be changed.

Kai, Markus what do you think about the changes?

**Comment by kaikreuzer** [comment]
I am fine with this proposal.
Just one question: Why should 2.1 and 2.2 depend on the module types of 1? If this example would use core module types, it would even be independent of 1, right?

(and btw, where is 3 in your list?)

**Comment by danchom** [comment]
1) We was thinking that the MT from demo will be simple and understandable for users, but you are right it is better to use core MT. In that way we  will not have dependencies between demos and will show real MT in use.
2) Just counting error ;)

**Comment by kaikreuzer** [comment]
This has been added meanwhile.
