### ISSUE TITLE
Trigger Channels Part 2

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2226]
With https://github.com/eclipse/smarthome/issues/1043, we have introduced trigger channels to the framework, but as already mentioned early in https://github.com/eclipse/smarthome/issues/1043#issuecomment-184598078 that was only a first step for the basic functionality.

Imho, we are left with a dangerous situation now, if people start using it although what they would really need for their purposes are the profile, which I'd like to call part 2.

In order to discuss about how to design this second part, I would like to take [the LeapMotion controller as an example](https://www.youtube.com/watch?v=czq3S13tGVk) for a triggering input device. As can be seen in the video, it can be e.g. used to control Color items, i.e. it sends ON/OFF, percentage values for dimming and HSB values for the colors. The raw events (and thus what we are currently left with) of this device are not really suitable. There are hundreds of these events per second and they are very generic like "4 fingers at position x,y,z" or "circle to right with radius x cm". Of course one could say that such raw events are emitted and you would have to implement rules, which then try to convert them to some meaningful commands. But this obviously does not make much sense.

Instead, the binding itself should have a chance to define configuration options and depending on those configuration options it could then directly provide item commands such as ON/OFF, so that such a trigger channel could be directly linked to an existing item (which e.g. represents a light and is linked to a hue bulb).

**Comment by markusjw** [comment]
If I understand your last paragraph correctly, it matches my opinion. There are two more or less separate things:

1. To link trigger channels to items, we might need trigger channel types that match the item types. A thing (let's say a rocker switch) can now implement two trigger channels (predefined type system.button) for the two buttons. But at the same time, it could also implement a "switch trigger channel" with on/off functionality, combining both buttons/positions of the rocker switch.

2. The mapping of hand gestures to trigger channels is specific to the Leap Motion binding. Or are there generic concepts needed for other bindings as well?

**Comment by kaikreuzer** [comment]
Regarding 1:
- For a rocker, I would rather prefer a single channel with events like up_pressed, down_pressed, released - since they are not really independent (you cannot press both sides at the same time).
- What you call a "switch trigger channel" is for me the "switch profile" that could be configured on the trigger channel. The very same device/channel could also be used to control a roller shutter, in which case you would instead configure a "rollershutter profile" on it and it would send UP/DOWN instead of ON/OFF. The logic of those profiles imho does not have to be implemented in every binding; instead, the logic is the same and thus should be shared where ever possible (which is obviously only possible if the channels provide the same "raw" events, which is the case if they are based on the same system channel type). That's why I suggest the concept of "profiles".

Regarding 2:
This would be an example of a custom profile (i.e. one that comes with the binding as it does not make sense to share it, since its raw events are too specific).

**Comment by pfink** [comment]
Some ideas regarding profiles:

- Taking a look to the key-value pairs of the binding config part within the item configuration files, in OH2, the key lost it's semantic purpose. In OH1, the key determined which binding to use (e.g. `knx="..."`), in OH2 it's just always `channel="..."`. Therefore, we gained some 'syntactical capacity' here, why not reuse it for profiles?
- `channel` could be the default profile for stateful channel types which just exposes the channel's commands / state updates 1:1 to the item
- for the already existing common trigger events, it would make sense to have some useful predefined profiles that are commonly used, e.g. `toggleButton` (should translate all `PRESSED` events to toggle ON/OFF states). So if one would like to use this profile, he could just use `Switch MySwitch { toggleButton="<MY_CHANNEL>" }`. This would also make it possible to use the existing mechanisms to bind multiple profiles to the same item (could make sense in some [maybe rare] cases if the profiles used do not contradict to each other), like `profile1="<MY_CHANNEL>", profile2="<MY_CHANNEL>"`.
- It would be great if it would be possible for the end-user to add custom profiles at runtime just like rules. I think a lot of users will have special requirements how to map the input of their devices to the OpenHab model, and with this feature they wouldn't have to create a rule for every single device anymore. The "Profile DSL" could look similar to something like this:
```
profile 'shortLongSwitchButton'

if(trigger == SHORT_PRESSED)
   return ON
else if(trigger == LONG_PRESSED)
   return OFF
```
- Of course, as a nice-to-have, it makes sense to add the possibility for binding developers to also provide predefined profiles. But I think the approach mentioned above would make it obsolete to make those profiles configurable with parameters. Casual users will be happy just using the predefined profiles without the burden of extra configuration and power users will have much more flexibility if they can copy and modifiy the predefined profiles without being limited by the given configuration options. Reusability of code blocks could be achieved by scripts.

**Comment by maggu2810** [comment]
@kaikreuzer Just to ensure I understand your thoughts about profiles correctly.
Let's assume we have rockers that emit four events:
* up_pressed
* up_released
* down_pressed
* down_released

Then profiles could be used to transform that events to commands.
For example:
* profile_rollershutter_1: drive as long as button is pressed
  * up_pressed => UP
  * down_pressed => DOWN
  * up_released => STOP
  * down_released => DOWN
* profile_rullershutter_2: drive on single click as long as possible
  * up_pressed => UP
  * down_pressed => DOWN
  * up_released, down_released: ignored

Some question:
Can a profile use internal variables to depend on its previous internal state?
E.g. toggle_profile: event1 => ON, event2 => OFF, event3 => ON, event4 => OFF

**Comment by triller-telekom** [comment]
There is another interesting use case for such profiles in the ESH forum: https://www.eclipse.org/forums/index.php/t/1085997

Basically the wanted feature is the possibility to adjust a raw value from a thing before it ends up in the logic of ESH by some value. This could also be done with a profile that adjusts each value on the respective channel by  a configurable value.

**Comment by jduquennoy** [comment]
That would indeed be awesome to be able to apply a profile to a given thing to alter the values it sends.
In my case, it would be to apply a bias to a value returned by a badly calibrated sensor.
Thanks for the work you are doing on this topic !
