### ISSUE TITLE
Add Javascript info text to PaperUI

### ISSUE THREAD

**Issue by ThomDietrich** [eclipse/smarthome#2235]
A small request.

Could somebody please add the typical "If you see this, your Browser does not support Javascript" warning to the static PaperUI view?

https://community.openhab.org/t/paper-ui-empty/14623/2?u=thomdietrich

**Comment by kaikreuzer** [comment]
@ThomDietrich I am not sure if the problem in the linked thread was that the browser didn't know javascript, it was simply IE ;-) So maybe the warning should be something like "unsupported browser, use chrome, firefox or safari instead and make sure js is enaböed" or something along this line.

@aounhaider1 Could you take care of this, please?

**Comment by ThomDietrich** [comment]
IE is a problem by itself, I do not doubt that :grin: Pointing out a counted number of browsers is not fair either. Let's go with a neutral form:
https://answers.atlassian.com/questions/74647/a-javascript-warning-when-access-the-jira-website

>Warning: either you have JavaScript disabled or your browser does not support JavaScript. To work properly, this page requires JavaScript to be enabled.

**Comment by kaikreuzer** [comment]
Well, my point is that this warning is not correct. IE supports Javascript and even if the user has enabled it, the Paper UI might not work on it.

**Comment by ThomDietrich** [comment]
Aaah misunderstood. Okay, I'm sure @aounhaider1 will think of something nice to tell the user :)
