### ISSUE TITLE
Incorrect update of dateTime channel of the NTP Binding

### ISSUE THREAD

**Issue by petarnv** [eclipse/smarthome#2242]
In the NTP Binding the state of an item, linked to a NTP thing is not updated with a time from the time zone, that is set as a property in the thing configuration. Even though in the NtpHandler the state of the item is updated with a DateTimeType, containing a calendar with the proper time zone (the one set in the configuration of the thing) - https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java#L199, this state is serialized in the ThingManager, when an event is posted (https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java#L169) by the method createStateEvent() - https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java#L218, where the toString() method of the DateTimeType is used (https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java#L86), which will return the time from the current time zone(http://stackoverflow.com/questions/11337557/what-is-the-default-timezone-in-java-util-date). Because of this the state of the items is always updated with the current time zone, even if a property for the time zone is set in the thing configuration.

I have made a PR with tests for this: https://github.com/eclipse/smarthome/pull/2243

This behavior can be seen in the following ignored tests:
1) the dateTime channel is updated with the right time zone
2) the calendar of the dateTime channel is updated with the right time zone

**Comment by marcelrv** [comment]
This issue is indeed known. Unfortunately not directly fixable by the binding see

https://github.com/eclipse/smarthome/issues/992
