### ISSUE TITLE
Wemo binding does not handle REFRESH command

### ISSUE THREAD

**Issue by svilenvul** [eclipse/smarthome#2249]
During the implementation of the #2247, I have noticed that the handlers in Wemo binding do not handle REFRESH command, but the channelLinked() method in the BaseThingHandler class is sending REFRESH command. Several tests in #2247 are ignored.

I would expect that on REFRESH command the binding will send a HTTP request to the device, ask for information about the current state and update the channels. In the WemoMakerHandler and the WemoHandler no request is sent at all. 

In the WemoLightHandler I have noticed that an invalid SOAP request is sent. This can be easily reproduced if the [ignored test](https://github.com/eclipse/smarthome/pull/2247/files#diff-5190de137bdbab1910f702e400f11f83R176) is executed. The handler sends request to set the device status with null value.

**Comment by hmerk** [comment]
Thanks for opening this issue.
As I have some Additions for WeMo in mind, I will take care of this.

**Comment by hmerk** [comment]
Created PR #2277 
@svilenvul Would be fine if you could test.

**Comment by svilenvul** [comment]
I have ran the ignored tests for REFRESH command and now they are passing.

**Comment by hmerk** [comment]
@svilenvul Thanks!!!

**Comment by maggu2810** [comment]
@svilenvul As #2277 is now merged, I assume this one could be closed. Correct?
