### ISSUE TITLE
ThingManager should adapt state updates to linked item type

### ISSUE THREAD

**Issue by adarazs** [eclipse/smarthome#2253]
I have a hue light defined like this in hue.things:

```
Bridge hue:bridge:xxx "Philips Hue Bridge" [ ipAddress="192.168.1.3", userName="xxx" ] {
    0210 1 "Hue White and Color - Living Room Ceiling" @ "Living Room" [ lightId="1" ]
```

I want to have an on/off switch on my sitemap, so I defined an item for it as

```
Switch living_light_ceiling_switch "Living Room Ceiling Switch" <light> (gLights) { channel="hue:0210:xxx:1:color" }
```

I read in the documentation that I need to use the :color channel instead of :switch to make it work. So now I have a sitemap definition as

```
Switch living_light_ceiling_switch "Living Room Ceiling Switch" <light> (gLights) { channel="hue:0210:xxx:1:color" }
```

It works nicely as far as turning the light on and off from the UI but if I try to turn the light on/off from the real Hue app the state doesn't get updated in the classic UI or HABdroid. I see in the basic UI that it gets updated with its HSB value (68,88,0) instead of an ON/OFF state.

This is problematic because in openHAB 1.x I had quite a few rules depending on the ON/OFF state of the item, for example if conditions like (living_light_command is another switch item):

```
if (living_light_ceiling_switch.state != living_light_command.state) { ... }
```

 and now those are not working at all. Can this be fixed in the binding? Either create/enable the :switch channel for the thing, or make the :color channel converted to ON/OFF states when the items is a simple switch.

Issue #866 might be related, but I thought I better open a new issue for this, as that one is not really about this switch state problem. I understand that rewriting my rules to somehow check for the brightness value might work, but it's far from ideal and probably I'm not the only one who will be hit by this during transition to openHAB2.

Oh, and I'm using beta4.

**Comment by kaikreuzer** [comment]
Thanks, @adarazs, this is indeed an unexpected behavior (let's call it bug :-)). It is actually NOT a problem within the hue binding itself, but needs to be fixed in the core ESH framework instead. I therefore adapted the issue title to make this clear.

**Comment by adarazs** [comment]
Thank you for acknowledging the bug, I mean behavior. :)

I think it's clear for you at this point but just stating that this also affects dimmer types too, not just switches.

For others fighting with the same problem, my workaround is:

- remove the hue link from the switch item
- add a rule that updates the switch items periodically directly from the "color" type items like this:

```java
// for color lights
postUpdate(living_light_ceiling_switch, if(living_light_ceiling_color.state.toString.split(",").get(2) == "0") OFF else ON)
// for dimmer only lights
postUpdate(dress_light_switch, if(dress_light_dimmer.state.toString == "0") OFF else ON)
```

Now the switch items are actually updated properly to their ON/OFF state and can be used in rules, but cannot be used to control the lights (use the color or dimmer items instead). It would be also possible to add rules that change the dimmer/color items when the switches receive a command, but I didn't do that.
