### ISSUE TITLE
REST API for changing state of an item doesn't work

### ISSUE THREAD

**Issue by andrew-veresov** [eclipse/smarthome#2255]
I have a Z-Wave switch which I can control via classicui of OpenHab (turn ON/OFF).

## Expected Behavior
When REST API command is sent to change a state of the item then not only the item state must be changed in the OpenHab database but also command must be sent to the actual device.
The REST API command is:
PUT http://localhost:8080/rest/items/lamp/state
ON

## Current Behavior
UI (classicui for example) shows that the state of the device is changed, but nothing happens with an actual device. Looks like a command is not even sent to the device.
At the same time if I click on a switch on the classicui page then the device is turned ON/OFF as expected.

## Steps to Reproduce (for bugs)
Use Postman to call OpenHab REST API
Send PUT "http://localhost:8080/rest/items/lamp/state" request with plain text body "ON"
Same happens if I try to use OpenHab Swagger documentation page. 
Sending "PUT /items/{itemname}/state Updates the state of an item." via it produces same result (UI changed but command is not sent to the device)

## Context
I'm trying to control the switch via REST API

## Environment
Windows 10,
2.0.0-SNAPSHOT
Build #504
Controller and device: Aotec Z-Stick + SwiidInter Z-Wave Cord Switch

**Comment by kaikreuzer** [comment]
> Sending "PUT /items/{itemname}/state Updates the state of an item." via it produces same result  -> UI changed

This clearly contradicts your issue title. It shows that the REST API works and that item states are updated correctly.

I assume that you have some misconfiguration in your setup regarding the ZWave devices. As ZWave is not part of ESH, I close this issue here. Since it is likely that there isn't any bug, I'd suggest to seek for help in the [openHAB community](https://community.openhab.org/) first.

**Comment by andrew-veresov** [comment]
But why doing same thing throw UI does change state in UI and on device? REST API changes only UI state and not the device state.
It looks like UI and REST API doesn't call some "common method" which does actual state change on the device.

**Comment by kaikreuzer** [comment]
State change on the device is done by the binding, not by the core framework.
In order to ask the device to change its state, you actually have to issue a command - this is probably your misconception.
