### ISSUE TITLE
Duplicate channels on Thing

### ISSUE THREAD

**Issue by digitaldan** [eclipse/smarthome#2256]
A thing's channels are stored as a List<Channel> , see 

https://github.com/eclipse/smarthome/blob/e0985e90d389350580e59bfbcd7e0adaaccf7519/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java#L49

Because this is a list, its possible for a Thing to have duplicate channels with the same ID. This also means that calling "getChannel(String id)" will only return the first instance of the duplicate channel. My assumption would be that a thing can only have a single instance of a channel.

**Comment by kaikreuzer** [comment]
See also https://www.eclipse.org/forums/index.php/t/1081737/

**Comment by sjka** [comment]
@kaikreuzer in the forum discussion you mentioned to use a SortedSet. However, from a user's perspective it makes sense to keep the order in the same way as the channels were defined. Therefore a LinkedHashSet would make more sense IMHO.

However, changing the List to a Set would break pretty much everything. You sure this is a good idea? I'd suggest to ensure uniqueness internally only and keep the API stable.

**Comment by kaikreuzer** [comment]
You are right, a LinkedHashSet would be the implementation that retains the given order, a SortedSet might actually mess it up by sorting it itself.

 > However, changing the List to a Set would break pretty much everything. You sure this is a good idea?

I didn't suggest this, I only said that this should have better be done from the start.

>  I'd suggest to ensure uniqueness internally only and keep the API stable.

Yes, we should simply add some checks, that should be good enough. Probably mainly the ThingBuilder needs to be fixed.
