### ISSUE TITLE
An item should not be editable if it is bound to read only channel 

### ISSUE THREAD

**Issue by emiovska** [eclipse/smarthome#2267]
When an item is provided from the .items file and has a custom pattern, the state description readOnly property in GenericItemProvider  is set to false by default.

Currently there are two state description providers: **GenericItemProvider** and **ChannelStateDescriptionProvider** which are sorted descending by service ranking.
Moreover the ChannelStateDescriptionProvider has service ranking -1 set in the **ChannelStateDescriptionProvider.xml** file which means that
GenericItemProvider is before the ChannelStateDescriptionProvider.

When getStateDescription method is called to get the state description of an item, the method iterates over the registered  StateDescriptionProviders and returns the first found not null value. That means that if the item is provided from .items file will always has the readOnly property in the stateDescription set to false.

According to description above there is a situation when an item provided from .items file and bound to read only channel can be edited from the UI. 
According to me, this is not the desired behavior because if the item is bound to read only channel 
(like sensor or web service) does not make sense that the item can be edited from the UI.

So, should this be considered as a bug?

**Comment by kaikreuzer** [comment]
Sorry, my reply is slightly late 😲 
Yes, you are right - this is currently a limitation; you cannot define stuff like min/max/read-only in item files while the whole StateDescription information is taken from it.
What would be needed is to somehow merge information from different StateDescriptionProviders - this is something @lolodomo [suggested here](https://github.com/eclipse/smarthome/pull/3825#issuecomment-314504609) in a similar way.

**Comment by lolodomo** [comment]
And my proposal was rejected lol

I was not axare of this issue but it is anither example showing why we need a kind of merge.

**Comment by kaikreuzer** [comment]
> And my proposal was rejected lol

... in the context of the addressed issue. That doesn't mean that the idea itself has been rejected, that's why I pinged you here ;-)

**Comment by lpapazow** [comment]
This bug can still be reproduced after [this PR](https://github.com/eclipse/smarthome/pull/3825)  has been merged. 

I could create a PR which fixes this issue in a [similar  way](https://github.com/eclipse/smarthome/pull/3825/files#diff-12183f2bd5de40fa6c6bcf35817f8aacR425) by assigning the result variable to a new StateDescription which takes the isReadOnly value from the current StateDescription and all other parameters from the previous result variable.

Would that be an appropriate way to fix the issue?

**Comment by kaikreuzer** [comment]
Should be fixed by https://github.com/eclipse/smarthome/pull/4882.
