### ISSUE TITLE
Basic UI does not update visible items

### ISSUE THREAD

**Issue by remogloor** [eclipse/smarthome#2268]
In classic UI it is possible to configure items with a visibility and change the visible items by changing a switch:

Switch item=interval label="Interval" mappings=[0="Day", 1="Week"]
Text item=DayItem visibility=[interval ==0]
Text item=WeekItem visibility=[interval ==1]

Basic UI correctly shows the visible items when navigating to the frame. But when the switch is changed it won't update the visible items like Classic UI does. After a manual reload the visible items are shown correctly.

**Comment by kaikreuzer** [comment]
See also https://github.com/eclipse/smarthome/pull/2030#issuecomment-249437634, @resetnow  is already aware of it. But good to track it as a separate issue here.

**Comment by resetnow** [comment]
Yes I'm aware and I'll hopefully fix it this weekend (I think it should go as a separate PR after sitemap events are merged).

**Comment by resetnow** [comment]
It doesn't seem like sitemap events are sent when visibility state changes. @kaikreuzer could you please tell whether this feature is implemented server-side?

**Comment by kaikreuzer** [comment]
@resetnow With https://github.com/eclipse/smarthome/pull/2290, this is now implemented :-)

**Comment by kaikreuzer** [comment]
Re-opening as the there is also something left to do by @resetnow in the Basic UI.

**Comment by maggu2810** [comment]
Ah, that's the reason for the missing "Fixes ..." ;)

**Comment by kaikreuzer** [comment]
Updated https://github.com/eclipse/smarthome/issues/2268#issuecomment-252566587 to make it clearer :-)

**Comment by resetnow** [comment]
Fixed in #2294.

One thing I noticed is that widget visibility events may stop working after a sitemap file was edited and reloaded.

**Comment by kaikreuzer** [comment]
I would tend to say that this is acceptable; editing the sitemaps always required a browser refresh in the past as well.

**Comment by resetnow** [comment]
Maybe it's just me, but I had to restart ESH after adding or removing a simtemap item with visibility condition.
