### ISSUE TITLE
group function is not correctly (at all...) persisted in the mapdb 

### ISSUE THREAD

**Issue by hfanieng** [eclipse/smarthome#2269]
After setting up and restarting ESH the groups created via the new group item function of Paper UI the values like sum, avg and so on get lost.

**Comment by kaikreuzer** [comment]
I can confirm the issue.

**Comment by sjka** [comment]
Fully plausible, as `ManagedItemProvider.toPersistableElement()` does not take care to persist the function field. Definitely a bug.
