### ISSUE TITLE
Safari, iOS (iPad): PaperUI corrupted by hide icon

### ISSUE THREAD

**Issue by Boby71** [eclipse/smarthome#2285]
I'm running the latest snapshot version from openhab2.
This is what the PaperUI looks like on my iPad Air:
![img_3039](https://cloud.githubusercontent.com/assets/22266373/19224322/e8eb273c-8e83-11e6-8a06-91dd936d6d4d.PNG)
On my PC (e.g. Firefox) everything looks normal.

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you please have a look?

**Comment by mdilger** [comment]
FWIW, I am using 2 iPad's on my system and neither are showing this problem.  

First one is an iPad 2 running iOS 9.3.5 and the other is an iPad Pro running iOS 10.0.2

**Comment by Boby71** [comment]
I'm running 10.0.2 as well, rebooted the iPad and cleared all cache/temp
data in Safari.
Tried to use a differnt browser - Firefox on iOS. And the result is the
same. Don't know if Firefox has its own rendering engine or using Safari in
the background, but it's strange to see the same issue in another
browser. My hardware: iPaid Air 1

Any idea which file(s) I should check if they're really up-to-date?

Am Montag, 10. Oktober 2016 schrieb Mike Dilger :

**Comment by aounhaider1** [comment]
Is this issue only in inbox screen or is it in all other pages as well?

**Comment by maggu2810** [comment]
> Don't know if Firefox has its own rendering engine or using Safari in the background

@Boby71 FYI: http://www.howtogeek.com/184283/why-third-party-browsers-will-always-be-inferior-to-safari-on-iphone-and-ipad/

**Comment by aounhaider1** [comment]
I was only able to reproduce this issue on an iPad air simulator using openhab 2.0.0.b4 release (which does not have latest PaperUI package). Everything worked fine using openhab 2.0.0 offline and online snapshots.

**Comment by kaikreuzer** [comment]
@Boby71 Could you report the exact version you are running?
(do a `list -s | grep org.eclipse.smarthome.ui.paper` on the console)

**Comment by Boby71** [comment]
Seems like I'm having an old version:
180 | Active    |  80 | 0.9.0.b1              | org.eclipse.smarthome.ui.paper, Fragments: 185

I did for the installation what's described here under "snapshot release":
http://docs.openhab.org/installation/linux.html#package-repository-installation
And every 2-3 days I make an apt-get update and apt-get upgrade to get the latest version.

-> Isn't this the latest version available?

Best regards,
Boby

**Comment by Boby71** [comment]
Only Inbox; the rest looks fine.

Btw: Just found out, my PaperUI package has the version 0.9.0.b1 - that's an old one, right?

**Comment by Boby71** [comment]
Markus, thank you - it says exactly this: No own rendering engine on iOS allowed.
That explains the same behaviour on different browsers...

**Comment by kaikreuzer** [comment]
> I did for the installation what's described here under "snapshot release":

But you have a beta release; I know that a while ago, there was some confusing documentation and snapshots actually gave you betas. I do not know how to clean it up in your case, but the best would be if you simply test a snapshot tar.gz version.

**Comment by Boby71** [comment]
I can confirm that the error vanished as soon as I used the snapshot zip 
file instead of apt-get. Thank you.
