### ISSUE TITLE
Basic UI: 

### ISSUE THREAD

**Issue by michaeljoos72** [eclipse/smarthome#2297]
Hi

This is more a feature request:

In Classic UI it's possible to see the numbers for a group item even if mapping is used:

![image](https://cloud.githubusercontent.com/assets/20517474/19263517/ff7562c8-8f9c-11e6-950e-20928211284d.png)

In Basic UI this is not possible right now. Any plan to implement this as well?

BR
Michael

**Comment by kaikreuzer** [comment]
I'd be for it - Basic UI should behave similar to the Classic UI. @resetnow?
