### ISSUE TITLE
Minor issue in title tag

### ISSUE THREAD

**Issue by xrow** [eclipse/smarthome#2308]
Hi,

It seems that for example german umlaut "ü" out of "Menü" is not properly encoded in the HTML title of the basic ui. If the files and text are properly encoded you don't need special HTML encoding.
<img width="202" alt="unbenannt" src="https://cloud.githubusercontent.com/assets/295491/19315659/d2ce2dd8-909e-11e6-89b4-7c2e5020ee96.PNG">

**Comment by kaikreuzer** [comment]
@resetnow Could you please check?
