### ISSUE TITLE
LIFX commands sometimes not executed due to UDP packet loss

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#2321]
In the current LIFX implementation commands may not be succesfully executed due to UDP packet loss. As a result bulbs do not turn on/off or change to the correct color. In my setup it occurs quite often since I have a lot of bulbs that are motion activated. Sometimes I end up in a completely unilluminated room which is quite annoying.

I think the binding should:
- keep track of the most recently sent state change that was made with a `SetLightPowerRequest` or `SetColorRequest`
- resend the most recent state change when no `StatePowerResponse` / `StateResponse` for a state change request is received within a certain interval

Futhermore:
- the number of such retries should be limited
- the retries should disregard the online/offline state of bulbs
- it should still be possible to change the state of bulbs using other applications such as the LIFX app

Do you have any thoughts on this @kgoderis? I might also put in my own PR for this.

**Comment by kgoderis** [comment]
I have never experiences UDP packet losses, but I can imagine this is quite annoying to say the least. 

Do you plan to leverage the message ID for this purpose? e.g. you can resend for every message that did not get a return, not only the last one sent, or LightPower/Color/State. btw, it is the reason why I initially opted for the (do not remember exact denomination by LIFX here) "mechanism to explicitly demand  message confirmations". 

Secondly, do we tend to keep the order of the messages sent to a bulb, or not? e.g. will we queue messages until we get a message confirmation, or let them be send/fired in parallel? Not keeping the order of messages can have side effects. 

On a separate note, did you notice that when we switch off a light in openHAB, it still is reported as "on" in the LIFX iOS app, albeit at a very low %. Think we have to investigate that.

**Comment by wborn** [comment]
I'm currently researching what a good approach could be for tackling this issue. Besides unguaranteed delivery of packets, UDP also has no guarantees about packet order. The very reason LIFX choose to use UDP over TCP is probably to eliminate packet overhead so packets either get lost or get delivered on time which is helpful for lighting effects. Making sure each packet is received at the bulb in the correct order would again introduce the overhead which they eliminated in the first place by using UDP.

I also see packet loss when I run LIFX effects through their LIFX app. But only when I setup a lighting effect that does drastic changes with short timings. E.g. when using the color cycle effect with speed 1s and a 250 degrees change. 

It's not really an issue when there is a constant stream of HSBK packets (`SetColorRequest`) when one of the packets gets lost. Another packet will probably arrive within a second or so. I do think that we should make sure that Power ON/OFF packets (`SetLightPowerRequest`) are properly received by a bulb. These will usually not be part of those lighting effects. In a similar way we should also make sure that the last packet of a stream of HSBK packets always arrives at a bulb.

> On a separate note, did you notice that when we switch off a light in openHAB, it still is reported as "on" in the LIFX iOS app, albeit at a very low %. Think we have to investigate that.

I'm an Android user and on the Android app the whole color wheel is desaturated when the bulb is off. This also works when the bulb is switched off by the binding. Sometimes I have to reopen the bulb screen in the app to see the updated state. I also see that the binding sets the brightness to 1%. Though you would expect 0% to show up in the app. This is the result of the statements in the first `if` clause  in the `handleColorOnOffCommand`:

```
    private void handleColorOnOffCommand(OnOffType onOffType) {

        if (currentColorState != null) {
            PercentType percentType = onOffType == OnOffType.ON ? new PercentType(100) : new PercentType(0);
            HSBType newColorState = new HSBType(currentColorState.getHue(), currentColorState.getSaturation(),
                    percentType);
            handleHSBCommand(newColorState);
        }
```

The brightness could be left as is when switching a bulb on/off.

Changing the brightness in these statements to 0% has some side-effects:
* the brightness will always be 100% when you switch off and switch on a bulb with a command via the binding
* you always have to change the brightness in the LIFX app (or other applications) when you switch off a bulb with the binding

Not changing the brightness would also have some side-effects with the current implementation:
* in paper UI you can no longer see if the bulb is on or off. That could be fixed with an extra channel though
* extra logic may need to be added to the binding so `IncreaseDecreaseType` commands keep working like before

**Comment by kgoderis** [comment]
> The brightness could be left as is when switching a bulb on/off.
> 
> Changing the brightness in these statements to 0% has some side-effects:
> 
> the brightness will always be 100% when you switch off and switch on a bulb with a command via the binding
> you always have to change the brightness in the LIFX app (or other applications) when you switch off a bulb with the binding
> Not changing the brightness would also have some side-effects with the current implementation:
> 
> in paper UI you can no longer see if the bulb is on or off. That could be fixed with an extra channel though
> extra logic may need to be added to the binding so IncreaseDecreaseType commands keep working like before

@kaikreuzer If I remember well we decided to change brightness for ON/OFF switching to bring it in line with other bindings e.g. Hue. Maybe we have to do things differently for LIFX, as @wborn suggests adding an additional channel

**Comment by kaikreuzer** [comment]
No, an additional channel makes no sense. Brightness=0% simply is the same as OFF in ESH terms (and from a consumer perspective, this makes a lot of sense anyhow).
There are just two different options on how to deal with an ON afterwards:
a) go to brightness 100%
b) go to the last brightness level before it was turned off (be it by receiving 0% or OFF, which are the same).
For different people and uses, a or b might be the better option, there isn't a "right" one. So we imho should offer this as a channel configuration setting.

But I agree with @wborn that in both cases, you could simply turn LIFX off without changing the brightness and turn it back on on an ON command, where in case a you would additionally also set the brightness to 100% (or actually it could be a configurable value, doesn't have to be 100%).

Does this make sense?

**Comment by kgoderis** [comment]
mmh... I would make it behave like the LIFX app itself. Having to change the brightness on the iOS app is quite annoying when being in a mixt environment of both ESH and iOS app (it is the Wife factor ;-) ). LIFX clearly sees brightness and switching as different things. 

With respect to b. here above, we could have side effects of lost state after a restart of the runtime and so forth....

**Comment by wborn** [comment]
The channel configuration option is already working well for me after a little coding. The channel configuration option goes on to the `color` channel for the color lights, and the `brightness` channel for the whites only lights. 

I came up with the following thing type `config-description`.

```
        <config-description>
            <parameter name="powerOnBrightness" type="integer" min="0" max="100" required="false" unit="%">
                <label>Power on brightness</label>
                <description>Brightness level used when switching on the light. Use empty value to leave brightness as is.</description>
                <default>100</default>
            </parameter>
        </config-description>
```

This single configuration option allows for the following brightness options when switching ON/OFF:
* the current (default) behavior: OFF: 0%  , ON: 100%
* user customizable power on value: OFF: 0%, ON X%
* LIFX like behavior: not changing the brightness when switching the light ON/OFF

I think the only issues with this are:
* When upgrading an existing ESH installation, it seems the default is LIFX like behavior. When lights are deleted/readded the default 100% is in place. An additional configuration option could solve that. But too many options makes things overcomplicated.
* With this kind of LIFX behavior you can no longer see in Paper UI if the bulb is ON/OFF. It is no issue for me, but for other it might be. Though they can always use the old behavior.

**Comment by wborn** [comment]
Thanks for making this happen Kai and Karel!

**Comment by kaikreuzer** [comment]
The kudos go to you @wborn for making this extensive refactoring!
