### ISSUE TITLE
PaperUI: message "PaperUI works best ..." on latest versions of Chrome, Edge, IE on Windows 10

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2325]
I have installed the latest openHAB Build (#542) on Windows 10. But now Paper UI complains that id works best with modern browsers.
This message appears on Chrome 54, Edge 38.14393 and also Internet Explorer 11.321.14393. Firefox 47 is OK.

In addtion on Chrome the configuration page for the HomeMatic is shown incomplete. On top of the page you can see the message, but not completelsy visible (looks the same on Edge and IE).

![image](https://cloud.githubusercontent.com/assets/616792/19413090/8b968b94-9324-11e6-8ec3-234279484e83.png)

On Firefox it looks perfect 
![image](https://cloud.githubusercontent.com/assets/616792/19413096/b2b62658-9324-11e6-94d6-b1dd5c5df0c3.png)

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you have a look, please?

**Comment by aounhaider1** [comment]
I could not reproduce this issue on Chrome. I tried with chrome 53 and 54 and everything seems to work fine. On edge and IE the error makes sense as it is they both do not support SSE. It is, however, missing the error class which I have added here https://github.com/eclipse/smarthome/pull/2335) With https://github.com/eclipse/smarthome/pull/2254 we will not need this message at all.
Can you please check your Chrome console if there are any errors there?

**Comment by MHerbst** [comment]
Checked it again with build #546. The form works now correct on all browsers. 
Only the message "PaperUI works ..." ist not completely visible on Edge:
![image](https://cloud.githubusercontent.com/assets/616792/19492035/77426480-9575-11e6-8169-011f651c592a.png)
