### ISSUE TITLE
WatchService Provides Only File Name Instead of Relative Path to File

### ISSUE THREAD

**Issue by dstivanov** [eclipse/smarthome#2341]
When implementing the AbstractWatchService, a developer can provide an option to track the sub-directories of the watched directory by implementing the AbstractWatchService.watchSubDirectories() method. However, when the sub-directories are tracked, the AbstractWatchService.registerDirectory(Path subDir) will be called for each sub-directory. This means that the file path, passed to the AbstractWatchQueueReader.processWatchEvent is containing only the name of the target file, but not its relative path to the watched directory.

Previously I have submitted an PR to fix this issue (https://github.com/eclipse/smarthome/pull/1597), but it was reverted (https://github.com/eclipse/smarthome/pull/1755) due to problems with FolderObserver.

Currently I know that there are two pending PRs that are proposing detailed tests for the classes that are using the Watch service - FolderObserver(https://github.com/eclipse/smarthome/pull/2074) and ConfigDispatcher(https://github.com/eclipse/smarthome/pull/2108). As long as these two PRs are merged I will be able to easily adapt my code to fix the described issue with the Watch service.

By the way, there is also a pending PR from @tomhoefer (https://github.com/eclipse/smarthome/pull/1668) that waits for the fixes on the AbstractWatchService in order to be merged.

I think that this set of related PRs could be easily merged if we take a look at the pending PRs for the tests.

Regards,
Mitko

**Comment by maggu2810** [comment]
> Currently I know that there are two pending PRs that are proposing detailed tests for the classes that are using the Watch service - FolderObserver(#2074) and ConfigDispatcher(#2108). As long as these two PRs are merged I will be able to easily adapt my code to fix the described issue with the Watch service.

#2074 has been merged

**Comment by dstivanov** [comment]
Thank you @maggu2810 ! I will try to help @petarnv with fixing the issues in the Config Dispatcher tests.

**Comment by svilenvul** [comment]
The tests for ConfigDispatcher [#2108](https://github.com/eclipse/smarthome/pull/2108) are merged as well, and a PR is opened for this issue: #2432

**Comment by dstivanov** [comment]
@svilenvul @maggu2810 As all the PRs in regard to this issue are merged I am going to close it.

@tomhoefer You can now continue you work on https://github.com/eclipse/smarthome/pull/1668 . Thanks for your patience!

**Comment by kaikreuzer** [comment]
@dstivanov We are only left with failing unit tests now, see https://github.com/eclipse/smarthome/pull/2557#issuecomment-263602682.

If they are not fixed, we will have to revert it (again)...

**Comment by kaikreuzer** [comment]
Ok, all seems well now!
