### ISSUE TITLE
VoiceManager fails to find suitable voice

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2352]
There is some problem with the selection of the right voice to use in VoiceManager.

If e.g. MaryTTS is installed, you have:

```
openhab> voice voices
marytts:bits1hsmm bits1-hsmm (de)
marytts:cmuslthsmm cmu-slt-hsmm (en_US)
marytts:bits3hsmm bits3-hsmm (de)
```

Calling

```
openhab> voice say test
```

results in 

```
21:39:47.778 [ERROR] [se.smarthome.core.voice.VoiceManager] - Error saying 'test ': Unable to find a voice for language de
```

When the locale (in Configuration->System) is set to "de" instead of "de_DE", TTS works as expected.

**Comment by Jaghova** [comment]
Is there any plan to add other lenguages in case they are supported? As far as I know VoiceRSS supports multiple lenguages.

**Comment by kaikreuzer** [comment]
The voice infrastructure supports ANY language, it all just depends on what voices are available. Currently, the VoiceRSS TTS has [support for de and en](https://github.com/openhab/openhab2-addons/blob/master/addons/voice/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudImplementation.java#L67), but this can be easily extended to all 26 languages offered by VoiceRSS (@jochenhiller, correct me, if I am wrong).

**Comment by JochenHiller** [comment]
@Jaghova Yep, there are more languages, which I planned to add. The initial contribution was done in just 2 evenings, I wanted to add first test cases before adding more features. But sure, I will add all supported languages of VoiceRSS extension soon.

@kaikreuzer about the reported issue: VoiceRSS extension does register languages with both country and region code (e.g. de_DE). So I did not run into that issue.

Just as an idea which I came up during testing and demoing that feature: the "say" command could support an option to specify the locale, e.g. "say --locale "de" "Hallo Welt"?
Nevertheless, the reported bug has to be fixed either.

**Comment by kaikreuzer** [comment]
> the "say" command could support an option to specify the locale, e.g. "say --locale "de" "Hallo Welt"?

The say() command in rules supports defining a voice that should be used - through this, the locale is also directly chosen. I would think that this is good enough (and we could add this option to the console say command as well, yes), since in most cases, you really want to chose the voice that is used.

**Comment by kaikreuzer** [comment]
I actually think that this problem might be fixed through the [commented out code](https://github.com/eclipse/smarthome/blob/360455fa2f7ba5d226794788186018c0c27cfd87/bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/VoiceManager.java#L339) in VoiceManager - unfortunately, this feature is only available in Java 8, so this code cannot be enabled (yet)...

**Comment by shorty707** [comment]
> The say() command in rules supports defining a voice that should be used - through this, the locale is also directly chosen. I would think that this is good enough (and we could add this option to the console say command as well, yes), since in most cases, you really want to chose the voice that is used.

To the documentation of say() ... I think the following should work for VoiceRSS ... but results in "cannot be resolved to an item ?
say("Hallo Welt",de_DE)

**Comment by cauer71** [comment]
Is it now possible to activate the language output in german?
