### ISSUE TITLE
invalid point to ItemThingLinkRegistry

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2357]
The JavaDoc of the public non-static method `ItemChannelLinkRegistry.getBoundThings(String itemName)` statues that the method is deprecated and the method `ItemThingLinkRegistry#getLinkedThings(String)` should be used instead.

https://github.com/eclipse/smarthome/blob/d87b1532643a1fbcdebe338e934db8b8c955507c/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java#L83

I wasn't aware of such a ItemThingLinkRegistry.

Also the `LinkEventOSGiTest.groovy` announces it adds also tests for `ItemThingLinkRegistry`.

For the tests it is easy, let's remove the comment that it adds test for that classes, too.

How should we change the comment of the `getBoundThings` method?
In the ESH source tree this method is called in tests of `ItemChannelLinkOSGiTest` only.

**Comment by kaikreuzer** [comment]
As the JavaDocs says "Will be removed soon", we might simply remove it now?
The idea of having an item for a Thing in order to be able to define a label is deprecated, since the Thing has a label property itself by now - so I would think the method is obsolete.
