### ISSUE TITLE
smarthome.js behind a proxy, event subscription wrong host.

### ISSUE THREAD

**Issue by quazzie** [eclipse/smarthome#2362]
I have openhab behind a nginx proxy.
Smarthome.js tries to subscribe to "http://127.0.0.1:8080/rest/sitemaps/events/...".
It should strip the "protocol://host:port" part from the Location response of /rest/sitemaps/events/subscribe

**Comment by BClark09** [comment]
Your nginx proxy is set up incorrectly I feel. 

Would you mind posting the configuration that you're using? Or comparing it to: [openHAB's docs](http://docs.openhab.org/configuration/nginx.html) on the subject?

**Comment by quazzie** [comment]
Hah, embarrassing!
You are correct. I had an error in my proxy config.
I had even looked at the doc's..

Thanks a bunch!
