### ISSUE TITLE
Sitemap Events should have header: X-Accel-Buffering = "no" 

### ISSUE THREAD

**Issue by BClark09** [eclipse/smarthome#2368]
# 2300 Fixed the problem with REST SSE behind a buffered reverse proxy.  However the change is not applied to Sitemap SSE.

The same header needs to be applied to [SitemapResource](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java) in order to pass events through a buffered reverse proxy.

**Comment by BClark09** [comment]
Was discussed in the previous PR, but thought it would be best to have an open issue for it.

**Comment by kaikreuzer** [comment]
@kolkoo Could you be so kind to create a PR for that?

**Comment by kolkoo** [comment]
It's happening as we speak!

**Comment by kolkoo** [comment]
Created #2388
