### ISSUE TITLE
Sitemap events widget IDs aren't the same as IDs obtained through ItemUIRegistry for Default type widgets

### ISSUE THREAD

**Issue by resetnow** [eclipse/smarthome#2370]
This was discussed in #2295, but I decided to open a new issue to define a problem better and to propose some solutions because I don't know how to fix it in BasicUI (and if I should fix it there at all).

When user specifies a Default type widget in a sitemap, this type is resolved through ItemUIRegistry.resolveDefault. The problem is the resulting widget does not contain the same references as original; in fact, there is no parent object. Therefore, when ItemUIRegistry.getWidgetId is called later for the resolved widget, item name is returned instead of the position in the sitemap.

Sitemap events code, on the other hand, handles sitemaps differently and produces correct IDs.

As a result, BasicUI doesn't update values of changed Default widgets as they are detached from their parent widgets.

As for solutions, I don't have any that I think look good:
1. Adding a setParent method to Widget interface and modifying EObject properties will break indexes for other widgets with the same parent;
2. Storing widget ID as a property probably could help (the property can be copied from default widget to the one replacing it) but the property should be updated on sitemap change.

Anyway, I would appreciate any feedback.

**Comment by lolodomo** [comment]
Your second option looks interesting.
It could be an additional map in the item UI registry storing the original widget id for each replaced default widget.
I have the feeling it could work.

**Comment by lolodomo** [comment]
Why not building a full copy of the widgets with widget resolution for default rather than having a mix of original and new widgets ? This copy will have correct parent / children and so no problem widget id.

**Comment by lolodomo** [comment]
We could define a new object that inherits from Widget but add the id as property.

**Comment by lolodomo** [comment]
Adding a new object would mean changing a lot of code. I think we just need an additional field in the Widget class to store the internal id. As Widget class is generated from DSL, it requires to update the sitemap syntax. I don't know if it is possible to specify an "hidden" field in the syntax ?

Once we have this field in Widget, the changes will be simple to set and use it in the UI items registry to solve the issue.

**Comment by lolodomo** [comment]
If we could have set the container for the created widget, our problem could have been solved by one line code !

I don't know what it is but I see methods eGet and eSet on the Widget class, and they are relative to feature. If we could use them to store the container, it could be one solution.

**Comment by lolodomo** [comment]
@sjka @kaikreuzer  : please close this issue, the merged PR #3471 fixed it.
