### ISSUE TITLE
Item Label using only Map Transformation fails

### ISSUE THREAD

**Issue by J-N-K** [eclipse/smarthome#2371]
An item defined in a .items file with a label using a MAP transformation

`String         Feiertag_Name       "[MAP(holidays_de.map):%s]"`

leads to 

`2016-10-30 13:07:24.043 [WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type MMAP
2016-10-30 13:07:24.044 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - couldn't transform value in label because transformationService of type 'MMAP' is unavailable`

(note that the M is doubled to MMAP) while

`String         Feiertag_Name       "Test [MAP(holidays_de.map):%s]"`

works fine. (OH 2.0.0b4)

**Comment by ThomDietrich** [comment]
Confirmed with latest snapshot.

**Comment by bdleedy** [comment]
Workaround is a space in front of [, but I can confirm this issue.

**Comment by ThomDietrich** [comment]
An item should always have a label. If you want your sitemap to not show a label, define `label=""` for the corresponding element there.

Maintainers: This is a bug. It should be either supported or forbidden to have no label defined for an item. The "MMAP" error is clearly a bug in the evaluation algorithm.

**Comment by bdleedy** [comment]
If I take a String in items and then in the sitemap have Text item=thatstring, the label for the sitemap element is on the left and the label for the item is on the right. That doesn't blank the items label.

**Comment by ThomDietrich** [comment]
I believe you got me wrong?

```
# item
String KodiTitle "Episode/Movie Title [%s]" (gKodi) {xbmc="<[#livingRoom|Player.Title]"}

#sitemap
Text item=KodiTitle label="" icon="kodilogo"
```

**Comment by bdleedy** [comment]
Yeah, that's exactly what I'm talking about. So with that config, nothing would be on the left but "Episode..." would be on the right.

**Comment by ThomDietrich** [comment]
Sorry, of course the value placeholder has to be in there. With the corrected example above:

![grafik](https://cloud.githubusercontent.com/assets/2870104/20990589/dcf59370-bcd9-11e6-9a12-68e9720c8802.png)

**Comment by ThomDietrich** [comment]
Thank you @maggu2810
