### ISSUE TITLE
Fix bugs in ESH scheduler and add more unit tests

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2394]
When reviewing https://github.com/eclipse/smarthome/pull/2094, I noticed a couple of issues (see [here](https://github.com/eclipse/smarthome/pull/2094#discussion_r86155377), [here](https://github.com/eclipse/smarthome/pull/2391/files#r86192254) and [here](https://github.com/eclipse/smarthome/pull/2391/files#r86191773)) that definitely would result in regressions wrt cron scheduled rules.

I think we need to do more extensive testing so that we can be sure that we do not break the functionality for existing (mainly OH2) users. There is no test coverage for the scheduler functionality itself yet, only for the expression parsing part - this needs to be addressed as well.

**Comment by kgoderis** [comment]
@kaikreuzer Some of your comments in https://github.com/eclipse/smarthome/pull/2391 seem to be missing; I copy from email digest to recap them:

> There seems something to be severely wrong in the scheduler implementation.
> If I enable TRACE logging on this unit test, I end up with many thousand lines of log file - it seems that calls like e.getTimeAfter(now) result in huge iterations with many thousand candidates just to find the next execution time; I'd assume that there should be more efficient ways?
> 
> As a consequence of this slow execution, the cron job actually never ends - it is executed indefinitely. I guess there is a bug that when the task is being removed and the next execution of it has already started that the removal fails in that case.

You might be interested in looking - with your mathematician hat on - at how the unified algorithm works for all types of Expressions. At the time I first developed the algorithm for the RFC5545 expressions, and then implemented cron expressions following the same strategy. Maybe after all this algorithm is not well suited for the cron expressions, and maybe we had to come up with something simpler and faster. @maggu2810 Do you have any creative ideas wrt this?

**Comment by kaikreuzer** [comment]
We might consider using https://github.com/jmrozanec/cron-utils for the CRON expressions and do a scheduler implementation similar to [this one](https://github.com/jprante/elasticsearch-gatherer/blob/master/src/main/java/org/xbib/cron/CronThreadPoolExecutor.java). Would this be an option, so that we do not have to come up with a clever algorithm ourselves?

**Comment by kgoderis** [comment]
I will study the code; the scheduler implementation you mention is similar to what we had initially - you killed it at the time because it effectively blocks threads in the scheduler pool (e.g. the Thread.sleep call). Woud you use the cron-utils lib as is, or shall we have our own equivalent implementation?

**Comment by kaikreuzer** [comment]
> you killed it at the time because it effectively blocks threads in the scheduler pool

Oh, right, I didn't see it in that code - that is of course still a valid argument and blocking threads must be avoided.

> Woud you use the cron-utils lib as is

It seems to be actively maintained, so if it is suitable as is, I would suggest to include it as a binary.

> I would keep the Quartz notation btw

What do you mean by this? You mean the syntax of the cron expressions is different?

**Comment by kgoderis** [comment]
> Woud you use the cron-utils lib as is
> It seems to be actively maintained, so if it is suitable as is, I would suggest to include it as a binary.
> 

Just had a look at the code - this is complicated stuff, I would definitely not want to fiddle with that. 

> I would keep the Quartz notation btw
> What do you mean by this? You mean the syntax of the cron expressions is different?

cron-utils supports different cron expression formats, including Quartz. Since we have used Quartz historically, I would not introduce other/new cron formats at all in our own code base.

**Comment by kaikreuzer** [comment]
ack to both :-)
