### ISSUE TITLE
MQTT Transport: Excpetions

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2396]
I recently had a look at "illegal catches" in my code using Checkstyle: http://checkstyle.sourceforge.net/config_coding.html#IllegalCatch

So I noticed that the MqttSenderChannel provides an interface method publish that states that this method throws "Exception".
It seems very uncommon to use such the class "Exception" in an API.

Shouldn't this be changed on the interface to an IOException or something similar?

**Comment by maggu2810** [comment]
https://github.com/eclipse/smarthome/blob/e0985e9/bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttSenderChannel.java#L24

**Comment by 9037568** [comment]
This allows an implementing class to throw any exception it needs to. That seems both fitting and necessary.
