### ISSUE TITLE
Color controls for HSB seem to be independant.

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#2399]
It seems that the 3 controls for color in PaperUI are independant controls?  If I slide the Sat, then I get a saturation, but H and B are 0. Likewise for others - if I change Hue, then S and B are 0.

For example, below I moved the brightness, and I get the following -:
```
2016-11-01 17:43:43.490 [DEBUG] [.c.thing.internal.ThingManager:458  ] - Delegating update '0,0,29' for item 'zwave_device_15785c713e3_node15_color_color' to handler for channel 'zwave:device:15785c713e3:node15:color_color'
```

The controls look as follows -:

![image](https://cloud.githubusercontent.com/assets/1041475/19900289/e604718e-a05a-11e6-9238-de443c3f646c.png)

I would have expected saturation and hue to be values as indicated in the image.

**Comment by sjka** [comment]
That's indeed not the plan - when one of the values changes it should indeed keep the values of the other ones

**Comment by kaikreuzer** [comment]
I cannot confirm this issue:
```
2016-11-03 17:00:43.895 [DEBUG] [.c.thing.internal.ThingManager:464  ] - Delegating update '90,64,59' for item 'lifx_colorlight_D073D50058D6_color' to handler for channel 'lifx:colorlight:D073D50058D6:color'
```

**Comment by BClark09** [comment]
I believe I am getting the same problem. Not just paper though.

```
{
  "link": "http://192.168.0.10:8080/rest/items/Bedroom_Light_Colour",
  "state": "100",
  "type": "Color",
  "name": "Bedroom_Light_Colour",
  "label": "Colour",
  "category": "ColorLight",
  "tags": [],
  "groupNames": [
    "Group_Lights"
  ]
}
```

**Comment by kaikreuzer** [comment]
Ok, so it is actually the runtime that discards the HSB value and only sends a brightness value as a state update. The Paper UI only takes this and sends it back, so it is not the fault of the Paper UI.

The cause is VERY likely https://github.com/eclipse/smarthome/pull/2334 - @sjka Any chance to analyze this asap?

**Comment by sjka** [comment]
yes, and I found the root cause. hang on a sec...

**Comment by kaikreuzer** [comment]
I'll build an ESH stable today, so that this fix is available in OH by tonight.
