### ISSUE TITLE
Listing channels bound to thing

### ISSUE THREAD

**Issue by bboser** [eclipse/smarthome#2409]
1) How do I get a list of all channels?
I tried overriding 
`channelLinked(ChannelUID did)`
in my handler class (which extends from BaseThingHandler), but it gets never called.

Background: I am trying to connect OH2 to a security system that has lots of "items" with all sorts of properties. In OH2 I am interested in some of them and define items for those. E.g.
`String name7 "Zone  7 name [%s]" <text>	{ channel="nx584:security:creston:zone7#name" }`

There is literally an infinite number of possible channels. So when an event arrives from the security system, I have no way of knowing if an item is interested and if so, what parameters it specifies in its channel.

2) Specifying these "parameters" is another challenge. OH1 apparently permitting specifying those directly in what now is called "channel". But in OH2 the "channel" must adhere to a very restrictive syntax. E.g. the following is not permitted:
`String name "blah" { channel="nx584:security:panel:partition=1:zone=7:name" } `

What's the correct way to accomplish this in OH2?

**Comment by kaikreuzer** [comment]
Closing in favor of https://www.eclipse.org/forums/index.php?t=rview&goto=1746819#msg_1746819.
