### ISSUE TITLE
BasicUI: Can't scroll through entire Selection list

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#2427]
If I define a Selection widget in the sitemap with more options than will fit in the browser window, I'm unable to scroll through the entire list of options.  This can be reproduced on multiple platforms and multiple browsers.  This is on build 555.

Sitemap widget:
```
Text label="Test Selection" {
    Frame {
        Selection item=TestItem label="Selection"
            mappings=[1="Option 1", 2="Option 2", 3="Option 3", 4="Option 4", 5="Option 5", 6="Option 6", 7="Option 7", 8="Option 8", 9="Option 9", 10="Option 10", 11="Option 11", 12="Option 12", 13="Option 13"]
    }
}
```

Scrolling all the way to the bottom of the list works fine.
![screenshot from 2016-11-09 09-16-40](https://cloud.githubusercontent.com/assets/19286354/20141675/6458c0d0-a65f-11e6-943f-7aa066b1d04f.png)

But scrolling to the top doesn't go all the way to the top of of the list.
![screenshot from 2016-11-09 09-17-00](https://cloud.githubusercontent.com/assets/19286354/20141676/64592d86-a65f-11e6-8546-2639de8f1885.png)

**Comment by kaikreuzer** [comment]
@resetnow Could you have a look?
