### ISSUE TITLE
Mixed content on Paper UI when showing Location items

### ISSUE THREAD

**Issue by hakan42** [eclipse/smarthome#2428]
When displaying Location items, a map segment from http://www.openstreetmap.org is included, which leads to a "mixed content" warning if the Ui is accessed via https (for example when behind a reverse proxy which adds SSL capability)

**Comment by hakan42** [comment]
Wow, this was fast, thank you 😄

**Comment by kaikreuzer** [comment]
I thank you for not only entering an issue, but also directly delivering the fix for it - that's how I like it 👍
