### ISSUE TITLE
Audio command input to ESH

### ISSUE THREAD

**Issue by shankarkalmade** [eclipse/smarthome#2431]
Hi I am working on integrating voice based command to ESH and there is not much documentation available. Can you please suggest better documentation or code snippet to start with

**Comment by kaikreuzer** [comment]
Please use our forum for general questions/discussions: https://www.eclipse.org/forums/index.php/f/271/

Note that there is currently a pending PR regarding audio documentation: https://github.com/eclipse/smarthome/pull/2425
