### ISSUE TITLE
Extend ProxyServlet connection timeout

### ISSUE THREAD

**Issue by ThomDietrich** [eclipse/smarthome#2434]
Class ProxyServlet has a [connection timeout of 5000ms](https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServlet.java#L761).

**Short:** Is it possible to extend this timeout?

**Long:** On a "Raspberry Pi 3 Model B Rev 1.2" with openHAB and InfluxDB+Grafana all on one system, the png creation used for an Image sitemap element takes up to 8 seconds. This results in no visible image and this error message:

[2016-11-10 18:05:28.872 [WARN ] [thome.ui.internal.proxy.ProxyServlet] - Proxy servlet failed to stream content due to a timeout](https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServlet.java#L222)

Discussion: https://community.openhab.org/t/influxdb-grafana-persistence-and-graphing/13761/134

**Comment by kaikreuzer** [comment]
Ok for me to increase it. What value would you suggest? Is hard-coded ok or shall we add optional configuration of this value through ConfigAdmin?

**Comment by ThomDietrich** [comment]
The reporting user in the community mentioned 8 seconds in his tests. If no downside comes with it (other processes depending on the timeout), I would go up to 15-30 to stay safe. ConfigAdmin: Up to you, I would be okay with a hard-coded value.

**Comment by kaikreuzer** [comment]
I'd go for 15 hardcoded seconds then - I think everything that takes longer is anyhow not acceptable to the user of the UIs...
@maggu2810 Any preferences from your end?

**Comment by maggu2810** [comment]
I still think about, what about if we receive some weeks later an issue "on my embedded board it takes <current_timeout> + 1"...
IIRC we increased the NTP timeout multiple times (I could be wrong).

But I agree, longer as 15 seconds is perhaps not accepted anyhow.

**Comment by ThomDietrich** [comment]
fine with me. I guess the RPi 3 is already at the lower end of possible OH platforms. Everything below that and running multiple applications is questionable

**Comment by kaikreuzer** [comment]
At least you should not run any bigger databases of image rendering on them...

**Comment by ThomDietrich** [comment]
Was just remembered of this issue. Is anything holding this back? In case you are waiting for PR from me, I would prefer for one of you to handle that.

**Comment by kaikreuzer** [comment]
You mean like https://github.com/eclipse/smarthome/pull/2659?

**Comment by ThomDietrich** [comment]
:sweat_smile: Thanks.
