### ISSUE TITLE
Paper UI - configure basic UI - icon format not set

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2438]
Just a minor thing. In Paper UI, if you open either Configuration => Services => UI => Basic UI or Configuration => Services => UI => Classic UI, the bahaviour with "icon format" is different.
For Classic UI, the field is alread filled with a value.
With Basic UI, the field is not filled and you have to select one value as it is a mandatory field. I was expecting "Vector" to be selected automatically as SVG is the default icon format for Basic UI.

**Comment by kaikreuzer** [comment]
This is not an issue of the Paper UI - it correctly shows what is configured in the solution (in your case, openHAB, which defines the default settings [here](https://github.com/openhab/openhab-core/blob/master/features/openhab-core/src/main/feature/feature.xml#L112).
All seems correct in there and in my freshly installed OH2 distro, it all looks good:

<img width="656" alt="screen shot 2016-11-11 at 11 44 30" src="https://cloud.githubusercontent.com/assets/3244965/20212579/4283cd14-a804-11e6-9c2c-9c6aca8d1928.png">

**Comment by lolodomo** [comment]
Maybe I don't remember exactly in which UI the icon type is not set and the problem may be more with Classic UI than Basic UI.
I searched for kind of config in all repo except openhab-core !
In the file you are pointing, I can see that iconType is defined for Basic UI but not for Classic UI. Maybe it explains what I notice.

**Comment by kaikreuzer** [comment]
Indeed, as you can see in the referenced file, it is not set for the Classic UI. Feel free to create a PR for it!
