### ISSUE TITLE
Basic UI: not updating the value of a group item

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2443]
I have a group item that displays the number of lights ON:
```
Group:Switch:OR(ON, OFF) GEclairage "Eclairage [(%d ON)]" <light> (All)
```
When the frame containing this item is opened and one light is switched ON or OFF, the valie is not updated in Basic UI.
Value is correct if I reopen the frame.
```
			Switch item=GEclairage mappings=[OFF="Eteindre"]
```
PS: it is OK in Classic UI and HABdroid.

**Comment by lolodomo** [comment]
@resetnow : I found why group value is not updated.
https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js#L1307
_t.container is null. I will search what's wrong in this line but maybe you have an idea (hint) ?

PS: for the same reason, the value color is not updated too.

**Comment by resetnow** [comment]
I would first check if there's an event in the SSE stream.

**Comment by lolodomo** [comment]
I separated the problems by opening the issue #3141 something not specific to Basic UI.

The current issue is specific to Basic UI: not able to refresh any group value received.
