### ISSUE TITLE
smarthome:audio play with Sonos: stop after few seconds

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2452]
I tried (with snapshot 583) the console command "smarthome:audio play" with one of my Sonos as sink.
The playback starts as expected but then stops suddenly after few seconds.

**Comment by lolodomo** [comment]
As I can see in the current code of the Sonos binding, there is a 10 seconds hardcoded for the audio servlet call. i imagine the difficulty is to determine the duration of a MP3 file from the file ?

**Comment by kaikreuzer** [comment]
Can you link to the code which you mean? No, in general the length of the mp3 should not matter - Sonos should play it back until it is finished and then switch back to the original playlist.

**Comment by lolodomo** [comment]
Line 87 in SonosAudioSink
https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosAudioSink.java#L87

**Comment by kaikreuzer** [comment]
Ah, ok. This parameter is actually meant to define how long a stream can be requested from the http servlet (time of the request). Once it started serving it, it should keep running; if this is not the case, it is indeed a bug (but rather in the AudioServlet than in the Sonos binding).

**Comment by lolodomo** [comment]
Ok, so the problem is elsewhere as the playback starts.
The console is "locked", is it normal ? It should start the job in background and then return ? Maybe there is a timeout in the console ?

**Comment by kaikreuzer** [comment]
Yes, blocking is normal; see also https://github.com/eclipse/smarthome/issues/2333 (1).
For the console it might make sense to launch these commands in a separate thread, though, this isn't currently done.

**Comment by lolodomo** [comment]
Please try with a music MP3 file of 4 minutes for example and you will reproduce the issue.
I just forgot to check the logs.

**Comment by lolodomo** [comment]
I just tried again. I can confirm that there is no error logged. What seems to happen is that the Sonos handler decided the end of the playback while not finished. I have the feeling now that the problem could be in the notification sound mechanism and how it detects end of playback.
I will have to add traces to understand what happens exactly.

**Comment by lolodomo** [comment]
Ok found.
waitForFinishedNotification in the Sonos binding handler is using a timeout of 10 seconds.

**Comment by lolodomo** [comment]
https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java#L2286

**Comment by kgoderis** [comment]
@R-Edelhoff Roland, can you have a look at this since ( I think) the notification code was added by you?

**Comment by R-Edelhoff** [comment]
Yes, we have limited the notification sound duration to 20s as it was supposed for short notifications and not for complete audio tracks. If we have a use case for playing whole tracks we could think about increasing the maximum play duration.

**Comment by lolodomo** [comment]
Ok so it is only a limitation of the Sonos audio sink.
I agree that I see no real need for playing a long file.
Maybe this limit should be documented somewhere in docs.openhab.org, maybe in the page describing audio management.
We could at least increase a little this timeout in case users would like to speech a long text.
To avoid this limit, I think the solution would consist in computing the file duration inside the audio manager and provide this duration as parameter to any selected audio sink when calling process(). Unfortunately, computing this duration is certainly not easy and depending on the file format.

**Comment by kaikreuzer** [comment]
I think the 20 seconds limit is ok, because it only applies for notification sounds on Sonos (which restore the original playlist afterwards). The feature is not meant to stream whole songs or similar.
Note that I also use the "normal" playURI of Sonos when serving urls (e.g. Internet radio streams).

We could circumvent the issue by always using playURI, but this obviously would throw away all the nice volume and playlist handling for notification sounds. We could also check the length of the audio and decide on this, but it would be pretty intransparent for the user what is happening.

The best way that comes to my mind is to register a second audio sink for Sonos, so that the user has the choice which one to use in which case.
For the current audio sink, we can add a note to the Sonos documentation that informs the user about the 20 seconds limit - I think this is acceptable.

@lolodomo Coming back to earlier comments here: Is there still another problem with the AudioServlet so that the playback actually stops already after 10 seconds and not after the (Sonos-specific) 20 seconds?

**Comment by lolodomo** [comment]
@kaikreuzer : I corrected my comment about 10 seconds, it was just a bad reading of the constant value in the code ! I just tried again and compute the timeout and I can confirm that it ends after a little more than 20 seconds. So I see no problem with the AudioServlet.

Your idea to define another audio sink for Sonos looks no so bad but will make things even more complex to understand for the final user...

**Comment by kaikreuzer** [comment]
> Your idea to define another audio sink for Sonos looks no so bad but will make things even more complex to understand for the final user

I agree, so I would suggest to only add such a feature if there is really a demand.

**Comment by lolodomo** [comment]
That is OK for me.
By the way, the limit is now documented.
