### ISSUE TITLE
Paper UI: voice configuration

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2453]
Using snapshot 583, I just played with TTS. I installed VoiceRSS, set my API key and selected VoiceRSS engine in Configuration => System => Voice.
After a restart, I discovered that this panel does no more offer to select the voice. I see now only two fields: Default Text-to-Speech and Default Human Language Interpreter.

When I run a smarthome:voice say command, I don't know what language is selected. Can the command be enhanced to offer the ability to define the language ?

**Comment by kaikreuzer** [comment]
This isn't a bug in the Paper UI, but an issue in the VoiceRSS service. It uses the same ID for all its voices:
```
        {
          "label": "default (Finnish)",
          "value": "voicerss:default"
        },
        {
          "label": "default (Chinese)",
          "value": "voicerss:default"
        },
        {
          "label": "default (Japanese)",
          "value": "voicerss:default"
        },
        {
          "label": "default (English)",
          "value": "voicerss:default"
        },
```
so the Paper UI does not stand a chance to distinguish them.
This should therefore be reported at https://github.com/openhab/openhab2-addons/issues.
@JochenHiller FYI, we discussed that issue already.

**Comment by lolodomo** [comment]
@kaikreuzer @JochenHiller : I think it could be simply fixed by updating the methods getAvailableVoices() and getAvailableVoices(Locale locale) in class VoiceRSSCloudImplementation. The default voice for a locale could be named using locale.toLanguageTag()
