### ISSUE TITLE
OpenHAB 1 reference in iconset bundle/API

### ISSUE THREAD

**Issue by satish-nikam** [eclipse/smarthome#2461]
Follwing files in iconset bundle/API has OpenHAB 1 reference.

smarthome/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/src/main/java/org/eclipse/smarthome/ui/iconset/classic/internal/ClassicIconProvider.java
smarthome/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/README.sh 
smarthome/extensions/ui/iconset/org.eclipse.smarthome.ui.iconset.classic/README.md

It shows following text as description.
"This is a modernized version of the original icon set of openHAB 1.

**Comment by kaikreuzer** [comment]
Well, this is a reference to the history where it comes from. Why is this a problem?
