### ISSUE TITLE
Basic UI: Colorpicker not updating on state changes

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2463]
If the color picker dialog is open and the item state changes, the picker does not update its color.
While this is probably good while using the picker (you do not want the know to jump around all the time), it would be nice if it would update itself whenever the knob is not used (i.e. the user does not actively change anything).

@resetnow Is this possible without too much effort?

**Comment by resetnow** [comment]
>Is this possible without too much effort

Yes, I'll do it as soon as I have time.

**Comment by resetnow** [comment]
Fixed in  #2536

**Comment by triller-telekom** [comment]
@kaikreuzer @sjka Can you please close this issue as well?
