### ISSUE TITLE
Extends functionality of composite module type handler

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#2465]
At the moment the outputs of Trigger and Action composite module types can reference the outputs of their child modules (in form of childModuleId.outputId). I think it will be better if the composite output can access data from beans or maps produced by the outputs of child modules.
For example:
A - is a module with output 'out1' producing on its output bean B 
B - is a bean which has a method getC() returning bean C and getMap() retruning map object.
C - is a bean which has a method getX()
map - is a Map object which has property value with key y.

If a module A is a child module of composite module type CA  then the output of CA can reference the child output in following way:
A.out1 -> output of CA returns bean B, as the current implementation do.
A.out1.c -> output of CA will returns bean C
A.out1.c.x -> output of CA will returns C.getX() value
A.out1.c.map.y -> output of CA will returns C.getMap().get(y) value

**Comment by kaikreuzer** [comment]
Sounds useful. I guess you want to implement that in the resolver using reflection, right?

> A.out1.c.map.y -> output of CA will returns C.getMap().get(y) value

I'd prefer to align this with the Javascript syntax, i.e.:

> A.out1.c[y] -> output of CA will returns C.getMap().get(y) value

**Comment by danchom** [comment]
Yes the access to beans will be through the reflection.
I think I can support JS syntax. I will converted [] into dots.
A.out1.c[y]  -> A.out1.c.y -> C.getMap().get(y) value
Is this ok for you?

**Comment by kaikreuzer** [comment]
Why would you want to use dots instead of square brackets? What is the problem to allow the reference to be `A.out1.c[y] `? I think it would be important to see the difference of a field or a map access. In theory. For the implementation it should be even easier, because whenever you come across square brackets, you know that you need to use `get("y")`, while for dots you need to use `getY()`. In theory, you could also come across a Map implementation that has a field called Y, i.e. there is a getY() method and get("y") could return something completely different.

**Comment by danchom** [comment]
> Why would you want to use dots instead of square brackets?
1) At the moment we don't use [] anywhere in our json syntax. I think it will be easier for the users to access data in unified way.
2) I think to implemented this feature by recursion 
>  For the implementation it should be even easier
Agree, It will be clean how to parse it. There are not problems like:
A.out1.c is a map and  a.c reference is looking for.   First we have to check for 'a.c' key in the map and if it does not exist then check for A.out1.c.a object and look for b key.
With your syntax it is easier: A.out1.c[a.b] or A.out1.c[a].b or A.out1.c[a][b] 
Ok I'll implement it in your way

**Comment by danchom** [comment]
merged #2584
