### ISSUE TITLE
Classic UI not displaying sitemap mappings correctly

### ISSUE THREAD

**Issue by BlinkyBillToo** [eclipse/smarthome#2468]
I have the following sitemap
`sitemap Test label="Test"
{
	Frame label="Indoor Climate Control" {
		Selection item=HVAC_5_thermostat_mode icon="climate" mappings=[0="Off",1="Heat",2="Cool",3="Auto"]
	}
}
The item is from a CT-100 Thermostat.

When I make a selection in the classic UI and return to the Frame, the mapping key is displayed and not the mapping text, as shown below
<img width="240" alt="classicui" src="https://cloud.githubusercontent.com/assets/23483257/20316741/2f82ef8a-ab31-11e6-887d-0ce573d23f3f.png">
This is not the case with the basic UI as shown below
<img width="242" alt="basicui" src="https://cloud.githubusercontent.com/assets/23483257/20316828/993baa16-ab31-11e6-985a-eb257a83bee7.png">

I migrated this configuration across from OpenHAB1, which also displayed the mapping text correctly.

**Comment by kaikreuzer** [comment]
I can confirm this issue (imho it was working in ESH recently), but couldn't yet find an obvious reason for this regression.

**Comment by triller-telekom** [comment]
This issue was fixed with PR #3381

@kaikreuzer @sjka : Please close this issue
