### ISSUE TITLE
Hue group issue since latest snapshot

### ISSUE THREAD

**Issue by rene54321** [eclipse/smarthome#2471]
Hi,

I have upgraded to latest snapshot build from today. Now the Hue groups are not working anymore. The old release from 11.11.16 was working fine. Has something changed since than?

Following error in the log when I turn off and on an light of that group:

```
[pse.smarthome.core.items.GenericItem] - failed notifying listener '[gHueLights_Wohnzimmer_Color (Type=GroupItem, BaseType=ColorItem, Members=8, State=null, Label=Wohnzimmer, Category=colorwheel), Licht_Farbe_WZ_TV_Rack_Rechts, null]' about state update of item java.lang.NullPointerException: {}
```

Also the Paper UI control tab Show internal error 500. I am also not able anymore to switch an Hue Color Group on and off. As suggested by Kai I tried to remove the (:Color:Max) from my goup but still the same behaviour. If I remove the groups from the item definition than all is working correctly also the paper ui control tab is working and showing all things with values again.

item config:
```
Group:Color:MAX gHueLights_Alle_Color "Alle Lampen" 

Color Licht_Farbe_WZ_TV_Rack_Oben       "TV-Rack Oben"       <colorwheel> (gHueLights_Alle_Color)     [ "Lighting" ] { channel="hue:0200:00178816e03f:1:color" }
Color Licht_Farbe_WZ_TV_Rack_Links      "TV-Rack Links"      <colorwheel> (gHueLights_Alle_Color)     [ "Lighting" ] { channel="hue:0200:00178816e03f:2:color" }
```

sitemap:
```
Colorpicker item=gHueLights_Alle_Color label="Alle" 
```
Regards René

**Comment by kaikreuzer** [comment]
If it worked before, it might be related to https://github.com/eclipse/smarthome/pull/2393 or a similar change. @sjka WDYT?

**Comment by rene54321** [comment]
Hi,

still the same with the build from today:

2016-11-17 14:13:08.515 [WARN ] [pse.smarthome.core.items.GenericItem] - failed notifying listener '[gHueLights_TV_Rack_Color (Type=GroupItem, BaseType=ColorItem, Members=3, State=null, Label=TV Rack, Category=colorwheel), Licht_Farbe_WZ_TV_Rack_Links, The argument 'state' must not be null or empty.]' about state update of item java.lang.IllegalArgumentException: The argument 'state' must not be null or empty.: {}

**Comment by kaikreuzer** [comment]
Nobody claimed that anything has been fixed meanwhile.

**Comment by rene54321** [comment]
Hi,

any news here? Seems I am the only one with this problem :-(

**Comment by kaikreuzer** [comment]
Did you notice that there are 210 open issues here?

**Comment by rene54321** [comment]
You are right sorry.

**Comment by maggu2810** [comment]
Do we have any information about the ref used by the latest known working version?

**Comment by rene54321** [comment]
Hi,

thats an good question. I think the old version was around the 11.11. But I am not 100% sure as I do the updates often in the last time.

**Comment by kaikreuzer** [comment]
@maggu2810 : I am pretty sure that it is related to the changes done in the context of https://github.com/eclipse/smarthome/pull/2334.

**Comment by sjka** [comment]
at least the timing matches. will have a look.

**Comment by sjka** [comment]
I think I found the root cause: #2504 
As there are no tests so far covering group items, I would ask everybody following this issue to double-check that I didn't miss anything else in that area...
