### ISSUE TITLE
Sonos notification sound: not working when line-in is playing

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2474]
Playing with the new TTS feature, I tested the Sonos notification mechanism with a lot of different sources being played and with the queue being filled or not.
It is working very well except in one case, when the current source is the line-in. The behavior is even different, depending on whether the queue is empty or not. In one case, the TTS audio is rendered but the line-in is then not restored. In the other case, the TTS audio is just not rendered at all.

**Comment by kgoderis** [comment]
@lolodomo Tx. Where you able to pinpoint the exact location of the issue in the code base?

**Comment by lolodomo** [comment]
I think "playNotificationSoundURI" does consider the case of "x-rincon-stream".
I can try to fix the issue.

**Comment by lolodomo** [comment]
What is required is just a method isPlayingLineIn + a special handle method for this case that will look very similar to handleRadioStream. I will propose a fix later today.

**Comment by lolodomo** [comment]
I fixed it. I will prepare a PR.

**Comment by lolodomo** [comment]
PR fixing the issue has been submitted.
