### ISSUE TITLE
Support for DLNA Media Renderers in Sonos binding

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2475]
I trace here a work in progress to add support for any DLNA Media Renderer in the Sonos binding.
The binding will automatically discover any DLNA media renderer. A new "DLNA" thing type will be added. This thing type, like any Sonos thing type, will allow to control playback, adjust volume, start playback of an URI and show the DLNA media renderer as an audio sink in openHAB (and so offer the TTS feature).
Playing an URI and audio sink features will probably work well only for few DLNA media renderers.

**Comment by kaikreuzer** [comment]
Why would you want to add that to the Sonos binding? Imho, it should be a new DLNA binding as it is in no way related to Sonos hardware, right? Rather comparable with e.g. the Chromecast binding of openHAB2.

**Comment by lolodomo** [comment]
Because we have already almost everything in the Sonos binding. A DLNA binding will be a kind of duplicate of the Sonos binding and will require a double maintenance.
I have no time and no wish for developing a new bindong so I stop immediately my work ( I just lost few hours of my free time).

**Comment by kaikreuzer** [comment]
>  I stop immediately my work ( I just lost few hours of my free time)

I didn't mean to offend you, I just asked a simple question...

**Comment by lolodomo** [comment]
This was discussed on the forum in the past and I got an encouragement from @kgoderis to go in this way.

**Comment by lolodomo** [comment]
Xxxcchttps://community.openhab.org/t/dlna-upnp-binding/1790

**Comment by lolodomo** [comment]
In fact, we could even rename the Sonos binding in DLNA binding and have support for specific Sonos features.

**Comment by kgoderis** [comment]
Ok - maybe my misunderstanding in the openhab.org thread, but I thought you copied over the Sonos code base and turned that into a DLNA binding. I have no experience at all with DLNA so difficult for me to judge to what extend DLNA and Sonos is overlapping. Now, with the Sonos binding being quite a complex chunk of code I would personally not introduce new stuff in there, but keep it specific to Sonos. This is reverse-engineered stuff after all

**Comment by kaikreuzer** [comment]
If there is code in common, we should use this opportunity to actually take some code out of Sonos and move it e.g. in the io.upnp bundle (or create a io.dlna bundle that can be shared and reused).
Note that there are probably also others requiring similar code, see e.g. https://github.com/openhab/openhab2-addons/pull/1431/files#diff-33d9ad525c7fd29cda2c1d2404bd5c2bR34.

**Comment by tavalin** [comment]
> Because we have already almost everything in the Sonos binding. A DLNA binding will be a kind of duplicate of the Sonos binding and will require a double maintenance.
I have no time and no wish for developing a new binding so I stop immediately my work ( I just lost few hours of my free time).

You have to remember not everyone has a Sonos so to have to install the Sonos binding to control my DLNA-capable Onkyo/Yamaha/any-other-brand AVR is not intuitive from a user-perspective.  As Kai said, if we can create some reusable DLNA code then moving it to it's own package/bundle so be reused sounds best and should eliminate the need for double maintenance.

**Comment by lolodomo** [comment]
Ok, I agree with you. So I close this enhancement proposal and let someone else work on a proper DLNA binding.
