### ISSUE TITLE
More flexible configuration references in Composite modules

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2477]
A configuration of a child module within a composite module can refer to a configuration value of the composite module using the $ symbol:

```
               "configuration":{  
                  "message":"$compositeMessage"
               }
```

This only works if this placeholder is the parameter value as a whole.
I know tried to define a module type like this:

```
    {
      "uid":"xsecondsTrigger",
      "label":"Fixed Rate",
      "description":"triggers a rule every x seconds",
      "visibility":"VISIBLE",      
      "configDescriptions":[  
         {  
            "name":"seconds",
            "type":"INTEGER",
            "label":"Seconds",
            "description":"Time to wait between executions.",
            "required":true,
            "min":1,
            "max":60
         }
      ],
      "children":[
            {
               "id":"1",
               "type":"TimerTrigger",
               "configuration":{
                  "cronExpression":"0/$seconds * * * * ?"
               }
            }
         ]
      }
```
what is currently not supported - but I think it would be a worthwhile enhancement.
I am not sure though, whether a $ symbol is enough to clearly identify a reference (and not be a part of the string), especially as it is not really clear, where it ends.
So we might consider to use e.g. `${seconds}` or go for a syntax like IFTTT is using, which would be `{{seconds}}` (which might be more end-user compatible and less developer-centric).

@danchom WDYT?

**Comment by danchom** [comment]
We have already support for this. You have to use following syntax:
"cronExpression":"0/${seconds} * * * * ?"

You can check module type of ItemStateChangeTrigger where we already use this feature.

"children":[
            {
               "id":"itemStateChangeTriggerID",
               "type":"GenericEventTrigger",
               "configuration":{
                  "eventSource":"$itemName",
                  "eventTopic":"smarthome/items/${itemName}/state",
                  "eventTypes":"ItemStateChangedEvent"
               }
            }
         ],

**Comment by danchom** [comment]
The difference between single and multiple references are:
1) When use single ref $x, it is replaced by the value of the object x, There is a type value check between types of property containing the reference and the type of referred property.
2) in the complex case where the  referred  property is part of some string pattern, the property is converted to string and after that it is replaced into the pattern.
May be we have to use same syntax (the second one) for both cases? What do you think?

**Comment by kaikreuzer** [comment]
Interesting, thanks for pointing that out - I indeed missed that. Maybe it is worth to add a section to the documentation for that feature as well?

> May be we have to use one and the same syntax ${x} for both cases?

It would be less error-prone. Can we always automatically decide whether the value or its string should be used, if we only find "${x}"? if the types map, we probably could always go for the value, if the target is a string, we could always use a toString(), right?

**Comment by danchom** [comment]
I think if the property value is just ${x} we have always replace it with its value. 
When it is part of the pattern :  "bla ${x} bla${y}" it should be replaced with its toString value.
Should we have to support $x for backward comparability for existing module types?

**Comment by kaikreuzer** [comment]
> I think if the property value is just ${x} we have always replace it with its value. 

No, because the child config parameter could be of type STRING, while the composite parameter is a DECIMAL.

> Should we have to support $x for backward comparability for existing module types?

Not because of me - we could simple adapt all module types within ESH, no need for backward compatibility. @maggu2810 fine for you as well?

**Comment by maggu2810** [comment]
I used it on very few places, so fine to change for me as well.
