### ISSUE TITLE
Basic ui GUI not updating when zwave device is changing state from on or off

### ISSUE THREAD

**Issue by arins** [eclipse/smarthome#2482]
Hi!
I own this dimmer [https://www.m.nu/flush-dimmer-gen5-qubino](https://www.m.nu/flush-dimmer-gen5-qubino)

My config looks like this

```
Text label="Office" icon="office" {
                        Switch item=zwave_device_0b45ea30_node2_switch_dimmer icon="light"
                        Text item=zwave_device_0b45ea30_node2_meter_watts label="Test [%.2f]" icon="energy"
                }
```

When I switch the light on (not dimming) from the actual dimmer on the wall the basic ui GUI is not updating but the watt meter is updated with correct value. If I refresh the page the switch is set to ON in the GUI.
Same thing happens if I switch the light off from the actual dimmer. The GUI is still showing ON but the meter is refreshed to 0. If i refresh the page the dimmer is set to OFF  in the GUI.

Turning the light ON or OFF from the GUI works flawlessly.

**Comment by kaikreuzer** [comment]
This rather seems to be an issue with the Z-Wave binding, not a general issue with the Basic UI, which in correctly updates, if there is a state update event.

**Comment by arins** [comment]
No I don't agree because openhab Android app and classic web interface works just fine with same openhab instance. The gui is always up to date and also responds when switch is changing state. But maybe the binding s reporting something wrong when state is changing?

**Comment by kaikreuzer** [comment]
Well, you should first investigate if you have an issue with the binding or with a specific UI.
UIs can (and should!) all be tested completely independent of any binding. Simply issue state updates on the console (`smarthome:update <itemname> <newstate>`) and see what happens.

**Comment by arins** [comment]
I will try that and come back with results.

**Comment by arins** [comment]
I ran smarthome:update zwave_device_0b45ea30_node2_switch_dimmer ON in the karaf console. Nothing happened in the GUI so I refreshed the webpage the GUI showed it was on. Same happens when I OFF it as well.
I tried the same command while watching the gui in openhab classic UI and android app and it worked there so there is something wrong with the basic ui.

**Comment by arins** [comment]
ok it was my mistake I was proxying openhab through nginx and the eventstream was not handled correctly. When I fixed that it worked. Read this post on stackoverflow: http://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx

But I noticed I had to send ON twice through karaf console to make it go from OFF to ON but not the opposite. Also If switch the light on nothing happens but then I can set state once to ON in the karaf console it goes to ON in the GUI. Something is still fishy.

short
When I send ON from karaf console the android app updates but I have to send ON twice to make the basic UI to update.



the event stream

```
message	{"topic":"smarthome/items/zwave_serial_zstick_0b45ea30_serial_sof/state","payload":"{\"type\":\"DecimalType\",\"value\":\"1866\"}","type":"ItemStateEvent"}	
08:28:47.264
message	{"topic":"smarthome/items/zwave_serial_zstick_0b45ea30_serial_sof/statechanged","payload":"{\"type\":\"DecimalType\",\"value\":\"1866\",\"oldType\":\"DecimalType\",\"oldValue\":\"1865\"}","type":"ItemStateChangedEvent"}	
08:28:47.267
message	{"topic":"smarthome/items/zwave_device_0b45ea30_node2_meter_watts/state","payload":"{\"type\":\"DecimalType\",\"value\":\"10.1\"}","type":"ItemStateEvent"}	
08:28:47.268
message	{"topic":"smarthome/items/zwave_device_0b45ea30_node2_meter_watts/statechanged","payload":"{\"type\":\"DecimalType\",\"value\":\"10.1\",\"oldType\":\"DecimalType\",\"oldValue\":\"9.1\"}","type":"ItemStateChangedEvent"}	
08:28:47.268
message	{"topic":"smarthome/items/zwave_device_0b45ea30_node2_switch_dimmer/state","payload":"{\"type\":\"OnOffType\",\"value\":\"OFF\"}","type":"ItemStateEvent"}	
08:28:50.255

here it is off and I send ON and nothing happens 
<------------------>

message	{"topic":"smarthome/items/zwave_device_0b45ea30_node2_switch_dimmer/statechanged","payload":"{\"type\":\"PercentType\",\"value\":\"0\",\"oldType\":\"PercentType\",\"oldValue\":\"100\"}","type":"ItemStateChangedEvent"}	
08:28:50.256
message	{"topic":"smarthome/items/zwave_device_0b45ea30_node2_switch_dimmer/state","payload":"{\"type\":\"OnOffType\",\"value\":\"ON\"}","type":"ItemStateEvent"}	
08:28:54.360
message	{"topic":"smarthome/items/zwave_device_0b45ea30_node2_switch_dimmer/statechanged","payload":"{\"type\":\"PercentType\",\"value\":\"100\",\"oldType\":\"PercentType\",\"oldValue\":\"0\"}","type":"ItemStateChangedEvent"}	
08:28:54.360

I send ON again 
<-------------------------------------->

	message	{"topic":"smarthome/items/zwave_device_0b45ea30_node2_switch_dimmer/state","payload":"{\"type\":\"OnOffType\",\"value\":\"ON\"}","type":"ItemStateEvent"}	
08:29:23.195

after this its shows on
<--------------------------------------->
```
