### ISSUE TITLE
Proposal for tests for org.eclipse.smarthome.core.audio

### ISSUE THREAD

**Issue by petarnv** [eclipse/smarthome#2489]
`org.eclipse.smarthome.core.audio` is one of the core bundles, that is not tested. I'm thinking of implementing tests for it, but recently I've seen a couple of PRs, related to the audio (e.g. https://github.com/eclipse/smarthome/pull/2426). @kaikreuzer, are you planning other changes of the audio and do you think that it is a good moment for tests for that bundle to be implemented?

**Comment by kaikreuzer** [comment]
Hi @petarnv! I think this bundle is done for the moment, I do not expect any bigger additions or refactorings for now - so yet, having test coverage on it would be awesome!

**Comment by petarnv** [comment]
A public PR is now submitted - https://github.com/eclipse/smarthome/pull/2687

**Comment by sjka** [comment]
#2687 was merged some time ago. It was just missing a reference for the auto-close to work.
