### ISSUE TITLE
System interpreter: adding french syntax

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2490]
I am interested in adding french syntax to the system rule interpreter.
Will work on it and propose a PR when done.

**Comment by kaikreuzer** [comment]
Nice :-)

**Comment by lolodomo** [comment]
In french, the equivalent of "the" can be "le", "la" or "l'" like for example "le machin", "la chose" or "l'exemple".
Considering that my item has "exemple" for label, will the current code be able to recognize "l'exemple" as being "l'" + my item label ?

**Comment by kaikreuzer** [comment]
No idea - have a try yourself. I fear that it won't work as expected - you might need to adapt the tokenizer to also treat ' as a symbol where words need to be separated.

**Comment by lolodomo** [comment]
I took a look to the method tokenize and I discovered that all ' are first suppressed. Hopefully, it was well thought ;) and we have locale as parameter for this method and I can update the method in case of franch.
I think I should replace any ' by a space so that a text like "faire l'action" will become "faire l action".

**Comment by lolodomo** [comment]
@kaikreuzer : we have the console command "smarthome:voice interpret" but is there an available call to the interpreter we can use in rules ?

**Comment by kaikreuzer** [comment]
Yes, right here: https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/actions/Voice.java#L73

**Comment by lolodomo** [comment]
Now implemented and merged.
