### ISSUE TITLE
[hue] Osram Lightify Plug not recognized during discovery

### ISSUE THREAD

**Issue by hakan42** [eclipse/smarthome#2496]
I have three Plugs from Osram integrated into my Hue network: (Links, sorry for the Amazon link but I could not find any neutral documentation, even on osram.de)

https://www.google.de/?gws_rd=ssl#q=osram+lightify+plug

https://www.amazon.de/Schnittstelle-Erweiterung-LIGHTIFY-Systems-herk%C3%B6mmlicher-Leuchtmittel/dp/B00YSXBP90

During discovery through OH2 (Build 594), I am told that the plugs are not supported:

    2016-11-19 10:59:33.529 [DEBUG] [binding.hue.handler.HueBridgeHandler] - Hue light 10 added.
    2016-11-19 10:59:33.530 [DEBUG] [l.discovery.HueLightDiscoveryService] - discovered unsupported light of type 'On/Off plug-in unit' and model 'Plug_01' with id 10

On the Hue app, the switches are considered to be "Light" items. Is there any way to get more debug information so we can resolve this issue?

**Comment by kaikreuzer** [comment]
We indeed only have support for [dimmable plug-in units](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueLightDiscoveryService.java#L56), not for On/Off ones - this is the first time that I see those. Support would need to be added to the binding.

**Comment by hakan42** [comment]
Sorry to reopen this, but with (offline) build 610, I still get the "unsupported light" message for my bulbs:

    2016-11-24 08:28:33.481 [DEBUG] [l.discovery.HueLightDiscoveryService] - discovered unsupported light of type 'On/Off plug-in unit' and model 'Plug_01' with id 8
    2016-11-24 08:28:33.486 [DEBUG] [l.discovery.HueLightDiscoveryService] - discovered unsupported light of type 'On/Off plug-in unit' and model 'Plug_01' with id 9
    2016-11-24 08:28:33.491 [DEBUG] [l.discovery.HueLightDiscoveryService] - discovered unsupported light of type 'On/Off plug-in unit' and model 'Plug_01' with id 10

This is with a clean installation with empty mapdb, cache and tmp directories.

**Comment by maggu2810** [comment]
@kaikreuzer Would it be possible (using some automated mechanism) to identify the ESH Git rev that is used in the OH builds?

**Comment by kaikreuzer** [comment]
Well, it is fairly easy to find out the timestamp of the build:

```
openhab> list -s | grep smarthome
 92 | Active   |  80 | 0.9.0.201611181452    | org.eclipse.smarthome.config.core
...
```

And with https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/changes, it is easy to see what PRs have already made it in the build and which don't (hint to @hakan42: This one here isn't yet published).

**Comment by maggu2810** [comment]
That allows the reporter to check.

I think about a method for the ESH developers.
I don't think, that:
* downloading the respective OH distribution
* check the timestamp of the ESH bundles
* go to the URL and check the changes
* ..
is something someone want to do to help on a problem.

So we could ask the reporter to report the ESH timestmap in addition to the OH build number.
I assume the timestamp fit to the start of the build, so we could use the Git history of that timestamp to find the resp. rev (there are only the last 6 releases on HIPP visible).

**Comment by hakan42** [comment]
Ah, cool, I will keep a bookmark on the changes page.  And in the meantime, compile this one binding from sources myself 😄 

for my understanding: Is this "-Stable" build job automatically building master or is it somehow triggered manually?

**Comment by kaikreuzer** [comment]
I trigger it manually in order to keep the disruptions low.
https://github.com/eclipse/smarthome/pull/2519 is e.g. a breaking change that will require adaptions in openhab-core, so if I'd create a stable release now, it would break the distro...
