### ISSUE TITLE
Yahoo Weather shows wrong air pressure

### ISSUE THREAD

**Issue by NorbertHD** [eclipse/smarthome#2502]
The Yahoo Weather binding shows the wrong air pressure. Currently it shows 33491 hPa which is about 33 times to high. Normal air pressure is around 1013 hPa.

**Comment by sjka** [comment]
I just checked: that's what comes back from the Yahoo API, claiming pressure values have the unit "mb" (which I assume stands for "millibar"). So from that perspective the binding is okay, the bug lies on Yahoo side.

Anyway... The closest unit I could find would be [inHg](https://en.wikipedia.org/wiki/Inch_of_mercury), which could explain the values: currently we get for Berlin 

```
34033.22 inHg(?) / 33.86389 inHg/hPa = 1005 hPa
```

which matches reality (or at least what Yahoo displays on their website...). So, WDYT? Should we simply fix it in the binding anyhow?

**Comment by kaikreuzer** [comment]
In [older versions](https://github.com/eclipse/smarthome/blob/0.7.0-release/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java#L123) of this binding, we also provided a "unit" parameter in our request, defining whether we want metric or us results. Maybe the API is providing correct us results and we just wrongly put hPa as a label next to it...? But right, if Yahoo returns "mb" with the response, that is definitely wrong there.

I'd be ok to transform the value in our binding code as you suggest.

**Comment by NorbertHD** [comment]
Perhaps you should only transform if a condition is met. Like: if value greater 15000 then value = value / 33.86389.
If Yahoo eventually sends really millibar(hPa) then it works also.

**Comment by sjka** [comment]
> Perhaps you should only transform if a condition is met.

Good thought, I did it like that in #2511

**Comment by sjka** [comment]
PS:

> In older versions of this binding, we also provided a "unit" parameter in our request, defining whether we want metric or us results.

btw, we [still](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java#L157) do that. And it's effective: if we switch it to "f", then we get the us units. Funny enough, the pressure is equally wrong there: it actually is in mb but claimed to be inHg. So they really mixed them up.

**Comment by kaikreuzer** [comment]
Do they have an issue tracker where we could report that? 😎

**Comment by sjka** [comment]
> Do they have an issue tracker where we could report that? 😎

Nothing you would consider as such - the only thing I could find is the YDN forum. Apparently those who are left are shielded pretty well from the public. I [tried](https://developer.yahoo.com/forums/#/discussion/11441/pressure-uses-the-wrong-units-in-the-weather-table)  nevertheless...
