### ISSUE TITLE
NTP Test: IDE errors

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2506]
My Eclipse IDE shows the following errors for the NTP Test project:

| Description | Resource | Path | Location | Type |
| ----------- | -------- | ---- | -------- | ---- |
| The type org.osgi.service.component.ComponentContext cannot be resolved. It is indirectly referenced from required .class files | NtpOSGiTest.groovy | /org.eclipse.smarthome.binding.ntp.test/src/test/groovy/org/eclipse/smarthome/binding/ntp/test | line 1 | Java Problem | 
| The project was not built since its build path is incomplete. Cannot find the class file for org.osgi.service.component.ComponentContext. Fix the build path then try building this project | org.eclipse.smarthome.binding.ntp.test | | Unknown | Java Problem |

@petarnv Have you seen this errors, too?

**Comment by maggu2810** [comment]
It could be solved by adding the package org.osgi.service.component to the "Import-Package" section.

```diff
diff --git a/extensions/binding/org.eclipse.smarthome.binding.ntp.test/META-INF/MANIFEST.MF b/extensions/binding/org.eclipse.smarthome.binding.ntp.test/META-INF/MANIFEST.MF
index d315238..bd4bc54 100644
--- a/extensions/binding/org.eclipse.smarthome.binding.ntp.test/META-INF/MANIFEST.MF
+++ b/extensions/binding/org.eclipse.smarthome.binding.ntp.test/META-INF/MANIFEST.MF
@@ -22,4 +22,5 @@ Import-Package: groovy.lang,
  org.eclipse.smarthome.test.storage,
  org.hamcrest;core=split,
  org.junit,
- org.osgi.framework
+ org.osgi.framework,
+ org.osgi.service.component
```

But if it is only indirectly referenced shouldn't the class be available by the dependency at all?

**Comment by sjka** [comment]
> @petarnv Have you seen this errors, too?

Not sure if it helps, but at least I do...

**Comment by petarnv** [comment]
@maggu2810, last time I was working on the NTP Tests, there were no such errors. Now, when I pull the latest changes, I get the same errors. The only solution, that I can find is the same as yours - https://www.eclipse.org/forums/index.php/t/823810/.

**Comment by sjka** [comment]
As it is a test fragment anyway, it surely does not hurt to add this dependency to it then.

**Comment by maggu2810** [comment]
> As it is a test fragment anyway, it surely does not hurt to add this dependency to it then.

You are right, I don't think it is important for the test bundles...
But I think we should know what we are doing and why this is necessary.
