### ISSUE TITLE
Paper UI: Extensions menu

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2510]
IIRC The Extensions navigation menu entry has been only visible if there has been an extension service in the past.
Why is it visible now all the time?

**Comment by maggu2810** [comment]
Is it related to #2320?

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you comment?

**Comment by kaikreuzer** [comment]
@kolkoo As you did #2320, do you have any suggestion how this could be solved?

**Comment by kolkoo** [comment]
We can make the root resource return only currently available services. I can prepare a PR. Should I?

**Comment by kaikreuzer** [comment]
Would be awesome :-)

**Comment by kolkoo** [comment]
#2523

**Comment by sjka** [comment]
just fyi: #2523 has been merged.

**Comment by maggu2810** [comment]
> just fyi: #2523 has been merged.

I know, I merged it. :wink: Thanks for the reminder. There has been to much tasks open... Sorry
