### ISSUE TITLE
ContactItem: OpenCloseType as accepted command type

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2528]
OpenCloseType is not listed as an accepted command type for a contact item.
My feeling is that it should.

**Comment by watou** [comment]
ContactItem is meant to represent a passive contact closure (like a reed switch) or similar device that can only report its state as open or closed.  It doesn't make sense to command such a device to change its state.  Other item types like RollerShutterItem or SwitchItem can be commanded to change their state.

**Comment by lolodomo** [comment]
Ok.
@watou: so we have no item that can accept an OPEN or CLOSE command ?
In this case, I think we should suppress these command types from the system HLI.

**Comment by kaikreuzer** [comment]
We could actually think about not having OpenClosedType implement Command anymore. I don't know what bindings might make break through that...

**Comment by lolodomo** [comment]
I close the issue as it is finally expected to not have OpenCloseType as accepted command type for a ContactItem item.

**Comment by euphi** [comment]
Please reconsider the decision to not accept commands for ContactItems.

Simple and important use case:

- Frequent test of an alarm system.

I have a group of ContactItems that trigger an alarm if Group-state is OPEN (simple OR-function).
For an alarm system it is common to have a test function. This shall be done by just adding the TestContact as a normal contact to the group.

**Comment by watou** [comment]
@euphi Instead of commanding the contact, you can update its state to be OPEN or CLOSED.  To do this from a UI, you could have a command-able item type (like a Switch item) which, when it receives a command, updates the state of a Contact item to be OPEN or CLOSED using a rule.  So your TestContact item will behave like any other Contact item.
