### ISSUE TITLE
System HLI: not accepted command type

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2529]
The system HLI returns a wrong message when you request a command to an item and the command type is not accepted by the matched item type. The error tells you that no match was found with this label while it should indicate no match with this label and command type.
I would suggest to update the message of the property "no_objects" for all languages to include the command type.

**Comment by lolodomo** [comment]
In English, we could replace "There is no object named like that." by "There is no object named like that accepting <command> command."
What do you think ?

**Comment by maggu2810** [comment]
@lolodomo I agree, that the message should be changed.
I am not familiar with the HLI code, but if the item is found but the command type does not fit, shouldn'T the error message be "The referenced object does not accept the given command type" (or something similar)?

**Comment by lolodomo** [comment]
That would be even better but that requires to add a new error message.
The change is a little more complex to do but of course doable.
I can go in that direction.
I need the same message in German ;)

**Comment by lolodomo** [comment]
Other point: there are commands for opening and closing things but they don't work as the OpenCloseType command tyoe is accepted by no item.
Should we suppress these commands from the syntax ?

**Comment by kaikreuzer** [comment]
> we could replace "There is no object named like that." by "There is no object named like that accepting command."

Note that both are different cases and both are valid (the one where the item does not exist, the other where the command is invalid for an existing item).

> Should we suppress these commands from the syntax ?

I would say yes.

**Comment by maggu2810** [comment]
> I need the same message in German ;)

If we have the correct one in English, I will give you one :wink:

**Comment by lolodomo** [comment]
In English, it could be:

> The referenced object does not accept the <command> command.

**Comment by maggu2810** [comment]
For example:

```text
Das Kommando <command> wird von dem referenzierten Objekt nicht unterstützt.
```
