### ISSUE TITLE
say command and marytts:bits3hsmm not working when using webaudio

### ISSUE THREAD

**Issue by Marty56** [eclipse/smarthome#2534]
Having set language to de, the newly enhanced "say" command is producing a kind of mikimouse sound when using selection the german voices under Windows 10. 
It seems that the sampling rate is a factor 10 to fast.
e.g. 
say("dies ist ein Test","marytts:bits3hsmm","webaudio")
same is happending with marytts:bits1hsmm

using "marytts:cmuslthsmm" it is working but not usable due to the american language "accent"

**Comment by kaikreuzer** [comment]
This is a bug of MaryTTS (see https://community.openhab.org/t/sonos-audio-sink-say/15576/24?u=kai), which is maintained at https://github.com/openhab/openhab2-addons/tree/master/addons/voice/org.openhab.voice.marytts.
