### ISSUE TITLE
Support of "multiple" in service configurations

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2535]
I have a config description of a service that looks like this:

```
        <parameter name="items" type="text" required="false" multiple="true">
            <label>Items</label>
            <description>List of items</description>
            <context>item</context>
        </parameter>
```

I expected the Paper UI to allow me to choose any number of items for this parameter, but it only renders a single drop-down box. If I remove the "context", it also only renders a single text entry box.

**Comment by aounhaider1** [comment]
You are right, it is not working for context='item'. I'll fix that. However, it works fine if you remove the context field. The input field shown in this case is, in fact, a multiple field but we are unable to add any new options, as server is returning the limitToOptions=true in this case (I think it is default value?).

**Comment by kaikreuzer** [comment]
If no options are provided, "limitToOptions" does not have any meaning and should be ignored. Not sure if we can change that easily on the runtime side (as true is a sensible default when options are provided).

**Comment by kaikreuzer** [comment]
@aounhaider1 This doesn't seem to work correctly yet.
With the item context, I see:

<img width="205" alt="screen shot 2016-12-02 at 10 27 37" src="https://cloud.githubusercontent.com/assets/3244965/20828924/0be0161a-b87a-11e6-8784-4256c98bc19d.png">

But the "Search" text stays there, even if I have selected items from the list (while I see in expert mode that the value is correctly set). I would expect to somehow see the selected items there now.
If I manually add something in the text field, the drop down vanishes and I cannot select anything from there anymore.

Btw, when we have a item-context, should we automatically regard this as a limitToOptions=true, so that the user cannot enter anything himself there?

**Comment by kaikreuzer** [comment]
@aounhaider1 Another question: What format is the configuration sent for multiple values?

What I receive in my service is:
```
[[Lights, FF_Corridor, Heating, Windows, Light_GF_Toilet_Ceiling, Light_GF_Toilet_Mirror, ImageURL, Wifi_Level]]
```

Shouldn't it be a simple comma-separated list instead? Why are there double brackets around it?

**Comment by aounhaider1** [comment]
PaperUI is sending the values as an array and I think its event stored correctly on the server but while getting the configurations it converts the the array into a string, that is causing the double brackets.
About showing the selected values, I think a good approach would be to show a placeholder like "3 item(s) selected".
The dropdown vanishes as there are no matching elements in the options. Another possibility would be to show the complete options list when no matches are found in the options.
