### ISSUE TITLE
Basic UI behind SSL proxy uses REST URLs with plain http

### ISSUE THREAD

**Issue by hakan42** [eclipse/smarthome#2539]
Originally I opened this ticket as https://github.com/openhab/openhab-core/issues/84

Here I am again, using build 612 behind my nginx reverse proxy 😄 

Page https://my-server/basicui/app?sitemap=sunlight tries to load

http://my-server/rest/sitemaps/events/aaca358d-e467-4af6-91b1-9939fec1adf6?sitemap=sunlight&pageid=sunlight

(notice the plain "http"), which in turn leads to "mixed content" warnings on the browser, preventing the UI from showing content.

Even if I allow the browser to load that "insecure content", on the next step I am warned that no ACAO-Header is set, so I cannot load any data into the just displayed page:

EventSource cannot load http://my-server/rest/sitemaps/events/55f58811-c39a-4125-b979-bb7848aec7d2?sitemap=sunlight&pageid=sunlight. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://my-server' is therefore not allowed access. The response had HTTP status code 404.

**Comment by kaikreuzer** [comment]
@resetnow Could you check how the SSE connection is created?

**Comment by BClark09** [comment]
I believe this is a proxy error, not a smarthome one.

Have you set:

```
proxy_set_header X-Forwarded-Proto      $scheme;
```

**Comment by hakan42** [comment]
@BClark09  the problem was once again in front of the computer 😄

Setting X-Forwarded-Proto fixed my problem. Reading the documentation more concentratedly would have pointed me to this 😊
