### ISSUE TITLE
sendHttpPostRequest works different for OH2

### ISSUE THREAD

**Issue by michelde** [eclipse/smarthome#2540]
Last week I migrated from OH1 to OH2 and experienced that some of my rules where not working anymore. My rules is about to send a new value to my Volkszaehler for logging purposes. 
The rule which worked within OH1 was:
```
rule "AussenTemperatur_an_Volkszaehler" 
when Item AussenTemperatur changed
then
var String request = ''
request = 'http://vz.server.home/middleware.php/data/13c3cda0.json?value=' + AussenTemperatur.state.toString
logDebug("New value for AussenTemperatur {}",  request);
sendHttpPostRequest(request)
```

To get it working I needed to change the `sendHttpPostRequest(request)` to `sendHttpPostRequest(request, "application/json", "")`.

Within log I could see: 
`20:12:29.860 [INFO ] [marthome.event.ItemStateChangedEvent] - AussenTemperatur changed from 0.3 to 0.4`
`20:12:29.870 [ERROR] [lipse.smarthome.io.net.http.HttpUtil] - Fatal transport error: java.lang.NullPointerException`

Maybe someone can check why the post is not working as within OH1.

**Comment by J-N-K** [comment]
The NPE is caused by missing parenthesis in l. 210 in HttpUtil.java:

`if (method.equals(HttpMethod.POST) || method.equals(HttpMethod.PUT) && content != null) {
            request.content(new InputStreamContentProvider(content), contentType);
        }
`
Since && has higher precedence than || this is equal to 

`if (method.equals(HttpMethod.POST) || (method.equals(HttpMethod.PUT) && content != null)) {
            request.content(new InputStreamContentProvider(content), contentType);
        }`

while it should be

`if ((method.equals(HttpMethod.POST) || method.equals(HttpMethod.PUT)) && content != null) {
            request.content(new InputStreamContentProvider(content), contentType);
        }`

I can't say however if that is the behaviour of OH1.

**Comment by 9037568** [comment]
For the case in question, don't all of those expressions result in an
ultimate "true" value and execute the associated code block?

In which case, the NPE can't come from here?

**Comment by watou** [comment]
I think the issue is that HTTP POST isn't also verifying that content isn't null with && taking precedence.

**Comment by 9037568** [comment]
Right you are.  I need more coffee.

**Comment by watou** [comment]
See #2541

**Comment by J-N-K** [comment]
Oops. Seems I'm a little bit late on this one.

**Comment by watou** [comment]
Great minds think alike!  😄   I put the `content != null` at the beginning of the expression since it's the first thing to consider, otherwise either PR fixes.

**Comment by J-N-K** [comment]
Looking at it I was thinking whether for readability it would be better to enclose `content != null` in braces, too. Of course != is evaluated first and it works that way, I have seen something similar in another place, where `if (foo - 1 > bar) {`. I had to think twice if this is evaluated in the way it should be.

**Comment by watou** [comment]
In a case like `if (foo - 1 > bar) {` I can see how parentheses around `foo -1` improves the clarity and removes doubt as to operator precedence.  In the case of `content != null && <expr>` it seems clear enough.  I suppose it's a matter of personal preference...
