### ISSUE TITLE
Different rules using the same Time cron statement are not triggered

### ISSUE THREAD

**Issue by Marty56** [eclipse/smarthome#2543]
It seems that OH2 Timers are not working if the same timer is used in different rules.
Bug was found in build 615.

Example:
rule "Uhr incrementieren"
when
	 Time cron "0 0/1 * * * ?"
then
	logInfo("erstes Timerule","eins")
end

rule "Uhr incrementieren"
when
	 Time cron "0 0/1 * * * ?"
then
	logInfo("zweites Timerule","zwei")
end

in Log I am receiving

10:14:00.034 [INFO ] [marthome.model.script.erstes Timerule] - eins
10:14:00.079 [INFO ] [marthome.model.script.erstes Timerule] - eins

and a third rule, having this timer is not triggered at all.

Remove these two rules and not restarting OH2 does not recover the third rule.

**Comment by kaikreuzer** [comment]
You should note that the rule id must be unique - having two rules with exactly the same id is not valid and I guess this is what causes your issue.

**Comment by Marty56** [comment]
You are correct!
After I have been unique names, the triggers worked again.
