### ISSUE TITLE
Wrong chart URLs in Basic UI when using non-default persistence service

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#2544]
I have an outside temperature chart with several periods similar to that of the demo. The only difference is that it uses JDBC as persistence service. I.e. this is how the sitemap looks:

```
Frame {
	Switch item=Outside_Temp_Chart_Period label="Chart period" mappings=[0="Hour", 1="Day", 2="Week", 3="Month", 4="Year"]
	Chart item=Outside_Temp_Chart service="jdbc" period=h refresh=600 visibility=[Outside_Temp_Chart_Period==0]
	Chart item=Outside_Temp_Chart service="jdbc" period=D refresh=3600 visibility=[Outside_Temp_Chart_Period==1]
	Chart item=Outside_Temp_Chart service="jdbc" period=W refresh=3600 visibility=[Outside_Temp_Chart_Period==2]
	Chart item=Outside_Temp_Chart service="jdbc" period=M refresh=3600 visibility=[Outside_Temp_Chart_Period==3]
	Chart item=Outside_Temp_Chart service="jdbc" period=Y refresh=3600 visibility=[Outside_Temp_Chart_Period==4]
}
```

When I initially open the Basic UI page with these charts it shows the correct graph image. However when changing the chart period several times it starts to use the wrong URL to the chart image.

A correct chart URL is:
```
http://machine/chart?groups=Outside_Temp_Chart&period=W&random=1&service=jdbc
```

After several changes a wrong chart URL that is being used is for instance:
```
http://machine/chart?groups=Outside_Temp_Chart&period=h&random=1&service=jdbc9153323982135213
```

When you use a non-default persistence service `org.eclipse.smarthome.ui.basic.internal.render.ChartRenderer` appends that service at the end of the chart URL. The Basic UI however expects the `random` parameter to be at the end of the URL. `function ControlImage(parentNode, callSuper)` in `smarthome.js` always seems to remove the last digit and append a new random to the end of the URL.

**Comment by watou** [comment]
I fixed the same bug in the Classic UI [here](https://github.com/eclipse/smarthome/pull/1106/files).  I suspect the Basic UI copied that bug from Classic UI.

**Comment by wborn** [comment]
@watou the issue in your link indeed seems to be related. 

I can think of some reasons why unix time would be preferred over using a random:
* the `&random=1` in the initial URL may be cached causing the wrong initial graph to be shown
* using `&t=unixtime` in URLs theoretically makes it possible to share cached graphs between clients, however since unixtime is in millis it will not likely happen
* calculating unixtime is more CPU friendly

Are there more reasons to switch away from the random?

Besides that, the current Basic UI Javascript code causes a graph to be loaded with an invalid URL resulting in a 404 Not Found.

**Comment by watou** [comment]
Yes, the purpose of the `t` or `random` parameter is only to bust the cache, so a unique value is needed.
