### ISSUE TITLE
CompositeTriggerHandler wrongly "dispose" child handlers

### ISSUE THREAD

**Issue by vilchev** [eclipse/smarthome#2550]
Currently CompositeTriggerHandler does: 

```
    @Override
    public void dispose() {
        List<Trigger> children = moduleType.getChildren();
        for (Trigger child : children) {
            TriggerHandler handler = moduleHandlerMap.get(child);
            handler.setRuleEngineCallback(null);
        }
        setRuleEngineCallback(null);
        super.dispose();
    }
```
The idea behind 
`            handler.setRuleEngineCallback(null);`
by now is to stop child handlers from notifying (trigger) the composite handler.

Most of Handler implementations, however, wouldn't expect `ruleCallback=null` (they can even have isNull check and never bother to set the new null value). The right way to notify given handler to stop working/ notifying should be calling the `dispose()`.

Proposal is 
where             

`handler.setRuleEngineCallback(null); `

to be replaced with

`handler.dispose();`

This wouldn't mean that all handlers would dispose all used resources (including ruleCallback=null) as expected (Someone could just forget..). 
Thats why additional check in the CompositeTriggerHandler.triggered(where child handlers notify/trigger) should be performed whether CompositeTriggerHandler is not already disposed.

**Comment by danchom** [comment]
Agree. The RuleEngineCallback has to be set by the setRuleEngineCallback and removed by the handler's dispose method. 
We have to check implementation of current module handles if the remove the reference to the rulecallback.
