### ISSUE TITLE
parameter.pattern does not seem used for validation

### ISSUE THREAD

**Issue by clinique** [eclipse/smarthome#2556]
I wanted to introduce such control for the Netatmo binding without success. Tested also on the AmazonDashbutton that restrict by regular expression the "MAC address" configuration item while Paper UI allows the entry of non matching value.

**Comment by kaikreuzer** [comment]
I agree, we should consider this information.
Potentially not only in the UI, but also on the server side when accepting configurations.

@aounhaider1 How difficult would it be to add a check for regex expressions in the Paper UI?

**Comment by aounhaider1** [comment]
There is support for regular expressions in JS as well as a wrapper in Angular. So simple validation should not be hard to implement.

**Comment by aounhaider1** [comment]
Would it make sense to define regex as a filter criteria in the parameter config description (with name "regex" and regular expression as the value) ?
