### ISSUE TITLE
ThingHandlers stay UNINITIALIZED of registration runs into timeout

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2559]
The method `ThingManager.registerChildHandlers()` has the following code:

```
                        registerHandler(child);
                        initializeHandler(child);
```
Within `registerHandler` the handler registration is done in a "Safe" call, i.e. it might return after 5 seconds without having successfully registered the handler by that time.
As a result, `initializeHandler` will simply do nothing, since it checks whether the handler is correctly registered already.

The outcome is that the Thing stays in UNINITIALIZED state indefinitely.

[This seems to be like a report](https://community.openhab.org/t/binding-handler-registration-issues/17422) of exactly that situation.

**Comment by lolodomo** [comment]
I can confirm that I already noticed cases where certain things remain in UNINITIALIZED state.
It does not occur very often.

**Comment by sjka** [comment]
btw, we have this pattern 4 times within the ThingManager, i.e. everywhere where registerHandler(...) ist called. Therefore I think it would make sense to remove the SafeMethodCaller from the doRegisterHandler block and protect the above to lines instead together, so it is ensured the second line will always be executed after the handler was registered, even if it took too long.
