### ISSUE TITLE
Rollershutter with slider

### ISSUE THREAD

**Issue by aounhaider1** [eclipse/smarthome#2560]
As the rollershutter item accepts percent value (http://www.eclipse.org/smarthome/documentation/concepts/items.html). Would it make sense to also have a slider for it on control page?

**Comment by sjka** [comment]
maybe it's personal preference, but I don't miss the slider control. 
It's good to have the percent values though in rules.

**Comment by kaikreuzer** [comment]
I like the fact that the Paper UI offers UP/DOWN/STOP buttons for Rollershutter - my suggestion would be to additionally make the percent value editable, so that users can manually post a certain value. This would cover all cases for testing and also provides the most often used controls for users.

**Comment by bbolte** [comment]
I am currently developing a binding with a Rollershutter and like the Paper UI for quick testing of the functionality. The up/down/stop buttons are good, but I miss the possibility to see/set the current position of the Rollershutter in percent for testing the full functionality of the binding and the device. As a workaround, I am currently defining an additional Dimmer channel, which forwards the PercentType commands to the Rollershutter channel.

In my opinion, it makes sense to integrate a position widget for the Rollershutter to avoid such workarounds. I would personally prefer a visual feedback of the Rollershutter position over just a numerical value, e.g. a slider as a device independent representation and/or a window with blinds as a device dependent representation.

Some devices may not support getting/setting the Rollershutter position in percent. I can imagine that a position widget could be confusing for users in this case. Maybe the visibility/appearance of the position widget could be configurable via the channel-type definition. (Options could be to use the category, tags, and/or state settings.)
