### ISSUE TITLE
CRON rule triggered multiple times if in same file as an invalid/unresolved rule

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2580]
See discussion at https://github.com/eclipse/smarthome/issues/2545:

There are situations where the same rule is scheduled multiple times. It appears to happen if rule files are refreshed and contain rules that weren't correctly parsed before (due to syntax errors or potentially unresolved item or action names).

**Comment by kaikreuzer** [comment]
I would think that this should be fixed by the fact that we now do not load rules with parsing errors anymore.

@JueBag If you still experience this issue, please feel free to re-open.

**Comment by JueBag** [comment]
I tried using my old rule as posted in [#2545](https://github.com/eclipse/smarthome/issues/2545).
Using the OH2.1 stable release, I get log messages that exactly point to the false usage of an escape character. 
```
20:02:31.210 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration mode 'check.rules' is either empty or cannot be parsed correctly!
20:02:31.555 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration mode 'check.rules' has errors, therefore ignoring it: [17,104]: Invalid escape sequence (valid ones are  \b  \t  \n  \f  \r  \"  \'  \\ )
[17,127]: Invalid escape sequence (valid ones are  \b  \t  \n  \f  \r  \"  \'  \\ )
```
In other words, CLOSED!

**Comment by kaikreuzer** [comment]
Perfect, thanks for the feedback!
