### ISSUE TITLE
Missing syntax validation in persistence definition files

### ISSUE THREAD

**Issue by hakan42** [eclipse/smarthome#2581]
Using many builds up to and including 624, trying to get influxdb persistence working, I had this influxdb.persist file, notice the 

```
Items {
	forInflux* : everyChange
}
```

after a very long debugging and reconfiguration session, I noticed that I was missing the "strategy" keyword:

```
Items {
	forInflux* : strategy = everyChange
}
```

Surprisingly, the first file was loaded and parsed by the ESH core, but of course no persisting happened. Only after adding the proper "strategy = " persistence started working.

If that keyword is so important, I would have expected an error message that it is missing. Either that, or if the keyword is optional, then persistence should work without. But silently failing is the worst of all options 😄

**Comment by triller-telekom** [comment]
I do not know exactly when this has been fixed but if I put this into a `*.persist` file:
```
Items {
	forInflux* : everyChange
}
```
I get this error on startup and the configuration is not added to the model repository and thus not used.

```
16:18:02.941 WARN  o.e.s.m.c.i.ModelRepositoryImpl[:92] - Configuration model 'logging.persist' has errors, therefore ignoring it: [17,15]: no viable alternative at input 'everyChange'
```

@kaikreuzer @sjka This issue can be closed.
