### ISSUE TITLE
Rule action interpret triggering a TTS in case of interpretation error

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2588]
Currently, the interpret action in rule is triggering a command saying the error when the interpreation produces an error. It is working, it is really fun and cool but I think it should be optional.
Additionaly, the text is played by the default audio sink and you have no choice of audio sink.
What do you think about the idea to add a parameter to the interpret action that would be the audio sink to use in case of error. If no audio sink is provided, this will fail silently.

**Comment by kaikreuzer** [comment]
Sounds good. How would you suggest to express that the response should be played on the default audio sink (as it is today)?

**Comment by lolodomo** [comment]
The 2 current "interpret" actions will use TTS with the default audio sink. Unchanged.
I will add a third interpret action with a new parameter that will be the audio sink to use. If this parameter is null, TTS will not be used. If not null, it will be the audio sink to use with TTS.
To disable TTS or to choose another audio sink than the default one, the user will use the new "interpret" action with 3 parameters: text, HLI and audio sink.
Is it ok ?

**Comment by kaikreuzer** [comment]
Sounds good!

**Comment by lolodomo** [comment]
Enhancement merged.
