### ISSUE TITLE
Improve normalization of modules'configuration properties.

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#2602]
At the moment the normalization of configuration properties are base on the configuration values instead of meta info, defined in ConfigDescriptionParameter, for this value.  This is a problem when the configuration property is defined as multiple or when it has a default value and its type is not string one (default value is always defined as String).
The proposal is to do normalization base on the ConfigDescriptionParameter when the rule is added or updated  through the RuleRegistry

**Comment by kaikreuzer** [comment]
I see in the RuleEngine code:

```
                        moduleConfiguration.put(configName, ConfigUtil.normalizeType(configValue, configDescription));
```
so it seems to already respect the ConfigDescription. Can you point to the place in the code that you want to address?

**Comment by danchom** [comment]
Yes you are right, it is done for rule modules' configuration data. Sorry, I've forgot about this .  But there isn't normalization when we add rule by template (normalization of rule's configuration). In the RuleEngine's getRuleByTemplate() method we call validateConfiguration(r1) which can failed because the parsed json data (part of the configuration object) can be different value from expected once declared in ConfigDescriptionParameter.
