### ISSUE TITLE
How to Setup Channels for Bridge?

### ISSUE THREAD

**Issue by lsafelix75** [eclipse/smarthome#2605]
Is it possible to define a channel for a bridge?  i am getting the following error in runtime 
_!ENTRY org.eclipse.equinox.cm 4 0 2016-12-06 22:56:04.763
!MESSAGE Given uid must not be null.
!STACK 0
java.lang.IllegalArgumentException: Given uid must not be null._

### 

Bridge myswitch:broker:mygateway1 [ gateway="my switch", pollingInterval=50 ] {
      Switch: status [ subtopic="status"]

    Thing topic f_masterbath_sww0 [pollingInterval=20 ] {
      Switch: status [ subtopic="status"]
    }
 }

**Comment by htreu** [comment]
The order of channels and bridges is important here: when defining the Thing first and the channels last it should work. See your example reformatted here:
```
Bridge myswitch:broker:mygateway1 [gateway="my switch", pollingInterval=50] {
	
	Thing topic f_masterbath_sww0 [pollingInterval=20] {
  		Switch: status [subtopic="status"]
	}
	
	Switch: status [subtopic="status"]
}
```
Does that fix your issue? We can close this issue then.

**Comment by lolodomo** [comment]
@kaikreuzer : issue to close ?
