### ISSUE TITLE
Support firmware updates in paper ui

### ISSUE THREAD

**Issue by tomhoefer** [eclipse/smarthome#2606]
This is a proposal how to integrate the firmware update feature into the paper UI. For this purpose we have to provide some more REST endpoints first of all:

- Get firmware status for a thing (provides the firmware status info domain object)
GET /things/{thing-uid}/firmware/status

- Update firmware for a thing
POST /things/{thing-uid}/firmware/update/{firmware-version}

- Get all firmwares for the thing´s thing type (provides the collection of firmware domain objects)
GET /thing-types/{thing-type-uid}/firmwares

The paper ui should subscribe to the following topics in order to get informed about firmware status or firmware update progress changes:
- smarthome/things/{thingUID}/firmware/status (for firmware status change)
- smarthome/things/{thingUID}/firmware/update/progress (for firmware update progress change)
- smarthome/things/{thingUID}/firmware/update/result (for result information of firmware update)

The complete firmware update concept bases on the firmware version property (available by the thing´s properties). So if a thing does not provide this property then we should not show any firmware update feature on the paper ui. Currently this property is shown on the thing´s detail page (Configuration -> Things -> select thing -> SHOW PROPERTIES). 

<img width="644" alt="bildschirmfoto 2016-12-06 um 15 48 44" src="https://cloud.githubusercontent.com/assets/5469298/20930696/bb580650-bbce-11e6-9042-b38c8af3cc96.png">

So I propose to remove the firmware version property from the original propertiest list and to introduce a separate firmware form.

![firmware-update-paper-ui2](https://cloud.githubusercontent.com/assets/5469298/20930804/22480ac2-bbcf-11e6-820b-45c5acf8ad29.png)

If the user clicks on "Show firmwares" then a table with all available firmwares is to be shown (containing firmware version, description, vendor, change log). The last column of the table should provide a button in order to install the selected firmware on the device. Based on the firmware update progress and/or result events the paper ui can show some progress information to the user.

**Comment by kaikreuzer** [comment]
> If the user clicks on "Show firmwares"

Shouldn't the button only be shown, if firmwares are available? Shouldn't it better be called "Show available firmwares"?

> then a table with all available firmwares is to be shown 

As a modal dialog, an expanded section on the current page or as a new page?

> The last column of the table should provide a button in order to install the selected firmware on the device

I guess there are devices that are not downgradable. Is this already respected in the list of available firmwares, so that older versions do not turn up at all?
Should the dialog close after the user pressed the button? What is he presented next?

> can show some progress information to the user.

Where and how should that happen? What should be displayed (progress bar? Text? Detailed messages?)

Some additional questions:
- I would think that there should be some label on the Things list that shows that notifies the user that an update is available.
- How is the Thing status OFFLINE.FIRMWARE_UPDATING related to the firmware upgrade process? If the Thing is in that status, would it make sense to show the firmware progress instead of the Thing status in the Thing list?

**Comment by tomhoefer** [comment]
> Shouldn't the button only be shown, if firmwares are available? Shouldn't it better be called "Show available firmwares"?

Sure, this is also possible. My original intention was to avoid the additional call. 

> As a modal dialog, an expanded section on the current page or as a new page?

I would prefer the same look and feel as it is implemented for the current properties view. So for the moment we should simply expand the current page. 

> I guess there are devices that are not downgradable. Is this already respected in the list of available firmwares, so that older versions do not turn up at all?

No. 

> Should the dialog close after the user pressed the button? What is he presented next?

Once the button has been pressed then we could show a kind of a modal dialog ("Firmware update started...") and close the expanded firmwares section. The paper ui should consume the progress info and result events in order to indicate the progress / result of the fw update. If the progress provides a percentage progress then it makes sense to show a progress bar (below of the fw status ? ). If not then only a label for the current progress step should be shown.

> I would think that there should be some label on the Things list that shows that notifies the user that an update is available.

Makes sense.

> How is the Thing status OFFLINE.FIRMWARE_UPDATING related to the firmware upgrade process? If the Thing is in that status, would it make sense to show the firmware progress instead of the Thing status in the Thing list?

The thing´s firmware update handler has to set this state immediately if its ```updateFirmware``` operation is invoked. I am not sure if we should mix the view of the thing status and the firmware status. We can discuss
