### ISSUE TITLE
MqttBrokerConnection Exception .. how to catch?

### ISSUE THREAD

**Issue by lsafelix75** [eclipse/smarthome#2607]
Hi,

I am using ESH's Eclipse SmartHome MQTT Transport Bundle as part of my openhab2 custom binding. In order to capture the MQTT connection state, i have implemented a class to 'implement" MQTTConnectionObserver() class. From there, i could intercept connection status via "setConnected(). However, whenever there is an exception like lost MQTT connection or like following, how do i catch them? I don't see much example on this MQTT bundle though. Thanks

_2016-12-07 00:58:34.860 [ERROR] [t.mqtt.internal.MqttBrokerConnection] - MQTT connection to 'local' was lost: MqttException : ReasonCode 0 : Cause : Could not update status, because callback is missing
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:176)[187:org.eclipse.paho.client.mqttv3:1.0.2]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
Caused by: java.lang.IllegalStateException: Could not update s_

**Comment by kaikreuzer** [comment]
An IllegalStateException sounds like nothing that you should catch and continue. I do not know this code, I think you will have to analyse yourself what is going wrong there.

In general, please use the forum at https://www.eclipse.org/forums/index.php/f/271/ for questions, not the issue tracker here. Thanks!
