### ISSUE TITLE
[Sonos] Test Firmware 7.0

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#2609]
Noticed today that Sonos has released firmware 7.0. At first sight, this release seems to support speakers directly from the Spotify app, which makes me believe that the protocol for controlling players could have been altered, extended, or generalised (DLNA?). 

Someone with a bit of ample time should take the leap forward and test the binding against this firmware.

**Comment by lolodomo** [comment]
Main features tested and no problem detected for me.
I had just to restart openHAB to have correct translating of commands to the group coordinator.

**Comment by kgoderis** [comment]
@lolodomo Did you encounter any further problems (see your other remark)?

**Comment by lolodomo** [comment]
No but I have not done additional tests.

**Comment by Marty56** [comment]
My uses case seem to work but I am only using a fraction of the available options

**Comment by lolodomo** [comment]
This issue can probably be closed.
