### ISSUE TITLE
Rule actions say and interpet: inconsistent parameter type

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2610]
We have 3 versions of the say rule action. They all provide as first parameter the text to be said.
One expects an Object class while the 2 others expects a String class.
This makes thing confusing for any user.
I would suggest to have a String parameter in all cases.
Same thing for interpret.

**Comment by kaikreuzer** [comment]
The reason why Object is used as a parameter is to allow StringType instances as a parameter, e.g. "receivedCommand" or "MyItem.state". Imho it makes a lot of sense, because having to always add `toString()` is annoying.

**Comment by lolodomo** [comment]
In this case, we should use Object in all cases. Is it ok for you ?

**Comment by kaikreuzer** [comment]
I would think so - not sure if I overlook anything, though.

**Comment by lolodomo** [comment]
I will update my PR #2593 to include this fix.
