### ISSUE TITLE
Add runNow(ruleUID) method in ruleRegistry.

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#2613]
The runNow(UID) method has to execute actions without evaluating rule's conditions. The executed actions must not have inputs or the input must have default values. 
If the input is connected the runNow method has to use input's  default value. 
The method has to execute as much as possible actions of the rule. (It will not stop on the first fail of action execution)

**Comment by kaikreuzer** [comment]
I'd think this is a duplicate of https://github.com/eclipse/smarthome/issues/689, right?

**Comment by danchom** [comment]
Yes it is the same issue. I'll close it.
