### ISSUE TITLE
[PaperUI] Issue more user-friendly error message when trying to modify automatically created item

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2638]
I have created some items automatically by activating simple mode and selecting some channels. Then I switched of simple mode and tried to modify the category of an automatically created item.
Paper UI's reaction was error message "405 method not allowed". In addition the log shows this warning:
```
20:24:43.692 [WARN ] [thome.io.rest.core.item.ItemResource] - Cannot update existing item 'yahooweather_weather_f5169938_temperature', because is not managed.
```
If it is not allowed to modify automatically created items then it would be better (and more user-friendly) if the information were only displayed as read-only values without the possibility to change any values.

**Comment by kaikreuzer** [comment]
Right, but the problem is that the UI can only find out if it is modifiable when doing so. There isn't any information like "read-only" available. Adding such an information would require a rather tricky refactoring.

**Comment by MHerbst** [comment]
I understand. But it would help if a more meaningful error message could be shown. "method not allowed" is very general.

**Comment by kaikreuzer** [comment]
I agree, that should be easy to be caught and changed by the Paper UI here.
@aounhaider1 Could you do this?
