### ISSUE TITLE
Adding an Item in PaperUI fails with no error if Name field contains a space. 

### ISSUE THREAD

**Issue by individualist** [eclipse/smarthome#2640]
To Reproduce: 
Under Configuration->Items click (+) to add an item. 
Fill in all required fields, but in the "Name" field supply a name containing a space, such as "Office Lights" 
Click (+) to add the item.   

Results: You are returned to the Items list without an error and without the item being added.   

Expected results:  
If spaces are not allowed in item names,  a message to that effect should be given, and/or the user not allowed to continue.

**Comment by kaikreuzer** [comment]
@aounhaider1 Is the item name validation broken?
