### ISSUE TITLE
Extensions should be able to optionally provide a link to online documentation

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2653]
Extensions currently only have a label that do not necessarily provide much information to the user.
Instead of adding icons, descriptions etc. (which might be useful in future as well), I would like to see the possibility to optionally provide a link to online documentation.

The Paper UI should then open a browser tab with that link, if the user clicks the extension text (which currently does nothing).

**Comment by MHerbst** [comment]
I already had a similar idea but you were faster with the issue :-). I thought about adding an additional  image with a question mark. On clicking the icon it would then show the help text.

I think it should be possible to create the documentation for each binding e.g. from the existing README.md files. 
Maybe it is possible to render the markdown files to HTML files during the maven build and either store them in the binding bundle (and make them available via REST) or loadable as HTML from the installation directory.
As an alternative there are Javascript files that can render markdown files online.

**Comment by kaikreuzer** [comment]
@MHerbst:
- "Adding them to the OSGi bundle": We were also thinking about this option in the beginning, but we discarded it for the following reasons:
Adding them to the OSGi bundle could potentially heavily increase the size and as we target small systems, this might not be a good thing to do. We therefore do NOT include the README.md and the doc folder in the build.properties of a bundle.

- "loadable as HTML from the installation directory": Well, "loadable as HTML" is what I suggest here. And the location of the URL MUST be up to the solution, because you might want to do some formatting so that it fits to your solutions' layout, etc. openHAB e.g. won't include the "pure ESH" version, but rather point to the one rendered at docs.openhab.org. A solution would also be able to provide urls to localhost and e.g. package the documentation pages so that they are served from the HTTP server locally. But this is completely up to the solution and does not need to be discussed at ESH.
