### ISSUE TITLE
Sonos binding: power off / power on

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2667]
I am testing the correct handling of the binding when powering off and powering on a Sonos device.

@kgoderis : I would like to understand what is the reason to call onUpdate() in thingDiscovered ? It is already called when the thing is initialized; this call will in fact do nothing as the job is already started.
https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java#L221
Was the idea to accelerate the process and to not wait for the next job cycle ?

I will propose a little update to be sure that when a thing changes from status OFFLINE to status ONLINE new GENA subscriptions will be requested.
What I noticed is that onServiceSubscribed is called with "failed" only after arround 5 minutes for all subscriptions when the Sonos device is OFF.

When powering off a Sonos, I was expected that thingRemoved to be called but it does never happen. isUpnpDeviceRegistered() still returns true. Normal ? Then when powering on the Sonos, thingRemoved is called and then thingDiscovered. So I am not sure we can rely on these methods thingDiscovered and thingRemoved. By the way, they are only doing something if you are using the default thing UID (not my case).

Finally, I discovered that after powering off a Sonos, if you request a new discovery, your Sonos is till discovered (due to cached data by jupnp ?) but there is an error detected by getSonosRoomName because it tries to read in the description file (which is not more accessible).
So discovery is not working very well in this case.

**Comment by kgoderis** [comment]
@lolodomo First of all it has been a *long* time ago that I have written the Sonos code at the time, so my answers might not be 100% ok here.

> Was the idea to accelerate the process and to not wait for the next job cycle ?

Yes, but if it can be done in a better way, then we should do that

> When powering off a Sonos, I was expected that thingRemoved to be called but it does never happen. isUpnpDeviceRegistered() still returns true. Normal ?

As far as a I remember there is a time-out mechanism at the UPNP level with very long time-outs. I *think* this is the reason we have these side-effects, and why devices are reported registered,... even when they are off-line in reality. We should complement the UPNP mechanism with our own mechanism. That was the reason why we have this separate polling job in the handler to check whether a device is online or not. If we can improve this, or leverage error code from other places (e.g. getSonosRoomName) then maybe we should do that.

**Comment by lolodomo** [comment]
I discovered that we can call addStatusListener (from the transport UPnP bundle) to create a scheduled job that will run a certain UPnP action and trigger onStatusChanged when the UPnP device becomes accessible or inaccessible. It could have been used in the Sonos binding. The Sonos binding rather implements its own scheduled job, the reason is probably that this job is doing more things (few UPnP action calls to retrieve updated data - like the LED status for example).

Yes, there is a little fix to be done to not discover a Sonos when getSonosRoomName() fails (returns null).

I may suggest to forget thingDiscovered and thingRemoved and rely only on our scheduled job. I know (tested) that it is working (even if a little fix is required to force new GENA subscriptions when the Sonos will be ON again). The only disadvantage is that it can take until one minute to make the thing ONLINE.  I think it is acceptable.

I will propose an update enhancing/fixing that.

**Comment by lolodomo** [comment]
Closed by merged PR #2686.
