### ISSUE TITLE
Multiple time cron expressions in rule not working

### ISSUE THREAD

**Issue by dschulte** [eclipse/smarthome#2668]
As requested ( https://github.com/openhab/openhab-distro/issues/355 ) I'm opening a new issue.

Works (fires every five seconds):
```
rule "cron test"
when
	// Time cron "0 0 0 * * ?" or
	Time cron "0/5 * * * * ?"
then
	logInfo("cron", "test")
end
```

Doesn't work as expected (second cron doesn't fire):
```
rule "cron test"
when
	Time cron "0 0 0 * * ?" or
	Time cron "0/5 * * * * ?"
then
	logInfo("cron", "test")
end
```

I'm using the current apt version of openhab:
```
openhab2-offline/testing,now 2.0.0~b4 all  [installiert]
  openHAB Offline Distribution
```

**Comment by pawlik13** [comment]
Just to update - this issue still persists for the OH2 snapshot version (seen with 20170114).

Regards, Paweł

**Comment by jn-se** [comment]
I can confirm the issue. For each rule only the first Time cron is used.
Any other ORs (like Item received update) are working well.

**Comment by MrMontesa** [comment]
Came accross this issue today as well. Quite a bit annoying to have as many rules as cron entries needed.

My use-case:

```
rule "Lights off depending on day of week"
when
    Time cron "00 15 22 ? * MON-THU,SUN" or
     Time cron "00 30 23 ? * FRI-SAT"
then
.... 
```

**Comment by jayekub** [comment]
+1

**Comment by FrankR59** [comment]
+1
