### ISSUE TITLE
Sonos binding: no value set immediately when linking an item to a channel

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2669]
The Sonos binding is not yet handling REFRESH command.
When the user links an item to a channel, the item value is not set until there is an event from the Sonos device providing a new value.

**Comment by lolodomo** [comment]
I think I know how to fix that and that is not very difficult. I will propose a fix.

**Comment by maggu2810** [comment]
👍

**Comment by lolodomo** [comment]
Closed by merged PR #2686.
