### ISSUE TITLE
Contact item displayed wrong in Paper UI depending on the label

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2672]
I have created two items (with the Homematic add-on) of the same type. For both things I have created an item (type: Contact, category: Contact). Although both items are configured identically they appear different on the "Control" page in Paper UI:
![image](https://cloud.githubusercontent.com/assets/616792/21296819/93945e2a-c574-11e6-9f54-32c50558a5f1.png)
Also the state of the righ contact does not change. 
To create the items I select a channel in the thing definition and option "Create new Item". For the left item id did not change anything in the item and for the right one I changed name and label.  I assume the differed display is cause because of this editing.

In Basic UI both look the same.

Also after a restart of openHAB the display was correct.

**Comment by kaikreuzer** [comment]
This is very likely a duplicate of or at least related to https://github.com/eclipse/smarthome/issues/1550

**Comment by MHerbst** [comment]
Unable to reproduce this this problem with release version OH 2.
