### ISSUE TITLE
Paper UI: Message "ERROR 404 - Not found" when trying to delete an item

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2673]
Tested with Build 650.

I have selecte a thing's channed and created and linked a new item. Then I tried to delete this item. But I got message "ERROR 404". Then I unlinked the item from the channel and tried again to delete the item in Paper UI. But the same message appeared. There was no message on the console.

In another attempt I tried to delete the item directly via the REST API:
````
curl -X DELETE --header "Accept: application/json" "http://localhost:8080/rest/items/Fenster_Arbeitszimmer"
``
This worked if the item is not linked to a channel. 

BTW: if the deletion is not possible because an item is still linked to a channed I would expect a message telling me that I have to unlink it first.

When I try to remove a linked item via the REST API (before unlinking it), I get the following message on the console (the REST API returns a response code 200):
```
23:20:15.766 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'TKWohnL_1_State' has been added.
23:20:15.766 [INFO ] [marthome.event.ItemStateChangedEvent] - TKWohnL_1_State changed from NULL to CLOSED
23:20:15.767 [INFO ] [smarthome.event.ItemRemovedEvent    ] - Item 'TKWohnL_1_State' has been removed.
```
It's quite interesting that the item was added (again) before it was removed :-).
When I then unlink this item from the channel it is automatically removed.

**Comment by kaikreuzer** [comment]
> It's quite interesting that the item was added (again) before it was removed :-).

It is actually a different item that gets added, it only has the same name. This is actually a feature - for any existing link that points to an item that does not exist, a "virtual" item is automatically created; so indeed, you will first have to remove the link and then the item.

**Comment by MHerbst** [comment]
OK. So it is clear that the virtual item was automatically removed when I unlinked it.
