### ISSUE TITLE
Paper UI: Search box for Things and Items view

### ISSUE THREAD

**Issue by kubawolanin** [eclipse/smarthome#2680]
Add-ons/Extensions views currently have a great feature that allows you to search through all visible items and filter out only those matching your search phrase.
It would be a great addition to the usability if similar feature was implemented in Things and Items menu.

![search-things](https://cloud.githubusercontent.com/assets/2270505/21323050/2ab39332-c61c-11e6-994a-87d6942033d7.PNG)

**Comment by kaikreuzer** [comment]
Yes, definitely needed when you buy more and more Things ;-)
I also already asked @aounhaider1 to add this to the Things menu (and Items as well in the context of https://github.com/eclipse/smarthome/issues/2614).
