### ISSUE TITLE
IP Cam: Stream will be not closed

### ISSUE THREAD

**Issue by maikt** [eclipse/smarthome#2692]
Hi,

this is my first issue and my english is not so good, please sorry for this.

I have a problem with my axis ip camera and the BasicUI. The camera video stream call is inserted into the sitemap with the following lines:
```
Text label="Axis IP Cam" icon=„video" 
{
	Video url="http://<user>:<password>@192.168.2.33/mjpg/video.mjpg" encoding=„mjpeg“
}

```
After starting openHAB 2 it is possible to view the video stream in the BasicUI. But after a few minutes or when I open the site several times, the stream can no longer be played.
So I searched the problem in the IP camera configuration and i have found it: The camera supports a maximum of 10 streaming connections and they are all occupied by my openHAB host (raspberry pi).
To release all connections, it is necessary to logout and restart openHAB 2.

I use the actual openHAB 2 snapshot from today.

Do I something wrong or is this a software bug?

Thanks for you help.
Maik

**Comment by watou** [comment]
Based on another recent report, I think the ProxyServlet is not properly cleaning up HTTP connections.  I will have a look.

**Comment by kaikreuzer** [comment]
FTR, there is also a report about an OOM exception wrt video, see https://github.com/openhab/openhab-core/issues/56. Might be related as well.
