### ISSUE TITLE
Problem with rules at startup

### ISSUE THREAD

**Issue by Nawygator** [eclipse/smarthome#2694]
Hey there,
at startup of OpenHab2 there is an issue about rules, that are created by the Rule engine of PaperUI.

```
20:29:43.547 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_2 updated: NOT_INITIALIZED
20:29:43.568 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_2 updated: NOT_INITIALIZED (CONFIGURATION_ERROR): Validation of rule rule_2 has failed! Condition Type "ItemStateCondition" does not exist!
20:29:43.572 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_1 updated: NOT_INITIALIZED
20:29:43.575 [INFO ] [smarthome.event.RuleStatusInfoEvent ] - rule_1 updated: NOT_INITIALIZED (CONFIGURATION_ERROR): Validation of rule rule_1 has failed! Condition Type "ItemStateCondition" does not exist!
[...]
```
If you disable every rule and then enable them again manually they work fine. 
As i saw in the [OH Community](https://community.openhab.org/t/new-rule-engine-startup-rule-initialisation/18622/3), im not the only one with this problem.

Greetings

PS:
Just for Information my current System:
RPi 3 with Raspbian Jessy
openHAB 2 Snapshot 663
Java 8u111

**Comment by kaikreuzer** [comment]
@danchom The openHAB distro contains the very latest ESH code. I have seen the same effect, the module handlers actually aren't available on a first start.
I think it could be caused by https://github.com/eclipse/smarthome/issues/2413, because I have seen similar exceptions about cyclic service dependencies in my log.

**Comment by danchom** [comment]
I'll check the problem.

**Comment by danchom** [comment]
I think the PR #2696 will fix the problem.

**Comment by dikkedimi** [comment]
Hi Kaikreuzer, this is my exact issue with the current openhab snapshot release!
