### ISSUE TITLE
JsonStorage uses com.google.gson.internal.* packages

### ISSUE THREAD

**Issue by watou** [eclipse/smarthome#2697]
But they were removed from the OSGi bundle exports [here](https://github.com/google/gson/commit/2016e9553eb946a09a9e70d83d31f4e8da675805) (and not restored [here](https://github.com/google/gson/pull/797#issuecomment-188270672)), so  code [here](https://github.com/eclipse/smarthome/blob/master/bundles/storage/org.eclipse.smarthome.storage.json/src/main/java/org/eclipse/smarthome/storage/json/PropertiesTypeAdapter.java#L20), [here](https://github.com/eclipse/smarthome/blob/master/bundles/storage/org.eclipse.smarthome.storage.json/src/main/java/org/eclipse/smarthome/storage/json/JsonStorage.java#L32) and [here](https://github.com/eclipse/smarthome/blob/master/bundles/storage/org.eclipse.smarthome.storage.json/META-INF/MANIFEST.MF#L9) will have to change to remove those dependencies before Gson is upgraded to >= 2.6.0 (or else use a private copy of the Gson library).

**Comment by triller-telekom** [comment]
@sjka @kaikreuzer This issue was fixed by the referenced PR, please close it.
