### ISSUE TITLE
Config parameters normalisation not working for thing parameters

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#2698]
I'm seeing some parameters being stored in the jsondb as a STRING when they are defined as INTEGER.

My guess is that this is happening in the normalisation code. The parameters in question are in the thing config descriptions - not the thing-type.

This is more obvious when using HABmin since HABmin only sends updates to parameters that have changed - if I don't change these parameters, then nothing is sent in the REST interface, but these parameters are being changed to STRING. PaperUI is sending the parameter as a number, and it's getting stored as 12.0 in json which is still wrong, but it does at least work in this instance.

I assume that whatever code does the normalisation is using the config descriptor for the thing-type, and not the thing itself. Possibly [here](https://github.com/eclipse/smarthome/blob/48e405fb3f1e60b56333e26bd42021bd5cfc1bc8/bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java#L671).

Having updated the zwave binding to allow [textual thing definitions](https://github.com/openhab/org.openhab.binding.zwave/issues/153), the binding no longer functions if parameters are updated with the UI.

**Comment by cdjackson** [comment]
I confirmed that as the system is only looking for the thing-type config descriptor, it doesn't get the full list of config descriptions and then doesn't normalise all parameters.

**Comment by sjka** [comment]
Good point - I simply missed the fact that there are Thing specific configuration descriptions as well when implementing it.

How about #2759?
