### ISSUE TITLE
Basic UI - Google Chrome - Colorpicker Handle wrong Position

### ISSUE THREAD

**Issue by streppelchen** [eclipse/smarthome#2701]
I added a Colorpicker item to my sitemap and tried changing the Handle to another position in Google Chrome. The Handle has an offset and i can't move it to the right-hand side of the Colorpicker.

This issue happens only in Google Chrome, i've also tested a current Safari and Firefox 50.1.0 which both work as intended.

I'm using Google Chrome Version 55.0.2883.95 (64-bit) on a Mac.
openHAB 2 beta 5 - Version 4.0.8 according to the Console output.

**Comment by kaikreuzer** [comment]
@resetnow Could you check this?

**Comment by resetnow** [comment]
I can't reproduce this on Linux with Chrome 55.0.2883.87. Can this be a MacOS-specific Chrome bug? Could you please try with Chrome Canary?

**Comment by wastlchuck** [comment]
I'm having the same issue in Chrome and Windows 10. 
With Chrome 56.0.2924.87 I can only move the handle at the outer edge of the colorpicker between 9 and 11 o'clock position.
With Chrome Canary I can move the handle between 9 and 12 o'clock position. And with some offset, the handle can be moved almost up to the middle of the colorpicker.
With Firefox everything is working fine.

**Comment by resetnow** [comment]
If possible, could you please share a screen recording? I heard windows 10 had this feature built-in

**Comment by resetnow** [comment]
Oh I see, thank you. I think it may be some weird floating point issue related to colorspace conversion. I'll look into it.
