### ISSUE TITLE
Paper UI Enhancement: add filter and/or grouping options to pages Things and Inbox

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2702]
The new search and filter options are really a great usability improvement. 
But in the case that the Inbox contains lots of things resp. the list of things is quite large I could imagine the following enhancements:

- Inbox:
  - alphabetic order of discovered things
  - search function
  - filter/group by binding type
- Things:
  - filter/group by binding type
- All pages with lists
  - on optional "compact view" with smaller images and maybe less text.

**Comment by kaikreuzer** [comment]
Sounds all like useful enhancements to me.
@aounhaider1 It probably makes sense to split it up in several PRs. Feel free to decide, what might be a quick win (like sorting inbox entries) and which might be a bigger refactoring (e.g. introducing filtering on other lists than items).

**Comment by kaikreuzer** [comment]
@aounhaider1 I noticed that the filters on Inbox and Things only check labels, but not ids, while on items and extensions, also ids are taken into account. I would vote for checking ids in Inbox and Things as well, wdyt?

**Comment by aounhaider1** [comment]
Yes, makes sense. I'll add that.
