### ISSUE TITLE
Paper UI Enhancment: Add an About / Info page

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2705]
I think especially for new users it is not so easy to find out the current version of Smarthome / openHAB ... and the correct places where he can ask for help.

Also the support very often needs information like the tool's version number, Java version, Operation System, browser.

Therefore I think it would be good to have one page with all relevant information:

- version of Smarthome and/or version of the software that is running on top of (like openHAB)
- links to issue tracker(s) resp. discussion forum
- links to online help
- information about the system the server is running on (e.g. Operating System incl. version, Java version)
- information about the client (e.g. browser version, operating system version)
- the usual copyright stuff :-)

**Comment by kaikreuzer** [comment]
Why would you think that the Paper UI is the right place for this? After all, it is one (optional) UI out of many.

For openHAB users, wouldn't the dashboard itself be the better place? This already contains the link to the online documentation, which in turn refers to the support forum, issue trackers, etc.

**Comment by MHerbst** [comment]
Your are absolutely right. The last days I have worked quite a lot with the Paper UI so only thought of it. 

The most important thing of this enhancement is that we need some additions to the REST API that make the information available. 

I agree, for openHAB users the dashboard is definitely the better place.

**Comment by kaikreuzer** [comment]
The REST API already exposes its version. For all the rest, I assume that the content is very solution specific and you might not even want to expose it on the REST API (note that the dashboard is a servlet, which can easily include information without requiring it being available through REST).

I'd therefore suggest to close this issue and rather open one for the openHAB Dashboard at https://github.com/openhab/openhab-core/issues.

**Comment by MHerbst** [comment]
OK
