### ISSUE TITLE
Basic UI: automatic update of newly added items requires restart

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2706]
Tested with build 675 on Raspberry and a Chrome Browser.

After adding new items (a frame with3 items) to a sitemap the newly added items are note updated automatically. Only a browser refresh updates these item. Older items contained in another frame were automatically updated.
After a restart all items were properly updated. It seems that a restart is necessary to enable the automatic update of newly added items.

In Classic UI the automatic updated works without restart. So it seems to be related to the Basic UI implementation.

**Comment by LordPacDemon** [comment]
All information under Basic UI not updating until manual reload of page under Firefox (54.0.1) / Chrome (60.0.3112.78). Under MS Edge and Internet Explorer it working.

**Comment by glyndon** [comment]
Seeing this exact behaviour today. BasicUI stops reflecting updates if config changed, until OpenHAB restarted. Then all is fine.

openHAB Distribution Version Information
----------------------------------------
build-no        : Release Build
online-repo     : https://dl.bintray.com/openhab/mvn/online-repo/2.2

Repository        Version
----------------------------------------
openhab-distro  : 2.2.0
smarthome       : 0.10.0.b1
openhab-core    : 2.2.0
openhab1-addons : 1.11.0
openhab2-addons : 2.2.0
karaf           : 4.1.3
