### ISSUE TITLE
Paper UI Enhancement: Add "copy to clipboard" button to item list

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2707]
The list of channels contain a button 
![image](https://cloud.githubusercontent.com/assets/616792/21507177/62ba84ec-cc76-11e6-9cc6-c44b3c0919c7.png) that allows to copy the channel name to the clipboard. 
The same function would also be helpful for item names. Especially when adding new items to a sitemap this function would make it easier to copy/paste the item names.

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you add this?

**Comment by watou** [comment]
Would it be possible and a good idea to copy a complete definition to the clipboard as one could paste into a .things or .items file, as an easy way to switch from UI definitions to DSL?

**Comment by kaikreuzer** [comment]
@MHerbst I assumed you are requesting this for the item list, but having re-read your description, I am not sure if this is your idea. Do you ask to have a second "copy" button on the channel links, next to the already existing one? That would probably rather be confusing.

@watou: Note that the Paper UI is agnostic of any DSL syntax.

**Comment by MHerbst** [comment]
@kaikreuzer Your first read was correct. I only mentioned the buttons on channel links as an example.

**Comment by watou** [comment]
> Note that the Paper UI is agnostic of any DSL syntax.

The solution (OH2) could provide a serializer that overrides the default format for objects copied to the clipboard, as a means of providing a useful feature while ESH remains agnostic to the text format copied.
