### ISSUE TITLE
Cron-Rules and Timers not executed with default threadCount

### ISSUE THREAD

**Issue by querdenker2k** [eclipse/smarthome#2708]
My Cron based rules and timers are not executed with the default threadCount. Just when i increase the threadCount they are executed. Even in the log with org.quartz is nothing to see with the small threadCount.

**Comment by kaikreuzer** [comment]
Can you provide more details / examples on how to reproduce it?

**Comment by querdenker2k** [comment]
I used the nightly SNAPSHOT which was the newest 4 days ago. Before i updated i used an older version of OH2 but there everything worked (all crons and timer rules). After updating to the nightly build the crons and timers did not work. There had not been executed. After updating to Beta5 i found out that the cron rules are not working when they have spaces in the rule name like "Test Test". This was simply tested with an empty (just printing some log data) rule.
(But i am not sure. I had as well deactivated the caldav binding, with with i am loading about 10 calendars. The binding is using quartz as well.)

**Comment by kaikreuzer** [comment]
There have been many improvements and fixes on the rule engine meanwhile (the latest is https://github.com/eclipse/smarthome/pull/4185), so I would hope that your issues are solved.
If you still encounter any issues, please feel free to open a new issue with details and logs about it. Thanks!
