### ISSUE TITLE
Sonos binding: the sound notification mechanism should not parse the queue content

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2709]
The sound notification mechanism is parsing the queue content just to know how many items are in the queue and then add the new item at the end of the queue. This parsing could take a huge amount of time in case you have several thousands of items in your Sonos queue. By the way, this parsing is useless, you can add an entry at the end of the queue without knowing how many items are in the queue.

I will propose an enhancement.

**Comment by lolodomo** [comment]
Is there any reason to insert the notification sound at the end of the queue ?
I think we could insert it "as next" in the queue and retrieve as result of the insert call the inserted position.
Like that, no need at all to parse the queue content to play a sound notification.

**Comment by kgoderis** [comment]
I have no clue, I did not contribute that code. but the approach you suggest might be more sensible
