### ISSUE TITLE
Sonos binding: SonosXMLParser.getEntriesFromString produces warnings

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2710]
It has been reported that SonosXMLParser.getEntriesFromString run by the binding when scanning the queue content (while a sound notification is played) produces several warnings due to metadata fields that are not considered. These fields are at least narrator and albumArtist.

**Comment by lolodomo** [comment]
Maybe the warning log should be replaced by a DEBUG log ?

**Comment by kgoderis** [comment]
Possibly, I think it was like it is to facilitate reverse engineering efforts. Pls feel free to improve this.
