### ISSUE TITLE
[PaperUI] Show Items even if Item Linking is "simple"

### ISSUE THREAD

**Issue by hakan42** [eclipse/smarthome#2712]
The paperui shows the item lists if the item linking option is not switched to "simple".

This list is so useful that I find myself always turning simple item binding to off, until I have to configure a new binding. Then I switch it to simple again for a short time.

Perhaps the list of Items could be always visible, and in a "read only" mode unless that option is switched to simple? Meaning, instead of removing the list, show it in read only mode somehow?

**Comment by kaikreuzer** [comment]
No, the whole idea of the simple mode is that the users does not have to KNOW at all about the existence of items - hence showing them would be counter productive.
The question is rather, if you are working with items, what are you missing in advanced mode that makes you switch back to simple mode at all?

**Comment by hakan42** [comment]
Mainly, I haven't found an easy way to determine the proper channel definition for a given item. I switch to simple, klick on the linkong button on the thing view, see the auto-generated item name and can deduct what the channel string must look like. 

Mostly, I need this for auto-discovered things or bindings I am not that familiar with. 

Admittedly, reading the documentation of a given binding might also help me here but where is the fun in that?  :)

**Comment by MHerbst** [comment]
I think you can also get the information via the Rest APi. If you instslk the Rest Add-On you can execute API  calls from the Browser.

**Comment by kaikreuzer** [comment]
> an easy way to determine the proper channel definition

Hm, isn't this very straight forward? The channel UID is displayed by the Paper UI and it even offers a "copy to clipboard" icon next to it, so that you can easily use it to link your items:

<img width="274" alt="screen shot 2016-12-29 at 18 35 22" src="https://cloud.githubusercontent.com/assets/3244965/21549880/c6372694-cdf5-11e6-8258-4203b9977992.png">

**Comment by hakan42** [comment]
Hmmm... Sorry, temporary blindness on my part. I guess I stared so often at the Paper UI that I simply stopped seeing that part. I'll try to add a sentence or two to the "Items" section of the documentation .
