### ISSUE TITLE
Basic UI: Visibility for frames

### ISSUE THREAD

**Issue by Andirs55** [eclipse/smarthome#2713]
As mentioned in the [forums](https://community.openhab.org/t/sitemap-visibility-features-are-gone-for-frames/15586/5) the visibility feature for frames do not work (anymore).

Example Sitemap:
```
Frame label="Kodi" visibility=[Mediaserver_Switch==ON] {
Text item=Kodi_Playerstate visibility=[Mediaserver_Switch==ON]
Text item=Kodi_Playertitle visibility=[Mediaserver_Switch==ON]
}
```

If the Mediaserver_Switch is OFF the text items are invisible,but the empty frame remains. 
In older versions it went invisible as well.

**Comment by kaikreuzer** [comment]
@resetnow Could you have a look, please?

**Comment by resetnow** [comment]
It looks like it was broken when I implemented client-side visibility events support. This can be fixed easily, but then there is a problem with sitemap events for frames — I don't see any events when a frame visibility is changed. I'll look into it.

**Comment by resetnow** [comment]
#2735

**Comment by lolodomo** [comment]
As PR was merged, I assume the issue could be closed ?
