### ISSUE TITLE
Documentation: label and description for a channel

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2716]
I discovered looking at the XSD that it is possible to define a label and a description for a channel. It is something not yet documented and I thought it was simply a missing feature.
Documentation only mentions the label and the description XML tags on the channel type, not on the channel.

**Comment by lolodomo** [comment]
I think it should be enhanced in this two places:
https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/bindings/xml-reference.md
https://eclipse.org/smarthome/documentation/development/bindings/how-to.html

**Comment by lolodomo** [comment]
I just proposed a fix for the documentation inside Git repository.
I imagine that the documentation inside Eclipse SmartHime WEB site will then be updated either by an automatic or manual action (https://eclipse.org/smarthome/documentation/development/bindings/xml-reference.html) ?

**Comment by kaikreuzer** [comment]
> I imagine that the documentation inside Eclipse SmartHime WEB site will then be updated either by an automatic or manual action 

Correct, I update that manually from time to time.
