### ISSUE TITLE
take over createTimerWithArgument functionality from openhab

### ISSUE THREAD

**Issue by tiktok7** [eclipse/smarthome#2718]
In Openhab, ScriptExecution.java was updated like [this](https://github.com/openhab/openhab/pull/1436/files) in 2014 to allow an extension to the createTimer syntax that allows a parameter to be supplied to the timer function. This was apparently not fed back to the equivalent smarthome source [file](https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/actions/ScriptExecution.java#L83). The background to the issue are shown [here](https://github.com/openhab/openhab/pull/1436)

**Comment by mag2bue** [comment]
Will this feature be available in the next version?

**Comment by maggu2810** [comment]
@kaikreuzer Does it make sense to add this to the model script execution code base?
@mag2bue / @tiktok7 If @kaikreuzer agree, will you create a PR?

**Comment by kaikreuzer** [comment]
> Does it make sense to add this to the model script execution code base?

Probably yes, it seems it was missed at the time to also port that change to ESH.

**Comment by maggu2810** [comment]
> Probably yes, it seems it was missed at the time to also port that change to ESH.

So @mag2bue / @tiktok7 only a PR is missing :wink:

**Comment by DigitalBites** [comment]
FYI... I have already implemented this and have been using it for the past couple days. I will create a PR so that others can use this as well. It appears that a number of people have been wanting this functionality and I bumped into needing it too. :)
