### ISSUE TITLE
change url of Paper UI from /ui to /paperui

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2725]
For consistency reasons, I would suggest to change the url of the Paper UI from /ui to /paperui, as we also have /classicui and /basicui.

@maggu2810 & @sjka, are you ok with such a change (seeing that it might potentially break existing documentation or clients)?

**Comment by maggu2810** [comment]
It will break something (at least for me), but I agree that it makes sense and should be done (rather sooner then later).
I am ok with such a change.

**Comment by BClark09** [comment]
Is it worth making /ui redirect to a default? This could be set as paperUI initially and then the capability to set it can come later.

**Comment by kaikreuzer** [comment]
I think this would be up to the solution to decide whether it wants to introduce such a redirect.

**Comment by maggu2810** [comment]
I agree with @kaikreuzer that such a redirect is something that should be placed in the resp. solution / product.

**Comment by sjka** [comment]
👍 
As far as I can tell we are okay with such a change.
