### ISSUE TITLE
sounds directory

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2726]
The sounds directory needs to be placed under the configuration directory (e.g. conf/sounds).

* `static final String SOUND_DIR = "sounds";`
* `File soundsDir = Paths.get(ConfigConstants.getConfigFolder(), AudioManager.SOUND_DIR).toFile();`

The doorbell mp3 is currently placed in `distribution/smarthome/runtime/sounds`.
If the SmartHome launch configuration is used it will look for sounds into `distribution/smarthome/conf/sounds`.

So, at the moment to use the doorbell sound for testing the `runtime/sounds` directory needs to be copied to `conf/sounds`.

Can the diretory be moved?
Any files (e.g. sources, resources, features, ...) that refer to `runtime/sounds`?

**Comment by kaikreuzer** [comment]
Imho, it can be moved safely to conf. That has been changed in the openHAB distro, but I missed that file here in ESH.
