### ISSUE TITLE
PlayerItem STOP state and/or command?

### ISSUE THREAD

**Issue by mtzro2003** [eclipse/smarthome#2741]
Hi!

I have a PlayerItem linked to the new Kodi binding and I noticed that the item does not have the STOP state. (original post: [https://community.openhab.org/t/open-tv-channel-in-xbmc-kodi/17330/18?u=mihai_badea](url))
Could the STOP state and command be implemented?
STOP is quite different than PAUSE. From PAUSE you can resume with a PLAY command, but from STOP evidently you cannot.

**Comment by kaikreuzer** [comment]
There was a long discussion (which I unfortunately cannot find anymore right now) about this when the Player item type was introduced. The outcome was that we wanted to keep UI requirements simply and take the [Apple Remote](http://store.storeimages.cdn-apple.com/4662/as-images.apple.com/is/image/AppleInc/aos/published/images/M/M4/MM4T2/MM4T2?wid=572&hei=572&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=-Tlkl2) as an archetype.

If a certain hardware/binding requires more than that, it should implement a dedicated channel. "stop" can actually then mean very different things for different bindings: Some go to a standby mode, some clear their playlist, some only change their position of the current title to 0 and others completely turn off the device. With a separate channel, we are better off to cover these different semantics individually.
