### ISSUE TITLE
BasicUI lacks branding

### ISSUE THREAD

**Issue by resetnow** [eclipse/smarthome#2750]
When BasicUI is added as a webapp to home screen on iOS or Android, the shortcut has a default icon, and the splash screen doesn't have an image. Now, would it be wrong to have Openhab-related images in Eclipse Smarthome repository? Where should the branding go? Files are served statically and no additional processing on the server side is needed.

References: 
* https://developer.chrome.com/multidevice/android/installtohomescreen
* https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by kaikreuzer** [comment]
Good point, I also wanted to address this sooner or later. You are quicker :-)

The openHAB specific files should go into https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.ui.basicui/patch/web

**Comment by resetnow** [comment]
Thanks for the hint. I couldn't find an openHAB logo in SVG, could you please point me to a vector version of <a href="http://www.openhab.org/assets/images/openhab-logo-square.png">this image</a>?

**Comment by kaikreuzer** [comment]
Try this: [openHAB-logo.svg.zip](https://github.com/eclipse/smarthome/files/685849/openHAB-logo.svg.zip)
