### ISSUE TITLE
PaperUI, text entry and annoying shifting

### ISSUE THREAD

**Issue by tmrobert8** [eclipse/smarthome#2752]
In the PaperUI->Control - if you have a channel that is a simple string and start typing letters, eventually you'll enter the 8th character and the whole field shifts down a line.

The problem with the shift down is that the field loses focus.  Especially annoying is if you click it again and backspace once (so we have 7 characters) - it shifts back up and loses focus again. This behavior makes it very difficult to enter something in.

I'd rather it either get's focus (and the carot position is after the last character) or the field simply scrolls

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you check how this could be improved?
