### ISSUE TITLE
UX improvements on rule editor

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2763]
I would like to suggest some improvements for the rule editor in the Paper UI.
This is how it currently looks like:

<img width="1006" alt="screen shot 2017-01-05 at 15 32 56" src="https://cloud.githubusercontent.com/assets/3244965/21684028/457df714-d35c-11e6-9a2a-46ecada5c594.png">

- Similar to the Things edit page, the title should not say `"Rules > Configure"`, but `"Edit <ruleId>"`.
- The name should be displayed much bigger, at least like "Triggers" etc. The "Name" caption can possibly be removed (and only the grey "Name" being left if the field is blank), if this is easily possible.
- The description field allows multi-line input, but it does not expand. It should always show all entered lines instead. Like for the name, the caption could be removed, if text has been entered.
- "Status" can imho be removed from the editing page
- The titles "Triggers", "Actions" and "Conditions" should be changed to "When...", "then..." and "but only if...". This will make it more clear to users and it also helps finding good label texts for modules (they are pretty technical right now...).
- The font size of the module labels should be increased
- There should be no horizontal line above the conditions

The result I would imagine to look similar to this:

<img width="1004" alt="screen shot 2017-01-05 at 16 02 26" src="https://cloud.githubusercontent.com/assets/3244965/21685084/7f448de2-d360-11e6-8812-7190814619f1.png">

**Comment by danchom** [comment]
Sounds good but:
1) If the name was not set I think the ruleUID should be display.
2) I'm not sure about changing names of triggers conditions and actions boxes. If the trigger name is WHEN how do you explain to customers that its configuration is part of the trigger section of JSON presentation? Also I'm  not sure if the users will understand purpose and difference between "when" and "but  only if"

**Comment by kaikreuzer** [comment]
1. No, the idea is already in the header of the page. This is the input field for the name, it must not display any other content.

2.:
> how do you explain to customers that its configuration is part of the trigger section of JSON presentation

I do not explain it at all, because a user should not have to know about JSONs at all - this is only relevant for developers.

> if the users will understand purpose and difference between "when" and "but only if"

I am sure they will - all they have to do is to read the full rule by concatenating the different parts:

When... the energy consumption changes
then... change the color of my light
but only if... someone is at home

Isn't this much better than:

Triggers - Item change update trigger
Actions - send command to item
Conditions - item state condition

**Comment by danchom** [comment]
Yes, It is better but I mean something like this:
Tiggers:
    the energy consumption changes
    the temperature changes
Actions:
    change the color of my light
Conditions:
    someone is at home

Anyway the words: When, Then, "but only if" are also good for me.
BTW in this interface there is no way to set connections between modules. Do you have some plans about them?

**Comment by kaikreuzer** [comment]
> Do you have some plans about them?

Not yet - I'd go for the start with auto-wiring.
But if you have suggestions how this could be added nicely, feel free to tell us :-)

**Comment by danchom** [comment]
I'm not sure how cool is it, but we have expressed them as table:
output -> connection (moduleID / inputID)
input -> connection (moduleID / outputID)

**Comment by kirantpatil** [comment]
:100: :+1: for 
When... the energy consumption changes
then... change the color of my light
but only if... someone is at home

**Comment by danchom** [comment]
May be connections can be expressed by unique colors or numbers.
For example:  if we have two ItemStatechangeTrigger, the first one for "the energy consumption changes" with event output mark as red or 1 and the second one for "the temperature changes" ,which can mark its  event output  as blue or 2 then the inputs which have to be connect to the "energy consumption changes" output must  select red color or number 1.

**Comment by kaikreuzer** [comment]
I guess you will have to come up with a drawing to have me understand the idea :-)
In any case, I think it will be difficult to fit it into the current block/list based editor and probably the UI framework with its widgets might be too limited.
I therefore would like to go for two approaches:
- Use auto-wiring for the existing (simple) rule editor only. Anything that would require manual wiring should not be allowed to do here
- Create an expert rule editor in future, which gives the user fully-fletched control over the wiring. This would probably rather end up in something similar as Node-RED.
