### ISSUE TITLE
Add additional contexts for config descriptions

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2764]
We currently have [this list of supported contexts](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#supported-contexts) (actively supported in the Paper UI).

Looking at rule modules, we might want to cover some more of the ESH entities:

- The RuleEnableModule requires the selection of a rule. A "Rule" context would be nice for it.
- The ChannelEventTrigger requires a trigger channel as a parameter. It would be nice to be able to use "Channel" as a context with a filter criteria "kind" with possible values "STATE" and "TRIGGER". Note that we do not have a /rest/channels endpoint, so the UI would have to traverse through the Things. Is that a problem, @aounhaider1?

**Comment by danchom** [comment]
LGTM.
