### ISSUE TITLE
BasicUI not showing all icons

### ISSUE THREAD

**Issue by mherwege** [eclipse/smarthome#2771]
I have created a number of switch type items through PaperUI, all exactly the same way. I did not specify a category for the items. In the PaperUI item configuration screen, the switch icon shows up for all of them. Only one of them shows with a switch icon in BasicUI, all the others have the icon missing.
Looking at the URL for the images, I can see different URLs: http://localhost:8080/icon/switch?state=OFF&format=svg for the one being served correctly and http://localhost:8080/icon/?state=OFF&format=svg for the one with the image missing. It looks like the type is not picked up for some reason.

**Comment by kaikreuzer** [comment]
Should be fixed with https://github.com/eclipse/smarthome/pull/2843
