### ISSUE TITLE
missing BasicUI and PaperUI after upgrade lastest snapshot

### ISSUE THREAD

**Issue by phil2fer** [eclipse/smarthome#2773]
After upgrading from `openhab2-offline_2.0.0~20170103034422_all.deb`,  to `openhab2-offline_2.0.0~20170106124335_all.deb`

 to openhab2-offline_2.0.0~20170106124335_all.deb, i have a problem with PaperUI and Basic UI. No more icon Application in my start page

![image](https://cloud.githubusercontent.com/assets/23247807/21732171/897a9af6-d458-11e6-8ed7-3498e30b6517.png)
and in my log file i have this error 

`2017-01-06 20:47:58.930 [INFO ] [org.eclipse.smarthome.ui.paper      ] - FrameworkEvent INFO - org.eclipse.smarthome.ui.paper
org.osgi.framework.BundleException: The bundle class path entry "patch/" could not be found for the bundle "osgi.identity; osgi.identity="org.eclipse.smarthome.ui.paper"; type="osgi.bundl
e"; version:Version="0.9.0.201612221226"; singleton:="true""`
and i have the same error with BasicUI

I don't know if it's a bug or not. Someone could help me to solve this issue ?

**Comment by kaikreuzer** [comment]
There is definitely no bug/problem is ESH.
I also tried the latest openHAB distro right now and both UIs start up correctly.
I'd assume that you have some broken setup due to upgrades.
In any case, it is probably best if you ask for help at 
https://community.openhab.org/.
