### ISSUE TITLE
Paper UI: Language set in Preferences is ignored

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#2777]
This is a follow-up issue to #2589.

On page *Preferences* it is possible to set a language for the user interface. This value is ignored. Instead always the language of the browser is used as language in all REST API  request that are executed by Paper UI receive the different values (e.g. binding infos).
I have checked it with the debugger and the *acceptlanguage* field of the request contains always the locale of the browser. 

The question is whether this language preference setting is really necessary. In my opinion the browser's language (with english as fallback language) is sufficient and I don't know whether anybody wants to set a different language.

Another option would be use the language set in the locale (under Configuration/System) also as language for Paper UI.

**Comment by kaikreuzer** [comment]
@aounhaider1 Can you have a look?
