### ISSUE TITLE
Basic UI: Displaying broken image when no icon is defined.

### ISSUE THREAD

**Issue by chriscolden** [eclipse/smarthome#2784]
I'm getting a broken image displayed in the browser when no icon is defined. Classic UI doesn't add the img tags when no icon is defined.

**Comment by kaikreuzer** [comment]
@resetnow Could you check?

**Comment by resetnow** [comment]
I thought about that, looks ugly. Would it be better to replace icon to `none` if there is no matching icon like this:

<img src="https://cloud.githubusercontent.com/assets/2057191/21773122/4e1ec364-d6a7-11e6-839d-6d70fb915fe8.png" width="400">

Or remove the icon completely:

<img src="https://cloud.githubusercontent.com/assets/2057191/21773104/3c767986-d6a7-11e6-8d40-884fae60a4c5.png" width="400">

?

**Comment by kaikreuzer** [comment]
> Would it be better to replace icon to none if there is no matching icon like this

Yes, definitely, this is also how the Classic UI renders it.

**Comment by ThomDietrich** [comment]
> Would it be better to replace icon to none if there is no matching icon like this

I would also agree

**Comment by lolodomo** [comment]
@resetnow: what would be the best solution to display the none.png image and how to know if we need to use the none.png file ?
I took a look to the code and I saw that the img src tag for the icon in snippets is currently a pattern in which we replace different parts (category, state, ...). Of course, similar code in the JavaScript code to refresh the icon.
Do we need to change all snippets to have the ability to set fully the value of the img src ?
And should we consider a specific "none" category when the comuted category is "number" ?

**Comment by resetnow** [comment]
@lolodomo there is a PR which illustrates the basic idea for that, but it was way too hacky so it wasn't merged https://github.com/eclipse/smarthome/pull/2799

It was meant to check the icon existence server-side.

**Comment by resetnow** [comment]
Just noticed I deleted the branch. There was a class that watched icon providers via OSGI, and there was a method getIcon, which would return "none" if there is no icon. Basically it was a proxy for all the icon providers.

**Comment by lolodomo** [comment]
Ok, I think that the real subject is the issue #2994 and the need to define a default icon in the iconset for any number item.
Do you agree that the problem mentioned in the current issue concerns only number items with no icon set ?
Using my sitemap, I noticed that problem only in this case.

**Comment by resetnow** [comment]
I too only have noticed it with numbers but I think a more future-proof solution would iclude other cases.

**Comment by lolodomo** [comment]
I found other cases when using selection elements in sitemap assicated to either a string item or number item.

**Comment by lolodomo** [comment]
As a workaround, adding `icon="none"` for the selection element in the sitemap of course avoids the broken image.

**Comment by lolodomo** [comment]
I think we should update the icon proxy to consider the none icon in case no provider is delivering the requested icon category, rather than returning a 404 error. We could log a message of course. The change is easy, I will propose a fix.

**Comment by lolodomo** [comment]
@kaikreuzer : you can close this issue now that PR #3441 is merged.
