### ISSUE TITLE
Misleading error msg, Valid command types

### ISSUE THREAD

**Issue by lejonpart** [eclipse/smarthome#2787]
Hi

I found this error message to be somewhat misleading,

openhab> smarthome:send Projcast_Control Pause
Error: Command 'Pause' is not valid for item 'Projcast_Control'
Valid command types are: ( PlayPauseType RewindFastforwardType NextPreviousType RefreshType )

Why does is not say that Valid command types are PLAY PAUSE and so on ...?

openhab> smarthome:send Projcast_Control PAUSE
Command has been sent successfully.
openhab> smarthome:items
Projcast_Control (Type=PlayerItem, State=PLAY, Label=Control, Category=)

Regards
Lejonpart

**Comment by sjka** [comment]
How about something like this?

```
Error: Command 'hallo' is not valid for item 'my_switch'
Valid command types are:  
  OnOffType: ON OFF 
  RefreshType: REFRESH 
```

**Comment by lejonpart** [comment]
@sjka A lot better :)
