### ISSUE TITLE
Icon (color) not changing for MAPped items

### ISSUE THREAD

**Issue by metbril** [eclipse/smarthome#2792]
I have an item for which the label is using a MAP:

**network.items**
```
Switch Network_Router "ASUS Router [MAP(network_nl.map):%s]" <network> (Network) { channel="network:device:001:online" }
```

**network_nl.map**
```
ON=online
OFF=offline
NULL=onbekend
-=-
```

**demo.sitemap**
```
Text   item=Network_Sonos
```

The icon does not change to ON (green) or OFF (red). It appears to look at the MAPped value instead of the actual switch value. So the icon is always default/neutral (black)

I would expect that the label is only used for display purposes.

This applies to any UI: basic, classic and iOS app.

If I remove the map in the items file, the icon is changing color:
```
Switch Network_Router "ASUS Router [%s]" <network> (Network) { channel="network:device:001:online" }
```

If I let the item definition unchanged, but force the label in the sitemap without a mapping, this does not have an effect on the icon (still black icon).
```
Text   item=Network_Sonos label="Routerrrrrr [%s]"
```

This requires me to specify a label in multiple places (the items file (without MAP) and **any** sitemap (with MAP)). 

I prefer to have [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) code.

**Comment by rtvb** [comment]
Related to #2788?

**Comment by lolodomo** [comment]
Should be fixed by merged PR. #3135

**Comment by lolodomo** [comment]
Please check that it is fixed with a recent snapshot (at least 849) and then clise the issue.

**Comment by lolodomo** [comment]
@kaikreuzer : this issue is fixed. Please close it.
