### ISSUE TITLE
Explicit import of joda DateTime required

### ISSUE THREAD

**Issue by rtvb** [eclipse/smarthome#2793]
Some date manipulations need explicit import of org.joda.time.DateTime.
Expected behaviour is that this is not required.

```
/* test.rules */

import org.joda.time.DateTime

rule "TestNow"
when
	Time cron "*/10 * * * * ?"
then

	var DateTime dt1 = now
	var DateTime dt2 = now.withTimeAtStartOfDay

	logInfo("TestNow", "Now: " + dt1) // raises error without import
	
	if (dt1 == dt2) { // raises error without import
		logInfo("TestNow", "EQ")
	} else {
		logInfo(TestNow", "DIFF")
	}

end
```

Please see this forum thread:
https://community.openhab.org/t/timer-and-date-calculations-in-rules-need-help/19843/12?u=rtvb

**Comment by watou** [comment]
Related issue: https://github.com/eclipse/smarthome/issues/1735

**Comment by kaikreuzer** [comment]
I hope the missing opening quotes were just a typo here on github and not really in your rule:
```
 		logInfo(TestNow", "DIFF")
```

You are right, the joda time package should be implicitely imported, but this seems to have gone missing on the last Xtext upgrade. I'll provide a fix.

**Comment by rtvb** [comment]
I hope the missing opening quotes were just a typo here on github

Yes that was a typo
