### ISSUE TITLE
Air Quality binding

### ISSUE THREAD

**Issue by kubawolanin** [eclipse/smarthome#2794]
I started working on a binding that would give you information about [AQI](https://en.wikipedia.org/wiki/Air_quality_index) in a given location, based on geo coordinates.
I'm using [aqicn.org](http://aqicn.org) for that purpose.

Here's a [openHAB community thread](https://community.openhab.org/t/measuring-air-quality-with-aqicn-org/19899) about the idea.

I'm already successfully reading `aqi` value along with other details about measurement.

My question is regarding data structure and handling it properly in a binding.
Take a look at this structure:
```json
{
  "status": "ok",
...
    "iaqi": {
      "pm25": {
        "v": 333
      },
      "pm10": {
        "v": 168
      },
      "o3": {
        "v": 4
      },
      "no2": {
        "v": 36
      },
      "so2": {
        "v": 52
      },
      "t": {
        "v": -13
      },
      "p": {
        "v": 988
      },
      "h": {
        "v": 84
      }
    }
...
```

These are details of particle pollution (PM2.5 / PM10) along with concentration of other gases in air + some extra data from WeatherUnderground, like temperature (`t`), pressure (`p`) and humidity (`h`).

The problem is that [some stations](https://aqicn.org/sources/) don't provide full information about things like `no2`, `so2` and so on.
According to [the documentation](https://aqicn.org/json-api/doc/), the only constant value for all stations is `pm25`.

I would like to create the following channels in my binding:
```xml
		<channels>
			<channel id="aqi" typeId="aqi" />
			<channel id="aqiDescription" typeId="aqiDescription" />
			<channel id="pm25" typeId="pm25" />
			<channel id="pm10" typeId="pm10" />
			<channel id="no2" typeId="no2" />
			<channel id="co" typeId="co" />
			<channel id="locationName" typeId="locationName" />
			<channel id="locationUrl" typeId="locationUrl" />
			<channel id="observationTime" typeId="observationTime" />
			<channel id="stationId" typeId="stationId" />
		</channels>
```

If for some reason there's no data containing `pm10`, `no2` or `co` for a given location, can I just return `0` in the channel? 
Or should I omit these completely and just go with `pm25`? 

Thank you,
Kuba

**Comment by hakan42** [comment]
I would provide all channels and leave it to the user to configure a channel for it.

And when fetching data from the API, leave the channels in UNDEF_STATE if that specific station provides no data for a given channel.

That way, you would give the user maximum flexibility. I go a similar way with my senseBox binding  (PR not merged yet, but you can read the sources on the PR list)

**Comment by kubawolanin** [comment]
Thank you @hakan42 for your insight! I did as you advised.
I've decided I'm going to publish this binding on `openhab2-addons` repo. Closing this issue for now.
For those interested in the binding itself, please check out (this pull request)[https://github.com/openhab/openhab2-addons/pull/1738].

Best regards!
Kuba
