### ISSUE TITLE
Update Guava to a more recent version

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#2801]
In ESH, we are currently using Guava 10.1. 

As discussed in https://www.eclipse.org/forums/index.php/t/1065860/, on of the main benefits of this version is that is is slightly smaller than newer versions (1.5M vs. 2.4M). 

However, all Solutions I'm aware of are packaging a Guava 15 or higher anyway. So do we really need to stick to that old version? We ran into troubles a couple of times now, with #2783 being just the latest accident.

Therefore I propose to upgrade to a more recent version. Guava 20 currently is the newest, but I haven't checked it yet for any potential incompatibilities.

**Comment by kaikreuzer** [comment]
> Guava 20 currently is the newest, but I haven't checked it yet for any potential incompatibilities.

If they follow semver, it would mean that 20 is as incompatible to 15 as 10 to 15 ;-)

For the few things that we are actually using, I still think that >2MB is simply terribly fat.
Maybe we should define (in a good OSGi manner) only a few packages from Guava that we allow to use - including their valid version range, which we should then also ensure in the MANIFEST.MF.

**Comment by sjka** [comment]
> the few things that we are actually using

That's a pretty valid point, indeed. I have created #2805 and #2809 in order to eliminate to outliers. Then we are left with only two packages when looking at our sources (i.e. not including imports from 3rd party libraries):

```
  52 com.google.common.base
 107 com.google.common.collect
```

So it would be pretty simple to restrict usage to only these two packages, i.e. not allow usage of additional ones.

Looking at what we are using there, I see a huge overlap with apache commons. When I have some time I will have a look at how much we actually "need" and what could be replaced instantly.

**Comment by maggu2810** [comment]
> Looking at what we are using there, I see a huge overlap with apache commons. When I have some time I will have a look at how much we actually "need" and what could be replaced instantly.

:+1:

**Comment by kaikreuzer** [comment]
> When I have some time I will have a look at how much we actually "need" and what could be replaced instantly.

Sorry to be doubtful about that as well. Imho, using apache commons might not be the best solution either. Actually, Guava seems to be more modern and closer to the specification, at least this is what [Google claimes](https://code.google.com/archive/p/google-collections/wikis/Faq.wiki). The fact that apache commons 2.6 (which we use) does not support generics is indeed not nice.
As a matter of fact commons 2.6 is pretty outdated and many libs have rather moved to commons 3.x or guava. Commons 3.x has a new namespace though, so this isn't backward compatible to 2.6 either.

**Comment by maggu2810** [comment]
@kaikreuzer If my reading is correct the FAQ compared "Apache Commons Collections" to the "Google Collections Library". So, it is related to one of the Apache Commons artifact (https://commons.apache.org/). There is also not a commons 2.6 but every artifact has its own versioning as they are not related to each others. Or am I missing something?

**Comment by kaikreuzer** [comment]
My example with 2.6 vs. 3.x referred to commons-lang. The same is true for commons-collection, there it is version 3.2 vs. version 4.x (which again comes with a new namespace).

**Comment by maggu2810** [comment]
Any reason not to bump the version of the used Apache Commons packages (haven't looked at the size, yet)?

**Comment by kaikreuzer** [comment]
Yeah, the reason is the changed package namespace. We would have to refactor all existing code, so it is a breaking change.
But nonetheless, I would agree that we should do this move sooner or later - unless we say that we completely want to drop commons and go for Guava instead :-)

**Comment by sjka** [comment]
I give up. Whatever we will decide to to one day, it won't be what I initially described here, therefore I close this issue for now.
