### ISSUE TITLE
SmartHome Designer fails to start

### ISSUE THREAD

**Issue by pvds2** [eclipse/smarthome#2813]
running Java 8 v111, and eclipse smarthome v8 or v9 unzipped in the applications folder.
I see the splash screen and then an error is thrown. The log says this:

```
!SESSION 2017-01-12 21:40:22.670 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Command-line arguments:  -os macosx -ws cocoa -arch x86_64

!ENTRY org.eclipse.core.runtime 4 0 2017-01-12 21:40:23.533
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.core.runtime [2]
  Unresolved requirement: Require-Bundle: javax.annotation; bundle-version="1.1.0"; visibility:="reexport"; resolution:="optional"
  Unresolved requirement: Require-Bundle: javax.inject; bundle-version="1.0.0"; visibility:="reexport"; resolution:="optional"
  Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.6.100,4.0.0)"; visibility:="reexport"
```
Anybody ran into this too and solved it?

BR

**Comment by kaikreuzer** [comment]
I assume your are talking about the Designer, right?
Indeed, this is currently broken (not only on Mac) - and you are right, there wasn't an issue entered for it yet, so thanks for that.

Note: I can only confirm an issue for the 0.9.0-SNAPSHOT - the [official 0.8.0 release](https://www.eclipse.org/downloads/download.php?file=/smarthome/releases/0.8.0/eclipsesmarthome-incubation-0.8.0-designer-macosx64.zip) works for me on macOS Sierra.

**Comment by pvds2** [comment]
Hi Kai,

I have retried this with the 0.8.0 version as you suggested. took your link to the offical site and downloaded the .zip. Moved the .zip to the Applications folder and unzipped. It fails as well. Same error log:


```
!SESSION 2017-01-13 11:40:14.680 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Command-line arguments:  -os macosx -ws cocoa -arch x86_64

!ENTRY org.eclipse.core.runtime 4 0 2017-01-13 11:40:15.357
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.core.runtime [2]
  Unresolved requirement: Require-Bundle: javax.annotation; bundle-version="1.1.0"; visibility:="reexport"; resolution:="optional"
  Unresolved requirement: Require-Bundle: javax.inject; bundle-version="1.0.0"; visibility:="reexport"; resolution:="optional"
  Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.6.100,4.0.0)"; visibility:="reexport"
```

**Comment by kaikreuzer** [comment]
Could you try the latest 0.9.0-SNAPSHOT from https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/, which has just been fixed today and works well for me?

**Comment by Leonid1973** [comment]
I tested SmartHomeDesigner 0.9 (actual Version from today) with macOS 10.12.3
Start fails with error: java.lang.RuntimeException: Application "org.eclipse.smarthome.designer.ui.application" could not be found in the registry. 
I don't know what to do. Can somebody help?

log-File is attached...

[1486725753210.txt](https://github.com/eclipse/smarthome/files/766510/1486725753210.txt)
