### ISSUE TITLE
[Hue Binding/Extended Color Light]: Brightness control changes color of light

### ISSUE THREAD

**Issue by gh-h2s** [eclipse/smarthome#2815]
For the Osram Lightify Flex you can not change the brightness of the color temperature.

As workaround, I added the brightness channel to the ExtendedColorLight.xml.

`		<channels>
			<channel id="color" typeId="color" />
			<channel id="color_temperature" typeId="color_temperature" />
			<channel id="brightness" typeId="brightness" />
			<channel id="alert" typeId="alert" />
			<channel id="effect" typeId="effect" />
		</channels>`

**Comment by kaikreuzer** [comment]
You mean sending a Percent value to the color channel does not work?

**Comment by gh-h2s** [comment]
It only works for the color channel, but not for the color temperature channel. The color temperature channel is always at 100% brightness and can not be controlled.

The Osram Lightify Flex (RGBW) has 2 modes, the color mode (RGB) and the color temperature mode (tunable white, White + Red or Blue). 

In the Philips Hue App you can control the brightness for both modes.

**Comment by kaikreuzer** [comment]
As I said, you always control the brightness by sending a percent value to the color channel.
You adjust the color temperature by sending a percentage value to the color_temperature channel.

**Comment by gh-h2s** [comment]
When I send the brightness value to the color channel, then the color channel will be set again. It's not possible to change the brightness in the color temperature mode. 

The color or color temperature is not my problem. The problem is to set the brightness in color temperature mode without changing to color mode.

Color mode = Red/Green/Blue
Color temperature = White/Red/Blue

I added the brightness channel to the ExtendedColorLight.xml all is working fine.

This is not working with openhab2.

Scenario:
1. Set color to Red and 100% brightness --> Result: Red
2. Set color temperature to 50% --> Result: The white LEDs are on.
3. Set brightness to color --> Result: Red and not white with 50% brightness

When I activate the brightness channel in the ExtendedColorLight.xml, then I can control the brightness in both mode. I mean the

**Comment by kaikreuzer** [comment]
Ok, that's why I asked "You mean sending a Percent value to the color channel does not work?".

Your answer to this is hence "Set brightness to color --> Result: Red and not white with 50% brightness", so this is a bug.

Adding a brightness channel is no good solution. Instead, the bug should be fixed and sending a brightness value should not change the active color.

**Comment by gh-h2s** [comment]
In my case the separate brightness control is the best solution. I can control only the brightness without big color picker panel and without effect on my room color setup.

**Comment by kaikreuzer** [comment]
You can always use a slider as a UI control for a color channel, this will then only adjust the brightness.
