### ISSUE TITLE
Map transformation service and '%d' in openhab2 does not work

### ISSUE THREAD

**Issue by HolgerHees** [eclipse/smarthome#2818]
It seams that %d is not supported as a placeholder with map transformation in openhab2

One possible solution is to replace %d with %s but this does not solve all problems.

e.g. with a group item where my map file looks like below:

5=AN
4=Einzeln
3=Einzeln
2=Einzeln
1=Einzeln
0=AUS

in openhab 1.x, I was using %d to map the group count value

now with openhab2, I can't do this anymore. If I change my placeholder %d to %s the group value is mapped to ON/OFF which is not useable in this case.

I can solve this by using a separate STRING item which will be filled by a separate rule. But this sound like "Using a sledgehammer to crack a nut".

the original issues was created here

https://github.com/openhab/openhab/issues/4965

**Comment by J-N-K** [comment]
Please provide the full item configuration. I have an idea what the problem is. @kaikreuzer, you can assign this to me.

**Comment by HolgerHees** [comment]
**default.items**

Group:Switch:OR(ON, OFF)        Motiondetector_Switch           "Gartenlicht Details. [MAP(motiondetector_switch_de.map):%d]" <selfLightInfo>   (Security)

**motiondetector_switch_de.map**

5=AN
4=Einzeln
3=Einzeln
2=Einzeln
1=Einzeln
0=AUS
undefined=undefiniert
-=undefiniert

**Comment by kaikreuzer** [comment]
>  @kaikreuzer, you can assign this to me.

I cannot assign the issue here, but feel free to come up with a PR!

**Comment by HolgerHees** [comment]
Am happy and surprised about the quick reaction :-)

**Comment by J-N-K** [comment]
@HolgerHees, I don't think this should work. From the docs:

> OR(value1, value2) 	Does a logical ‘OR’ operation. If at least one item is of ‘value1’ this is returned, otherwise the ‘value2’ is returned.

So you'll never get anything other than ON or OFF from this item defintion (at least if it is implemented according to the documentation). I'm not sure (and I don't have a OH1 setup available to check) thta this was different in OH1. It seems what you want is

> SUM 	Calculates the sum of all items in the group.

Please try that and report back. If it is not working out of the box, I would suggest to add something like COUNT(state) as a group function to count the number of all items in a specific state.

**Comment by HolgerHees** [comment]
thanks for you help. Evertime I learn new thinks.

first, the behavior in openhab 1.x is different, If you use %d here you will get the count value from the group item. But after your hint, the new behavior in openhab 2.x makes more sence. Because it is more clearly.

and it works in openhab 1.x too. :-)

now my item definition looks like

Group:Number:SUM        Motiondetector_Counter          "Gartenlicht Details. [MAP(motiondetector_counter_de.map):%s]" <selfLightInfo>  (Security)

and it works perfectly on openhab 1.x and it will be forward compatible. So if I start to move to openhab 2.x again. I have to fight with one problem less ;-)

THANKS!
