### ISSUE TITLE
Default value ignored by Paper UI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2819]
I have a config parameter defined as:
```
      {  
         "name":"operator",
         "type":"TEXT",
         "label":"Operator",
         "description":"the compare operator (one of =,<,>,!=)",
         "required":false,
         "options":[
            {
            "label": "=",
            "value": "="
            },
            {
            "label": "!=",
            "value": "!="
            },
            {
            "label": ">",
            "value": ">"
            },
            {
            "label": "<",
            "value": "<"
            }
          ],
          "default":"="
      }
```
I would expect the Paper UI to show "=" as a selection, but the field is left empty:

<img width="264" alt="screen shot 2017-01-13 at 09 34 38" src="https://cloud.githubusercontent.com/assets/3244965/21923304/8e20c6e6-d973-11e6-8664-879bb732b085.png">

**Comment by aounhaider1** [comment]
Shouldn't it be "defaultValue": "=" ?

**Comment by kaikreuzer** [comment]
Should it? In https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-configuration-descriptions, it says that the property name is "default"...

**Comment by kaikreuzer** [comment]
Now this is nasty. @aounhaider1 found out that this is due to the ConfigDescriptionParameterDTO - as "default" is a reserved keyword in Java, the DTO uses "defaultValue" as a field name instead of "default". Therefore, the serialized JSON becomes "defaultValue", although our XMLs contain "default". I think the right thing to do is to add a `@SerializedName("default")` to the field.
But this means that it is a breaking change - any UIs that currently expect "defaultValue" will need to be adapted...

Any thoughts, @maggu2810 & @sjka?

**Comment by maggu2810** [comment]
I am fine with both.
Is there any need that the DTO for the REST interface uses the same name as the XML element or only to keep one wording if possible?

**Comment by kaikreuzer** [comment]
> Is there any need that the DTO for the REST interface uses the same name as the XML element or only to keep one wording if possible?

What needs to be the same are the property names within the XML and the JSON - because both refer to the same [definition of config descriptions](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#configuration-descriptions) (which we actually should also update to also embrace JSON). The internal field name of the DTO can be different, but the input and output should match. Note that we also ask developers to define config descriptions in JSON (for the automation component), therefore we cannot chose a different name on the REST API - that would be a mess.
