### ISSUE TITLE
Fix events and event order fired by the automation module

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#2823]
When a rule is added the first NOT_INITIALIZED event is redundant.
For example:
osgi> 14:28:16.652 INFO  s.event.RuleStatusInfoEvent[:43] - rule_3 updated: NOT_INITIALIZED
14:28:16.657 INFO  s.event.RuleStatusInfoEvent[:43] - rule_3 updated: IDLE
14:28:16.658 DEBUG o.e.s.c.c.r.AbstractManagedProvider[:62] - Added new element rule_3 to ManagedRuleProvider.
14:28:16.658 INFO  smarthome.event.RuleAddedEvent[:43] - Rule 'rule_3' has been added.

or when the rule can't be resolved, the following events are fired:
osgi> 14:28:16.652 INFO  s.event.RuleStatusInfoEvent[:43] - rule_3 updated: NOT_INITIALIZED
14:28:16.657 INFO  s.event.RuleStatusInfoEvent[:43] - rule_3 updated: NOT_INITIALIZED
14:28:16.658 DEBUG o.e.s.c.c.r.AbstractManagedProvider[:62] - Added new element rule_3 to ManagedRuleProvider.
14:28:16.658 INFO  smarthome.event.RuleAddedEvent[:43] - Rule 'rule_3' has been added.

1) The first one NOT_INITIALIZED must be skiped
2) Order of events should be:
- Rule 'rule_3' has been added.
- rule_3 updated: NOT_INITIALIZED
- rule_3 updated: IDLE

**Comment by danchom** [comment]
May be the NOT_INITIALIZED  should not be fired in case of resolved rule:
At the moment the events are:
1) added/updated -> NOT_INITIALIZED  -> IDLE <->RUNNING
2) added/updated -> NOT_INITIALIZED
3) DISABLED -> NOT_INITIALIZED  -> IDLE <->RUNNING
4) DISABLED -> NOT_INITIALIZED
5) IDLE / RUNNING -> NOT_INITIALIZED ->DISABLED
6) NOT_INITIALIZED ->DISABLED

but they should be:

1) added/updated -> IDLE <->RUNNING
2) added/updated -> NOT_INITIALIZED
3) DISABLED -> IDLE <->RUNNING
4) DISABLED -> NOT_INITIALIZED
5) IDLE / RUNNING / NOT_INITIALIZED ->DISABLED

What do you thing?

**Comment by kaikreuzer** [comment]
The current situation is similar to [what we have on the Things](https://www.eclipse.org/smarthome/documentation/concepts/things.html#status-transitions). The important information here is that the state actually describes the handler status and the thing status at the same time - UNINITIALIZED describes the handler and it is a natural status on the transition to getting a Thing to ONLINE.

But I am open to discuss to follow a different logic for the rules - i.e. only describing the status of a rule itself (and NOT_INITIALIZED simply means that there is some issue with a handler, be it that they are not there or that something is misconfigured). So your suggestion sounds fine to me.

@maggu2810 & @sjka, do you have any comments?

**Comment by maggu2810** [comment]
I don't see a real cons if we change the status for rules at the moment, so okay for me.

**Comment by sjka** [comment]
I'm okay with changing them now. However, one thought about the name of the state: For Things we use UNINITIALIZED instead of NOT_INITIALIZED. IMHO we should strive for consistency throughout the project. Especially as the meaning is more or less the same.

**Comment by danchom** [comment]
There is one cons, when a rule is added it will be without status until it goes into IDLE or NOT_INITILIAZED (uninitialized - I'm ok to change the name). If someone call getStatus(theRule) it will receive null. This can be long time in case of deadlock of handler initialization. May be it is better to have INITIALIZING status for this period of time.
For example:
added -> initializing -> idle
added -> initializing -> not_initialized
because at the moment we have:
added -> not_initialized -> not_initialized , this I think it is not sufficient. 
What do you think?

**Comment by kaikreuzer** [comment]
Introducing INITIALIZING, we would then be very close to the Things statuses, which isn't bad.
But note that the state diagram of the Things say that UNINITIALIZED is the starting point.
So we would actually have:
added -> UNINITIALIZED -> INITIALIZING -> IDLE
added -> UNINITIALIZED -> INITIALIZING -> UNINITIALIZED (with details)

I think we should use the same definition in this case. Imho there is no need to send an event for the first "UNINITIALIZED" status after a rule has been added (this could simply be set internally and returned, if anybody calls getStatus() at that time). Looking at what we get as events, we would hence end up with what you suggest.

**Comment by danchom** [comment]
>added -> UNINITIALIZED -> INITIALIZING -> IDLE
added -> UNINITIALIZED -> INITIALIZING -> UNINITIALIZED (with details)

this is ok for me. I think also there is no need of event for the first UNINITIALIZED(without details) state.
