### ISSUE TITLE
Duplicated entry after modifying config in text based mode

### ISSUE THREAD

**Issue by MageGH** [eclipse/smarthome#2831]
Original entry:
Group GF_Wardrobe    "Wardrobe"      \<bath\>  (gGF)
Modified entry:
Group GF_Wardrobe    "Wardrobe"      \<wardrobe\>  (gGF)

On the Basic UI the entry will be duplicated and the duplication can be seen in the SmartHome-Designer also.

**Comment by kaikreuzer** [comment]
Looks like a duplicate of https://github.com/eclipse/smarthome/issues/637.
