### ISSUE TITLE
CometVisu does not work on Win10

### ISSUE THREAD

**Issue by MageGH** [eclipse/smarthome#2832]
I am getting the error below after installing CometVisu on build #717 (Win 10 Prof 64 bit).

HTTP ERROR 404
Problem accessing /cometvisu/. Reason:
Not Found

**Comment by kaikreuzer** [comment]
CometVisu is not part of ESH.
Please either enter an issue at https://github.com/openhab/openhab2-addons (but provide more details on your configuration plus log files) or ask for help at https://community.openhab.org/
