### ISSUE TITLE
Missing supported contexts

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2834]
The documentation contains a list of [valid contexts for config parameters](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#supported-contexts).

This currently lists only stuff supported by the Paper UI (and "contexts [that] require a specific format").
Imho this should list ALL defined contexts that people are allowed to use (independent of whether certain UIs already support it or not). The full list is currently only mentioned (well-hidden) in the [XML example](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-configuration-descriptions).

**Comment by kaikreuzer** [comment]
@aounhaider1 May I ask you to update that list accordingly?

**Comment by kaikreuzer** [comment]
Another comment: There is "Day of week" given as a supported context, but this is missing in the XML above. I assume the correct name would be "dayOfWeek", right? Please correct this as well.

**Comment by triller-telekom** [comment]
@kaikreuzer: Aoun has done this update on 23.02.2017 in commit e4cad788eec2087bd2e3c5c691a4aac90dd65674 but I cannot find a PR for it.

Can you please close this issue?

**Comment by kaikreuzer** [comment]
Sure.

**Comment by kaikreuzer** [comment]
FTR, PR was https://github.com/eclipse/smarthome/pull/3061.
