### ISSUE TITLE
binding skeleton script creates invalid tests

### ISSUE THREAD

**Issue by J-N-K** [eclipse/smarthome#2840]
When using the binding skeleton script, the result is not compilable because of imports that can't be resolved.

**Comment by kaikreuzer** [comment]
Can you fix this?

**Comment by J-N-K** [comment]
I'll give it a try

**Comment by J-N-K** [comment]
Someone with deeper knowledge of the packages needs to look into this. I ran into the problem that org.eclipse.smarthome.core.thing.setup is not found. If I remove that from the archetype manifest, it complains about slf4j-api and an unkown type .jar.

**Comment by kaikreuzer** [comment]
fixed by https://github.com/eclipse/smarthome/pull/2942
