### ISSUE TITLE
default value of limitToOptions is unclear

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2844]
The [documentation](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-configuration-descriptions) says that the default value of the "limitToOptions" property is true in case it is not specified. The [code](https://github.com/eclipse/smarthome/blob/master/bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameter.java#L91) sets it to false, though.

Only one of both can be right - which one?

**Comment by maggu2810** [comment]
Hm, I don't care who wins, but it should be consistent in code and documentation.
Do you prefer true or false?

**Comment by maggu2810** [comment]
> Changing the code to match the documentation will be a breaking change

Hm, so let's change the documentation. The current behaviour has been this way the last month the same.

**Comment by cdjackson** [comment]
The original intention was that it should default to true and I think this was implemented and tested when I originally implemented this so I'm guessing there has been some recent changes to change this?.  The reason is that it avoided breaking earlier code where there were only options. 

If this changes please let eme know as this probably breaks things in aware where I assume the default is true and only add this parameter into the thing xml definitions if it's false.

**Comment by maggu2810** [comment]
Let's have a look at the history...

```sh
git blame bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameter.java | grep 'private boolean limitToOptions = false;'
```

```text
5a6e726c04 (Christoph Knauf 2015-11-30 17:25:41 +0100  91)     private boolean limitToOptions = false;
```

```text
commit 5a6e726c041fe78535da52bc12f747123ce4f8b8
tree af6ca66f8fbbaf54629ec75a94c2ce6be88a13ea
parent 107fc84f1239726b30880f1f9c85a358e2e31140
author Christoph Knauf <christoph.knauf@itemis.de> 1448900741 +0100
committer Christoph Knauf <christoph.knauf@itemis.de> 1449064548 +0100

    Bug 482684 - ConfigDescriptionParameter methods should not return null
    
    Changes:
    ConfigDescriptionParameter.java contains only boolean attributes (no
    Boolean Attributes anymore). Null safe conversion from Boolean to boolean in constructor
    
    Implemented ConfigDescriptionParameterBuilderTest.groovy to clarify usage of ConfigDescriptionParameterBuilder.java and ConfigDescriptionParameter.java
    
    Added default constructor to ConfigDescriptionParameter.java
    
    Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=482684
    
    Explicit initialization of boolean fields
    
    Signed-off-by: Christoph Knauf  <christoph.knauf@itemis.de>
```

The commit 5a6e726c041fe78535da52bc12f747123ce4f8b8 changes:
```diff
-    private boolean limitToOptions;
+    private boolean limitToOptions = false;
```

the default is false, so nothing has been changed by this commit.

So, let's have a look at the parent:

```sh
git blame 107fc84f1239726b30880f1f9c85a358e2e31140 -- bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameter.java | grep 'private boolean limitToOptions;'
```

```text
62ef11816a (Chris Jackson 2015-04-26 18:03:26 +0100  83)     private boolean limitToOptions;
```

```text
commit 62ef11816a1f1332a6c9c3f5f54771732a22c6bb
tree a70bce0aed5275a277d785d61bc90a2e88371f2c
parent 143ccc312f36e350b6e55b76b3733f5a629ce068
author Chris Jackson <chris@cd-jackson.com> 1430067806 +0100
committer Chris Jackson <chris@cd-jackson.com> 1431014694 +0100

    Add extra configuration attributes to ConfigDescriptionParameter
    Signed-off-by: Chris Jackson <chris@cd-jackson.com>
    
    Signed-off-by: Chris Jackson <chris@cd-jackson.com>
```

That commit introduced the limitToOptions member without a explicit initialitation.
So it has been initialized false from the beginning.

Or do I miss some detail here?

**Comment by cdjackson** [comment]
I can't check as I am in India. Maybe there was an error or maybe it is initialised in the builder. In any case I think it makes more sense to initialise to true - in most cases if you supply options you want the selection to be limited to these options.

**Comment by watou** [comment]
The common usage of a list of options is that the user should be able to choose only from the available options.  The exceptional case is that the user should be able to type in his or her choice, ignoring the list of available options.  So, regardless of history, `limitToOptions=true` is the sensible default.

**Comment by kaikreuzer** [comment]
I agree, it should be true as default and that's what Chris also originally expected.

The problem has been introduced with https://github.com/eclipse/smarthome/commit/5a6e726c041fe78535da52bc12f747123ce4f8b8 - before this change, the JSON simply did not contain ANY value for limitToOptions, so it was up to the UI to know the default (and I assume HABmin then uses "true). With that commit above, we are now always sending the value, but it is wrongly set to false as a default.

**Comment by watou** [comment]
So the doc is right, the implementation of it needs fixed, and any code that relied on the wrong default also needs to be fixed.  That's my opinion, anyway!

**Comment by maggu2810** [comment]
> The problem has been introduced with 5a6e726

Really, I assume it has been introduces by 62ef11816a1f1332a6c9c3f5f54771732a22c6bb

I agree with @cdjackson, @watou and @kaikreuzer that using options implies that you want to limit to that options and not using the provided options as a limit is the corner case.
I am also fine with changing the impl, but if my assumption about the commit ID is correct it has been used by implementations (if someone relies on it) since Apr 26, 2015 (or at least some days later the commit has been merged).

I no one complains about changing the implementation, let's do it.
