### ISSUE TITLE
Wrong average of Group:Number:AVG

### ISSUE THREAD

**Issue by DimitrisSar** [eclipse/smarthome#2847]
Maybe this is a bug...

The value of certain Group functions (MIN, MAX, AVG, SUM) is calculated incorrectly when using items with percentages.

Please see: https://community.openhab.org/t/wrong-average-of-group-number-avg-with-dpt-knx-5-001/20529

**Comment by kaikreuzer** [comment]
Could you paste a very short and simple example here that can be used to reproduce and analyze the issue?

**Comment by DimitrisSar** [comment]
Using openHAB 2.0 RC1 (with multiple KNX 1.x bound items).
Short example of the case to reproduce this issue:

2 defined items, having the following values for their state:
P11_J1 (Type=RollershutterItem, State=50, Label=P11_J1, Category=null, Groups=[Shutters])
P11_J2 (Type=RollershutterItem, State=100, Label=P11_J2, Category=null, Groups=[Shutters])

Are grouped in the "Shutters" Group.

Within the .items file, they are defined as follows:
Rollershutter   P11_J1          "P11_J1"                (Shutters)        {knx="2/0/0,2/0/1,2/3/0+<2/2/0"}
Rollershutter   P11_J2          "P11_J2"                (Shutters)        {knx="2/0/2,2/0/3,2/3/2+<2/2/2"}

When defining the Group within the .items file and using a function (AVG, MIN, MAX or SUM) the calculated value appears wrong.

For Average:
Group:Number:AVG        Shutters        "Avg. Rollershutters [%.2f %%]"

The value comes up in the sitemap as "0.75 %" instead of "75%" (the average of 2 items with values 100 % & 50%)

Similar problem exists with the MIN, MAX & SUM group functions.

**Comment by kaikreuzer** [comment]
You are transforming PercentTypes to a DecimalType here, so it is imho fully correct that the value of the group item is a value between 0-1.

What happens if you define the group to be of Rollershutter type as well? `Group:Rollershutter:AVG`?

**Comment by DimitrisSar** [comment]
It works fine then 👍 

Thank you Kai.   This was a miss-configuration, not an issue after all :)

**Comment by kaikreuzer** [comment]
Glad I could help :-)

**Comment by DimitrisSar** [comment]
Sorry for not covering also another case from another user...  I will follow up with the post below:

He is experiencing the same problem (Group average being displayed incorrectly) when using "Number" type of items.

Example:
```
Number RelHumidity_EG_Kind1  			"rel. Luftfeuchte [%.1f %%]" <humidity>   (gRelHumidityEG, EG_Kind1, RelHumidityEG) 		{ knx="5.001:12/3/0" }
Number RelHumidity_EG_Kind2  			"rel. Luftfeuchte [%.1f %%]" <humidity>   (gRelHumidityEG, EG_Kind2, RelHumidityEG) 		{ knx="5.001:12/3/1" }

```

have a state of 38 and 40 correspondigly and are displayed as "38 %" and "40 %" on his sitemap, while the Group:Number:AVG shows "0.4%" when using:

```
Group:Number:AVG		RelHumidityEG "Avg. Erdgeschoss rel. Luftfeuchte [%.1f %%]"		<humidity>	(gRelHumidityEG)
```

**Comment by kaikreuzer** [comment]
I cannot confirm, all is as expected:

```
openhab> smarthome:items
ItemAVG (Type=GroupItem, BaseType=NumberItem, Members=2, State=NULL, Label=null, Category=null)
Item1 (Type=NumberItem, State=NULL, Label=null, Category=null, Groups=[ItemAVG])
Item2 (Type=NumberItem, State=NULL, Label=null, Category=null, Groups=[ItemAVG])
openhab> smarthome:update Item1 38
Update has been sent successfully.
openhab> smarthome:update Item2 40
Update has been sent successfully.
openhab> smarthome:items
ItemAVG (Type=GroupItem, BaseType=NumberItem, Members=2, State=39, Label=null, Category=null)
Item1 (Type=NumberItem, State=38, Label=null, Category=null, Groups=[ItemAVG])
Item2 (Type=NumberItem, State=40, Label=null, Category=null, Groups=[ItemAVG])
```

**Comment by timjakobi** [comment]
Hi Kai,
see the output of karat console. I have knx:DPT9.001 temp items and knx:DPT5.001 humidity items. Both as Group:Number:AVG.
<img width="1280" alt="bildschirmfoto 2017-01-20 um 20 33 21" src="https://cloud.githubusercontent.com/assets/13568856/22162607/b55f565a-df4f-11e6-85c7-d5ba937e7928.png">
