### ISSUE TITLE
[PaperUI] items view does not update

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#2871]
When having http://localhost:8080/paperui/index.html#/configuration/items open and e.g. updating an item DSL (i.e. removing/adding items), the displayed items stay the same. A refresh of course fixes it, but I would have expected the same behavior as for things etc.

@aounhaider1 could you please have a look?

**Comment by aounhaider1** [comment]
The runtime is not sending any item update events when DSL is changed. Strangely, the event is sent when I update an item through rest endpoint.

**Comment by sjka** [comment]
Strange... I will check that.

**Comment by sjka** [comment]
funny. we hit a "TODO" in GenericItemProvider 😄 

I have created #2896 for the events. Could it be that they are still not processed properly by the PaperUI?

**Comment by kaikreuzer** [comment]
@sjka Is there still a problem in the Paper UI or is it working as expected with #2896?

**Comment by sjka** [comment]
No - the item events now are sent by the framework (& received by the paper UI) but the list does not update dynamically. @aounhaider1 is having a look.
