### ISSUE TITLE
Wrong Zodiac

### ISSUE THREAD

**Issue by michaeljoos72** [eclipse/smarthome#2875]
Hi

Today 20. January should be CAPRICORN=Steinbock (last day).
But Astro-Binding 2.00 (OH2) already shows AQUARIUS=Wassermann

It seems that we have a shift of one day

Michael

**Comment by kaikreuzer** [comment]
Please report this at https://github.com/openhab/openhab2-addons/issues, this is where the astro binding lives - thanks!
