### ISSUE TITLE
Log levels not kept after restart

### ISSUE THREAD

**Issue by rtvb** [eclipse/smarthome#2880]
If I set a specific log level (for a binding) and remove it after use, the log level is set again after a restart. I expected that it is kept default. I now have to explicitly set the level to `INFO` (or any default level) to remove it permanently.

1. Set log level, e.g. `log:set DEBUG org.openhab.binding.mqtt`
2. Use log level
3. Remove log level, e.g. `log:set DEFAULT org.openhab.binding.mqtt`
4. Show log levels with `log:list` ==> gone!
5. Restart openHAB and start console
6. Show log levels with `log:list` ==> back again!

```
Logger                                                      | Level
-------------------------------------------------------------------
ROOT                                                        | WARN
javax.jmdns                                                 | ERROR
org.apache.aries.spifly                                     | ERROR
org.apache.karaf.kar.internal.KarServiceImpl                | ERROR
org.eclipse.smarthome                                       | INFO
org.jupnp                                                   | ERROR
org.openhab                                                 | INFO
org.openhab.binding.mqtt                                    | DEBUG
org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper | ERROR
smarthome.event                                             | INFO
smarthome.event.InboxUpdatedEvent                           | ERROR
smarthome.event.ItemStateEvent                              | ERROR
smarthome.event.ThingStatusInfoEvent                        | ERROR
```

**Comment by watou** [comment]
Sounds a bit like what is described here:  https://issues.apache.org/jira/browse/KARAF-2381

> ...while log:set DEBUG is persisted the inverse log:set DEFAULT is not persisted. So after a restart I'll be surprised to realize that the logs are at DEBUG level.

**Comment by J-N-K** [comment]
I have seen that, too. Didn't notice it only happens with DEFAULT, maybe that's why I was not able to reproduce it.

**Comment by kaikreuzer** [comment]
Guys, this is the issue tracker for ESH, not for Karaf or the openHAB Distro.

**Comment by watou** [comment]
> this is the issue tracker for ESH, not for Karaf or the openHAB Distro.

Of course this is obvious!  Are you saying this issue should be opened in a different issue tracker.  If so, which do you suggest?

**Comment by kaikreuzer** [comment]
Well, Karaf or openHAB Distro, but it depends if there is at all a bug, I didn't read the discussion and explanations on the linked Karaf issue.
