### ISSUE TITLE
[BasicUI] Slider knob not showing in BasicUI on Microsoft Edge 

### ISSUE THREAD

**Issue by FusedHe3** [eclipse/smarthome#2882]
Hi everybody,

I know this isn't a major issue, but I noticed that the slider knob is missing when using the BasicUI in Microsoft Edge. This makes adjusting the slider a bit tricky.
**Edge:**
![snip_slider](https://cloud.githubusercontent.com/assets/25036470/22208950/09581e36-e185-11e6-9086-532c825785bc.png)
**IE:**
![snip_slider12](https://cloud.githubusercontent.com/assets/25036470/22209454/d047fe98-e186-11e6-9b47-054dac78873d.png)

Using the F12 DOM Explorer and comparing the CSS styling between Edge and Internet Explorer, I discovered that the height of `.mdl-slider.is-upgraded `is set to 2px in Edge and due to an override from `_:-ms-input-placeholder, :root .mdl-slider.mdl-slider.is-upgraded` it is set to 32px in IE. As this override doesn't happen in Edge, the height stays at 2px and the knob isn't showing.

**Edge:**
![snip_slider2](https://cloud.githubusercontent.com/assets/25036470/22208958/130dc250-e185-11e6-8898-0420ef0b0612.png)

**IE:**
![snip_slider23](https://cloud.githubusercontent.com/assets/25036470/22208962/1692ab84-e185-11e6-85df-6a4c2830b981.png)
![snip_slider4](https://cloud.githubusercontent.com/assets/25036470/22208975/1f652c14-e185-11e6-87b8-46db9a4f2b58.png)

Setting the height to 32px in Edge fixes the problem.

I don't know if this is an issue inherent to Google Material Design or if there is a simple fix. But it would be nice to see the slider working in Edge to, as I use it as my primary browser on all my devices.

Thanks!

**Comment by kaikreuzer** [comment]
@resetnow, could you please have a look?

**Comment by resetnow** [comment]
It looks like this particular problem is present upstream — I tried updating MDL to a latest version and it looked even worse. Also, even with the width property applied the knob is off by 10-20 pixels to the left. I'll try to fix it upstream and then backport the fix here — I assume in this case we won't have to deal with the legal approval process.

**Comment by resetnow** [comment]
Relevant issue: https://github.com/google/material-design-lite/issues/1625

**Comment by FusedHe3** [comment]
Great, thanks!

**Comment by resetnow** [comment]
It seems Google's MDL is in limited support mode — it may not be possible to push a full fix there. So I have opened #2932 with a CSS fix for sliders, it doesn't fix them completely but at least the knob is visible and can be moved.

**Comment by FusedHe3** [comment]
Thanks @resetnow! At least it's working now :D
