### ISSUE TITLE
[Paper UI] Widgets on Control UI change position on every browser reload

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2884]
On every browser reload (F5), the widgets are at a different position (using Safari), which is pretty annoying:

![screen shot 2017-01-23 at 16 40 29](https://cloud.githubusercontent.com/assets/3244965/22210643/cffe5f28-e18a-11e6-9fb7-fb936ff25e32.png)
![screen shot 2017-01-23 at 16 40 35](https://cloud.githubusercontent.com/assets/3244965/22210644/d00495fa-e18a-11e6-8d03-99cf73506926.png)
![screen shot 2017-01-23 at 16 40 41](https://cloud.githubusercontent.com/assets/3244965/22210646/d004f342-e18a-11e6-9127-5f47a7aeb647.png)
![screen shot 2017-01-23 at 16 40 51](https://cloud.githubusercontent.com/assets/3244965/22210645/d004ad88-e18a-11e6-84c8-b87148d1d72f.png)

In any case (also on other browsers), I do not really like the layout algorithm - it often leaves pretty big gaps and it all rather looks shuffled around instead of being nicely stacked.
@aounhaider1 Are there any possibilities to improve this?

**Comment by MHerbst** [comment]
> In any case (also on other browsers), I do not really like the layout algorithm - it often leaves pretty big gaps and it all rather looks shuffled around instead of being nicely stacked.

There are some Javascript libraries that can layout boxes of different sizes gapless ("masonry layout"). The most famous is probably Isotope. But it is licenses under GPLv3. 
I found another one that is licenses under MIT license: http://mcpants.github.io/jquery.shapeshift/

**Comment by kubawolanin** [comment]
@MHerbst you don't actually need a library nowadays. In todays world you can use flexbox-based layout sufficiently. Take a look at [this example](https://medium.com/@_jh3y/how-to-pure-css-masonry-layouts-a8ede07ba31a#.6zq9ukteu).

**Comment by aounhaider1** [comment]
@MHerbst It was indeed a bug. We are already using masonry by Desandro so we don't need another library for that.
@kubawolanin Essentially we can, but I don't see any reason we should reinvent the wheel when we already have much cleaner solution available.

**Comment by kubawolanin** [comment]
@aounhaider1 how utilizing a heavy library for a simple task like this is a cleaner solution? Flexbox allows you to accomplish this with just a few lines of CSS. I can help!

Reinventing the wheel would be writing flexbox spec by yourself :-)

Cheers

**Comment by MHerbst** [comment]
> We are already using masonry by Desandro so we don't need another library for that.

:-) I'd better have looked into the source code before ...

> Flexbox allows you to accomplish this with just a few lines of CSS. I can help!

Flexbox has lots of advantage, but there are probably quite a few browser versions in use that do not support it fully.
