### ISSUE TITLE
Not all bundles loaded on first start 

### ISSUE THREAD

**Issue by juelicher** [eclipse/smarthome#2886]
Hi, 

by mistake I reported this issue in the openhab1-addons repository, where it was closed. As I still think, that the behavior, as described below, is a bug of the openHAB core I assume, that this is the right repository to report it. 

I performed the following steps:

Started a clean install of OH2, without modifying any of the configuration files
-> Everything OK

Stopped OH2 and copied my config files and restarted it
This resulted in the following warning ragarding the installation of the transformation services:

23:20:15.109 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-transformation-xpath, openhab-transformation-map, openhab-transformation-javascript, openhab-transformation-xslt, openhab-transformation-regex, openhab-transformation-exec, openhab-transformation-scale, openhab-transformation-jsonpath': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-exec1; type=karaf.feature; version="[1.9.0.SNAPSHOT,1.9.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-exec1)(type=karaf.feature)(version>=1.9.0.SNAPSHOT)(version<=1.9.0.SNAPSHOT))"

Additionally openHAB tries to uninstall some bundles, which fails :

`23:20:19.288 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed uninstalling 'openhab-ui-cometvisu': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-exec1; type=karaf.feature; version="[1.9.0.SNAPSHOT,1.9.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-exec1)(type=karaf.feature)(version>=1.9.0.SNAPSHOT)(version<=1.9.0.SNAPSHOT))"

23:20:23.487 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed uninstalling 'openhab-misc-homekit': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-exec1; type=karaf.feature; version="[1.9.0.SNAPSHOT,1.9.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-exec1)(type=karaf.feature)(version>=1.9.0.SNAPSHOT)(version<=1.9.0.SNAPSHOT))"
`

Stopped and restarted OH2 without changing the configuration:
Only a warning regarding regex transformation:
00:02:31.051 [WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type REGEX 00:02:31.051 [WARN ] [ab.binding.exec.internal.ExecBinding] - couldn't transform response because transformationService of type 'REGEX' is unavailable

Stopped and restarted OH2 without changing the configuration:
-> No more warnings, works as expected.
I have the following configuration in addons.cfg (all other entries are commented out). As the transformation services are part of the expert package they should have been installed on the first start, additionally OH2 should not have tried to deinstall other bundles:

`package = expert

remote = true

legacy = true

experimental = true
binding = astro,caldav-command1,denon1,exec1,fritzboxtr0641,http1,hue,knx1,network,snmp1,tcp1,weather1,wol1

ui = basic, classic, cometvisu, habmin, habpanel, paper

persistence =jdbc-sqlite,mapdb,rrd4j

action = mail, prowl

misc = homekit, restdocs`

As it worked after some retries this might have been a temporary problem with a server or OH2 needed more time to install all addons?!

**Comment by maggu2810** [comment]
I don't see any relationship to the Eclipse SmartHome framework, it seems to be related to openHAB only.

If you don't know with openHAB issue tracker is the correct one (distro, core, ...) -- or perhaps all the time -- you should first try to find some help in the openHAB Community: https://community.openhab.org/

**Comment by juelicher** [comment]
Just wanted to help make this software better... 

I assumed, that loading the bundles is part of the eclipse smarthome part, but probably I don't understand the dependencies of the architecture.

**Comment by maggu2810** [comment]
We are grateful for any help! 😉 
It could be difficult to find the correct tracker to report an issue.

Eclipse SmartHome is the core framework, it consists of different OSGi bundles that implement a lot of functionality.
But ESH is not a product or a solution itself.
It is also not something that implements a Karaf based runtime etc.

openHAB is a SmartHome product that is based on ESH and is using the Karaf container.
So, I assume the openHAB distro would be the correct place.
Just to note, that there the OH project is split into different repos (and so trackers) e.g. oh1 addons, oh2 addons, core bundles of oh2, distribution, linux packaging, documentation, ...

Your comment shows that you are using 1.9.0-SNAPSHOT of the openHAB bundles.
There is already the 2.0.0 one released, so perhaps you should test this one.

To keep the different openHAB issue trackers small it is always a good thing to discuss the problem in the openHAB community first, perhaps it is already solved, someone could help you to find the correct OH tracker etc.

So, thanks for your report, but I still think it has been the wrong project.
Perhaps my very short explanation helps you to understand the stuff better.
