### ISSUE TITLE
[sonos] Add support for clear player queue

### ISSUE THREAD

**Issue by torstesu** [eclipse/smarthome#2894]
The current sonos binding does not provide a channel to clear the current queue of a player. The playlist channel only allows to add tracks from a playlist to a player's queue. Thus, when using the playlist channel multiple times on the same player with different playlists, the queue will represent a mix of the playlists added.

In many use cases, a user would prefer to clear the queue so to only play tracks from the selected playlist.

My proposal is to implement a new channel to enable the user to clear the queue of a player. Keeping the playlist and the proposed clearqueu channel separated, will allow the user to choose the behaviour when adding tracks to the queue.

**Comment by lolodomo** [comment]
An additional channel is an option.
Another option would be to accept in the existing playlist channel either `<playlist name>` or something like `CLEAR#<playlist name>`. If the channel command starts with "CLEAR#', the binding will replace the queue content by the playlist content.

**Comment by kaikreuzer** [comment]
> something like `CLEAR#<playlist name>`.

I would strongly suggest not to introduce special syntactical commands within a command value.

**Comment by lolodomo** [comment]
To avoid source code conflicts, I will implement this enhancement (so with a new switch channel) as soon as my pending Sonos PR is merged.
