### ISSUE TITLE
Hue Binding: Offline Hue lights not reported as such

### ISSUE THREAD

**Issue by obartelt** [eclipse/smarthome#2909]
When I switch a Hue light off manually (cutting power by using a wall switch), I get an event in the Karaf console:

[me.event.ThingStatusInfoChangedEvent] - 'hue:0100:001788253ecd:8' changed from ONLINE to OFFLINE: Bridge reports light as not reachable

But the light is still shown as "on" in OpenHAB (brightness as it was set (e.g. 100%), and the :switch channel set to ON).

Is that a bug? How can I get the real state of the light in OpenHAB (i.e. "off"/0%)?

**Comment by kaikreuzer** [comment]
No bug, see https://github.com/openhab/openhab2-addons/issues/1776#issuecomment-275699086.
