### ISSUE TITLE
Better use standard URL encoding in Yahoo weather binding

### ISSUE THREAD

**Issue by janssk1** [eclipse/smarthome#2912]
I wanted to play around using a simple binding, but too my surprise the bundled yahoo weather binding is not working on OpenHub2

The thing stays offline and the logs show 'The location for WOEID 966591 could not be found', even if the location is good. 

It seems the binding generates incorrect HTTP requests towards yahoo

https://query.yahooapis.com/v1/public/yql?format=json&q=SELECT%20location%20FROM%20weather.forecast%20WHERE%20woeid%20=966591

The last = should be URL encoded, using %3D

PS: Better use standard URL encoding (java/net/URLEncoder) instead of manual character replacements

**Comment by MHerbst** [comment]
I am not sure whether the URL encoding causes the problem. I have tried it with your WOEID and I also got the message that it is wrong. But after some minutes correct values were retrieved. 
Maybe it is just the wrong message. But anyway there is a problem (dont't know whether it is in the binding or on Yahoo's side).

**Comment by maggu2810** [comment]
> Better use standard URL encoding (java/net/URLEncoder) instead of manual character replacements

Can you create a PR for that?
