### ISSUE TITLE
MP3 AudioFormat used by URLAudioStream has an incorrect container

### ISSUE THREAD

**Issue by syphr42** [eclipse/smarthome#2913]
AudioFormat.MP3 is defined as follows:

```
public static AudioFormat MP3 = new AudioFormat(AudioFormat.CONTAINER_NONE, AudioFormat.CODEC_MP3, null, null, null,
            null);
```

While URLAudioStream creates an AudioFormat defined as follows:

```
this.audioFormat = new AudioFormat(AudioFormat.CODEC_MP3, AudioFormat.CODEC_MP3, false, 16, null, null);
```

Based on the JavaDoc for AudioFormat.CONTAINER_NONE, I believe the bug is in URLAudioStream.

```
    /**
     * {@link AudioCodec} encoded data without any container header or footer,
     * e.g. MP3 is a non-container format
     */
    public static final String CONTAINER_NONE = "NONE";
```

The container on URLAudioStream's AudioFormat should be AudioFormat.CONTAINER_NONE. Due to this, AudioFormat::isCompatible(AudioFormat) does not work correctly for URLAudioStream when testing for MP3.

The fix would be this inside org.eclipse.smarthome.core.audio.URLAudioStream:

```
this.audioFormat = new AudioFormat(AudioFormat.CONTAINER_NONE, AudioFormat.CODEC_MP3, false, 16, null, null);
```

**Comment by lolodomo** [comment]
What is the consequence of this issue for the user ?

**Comment by syphr42** [comment]
I found this while testing out a pull request to make the Squeezebox player an AudioSink (https://github.com/openhab/openhab2-addons/pull/1684). I would like to use a web-based TTS service without caching files on the hard disk since Squeezebox can simply stream the URL. However, Squeezebox needs to test for MP3 or WAV format compatibility and so the URLAudioStream is failing the compatibility test due to this bug.

While a hack could be added to the Squeezebox code to make it work, I was hoping to get this fixed at the source. I'm putting a pull request together now.

**Comment by mhilbush** [comment]
@syphr42,

 Glad to see you're testing the squeezebox PR.  Let me know if you run into any issues; there's a thread [here](https://community.openhab.org/t/squeezebox-speak-on-oh2/20843) on the forum where it has been discussed.  Or, you can post directly on the PR.

How familiar are you with the LMS?  I've run into some trouble getting pause to work properly after the notification.  The scenario is when a player is paused.  After playing the notification, when restoring the player state, sending a pause to the player is not working as expected.  I put a delay (i.e. hack) in the code for now until I can sort out the root cause...

**Comment by lolodomo** [comment]
Any chance that it could explain why I have difficulty with chromecast binding and play/say console commands?

**Comment by syphr42** [comment]
@lolodomo Maybe. I haven't tried the Chromecast binding, so I can't say for sure. If you check the code and it compares a URLAudioStream's AudioFormat to AudioFormat.MP3 for compatibility then you are probably hitting this issue.

@mhilbush I posted some information about what I was doing on your PR. I'm not very familiar with the inner workings of LMS, but I'll poke around a bit and see what I can find. Let's keep further communication about the PR over there to avoid cluttering up this issue.

**Comment by lolodomo** [comment]
@syphr42 : what do you think about this line: https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/handler/ChromecastHandler.java#L289

**Comment by lolodomo** [comment]
For my problem, the reason is probably elsewhere as a FileAudioStreal is used, not a URLAudioStream .
