### ISSUE TITLE
[Paper UI] Multiple inbox entries shown for the same discovery result

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2918]
There are situations, where the Paper UI inbox does not correctly update itself and rather adds already known results another time. This is what I saw after leaving the inbox page open for a while:

<img width="260" alt="972c0e8a-d9a5-11e6-9115-edfb3d964078" src="https://cloud.githubusercontent.com/assets/3244965/22414942/edc279f2-e6c3-11e6-91ca-b31670db8d74.png">

See also https://github.com/openhab/openhab2-addons/issues/1667.

**Comment by sjka** [comment]
Repeating my comment from openhab/openhab2-addons#1667:

> So, while this obviously is annoying and we should think about if and how this behavior in the jUPnP library can be "fixed", the ESH core is behaving correctly. On the other hand, the PaperUI apparently can get confused by so many events in a row. We should have a look there too.

I see two action items:

* **PaperUI**: Check what can be done in order to prevent such event race conditions (@aounhaider1 any suggestions?)
* **jUPnP**: Check if such alternating discoveries can be prevented (jupnp/jupnp#73)
