### ISSUE TITLE
Automation: Rules cannot be distinguished by scope

### ISSUE THREAD

**Issue by ViToni** [eclipse/smarthome#2921]
Rules can be created in different scopes.
Uses cases might be
* system rules
* rules created by an installing party
* rules created by the user
* rules created (automatically) by a remote UI

Currently there is no means to distinguish these rules and to find rules for a given scope in an easy way.

A solution might be to add a `Scope` property to Rule.
Changes needed would be
* `Scope` property for Rule
* Change the REST API to enable transfer of `Scope` for Rule
* Change the REST API to enable search by `Scope` for Rule
* Changes to PaperUI to show (not modify) this information

A different approach might be to a reuse the existing tags property.
There is already a search functionality for Rules by tags.
This approach has the downside that tags are user visible and would be editable by the user.

**Comment by danchom** [comment]
There is visibility property to differentiate rules. The scope property duplicate purpose of the visibility.

**Comment by danchom** [comment]
Also you can use tags for this purpose.

**Comment by ViToni** [comment]
Thae basic idea is, that eg. if there is some kind of alarm system, the setup for the system could create rules with the scope `Alarm`.
If the setup is run again it could check for the rules with scope `Alarm` and change or delete & recreate them if necessary. 

All `Rules` created by the user could have the scope `User`.

Or if the user would want to uses some special remote UI, this remote Ui could manage its own rules in an easy way.

The scope is something which could be user visisble but should not necessarily be user editable.
Tags are in my understanding a means for the user to manage/categorize his rules, therefore editable by the user.
The scope is intended for  remote UIs, special systems, etc.

The aforementioned `Alarm` system example could use tags and scope together, eg:
* Tags=[Security, Indoor, Living room, Windows]
Scope= [InstallingParty1]
* Tags=[Security, Indoor, Living room, Smoke Detector],
Scope= [HealthApp3]
* Tags=[Security, Indoor, Kitchen, Windows]
Scope= [InstallingParty1]
* Tags=[Security, Indoor, Kitchen, Smoke Detector]
Scope= [HealthApp3]
* Tags=[Security, Garden, Camera]
Scope= [SecurityProvider1]
* Tags=[Security, Garden, Motion Detector]
Scope= [SecurityProvider1]
* Tags=[Security, Indoor, Motion Detector]
Scope= [User]
* Tags=[Security, Garden, Motion Detector]
Scope= [User]

The scope links the originator/creator to the rule.

**Comment by danchom** [comment]
@ViToni  thanks for explanation.
>If the setup is run again it could check for the rules with scope Alarm and change or delete & recreate them if necessary.

This is not possible for rules created by our importers. We have two types of rules:
- editable - these are rules added through the RuleRegistry interface and stored in ManagedRuleProvider. Our importers (BundleResourceImiporter and FileResoureImporter) uses RuleRegistry and imports Rules instead of provides them.  The main reason is to prevent loosing user changes on system restart. If you want to reload a rule (with same uid), it must be manually deleted first.
- not editable - they can be provided by custom providers and they are loading on each system restart. The user can only enable/disable them.
>The scope is something which could be user visisble but should not necessarily be user editable.

We are providing rule's visibility property for this, but it has some predefined values. 

>Or if the user would want to uses some special remote UI, this remote Ui could manage its own rules in an easy way.

This can be done by tags.

>Tags are in my understanding a means for the user to manage/categorize his rules, therefore editable by the user.

Right, but you can have some system tags

> The aforementioned Alarm system example could use tags and scope together

You can use tags and visibility together

> The scope links the originator/creator to the rule.

Visibility links the originator/creator to the rule.

Btw in the past rules had scope property, but we have decided to remove it because it is a special case of tags. The tags are more general because you have opportunity to associate a rule with more then one "scopes" tags.

**Comment by ViToni** [comment]
>If the setup is run again it could check for the rules with scope Alarm and change or delete & recreate them if necessary.

Maybe my wording was misleading. By setup I mean some remote UI (eg. a phone app) being called again to setup the rules for its (the app's) use case.

>> The scope is something which could be user visisble but should not necessarily be user editable.

> We are providing rule's visibility property for this, but it has some predefined values.

The scope is _NOT_ used to change the visibility of a rule. It is the value of the scope Property itself which might or might not be shown to the user (maybe showing it at least in the PaperUI but making it readonly would be a good start, because it is not designed to be changed. The scope should be immutable from the user perspective). (All user created rules could have implicitly the scope "user" )
It is _NOT_ meant to hide rules or change their visibility

>> Tags are in my understanding a means for the user to manage/categorize his rules, therefore editable by the user.

=> User editable

>> The scope is intended for remote UIs, special systems, etc.

=> Scope is set at creation time

>>The scope links the originator/creator to the rule.

>Visibility links the originator/creator to the rule.

I fail to see how the Visibilty enum (VISIBLE, HIDDEN, EXPERT) could help here. 
Should a remote UI search for a given tag _and_ Visibilty=HIDDEN or Visibilty=EXPERT?
How would the user delete/disable hidden rules if he does not want them anymore?

**Comment by kaikreuzer** [comment]
@danchom I also do not see how Visibility could help here. But I remember that we once discussed that the rule "uid" is supposed to be a "real" uid, i.e. it should be built from several segments, one being a kind of namespace prefix, right?

@ViToni Would such a prefix address your requirements? We could have "system", "user", "appXYZ" prefixes and this would at the same time make sure that the UIDs from different rule providers are unique and do not clash. We would need some "pattern search" functionality for that, so that it is easy to filter rules for certain prefixes in their UID.

**Comment by kaikreuzer** [comment]
This feels a bit like a misuse of tags to me. I'd really like to see them as semantical information in the light of https://github.com/eclipse/smarthome/issues/1093; using them for filtering for "sources"/"owners" does not seem to be right.

> @Kai the problem with prefixes is there isn't a useful way to filter rule base on part of uids.

Correct, but we could offer some smarter search options, like checking for prefixes and/or substrings on uids.

**Comment by ViToni** [comment]
I would like to explain the basic idea a bit more:
  - Visibilty of `Rule`s
My personal point of view i, that rules should not be hidden from the user. The `Scope` property is in no way meant to hide `Rule`s.
Rules should be visible to the user otherwise he might not understand what's happening in his environment, because an invisible rule which activates an action is "non-existent" for him.

  - Visibility of the `Scope` property
This is a desgin decision for the UI, not directly related to the capability to have a scope.
Again my personal point of view is to show this property to the user, without making it editable (this still could be done at a later point in time). This way the user knows where a rule originated from but cannot change this property (which might break things depending on  a certain `scope`) 

  - The `Scope` property itself
After reading #1093 I would like even more to have such a sematic property to be able to distinguish who/what created the rule.
A similiar concept is used in the ProSyst Home Automation Manager API:
https://dz.prosyst.com/pdoc/mBS_SH_SDK_7.4.1/modules/automationengine/api/com/prosyst/mbs/services/ham/Rule.html
The HAM-API is using something called application ID which is even deeper integrated into the API because it is a basic property of HAObject:
https://dz.prosyst.com/pdoc/mBS_SH_SDK_7.4.1/modules/automationengine/api/com/prosyst/mbs/services/ham/HAObject.html

It seems to me as if the application ID and the `Scope` property are different names for the same concept.
The idea to name it `Scope` was to have something more general (not only related to applications only).

@danchom Would you prefer to change the name from `Scope` to something diffferent to be more similar to the ProSyst API?

**Comment by danchom** [comment]
Hi ViToni, 
I'm agree with you that the rules should be always visible. 
The application id was introduce in HAM to separate automation objects and rules between different applications, moreover it introduce security concept where the resources (rules and automation objects) of one application can be access only when you have permissions for that. The HAM has a different architecture which is not applied in new Automation module.  
In the beginning of Automation module architecture we have a scopeId as part of rule definition which is close to your concept, but we have rejected it because the scopeId can't be used for security concept and it is corner case of tags. 
You can see here:
https://github.com/eclipse/smarthome/pull/1458
https://github.com/eclipse/smarthome/commit/c8ed2e79020082f1297f9dd4d63c5a774959fb10

**Comment by kaikreuzer** [comment]
@ViToni I'd again like to point to my suggestion in https://github.com/eclipse/smarthome/issues/2921#issuecomment-277993520 - I didn't yet see any response to that and as far as I can see, it would address all requirements that you have mentioned here.

**Comment by ViToni** [comment]
@kaikreuzer I like this approach. Your suggestion has the benefit that there is no additional property which needs to be persisted.
The implementation can be changed to scan for a prefix within the UID / set a prefix to the UID. 

@danchom @kaikreuzer 
Is this approach fine for all?

**Comment by danchom** [comment]
This approach is fine for me if it does not do breakable changes in API. I mean the UID of rule should stay String which can contain segments. We can add pattern search" functionality  method in RuleRegistry.
But IMHO this functionality duplicates tags and even more it is a corner case of tags. I can't  see the difference. Both can mark group of rules as (system, user, appXYZ), both can be editable from the user, both will defines some pattern search, both does not define any security restrictions. 
The difference is just that the if a rule belongs to two scopes you can not do this with ruleUID segments.
May be I'm wrong but I don't see any advantages of this approach.
@kaikreuzer what do you think?

**Comment by kaikreuzer** [comment]
@danchom See my https://github.com/eclipse/smarthome/issues/2921#issuecomment-279754689 regarding tags. So no, for me this is no duplication (and besides the argument given there, the tags are something that is under the control of the user, while the scope/UID is under control of the system/app).

**Comment by danchom** [comment]
@kaikreuzer semantically you are right, but the user can change the uid of rule as easy as to add a new tag.
OK what is the propolsal?
The uid could be in form of "xxx:yyy:zzz" and to add a method:
Collection<Rule> getAll(String "patternUID");
The pattern has to be regex or something simple?

**Comment by kaikreuzer** [comment]
> but the user can change the uid of rule as easy as to add a new tag.

I'd think that no "normal" end user UI will allow the user to define or modify the rule UID.

> The uid could be in form of "xxx:yyy:zzz"

Imho a "prefix:id", would suffice.

> Collection getAll(String "patternUID");

I wonder if we should directly go for something more generic like `getAll(FilterCriteria filter)`, where we could add all possible criterias to FIlterCriteria (a new class, not the existing one) - you might want to filter for a prefix, certain tags and and current status at the same time. Introducing all kinds of methods for these different combinations can become ugly... I see that for the item registry we e.g. already have a `getItemsByTagAndType` method - imho not a really good way to deal with it. Such a new filter method could possibly even be introduced on the Registry interface itself.

**Comment by danchom** [comment]
Usually when we want to filter to more then one property we are using LDAP expression. 
What do you think to have  getAll(String ldapFilter).  For example:  getAll("('&(uid=abc)(tag=tag1)"); This gives possibility to evaluate  arbitrary logic expression over the predefined fields.

**Comment by kaikreuzer** [comment]
Imho LDAP filters are the worst possible syntax anybody could come up with. If we want to really allow "arbitrary logic expression", we could add such a method (`getAllByLDAPFilter`) optionally. But we should definitely have an easier mechanism for standard queries.

**Comment by ViToni** [comment]
I would second that. Using `getAll(FilterCriteria filter)` as proposed in https://github.com/eclipse/smarthome/issues/2921#issuecomment-285375056 seems to be a more versatile approach. If anyone wants to use LDAP-like search expressions, he can implement a FilterCriteria with this functionality.
Is the usage of a String UID set? (I've seen UID classes (Things-related)). This might be a chance to harmonize UID all over the places.

If the `FilterCriteria` approach is agreed on, I would implement that.
If  harmonizing UID classes is an option, I would  implement it, too (but as a different issue to not mix things up).

@danchom Is the approach using `FilterCriteria` fine for you? 
(As I understood using a prefix is already agreed on.)

**Comment by danchom** [comment]
Ok, I'm agree with the FilterCriteria approach. You mean filter criteria will be an interface and a different impl on this interfaces can be applied to the getAll().  I'm not sure if we have to provide some default impl. of it. There are a lot of different criteria and may be we have to leave this to the user.

>Is the usage of a String UID set? 

Yes we have set that when design the Automation API and this is a breakable change. 
Also I have following concerns about the UID class:
1) It is part of the thing package
2) I don't see any advantage of its usage. It just split the text, but for the automation purposes it not needed. Moreover we have to converted back to single string and used the connected parts  as uid in automation engine.     

>As I understood using a prefix is already agreed on.

Yes the uid is a String and it can have any prefix. You can composite rule's uid as you want.
When you want to get part of available rules you have to impl FilterCriteria which will define the  scope of rules you are interested in. I think this approach is versatile.

**Comment by ViToni** [comment]
> Ok, I'm agree with the FilterCriteria approach. 

Great.
> You mean filter criteria will be an interface and a different impl on this interfaces can be applied to the getAll(). 

Exactly. 
> I'm not sure if we have to provide some default impl. of it. There are a lot of different criteria and may be we have to leave this to the user.

I would provide a simple implementation so that it can be used within the REST API to search for tags and scope (both are missing at the moment).

**Comment by ViToni** [comment]
Please review  the PR:
https://github.com/eclipse/smarthome/pull/3180

**Comment by ViToni** [comment]
Will be resolved  by PR https://github.com/eclipse/smarthome/pull/3180.
