### ISSUE TITLE
[Paper UI] Optionally present extensions in a card layout for easy browsing

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2923]
Currently, the Paper UI shows extensions as a flat list (sorted by category).

This is a good solution for "self-explaining" extensions, such as bindings, where the label of the extension almost says it all.

Once we add rule templates and similar things as extensions, we should imho think of better ways of presenting them - the user won't search for a specific label, but rather do "window shopping", i.e. browsing through the catalog to see what might be interesting for him. With https://github.com/eclipse/smarthome/issues/2922, the extensions can provide more data to present them nicely. To make use of it, I would suggest a card layout similar to the "Control UI" and the user should be able to toggle between list and card layout.

**Comment by sjka** [comment]
I have created #2928 for enhancing the Extension class, which can be used in order to implement this here.  When implementing the card layout, please give feedback in #2928 in case something does not work out as expected from a UI's perspective.
