### ISSUE TITLE
Implement ExtensionService for Eclipse IoT Marketplace

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#2924]
The Eclipse Foundation is preparing an [IoT Marketplace](https://bugs.eclipse.org/bugs/show_bug.cgi?id=506792), which can host extensions specifically for ESH.
For this, we should have an ExtensionService implementation that can sync the content of the Marketplace and provide installation/uninstallation functionality.

Some remarks:
- The service should be configurable to allow filtering of the Marketplace content (e.g. regarding license (e.g. only open-source), quality level (only stable, no betas), etc.)
- https://github.com/eclipse/smarthome/issues/2922, https://github.com/eclipse/smarthome/issues/2920 and #2923 must be in place for it as well
- For the start, I think it is ok to sync the full (raw) content from the Marketplace (configurable, default e.g. once a day).
- If the content becomes too much for the Paper UI, a first useful measure will be to use pagination on the REST API - but this can be a later step.

**Comment by cdjackson** [comment]
Will this allow multiple binding versions to be incorporated? Eg can we have a stable, nightly and bleeding edge version so users can decide? 

Below you say 'no betas' - I'm not sure if this means that you would only allow stable then?  If the IOT marketplace can support multiple versions then I think this would solve the issue that many people are asking on the OH forum about running some snapshot bindings with stable runtime.

**Comment by kaikreuzer** [comment]
> Will this allow multiple binding versions to be incorporated? Eg can we have a stable, nightly and bleeding edge version so users can decide?

Yes.

> Below you say 'no betas' - I'm not sure if this means that you would only allow stable then?

This was just an example. What I wanted to say with that is that it should be fully up to the solution to decide, which content from the Marketplace should be made available.

**Comment by cdjackson** [comment]
Great - I think this would be a very welcome addition.

**Comment by kgoderis** [comment]
+1

**Comment by lolodomo** [comment]
To be closed ?
