### ISSUE TITLE
Configuration folder 'conf\services' does not exist

### ISSUE THREAD

**Issue by amarpulli544** [eclipse/smarthome#2947]
Hello,

I am trying to access eclipse smart home. I successfully code complied in Eclipse Smart Home IDE without any errors. But unable to access paper ui. What I should  do to access paper ui . Here is my log file, in log file marked some files these files couldn't find in a project.

![upld](https://cloud.githubusercontent.com/assets/16384828/22505502/d8261574-e8a1-11e6-849e-b2fde4a433fd.png)

Thanks
Amar.

**Comment by kaikreuzer** [comment]
The message is not related to the Paper UI at all.
To develop the Paper UI in the IDE, please see https://www.eclipse.org/smarthome/documentation/development/notes.html#paperui-development-jshtml.
In general, please use the forum at https://www.eclipse.org/forums/index.php/f/271/ for support questions, thanks!
