### ISSUE TITLE
Configuration model 'logging.persist' has errors

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#2954]
Using the standard Eclipse SmartHome launch Runtime shows that warning:
```text
21:56:59.672 WARN  o.e.s.m.c.i.ModelRepositoryImpl[:92] - Configuration model 'logging.persist' has errors, therefore ignoring it: [15,1]: no viable alternative at input '}'
```

Is the logging configuration `logging.persist` really corrupt?
Can you show me the error?

**Comment by kaikreuzer** [comment]
Well, use the Designer and you will see that it is indeed an error:

<img width="829" alt="screen shot 2017-02-02 at 10 57 00" src="https://cloud.githubusercontent.com/assets/3244965/22544759/6b0eda08-e936-11e6-8131-e06585c165c5.png">

There is a semicolon missing at the line end, this is the corrected version:

<img width="819" alt="screen shot 2017-02-02 at 10 58 02" src="https://cloud.githubusercontent.com/assets/3244965/22544793/8a18bacc-e936-11e6-8760-1d9006d9dfa3.png">

BUT: As we do not have any logging persistence service in ESH, I wonder whether we should completely remove this file?

**Comment by maggu2810** [comment]
I am fine with removing that file.
Using the Designer? I should do it :wink:

**Comment by maggu2810** [comment]
If there is no file in that directory, it will not be part of the Git repo (no empty directories for Git).

**Comment by kaikreuzer** [comment]
We can also fix the file, so that we at least have an example of how they should look like.
Btw, maybe we should continue on https://github.com/eclipse/smarthome/pull/2081, so that we at least have ONE persistence service available in ESH for such things :-)

**Comment by maggu2810** [comment]
> Btw, maybe we should continue on #2081, so that we at least have ONE persistence service available in ESH for such things :-)

If we ever know how to handle an invalidated value e.g. if a binding knows that the current value is not correct anymore but does not know another one (https://github.com/eclipse/smarthome/pull/2081#issuecomment-260286090) I will update the PR.
