### ISSUE TITLE
[Basic UI] - Live Update doesn't work except on IE

### ISSUE THREAD

**Issue by guyyakobovitch** [eclipse/smarthome#2956]
test.items:
```
Switch Test_Switch
Number Test_Number
```

test.sitemap:
```
sitemap test label="test sitemap" {
	Frame {
		Switch item=Test_Switch
		Setpoint item=Test_Number
	}
}
```

test.rules:
```
rule "test rule"
when Time cron "*/3 * * * * ?" then
	if (Test_Switch.state == OFF) {
		postUpdate(Test_Switch,ON)
		postUpdate(Test_Number,1)

	}
	else {
		postUpdate(Test_Switch,OFF)
		postUpdate(Test_Number,2)
	}
end

```

The expected behavior of switch toggling is working only on IE (no SSE?). On Chrome & Firefox I have to refresh the page to see changes.
When I made dashboard with those items on HABPanel, it worked perfectly.

Tried it on two machines, two different installations, same behavior.

EDIT: Thing I found later is that it does work few minutes after creating the sitemap, but then it stops for good. Refreshing doesn't help (of course when refershing the state changes, but no live update). 

Environment:
Ubuntu 16.04 x64
OpenHAB 2.0.0-1 (as package from stable repository)

**Comment by guyyakobovitch** [comment]
Should I post this issue to another repository?

**Comment by maggu2810** [comment]
I think the repository is correct.
@resetnow Can you have a look at / do you know about that?

**Comment by resetnow** [comment]
Live updates may not work after the sitemap is edited — you will need to restart openHAB. If the package you are using is the one released on January 23, it should work — I'm using a git version from about the same time and it works for me. 

Also, can you open a developer console in your browser (F12) and check if there are any errors?

**Comment by guyyakobovitch** [comment]
Normal behavior seems to be when openhab is restarted.
But about an hour (+-) later it happens again (I did change the sitemap during that time). 
Developer console in chrome (F12) is clean. 
The problem happens simultaneously on all BASIC UI clients, on chrome on my android, and on the PC.
Commands and updates are sent when Switch/Setpoint are clicked, but no update is showing (only on page refresh).

I'm using OpenHAB 2.0.0-1 (as package from stable repository), and experienced that behavior on more than one system (which have openHAB 2.0.0-1 installed).

**Comment by resetnow** [comment]
Well, to test it properly, try not editing a sitemap during an extended period of time. It's still a problem, I'm just trying to figure out whether it's a new or an existing one.

**Comment by guyyakobovitch** [comment]
There is no problem(!) if not touching config files after openhab2 service loads.

**Comment by guyyakobovitch** [comment]
I tested it for the last few days, and it is working without problems (as long as I don't touch the config files)

**Comment by wborn** [comment]
That the SSE stream breaks when configurations are modified is already reported in #2706. So that makes this issue a duplicate.
