### ISSUE TITLE
Basic UI sends dimmer command twice

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#2959]
When changing the slider on the sitemap, the Basic UI appears to be sending the dimmer command twice.  Here's a screen snip of the browser debug that was produced after moving the slider. You can see the two OfficeLamp_Dimmer calls.

![be02fef76bb4a01be236e3869926aec3853f8044_1_690x105](https://cloud.githubusercontent.com/assets/19286354/22550458/302809f4-e91e-11e6-87b9-db904e911347.JPG)

Here are the associated lines in event.log.
```
2017-01-31 11:48:59.064 [ItemCommandEvent          ] - Item 'OfficeLamp_Dimmer' received command 31
2017-01-31 11:48:59.071 [ItemStateChangedEvent     ] - OfficeLamp_Dimmer changed from 16 to 31
2017-01-31 11:48:59.262 [ItemCommandEvent          ] - Item 'OfficeLamp_Dimmer' received command 31
```

The item is defined like this.
```
Dimmer  OfficeLamp_Dimmer   "Office Test Lamp [%d %%]"          <light>                                 { channel="zwave:device:zstick:node6:switch_dimmer" }
```

The sitemap is defined like this.
```
Slider item=OfficeLamp_Dimmer label="Office Test Lamp"
```

I don't see this behavior when changing the value using other UIs, such as PaperUI or the Karaf console.

**Comment by kaikreuzer** [comment]
@resetnow Could you please have a look?

**Comment by resetnow** [comment]
One or more commands may be sent during slider changes (when user drags the slider knob) and another will be sent after the knob is released. It's “may be” because it depends on the browser and it's hard to get  the exact same behavior across different platforms. I assumed it's not a problem for slider items, is it?

**Comment by mhilbush** [comment]
The behavior is caused by a single click on the slider (versus dragging the slider).  The mouse press event didn't generate anything.  The mouse release event generated the 3 operations shown above in the browser debug window.

I see the behavior on Chrome and Firefox on both Windows and Mac platforms.

As for causing a problem, I would agree it's not causing a problem (other than in this case resulting in unnecessary transactions on the Z-Wave network).
