### ISSUE TITLE
BasicUI: Switch, no differentiation between OFF and NULL

### ISSUE THREAD

**Issue by ThomDietrich** [eclipse/smarthome#2962]
A switch item can have three states, the obvious ON and OFF, and a third initialized NULL state. BasicUI currently doesn't differentiate between OFF and NULL. Here's an example, where the icon state is somewhat helpful (and wrong too at the same time):

![grafik](https://cloud.githubusercontent.com/assets/2870104/22573532/b6579ad6-e9a9-11e6-95f7-2e24f185ff53.png)

The states here are actually: NULL, OFF, OFF, OFF
In this second example, the states are NULL, OFF, NULL:

![grafik](https://cloud.githubusercontent.com/assets/2870104/22573564/e84c389e-e9a9-11e6-8c10-73eb1abd2d4e.png)

Not so obvious :)

I'm not entirely sure how to solve that clarity problem... Maybe by putting the knob in the middle and/or making it cloudy?

@resetnow

**Comment by maggu2810** [comment]
The Framework itself allows four possible states (as it allows the OnOffType and the UndefType):
* OnOffType.ON
* OnOffType.OFF
* UndefType.NULL
* UndefType.UNDEF

IIRC at the moment no one set UNDEF in the core framework, but it is possible by the framework.
NULL is set as long as no other state has been set (startup, item refresh without anyone handling the refresh command, ...).
IMHO the UI shoud differ at least between real values (ON, OFF) and the "undef" ones (I don't think it is necessary for the UI to differ between the different values of the UndefType enum).

**Comment by resetnow** [comment]
I can't think of a way to implement that in a non-confusing way. Graying it out will make it look disabled. Moving the knob to the middle requires modifications in the MDL library. I understand equating OFF and NULL is not technically correct, but adding a third state to a control that historically only had two states is just going to raise more questions from users.

**Comment by maggu2810** [comment]
I agree it could be confusing and don't know what is a good solution for the UI to render that.
But this don't apply to the switch state only but for every item type (as every one allows the usage of the undef type and is set to null on startup).

**Comment by kaikreuzer** [comment]
I don't think we should do any changes here - having a greyed out icon imho is good enough to signal to the user that the current state is not yet known. This should anyhow only be the case at system startup thus not be a "normal" situation. And as @maggu2810 says, this would need to be done in all other UIs that exist, which might be pretty difficult. Having the off-state for the knob and a grey icon as a default for null values is imho a fair compromise.

**Comment by maggu2810** [comment]
> having a greyed out icon imho is good enough to signal to the user that the current state is not yet known

My reading of @resetnow comment

> Graying it out will make it look disabled.

has been that it is not greyed out ATM.

I cannot have a look at the UI now, so: It is greyed out at the current master or it is shown identical to off?

**Comment by resetnow** [comment]
>Graying it out will make it look disabled.

I was referring to graying out the switch itself — as if it was 50% transparent and more drak-gray.

**Comment by kaikreuzer** [comment]
> It is greyed out at the current master or it is shown identical to off?

As @resetnow says: Wrt "greyed" out, I was referring to already have the icon greyed out, so I would not do anything to the switch itself. And the grey icons are managed through the icon set / icon servlet, so this is the same feature on all UIs automatically. If there are icons where a grey version is missing, we should add that.

**Comment by ThomDietrich** [comment]
@kaikreuzer as you can see in my examples, the "battery" icon is one example where there is no differentiation between the OFF and the UNDEF/NULL icon. The "siren" icon is even colorful in the NULL state. I don't think we should rely on the icons alone. Even if you designed another battery and siren icon, there will be others, including user-defined icons.

> This should anyhow only be the case at system startup thus not be a "normal" situation. 

We can't know that. If and how an item is set to any value is totally up to the way it is used and (if even) the linked binding. In my case I was experiencing a severed MQTT connection...

> Having the off-state for the knob and a grey icon as a default for null values is imho a fair compromise.

I can sadly not confirm that. The icon is not a clear source of information, however the binary switch tells a clear story. Additionally (a personal concern of mine) the icon solution is not screenreader accessible.

As I said in my initial post, I don't know the best solution but there should be one. The current situation is simply misleading.

> IMHO the UI shoud differ at least between real values (ON, OFF) and the "undef" ones"

> adding a third state to a control that historically only had two states is just going to raise more questions from users.
  
> this don't apply to the switch state only but for every item type

> I was referring to graying out the switch itself — as if it was 50% transparent and more drak-gray.

These are fair points. 50% grayed out for all UndefType items (maybe with an additional title) would be a intuitive solution.

![grafik](https://cloud.githubusercontent.com/assets/2870104/22619016/5c1ef062-eaeb-11e6-8348-87649c02b89c.png)

I understand that the raised problem is not an easy one. Please bear with me.

**Comment by watou** [comment]
I don't see a way to have a switch widget represent more than two states in an acceptable way.  Could the visual feedback need be met instead by `switch-undef` and `switch-null` icons?

**Comment by kaikreuzer** [comment]
> Could the visual feedback need be met instead by switch-undef and switch-null icons?

The "no state" icon name is automatically the one used for undef/null.
I.e. a switch.png should be grey, switch_on.png green, switch_off.png red (or something like that). And this is how it is already done for most icons (where it makes sense).

**Comment by watou** [comment]
> In this second example, the states are NULL, OFF, NULL: [graphic of battery icons] Not so obvious :)

To address the original question of battery icons not reflecting NULL or UNDEF state, the default battery icon should indicate the undetermined battery level, maybe with a question mark overlaying the battery icon.  The same suggestion applies to any other default icons that might give a misleading default state that suggests known state.

**Comment by ThomDietrich** [comment]
@watou The original question was not related to the battery icon. I merely chose it as an example. Please read my answer above, where I already tried to make a point...

**Comment by watou** [comment]
> the binary switch tells a clear story

Yes, it needs to tell a clear story: ON or OFF.  It is even incorrect to grey it out in any case except when it would be disabled for the user, which is not applicable here.  The icon would be the only other place to explain the state besides the textual label (which would be screen readable).  For icons where there ought to be a distinction between UnDefType vs. other states, those icons should be updated.  Just my opinion! 😄

**Comment by ThomDietrich** [comment]
Let's try to summarize while this ticket is still warm.

* Items can be in the range of their respective states, or uninitialized (UndefType)
* If and how an item is getting initialized is only dependent on the user setup
* Sitemap elements are currently not clearly indicating an uninitialized state of an item (this applies for all element/item types)
* The visual icon is not strictly representing the item state (e.g. see static user provided icons)
* The item label is a static element
* The control element is what represents the current state of an element/item
* "As a user, I want to know in which state my items are, so that I am certain about the situation in my home and can build and test extensions." 

I would recommend the control element area of the sitemap to indicate the UndefType state, as this is the "state area" which otherwise transports wrongful information! Example: If a binary state is neither ON nor OFF, a visual representation should not indicate one or the other but be marked accordingly.

How to solve this? @resetnow already gave a nice idea, to apply opacity. I've shown a screenshot with this in action above. To further clarify the meaning, I've added a tooltip, which would also be Screenreader accessible - btw the reason for this thread.

I would like to find a resolution. I would even take it upon me to implement the needed change, if workload is the issue.

**Comment by resetnow** [comment]
I'd like to note that my idea was an example of  <i>bad</i> and confusing implementation.

Another solution would be adding an "undefined" icon to each icon type. Overlaying a question mark should work too, may not look as good in some cases though.

**Comment by ThomDietrich** [comment]
The icon is from a functional standpoint not the right place for this information.
Adding opacity and a tooltip looks great to me, check the screenshot above to see it in action. The combination is quite intuitive.

**Comment by lolodomo** [comment]
switch.png is unfortunately not grey but identical to switch-on.png meaning green. I would suggest to change that.
Then isn't it possible to change our icon management to use a generic undefined.png icon when the item state is undefined ? All undefined items will then have the same icon.

**Comment by ThomDietrich** [comment]
@lolodomo that might bring around some clarity but yet again I'm not sure if this will be the overall intuitive solution. In the example of the switch you'll see some icon (the user will not necessarily know the meaning of the "undefined" icon) and a switch in one of two valid non-undef positions.
I agree that the icons should be corrected to behave equally but as for the undefined state of an item: I'm still convinced another solution is needed. A disabled control element with an additional tooltip is still a good, intuitive and easy to be implemented solution, imho.

**Comment by kaikreuzer** [comment]
> a disabled control element with an additional tooltip is still a good

I still disagree. A disabled element does not even let (or invite) the user to bring it into a defined state.
The icon and the label is what is there to display item states. Controls are there to issue commands in the first place. A physical wall switch does also not "grey out", just because it doesn't know if the light attached to it is REALLY on...

> easy to be implemented solution

Again, I disagree. As mentioned above, all existing UIs would have to come up with a way to do this with a decent UX.
As you correctly mention "NULL" is only allowed if an item is not yet initialized. A proper solution should make sure that all items ARE initialized and thus this question should not at all come up (or be a corner case).

**Comment by ThomDietrich** [comment]
I think I (finally) got your point and the course of our disagreement: In my perception of the presentation the right part (i.e. the switch) is what matters and hence should always hint a certain state the item is in. You however see this right part as the control part first and foremost and expect the left part (the icon) to be the presentation of the current state of an item. In my perception of the UI the icon is nothing more than a nice image of what I'm controlling without a clear message (for most sitemap elements besides a binary switch).

With this in mind I can understand the arguments above. I'd agree that the icon should clearly indicate the undefined state of an item. How do you feel about @lolodomo 's suggestion to have one "undefined" icon for all? Would definitely make this easier and would make the rather special case of an item being in an undefined state clear.

One last nitpick: Even with an "undefined" icon (however implemented) the end user might still want to know what it means (this special icon that seems to carry additional information). Would you agree that a tooltip for the "undefined" icon would make sense?

> As you correctly mention "NULL" is only allowed if an item is not yet initialized. A proper solution should make sure that all items ARE initialized and thus this question should not at all come up (or be a corner case).

The only part where we still disagree. If, how and when an item is initialized is totally up to the users setup/rules/bindings and not under our control. Correct?

**Comment by lolodomo** [comment]
Why clising this issue ?
At my knowledge, this is still open and waiting for a solution acceptable by the mainteners.

**Comment by ThomDietrich** [comment]
Hey @lolodomo, indeed it does and I still care strongly about this problem.
I've closed it because my initial arguments where a bit sidetracked and from the wrong perspective. See my last comment.
You have since opened another issue (#3742) discussing the real issue. I was going to add my opinion there.

Do you agree so far?
