### ISSUE TITLE
Rules without triggers and actions can be created using REST

### ISSUE THREAD

**Issue by adimova** [eclipse/smarthome#2982]
Perform POST REST call using rule without triggers or actions (null or empty) - rule is added in RuleRegistry but should not be. The expected behavior is error message: code = 400, message = "Creation of the rule is refused. Missing required parameter."

**Comment by danchom** [comment]
This Issue is related to #2964 discussion

**Comment by danchom** [comment]
We have decided the rules with at least one action (for scene purposes) to have possibility  to be added in rule engine.
