### ISSUE TITLE
ClassCastException in Automation REST

### ISSUE THREAD

**Issue by adimova** [eclipse/smarthome#2984]
java.lang.ClassCastException: org.eclipse.smarthome.automation.type.ActionType cannot be cast to org.eclipse.smarthome.automation.type.TriggerType
at org.eclipse.smarthome.automation.dto.TriggerTypeDTOMapper.map(TriggerTypeDTOMapper.java:36)
at org.eclipse.smarthome.automation.rest.internal.ModuleTypeResource.getAll(ModuleTypeResource.java:82)

**Comment by adimova** [comment]
Possible solutions are:
1. Changing the code in ModuleTypeResource.getAll:
@GET
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "Get all available module types.", response = ModuleTypeDTO.class, responseContainer = "List")
    @ApiResponses(value = { @ApiResponse(code = 200, message = "OK") })
    public Response getAll(
            @HeaderParam("Accept-Language") @ApiParam(value = "language") String language,
            @QueryParam("tags") @ApiParam(value = "tags for filtering", required = false) String tagList,
            @QueryParam("type") @ApiParam(value = "filtering by action, condition or trigger", required = false) String type) {
        final Locale locale = LocaleUtil.getLocale(language);
        final String[] tags = tagList != null ? tagList.split(",") : null;
        final List<ModuleTypeDTO> modules = new ArrayList<ModuleTypeDTO>();

        if (type == null || type.equals("trigger")) {
            modules.addAll(TriggerTypeDTOMapper.map(moduleTypeRegistry.getTriggers(locale)));
        }
        if (type == null || type.equals("condition")) {
            modules.addAll(ConditionTypeDTOMapper.map(moduleTypeRegistry.getConditions(locale)));
        }
        if (type == null || type.equals("condition")) {
            modules.addAll(ActionTypeDTOMapper.map(moduleTypeRegistry.getActions(locale)));
        }
        if (tags != null) {
            filterByTags(modules, Arrays.asList(tags));
        }
        return Response.ok(modules).build();
    }

    /**
     * @param modules
     * @param tagList
     */
    private void filterByTags(List<ModuleTypeDTO> modules, Collection<String> tagList) {
        for (Iterator<ModuleTypeDTO> it = modules.iterator(); it.hasNext();) {
            ModuleTypeDTO mt = it.next();
            Collection<String> mtTags = mt.tags;
            if (!mtTags.containsAll(tagList)) {
                it.remove();
            }
        }
    }

OR

2. Changing the ModuleTypeRegistry methods:
getTriggers(String... tags), getTriggers(Locale locale, String... tags)
getConditions(String... tags), getConditions(Locale locale, String... tags)
getActions(String... tags), getActions(Locale locale, String... tags)

**Comment by danchom** [comment]
For the first solution you can use method moduleTypeRegistry.getByTags(..) to retrieve all the modules and after that to filter them by specific type i.e. instanceOf Trigger, instanceOf Action and etc.  In that way we will be sure that the tag filtering is same as it is done in the moduleTypeRegistry (it will be done on one place).
But I'm for the second solution, it is not API breaking change and in that way the extension of getTriggers, getConditions and getActions methods will be available in java api, not only in the rest one.

**Comment by kaikreuzer** [comment]
I would have expected that 
```
public <T extends ModuleType> Collection<T> getByTags(Locale locale, String... tags);
```
only returns instances of T, so that there would't be any issue in the first place. Is that not working because of Java's type erasure? If so, I also think that this method is rather useless and option 2 sounds like a good option.

**Comment by maggu2810** [comment]
> Is that not working because of Java's type erasure?

Yes.

If getByTags should return only instances of class `T` it needs an attribute `Class<T> clazz` and implement an instance check.

**Comment by danchom** [comment]
Your proposal is to add parameter Class<T> clazz to the getByTags method?
i.e.
public Collection<T> getByTags(Class<T> clazz, Locale locale, String... tags);

**Comment by kaikreuzer** [comment]
No no, please don't! Option 2 be it!
