### ISSUE TITLE
DiscoveryServiceRegistryImpl#thingRemoved will not remove the cachedElement

### ISSUE THREAD

**Issue by afuechsel** [eclipse/smarthome#2990]
Findbugs showed this bug: org.eclipse.smarthome.core.thing.ThingUID is incompatible with expected argument type org.eclipse.smarthome.config.discovery.DiscoveryResult in org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.thingRemoved(DiscoveryService, ThingUID)

This is true, as it is a `MultiMap<DiscoveryService, DiscoveryResult>`, which would not contain a key value pair of `<DiscoveryService, ThingUID>` trying remove here: 

``` 
            cachedResults.remove(source, thingUID);
```

**Comment by triller-telekom** [comment]
This line
```
cachedResults.remove(source, thingUID);```

has been removed from DiscoveryServiceRegistryImpl#thingRemoved  and replaced by

```
synchronized (cachedResults) {
            Iterator<DiscoveryResult> it = cachedResults.get(source).iterator();
            while (it.hasNext()) {
                if (it.next().getThingUID().equals(thingUID)) {
                    it.remove();
                }
            }
        }
```
So I guess this issue can be closed @sjka @kaikreuzer
