### ISSUE TITLE
isLinked exception when a channel is unknown by the thing

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#2999]
isLinked(channel) throws an exception when the channel in argument does not exist for the thing.
When a binding is enhanced with a new channel and a user updates to this new binding version, a use of isLinked for the new channel will lead to an exception until the user removes his thing and create another one.

I am asking myself if the exception should not be catched by isLinked and if the channel does not exist then returns false ?

Another option would be to be modify every binding using isLinked to catch the exception. Lot of work.

It leads to another consideration: would it be possible to automlatically add the new channels to old things.

**Comment by lolodomo** [comment]
Here is an example of the problem : https://community.openhab.org/t/solved-sonos-binding-problems/22599

**Comment by J-N-K** [comment]
IMHO the last option would be best. The OH2 Astro binding had the Same problem. As long as only one or two things need to be updated, manually doing so is ok, but imagine a OneWire binding where you need to configure each sensor again.

**Comment by maggu2810** [comment]
> It leads to another consideration: would it be possible to automlatically add the new channels to old things.

IIRC there is already an issue (or an comment in an issue) that will bring that function into account.
Will try to find them...

**Comment by maggu2810** [comment]
#2555

**Comment by lolodomo** [comment]
I close this issue as the real issue is #2555.
