### ISSUE TITLE
Paper UI not showing updated thing settings without a browser cache refresh

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3000]
Using Paper UI, I update a thing configuration and validate. My thing is updated (dispose and then initialize).
Then if I reopen my thing configuration in Paper UI, I see the previous settings. Using Ctrl+F5 in Firefox then show me the current and correct settings.

**Comment by lolodomo** [comment]
Using snapshot 786.

**Comment by kaikreuzer** [comment]
Congratulations on issue 3000 :-)

@aounhaider1 Could you check this issue, please?

**Comment by kaikreuzer** [comment]
@lolodomo In case #3024 does not fix this issue, please simply re-open the issue here!
