### ISSUE TITLE
SSE event - trouble with empty separator line 

### ISSUE THREAD

**Issue by rgabo74** [eclipse/smarthome#3004]
I am using the Rest API from OpenHab2.0. I have troubles with all kinds of sse clients. I finally realized that clients looking for an empty line closing the event. SSE server in eclipse smarthome seem to be sending the empty line before the event, not after, which does not seem to be along with the specs.  

![image](https://cloud.githubusercontent.com/assets/11273702/22906605/94c7dab2-f245-11e6-839b-a228d006ecc3.png)

**Comment by maggu2810** [comment]
I looked at the code and it seems we are using the upstream jersey implementation.

I also tested it myself using the command line tool `curl`

```
curl http://127.0.0.1:8080/rest/events
```

I generate an event and this has been written
```
event: message
data: {"topic":"smarthome/inbox/ntp:ntp:local/removed","payload":"{\"flag\":\"NEW\",\"label\":\"Local Time\",\"properties\":{\"timeZone\":\"Europe/Berlin\"},\"thingUID\":\"ntp:ntp:local\",\"thingTypeUID\":\"ntp:ntp\"}","type":"InboxRemovedEvent"}

```

So, no newline at the beginning but a new line at the end.
After some time I generate another event

```
event: message
data: {"topic":"smarthome/inbox/ntp:ntp:local/added","payload":"{\"flag\":\"NEW\",\"label\":\"Local Time\",\"properties\":{\"timeZone\":\"Europe/Berlin\"},\"thingUID\":\"ntp:ntp:local\",\"thingTypeUID\":\"ntp:ntp\"}","type":"InboxAddedEvent"}

```

again, a new line at the end after the event generation and no-one in front of the event.

**Comment by kaikreuzer** [comment]
So all seems to be correct. @rgabo74 Feel free to re-open, if you disagree.
