### ISSUE TITLE
Basic UI: Available Sitemaps prompt

### ISSUE THREAD

**Issue by ThomDietrich** [eclipse/smarthome#3006]
From time to time you can see newcomers struggling with the basic UI and the sitemap shown there. Two pieces of knowledge are missing in this case. 1) the sitemap shown by default is "_default", the sitemap automatically generated from things, and 2) another sitemap (user-created) needs to be explicitly set (can not be selected) under Settings or browsed directly by modifying the URL.

Reasons for this misconceptions are, *in my opinion*, the fact, that "_default" is not marked as such (the user doesn't understand why "his" sitemap doesn't show what he defined) and a user-defined sitemap is not offered as an option, if available.

The solution already exists. If the Basic UI Default Sitemap setting is set to "" rather than "_default", you are presented with:

![](https://cloud.githubusercontent.com/assets/2870104/22919498/81b25d12-f290-11e6-8dcb-e4c448fac35f.png)

One approach for improvement I can think of is, that Basic UI should be shipped with the Default Sitemap setting "" and the shown List of "Available Sitemaps" should always contain the "_default" sitemap (with a descriptive name). In case there is no user-defined sitemap, a note could be shown: "Build your own sitemap now! Have a look at http://docs.openhab.org/configuration/sitemaps.html for more details."

This approach is only one idea, what do you think?

**Comment by MHerbst** [comment]
Good idea.

**Comment by kaikreuzer** [comment]
Actually, the _default sitemap is created by openhab.core, the default configuration is defined there as well and the Basic UI as it is part of ESH must not reference any openHAB documentation. So I'd suggest to move this issue over to https://github.com/openhab/openhab-core.

**Comment by ThomDietrich** [comment]
Thanks. https://github.com/openhab/openhab-core/issues/118
Even after all these months, each issue creation is a round of russian roulette :smile:
