### ISSUE TITLE
Basic UI: Colorpicker ON/OFF problem

### ISSUE THREAD

**Issue by rockster2410** [eclipse/smarthome#3009]
Hi,
there is an issue with the colorpicker in the BasicUI.
The colorpicker is working perfectly but not the two buttons next to it (left and right to turn on and off).

The problem is discussed here: 
https://community.openhab.org/t/openhab2-problem-with-colorpicker-in-basic-ui/19421

Does anyone know a solution?

Thanks!

**Comment by kaikreuzer** [comment]
@resetnow Could you please check?

**Comment by resetnow** [comment]
This is an old bug I forgot about, sorry.

Question: should I leave INCREASE/DECREASE commands on long press? They don't seem to do anything to me (on demo sitemap), are they specific to a binding?

**Comment by kaikreuzer** [comment]
> should I leave INCREASE/DECREASE commands on long press?

Yes, please! They only work if you have associated a binding; the auto-update that jumps in when no binding is configured indeed does not handle INCREASE/DECREASE.
