### ISSUE TITLE
Not all LIFX items are shown in PaperUI

### ISSUE THREAD

**Issue by CWempe** [eclipse/smarthome#3014]
I added all my four LIFX bulbs.
I configured the things and items via config files.

#### lifx.things
```
Thing lifx:colorlight:subwoofer "Licht Subwoofer" [ deviceId="d***a", fadetime=300 ]  {
    Channels:
        Type color : color [ powerOnBrightness= ]
}

Thing lifx:colorlight:fenster "Licht Fenster" [ deviceId="d***7", fadetime=300 ]  {
    Channels:
        Type color : color [ powerOnBrightness= ]
}

Thing lifx:colorlight:beamer "Licht Beamer" [ deviceId="d***e", fadetime=300 ]  {
    Channels:
        Type color : color [ powerOnBrightness= ]
}

Thing lifx:colorlight:kommode "Licht Kommode" [ deviceId="d***5", fadetime=300 ]  {
    Channels:
        Type color : color [ powerOnBrightness= ]
}
```

#### lifx.items
```
Switch Subwoofer_Toggle      { channel="lifx:colorlight:subwoofer:color" }
Dimmer Subwoofer_Dimmer      { channel="lifx:colorlight:subwoofer:color" }
Color  Subwoofer_Color       { channel="lifx:colorlight:subwoofer:color" }
Dimmer Subwoofer_Temperature { channel="lifx:colorlight:subwoofer:temperature" }

Switch Beamer_Toggle         { channel="lifx:colorlight:beamer:color" }
Dimmer Beamer_Dimmer         { channel="lifx:colorlight:beamer:color" }
Color  Beamer_Color          { channel="lifx:colorlight:beamer:color" }
Dimmer Beamer_Temperature    { channel="lifx:colorlight:beamer:temperature" }

Switch Fenster_Toggle        { channel="lifx:colorlight:fenster:color" }
Dimmer Fenster_Dimmer        { channel="lifx:colorlight:fenster:color" }
Color  Fenster_Color         { channel="lifx:colorlight:fenster:color" }
Dimmer Fenster_Temperature   { channel="lifx:colorlight:fenster:temperature" }

Switch Kommode_Toggle        { channel="lifx:colorlight:kommode:color" }
Dimmer Kommode_Dimmer        { channel="lifx:colorlight:kommode:color" }
Color  Kommode_Color         { channel="lifx:colorlight:kommode:color" }
Dimmer Kommode_Temperature   { channel="lifx:colorlight:kommode:temperature" }
```

#### karaf output
```
openhab> smarthome:items
Subwoofer_Toggle (Type=SwitchItem, State=ON, Label=null, Category=null)
Subwoofer_Dimmer (Type=DimmerItem, State=58, Label=null, Category=null)
Subwoofer_Color (Type=ColorItem, State=0,0,58, Label=null, Category=null)
Subwoofer_Temperature (Type=DimmerItem, State=100, Label=null, Category=null)
Beamer_Toggle (Type=SwitchItem, State=ON, Label=null, Category=null)
Beamer_Dimmer (Type=DimmerItem, State=58, Label=null, Category=null)
Beamer_Color (Type=ColorItem, State=0,0,58, Label=null, Category=null)
Beamer_Temperature (Type=DimmerItem, State=100, Label=null, Category=null)
Fenster_Toggle (Type=SwitchItem, State=ON, Label=null, Category=null)
Fenster_Dimmer (Type=DimmerItem, State=46, Label=null, Category=null)
Fenster_Color (Type=ColorItem, State=0,0,46, Label=null, Category=null)
Fenster_Temperature (Type=DimmerItem, State=100, Label=null, Category=null)
Kommode_Toggle (Type=SwitchItem, State=OFF, Label=null, Category=null)
Kommode_Dimmer (Type=DimmerItem, State=0, Label=null, Category=null)
Kommode_Color (Type=ColorItem, State=0,0,0, Label=null, Category=null)
Kommode_Temperature (Type=DimmerItem, State=100, Label=null, Category=null)
```

#### PaperUI
![image](https://cloud.githubusercontent.com/assets/1270359/22944679/c594c04a-f2f1-11e6-85e4-cfcc18c2f43d.png)

As you can see two of four bulbes do not show Color and Saturation.

The item "Licht Subwoofer" was added first as a single bulb.
The other three ware added later but at the same time.

**Comment by kaikreuzer** [comment]
```
Switch Subwoofer_Toggle      { channel="lifx:colorlight:subwoofer:color" }
Dimmer Subwoofer_Dimmer      { channel="lifx:colorlight:subwoofer:color" }
Color  Subwoofer_Color       { channel="lifx:colorlight:subwoofer:color" }
```

This is not recommented. Having the color item should be fully enough - the other items really merely duplicate that (duplicates with some restrictions).

**Comment by CWempe** [comment]
Ok.
I removed the other items and the PaperUI does show all four bulbes with three sliders 'inside' the color items as expected. 

- I will try to edit the dosumentation more clearly about this.
- I am not sure if this solves the issue. I still think all configured items should be displayed.
Even if they don't make sense.

**Comment by kaikreuzer** [comment]
>  I still think all configured items should be displayed. Even if they don't make sense.

Yes, I agree, this should work nonetheless. But this is most likely not an issue about LIFX nor Paper UI, but simply that the core framework does not correctly send updates to all linked items. So we should probably rather formulate a pretty different and much simpler bug report.

> Where do I find the Github for the lifx-addon to edit the README???

You are here at ESH, that's why it is here: https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.lifx

**Comment by CWempe** [comment]
> So we should probably rather formulate a pretty different and much simpler bug report.
Like: "Some random items are not displayed by PaperUI"? 😕 

> You are here at ESH, that's why it is here: 
I am here, because of paperUI.
I expected the lifx binding where all the other bindings are.
But you are right, of cause. 😄

**Comment by triller-telekom** [comment]
In the current PaperUI all items are shown. See the screenshot.

So I guess this issue can be closed @sjka @kaikreuzer.

![image](https://user-images.githubusercontent.com/26876013/30704300-94b20a48-9ef2-11e7-9d1f-f5bef33f74de.png)
