### ISSUE TITLE
Wrong redirection when behind a reverse proxy server

### ISSUE THREAD

**Issue by robnielsen** [eclipse/smarthome#3018]
When smarthome is behind a reverse proxy server that only allows https, the redirection from https://host/ is improperly going to http://host/start/index. This is happening because the 302 redirect is ignoring the X-Forwarded-Proto header. See https://community.openhab.org/t/nginx-redirect-to-port-80/16760/6 for more details.

**Comment by maggu2810** [comment]
Isn't the redirect done by the Jetty configuration of openHAB?
I don't see any relationship to ESH, could you please point me to?

**Comment by kaikreuzer** [comment]
Correct, the redirection is defined [here](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/runtime/etc/jetty.xml#L42-L50).

@robnielsen If you know what needs to be changed there to keep the correct scheme in place, please provide a PR for it!
