### ISSUE TITLE
Not clear error message when module id contains spaces.

### ISSUE THREAD

**Issue by plamen-peev** [eclipse/smarthome#3023]
For example if we have a rule on which one of the modules is with id `"Timer Trigger"` the description of the error that is thrown, by the fact that the the module id can not contain white spaces, is unclear. 
The message says: Validation of rule ..... has failed! Timer Trigger

It is unclear because the expression: 
`"Invalid module uid: " + mId != null ? mId
                        : "null" + ". It must not be null or not fit to the pattern: [A-Za-z0-9_-]*"` is not evaluated properly.

**Comment by kaikreuzer** [comment]
Please add a "fixes #XXXX" to your PRs in future, then the associated issues will automatically be closed upon merge.
