### ISSUE TITLE
BasicUI Switch element linked to Dimmer item does not update correctly

### ISSUE THREAD

**Issue by mherwege** [eclipse/smarthome#3036]
I put on one sitemap both a slider and a switch for the same dimmer item.
When I move the slider (but not to 0 so the light does not completely turn off), my switch element does turn off. Refreshing the browser turns it back on.
When the switch and slider are off, turning the light on with the switch does turn the physical light on, but does not turn the switch on. Again refreshing the browser solves it.
Also turning the light on using the slider does not turn the switch on.
The same behavior can be observed with a setpoint element rather than a slider element. The setpoint and slider elements do remain in sync.

**Comment by lolodomo** [comment]
Should be tested again now that PR #3332 was merged.

**Comment by lolodomo** [comment]
I tested and for me it is now working as expected.
@kaikreuzer : please close this issue.

**Comment by maggu2810** [comment]
> @kaikreuzer : please close this issue.

I hope it is okay, if this issue is closed by another one, too :wink:

**Comment by mherwege** [comment]
Tested, and it works.
