### ISSUE TITLE
[Feature Request] More icons

### ISSUE THREAD

**Issue by mueller-ma** [eclipse/smarthome#3044]
Hi,
I would like to see some more icons:

- Smartphone, Tablet, Computer, Laptop, Server, ...
- Temperature icons like the humidity ones. A good aproach would be to create temperature_celsius-0, temperature_fahrenheit-40,.. where the number is the actuall value, not a percentage value.
- Arrows. Currently there is flowpipe and returnpipe. I can give it a try, but I don't know how to name the icons. arrow_red-down, arrow_down-red, arrow-3... What do you think about that?
- Player on/off (Reuse the reciever icon)

**Comment by triller-telekom** [comment]
@mueller-ma Sorry for getting back to you so late.

Are you still interested in creating new icons? If you are, please have a look at #4212 where we currently consolidate our icon sets.

**Comment by mueller-ma** [comment]
I'm closing this, because it is now kind of a duplicate. I wanted to create icons, but it seems harder than I thought and I don't have much experience with graphics.
