### ISSUE TITLE
Documentation for config parameter contexts

### ISSUE THREAD

**Issue by rodneyrehm** [eclipse/smarthome#3054]
The changes made to the documentation in regard to parameter contexts in #2168 are missing a few things:

* The newly introduced context "Day of week" was not added to the [XML structure for Configuration Descriptions](https://github.com/qivicon/smarthome/blame/09b115c0738e8117db67baa8dbd66002c7648a1e/docs/documentation/development/bindings/xml-reference.md#L52) and [ConfigDescriptionParameter.getContext()](https://github.com/eclipse/smarthome/blob/6dd1df77136a70ec55da6746be05bf65b78ba15b/bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameter.java#L331-L347)
* The actual *value* for "Day of week" [is not mentioned](https://github.com/qivicon/smarthome/blame/09b115c0738e8117db67baa8dbd66002c7648a1e/docs/documentation/development/bindings/xml-reference.md#L114), I'd *assume* `weekday`, but [PaperUI include.config.html](https://github.com/eclipse/smarthome/blob/1121ecac6294f5ed396127ad8776862b99578bd4/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/partials/include.config.html#L150) suggests `dayofweek`
* The [Supported Contexts section](https://github.com/qivicon/smarthome/blame/09b115c0738e8117db67baa8dbd66002c7648a1e/docs/documentation/development/bindings/xml-reference.md#L104-L115) is missing a number of values presented in the XML block above.

Furthermore the listed date/time contexts leave questions:

* `date` is supposed to be formatted as `DD:MM:YYYY`, while [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) specifies it as `YYYY-MM-DD`
* `time` apparently allows integer input (I assume [unix epoch](https://en.wikipedia.org/wiki/Epoch_(reference_date)#Notable_epoch_dates_in_computing)?) or `hh:mm`, while [ISO 8601 Dates](https://en.wikipedia.org/wiki/ISO_8601#Times) allows `hh:mm:ss` and `hh:mm`. Are these UTC or local time zone?
* "Day of week" isn't mentioned in ISO 8601, so the enum looks fine

The following tables are extracted from the docs I created for one of the parameter rendering engines used in Qivicon. They aren't perfect, but should be a good starting point for the ESH docs…

## Parameter Contexts

| context | format | implementation | ignored limitations | Qivicon notes |
| ------- | ------ | -------------- | ------------------- | ------------- |
| text | literal text | `<input type="text">` | none | default context |
| network-address | IPv4, IPv6, domain name | `<input type="text">` | none | format not enforced in Qivicon |
| password | literal text | `<input type="password">` | `pattern` | |
| password-create | literal text | custom password input | none | |
| color | [`#aabbcc`](https://html.spec.whatwg.org/multipage/forms.html#color-state-(type=color)) | `<input type="color">` | `minimum`, `maximum`, `stepsize`, `pattern` | not implemented in Qivicon |
| date | [`2017-02-22`](https://html.spec.whatwg.org/multipage/infrastructure.html#dates) | `<input type="date">` | `minimum`, `maximum`, `stepsize`, `pattern` | not implemented in Qivicon |
| datetime | `2017-02-22T20:21:52.344Z` | [`Date.toISOString()`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) | `minimum`, `maximum`, `pattern` | not implemented in Qivicon |
| email | `user@host` | `<input type="email">` | `minimum`, `maximum`, `stepsize`, `pattern` | |
| month | *not defined* [HTML5 months?](https://html.spec.whatwg.org/multipage/infrastructure.html#months) | ? | `minimum`, `maximum`, `stepsize`, `pattern` | not implemented in Qivicon |
| week | [`2017-W08`](https://en.wikipedia.org/wiki/ISO_8601#Week_dates) | `<input type="week">` | `minimum`, `maximum`, `stepsize`, `pattern` | not implemented in Qivicon |
| time | `hh:mm:ss` | `<input type="time">` | `minimum`, `maximum`, `stepsize`, `pattern` | not implemented in Qivicon |
| tel |  | `<input type="tel">` | `minimum`, `maximum`, `stepsize`, `pattern` | |
| url | [RFC 3986](http://tools.ietf.org/html/rfc3986) | `<input type="url">` | `minimum`, `maximum`, `stepsize`, `pattern` | |
| item | ESH Item name | *ESH* | `minimum`, `maximum`, `stepsize`, `pattern` | not implemented in Qivicon |
| thing | ESH Thing UID | *ESH* | `minimum`, `maximum`, `stepsize`, `pattern` | not implemented in Qivicon |
| group | ESH Group name | *ESH* | `minimum`, `maximum`, `stepsize`, `pattern` | not implemented in Qivicon |
| tag | ESH Tag name | *ESH* | `minimum`, `maximum`, `stepsize`, `pattern` | not implemented in Qivicon |
| service | ESH Service UID | *ESH* | `minimum`, `maximum`, `stepsize`, `pattern` | not implemented in Qivicon |

## Parameter limitations per type

| limitation | `TEXT` | `INTEGER` | `DECIMAL` | `BOOLEAN` | Qivicon notes |
| ---------- | ------ | --------- | --------- | --------- | ------------- |
| minimum | input.length >= minimum | input >= minimum | input >= minimum | no | |
| maximum | input.length <= maximum | input <= maximum | input <= maximum | no | |
| stepsize | no | yes | yes | no | |
| pattern | input.match(pattern) | no | no | no | |
| options | yes | yes | yes | no | |
| limitToOptions | yes | yes | yes | no | where `options` are provided, `limitToOptions` is forced to be true, as Qivicon does not support [`<datalist>`](https://developer.mozilla.org/en/docs/Web/HTML/Element/datalist) |
| required | input.length > 0 | input.length > 0 (includes `0`) | input.length > 0  (includes `0`) | no | |
| multiple | yes | yes | yes | no | ignored by Qivicon |
| multipleLimit | yes | yes | yes | no | ignored by Qivicon |

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you check the Paper UI implementation against this and complete the documentation with those infos? I think @rodneyrehm's tables are a very good starting point for this.
