### ISSUE TITLE
BasicUI: Updates in Items end up in wrong place

### ISSUE THREAD

**Issue by DanielMalmgren** [eclipse/smarthome#3056]
Hi.
Got a kinda weird problem here. When I first load up Basic UI everything looks fine, but as soon as I change track on my Sonos system, the new track name suddenly appears in completely wrong place in the UI.

This is a snippet of the relevant part of my sitemap:
```
Frame label="Vem är hemma?" {
            Text item=DanielsMobil_Online label="Daniel"
            Text item=VickesMobil_Online label="Victoria"
            Text item=EllasMobil_Online label="Ella"
    }

    Frame label="SONOS" {
            Text item=sonoskok_completetrackinfo label="Spelas i köket [%s]"
            Default item=SonosKK_Volume label="Volym köket"
    }
```

...and this is what that part of the UI looks like after changing track:

![basicuibug](https://cloud.githubusercontent.com/assets/2837262/23250548/ec1a8aa6-f9a9-11e6-98dc-8993b95c9c44.png)

The Item sonoskok_completetrackinfo contains both artist, album and track title. There IS an Item that contains only the title (ie the string that appears) but that Items is not represented anywhere on the sitemap.

Everything works fine in iOS and Android apps, I've only seen this happening in Basic UI.

Version info: OH 2.0.0, basicui 2.0.0, Debian 8.7

**Comment by kaikreuzer** [comment]
Can you reduce your problem to a pure Basic UI update problem, i.e. take Sonos out of the picture here?
I.e. can you reproduce it by doing a state update on the console through 
```
smarthome:update sonoskok_completetrackinfo "Some new text"
```
?

**Comment by DanielMalmgren** [comment]
Ok, tried updating both sonoskok_completetrackinfo and sonos_PLAY1_RINCON_B8E937BECD0001400_currenttitle (which is the Item containing just the title, sorry for the naming chaos here) using smarthome:update and it all works like it should (ie the text label that should be updated is updated and nothing else). Does this mean it's the SONOS binding doing something fancy?

I noticed another thing as well, no idea if it's relevant: When first loading the page there is no text at all on the labels under the "Vem är hemma?" frame (as you can see on my daughter Ella in the screenshot above), so the only way to see who's home and not is looking at the colour of the icon. When I tried simulating being home now (smarthome:update DanielsMobil_Online ON) though I see the text "ON" there (and after a while when the network binding has done it's job it says "OFF").

**Comment by kaikreuzer** [comment]
> Does this mean it's the SONOS binding doing something fancy?

Well, it might be some special chars in the state causing an issue in the Basic UI. You'd have to do some further tests to see what event causes it (again, you should be able to reproduce it by sending the event on the command line - the Sonos binding does nothing else than that).

> so the only way to see who's home and not is looking at the colour of the icon. 

Which is correct, because you define a label without a state placeholder (i.e. `label="Daniel"` instead of `label="Daniel [%s]"`).

**Comment by triller-telekom** [comment]
@DanielMalmgren Does this issue still apply? Did you find a way to reproduce it in a current version of Eclipse SmartHome? If not, can you please close this issue? Thanks.

**Comment by DanielMalmgren** [comment]
No, haven't seen it since quite some months. Guess I'll simply close the issue 👍
