### ISSUE TITLE
Control UI does not show Image items when being opened

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3087]
When an Image item has a state, the Paper UI does not correctly render it when opening the Control tab:

<img width="437" alt="screen shot 2017-02-28 at 13 38 44" src="https://cloud.githubusercontent.com/assets/3244965/23405605/59749e88-fdbb-11e6-8ae6-f8142f64ba77.png">

Once an update is received through SSE, it is displayed correctly.

**Comment by lolodomo** [comment]
I have noticed that too.
I can try to debug the problem

**Comment by kaikreuzer** [comment]
No need, already identified and PR is coming.
