### ISSUE TITLE
Display localized description for a thing status info

### ISSUE THREAD

**Issue by tomhoefer** [eclipse/smarthome#3093]
## Desired impact in front of user

In our project we have to display a localized description for a thing status, e.g »Device is blocked by remote service for 60 minutes. Maximum limit of 10 configuration changes per hour has been exceeded. For further info please refer to the device vendor. « in case of device status ```ONLINE:CONFIGURATION_PENDING```.

## Problem

The ESH device status infrastructure  is not able to handle localized thing status description strings.

### Solution (Binding)

The corresponding binding does not provide a localized string in the ```ThingStatus.description``` property, but instead provides the reference of the localization string, e.g. ```@text/rate_limit```.

The binding is able to provide placeholder values as a JSON-serialized array of strings:

```
@text/rate_limit ["60","10"]
```

```
rate_limit=Device is blocked by remote service for {0} minutes. Maximum limit of {1} configuration changes per hour has been exceeded. For further info please refer to device vendor
```
The corresponding thing should provide a new property ```localizedStatus```, so the UI can avoid requesting the REST services for things that don't support translated status messages

### Solution (ESH)

The existing REST endpoints ```/rest/things``` and ```/rest/things/<ThingUID>``` as well as a new endpoint ```/rest/things/<ThingUID>/status``` resolve the ```ThingStatus.description``` property using the I18N infrastructure already in place in ESH.

If the string in ```ThingStatus.description``` is not a localization-message-id (begins with ```@text/```) the string is to be returned verbatim.

For events and REST requests that don't contain a preferred language the localization-message must be translated to the ESH default locale (provided by locale provider).

**Comment by kaikreuzer** [comment]
Sounds feasible to me in general with one exception:

> The corresponding thing should provide a new property localizedStatus

The properties describe the Thing (device), not the features of a binding. I would therefore abstain from misusing the properties for such an information.

As a result, I would suggest that the information in the event simply has to be considered to be in default locale in any case and if a UI expects a localized version, it has to do the REST request in any case. (alternatively, your solution can keep this info somewhere else and decide based on the Thing type / binding ID whether it wants to display a localized value or not).

P.S.: `ONLINE:CONFIGURATION_PENDING` - really? If your access is blocked for 60 minutes and thus you cannot access the device, I would very much expect an OFFLINE status.

**Comment by tomhoefer** [comment]
> The properties describe the Thing (device), not the features of a binding. I would therefore abstain from misusing the properties for such an information.
I agree. I will think about to a different solution

> P.S.: ```ONLINE:CONFIGURATION_PENDING``` - really?
Sure... In this case it should be offline

**Comment by lolodomo** [comment]
Is it still open ?

**Comment by kaikreuzer** [comment]
No, thanks for noticing.
