### ISSUE TITLE
ConfigParam MIN and MAX value not compated properly

### ISSUE THREAD

**Issue by ivivanov-bg** [eclipse/smarthome#3102]
When a config parameter is of type decimal and has `min` and `max` value specified, the comparison is done in `org.eclipse.smarthome.config.core.validation.internal.TypeIntrospections.FloatIntrospection` as follows:

```java
@Override
boolean isMaxViolated(Object value, int max) {
    if (isBigDecimalInstance(value)) {
           return Float.compare(((BigDecimal) value).floatValue(), max) > 0;
    }
    return Float.compare((float) value, max) > 0;
}
```

The signature of the method expects the MAX value to be integer which causes precision issues.

**Comment by maggu2810** [comment]
Let's assume #3103 fixes your issue. Reopen is it doesn't fix it.
