### ISSUE TITLE
PaperUI | DecimalType is parsed to Integer

### ISSUE THREAD

**Issue by walwe** [eclipse/smarthome#3108]
I noticed that the Paper UI no longer displays decimals places.
This bug was introduced in #2628: 
The PR added the handling of the `statechanged` event, but it ignores the fact, that the `statechanged`event is not unique to the Rollershutter type and therefore parsing all DecimalType and PercentType using `parseInt`.

Please correct me if i am wrong, but I do not see a real use case for the `statechanged` event and therefore would simply delete the event listener, thus preventing it from overwriting the state properly handled by the `state` event.

**Comment by kaikreuzer** [comment]
@aounhaider1, Could you please check?
