### ISSUE TITLE
PaperUI, Rules: Rule from catalog

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#3110]
Using the current PaperUI on a setup with enabled Rule / Automation support, it shows the "Rule from catalog" option if you want to create a new rule.
This results in "ERROR: 503 - Service Unavailable".
I assume this option should only be visible if the service is available.

**Comment by kaikreuzer** [comment]
Yes, I noticed the same and already asked @aounhaider1 to fix this.
