### ISSUE TITLE
Reduce the Threads "Dir Watcher" count

### ISSUE THREAD

**Issue by adimova** [eclipse/smarthome#3129]
The idea is all automation file providers to share one watch service, that way will achieve the reducing the count of the threads and they become two: one thread "Dir Watcher"(this one processing watch events) and one that watch the directory.

This change has impacts in the same code as #3112

**Comment by kaikreuzer** [comment]
Question: Would it make sense to extend that improvement to ALL watch services in ESH, i.e. only have a single thread in place that watches all registered directories? This might be possible to change AbstractWatchService in a way that it only constructs a single watch thread for all class instances.

**Comment by maggu2810** [comment]
Sounds like a good plan.

**Comment by adimova** [comment]
As intention it is a good idea, I'll try to implement it, seems it is possible and not a big change

**Comment by danchom** [comment]
Merged #3144
