### ISSUE TITLE
Scheduler not working reliable for Cron Expressions

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#3132]
Rules using a Cron trigger does not work as expected.

There are messages from the `ExpressionThreadPoolManager` (I assume for every rule one message):

```
2017-03-08 07:15:00,423 | Expression '0 15 07 ? * MON,TUE,WED,THU,FRI,SAT,SUN' has no future executions anymore
2017-03-08 07:15:00,474 | Expression '0 15 07 ? * MON,TUE,WED,THU,FRI,SAT,SUN' has no future executions anymore
2017-03-08 07:15:00,835 | Expression '0 15 07 ? * MON,TUE,WED,THU,FRI,SAT,SUN' has no future executions anymore
2017-03-08 07:15:00,849 | Expression '0 15 07 ? * MON,TUE,WED,THU,FRI,SAT,SUN' has no future executions anymore
2017-03-08 08:00:00,615 | Expression '0 00 08 ? * MON,TUE,WED,THU,FRI,SAT,SUN' has no future executions anymore
2017-03-08 19:15:00,372 | Expression '0 15 19 ? * MON,TUE,WED,THU,FRI,SAT,SUN' has no future executions anymore
2017-03-08 19:45:00,450 | Expression '0 45 19 ? * MON,TUE,WED,THU,FRI,SAT,SUN' has no future executions anymore
2017-03-08 20:00:00,166 | Expression '0 00 20 ? * MON,TUE,WED,THU,FRI,SAT,SUN' has no future executions anymore
2017-03-08 21:00:00,157 | Expression '0 00 21 ? * MON,TUE,WED,THU,FRI,SAT,SUN' has no future executions anymore
```

I assume it is a bug that there are no future executors for that expression.

@kgoderis Could you have a look at.
Is it similar to #2105 or #2746?

**Comment by maggu2810** [comment]
I just had a look at the uptime of the system:
```
11:30:46 up 3 days, 22:04
```

and the date of the system
```
Fri Mar 10 CET 2017
```

So, it worked only one day this time.

**Comment by maggu2810** [comment]
@kgoderis I have created a test using the current code base:

```
    @Test
    public void findNext() throws ParseException {
        final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");

        final String[] expressions = new String[] { //
                "0 15 07 ? * MON,TUE,WED,THU,FRI,SAT,SUN", //
                "0 00 08 ? * MON,TUE,WED,THU,FRI,SAT,SUN", //
                "0 15 19 ? * MON,TUE,WED,THU,FRI,SAT,SUN", //
                "0 45 19 ? * MON,TUE,WED,THU,FRI,SAT,SUN", //
                "0 00 20 ? * MON,TUE,WED,THU,FRI,SAT,SUN", //
                "0 00 21 ? * MON,TUE,WED,THU,FRI,SAT,SUN" //
        };

        final List<CronExpression> cronExpressions = new LinkedList<>();
        for (final String expression : expressions) {
            cronExpressions.add(new CronExpression(expression));
        }

        cronExpressions.forEach(expr -> {
            Date curDate = Calendar.getInstance().getTime();

            int counter = 1;
            while (counter <= 150) {
                final Date nextDate = expr.getTimeAfter(curDate);
                if (nextDate == null) {
                    final String msg = String.format("Cannot find a time after '%s' for expression '%s'",
                            sdf.format(curDate), expr.getExpression());
                    System.err.println(msg);
                    Assert.fail(msg);
                }

                curDate = nextDate;
                ++counter;

                Calendar cal = Calendar.getInstance();
                cal.setTime(curDate);
                cal.add(Calendar.MINUTE, 1);
                cal.add(Calendar.SECOND, 1);
                curDate = cal.getTime();
            }
        });
    }
```

This results in:

```
Cannot find a time after '2017-03-10 12:16:01.000' for expression '0 15 07 ? * MON,TUE,WED,THU,FRI,SAT,SUN'
```

**Comment by maggu2810** [comment]
It seems to be related to the question mark on position four.
IIRC you we support the Quartz definition documented e.g. here: http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html

A question mark for "Day of month" should be allowed.

I tested the expression:
* `* * * ? * *` getTimeAfter does not return
* `0 * * ? * *` getTimeAfter returned null

**Comment by kgoderis** [comment]
@maggu2810 If this would be the issue, then I am very glad that the bug is not in the core algorithm itself, and thus the patch could relatively easy. That being said, it has been a *long* time that I have been in the code, you might be faster than me in fixing this in https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/CronExpression.java#L736

**Comment by kgoderis** [comment]
https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/CronExpression.java#L869 is where it goes wrong

**Comment by maggu2810** [comment]
It seems that
```
0 15 07 * * ?
```
works as expected.

But
``` 
* `0 15 07 ? * MON,TUE,WED,THU,FRI,SAT,SUN
```
does not work at all.

**Comment by maggu2810** [comment]
It seems that
```
0 15 07 * * ?
```
works as expected.

But
``` 
* 0 15 07 ? * MON,TUE,WED,THU,FRI,SAT,SUN
```
does not work at all.

You agree that the expression should return the same result?

**Comment by kgoderis** [comment]
> You agree that the expression should return the same result?

yes, however, in the algorithm at https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/CronExpression.java#L869 the behaviour will be different. The first example will return the candidates collection, the second one is "specific", and will execute the method.

**Comment by maggu2810** [comment]
> you might be faster than me in fixing this

Hm, I don't think so, because it not only about "it has been a long time that I have been in the code" but only that I never dig into the code that deeply as you.

I created #3133 to reproduce the issue(s).
