### ISSUE TITLE
Group:Switch / Group:Contact: number of items not refreshed in UIs

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3141]
If you have such item with a %d in the label, you can notice that the value is not refreshed in Classic UI or HABdroid except when the group state is updated, that is number updated to 0 or number leaving 0.
To be even clearer. If you count your opened windows and you have 4 opened. You display the group item in UI, 4 is displayed. Then you close one window. You can see that the number remains at 4 in UI. It is updated only if you refresh the UI frame.

That is probably because there is no event produced with the updated number when the group global state is unchanged.

**Comment by resetnow** [comment]
Group dependency is not currently tracked — you can try implementing it here https://github.com/eclipse/smarthome/blob/3ae5d7b1b284f2bde6199bfe8dad950fd38cae39/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java#L156

**Comment by lolodomo** [comment]
In fact, PageChangeListener.constructSitemapEvents is called only when PageChangeListener.stateChanged is triggered.
Nothing is done when PageChangeListener.stateUpdated is triggered.

Consider a group of windows. If you open or close one of the windows without changing the group state, PageChangeListener.stateUpdated  is triggered and so no event is sent to UIs. If you open or close one of the windows and change the group state, PageChangeListener.stateUpdated and PageChangeListener.stateChanged are triggered.

So I assume we have to produce an event when PageChangeListener.stateUpdated is called and state is unchanged, at least for group items.

What is certain is that the problem is not inside each UI. They don't update because they receive nothing.

**Comment by lolodomo** [comment]
Maybe for group item, we should only consider PageChangeListener.stateUpdated and not PageChangeListener.stateChanged.

**Comment by lolodomo** [comment]
Please note the PR fixed Basic UI but not Classic UI.
It looks like it was already working in HABdroid but with a very slow update, as if there is a refresh mechanism implemented.
