### ISSUE TITLE
In Sitemaps LabelColor and ValueColor not working on Selection elements in BasicUI

### ISSUE THREAD

**Issue by geiststreicher** [eclipse/smarthome#3143]
I've defined the following switch:

`Switch hmvar_Presence "Presence" <parents_3_3> (gPresence) {channel="homematic:GATEWAY-EXTRAS-CCU2:ccu2:GWE00000000:1#Presence"}`

In my sitemap I tried to apply the following label colors:

`Selection item=PresenceString label="Presence" labelcolor=[hmvar_Presence==ON="green", hmvar_Presence==OFF="red"] mappings=[auto="auto", present="here", notPresent="not here"]`

The entry is shown without any labelcolor in the BasicUI.

It works perfectly in the ClassicUI, except that not only the label is colored, but the displayed selection entry, too. Though this might be by design (and is okay for me).

**Comment by lolodomo** [comment]
I will work on this issue to fix it.

**Comment by lolodomo** [comment]
I fixed the issue in Basic UI, distinguishing labelColor and valueColor.
I am waiting for my previous PR relative to Basic UI to be merged before submitting the fix.

By the way, the behavior in Classic UI has 2 bugs:
* the displayed value is not the mapped value.
* if you have only a labelColor defined, the value will inherit color from labelColor; if labelColor and valueColor are defined, the behavior is correct
I will take a look to Classic UI code in case I can find a quic
