### ISSUE TITLE
BasicUI compiled frontend files should not be commited to the repo

### ISSUE THREAD

**Issue by resetnow** [eclipse/smarthome#3145]
This is an old problem but lately more people started contributing to BasicUI, so it has become more noticeable. Currently minified js/css files are stored in the repository to avoid legal stuff. I think sooner or later we'll have to fix this, and to make it easier, I propose the following changes:

1. BasicUI uses grunt, but PaperUI already has approved gulp. In our case it doesn't really matter what to use, so grunt can be replaced with gulp.
1. This leaves the following packages for CQ:
    1. https://www.npmjs.com/package/gulp-less
    1. <s>https://www.npmjs.com/package/gulp-uglify</s>
    1. https://www.npmjs.com/package/gulp-eslint

(I also assume the whole node and npm build process uses approved components too)

**Comment by resetnow** [comment]
@kaikreuzer what do you think? If this is something you'd like to see implemented, it might be necessary to create legal review requests now so I can fix it later in the summer.

**Comment by kaikreuzer** [comment]
Makes sense! We have similar tooling already in place for the Paper UI, so I would hope that we do not need to create too many new CQs. Maybe @htreu can have a closer look and come up with a suggestion for the Basic UI (so that it is as close as possible to the Paper UI build mechanisms).

**Comment by resetnow** [comment]
I checked again and removed gulp-uglify — PaperUI already has it. This leaves two packages for CQ, the rest (including the build system) can be inherited from PaperUI. I think eslint would be useful for PaperUI too.

**Comment by kaikreuzer** [comment]
Sorry @resetnow, I completely lost track of this.
Do I understand it correctly that both gulp-less as well as gulp-eslint are only required at build time (i.e. they are downloaded by npm, used during the build and nothing of it gets packaged in our distributables)?

**Comment by resetnow** [comment]
Yes, that's right.

**Comment by kaikreuzer** [comment]
Thanks. Created CQ 13980.
Feel free to already prepare a PR that changes the Basic UI build accordingly!

**Comment by kaikreuzer** [comment]
Hey, the CQ has already been approved today! So go ahead and use gulp-less and gulp-eslint and all the rest you find in the Paper UI :-)

**Comment by resetnow** [comment]
Fastest CQ ever :) will try to come up with something over the weekend

**Comment by sjka** [comment]
If I'm not mistaken this is implemented by #4040
