### ISSUE TITLE
Circular reference while initializing StateDescriptionProvider

### ISSUE THREAD

**Issue by dragondagda** [eclipse/smarthome#3150]
Hi,

we're having an issue, that sometimes(1 out of 4) at startup a circular reference occurs while initializing StateDescriptionProvider. It seems that this circular reference is happening between ItemChannelLinkRegistry and ItemRegistry. We tried to change some configurations, but couldn't solve it.

That's what we tried:

- We used different esh versions: 0.9.0.b4 and 0.9.0-SNAPSHOT
- We used different karaf versions: 4.0.4, 4.0.8, 4.1.0
- We tried Felix aswell as Equinox (you can find the stacktraces attached for both [karaf: 4.0.8 and esh: 0.9.0-SNAPSHOT])
- We looked into the configuration files of openhab and tried to adjust ours to the openhab configurations

We saw the #2413 issue but we're not sure if it is related here. We are using automation bundles, but the error occurs in esh core.

If you need more information, just tell.

**Stacktraces:**
- [circular_reference_equinox.txt](https://github.com/eclipse/smarthome/files/847929/circular_reference_equinox.txt)
- [resulted_in_a_cycle.txt](https://github.com/eclipse/smarthome/files/847939/resulted_in_a_cycle.txt)

**Comment by dragondagda** [comment]
We're working with ESH 0.9.0.b5 now, but are still seeing this issue. Could somebody reopen this bug? Do you need another stracktrace?

**Comment by sjka** [comment]
> Could somebody reopen this bug? 

Of course.

> Do you need another stracktrace?

Sure, it would help - as there were some fixes done I'd expect the stacktraces have changed. So Iit would helpful to have them as I haven't seen it anymore myself lately.

**Comment by dragondagda** [comment]
There you go ;-) Thanks for reopening the issue.

[3150_stacktrace.txt](https://github.com/eclipse/smarthome/files/1130736/3150_stacktrace.txt)

**Comment by sjka** [comment]
I didn't yet looked deeper into the new errors. But on the first glance I noticed you are running on Felix and not on Equinox. Which of course is perfectly fine - it just might matter for the analysis.

**Comment by htreu** [comment]
As the JAXRS ResourceTracker is in the stacktrace `at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39)` this might very well be fixed by https://github.com/eclipse/smarthome/pull/4153.
@dragondagda could you please check again with the latest SNAPSHOT?

**Comment by kaikreuzer** [comment]
If it helps re-testing: Latest openHAB distro 1034 now contains this fix.

**Comment by dragondagda** [comment]
With Beta6 this service cycle didn't occur anymore (we tested with several (>30) restarts/deployments). Thanks for the fix!

**Comment by sjka** [comment]
Awesome, thanks for the feedback!
