### ISSUE TITLE
[Paper UI] Add-on title overlaps with upper-right icon in card view

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#3158]
In the add-ons card view the add-on title of some add-ons overlaps with the icon in the upper-right corner:
![image](https://cloud.githubusercontent.com/assets/616792/24081276/12c77c9e-0cb1-11e7-956f-d02ceea07325.png)

It seems that the automatic line break does not work correctly for all title variants.

**Comment by kaikreuzer** [comment]
Thanks, I wanted to create the same issue, you were faster ;-)

@aounhaider1 Can you fix that?
