### ISSUE TITLE
[Paper UI] Consider use of same height for all cards in add-ons view

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#3159]
The cards in the add-ons view are sorted from left to right and from top to bottom. If the marketplace client is installed the height of the cards differs quite a lot which leads to a confusing display, e.g.
![image](https://cloud.githubusercontent.com/assets/616792/24081330/d4cca88c-0cb1-11e7-9b5b-1dd3059e4c1c.png)
It would look better if all cards have the same height. If the description is too long for the card, we could display an ellipsis in the card on the complete description as a tooltip when hovering over the card.

**Comment by kaikreuzer** [comment]
What you are asking for is a grid layout, not a card layout.
Note that this layout has been chosen for browsing, not for searching - it should resemble more a catalog that you browse through; It uses the same design principle as e.g. Google+ here.

If you want a sorted presentation, you should rather go for the list view.

And if you only want to see marketplace content in the card view, simply type "market" in the search field.

For these reasons, I'd suggest to close this issue.
