### ISSUE TITLE
itemAdded called multiple times on RegistryChangeListener at boot

### ISSUE THREAD

**Issue by pdegeus** [eclipse/smarthome#3160]
Hi there,

I'm maintaining the ImperiHome IO add-on for openHAB and have an issue getting the item event listener stable when loaded at boot time of openHAB.

Consider the following code:

    public class TestAddon {
            
        private final Logger logger = LoggerFactory.getLogger(TestAddon.class);
    
        private ItemRegistry itemRegistry;
    
        private ItemProcessor itemProcessor;
    
        protected void activate() {
            logger.info("TEST - Addon activated");
            itemProcessor = new ItemProcessor(itemRegistry);
        }
    
        protected void deactivate() {
            itemProcessor.destroy();
            itemProcessor = null;
    
            logger.info("TEST - Addon deactivated");
        }
    
        protected void setItemRegistry(ItemRegistry itemRegistry) {
            this.itemRegistry = itemRegistry;
        }
    
        protected void unsetItemRegistry(ItemRegistry itemRegistry) {
            this.itemRegistry = null;
        }
    
    }

    public class ItemProcessor implements ItemRegistryChangeListener {
    
        private final Logger logger = LoggerFactory.getLogger(ItemProcessor.class);
    
        private final ItemRegistry itemRegistry;
    
        public ItemProcessor(ItemRegistry itemRegistry) {
            this.itemRegistry = itemRegistry;
    
            itemRegistry.addRegistryChangeListener(this);
            allItemsChanged(null);
        }
    
        public void destroy() {
            itemRegistry.removeRegistryChangeListener(this);
        }
    
        @Override
        public void added(Item item) {
            logger.info("TEST -- Item added: {}", logString(item));
        }
    
        @Override
        public void removed(Item item) {
            logger.info("TEST -- Item removed: {}", logString(item));
        }
    
        @Override
        public void updated(Item oldItem, Item newItem) {
            logger.info("TEST -- Item updated, old={} new={}", logString(oldItem), logString(newItem));
        }
    
        @Override
        public void allItemsChanged(Collection<String> oldItems) {
            logger.info("TEST -- allItemsChanged");
    
            for (Item item : itemRegistry.getItems()) {
                logger.info("TEST -- allItemsChanged item: {}", logString(item));
            }
        }
    
        private String logString(Item item) {
            return item.getName() + '@' + Integer.toHexString(System.identityHashCode(item));
        }
    
    }

When dropped into the 'addons' directory, this gives me the following log when freshly starting openHAB:

    2017-03-10 21:03:19.818 [INFO ] [org.openhab.io.test.ItemProcessor   ] - TEST -- allItemsChanged
    2017-03-10 21:03:27.174 [INFO ] [org.openhab.io.test.ItemProcessor   ] - TEST -- Item added: M_ENT_Temperature@3ac4d37c
    2017-03-10 21:03:27.388 [INFO ] [org.openhab.io.test.ItemProcessor   ] - TEST -- Item added: M_ENT_Temperature@328f69c5
    2017-03-10 21:03:27.659 [INFO ] [org.openhab.io.test.ItemProcessor   ] - TEST -- Item added: M_ENT_Temperature@10aacbc9
    2017-03-10 21:03:27.882 [INFO ] [org.openhab.io.test.ItemProcessor   ] - TEST -- Item added: M_ENT_Temperature@12f9dd16
    2017-03-10 21:03:28.148 [INFO ] [org.openhab.io.test.ItemProcessor   ] - TEST -- Item added: M_ENT_Temperature@61bd4d5

The 'added' method of the ItemProcessor is called 5 times for the same item, but with a different org.eclipse.smarthome.core.items.Item instance. There are no calls to 'removed' or 'updated' (as expected).
The log is filtered for one particular item; the same happens for all items in my system. 

My real add-on is adding a StateChangeListener to each item it's interested in. However, only the first Item instance provided to 'added' is really working and delivering state updates. 
This doesn't seem very stable or desirable. How should my add-on deal with this? Should I ignore repeated 'added' calls for the same item name? Is this a bug?

I'm using the current snapshot of openHAB 2. My items are in .items files, so not added with Paper UI.

**Comment by maggu2810** [comment]
I don't think this is the expected behavior.
The `added` notification should be called only once for one item.

**Comment by maggu2810** [comment]
```text
08:50:24.500 INFO  o.e.s.b.t.i.ItemListenerTest[:67] - TEST - Addon activated
08:50:24.501 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:47] - TEST -- allItemsChanged
08:50:27.726 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: Weather_Temperature@31cecf46
08:50:27.874 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoSwitchGroup@368b2fca
08:50:27.876 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoSwitch@68c102f
08:50:27.877 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoDimmer@4fa73eb7
08:50:27.877 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoRollershutter@7dbf9705
08:50:27.877 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoColor@12a50207
08:50:27.877 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoDateTime@744e6514
08:50:27.878 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoLocation@26aafac
08:50:27.878 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoString@36c075b
08:50:27.878 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoContact@39e3980b
08:50:27.879 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: Weather_Temperature@3e022ce6
08:50:28.016 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:37] - TEST -- Item removed: Weather_Temperature@31cecf46
```

I tried to reproduce your problem, but did not succeed.
Can you create a minimal example that demonstrate your problem?

You can e.g. continue mine: https://github.com/eclipse/smarthome/compare/master...maggu2810:demo-3160?expand=1

If I start this demo using the Eclipse IDE, the result looks as expected.

**Comment by pdegeus** [comment]
Thanks for looking into this! I had a big argument with Eclipse IDE trying to start your test and eventually gave up (sorry, I'm an IntelliJ guy).

However, I cloned my openHAB VM, messed around with my config and found a big clue: the issue does not occur with a single items file. When adding a second file, the items in the first file are 'added' to the listeners again. When adding a third items file, the items in the first and second file are repeated.

Can you verify this? I hope this would make it easier to pinpoint the bug.

**Comment by maggu2810** [comment]
You are right. It could be reproduced using multiple item files.

* demo1.items

```
Switch DemoSwitch1
```

* demo2.items

```
Switch DemoSwitch2
```

* demo3.items

```
Switch DemoSwitch3
```


This results into:

```text
09:42:56.340 INFO  o.e.s.b.t.i.ItemListenerTest[:67] - TEST - Addon activated
09:42:56.341 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:47] - TEST -- allItemsChanged

09:42:59.821 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:110] - Loading model 'demo2.items'
09:42:59.822 DEBUG o.e.s.m.i.i.GenericItemProvider[:150] - Processing binding configs for items from model 'demo2.items'
09:42:59.824 DEBUG o.e.s.m.i.i.GenericItemProvider[:129] - Read items from model 'demo2.items'
09:42:59.825 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoSwitch2@2e63582
09:42:59.832 INFO  smarthome.event.ItemAddedEvent[:43] - Item 'DemoSwitch2' has been added.

09:42:59.837 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:110] - Loading model 'demo3.items'
09:42:59.839 DEBUG o.e.s.m.i.i.GenericItemProvider[:150] - Processing binding configs for items from model 'demo3.items'
09:42:59.840 DEBUG o.e.s.m.i.i.GenericItemProvider[:129] - Read items from model 'demo2.items'
09:42:59.841 DEBUG o.e.s.m.i.i.GenericItemProvider[:129] - Read items from model 'demo3.items'
09:42:59.842 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoSwitch2@71f92d1a
09:42:59.843 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoSwitch3@4b8e23a6
09:42:59.843 INFO  smarthome.event.ItemAddedEvent[:43] - Item 'DemoSwitch2' has been added.
09:42:59.844 INFO  smarthome.event.ItemAddedEvent[:43] - Item 'DemoSwitch3' has been added.

09:42:59.850 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:110] - Loading model 'demo1.items'
09:42:59.851 DEBUG o.e.s.m.i.i.GenericItemProvider[:150] - Processing binding configs for items from model 'demo1.items'
09:42:59.851 DEBUG o.e.s.m.i.i.GenericItemProvider[:129] - Read items from model 'demo2.items'
09:42:59.851 DEBUG o.e.s.m.i.i.GenericItemProvider[:129] - Read items from model 'demo3.items'
09:42:59.851 DEBUG o.e.s.m.i.i.GenericItemProvider[:129] - Read items from model 'demo1.items'
09:42:59.851 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoSwitch2@7df559cb
09:42:59.852 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoSwitch3@e7f70b9
09:42:59.852 INFO  smarthome.event.ItemAddedEvent[:43] - Item 'DemoSwitch2' has been added.
09:42:59.852 INFO  o.e.s.b.t.i.ItemListenerTest$ItemProcessor[:32] - TEST -- Item added: DemoSwitch1@b5665d0
09:42:59.852 INFO  smarthome.event.ItemAddedEvent[:43] - Item 'DemoSwitch3' has been added.
09:42:59.853 INFO  smarthome.event.ItemAddedEvent[:43] - Item 'DemoSwitch1' has been added.
```

**Comment by triller-telekom** [comment]
@maggu2810 Thank you for your example branch. I could reproduce it and fix the bug.
