### ISSUE TITLE
JSON Field Type Mismatch in `/rules` Endpoint.

### ISSUE THREAD

**Issue by jvivanco28** [eclipse/smarthome#3168]
Hi,

It seems like there might be a JSON field type mismatch when hitting the `/rules` endpoint. 

When fetching the rules from `GET /rules`, sometimes the JSON response for a rule contains the field `"required": "false"` which I believe is meant to actually be a `boolean` (inside `Rule->Actions->Inputs`).

Steps:
- I created a new rule (containing just one trigger) with `POST /rules`. 
- Next, I updated that rule so that it would have a second trigger by calling the `PUT /rules/{ruleUID}` endpoint.
- After refreshing the list of rules by calling `GET /rules`, the newly updated rule JSON now contains the field `"required": "false"`. That field wasn't there prior to adding a second trigger.

Here's what the final JSON response looked like (scrapping out all of the unnecessary stuff).
`
{
...
	"actions": [{
		"inputs": {
			"required": "false"
		},
		"id": "2",
		"configuration": {},
		"type": "script.ScriptAction"
	}],
...
}
`

Is this intended, or a bug? The `/module-types` endpoint also uses the `Inputs` JSON schema, but that one actually sets the `"required"` field to a `boolean` instead of a `String`.

**Comment by kaikreuzer** [comment]
@danchom Could you have a look at that?

**Comment by danchom** [comment]
Ok I'll check this. 
> The /module-types endpoint also uses the Inputs JSON schema, but that one actually sets the "required" field to a boolean instead of a String.

The input's JSON Data returned by the /module-types endpoint is a meta data describing corresponding input. It is different from the input's JSON data returned for the action, which contains map of connected inputs this action i.e. {"input1":"module1.output1", "input2":"module2.output1" }.

**Comment by danchom** [comment]
I can't reproduce your problem. 
1) I've created a rule only with a trigger.
2) I use POST /rules to add it into rule registry
3) I use PUT /rules/ruleID to update the rule added in point 2. This time the payload contains a rule with same  ruleUID and two triggers only.
4) The result of GET /rules contains list of one rule with two triggers and no actions.

It is strange that you have added a rule with triggers but received a rule containing actions. Are you sure you are retrieving the same rule?

**Comment by danchom** [comment]
@jvivanco28  Could you please check this issue again and if possible show me a way to reproduce the problem.

**Comment by jvivanco28** [comment]
@danchom I can reproduce the issue by doing the following:

`PUT /rules/rule_1`
`{
	"conditions": [],
	"name": "A Test Rule",
	"triggers": [{
		"id": "1",
		"label": "an item state changes",
		"description": "This triggers the rule if an item state has changed.",
		"type": "core.ItemStateChangeTrigger",
		"configuration": {
			"itemName": "some_item_id"
		}
	}],
	"configDescriptions": [],
	"actions": [{
		"id": "2",
		"label": "send a command",
		"description": "Sends a command to a specified item.",
		"type": "core.ItemCommandAction",
		"configuration": {
			"itemName": "some_switch_id",
			"command": "ON"
		},
		"inputs": {
			"required": false
		}
	}],
	"uid": "rule_1"
}`

We were actually implicitly setting `Action#required = false` when updating the rule which I was unaware of at the time I posted first. Anyway, when we refresh the rule with `GET /rules/rule_1` the response assigns the `required` field as the string `"false"` instead of a boolean.

`GET /rules/rule_1` response:
`{
	"enabled": true,
	"status": {
		"status": "IDLE",
		"statusDetail": "NONE"
	},
	"triggers": [{
		"id": "1",
		"label": "an item state changes",
		"description": "This triggers the rule if an item state has changed.",
		"configuration": {
			"itemName": "some_item_id"
		},
		"type": "core.ItemStateChangeTrigger"
	}],
	"conditions": [],
	"actions": [{
		"inputs": {
			"required": "false"
		},
		"id": "2",
		"label": "send a command",
		"description": "Sends a command to a specified item.",
		"configuration": {
			"itemName": "some_switch_id",
			"command": "ON"
		},
		"type": "core.ItemCommandAction"
	}],
	"configuration": {},
	"configDescriptions": [],
	"uid": "rule_1",
	"name": "A Test Rule",
	"visibility": "VISIBLE"
}`

**Comment by maggu2810** [comment]
@danchom Currently the ActionDTO uses `Map<String,String>` for `inputs`. Could this be related to.

**Comment by danchom** [comment]
I think the @jvivanco28 is mix the 
ActionDTO and ActionTypeDTO where the inputs field is define as List<Input> objects and they are two different type of data. 

The ActionDTO represents a action instance part of rule. Its inputs field is a map of String keys and String values. This map shows where the inputs of action instance are connected to. For example it should be: "
{
 "input1": "trigger1.output2",
 "input3": "actionX.output1"
} 
which means the input1 of this action instance is connected to output2 of trigger1 instance of the same rule and the input3 of this action instance is connected to output1 of actionX instance of the same rule.

The ActionTypeDTO represents an ActionType automation object which provides meta data related to all action instances of this type. The data defines names, types, default values, if they are required or not and etc. of configuration properties, inputs and outputs for all instances of this ActionType.  
The input meta data is used by the automation engine to verify connections(types of connected input and output), to check if all required connections are set and etc.

When a new rule is created by the "PUT /rules/rule_1", the action instance must be specified (not action types). Actually you have specified  that the action instance "2", connects its input named "required" to module false. And normalization tries to fix you mistake and converts boolean false to "false" string. For that reason you retrieve different type of data.

I don't see a bug here.

**Comment by jvivanco28** [comment]
Yep. I think you're right. A bit of a mix up on our end differentiating between the Action and ActionType models.

Thanks for the quick and helpful feedback, guys. Very much appreciated!
