### ISSUE TITLE
Classic UI: page title containing item state is not updated

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3176]
If you open a frame linked to an item, the title at the top of the page display the item label with including its state. If the item state is then changed, the title is not updated.
Exiting the frame and re-opening it then oif course displays the correct title.

**Comment by triller-telekom** [comment]
This issue is related to #3175

**Comment by lolodomo** [comment]
I fixed this issue for Classic UI, it was easy compared to what must be implemented for Basic UI.

Note that if the linked item is a group with a function, the title will be updated only when the group state changes. So if your label indicates for example the number of opened windows, the title will change only when the value is going from non zero to zero or from zero to non zero. It is due to the fact the group state is not changed when the the number of opened windows is going for example from 1 to 2.

For a page linked to a standard item, the page title is updated as expected.

**Comment by lolodomo** [comment]
I have even fixed the case of the group item in the title. So this issue is fully fixed by my PR.
