### ISSUE TITLE
Security exception is thrown in AbstractEventFactory in security mode.

### ISSUE THREAD

**Issue by plamen-peev** [eclipse/smarthome#3179]
When I run the framework in security mode, Security Exception is thrown while an instance of a class that extends AbstractEventFactory  is created.
The problem is that the Declarative Services implementation which actually creates the instance does not have a permission to read `automation.esh.event.payload.enabled` system property.
The exception is thrown at this block of code:
`static {
        eshEventsPayload = Boolean.valueOf(System.getProperty(ESH_EVENTS_PAYLOAD, Boolean.FALSE.toString()))
                .booleanValue();
    }`.
Since I can't override a static block in a child class, I suggest to make the reading in a doPrivileged() method.
Are You ok with this ?

**Comment by danchom** [comment]
Sounds good for me. @kaikreuzer , @maggu2810  what do you think?

**Comment by maggu2810** [comment]
Need to have a look at the code. Don't know why we need to use a system property at all.

**Comment by danchom** [comment]
Actually  there is not such code in org.eclipse.smarthome.core.events.AbstractEventFactory. So there is no such problem.

**Comment by maggu2810** [comment]
If there is no such code available, then I don't understand the issue at all?
What should be changed in the current code base?
@plamen-peev Can you point me to the location you complain?

**Comment by plamen-peev** [comment]
It is my mistake.
I am looking at old source code.
