### ISSUE TITLE
Change to DayLigth saving Time causes stop in timerelated persistence strategies

### ISSUE THREAD

**Issue by JueBag** [eclipse/smarthome#3185]
As reported in the OH community ( [Link](https://community.openhab.org/t/openhab-not-saving-mesaurements-after-daylight-saving-time-change/25647)) the change to DayLigth Saving Time caused persistence schedules that are only using a time based strategy (everyMinute etc.) to stop at the time-switch.

Checks done on my side:
Actual values continued to be displayed.
The check of the database (rrd4j with a "everyMinute" strategy) showed the last value to be stored at the time-switch.
Several users confirmed that after restart of the OH-instance the time-scheduled persistence was working again. 
There is also an report on a cron based rule that stopped working, can't say if it is really related to the above.

**Comment by kaikreuzer** [comment]
@kgoderis This might be a bug in the cron scheduler, right?

**Comment by kgoderis** [comment]
@kaikreuzer most probably. I hope I can figure this one out, not sure how I will simulate a change in DLST over here.

**Comment by pdegeus** [comment]
Just found this issue after noticing my influxdb stopped collecting data at exactly 3:00 this Sunday.
If it helps, my log file shows this:
```
2017-03-26 03:00:00.018 [INFO ] [cheduler.ExpressionThreadPoolManager] - Expression '0 0 * * * ?' has no future executions anymore
2017-03-26 03:00:00.019 [INFO ] [cheduler.ExpressionThreadPoolManager] - Expression '0 0 * * * ?' has no future executions anymore
2017-03-26 03:00:00.024 [INFO ] [cheduler.ExpressionThreadPoolManager] - Expression '0 * * * * ?' has no future executions anymore
2017-03-26 03:00:00.028 [INFO ] [cheduler.ExpressionThreadPoolManager] - Expression '0 * * * * ?' has no future executions anymore
```

**Comment by kaikreuzer** [comment]
Any success @kgoderis?

**Comment by kgoderis** [comment]
@kaikreuzer No(t yet). As you have might have noticed I am quite absent lately due to an overload @ my businesses.

**Comment by kaikreuzer** [comment]
No rush - I know that you are waiting for any other things for me and I admire how you manage to do all that stuff despite of your businesses :-)
