### ISSUE TITLE
[REST/Persistence] API request for persistence items returns empty list

### ISSUE THREAD

**Issue by jn-se** [eclipse/smarthome#3186]
I installed two persistence extensions: rrd4j and InfluxDB.

A GET request to "/rest/persistence" returns the following result:

`[
  {
    "id": "rrd4j",
    "label": "rrd4j",
    "type": "Queryable"
  },
  {
    "id": "influxdb",
    "label": "influxdb",
    "type": "Queryable"
  }
]`

A GET request to "/rest/persistence/items?serviceId=rrd4j" and "/rest/persistence/items?serviceId=influxdb" returns an empty list with status code 200:

`[]`

Expected result: A list of all available items as defined in the *.rules file.

The data for a specific item is available at "/rest/persistence/items/{ITEMID}?serviceId=influxdb".

The behaviour can be reproduced with a clean install of openHAB 2.0.0.

**Comment by kaikreuzer** [comment]
Even without the query parameter, there are no results as can be seen at http://demo.openhab.org:8080/rest/persistence/items.
Clearly looks like a bug.

**Comment by sjka** [comment]
On a first glance it looks like this is a limitation of the compatibility layer: [QueryablePersistenceServiceDelegate](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/persistence/internal/QueryablePersistenceServiceDelegate.java#L91), or did I miss anything?

**Comment by jn-se** [comment]
Yes, found this line of code, too. But I'm not sure about the meaning because I'm not deeply involved in the source code. Can it be fixed easily?

**Comment by maggu2810** [comment]
The persistence REST interface works for me with a binding that does not use the OH1 compatibility layer.
The compat1x bundle is not part of ESH and so I don't think it is a bug in the ESH REST/SEE Persistence stuff.

**Comment by jn-se** [comment]
@maggu2810, which binding is working for you?

**Comment by maggu2810** [comment]
A h2 persistence implementation that is not part of the openHAB or ESH code base (realted to #1956, #2081)
