### ISSUE TITLE
SmartHome Designer use with openhub 2 on qnap ?

### ISSUE THREAD

**Issue by badplay** [eclipse/smarthome#3190]
Hey
i have installed openhub2 on a qnap with http://docs.openhab.org/installation/qnap.html

but i dont find a folder called config .... i have set up a shared folder directly in the root but it is empty :(

so what should i do??

**Comment by kaikreuzer** [comment]
Sorry, this is not at all an issue about Eclipse SmartHome - I'd suggest you go and seek for help at https://community.openhab.org/tags/qnap.
