### ISSUE TITLE
Yahoo Weather Control - Pressure measurement not in hPa

### ISSUE THREAD

**Issue by sveco** [eclipse/smarthome#3194]
Hi. I am using OpenHab2 and binding-weather - 1.9.0.b4, pressure reading are strange to say the least:
My weather.cfg:

> location.home.woeid=818717
> location.home.provider=Yahoo
> location.home.language=sk
> location.home.updateInterval=10

items:
Number 	 Pressure 	   "Tlak [%.1f hPa]"	<pressure>	{weather="locationId=home, type=atmosphere, property=pressure" }

It shows 34033.2 hPa, actual pressure is around 1005 according to yahoo page, 1009.14 on wxdata.weather.com. I suspect there is some problem with unit conversion, and I assure you I am not on the bottom of the sea. Any idea how to fix it?

**Comment by kaikreuzer** [comment]
This was supposed to be already fixed with https://github.com/eclipse/smarthome/pull/2511.
@sjka Could you check why there is still an issue with that?

**Comment by kaikreuzer** [comment]
Ah, sorry, just read:

> binding-weather - 1.9.0.b4

This is not at all about the Yahoo binding then, but about some old openHAB 1 binding. The correct issue tracker for you is hence https://github.com/openhab/openhab1-addons/issues.

**Comment by sveco** [comment]
Upgraded to latest build, and switched to Wunderground, problem solved.
