### ISSUE TITLE
Color Tag shuts down HomeKit

### ISSUE THREAD

**Issue by curryking1607** [eclipse/smarthome#3197]
Hello,
just a quick question, but I didn't want to spam it in the 1093 section.
As soon as I add the "Lighting" tag to a Color Item in my .items config,
the HomeKit service shuts down and appear on the iPhone as "No Response".
This problem is not new and the logs, but has never been solved.
Would be kind of you to quickly have a look.

https://community.openhab.org/t/homekit-bug-with-colorpicker/19190

Actually, @beowulfe has already taken part in 1651 (https://github.com/openhab/openhab2-addons/issues/1651).
But this issue was closed without a solution.

**Comment by kaikreuzer** [comment]
https://github.com/openhab/openhab2-addons/issues/1651 is still open and as this seems to be an issue with the HomeKit add-on and not with ESH, that is also the right place for the issue.
