### ISSUE TITLE
Default sitemap item disregards visibility parameter

### ISSUE THREAD

**Issue by pabloNZ** [eclipse/smarthome#3208]
https://community.openhab.org/t/sitemap-default-element-type-visibility-parameter/24802

Default sitemap items don't adhere to any visibility parameters.

**Comment by sjka** [comment]
I can reproduce this issue and I had a look into the code. It looks like several properties are not copied over from the "Default" placeholder widget into the concrete implementation. However, when trying to [quickly fix](https://github.com/sjka/smarthome/commit/2a2b6780f0b60449df31bc4af58ae3686f454d5a) this I stumbled upon the next related bug, so it requires some deeper analysis.

**Comment by lolodomo** [comment]
@sjka @kaikreuzer  : please close this issue, the merged PR #3471 fixed it.
