### ISSUE TITLE
Firmware properties

### ISSUE THREAD

**Issue by tomhoefer** [eclipse/smarthome#3209]
Currently the firmware domain object ```org.eclipse.smarthome.core.thing.binding.firmware.Firmware``` consists of the following meta information:
-uid
-vendor
-model
-description
-version
-prerequisiteVersion
-changelog
-onlineChangelog
-md5Hash

Now we have to support firmware updates that may lead to a factory reset of the device. For this reason we have to introduce additional meta information (e.g. requiresFactoryReset) for the firmware.

In order to avoid changes of the firmware domain object each time a new requirement pops up I would like to introduce firmware properties to specify additional (seldomly used) meta information which can be set by the ```org.eclipse.smarthome.core.thing.firmware.FirmwareProvider``` and might be used by the ```org.eclipse.smarthome.core.thing.binding.firmware.FirmwareUpdateHandler```

So I would like to introduce a ```Map<String, String> properties``` for the firmware domain object. Furthermore I would like to declare the property for requiresFactoryReset inside the firmware class. 

Do you have any concerns / remark?

**Comment by sjka** [comment]
I'm okay with your proposal, as long as these properties are more or less means to customize the behavior of the FirmwareUpdateHandler. Anything that might be of a concern for the user should still become a first-class field.

**Comment by triller-telekom** [comment]
@kaikreuzer this issue has been implemented in pr #3210. Can you please close it?
