### ISSUE TITLE
Move Astro binding from openHAB2 to ESH

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3213]
The [Astro binding](https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.astro) is a very useful binding, which is used by many openHAB users.
As it is not really a device integration, but rather a basic functionality that is useful for many use cases, I think it would be beneficial to make it a part of ESH itself and make it available to other solutions as well.
I therefore suggest to refactor its namespace and create a PR that moves the code to here. This has been also already discussed with @gerrieg, the main author of that binding.

**Comment by svilenvul** [comment]
Should we refactor [this PR](https://github.com/openhab/openhab2-addons/pull/1434) as well ?

**Comment by sjka** [comment]
yes, but wait until the binding actually moved (see https://github.com/openhab/openhab2-addons/pull/1434#issuecomment-292870324)
