### ISSUE TITLE
Show channels (optionally) in alphabetical order in Paper UI

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#3219]
On the "Things" configuration page in Paper UI the channels appear in in an unsorted order. If you have quite a large number of channels this is quite annoying because you permanently have to scroll up and down and search the channels that you want to configure.
In this example from the Homematic binding you can see the problem:
![image](https://cloud.githubusercontent.com/assets/616792/24830572/18c70262-1c89-11e7-8977-caa1d75947d1.png)
If would help if the channels would (at least optionally) appear in an alphabetical order sorted by the label text.

**Comment by kaikreuzer** [comment]
They should be sorted exactly in the order that is defined by the binding - this is done intentionally, so that a binding has a chance to sort them by topic/relevant/whatever.
So I would suggest you open an issue for Homematic to address this specifically in that binding.

**Comment by MHerbst** [comment]
@kaikreuzer I agree with you that the binding should be responsible for the order but I am not sure whether it is possible (at least in the case when the channels are created dynamically like in the Homematic binding). 
I have modified the implementation of the `ChanneltypeProvider` interface in the binding to return the channel types in a certain order (method `getChannelTypes`). But the order was ignored because the Method `ChannelTypeResource#convertToChannelTypeDTOs` stores the returned channel types in a HashSet.

**Comment by kaikreuzer** [comment]
> But the order was ignored because the Method ChannelTypeResource#convertToChannelTypeDTOs stores the returned channel types in a HashSet.

Well, this is then definitely something that I would consider a bug.

**Comment by MHerbst** [comment]
@kaikreuzer If you reopen this issue I could provide a clearer description or is it better to open a new issue?

**Comment by kaikreuzer** [comment]
I'd suggest a new issue.
