### ISSUE TITLE
Passing rules context with RunRuleAction

### ISSUE THREAD

**Issue by BenediktNiehues** [eclipse/smarthome#3227]
If a set of actions and/or conditions from ruleA are executed with the RunRuleAction from anoter ruleB it would be helpful to have the context of ruleB as executionContext for ruleA, too. Therefore the RunRuleAction should forward the rule context of the calling rule.

**Comment by BenediktNiehues** [comment]
PR for this: #3240

**Comment by danchom** [comment]
Merged by #3240
