### ISSUE TITLE
PaperUI does not respect limitToOptions=false

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#3246]
The configuration parameter dropdown is rendered as a list only and it's not possible to enter values other than those in the list.

**Comment by cdjackson** [comment]
My mistake - it does work, however once data is typed into the editbox, it's not possible to select from the list without emptying the editbox.

**Comment by htreu** [comment]
@cdjackson can this be closed then? I guess we should provide a new issue if the behaviour you described is not acceptable.

**Comment by cdjackson** [comment]
We can close it and open another if you prefer?

**Comment by htreu** [comment]
@kaikreuzer please close here. With #3555 merged we can describe the bug and create a new issue.
