### ISSUE TITLE
String Item auto creation: missing [%s] in label => no display in UI

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3248]
When you use channel auto linking, string items are created with a default label that does not contain a "[%s]" to display the item value.
In case the linked channel has no pattern defined, the result is that the item value is not displayed un UI when opening a page containing such a string item !
When the channel value is updated, Basic UI then updates the item value.

If I add a pattern "%s" to the channel, of course the problem is solved. But I suppose it is not mandatory to set a pattern on a "string" channel. The Sonos binding defines no pattern for channels for example.

If the item had a label with "[%s]" in its label, the problem would be solved.

So would it be ok to change automatic creation of string items in such a way ?

PS: I have not tested with channels linked to number items; maybe the problem is identical.

**Comment by lolodomo** [comment]
An alternative would be to enhance TextRenderer:renderWidget to get the value from itemUIRegistry.getState(w) when getValue(w) returns an empty string.

**Comment by lolodomo** [comment]
In fact, it can be fixed just by an update in the method AbstractWidgetRenderer:getValue(Widget w).
I will propose a fix.

**Comment by lolodomo** [comment]
The second alternative is OK for Basic UI but does not solve the problem for Classic UI and HABdroid. Apparently Classic UI and HABdroid are just never display the value of such items ! That is worst than Basic UI.
I never used "auto link" mode but I am very surprised that noone has discovered and fixed this major bug before.
So I think the real solution is to have a label with [%s] when the item is created.

**Comment by lolodomo** [comment]
@kaikreuzer : please comment (when you have time)

**Comment by lolodomo** [comment]
A third solution would be to consider a default pattern for any string channel. The change to do is in the method ItemUIRegistryImpl:getLabel(Widget w). Compared to my first solution, this solution would avoid creating again every items.
I am sure this solution would fix Basic UI, I can test it to verify that it fixed Classic UI and HABdroid too.

**Comment by lolodomo** [comment]
I tested the last solution and it fixed all UIs (Basic UI, Classic UI and HABdroid).

**Comment by lolodomo** [comment]
So I propose to replace this block https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java#L287
by
```
                if (getFormatPattern(label) == null) {
                    final StateDescription stateDescription = item.getStateDescription();
                    if (stateDescription != null) {
                        final String pattern = stateDescription.getPattern();
                        if (pattern != null) {
                            label = label + " [" + pattern + "]";
                        }
                    } else if (item.getClass().equals(StringItem.class)) {
                        // We consider a default pattern for string items
                        label = label + " [%s]";
                    }
                }
```
If my solution is validated, we can think if other item types needs a default pattern too. NumberItem ?

**Comment by kaikreuzer** [comment]
> @kaikreuzer : please comment (when you have time)

Sorry, didn't find any time yet and as you noticed, this is a complex topic...
Only added some remark on the PR just now: https://github.com/eclipse/smarthome/pull/3262#issuecomment-295134213

**Comment by lolodomo** [comment]
@kaikreuzer : I think the correct approach and fix would be to update the item label for the item created automatically by the code in order to include the value (add "[%s]" in the label). Is it ok for you ?

**Comment by lolodomo** [comment]
Not obvious to find where is done the automatic creation of item :(

Just to eliminate one solution: is it normal to have no state description with a pattern for a channel ?

**Comment by maggu2810** [comment]
> Not obvious to find where is done the automatic creation of item :(

What about: https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java#L41

**Comment by lolodomo** [comment]
Thank you.
I will propose a fix.

**Comment by lolodomo** [comment]
I realized yesterday that there is nothing really blocking, any user can define a label with a pattern for the text element in the sitemap.
