### ISSUE TITLE
Unable to Convert From Celsius to Fahrenheit

### ISSUE THREAD

**Issue by NolanGarrett** [eclipse/smarthome#3252]
I have multiple Z-Wave devices that report temperature. They all report in Celsius. If you change to Fahrenheit and save, then go back to the device, it is reset to Celsius. After opening a ticket regarding the binding/HABmin2, I was instructed this is likely an ESH issue and to open a bug report here.

**Comment by mhilbush** [comment]
I ran into this as well with HABmin.  Did you try setting the scale using PaperUI?  I just did that and it worked on three different device types.  Try PaperUI and report back.  It you can set it using PaperUI, but not HABmin, it's likely a HABmin issue.

**Comment by NolanGarrett** [comment]
You are correct, PaperUI works fine. Closing this out.
