### ISSUE TITLE
Paper UI: Rollershutter buttons do not work

### ISSUE THREAD

**Issue by markusjw** [eclipse/smarthome#3257]
I have the following problems with the Rollershutter widget in Paper UI (Control view):
- The buttons (up, down, stop) do not result in any commands sent to the thing channel.
- The read-only widget does not seem to show the correct value, at least not with the right formatting

The following features work for me:
- Entering a manual shutter level results in a command to the channel.
- Setting the item type to read-only removes the buttons and sometimes shows the value (without formatting).

I don't know if the rollershutter support is final or "work in progress". If there is more to be done, we could discuss this in the forum:
https://www.eclipse.org/forums/index.php/t/1085092/

**Comment by maggu2810** [comment]
> The buttons (up, down, stop) do not result in any commands sent to the thing channel.

Which browser do you use?

@aounhaider1 Is this a known issue?

**Comment by markusjw** [comment]
I am using Firefox 52.0.2

**Comment by markusjw** [comment]
The behaviour is the same in Chrome.
More precisely: The up/down buttons change the shown value to 0 or 100%, but do not result in a command.

**Comment by aounhaider1** [comment]
I will check it.

**Comment by aounhaider1** [comment]
Seems to be working. This is the ESH consolse log.
<img width="925" alt="screen shot 2017-05-02 at 11 01 21" src="https://cloud.githubusercontent.com/assets/5161937/25612654/d589b520-2f2b-11e7-8ab9-51858d434154.png">

```The read-only widget does not seem to show the correct value, at least not with the right formatting```
Can you please describe what is not correctly shown (the expected and show value)? Also a screenshot of wrongly formatted value would be nice.

**Comment by markusjw** [comment]
Concerning the formatting:
This is the item type configuration:
```
	<channel-type id="readOnlyShutterLevel">
		<item-type>Rollershutter</item-type>
		<label>Real shutter level</label>
		<description>The real current shutter level</description>
		<category>Blinds</category>
		<state min="0" max="100" step="1" pattern="%.1f %%" readOnly="true" />
	</channel-type>

	<channel-type id="shutterLevel">
		<item-type>Rollershutter</item-type>
		<label>Virtual shutter level</label>
		<description>The (controllable) virtual shutter level</description>
		<category>Blinds</category>
		<state min="0" max="100" step="1" pattern="%.1f %%" />
	</channel-type>
```
When both items (the linked channels) are set to 100.0, they show this:
![2017-05-03 paper ui rollershutter item number format](https://cloud.githubusercontent.com/assets/19324427/25651470/8c0c2d3e-2fe3-11e7-9518-8a8baaa6bffb.png)

**Comment by markusjw** [comment]
@aounhaider1 Thanks for the commit.
What if no pattern is given? In that case I experience the same behavior as with the config above: a percent sign is shown unless the Rollershutter item is read-only.

**Comment by markusjw** [comment]
Update: There is no problem with the buttons. I ran into that because of two reasons:
- I am not getting the log output shown above.
- I ignored the UpDownType and StopMoveType because value is empty. That was my fault.
