### ISSUE TITLE
[ThingStatus] Some invalid transitions (eg from ONLINE to UNKNOWN) are not propagated

### ISSUE THREAD

**Issue by mdicke2s** [eclipse/smarthome#3261]
If a client requests a transition to UNKNOWN from a source state other than INITIALIZING, the transition is not executed (which is absolutely correct since the transition graph does not allow this). Actually in the code there is just a 'return' statement, so that the client doen't get any respond on what happened.

Therefore I suggest to change the code:
ThingManager#statusUpdated() should throw an appropriate exception to signal that the requested transition is not allowed and was not executed.

**Comment by sjka** [comment]
I agree, swallowing them silently is a little surprising...
A log statement would be another option, but I tend to agree that we should do it "the hard way" in order to make clear that the API was used in a way which is not anticipated.

**Comment by maggu2810** [comment]
I agree with the hard way and throwing an exception.
