### ISSUE TITLE
Some issues with the archetype

### ISSUE THREAD

**Issue by martinvw** [eclipse/smarthome#3270]
There are some issues with the archetype, I'm planing on fixing them, but if there are others please let me know:

- I see that the Handler example contains a mix of tabs and spaces
- I see that the Handler example contains an outdated copyright header
- The xml files in the ESH-INF directory are not indented with tabs but with spaces, I believe the XML files should be indented with tabs.
- the build.properties is missing the about.html
- the about.html file is missing

**Comment by kaikreuzer** [comment]
> the build.properties is missing the about.html

Please note that the about.html needs to be configurable as the [openHAB 2 script](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/create_openhab_binding_skeleton.sh) requires a different version than the ESH one.

**Comment by martinvw** [comment]
Thanks for the reminder!

**Comment by martinvw** [comment]
How are you about returning null, I would really like the `HandlerFactory.createHandler` to return an exception instead of null. Why?

http://www.yegor256.com/2014/05/13/why-null-is-bad.html

Another reason is that the case always means a programming error, because the framework had the responsibility to check `supportsThingType` and if that returns `true`  while `createHandler` can't handle it we have an issue.

**Comment by martinvw** [comment]
Should the `about.html` contain the (dynamic) current date?

**Comment by martinvw** [comment]
Intellij marks this part of `pom.xml` unneeded, because it's inherited.
```xml
<groupId>org.openhab.binding</groupId>
``` 

Can I remove it

**Comment by kaikreuzer** [comment]
> How are you about returning null, I would really like the HandlerFactory.createHandler to return an exception instead of null.

I would move this discussion out from this issue since if we decide to change the current implementation, we should also address existing handler factories accordingly.

> The date in the about.html files must be changed to the current.

Where did you find this sentence? For the [Eclipse about.html](https://www.eclipse.org/legal/epl/about.php), it is actually June 5, 2006 as a fixed date. Afaik, it is the date of this about text has been last modified. Only the "Third-Party Content About File Template" asks people to actually update the date (as they also modify the content of the file).

> Can I remove it

yes

**Comment by martinvw** [comment]
Makes sense to move out the discussion :-)

about the date:

[openHAB B.2](http://docs.openhab.org/developers/development/guidelines.html#b-osgi-bundles)

> Every bundle must contain an about.html file, providing license information. If there is a third-party software in the bundle, its licence information must be added to the bundle’s about.html file. You can look at and use these two examples: about.html without 3rd party licence information and about.html with 3rd party licence information. The date in the about.html files must be changed to the current.

**Comment by kaikreuzer** [comment]
> The date in the about.html files must be changed to the current.

Maybe this should be weakened to "should be update, if the file content is changed".

**Comment by martinvw** [comment]
What do you think of this?

> Every bundle must contain an about.html file, providing license information. If there is a third-party software in the bundle, its licence information must be added to the bundle’s about.html file and the date in the about.html files must be changed to the current. You can look at and use these two examples: about.html without 3rd party licence information and about.html with 3rd party licence information. .

**Comment by martinvw** [comment]
@kaikreuzer since there seems to be no proper way to use an external file for the archetype generate I thought about adding a copy file command in both the windows and *nix script for openHAB and putting the default file here. Can you agree on that?

**Comment by kaikreuzer** [comment]
> Can you agree on that?

Yes!
