### ISSUE TITLE
Intropduction of a common filtering API

### ISSUE THREAD

**Issue by ViToni** [eclipse/smarthome#3281]
While working on the Automation part of ESH (https://github.com/eclipse/smarthome/issues/2921) the idea came up to introduce a filtering approach to the RuleRegistry (see https://github.com/eclipse/smarthome/issues/2921#issuecomment-285375056).

However a change such as a filtering API might be better provided in a more general way and in a central place so it's available project wide and not only in the automation part.

- The idea to use Java8 [`Predicate`](https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html)s seems out of scope as parts of ESH must be available in Java 1.5 environments.
- Another approach would have been to make use of Google guava library with its [`Predicate`](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Predicate.java)s but this would introduce a dependency to `guava` in the public API.
- So it might be reasonable to implement an independent solution for ESH.

The questions are:
1. What would be a good solution for ESH?
2. Where would be the place for such a filtering API?

**Comment by sjka** [comment]
> The idea to use Java8 Predicates seems out of scope as parts of ESH must be available in Java 1.5 environments.

Why don't these "parts" then bring their own `Predicate`? I would prefer not re-inventing yet again another wheel...

**Comment by kaikreuzer** [comment]
> Why don't these "parts" then bring their own Predicate? 

If we add a new method to `Registry`, we cannot make a difference between the "parts" - it should be the same API for them all. And introducing our own `Filter` class could also directly refer to the types of the Registry and offer ESH specific methods that we want to allow for such a filter.

**Comment by maggu2810** [comment]
I would prefer also the Predicate of Java 1.8 but I see the point that it cannot be used for the automation because of its limitation to Java 1.5

@kaikreuzer You pointed out an interesting topic. Ever base class or every API of the core that is used by automation stuff is limited to the 1.5 feature set, too.

**Comment by danchom** [comment]
The Automation is not 1.5 compatible from a long time ago.  As I remember @kaikreuzer said that we can't obligate contributors to write 1.5 compatible code when the ESH is 1.7 compatible and we agreed with him. At the moment the automation module is 1.7 compatible. Now the situation is the same. If we use the 1.8 Predicate we will lose the support of some jvms as skelmir, but on the other hand, there are a lot of other interfaces in the java.util.function which can be used with lambdas and I think it is not good idea to duplicate all of them. So I'm agree that the 1.8 predicate can be used.

**Comment by sjka** [comment]
Hey, that's pretty good news! Would you please update https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/guidelines.md#c-language-levels-and-libraries then accordingly?

**Comment by kaikreuzer** [comment]
Indeed good news that I also wasn't aware of - my last knowledge was that while contributors might write Java 1.7 code, you will make sure to do follow-up PRs that will port it down to 1.5.
If we can agree in general to allow Java8 CP2 compatible code for the automation engine (just like it is for the rest of ESH), it would be a huge relief and definitely helpful for having consistency within our project.

**Comment by maggu2810** [comment]
Great news (not for you but at least for @sjka, @kaikreuzer and me) @danchom 
:+1:

**Comment by danchom** [comment]
>Java 1.7 code, you will make sure to do follow-up PRs that will port it down to 1.5

Yes this was the plan, but its hard to back port the code which is out of automation module. We have also decided to accept code containing guava lib for the same reason.

**Comment by ViToni** [comment]
Definitely great news to go beyond Java 1.5. 

As far as I understood Java 1.8 (compact2) is the new baseline.

If my understanding is correct I would create a separate PR regarding some common `Predicate`s for Rules, but now base on Java 1.8 `Predicate`s.

**Comment by maggu2810** [comment]
> I would create a separate PR regarding some common `Predicate`s for Rules, but now base on Java 1.8 `Predicate`s.

:+1:

**Comment by ViToni** [comment]
Regarding the `common filter APi` I would introduce  a `stream()` method into the `Registry` and provide a default implementation for `AbstractRegistry`.

This approach makes a filterable `Stream` available without being invasive to exiting code.

**Comment by kaikreuzer** [comment]
@danchom & @maggu2810: This idea has been discussed with @sjka and myself, and we came to the conclusion that his is probably the most modern and flexible way to provide filtering possibilities on all registries. After all, Java8 stream API is meant exactly for such purposes.

Let us know what you think and if you have any concerns.

**Comment by ViToni** [comment]
As reference here is the PR that shows the needed changes: https://github.com/eclipse/smarthome/pull/3355

**Comment by danchom** [comment]
Sounds good to me.

**Comment by maggu2810** [comment]
No concerns

**Comment by ViToni** [comment]
Issue closed (and resolved) due to the merge of the of https://github.com/eclipse/smarthome/pull/3355 in general (since streams support filtering) and in special by the merge of  https://github.com/eclipse/smarthome/pull/3698 which provides some `Predicates` for filtering `Rule` streams.
