### ISSUE TITLE
Basic UI: text element updated when not expected

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3294]
When receiving a SSE event, Basic UI frontend takes the value from the label when the label contains something betwen []; if not, the value is the state value itself.
https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js#L1624
But if the backend does not provide something between [] it might be because we don"t want a value displayed. That is the case for example for a string item without [%s] in label (and a channel without pattern / state description).
I am sure there was a reason for that piece of code in frontend but I don't find it and I don't understand why the frontend overrides what is provided by the backend.

**Comment by lolodomo** [comment]
@resetnow : this is for you ;)

**Comment by resetnow** [comment]
I don't think I understand the problem. If there is no label with format defined in the sitemap, item state sill be displayed «as is». If there is a label format, there is this hack with []. Could you please explain what behaviour is expected here?

**Comment by lolodomo** [comment]
I think there are two subjects.

First is: shall we display a state if there is no format in label in all circumstances? For example for a standard group, I think the answer is no.

Second is that when you open a page, the backend is displaying no value if the item label does not comtain a format but later the frontend displays one value when receiving a SSE event. It is not consistent. We can discuss if the problem is on backend or frontemd.

**Comment by lolodomo** [comment]
Note that only channels without pattern in state description are concerned.
If a patern is defined for the channel, it will be used.

**Comment by lolodomo** [comment]
And third sunject: maybe a different snippet without value should be used for standard groups ?

**Comment by maggu2810** [comment]
> shall we display a state if there is no format in label in all circumstances?

I assume this is not related to BasicUI only but should be defined as a common concept for all UIs.

**Comment by lolodomo** [comment]
@maggu2810 : yes a general discussion would be appreciated for the first subject.

Until now, considering classic UI, basic UI and HADroid, basic UI is the only UI to force the display of the state on a page update. There is no such problem with Classic UI and HABdroid.

To be clearer, what is additionally very annoying in basic UI is the inconsistency between page loading and page refresh.

**Comment by wborn** [comment]
There are a lot of examples in README.md files where labels are omitted for simplicity. So if the behavior changes these will also need to be updated. Because of these examples, there will also be users who use items without labels.

**Comment by lolodomo** [comment]
I will fix the problem of consistency in Basic UI between the page loading and the page refreshing.
