### ISSUE TITLE
UpDownType should include a neutral position

### ISSUE THREAD

**Issue by n-kristev** [eclipse/smarthome#3297]
I am currently working on a binding, and one of the devices is a blinds actuator. The `RollershutterItem`  class is the default class used for blinds, and it is using the `UpDownType` for its current blinds direction state.

However, there is a problem: a blinds actuator actually has 3 states (not moving, up, down), while the `UpDownType` only has `UP` and `DOWN.` At the moment I am working around this by having the Not Moving state set as  `UnDefType.UNDEF`. However, this introduces an element of incertanity (why is the state undefined - an error or normal operation?) and additionally confuses the UI, as the `PercentType` component of `RollershutterItem` is updated correctly with the current position of the blinds, so the users sees something like "UNDEF/XX percent". 

For me it would make sense to add a new state - `NOT_MOVING` - to the posible states for `UpDownType`. What do you think?

**Comment by maggu2810** [comment]
The rollershutter item supports this types:
* PercentType
* UpDownType
* UnDefType

and this commands (+ RefreshType):
* UpDownType
* StopMoveType
* PercentType

If we look at the `setState` function we will see that every state that is set and is an instance of a convertible one, will be transformed to a percent type.
So, it seems if you set "up" or "down" as a state to signal the rollershutter is currently moving, the state is already converted to 0 for up and 100 for down.
So, `up` as a command is meant to move to position `0` and if you set this state, the user "see" that the rollershutter is at position zero...

There is also the stop move command. Stop makes sense if you know that the rollershutter is currently moving. As the state does not signal "I am moving up" or "I am moving down", this makes only sense if you "see" the real rollershutter is moving.
To send "move" as a command is perhaps not really useful without direction (except you define that the direction toggles).

@n-kristev After reading this I don't know how the item should be correctly used (wrt. to up down stop move).

**Comment by n-kristev** [comment]
@maggu2810 So it would like like the problem is that the shutter item state is ambiguous as it is currently defined. On one hand it shows the current position of the blinds, and on the other it also shows the direction they are moving. 
It would seem like the state should be made to some kind of a compound type, which includes movement status (up/down/static), and current position.

**Comment by kaikreuzer** [comment]
The state simply describes the current position and not any transition. We also do not have information for Dimmers, whether they are currently being turned on or off or for Temperature values whether they are going up or down.
If you really need additional information about movement direction (and maybe even speed?), I would think that this should be modelled in additional channels.

**Comment by n-kristev** [comment]
I think I understand now, so the `UpDownType` in the state indicates only that the blinds are in top/bottom position, not that they are currently moving. 
@kaikreuzer  Does this mean that I should not try to set `UpDownType` in the state through my binding at all?

**Comment by kaikreuzer** [comment]
When you set the state to UP or DOWN, this simply translates to 0% and 100% - so if this is what you intend, you can set the state, otherwise, better don't :-)

**Comment by n-kristev** [comment]
OK, thanks for clarifying this. Maybe a small comment in `RollershutterItem` would be helpful in the futire (I have created a pull request, feel free to discard it if you think it is not needed).
