### ISSUE TITLE
Sitemap: Feature request chart period

### ISSUE THREAD

**Issue by Auto-Mark** [eclipse/smarthome#3299]
Currently the sitemap supports charts with some fixed periods:
[http://docs.openhab.org/configuration/sitemaps.html#element-type-chart](url)

In my application it would be helpful to view the data of the last 48 hours which is not included in the list of valid periods.

So it would be nice if the sitemap also supported the period 48h or 2D.

Thanks a lot.

**Comment by lolodomo** [comment]
I will add the two days choice.
