### ISSUE TITLE
Reusable cache util

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3302]
As we have seen in eclipse/smarthome#2809 and now also in https://github.com/openhab/openhab2-addons/pull/1543, it would be useful to have little a utility to easily build a small cache. While guava offeres a nice one in some versions, it turned out it's not feasible for us to use because we'd need to update guava to a newer version (see #2801 why this is not a good idea). 
Therefore I suggest to (maybe) pimp the little [ExpiringCache](https://github.com/eclipse/smarthome/blob/3ae5d7b1b284f2bde6199bfe8dad950fd38cae39/extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/internal/ExpiringCache.java) from the yahoo weather binding a little and make it available as an API from the core.

**Comment by kaikreuzer** [comment]
Sounds useful, especially as those implementations do not belong in bindings.

**Comment by kaikreuzer** [comment]
With https://github.com/openhab/openhab2-addons/issues/2009, I just came across another issue, where it would be tremendously helpful to have that feature available in the ESH core.

@cweitkamp Would you maybe be interested in addressing this?

**Comment by cweitkamp** [comment]
@kaikreuzer Thanks for suggesting me as potential participant for this implementation. Of course I want to help you with this. I am going to start working on it next weekend.

**Comment by kaikreuzer** [comment]
Great, thank you! 
A good package for it might be `org.eclipse.smarthome.core.common`, but feel free to come up with any better suggestions and improvements to the implementation from @sjka :-)

**Comment by cweitkamp** [comment]
PR #3572
