### ISSUE TITLE
REST Endpoints documentation page has no content.

### ISSUE THREAD

**Issue by dushanlk** [eclipse/smarthome#3304]
No content available in this page, http://www.eclipse.org/smarthome/rest/index.html
But [here](http://www.eclipse.org/smarthome/documentation/features/rest.html#rest-endpoints) asking to visit.

**Comment by kaikreuzer** [comment]
Works for me on both Chrome and Safari. Do you have any browser plugins installed that might block the Javascripts?

**Comment by maggu2810** [comment]
Works for me, too.

**Comment by sjka** [comment]
Me too. Takes a moment though to load/render. Patience you must have 😉

**Comment by dushanlk** [comment]
Hi All,

I have no any third party extensions on browsers to block JavaScript. I tried on Chrome, Firefox and Safari, still not getting the content. It prints some access control error in the browser console.

`XMLHttpRequest cannot load https://www.eclipse.org/smarthome/rest/swagger.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.eclipse.org' is therefore not allowed access.
index.html:278 Unable to Load SwaggerUI
swagger-ui.min.js:2 Uncaught Can't read from server.  It may not have the appropriate access-control-origin settings.` 

Any solution? :)

**Comment by kaikreuzer** [comment]
The most obvious solution is to use https://www.eclipse.org/smarthome/rest/index.html, right?

**Comment by dushanlk** [comment]
Oh, Thanks a lot @kaikreuzer, :+1:  Unintentionally I was using without HTTPS. Hope we better to have auto HTTPS append on `http://www.eclipse.org` domain. Thanks all, Regards.
