### ISSUE TITLE
BasicUI: Images and Charts not updating according to Configuration

### ISSUE THREAD

**Issue by Auto-Mark** [eclipse/smarthome#3308]
There's been a discussion in the community about images and charts not updating as expected:
https://community.openhab.org/t/basic-ui-image-refresh-rate-in-seconds-instead-miliseconds/27152

Some tests suggest that the refresh parameter is interpreted differently:
* ClassicUI: milli sec
* BasicUI: sec

**Fix**: Use same time base for all UIs

Also, in my own setup the update works only on images not on charts.
The chart initially loads in BasicUI but then instead of updating it shows a broken image symbol.

**Comment by kaikreuzer** [comment]
It should be a value in milli secs, see [here](http://docs.openhab.org/configuration/sitemaps.html#element-type-chart).

So I would say that it is a bug in the Basic UI. @resetnow, Would you agree?

**Comment by resetnow** [comment]
Yes, it's a bug, value is multiplied by 1000 in BasicUI. Obvious fix but I think we need to set a lower limit (50 ms?) to avoid accidental request spam.

**Comment by kaikreuzer** [comment]
Yes, a lower limit makes sense. 50ms sounds sensible to me, maybe even 100ms.

**Comment by Auto-Mark** [comment]
Using basicUI CalDAV also is not updating. Maybe this is related to the issue described here:
[https://github.com/openhab/openhab1-addons/issues/5170](https://github.com/openhab/openhab1-addons/issues/5170)
And maybe the weather binding not updating is also connected to this:
[https://github.com/openhab/openhab-distro/issues/447](https://github.com/openhab/openhab-distro/issues/447)

**Comment by lolodomo** [comment]
I proposed a fix, setting the minimum value to 100 ms.

**Comment by Auto-Mark** [comment]
According to a user the behaviour hasn't changed:
[community.openhab.org](https://community.openhab.org/t/basic-ui-image-refresh-rate-in-seconds-instead-miliseconds/27152/8)

**Comment by lolodomo** [comment]
Normal, it is not yet included in OH snapshots. You will have to wait few days, the time for kaikreuzer to include a new ESH version in OH. The last is from the 12th of May.

**Comment by kaikreuzer** [comment]
You can always check here, which changes are already included in openHAB: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/changes

**Comment by Auto-Mark** [comment]
Thanks for this clarification. I will do so in the future.

**Comment by lolodomo** [comment]
Please note that refresh intervals look like inappropriate for charts in the demo sitemap:
```
				Switch item=Weather_Chart_Period label="Chart Period" icon="chart" mappings=[0="Hour", 1="Day", 2="Week"]
				Chart item=Weather_Chart period=h refresh=600 visibility=[Weather_Chart_Period==0, Weather_Chart_Period=="NULL"]
				Chart item=Weather_Chart period=D refresh=3600 visibility=[Weather_Chart_Period==1]
				Chart item=Weather_Chart period=W refresh=3600 visibility=[Weather_Chart_Period==2]
```
I am not sure but my first feeling is that these values are in seconds rather than in milliseconds ?
