### ISSUE TITLE
Handling exceptions from the schedulers

### ISSUE THREAD

**Issue by martinvw** [eclipse/smarthome#3325]
I think that it is a pity that at this moment (almost) every Runnable in openHAB (and most likely the also in the Eclipse Smarthome) contain a `catch Exception` and some (even) contain a catch Throwable. But this should imho not be a responsibility of the bindings, their code should be clean and straight forward. 

One of the many examples is this one (chosen because its the first binding in the list): https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/handler/AirQualityHandler.java#L120

However I would like to make the framework responsible for this, there are a few solutions for this:

1. Handle them in the [`ThreadPoolExecutor.afterExecute`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#afterExecute(java.lang.Runnable,%20java.lang.Throwable)) [example](http://blog.kavinyao.com/2014/11/java-thread-pool/#gist14515810)
2. Implementing a `ThreadFactory` and registering the `UncaughtExceptionHandler` [example](http://farenda.com/java/java-uncaughtexceptionhandler-executorservice/)
3. Something custom with wrapping the runnables, a minor benefit as that we could really tailor the logging for example to log from the runnable class.

I was really curious how you feel about this subject, so please let me know.

Note that it is also considered on a list of secure coding habits: https://www.securecoding.cert.org/confluence/display/java/TPS03-J.+Ensure+that+tasks+executing+in+a+thread+pool+do+not+fail+silently

**Comment by sjka** [comment]
Thanks for bringing up this topic. Indeed, it's a good idea!

Probably I'd use the first option, as it is straight-forward and you have the Runnable at hand, hence you can get a logger for it. So I don't see a need for the third option. However, I don't have any strong feelings about it. 

Another question would be: What do you want to do then? Of course, logging the error. But afaik most handlers then also take some action on their Things, i.e. set them to OFFLINE/... How should this be done? If you want to do it also in the generic exception handling, then you ought to make sure that this doesn't interfere with all the other usages of the scheduler as t is heavily used by the framework itself too. On the other hand, if that's not done centrally, then the bindings still need to catch exceptions and nothing is won.

**Comment by martinvw** [comment]
Nope I agree that option 3 does not add too much value, I started out with the third option in head but realised that the JDK already offered us some more standard solution for it.

Regarding changing the status, yes we could consider but I think that to do the properly we should wrap the ExecutorService and we would still have a problem with calling the protected `updateStatus` from the extended ExecutorService. 

So I do not think that it should take the status update 'burden' away. But it makes sure that there is at least some logging if the thread fails unexpected instead of the current (JDK default) of silently failing (repeated) tasks. Also code only catching and logging the exception could be removed which cleans up a lot of code in openHAB, although we could also consider to check for each of them whether they may require a status update.

**Comment by kaikreuzer** [comment]
Sounds like a good thing to address.
Just one remark: The current ESH QueueingThreadPoolExecutor has been implemented, because there wasn't anything similar available in Java 7. In Java 8 though, there are [new thread pool implementations](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newWorkStealingPool-int-) that might be worth a look whether they could be a replacement for the ESH implementation.

**Comment by martinvw** [comment]
Looking at the current implementation I would even say that option 2 makes the most sense since we already have our own ThreadFactory:

https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/QueueingThreadPoolExecutor.java#L215

Regarding switching to another executor, that requires some more thinking and maybe discussion. I'll try to read up about our current implementation and the one you referenced.

**Comment by martinvw** [comment]
Just a few nights ago I realised something important (with respect to this issue) if we handle the logging of the exception outside of the actual runnable, we still terminate the repeated tasks so I think a combination of 2 & 3 can be the only real solution. I will try to create a WIP PR in the upcoming week.

**Comment by martinvw** [comment]
I think this is mostly solved with #4543
