### ISSUE TITLE
Remove "bundleContext" (and similar) from BaseThingHandler

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3327]
When the Thing infrastructure was refactored to NOT have thing handlers registered as OSGi services anymore, a few parts where "forgotten" in the BaseThingHandler:

```
    protected ThingRegistry thingRegistry;
    protected ItemChannelLinkRegistry linkRegistry;
    protected BundleContext bundleContext;

    @SuppressWarnings("rawtypes")
    private ServiceTracker thingRegistryServiceTracker;
    @SuppressWarnings("rawtypes")
    private ServiceTracker linkRegistryServiceTracker;
```
I would claim that none of those should be in there - especially not as `protected` so that it becomes available to individual handler implementations.

Removing them will be an API breaking change, but therefore it should imho be done rather sooner than later.

**Comment by sjka** [comment]
I agree we should do it rather sooner than later! 

I just remember a discussion with @sbussweiler about the bundleContext. There were some bindings using it, but nevertheless we should clean that up!

**Comment by maggu2810** [comment]
> kaikreuzer:
> but therefore it should imho be done rather sooner than later.

> sjka
> I agree we should do it rather sooner than later!

Okay for me as well

**Comment by htreu** [comment]
This is now duplicated by https://github.com/eclipse/smarthome/issues/5182.
