### ISSUE TITLE
Binding configuration persistence 

### ISSUE THREAD

**Issue by svilenvul** [eclipse/smarthome#3331]
If this has been discussed already, excuse me, I couldn't find an open issue about it.

We are developing binding for openHAB and we want to store the username and the password for an account in a binding configuration.

The scenario is following:  the user enters the credentials in the PaperUI (Configuration -> Bindings -> Configure), binding configuration is updated, the runtime is stopped and then started and the configuration is empty. Is that expected behavior?

I have started looking at the code and I found that BindingResource calls the OSGi ConfigurationAdmin service in the updateConfiguration method. It is even more interesting how the configuration values are [get](https://github.com/eclipse/smarthome/blob/3ae5d7b1b284f2bde6199bfe8dad950fd38cae39/extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosHandlerFactory.java#L59), when they are needed.

So in general my questions are - is binding configuration persisted? How persistence can be added if it is missing?

If it is not persisted, from binding developer's point of view it is really confusing, because there is no clue for that, when looking at the binding and the thing .xsd files.

**Comment by svilenvul** [comment]
Could someone help me answering the question  - is binding configuration persisted ? How persistence can be added if it is missing ?

**Comment by sjka** [comment]
Please post your support request in the [forum](https://www.eclipse.org/forums/index.php/f/271/). This will raise the chance to get somebody seeing & answering it. Thanks.

**Comment by svilenvul** [comment]
Thanks @sjka ! I have found actually a similar [thread ](https://www.eclipse.org/forums/index.php/m/1753954/?srch=binding+configuration#msg_1753954 )in the forum - maybe I will try to bring it back to life.

I have found as well the [XmlBindingInfoProvider](https://github.com/eclipse/smarthome/blob/78b6ef19d9fc8da7969f41228d3f3b56f21b8a7f/bundles/core/org.eclipse.smarthome.core.binding.xml/src/main/java/org/eclipse/smarthome/core/binding/xml/internal/XmlBindingInfoProvider.java). I guess a ManagedProvider is required in order to add persistence.
