### ISSUE TITLE
Basic UI: missing value for switch element

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3340]
Either Classic UI or HABdroid are displaying for sitemap switch element the value (when defined in the item label) in addition to the switch control. Basic UI just displays the switch control without any value. I think this value should be displayed.

I prefer how it is displayed by Classic UI rather than HABdroid, that is at right just in front of the switch control.

**Comment by lolodomo** [comment]
@resetnow: it was easy to add the value for switch (when the user defines soimething like "xxxx [%s]" as label for the item. The only difficulty I encountered was the following line:
https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js#L1195
Now, I need that _t.setValuePrivate to be called after the command is pushed and an update is received so that I can update the value. So I was forced to comment this line. I just would like to understand what was exactly the reason to bypass the next call to setValuePrivate ?

**Comment by lolodomo** [comment]
I also discovered that when I move the little slide, the change listener is called twice, meaning that 2 events are dispatched. Are you aware about that and is it a bug ?

**Comment by resetnow** [comment]
It messes up material design animations. You can remove that line, check current switch state (`input.checked`) in  setValuePrivate callback and only call material design functions when the state is actually changed.

**Comment by resetnow** [comment]
>change listener is called twice

Which one — SSE event callback or DOM element `change`? I'm not aware of this.

**Comment by lolodomo** [comment]
I put a breakpoint here: https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js#L1191
Then I use the UI to switch ON the item. I can see that my breakpoint is reached twice.

**Comment by resetnow** [comment]
That's weird — I would check the call stack and also see if restoring suppressUpdate changes that.

**Comment by lolodomo** [comment]
It was even before I comment suppressUpdate. It is not relative to my change. I am using Firefox for debugging.

I added the test to check that the state is really updated in setValuePrivate. I will produce a PR.

**Comment by kaikreuzer** [comment]
@lolodomo Could you add some screenshots of Classic UI & Basic UI to show what the issue is exactly about and what your PR changes?

**Comment by lolodomo** [comment]
Hre is the result in Basic UI (look at the frame labelled "Switch with value and color"):
![basicui](https://cloud.githubusercontent.com/assets/10186704/25618503/798bf384-2f47-11e7-8670-92b10ab9b72a.JPG)
As a comparison, here is the result in Classic UI:
![classicui](https://cloud.githubusercontent.com/assets/10186704/25618522/8a3f4a1e-2f47-11e7-8801-b4a7ceebaafe.JPG)
Before this change, you did not have "ON" and "éteint" displayed in front of the switch control.

**Comment by lolodomo** [comment]
As a comparison, here is the result in Classic UI:
![classicui](https://cloud.githubusercontent.com/assets/10186704/25618648/1357a7d8-2f48-11e7-9dca-a474041784e7.JPG)

**Comment by kaikreuzer** [comment]
Thanks. Since when is this rendered like that in the Classic UI? I thought to only remember a discussion where the agreement was NOT to do it because it looks rather ugly (and instead go for the "mapping buttons"...

**Comment by resetnow** [comment]
It does look ugly btw, I just assumed this feature is missing from BasicUI

**Comment by lolodomo** [comment]
Please note that in all cases, displaying the value is oiptional and only happens if the user has requested it by defining a format in the label of the switch item.
As you can see, the third switch in my example has no value displayed.

**Comment by lolodomo** [comment]
And using mappings is of course another possible option. The user has several choices to display a switch.

**Comment by lolodomo** [comment]
And of course, I have not changed Classic UI, I think it is like that in Classic UI since a very long time.
My goal was only to add this useful feature in Classic UI too.

**Comment by lolodomo** [comment]
I believe we should have the ability to display the value even with the switch control keeping it not mandatory for users who think it is ugly.
If you think it is ugly like that, what would be your suggestion ? Would you prefer the value displayed just at right of the label like it is done by HABdroid ?

**Comment by lolodomo** [comment]
Interesting, users are asking for the value for the dimmer too.
https://community.openhab.org/t/basicui-and-slider-item-no-values-visable/11406

**Comment by resetnow** [comment]
>Since when is this rendered like that in the Classic UI? 

I think this feature has been here for a while, it's just how ClassicUI formats labels:

https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/render/AbstractWidgetRenderer.java#L112

So any widget may contain a separate value string in ClassicUI. I would add it to BasicUI for the sake of consistency — and since it's not visible unless the user specifically defined a label format, it shouldn't affect overall UX.
