### ISSUE TITLE
Basic UI: value not updated for a selection element in sitemap

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3346]
I have a selection item associated to a string item.
When I open the page containing this element, the value is correct.
Then if the value is updated, the selection element displays a blank value.

**Comment by lolodomo** [comment]
I fixed this issue, it occured when a transformation was used in the label of the associated item.
The item state has to be considered rather than the transformed state value.

**Comment by triller-telekom** [comment]
If you have fixed it, can you please reference this issue in your PR with "Fixes #num" so this issue gets closed automatically once your PR gets merged?

**Comment by lolodomo** [comment]
The PR is not yet submitted. I have another PR waiting for a merge touching a common file. I don't want to introduce a conflict between PRs.

**Comment by triller-telekom** [comment]
As long as you do not touch the very same lines this should not be an issue, but I understand your concern, a merge of a conflict can be ugly.
