### ISSUE TITLE
AudioSource requirement in KSpottedEvent

### ISSUE THREAD

**Issue by ghys** [eclipse/smarthome#3348]
In [KSpottedEvent](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/KSpottedEvent.java#L28) an `AudioSource` has to be provided, but it isn't easily feasible to do so because the signature of the [`KSService.spot()`](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.voice/src/main/java/org/eclipse/smarthome/core/voice/KSService.java#L79) method changed and now provides an `AudioStream` instead.

Is it really useful?

**Comment by kaikreuzer** [comment]
I cannot tell - looking at the code, I also do not see a use case that would require the AudioSource/AudioStream as a property of the KS event. Assuming, the KSListener is always a dedicated callback instance for every audio source, I would say that we can remove this info from the event. Feel free to create an according PR!
