### ISSUE TITLE
thingUpdated() gets called during initialize()

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3351]
As observed in https://github.com/openhab/openhab2-addons/pull/2019#issuecomment-298440882 and https://www.eclipse.org/forums/index.php/t/1085852/ it seems that `ThingHandler.thingUpdated()` gets called while the handler is still in `ThingHandler.initialize()`. This puts the unnecessary burden of handling synchronization on bindings and is not intended.

**Comment by martinvw** [comment]
Pitty, was no one yet able to make progress on this, it's blocking openhab/openhab2-addons#2019

Was it confirmed to happen, do we have any call traces where the calls actually come from, because the code  I see in openhab/openhab2-addons#2019 does do an async initialization.

And the documentation (which can of course be incorrect or outdated) states that `ThingHandler.thingUpdated` is:
>  This method is only called, if the thing has been initialized (status ONLINE/OFFLINE).

**Comment by martinvw** [comment]
> And the documentation (which can of course be incorrect or outdated) states that 
There it starts, it was changed in #3088

I think it might actually be really closely related to that change. @sjka can you look along with me?

**Comment by sjka** [comment]
Yes, I think I know what the problem is here:

1. There indeed was a conscious decision to also inform the handler about an update as soon as the `initialize()` method returned. The assumption is the even if the Thing is not yet in ONLINE/OFFLINE/UNKNOWN status, the ThingHandler still started doing something, hence also needs to be informed if something changed.  You are right, the documentation needs to be updated. We missed that. 

2. There was another change in the ThingManager which made the `initialize()` be called asynchronously. As it seems, this broke the "protection" described above, so that `thingUpdated()` currently also can get called while the `initialize()` is still running. This is a bug and needs to be fixed somehow. 

It's all a bit tricky, therefore I can't promise to fix it immediately, but I will have a look into this in the next couple of days.
