### ISSUE TITLE
Default icon missing for selection element in sitemap

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3352]
If you define in your sitemap a selection element, UIs will by default consider an icon with name starting with selection. As no such icon exists in the classic iconset, a broken image is displayed.

If you add for example the tag icon="switch" in the sitemap, a switch icon is then displayed for the selection. Basic UI takes the current state into account to displayed the right icon. There is a bug in Classic UI as it does not consider the right state.

By the way, I would suggest to include a default selection.png icon in the classic iconset.

**Comment by lolodomo** [comment]
I proposed PR #3353 for the specific issue in Classic UI.

**Comment by lolodomo** [comment]
If we don't want to add a default icon for selection element, one alternative would be to consider the icon associated to the linked item when the user did not set an icon for the selection element.

**Comment by triller-telekom** [comment]
@lolodomo is this issue now fixed with your referred PR? If so, can you please close it?

Regarding the extra icon for selection: If we only need it for the classicui I think its not worth the effort because in the long run we would like to get rid of the classicui in favor for the new basicui.

**Comment by lolodomo** [comment]
No this issue is still open, an icon is missing in the classic iconset. All UIs are impacted.

**Comment by lolodomo** [comment]
The icon "none" is now displayed in this case by UIs.
