### ISSUE TITLE
Icon for volume muting

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3354]
In the classic iconset, we already have the icon soundvolume_mute.png.
![soundvolume_mute](https://cloud.githubusercontent.com/assets/10186704/25631317/4a0d0b06-2f70-11e7-942a-d8f04b7fdfb7.png)

Generally, sound muting is handled by a switch channel. That is the case for example in the Sonos binding. That's why I would sugget to add three icons in the iconset:
* mutevolume.png that will be the same as current soundvolume.png
* mutevolume-on.png that will be the same as current soundvolume_mute.png
* mutevolume-off.png that will be the same as current soundvolume.png

Please let me know if you agree and then I submit a PR.

**Comment by lolodomo** [comment]
So we will use 
![soundvolume_mute](https://cloud.githubusercontent.com/assets/10186704/25631538/0185c07a-2f71-11e7-99bc-2b5b13c4057d.png)
and
![soundvolume](https://cloud.githubusercontent.com/assets/10186704/25631557/0acb2c7e-2f71-11e7-9aa5-a146a9773187.png)

**Comment by lolodomo** [comment]
For OFF state, we could rather use soundvolume-0.png
![soundvolume-0](https://cloud.githubusercontent.com/assets/10186704/25631661/5a66ead4-2f71-11e7-9457-7527e316fe7e.png)

**Comment by lolodomo** [comment]
I would suggest to change color for these icons as they are almost not visible when using a dark theme like the one proposed by HABdroid.

**Comment by kaikreuzer** [comment]
Shouldn't we rather say that a "mute" channel should be of soundvolume category and thus we rename the icons to soundvolume_off.png and soundvolume_one.png?

I agree that the fully-black style does not really fit to the other classic icons.
@reitermarkus Any suggestion to make them a better fit?

**Comment by lolodomo** [comment]
If we keep soundvolume, soundvolume-off.png will correspond to sound muted. In this case, the state is reversed compared to our "mute" channel in the Sonos binding.
To use this icon, that will require to reverse the channel in the Sonos, that is naming it "unmute" rather than "mute".

I have not checked what other audio bindings are considering as channel, mute or unmute.

PS: "-" has to be used rather than "_" in the icon name.

**Comment by kaikreuzer** [comment]
Ah, you are right, I missed that negation... Changing all such channels to "unmute" does not really sound like a valid option to me (afaik all others use "mute" as well).
So how about simply mute-on and mute-off?

**Comment by lolodomo** [comment]
mute-on and mute-off is perfect for me.

**Comment by lolodomo** [comment]
Can someone explain when script _iconcopy is run ?
Even if the icon is created by the script, we have to add it in the repo ?

**Comment by kaikreuzer** [comment]
It is a helper script for the maintainers, it isn't automatically executed.
So yes, the result of its execution needs to be checked into the repo.

**Comment by lolodomo** [comment]
What colour would you suggest instead of full black ?

**Comment by lolodomo** [comment]
Here are the updated icons I propose.
For volume:
0 ![soundvolume-0](https://user-images.githubusercontent.com/10186704/27984659-def57434-63db-11e7-98d6-9c4c72bd18ec.png)
33 ![soundvolume-33](https://user-images.githubusercontent.com/10186704/27984662-e33c73f8-63db-11e7-9354-7405404a3b29.png)
66 ![soundvolume-66](https://user-images.githubusercontent.com/10186704/27984665-e79bcdb8-63db-11e7-90db-10145a6f16a7.png)
100 ![soundvolume-100](https://user-images.githubusercontent.com/10186704/27984666-ea2d3440-63db-11e7-9615-f4799f508526.png)

For mute:
ON ![mute-on](https://user-images.githubusercontent.com/10186704/27984668-f2adab86-63db-11e7-95ee-c8765d2c7b68.png)
OFF ![mute-off](https://user-images.githubusercontent.com/10186704/27984669-f5575ad0-63db-11e7-8baa-3bad4dbba928.png)

If that's ok, I create a PR.

**Comment by kaikreuzer** [comment]
As discussed on another PR, instead of changing the color to plain green/red, I would rather prefer to go for a design that better matches the rest of the iconset - so less iconic, but slightly more realistic.
I'd wish @reitermarkus would be still around. I loved all his work on the icons a lot...
