### ISSUE TITLE
Item creation error for channels which have group defined

### ISSUE THREAD

**Issue by ppieczul** [eclipse/smarthome#3359]
If a channel has a group which was defined using:
`new ChannelUID(getThing().getUID(), groupId, id);`

its ID will look like: 
`<thingid>_<groupid>#<channelid>`

Then, when such channel is linked to a thing and item is created for this channel, it will fail at
`org.eclipse.smarthome.core.items.ItemUtil.assertValidItemName(ItemUtil.java:75)`

due to passing # sign in the method 
`org.eclipse.smarthome.core.thing.link.ThingLinkManager.createLinkIfNotAdvanced()`

This last method uses deriveItemName() which does not replace # to _. Or it does not omit group name when building item name for the link.

**Comment by sjka** [comment]
Thanks for the report and the detailed analysis. However, I cannot reproduce this issue. Checking the code, the `ThingLinkManager.deriveItemName(...)` method replaces _everything_ which is _not_ valid (i.e. `[^a-zA-Z0-9_]`)  with `_` and the code has not change for at least a year. 
What version are you using? Especially, what is the version of your `org.eclipse.smarthome.core.thing` bundle?

**Comment by ppieczul** [comment]
You are right, my fault, this issue is present in habmin only when habmin transforms channel name into item name it does not replace #. I am closing this and moving to habmin. Thank you.

**Comment by sjka** [comment]
Sure, no problem. Always happy with a bug that "fixes itself" 😄
