### ISSUE TITLE
Label returned by UI backend: when including the state value ?

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3367]
https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java#L290

The label returned by UI backend will first use, if defined, the pattern defined in the item label. If not defined, it will look for a pattern in channel state description. If found, this pattern will be used to include the state as value in the label. If not, the value will not be included in the label.

This leads to a situation where the user cannot decide to not have the value as the channel has precedence.

At the reverse, the current code has of course an interest, that is a value will be displayed for such channel, even if the user did not care of the format in the label.

So 2 questions:
* when using the pattern defined in the state description ?
* how to prevent having any value displayed ?

**Comment by lolodomo** [comment]
Issue #3248 has a direct link to this subject.
Issue #3294 has a partial link to this subject.

**Comment by lolodomo** [comment]
Here is one proposal: we could decide that looking for a pattern in the channel state description will occur only if the item label contains "[]".
As a result:
* item label "text" will lead to "text" whatever the channel state description
* item label "text [%.1f"] will lead to "text [21.2]" whatever the channel state description
* item label "text []" will lead to "text" if there is no pattern in the channel state description
* item label "text []" will lead to "text [21.23]" if there is a pattern "%.2f" in the channel state description

Then for automatic creation of items, it will make sense to create label ending with " []".

Please comment.

**Comment by sjka** [comment]
I see your point.

> Then for automatic creation of items (auto-link mode of Paper UI), it will make sense to create item with label ending with " []".

The channel defines such a format and from my point of view the "default" behavior should be that it gets used. If the user has to add empty brackets just to find out if maybe some default is hidden somewhere sounds a bit surprising to me.

How about turning it the other way round? By added empty `[]` you would override the default format, ending up with none (generously ignoring the difference between "empty" and "not set").

**Comment by lolodomo** [comment]
I fully agree with you, that is better to do it in your way. The other advantage is that we have nothing to change in the automatic creation of items.

**Comment by lolodomo** [comment]
@sjka : what would be your suggestion for #3248 ?

**Comment by sjka** [comment]
fixed with #3372
