### ISSUE TITLE
Status Transition OFFLINE -> UNKNOWN

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3387]
I just had this during development:

```
Illegal status transition to from OFFLINE to UNKNOWN. This is only allowed as the first state after INITIALIZING.
```
I was in OFFLINE-CONFIGURATION_ERROR as I so far never had any valid configuration for my handler. Now I have some and I have a long running job to figure out whether my device is ONLINE or not - so I want to set the status to UNKNOWN meanwhile. Is that a valid wish?

**Comment by sjka** [comment]
I guess so... We somehow didn't have this in mind. Thinking of it, pretty much every status detail of OFFLINE could result in UNKNOWN once you can communicate with it, be it that the network connection came, the bridge came back, the firmware has been updated...

Looks like we better remove this restriction entirely...? 

Just for ONLINE->UNKNOWN I still don't see a valid use-case. Do you?

**Comment by kaikreuzer** [comment]
> Just for ONLINE->UNKNOWN I still don't see a valid use-case. Do you?

Probably the same as the one above: You have a valid configuration and your Thing is ONLINE and now you have to handle a configuration update (e.g. an IP address change) - UNKNOWN should be a valid status in that case.

**Comment by sjka** [comment]
let's drop the restriction completely then. I will prepare a PR.
