### ISSUE TITLE
LIFX color temperature channel not working as expected

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3389]
When using the color temperature channel of LIFX bulbs, it slightly changes the tone, but it does not switch to "white mode". Instead, I expect it to always switch to a white tone (cold to warm), but not keep hue/saturation in place from before (same as in the LIFX app when switching from "color" to "white tone" color wheel).

This is afaik a regression - I remember that we discussed that in the past already and it had been fixed.

@wborn Could you please have a look?

**Comment by wborn** [comment]
It would indeed be better if the temperature channel behaved like how it behaves in the App. The value currently only changes the K value of the HSBK quadruple.

The only issue with such a change is that it no longer allows you to programmatically set all elements of a HSBK value. The Kelvin values are always used to tint HSB values, see for instance this answer/discussion in the LIFX community: https://community.lifx.com/t/interpolating-colors-whites/573/6

So I currently use this in some presets where the tint of the K value makes or breaks how nice (warm) the light is. 

The behavior could perhaps also be a configuration option on the temperature channel? It would then default to how it works in the App.

Something I also don't like in the current binding implementation is that 2 channels need to be updated for a full HSBK value update. From what I've read people would also like to use custom fade times from within rules. Any ideas on how that could be accomplished? Except for some String channel that takes hsbk,fadetime values. ;-)

**Comment by kaikreuzer** [comment]
> It would indeed be better if the temperature channel behaved like how it behaves in the App.

As I said, it already did so in the past, so we have a regression here.

> it no longer allows you to programmatically set all elements of a HSBK value

Imho it is fully ok with dropping that "feature" as I fully agree with the comment from LIFX:
_"We went with kelvin also setting saturation to 0 as we felt it covers the most common use case where people would want the light to be set to white when they set kelvin."_

Actually, I doubt that setting a Kelvin value for any color (but white) makes any kind of sense...
So the color temperature channel should always set the saturation to 0.

> So I currently use this in some presets where the tint of the K value makes or breaks how nice (warm) the light is.

You just have to choose another hue/saturation combination to reach exactly the same goal. There isn't such a thing as HSBK, this is an (unduly) invention by LIFX.

> would also like to use custom fade times from within rules. Any ideas on how that could be accomplished?

I do not want to go into this - ESH does not support parameterized commands, this would lead us to RPC-style communication with a lot additional complexity. So my recommendation would be to have people define different items that are all linked to the same channel and where the fadetime is [configured on the link](https://github.com/eclipse/smarthome/issues/583).

**Comment by wborn** [comment]
> You just have to choose another hue/saturation combination to reach exactly the same goal. There isn't such a thing as HSBK, this is an (unduly) invention by LIFX.

The need for having control over K values comes from the fact that when you use the App for picking colors, it does not use a default K value. Instead it uses the last selected K value from the whites picker. So it becomes difficult to exactly reproduce the colors selected in the App with the binding.

So what also could work is fixing the regression so the binding works exactly like the App. Then it should be possible with rules to first change the light temperature, followed immediately by a color update. That should also keep things simple without unnecessary configuration options.
