### ISSUE TITLE
LIFX Infrared channel not working as expected

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3390]
I just tried a LIFX+ bulb with IR support. From the app, it seems that the IR light can only be switched on and off, but it isn't able to dim it.

The LIFX binding offers IR as a dimmer, though. I tried that and checked the light intensity with an IP cam, but it seems that it indeed does not dim - I see some changed in intensity when using the slider, but this is not continuous and also not significant. So I assume that we probably should change it to a switch channel. @wborn wdyt?

**Comment by wborn** [comment]
Thanks for the feedback! It looks like the endianness of the FIELD_STATE in `StateLightInfraredResponse` and `SetLightPowerRequest` needs to be changed to `.little()`:
```
    public static final Field<Integer> FIELD_STATE = new UInt16Field().little();
```

It got copied from `SetLightPowerRequest` where the endianness does not matter. :-)

Now when I hook up a power meter it also shows correct readings when changing the slider. Changing the IR slider causes the power consumption to range between 0W and 5W. With this fix through my Nest cam in IR mode it also seems to work like a dimmer but the cam always auto adjusts the IR brightness.

In the Android App it is not even possible to enable/disable IR control. There is only an "eye" symbol that indicates if IR is on and when you tap it you can see the IR brightness percentage (but you can not change it). Most likely the app will some day get updated with IR schedules and brightness configuration.

In the future other IR (flood) lights may get introduced that waste even more energy on full IR brightness and get mapped to the `colorirlight` Thing type. So I do think the dimmer has a use. We could also implement `OnOffType` commands on that channel (maybe even reusing the powerOnBrightness channel configuration option).

**Comment by kaikreuzer** [comment]
Ok, sure, if the IR light actually is dimmable, then let's stay with the dimmer channel here.
So please simply create a PR that fixes the behavior of it!
