### ISSUE TITLE
Paper UI: Text entry field jumps from left to right and back

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#3392]
Tested with openHAB build 909 on Windows 10 with Chrome 58 (Edge shows the same behavior)

This is the initial view of the configuration page for the Homematic bridge configuration:
![image](https://cloud.githubusercontent.com/assets/616792/25783695/452c7b90-3361-11e7-8a86-8ce9a6cbd7fb.png)
The text entry field "Callback Network Address" is located in the right column. I think there is a bug in layout because the "Callback Network Address" should be located in the left column.

Now I set the focus to field "Gateway type" (either by clicking into the field or by using the Tab key) and "Callback Network Address" jumps to the left column:
![image](https://cloud.githubusercontent.com/assets/616792/25783747/accabc30-3361-11e7-8542-c52fee11e7f8.png)

If I then click into the edit field "Callback Network Address" or if the browser window loses the focus the field automatically jumps to the right column again.

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you please check?
