### ISSUE TITLE
UI: default elements at first level of a sitemap are ignored

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3396]
Default elements at first level of a sitemap are ignored by Classic UI and Basic UI.
It is due to the fact that the widgets to be rendered are goitten with sitemap.getChildren(), meaning without any conversion of default element to a concrete element.

I will propose a fix.

**Comment by htreu** [comment]
Do you already have a solution in mind? I guess the sitemaps where meant to be divided into separate frames and not have single widgets on the top level (even though it works with non Default widgets).

You could implicitly combine all top level widgets into a Frame in the SiteMapProvider which will fix the problem for all renderings.
Another way would be to explicitly disallow widgets not wrapped into a Frame and make a note in the documentation.

WDYT?

**Comment by lolodomo** [comment]
It is not the purpose of my issue. My concern with this issue is only the handling of default elements in sitemap.
But to answer a little to your question, my feeling is that the current rendering of elements at top of a sitemap not being in a frame is acceptable in Basic UI while awful in Classic UI. But I need to make more tests with Basic UI.
I encourage you to open a specific issue.

**Comment by lolodomo** [comment]
@htreu : for your comment about widgets at top level of a sitemap and not in a frame, here is the current situation:
* in Basic UI, the rendering is ok in my opinion
* in HABdroid, the rendering is ok but HABdroid is doing some wrong grouping if you have a widget between two frames
* in Classic UI, I improved the rendering by adding a frame around everything when you have at least one widget of this kind.
But I agree with you that it could be improved by all UIs even if I think it is not an easy change to do.

**Comment by htreu** [comment]
@lolodomo I guess your current solution in #3471 does fix this problem for most situations. And I agree that especially

> if you have a widget between two frames

would make for a complex change to fix. This can be closed then.

**Comment by kaikreuzer** [comment]
Actually - I better leave it open as it will be auto-closed once #3471 is merged.
