### ISSUE TITLE
PaperUI 2.1.0 Snapshot 0.9.0.201705081500 is blank

### ISSUE THREAD

**Issue by AngelosF** [eclipse/smarthome#3399]
After upgrade of the openHAB2 snapshot installation from 910 to 911, PaperUI comes up with only {{title}} > {{subtitle}} info
![paperui_error](https://cloud.githubusercontent.com/assets/25465966/25817634/9b80b9dc-3430-11e7-8b89-3f919f8130de.jpg)

OH Community Thread: https://community.openhab.org/t/paperui-empty-after-upgrade-to-snapshot-911/28051

**Comment by kaikreuzer** [comment]
Looking into it...

**Comment by kaikreuzer** [comment]
New ESH stable build triggered: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/193/

**Comment by rodneyrehm** [comment]
I'm not familiar with the PaperUI. But from what I can tell (after 3min of looking at it) the file [`filter.firmware.spec.js`](https://github.com/qivicon/smarthome/blob/90f06d47934beec534b5a936c4f3e575f83223cc/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/filters/filter.firmware.spec.js) is included by [gulp concat controllers.js](https://github.com/eclipse/smarthome/blob/90f06d47934beec534b5a936c4f3e575f83223cc/extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js#L37-L42).
