### ISSUE TITLE
ItemEventFactory has to use toFullString for GroupItemStateChangeEvent

### ISSUE THREAD

**Issue by BenediktNiehues** [eclipse/smarthome#3408]
When creating GroupItemStateChangeEvent the ItemEventFactory uses toString() on the new and old state which would end up in an IllegalArgumentException during deserialization when the state is a RawType.

**Comment by lolodomo** [comment]
PR is merged. Issue to be closed.

**Comment by sjka** [comment]
Ah, wrong syntax for the auto-close... Thanks for the hint!
