### ISSUE TITLE
Paper UI does not store Things' Location in Build #914

### ISSUE THREAD

**Issue by marcus-schneider** [eclipse/smarthome#3432]
If you edit the location from within HABmin changes are applied successfully, changes from Paper UI are discarded.

**Comment by kaikreuzer** [comment]
I can confirm this issue, we will look into it, thanks!

**Comment by htreu** [comment]
Its a bug in PaperUI, the method `update` was defined twice on the `thingService`. The 2nd definition is for updating firmwares and got called every time a thing should update. PR in the works.
