### ISSUE TITLE
Create a new EveryChangeLastUpdate persistence global strategy ?

### ISSUE THREAD

**Issue by briaeros** [eclipse/smarthome#3446]
I use smarthome by openhab, and configure an item on EveryChange.
The item update itself regurlary (every 30s or every minutes) , but each data change infrequently, so everyUpdate isn't an option.
The persistence database store the data at each change, but failed to store the last update timestamp before the change.

For example , if the item send value update every minutes and have the following scenario
1 from 10:00 to 10:59
5 from 11:00 to 11:44
200 from 11:45 to 11:46
then 5

The actual code with everyChange strategy will store "10:00 - 1" "11:00 - 5" "11:45 - 200" "11:47 - 5", and any chart will show a sawtooth with a line drawn from 1 to 5 in one hour, etc.

I think it will be great to have a new strategy which before saving the changed value, store the previous value with the timestamp of the last update
In the example, that will store 
"10:00 - 1" "10:59 - 1" "11:00 - 5" "11:44 - 5" "11:45 - 200" "11:46 - 200" "11:47 - 200"

This strategy prevents to store too many non-pertinent values, without losing any information.

I've try to see where was the code for "EveryChange" strategy, but couldn't find it. So I don't know if it's easy to add a new  global strategy like it.

**Comment by kaikreuzer** [comment]
> and any chart will show a sawtooth with a line drawn from 1 to 5 in one hour

This is actually your issue. The data in the database it fully ok - if you ask for the value at 10:59 it will tell you "1", so everything is fine.
I therefore don't think that solving your issue through a different way of persisting the data is the right approach.
If you use rrd4j for charts, you e.g. have the chance to define whether you want averages or absolut values being rendered - this is a feature to address issues like yours. Other chart renderers might have similar features (or you might want to ask for such a feature).

**Comment by briaeros** [comment]
Thanks for the answer.
I agree with you on the issue/symptom, but not on the solution.

If I look on the database, and I search for the value at 10:59, it says "Not Found".
And, without any more data, it's a reasonable asumption to do a linear interpolation beetween the only two value the database contains "10:00" and "11:00".(Once again, without only the databases informations, we don't know the update rate of the item. So the value could have been modified at 10:30, or even at 10:01)
Of course we could change how the charts works and force the asumption that the date of a change is less or equal than the update rate of the item (a value we don't store anywhere, and which is really more complex to infer than just store the last update before change imho).
Or we could even do a overly generous simplification that the rate of change of the items is low enough in face of his update rate, so the date of change is the moment where the value changes.
That's two strategies that must be implemented on the "presentation" layer (the chart), and manually selected, because the data layer doesn't give them enough information on how to treat the data.
This could be a totally acceptable way of doing, but I found it  little sad because the data layer _could_ store the needed informations without any new input and scheme modification.


I propose this new persistence strategy because this one doesn't lose any informations with items  which update theirs status  at fixed interval, with a minimal amount of overhead on the database size (twice the size). It have the additional good properties to correct my "sawtooth" issue :)
Of course, this strategy isn't useful for items which update theirs status only on change.

I'm not really good in java, but if someone could point me where/how they are defined (I have found that the choice is done in "GlobalStrategies", but apart this ...), I will gladly try to offer a patch :)

**Comment by sjka** [comment]
> And, without any more data, it's a reasonable asumption to do a linear interpolation beetween the only two value the database contains "10:00" and "11:00"

That's exactly the point: This assumption in your case apparently is incorrect. No matter where you do decision how to interpolate (i.e. graph drawing layer, database retrieval, or database write): You have to decide which strategy is most appropriate for this specific item. If the device does not send any more frequent data, you cannot compensate this by simply writing the previous value into the database again. It's for sure a wrong value, and in the end you won't be able anymore to distinguish "real" values from these badly "interpolated" ones in the database. 

Really, interpolation must not be done within the database! The decision how the values should be rendered (i.e. straight connections between dots or "stair" styled lines which are horizontal and jump at every value) must be done in the UI layer (e.g. rrd4j, graphana, whatever...).

**Comment by maggu2810** [comment]
> Really, interpolation must not be done within the database! The decision how the values should be rendered (i.e. straight connections between dots or "stair" styled lines which are horizontal and jump at every value) must be done in the UI layer (e.g. rrd4j, graphana, whatever...).

I think so, too.
