### ISSUE TITLE
Add TriggerChangeListener 

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#3453]
Each trigger uses RuleEngineCallback to notify  rule engine about its triggering, but the other triggers are not notified about the change and it is impossible to create a CEP handler base on triggered values of other triggers.    
My proposal is to add Observer pattern to the RuleEngineCallback (it has to have opportunity to add/remove/notify TriggerChangeListeners) . 
In that way a trigger handler can be registered as listener in RuleEngineCallback and implement some complex trigger logic (it will notified each time when each trigger is trying  to run the rule).

**Comment by danchom** [comment]
The main idea here is to create a script trigger which will be called by the RuleEngineCallback.

**Comment by kaikreuzer** [comment]
I am not sure if I fully understood your concept here.
A few design decisions of the current rule engine speak against such an implementation:
- Modules are independent of each other and thus their implementations should not depend upon another.
- If a trigger requires complex logic, it should itself be configurable in a way that it fully contains this logic.
- We do not have a contract about the identity of RuleEngineCallback instances. Every module potentially gets its very own callback instance and thus an observer pattern does not make sense on that class.

Could you describe a concrete example for your requirement? How would e.g. a script trigger logic look like?

**Comment by danchom** [comment]
> Modules are independent of each other and thus their implementations should not depend upon another.

The triggers will stay independent, they will communicate through events. If the source trigger is not available the script trigger (or other trigger register as listener) won't receive events from it. 
>If a trigger requires complex logic, it should itself be configurable in a way that it fully contains this logic.

I'm not sure about that. Why we have to duplicate implementation logic of  core.ItemStateUpdateTrigger in complex condition when we just needs a result from it (the output values)? I think it will be easier to implement complex events base on existing trigger types. 

>We do not have a contract about the identity of RuleEngineCallback instances. Every module potentially gets its very own callback instance and thus an observer pattern does not make sense on that class.

We have RuleEngineCallback interface. I've extended the interface with addTriggerChangedListerner and removeTriggerChangedListener. as it is done in Registry interface. 
Each rule has only one RuleEngineCallback instance which it shares between its triggers. When a rule is resolved and started, the RuleEngine  assigns the RuleEngineCallback instance to his triggers. At this moment a trigger (i.e. script trigger) can subscribe itself to listen data from other triggers. 
When a trigger is changed, the RuleEngineCallback first will call the RuleEngine with the new trigger data and then it will pass it to the listeners.

>Could you describe a concrete example for your requirement? How would e.g. a script trigger logic look like?

It is not needed to be script trigger, it can be any trigger handler which do complex logic over the existing triggers. The script trigger is just an example where the complex logic is implemented by supported scripts. 
- Implement the issue #3224. 
-- item state is changed
-- item state change trigger is triggered and tries to run the rule. There should be a condition which will stop the rule execution base on this trigger.
-- RuleEngineCallback notifies script trigger about the state change. The script checks if it is interested by this event and if yes it checks the time period of the last state event and the number of fired events. If the requirements are fulfill then the script trigger as a normal trigger notifies RE to start the rule
- Another example is to create some of the trigger outputs state full. The script can store their state between rule execution and fill its output with the last values. In that way we can create a logic condition based on states on multiple items.

**Comment by kaikreuzer** [comment]
> The triggers will stay independent, they will communicate through events.

Well, so they depend on each other - not by Java code but by relying on specific outputs from the other trigger.

> Each rule has only one RuleEngineCallback instance which it shares between its triggers. 

This is only an internal implementation detail, nothing tells you that it stays like this as this isn't part of any API contract. That's why I said "Every module potentially gets its very own callback instance", which imho actually might be a cleaner architectural approach as it clearly separates the different handlers and thus reduces side effects.

> Why we have to duplicate implementation logic 

If you look closely, what you ask for is "event" processing. Item state changes are already events, you do not need to wrap that into an additional trigger. All other things you might want to "catch" should be events as well, so I'd claim that you should have a CEPTrigger implementation which can be flexibly configured (e.g. through scripts) to process and combine any sorts of events. Wouldn't that be a much neater solution?

**Comment by danchom** [comment]
See https://github.com/eclipse/smarthome/issues/3474#issuecomment-306708620
