### ISSUE TITLE
[Test failures] FSInternetRadioHandlerOSGiTest failing

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3456]
Just recently the following FSInternetRadioTest started failing pretty persistently on Travis: 

```
verify the HTTP status is handled correctly when it is not OK_200(org.eclipse.smarthome.binding.fsinternetradio.test.FSInternetRadioHandlerOSGiTest)  Time elapsed: 1.13 sec  <<< FAILURE!
java.lang.AssertionError: Something went wrong with the removal of the registered Items
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert$assertThat$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:173)
	at org.eclipse.smarthome.binding.fsinternetradio.test.FSInternetRadioHandlerOSGiTest.clearTheItemRegistry(FSInternetRadioHandlerOSGiTest.groovy:741)
	at org.eclipse.smarthome.binding.fsinternetradio.test.FSInternetRadioHandlerOSGiTest.tearDown(FSInternetRadioHandlerOSGiTest.groovy:127)
```

Hudson is still happy, so we still have nightly builds. It mainly hits the PR builds on Travis.

**Comment by sjka** [comment]
@m-memova Could you please heeeelp? 😢

**Comment by m-memova** [comment]
Really? Again? What are you doing with those tests, man ? :-D I will take a look.

**Comment by sjka** [comment]
I don't know. Just executing them, I guess? 😉 

The problem with these tests for sure is that they actually are integration tests, not only testing the binding, but indirectly also the complete ESH framework. That's why the are hit by asynchronous behavior, automated magic like autoupdate if item states, auto linking and all that. If some of these things change in a slight aspect (e.g. timing, implemented in a different way), then these tests also suffer.

I think if you want to really get rid of this stuff, then it would make sense to reduce the test scope to the binding itself, just making sure it uses the ESH APIs correctly. I.e. if you want to test if a certain action leads to an item update, just take the standalone ThingHandler, feed it with a mocked ThingHandlerCallback and ensure it's calling `stateUpdated(...)`. Don't care what happens afterwards. 

The new [testing documentation](https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/testing.md#mockito) gives a pretty good example of how this can be done using plain Java 8 (hooray) with Mockito. For the majority of binding tests, this suffices and there is hardly any need for OSGiTests.

**Comment by m-memova** [comment]
Thank you, you are right. I will read the documentation and I will try to rewrite the tests as soon as I can.

**Comment by m-memova** [comment]
@sjka, I am currently rewriting the tests but I noticed something that is a little bit strange to me. In the FrontierSiliconRadioConnection class there is a method `public FrontierSiliconRadioApiResult doRequest(String requestString, String params)`. And that method could return null. But in the FrontierSiliconRadio class it is called as a void method. (`conn.doRequest(REQUEST_SET_MODE, params); `for example). In practice, that result which is returned is never used. Moreover, that possible null value is never taken into account. Am I wrong or missing something? Do you have any idea?

**Comment by maggu2810** [comment]
@m-memova Do you still work on this topic?

**Comment by maggu2810** [comment]
See #3732

**Comment by m-memova** [comment]
I have refactored the tests. They are pure Java tests now but some more changes are needed in order to use Mockito. @maggu2810 , did you start working on that ?
