### ISSUE TITLE
No setpoint icon in BasicUI

### ISSUE THREAD

**Issue by mherwege** [eclipse/smarthome#3477]
I put a dimmer item in a sitemap as a setpoint, without defining any icon. There is a missing icon symbol showing. It looks for http://openhabianpi:8080/icon/setpoint?state=0&format=svg which does not exist.

**Comment by lolodomo** [comment]
It is not specific to Basic UI but to the classic iconset. Icon missing in the iconset.

With a recent change I have done, UIs will now display the none icon in this case.

**Comment by kaikreuzer** [comment]
> UIs will now display the none icon in this case.

Which is imho a fair solution here.
