### ISSUE TITLE
Thing Handler: act on label changes

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#3482]
I would like to synchronize the thing label with an external system that also manages the name.
So, if the user changes the label of the thing the handler should send that change to the external system.

Currently there is no notification of the handler if the thing's label has been changed.

WDYT about?
Could we add a notification / callback so the handler knows about a changed thing label (same perhaps for location)?
The default implementation would be "ignore the changed label (location)" but it would be nice if the author of the handler is able to act on that changes.

**Comment by kaikreuzer** [comment]
Afaik, the label is a part of the Thing itself, so when it is updated, a ThingUpdatedEvent is sent - you could hence subscribe to these events and check old vs. new version to see if the label has changed. Would that be good enough for your requirement?

**Comment by maggu2810** [comment]
Using the `ThingUpdatedEvent` works. Thanks for that tip.
