### ISSUE TITLE
Width & Refresh of Images in BasicUI

### ISSUE THREAD

**Issue by michaeljoos72** [eclipse/smarthome#3498]
Hi

I've added a Webcam-Image to my Sitemap:

Image icon="camera" url="http://user:password@xxx.xxx.x.xx/axis-cgi/jpg/image.cgi?camera=1&resolution=640x360&compression=25" refresh=10000

With that I found 2 issues:

1) Autorefresh doesn't work in BasicUI. Tried that with Chrome and Edge. Classic UI looks good!
2) BasicUI doesn't scale the image to it's width. In ClassicUI this is, as I can see, set to 90%

See below pictures to see the difference between ClassicUI and BaiscUI.

Thanks
Michael

![image_classic](https://cloud.githubusercontent.com/assets/20517474/26281661/6b7e9e48-3dfe-11e7-8a79-f06d6e207078.jpg)

![image_basic](https://cloud.githubusercontent.com/assets/20517474/26281662/6eef4636-3dfe-11e7-8013-e29234bb5ebf.jpg)

**Comment by kaikreuzer** [comment]
I would also vote to scale images in width, but I remember that @resetnow was against it as he said that this leads to too huge images that might not fully fit on the screen (wrt their height).
But maybe he is willing to reconsider it after I am not alone anymore asking for this feature ;-)

**Comment by resetnow** [comment]
Do you think we could add `width="percentage"` to Image sitemap member? This way, we could make BasicUI images 100% by default and provide a way to override that.

**Comment by kaikreuzer** [comment]
No, I wouldn't want to add css-like styling - the layout is left on purpose to the UIs.

**Comment by resetnow** [comment]
Well, it's up to you in the end of the day, but just for the reference here is how it looks on 2k screen:

![screenshot from 2017-05-21 20-57-52](https://cloud.githubusercontent.com/assets/2057191/26286224/9d4beec0-3e68-11e7-806d-584bf01dcae8.png)

Maybe a default image width as BasicUI setting?

**Comment by resetnow** [comment]
Also, charts can stay at their default width, since they are a separate entity. And images can be enlarged.

**Comment by lolodomo** [comment]
For the refresh, i should have already fixed it. To be tested when the fix is available in OH snapshot.

**Comment by kaikreuzer** [comment]
>  just for the reference here is how it looks on 2k screen

I like it! Btw, charts can be requested with different resolutions, so that the font size is smaller, so you simply have a proper hi-res image. (don't ask me for the details right now, though).

**Comment by resetnow** [comment]
Ok — then we can resize images to 100% width by default. I think I'll use a userscript for desktop.

**Comment by michaeljoos72** [comment]
Hi

I have now another issue in BasicUI and Images. As soon as I add an image with width > than BasicUI it looks like this:

![image](https://user-images.githubusercontent.com/20517474/31314236-f1d833ee-abfb-11e7-852b-b20e2f42dab6.png)

We should have a max-size=100%.

BTW: It looks nice as soon as I reduce the Browser-Width to the "one-column-responsive" Design:

![image](https://user-images.githubusercontent.com/20517474/31314249-79653bb8-abfc-11e7-850b-0a41a52273d3.png)

Thanks
Michael

**Comment by michaeljoos72** [comment]
@resetnow @kaikreuzer Hi, did you get a message about the above mentioned issue? Thanks Michael

**Comment by resetnow** [comment]
@michaeljoos72 could you please clarify what version of openHAB you are using? Either it's very old or there has been a regressing since it was fixed at some point.

**Comment by michaeljoos72** [comment]
Ah, sorry. Sure! I'm working with snapshots, currently 2.2.0 Build #1061
The picture has a resolution of 1280x720 and it only happens with the "2-column"-Design in BasicUI

**Comment by michaeljoos72** [comment]
@resetnow did you already find time to have a look into this? Now I'm on openHAB 2.2.0 Build #1067

**Comment by resetnow** [comment]
@michaeljoos72 sorry for the long wait, looking into it now

**Comment by resetnow** [comment]
@michaeljoos72 it was a regression, I have opened https://github.com/eclipse/smarthome/pull/4450

**Comment by cweitkamp** [comment]
I observed the same issues concerning the width of an image while implementing https://github.com/openhab/openhab2-addons/pull/2304. Your latest changes solved them. Tested with openHAB 2.2.0 Build #1072.

**Comment by lolodomo** [comment]
So it can be closed finally ?

**Comment by michaeljoos72** [comment]
yeap :) thanks!
