### ISSUE TITLE
[Scheduler] Excessive use of SimpleDateFormat

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3506]
When looking into [AbstractExpression.java](https://github.com/eclipse/smarthome/blob/3ae5d7b1b284f2bde6199bfe8dad950fd38cae39/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/AbstractExpression.java), I noticed it is using `SimpleDateFormat` excessively, mainly for logging on trace level - regardless of whether logging is enabled for this level or not. This especially hurts as it causes failures (see #3505) and massively slows down the scheduler. 

Please be aware that it will executed all the time in constructs like this, no matter if something gets logged or not:

```java
for (Date aDate : getCandidates()) {
    logger.trace("Final candidate {} is {}", getCandidates().indexOf(aDate), sdf.format(aDate));
}
```

**Comment by sjka** [comment]
@kgoderis could you please have a look?

**Comment by kgoderis** [comment]
@sjka Indeed, that was all from before someone pointed me out isTraceEnabled() (or alike) on Logger.
