### ISSUE TITLE
PaperUI has empty Control page

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#3516]
The Control page is completely empty if I have Things in Uninitialized state.  The Things are Uninitialized because the binding for those Things is uninstalled.  If I delete those Things, the Control page is populated again.

Here's an image showing the empty Control page, along with the network trace showing all the Things being received by PaperUI.
<img width="1440" alt="screen shot 2017-05-24 at 1 22 49 pm" src="https://cloud.githubusercontent.com/assets/19286354/26416746/eeee17a8-4084-11e7-92c4-270d14e190a6.png">

**Comment by mhilbush** [comment]
Here's the Control page after deleting the Uninitialized Things.
<img width="1412" alt="screen shot 2017-05-24 at 1 31 33 pm" src="https://cloud.githubusercontent.com/assets/19286354/26416883/6a6cf61a-4085-11e7-8a73-4a74ddcf6510.png">

**Comment by kaikreuzer** [comment]
Thanks for figuring out the cause for this!
@aounhaider1 or @htreu Would you have a chance to have a look?

**Comment by mhilbush** [comment]
> Thanks for figuring out the cause for this!

Thanks.  I've been scratching my head over this one for quite a while.  I tried a bunch of different things (no pun intended).  I deleted those Uninitialized Things for another reason, then I noticed that the Control page was working again.  As the saying goes, it's better to be lucky than good.  :-)
