### ISSUE TITLE
[Paper UI] Brightness slider must not send HSB commands

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3519]
Using the brightness slider (the middle one) for color channels in the Paper UI results in HSB commands being sent. Instead, it should send PercentTypes only, because otherwise it is not possible to adjust the brightness if the hue&saturations settings might not be correct in the UI (e.g. because the color has been adjusted using a color temperature control).

As far as I remember, this used to be the case in the past. Has anything changed here?

**Comment by aounhaider1** [comment]
It is still sending brightness as a percent value between 0-100.

**Comment by kaikreuzer** [comment]
Can you prove this by showing a log of the runtime when adjusting the slider? I only saw HSB events being logged there... Do we somewhere convert the command from percent to HSB?
