### ISSUE TITLE
Upgrading commons.lang to commons.lang3

### ISSUE THREAD

**Issue by martinvw** [eclipse/smarthome#3522]
Sometimes developer of bindings tend to bring along commons-lang3 for which I cannot completely blame them. 

Is there a reason we choose for commons.lang 2.6, it is the newest version not being commons-lang3 but dates back to january 2011. Commons lang broke backwards compatibility (by switching package structure) to include support for Java 5...

> Lang is now Java 5 based. We've generified the API, moved certain APIs to support varargs and thrown out any features that are now supported by Java itself. We've removed the deprecated parts of the API and have also removed some features that were deemed weak or unnecessary. All of this means that Lang 3.0 is not backwards compatible.

**So my question**: can we please upgrade with of course a (long) phase in between in which we drag along both version.

Some references:

- [What's new in Commons Lang 3.0?](https://commons.apache.org/proper/commons-lang/article3_0.html)
- [Version history for the old commons-lang](https://mvnrepository.com/artifact/commons-lang/commons-lang)
- [Version history for the >= 3 commons-lang](https://mvnrepository.com/artifact/org.apache.commons/commons-lang3)

**Comment by sjka** [comment]
> Is there a reason we choose for commons.lang 2.6

Only that its API is not compatible, see e.g. https://github.com/eclipse/smarthome/issues/2801#issuecomment-272413821. Apart from that I'm not aware of any good reasons.

> with of course a (long) phase in between in which we drag along both version

That's not so ideal for solutions running on devices having very limited resources as it adds ~500kB to the footprint. We certainly _will_ need a transition phase, but we should keep it as short as possible!

Talking about size: o.a.c.l 2.6 was 284kB, o.a.c.l 3.5 is 480kB, so it almost doubled. Having a look at how it is currently used, we really also have to ask ourselves whether it's worth it at all, as it is almost only about `StringUtils` and `StringEscapeUtils`:

```
  90 import org.apache.commons.lang.StringUtils;
  11 import org.apache.commons.lang.builder.ToStringStyle;
  11 import org.apache.commons.lang.builder.ToStringBuilder;
   9 import org.apache.commons.lang.StringEscapeUtils;
   4 import org.apache.commons.lang.ArrayUtils;
   2 import org.apache.commons.lang.time.DateUtils;
   2 import org.apache.commons.lang.StringUtils;
   1 import org.apache.commons.lang.time.DateFormatUtils;
   1 import org.apache.commons.lang.reflect.FieldUtils;
   1 import org.apache.commons.lang.RandomStringUtils;
```

**Comment by martinvw** [comment]
Good that you added the reference to the other issue, thanks!

Is the count only for smart home or also for openHAB

**Comment by sjka** [comment]
Good point. The count is for ESH only. 

In openHAB2-addons the numbers are similar but definitely a bit more diverse:

```
  89 import org.apache.commons.lang.StringUtils;
  16 import org.apache.commons.lang.builder.ToStringBuilder;
  10 import org.apache.commons.lang.builder.ToStringStyle;
   7 import org.apache.commons.lang.ObjectUtils;
   5 import org.apache.commons.lang.builder.HashCodeBuilder;
   5 import org.apache.commons.lang.ArrayUtils;
   4 import org.apache.commons.lang.math.NumberUtils;
   4 import org.apache.commons.lang.builder.EqualsBuilder;
   3 import org.apache.commons.lang3.builder.ToStringBuilder;
   3 import org.apache.commons.lang.StringEscapeUtils;
   3 import org.apache.commons.lang.NullArgumentException;
   2 import static org.apache.commons.lang.StringUtils.isNotBlank;
   2 import org.apache.commons.lang3.StringUtils;
   2 import org.apache.commons.lang.WordUtils;
   2 import org.apache.commons.lang.BooleanUtils;
   1 import org.apache.commons.lang.SystemUtils;
   1 import org.apache.commons.lang.RandomStringUtils;
```

However, it clearly is not representative as the majority of the bindings is "hiding" in PRs. 

Anyway, whatever we do here in ESH, openHAB of course is free to decide differently and allow more dependencies than the ESH core.

**Comment by kaikreuzer** [comment]
> Anyway, whatever we do here in ESH, openHAB of course is free to decide differently and allow more dependencies than the ESH core.

Well, yes and no. So far we said that openhab bindings in openhab2-addons should respect the very same rules as ESH bindings, so that they are easily interchangeable. Otherwise we would not be able to potentially move bindings to ESH (as just done with Astro) anymore.

**Comment by kaikreuzer** [comment]
Coming back to this, I think it is tough to completely replace commons-lang 2 by 3, considering the amount of code that is already out there - and requiring solutions to carry both versions isn't ideal either.

In the light of https://github.com/eclipse/smarthome/pull/5356, I would rather suggest that we try to avoid the use of such libraries if possible - if the main use case are string operations, then Java 8 has already some better support now and we could also provide a few useful things in `esh.core.common`, if we think this is helpful.
