### ISSUE TITLE
How to set addons location

### ISSUE THREAD

**Issue by dushanlk** [eclipse/smarthome#3535]
I'm developing a new extension service for eclipse smarthome. But still I couldn't set add-ons bundle location to karaf config. When fetching properties for given service id using configuration admin it's null. When I was looking on OpenHab shell, it has

```
Pid:            org.openhab.addons
BundleLocation: mvn:org.openhab.core/org.openhab.core.karaf/2.0.0
Properties:
remote = true
service.pid = org.openhab.addons
```
Still I couldn't figure out how this came to config from OpenHab. Is this came from OpenHab extension service or somewhere else. Can you please help me on this.

**Comment by sjka** [comment]
This is a question about openHAB, so please ask in their community forum: https://community.openhab.org/
