### ISSUE TITLE
/rest/items returns 500 NullpointerException if the state of an Item is null

### ISSUE THREAD

**Issue by volkerrichert** [eclipse/smarthome#3539]
Hi!

The call to /rest/items results in a internal server error, if an item state is null. I debug it down to EnrichedItemDTOMapper.java#46 [https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/EnrichedItemDTOMapper.java#L46]

`String state = item.getState().toFullString();`

This happend using the latest build form 2.1 (05/29/2017). The root cause of the problem seems to be the volume item of one of my Sonos play1.

sonos_PLAY1_RINCON_5CAAFD4D84FE01400_volume (Type=DimmerItem, **State=null**, Label=Volume, Category=SoundVolume).

For sure, this should be fixed in the solos bilding itself, but the rest api should handle this

Volker

**Comment by kaikreuzer** [comment]
This is very likely the same root cause as https://github.com/eclipse/smarthome/issues/3520 and thus I hope that https://github.com/eclipse/smarthome/pull/3537 will fix this.
@triller-telekom would you agree?

**Comment by volkerrichert** [comment]
yeap, looks like.

**Comment by triller-telekom** [comment]
Yes it is definitely the same issue and the pr #3537 should fix it since its a `DimmerItem` which is affected by the bug.
