### ISSUE TITLE
ExpressionThreadPoolExecutor has not way to access scheduled expressions

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3552]
There currently is no way of finding out which expressions have been scheduled currently in a ExpressionThreadPoolExecutor

**Comment by sjka** [comment]
Some more context: it maintains an internal `Map<Expression, Runnable> scheduled` which is maintained internally, but you will need to keep a copy of all the expressions that you ever scheduled if you want to remove them later on by calling `remove(Expression)`.

**Comment by kgoderis** [comment]
@sjka in the light of the recent discussion on Astro, and in the context of "don't mess with the Expressions of your neighbour", shall we close this? If not, then it is a question of adding a method to return the keys of the map, but then one can still tamper. As an alternative, we could work with a Map<String,Map<Expression,Runnable>> structure (with String whatever id) and .getExpressions(String id), but it adds a layer of complexity
