### ISSUE TITLE
REST API documentation page is not working

### ISSUE THREAD

**Issue by dushanlk** [eclipse/smarthome#3557]
REST API [documentation page ](https://www.eclipse.org/smarthome/rest/index.html) has been crashed, affected by other change or malfunctioning. 

![imsgropn](https://cloud.githubusercontent.com/assets/8017655/26671560/861c8dee-46e8-11e7-896f-43b98b96d88f.png)

**Comment by sjka** [comment]
Oh, your're right, that's not how it is supposed to look like...
Thanks for pointing this out!
I will have a look.

**Comment by sjka** [comment]
Ok, the REST API documentation should be back at it's old glory now.

**Comment by dushanlk** [comment]
Thank you for the immediate fix @sjka :+1:
