### ISSUE TITLE
[basicui] Charts not updating on refresh interval

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#3561]
After installing build 929, my charts no longer refresh at the refresh interval defined in my sitemap.

The charts load fine the first time when loading the page, and if I manually refresh the page. But, at the refresh interval defined in the sitemap, the charts don't render, and all I get is a broken image.

See here for more details.
https://community.openhab.org/t/charts-not-displaying-at-refresh-interval/29266

This behavior did not exist in build 917.

@lolodomo Possibly related to this change?
https://github.com/eclipse/smarthome/pull/3444

**Comment by kaikreuzer** [comment]
@resetnow Maybe you have an idea as well?

**Comment by lolodomo** [comment]
My change is certainly not the reason of this problem. I fixed the refresh interval (ms vs seconds), not what is done during refresh.

**Comment by mhilbush** [comment]
Thanks for checking.  So the problem was hidden because the chart refresh rarely, if ever, occurred (due to the chart refresh interval in ms being multiplied by 1000)?

**Comment by lolodomo** [comment]
Yes certainly.
If we have a chart setup in the demo sitemap, I could have a look.

**Comment by lolodomo** [comment]
The problem is probably that data-proxied-url is not set when using charts. It will explain the null you get in your url.

**Comment by mhilbush** [comment]
Yep.  I was just looking at that line of code.

**Comment by lolodomo** [comment]
Confirmed, not set in ChartRenderer.

**Comment by lolodomo** [comment]
Explanation found. Remains to find the best fix. Is the URL a fixed URL ?

**Comment by lolodomo** [comment]
We have to take care about the chart period change.

**Comment by lolodomo** [comment]
I will propose a fix.

**Comment by lolodomo** [comment]
The chart in the demo sitemap is just not working at all for me when using Eclipse, even when the page is first displayed, neither in Basic UI nor in Classioc UI.
What do I miss ? Is there special bundles to enable ?

**Comment by lolodomo** [comment]
Here is the URL I can find in the HTML code:` /chart?groups=Weather_Chart&period=h&t=1496384548796`

**Comment by kaikreuzer** [comment]
You might be missing a persistence service? If no data is persisted, the charts won't be able to render.

**Comment by lolodomo** [comment]
Ok I will start rrdj.

I think we have another problem, the refresh interval should be in ms according to OH 1 wiki but in the demo sitemap they seem to be in seconds for charts. I will check what values I set in my own sitemap but I am sure the values in the demo sitemap have introduced confusion for any user.
Is it clear that the refresh interval for chart is like for image in ms ?

**Comment by lolodomo** [comment]
For example, 600 is used for the first chart. Was the wish to refresh it every 10 minutes or really every 600 ms ?

**Comment by lolodomo** [comment]
In the OH2 documentation, it is said that unit is ms too.

**Comment by kaikreuzer** [comment]
Yes, afair, they should be in ms. So the openhab demo sitemap indeed has incorrect values!

**Comment by lolodomo** [comment]
Sorry I gave up, impossible to make chart working for me from Eclipse !
If someone wants to try, here is the change I propose:
```
diff --git a/extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/ChartRenderer.java b/extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/ChartRenderer.java
index aa29939..ea5854e 100644
--- a/extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/ChartRenderer.java
+++ b/extensions/ui/org.eclipse.smarthome.ui.basic/src/main/java/org/eclipse/smarthome/ui/basic/internal/render/ChartRenderer.java
@@ -51,10 +51,11 @@ public class ChartRenderer extends AbstractWidgetRenderer {
                 itemParam = "items=" + chart.getItem();
             }

-            String url = "/chart?" + itemParam + "&period=" + chart.getPeriod() + "&t=" + (new Date()).getTime();
+            String chartUrl = "/chart?" + itemParam + "&period=" + chart.getPeriod();
             if (chart.getService() != null) {
-                url += "&service=" + chart.getService();
+                chartUrl += "&service=" + chart.getService();
             }
+            String url = chartUrl + "&t=" + (new Date()).getTime();

             String snippet = getSnippet("chart");
             snippet = preprocessSnippet(snippet, w);
@@ -66,6 +67,8 @@ public class ChartRenderer extends AbstractWidgetRenderer {
             }

             snippet = StringUtils.replace(snippet, "%id%", itemUIRegistry.getWidgetId(w));
+            snippet = StringUtils.replace(snippet, "%proxied_url%", chartUrl);
+            snippet = StringUtils.replace(snippet, "%valid_url%", "true");
             snippet = StringUtils.replace(snippet, "%url%", url);

             sb.append(snippet);
```

**Comment by lolodomo** [comment]
Ok I got it work !

**Comment by lolodomo** [comment]
Ok, that was my fault and the result of changes in the demo items and sitemap.
I should now be able to try my fix.
