### ISSUE TITLE
[Hue PaperUi] Icons missing, Text not aligned

### ISSUE THREAD

**Issue by NorbertHD** [eclipse/smarthome#3570]
At Hue devices in the PaperUI the (light/power) icons are missing in front of "Brightness", "Saturation" and "Off/On".
At least the text should be aligned to the lines with icons.
![hue1](https://cloud.githubusercontent.com/assets/8472266/26734010/edd20412-47bc-11e7-9a90-d8a330876c65.png)
![hue2](https://cloud.githubusercontent.com/assets/8472266/26734015/f1d4a268-47bc-11e7-95ce-3144580afa24.png)
![hue3](https://cloud.githubusercontent.com/assets/8472266/26734017/f567acc2-47bc-11e7-963c-4bb8bc6accea.png)

**Comment by kaikreuzer** [comment]
I'd agree. @aounhaider1 is this something you could look at?

**Comment by htreu** [comment]
I guess alining the text (.g. "Brightness" and "Saturation") with the first line "Color" will introduce a lot of whitespace to the card. And for smaller cards (3 cards in a row) the text "Brightness" interferes with the slider.

![image](https://cloud.githubusercontent.com/assets/1729268/26827847/49b7f912-4abf-11e7-893d-3343a67d19c6.png)

![image](https://cloud.githubusercontent.com/assets/1729268/26827956/bbafea3e-4abf-11e7-9b57-a1a04894d4b6.png)

What other options can you think of for providing a channel type icon?

**Comment by kaikreuzer** [comment]
I'd be ok with the one icon, but having the texts aligned and the sliders shrunk as much as needed.
