### ISSUE TITLE
[BasicUI] Image not resized properly

### ISSUE THREAD

**Issue by sebmarchand** [eclipse/smarthome#3571]
Image displayed in the Basic UI (by adding an Image element in the Sitemap) are not resized properly). In my setup I'm trying to display a screenshot from a security camera that has a 1920*1080 resolution, and the  image is always bigger than its container.

Adding this to the page's css (via the Chrome dev console) fix the issue:

img {
    max-width: 100%;
    max-height: 100%;
}

I don't have much experience in Web development, so it might not be the right fix :).

This is working fine in the Classic UI

**Comment by kaikreuzer** [comment]
@resetnow Could you have a look? So far, images were always too small, now they seem to be too big 😲

**Comment by sebmarchand** [comment]
Wow, thanks for the quick fix!
