### ISSUE TITLE
JSR223 Scripting: Script reloading is broken

### ISSUE THREAD

**Issue by steve-bate** [eclipse/smarthome#3579]
@smerschjohann  The script engines are being registered using the file name but they are queried (for reloading purposes) using a "script identifier" (based on the file URL). This causes scripts to not be reloaded correctly.

In `ScriptFileWatcher.importFile`, I changed:

```java
ScriptEngineContainer container = manager.createScriptEngine(scriptType, fileName);
```
to 
```java
ScriptEngineContainer container = manager.createScriptEngine(scriptType, getScriptIdentifier(url));
```
and that fixed the problem for me.

**Comment by smerschjohann** [comment]
Thank you. I guess, my last refactoring was not that clean...
