### ISSUE TITLE
scripts: ctx.ruleUID not available

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#3590]
#3007 added the ruleUID variable to the ctx object, so we could use `ctx.ruleUID` inside of scripts.

#1783 removed ruleUID from ctx but add it to the global namespace, so a script could access the rule's UID by using `ruleUID` (without `ctx.`).

#1783 has been merged "long" time ago, but "my" instances still uses an ESH version before that changes.
Now I tried to update that instances using a more recent ESH version and I realized that all the scripts does not work anymore.

I was not aware of that change and I do not see that we discussed that move (at least not in #3007 where we discussed that it is okay to leave the ruleUID in the context of scripts).

@smerschjohann What has been the reason for that change?

**Comment by kaikreuzer** [comment]
@smerschjohann Could you please comment?

**Comment by smerschjohann** [comment]
hm, that was not my intention. I think it is correct that it is in the global namespace (without ctx), but I think I failed at the merge of that sourcefile. You can of course add that to the ctx object again.
