### ISSUE TITLE
PaperUI: Rules loads Extensions

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#3591]
If you don't use an extension service but open the rule category in the PaperUI (http://127.0.0.1:8080/paperui/index.html#/rules) it complains about a non available service using a notification:
ERROR 503 - Service not available

The service that is not available is the extension one.
I don't think we need to warn every time the rules category is opened that the extension service is not available but accept the missing service silently.

**Comment by kaikreuzer** [comment]
Yes, clearly a bug.
