### ISSUE TITLE
PaperUI advanced configuration group 

### ISSUE THREAD

**Issue by tmrobert8** [eclipse/smarthome#3620]
This may or may not be a bug - seems to work differently then channel advanced settings.  For a transport that I've been working on - I have a configuration descriptor (below).  When you go to Configuration->Services->Press the Configure button on my transport - I expected the advanced group to be hidden behind a 'Advanced' or 'Show More' type of button - but it was simply displayed as is (see the screen shot below).

Here is my config:
`

        <parameter-group name="advancedSettings">
            <label>Advanced Settings</label>
           <description>Advanced Settings</description>
           <context>String</context>
          <advanced>true</advanced>
        </parameter-group>    

        <parameter name="ipAddresses" type="text" required="true">
            <label>HostNames/IP Addresses</label>
            <description>"Auto" to auto-detect or a comma delimited list of Hostnames and/or IP Addresses</description>
            <default>Auto</default>
        </parameter>
        
        <parameter name="exposeAll" type="boolean" required="true">
            <label>Expose All</label>
            <description>Expose all things</description>
            <default>false</default>   
        </parameter>
        
        <parameter name="localIpAddress" type="text" required="false" groupName="advancedSettings">
            <label>Local IP Address</label>
            <description>Local IP Address (leave blank to auto discover)</description>
            <default></default>   
        </parameter>
`
I expected PaperUI to provide an "Show More" type of button similar to advanced channels in the thing configuration - but it simply displayed the 'advanced' group in the configuration dialog.

![image](https://user-images.githubusercontent.com/20641634/26949088-a02de3e4-4c66-11e7-83b9-8f01bdea02c1.png)

**Comment by htreu** [comment]
I noticed this too a few days ago. Will have a look at it later.

**Comment by aounhaider1** [comment]
The problem here is that PaperUI checks the advanced property of parameters only and not of the group. In the above case it is false for all parameters, so the questions is should the advance property on group supersede the advance property of encapsulating parameters?

**Comment by tmrobert8** [comment]
According to [Eclipse SmartHome XML reference](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html) - there is no advanced property on the parameter itself (that's why I went with a group instead).  Is this an oversight on the document?

**Comment by aounhaider1** [comment]
The doc should be updated in that case, the advance property is part of the Parameter description https://github.com/eclipse/smarthome/blob/master/bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core/dto/ConfigDescriptionParameterDTO.java#L41.

**Comment by tmrobert8** [comment]
Interesting - something strange is still going on however.  See the following screen prints when I tried to use that (and I am running the latest and greatest).  I double checked that xsd and the ConfigDescriptionParameter - both seem to indicate that advanced is allowed but clearly it's getting flagged...

![image](https://user-images.githubusercontent.com/20641634/26976669-d70dd612-4cf2-11e7-97d2-c2810ef43ec2.png)

![image](https://user-images.githubusercontent.com/20641634/26976682-e6c26578-4cf2-11e7-8aeb-64a3986c1fff.png)

**Comment by aounhaider1** [comment]
Should be added as a tag:
```xml
<parameter name="localIpAddress" type="text" required="false" groupName="advancedSettings">
				<label>Local IP Address</label>
				<description>Local IP Address (leave blank to auto discover)</description>
				<default>0</default>
				<advanced>true</advanced>
</parameter>
```

**Comment by tmrobert8** [comment]
AHH - thanks I totally misread the xsd in my quick look.  You are correct and it does correctly show the "Show More" button in that case..

**Comment by aounhaider1** [comment]
@kaikreuzer, @htreu what do you think the behaviour should be in this case?

**Comment by htreu** [comment]
@aounhaider1 My guess is that the `advanced`property on parameter groups should indeed supersede the property of the encapsulated params and display the `More` button for this group.
I will propose a fix for this.

**Comment by aounhaider1** [comment]
Ok. Already did that. Will create a PR shortly.

**Comment by htreu** [comment]
Tnx a lot @aounhaider1! I´m also working on this but did a lot of refactoring left & right in the code. My suggestion is to merge your PR and I will rebase and propose my refactoring afterwards.

**Comment by kaikreuzer** [comment]
#3640, so @htreu go and rebase :-)
