### ISSUE TITLE
add (german) translations for system channel types

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3623]
System channel labels are currently only available in English. There are bindings that expect German texts, so this should be added (further languages upon request I would say).

See https://github.com/openhab/openhab2-addons/issues/1668.

**Comment by cweitkamp** [comment]
@gerrieg Do you have time for to look into this? If not, I can offer my help.

**Comment by gerrieg** [comment]
@cweitkamp yes please, any help is welcome. I'm very busy atm.

**Comment by cweitkamp** [comment]
@kaikreuzer One question: I have two different ways to solve this in my mind. Which one do you/we prefer?

1. A system-wide translation for a system channel, means one system channel always has the same name and the develops don't have the chance to overrule that translation.

2 . A binding dependant translation for a system channel, means there will be a default translation for one system channel, but the developers may override that translation by defining an own in the binding properties.

wdyt?

**Comment by kaikreuzer** [comment]
I would tend to option 1. Note that we are talking about channel types here - so a binding anyhow has the chance to overwrite the label and description for the channels (if I am not mistaken).

**Comment by cweitkamp** [comment]
PR #3754

**Comment by cweitkamp** [comment]
> Note that we are talking about channel types here - so a binding anyhow has the chance to overwrite the label and description for the channels (if I am not mistaken).

@kaikreuzer I tested that mentioned behavior during development. For me it was not possible to override the labels or descriptions of the system channels. Neither in ESH core unit tests, nor in OH2 avmfritz binding.

**Comment by sjka** [comment]
> For me it was not possible to override the labels or descriptions of the system channels.

This _should_ be done in [ThingFactoryHelper, l. 100ff](https://github.com/eclipse/smarthome/blob/3ae5d7b1b284f2bde6199bfe8dad950fd38cae39/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingFactoryHelper.java#L100). So it's worth having a look why it is _not_ working...!
