### ISSUE TITLE
Persistent Inbox updates non-normalized configuration parameters

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3664]
The binding's discovery service "discovers" the existing thing and synchronizes its configuration. Thereby it does not normalize the values, so it e.g. replaces existing BigDecimals with Integers.

**Comment by sjka** [comment]
@martinvw this looks like a pretty good candidate for what we were searching for, doesn't it?

**Comment by martinvw** [comment]
> @martinvw this looks like a pretty good candidate for what we were searching for, doesn't it?

You mean the one where sometimes other types popped-up, yes this looks likely 👍
