### ISSUE TITLE
[HttpUtil] guessContentType for downloadData not sufficient for JPEG

### ISSUE THREAD

**Issue by andreasreinhardt** [eclipse/smarthome#3673]
`org.eclipse.smarthome.io.net.http.HttpUtil.downloadData(String, String, boolean, long)` uses `java.net.URLConnection.guessContentTypeFromStream(InputStream)` tries to determine the actual MIME type of content if no header was sent from the server. This implementation is not sufficient for JPEG (see [Wikipedia](https://en.wikipedia.org/wiki/Magic_number_%28programming%29#Magic_numbers_in_files), enumeration item JPEG), as it compares the first 3 bytes instead of only the first 2 bytes. In the special use case of this method, it is also possible to look into the first and the last 2 bytes as the data is already downloaded and available in memory.
This will fix [openhab2-addons/issues/2302](https://github.com/openhab/openhab2-addons/issues/2302)

**Comment by kaikreuzer** [comment]
Could you come up with a PR to fix this?

**Comment by andreasreinhardt** [comment]
I'm not sure, whether I am allowed to contribute.

**Comment by andreasreinhardt** [comment]
I'm currently preparing a pull request, give me some more minutes.

**Comment by triller-telekom** [comment]
Could you please create a PR with your fix?

**Comment by kaikreuzer** [comment]
@triller-telekom Already there since 5 days and under discussion: https://github.com/eclipse/smarthome/pull/3674

**Comment by triller-telekom** [comment]
THX, I expected a direct link to the PR, which you just created now :)

**Comment by lolodomo** [comment]
This issue can be closed now.
