### ISSUE TITLE
[Paper UI] On/Off toggle not in sync with slider

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3687]
When looking at a dimmer item, a slider and a toggle is rendered. When the slider is moved to 0 %, the toggle should go OFF, but it doesn't. If the toggle is OFF and the slider is moved to any value > 0%, it should go ON, but it doesn't.

<img width="427" alt="screen shot 2017-06-16 at 23 37 57" src="https://user-images.githubusercontent.com/3244965/27245603-ded02d00-52ec-11e7-9bb9-da3846347cd6.png">

**Comment by floriandd2ba** [comment]
On BasicUI i see the same: https://github.com/openhab/openhab-distro/issues/555

**Comment by floriandd2ba** [comment]
#4430
