### ISSUE TITLE
Paper UI: Switch commands doesn't trickle down in nested groups

### ISSUE THREAD

**Issue by eleson2** [eclipse/smarthome#3694]
Having a group `AllLamps` with three lamps plus the group `WindowLamps` with additional lamps.

Switching `AllLamps`off  turns the three lights off, but not the lamps in the group `WindowLamps`.
However , Sending commands directly to `WindowsLamps` does act on the lamps in the group. 
So the behavior seems to differ depending on nesting of groups.

**Comment by kaikreuzer** [comment]
Please remove Paper UI from the title, unless you think it is related to the Paper UI in any way.

Could you provide a simple reproducible scenario? It should be enough to provide the item definitions, a "smarthome:send <itemname> OFF" console command with the according event log output.

**Comment by eleson2** [comment]
AFAIK , groups in items file does not behave like this. 
So from my point of view Groups entered in Paper UI  acts like this. 

Tried to create this Scenario in paper UI:
```
Name       Label         Type         BaseType      Parent
Group1     Group1       Group         Switch
Group2     Group2       Group         Switch        Group1        
Switch1    Switch1      Switch                      Group1 
Switch2    Switch2      Switch                      Group2 
```
default.sitemap:
```
sitemap default label="test" {
  Frame label="testframe" {
     Switch item=Group1
     Switch item=Group2
     Switch item=Switch1
     Switch item=Switch2
  }
}
```
But this works as expected! 

So I cant reproduce it easily. 
My problems remains, but it doesn't seem to be neither consistent nor repeatable.

I will close the ticket.
