### ISSUE TITLE
io.transport.mqtt: Too restrictive

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#3695]
## API is too restrictive
The io.transport.mqtt bundle is very restrictive in what functionality it exports. At the moment it allows: 
* (un)registerConnectionObserver: Notification about dis/connection to a **known** broker.
* (un)registerMessageConsumer: Subscribe to a topic on a known broker.
* (un)registerMessageProducer: Send data to a known broker.

It does not allow to alter or enumerate the brokers, only known ones can be accessed. It does not allow to access the underlying MqttBrokerConnection.

## Flaws in the current implementation
But access would be necessary for the following reasons:
* Increase the security by not using the **getVeryTrustingTrustManager** [MqttBrokerConnection.java#L385](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/MqttBrokerConnection.java#L385) but an actual ``X509TrustManager`` implementation. 
* Finer control of what happens if the connection to the broker is lost and how it could be reestablished.There is only a fixed interval timer right now. A smarter solution might react to disabled/enabled network interfaces, check for a connection faster/slower than now.

## Proposed changes
All changes are **fully backwards compatible** to existing configuration files and API consumers.
I'd like to make the following changes to the bundle and would like to collect some feedback first:
1. Make the ``getConnection`` method of **MqttService** public. Make the **MqttBrokerConnection** class public.
2. Allow to replace the `X509TrustManager`` in a MqttBrokerConnection.
3. Add means, to add / remove / enumerate **MqttBrokerConnection** of **MqttService**. This way a broker discovery binding could be written, which adds/removes brokers to the **MqttService** and binding writers can write discovery services for ESH things, that represent a specific topic on a matching broker. 
4. Remove MqttBrokerConnection::setAsync. Use IMqttActionListener to be asynchronously notified of success/fail of a MqttDeliveryToken and notify the producer asynchronously in return, instead of block / waiting for a response [MqttBrokerConnection.java#L467](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/MqttBrokerConnection.java#L467).
5. The question is, how much is backwards compatibility important. It is possible to archive everything above without removing anything of the old MqttService interface, but it adds code clutter.

### Easy configuration of Mqtt Brokers
I'm using some Mqtt sensors and actors myself and know that it can be tedious to configure a working, securely connected Mqtt broker. I've seen a lot of forum topics about this subject in the OpenHab community.
I therefore plan an OpenHab binding, that
* uses auto discovery (most brokers announce themselves via mDNS Service Discovery) and
* the PaperUI to configure broker connections.
* The binding would also offer to use an embedded broker (the [Moquette broker](https://github.com/andsel/moquette)).

The configured brokers will end up in the MqttService, available to be consumed by other bindings additionally to the textual configured brokers.

### Mqtt vendor binding
A vendor that uses mqtt as communication protocol with an edge device that runs a mqtt broker. The vendor can easily write an ESH binding with the `MqttBrokerConnection`, equipped with the necessary ssl secrets and pairing mechanisms. 

### Binding that implements things/channels based on Mqtt topics
An imaginary future binding that doesn't want to care about Mqtt broker configurations and possibly delegate this task to a core binding like in suggestion 1.
There exists for example the "Homie" Mqtt convention (https://git.io/homieiot) or the EasyESP OpenHab Mqtt protocol. A binding would only need to map those known topics to statically defined things and channels like:

| Mqtt Topic                             | -cmd | -state | ESH Thing    | Channel |
|---------------------------------------|-------|--------|------------|--------------|
| next_great_mqtt_iot_spec/doorbell | set | on | doorbell | state   |

With the proposed changes, it would simply enumerate all configured brokers and find out which brokers support the wanted topics and list the available things in the inbox.

## Discussion
Topic in the ESH forum: https://www.eclipse.org/forums/index.php/m/1766231/#msg_1766231

**Comment by htreu** [comment]
Hi @davidgraeff, thanks a lot for starting this discussion. Could you describe your use case in more detail and give some examples?
Regarding your proposed changes:

1) Yes, this would be okay. Right now the MqttService instantiates the MqttBrokerConnection and sets all the connection properties afterwards. With the proposed change it would be nice to have MqttBrokerConnection immutable and give all the connection details in the constructor (might be a separate MqttConnectionConfiguration entity).
Making the `MqttBrokerConnection` public would allow you to instantiate and manage your own private connection(s) and even address 2) for changing the TrustManager used to connect (through the MqttConnectionConfiguration?).

2) see 1.

3) & 4. This way the MqttService would become some sort of shared connection pool which handles the MqttBrokerConnctions (but not necessarily _all_, you can keep your own connection private). Would it then make sense to take away the delegating methods for (un)registering the listeners from the MqttService and operate directly on the MqttBrokerConnection?

5. makes sense.

@maggu2810 I saw your input on other MQTT topics, what do you think?

**Comment by davidgraeff** [comment]
3. & 4.: I basically implemented everything that I've listed to see if it is feasible. And yes, I stumbled over those delegating methods. The question is, how much is backwards compatibility important. At the moment I have archived everything without removing anything of the old MqttService interface.

**Comment by maggu2810** [comment]
@davidgraeff How do you intend to handle command / state vs. publish / subscribe?
If there is "next_great_mqtt_iot_spec/doorbell/state" I assume "doorbell" is the item name and "state" an indication that it is a state and not a command.
If a command is published is the topic for item "doorbell" equal to "next_great_mqtt_iot_spec/doorbell/command"?
Which topic (e.g. using wildcards) is the client subscribed to?

If you are e.g. subscribe to "next_great_mqtt_iot_spec/doorbell/state" and publish to the same topic, how do you detect / break the loop?

**Comment by davidgraeff** [comment]
@maggu2810: This is a usage example for the proposed API changes, please don't pinpoint me on that imaginary non existing binding with the imaginary non existing next _big mqtt iot standard spec_. There a lot of COAP Iot wanna be standard specs that specify all kind of resource ids and their exact value ranges. If an mqtt ios standard spec appears that defines topics/states/commands, it would be easy to write a binding with the proposed changes, that's all I wanted to say :)
