### ISSUE TITLE
Java runtime permission is required in RuleEngineCallbackImpl

### ISSUE THREAD

**Issue by plamen-peev** [eclipse/smarthome#3702]
When the automation is running in security mode, a java.lang.RuntimePermission is required when a rule is removed.
The problem comes from `RuleEngineCallbackImpl` because `shutdownNow()` is called on `ExecutorService` instance.
[eshStackTrace.txt](https://github.com/eclipse/smarthome/files/1087401/eshStackTrace.txt)

My suggestion is to shange the `dispose()` method to look like this:

    public void dispose() {
        synchronized (this) {
            AccessController.doPrivileged(new PrivilegedAction<Void>() {

                @Override
                public Void run() {
                    executor.shutdownNow();
                    return null;
                }
            });
            executor = null;
        }
    }

**Comment by kaikreuzer** [comment]
Could you create an according PR?

**Comment by plamen-peev** [comment]
You can see the changes in this PR [https://github.com/eclipse/smarthome/pull/3703]()

**Comment by plamen-peev** [comment]
Yo can see the changes in [https://github.com/eclipse/smarthome/pull/3703](url)

**Comment by plamen-peev** [comment]
You can see the changes [here](https://github.com/eclipse/smarthome/pull/3703)

**Comment by danchom** [comment]
Resolved by #3703
