### ISSUE TITLE
[Paper UI] Support "location" context for config parameters

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3709]
According [to the docs](https://github.com/eclipse/smarthome/pull/3587/files#diff-8e67ab95e48e5025e43751c8d5255b9eR131) we now have a "location" context for config parameter.

For this, it is expected that the Paper UI renders a dedicated widget. We already have an OSM widget for Location items, so it would make sense to use the same here. It must be possible to select a location from the map, but also to still manually enter lat,long,alt fields as numbers in input fields.

**Comment by htreu** [comment]
We implemented this using OpenLayers (https://github.com/openlayers/openlayers). We need a CQ for version 4.2.

**Comment by htreu** [comment]
Although we only use a subset of functions from OpenLayers its not crystal clear which JavaScript files are actually used by our custom build of the library.

@kaikreuzer or @maggu2810 or @sjka please create a CQ for https://github.com/openlayers/openlayers/tree/release-v4.2.0
