### ISSUE TITLE
[astro] astroDawn#start -->value is empty (not available)

### ISSUE THREAD

**Issue by Celaeno1** [eclipse/smarthome#3718]
I have a problem. Channel **astroDawn#start** is not running anymore. I first recognized it with build 920 and after this until now I used build 940 (0.9.0.201706071228), today I updated to build 958 (0.9.0.201706191632), but it is still not running! --> **astroDawn#start** is empty! See also here:  
[link](https://community.openhab.org/t/astro-binding-with-weather/30315/3) and here: [link](https://community.openhab.org/t/astro-binding-with-weather/30315/4)

**Comment by kaikreuzer** [comment]
@amitjoy Would you think that this is fixed by #3716 as well?

**Comment by amitjoy** [comment]
@Celaeno1 Could you kindly let me know your location that has been set to the Sun thing? For your information, in most of the places in Germany, right now there exists no astronomical dawn but the places in Munich, Ulm do have. If have change your location to any of the places in Munich, the astronomical dawn will show up.

**Comment by sihui62** [comment]
> Could you kindly let me know your location that has been set to the Sun thing?

For my test (although not Celaeno1 ;-)) I have used a location in the northwestern part of Germany and you are right, no data shown on suncalc:

![1](https://user-images.githubusercontent.com/10405486/27385109-c8ed1d92-5691-11e7-96fe-4b6b9585d168.JPG)

**Comment by Celaeno1** [comment]
Ok, this is no binding issue, it's an astronomical issue. "Astronomical dawn" is "n/a" in my hometown. I understand. Thanks!
