### ISSUE TITLE
Paper UI: Control panel not usable

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3722]
I can see things appearing in the page but the page looks as "locked", scrolling is not working.
I have only less than 30 things (one is OFFLINE).
I decided to use location in my things to have several tabs, thinking it will help to accelerate rendering of things but it does not help (even worst ?).

**Comment by htreu** [comment]
@lolodomo I tried to reproduce your issue w/o success. I did configure some (~20) things, some of them offline and tested in Chrome (58) and Safari (10.1) but scrolling and thing control is possible. Can you give some more details on how to reproduce the issue?

**Comment by lolodomo** [comment]
One important point is that my OH server is run by a slow machine (RPI 2) but except with that I encounter no performance issue with OH.

The control page has always taken a lot of time to load but in the past you just have to wait and then you could use it. Now there seems to be a kind of loop.
The problem occurs with Firefox on PC and Chrome on Android. On Firefox I have a permanent popup asking me to continue or exit a script. In the past, I have to click one or 2 times on continue and the page was loaded.

**Comment by kaikreuzer** [comment]
@htreu Might that be in any way related to the new REST streaming? Although it was meant as a performance improvement, maybe we have overlooked something that can cause issue?

@lolodomo Do you have the REST API docs add-on installed? If so, it would be interesting how long requests to get all things and all thing-types actually take.

**Comment by lolodomo** [comment]
I will install the REST API docs and mesure rhe requests duration later in the evening.
Other information :  I am running build 951.

**Comment by lolodomo** [comment]
The 2 requests are running fast, around 1 second.

**Comment by htreu** [comment]
@lolodomo could you please try with the PR I did? Its a very simple attempt to speed up control page rendering.

**Comment by lolodomo** [comment]
I am now building your PR. I will let you know if it resolves the issue or not.

**Comment by lolodomo** [comment]
This PR can be closed after the merge of @htreu 's PR.
