### ISSUE TITLE
Wemo Bulb states showing incorrectly

### ISSUE THREAD

**Issue by ReidChris** [eclipse/smarthome#3723]
I have two Wemo bulbs in lamps (hallway lamp and livingroom lamp) that are connected to a wemo bridge.

They're configured in Openhab2 , on my sitemaps and work fine. Recently though, if I change the state (on, off) or brightness of either bulb, the non-changed bulb also shows the changes in the UI but not physically (i.e. only one will dim or turn on/off) but both will show the changed UI.

The logs show that both bulbs have received an ItemStateChangedEvent despite only one of them physically changing states. 

At the same time, I've also noticed that if a rule is present inside the Wemo app that turns the bulb off by dimming, the switches in OpenHab won't turn the item back on - I need to tap the dimmer slider to make the bulb respond. In PaperUI there now appears an "Off/On" switch that I don't remember seeing before.

I think there may have been a firmware update on the bridge about a week or two ago. The current firmware version on the link is WeMo_WW_2.00.10966.PVT-OWRT-Link. Firmware version on the bulbs is 83.

**Comment by hmerk** [comment]
I tried to track this down to a root cause, but without success. I can this behaviour in my IDE, but not with every start of openHAB.
There is definitely just one command send to one bulb, so I have no clue where the second ItemStateChangeEvent is originated.

@sjka Do You have a clue how to identify the cause for the second event ?

The Presence of a rule seems to block the binary state of the bulb, this is not binding related.
ON/OFF switch in PaperUI is nothing new.

**Comment by ReidChris** [comment]
Thanks for looking into this. 
I've also noticed that changing the dimmer level of one bulb changes the value (but not the physical brightness) of the other, but this shows in the UI randomly and not everytime. The log shows the changes applying to both bulbs. In the screenshot, I had clicked the "Hallway Lamp" to On, but the logs show the "Living Room Lamp" also changing. The UI in PaperUI and BasicUI temporarily reflected the incorrect change to Living Room Lamp.
![image](https://user-images.githubusercontent.com/29626897/27505185-22e7abb2-58dd-11e7-976d-7a4b9bd95776.png)


The "ON/OFF" switch I mentioned in PaperUI was a switch that appeared underneath the dimmer that I'd never noticed before, but looking at PaperUI just now, it is no longer there just the usual State switch and the Dimmer are.

**Comment by triller-telekom** [comment]
@ReidChris Do you have an example `.items` and `.sitemap` file for your setup? Do you have any `groups` involved in your setup?

**Comment by triller-telekom** [comment]
@ReidChris Do you still have the problem? I just saw in your screenshot that there are **two** wemo bridges `...F423057..` and `...F4202C1...` involved. Are you sure your setup is correct?

Otherwise please close this issue. Thanks.

**Comment by ReidChris** [comment]
@triller-telecom there was only ever one physical wemo bridge... I gave up on wemo and moved over to Hue.
