### ISSUE TITLE
Basic UI: bad refresh of value containing XML

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3744]
The value containing XML seems to be correctly displayed, even if truncated, when the page is first opened but when an update is sent the dispayed value rhen looks like an empty string.
Can be checked with the zonegroup channel of the Sonos binding

**Comment by lolodomo** [comment]
In backend, StringEscapeUtils.escapeHtml is applied to the value.
I see no character escaping in front end when handling update event.
@resetnow: are you doing the same analysis ?

**Comment by lolodomo** [comment]
I will have to look at the label (in event) received in this case too.

**Comment by resetnow** [comment]
I see what you mean. Escaping code can be taken from <a href="https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js#L1401">setTitle</a> and should be applied to all values in SSE event listener (not sure about long-polling one). If you're going to make a PR, please say so, so we don't end up with two identical PRs.

**Comment by lolodomo** [comment]
I will propose a fix. The " could be another character to escape ?

**Comment by resetnow** [comment]
I don't remember using labels or values as HTML attributes anywhere but just in case escaping it won't hurt.
