### ISSUE TITLE
powerOnBrightness is ignored when "empty" in the things file

### ISSUE THREAD

**Issue by GarethBlain** [eclipse/smarthome#3745]
I really want to keep all my config for things together (in the .things file rather than the PaperUI option) but adding a Lifx light I want the powerOnBrightness to be the previous power off value and setting it to empty in the PaperUI things config works fine when you add it (as a thing) using PaperUI  BUT if you want to add it in the .things file then following the demo.things file [here](http://docs.openhab.org/addons/bindings/lifx/readme.html#demothings) causes the default value of '100' to be used... e.g.

    Thing lifx:colorlight:living [ deviceId="D073D5A1A1A1" ] {
        Channels:
            Type color : color [ powerOnBrightness= ]
    }

IF however you use a value between 0-100 it DOES use that. e.g.

    Thing lifx:colorlight:living [ deviceId="D073D5A1A1A1" ] {
        Channels:
            Type color : color [ powerOnBrightness=75 ]
    }

**Comment by sjka** [comment]
The problem I can see in the lifx binding is that it specifies 100 as the default value [here](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/config/config.xml#L21). Therefore, if you don't include the `powerOnBrightness` parameter in your DSL file, it will automatically use the 100 (and in fact it _should_ do the same in the PaperUI - if not, I'd consider it as a bug). 

Therefore if the lifx binding really intends to stick to the "unset == keep the last value" strategy, then it should not declare the default value.

**Comment by GarethBlain** [comment]
That is what I thought. BUT the Lifx bindings are using said "bug" as a feature and the manual says "Use empty value to leave brightness as is." [here](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/config/config.xml#L20)
It's basically giving the effect that it's set to 100 by default but though the PaperUI you can remove it and the default isn't added back. Would be nice to replicate this correctly in the config. :)

**Comment by sjka** [comment]
I don't have a LIFX bulb, so it would be cool if anybody could try out if omitting the default value leads to the wanted behavior and create a PR.
