### ISSUE TITLE
bad formatting of validation error position in log file

### ISSUE THREAD

**Issue by mueller-ma** [eclipse/smarthome#3770]
I updated my oh2 to oh2.1 and now one of my sitemaps doesn't load with follwing error:
```
[WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'default.sitemap' has errors, therefore ignoring it: [1,219,16]: missing RULE_ID at 'label='
[1,224,16]: missing RULE_ID at 'label='
```

What does this mean? Line 219 and 224?

**Comment by kaikreuzer** [comment]
Please use the openHAB Forum (https://community.openhab.org/) for general openHAB support and only create issues here if there is a bug in the code (and not in your configuration file).

Hint: It will help if you then also post your sitemap. You might also want to use the Designer, which should give you clear indications of where your file in wrong.

**Comment by mueller-ma** [comment]
Isn't this kind of a bug? For every other error I get [line, char] but here I get three values

**Comment by mueller-ma** [comment]
Ahh. It's line 1219, char 16

**Comment by kaikreuzer** [comment]
> Isn't this kind of a bug?

Well, yes. If the title wasn't "missing RULE_ID at 'label=' after updating oh2", but "bad formatting of validation error position in log file" and the description wasn't "my sitemaps doesn't load", but something else, it could be indeed considered a bug report ;-)

**Comment by kaikreuzer** [comment]
Created #3775 as a fix.
