### ISSUE TITLE
Correction for ScriptedRuleProvider.xml

### ISSUE THREAD

**Issue by thucke** [eclipse/smarthome#3790]
In the file `ScriptedRuleProvider.xml` the following definition

`<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" immediate="true" name="org.eclipse.smarthome.automation.module.script.rulesupport.internal.shared.ScriptedRuleProvider">`

should be replaced with

`<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" immediate="true" name="org.eclipse.smarthome.automation.module.script.rulesupport.shared.ScriptedRuleProvider">`

(... false `.internal.shared` in the name definition)

**Comment by triller-telekom** [comment]
Thanks for reporting this. I have fixed the package name in the xml file.
