### ISSUE TITLE
Paper UI shows '404 Not Found' for Thing with firmware property

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#3791]
The new [OH2 Plugwise Binding](https://github.com/openhab/openhab2-addons/pull/1907) has Things with firmware properties that store the firmware version. Therefor the properties key `Thing.PROPERTY_FIRMWARE_VERSION` is [reused](https://github.com/wborn/openhab2-addons/blob/d5d2518310ec7de1bbcdde5ac4c490c699a2828e/addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseUtils.java#L101).

Since https://github.com/eclipse/smarthome/pull/3206 got merged the Plugwise Things now get a firmware panel in Paper UI, eventhough there is no support for upgrading their firmware using a `FirmwareUpdateHandler` at all. 

Now everytime you open a Thing page for these Things in Paper UI, an 'ERROR: 404 - Not Found' is shown. Paper UI tries to call `/firmware/status` but fails:

![firmware-404](https://user-images.githubusercontent.com/12213581/27810551-139d6e72-605c-11e7-97c7-12deaa166977.png)

**Comment by sjka** [comment]
@htreu could you please have a look?

**Comment by htreu** [comment]
I´m on it. Stay tuned.
