### ISSUE TITLE
java.lang.StackOverflowError in GroupItem.collectMembers()

### ISSUE THREAD

**Issue by triller-telekom** [eclipse/smarthome#3794]
The PR #3464 introduced the possibility to retrieve also sub groups from a group item.

However there was a check missing that leads to a StackOverflowError as reported in the [KNX Forum](https://knx-user-forum.de/forum/supportforen/openhab/1108731-openhabian-teilweise-absturz-openhab-2-1)

**Comment by kaikreuzer** [comment]
Don't miss to leave a message about it in the KNX User Forum!
