### ISSUE TITLE
When MCP23017 binding is installed on Openhabian 1.3 (with OH 2.1), Openhab cannot start.

### ISSUE THREAD

**Issue by szymic1** [eclipse/smarthome#3797]
When MCP23017  binding is installed on  Openhaian 1.3 (with OH 2.1), OH cannot start. 

## Expected Behavior
OH shoud start when I put MCP23017 binding jar in /usr/share/openhab2/addons. 

## Current Behavior
I've tried to install MCP23017 binding (from https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.mcp23017/target/3). 
but when I copied this to adds directory there are problem with starting Openhab.
In the openhablog there are following information. "Started dashboard.." is displayed every 10seconds (in a loop):

```
2017-07-02 12:48:31.703 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.10:8080
2017-07-02 12:48:31.720 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.10:8443
2017-07-02 12:48:46.125 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'test.items'
2017-07-02 12:48:54.990 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'test.rules'
2017-07-02 12:49:44.305 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.10:8080
2017-07-02 12:49:44.322 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.10:8443
```
It happens when system start but it also happen when OH running and I put MCP file on runnnign system. This binding works on OH 2.0 without problem.

## Possible Solution
Only uninstalling MCP binding helps.

## Steps to Reproduce (for bugs)
1. Install Openhabian 1.3 from SD image 
2. Copy  MCP binding file to  /usr/share/openhab2/addons ( download binding from https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.mcp23017/target/3 I've used org.openhab.binding.mcp23017-1.11.0-SNAPSHOT.jar	 but 1.10 also does not work)
3. Now you should see loop in openhab.log log messages

## Your Environment
Raspberry 2, Openhabian 1.3, with Razberry hut

Copy of this bug is here https://github.com/openhab/openhab1-addons/issues/5237#issuecomment-312887038  but as https://github.com/9037568 suggested it is rather bug of OH.

**Comment by sjka** [comment]
As this is an openHAB 1 binding using openHAB's compatibility layer, would you please be so kind and open this very same ticket (just copy & paste) in https://github.com/openhab/openhab-core? 
Thanks & sorry to annoy you with this. I know it's sometimes confusing with all these github projects 😄

**Comment by szymic1** [comment]
Done :) 
https://github.com/openhab/openhab-core/issues/164

**Comment by sjka** [comment]
Cool, thanks for your patience! 
Let's see what the analysis within the compatibility layer comes up with. In the worst case we might end up here again once we figured out in the compatibility layer the root-cause... I'll close this for now, but of course we could re-open it easily if needed.
