### ISSUE TITLE
Discussion about Registry interface

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#3798]
The Registry interface has following public methods:
  public E get(K key);
  public E add(E element);
  public E update(E element);
  public E remove(K key);
  
Get method abstracts getting an element and hide provider implementation. This is ok but leads to the next questions:
1) Can I update an element which I was returned by the get method? What happen if the element is not from managed provider. Isn't be better to throw an exception and notify the caller about the problem (the AbstractRegistry just returns silently null and just log an warning).
2) Can I remove an element? Only elements from managed provider can be removed, the others just log an warring.
3) There is no way to distinguish the elements that can be edit and these which can't. 
4) Only the managed provider can work with editable elements and it is only one instance. Isn't be better to have multiple managed providers and the Registry to pass the execution of add/update/remove request to it. Then the provider will decide to execute the operation or to throw an exception.

What do you think to provide an ManagedElement interface and providers that can edit elements (i.e. ManagedProvider and third party manaeged providers) have to deal with it. The registry methods will be:

  public ManagedElement add(ManagedElement element);
  public ManagedElement update(ManagedElement element);
  public E remove(K key) throws IllegalArgumentException; //when K is not a key for ManagedElement

Yes I know this  is backward incompatible change, but I want to know what do you think about this @kaikreuzer, @maggu2810, @sjka.

**Comment by sjka** [comment]
regarding 1.-3. The only place where this requirement came up so far where related to things. And this was realized by adding an "editable" flag to the corresponding DTO (see #3289). The same of course could be done in the RuleDTO if that helps UIs. 

regarding 4. for "update" & "remove" this would be doable. For "add", this leads to quite some fun. Until now, having one database backed provider per entity is working pretty well, so I don't think it would be better to have multiple.

I personally don't see at the moment how the huge pain of changing the registry interface(s) and all the places which rely on the singularity would be justified by any benefits.

**Comment by danchom** [comment]
I don't see any "editable" property in ThingDTO, may be it is part of properties or configuration of a Thing. Anyway this can't be solve only thought the DTO, because the java api uses real objects, not DTO presentation. It can be part of the interface of all objects which want to be edit. For example:
1) Rules - here we uses importers instead of providers and store almost all rules into managed provider which partially solve the problem. But we also support a read only rule providers (which provides read only rules) and there is no way to  distinguish them from imported rules.
2) If I want to create a template editor, I've to store my new created templates into managed provider, but there is no way to distinguished my templates from these created by the bundle resource provider or file provider.
3) Same  problem arise with editor for composite module type. Actually we always have a problem when we want to add or edit object  from registry. The one solution is: each of this objects must be obligated to have "editable" flag. The other solution is to change registry interface. (we can add these new methods and deprecate the old ones)
>regarding 4

Actually the provider may want to use some remote service from which it provides objects and I think it should have opportunity to add/update/remove objects remotely too.

**Comment by kaikreuzer** [comment]
I'd agree with @sjka's https://github.com/eclipse/smarthome/issues/3798#issuecomment-313138840 above and would suggest to close the issue. If you still see the need for changes, feel free to re-open it.
