### ISSUE TITLE
JSR223: Script names not scoped by subdirectory for script loading at system start.

### ISSUE THREAD

**Issue by steve-bate** [eclipse/smarthome#3801]
Although the JSR223 scripting code loads files from subdirectories of `automation/jsr223`, it does not scope the file names by directory when loading scripts. For example if there is a file called 'script1.py' in two subdirectories, only one will be loaded at start time. If the scripts are added or modified after openHAB starts, then both will be loaded. @smerschjohann

**Comment by kaikreuzer** [comment]
Sounds indeed like a bug to me.
