### ISSUE TITLE
[Question] [PaperUI] Ability to get URL to Paper UI from REST API

### ISSUE THREAD

**Issue by kubawolanin** [eclipse/smarthome#3827]
Thanks to https://github.com/openhab/openhab-vscode/issues/29 I've discovered that direct URL to Paper UI differs. E.g. I'm running latest OH distro and the url is `/paperui/index.html` whereas some people seem to have it located in `/ui/index.html`.
Presumably they're running the older version of the ESH framework.

That said, is there a way to determine what's the exact URL to the specific UI over REST API?
I looked over [here](http://demo.openhab.org:8080/rest/extensions) and [there](http://demo.openhab.org:8080/rest/services) but didn't find any clues.

The reason I'm asking for this is that my extension has a hardcoded URL to the PaperUI now and I'd like to be able to read it from the API instead of taking it for granted.

Thank you!

**Comment by IOOOTAlan** [comment]
Hi @kubawolanin,

I don't think this is an information which can be get from the REST API, but I think you could obtain it from the pax-web OSGI service installed in the ESH platform, if you get a reference to the `HttpContext` service.
Sorry but I couldn't find any usable example for this...

**Comment by kaikreuzer** [comment]
All information you can get from ESH REST API is its version, see e.g. http://demo.openhab.org:8080/rest/, which gives you `"version":"0.9.0.201702171712"` (outch, I see I have to update the demo server soon!).
So you could use the timestamp to decide, whether the Paper UI is at /ui or at /paperui (I could check the day for you on which the location changed).

On the REST API itself, you won't find any other information (as the UIs are actually not part of the REST API).
If you don't want to hard-code that logic, but rather want to find the right urls dynamically, your only chance is to use the openHAB Dashboard HTML that you get at `<server>:<port>/start/index`. This renders the dashboard tiles and thus includes the links to all UIs, which you could parse.

**Comment by kubawolanin** [comment]
Hey Kai, thanks for the ideas and explanation!

> you could use the timestamp to decide, whether the Paper UI is at /ui or at /paperui 
I'll definitely do it this way. Is the `version` node in the same place for non-ESH openHAB 1.x? I think I might need to classify users of the old runtime as well.

> (I could check the day for you on which the location changed).
If that's not a biggie, than please - it would be awesome! :)

> This renders the dashboard tiles and thus includes the links to all UIs, which you could parse.
Nah, this looks way too hacky for my task 😉 I'll stay with the version comparing.

Thank you!

**Comment by sjka** [comment]
The URL was changed by #2728 which made it into ESH stable build 166 https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/166/changes
