### ISSUE TITLE
[Systeminfo, Documentation] CPU average load for last 1, 5, 15 minutes

### ISSUE THREAD

**Issue by spy0r** [eclipse/smarthome#3829]
Hi,

i wanted to ask why the average load in the systeminfo binding is shown as "percent" if created via Paper UI.
In the documentation its description is "Load in percents for the last x minute(s)" as well.

In my mind the average load is related to the number of cores/threads and has nothing to do with percent, except you normalized the values to the number of cores, which i doubt.

Please see: https://en.wikipedia.org/wiki/Load_(computing) as well as https://community.openhab.org/t/custom-theme-in-habpanel-2-1-example/31100/11?u=spy0r

Thanks for explanation or correction :)
Stef

**Comment by sjka** [comment]
The system info binding is not maintained here. Therefore please post your question in https://github.com/openhab/openhab2-addons

**Comment by spy0r** [comment]
Okay, sorry for that, but the documentation is here?

**Comment by sjka** [comment]
No, it's also there: https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.systeminfo/README.md

**Comment by spy0r** [comment]
thanks! there will be the time i understand this...

**Comment by sjka** [comment]
ah, don't worry.... It _is_ confusing sometimes!
I'd rather have an issue reported in the wrong project than _not_ having it reported at all! We'll always get it sorted out.
