### ISSUE TITLE
RULES: Error aborting execution rule with return

### ISSUE THREAD

**Issue by SebZim** [eclipse/smarthome#3831]
Hi @all,
referencing to this discussion here:
[https://community.openhab.org/t/exit-rule-with-return-false/26913/6](https://community.openhab.org/t/exit-rule-with-return-false/26913/6)

I put this case to the issues.
Maybe not a big deal. Main problem is, to be able to break a rule execution.
This works with
`if (something) return false`
but it causes an error in the designer and during loading the rule file.

If you use instead this one:
`if (something) return`
then, there is no error in the designer and no error during loading the file, but the execution of the rule is not longer possible.

Thx for solving.

**Comment by sjka** [comment]
I can confirm this is a bug. I just had a look into the code, and it looks like it is the interpreter who is choking on `null` being the result of an expression.

**Comment by ThomDietrich** [comment]
@sjka thanks for solving the issue so quickly!
Just a minor but important nitpick: You've solved the issue but nobody knows about that. Could you please add a short summary to the community thread and *more importantly* add a paragraph to https://github.com/openhab/openhab-docs/blob/gh-pages/configuration/rules-dsl.md#scripts ?

Thanks!

**Comment by SebZim** [comment]
Hi sjka,
tested the change with the last Snapshot of OH build #989.
The `return` doesn´t stop the execution of a rule.
Maybe something still missing?
Can you please have a look on it.
Thanks very much.

**Comment by sjka** [comment]
Thanks for testing it. 

I just tried with the following example rule:

```
rule TestReturn
when 
    Time cron "0/3 * * * * ?"
then
    logInfo("rule", ":-)")
    if (1==1) {
        return
    }
    logInfo("rule", ":-(")
end
```

which gives me

```
09:10:15.035 [INFO ] [.eclipse.smarthome.model.script.rule] - :-)
09:10:18.004 [INFO ] [.eclipse.smarthome.model.script.rule] - :-)
09:10:21.004 [INFO ] [.eclipse.smarthome.model.script.rule] - :-)
09:10:24.003 [INFO ] [.eclipse.smarthome.model.script.rule] - :-)
09:10:27.005 [INFO ] [.eclipse.smarthome.model.script.rule] - :-)
09:10:30.004 [INFO ] [.eclipse.smarthome.model.script.rule] - :-)
```

So this appears to be working as expected. Could you please give me an example where it does not work in order to reproduce it so I can have a look at what's going wrong there?

**Comment by sjka** [comment]
@ThomDietrich sure, will do once the remaining concerns have been clarified.

**Comment by SebZim** [comment]
Hi,
thanks for this quick response.
Here is my very simple test rule:

```
rule "gT Änderung"
when
    Item gT_SV changed

then
    logInfo("Info","Änderung SV Temperatur erkannt1")
    return
    logInfo("Info","Änderung SV Temperatur erkannt2")                                                                                                                                                              
end
```

In the logfile should never the second Info log be displayed - but it does :-(
```
2017-07-26 09:18:35.128 [INFO ] [.eclipse.smarthome.model.script.Info] - Änderung SV Temperatur erkannt1                                                                                                           
2017-07-26 09:18:35.131 [INFO ] [.eclipse.smarthome.model.script.Info] - Änderung SV Temperatur erkannt2  
```

**Comment by sjka** [comment]
😲  confirmed and agreed!
Will have a look...

**Comment by sjka** [comment]
Aaaaah, haha, found it... 

In java (and xbase accordingly), a line break has no meaning. And `return` optionally _can_ have an argument. As you left out the semicolons, the interpreter reads it differently from what we humans intuitively would do. When reformatting your code like following, the problem get more clear I think:

```
    logInfo("Info","Änderung SV Temperatur erkannt1")
    return logInfo("Info","Änderung SV Temperatur erkannt2")                                                                                                                                                              
``` 

Therefore in this case you need to help the interpreter, eliminating the ambiguity with a semicolon:

```
    logInfo("Info","Änderung SV Temperatur erkannt1")
    return;
    logInfo("Info","Änderung SV Temperatur erkannt2")                                                                                                                                                              
```

I will consider this caveat in my outstanding PR for the documentation.

**Comment by SebZim** [comment]
Great :-)
Thanks a lot.

**Comment by sjka** [comment]
Sure, you're welcome - thanks for bringing this up!

Regarding the docu: I created https://github.com/openhab/openhab-docs/pull/457 for it.

**Comment by ThomDietrich** [comment]
@sjka haha nice catch. I'd also not have known that. Adding the semicolon is one solution but seems tricky and easy to get wrong. How would you feel about "return void" or any other argument as the standard solution for the documentation?

**Comment by sjka** [comment]
We would require something that is also a valid statement. `return void` is not, as `void` is not an existing identifier. That would be `return null` - but then again the syntax is incorrect leading to a  "Void functions cannot return a value."-error (which in fact the Designer would have complained about if @SebZim would have used it or would have inspected his log files... 😉 )

Unfortunately java was designed to have `;` - and leaving them out only works in most of the cases. This is one where it doesn't. 

So far I'm not aware of any better solution to this.

**Comment by ThomDietrich** [comment]
Ah I see. Okay then, please bear with me. :smiley:  What if you added another change to the validator to allow a return null? Wouldn't that solve all problems?

(the Designer already has some flaws, we can add this minor one to it, IF someone would solve the others this one could be handled as well)

**Comment by sjka** [comment]
Sure, no problem. However, this is not a question of only suppressing a warning - it's none of those warnings that _we_ invented ourselves (that would have been easy then...), but it actually comes from the base language. We of course _could_ change the DSL language definition so that it expects a return value. But then suddenly it's not optional anymore and you would _have_ to return something on _every_ rule. Which would be the much bigger pain.
In fact I don't think that so many users will run into this issue - most of the time you will do early returns based in a condition - and then the return statement is the last one in a block where it does not need the `;` because the parser can use the `}` for orientation.

**Comment by ThomDietrich** [comment]
I agree that changing the language is definitely too much.

I hoped there is a clean way to find a middle path.

Aaaaanyhow. You are totally right with the last bit:

1. not many users will use an early return
2. an unconditional return doesn't make sense
3. further commands after a return do not make sense.

The only critical case I can still think of is this one:

```java
if (1==1) return
```

Okay let's leave the issue as is. I'll merge your docs PR. Thanks for the open discussion :v:
