### ISSUE TITLE
IconServlet: Requesting non-existing icon automatically delivers "none" icon

### ISSUE THREAD

**Issue by FlorianSW** [eclipse/smarthome#3842]
Steps to reproduce:
1. Start the eclipse smarthome runtime
2. Open the browser and request a non-existing image, e.g. using this url:
 http://localhost:8080/icon/big_bulb1?state=null&format=PNG

Expected result:
As the image does not exist, the request should get the reponse code 404 and an empty response, indicating, that the requested image does not exist and the client should handle this case accordingly.

Observed result:
The request is automatically redirectred (internally, without sending a 302 or 301 to the client to indicate, that the request should be retried with the URL in the Location header, see the code starting from [here](https://github.com/eclipse/smarthome/blob/9910b321f87576eeb0e0de2fe5552837ddf5a95b/bundles/ui/org.eclipse.smarthome.ui.icon/src/main/java/org/eclipse/smarthome/ui/icon/internal/IconServlet.java#L120)), as if it would request the "none" image category and the empty "none" image is delivered to the client with a 200 OK status code.

This makes it difficult for clients to identify if the requested image was returned and, e.g. should be cached or something else, or if the image could not be found. If the requested image could not be found, it should be up to the client how it handles such cases.

**Comment by lolodomo** [comment]
It was changed to avoid the display of the bad image icon in WEB browsers UIs.
Maybe the change is to be done in UI ? Any idea how the frontend (HTML img tag) can handle a not OK status ?

**Comment by lolodomo** [comment]
Initial Issue was #2784

**Comment by lolodomo** [comment]
After a search, I see there are solutions using `onerror` attribute and JS or CSS.

**Comment by FlorianSW** [comment]
Yes, that would be the better solution :) I'll submit a PR :)
