### ISSUE TITLE
Log is filled with errors when using a Favorite with Ampersand in Sonos Binding

### ISSUE THREAD

**Issue by rocketdeveloper** [eclipse/smarthome#3861]
Hi,

when you specify an Sonos-Favorite you want to play which contains an Ampersand (&), you get lots of erros in the logs and console:
`sendCommand(Sonos_Favorite,"Entspannte Rock-Klassiker & Oldies")`
leads to
`[ERROR] [inding.sonos.internal.SonosXMLParser] - Could not parse MetaData from string '<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="100c206ccatalog%2fstations%......%2f%23chunk-....." parentID="10012064catalog%2fstations%2frefinements%2fgenres%2fa3d0cc3b-368f-465e-b995-fasdafs%2f%23prime_stations" restricted="true"><dc:title>Entspannte Rock-Klassiker & Oldies</dc:title><upnp:class>object.item.audioItem.audioBroadcast</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON51363_X_#Svc533463-0-Token</desc></item></DIDL-Lite>`
and in the console to `[Fatal Error] :1:481: The entity name must immediately follow the '&' in the entity reference` which is repeated every few seconds.

The Favorite is getting played though. I have tried it with several escapings but none of them worked. The Favorite is not found and nothing is getting played.

```
Favorite 'Entspannte Rock-Klassiker &amp; Oldies' not found
Favorite 'Entspannte Rock-Klassiker &amp;amp; Oldies' not found
Favorite 'Entspannte Rock-Klassiker %26 Oldies' not found
Favorite 'Entspannte Rock-Klassiker &#38; Oldies' not found
```

**Comment by 9037568** [comment]
Coming from either [line 219](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/SonosXMLParser.java#L219) or 221.

I'd like to try reproducing this. Can you provide your configs (items/things/sitemaps/rules/etc)?

**Comment by rocketdeveloper** [comment]
Here are the relevant parts:

Thing:
> Thing sonos:Play1:living [udn="RINCON_949F3E75CB7901XXX", refresh=60]

Items: 
> Player Sonos_Controller   "Controller"        <player>                  (MySonos) {channel="sonos:PLAY1:RINCON_949F3E75CB7901XXX:control"}
> String Sonos_Favorite "SonosFavorite" <text> (MySonos) {channel="sonos:PLAY1:RINCON_949F3E75CB7901XXX:favorite"}

you need an item with an Ampersand as a Favorite in Sonos. I think you can also use the Desktop-App to create some Favorites

**Comment by lolodomo** [comment]
I will take a look and fix this issue.

**Comment by lolodomo** [comment]
I am not able to reproduce the problem.
First I tried to rename a radio in my Sonos favorites from `RTL 2` to `RTL & 2`.
Using the command `smarthome:send SonosChambreFavorite "RTL & 2"` in the console, the radio station is played and I see no errors in logs.
Then I tried to rename a Spotify song in my Sonos favorites from `Bird Set Free` to `Bird & Set & Free`.
Using the command `smarthome:send SonosChambreFavorite "Bird & Set & Free"` in the console, the song is played and I see no errors in logs.

Can you explain how you request your favorite ?

**Comment by lolodomo** [comment]
Also I tried `sendCommand(SonosChambreFavorite,"Bird & Set & Free")` inside a rule and no problem.

So that I can be exactly in the same case, can you tell me what is "Entspannte Rock-Klassiker & Oldies" ? Is a tune-in radio ?

**Comment by rocketdeveloper** [comment]
I can still reproduce this issue. 
If I use `sendCommand(Sonos_Favorite,"Entspannte Rock-Klassiker & Oldies") ` inside a rule I see in the openhab.log the following output:

`2017-08-20 18:37:16.144 [ERROR] [inding.sonos.internal.SonosXMLParser] - Could not parse MetaData from string '<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="135c106ccatalog%2fstations%2fA3F22YHFVQ9TGY%2f%23chunk-sQfKS2mBSZusTMSUcgiQ" parentID="10082064catalog%2fstations%2frefinements%2fgenres%2fa3d0cc3b-368f-465e-b995-2212e61fe93b%2f%23prime_stations" restricted="true"><dc:title>Entspannte Rock-Klassiker & Oldies</dc:title><upnp:class>object.item.audioItem.audioBroadcast</upnp:class><desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON74363_X_#Svc51263-0-Token</desc></item></DIDL-Lite>`

and in the Openhab Console log the following every few seconds:

`[Fatal Error] :1:481: Auf "&" in der Entityreferenz muss umgehend der Entityname folgen.
`

Entspannte Rock-Klassiker & Oldies is an Amazon Prime Radio station. 

It seems to be sth with the station or the thing that this is a favorite inside Sonos. If I create a playlist and name it "A&B" and start it with `sendCommand(Sonos_Playlist,"A & B")` it gets played without an error

**Comment by lolodomo** [comment]
Finally, I might have identified where is the problem. We are building XML metadata including the title in particumlar without any XML characters escaping.
I just have to understand why it is working well for favorite tunein radio stations as it is handled the same way.

**Comment by lolodomo** [comment]
I should have fixed the issue.
I finally understood why my use case with favorite renaming was not triggering the issue.

**Comment by rocketdeveloper** [comment]
Thanks :-)
