### ISSUE TITLE
Device specific IDs to automatically ignore things in the inbox

### ISSUE THREAD

**Issue by afuechsel** [eclipse/smarthome#3863]
**Current situation:** If creating a thing using the inbox, the UID of this thing normally contains some device-specific identification (serial number, MAC address, whatsoever), e.g. `hue:bridge:001788153957`. If creating this thing _manually_, either from a DSL or the Paper UI, the thing UID is manually defined and not necessarily the same as in the inbox. As a consequence, the thing, although already added to the framework will appear in the inbox and could be added again. A user may click on "Ignore" for that inbox entry to avoid this situation. 

**Proposal:** This behavior is odd and could be automated by introducing a configurable service, that _auto-ignores_ existing things in the inbox. A binding must implement some identification service to create a _device specific ID_, that clearly identifies this device (e.g. serial number, MAC address, ...). The _auto-ignore service_ will be called whenever a thing changes into ONLINE state and checks whether the inbox already contains an entry with the same _device-specific ID_ and calls IGNORE for this entry. 

The _auto-ignore service_ uses only standard features of ESH and could be switched off if not required.

**Comment by sjka** [comment]
> A binding must implement some identification service 

Why not adding a method to the ThingHandler, with a default implementation that simply returns `null`? We strive to hide OSGi as much as possible from binding developers, so we shouldn't stick it into their faces for this feature.

> that clearly identifies this device

Just to be clear: this does not necessarily have to be a serial number, nor does it need to be _globally_ unique or anything. The distinguishing characteristic that is unique within the system and is used by the thing handler anyway in order to communicate with the correct device would suffice.

> The auto-ignore service will be called whenever a thing changes into ONLINE state

By means of registering itself as an event listener, right?

**Comment by afuechsel** [comment]
> Why not adding a method to the ThingHandler, with a default implementation that simply returns null? 

Yes, isn't an empty string or Optional.empty better? Anyway, I agree. 

> By means of registering itself as an event listener, right?

Yes

**Comment by sjka** [comment]
> Yes, isn't an empty string or Optional.empty better? Anyway, I agree.

No.

**Comment by afuechsel** [comment]
Just discovered a flaw in the concept: auto-ignoring when a thing comes ONLINE works fine, we need also to perform the same check in the discovery, so when a result is going to be added to the inbox it needs to be checked not only if a thing with the uid is already existing, but also a thing with the same deviceId. 

Whilst this is easy to implement, we have a problem when things are actually *deleted*. In that case all IGNORED entries in the inbox must be checked if they are actually ignored because of the manually added thing that is currently deleted. If so, the entry in the inbox must also be deleted, so the next discovery would again add it. Failing to do so would the discovery would just update the ignored entry and it will not appear in the inbox again. Now - how can we react to the actual removal? Listening to status change events and checking if the status is actually REMOVING will not work, as the thing will be removed from the registry just before I would have a chance in the event handler to retrieve it's device id.

**Comment by lolodomo** [comment]
@afuechsel : I would like to implement that feature for the Sonos binding (and other bindings). The obvious identification would be the UDN of the Sonos device which is the main configuration parameter of the Sonos thing.
Would it be possible in `representation-property` to refrence a config parameter of the thing which is a kind of property ?

**Comment by afuechsel** [comment]
@lolodomo This would require some extension of the concept. The main reason why choosing the property was that a property should reflect the physical device properties, that are normally not changing, like MAC address or serial number. I guess, the UDN of a Sonos device is also not changing. So why is it a configuration parameter and not a property? And couldn't it be changed to make it a property? 

Remember, the matching in the inbox auto ignore service is done with the representation property's value of the discovery result. Since a discovery result does not distinguish between properties and config parameters, everything here is a property. So I guess, the UDN would be part of the discovery result too?

**Comment by lolodomo** [comment]
The UDN is a configuration and not a property in the thing because it is required when defining a thing manually to identify the Sonos device.
I believe this will be the case in all bindings linked to a physical device.
Yes, the UDN is a property in the discovery result.
So the only solution is to add another property with a different name that will be set with the UDN too ?

**Comment by afuechsel** [comment]
I'm afraid, yes. @kaikreuzer if @lolodomo is right and several bindings use a config param instead of a property - would it be an option to extend the concept to allow the representation property not only point to properties but also config params? For me this sounds a little bit awkward and hacky.

**Comment by kaikreuzer** [comment]
> So the only solution is to add another property with a different name that will be set with the UDN too ?

Another one might be that @afuechsel's new service also considers Thing configuration parameters as a potential match for "representation properties" (as we do not make a difference between params&properties in DiscoveryResults either).

**Comment by kaikreuzer** [comment]
> For me this sounds a little bit awkward and hacky.

Yes, a little, but maybe something we could live with ;-)

**Comment by afuechsel** [comment]
I could create another PR but I am on vacation for two weeks soon - without any notebook. :)

**Comment by kaikreuzer** [comment]
How do we sync discovery result properties to things? Should be the same logic.

**Comment by lolodomo** [comment]
No hurry,  I can wait for the enhancement before implementing it in the Sonos binding.

**Comment by kaikreuzer** [comment]
@afuechsel Still has a whole afternoon 😎

**Comment by afuechsel** [comment]
In the "Whole afternoon" I implemented the change to include config parameter values in the comparison with the representation value. #3983

**Comment by kaikreuzer** [comment]
You're the best - and you have very long afternoons 😎
