### ISSUE TITLE
Sonos notification broken in snapshot 988

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3877]
Sonos TTS seems to be broken in snapshot 988.
There was this recent PR #3808. I see something strange in this PR, the old value was in milliseconds (20000) while the new default thing setting is in seconds (40), so I think 40 ms is used by default !
@ivivanov-bg : can you check please ?

**Comment by lolodomo** [comment]
Later I will set the thing setting to 20000 as a workaround to see if it solves the problem.
But the real fix would be to apply a conversion from second to mullisecond.

**Comment by lolodomo** [comment]
And I see no valid reason to set this new thing setting as required.

**Comment by maggu2810** [comment]
> But the real fix would be to apply a conversion from second to mullisecond.

I had a short look at #3808 and it seems you are right.

**Comment by lolodomo** [comment]
I submitted PR #3883 that fixes the bug introduced by PR #3808. I restored a default timeout of 20 seconds which is already very long. If someone needs a longer timeout, it will use the new setting.

Unfortunately, TTS with Sonos is still not working after my fix, probably due to other changes relative to audio. @cweitkamp, maybe your PR #3837 could be one of the source of the problem ? Did you test TTS with Sonos after your change ?  

I am back now to snapshot 951 with working audio and TTS.

**Comment by lolodomo** [comment]
Another candidate could be PR #3764.

**Comment by cweitkamp** [comment]
Sry, I did not test TTS with Sonos. Any log files?

#3837 was merged after you created this issue. I suggest that PR to be not the reason.

#3764 seems more likely. I am going to review my changes.

**Comment by lolodomo** [comment]
My fix (PR #3883) has been applied to the last sources that includes your PR #3837.
To test in my production environment (snapshot 988), I installed the fixed Sonos binding + the new version of the core.audio bundle.

**Comment by lolodomo** [comment]
Oups, I see what you mean, I have the problem with the snapshot 988 in which PR #3837 is not included. So you are right, the problem cannot be due to this PR merged today.

**Comment by lolodomo** [comment]
Cool, a new ESH build was done this morning with all the recent ESH fixes so the next OH snapshot (990l should include them tomorrow and I will test again TTS with Sonos.

**Comment by lolodomo** [comment]
@kaikreuzer: yhat is not clear for me, does the OH snapshot 989 already include the ESH nuild from today ?

**Comment by kaikreuzer** [comment]
This morning? It depends on where on the world you are - I did the build just a few minutes ago ;-)
[openHAB distro 990](https://openhab.ci.cloudbees.com/job/openHAB-Distribution/990/) will include it.

Looking forward to get positive feedback from your testing!

**Comment by lolodomo** [comment]
Bingo, the problem is solved in OH distribution 990. So the problem was only the bug with the timeout handling.
@cweitkamp : I hope you have lost time to search.

**Comment by cweitkamp** [comment]
@lolodomo Glad to hear that it could be solved so fast. I haven't lost time. I only won a new bullet point on my TODO list. Since there is no unit test for `VoiceConsoleCommandExtension` I put it onto mine. Maybe we should put a unit test for the Sonos binding on any TODO list as well.
