### ISSUE TITLE
Rule Modules/Templates use "defaultValue" instead of "default"

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3881]
This is a follow-up on #2819.

The automation component does not use the ConfigDescriptionDTOs and hence it is not correctly serializing the "default" property as @htreu describes in https://github.com/eclipse/smarthome/pull/2842#issuecomment-306766789.

Not sure what approach we should take to address it, though, so looking forward to your ideas.

**Comment by danchom** [comment]
I'll check this.
