### ISSUE TITLE
Allow central configuration of the primary network interface

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#3884]
Currently, `NetUtil.getLocalIpv4HostAddress()` makes a best effort guess about which is the IP address that is used to be reachable for external devices/systems. If users have multiple network interfaces, this has a high risk to fail.

I think we therefore need to provide a central configuration where the desired network address can be chosen.

**Comment by davidgraeff** [comment]
And a documentation/advice for binding developers to explain when to use the configured network interface and when to just bind to all network interfaces (discovery services might want to do that).
