### ISSUE TITLE
DateTimeType doesn't store information about timezone

### ISSUE THREAD

**Issue by doandzhi** [eclipse/smarthome#3886]
Hello, I have started working on the ignored tests of **org.eclipse.smarthome.binding.ntp.test** - https://github.com/eclipse/smarthome/issues/1983, where 2 tests are ignored because of their unexpected behaviour. The problem is that **DateTimeType** uses **Calendar** object that doesn't contain information about the timezone.I would like to propose changing the **DateTimeType**'s structure and implement it with **ZonedDateTime** instead of **Calendar** (as Eclipse SmartHome is already using **Java 1.8**). 

What do you think?

I found a similiar discussion started a year ago - https://github.com/eclipse/smarthome/issues/2242

Regards,

**Comment by maggu2810** [comment]
I don't know about the impacts of that changes -- but you will identify it on your implementation.
At least it sounds like a good idea.

**Comment by marcelrv** [comment]
I think that is a much needed change. Now we have moved to Java1.8 let's fix this long standing issue
