### ISSUE TITLE
[PaperUI] set strict dependencies for eventsource-polyfill and jquery-ui

### ISSUE THREAD

**Issue by htreu** [eclipse/smarthome#3889]
In `package.json` both dependencies are still declared with range versions using `^`. This should be changed to match the strict versions with valid CQs.

**Comment by htreu** [comment]
@kaikreuzer please let me know which exact versions of `eventsource-polyfill` and `jquery-ui` have been approved. I will then provide a PR.

**Comment by kaikreuzer** [comment]
- EventSource Polyfill Version: 20160604
- jQuery UI 1.11.2

**Comment by htreu** [comment]
> EventSource Polyfill Version: 20160604
thats a strange version. Is there an URL attached?

**Comment by kaikreuzer** [comment]
20160604 is the date of the latest commit of the repo (for which there is no released version): https://github.com/amvtek/EventSource/commits/master

So it corresponds to the current master.
