### ISSUE TITLE
Connection timed out from repo

### ISSUE THREAD

**Issue by antoniolobefaro** [eclipse/smarthome#3894]
when I try to compile with "mvn clean install" a lot of repository in smarthome.target return  Connection timed out. 
are there some problems with them? 
for example 
http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository/
http://download.eclipse.org/eclipse/updates/4.4/

**Comment by kaikreuzer** [comment]
Yes, sometimes the Eclipse infrastructure is down or unresponsive.
Simply try again in a few hours or enter a bug for the Eclipse webmasters at https://bugs.eclipse.org/bugs/enter_bug.cgi.
