### ISSUE TITLE
multiple google charts with a switch to set the chart period. Wrong chart's dimensions

### ISSUE THREAD

**Issue by lucarui** [eclipse/smarthome#3901]
Hello,
I noticed that using a chart switch on sitemap in order to change the chart period, when I change from a a period to another, the new chart has very small dimensions. All html elements below the charts are the same (change only the json object passed to them) but the first chart that is shown at the page load has correct dimensions; the others, when I press on switch periods, have a very small dimensions.
If I came back to the first, the chart continues to have correct dimensions. It's like only the first "period" works well and the others set wrong dimensions to the charts.

chart shown at the page start:
![image](https://user-images.githubusercontent.com/22214152/28663321-55c727ac-72bd-11e7-87b5-1bfc23f2349b.png)

If I click on other period values....:
![image](https://user-images.githubusercontent.com/22214152/28663333-5c95fb08-72bd-11e7-851a-0132e716f082.png)

**Comment by kaikreuzer** [comment]
@resetnow Could you check this?

**Comment by resetnow** [comment]
@lucarui could you please post the part of your sitemap where charts and switch are defined?

**Comment by lucarui** [comment]
@resetnow  this is the section of my sitemap:

`Text label="Andamento dei consumi" icon="chart"{
	Switch item=sdm230cantina_Chart_Period label="Consumi istantanei" icon="chart"  mappings=[0="1 Ora", 1="6 Ore", 2="24 Ore", 3="72 Ore"]
		   			Webview label="Consumo 1H" url="../static/chartSDM230cantina_1Hours.html" height=6 visibility=[sdm230cantina_Chart_Period==0, sdm230cantina_Chart_Period=="NULL"]
		   			Webview label="Consumo 6H" url="../static/chartSDM230cantina_6Hours.html" height=6 visibility=[sdm230cantina_Chart_Period==1]
		   			Webview label="Consumo 24H" url="../static/chartSDM230cantina_24Hours.html" height=6 visibility=[sdm230cantina_Chart_Period==2]
		   			Webview label="Consumo 3D" url="../static/chartSDM230cantina_72Hours.html" height=6 visibility=[sdm230cantina_Chart_Period==3]
		    	}`

**Comment by resetnow** [comment]
Thanks. I'll check this later, but right now I would suspect that iframes loaded in background don't resize properly since they can't know viewport dimensions before they are actually displayed, so this problem might not be related to BasicUI at all. Did you write these html files by yourself? If so, have you tried handling document resize event? Can you check if the iframe element itself is the right size?

(and I'll leave this formatted fragment here for the sake of readability)
```
Text label="Andamento dei consumi" icon="chart" {
	Switch item=sdm230cantina_Chart_Period label="Consumi istantanei" icon="chart" mappings=[0="1 Ora", 1="6 Ore", 2="24 Ore", 3="72 Ore"]
	Webview label="Consumo 1H" url="../static/chartSDM230cantina_1Hours.html" height=6 visibility=[sdm230cantina_Chart_Period==0, sdm230cantina_Chart_Period=="NULL"]
	Webview label="Consumo 6H" url="../static/chartSDM230cantina_6Hours.html" height=6 visibility=[sdm230cantina_Chart_Period==1]
	Webview label="Consumo 24H" url="../static/chartSDM230cantina_24Hours.html" height=6 visibility=[sdm230cantina_Chart_Period==2]
	Webview label="Consumo 3D" url="../static/chartSDM230cantina_72Hours.html" height=6 visibility=[sdm230cantina_Chart_Period==3]
}
```

**Comment by lucarui** [comment]
I will try handling the resize event and I let you know. Thanks.

**Comment by lucarui** [comment]
Great @resetnow !!!
It has been solved with the resize event.
This is my HTML code. I hope it could be useful for those who want to implement Google chart:

`<html>
  <head>
    
    <script type="text/javascript" src="js/loader.js"></script>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript">

    $(window).resize(function(){
        drawChart();
    });

    // Load the Visualization API and the piechart package.
    google.charts.load('current', {'packages':['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);

    var jsonData;
    function drawChart() {
      $.ajax({
          type: "GET",
          url: "your service url. It MUST return a particula JSON object. See the php file I posted",
          dataType: "json",
          // imposto un'azione per il caso di successo
          success: function(risposta){
                jsonData = risposta;

                // Create our data table out of JSON data loaded from server.

                var options = {
                        chartArea: {bottom: '70'}
                };

                var data = new google.visualization.DataTable(jsonData);
                // Instantiate and draw our chart, passing in some options.
                var chart = new google.visualization.LineChart(document.getElem$
                chart.draw(data,options);

          },
          // ed una per il caso di fallimento
          error: function(){
                jsonData="Error!";
          }
          });
    }
    </script>
  </head>
  <body>
    
    <div id="chart_div"></div>
  </body>
</html>
`

And this is the PHP service:

`<?php

    if (isset($_GET["ore"])) {
        $hours = $_GET["ore"];
    }else{
        $hours = 0;
    }

    $servername = "ipaddress";
    $username = "your username";
    $password = "yourpassword";
    $dbname = "your db";


    $db=new mysqli($servername, $username, $password, $dbname) or die('Could no$

    $jsonTable = array();
    $table = array();

    $table['cols'] = array(
        array('label' => 'Data','type' => 'string'),
        array('label' => 'W','type' => 'number')
    );

    $rows = array();


    if($result = $db->query("yourquery")
        while($row=$result->fetch_row()){
            $temp = array();

            $date = DateTime::createFromFormat("Y-m-d H:i:s", $row[0]);

//            $temp[] = array('v' => explode(" ",$row[0])[1]);
            $temp[] = array('v' => $date->format("j F H:i"));
            $temp[] = array('v' => (int)$row[1]);
            $rows[] = array('c' => $temp);
        }

        $table['rows'] = $rows;

        $jsonTable = json_encode($table);

        $result->close();
       // $json['records']=$righe;
    }
 }

    $db->close();

    // set up header; first two prevent IE from caching queries
    header('Cache-Control: no-cache, must-revalidate');
    //header('Content-type: application/json');
    //header('Content-Security-Policy: frame-ancestors sweethomeremigio.it');
    header('Access-Control-Allow-Origin: *');
    echo $jsonTable;
    //echo json_encode($jsonTable);

?>

`

**Comment by lucarui** [comment]
closed
