### ISSUE TITLE
[Docs] How to run your own Bundles

### ISSUE THREAD

**Issue by mjohenneken** [eclipse/smarthome#3905]
Hey,
i had a hard time figuring out why my changes to the org.eclipse.smarthome.voice bundle had no effect. The reason was that i had to explicitly mark the bundle in the RunConfiguration > Plugins > Workspace to run my code and not the bundle provided in target platform. Coming from a Android/JEE Background i think this is not intuitive. I assume the bundles in Target Platform are precompiled and you have to mark specific packages in you workspace because auf start-up time?

I would suggest to document this in developer docs [here](http://docs.openhab.org/developers/prerequisites/targetplatform.html) or [here](https://eclipse.org/smarthome/documentation/development/notes.html).

**Comment by kaikreuzer** [comment]
I would claim that this is already documented [here](http://docs.openhab.org/developers/prerequisites/equinox.html#ii-start-equinox-runtime-from-eclipse).
In general, this is "standard knowledge" of how to use the Eclipse IDE for bundle development - so the fully fledge documentation on all of this can be found at http://help.eclipse.org/oxygen/index.jsp?nav=%2F4.
If you feel that new openHAB developers might need some better introduction to those topics, please feel free to directly contribute to https://github.com/openhab/openhab-docs#contributing-to-the-documentation. Thanks!
