### ISSUE TITLE
Introduction of the Identifiable broke the Registry interface 

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3907]
With #3762, the generic type parameter of the Registry interface was restricted. While this is nicely source compatible, this completely broke the binary contract between any usages of the API:

`Object Registry.update(Object)` -> `Identifiable Registry.update(Identifiable)`
`Object Registry.add(Object)` -> `Identifiable Registry.add(Identifiable)`
`Object Registry.get(String)` -> `Identifiable Registry.get(String)`
`Collection<Object> Registry.getAll()` -> `Collection<Identifiable> Registry.getAll()`

So any application which was compiled against the old signatures will fail to resolve the correct methods with the new version.

**Comment by danchom** [comment]
I think we have already commented this here:
https://github.com/eclipse/smarthome/pull/3670#discussion_r124230515
;)

**Comment by sjka** [comment]
No, not really. At least I was not aware of how bit the impact was.
We were discussing this as a solution with 

> very little influence about the existing API

and if you just consider the source compatibility this indeed holds true. What we missed to realize is that this change was completely incompatible in the binary level.

In any case, I realize that we won't rollback this change, so there actually is no use to keep this issue open.

**Comment by sjka** [comment]
Although done in the context of the automation component, this issue was not about the rule engine itself. Therefore removing the label.

**Comment by maggu2810** [comment]
> if you just consider the source compatibility this indeed holds true. What we missed to realize is that this change was completely incompatible in the binary level.

I have to admit that I recompile and update all bundles after a new ESH build so it has been never a problem for myself.
