### ISSUE TITLE
[Lifx] direct IP address support

### ISSUE THREAD

**Issue by paulianttila** [eclipse/smarthome#3913]
Currently lifx addon implementation is based on lifx discovery protocol, which works fine when bulbs and server is running on the same network. For security reason, my lifx bulbs are in dedicated VLAN and server (OH) is running on different VLAN. Broadcast communication is not allowed between different VLANs, so lifx addon can't find bulbs and therefore I can't control them. 

Currently only deviceId (mac address) can be manually configured to addon, and if I have understand correctly, addon then finds the IP address of the bulb by using UDP broadcast communication. 

My request is to enhance the addon and make possible to configure IP address to bulb configuration, which addon could then use directly.

**Comment by htreu** [comment]
Hey @wborn, is this something you could have a look at? Thanks in advance :-)

**Comment by wborn** [comment]
@paulianttila With #4231 you can now optionally configure the host of the light. I've succesfully tested controlling lights from another machine on another location via a VPN and Docker in bridge mode when UDP broadcasts don't work. :-)

**Comment by paulianttila** [comment]
@wborn, just tested your changes and host parameter seems to works great. Now I can control bulbs in my vlan environment without python script. Big thanks to you 👍
