### ISSUE TITLE
[Coding Guidelines] Require-Bundle header in org.eclipse.smarthome.model bundles

### ISSUE THREAD

**Issue by svilenvul** [eclipse/smarthome#3926]
I am trying to reduce the errors logged by the [Static Analysis Tool](https://github.com/openhab/static-code-analysis) in the Eclipse SmartHome repo and I found a lot of violations of the following rule (`The manifest must not contain any “Require-Bundle” entries. Instead, “Import-Package” must be used.`) in the `org.eclipse.smarthome.model.*` bundles.

I guess this was done on purpose, so my question is should we ignore these bundles ?

**Comment by kaikreuzer** [comment]
Yes, the model bundles were generated through Xtext and it isn't easily possible to get rid off the Require-Bundle directives. I'd therefore suggest to ignore the test on these bundles.

**Comment by svilenvul** [comment]
Thanks for the quick reply.

They seem to export internal packages as well, should this check be ignored as well ?

**Comment by kaikreuzer** [comment]
Would have to check, but most likely yes.
Have a try yourself and remove the export and see if stuff still works :-)

**Comment by svilenvul** [comment]
OK, they are auto generated too :), no need to check anymore.
