### ISSUE TITLE
Timezone Service Proposal

### ISSUE THREAD

**Issue by doandzhi** [eclipse/smarthome#3936]
Hello, I started the [refactoring of the DateTimeType](https://github.com/eclipse/smarthome/issues/3886) using a Java 8 class called **ZonedDateTime** which stores the timezone unlike the Calendar class (the current implementation).

   While adapting the tests of the **Astro** binding I faced difficulties working with the timezone. The given timestamps are with a certain **timezone** and to achieve the same timestamps in the test results they have to use a timezone _property_ in order to convert the values properly. Otherwise _local timezone_ is used which will cause test failures when they are not in correct timezone. The solution was to use the timezone offset as a configuration property.

   I would like to propose  implementing a  service which provides the **_timezone_** of a given _latitude_ and _longtitude_. This can be **reusable** and I believe it will come in handy later.

**Comment by Bulibas** [comment]
It seems like a very clever solution of an uncomfortable problem.

**Comment by triller-telekom** [comment]
If you want to do it based on the latitude and longitude of the current user, have a look at the
[LocationProvider](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/i18n/LocationProvider.java) and its implementation the [I18nProviderImpl](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/I18nProviderImpl.java)

At least the timezone is closely related to this and maybe should be integrated there as well.

**Comment by doandzhi** [comment]
Thank you for the suggestions! We will do it like this. I will add a getTimezone method in the LocationProvider  and  the timezone will be calculated on the modification of the managed service.

Here comes the question how would the timezone be calculated. I made some research and found quite good implementation of the needed calculations https://github.com/drtimcooper/LatLongToTimezone referencing to [this 27K LOC mapper class](https://raw.githubusercontent.com/drtimcooper/LatLongToTimezone/master/src/main/java/com/skedgo/converter/TimezoneMapper.java). The mapper class is with MIT License and it looks like a practical solution if we don't want to rely on a web service.

**Comment by triller-telekom** [comment]
Thank you for doing the research on the Timezone mapping. Indeed we would like to have something that works without a webservice. However, given that the plain .java file is 1.8MB already I think that this is probably too much. ESH is meant to be a framework which can be used by solutions builders which might use an embedded device instead of a PC or a raspberry pi, where storage will be limited.

So instead of implementing an automatic mapping, how about trying to query the underlying OS for a timezone and setting this as a default in the `LocationProvider`. A user could then choose a different one via a drop down list in PaperUI.

**Comment by triller-telekom** [comment]
@doandzhi Since you are touching our date/time datatypes, maybe you can also have a look on this [issue](594) about timestamps on the persistence api. Would be cool!

**Comment by doandzhi** [comment]
Fine, but by now the PR regarding the impacts of my changes is really solid. I suppose that it is better to make it in a separate PR. Wouldn't it be a cleaner approach?

**Comment by triller-telekom** [comment]
Sure, a separate PR makes sense. I just saw that is is related :)
