### ISSUE TITLE
result of calculation in rule is unexpected

### ISSUE THREAD

**Issue by NWiBGRsK** [eclipse/smarthome#3942]
Hi,

I spent quite some time in calculating values within a rule ... I found this behaviour, when trying to validate my results ...

  var double res1 = (2 * 2 ** 2)  //res1 is '16'
  var double res2 = (2 * (2 ** 2)) //res2 is '8'

Maybe I am wrong, but I would expect both results to be the same (both should be '8')

**Comment by kaikreuzer** [comment]
The rules use Xtend as a language. [Checking the docs](https://www.eclipse.org/xtend/documentation/203_xtend_expressions.html#operators), I read that "*" and "**" have the same precendence, therefore the results are as expected.

If you feel that this is wrong, feel free to create a ticket at https://github.com/eclipse/xtext-xtend/issues.
