### ISSUE TITLE
PaperUI - DecimalType default value of thing parameter is parsed to Int

### ISSUE THREAD

**Issue by Sydrimon** [eclipse/smarthome#3945]
I have following code describing a thing parameter:
``` 
<parameter name="targetResolution" type="decimal" required="true">
    <label>Resolution of the read Value</label>
    <description>
         Resolution of the value. Raw value will be multiplied with this.
    </description>
    <default>0.01</default>
</parameter>
```
If I try to add such thing in the UI the default value set is `0`. Integer values are shown correctly.
The backend handles the default value as String `"0.01"` and the API hands over the value `0.01`.
I assume there is something going wrong in the javascript.

**Comment by Sydrimon** [comment]
I found the source of this problem.

A decimal value gets parsed to Int [here](https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js#L197) causing this problem. 
Introduced in #3656.

Also there is a decimal value parsed to Int [here](https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js#L432), which causes the same problem.
Introduced in #1889.

Another occurrence, also related to the problem: [services.js#L484](https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js#L484).
Also introduced in #1889.

**Comment by kaikreuzer** [comment]
@htreu Can you check?
