### ISSUE TITLE
Hue binding: lightId configuration setting AND property

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#3965]
`lightId` is the main configuration setting of a hue thing but an additional `lightId` property is created with the same value.
Is there a reason to have this in double ?
Should we suppress the property ?

**Comment by kaikreuzer** [comment]
I would agree that it is not needed as a property as this is always identical to the config param.
@afuechsel, do you agree?

Btw, I also noticed that we have "serialNumber" as a configuration parameter on the hue bridge, which does not seem to make much sense to me - I would think that it is enough to have it as a property. Does anyone see a reason against removing this param?

**Comment by lolodomo** [comment]
I see that too this weekend and did not understand why the serial mumber is a configuration setting.

**Comment by afuechsel** [comment]
Yes, I was wondering, why I could actually SET the serial number when creating a thing manually. +1 for removing it.

**Comment by lolodomo** [comment]
I will propose a fix for light id and serial number.

**Comment by afuechsel** [comment]
#3985 for the other clean up tasks found in the hue binding

**Comment by lolodomo** [comment]
If you want to deal with the serial number configuration setting, you are welcome.

**Comment by kaikreuzer** [comment]
https://github.com/eclipse/smarthome/pull/3985 includes the serial number cleanup already.

**Comment by lolodomo** [comment]
Now fixed
