### ISSUE TITLE
New ImageType

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#3989]
I'm wondering if a binding generates or provides images in a channel for UIs, what is the type I should choose. I see those possible options at the moment:

* Store the image in the http/static folder and provide a link through a StringType
* Use a RawType and send the binary image. This is done here: https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/handler/ZonePlayerHandler.java#L670

This issue is either about introducing something like an ImageType with the fields `binaryData` and a `imageType` enum (JPEG,PNG,BMP,WEBP) or extending the documentation where one of the options above is recommended instead.

**Comment by maggu2810** [comment]
Doesn't an image item and a raw type do the job?
Image item already declared that the type should encode an image.
The image type could mostly be identified by a magic header or something similar and doesn't need to be set by a redundant enum (that at least must fit to the raw data itself).

So IMHO an updated documentation should do the job.

WDYT?

**Comment by davidgraeff** [comment]
I'm fine with an updated documentation with a small example if possible.

**Comment by davidgraeff** [comment]
@sjka Can you tag this as documentation? Thanks
