### ISSUE TITLE
Weather Underground: Implement Bridge with API Key

### ISSUE THREAD

**Issue by triller-telekom** [eclipse/smarthome#4000]
During the implementation of the automatic discovery in PR #3960 we noticed that the API key has to be entered for every thing. If a user wants to have multiple things, each for a different location, he has to enter the API key per thing.

The problem can be fixed by adding a bridge to the binding that holds the API key and which has things that only hold the location.

**Comment by lolodomo** [comment]
This issue can now be closed.
