### ISSUE TITLE
Localizing the thing discovery result

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4025]
It would be a good idea to localize the label of a thing discovery result to give the opportunity to each binding implementing a discovery service to provide a label that can be translated in different languages.

Several ESH bindings are currently providing a label that is hardcoded in English like for exemple "Local Time" in the NTP binding, "Local Sun" and "Local Moon" in the Astro binding or "Local Weather" in the WU binding. This label is displayed in Paper UI in the inbox. Hopefully, the user has the ability in Paper UI to update this label before the thing is finally created.

This enhancement would require the creation of a new translation service, something similar to what was implemented for the thing status description where you can use `"@text/xxx"` as description. It should be possible to use `"@text/xxx"` in the `withLabel` method of the discovey result builder.

Of course, the translation service should be requested in each place where the discovery result is used, for example in the console command displaying the discovery entries of the inbox.

If noone is voluntary, I could try to impement that.

**Comment by afuechsel** [comment]
+1 from me. Localization is an issue for the discovery results.

**Comment by JochenHiller** [comment]
Also +1 from me. Seems to be a good idea to clone the thing status approach also for I18N discovery results

**Comment by tomhoefer** [comment]
Makes definitely sense

**Comment by kaikreuzer** [comment]
@lolodomo It sounds as if your feature request found some friends ;-)
So feel free to start looking into it!

One thought: Would we really require a "dynamic" translation at any time (as it is done for config status etc.) or wouldn't it here be good enough to enable the binding to provide the label in the current system language when creating the inbox entry? Note that this label becomes the Thing label, which is also considered a user-defined field, which is therefore not dynamically translated.

If we agree that this is what we need, there shouldn't be much change necessary: The discovery services would simply have to pass a localised version of the label to `DiscoveryResultBuilder.withLabel()`. The only thing we might want to offer on the framework side is a naming convention for the property key of the format string to use and maybe some `DiscoveryResultI18nUtil` that helps on the translation using that key.

**Comment by lolodomo** [comment]
Yes the idea is to create a discovery result with a translated label. The idea is to use the usual syntax  "@text/xxx" with xxx being set in the properties file.
The only thing not clear for me is if it requires a new specific service like for the config status localization ?

**Comment by kaikreuzer** [comment]
That's what I tried to outline above - I do not see a need for a new service; a `DiscoveryResultI18nUtil` (similar to e.g. `BindingI18nUtil`) should be just fine.

**Comment by lolodomo** [comment]
I will try to implement that in the next days.
