### ISSUE TITLE
Sonos binding: Paper UI does not propose the creation of all Sonos thing types

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4036]
When trying to create manually a new Sonos thing from Paper UI, only the "Zone Player" thing type is proposed, not all the others things types.

**Comment by lolodomo** [comment]
Ok, it si due to the listed tag set to false in the XML: `<thing-type id="PLAY3" listed="false">`.
What is the reason to not let the user create manually any Sonos thing ?

**Comment by kaikreuzer** [comment]
Afair the reason was that anyhow they all had exactly the same features and thus it didn't make sense to confuse the user with a long list.

**Comment by lolodomo** [comment]
Ok, thank you for the explanation. I was afraid that the auto ingore discovery could not work in this case (different thing type) but in fact it works well too.
