### ISSUE TITLE
OH bindings no more building with the current ESH

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4042]
OH bindings building is failing with the current ESH.
It seems to be relative to JDT annotions added like `@NonNull`.
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.openhab.binding.boschindego: Compilation failure: Compilation failure:
[ERROR] D:\dev\openhab2\git\openhab2-addons\addons\binding\org.openhab.binding.boschindego\src\main\java\org\openhab\binding\boschindego\handler\BoschIndegoHandler.java:[247]
[ERROR]         public void handleConfigurationUpdate(Map<String, Object> configurationParameters) {
[ERROR]                                               ^^^
[ERROR] Illegal redefinition of parameter configurationParameters, inherited method from BaseThingHandler declares this parameter as 'Map<@NonNull String,Object>' (mismatching null constraints)
```

**Comment by kaikreuzer** [comment]
So how do you explain that https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/115/ is green...?


Anyhow, openHAB build issues do not belong in the ESH issue tracker.
The null annotations should have been addressed there through https://github.com/openhab/openhab-core/pull/179 (and others). If this does not work as expected, please file a bug there (and mention how you exactly launch the build).

**Comment by lolodomo** [comment]
I was just signaling issues (breaking API or sort of) in case you produce a new ESH build for OH. Until that, no problem of course.

**Comment by kaikreuzer** [comment]
Ok, sure, that's appreciated.
So just to get you right: If you do a local ESH build so that the artefacts are installed in the local Maven repo and you then do an openhab2-addons build, you get this error?
@triller-telekom Could you check this? Do we require people to have null annotations on every overridden method? Or what is this error trying to tell us...?

**Comment by lolodomo** [comment]
Yes, ESH build with maven and then OH2 build.
I can see all the errors in Eclipse too after a full rebuild.

**Comment by lolodomo** [comment]
It looks like that the addition of these annotations in ESH core could require a massive amount of changes in OH if all method signatures have to be updated.

**Comment by triller-telekom** [comment]
It's a bug in Eclipse JDT :(

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=463359

I have reverted the changes regarding generics on the Bindings API, see PR #4046

**Comment by lolodomo** [comment]
I can confirm that the openhab-core PR + ESH PR made OH2 buildable again with Maven.
Errors on OH2 bindings are still present in Eclipse but I imagine it is the purpose of the pending OH2 PR to fix them.
