### ISSUE TITLE
Paper Ui does not display the channel description anymore

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4043]
It is a pity to define channel descriptions and to not display them in Paper UI.
I think the channel description was present in the past but seems to have been replaced by the item type ?
My opinion is that the description would be more useful for the user than the item type.

**Comment by kaikreuzer** [comment]
It actually does, it is only extremely hidden, see https://github.com/eclipse/smarthome/issues/3824.

**Comment by lolodomo** [comment]
Oh yes it is terribly hidden !!!

If I have known that before, I could have vérified all my channel description translations in Paper UI !
