### ISSUE TITLE
[REST API] Ability to add/edit multiple items within one request

### ISSUE THREAD

**Issue by kubawolanin** [eclipse/smarthome#4060]
## Background

I'm working on a [home structure generator](https://github.com/openhab/openhab-core/pull/172) for openHAB. It allows you to create an Items collection with simple point-and-click. 

There are two forms of generated Items:
* Text file - Xtext based `*.items` file
* REST API call - Items are structured as objects that [API](demo.openhab.org/doc/index.html) understands

In order to accomplish the feature from the second bulletpoint I need to be able to pass an array of Items in one PUT request.
Otherwise hundreds of requests would be needed for each Item separately.

## Problem statement

According to [the REST docs](demo.openhab.org/doc/index.html) I can do a `PUT /items/{itemname}` to add a new Item.
There's no option to add an array of Items within one request.

See this comment: https://github.com/openhab/openhab-core/pull/172#issuecomment-322549324

## Possible solution

REST API should allow to receive `PUT /items` with the following parameter:

parameter: `body`
value:
```json
[{
  "type": "string",
  "name": "string",
  "label": "string",
  "category": "string",
  "tags": [
    "string"
  ],
  "groupNames": [
    "string"
  ],
  "groupType": "string",
  "function": {
    "name": "string",
    "params": [
      "string"
    ]
  }
}, {
  "type": "string",
  "name": "string",
  "label": "string",
  "category": "string",
  "tags": [
    "string"
  ],
  "groupNames": [
    "string"
  ],
  "groupType": "string",
  "function": {
    "name": "string",
    "params": [
      "string"
    ]
  }
},
...
]
```

**Comment by triller-telekom** [comment]
@kubawolanin I am currently looking into this issue and I am asking myself what kind of `Status` I should send for the response of such a bulk action.

As information I do have 3 lists: `added items`, `updated items`, `failed items` whose names I was planning to return in my response. So my response would contain these 3 list of names plus the `Status` code.

If I just return `Status.OK` in any case it would be up to the client to parse the lists and decide what do to. But there could also be a slightly smarter logic to return `Status.CREATED` if only the first list is populated, `Status.METHOD_NOT_ALLOWED` if only the last one is populated, and `Status.OK` in all other cases.

So which `Status` would you expect in your client?

**Comment by kubawolanin** [comment]
Hi @triller-telekom! Thank you so much for working on it!

> Edit: I have implemented it in a way that it responds OK with a detailed list of status codes.

That was my thought as well :)
Cheers
