### ISSUE TITLE
Astro range event still not applied

### ISSUE THREAD

**Issue by marcus-schneider** [eclipse/smarthome#4087]
Still neither "earliest" (tested with rise) nor "offset" (tested with set) are applied in build #1016 and #1017.

**Comment by kaikreuzer** [comment]
Correct, see https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB.

**Comment by kaikreuzer** [comment]
FTR: https://github.com/eclipse/smarthome/pull/4061 fixes that issue.
