### ISSUE TITLE
New service for providing SSL/DTLS configuration

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#4088]
At the moment there are only web services (REST, PaperUI, etc), that needs configuration for secure connection support. But this may change with further enhancements and added features, like
* the embedded Mqtt Broker ( #3910 ) and
* LwM2M support, which is based on CoAP and therefore ESH would be in the role of a CoAP server ( #4063 ).

I suggest to provide a central OSGi service to provide SSL/DTLS configuration.

## Features
* Easy for a consumer of ESH to configure private key and certificate key files in a central place (would allow to integrate this configuration into PaperUI)
* It should support means to create a secure server socket for TCP (TLS) as well as UDP (DTLS).
* Generate a single private/public key and self-signed certificate on first start for out-of-the-box HTTPS and SSL support for all running network server services. 
* If the user provides (or changes) the domain configuration, ACME would be used to sign a certificate with Let's Encrypt.
* Although the purpose of this service is to provide a single point for creating TLS sockets, to share the same certificate and keys, it might be required in some environments to create sockets in different contexts with different certificates. For instance management interfaces like PaperUI on one hand (for an internal domain) and extensions with server functionality like an embedded Mqtt broker (for an external domain) on the other hand.

## API

```
  interface NetworkServerTlsApi {
     SSLContext createSSLContext(@Nullable String context) throws SecureSocketException;

     Connector createConnector(@Nullable String context, InetSocketAddress bindToAddress) throws SecureSocketException;
  };

  @Component(service = NetworkServerTlsApi.class, configurationPolicy = 
           ConfigurationPolicy.OPTIONAL, name = "tls")
  class NetworkServerTls implements NetworkServerTlsApi {

     SSLContext createSSLContext(String context) throws SecureSocketException;

     Connector createConnector(String context, InetSocketAddress bindToAddress) throws SecureSocketException;
  };
```

* TCP/TLS: The service would provide a `getSSLContext()` method which returns a `SSLContext`. The context can be used to create a `SSLServerSocketFactory` or `SSLEngine` if necessary.
* UDP/DTLS: The use of *Element-Connector* of https://github.com/eclipse/californium/tree/master/scandium-core provides an easy interface. A method `getConnector(InetAddress)` which returns a `Connector` would be provided. (The alternative is to make the user implement his own UDP connection management with a `SSLEngine`, that would require implementing packet reordering, retransmitting, DTLS handshake.)

The methods would throw a `SecureSocketException` which wraps the original `Exception` if anything goes wrong.

## Configuration of the service

Because configuration cannot be hierarchically, we use the "|" character to map a config value to different contexts. If a requested context is not found, the "default" context is used.
The following configuration parameters are available:

* javaKeystore=/to/file|default, /another/file|keyStorePassword|otherContext
* privateKeyPassword=password|default
* domain: www.example.com|default
* presharedkey: BASE64KEY|default, ANOTHERBASE64KEY|other

If domain is set and valid, ACME will be used to request a certificate signing from Let's Encrypt.
DTLS allows PSK and some IoT devices might only support PSK. 

Advanced configuration options could be provided for algorithm selection and certificate details like:
* algorithm ("SHA1WithRSA")
* keysize  (1024)
* commonName = ("www.thedomainname.com")
* organizationalUnit = ("Eclipse Smarthome")
* organization = ("Eclipse")
* city = "somecity"
* state = "somestate"
* country = "DE"
* validity = 1096; // 3 years
* alias = "esh";

## Implementation

* `java.security.KeyPairGenerator` (public / private key)
* `sun.security.tools.keytool.CertAndKeyGen` (self signed certificate)
* [ACME library](https://github.com/shred/acme4j)

Example implementations:
* KeyPairGenerator: https://stackoverflow.com/a/6164414
* CertAndKeyGen: https://stackoverflow.com/a/7304633
* ACME: openhab/openhab-core#92

## Always valid certificates

When one of the get methods is used, the validity of the certificate is checked, if it is invalid or will be invalid within the next 7 days, a new certificate is generated (and ACME signed).

A scheduled tasks checks every 14 days (for long running ESH instances) if a certificate needs replacement.

## Discussion
1. The naming of the Service class and interface
2. The method names and signatures
3. Do we want to allow multiple context and a default context?
4. If a self-signed certificate is generated, what should be used for "Organisation", "City", "State" etc.
5. Should there be a listener interface to notify consumers of replaced/refreshed certificates?
6. Should the user be limited in what formats he can provide to us? A the moment he needs to provide a public key and private key / certificate file (with any supported format). Should we allow the user to provide a single java keystore file, too?

**Comment by kgoderis** [comment]
@davidgraeff you might want to look at the PR that I proposed some time ago in which an ACME implementation (for let's encrypt) is provided. https://github.com/openhab/openhab-core/pull/92

**Comment by davidgraeff** [comment]
@kgoderis I have seen your contribution, but in my opinion it is too short sighted because it only targets jetty. Moquette, which I use for the MqttBroker uses *netty*, and Californium for CoAP uses *scandium*.

I would rather go with a more generic approach for TCP / UDP connections, because all TCP Servers (netty+jetty) support to set a custom SSLSocketFactory and for DTLS on UDP there exists only scandium in the java world, which makes it a defacto standard until Java9 establishes Java interfaces.

But I think ACME would be awesome to have in this proposed OSGi service for creating a custom certificate.

**Comment by kgoderis** [comment]
@davidgraeff indeed, and it was the acme piece in particular that I was referring to. If that could be integrated we get a lot of benefits. It has been a while since I wrote that code so I am not sure how easy it would be.

@kaikreuzer what do you think?

**Comment by kaikreuzer** [comment]
> @kaikreuzer what do you think?

If it releases me from my bad consciousness of not having reviewed  openhab/openhab-core#92 by now, I am all for it ;-)

No, seriously: I understand @davidgraeff's request and having (optional) ACME support in that framework would be a plus.

**Comment by davidgraeff** [comment]
Is the acme library Apache or eclipse license?

_Sent from my Lge LG-F700K using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kgoderis** [comment]
@davidgraeff Apache 2.0

**Comment by kaikreuzer** [comment]
No issue for ESH then.

**Comment by davidgraeff** [comment]
To continue on this I like to discuss how the configuration for the service should be done. The following conditions need to be met:
* Hierarchical structure possible
* File config is synchronized to the service config

The OSGI properties interface would work. A value of the properties map can theoretically contain another map object. The current ConfigAdmin unfortunately does not meet criteria 2 and can not provide us with with a file format to express hierarchical structure.

I would go or a json based configuration file format therefore that is read and parsed by GSON and where the filename is expected to be the servicePID + ".json.cfg".

**Comment by kaikreuzer** [comment]
ESH has the notion of `ConfigurableService`s, which simply have to provide a `ConfigDescription` and which can then be configured through cfg files (in openHAB e.g. in `conf/services/*.cfg`) as well as through the Paper UI (Configuration->Services).

**Comment by davidgraeff** [comment]
Yup I read about that when I skimmed through the ESH packages. I haven't found it in the documentation.
It does not support tree like structures though, I assume?

**Comment by kaikreuzer** [comment]
Correct, unfortunately no trees, only flat lists.

**Comment by davidgraeff** [comment]
The ConfigDescription can handle groups. Is it possible to "simulate" a tree (depth=2) structure? For both mentioned services, I would need to describe an instance (Mqtt connection / TLS configuration) with multiple parameters. Does PaperUI support to add a new instance / "group"?

**Comment by kaikreuzer** [comment]
No, groups are only used for a logical grouping within the UI based on the parameters. Every parameter can refer to a groupId it belongs to. But you cannot create new group "instances" within a configuration.

**Comment by davidgraeff** [comment]
Can ConfigDescription and the xml dtd behind it be extended to include the concept of group-able parameters that can exist in multiple instances? There are probably more use cases than only the two services that needs this. For instance I can think of user management related configuration where a parameter group instance would consist of a username and a password.

**Comment by kgoderis** [comment]
@davidgraeff Hi David, did you make any progress on this topic/issue? e.g. a first draft/WIP of an implementation?

**Comment by davidgraeff** [comment]
Yes, #4105. The PR is done and "works", but I need a way to securely store passwords on disk. That need to be merged first before the PR can be reviewed and finalized.

**Comment by kaikreuzer** [comment]
@davidgraeff You closed this issue, while https://github.com/eclipse/smarthome/pull/4105 is still open. How shall we proceed with it? Do you still want to push https://github.com/eclipse/smarthome/pull/4105 forward or shall we close it for now?

**Comment by davidgraeff** [comment]
It needs to be done IMO. Like #5131 from Henning. I'm at the Paper UI redesign which takes 100% of my ESH/OH time. Maybe adding a WIP to the title helps?
