### ISSUE TITLE
Can't get Eclipse IDE to work, lots of errors

### ISSUE THREAD

**Issue by resetnow** [eclipse/smarthome#4094]
Every once in a while build breaks when I update my fork. Usually I do the following until it works:

1. `git reset --hard`
1. `git clean -xdf`
1. Delete `~/.m2`
1. Reinstall Eclipse
1. Delete `~/.eclipse/org.eclipse.oomph.setup` and reinstall Eclipse

Usually 1 and 2 is enough. However, right now I can't get IDE setup to work now matter what I try (and I have tried all of the above). 

Here is one of my tries:

![screenshot from 2017-08-19 12-33-25](https://user-images.githubusercontent.com/2057191/29486353-872cf9ca-84ec-11e7-8fbe-993f16494c4e.png)

I think model codegen didn't run after code import, and I can't even run it manually — it doesn't appear in run configurations and I when I import "Generate all models" through the usual `File > Import` process, nothing happens.

Here is how I set it up in Eclipse Installer:

![screenshot from 2017-08-19 12-45-33](https://user-images.githubusercontent.com/2057191/29486377-dec6384a-84ec-11e7-8312-a50f1402260a.png)
![screenshot from 2017-08-19 12-45-49](https://user-images.githubusercontent.com/2057191/29486376-dec61e46-84ec-11e7-9267-bd6148401258.png)

With all that, Maven build still works.

**Comment by kaikreuzer** [comment]
Something is odd here. The screenshots seem to tell me that you are using the openHAB IDE (not the ESH IDE). In the openHAB IDE, no esh.model projects are ever imported into the workspace as the whole Xtext code generation is not supported in that IDE. Instead, the model projects are only used as a binary from the target platform.

**Comment by kaikreuzer** [comment]
Oh, and btw, you definitely need "openHAB Development" being selected in the IDE setup!

**Comment by resetnow** [comment]
No only I needed to select “openHAB Development” (along with ESH) in the installer, I also used wrong git clone location rule. Here is how it should be:

![screenshot from 2017-08-20 12-05-51](https://user-images.githubusercontent.com/2057191/29493592-017b86a0-85a2-11e7-900a-8c7a911592f9.png)

Thank you!
