### ISSUE TITLE
Basic UI - Webview visibility change not working

### ISSUE THREAD

**Issue by biohazardxxx** [eclipse/smarthome#4096]
In basic ui the web elements are not rendered if their visibility changes to visible. After a page refresh/reload they are shown.
Since this works fine in classic UI, I strongly belive it i a bug.
My sitemap part as example:

```
Switch item=CHART_PERIOD_HW1 label="Zeitspanne" icon="line" mappings=[0="Woche", 1="2 Wochen", 2="Monat"] 			
Webview visibility=[CHART_PERIOD_HW1==0, CHART_PERIOD_HW1==Uninitialized] height=10 url="http://192.168.0.5:3000/dashboard-solo/db/openhab?orgId=1&panelId=1&from=1502893071078&to=1502914671078&theme=light"
Webview visibility=[CHART_PERIOD_HW1==1] height=10 url="http://192.168.0.5:3000/dashboard-solo/db/openhab?orgId=1&panelId=2&from=1502893996239&to=1502915596239&theme=light"
Webview visibility=[CHART_PERIOD_HW1==2] height=10 url="http://192.168.0.5:3000/dashboard-solo/db/openhab?orgId=1&panelId=3&from=1502894035198&to=1502915635198&theme=light"
```

**Comment by triller-telekom** [comment]
I just tried to reproduce your problem, but for me its working fine.

How is the underlying item `CHART_PERIOD_HW1` defined in your `.items` file?

Have you tried restarting your smarthome instance after editing the items and sitemap files? Does it work then? Maybe its a hickup while reloading them.

**Comment by biohazardxxx** [comment]
Sorry I missed your comment!
It is defined like this:

`Number	CHART_PERIOD_HW1`

Sure had several restarts. Strange is that same works ok on classic ui (used it at OH1 that way).
I am using chrome you? (can't try another one currently since my OH2 crashed :-()

**Comment by triller-telekom** [comment]
Strange now as I try it again it behaves as follows: In basicui all 3 webviews are shown below each other. In classicui only one webview is shown, depending on what button is selected.

Unfortunately I cannot remember how I defined my item when I tried it on August the 22th but to not make the same mistake again, this is how my setup looks like and how I can reproduce it:

sitemap:
```
sitemap demo label="Demo Sitemap" {

    Frame label="Test" {
        Switch item=CHART_PERIOD_HW1 label="Zeitspanne" icon="line" mappings=[0="Woche", 1="2 Wochen", 2="Monat"]           
        Webview visibility=[CHART_PERIOD_HW1==0, CHART_PERIOD_HW1==Uninitialized] height=10 url="http://www.stefantriller.de/0.html"
        Webview visibility=[CHART_PERIOD_HW1==1] height=10 url="http://www.stefantriller.de/1.html"
        Webview visibility=[CHART_PERIOD_HW1==2] height=10 url="http://www.stefantriller.de/2.html"
    }
}
```

items
```
Number CHART_PERIOD_HW1
```

@lolodomo or @resetnow do you have any idea what is wrong in basicui?

**Comment by lolodomo** [comment]
@triller-telekom : I never used webviews but I will check the current behaviour using your example.

**Comment by lolodomo** [comment]
Ok, tested and working as expected in Basic UI with Firefox and Chrome.
Only change done is replace `==Uninitialized` by `=="NULL"`.
```
	Frame label="Weather" {
		Text item=Weather_Temperature valuecolor=[Weather_LastUpdate=="NULL"="lightgray",Weather_LastUpdate>90="lightgray",>25="orange",>15="green",>5="orange",<=5="blue"] {
			Frame {
				Switch item=Weather_Chart_Period label="Chart Period" icon="chart" mappings=[0="Hour", 1="Day", 2="Week"]
                Webview visibility=[Weather_Chart_Period==0, Weather_Chart_Period=="NULL"] height=10 url="http://www.stefantriller.de/0.html"
                Webview visibility=[Weather_Chart_Period==1] height=10 url="http://www.stefantriller.de/1.html"
                Webview visibility=[Weather_Chart_Period==2] height=10 url="http://www.stefantriller.de/2.html"			}
		}
```

Refresh will not work in Microst Edge (other issue opened for that).
So I will suggest closing this issue.

**Comment by lolodomo** [comment]
Maybe @biohazardxxx 's problem is more relative to used URLs ?

**Comment by triller-telekom** [comment]
I have just tested the example again with `NULL` as lolodomo corrected my example and it does work for me with the current master branch as expected in classicui and basicui using firefox or chromium in their latest versions.

@biohazardxxx Can you please copy&paste the example from @lolodomo  and report back if the problem also occurs with this minimal example for you?

**Comment by biohazardxxx** [comment]
HI, 
I can confirm replaceing ==Uninitialized by =="NULL" made it work.
Thank you.
Case closed!
