### ISSUE TITLE
Binding Skeleton fails mvn install

### ISSUE THREAD

**Issue by RyanRamchandar** [eclipse/smarthome#4127]
I setup my esh environment on the mac following: https://eclipse.org/smarthome/documentation/development/ide.html

I was able to successfully run the Smarthome Runtime from eclipse IDE and view the PaperUI in my browser.

Before creating a binding I wanted to make sure my environment was correct. So I created a simple test binding using
```
$ ./create_binding_skeleton.sh test test
``` 
However when I call `mvn install` in its directory I get this error:
```
...
[INFO] Resolving dependencies of MavenProject: org.eclipse.smarthome.binding:org.eclipse.smarthome.binding.test:0.9.0-SNAPSHOT @ /Users/ryan/Documents/esh-workspace/smarthome-master/git/smarthome/extensions/binding/org.eclipse.smarthome.binding.test/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.smarthome.binding.test 0.9.0.qualifier
[ERROR]   Missing requirement: org.eclipse.smarthome.binding.test 0.9.0.qualifier requires 'package org.eclipse.smarthome.config.core 0.0.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.smarthome.binding:org.eclipse.smarthome.binding.test:0.9.0-SNAPSHOT @ /Users/ryan/Documents/esh-workspace/smarthome-master/git/smarthome/extensions/binding/org.eclipse.smarthome.binding.test/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

I was expecting `mvn install` to succeed and to find its jar file .

**Comment by maggu2810** [comment]
Do you try to build the whole reactor or your new bundle only?

**Comment by kaikreuzer** [comment]
@RyanRamchandar You need to execute the full build locally at least once before you are able to use the skeleton generation script.

**Comment by RyanRamchandar** [comment]
Yes that did it.

Here are the correct steps:
1. Set up dev environment via: 
https://eclipse.org/smarthome/documentation/development/ide.html
2. navigate to `smarthome` repo directory
3. run `mvn install`
4. go to smarthome/extensions/binding/
5. run `create_binding_skeleton.sh`
6. navigate to the new binding directory
6. run `mvn install`
