### ISSUE TITLE
Add a blog section to our website

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4132]
Our project website is pretty static and hasn't been touched for a long time.
I think it would be cool if we could regularly publish some content about the project, its features and progress - a blog would imho be an appropriate mechanism.

I'd therefore suggest to add a "blog" menu entry to our (Jekyll-based) website and allow the contribution of posts through standard PRs against our repo.

**Comment by maggu2810** [comment]
Makes sense.
