### ISSUE TITLE
Astro binding :  Peculiarities of the Sun phase channel

### ISSUE THREAD

**Issue by kjasdal** [eclipse/smarthome#4138]
I am using the Astro binding in my openHAB system, using the Sun / Phase channel as a way to check the "state of daylight" in my rules. 

While testing this I was looking at the log files for a "full cycle" (i.e. a 24 hour period) and I noticed a couple of strange things. 

Here is a snip of my log file:

2017-08-14 03:55:00.003 [ItemStateChangedEvent     ] - AstroSunHome_sPhase_Name changed from UNDEF to NAUTIC_DAWN
2017-08-14 05:02:00.003 [ItemStateChangedEvent     ] - AstroSunHome_sPhase_Name changed from NAUTIC_DAWN to CIVIL_DAWN
2017-08-14 05:50:00.004 [ItemStateChangedEvent     ] - AstroSunHome_sPhase_Name changed from CIVIL_DAWN to SUN_RISE
2017-08-14 05:54:00.002 [ItemStateChangedEvent     ] - AstroSunHome_sPhase_Name changed from SUN_RISE to DAYLIGHT
2017-08-14 13:34:00.002 [ItemStateChangedEvent     ] - AstroSunHome_sPhase_Name changed from DAYLIGHT to NOON
2017-08-14 21:14:00.003 [ItemStateChangedEvent     ] - AstroSunHome_sPhase_Name changed from NOON to SUN_SET
2017-08-14 21:18:00.003 [ItemStateChangedEvent     ] - AstroSunHome_sPhase_Name changed from SUN_SET to CIVIL_DUSK
2017-08-14 22:06:00.007 [ItemStateChangedEvent     ] - AstroSunHome_sPhase_Name changed from CIVIL_DUSK to NAUTIC_DUSK
2017-08-14 23:13:00.003 [ItemStateChangedEvent     ] - AstroSunHome_sPhase_Name changed from NAUTIC_DUSK to ASTRO_DUSK
2017-08-15 00:00:00.023 [ItemStateChangedEvent     ] - AstroSunHome_sPhase_Name changed from ASTRO_DUSK to UNDEF

The first thing I notice is that apparently the Sun / Phase channel will never report NIGHT as a state (contrary to what the documentation states) but instead goes back to UNDEF. 

The next thing is that the Sun / Phase channel can report a stated called NOON (and this is as stated in the documentation). As can been seen in the log this is reported as the phase from 13:34 until SUN_SET. 

As far as I know, however, NOON is a specific point in time (12:00 / midday) and not a period of time, thus (IMO) NOON should not really be reported on the Sun / Phase channel.

**Comment by triller-telekom** [comment]
> The first thing I notice is that apparently the Sun / Phase channel will never report NIGHT as a state (contrary to what the documentation states) but instead goes back to UNDEF.

This depends on your location. It might be the case that in this specific time of the year there is no astronomical night for you ;) You can use this [site](https://www.timeanddate.com/worldclock/astronomy.html) to see if there is a night at your location.

**Comment by sjka** [comment]
That would still leave the question: Why is it UNKNOWN then - even if there would be no "NIGHT" at a certain location, shouldn't it rather transition symmetrically from ASTRO_DUSK to ASTRO_DAWN then? In the definition, there is no room for an "UNKNOWN" phase.

**Comment by kjasdal** [comment]
> It might be the case that in this specific time of the year there is no astronomical night for you ;)
Although this holds true for the northern part of Norway - for parts of the year - I am afraid it does not for my part (I live at the south most tip). The site you linked to reports night as 23:26 until 03:27 for the current 24-hour period. 

The main point, however, is as @sjka pointed out; there should not be an UNKNOWN (or UNDEF as I experience) period. If there is no night, then the transition should be nautical twilight -> astro twilight -> nautical twilight.

**Comment by kjasdal** [comment]
I just took a look at the logs for the previous 24-hour period, and I see that the situation is apparently a bit different than what I thought:

2017-08-27 23:37:00.010 [vent.ItemStateChangedEvent] - AstroSunHome_sPhase_Name changed from ASTRO_DUSK to NIGHT
2017-08-28 00:00:00.028 [vent.ItemStateChangedEvent] - AstroSunHome_sDaylight_Start changed from 2017-08-27T06:23:00.000+0200 to 2017-08-28T06:25:00.000+0200
2017-08-28 00:00:00.031 [vent.ItemStateChangedEvent] - AstroSunHome_sDaylight_End changed from 2017-08-27T20:40:00.000+0200 to 2017-08-28T20:37:00.000+0200
2017-08-28 00:00:00.032 [vent.ItemStateChangedEvent] - AstroSunHome_sPhase_Name changed from NIGHT to UNDEF
2017-08-28 03:30:00.008 [vent.ItemStateChangedEvent] - AstroSunHome_sPhase_Name changed from UNDEF to ASTRO_DAWN
As can be seen, NIGHT is indeed reported (as coming after ASTRO_DUSK), however, it seems that at midnight (when the scheduler runs the astro job to calculate values for the next 24-hour period) the state is set to UNDEF, and left like that until the next state transition (which is when ASTRO_DAWN starts).

**Comment by kjasdal** [comment]
Seeing that this has gotten a "bug"-label, I just wanted to summarize what I believe are issues that should be looked at (and hopefully corrected):

1) When the DailyJob is run at midnight, the Sun Phase state is set to UNDEF. 
- This should not happen (the state should continue to be NIGHT).
2) There is a Sun Phase called NOON that seems to have a duration of one minute (although some comment in the code states that NOON has the same start and end time). 
- NOON should not be a Sun Phase since this is a specific point in time, and not a duration.
- It makes sense to keep it as an Event, though. 
- If it is difficult implementation-wise to have one and not the other, I guess NOON could be kept with a duration of 0 minutes. 
- In this case, the DAYLIGHT period needs to be split into two periods; one before NOON and one after NOON, to be able to move back to DAYLIGHT after passing NOON. As it is now, NOON continues all the way until SUNSET, :-)

**Comment by sjka** [comment]
Good summary, thanks!

1. Indeed, the first thing the DaiyJobSun does is republishing all channels with the claculations of a new sun object. This however appears to not have the correct phase calculated initially [here](https://github.com/eclipse/smarthome/blob/0bae79367d47fcd8288670c7f79afcfbb15c5a9b/extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/calc/SunCalc.java#L243). 

2. Sounds plausible to _me_. 
> If it is difficult implementation-wise to have one and not the other

Not necessarily... If you just drop [this one line](https://github.com/eclipse/smarthome/blob/9480a0b3f32b835cfd7b86f4cccfaec23f44468c/extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/job/DailyJobSun.java#L81), it's not a "phase" anymore but the events still get sent by the scheduled range (a few lines above). No need for any quirks with two DAYLIGHT jobs and the like. However, I think it's mainly a matter of how many people rely on the "NOON" phase in their rules which this would break. 

@gerrieg as the original author of the binding, do you have any particular opinion here?

**Comment by gerrieg** [comment]
1.) UNDEF should not happen
2.) Makes sense to remove NOON from the sun phase and keep it as event

@kjasdal can you please post (or send by mail) your coordinates so that i can try it myself. Then i can say more.

**Comment by kjasdal** [comment]
Here you go @gerrieg: 
Thing astro:sun:home [ geolocation="58.1461,07.9957" ]

Let me know if I can help in any other way!

**Comment by gerrieg** [comment]
I found a bug in the initial calculation of the sun phase at midnight. Will fix it soon and thanks for the bug report.

**Comment by kjasdal** [comment]
I hope this doesn't re-open the thread, but I just wanted to let you know that the fix has propagated all the way to my openHAB setup and I can confirm that it is working well. No more UNDEF's at midnight, and no more NOON's at midday, :-)

Thanks for a swift resolve!

**Comment by sjka** [comment]
> I hope this doesn't re-open the thread

Nope, all fine. Thanks for the feedback!
