### ISSUE TITLE
Line wrapping?

### ISSUE THREAD

**Issue by pearson** [eclipse/smarthome#4139]
The standard Eclipse editor option for soft line wrapping seems to be removed. (Or it is well hidden!) 

I'm new to the SmartHome Designer, but I've looked at the latest snapshot as well as the release 0.8.0, and I cannot find the soft line wrapping option anywhere. I'm using the Win 64 versions.

Is it possible to get this option back? 

Thanks!

**Comment by kaikreuzer** [comment]
Just like code, the config files are not considered to be soft-wrapped.
Note that there is no further effort put into the Designer, but other options are actively pursued now, see https://dev.eclipse.org/mhonarc/lists/smarthome-dev/msg00146.html.

**Comment by pearson** [comment]
I'd debate that point, as Eclipse's line wrapping feature is simply a visual aid for lines that are longer than a viewing window is wide. 

Thanks for the link, though. It's good to know that it's a waste of time to work on this code base.
