### ISSUE TITLE
Dynamic changes to the channel type parameters

### ISSUE THREAD

**Issue by ppieczul** [eclipse/smarthome#4140]
## Introduction

The goal for this topic is to agree on the changes required in the framework in order to support dynamic changes to some of the channel type characteristics. An examples are: value to text mappings (options) and format string, which are provided as part of the channel type definition, either in xml or through a channel type provider programatically. Also, we can think of extending it to other channel type parameters, i.e. min/max/step values and read-only attribute, although I don't have a real life use case for them today.

Current design seems to assume that channel types are to be available when thing becomes online and they should not change during its lifetime. For example, Paper UI is designed around this assumption and is able to refresh channel changes dynamically, but not channel types.

In some circumstances it is needed to at least update the definition of channels types, based on the information received in the runtime from a remote device under binding supervision. One example is Loxone binding, which can receive from the Miniserver an update with a new definition of labels for lighting controllers, while the device remains connected and operating all the time. It is a change in the device configuration that we need to reflect in the openHAB.

Before we jump to the design of what needs to be done, I'd like to agree on the assumptions for the changes. Here is how I see this situation.

## End user use cases

I think that there is basically one requirement that affects what end user will see:

  * User should see the dynamic changes to the available channel type options and format immediately as they happen on the remote device (thing). They should become visible in the UIs and rest API, providing that the user has not provided custom configuration of these parameters through configuration files. There should be no interruption to the thing operation, for example thing should not go offline and online again for these changes to be visible.

@Kai, for now I would like to review and agree on the assumptions, the use cases and set of parameters that we should be allowing for dynamic modifications, so that we are on the same page wrt requirements for the change.

Thank you
Pawel

**Comment by kaikreuzer** [comment]
FTR: This discussion was started during the Loxone bindin review here: https://github.com/openhab/openhab2-addons/pull/2423#discussion_r132446174

My suggestion there was not to allow channel types to be dynamic, but rather to provide a way to dynamically contribute to a StateDescription from within a binding (currently this is only static through the `ChannelStateDescriptionProvider`, which derives its input from the channel type.

**Comment by davidgraeff** [comment]
I thing, I had the same problem (assuming that I understood the problem) in the OpenHAB Yamaha binding. The device returned a list of supported input modes, and I needed to create a channel type dynamically with the given modes as state options:

 https://github.com/openhab/openhab2-addons/blob/c8bd7f9ebda6be35d76bb37a8b98cda8fdf97aca/addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderAvailableInputs.java#L77

Is this related?

**Comment by ppieczul** [comment]
It may be relevant. If your channels could share the same channel type, if only you did not have to provide format and options to the channel type, then I think it is relevant. The other thing is whether you have this information at initialization time or before thing goes online or after thing goes online. In my case this is the worst situation - after the thing goes online.

There is also harmony hub binding, which may be relevant - there the bridge creates channel with lists of activities received from the hub. If not the list, it could possibly use shared type for all activity channels for various hubs.

What makes me wonder is why channel types at all? They are useful as programatic template until channel is created. But why are they runtime entities? What would be the consequences if all the channel type attributes were actually channel attributes? It would be interesting to know statistical information about type:channel relationship, how many of them are 1:1 and how many n:1 - what are we saving by having channel types.

**Comment by ppieczul** [comment]
Ok, let's start with that. I will need your help as my understanding of how Eclipse smarthome is designed is just building up now. My initial idea would be:
  * In `org.eclipse.smarthome.core.thing.type` create a `ChannelTypeStateDescriptionProvider` interface with a method to resolve `ChannelTypeUID` into `StateDescription`
  * Create a registry of providers in a similar way to `ChannelTypeProvider`, add it to bundle activator
  * Now, for a dynamic provisioning of `StateDescription`, I am thinking of modifying a `getStateDescription()` method of `ChannelStateDescriptionProvider` class to take into account all state description providers when resolving item name into state description. It would take precedence over the value from `ChannelType`
  * But maybe it could be taken into account more broadly, in `ChannelTypeRegistry`, inside `getChannelType`?

Please comment.

Thanks
Pawel

**Comment by ppieczul** [comment]
On a second thought, this will be not enough, because to differentiate the state descriptions per channel for the same channel type, I will need to map Channel to StateDescription, not ChannelType. Then it leaves only the third bullet as a possible option.

**Comment by ppieczul** [comment]
@kai can you look the code in #4238 - I tried to model what I think it could be

**Comment by kai** [comment]
> @kai can you look the code in #4238 - I tried to model what I think it could be

@ppieczul You probably [meant to mention](https://github.com/eclipse/smarthome/graphs/contributors) @kaikreuzer, rather than me

**Comment by kaikreuzer** [comment]
@ppieczul Very sorry to be so late with further comments.
As already mentioned in https://github.com/eclipse/smarthome/issues/4140#issuecomment-325209748, I think that channel types should not be a part of the discussion/implementation at all - so it feels to me as if most of your outline above heads the wrong direction.

> I am thinking of modifying a getStateDescription() method of ChannelStateDescriptionProvider class to take into account all state description providers when resolving item name into state description. It would take precedence over the value from ChannelType

This is actually imho exactly what we need. At the moment, this implementation only looks at the channel type information, so we would have to add a hook, through which bindings would be allowed to "tweak" the information for certain channels (not sure about a good name for such a hook interface as `ChannelStateDescriptionProvider` is already taken).

But if I do not overlook anything, such a new hook interface is all that is required - no need for introducing any new registries, etc.

**Comment by ppieczul** [comment]
So would that mean extending the `Channel` class with a method that could be overridden in a binding and used for resolution of the state description?

**Comment by triller-telekom** [comment]
I think what @kaikreuzer means is that bindings can define a service reference to `ChannelStateDescriptionProvider` in their handler factory. The `ChannelStateDescriptionProvider` then needs a new method to register `DynamicChannelStateDescriptionProvider`s (or whatever cool name you can come up with for the new interface).

The binding can define such a `DynamicChannelStateDescriptionProvider` and register it there.

[Inside the ChannelStateDescriptionProvider](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelStateDescriptionProvider.java#L71) you can iterate over the registered providers and select the description. Your PR is doing something like that already, but a little more complicated with your new registry etc.

**Comment by kaikreuzer** [comment]
@triller-telekom Almost correct, besides the fact that you do not need the "service reference to ChannelStateDescriptionProvider in their handler factory" - "binding can define such a XXXProvider and register it" should imho be enough.

**Comment by ppieczul** [comment]
@triller-telekom @kaikreuzer Ok, so I think I don't understand how this is different to what I modeled and where do hooks come into this picture. A binding registers an implementation of the provider and that's it - it will be called when a state description is being prepared. 
If this is about the registry - can you guide me where else should I gather the information about various implementations of the provider?
Thanks

**Comment by triller-telekom** [comment]
Yes it is about the registry, you do not need it.

Inside the ´ChannelStateDescriptProvider` you can create a service reference to the new interface `DynamicStateDescriptionProvider`

```
@Reference(cardinality=ReferenceCardinality.MULTIPLE)
    protected void addDynamicStateDescriptionProvider(DynamicStateDescriptionProvider dynamicStateDescriptionprovider) {
        this.dynamicStateDescriptionProviders.add(dynamicStateDescriptionprovider);
    }
```

This, together with your hooking code that iterates over this provider list and applies the description, is enough.

**Comment by ppieczul** [comment]
I think I need help. I am able to build whole smarthome from top level. Well, not whole, because marytts hangs in tests. But at least it goes that far.

But how can I build a single project in smarthome? I would like to build just the one I modify and later also run the tests. 

When I enter a subdirectory, e.g. `smarthome/extensions/ui/org.eclipse.smarthome.ui.paper` and run `mvn install`, I am getting an error: `Could not resolve target platform specification artifact`.

I also tried running `mvn --projects <project> install` from the top level, but I can't figure out what to pass as a project. Any obvious name as "Eclipse SmartHome Paper UI" or java package does not work.

Thanks in advance

**Comment by kaikreuzer** [comment]
@ppieczul Partial builds are a bit tricky due to Tycho.
What works for me is to run a full build ("mvn clean install") from the root of the project. After this, you should have all required artefacts as snapshots in your local repo and subsequent partial builds (like a "mvn install" in the Paper UI folder) should then work.

**Comment by ppieczul** [comment]
@kaikreuzer Your hint helped me a lot - actually it is pretty convenient for me to build single module and also I figured out how to run a single test. I might ask for a bit of advise on my next step.

I would like to bring the local changes in the smarthome into openhab to test it with the bindings. Eclipse builds the smarthome projects in Runtime working set just fine. But for the launch, all the bundles are used from the target environment, not from the workspace, so the compiled projects are just not executed.

If I select a single project to be taken from the workspace (like org.eclipse.smarthome.core.thing), it does not work (lots of exceptions), I suppose it is too much incompatibilities between workspace and target for a single project to work. But I don't know what set of projects to select to make it work. Any hints? Thanks.

**Comment by ppieczul** [comment]
@davidgraeff the feature is now in and you may take a look if it makes sense for the Yamaha binding to get rid of the channel type provider and move to the dynamic state description provider.
As an example I have implemented this in my binding: https://github.com/openhab/openhab2-addons/pull/2786
Thanks
Pawel
