### ISSUE TITLE
PaperUI: add new channels to things

### ISSUE THREAD

**Issue by htreu** [eclipse/smarthome#4142]
For generic bindings like KNX (see https://github.com/openhab/openhab2-addons/pull/2323), MQTT (see #3876) and others, where things are used to structure generic things with a user defined sub-list of channels the PaperUI should provide a feature to add channels to things.
This results in the following tasks:
- identify if its allowed to add channels to a specific thing
- provide an "Add channel" button to those things
- Select one of the available channel-types for the thing
- Edit the channel configuration
- Add the channel and configuration to the thing via REST

Only the "identify if channels can be added to thing" part needs changes in the core framework. The first idea is to provide a flag on the thing-type definition to indicate this.

**Comment by kaikreuzer** [comment]
> Only the "identify if channels can be added to thing" part needs changes in the core framework

See https://github.com/eclipse/smarthome/issues/4146.
