### ISSUE TITLE
MqttService API break

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#4170]
As we don't have any consumers of the MQTT API right now (they would have been affected by the reconnect bug that just recently got fixed), we should discuss some little API breaks that I strongly recommend:

In MqttBrokerConnection:
* Rename close() to stop(). The semantic of close is usually, that the object cannot be used anymore. Stop would be matching with start(). Alternatively call start() open() instead.
* Remove all deprecated methods.

Cheers, David

**Comment by maggu2810** [comment]
At least me is using the MQTT transport bundle and has been affected by the reconnect bug.
But the changes are okay for me.

**Comment by davidgraeff** [comment]
I thing the URL should stay, paho uses this: https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttAsyncClient.html#MqttAsyncClient-java.lang.String-java.lang.String-

**Comment by maggu2810** [comment]
IIRC @kaikreuzer dislike the `tcp` and `ssl` prefix.
Does it care which representation paho is using? We are using an abstraction layer, so if we would like to use `host`, `port`, `useSSL`, we could build the paho URL using that three information. If we ever move from paho to another implementation, we could build (using this three information) another URL representation.

**Comment by davidgraeff** [comment]
I changed the url to host+port+secure and removed the name from the connection as well as the textualConfigured flag.
