### ISSUE TITLE
Component XML generation broken for services with a configuration-pid

### ISSUE THREAD

**Issue by sihui62** [eclipse/smarthome#4179]
https://community.openhab.org/t/oh-2-2-0-snapshots-1025-1028-zwave-npe/33711/65

**Comment by kaikreuzer** [comment]
The issue is that Felix Fileinstall writes this entry to the config file:
```
autoLinks = B"false"
```
I assume that the link service does not correctly handle boolean (instead of string) values.

**Comment by maggu2810** [comment]
```Java
Object value = context.getProperties().get("autoLinks");
autoLinks = value == null || !value.toString().equals("false");
```

I assume there is a missing "to lower case" between `toString()` and `equals`

**Comment by maggu2810** [comment]
I has been wrong. The code should be correct:

```Java
    public static void test(final Object value) {
        final boolean flag = value == null || !value.toString().equals("false");
        System.out.println(String.format("%s => %b", value, flag));
    }

    public static void main(final String args[]) {
        test("true");
        test("false");
        test(true);
        test(false);
        test(Boolean.TRUE);
        test(Boolean.FALSE);
    }
```

```text
true => true
false => false
true => true
false => false
true => true
false => false
```

**Comment by kaikreuzer** [comment]
My suspicion was apparently wrong. It seems that the configuration is just fine.
If I call GET http://localhost:8080/rest/services/org.eclipse.smarthome.links/config I get
```
{
  "felix.fileinstall.filename": "file:/Users/kai/Downloads/oh/userdata/etc/org.eclipse.smarthome.links.cfg",
  "autoLinks": false
}
```
Also, the toggle in the Paper UI correctly is in "off" state:

<img width="851" alt="screen shot 2017-09-05 at 16 46 07" src="https://user-images.githubusercontent.com/3244965/30067145-48138c4c-925a-11e7-8394-a7567d53496a.png">

Nonetheless, the "Items" menu is not visible.
I therefore assume that it must be an issue in the Paper UI - @htreu Could you have a look?

**Comment by kaikreuzer** [comment]
We have tracked down the issue to be a bug in the XML generation during the Maven build:
https://issues.apache.org/jira/browse/FELIX-5506

This effectively means that all our services that rely on a specific configuration-pid are currently broken. 😢

**Comment by maggu2810** [comment]
:open_mouth:

**Comment by maggu2810** [comment]
Should we add the `Critical` label?

**Comment by kaikreuzer** [comment]
Yes and I also updated the title to reflect that this is actually not at all about the Paper UI.

**Comment by maggu2810** [comment]
Should we try to use the attached patch (JIRA) and build a r1 of the SCR plugin?

**Comment by htreu** [comment]
The most promising solution right now is to re-package the org.apache.felix:org.apache.felix.scr.ds-annotations jar and apply the fix described in https://issues.apache.org/jira/browse/FELIX-5506.
Question: do we re-package with the original groupID/artifactId and only change the version number to the version we provide, or de we re-package with our own o.e.sh groupId?
Same question for the package itself: duplicate the apache package structure including license headers or provide o.e.sh package names with Eclipse license headers?

**Comment by htreu** [comment]
@maggu2810 I already have this build at hand. please let me know how you think about providing the library in terms of naming/packaging (see https://github.com/eclipse/smarthome/issues/4179#issuecomment-327697004).
I already have it in the `tools` module which can be build first in the reactor build:
```
[INFO] Reactor Summary:
[INFO] 
[INFO] Eclipse SmartHome .................................. SUCCESS [  0.255 s]
[INFO] Eclipse SmartHome Tools ............................ SUCCESS [  0.028 s]
[INFO] Eclipse SmartHome Archetypes ....................... SUCCESS [  0.097 s]
[INFO] Eclipse Smarthome Binding Archetype ................ SUCCESS [  0.640 s]
[INFO] Eclipse Smarthome Binding Archetype Testsuite ...... SUCCESS [  0.048 s]
[INFO] Eclipse SmartHome DS AnnotationProcessor - Apache Felix SCR drop in replacement SUCCESS [  1.096 s]
[INFO] Eclipse SmartHome Bundles .......................... SUCCESS [  0.067 s]
[INFO] Eclipse SmartHome Test Components .................. SUCCESS [  0.010 s]
[INFO] Eclipse SmartHome Core Components .................. SUCCESS [  0.010 s]
```

This way it will be available for all other artefacts to build the DS meta files.

**Comment by kaikreuzer** [comment]
@htreu I'd think the main issue with this approach is that we cannot take the sources of the Felix and add them to the ESH repository. It might be easier to build it by hand and host it as a plugin externally as a temporary solution.

**Comment by htreu** [comment]
This sounds like groupId/artifactId/package names will all remain apache original but with a different version. Do we have an external maven repo to host the artifact?

**Comment by kaikreuzer** [comment]
I could offer hosting it at JCenter (which we anyhow already have listed as a plugin repo), but I would then change the group id to "org.openhab" as it should be made clear that it isn't an official release from Apache.

**Comment by htreu** [comment]
okay, I will provide a PR changing the pom.xmls here and the artifact for hosting at JCenter.

**Comment by maggu2810** [comment]
My favorite would be changing the group ID and the version.
I prefix the group ID mostly with a domain under my control and 'thirdparty', so e.g. if you would like to use openHAB "org.apache.felix" => "org.openhab.thirdparty.org.apache.felix".
If you change a stable release you could append a `.sp1` to the version (see e.g. [ComparableVersion])

[ComparableVersion]: https://maven.apache.org/ref/3.0.3/maven-artifact/apidocs/org/apache/maven/artifact/versioning/ComparableVersion.html

**Comment by kaikreuzer** [comment]
Issue is fixed in latest openHAB distro 1034.

**Comment by gismofx** [comment]
Thanks! I just pulled 1034 and _Items_ are back!
