### ISSUE TITLE
Inbox auto ignored results are never removed

### ISSUE THREAD

**Issue by afuechsel** [eclipse/smarthome#4187]
When adding e.g. a hue bridge manually, its result is automatically set to IGNORED in the inbox as expected. When removing the bridge, the IGNORED entry in the inbox must be automatically deleted so a new discovery can find it again. It turns out, that this is not happening most of the time.

The reason is, that we do not have such a thing as a Pre-Delete-Hook, where we could easily check and remove possible ignored entries.Listening to ThingStatusChangedEvents as currently implemented does not help, because a REMOVED event indicates that a thing is already removed and REMOVING is not always fired and sometimes directly followed by a REMOVED. In most cases we are accessing the ThingRegistry too late to get informations about the thing being removed (it just returns null).

**Comment by dominicdesu** [comment]
This fix might have caused a small issue with the hue binding, please see #4375
