### ISSUE TITLE
Inbox auto-ignores discovery results when representation property value matches, but thing type does not

### ISSUE THREAD

**Issue by hsudbrock** [eclipse/smarthome#4191]
The inbox auto-ignore feature ignores discovery results if the representation property value of the discovery result is the same as the representation property value of an existing thing. In consequence, discovery results are ignored even if there is an existing thing of a different type with the same representation property value.

Context: The representation property value is something that is in some sense unique for all things of that type of thing (e.g., serial number, ID assigned by bridge, MAC address, ...).

 I believe that one should not compare representation property values of different thing types, as this could clash (e.g., if the serial numbers for some type of light bulb look, by chance, the same as the serial numbers of some type of switch).

I added a unit test illustrating this behavior here: https://github.com/hsudbrock/smarthome/tree/thing-type-not-considered-when-autoignoring-in-inbox

In a discussion with @kaikreuzer, it came up that it might be necessary to also not compare representation property values if things/discovery results are attached to different bridges, to not ignore a discovery result for one bridge just because there is a thing attached to another bridge with the same ID assigned to by the bridge.

**Comment by afuechsel** [comment]
@hsudbrock Would it be possible to post your test code here? 

About the issue, you are absolutely right, this needs to be fixed. Also the bridge issue with different bridges should be solved in a potential PR.

**Comment by hsudbrock** [comment]
@afuechsel Yes, I can post the test code here. It is probably not a "minimal" test, since I adapted one of the existing unit tests for the auto-ignore feature for it. I stripped the class AutomaticInboxProcessorTest down to make it somewhat more readable here (see https://github.com/hsudbrock/smarthome/commit/1d095d10060aa0ba4d59b9dbea8a0b8916b7f595 for the complete class with my added test).

Here is the stripped down version of AutomaticInboxProcessorTest with only my added test:

```java
public class AutomaticInboxProcessorTest {

    // Excerpt of the AutomaticInboxProcessorTest

    private static final String DEVICE_ID = "deviceId";
    private static final String DEVICE_ID_KEY = "deviceIdKey";
    private static final String OTHER_KEY = "otherKey";
    private static final String OTHER_VALUE = "deviceId";
    private static final String CONFIG_KEY = "configKey";
    private static final String CONFIG_VALUE = "configValue";

    private static final ThingTypeUID THING_TYPE_UID = new ThingTypeUID("test", "test");
    private static final ThingTypeUID THING_TYPE_UID3 = new ThingTypeUID("test3", "test3");

    private static final ThingUID THING_UID = new ThingUID(THING_TYPE_UID, "test");
    private static final ThingUID THING_UID3 = new ThingUID(THING_TYPE_UID3, "test3");

    private static final ThingType THING_TYPE = new ThingType(THING_TYPE_UID, null, "label", null, true, DEVICE_ID_KEY,
            null, null, null, null);
    private static final ThingType THING_TYPE3 = new ThingType(THING_TYPE_UID3, null, "label", null, true, OTHER_KEY,
            null, null, null, null);

    private final static Map<String, String> THING_PROPERTIES = new ImmutableMap.Builder<String, String>()
            .put(DEVICE_ID_KEY, DEVICE_ID).build();
    private final static Map<String, String> OTHER_THING_PROPERTIES = new ImmutableMap.Builder<String, String>()
            .put(OTHER_KEY, OTHER_VALUE).build();
    private final static Configuration CONFIG = new Configuration(
            new ImmutableMap.Builder<String, Object>().put(CONFIG_KEY, CONFIG_VALUE).build());

    private AutomaticInboxProcessor inboxAutoIgnore;
    private PersistentInbox inbox;

    @Mock
    private ThingRegistry thingRegistry;

    @Mock
    private ThingTypeRegistry thingTypeRegistry;

    @Mock
    private Thing thing;

    @Mock
    private Thing thing3;

    @Mock
    private ThingStatusInfoChangedEvent thingStatusInfoChangedEvent;

    @Mock
    private ConfigDescriptionRegistry configDescriptionRegistry;

    @Mock
    private ThingHandlerFactory thingHandlerFactory;

    @Mock
    private ManagedThingProvider thingProvider;

    @Before
    public void setUp() throws Exception {
        initMocks(this);

        when(thing.getConfiguration()).thenReturn(CONFIG);
        when(thing.getThingTypeUID()).thenReturn(THING_TYPE_UID);
        when(thing.getProperties()).thenReturn(THING_PROPERTIES);
        when(thing.getStatus()).thenReturn(ThingStatus.ONLINE);
        when(thing.getUID()).thenReturn(THING_UID);

        when(thing3.getConfiguration()).thenReturn(CONFIG);
        when(thing3.getThingTypeUID()).thenReturn(THING_TYPE_UID3);
        when(thing3.getProperties()).thenReturn(OTHER_THING_PROPERTIES);
        when(thing3.getStatus()).thenReturn(ThingStatus.ONLINE);
        when(thing3.getUID()).thenReturn(THING_UID3);

        when(thingRegistry.stream()).thenReturn(Stream.empty());

        when(thingTypeRegistry.getThingType(THING_TYPE_UID)).thenReturn(THING_TYPE);
        when(thingTypeRegistry.getThingType(THING_TYPE_UID3)).thenReturn(THING_TYPE3);

        when(thingHandlerFactory.supportsThingType(eq(THING_TYPE_UID))).thenReturn(true);
        when(thingHandlerFactory.createThing(eq(THING_TYPE_UID), any(Configuration.class), eq(THING_UID),
                any(ThingUID.class)))
                        .then(invocation -> ThingBuilder.create(THING_TYPE_UID, "test")
                                .withConfiguration((Configuration) invocation.getArguments()[1]).build());

        inbox = new PersistentInbox();
        inbox.setThingRegistry(thingRegistry);
        inbox.setStorageService(new VolatileStorageService());
        inbox.setManagedThingProvider(thingProvider);
        inbox.setConfigDescriptionRegistry(configDescriptionRegistry);
        inbox.setThingTypeRegistry(thingTypeRegistry);
        inbox.addThingHandlerFactory(thingHandlerFactory);

        inboxAutoIgnore = new AutomaticInboxProcessor();
        inboxAutoIgnore.setThingRegistry(thingRegistry);
        inboxAutoIgnore.setThingTypeRegistry(thingTypeRegistry);
        inboxAutoIgnore.setInbox(inbox);
    }

    /**
     * This test is just like the test testThingWentOnline in the AutomaticInboxProcessorTest, but in contrast to the
     * above test (where a thing with the same thing type and the same representation property value went online) here a
     * thing with another thing type and the same representation property value goes online.
     * <p/>
     * In this case, the discovery result should not be ignored, since it has a different thing type.
     */
    @Test
    public void testThingWithOtherThingTypeButSameRepresentationPropertyWentOnline() {
        // Add discovery result with thing type THING_TYPE_UID and representation property value DEVICE_ID
        inbox.add(DiscoveryResultBuilder.create(THING_UID).withProperty(DEVICE_ID_KEY, DEVICE_ID)
                .withRepresentationProperty(DEVICE_ID_KEY).build());

        // Then there is a discovery result which is NEW
        List<DiscoveryResult> results = inbox.stream().filter(withFlag(DiscoveryResultFlag.NEW))
                .collect(Collectors.toList());
        assertThat(results.size(), is(1));
        assertThat(results.get(0).getThingUID(), is(equalTo(THING_UID)));

        // Now a thing with thing type THING_TYPE_UID3 goes online, with representation property value being also the
        // device id
        when(thingRegistry.get(THING_UID3)).thenReturn(thing3);
        when(thingStatusInfoChangedEvent.getStatusInfo())
                .thenReturn(new ThingStatusInfo(ThingStatus.ONLINE, ThingStatusDetail.NONE, null));
        when(thingStatusInfoChangedEvent.getThingUID()).thenReturn(THING_UID3);
        inboxAutoIgnore.receive(thingStatusInfoChangedEvent);

        // Then there should still be the NEW discovery result, but no IGNORED discovery result
        // However, this currently fails since the discovery result is auto-ignored, as it has the same representation
        // property value as the thing that just went online
        results = inbox.stream().filter(withFlag(DiscoveryResultFlag.NEW)).collect(Collectors.toList());
        assertThat(results.size(), is(1));
        assertThat(results.get(0).getThingUID(), is(equalTo(THING_UID)));
        results = inbox.stream().filter(withFlag(DiscoveryResultFlag.IGNORED)).collect(Collectors.toList());
        assertThat(results.size(), is(0));
    }

}
```

**Comment by maggu2810** [comment]
I agree that this needs to be solved.

Shouldn't it be responsible to the binding itself to choose a representation property that is unique?
The binding could use the binding ID as prefix for the "normal" representation property.
If the type is relevant the binding could use the binding ID + thing type as prefix for the "normal" representation property.

> it came up that it might be necessary to also not compare representation property values if hings/discovery results are attached to different bridges

If the representation property is changeable at runtime the binding could use binding ID + thing type + bridge UID as prefix for the "normal" representation property.

**Comment by hsudbrock** [comment]
@maggu2810 I agree that it should also work to let the binding itself choose a representation property that is unique amongst all bindings (e.g., as you suggest, by including the binding ID or the thing type ID or the bridge ID in the representation property values).

However, I think that the "safer" way would not to rely on the correctness of the bindings here, but to include a check in Eclipse SmartHome itself (i.e., auto-ignoring discovery results only if a thing _of the same thing type_ with the same representation property value exists).

**Comment by sjka** [comment]
> auto-ignoring discovery results only if a thing of the same thing type with the same representation property value exists

Thing type or binding ID? Remember, some nasty little buggers might change their thing type - either during pairing when the binding finds out more details, or e.g. after a firmware upgrade.

**Comment by hsudbrock** [comment]
@sjka I see. Then one should probably use the binding ID, i.e. "auto-ignore discovery results only if a thing from the same binding (i.e., with the same binding ID) and with the same representation property value exists". I.e., bindings would be responsible to ensure that the representation property is unique across all thing types that the binding provides, and we would avoid the danger that (in some possibly rare case) a thing from one binding is ignored just because a thing from another binding has the same representation property value.

**Comment by sjka** [comment]
Sounds reasonable to me.

**Comment by lolodomo** [comment]
To me too.

**Comment by kaikreuzer** [comment]
> > Then one should probably use the binding ID

> Sounds reasonable to me.

Does it still sound reasonable when seeing https://github.com/eclipse/smarthome/issues/4710?
We now have the situation that two different thing types from the same binding have the same representation property - and our current mechanism fails miserably. What shall we do about it?

#4710 seems to me to be a more important case than migrated thing types for the moment - so if we have to choose the one over the other, I'd rather vote for checking against the thing type for now.

**Comment by sjka** [comment]
Well, I guess you have a point there. I wan't aware that they don't have to be unique.

**Comment by afuechsel** [comment]
@kaikreuzer @sjka I am a little bit lost. Why do different things of different thing types of the same binding have the same representation property VALUE in case of #4710?

**Comment by sjka** [comment]
The representation property was meant to help users to distinguish two different devices of the same type, and therefore the contract was like that since the beginning. The astro binding e.g. uses the same representation property for both, sun _and_ moon at the same location. And others may do so too. The documentation also doesn't say that it needs to be unique per binding.

I wasn't aware of this either. It somehow also make sense though.

**Comment by maggu2810** [comment]
WRT https://github.com/eclipse/smarthome/issues/4191#issuecomment-327404159 can't the developer choose what should be unique?
Couldn't we use
* binding-id:thing-type:prop-name if binding ID and thing type should fit
* :thing-type:prop-name if the binding could differ but the thing type should fit
* binding-id::prop-name if the binding has different types but that ones should not matter

**Comment by kaikreuzer** [comment]
Not sure how that should exactly look like if different types of the same binding declare different formats for the representation property. But happy to discuss, while I think it will take some efforts to get that in place.

To have a quick solution for #4710 (which I consider rather major as it directly affects a popular ESH binding in its normal behavior), I would suggest to change the current implementation to check for the thing-type, because this is the most obvious behavior and it matches our documentation.

The case with migrated thing types is pretty rare and thinking about it it would also only be an issue if someone manually defines devices using a different thing UID for them. The bindings that use type migration (BLE+ZWave) are anyhow rather used through discovery only and in that case we have the same thing UID (before and after migration), so we won't see duplicates in the inbox in any case.

**Comment by triller-telekom** [comment]
I have created PR #4731 which implements comparing the thingtype-uid instead of the bindingid.
