### ISSUE TITLE
Registry for RESTResource(s)

### ISSUE THREAD

**Issue by amitjoy** [eclipse/smarthome#4193]
I believe it would be a useful OSGi service to track all the registered RESTResource(s) or the URI paths registered by the available RESTResource(s). I am opening this issue (or specific feature request) to start discussing it.

**Comment by kaikreuzer** [comment]
Well, we already have `RootResource`, which does that. It doesn't provide that info as an OSGi service, though, it only serves it to the REST API. Why do you think it would be useful to have such an OSGi service?

**Comment by amitjoy** [comment]
Any consumer application might need to check the list of REST URIs registered in the runtime. A concrete use-case would be as follows:

1. Bundles can provide REST configuration by specifying REST endpoints to be consumed by the respective bundle
2. Such a Registry would facilitate checking if the specified REST service is at all registered in the runtime
3. If it is registered but not specified in bundle-specific REST configuration, it should encounter FORBIDDEN 403
4. If it is not registered but specified in the bundle-specific REST configuration, it should encounter 404.

This is an example scenario in which I feel the need of a REST Registry. It can also be made available in the project but I believe it would be a good to have it in ESH.

**Comment by maggu2810** [comment]
I assume @sjka does know more about "com.eclipsesource.jaxrs.publisher" as he already looked into it while implementing the resource filter recently.

Just thinking about it what could be done...
* All ESH REST resources could be blacklisted for the "com.eclipsesource.jaxrs.publisher" so they are not scanned.
* Perhaps we could implement it in a way we do not depend on that publisher implementation at all and drop it in the runtime
* We could create our own publisher that using DS with a dynamic multiple reference to e.g. interface "EshRestResource". Every time a new reference is bound, it register that reference to JAX-RS.
* The "EshRestResource" interface is implemented by our REST resources and they will be components.
* EshRestResource could define a method `@NonNull String getRelativePath()` that returns the path relative to the REST root one

I assume a publisher that does not scan all resources and using a publisher that only act on OSGi references could be good at all.

**Comment by kaikreuzer** [comment]
@maggu2810 I understood the request to be completely independent of any jaxrs.publisher discussion.

**Comment by maggu2810** [comment]
Me, too but while I think about an implementation for the solution I realized that we could kill two birds with one stone.

**Comment by JochenHiller** [comment]
I would like to give more details why @amitjoy came up with that issue.

We are using the com.eclipsesource.jaxrs.publisher in our commercial product based on Eclipse SmartHome. We have added security stuff to the REST endpoints, where we can give (or deny) permissions to access resources and verbs based on caller identity (based on OAuth2 tokens).

We have such kind of filter implemented:
* if no access token given, or invalid/expired token, we return a 401 (Unauthorized)
* if access token is valid, but permission for endpoint/verb for caller identity is missing, we return a 403 (Forbidden)  
* if access token is valid, but endpoint is wrong (e.g. /rest/blablub) we initially thought to return a 404 (Not Found)

This would need to know which kind of endpoints are available, therefore the idea to know which REST resources are registered in runtime.

We had a follow-up discussion if it is good or bad to return a 404 in case of an invalid endpoint URL. One can argue that delivering a 404 would give an attacker more information than needed. So returning a 403 for an invalid endpoint URL would be also fine, as the caller even has made something wrong: either calling invalid endpoint, or missing permissions to call a valid endpoint.

I propose to NOT invest time/code into such a solution, as I do see too less benefit, even maybe exposing too much information in case of protected REST resources. So I would reject that issue.

Any thoughts?

**Comment by sjka** [comment]
> So returning a 403 for an invalid endpoint URL would be also fine, as the caller even has made something wrong: either calling invalid endpoint, or missing permissions to call a valid endpoint.

To my knowledge that's not only fine, but rather the proper way of doing it. 

> So I would reject that issue.

Sounds good, unless anybody sees another valid use-case for it.

@maggu2810 I would treat revolutionizing the publisher as a separate issue then, if you still feel like giving it a go 😄

**Comment by maggu2810** [comment]
So, if the issue has been rejected (@amitjoy I assume @JochenHiller has your agreement) I will close it.

@sjka if we ever feel happy to convert the REST resources to OSGi services this is something that can perhaps solved on the go. No need (for me) to change anything.

**Comment by amitjoy** [comment]
As @JochenHiller has mentioned, we had a follow-up discussion in this regard and due to the argumentations that @JochenHiller mentioned, it would rather expose internal details inadvertently.
