### ISSUE TITLE
Add MeteoBlue weather service binding

### ISSUE THREAD

**Issue by 9037568** [eclipse/smarthome#4200]
This is something I've started working on.

This ticket is to serve as a placeholder if the ESH community would consider adopting it. If not, please close this ticket.

**Comment by triller-telekom** [comment]
@9037568 Just out of curiosity: Would you like to share the state of your binding with us? Maybe you can even create a WIP (work in progress) PR?

**Comment by 9037568** [comment]
I'd be happy to do that, but I haven't had as much time to work on this as I had hoped. Perhaps over the holidays I'll be able to get it into a shape that's good enough to present a first view WIP.

**Comment by 9037568** [comment]
I have the basic data retrieval working. Plan to commit a first version to my fork soon.

**Comment by lolodomo** [comment]
I would like to try the meteoblue binding with a free (non commercial) usage. I did not found a simple way to subscribe to the API, it looks like it is done through a mail !
I am not sure what to answer to the questions:

- `Historical or forecast data`: I suppose it is forecast ?
- `Desired data package(s) or weather variables`: I suppose it is weather variables ?
-  `Approximate number of daily request: (e.g. number of locations x number of daily updates)`: ok, it is easy, 1 in my case.

Then, I read in the auto generated mail: `We want to test the meteoblue API for 14 days for free.` Does it mean that it will stop working after 14 days ?

Maybe, all this should be explained in README.

**Comment by 9037568** [comment]
Hey, @lolodomo, not sure where you got all of those questions.

If you go to the link for ["Non-commercial use"](https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use) and click the big blue "Data package basic-day" button at the bottom of the page where it says "Get meteoblue non-commercial API service", you should get the email template that contains this text:

````
Dear meteoblue Team,

I want to get the free basic-day data package and hereby agree to the meteoblue terms and conditions. I also confirm, that the purpose of usage is non-commercial and that I implement the meteoblue logo with link to www.meteoblue.com if I use the data for a website or an app.

Non-commercial uses are all uses without direct profit purposes. More information and examples can be found here:
https://content.meteoblue.com/en/legal/commercial-non-commercial-use

Full name: (pre and surname)
Full address: (street or postbox, postal code, city, country)
Email address: (valid email address)
Website: (if available)
Detailed description of the purpose of API usage:
````

For "detailed description", you should just put that you want to use the weather data with your own personal home automation system.

**Comment by lolodomo** [comment]
Thank you a lot, I just did not see the "Non-commercial use" page !
