### ISSUE TITLE
build with enabled static code analyzer tool

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#4202]
Track "problems" of "Static Code Analyzer Tool" introduction.

**Comment by maggu2810** [comment]
HIPP seems to fail all the time now.

**Comment by maggu2810** [comment]
What is the estimated time for a full build?
I am currently running a build + deploy to a private repo and the job is still running (above 3 hours now).

It also seems to consume a lot of memory:

```
$ cat /proc/24563/status
Name:	java
Umask:	0022
State:	S (sleeping)
Tgid:	24563
Ngid:	0
Pid:	24563
PPid:	24415
TracerPid:	0
Uid:	1000	1000	1000	1000
Gid:	1000	1000	1000	1000
FDSize:	2048
Groups:	7 10 14 104 250 967 968 969 970 980 993 1000 
NStgid:	24563
NSpid:	24563
NSpgid:	24415
NSsid:	23405
VmPeak:	 6842044 kB
VmSize:	 6727840 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	 4155984 kB
VmRSS:	 4147612 kB
RssAnon:	 4132468 kB
RssFile:	   15144 kB
RssShmem:	       0 kB
VmData:	 4503984 kB
VmStk:	     136 kB
VmExe:	       4 kB
VmLib:	   17148 kB
VmPTE:	    9068 kB
VmPMD:	      36 kB
VmSwap:	   69236 kB
HugetlbPages:	       0 kB
Threads:	59
SigQ:	0/31074
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	2000000181005ccf
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	0
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	1
Mems_allowed_list:	0
voluntary_ctxt_switches:	29
nonvoluntary_ctxt_switches:	2
```

**Comment by kaikreuzer** [comment]
HIPP fails with
```
[INFO] o.h.m.e.h.MavenExecutionResultHandler - [1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0:checkstyle (default) on project org.eclipse.smarthome.core: Unable to execute mojo
[DEBUG] Closing connection to remote
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0:checkstyle (default) on project org.eclipse.smarthome.core: Unable to execute mojo: Execution null of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:checkstyle failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:2.17:checkstyle: java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V
```
@svilenvul Does this mean anything to you?

**Comment by maggu2810** [comment]
FYI:

```text
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:35 h
[INFO] Finished at: 2017-09-06T13:29:30+02:00
[INFO] Final Memory: 621M/2031M
[INFO] ------------------------------------------------------------------------
```

About the HIPP problem:
Hasen't there been a problem on openHAB some time that only occurs on the build system? I assume you can point me to the correct issue @kaikreuzer

**Comment by kaikreuzer** [comment]
Cannot find it myself right now... But it was about a SAX parser dependency, which by now has been removed in SAT, so this here is definitely something else.

**Comment by maggu2810** [comment]
What I have in mind has been this one: https://community.openhab.org/t/jenkins-build-problems/25977/37
Now we added a bunch of plugins (dependencies of the SAT one). I followed the artifactory plugin problem not in detail but could there be something related?

**Comment by kaikreuzer** [comment]
No, I doubt that this is related, because it was really just due to that specific Maven plugin that was used for deployment.

The weird thing is that travis just passes nicely with SAT as can be seen on all the latest PRs...

**Comment by maggu2810** [comment]
My system succeeded, too.
Does HIPP inject another plugin?
Need to check what has been the reason for the ZIP failures we solved some month ago.
Or perhaps the Maven version could be relevant?

**Comment by kaikreuzer** [comment]
It seems to be the maven-checkstyle-plugin, which still depends on Maven 2.1 stuff.
It might be worth a try to update to version 3.0.0 of that plugin: https://issues.apache.org/jira/browse/MCHECKSTYLE-335

**Comment by kaikreuzer** [comment]
... which isn't yet released :-(

**Comment by maggu2810** [comment]
Hm, HIPP and my machine is using the same Maven version (Apache Maven 3.3.9). So why does it make a difference?

**Comment by maggu2810** [comment]
We should who injects the different slf4j version and exclude the old ones (at least we could give it a try).
We should not mix different versions in the classpath at all.

urls[2] = file:/home/hudson/genie.smarthome/.hudson/jobs/SmartHomeDistribution-Nightly/workspace/.maven/repo/org/slf4j/slf4j-simple/**1.7.24**/slf4j-simple-1.7.24.jar
urls[98] = file:/home/hudson/genie.smarthome/.hudson/jobs/SmartHomeDistribution-Nightly/workspace/.maven/repo/org/slf4j/slf4j-jdk14/**1.5.6**/slf4j-jdk14-1.5.6.jar
urls[99] = file:/home/hudson/genie.smarthome/.hudson/jobs/SmartHomeDistribution-Nightly/workspace/.maven/repo/org/slf4j/jcl-over-slf4j/**1.5.6**/jcl-over-slf4j-1.5.6.jar

**Comment by maggu2810** [comment]
It seems the static code analyzer has dependencies to slf4j.

```text 
    <slf4j.api.version>1.7.24</slf4j.api.version>
    <slf4j.simple.version>1.7.24</slf4j.simple.version>
```

"... that the Mojo will have access to the standard Maven user-feedback mechanism, `org.apache.maven.plugin.logging.Log`, so the Mojo can communicate important events to the console or other log sink."

Shouldn't we drop the slf4j usage in the plugin and rely on the mojo logging mechanism?

**Comment by kaikreuzer** [comment]
Probably yes, so feel free to open an issue at https://github.com/openhab/static-code-analysis.

Shall we temporarily deactivate the plugin, so that we get the build green again?

**Comment by maggu2810** [comment]
> Shall we temporarily deactivate the plugin, so that we get the build green again?

I think so. Should be possible in the build configuration using `-DskipChecks`, if I understand the pom correctly. But you surely know.

**Comment by kaikreuzer** [comment]
Let's see: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/2163/console

**Comment by kaikreuzer** [comment]
Seems to work.

Off-topic question: What would you think about retiring our Hudson and request a modern Jenkins instance (https://wiki.eclipse.org/Jenkins) as a replacement?

**Comment by maggu2810** [comment]
> What would you think about retiring our Hudson and request a modern Jenkins instance 

I like it.
I followed the Eclipse bug and so one for a while but didn't ask you because we have all such a lot stuff to do. :wink:

**Comment by kaikreuzer** [comment]
> but didn't ask you because we have all such a lot stuff to do.

Right, but I am afraid that that won't change over the next years...

So here we go: https://bugs.eclipse.org/bugs/show_bug.cgi?id=521928

**Comment by maggu2810** [comment]
@svilenvul migrated the logging.
Do you consider to release a 3.1?

**Comment by kaikreuzer** [comment]
No, only a 0.3.1 ;-)
Yeah, I could schedule it for the next days (cannot promise to find the time tomorrow).

**Comment by kaikreuzer** [comment]
Seems a new release is not urgent anymore. Our new Jenkins succeeds with SAT enabled 👍

**Comment by kaikreuzer** [comment]
@svilenvul The [report looks a bit raw](https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/ws/target/summary_report.html) - do you why this is?

**Comment by svilenvul** [comment]
Jenkins requests a username and password and I can`t open it, but I think I know what you mean.

Yes, I should have warned you, the report as you know it before is now called `summary_bundles.html` (it wasn't really a summary report, it was just containing links to individual reports.)

The new one was an attempt to provide a different view - how often an issue occurs in the whole repository.

**Comment by kaikreuzer** [comment]
No, that's not what I meant. Here's how it looks like (and how the detailed bundle reports appear as well):

<img width="1370" alt="screen shot 2017-09-11 at 08 29 53" src="https://user-images.githubusercontent.com/3244965/30261180-976b2e24-96cb-11e7-9391-8b2abd8fe50a.png">

**Comment by svilenvul** [comment]
Let me guess than - the tool uses inline [CSS for visualization](https://github.com/openhab/static-code-analysis/blob/master/src/main/resources/report/create_html.xslt#L48) which may be suppressed by: https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy.

```The CSP header sent by Jenkins can be modified by setting the system property hudson.model.DirectoryBrowserSupport.CSP:```

**Comment by kaikreuzer** [comment]
Could be... I cannot change those settings myself. Could you maybe directly open an issue at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community (Component "Hudson") and request this change?

**Comment by svilenvul** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=522114

**Comment by kaikreuzer** [comment]
Nothing has happened on that issue so far, I just pinged the admins again...
