### ISSUE TITLE
New DB driver

### ISSUE THREAD

**Issue by briaeros** [eclipse/smarthome#4228]
As #3446 get closed with an answer which indicate exactly the opposite of what I was trying to said/ask/wish, I permit myself to open a new wishlist.

English isn't my native language , I must had trouble explain what I wanted, so  I will be much more concise and I hope it will be clearer.

Actually only two driver exists when a sensor send values.
- first change timestamp for a value (ie : each time a value is changed, the timestamp and the changed value is store. If the value is updated but not changed , then nothing happened).
- each timestamp for a value (ie : each time a value is updated, even if not changed, the timestamp and the value will be stored).

Will it be possible to have a driver storing the following information for a sensor
- first update timestamp for a value
- last update timestamp for a value.

For each update of the value (each time the sensor/item/things send us a value):
- if the value doesn't change (the same that the previous value), the timestamp of this update is stored in memory.
- If  the value change , then we write two line
  - the old value, and the timestamp of the last update at this value
  - the new value, and the current timestamp.

This is only storing whatever information that the sensor send, and avoiding storing redundant information.
There are no interpolation, no data modification, and absolutely nothing that could be delegate to any ui/frontend/application up in the layers

Only, storing simple, raw information that the sensor send, and avoiding storing too many unuseful value.

Other home automation store these informations (when changed and last update) (domoticz for example, if my memory serves me right)

Thanks.

**Comment by htreu** [comment]
> avoiding storing too many unuseful value

I dont think its "unuseful" value. Storing a value on every update is actually the best/detailed data you will get from a binding/device. I try to understand what your problem is with this approach.
Even storing only on state change (i.e. storing only when the value differs) will give you a proper result because you can be sure the value did not change until the timestamp with the new value is written. All you have to know when rendering the values is the frequency your device/binding sends updates.
In the end it boils down to a rendering issue. Your suggestion to store the last value/timestamp before a new value is stored is just a helper for the rendering.

**Comment by briaeros** [comment]
Hello,

> I dont think its "unuseful" value

storing redudant information is what I noted as "unuseful". As long as we know the first timestamp and the last timestamp at a specific value, we know(hope) that all others values are at this specific value.

> storing only on state change (i.e. storing only when the value differs) will give you a proper result [...]All you have to know when rendering the values is the frequency your device/binding sends updates.

Storing only on state change on db , and storing the "update rate"  "somwhere else" will require 
- a specific configuration for each things, store by another way, to replace information that the DB have already but decided to discard.
- will need to be updated when the things change (we can modify the configuration of the hardware/... without updating the thing configuration) (and anyone who manage more than an handful of nodes/server/whatever know that if theses tasks aren't automatized, one day or another , theses will be "out of sync").
- Will need to modify most existing frontend or application using the BD to manage this new configuration variable.
- Will not work with dynamic update rate things  (where things could be ask to to update at more regular interval with certains conditions (time,rate of change, external input, whatever)).

On the other hand, Adding a new BD driver, will add the capability to 
- not drop any information as store on change do
- is compatible with all the existing apps/frontend using eclipse smarthome
- automatically manage any updaterate change (whatever the reason), without any other configuration needed.
- store only information that are meant to be store.

>In the end it boils down to a rendering issue.
It's not "boils down a rendering issue".
I didn't ever talk about rendering. I only talk about storing information and which information store and which discard.

Please, please, please, don't modify my problem , or my question.
"out of the way update rate variable" It's no way as flexible and useful , ask for much more works on many other parts, and it's just not what I'm asking.

>Your suggestion to store the last value/timestamp before a new value is stored is just a helper for the rendering.

Nope. All I'm asking is that the DB driver doesn't drop the information it get, while being clever enough to not store redundant information.


I could totally understand you don't have time to implement this. All I asked is a little tips to where (file, class,...) so I could code this and propre a patch (by inspiring from the update on change).
I'm not really that  good in java, but I'm pretty sure I could modify the code which manage the "store on change" to make what I want, and then propose a patch.

**Comment by udo1toni** [comment]
To be honest, you will loose information, because you won't store the updates but only the last update. 

For example, my doorbell sends only ON but never OFF, so I get only updates, but every update is an event which should be stored.

So, when changing this behavior, it definitely has to be configurable.

**Comment by htreu** [comment]
@briaeros for you own persistence strategy you may have a look into the `org.eclipse.smarthome.core.persistence.strategy.SimpleStrategy` which defines the three global persistence strategies. On top there is the `org.eclipse.smarthome.core.persistence.strategy.SimpleCronStrategy` which defines a cron expression based persistence strategy.
The strategies are evaluated in the `org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl`which is registered as a `StateChangeListener`. The `handleStateEvent` method will then trigger a persistence service to store a specific item.

**Comment by kirantpatil** [comment]
@briaeros, what db (postgresql, H2SQL ...) does your db driver supports in ESH ? Are you also planning to add db support to ESH, since there is no db support in ESH at this moment https://github.com/eclipse/smarthome/pull/2081#issuecomment-304440897.

**Comment by kaikreuzer** [comment]
As this was a feature request, which has been clarified to not be the right approach (as this is what the strategies are for), I am closing this issue.
