### ISSUE TITLE
Maven build failing for any binding due to checkstyle code analysis

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4230]
If I run a "mvn clean install" at the root of the repo, everything is fine.

But if I run it inside "extensions/binding" or "extensions/binding/org.eclipse.smarthome.binding.sonos", I got this kind of error:
```
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0:checkstyle (default) on project org.eclipse.smarthome.binding.sonos: Unable to execute mojo: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: Unable to find suppressions file at location: D:\dev\openhab2\git\smarthome\extensions\binding\org.eclipse.smarthome.binding.sonos\tools\static-code-analysis\checkstyle\suppressions.xml: Could not find resource 'D:\dev\openhab2\git\smarthome\extensions\binding\org.eclipse.smarthome.binding.sonos\tools\static-code-analysis\checkstyle\suppressions.xml'.
```
I can confirm that I don't have any tools directory inside the binding structure; this directory seems to be present only at the root of the repo.

**Comment by J-N-K** [comment]
The same issue occurs in IDE. I didn't report it because I thought it was a local issue.

**Comment by maggu2810** [comment]
I have a fix in mind. Will create a PR next week.
