### ISSUE TITLE
Secrets vault service API

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#4235]
A service should be offered by ESH that keeps secrets.

## Requirements 

* The service would need to be unlocked with a user provided master password on start (via environment, cli argument, etc). 
* En/Decryption would take place with the master password hash, so that we don't need to keep the master password in memory.
* Getting/Setting secrets directly operates on a file, so that we don't keep plain secrets in memory for longer than necessary. Needs an internal lock to be thread safe.
* Only the component that has set a secret, can retrieve it again. (ManagedFactoryService that creates new instances per service that acquires SecretsVault).
* It is recommended to use `char[]` instead of `String` for secrets (https://stackoverflow.com/a/8889285)

## API
A proposed API could look like:

```java
public interface SecretsVault {
   @Nullable byte[] getSecret(@NonNull String key) throws IOException, GeneralSecurityException;
   void setSecret(@NonNull String key, @Nullable byte[] secret) throws IOException, GeneralSecurityException;
}

public interface Crypto {
   char[] encrypt(byte[] password, char[] plain) throws GeneralSecurityException;
   char[] decrypt(byte[] password, char[] cipher) throws GeneralSecurityException;

   byte[] encrypt(byte[] password, byte[] plain) throws GeneralSecurityException;
   byte[] decrypt(byte[] password, byte[] cipher) throws GeneralSecurityException;

   byte[] masterPasswordHash();
}
```

At some point the user might want to change the master password. This should be possible via rest/gui or via a second environment variable / cli argument, so that the old and new passwords are provided for an upcoming ESH start. All saved secrets should be migrated to the new password.

The interface could look like this:
```java
public interface SecretsVaultManagement {
   boolean migrateMasterPassword(String oldPassword, String newPassword);
}
```
## Example use-case
I have the issue in #4105 (SSL service) that I need to store passwords of the private key and keystore file. Those should not be plain text, as the file is readable by everyone. I would use the API like this:

```java
// Service start
String secret = secretsVault.getSecret("cryptPass");
if (secret==null) {
   secret = crypto.encrypt("cryptPass".toCharArray());
   secretsVault.setSecret("cryptPass", secret);
}
```

The obtained `secret` is then used to encrypt/decrypt private passwords before/after interacting with the configuration. The above approach still works if the 1) the secrets file gets removed, but the master password stays the same, 2) if the master password changes but the secrets file is still available.

**Comment by triller-telekom** [comment]
What about joining the ideas with PR #4169?

In there @paulianttila proposes a sevice for encypted configuration file values. Such a value could also be private keys, etc.

Since there already is some code to start with it would be cool if features that you need for #4105 would be integrated into #4169. In case that discussions around #4169 take longer we could also decide to store the private key as a plain text value for now and replace that in a follow-up pr once we have come to an agreement.

@davidgraeff: WDYT?
