### ISSUE TITLE
build fails in o.e.s.c.voice.test because of SAT

### ISSUE THREAD

**Issue by J-N-K** [eclipse/smarthome#4236]
Local build and Jenkins fails because SAT reports incompatible type comparion in voice tests in in InterpretCommandTestl.90

`assertThat(console.getPrintedText(), is(not(equals(INTERPRETED_TEXT))));`

To me this looks like a false positive, `console.getPrintedText()` returns a String, `INTERPRETED_TEXT` is a String.

**Comment by kaikreuzer** [comment]
See also https://github.com/eclipse/smarthome/pull/2860#issuecomment-328179573.
