### ISSUE TITLE
Target platform jetty problems

### ISSUE THREAD

**Issue by VelinYordanov** [eclipse/smarthome#4244]
I am working on migrating the FSInternetRadio tests to mockito and in order to do that I created a jetty server for the tests. I noticed that the smarthome target platform has 2 versions of some of the jetty packages - 9.3.14 and 9.4.5. When choosing the 9.3.14 version I am able to successfully execute the tests in eclipse but when running the tests in maven i get an error code 13.

Maven log: [1505133571133.txt](https://github.com/eclipse/smarthome/files/1292586/1505133571133.txt)

See #4243

**Comment by VelinYordanov** [comment]
@sjka @kaikreuzer Can you provide any assistance?

**Comment by maggu2810** [comment]
Can't we remove 9.4.5 from the target platform?

**Comment by kaikreuzer** [comment]
Where does it come from? I'd suspect it is implicitly included through the Eclipse SDK features, so it won't be too easy to exclude it. Before the Eclipse upgrade, we always had Jetty 8.1 as an additional version in the target platform...

**Comment by maggu2810** [comment]
Currently (I need to check again, because I already changed the target definition file) I see Jetty 9.4.5 stuff also in the jetty 9.3.14 repo.

Another question:
Why do we need the repo "http://download.eclipse.org/eclipse/updates/4.7" with "Eclipse SDK" and "PDE" in the target platform at all? Is it necessary for the Maven build?
I removed the repo (and so the two features) from the file and didn't realize any error in the Eclipse IDE (after a full rebuild). I am currently starting a maven build using an empty local maven repo.

**Comment by maggu2810** [comment]
@kaikreuzer Can you give this one [smarthome.target] a try?

Using the IDE to change part of the content of the target platform seems to rearrange XML elements so here the changes in separate commits: https://github.com/eclipse/smarthome/compare/master...maggu2810:tp?expand=1

Sort summary:
* remove repo "http://download.eclipse.org/eclipse/updates/4.7" with "Eclipse SDK" and "PDE" in the target platform
* add all currently available bundles and remove the 9.4.5 jetty ones (also remove duplicate entries)

IMHO the "used bundle" filter will allow us to remove all the unused plugins from time to time.
This should not add much work if we add new or update existing features, but will us allow to control what should be used and what should not be used.

[smarthome.target]: https://github.com/maggu2810/smarthome/blob/tp/targetplatform/smarthome.target

**Comment by sjka** [comment]
> Currently (I need to check again, because I already changed the target definition file) I see Jetty 9.4.5 stuff also in the jetty 9.3.14 repo.

I can confirm this. However, the 9.4.5.x bundles neither seem to exist at this location nor they are mentioned in the content.xml/artifacts.xml. I _must_ have missed something, but this looks weird!

**Comment by sjka** [comment]
> Why do we need the repo "http://download.eclipse.org/eclipse/updates/4.7" with "Eclipse SDK" and "PDE" in the target platform at all?

For the designer, I guess

**Comment by kaikreuzer** [comment]
> For the designer, I guess

Sounds like a good reason for it. So as long as we have the launch config for the designer in the IDE, we should not remove those. But if we soon succeed to have a replacement and fully deprecate the designer, we can indeed hugely clean our target platform.

**Comment by maggu2810** [comment]
> * add all currently available bundles and remove the 9.4.5 jetty ones (also remove duplicate entries)

> IMHO the "used bundle" filter will allow us to remove all the unused plugins from time to time.
This should not add much work if we add new or update existing features, but will us allow to control what should be used and what should not be used.

I could leave `repo "http://download.eclipse.org/eclipse/updates/4.7" with "Eclipse SDK" and "PDE"` in place, but WDYT about explicitly naming the bundles that should be present in the TP?
We could start with removing unwanted Jetty version and reduce the big number of bundles from time to time.

**Comment by kaikreuzer** [comment]
> WDYT about explicitly naming the bundles that should be present in the TP?

It makes the maintenance of the target file imho much harder; in general I am for it, but I would prefer to wait with that step until we have deprecated the designer, so that the list of repos to handle that way is much shorter.

**Comment by VelinYordanov** [comment]
Thanks for the assistance. I managed to fix my problem by using filters for the version i needed in the pom.xml. If there will be no further discussion you can close the issue.
