### ISSUE TITLE
[Tradfri] Support for new RGB bulbs

### ISSUE THREAD

**Issue by hreichert** [eclipse/smarthome#4251]
IKEA sells new Tradfri products.

RGB bulbs, E27 socket, 600 lm, 8.6 W
packaged with 1 remote control
Product number: 703.389.51

I think they will be announced in October 2017.
The official IKEA Tradfri app does not support them fully right now. Currently it's only possible to change the color temperature (from white to orange), but you can not select a color yet. If you change the color through the remote control (RGB), the app shows the correct color.

**What about support for this RGB bulbs in the Eclipse Smarthome Tradfri Binding?**
I'm willing to implement the RGB support and contribute it, but I got only limited time resources right now... So I want to coordinate first, if somebody else is already implementing this. 

Here are some pictures:

![tradfri_rgb_1](https://user-images.githubusercontent.com/21249127/30291873-7ac52fea-9734-11e7-94f0-e87fb538ea2f.jpg)
![tradfri_rgb_2](https://user-images.githubusercontent.com/21249127/30291872-7ac4e83c-9734-11e7-8900-c8593a7c8acb.jpg)
![tradfri_rgb_3](https://user-images.githubusercontent.com/21249127/30291875-7acc5608-9734-11e7-9a6e-7b5e371eba7e.jpg)
![tradfri_rgb_4](https://user-images.githubusercontent.com/21249127/30291874-7aca0240-9734-11e7-950c-dac8943d236b.jpg)

**Comment by normalfag** [comment]
ja, genau!

**Comment by sjka** [comment]
> What about support for this RGB bulbs in the Eclipse Smarthome Tradfri Binding?

Yes, sure! The only limiting factor so far was their non-availability - nobody mentioned here yet that he/she was working on it. So it's good that you created this issue for coordination! 

Looking forward to your contribution!

**Comment by hreichert** [comment]
CoAP response for RGB bulb:
```
{  
  "9001":"TRADFRI bulb E27 CWS opal 600lm",
  "9002":1505151864,
  "9020":1505253777,
  "9003":65550,
  "5750":2,
  "9054":0,
  "9019":1,
  "3":{  
    "0":"IKEA of Sweden",
    "1":"TRADFRI bulb E27 CWS opal 600lm",
    "2":"",
    "3":"1.3.002",
    "6":1
  },
  "3311":[  
    {  
      "5707":0,
      "5850":1,
      "9003":0,
      "5710":6554,
      "5851":8,
      "5708":0,
      "5709":13107,
      "5711":0,
      "5706":"6c83ba"
    }
  ]
}
```
* Firmware version _1.3.002_ (RGB) is newer than currently available _1.2.217_ (Dimmable/Colortemperature bulb)
* Attribute _5706_ (COLOR) represents the correct hex value _6c83ba_ of the current bulb color

**Comment by hreichert** [comment]
@kaikreuzer Is it OK that I change the `getColorTemperature()` calculation within this issue? I want to implement a fallback if the current calculation fails due to full-color XY-values. So this is related to "Support for new RGB bulbs", I think?

**Comment by hreichert** [comment]
The new full color lights are ZLL ID 0x0200, so I name the new ThingType 200, correspondending to the existing thing types 100 and 220.

**Comment by kaikreuzer** [comment]
> The new full color lights are ZLL ID 0x0200 (Color Light), NOT 0x0210 as I initially thought.

This is interesting. According to the [specification](https://www.nxp.com/docs/en/user-guide/JN-UG-3091.pdf) (page 27), the "Extended Colour Light" is about "colour temperature, in
addition to the colour parameters supported by the Colour Light device".
So just to clarify this discrepancy: Is it that the bulbs actually do not allow setting the color temperature directly (through a specific Zigbee cluster), but that your implementation rather calculates an appropriate color value for a certain temperature through software?

**Comment by hreichert** [comment]
Correct. The color temperature calculation is the same as for the existing "dimmable color temperature" bulbs: Coordinates from x/y space. I don't know how the IKEA gateway handles this in detail for the different lamp types, but the interface to the bulbs is exactly the same for color temperature lamps and color lamps.

Regarding Zigbee ZLL: I hooked up all lamp types to a Zigbee adapter with the deCONZ software and confirmed the device IDs. The new full color bulbs are type 0x0200 and only support x/y color setting in the "Colour" cluster; not the setting of hue and saturation.
