### ISSUE TITLE
[Paper UI] Control page items stop being updated

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#4255]
After navigating away from the Control page and returning back to it the items in it no longer update. According to the browser debug console the updates are received via SSE.

This is how I reproduce it:
1. Install latest OH 2.2.0-SNAPSHOT (I've tested with build # 1036 and Chrome 61.0.3163.79 (Official Build) (64-bit))
2. Set "Item Linking" (Configuration > System) to "Simple Mode" and click "Save"
3. Install a binding, let it automatically discover Things and add these via "Inbox"
4. Open the "Control" page that is now populated with several Things and items that have state
5. Interact with some of the Things so there are item state changes
6. Check if the state is correctly updated
7. When it does, navigate away to another page (e.g. "Addons") and navigate back to the "Control" page
8. Repeat step 5 and 6 and now typically the state is no longer automatically updated even though the events are received by the browser via SSE

The updates again resume after a browser reload.

I've seen this issue with several bindings, e.g. while testing with the LIFX, Plugwise and the new Nest Binding. Restarting the runtime also does not fix this.

**Comment by htreu** [comment]
thanks for the report @wborn. I will take a look.
