### ISSUE TITLE
Error for PaperUI

### ISSUE THREAD

**Issue by HeyChangSha** [eclipse/smarthome#4261]
when i change the runtime plug-in choice the org.eclipse.smarthome.ui.paper and org.openhab.ui.paperui in workspace (not target platform) there is an error : ProxyServlet: /paperui/index.html 
anybody who has fix this problem? please help me

**Comment by kaikreuzer** [comment]
Check https://www.eclipse.org/smarthome/documentation/development/notes.html#paperui-development-jshtml for details on how to do development on the Paper UI within the workspace.
