### ISSUE TITLE
[Paper UI] Unable to update a Thing when its type has no configuration description

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#4265]
When a Thing Type does not have a `<config-description>` XML block, you can not update any Things of this type in Paper UI. An example of this are the Nest Binding [Thing types](https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.nest/ESH-INF/thing) (except for the type defined in bridge.xml).

Because of this it is not possible to update following Thing properties for such Thing Types:
* Name
* Location
* Bridge

Reproduction scenario:
1. Open Paper UI
2. Add Nest Binding and add a Nest Account
3. Let it detect Nest devices and add these via "Inbox"
4. Now open "Configuration -> Things"
5. Click on a Thing (e.g. a Cam, Protect or Thermostat) to open its details
6. Click the edit configuration button on top of the screen
7. Update the "Name" and "Location"
8. Now when you click the "Checkmark" on top of the screen nothing happens and the changes are not applied.

When you monitor the network traffic via the browser debug console in step 7, it shows a 404 not found occurs for a request to `/rest/config-descriptions`.

When I recompile the code and give these thing types a `<config-description>` XML block it is possible to update these Things.

**Comment by kaikreuzer** [comment]
Err, how is this at all possible? (I know, I merged that binding, so I should have asked that earlier already...)

How can a handler identify a certain thing if there isn't a single config parameter? This sounds like an invalid case to me.

**Comment by wborn** [comment]
In the code that got merged the only Thing you can add manually is the Nest Bridge. The other Things have `listed="false"`.

It then uses discovery to add the other Things (with a REST call to the Nest API) to the Inbox. The Nest Things have a property that stores the Nest device ID which is a 50+ character long computer generated string. Normally you could only retrieve this ID by making your own REST calls.

When the Thing handlers receive Commands they again retrieve the Nest device ID from the properties and use it in their REST calls to Nest.

**Comment by kaikreuzer** [comment]
Thanks, so this is indeed the flaw.
I should remember not to merge any binding that is [lacking the Full Example in the README...](https://github.com/openhab/openhab2-addons/pull/1880#discussion_r134551125).

The device ID has to be a config parameter, it must not be a property. The discovery would set it and if there is someone wanting to configure it textually, he would be able to do so, if he gets hold of the id (e.g. through a manual REST call).

May I ask you to do that refactoring as part of your https://github.com/openhab/openhab2-addons/pull/2698?

**Comment by kaikreuzer** [comment]
Argh, again I am mixing up things - @martinvw is the author of openhab/openhab2-addons#2698, so I probably rather have to ask him for that change...

**Comment by wborn** [comment]
> May I ask you to do that refactoring as part of your openhab/openhab2-addons#2698?

I'll fix it in that PR. We're collaborating together. :-) This change will also allow people to define the Things in files which would otherwise not be possible.

**Comment by wborn** [comment]
It would be better to prevent these kinds of errors by letting ESH validate that there is a config-description block for each thing type. If things types without these blocks still allowed the UI should be able to handle these and this issue/PR still makes sense.

**Comment by htreu** [comment]
Technically the XSD does allow the absence of the `<config-description>` element:

```
<xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
```

>How can a handler identify a certain thing if there isn't a single config parameter?

Isn´t there always one handler for one thing? Using the magic-bundle and creating multiple things from one thing-type (which is missing config-parameters, too) does indeed work.

**Comment by kaikreuzer** [comment]
> Isn´t there always one handler for one thing? 

Yes, of course. But I am talking about the real device: The handler needs a configuration to know how to access the device and hence it needs at least one parameter. So two things of the same type need to differ in their configuration.

**Comment by kaikreuzer** [comment]
> If things types without these blocks are still allowed the UI should be able to handle these and this issue/PR still make sense.

Config descriptions are regarded as optional meta-data for describing the (mandatory) configuration - so technically, I would not change the XSD, but you are right that in practice the thing types should almost in all cases also come with a config description.
