### ISSUE TITLE
[Rest] DELETE /rest/things/*/channels/*/link

### ISSUE THREAD

**Issue by martinvw** [eclipse/smarthome#4273]
As reported in https://github.com/openhab/openhab-core/issues/209 the rest api offers an endpoint `DELETE /rest/things/*/channels/*/link` which does not really function also it seems to be duplicate compared to `DELETE /rest/links/*/*` and the implementations differ.

Maybe they (there is also an add endpoint) should be removed otherwise there some issues which I quickly spotted:

* Wrong annotation for itemName, that is why it's not shown in Swagger, also its not validated in anyway before passing it to the internal method, so I see no way it could properly report if the link is not found or something
* Missing else if the link does not exist, so you would at least have some feedback, imho that could/should also be a 404
* The implementation does not match the one in https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/link/ItemChannelLinkResource.java#L101 but accepts the same parameters, can / should they share some code, should they contain the same code or as suggested should this one be removed?

Regards

**Comment by sjka** [comment]
Look like yet another remaining of the ThingSetupManager (#1726, R.I.P.)

It's broken so it's safe to assume that no UI currently can be using it. Therefore I also tend to drop it rather than fixing it.
