### ISSUE TITLE
Wemo Light Handler: remove subscription

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#4282]
@hmerk Hi, I have a question about the current `removeSubscription` implementation.

```Java
    private synchronized void removeSubscription() {
        logger.debug("Removing WeMo GENA subscription for '{}'", this);
        if (service.isRegistered(this)) {
            String subscription = null;

            if ((subscriptionState.get(subscription) != null) && subscriptionState.get(subscription).booleanValue()) {
                logger.debug("WeMo {}: Unsubscribing from service {}...", getUDN(), subscription);
                service.removeSubscription(this, "bridge1");
            }

            subscriptionState = new HashMap<String, Boolean>();
            service.unregisterParticipant(this);

        }
    }
```

You set `subscription` to `null` and use this as a key for the `subscriptionState` map.
A key of a map is IMHO non null by default, so what do you want to check here?
What am I missing here?

**Comment by maggu2810** [comment]
The [Map interface][Map#get(Object)] itself does not forbid null keys.

Also the HashMap itself explicitly allows null keys.

```
This implementation provides all of the optional map operations, and permits null values and the null key. 
```

So, if this is what you want to do, all is fine.

[Map#get(Object)]: https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#get-java.lang.Object-

**Comment by maggu2810** [comment]
In `onSubscription` you use `String subscription = "bridge1";` shouldn't be used the same in `removeSubscription`?

**Comment by hmerk** [comment]
Hmm, seems you are wright, i will check....
