### ISSUE TITLE
Chart: add parameter in url to change font size

### ISSUE THREAD

**Issue by mueller-ma** [eclipse/smarthome#4284]
Especially on high-res smartphones the text is too small.
I tried to reduce the resolution of the chart to increase the font size, but than it will be a little bit pixelated.

Something like "http://openhab/chart?items=foo&fontsize=10px" would help a lot

**Comment by hreichert** [comment]
I'm currently working on some enhancements to the ESH DefaultChartProvider (support for themes / different looks). 
See issue #4288 

Maybe we can discuss the use of a new parameter "fontscale".
