### ISSUE TITLE
Circular dependency: ThingConfigDescriptionProvider & ConfigDescriptionRegistry

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#4300]
No idea why we haven't seen this before, but just ran into this one:

```
Circular reference detected trying to get service {org.eclipse.smarthome.config.core.ConfigDescriptionRegistry}={service.id=127, service.bundleid=86, service.scope=bundle, component.name=ConfigDescriptionRegistry, component.id=119}
 stack of references: ServiceReference: {org.eclipse.smarthome.config.core.ConfigDescriptionRegistry}={service.id=127, service.bundleid=86, service.scope=bundle, component.name=ConfigDescriptionRegistry, component.id=119}
ServiceReference: {org.eclipse.smarthome.config.core.ConfigDescriptionProvider}={service.id=128, service.bundleid=78, service.scope=bundle, component.name=org.eclipse.smarthome.core.thing.internal.ThingConfigDescriptionProvider, component.id=108}
```

Looks like SCR is right :-(

**Comment by armintan** [comment]
Is there any update? I just ran into the same issue.

!ENTRY org.apache.felix.scr 4 0 2018-01-27 19:26:10.349
!MESSAGE Circular reference detected trying to get service {org.eclipse.smarthome.config.core.ConfigDescriptionRegistry}={service.id=154, service.bundleid=120, service.scope=bundle, component.name=ConfigDescriptionRegistry, component.id=139}
 stack of references: ServiceReference: {org.eclipse.smarthome.config.core.ConfigDescriptionRegistry}={service.id=154, service.bundleid=120, service.scope=bundle, component.name=ConfigDescriptionRegistry, component.id=139}
ServiceReference: {org.eclipse.smarthome.config.core.ConfigDescriptionProvider}={service.id=155, service.bundleid=31, service.scope=bundle, component.name=org.eclipse.smarthome.core.thing.internal.ThingConfigDescriptionProvider, component.id=83}

!STACK 0
java.lang.Exception: stack trace
