### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by RaspberryIoT** [eclipse/smarthome#4305]
Hello,

I am new to java and programming in general. 

I am trying to follow the installation guide provided on the official website and I now face a roadblock. I also posted this on Eclipse SmartHome Forums:

[https://www.eclipse.org/forums/index.php/t/1088847/](url) 

I followed the installation instructions provided in the following link:

http://www.eclipse.org/smarthome/documentation/development/ide.html

to install the Eclipse SmartHome on a Windows 10 PC. I was able to follow the guide up till step 9. The guide says step 9 should clear all the errors in the project but unfortunately I still have many errors, to be precise the compiler counts them to be 461. 
I think I'm doing something wrong but I cannot figure out what that is since I am following every step as is and since I cannot figure out I tried reinstalling it a few times which did not help so I tried on another PC which had a fresh install of windows 10 and I got the same results. 

Since this method was failing compilation I tried following the one on GitHub repository using command line:

https://github.com/eclipse/smarthome

Under step 3, Building with Maven after running the command "mvn clean install" after the end of compilation the command line too gave me errors. So I tried running the next command mentioned there "mvn -DskipTests=true clean install" which still gives me errors.

I thought its worth mentioning that I have a few types of recurring errors.

Type one: 

Description: Project 'org.eclipse.smarthome.model.item.ide' is missing required source folder: 'src-gen'	
Resource: org.eclipse.smarthome.model.item.ide	
Path:
Location	: Build path
Type: Build Path Problem

Type two:

Description: Package 'org.eclipse.smarthome.model.ide.contentassist.antlr.internal' does not exist in this plug-in
Resource: MANIFEST.MF
Path: /org.eclipse.smarthome.model.item.ide/META-INF
Type: Plug-in Problem

and different types of Java problems which I believe are because the project is not able to find proper libraries and dependencies.

Any idea what I am doing wrong?

Any help much appreciated, Thank you.

**Comment by maggu2810** [comment]
Hi @RaspberryIoT,

> I also posted this on Eclipse SmartHome Forums:
> https://www.eclipse.org/forums/index.php/t/1088847/

I haven't read the forum thread yet, but why do we need an additional issue?

Just an idea: Do your installation path contain any whitespace or other non-alphanumeric characters?

**Comment by RaspberryIoT** [comment]
"Do your installation path contain any whitespace or other non-alphanumeric characters?"
No, there are no white-spaces.

"I haven't read the forum thread yet, but why do we need an additional issue?"
I'm sorry I'm new to GitHub as well, I thought this was an issue :/?

I know I'm doing something wrong on my part. I tried multiple installions on two windows 10 pcs and one Ubuntu, same result. I cannot figure out since I am following every step instructed.

Thank you for your time.

**Comment by hreichert** [comment]
@RaspberryIoT 
> Under step 3, Building with Maven after running the command "mvn clean install" after the end of compilation the command line too gave me errors. So I tried running the next command mentioned there "mvn -DskipTests=true clean install" which still gives me errors.

What errors do you get after `mvn -DskipTests=true clean install`?

**Comment by Jianfeili** [comment]
I have seen the same issues that @RaspberryIoT has reported on window 10 in Eclipse after following with the instructions http://www.eclipse.org/smarthome/documentation/development/ide.html faithfully. There are errors in many eclipse projects and I have tried fresh installation a few times in last two days.  Some of the issues like missing "'src-gen" and "xtend-gen" folder in 6 or 7 projects, I created those directories manually, but I am still unable to get the eclipse error free.

**Comment by Jianfeili** [comment]
Hi

Here is the summary report from  "mvn -DskipTests=true clean install" 

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Eclipse SmartHome .................................. SUCCESS [  0.675 s]
[INFO] Eclipse SmartHome Bundles .......................... SUCCESS [  0.235 s]
[INFO] Eclipse SmartHome Test Components .................. SUCCESS [  0.086 s]
[INFO] Eclipse SmartHome Core Components .................. SUCCESS [  0.084 s]
[INFO] Eclipse SmartHome Core ............................. SUCCESS [ 50.325 s]
[INFO] Eclipse SmartHome Configurations ................... SUCCESS [  0.082 s]
[INFO] Eclipse SmartHome Configuration Core ............... SUCCESS [ 20.362 s]
[INFO] Eclipse SmartHome Configuration XML ................ SUCCESS [ 13.791 s]
[INFO] Eclipse SmartHome AutoUpdate Binding ............... SUCCESS [  8.249 s]
[INFO] Eclipse SmartHome Test ............................. SUCCESS [ 13.758 s]
[INFO] Eclipse SmartHome I/O Components ................... SUCCESS [  0.076 s]
[INFO] Eclipse SmartHome Console .......................... SUCCESS [  9.655 s]
[INFO] Eclipse SmartHome Thing ............................ SUCCESS [ 25.744 s]
[INFO] Magic Bundle ....................................... SUCCESS [  9.998 s]
[INFO] Magic Bundle Tests ................................. SUCCESS [  8.091 s]
[INFO] Eclipse SmartHome Auth Components .................. SUCCESS [  0.062 s]
[INFO] Eclipse SmartHome JAAS Authentication .............. SUCCESS [  6.470 s]
[INFO] Eclipse SmartHome Configuration Dispatcher ......... SUCCESS [  9.058 s]
[INFO] Eclipse SmartHome Configuration Dispatcher Tests ... SUCCESS [ 12.918 s]
[INFO] Eclipse SmartHome Configuration Core Tests ......... SUCCESS [ 15.491 s]
[INFO] Eclipse SmartHome Configuration Discovery .......... SUCCESS [ 15.162 s]
[INFO] Eclipse SmartHome Core Thing XML ................... SUCCESS [ 13.386 s]
[INFO] Eclipse SmartHome Configuration Discovery Tests .... SUCCESS [ 20.967 s]
[INFO] Eclipse SmartHome Config XML Tests ................. SUCCESS [ 13.185 s]
[INFO] Eclipse SmartHome Core Audio ....................... SUCCESS [ 12.413 s]
[INFO] Eclipse SmartHome Core Binding XML ................. SUCCESS [  9.799 s]
[INFO] Eclipse Smarthome Audio Test ....................... SUCCESS [ 14.458 s]
[INFO] Eclipse SmartHome Sample Extension Service ......... SUCCESS [  8.219 s]
[INFO] Eclipse SmartHome REST Interface ................... SUCCESS [ 12.216 s]
[INFO] Eclipse SmartHome Core ID .......................... SUCCESS [  7.486 s]
[INFO] Eclipse SmartHome ID Tests ......................... SUCCESS [  7.543 s]
[INFO] Eclipse SmartHome Core Tests ....................... SUCCESS [ 23.262 s]
[INFO] Eclipse SmartHome Thing Tests ...................... SUCCESS [ 36.961 s]
[INFO] Eclipse SmartHome Core Persistence ................. SUCCESS [ 10.593 s]
[INFO] Eclipse SmartHome Core Scheduler Service ........... SUCCESS [  6.452 s]
[INFO] Eclipse SmartHome Core Transformation Service ...... SUCCESS [  8.686 s]
[INFO] Eclipse SmartHome Core Binding XML Tests ........... SUCCESS [ 10.324 s]
[INFO] Eclipse SmartHome Core Thing XML Tests ............. SUCCESS [ 12.008 s]
[INFO] Eclipse SmartHome Core Voice ....................... SUCCESS [ 14.074 s]
[INFO] Eclipse SmartHome Core Voice Test .................. SUCCESS [ 11.550 s]
[INFO] Eclipse SmartHome Automation ....................... SUCCESS [  0.091 s]
[INFO] Eclipse SmartHome Automation API ................... SUCCESS [ 13.127 s]
[INFO] Eclipse SmartHome Automation Commands .............. SUCCESS [ 13.122 s]
[INFO] Eclipse SmartHome Automation Parser GSON ........... SUCCESS [  8.920 s]
[INFO] Eclipse SmartHome Automation Providers ............. SUCCESS [ 12.898 s]
[INFO] Eclipse SmartHome Automation Provider File ......... SUCCESS [ 10.727 s]
[INFO] Eclipse SmartHome Automation Core .................. SUCCESS [ 17.057 s]
[INFO] Eclipse SmartHome Automation Core Tests ............ SUCCESS [ 11.498 s]
[INFO] Eclipse SmartHome Automation Sample JSON ........... SUCCESS [  9.264 s]
[INFO] Eclipse SmartHome Automation Core Modules .......... SUCCESS [ 12.064 s]
[INFO] Eclipse SmartHome Automation Core Module Tests ..... SUCCESS [ 11.844 s]
[INFO] Eclipse SmartHome Automation Script Modules ........ SUCCESS [ 11.167 s]
[INFO] Eclipse SmartHome Automation Media Modules ......... SUCCESS [ 13.043 s]
[INFO] Eclipse SmartHome Automation Timer Modules ......... SUCCESS [ 11.233 s]
[INFO] Eclipse SmartHome Automation Module Timer Tests .... SUCCESS [ 11.266 s]
[INFO] Eclipse SmartHome Models ........................... SUCCESS [01:13 min]
[INFO] Eclipse SmartHome Model Core ....................... SUCCESS [ 15.130 s]
[INFO] Eclipse SmartHome Model Lazy Generation ............ SUCCESS [ 11.364 s]
[INFO] Eclipse SmartHome Model Items ...................... SUCCESS [01:20 min]
[INFO] Eclipse SmartHome Model Persistence ................ SUCCESS [ 52.471 s]
[INFO] Eclipse SmartHome Automation Script Default Scope .. SUCCESS [ 23.402 s]
[INFO] Eclipse SmartHome Automation Script RuleSupport .... SUCCESS [ 12.677 s]
[INFO] Eclipse SmartHome Automation Script Module Tests ... SUCCESS [ 11.000 s]
[INFO] Eclipse SmartHome Automation Event Tests ........... SUCCESS [ 12.239 s]
[INFO] Eclipse SmartHome Automation Integration Tests ..... SUCCESS [ 21.642 s]
[INFO] Eclipse SmartHome Automation Sample Extension Java . SUCCESS [ 12.495 s]
[INFO] Eclipse SmartHome Automation REST API .............. SUCCESS [  9.531 s]
[INFO] Eclipse SmartHome Automation Sample REST API ....... SUCCESS [  7.333 s]
[INFO] Eclipse SmartHome Automation Java Demo ............. SUCCESS [  6.652 s]
[INFO] Eclipse SmartHome Automation Json Demo ............. SUCCESS [  1.703 s]
[INFO] Eclipse SmartHome Automation Module Type Demo ...... SUCCESS [  9.840 s]
[INFO] Eclipse SmartHome Designer Bundles ................. SUCCESS [  0.079 s]
[INFO] Eclipse SmartHome Network I/O ...................... SUCCESS [ 10.502 s]
[INFO] Eclipse SmartHome Model Script ..................... SUCCESS [01:14 min]
[INFO] Eclipse SmartHome Designer Core Plugin ............. SUCCESS [ 14.273 s]
[INFO] Eclipse SmartHome Designer UI Plugin ............... SUCCESS [ 14.570 s]
[INFO] Eclipse SmartHome Console for OSGi framework Eclipse Equinox SUCCESS [  7.495 s]
[INFO] Eclipse SmartHome Console for OSGi Console RFC 147 . SUCCESS [  8.080 s]
[INFO] Eclipse SmartHome Console for OSGi runtime Karaf ... SUCCESS [  8.685 s]
[INFO] Eclipse SmartHome Monitor .......................... SUCCESS [  7.396 s]
[INFO] Eclipse SmartHome Network I/O Tests ................ SUCCESS [  7.305 s]
[INFO] Eclipse SmartHome IO REST Tests .................... SUCCESS [ 12.133 s]
[INFO] Eclipse SmartHome Authentication Support for the REST Interface SUCCESS [  7.178 s]
[INFO] Eclipse SmartHome Basic Auth for the REST Interface  SUCCESS [  7.211 s]
[INFO] Eclipse SmartHome Core REST Interface .............. SUCCESS [ 16.732 s]
[INFO] Eclipse SmartHome IO REST Core Tests ............... SUCCESS [ 11.465 s]
[INFO] Eclipse SmartHome mDNS Service ..................... SUCCESS [ 10.007 s]
[INFO] Eclipse SmartHome REST mDNS Announcer .............. SUCCESS [  8.015 s]
[INFO] Eclipse SmartHome REST JAX-RS Optimizations ........ SUCCESS [  7.891 s]
[INFO] Eclipse SmartHome SSE Interface .................... SUCCESS [ 10.853 s]
[INFO] Eclipse SmartHome IO SSE Tests ..................... SUCCESS [ 10.236 s]
[INFO] Eclipse SmartHome Model Sitemap .................... SUCCESS [01:25 min]
[INFO] Eclipse SmartHome UIs .............................. SUCCESS [  0.125 s]
[INFO] Eclipse SmartHome UI ............................... SUCCESS [ 17.056 s]
[INFO] Eclipse SmartHome Sitemap REST Interface ........... SUCCESS [ 12.253 s]
[INFO] Eclipse SmartHome Core REST UI Logging Module ...... SUCCESS [  7.720 s]
[INFO] Eclipse SmartHome Voice REST Interface ............. SUCCESS [  7.405 s]
[INFO] Eclipse SmartHome DBus Transport ................... SUCCESS [  1.882 s]
[INFO] Eclipse SmartHome MQTT Transport ................... SUCCESS [ 11.757 s]
[INFO] Eclipse SmartHome Mqtt Transport I/O Tests ......... SUCCESS [  9.294 s]
[INFO] Eclipse SmartHome UPnP Transport ................... SUCCESS [  9.720 s]
[INFO] Eclipse SmartHome IO UPnP Tests .................... SUCCESS [ 11.146 s]
[INFO] Eclipse SmartHome Model Core Tests ................. SUCCESS [ 12.204 s]
[INFO] Eclipse SmartHome Model Item IDE ................... SUCCESS [ 20.570 s]
[INFO] Eclipse SmartHome Model Items Runtime .............. SUCCESS [  7.538 s]
[INFO] Eclipse SmartHome Model Item UI .................... SUCCESS [ 23.521 s]
[INFO] Eclipse SmartHome Items Model Tests ................ SUCCESS [ 13.735 s]
[INFO] Eclipse SmartHome Model Persistence IDE ............ SUCCESS [ 20.655 s]
[INFO] Eclipse SmartHome Model Rules ...................... SUCCESS [01:28 min]
[INFO] Eclipse SmartHome Model Rule IDE ................... SUCCESS [ 37.420 s]
[INFO] Eclipse SmartHome Model Script IDE ................. SUCCESS [ 33.644 s]
[INFO] Eclipse SmartHome Model Sitemap IDE ................ SUCCESS [ 37.245 s]
[INFO] Eclipse SmartHome Thing Model ...................... SUCCESS [ 42.862 s]
[INFO] Eclipse SmartHome Model Thing IDE .................. SUCCESS [ 21.202 s]
[INFO] Eclipse SmartHome Language Server .................. SUCCESS [ 10.349 s]
[INFO] Eclipse SmartHome Model Persistence Runtime ........ SUCCESS [ 10.605 s]
[INFO] Eclipse SmartHome Model Persistence UI ............. SUCCESS [ 21.428 s]
[INFO] Eclipse SmartHome Model Persistence Tests .......... SUCCESS [ 11.958 s]
[INFO] Eclipse SmartHome Model Rules Runtime .............. SUCCESS [ 15.134 s]
[INFO] Eclipse SmartHome Model Script UI .................. SUCCESS [ 27.741 s]
[INFO] Eclipse SmartHome Model Rules UI ................... SUCCESS [ 29.535 s]
[INFO] Eclipse SmartHome Model Rules Tests ................ SUCCESS [  2.156 s]
[INFO] Eclipse SmartHome Model Script Runtime ............. SUCCESS [  9.711 s]
[INFO] Eclipse SmartHome Model Script Tests ............... SUCCESS [ 11.261 s]
[INFO] Eclipse SmartHome Model Sitemap Runtime ............ SUCCESS [  8.045 s]
[INFO] Eclipse SmartHome Model Sitemap UI Plugin .......... SUCCESS [ 25.514 s]
[INFO] Eclipse SmartHome Thing Model Runtime .............. SUCCESS [  8.589 s]
[INFO] Eclipse SmartHome Thing Model UI ................... SUCCESS [ 22.588 s]
[INFO] Eclipse SmartHome Thing Model Tests ................ SUCCESS [ 24.669 s]
[INFO] Eclipse SmartHome UI Tests ......................... SUCCESS [ 11.820 s]
[INFO] Eclipse SmartHome UI Icon Support .................. SUCCESS [ 11.656 s]
[INFO] Eclipse SmartHome UI Icon Tests .................... SUCCESS [ 12.530 s]
[INFO] Eclipse SmartHome Storages ......................... SUCCESS [  0.079 s]
[INFO] Eclipse SmartHome JSON Storage ..................... SUCCESS [ 11.995 s]
[INFO] Eclipse SmartHome Storage JSON Tests ............... SUCCESS [ 11.845 s]
[INFO] Eclipse SmartHome MapDB Storage .................... SUCCESS [ 11.240 s]
[INFO] Eclipse SmartHome Storage MapDB Tests .............. SUCCESS [ 11.494 s]
[INFO] Eclipse SmartHome Extensions ....................... SUCCESS [  0.078 s]
[INFO] Eclipse SmartHome Bindings ......................... SUCCESS [  0.078 s]
[INFO] Eclipse SmartHome Astro Binding .................... SUCCESS [ 21.193 s]
[INFO] Eclipse SmartHome Astro Binding Tests .............. SUCCESS [ 15.911 s]
[INFO] Eclipse SmartHome DigitalSTROM Binding ............. SUCCESS [ 37.015 s]
[INFO] Eclipse Smarthome DMX Binding ...................... SUCCESS [ 16.688 s]
[INFO] Eclipse Smarthome DMX Binding Tests ................ SUCCESS [ 14.809 s]
[INFO] Eclipse SmartHome hue Binding ...................... SUCCESS [ 19.807 s]
[INFO] Eclipse SmartHome hue Binding Tests ................ SUCCESS [ 21.133 s]
[INFO] Eclipse SmartHome FSInternetRadio Binding .......... SUCCESS [ 14.064 s]
[INFO] Eclipse Smarthome FSInternetRadio Binding Test ..... SUCCESS [ 15.798 s]
[INFO] Eclipse SmartHome LIFX Binding ..................... SUCCESS [ 23.741 s]
[INFO] Eclipse SmartHome LIRC Binding ..................... SUCCESS [ 15.257 s]
[INFO] Eclipse SmartHome NTP Binding ...................... SUCCESS [ 14.542 s]
[INFO] Eclipse SmartHome NTP Binding Tests ................ SUCCESS [ 16.013 s]
[INFO] Eclipse SmartHome Sonos Binding .................... SUCCESS [ 26.187 s]
[INFO] Tradfri Binding .................................... SUCCESS [ 16.588 s]
[INFO] Tradfri Binding Tests .............................. SUCCESS [ 17.402 s]
[INFO] WeatherUnderground Binding ......................... SUCCESS [ 14.768 s]
[INFO] Eclipse SmartHome WeMo Binding ..................... SUCCESS [ 16.611 s]
[INFO] Eclipse SmartHome Wemo Binding Tests ............... SUCCESS [ 19.341 s]
[INFO] Eclipse SmartHome YahooWeather Binding ............. SUCCESS [ 10.551 s]
[INFO] Eclipse SmartHome Extension Service Extensions ..... SUCCESS [  0.080 s]
[INFO] Eclipse SmartHome IoT Marketplace Extension Service  SUCCESS [ 11.775 s]
[INFO] Eclipse SmartHome IoT Marketplace Extension Automation Support SUCCESS [  8.393 s]
[INFO] Eclipse SmartHome I/O Services ..................... SUCCESS [  0.086 s]
[INFO] Eclipse SmartHome JavaSound I/O .................... SUCCESS [ 11.044 s]
[INFO] Eclipse SmartHome Web Audio Support ................ SUCCESS [  8.802 s]
[INFO] Eclipse SmartHome Transformation Services .......... SUCCESS [  0.079 s]
[INFO] Eclipse SmartHome Exec Transformation Service ...... SUCCESS [  7.697 s]
[INFO] Eclipse SmartHome Javascript Transformation Service  SUCCESS [  8.230 s]
[INFO] Eclipse SmartHome Map Transformation Service ....... SUCCESS [  8.605 s]
[INFO] Eclipse SmartHome Map Transformation Service Tests . SUCCESS [  9.965 s]
[INFO] Eclipse SmartHome Scale Transformation Service ..... SUCCESS [ 10.104 s]
[INFO] Eclipse SmartHome Scale Transformation Service Tests SUCCESS [  9.830 s]
[INFO] Eclipse SmartHome RegEx Transformation Service ..... SUCCESS [  8.443 s]
[INFO] Eclipse SmartHome RegEx Transformation Service Tests SUCCESS [  8.352 s]
[INFO] Eclipse SmartHome XPath Transformation Service ..... SUCCESS [  8.408 s]
[INFO] Eclipse SmartHome XPath Transformation Service Tests SUCCESS [  8.219 s]
[INFO] Eclipse SmartHome JSonPath Transformation Service .. SUCCESS [  8.273 s]
[INFO] Eclipse SmartHome JSonPath Transformation Service Tests SUCCESS [  8.366 s]
[INFO] Eclipse SmartHome Xslt Transformation Service ...... SUCCESS [  8.539 s]
[INFO] Eclipse SmartHome Xslt Transformation Service Tests  SUCCESS [  8.144 s]
[INFO] Eclipse SmartHome UI Extensions .................... SUCCESS [  0.078 s]
[INFO] Eclipse SmartHome Icon Sets ........................ SUCCESS [  0.078 s]
[INFO] Eclipse SmartHome Classic Icon Set ................. SUCCESS [ 11.805 s]
[INFO] Eclipse SmartHome Basic UI ......................... SUCCESS [03:45 min]
[INFO] Eclipse SmartHome Classic UI ....................... SUCCESS [ 17.371 s]
[INFO] Eclipse SmartHome Paper UI ......................... FAILURE [ 40.846 s]
[INFO] Eclipse SmartHome Voice Services ................... SKIPPED
[INFO] Eclipse SmartHome MacOS TTS ........................ SKIPPED
[INFO] Eclipse SmartHome Mac TTS Tests .................... SKIPPED
[INFO] Eclipse SmartHome Features ......................... SKIPPED
[INFO] Eclipse SmartHome Runtime Core Feature ............. SKIPPED
[INFO] Eclipse SmartHome Runtime Model Feature ............ SKIPPED
[INFO] Eclipse SmartHome Runtime UI Feature ............... SKIPPED
[INFO] Eclipse SmartHome Runtime REST Feature ............. SKIPPED
[INFO] Eclipse SmartHome Runtime Automation Feature ....... SKIPPED
[INFO] Eclipse SmartHome Runtime Equinox Console Feature .. SKIPPED
[INFO] Eclipse SmartHome Runtime RfC147 Console Feature ... SKIPPED
[INFO] Eclipse SmartHome Runtime Binding Feature .......... SKIPPED
[INFO] Eclipse SmartHome Test Dependencies ................ SKIPPED
[INFO] Eclipse SmartHome Karaf Features ................... SKIPPED
[INFO] Eclipse SmartHome Target Platform Feature .......... SKIPPED
[INFO] Eclipse SmartHome Core Feature ..................... SKIPPED
[INFO] Eclipse SmartHome Extensions Feature ............... SKIPPED
[INFO] Eclipse SmartHome Karaf Feature Verification ....... SKIPPED
[INFO] Eclipse SmartHome Products ......................... SKIPPED
[INFO] Eclipse SmartHome p2 Repository .................... SKIPPED
[INFO] Eclipse SmartHome Tools ............................ SKIPPED
[INFO] Eclipse SmartHome Archetypes ....................... SKIPPED
[INFO] Eclipse Smarthome Binding Archetype ................ SKIPPED
[INFO] Eclipse Smarthome Binding Archetype Testsuite ...... SKIPPED
[INFO] Eclipse SmartHome Target Platform .................. SKIPPED
[INFO] Eclipse SmartHome Distribution ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50:22 min
[INFO] Finished at: 2017-10-02T21:10:38-04:00
[INFO] Final Memory: 510M/1832M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project org.eclipse.smarthome.ui.paper: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Thanks for your help.

**Comment by ellipsistechnology** [comment]
Not sure why this one was closed - was the issue resolved/not reproducible? I'm getting the same issue with errors after following the [instructions](https://www.eclipse.org/smarthome/documentation/development/ide.html) on a Mac. The most obvious issue is a number of missing packages/classes, for example the org.eclipse.smarthome.model.rule.rules package is missing. Searching through git, including through past versions, I'm unable to see any implementation of this package - is it perhaps generated? Any help in getting this going would be greatly appreciated.

**Comment by maggu2810** [comment]
Please close the Eclipse IDE and try to build ESH using the following instructions:

```sh
mvn clean install -DskipChecks=true -DskipTests=true
```

Does this one succeed?
If not, please add the a log.
