### ISSUE TITLE
PaperUI: new group type item does not show rollershutter base type

### ISSUE THREAD

**Issue by sihui62** [eclipse/smarthome#4307]
I am currently on #build 1034:

![rollershutter_missing](https://user-images.githubusercontent.com/10405486/30628154-da4c8d5e-9dd4-11e7-960d-feabe713f925.JPG)

As a workaround I could use a dimmer base type ;-)

**Comment by kaikreuzer** [comment]
@htreu That should be an easy one to fix :-)

**Comment by htreu** [comment]
For the Rollershutter group type we need to provide a group function. Since Rollershutter accepts `DecimalType` we may go with `min,max,avg` or a subset. Alternatively we may drop the group function and do not give a combined state for rollershutter groups.
