### ISSUE TITLE
Basic UI internationalization

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4327]
Basic UI seems to have only few hardcoded texts (in english). I can find "Offline: waiting for connection to become available" in main.html and few others in sitemap_list.html and list_sitemap_empty.html.

So internationalization seems to be easy to provide.

@resetnow : wdyt ? Do I miss something ?

**Comment by resetnow** [comment]
>Do I miss something ?

Probably not. I've thought about it, just wasn't sure what mechanism should be used for implementation.

**Comment by lolodomo** [comment]
My idea is to replace hardcoded texts by %variable% and use the servlet to replace them with translated texts using the ESH i18n mechanism.
