### ISSUE TITLE
Basic/Classic UI build broken due to changes in chart

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4334]
It looks like a method `getLegend` is missing in the interface class `Chart` leading to Basic UI, Classic UI and sitemap REST API failing to build.
A fix is expected quickly if possible ;)

**Comment by lolodomo** [comment]
There are also fix to apply in ChartProviderDelegate.

**Comment by lolodomo** [comment]
@hreichert : could you have a look please ?

**Comment by hreichert** [comment]
@lolodomo Fix for ChartProviderDelegate is here: https://github.com/openhab/openhab-core/pull/215
BasicUI/ClassicUI: The `Chart` class is generated from xtend model. Can you confirm that you regenerated your model? Especially the sitemap model.

**Comment by lolodomo** [comment]
No, I just started Eclipse with new sources.
I just started a "mvn clean install" that should fix my problem. Sorry for disturbing.

**Comment by hreichert** [comment]
You're welcome :-)
