### ISSUE TITLE
Basic UI: Mixed content (https _and_ http)

### ISSUE THREAD

**Issue by bbesser** [eclipse/smarthome#4364]
Hi,

from the internet, I access BasicUI via an HTTPS-reverse-proxy (yes, it is secured), i.e. I browse to

https://MYSERVER/basicui/app?sitemap=SITEMAP

(placeholders used). The webpage reloads every 10 seconds and each time shows the message

Offline: waiting for connection to become available

at the bottom of the screen.

Using the common browser developer tools, I see the attempt to connect to the following event source:

http://MYSERVER/rest/sitemaps/events/UUID?sitemap=SITEMAP&pageid=PAGE

(placeholders used). However, the protocol for the request is HTTP instead of HTTPS, hence the connection cannot be established.

Best regards and keep up the great work!
bbesser

**Comment by sjka** [comment]
I have the same setup (i.e. an nginx reverse proxy which does the ssl termination) I can't confirm this behavior, all these event subscriptions (and other calls) are using the same (https) protocol.
With what version are you observing this?

**Comment by bbesser** [comment]
openHAB 2.1.0-1 (Release Build)
ui-basic - 2.1.0
(apache2 as reverse proxy)

Regards
bbesser

**Comment by kaikreuzer** [comment]
Must be clearly an issue with your Apache configuration then. Note that SSE might require some additional settings, the [same is true for NGINX](https://community.openhab.org/t/nginx-with-https-as-reverse-proxy-for-openhab2/13531/3?u=kai).
If you cannot figure it out what you need to change in Apache, I'd suggest to follow up on it [in your forum thread](https://community.openhab.org/t/basicui-mixed-content-requests-https-and-http/34727).
