### ISSUE TITLE
Sitemap / Item with Image causes NullPointerException

### ISSUE THREAD

**Issue by johnjore** [eclipse/smarthome#4367]
Sitemap
```
Frame label="Image" {
		Image item=Arf url="http://x.x.x.x:80/profiles/jj.png"
		Image item=ModeJJ url="http://x.x.x.x:80/profiles/jj.png"
	}
```
Items file:
`String ModeJJ								//Home, Away, Sleep, Unknown
`
Arf is not defined in sitemaps.

I have a rules file that updates ModeJJ and from the log file I _think_ this is the last entry:
> ModeJJ.postUpdate("Away")
> [ItemStateChangedEvent     ] - ModeJJ changed from NULL to away

Using the REST API I find these two from the sitemap:
```
http://x.x.x.x:8080/proxy?sitemap=default.sitemap&widgetId=0000
http://x.x.x.x:8080/proxy?sitemap=default.sitemap&widgetId=0001
``` 

The first one works fine (yes, with the non-existent item), 2nd one has this error when I open it in a browser: [https://image.ibb.co/j0Cbkb/Capture.png](https://image.ibb.co/j0Cbkb/Capture.png)

> HTTP ERROR 500
> Problem accessing /proxy. Reason:
>     Server Error
> Caused by:
> java.lang.NullPointerException
> Powered by Jetty://
> 

Assuming this is a bug and it should fail gracefully if it does not like the state of the item. Currently on OH 2.1. Apologies if this is a duplicate or fixed in 2.2.

**Comment by johnjore** [comment]
Not sure what the item comment refers to,  but lets focus on the NPE for now:

> 2017-10-03 10:57:25.254 [WARN ] [eclipse.jetty.servlet.ServletHandler] - /proxy
> java.lang.NullPointerException
>         at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:521)[71:org.eclipse.jetty.client:9.2.19.v20160908]
>         at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:694)[71:org.eclipse.jetty.client:9.2.19.v20160908]
>         at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:678)[71:org.eclipse.jetty.client:9.2.19.v20160908]
>         at org.eclipse.jetty.proxy.AbstractProxyServlet.sendProxyRequest(AbstractProxyServlet.java:538)[80:org.eclipse.jetty.proxy:9.2.19.v20160908]
>         at org.eclipse.jetty.proxy.ProxyServlet.service(ProxyServlet.java:91)[80:org.eclipse.jetty.proxy:9.2.19.v20160908]
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)[21:javax.servlet-api:3.1.0]
>         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[84:org.eclipse.jetty.servlet:9.2.19.v20160908]
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[84:org.eclipse.jetty.servlet:9.2.19.v20160908]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)[175:org.ops4j.pax.web.pax-web-jetty:4.3.0]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[83:org.eclipse.jetty.server:9.2.19.v20160908]
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[82:org.eclipse.jetty.security:9.2.19.v20160908]
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[83:org.eclipse.jetty.server:9.2.19.v20160908]
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[83:org.eclipse.jetty.server:9.2.19.v20160908]
>         at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)[175:org.ops4j.pax.web.pax-web-jetty:4.3.0]
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[84:org.eclipse.jetty.servlet:9.2.19.v20160908]
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[83:org.eclipse.jetty.server:9.2.19.v20160908]
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[83:org.eclipse.jetty.server:9.2.19.v20160908]
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[83:org.eclipse.jetty.server:9.2.19.v20160908]
>         at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[175:org.ops4j.pax.web.pax-web-jetty:4.3.0]
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[83:org.eclipse.jetty.server:9.2.19.v20160908]
>         at org.eclipse.jetty.server.Server.handle(Server.java:499)[83:org.eclipse.jetty.server:9.2.19.v20160908]
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[83:org.eclipse.jetty.server:9.2.19.v20160908]
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[83:org.eclipse.jetty.server:9.2.19.v20160908]
>         at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[74:org.eclipse.jetty.io:9.2.19.v20160908]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[86:org.eclipse.jetty.util:9.2.19.v20160908]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[86:org.eclipse.jetty.util:9.2.19.v20160908]
>         at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]
>

**Comment by maggu2810** [comment]
ESH itself is tested against Jetty 9.3.14. So it would perhaps make sense to create a minimum example configuration that could be used in the IDE for testing.

**Comment by kaikreuzer** [comment]
I just tested this against the current master. The exception that is logged is
```
2017-10-10 15:49:40.064 [WARN ] [lipse.jetty.server.HttpChannel:480  ] - //localhost:8080/proxy?sitemap=demo.sitemap&widgetId=0000&t=1507643379916java.lang.IllegalArgumentException: Invalid protocol null
	at org.eclipse.jetty.client.HttpClient.destinationFor(HttpClient.java:496)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:539)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:693)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:677)
	at org.eclipse.jetty.proxy.AbstractProxyServlet.sendProxyRequest(AbstractProxyServlet.java:549)
	at org.eclipse.jetty.proxy.ProxyServlet.service(ProxyServlet.java:119)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1223)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:148)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:131)
```
This is imho fine as it is correct that the item state does not specify any protocol (if it is simply "away") and thus the url cannot be connected to.
Returning an internal server error 500 is imho also the correct result. It is not the fault of the caller, but it is indeed an error on the server (here: the item state is invalid), which causes the issue.

**Comment by kaikreuzer** [comment]
FTR, this is the result in the browser, so there is no NPE anymore:

<img width="507" alt="screen shot 2017-10-10 at 16 02 32" src="https://user-images.githubusercontent.com/3244965/31390549-7ef4a7ba-add4-11e7-89a3-30e81f049bd3.png">

**Comment by johnjore** [comment]
No, this is not right. Lets back up a second.

Two variables defined in the items file:
```
Number ModeJJNumber
String ModeJJString
```

Rule file updates the values with some temporary data:
```
rule "Temp Rule"
when
        Time cron "0 0/1 * * * ?"
then
        postUpdate(ModeJJNumber, 19)
        postUpdate(ModeJJString, "string")
end
```
Log file shows the variables have been updated with the temp data

> 2017-10-10 15:59:00.110 [ItemStateChangedEvent     ] - ModeJJNumber changed from NULL to 19
> 2017-10-10 15:59:00.111 [ItemStateChangedEvent     ] - ModeJJString changed from NULL to string
> 

Sitemap:

> 	Frame label="Image" {
> 		Image item=ModeJJString url="http://x.x.x.x:8080/static/profiles/jj.png"
> 		Image item=ModeJJNumber url="http://x.x.x.x:8080/static/profiles/jj.png"
> 		Text  item=ModeJJNumber
> 		Text  item=ModeJJString
> 	}
> 
Using Chrome and the classic UI, neither text item show any value, and one picture is shown, the one using the ModeJJNumber.

Why?

This used to work in OH1. If this is change from OH1, how does one define variables in OH2 so they can be used in sitemaps?

**Comment by lolodomo** [comment]
To show a value, adding a label with a format could certainly help.

Regarding your image elements, I don't understand what you are trying to do ! Linking an image element to a number item has just no sense because an image element can only be linked to either a string item containing an URL or an image item containing the raw data of an image.

**Comment by johnjore** [comment]
Nah, you're missing the point. Forget the lines with the URL for now, and look only at 

```
Text item=ModeJJNumber
Text item=ModeJJString

```
Only the Text item with "ModeJJNumber" works correctly, after its been updated by the rule. The string item never displays anything using Chrome. The only difference between the two is that one is defined as a String, the other a Number in the items file. If they are left as NULL, it shows up, but without a value of course.

Why does the item defined as a number work correctly when updated from a rule, but not something defined as String?

(I didn't understand what the real problem was at the beginning, and i probably muddled it with the URL  part)

**Comment by lolodomo** [comment]
So now your problem is the code in rule...
Can you check in your file events.log that you see a state change for your 2 items when your rule is run ? If not, there is a problem in your rule.
By the way, I would advice to use `sendCommand` rather than `postUpdate` and maybe use `ModeJJNumber.sendCommand(19)` and `ModeJJString.sendCommand("string")`
Once you see an update of your items in the events.log file, if you still see nothing in UI, add a label with format like for example `Number ModeJJNumber label="ModeJJNumber [%d]"`. But normally you should inherite a default format and it should work without.

**Comment by johnjore** [comment]
As above, the log file shows the number and string were updated with the correct values:

2017-10-10 15:59:00.110 [ItemStateChangedEvent ] - ModeJJNumber changed from NULL to 19
2017-10-10 15:59:00.111 [ItemStateChangedEvent ] - ModeJJString changed from NULL to string

I'll need to test using postUpdate and report back tomorrow. Thanks for the suggestion.

**Comment by lolodomo** [comment]
In this case, the rule is OK. So try to add a label as explained just before using `[%d]` for the number item and `[%s]` for the string item.

**Comment by paulianttila** [comment]
Anyhow, the orginal problem (or how it’s descriped) is a bug in the code or documentation.

From https://docs.openhab.org/configuration/sitemaps.html#element-type-image

url is the default URL from which to retrieve the image, if there is no associated Item or **if the associated item’s state is not a URL**.

**Comment by paulianttila** [comment]
Exactly @lolodomo, but ModeJJ is string item and that caused the problem. String item content was ”Away”, which is not valid url, so OH should fetch image from the url, right?

**Comment by lolodomo** [comment]
Exactly. If the item value is not a valid URL, the code is failing back to the URL set in url=.

**Comment by paulianttila** [comment]
@lolodomo great, now we have a common understanding how it should work. How I understand the problem, code doesn't work like that, it return internal server error 500 rather than failing back to url=.  

Or is this failing back feature actually a client feature, so if OH returns an error, client should fetch the image from fall back url?

**Comment by lolodomo** [comment]
It is implemented on the proxy if I correctly remember.

**Comment by evansj** [comment]
I would say that the documentation matches the current behaviour. If the item is a `String` then it's expected to be a valid URL.

There's one part of the document that states:

> `url` is the default URL from which to retrieve the image, if there is no associated Item or if the associated item’s state is not a URL.

The problem is with the part *if the associated item's state is not a URL*. I suspect that Java decodes the URL `string` as a "valid" URL with the following properties:

Field | value
-----|-----
protocol | `null`
host | `"string"`
port | `-1`
path | `""` (empty string)
file | `""` (empty string)

i.e. it's not an invalid URL, just one that is useless. :-) Therefore, an attempt is made to load the  image from that URL instead of falling back to the `url` parameter of the `Image` element. **Note** this is a guess, I've not verified this behaviour, but it explains the "Invalid protocol `null`" error message. The Number item from the original example is ignored because (I presume) the code only uses the item parameter if the item's type is `String` or `Image`.

The `Image` element docs are

    Image [item=<itemname>] [icon="<iconname>"] url="<url of image>" [label="<labelname>"] [refresh=xxxx]

implying that all parameters except `url` are optional. So if you just want to include an image, something like this should work:

    Image url="http://x.x.x.x:8080/static/profiles/jj.png"

Sorry if I misunderstood the problem. The way I read it, it sounds like @johnjore is just trying to display a static image but thought that `item=<ITEM>` was a required parameter.

**Comment by johnjore** [comment]
What I was trying to do, (and worked in OH1.8), was a static image with a status message below (Home, Away). When moving to OH2, I got the NPE, and ended up implementing a workaround.

When logging the ticket, I removed everything relating to my client to simplify the bug report. However, as I use a custom written android client (Kala), my sitemaps are a little different, as they are extended with additional features compared to OH. Things are therefore a little different to what they appear here.

I'm grateful for all suggestions and may circle back to this one day and see if my workaround can be removed. For now, I'm just going to leave it as it is. 

Again, thanks for chipping inn, but please don't spend more time on this.

**Comment by lolodomo** [comment]
@evansj : if your assumption is correct, I think we should add a control that the protocol is not null.
I will try to reproduce that but to be honest it is not my first priority.

**Comment by paulianttila** [comment]
Proxy create URI directly rather than URL. URL doesn't accept url string which doesn't have protocol, so maybe proxy should create URL and then convert that to URI (.toURI()).

https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#URL(java.lang.String)

Current proxy implementation:
```
String itemName = widget.getItem();
if (itemName != null) {
	State state = itemUIRegistry.getItemState(itemName);
	if (state != null && state instanceof StringType) {
		try {
			uri = URI.create(state.toString());
			request.setAttribute(ATTR_URI, uri);
			return uri;
		} catch (IllegalArgumentException ex) {
			// fall thru
		}
	}
}

```

**Comment by lolodomo** [comment]
It exists a similar URL check in the Basic UI servlet.
