### ISSUE TITLE
Hue binding blocks when adding new thing from inbox

### ISSUE THREAD

**Issue by dominicdesu** [eclipse/smarthome#4375]
Hi,
when adding a new hue thing from thre inbox, it takes 5 seconds before the message appears that the thing has been added and in the log file I can see the following line:
`2017-10-04 20:12:54.725 [WARN ] [ome.core.thing.internal.ThingManager] - Initializing handler for thing 'hue:0200:00178812c614:3' takes more than 5000ms.`

There was a [recent change for the AutomaticInboxProcessor](https://github.com/eclipse/smarthome/pull/4192/files#diff-2ba4d1bdb2c89e2c8b66b342a88ed23eR139) which seems to cause this issue. The call of `updateThing(thing)` in the HueLightHandler seems to block for 5 seconds before the binding thread is killed(?) by Eclipse SmartHome.

Despite the 5 seconds delay for adding the thing the binding still seems to work correctly though.

I am using ESH/hue binding build  0.9.0.201709260841.

**Comment by sjka** [comment]
Do you happen to have some debug logs around the one line you pasted here? It would be especially helpful to have this one:

```
Timeout of {}ms exceeded, thread {} ({}) in state {} is at {}.{}({}:{})
```

**Comment by dominicdesu** [comment]
@sjka sorry for the delay, was trapped in Northern Germany...
```
2017-10-08 11:42:52.142 [DEBUG] [arthome.core.common.SafeMethodCaller] - Timeout of 5000ms exceeded, thread safeCall-3324 (166928) in state WAITING is at sun.misc.Unsafe.park(Unsafe.java:-2).
2017-10-08 11:42:52.147 [WARN ] [ome.core.thing.internal.ThingManager] - Initializing handler for thing 'hue:0200:00178812c614:3' takes more than 5000ms.
```
