### ISSUE TITLE
Sitemap: Error 500 when slider is any other value than 0

### ISSUE THREAD

**Issue by sgofferj** [eclipse/smarthome#4397]
System: Ubuntu server 16.04 LTS on Xeon 1240L V3. Openhab stable from ppa

In my sitemap I have a Slider item for a dimmer.
`Slider item=B1_1_Dim label="B1 Dimmer [%.0f]" icon="light"`

When I move the slider in BasicUI or the OpenHAB Android app, it sends the correct value but the displayed value is always 0. If the value is changed by any means, the Android app won't load the sitemap any more and the Basic UI would display a 500 Error:
> java.lang.IllegalArgumentException: Value must be between 0 and 100
> 	at org.eclipse.smarthome.core.library.types.PercentType.validateValue(PercentType.java:50)
> 	at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:45)
> 	at org.eclipse.smarthome.core.library.types.DecimalType.as(DecimalType.java:153)
> 	at org.eclipse.smarthome.core.items.GenericItem.getStateAs(GenericItem.java:87)
> 	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.convertState(ItemUIRegistryImpl.java:485)
> 	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getState(ItemUIRegistryImpl.java:464)
> 	at org.eclipse.smarthome.ui.basic.internal.render.AbstractWidgetRenderer.getState(AbstractWidgetRenderer.java:229)
> 	at org.eclipse.smarthome.ui.basic.internal.render.AbstractWidgetRenderer.preprocessSnippet(AbstractWidgetRenderer.java:92)
> 	at org.eclipse.smarthome.ui.basic.internal.render.SliderRenderer.renderWidget(SliderRenderer.java:46)
> 	at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.renderWidget(PageRenderer.java:164)
> 	at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.processChildren(PageRenderer.java:129)
> 	at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.processChildren(PageRenderer.java:150)
> 	at org.eclipse.smarthome.ui.basic.internal.render.PageRenderer.processPage(PageRenderer.java:92)
> 	at org.eclipse.smarthome.ui.basic.internal.servlet.WebAppServlet.service(WebAppServlet.java:152)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
> 	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
> 	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
> 	at java.lang.Thread.run(Thread.java:748)
> 

I double checked from the logs that the item's value stays indeed between 0 and 100. Every other value than 0 causes the error.

**Comment by sjka** [comment]
I just tried reproducing your issue, having a items file with

```
Dimmer testDimmer
```

and a sitemap with

```
Slider item=testDimmer label="Test Dimmer [%.0f]" icon="light"
```

I changed the value twice through the BasicUI, which resulted in the following logs:

```
14:20:48.729 DEBUG o.e.s.i.r.c.i.i.ItemResource[:296] - Received HTTP POST request at 'items/testDimmer' with value '87'.
14:20:48.730 INFO  s.event.ItemCommandEvent[:47] - Item 'testDimmer' received command 87
14:20:48.733 INFO  smarthome.event.ItemStateEvent[:47] - testDimmer updated to 87
14:20:48.734 INFO  s.event.ItemStateChangedEvent[:47] - testDimmer changed from 29 to 87

14:20:49.325 DEBUG o.e.s.i.r.c.i.i.ItemResource[:296] - Received HTTP POST request at 'items/testDimmer' with value '44'.
14:20:49.328 INFO  s.event.ItemCommandEvent[:47] - Item 'testDimmer' received command 44
14:20:49.330 INFO  smarthome.event.ItemStateEvent[:47] - testDimmer updated to 44
14:20:49.330 DEBUG o.e.s.i.r.s.i.SitemapEventOutput[:52] - Sent sitemap event for widget 0000 to subscription fa47c912-0fd1-4b6e-87a9-a579adc69478.
14:20:49.331 INFO  s.event.ItemStateChangedEvent[:47] - testDimmer changed from 87 to 44
```

Looks pretty good to me!

Also, the value was reflected correctly in the BasicUI:
![image](https://user-images.githubusercontent.com/2592443/31440364-ebcf2c14-ae8f-11e7-8dc8-484bbc55b74c.png)

Could you please provide a minimal sample configuration which allows reproducing it?

**Comment by sgofferj** [comment]
/etc/openhab2/sitemaps/main.sitemap (dimmer disabled now)
```
sitemap main label="Home" {
    Frame {
        Switch item=sceneSwitch label="" icon=""  mappings=[0="OFF",1="Work",2="TV",3="Bed"]
    }
    Frame label="Living room" {
//      Slider item=B1_1_Dim label="B1 Dimmer [%.0f]" icon="light"
        Switch item=B1_1_Col label="" icon="light"  mappings=["0000000000"="Off","00000000FF"="Warm","000000FF00"="Cold","FFFFFFFFFF"="Full"]
        Switch item=Livroom2 label="LEDs" icon="light"
        Switch item=Livroom1 label="Red" icon="light"
        Switch item=Switch2  label="Fan" icon="fan"
    }                                                                                                                                                          

    Frame label="Bedroom" {
        Switch item=Bedroom1 label="Light" icon="light"
        Switch item=Bedroom2 label="Stereo" icon="receiver"
    }

    Frame label="Terrace" {
        Switch item=Switch3 label="LED strip" icon="light"
    }

    Frame label="Weather" {
        Text item=weatherTemp label="Temperature [%.1f °C]" valuecolor=[>25="orange",>15="green",>5="orange",<=5="blue"]icon="temperature"
        Text item=weatherHum label="Humidity [%.1f %%]" icon="humidity"
        Text item=weatherPress label="Pressure [%.0f hPa]" icon="pressure"
    }

}
```

/etc/openhab2/items/switches.items
```
Group:Switch:OR(ON,OFF) gALL
Group:Switch:OR(ON,OFF) gLIGHTS
Group:Switch:OR(ON,OFF) gSOUND
Group:Switch:OR(ON,OFF) gPHONES

Number sceneSwitch "Scene"
Switch sceneSet "Scene set"

Switch Network_WOL_ENT  "Wakeup Enterprise"     (Status, Network)       { channel="network:device:192_168_10_1:online", wol="192.168.10.255#78:e7:d1:f7:ac:0c" }

Switch Bedroom1         "Bedroom Ch1"           (gALL, gLIGHTS)         { mqtt="<[broker:bedroom/stat/POWER1:state:default], >[broker:bedroom/cmnd/POWER1:command:*:${command}]" }
Switch Bedroom2         "Bedroom Ch2"           (gALL, gSOUND)          { mqtt="<[broker:bedroom/stat/POWER2:state:default], >[broker:bedroom/cmnd/POWER2:command:*:${command}]" }

Switch Livroom1         "Livroom Ch1"           (gALL, gLIGHTS)         { mqtt="<[broker:livroom/stat/POWER1:state:default], >[broker:livroom/cmnd/POWER1:command:*:${command}]" }
Switch Livroom2         "Livroom Ch2"           (gALL, gLIGHTS)         { mqtt="<[broker:livroom/stat/POWER2:state:default], >[broker:livroom/cmnd/POWER2:command:*:${command}]" }
Number LivroomT         "Livroom Temp"                                  { mqtt="<[broker:livroom/tele/SENSOR:state:JSONPATH($.DHT22.Temperature)]" }
Number LivroomH         "Livroom Hum"                                   { mqtt="<[broker:livroom/tele/SENSOR:state:JSONPATH($.DHT22.Humidity)]" }

Switch Switch1          "Switch 1"              (gALL)                  { mqtt="<[broker:switch1/stat/POWER:state:default], >[broker:switch1/cmnd/POWER:command:*:${command}]" }
Switch Switch2          "Switch 2"              (gALL)                  { mqtt="<[broker:switch2/stat/POWER:state:default], >[broker:switch2/cmnd/POWER:command:*:${command}]" }
Switch Switch3          "Switch 3"              (gALL, gLIGHT)          { mqtt="<[broker:switch3/stat/POWER:state:default], >[broker:switch3/cmnd/POWER:command:*:${command}]" }

Switch B1_1_Sw          "B1-1-Switch"           (gALL, gLIGHTS)         { mqtt="<[broker:b1-1/stat/RESULT:state:JSONPATH($.POWER)], >[broker:b1-1/cmnd/POWER:command:*:${command}]" }
Number B1_1_Dim         "B1-1-Dimmer"                                   { mqtt="<[broker:b1-1/stat/RESULT:state:JSONPATH($.Dimmer)], >[broker:b1-1/cmnd/Dimmer:command:*:default]" }
//Number B1_1_CT                "B1-1-ColorTemp"                                { mqtt="<[broker:b1-1/stat/RESULT:state:JSONPATH($.CT)],     >[broker:b1-1/cmnd/CT:command:*:default], >[broker:b1-1/cmnd/CT:command:*: ]" }
String B1_1_Col         "B1-1-Color"                                    { mqtt="<[broker:b1-1/stat/RESULT:state:JSONPATH($.Color)],  >[broker:b1-1/cmnd/Color:command:*:default]" }
```

/etc/openhab2/items/weather.items
```
Number  weatherTemp     "Outside temperature"   { mqtt="<[broker:weather/temperature:state:default]" }
Number  weatherPress    "Pressure"              { mqtt="<[broker:weather/pressure:state:default]" }
Number  weatherHum      "Outside humidity"      { mqtt="<[broker:weather/humidity:state:default]" }
Number  weatherDew      "Outside dew point"     { mqtt="<[broker:weather/dewpoint:state:default]" }
Switch  weatherStat     "Weather sensor status" { mqtt="<[broker:weather/stat:state:default]" }

DateTime        weatherUpdated  "[%1$tm/%1$td %1$tH:%1$tM]"
```

Please let me know what else config files you need.
I also see the values change in the event log but as mentioned, they don't show up in the android app or Basic UI. They do shop up in my HABPanel.

**Comment by sgofferj** [comment]
When I use Dimmer instead of Number, it works. But shouldn't it work with Number also?

**Comment by sjka** [comment]
So I summarize this as a minimal example to make sure I got it right:

The `test.items` file: 

```
Dimmer testDimmer
Number testNumber
```

The `test.sitemap` file:

```
sitemap test label="Test Sitemap" {
    Frame label="Test" {
        Slider item=testDimmer label="Test Dimmer [%.0f]" icon="light"
        Slider item=testNumber label="Test Number [%.0f]" icon="light"
    }
}
```

With this, the "dimmer" works nicely as expected. 

The "number" variant however throws the following exception when changing the value via the BasicUI:

```
08:25:54.120 DEBUG o.e.s.i.r.c.i.i.ItemResource[:296] - Received HTTP POST request at 'items/testNumber' with value '37'.
08:25:54.123 INFO  s.event.ItemCommandEvent[:47] - Item 'testNumber' received command 37
08:25:54.126 INFO  smarthome.event.ItemStateEvent[:47] - testNumber updated to 37
08:25:54.127 INFO  s.event.ItemStateChangedEvent[:47] - testNumber changed from 73 to 37
08:25:54.139 WARN  o.e.s.core.items.GenericItem[:232] - failed notifying listener 'org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener@4b4187d7' about state update of item testNumber: Value must be between 0 and 100
java.lang.IllegalArgumentException: Value must be between 0 and 100
	at org.eclipse.smarthome.core.library.types.PercentType.validateValue(PercentType.java:50)
	at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:45)
	at org.eclipse.smarthome.core.library.types.DecimalType.as(DecimalType.java:153)
	at org.eclipse.smarthome.core.items.GenericItem.getStateAs(GenericItem.java:91)
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.convertState(ItemUIRegistryImpl.java:526)
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getState(ItemUIRegistryImpl.java:505)
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getLabelColor(ItemUIRegistryImpl.java:1005)
	at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.constructSitemapEvents(PageChangeListener.java:192)
	at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.constructSitemapEvents(PageChangeListener.java:184)
	at org.eclipse.smarthome.io.rest.sitemap.internal.PageChangeListener.stateChanged(PageChangeListener.java:156)
	at org.eclipse.smarthome.core.items.GenericItem$1.run(GenericItem.java:229)
```

> But shouldn't it work with Number also?

No, afaik this it not intended to work. See also https://github.com/eclipse/smarthome/issues/1700#issuecomment-289928566
