### ISSUE TITLE
New Rule Engine causes deadlock in concierge

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#4400]
see https://github.com/eclipse/smarthome-packaging-sample/issues/13#issuecomment-335803723 for details.

To me this looks like a bug in concierge (and therefore I opened an issue there). Nevertheless, this brings me back to the question whether it is really a good idea to mess with bundle resolution within ESH, or if that rather should be left to the solution built on top... I personally consider this a design flaw!

**Comment by kaikreuzer** [comment]
I agree - bundles should not interfere with the lifecycle of other bundles; this should be changed in the automation module.
