### ISSUE TITLE
"Bridge Selection" Dropdown Menu No Longer Shows Up on PaperUI's Thing Page

### ISSUE THREAD

**Issue by lsafelix75** [eclipse/smarthome#4401]
Hi,

Can someone verify that “Bridge” dropdown is still shown on the latest Openhab2 nightly build (openHAB 2.2.0 Build #1058 or ESH #231)? This issue applies on both IDE and Snapshot. In my custom binding, I have thing defined as below in ESH-INF .xml:

```
<thing-type id="topic">
		<supported-bridge-type-refs>
			<bridge-type-ref id="broker" />
		</supported-bridge-type-refs>
		<label>XXXXX</label>
		<description>YYYY </description>
 		
		<channel-groups>
                   <channel-group id="abc" typeId="abc" />
                   <channel-group id="xyz" typeId="xyz" />
               </channel-groups>
	<config-description>
              <Param> ......
	</config-description>
	</thing-type>
	
</thing:thing-descriptions>
```
UPDATE: I reliazed that this only happened on discovered things and not manually added things. Wondering what has changed since previous builds on Discovery

**Comment by htreu** [comment]
I can confirm this bug. Its was introduced by #4359. Stay tuned, fix is on the way.
