### ISSUE TITLE
Latest OH2+ESH IDE Package Through Eclipse Installation has full of errors  

### ISSUE THREAD

**Issue by lsafelix75** [eclipse/smarthome#4418]
I am getting a lot "DS Annotation Problems", " Java Problems" even for fresh installation.

**Comment by ppieczul** [comment]
I have the same situation and @sprehn reported similarly.

**Comment by lsafelix75** [comment]
Looks like something is broken. I can confirm that the following in openhab.target are not downloaded:

<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
<unit id="org.eclipse.smarthome.feature.runtime.core.feature.group" version="0.0.0"/>
<unit id="org.eclipse.smarthome.feature.runtime.binding.feature.group" version="0.0.0"/>
<unit id="org.eclipse.smarthome.feature.runtime.console.equinox.feature.group" version="0.0.0"/>
<unit id="org.eclipse.smarthome.feature.runtime.rest.feature.group" version="0.0.0"/>
<unit id="org.eclipse.smarthome.feature.runtime.automation.feature.group" version="0.0.0"/>
<unit id="org.eclipse.smarthome.feature.test.feature.group" version="0.0.0"/>

**Comment by kaikreuzer** [comment]
I cannot confirm this for the ESH IDE - it resolves all fine.
I can confirm the issue for the openHAB IDE though - so let's continue on https://github.com/openhab/openhab-distro/issues/556.
