### ISSUE TITLE
OSGiEventManager / ThingLinkManager massive delays in OH 2.2 

### ISSUE THREAD

**Issue by marcus-schneider** [eclipse/smarthome#4419]
In OH 2.2 Build #1060 (also tested with lots of other Snapshot Builds over the last two Months) I see massive delays from sending a command to execution. It does not occur in the Stable Release.
After a restart of the service or the RPi3 everything works fine for a few hours. Delays seem to increase over the uptime. After a reboot last night this morning the logs looked like this:

```
07:54:00.004 [INFO ] [smarthome.event.ChannelTriggeredEvent] - astro:sun:home:rise#event triggered START
07:54:00.009 [INFO ] [smarthome.event.ChannelTriggeredEvent] - astro:sun:home:civilDawn#event triggered END
07:54:04.652 [INFO ] [lipse.smarthome.model.script.Rolladen] - Rolladen jetzt öffnen
...
07:55:47.633 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'ROLL_SCH' received command 100
07:55:52.653 [WARN ] [core.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.CommunicationManager@cdbc56' takes more than 5000ms.
...
07:56:48.259 [INFO ] [smarthome.event.ItemStateChangedEvent] - ROLL_SCH changed from 10 to 99
```

From command to execution it took almost three minutes.
In this case the Item was triggered by a rule, but same behaviour, when you try to contol manually from any device or UI.

Community could not help so far [https://community.openhab.org/t/osgieventmanager-thinglinkmanager-delays-in-oh-2-2/35123](url)

Edit: example is for Z-Wave rollershutters on collocated Z-Way Server but happens to other bound devices as well

**Comment by kaikreuzer** [comment]
> but happens to other bound devices as well

It is very likely that this is cause by some binding (e.g. Z-Way?). You should try to reproduce it without any bindings and by adding them one by one you might be able to find the culprit.

@sjka In any case it looks a bit weird that dispatching to the CommunicationManager times out. Didn't we usually have logs that point to a specific handler that causes the issue? Any idea here?

**Comment by marcus-schneider** [comment]
Built up all from scratch, adding Bindings, removings Binding, testing...same same.

After my post here switched back to Stable Release, everything fine. Now just PaperUI that kills me again.
But at least no more delays. Should keep this version until 2.2 is stable.

**Comment by kaikreuzer** [comment]
We did a lot of changes and improvements wrt blocking behavior in the event processing, so I would claim that this should be solved by now.

If there is still an issue, feel free to re-open.
