### ISSUE TITLE
Paper UI: Switch of DimmerItemController inconsistent to slider

### ISSUE THREAD

**Issue by mdicke2s** [eclipse/smarthome#4430]
There is a chance of having switch=off even if the percentvalue is different than 0% (see screenshot). This can be repoduced by appliying the following interactions to the DimmerItemController:
1) refresh paperui with having dimmer item set to 100%; result: slider=100, switch=on
2) click switch; result: silder=0, switch=off
3) click slider at 30%; result: slider=30, switch=off

Remark 1: Actually if you have a second browser open, it is shown correctly there
Remark 2: Didn't manage to do so without UI interaction (by just sending commands from elsewhere)
Remark 3: From the configuration slider=100, switch=on you can also go to slider=0, switch=on by using the slider

I would appreciate if somebody with JS knwoledge takes care of this. @aounhaider1 already agreed to take a look here.

![screenshot-2017-10-17 paper ui](https://user-images.githubusercontent.com/1636603/31661958-83c2d52c-b334-11e7-987a-1074839939b1.png)

**Comment by floriandd2ba** [comment]
I see the same in my configuration: https://github.com/openhab/openhab-distro/issues/555

Could it be this function, who needs a change:
Source:
https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java

    /**
     * Converts an item state to the type the widget supports (if possible)
     *
     * @param w Widget in sitemap that shows the state
     * @param i item
     * @return the converted state or the original if conversion was not possible
     */
    **private State convertState(Widget w, Item i)** {
        State returnState = null;

        if (w instanceof Switch && i instanceof RollershutterItem) {
            // RollerShutter are represented as Switch in a Sitemap but need a PercentType state
returnState = i.getStateAs(PercentType.class);

**NEW**
        if (w instanceof Switch && i instanceof DimmerItem) {
            // Dimmer use a PercentType state, but Switch need ON/OFF for show the right state
returnState = i.getStateAs(OnOffType.class);
**NEW**

I don't have a lot of programming skill, so just guess.
