### ISSUE TITLE
Item group assignment does not take effect without service restart

### ISSUE THREAD

**Issue by sgofferj** [eclipse/smarthome#4434]
System: openhab stable from PPA on Ubuntu server 16.04 LTS

I noticed that when I change the group assignment of an item in the .items-file, the change does not take effect without a service restart. openhab.log indicates that the file change was detected and the model was updated. Other item changes do take effect without service restart.

**Comment by sjka** [comment]
I can confirm this:

test.items before:

```
Group testGroup
Number testItem1 (testGroup)
Number testItem2
```

test.items after:

```
Group testGroup
Number testItem1 (testGroup)
Number testItem2 (testGroup)
```

still gives

```
testGroup (Type=GroupItem, Members=1, State=NULL, Label=null, Category=null)
testItem1 (Type=NumberItem, State=NULL, Label=null, Category=null, Groups=[testGroup])
testItem2 (Type=NumberItem, State=NULL, Label=null, Category=null)
```
