### ISSUE TITLE
Firmware Update: Model-specific firmwares

### ISSUE THREAD

**Issue by hsudbrock** [eclipse/smarthome#4446]
### The issue

Currently, in Eclipse SmartHome, a firmware is always related to exactly one thing type. Moreover, the `o.e.sh.core.thing.firmware.FirmwareUpdateService` determines the latest firmware available for a thing based solely on the thing's type.

Consider two devices that, from the perspective of Eclipse SmartHome, provide the same functionality and are controlled using the same protocols, but that are actually different device models and need different firmware versions. (Example: Two different models of a roller shutter from the same company.) For the binding, it makes sense to use one thing type and thing handler for both devices (to avoid the additional complexity of having two thing types and handlers that provide the same function).

In this case, the current way of handling firmware update in Eclipse SmartHome is not sufficient, since firmwares are related to exactly one thing type. To obtain the correct firmware in the described case, one needs to identify the latest firmware based on thing type and the thing's model ID.

### Solution suggestions

I suggest to extend the Eclipse SmartHome firmware code such that firmwares can be for a specific model (in addition to being for a specific thing type).  I see two ways how to consider a thing's model in the Eclipse SmartHome firmware code:

1. Adding a boolean property `isModelSpecific` to `o.e.sh.core.thing.binding.firmware.Firmware` such that a firmware can indicate that it must only be used for things with a corresponding model ID.
2. Extending the `o.e.sh.core.thing.firmware.FirmwareProvider` interface such that firmware providers can (optionally) provide firmwares based on thing type and model ID.  (Could be done in a backwards compatible way by providing default implementations for the new interface methods.)

For the first approach, the `o.e.sh.core.thing.firmware.FirmwareUpdateService` has to be changed such that it only considers firmwares that are suitable for a given thing (based on the new `isModelSpecific` flag, the firmware's `model`, and the thing's `modelId` property).

For the second approach, the `o.e.sh.core.thing.firmware.FirmwareRegistry`has to be extended to provide firmwares based on thing type and model ID as well. Moreover, the `o.e.sh.core.thing.firmware.FirmwareUpdateService` has to be adapted to use the new methods of the `FirmwareRegistry` when finding suitable firmwares for a thing.

My preference is the first approach, since it does not require to adapt existing interfaces.

I would be happy about feedback on these suggestions; I am also willing to implement this improvement :smile:

### Credit
Credit for suggesting such an improvement in Eclipse SmartHome as well as initial ideas for implementation goes to @tomhoefer.

**Comment by sjka** [comment]
Thanks for taking care of this. Indeed, it makes much more sense (optionally) having the model ID checked than having to use different thing types just for this purpose!
