### ISSUE TITLE
[Documentation]Iconset broken

### ISSUE THREAD

**Issue by Confectrician** [eclipse/smarthome#4456]
Hi,

somehow the [classic iconset page](https://www.eclipse.org/smarthome/documentation/features/ui/iconset/classic/readme.html) seems to be broken.
![image](https://user-images.githubusercontent.com/7161177/31962225-4aea8370-b8fd-11e7-95bd-5a3e3ecfa631.png)

There are a lot "no category" question marks.

**Comment by kaikreuzer** [comment]
The page is not broken, we are simply lacking the icons in this iconset.

**Comment by Confectrician** [comment]
Thanks for clarification.
