### ISSUE TITLE
findbugs @ org.eclipse.smarthome.ui: path concatenation seems to be broken

### ISSUE THREAD

**Issue by boaks** [eclipse/smarthome#4457]
> [INFO] --- static-code-analysis:0.3.0:findbugs (default) @ org.eclipse.smarthome.ui ---
> [INFO] Adding dependency to static-code-analysis:0.3.0
> [INFO] Adding dependency to bug-pattern:1.2.4
> [INFO] Adding dependency to spotbugs:3.1.0-RC3
> [INFO] Fork Value is false
>      [java] JVM args ignored when same JVM is used.
>      [java] The following errors occurred during analysis:
>      [java]   File from auxiliary classpath not found: filesystem:C:\projects\smarthome\bundles\ui\org.eclipse.smarthome.ui\lib\xchart-2.6.1.jarC:\Users\Achim\.m2\repository\p2\osgi\bundle\org.eclipse.jdt.annotation\2.1.100.v20170511-1408\org.eclipse.jdt.annotation-2.1.100.v20170511-1408.jar
>      [java]     java.io.FileNotFoundException: File C:\projects\smarthome\bundles\ui\org.eclipse.smarthome.ui\lib\xchart-2.6.1.jarC:\Users\Achim\.m2\repository\p2\osgi\bundle\org.eclipse.jdt.annotation\2.1.100.v20170511-1408\org.eclipse.jdt.annotation-2.1.100.v20170511-1408.jar doesn't exist
>      [java]       At edu.umd.cs.findbugs.classfile.impl.ClassFactory.createFilesystemCodeBase(ClassFactory.java:111)
>      [java]       At edu.umd.cs.findbugs.classfile.impl.FilesystemCodeBaseLocator.openCodeBase(FilesystemCodeBaseLocator.java:77)
>      [java]       At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.processWorkList(ClassPathBuilder.java:628)
>      [java]       At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:230)
>      [java]       At edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:677)
>      [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:218)
>      [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
>      [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
>      [java]       At sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      [java]       At sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>      [java]       At sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>      [java]       At java.lang.reflect.Method.invoke(Method.java:498)
>      [java]       At org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:221)
>      [java]       At java.lang.Thread.run(Thread.java:748)
> [INFO] Done FindBugs Analysis....
> 

> art-2.6.1.jarC:\Users\

Path separation seems to be missing.

**Comment by kaikreuzer** [comment]
@svilenvul Could you check what causes this?

**Comment by VelinYordanov** [comment]
@kaikreuzer  I think it could be an issue with spotbugs. I submitted an issue there in case someone can help out with that. spotbugs/spotbugs#479

**Comment by VelinYordanov** [comment]
@kaikreuzer I managed to fix the issue with this PR spotbugs/spotbugs-maven-plugin#11.
The problem should be gone in the next version of the spotbugs maven plugin.

**Comment by triller-telekom** [comment]
@VelinYordanov Thank you for taking care of reporting this bug upstream. Since this was in November, do you have an estimate date when the new version will be available? Which version number will it have?

**Comment by sjka** [comment]
With openhab/static-code-analysis/pull/254 and #5422 being merged, this should be fixed now.
