### ISSUE TITLE
create channel of specific type

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#4461]
I would like to create a channel for a thing dynamically at runtime.
The channel type is defined (e.g. by a file `ESH-INF/thing/foo.xml`) and so well known.

The `ThingFactoryHelper` already contains code that could be reused to create a channel of a given channel type (so all information is already filled in).
The method is currently private.
Is there any reason to keep them private?

If the function would be public a developer could use e.g.

```Java
final ChannelTypeUID channelTypeUID = new ChannelTypeUID("my-binding", "my-channel-type");
final Channel channel = ThingFactoryHelper.createChannel(
    new ChannelDefinition("my-generated-channel", channelTypeUID),
    getThing().getUID(),
    null /* no group */,
    configDescriptionRegistry
);
```

Do you see any design flaws here?

**Comment by sjka** [comment]
The biggest flaw I see here that is is a static method which piggy-backs on the equally static `TypeResolver.resolve(...)` which in turn gets some service references from a static field in the activator. This is brutally against everything we ever learned how to behave well in the OSGi context.
So to me opening up this API and make it public would be a step back in our attempts to clean up such crappy places. I don't think having static helper methods in our APIs leads us to where we want to be.

Apart from that, conceptually I don't see an issue with reusing the same code.

**Comment by kaikreuzer** [comment]
I'd think that this feature is now available through `ThingHandlerCallback.createChannelBuilder()`.
