### ISSUE TITLE
UpnpDiscoveryService will fail when org.jupnp.registry package is not available

### ISSUE THREAD

**Issue by JochenHiller** [eclipse/smarthome#4470]
We saw a lifecycle issue in bundle `org.eclipse.smarthome.config.discovery`.

The bundle declares an `import-package: org.jupnp.registry;resolution:=optional`. So bundle is fine to live without any jUPnP classes in runtime.

On the other side there is a DS component defined like that:
```
@Component(immediate = true, service = DiscoveryService.class, configurationPid = "discovery.upnp")
public class UpnpDiscoveryService extends AbstractDiscoveryService implements RegistryListener {
```

This means that this component will be immediately activated. But when as this point in time the optional package is missing, the DS comp can not be activated as the interface to implement is missing. Which will result in a `ClassNotFoundException` or `NoClassDefFoundError`. Which will result in an Unsatisfied DS component, and furthermore other DS comps unsatisfied.

Thats what we observed when updating bundles in runtime.

We propose to move this UPnP specific logic out of the generic `o.e.sh.config.discovery` bundle to the `org.eclipse.smarthome.io.transport.upnp` bundle where there can be easily mandatory references to jUPnP classes/interfaces.

What do you think?

**Comment by sjka** [comment]
The mDNS stuff also has its DiscoveryService implementation in the o.e.sh.io.transport.mdns bundle, so it would simply become symmetric. 

Also, all upnp based bindings as of today already require the o.e.sh.io.transport.upnp bundle - even those which actually don't need it (like e.g. hue). 

So maybe  miss something, but I don't see an issue moving it over there.

**Comment by sjka** [comment]
Just found one: UpnpDiscoveryParticipant also has some dependencies, and moving that would either lead to having to change all bindings (not really cool) or slit packages (yuck!).

**Comment by amitjoy** [comment]
To get rid of huge API breaking changes, we could adapt this component to be failsafe even if the optional packages do not become available when device scanning gets started. In proposal PR #4472, I have taken the similar approach to have a dedicated failsafe component that deals with all JUPnP optional dependencies. This component will only be enabled if and only if the optional dependencies are available to the config.discovery bundle's classloader.
