### ISSUE TITLE
[Tradfri] Adapt binding to use DTLS identities

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4479]
IKEA has introduced new security features with the latest Tradfri gateway firmware, see https://github.com/ggravlingen/pytradfri/issues/90.

It seems as if the current implementation breaks as soon as the new firmware is installed on a gateway. We therefore should adapt the binding asap to use the new mechanism.

I am yet undecided whether we still need to support the old way for old gateways as well - probably it is easiest to check the firmware version and simply set the Thing status to OFFLINE and asking the user to update the firmware, if an old version is encountered.

**Comment by kaikreuzer** [comment]
@hreichert & @cweitkamp As you are heavy Tradfri users: Do you already have the latest firmware installed and can confirm the issue? Anyone interested in implementing the required change?

**Comment by Landrash** [comment]
@kaikreuzer Can confirm that the latest firmware is out to the gateways and will auto-install if the gateway got wan access.

**Comment by cweitkamp** [comment]
I heard about it. There are some discussions on the community forum about it: https://community.openhab.org/t/ikea-tradfri-gateway/26135/147

I personally blocked internet access for the gateway in my firewall setup. Hence my firmware is not updated, yet.

**Comment by hreichert** [comment]
@kaikreuzer 
I'm currently not at home, but I see the following in OpenHAB PaperUI:
> Current firmware version: 1.2.42
I tried switching my hallway light on, and my webcam shows that it worked!

**Comment by juppe69** [comment]
I think it will work if the binding and gateway was installed before the update, but if you try to install the binding on a new system I dont think it will work.

**Comment by keithr99** [comment]
I left a related comment at the below. I can confirm all my lights/groups etc  work (excluding removing things) on the new gateway firmware.
https://community.openhab.org/t/possible-mid-reuse-before-lifetime-end-tradfri/34183/5

**Comment by ptweety** [comment]
Also still running fine with new firmware on the gateway. Has someone already tried to restart OH or reboot the gateway?

**Comment by sysadmama** [comment]
Restarted OH2, rebooted gateway. Everything still works as expected.

**Comment by juppe69** [comment]
I have rebooted OH and it works fine, but if you try to add the gateway to a system where it has not been installed it will not work. So something have to be done whit this.

**Comment by juppe69** [comment]
Nice to see such a fast fix.
When and where will this fix be available?
Would like to use it when I install my new system.

**Comment by juppe69** [comment]
I've tested the new snapshot (1073), is tradfri suppose to work in that snapshot?
Because I can't get it to work. It is still tre same error as before. I cant set the security code for the gateway. When I try to add things I can select the tradfri binding, but it directly try to find things and I dont get opportunity to enter the security code. The gateway is not showing up among the other things.

**Comment by andreas-bell** [comment]
hi, I have just bought my first Tradfri Gateway and 4 bulbs, set them up first in the Tradfri App. 
Everything worked, and I saw some messages about firmware updates done automatically.
GW is showing 1.2.42 and lamps 1.2.217
Then on my OH 2.1 (stable) I added the GW manually with IP and secret code. All lamps were then found automatically and working fine. I understand this is in contrast to some reports above and I have no clue why it worked for me. But I'm glad it worked so smoothly :-)

**Comment by juppe69** [comment]
How do I add the gateway manually, where do I enter the IP and secret code? I've tried to add it via the PaperUI and that doesn't work for me.

**Comment by andreas-bell** [comment]
In the PaperUI add the binding under AddOns. Then go to the Things, look for the Tradfri Gateway, edit it to set the IP and the code. It should change to status online.

**Comment by juppe69** [comment]
I did try that, but as I wrote the gateway did not show up in things in PaperUI. But I got it to work by enter it manually in the things file. 
But it would be nice to get it to work via the PaperUI.
