### ISSUE TITLE
[Tradfri] Binding doens´t provide group events after Tradfri App/Gateway Update

### ISSUE THREAD

**Issue by haukman** [eclipse/smarthome#4488]
I´m using Tradfri Group events in my OpenHab-config to trigger some other devices in my livingroom. After the update from IKEA for the App/Gateway (which makes HomeKit/Alexa available) the events.log stopped receiving these entries. I can still control all my tradfri devices from OpenHab, so this is not a general connection issue.

Can someone confirm this behaviour?

## Expected Behavior
Pressing the Tradfri-Remote (that is part of a Tradfri group), should create event in my envents.log (worked fine until update)

## Current Behavior

No events displayed int the events.log anymore
## Steps to Reproduce (for Bugs)

1. Add a tradfri-Group to your config.things, config.items
2. Turn the lights on and off and watch the events.log

## Context

Thank you!

**Comment by kaikreuzer** [comment]
Are groups an official feature of the binding at all? I do not see anything being mentioned in its documentation at https://www.eclipse.org/smarthome/documentation/features/bindings/tradfri/readme.html...

**Comment by haukman** [comment]
That´s correct - it´s not documented. I found it in the forum:

https://community.openhab.org/t/ikea-tradfri-gateway/26135/84

This is my things-file:

```
//Tradfri Binding
Bridge tradfri:gateway:mygateway [ host="X.X.X.X", code="XXX" ] {
    0220 lampe_kommode [ id=65537 ]
    0220 lampe_fensterbank [ id=65539 ]
    0220 lampe_tisch [ id=65538 ]
    group wohnzimmer [ id=139544 ]
}
```
Without the group definition openHab didn´t receive events if some member of the group "wohnzimmer" changed it status directly through the Tradfri-Remote.

**Comment by haukman** [comment]
This user has the same issue: https://community.openhab.org/t/ikea-tradfri-gateway/26135/141

**Comment by sjka** [comment]
There was a (now abandoned) PR which attempted to add group support (#3799) and never made it into the code base. So no, this is simply not supported by the binding.
