### ISSUE TITLE
Memory leak on RPI ? Maybe due to image channels ?

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4490]
I was surprised to discover this morning that my RPI 2 had only 32 MB of free memory and the OH java process was using 35,9% of the memory !
```
             total       used       free     shared    buffers     cached
Mem:           973        939         33          6         33        121
-/+ buffers/cache:        784        188
Swap:           99          0         99
```
After disabling few Netatmo Welcome things and restarting openHAB, I can see that I have around 206 MB of free memory.
Without Sonos playing, I can see that the free memory decreases slowly while the java process increases its memory usage.
If I start a playlist on my 2 Sonos, I can see that almost everytime I switch to the next song, the free memory decreases of until 1 MB.
Displaying (hi-res) charts in HABdroid seems to have an impact too but maybe less important.

After maybe 1 hour my free memory is now 171 MB and the java uses 23% of the memory.

Is it normal ?
When is triggered the JVM garbage ùeùory collector ?

I am asking myself if we have not a problem with the image channels and memory data not released ?
WDYT ?

**Comment by lolodomo** [comment]
Here is what I have now:
```
             total       used       free     shared    buffers     cached
Mem:           973        808        164          6         34        123
-/+ buffers/cache:        650        322
Swap:           99          0         99
```

**Comment by mueller-ma** [comment]
Memory that is | You'd call it | Linux calls it
-- | -- | --
used by applications | Used | Used
used, but can be made available | Free (or Available) | Used (and Available)
not used for anything | Free | Free

from https://www.linuxatemyram.com/

**Comment by lolodomo** [comment]
So there is no problem and I can close this issue ?

**Comment by mueller-ma** [comment]
I dont know, look at your available ram and if it gets less over time:
`cat /proc/meminfo | grep '^MemAvailable:' | awk '{print $2/1024}'`

**Comment by lolodomo** [comment]
Your command leads to 393.312 while the free command leads to 
```
             total       used       free     shared    buffers     cached
Mem:           973        931         41          6         36        148
-/+ buffers/cache:        745        227
Swap:           99          0         99
```
So it seems you're right and I have no problem. I will check the available memory in few hours.

**Comment by maggu2810** [comment]
Can you use visualvm or something similar to visualize the available objects and get a point what eating the memory?

**Comment by mueller-ma** [comment]
Nothing id eating the memory. This is how linux works. Whenever you have file io linux cashes the files in memory and showing it as not free, but available. This version of `free` however doesnt show how much ram is available.

**Comment by maggu2810** [comment]
> Nothing is eating the memory.

Hi @mueller-ma, I know how the linux memory management is working (at least a little bit). :wink: 
But I cannot state that nothing is eating the memory just because it could be explained by the caching / memory handling of the Linux OS.

I have some ESH products running and some of them run into OOM errors. So there is something eating memory in some cases. If it is in my case related to an ESH bundle, a third party dependency or a private bundle is another story.

I have already seen using `VisualVM` that more and more memory is used on instances that are running for weeks, so this is really unrelated to the operation system as the memory usage of the JVM is inspected.

**Comment by maggu2810** [comment]
What I want to say, you could tell @lolodomo that it does not need to point to a memory leak, but you cannot tell that there is no memory leak.

**Comment by triller-telekom** [comment]
@lolodomo Do you still think there is a memory problem? At least if there is, you cannot narrow it down to the use of image channels, can you?

So shall we rename this issue to something like "general memory leak" or rather decide to close it for now and open a new one once we have at least some more evidence?

**Comment by lolodomo** [comment]
Yes I think there is no link with image channels.
I don't know if there is or not a memory leak but OH on my RPI 2 never crash.
So I close the issue and I will reopen it the day I have more detailed information.
