### ISSUE TITLE
Basic UI requesting chart data even for hidden charts

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4492]
After tracing the chart servlet, I discovered that if in your sitemap, you have several charts defined with different periods and a visibility attribute set to only display the chart for the selected period, in fact Basic UI is requesting the server for all charts, meaning even for charts it does not render.
This leads to useless activity on server side.
Basic UI should consider the visibility property.

**Comment by lolodomo** [comment]
@resetnow : could you please explain to me why the change of visibility of a widget is handled by a complex mechanism which leads to a delay of 100 ms if my reading of the code is correct ?
https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/web-src/smarthome.js#L268

**Comment by lolodomo** [comment]
For image and chart widgets, I think we should simply use "images/none.png" as image URL when the widget is hidden. This will avoid the download of a big image or chart when unnecessary.
I will propose a fix.

**Comment by resetnow** [comment]
@lolodomo DOM changes are queued and apprlied after a delay of 100 ms in order to apply them all at once. The delay is needed in case the connection is not so good. This helps to avoid glitches when, for example, chart period is switched — otherwise you could have moments when either all charts are hidden or several are visible.

**Comment by lolodomo** [comment]
@resetnow : thank you for the explanation.
My current fix seems to introduce a problem with refresh ... or there was a problem with refresh. To be continued.
