### ISSUE TITLE
Chart servlet: performance problem on RPI

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4493]
Using android app and opehHAB server on my RPI 2, I see that it takes several seconds to display a chart.
As a remember the android app is requesting a big chart with my tablet (2560x1280).

After tracing the chart servlet on my RPI2, I discovered that the server takes around 7 seconds to handle the HTTPS request and build the PNG data. What takes most of the time (5 seconds) is the writing of the PNG data done at this line: https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/ChartServlet.java#L281

Any idea whether we can make `ImageIO.write` run faster ?

What would be the solution to avoid that case ? Should the server build a smaller chart in case the CPU is slow ?

The discussion started here: https://github.com/openhab/openhab.android/issues/440

**Comment by mueller-ma** [comment]
Is it possible to generate a svg instead of png?

**Comment by lolodomo** [comment]
Apparently the XChart library we are using ( https://knowm.org/open-source/xchart/ ) does not support SVG output but this would be possible if using an additional library : https://github.com/eseifert/vectorgraphics2d

**Comment by mueller-ma** [comment]
Dont know if that may help: #4495 
Could be included in the android app as webview, but I dont know if that will be more perfomant.

**Comment by lolodomo** [comment]
Before studying the move of the chart rendering from server to client, we could think if the current chart provider (on server side) could be optimized to provide a low resolution chart when the server is running on a slow machine.
Do we have something to know what are the server performance and to decide if the server is a slow machine or not ?
Maybe we could compute the time needed to create the PNG data and then introduce an automatic limit in resolution. So the chart provider will adjust itself after the first chart requests.
WDYT ?

**Comment by lolodomo** [comment]
Now I see that we can define settings for the chart servlet like default width, default height and scale.
Maybe the scale setting is almost what should be used by the users with slow server hardware. The scale is applied to the requested height. For example, if the requested height is 1280 and scale setting is set to 0.5, the used height will be 740.
What I don't understand is why the scale is not applied to the requested width ? Is it a bug ?
I will try to set these settings and see what happens.
Note that these settings would allow higher resolution charts in Basic UI and Classic UI to.

**Comment by lolodomo** [comment]
Maybe the scale setting is more an adjustment of the chart ratio ?
By the way, I think the idea to have an additional setting that could limit the size of the chart is the solution. This could be a maximum width for example ?

**Comment by mueller-ma** [comment]
> we could think if the current chart provider (on server side) could be optimized to provide a low resolution chart when the server is running on a slow machine.

I dont think so. The server should provide whatever resolution is requested. If it takes too long, the client should request a lower resolution.

> Maybe the scale setting is more an adjustment of the chart ratio ?

If you mean the dpi setting: Its used to scale the text inside the chart, but has nothing to do with the height and width.

**Comment by lolodomo** [comment]
I am talking about chart settings on server side.
I will try to add an optional maxWidth chart setting on server side. Any user will have the choice to use or not. By default, there will be no maximum width set and nothing will be changed. It will have sense to use this new setting only on slow hardwares like RPI and only if you prefer having faster charts than high res charts. I just need to check what are the impacts in the openHAB app and in particular the size of the legend.
