### ISSUE TITLE
Adding MAC Address to thing property

### ISSUE THREAD

**Issue by tomhoefer** [eclipse/smarthome#4509]
Currently the thing interface defines the following keys for the thing properties:
```
public interface Thing extends Identifiable<ThingUID> {
    /** the key for the vendor property */
    String PROPERTY_VENDOR = "vendor";
    /** the key for the model ID property */
    String PROPERTY_MODEL_ID = "modelId";
    /** the key for the serial number property */
    String PROPERTY_SERIAL_NUMBER = "serialNumber";
    /** the key for the hardware version property */
    String PROPERTY_HARDWARE_VERSION = "hardwareVersion";
    /** the key for the firmware version property */
    String PROPERTY_FIRMWARE_VERSION = "firmwareVersion";
    ...
```
I think it is worth to add a constant for the MAC address to the list of property keys maintained in ESH. At least we already require the MAC address in several bindings.

**Comment by sjka** [comment]
We shouldn't put too many specific ones in here, but I agree that the MAC address is a pretty common one, so why not...

Will you create a PR for it?

**Comment by tomhoefer** [comment]
I understand that we shouldnt add to many property into the thing interface. But my initial thought was also that the mac address is a common one.

> Will you create a PR for it?
I will try :)
