### ISSUE TITLE
Handling RuntimeExceptions in scheduled tasks (in bindings)

### ISSUE THREAD

**Issue by Hilbrand** [eclipse/smarthome#4543]
While reviewing some bindings I found that almost everyone catches `Exception`. It's advised to not do this. However to do it correctly one should still catch `RuntimeException`. At least if the code is run by a scheduled task using the `scheduler` from the `BaseThingHandler`. Because if a `RuntimeException` is thrown inside a scheduled job that is not catched it will silently stop the scheduling and not log the error if nothing extra is done (which I haven't seen). A solution to this can be call get on the ScheduledFuture. Something like this:
```
scheduler.submit(() -> {
            try {
                refreshJob.get();
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            } catch (ExecutionException e) {
                logger.error("ExecutionException", e);
            }
        });
```
But then every binding has to add code like this, which is basically the same extra work to add the catch for RuntimeException in the scheduled task.

I asked a question about this on the eclipse forum: https://www.eclipse.org/forums/index.php?t=msg&th=1089703&goto=1775340&#msg_1775340 Based on the answers I've looking into this and came up with the following possible solution. This adds a wrapper around the `ScheduledThreadPoolExecutor` in `ThreadPoolManager`:
```
private static class WrappedScheduledExecutorService extends ScheduledThreadPoolExecutor {

        public WrappedScheduledExecutorService(int corePoolSize, ThreadFactory threadFactory) {
            super(corePoolSize, threadFactory);
        }

        @Override
        public ScheduledFuture<?> scheduleWithFixedDelay(Runnable command, long initialDelay, long delay,
                TimeUnit unit) {
            return super.scheduleWithFixedDelay(() -> wrap(command), initialDelay, delay, unit);
        }
       
       <some other methods to be wrapped not included here>

        private void wrap(Runnable command) {
            try {
                command.run();
            } catch (RuntimeException e) {
                logger.error("Unexpected Runtime Exception, scheduler stops: ", e);
                throw e;
            }
        }
    }
```
This wrapping is possibly needed on other places as well, but I left that out here.
My question is: Is the wrapping something that is a desired solution? Or are there other solutions/ideas that are preferred? Or would something like the `get()` call be preferred? The latter could be something done in the `BaseThingHandler` were it could keep track of scheduled tasks. That would also make it possible to handle the cancel in `dispose` automatically (because every binding seems to need to implement this at the moment).

**Comment by triller-telekom** [comment]
I agree that "swallowing" `Exceptions` is a problem especially if it silently kills a dedicated thread.

I am just wondering if we should offer an additional `WrappedScheduledExecutorService` or if we should implement the wrapping directly in `ScheduledThreadPoolExecutor`.

If we create the additional wrapper, users can still use the non-wrapped version and forget to catch the `Exception`.

Anyway, I would vote for at least logging the `RuntimeException` to the error log so users have evidence that the thread was killed instead of wondering why their (discovery) job does not return any results.

**Comment by tmrobert8** [comment]
This soooo needs to be done

**Comment by martinvw** [comment]
See also my previous issue: https://github.com/eclipse/smarthome/issues/3325

**Comment by martinvw** [comment]
@sjka @triller-telekom is this now completely resolved or did we revert back to how it was?

**Comment by triller-telekom** [comment]
@martinvw With PR https://github.com/eclipse/smarthome/pull/5045 this is now resolved. `RuntimeException` within schedules tasks are now logged as a warning.

**Comment by triller-telekom** [comment]
@sjka @kaikreuzer Can you please close this issue?
