### ISSUE TITLE
Scheduler in Profiles

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#4544]
For some profile implementations it would make sense to have access to a scheduler (as pointed out in the [forum](https://www.eclipse.org/forums/index.php/t/1089956/)). Therefore it must be exposed somehow to the binding without allowing access to the ThreadPoolManager directly. 

My proposal would be using the `ProfileCallback` class and include something like `ProfileCallback.getScheduler()`.

**Comment by kungfoolfighting** [comment]
I can't really come up with the perfect solution, but even if it makes the Profile interface more complicated, I would much rather inject another parameter than have a callback object provide functionality that is not at all related to callbacks and only marginally related to interacting with the CommunicationManager.
So either the callback is renamed to something else (maybe related to delegate) or we should have another parameter, which I think I slightly prefer.
