### ISSUE TITLE
Basic UI with Edge: change of visibility not dynamically taken into account

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4558]
Using Microsoft Edge, the change of visibility of a sitemap element is not dynamically taken into account. You have to reopen the current page.
Of course, it is working in Firefox or Chrome.

**Comment by lolodomo** [comment]
I can at least confirm that it is not implemented in case of long polling change listener.

**Comment by lolodomo** [comment]
I have the feeling that it should be easy to make widgets visible but less easy to identify the widgets to hide.

**Comment by lolodomo** [comment]
@resetnow: I investigated this issue and finally understood one of the problems.
In long polling mode, we are relying on `dataModelLegacy` which in fact stores only the widgets being attached to an item. Thinking about it, I don't understand why we are keeping `dataModelLegacy` while we could use `dataModel` as we do in the SSE case. It will give a better chance to update the visibility of all widgets and will make the code more common between SSE and long polling.
Was there a valid reason to keep `dataModelLegacy` for long polling HTTP requests ?

**Comment by resetnow** [comment]
If I remember correctly dataModelLegacy binds item IDs to widgets while dataModel uses widget IDs as a key, and back then it wasn't possible to get sitemap-related events. Is it possible now?

**Comment by lolodomo** [comment]
Oh yes, I see, it was impossible before my fix #4820. Now we get in the REST API response widget IDs which are identical to the id used by Basic UI as key in dataModel. So this could now be changed and I think we could forgive dataModelLegacy.
I will study that and propose a PR.

**Comment by lolodomo** [comment]
I was able to suppress dataModelLegacy and make more code common between SSE and long polling.
In the case of Microsoft Edge (long polling), I was able to make widgets becoming visible dynamically but I am still fighting to identify the right widgets to hide dynamically.

**Comment by lolodomo** [comment]
Ok I have now something working well to show/hide dynamically.
To avoid code conflict, I will propose a PR only when my other PR 4810 is merged.
