### ISSUE TITLE
Basic UI should consider browser locale to select the right language

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4561]
Currently the few translated texts are applied using the server locale. The browser locale should rather be used.

I will propose a PR.

**Comment by kaikreuzer** [comment]
Will this end up in a consistent behavior with Paper UI + Classic UI?

As we set the locale on the server, I actually very much prefer to have this one being used - we are not talking about a public webserver here with international users, but about a private setup, where the admins want to make sure they know what languages are being used in the UIs.

If we want to provide the option to use the browser locale, I would rather suggest to introduce this as a configuration parameter of the UI (and we should do this for Paper+Classic+Basic UI at the same time).

**Comment by lolodomo** [comment]
Classic Ui is not yet internationalised.
I think Paper UI is not too ?
At my knowledge, only Basic UI is + the current work on OH dashboard. We discussed about that in the topic for dashboard.
But why not an additional option, I can add it.

**Comment by lolodomo** [comment]
I will not work on Classic UI internationalization myself.
For Paper UI, you previously explained you see no reason to translate what is an admin UI.

**Comment by lolodomo** [comment]
Where do you imagine this new setting ? As I understand, you don't want a Basic UI setting but a global setting for any UI ?
This setting would be labelled something like "use browser language for UI rather than server locale" and be set to false by default.

**Comment by lolodomo** [comment]
And how the UI would get this global setting ?

I would suggest a Basic UI setting to keep things simple.

**Comment by kaikreuzer** [comment]
What texts does "the few translated texts" actually refer to wrt the Basic UI? I am not aware of any texts that are hardcoded in the UI itself...

> As I understand, you don't want a Basic UI setting but a global setting for any UI ?

No, it is ok to have this setting per UI in their existing configuration.

**Comment by lolodomo** [comment]
Perfect, that would be very easy to add.

What I was telling is just that the internationalization of Basic UI was very simple because it only required to translate less than 10 texts. It concerns mainly the page that shows the available sitemaps + the message displayed when the connection to the server is lost.

**Comment by kaikreuzer** [comment]
Ah, ok, thanks for the clarification!

**Comment by lolodomo** [comment]
I close this feature as it looks better in the context of a home automation system to define the language on the server side.
