### ISSUE TITLE
State of zonegroup item contains XML

### ISSUE THREAD

**Issue by aounhaider1** [eclipse/smarthome#4570]
In sonos PLAY:1 the state of zonegroup item contains a large XML. I am just wondering if this is a feature or a bug?
Here is the item:
```xml
{
  "link": "https://192.168.2.154/rest/items/sonos_PLAY3_RINCON_B8E9373719EE01400_zonegroup",
  "state": "<ZoneGroups><ZoneGroup Coordinator=\"RINCON_B8E9373719EE01400\" ID=\"RINCON_B8E9373719EE01400:1928870658\"><ZoneGroupMember UUID=\"RINCON_B8E9373719EE01400\" Location=\"http://192.168.2.152:1400/xml/device_description.xml\" ZoneName=\"Lounge\" Icon=\"x-rincon-roomicon:living\" Configuration=\"1\" SoftwareVersion=\"39.2-47040\" MinCompatibleVersion=\"38.0-00000\" LegacyCompatibleVersion=\"25.0-00000\" BootSeq=\"59\" WirelessMode=\"0\" WirelessLeafOnly=\"0\" HasConfiguredSSID=\"1\" ChannelFreq=\"2437\" BehindWifiExtender=\"0\" WifiEnabled=\"1\" Orientation=\"0\" RoomCalibrationState=\"4\" SecureRegState=\"2\" VoiceState=\"0\"/></ZoneGroup></ZoneGroups>",
  "stateDescription": {
    "pattern": "%s",
    "readOnly": true,
    "options": []
  },
  "type": "String",
  "name": "sonos_PLAY3_RINCON_B8E9373719EE01400_zonegroup",
  "label": "Zone Group",
  "tags": [],
  "groupNames": [
    "sonos_PLAY3_RINCON_B8E9373719EE01400"
  ]
}
```
Screenshot of PaperUI control page:
<img width="804" alt="screen shot 2017-11-16 at 15 52 02" src="https://user-images.githubusercontent.com/5161937/32897509-2446099c-cae6-11e7-86be-ca56095aa317.png">

**Comment by aounhaider1** [comment]
@kgoderis maybe you know about this?

**Comment by kaikreuzer** [comment]
[RTFM](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/README.md#channels): "XML formatted string with the current zonegroup configuration"

The question remains whether this channel is helpful to anyone. I would vote to simply remove it.

**Comment by kaikreuzer** [comment]
@kgoderis Would you be ok to remove this channel or does it really serve any purpose?

**Comment by kgoderis** [comment]
@kaikreuzer I think this channel was added by someone else later on, I have no recollection that I added this one; I only remember that I did a lot of work *not* to have any XML-driven String Items, so as far as I am concerned this one can go.

**Comment by maggu2810** [comment]
It has been already part of the binding as it has been migrated from OH2 to ESH: 9a2fc9cba501faa943f2e4aee3ce30ee67f6f77f

It has been already part of the binding as it has been published in the OH2 addons repo: openhab/openhab2-addons@8ab9c05a2b055ecc71d79f2103fb52f89034cb8d

I don't know at which places it exist in front of the OH2 addons repo.

So, if no one remembers about the use case, I assume we could drop that channel. But as long as this channel is marked as advanced I don't know if it must be removed at all...

**Comment by kaikreuzer** [comment]
> I don't know if it must be removed at all...

If it simply does not make sense, there is no reason to keep it -> #4607

**Comment by lolodomo** [comment]
I don't use this channel and I don't think I added it myself but this channel was maybe used by users in rules to know the group composition.

**Comment by lolodomo** [comment]
Please note that suppressing this channel but keeping the channel zonegroupid makes no real sense.

**Comment by kgoderis** [comment]
@lolodomo on the contrary, it is the only way for Rules to figure out what player is belonging to what group

**Comment by lolodomo** [comment]
Yes, you're right.
