### ISSUE TITLE
openHAB does not update on Firefox and Chrome

### ISSUE THREAD

**Issue by Josar** [eclipse/smarthome#4575]
Setup:
Openhab 2
RPI3 as acces point, to rule out network problems.
Connected with an win10 PC by wifi.

Basic UI:
When i toggle a switch connected to the gpio of the rpi the connected light switches on.
When i have the sitmap opened in MS Edge the item states update. 

Had this issue at the very begining of my openhab experience on the PaperUI which was not very pleasant. I reported it here and was told it an local network problem.
https://github.com/openhab/openhab2-addons/issues/2252

I used firefox which did not update, but wireshark showed some incoming traffic.
After some testing i found MS edge to work and was glad. 
But now others report the same.
https://community.openhab.org/t/update-value-of-item-on-sitemap-automatically/36185
and some digging brought up older reports
https://community.openhab.org/t/icons-no-longer-updating-in-basicui/15199

First i thought it might be some add blockers as it worked with edge, but a clean installed Chrome does also not update.

Is this an known issue? 
Is there a fix for that?
Or at least a workouround?

Microsoft Edge 40.15063.674.0 Microsoft EdgeHTML 15.15063
Google Chrome Version 62.0.3202.94 (Offizieller Build) (64-Bit)
Firefox Version 57.0 (64-Bit)

Further investigations show:
Updates of labels in rules also do not update in edge.  
The update almost instante in the android app.
But only after refresh the changes are displayed in the browser.
The same is with the chrome browser on android, does not update.

**Comment by lolodomo** [comment]
Automatic refresh in Basic UI and Firefox is working well for me.
Are you able to provide a scene using the demo sitemap that trigger the problem ?

**Comment by Josar** [comment]
@lolodomo 

I had installed the new firefox recently and think i did not check if it works with it. But it does Update sometimes. But not for all changing thinks on a sitemap. 
I use the GPIO binding to toggle pins ouf the rpi and shorted two of them. One as contact two as switch.

```
Switch pin1 "State [%s]" {gpio="pin:8 force:yes", autoupdate="true"}
Switch pin2 "State [%s]" {gpio="pin:9 force:yes", autoupdate="true"}
Contact cont1 "State [%s]" {gpio="pin:10"}
```
sitemap testUpdate{
Text item=cont1
Switch item=pin1 
Switch item=pin2 

}


rule "Test Pin high"
  when
     Item pin1 received command ON
  then

  sendCommand(pin2, ON)
  
  cont1.label= "Test a label change"
  logInfo("Test", "TEST Pin ON")
end

rule "Test Pin1 low"
  when
     Item pin received command ON
  then

  sendCommand(pin2, OFF )
  
  // cont.label= "Testing"
  logInfo("Test", "TEST Pin OFF")
end`

**Comment by lolodomo** [comment]
I was not aware that it was possible to update a label with a line such as `cont1.label= "Test a label change"`. Are you sure your rule is valid with such a cmmand ?

At my knowledge, SSE events are sent only when there is a change of an item state. So if the item value is updated, you will have an update in the Basic UI page; but if only the label is updated, I don't think there is an SSE event sent to UI.

Regarding the update of value, did you try suppressing `autoupdate="true"` just to see if your problem is related to that ?

**Comment by Josar** [comment]
I updated my post.
@lolodomo I updated my post. Something went wrong when posting. Copy paste into double quotes did'nt work. Had to use the double tripple qoutes. 

- Its is possible, no error in karaf and label gets updated in smarthome:items list
- The label changes instantly in the app, so there is something which gets sent to the app.
-  I had the cont without autoupdate="true" and the pin2 with. But both did not change in FF.

**Comment by lolodomo** [comment]
You have to check what are the events generated in your server logs.
To check if the problem is really in Basic UI, you should be able to reproduce it just by defining these items:
```
Switch pin1 "State [%s]"
Switch pin2 "State [%s]"
Contact cont1 "State [%s]"
```
and keeping your 2 rules.
What is the result in this case ?

**Comment by sjka** [comment]
> Are you sure your rule is valid with such a command ?

It shouldn't! There are no setters in the [Item-Interface](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/Item.java) by intention and I'd consider it a bug that the rule is valid at all. Don't waste any time investigating this aspect...

**Comment by lolodomo** [comment]
For the refresh of the label, for me that is clearly not something handled by the SSE mechanism. The label will be upodated **only if the value is updated too**.

As a remember, the refresh mechanism in Basic UI is different in Firefox/Chrome and Edge. SSE in not used for Microsoft Edge.

**Comment by lolodomo** [comment]
@sjka: ok with you, I am surprised that this is possible to update the label inside a rule. So we forget this point, remains the update of items pin1 and pin2 that should be ok.

**Comment by Josar** [comment]
> only if the value is updated too.

Updating the state does not trigger an update of the label. but as @sjka said it shouldn't so im OK with that.
But In BasicUI firefox does not update. Which is not so good i think, but probably a feature from ff.

**Comment by lolodomo** [comment]
Refresh is working so we have just to find why it does not work for you. Please try with the updated items, as I proposed. The problem could be in gpio binding.

**Comment by Josar** [comment]
I dont understand your aproach and for what i schould look for.

besides that its not just me, there are a complains from others too.

But one question if edge updates properly then its no problem with the items, neither the sitemap nor the rules and in my understanding also not of any event not getting fired. correct me if i'm wrong.

Are edge and ff handled differently by the server which provides the changes?  If not its something happening in ff. Or i'm wrong here too?

**Comment by lolodomo** [comment]
Yes the changes are provided differently by the server for Edge and Firefox. Firefox is based on SSE events sent by the server; Edge is not.
What you are putting in evidence is a potential issue in the production of SSE events.
What I try to do is to have the simplest example I can reproduce and to be sure that te problem is not relative to a particular binding.
Without the ability to reproduce your case, unfortunately I will be of any use for you.
So please follow my indications:
* please check your logs to see what states are pushed by the gpio binding. Is it ON and OFF states ?
* please check with items deattached from a binding to see if the problem is really inside Basic UI.

**Comment by Josar** [comment]
So i removed all files from rules, items, things and set upd this minimal example.

Karaf log when switching pin 1
``````
 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'test.rules'
 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'pin1' received command ON
 [INFO ] [marthome.event.ItemStateChangedEvent] - pin1 changed from OFF to ON
 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'pin2' received command ON
 [INFO ] [.eclipse.smarthome.model.script.Test] - TEST Pin ON
 [INFO ] [marthome.event.ItemStateChangedEvent] - pin2 changed from OFF to ON
``````
Edge took very long to update pin2, but then very fast everytime. 
Started firefox and Now Firefox updates.

Added the Binding and still both work. 
``````
 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'pin1' received command ON
 [INFO ] [marthome.event.ItemStateChangedEvent] - pin1 changed from OFF to ON
 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'pin2' received command ON
 [INFO ] [.eclipse.smarthome.model.script.Test] - TEST Pin ON
 [INFO ] [marthome.event.ItemStateChangedEvent] - pin2 changed from OFF to ON
 [INFO ] [marthome.event.ItemStateChangedEvent] - cont1 changed from CLOSED to OPEN
``````

So it seems that another sitemap, items, rules configuration is the cullprit. So maybe generating the SSE events where disturb by something.

I will have a look into that but this will take some time. 

Thank you very much for the detailed explanation.

**Comment by lolodomo** [comment]
Note that I will not be surprised if Basic UI requires a refresh after an update of the config files.

**Comment by Josar** [comment]
I just freshly set up the rpi. And made my example to work again and it seems when i add the gpio then it starts to get buggy.

When i just use the two items and press the button on the sitemap everything works, very occasionally a update of led_p1 fails.
As soon as i add the gpio for led_p1no update of led_p1 in FF. The switch toogles but state and icon of button_p1 don't not change and also led_p1 does not change.
```
Switch led_p1 "Output [%s]"  {gpio="pin:9 force:yes"}
Switch button_p1 "Input [%s]" // {gpio="pin:10"}
```
```
sitemap test label="Test" {
 Frame {
  Switch item=led_p1 icon="light"
  Switch item=button_p1
 }
}
```
```
rule "Button 1 ON"
  when
     Item button_p1 received command ON
  then
       led_p1.sendCommand(ON);
       logInfo("Button Pressed", "State is:" + button_p1.state )
end
rule "Button 1 OFF"
  when
     Item button_p1 received command OFF
  then
       led_p1.sendCommand(OFF);
       logInfo("Button Pressed", "State is:" + button_p1.state )
end
```

Now i change the button_p1 to be a contact.
```

**Comment by kaikreuzer** [comment]
@Josar I think your examples are far too complex for being properly understood or investigated.

If you claim that there is an issue for Firefox getting updates, best use the demo.sitemap and demo.items files and say which state update you are triggering, which you expect to be shown in the browser. You can send state updates on the console simply by `smarthome:update <itemname> <state>`.

**Comment by lolodomo** [comment]
Some users are complaining that refresh is not working after an update of config files. Please restart OH after any update of your files to see if you are not in this case.

**Comment by sjka** [comment]
> Some users are complaining that refresh is not working after an update of config files. 

@lolodomo is there an issue for _that_?

**Comment by lolodomo** [comment]
I think there is not.
Note that I can't reproduce myself this possible issue.

**Comment by lolodomo** [comment]
I was finally able to reproduce yesterday while I updated several times the demo sitemap file, one time the refresh through SSE was not working anymore. Clearing the browser cache did not help. Restarting Firefox did not help too. Only restarting the server allowed making the refresh working again.
I was working on another problem. I will try to investigate later. My feeling is that in my dev env, it really does not occur often.

**Comment by lolodomo** [comment]
I tried to reproduce again but without success. After around 20 saves of my demo sitemap, the live update is still working. I even try to break the sitemap (invalid syntax) and then fix it. The live update is restarted.
It should happen only in very specific conditions I was not able to identify.

**Comment by Josar** [comment]
https://community.openhab.org/t/icons-no-longer-updating-in-basicui/15199/28
https://community.openhab.org/t/text-or-number-automatically-update-ui/40004

**Comment by kaikreuzer** [comment]
FTR: Testing a recent snapshot on a RaspPi this week, I also had many issues with lost state changes in the Basic UI with Chrome. Didn't dive into any deeper investigation, but it felt rather unreliable...

**Comment by lolodomo** [comment]
In case the problem is that SSE is or becomes unreliable, I could add an option in Basic UI to disable SSE usage. With my recent changes, the long polling mode is more reliable than before.

**Comment by kaikreuzer** [comment]
I haven't heard any recent complains and as @lolodomo cannot reproduce it, I suggest to close this issue.

Feel free to re-open, if there is a reproducible situation of a such a bug.

**Comment by stefan-muc** [comment]
Here an user in community provides a hopefully reproducible situation: https://community.openhab.org/t/basic-ui-live-update/39514/22
Does that help?
