### ISSUE TITLE
PaperUI: Sort options time zone dropdown alphabetically

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#4588]
We have the new dropdown for selecting the `Time Zone` in `Configuration > System > Reginal Settings`. It was very hard for me to find my local time zone in the dropdown. Is it possible to sort this list alphabetically?

![bildschirmfoto vom 2017-11-19 10-43-33](https://user-images.githubusercontent.com/5131747/32989460-c2b355c6-cd16-11e7-91d3-2bbbbf1979a9.png)

**Comment by mherwege** [comment]
Could it not be sorted by time offset? I believe that’s the way it is sorted when selecting a timezone in most calendars.

**Comment by kaikreuzer** [comment]
I am also for sorting by offset!

**Comment by kaikreuzer** [comment]
This probably makes it difficult for the Paper UI to do, so I think it is better to already deliver a correctly sorted list from the server side.

**Comment by cweitkamp** [comment]
Agreed. Sorting by time offset is the usual way. That would help as good as sorting alphabetically.
