### ISSUE TITLE
Tradfri Handler Lifecycle

### ISSUE THREAD

**Issue by ivivanov-bg** [eclipse/smarthome#4631]
https://github.com/eclipse/smarthome/blob/7e1e42c32ee7189c9c68064611aac4a276fddec7/extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java#L124

Any particular reason for setting the status to UNKNOWN (beside for the LightHandlerTest) 
This status basically breaks the proper lifecycle handling because it allows the Light Handler to start initializing BEFORE the gateway is initialized which may cause the following two calls to return null:
https://github.com/eclipse/smarthome/blob/7e1e42c32ee7189c9c68064611aac4a276fddec7/extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriThingHandler.java#L63
https://github.com/eclipse/smarthome/blob/7e1e42c32ee7189c9c68064611aac4a276fddec7/extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriThingHandler.java#L67

**Comment by cweitkamp** [comment]
I guess this is related to the issue mentioned in #4587.

**Comment by ivivanov-bg** [comment]
I even think - this is the cause for the issue mentioned in #4587.
If the status is not set to unknown - then it remains 'INITIALIZING' and the Light Handler is not initialized while the gateway status is such.

The only valid reason for the UNKNOWN status I see is for the light handler osgi test to pass:
https://github.com/eclipse/smarthome/blob/7e1e42c32ee7189c9c68064611aac4a276fddec7/extensions/binding/org.eclipse.smarthome.binding.tradfri.test/src/test/java/org/eclipse/smarthome/binding/tradfri/TradfriHandlerTest.java#L95
