### ISSUE TITLE
Develop New UI WebsocketServlet with ClassNotFoundException for WebSocketServletFactory

### ISSUE THREAD

**Issue by lsafelix75** [eclipse/smarthome#4640]
Hi,

I am trying to develop a Websocket Servlet UI plugin by registering the newly developed servlet to httpservice. However, I am not able to get it work and always getting ClassNotFoundException for WebSocketServletFactory though i already manually add its .jar file into classpath (because it doesn't come with ESH repo). I am wondering whether there are experts who can share some lights on how to resolve this. Thanks.

**Comment by maggu2810** [comment]
How do you test?
At which state you get the `ClassNotFoundException`?
The service `org.eclipse.jetty.websocket.servlet.WebSocketServletFactory` is provided by "Jetty :: Websocket :: Server"

**Comment by maggu2810** [comment]
See e.g. the "Provide-Capability" section of its manifest:

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven Bundle Plugin
Built-By: joakim
Build-Jdk: 1.8.0_74
Implementation-Vendor: Eclipse.org - Jetty
Implementation-Version: 9.3.15.v20161220
url: http://www.eclipse.org/jetty
Bnd-LastModified: 1482263232439
Bundle-Classpath: .
Bundle-Copyright: Copyright (c) 2008-2016 Mort Bay Consulting Pty. Ltd.
Bundle-Description: Jetty module for Jetty :: Websocket :: Server
Bundle-DocURL: http://www.eclipse.org/jetty
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0, http://www
 .eclipse.org/org/documents/epl-v10.php
Bundle-ManifestVersion: 2
Bundle-Name: Jetty :: Websocket :: Server
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Bundle-SymbolicName: org.eclipse.jetty.websocket.server
Bundle-Vendor: Eclipse Jetty Project
Bundle-Version: 9.3.15.v20161220
Export-Package: org.eclipse.jetty.websocket.server;version="9.3.15";us
 es:="javax.servlet,javax.servlet.http,org.eclipse.jetty.http.pathmap,
 org.eclipse.jetty.io,org.eclipse.jetty.server,org.eclipse.jetty.serve
 r.handler,org.eclipse.jetty.servlet,org.eclipse.jetty.util,org.eclips
 e.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.
 jetty.util.ssl,org.eclipse.jetty.util.thread,org.eclipse.jetty.websoc
 ket.api,org.eclipse.jetty.websocket.api.extensions,org.eclipse.jetty.
 websocket.common,org.eclipse.jetty.websocket.common.events,org.eclips
 e.jetty.websocket.common.io,org.eclipse.jetty.websocket.common.scopes
 ,org.eclipse.jetty.websocket.server.pathmap,org.eclipse.jetty.websock
 et.servlet",org.eclipse.jetty.websocket.server.pathmap;version="9.3.15"
Import-Package: javax.servlet;version="[2.6.0,3.2)",javax.servlet.http
 ;version="[2.6.0,3.2)",org.eclipse.jetty.http;version="[9.3.15,9.3.16
 )",org.eclipse.jetty.http.pathmap;version="[9.3.15,9.3.16)",org.eclip
 se.jetty.io;version="[9.3.15,9.3.16)",org.eclipse.jetty.server;versio
 n="[9.3.15,9.3.16)",org.eclipse.jetty.server.handler;version="[9.3.15
 ,9.3.16)",org.eclipse.jetty.servlet;version="[9.3.15,9.3.16)",org.ecl
 ipse.jetty.util;version="[9.3.15,9.3.16)",org.eclipse.jetty.util.anno
 tation;version="[9.3.15,9.3.16)",org.eclipse.jetty.util.component;ver
 sion="[9.3.15,9.3.16)",org.eclipse.jetty.util.log;version="[9.3.15,9.
 3.16)",org.eclipse.jetty.util.ssl;version="[9.3.15,9.3.16)",org.eclip
 se.jetty.util.thread;version="[9.3.15,9.3.16)",org.eclipse.jetty.webs
 ocket.api;version="[9.3.15,9.3.16)",org.eclipse.jetty.websocket.api.e
 xtensions;version="[9.3.15,9.3.16)",org.eclipse.jetty.websocket.api.u
 til;version="[9.3.15,9.3.16)",org.eclipse.jetty.websocket.common;vers
 ion="[9.3.15,9.3.16)",org.eclipse.jetty.websocket.common.events;versi
 on="[9.3.15,9.3.16)",org.eclipse.jetty.websocket.common.extensions;ve
 rsion="[9.3.15,9.3.16)",org.eclipse.jetty.websocket.common.io;version
 ="[9.3.15,9.3.16)",org.eclipse.jetty.websocket.common.scopes;version=
 "[9.3.15,9.3.16)",org.eclipse.jetty.websocket.servlet;version="[9.3.1
 5,9.3.16)"
Originally-Created-By: Apache Maven Bundle Plugin
Provide-Capability: osgi.serviceloader;osgi.serviceloader="org.eclipse
 .jetty.websocket.servlet.WebSocketServletFactory"
Require-Capability: osgi.extender;filter:="(osgi.extender=osgi.service
 loader.registrar)",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-2.4.1.201501161923
```

**Comment by lsafelix75** [comment]
@maggu2810  thanks for the feedback. Following is my manifest. jetty.websocket.servlet isn't part of ESH/OpenHAB repo, hence i had to download a compatible version and include it and several others in my classpath.

The the error was thrown when i run the following code, especially on " httpService.registerServlet()" which threw ClassNotFoundException error.
```

            initParams.put(PROXY_DEST_URL, "http://192.168.0.111:1880/");
            initParams.put(PROXY_PREFIX, "/test/");
            initParams.put("maxThreads", "100");

            // Store the current CCL
            ClassLoader ccl = Thread.currentThread().getContextClassLoader();

            bundleContext = FrameworkUtil.getBundle(this.getClass()).getBundleContext();
            // Bundle bundle = bundleContext.getBundle();
            Bundle bundle = findJettyBundle(bundleContext); //this refer to bundle "org.eclipse.jetty.http"
            BundleWiring bundleWiring = bundle.adapt(BundleWiring.class);
            ClassLoader classLoader = bundleWiring.getClassLoader();
            Thread.currentThread().setContextClassLoader(classLoader);

            httpService.registerServlet(TESTUI_ALIAS, new WebSocketProxyServlet(), initParams, null);

            // Restore the classloader
            Thread.currentThread().setContextClassLoader(ccl);


```
Manifest-Version: 1.0
Bundle-ActivationPolicy: lazy
Bundle-ClassPath: .,
 lib/tyrus-client-1.13.1.jar,
 lib/tyrus-core-1.13.1.jar,
 lib/websocket-server-9.3.14.v20161028.jar,
 lib/websocket-servlet-9.3.14.v20161028.jar,
 lib/javax.websocket-api-1.1.jar
Bundle-ManifestVersion: 2
Bundle-Name: TestUI Binding
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Bundle-SymbolicName: org.openhab.binding.testui;singleton:=true
Bundle-Vendor: openHAB
Bundle-Version: 2.2.0.qualifier
Export-Package: 
 org.openhab.binding.testui,
 org.openhab.binding.testui.handler
Import-Package: 
 com.fasterxml.jackson.annotation;version="2.4.5",
 javax.servlet,
 javax.servlet.http,
 javax.ws.rs,
 javax.ws.rs.core,
 org.apache.commons.codec.binary;version="1.9.0",
 org.apache.commons.httpclient;version="3.1.0",
 org.eclipse.jetty.client;version="9.3.14",
 org.eclipse.jetty.client.api;version="9.3.14",
 org.eclipse.jetty.client.util;version="9.3.14",
 org.eclipse.jetty.proxy;version="9.3.14",
 org.eclipse.jetty.server;version="9.3.14",
 org.eclipse.jetty.server.handler;version="9.3.14",
 org.eclipse.jetty.servlet;version="9.3.14",
 org.eclipse.jetty.util;version="9.3.14",
 org.eclipse.jetty.websocket.api;version="9.3.14",
 org.eclipse.jetty.websocket.client;version="9.3.14",
 org.eclipse.jetty.websocket.common.scopes;version="9.3.14",
 org.eclipse.smarthome.config.core,
 org.eclipse.smarthome.core.library.types,
 org.eclipse.smarthome.core.thing,
 org.eclipse.smarthome.core.thing.binding,
 org.eclipse.smarthome.core.thing.binding.builder,
 org.eclipse.smarthome.core.thing.type,
 org.eclipse.smarthome.core.types,
 org.openhab.binding.testui,
 org.openhab.binding.testui.handler,
 org.openhab.core,
 org.openhab.ui.dashboard,
 org.osgi.framework,
 org.osgi.framework.wiring;version="1.2.0",
 org.osgi.service.component,
 org.osgi.service.component.annotations;resolution:=optional,
 org.osgi.service.http,
 org.slf4j
Service-Component: OSGI-INF/*.xml
Require-Bundle: org.eclipse.jetty.util

**Comment by maggu2810** [comment]
I didn't really understand what you want to do in your example. Why you change the classloader etc.
I also don't understand how this is related to the Eclipse SmartHome framework.
It seems to be more related to general usage of WebSocket related stuff in an Jetty based OSGi environment.
But this is not the correct place, as there is no issue in ESH.

**Comment by lsafelix75** [comment]
@maggu2810  i am trying to create a UI plugin for Node-Red which can be served remotely. Unfortunately, it uses WebSocket and hence i need to create websocketservlet on myopenhab bundle. This is essential (to me) as PaperUI's scheduler does not look really ready yet.

**Comment by kaikreuzer** [comment]
Afaics, this is not a bug report, but rather a support request, so I am closing it due to inactivity.
