### ISSUE TITLE
mDNS discovery always considers all thing types supporting mDNS discovery

### ISSUE THREAD

**Issue by hsudbrock** [eclipse/smarthome#4644]
**Context**
The method `o.e.sh.config.discovery.DiscoveryServiceRegistry#startScan(thingTypeUID, scanListener)` starts a discovery based on a specific thing type. Running this method will not discover results for that thing type only. Instead, running this method starts a discovery using all discovery services that support that thing type (but possibly also many other thing types).

Example: If a thing can be discovered using mDNS, starting the discovery for that thing type will start a mDNS discovery, which will discover all things discoverable via mDNS.

**Issue**
The behavior described above matches the JavaDoc of the `startScan` method ('the Thing type UID pointing to collection of discovery services to be forced to start a discovery`). However, this behavior leads to rather lengthy discovery in the case of mDNS.

For mDNS discovery (cf. `o.e.sh.config.discovery.mdns.internal.MDNSDiscoveryService`) an mDNS scan is done sequentially for each `o.e.sh.config.discovery.mdns.DiscoveryParticipant`, each taking 6 seconds (the default timeout of the jmDNS library). If there are many bindings supporting mDNS discovery, each providing a `DiscoveryParticipant`, the scan takes rather long.

**Potential improvement**
I suggest to improve this, e.g., by allowing to start a scan for one (or a list of) thing type(s) that does not trigger scans for other thing types as a side effect, as is currently the case for the mDNS discovery (or, as another example, upnp discovery). For mDNS discovery, this would mean that the `MDNSDiscoveryService` could filter the set of `DiscoveryParticipant`s by thing type, only starting those `DiscoveryParticipant`s that support the requested thing type.

Is this a sensible improvement, or do I overlook something here? I would be happy about feedback.

**Side note**
For mDNS, the discovery timeout is currently 5 seconds, while the timeout for one jMDNS lookup is 6 seconds. I.e., even if there is only one `DiscoveryParticipant`, the discovery might take longer than the 5 seconds timeout. Should this be improved in the mDNS discovery as well, by aligning the timeout of the mDNS discovery to 6 seconds?

**Comment by kaikreuzer** [comment]
Sounds all sensible. I actually wasn't aware that the `JmDNS.list` method actually triggers a network scan and not only returns the results from its own cache. It also is weird that only a single service type can be requested, otherwise I would have said that we should simply provide the list of all services we are interested in.

**Comment by afuechsel** [comment]
This applies also to jupnp discovery
