### ISSUE TITLE
JSR223 rules with timers break after the first execution

### ISSUE THREAD

**Issue by philippwaller** [eclipse/smarthome#4651]
With the current build, I noticed that JS223 rules with timers breaks after the first execution. The issue appears only on newer builds and is reproducible with the following code:

    from threading import Timer
    scriptExtension.importPreset("RuleSupport")
    scriptExtension.importPreset("RuleSimple")

    class MyTimerRule(SimpleRule):
        def __init__(self):
            self.triggers = [
                Trigger("MyTrigger", "core.ItemStateUpdateTrigger",
                        Configuration({"itemName": "LR_Switch_PressShort"}))
            ]

        def execute(self, module, input):
            def callback():
                return
            Timer(2, callback).start()

    automationManager.addRule(MyTimerRule())

Please find attached the relevant log entries. 

**[FAILED] OpenHAB 2.2 Snapshot Build 1099 (ESH 0.9.0.201711242229)**
    
    29-Nov-2017 18:53:10.478 [DEBUG] [ipse.smarthome.automation.core.internal.RuleEngine] - The trigger 'MyTrigger' of rule '8a742e1c-3e87-455d-acce-78129e226819' is triggered.
    29-Nov-2017 18:53:10.480 [DEBUG] [ipse.smarthome.automation.core.internal.RuleEngine] - The rule '8a742e1c-3e87-455d-acce-78129e226819' is executed.
    29-Nov-2017 18:53:15.632 [DEBUG] [ipse.smarthome.automation.core.internal.RuleEngine] - The trigger 'MyTrigger' of rule '8a742e1c-3e87-455d-acce-78129e226819' is triggered.
    29-Nov-2017 18:53:15.642 [ERROR] [ipse.smarthome.automation.core.internal.RuleEngine] - Failed to execute rule '8a742e1c-3e87-455d-acce-78129e226819': Fail to execute action: 1

**[WORKING] OpenHAB 2.1 Stable (ESH 0.9.0.b5)**
    
    2017-11-29 18:42:38,989 [DEBUG] [org.eclipse.smarthome.automation.core.internal.RuleEngine] - The trigger 'MyTrigger' of rule 'rule_1‘ is triggered.
    2017-11-29 18:42:38,991 [DEBUG] [org.eclipse.smarthome.automation.core.internal.RuleEngine] - The rule 'rule_1‘ is executed.
    2017-11-29 18:42:41,001 [DEBUG] [org.eclipse.smarthome.automation.core.internal.RuleEngine] - The trigger 'MyTrigger' of rule 'rule_1‘ is triggered.
    2017-11-29 18:42:41,004 [DEBUG] [org.eclipse.smarthome.automation.core.internal.RuleEngine] - The rule 'rule_1‘ is executed.

**Comment by smerschjohann** [comment]
I cannot reproduce with latest 2.2.0 release. Can you try again with the latest version?
