### ISSUE TITLE
Sitemap REST API: 30 seconds timeout

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4668]
I discovered that the sitemap REST API has a feature to block the request until a change in the page occurs but there is also a timeout of 30 seconds (in the method `waitForChanges`). When the timeout is reached, the page data is returned even without any data change.

https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java#L217

This is a problem in the Android app for example because the page is reloaded every 30 seconds even when nothing is changed: https://github.com/openhab/openhab.android/issues/460

I see 2 ways to fix that:

1. disable the timeout in the REST API
2. keep the timeout but add a flag in the response to notify the caller when the timeout was reached

WDYT ?

**Comment by kaikreuzer** [comment]
This is for long-polling and such "normal" requests have to time-out, so (1) is imho not an option. For having a lasting connection, the Android app should be refactored to use SSE, which is the right mechanism for that.

As a quick solution (2) sounds acceptible to me - the app would then only have to check for this flag and avoid any page refresh. This would be a breaking change, though, so we should carefully check if anybody else might be impacted by it.

**Comment by lolodomo** [comment]
Moving to SSE is certainly a big work. I could have a try but only in the future (2018).

Another option for a quick fix could be a special HTTP code to notify the timeout ?

**Comment by lolodomo** [comment]
Note that the servlet for the Classic UI is handling such timeout: https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.classic/src/main/java/org/eclipse/smarthome/ui/classic/internal/servlet/WebAppServlet.java#L162
It returns a specifc XML.

**Comment by lolodomo** [comment]
If we want to avoid any break, we could add an optional parameter to the API. Any app using the API without this parameter will have an unchanged behaviour. Only the app using this new parameter could have the new behaviour.

**Comment by lolodomo** [comment]
Finally the easiest solution would be to return an empty response when the timeout expired. This will be correctly handled by the Android app without any change. Like that, you need no new field.
