### ISSUE TITLE
Sitemap SSE: item state vs widget state

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4670]
As I explained in the issue #4445, there is something that should be fixed in the SSE events the server is producing. The SSE event includes data for the linked item and in particular its state. But in fact, this state is overwritten by a state adjusted to the widget type. It is done at this line: https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java#L204
As a result, the UI caller has no information on the real item state but only the widget state.
This conversion is helpful because the UI like Basic UI has not to implement this conversion logic.

I think it will be better to distinguish in the SSE event the real item state from the computed widget state. That is why I propose to add a new field that will contain the computed widget state, leaving the item state with its real state.
This change will probably break any app using SSE. As an example, a littke change will be required in the Basic UI to use the right field in the JavaScript file.

The only difficulty is that I would like to avoid duplicating big data. This can only happen with image items. I don't want to duplicate the image raw data in the SSE event.

WDYT ?

**Comment by lolodomo** [comment]
The new field will be available in the sitemap REST API too. In this case, this would be a new information not yet available. Any REST consumer can use it or ignore it. So this will break nothing in this case.

**Comment by lolodomo** [comment]
The new field would be added in the class SitemapWidgetEvent.

**Comment by lolodomo** [comment]
Maybe a concrete example could help to understanding what I am talking about.
Today for a Switch widget linked to a Dimmer item, the state in the SSE event is ON when the item state is in fact 80. The change I propose would be to have in the SSE event the item state set to 80 and a new widget state set to ON.

**Comment by maggu2810** [comment]
I am not sure if I understand your exmaple correctly:
* switch widget
* dimmer item

The UI sends a command triggered by the "switch widget" to the "dimmer item". The commands could be "ON" or "OFF" (because of the switch widget).
The command will be delegated to the profile handling and the thing handler and the thing handler could send a state update to the channel that will result in an update for the item.
So, the thing handler could send a state update to 100% or 80% or whatever (e.g. the last non 0% dimm-state the device has used) it does if receives an ON from the UI.
Isn't the event in the SSE connection then exactle the state that has been created by the handler?


I have to admit that I don't know much about the widget / UI stuff.
I don't think we should add widget information to SSE.
An item could be added to several widgets on several sitemaps or UIs. Should we include every possible / used widget state for an item?
IMHO The SSE should not include such UI specific parts.

**Comment by lolodomo** [comment]
An SSE event is attached to a sitemap widget. When an item is updated, the server builds an SSE event and broadcasts it to all subscribers. This SSE event contains information about the updated item and in particular its state. But as I explained, this is not really the item state but a state converted to the widget type. So if your item is updated from 50 to 70, the SSE event pushed to subscribers will in fact contain ON rather than 70 because the widget is a switch.
So we are saying the same thing, I think the SSE should contain the real item state. But at the same time, the current conversion is very helpful for the UIs. As an example, the Basic UI is using this converted state to directly update the widget. If we just replace the converted state by the real state, Basic UI will have to implement the conversion logic in its JavaScript. That's why I think we should have in fact the two states in the SSE event.

**Comment by maggu2810** [comment]
Hm, I am using the REST interface and SSE without any sitemap or widgets.
What do I need to do to see a widget state on SSE?
I will try to reproduce.

**Comment by maggu2810** [comment]
Are you sure, that you don't see the state that is produced by the auto-update mechanism?

**Comment by lolodomo** [comment]
I am talking specifically about the sitemap SSE and so about widgets updates.
And I am sure about the converted state, I have pointed the code that is doing this conversion.

**Comment by maggu2810** [comment]
Ah, okay, I did not know that SSE is also in use for sitemap.
Which is the URL the event stream could be accessed?

I only know about the `/rest/events` one that is implemented here: https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sse/src/main/java/org/eclipse/smarthome/io/rest/sse/SseResource.java

**Comment by lolodomo** [comment]
`/rest/sitemaps/events/subscribe` to subscribe and then `/sitemaps/events/{subscriptionid}`

**Comment by lolodomo** [comment]
Ok, I need now a fix to this issue to implement SSE in the Android app. So I will propose the fix.

To avoid duplicating the item state in the message, I will set the new state field to `#item.state#` when the widget state is simply the (raw) item state.
