### ISSUE TITLE
Document how to use null annotations with classes that implement unannotated interfaces

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#4693]
After reading the [Code Style Guidelines](https://www.eclipse.org/smarthome/documentation/development/guidelines.html#a-code-style), [Blog](https://www.eclipse.org/smarthome/blog/2017/11/30/nullannotations.html) and adding some null annotations to projects I now notice it becomes difficult to use null annotations with classes that implement unannotated interfaces.

For example when adding `@NonNullByDefault` to the HarmonyHubHandlerFactory I could not manage to get the compiler happy about the implementation of the methods of the unannotated ChannelTypeProvider  interface.

Is this simply not possible or are there some tricks that can get it to work? It would be helpful if the documentation makes notion of this.

**Comment by triller-telekom** [comment]
@wborn Our null annotations are still work in progress. We try to split the adding of new annotations into small portions (PRs) that can easily be reviewed by others. For now we only have a few core packages annotated.

So if you are struggling with the not yet annotated `ChannelTypeProvider`, how about adding some null annotations and proposing a PR by yourself? ;-) Your help would be greatly appreciated! But please create a separate PR for that and try to keep  as little other classes affected as possible, i.e. stop annotating once the `ChannelTypeProvider` has its annotations and the build is happy without any errors ;)

**Comment by triller-telekom** [comment]
Thanks to @sjka we have annotations on the `ChannelTypeProvider` since this PR: https://github.com/eclipse/smarthome/pull/4735/files#diff-40a2a4edcb30dc026e81c7ab59f420adR28

@wborn Does that solve your problem so this issue can be closed?

**Comment by wborn** [comment]
Thanks @sjka ! This solves the issue :+1:
