### ISSUE TITLE
Multiple AND or OR operators in Eclipse smarthome rules using rule REST API

### ISSUE THREAD

**Issue by dushanlk** [eclipse/smarthome#4694]
I already know how to create a rule with only one condition.

```
"conditions": [
        {
            "id": "7",
            "label": "Test rule",
            "description": "This triggers the rule if an item state has changed.",
            "configuration": {
            "itemName": "sensor_luminance_TUID_zwave_device_octopuszstick1_node12",
            "state": "48",
            "operator": "="
            },
            "type": "core.ItemStateCondition"
        }
    ]
```

But I have a requirement to create rules with multiple OR or AND operators. Ex:

```
Example 01 

If( X AND Y AND Z ) {
       DO THIS
 }

Example 02

 If ((X AND Y) OR Z) {
       DO THIS
 }
```

Is this possible with Rule REST API?

**Comment by maggu2810** [comment]
@adimova Can you help?

**Comment by dushanlk** [comment]
Guys,

I posted this in Eclipse community forum and got the answer.
https://www.eclipse.org/forums/index.php?t=msg&th=1090481&goto=1778152&#msg_1778152

> 
> Hi Dushan,
> 
> a rule can have a list of triggers and can be started by any of the triggers in this list. As for the conditions, a rule will execute its action(s) only if all given conditions match. For more information start on the JavaDoc for the Rule class.
> 
> Hope that helps. Cheers,
> Henning

Hope this will help somebody in future.

Regards,
Dushan
