### ISSUE TITLE
OSGiEventManager: prevent timeouts

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#4697]
WRT: openhab/openhab-distro#600

What do you thin about chaning the implementation of the `OSGiEventManager` a little bit?

Proposal of the changes:
* add a blocking queue of `org.osgi.service.event.Event` to the member variables
* the activate method starts a thread that reads the elements from the queue
* the deactivate method stops the thread started by the activate method
* the reader thread reads elements from the blocking queue and handles it as it is done at the moment in the `handleEvent(org.osgi.service.event.Event osgiEvent)` method
* the `handleEvent(org.osgi.service.event.Event osgiEvent)` method that is called be the `EventAdmin` adds the `Event` to the blocking queue

With this approach we can consume the events as fast as possible and return the control to the event admin.
So we don't need to change the global "blocking event handler" handling and keep the blacklisting as set default.

**Comment by sjka** [comment]
Might be worth a try - especially to see if that _still_ would cause timeouts 😉

**Comment by kaikreuzer** [comment]
I think the most important part on that would be that we should refrain from doing any logging inbetween 😎

**Comment by maggu2810** [comment]
So, I assign this issue to me and will try to implement that change.
