### ISSUE TITLE
[Astro] Only one autodiscovered astro item could be added

### ISSUE THREAD

**Issue by NorbertHD** [eclipse/smarthome#4710]
Build is 1119, "Item Linking" is "Simple Mode", PaperUI.

When adding one autodiscovered astro item (eg. Local Sun) both  items (Sun and Moon) disappear in Inbox, and only "Local Sun" is added to Control. A new Inbox Scan doesn't find the remaining item.
Only manual adding is possible.

A few builds early both items where added to Control when adding one item. And a few builds before that the selected item was added to control and the other  remains in inbox and can then be added..

**Comment by kaikreuzer** [comment]
Thanks for the report - I can confirm the issue and will look into it.

**Comment by kaikreuzer** [comment]
Fixed by #4731.
