### ISSUE TITLE
Cannot refer to the non-final variable <someVar> inside a lambda expression

### ISSUE THREAD

**Issue by jewesta** [eclipse/smarthome#4711]
Hi.

As I've been [made aware](https://github.com/openhab/openhab-distro/issues/604) my issue is not directly related to openHAB but rather the eclipse smarthome project on which openHAB is based. So I'll report it here.

I believe many people using lambdas in openHAB will stumble across this eventually. There are a few forum discussions concerning this compiler error message, e.g. [this one](https://community.openhab.org/t/cannot-refer-to-the-non-final-variable-i-inside-a-lambda-expression/27506).

There are two workarounds. The first one is to ignore the error because the code clearly works and I do not see why it shouldn't. It's in the nature of lambdas that they can access the enclosing scope. The second one is to make the var global. Solution 1 is annoying, solution 2 forces users to adopt an inelegant coding style.

Initially I thought that this was a limitation of openHAB Designer (as suggested by the forum discussion I mentioned). But now that Designer is (de facto) deprecated and the combination VS Code + LSP shows the same symptoms I thought I'd create this issue.

Here's a simple openHAB example just for the purpose of reproducing the bug.

```php
import java.util.List
import java.util.Arrays

rule "test"
when
	System started
then
	var int index = 0
	val List<String> strings = Arrays.asList("a", "b", "c")
	strings.forEach[entry |
		// Cannot refer to the non-final variable index inside a lambda expression
		index++
		logInfo("test", "Entry #" + index + " = " + entry)
	]
end
```

The output to the openHAB log file:

```
2017-12-10 10:38:16.932 [INFO ] [.eclipse.smarthome.model.script.test] - Entry #1 = a
2017-12-10 10:38:16.938 [INFO ] [.eclipse.smarthome.model.script.test] - Entry #2 = b
2017-12-10 10:38:16.943 [INFO ] [.eclipse.smarthome.model.script.test] - Entry #3 = c
```

Thanks for considering! :-)

**Comment by htreu** [comment]
Hi @jewesta,

can you please also post the error message you get? The output you posted above is exactly what I would expect the rule to produce. I also can reproduce it in my ESH environment but get no error when the rule is parsed.

**Comment by jewesta** [comment]
Hi @htreu,

first of all my apologies for the late reply. And thank you very much for taking the time to look into this.

What happens in my setup is that Visual Studio Code marks the var "index" inside the lambda as an error (red underline). When hovering over the error, the popup text reads "Cannot refer to the non-final variable index inside a lambda expression".

<img width="633" alt="screenshot" src="https://user-images.githubusercontent.com/25198212/35187873-dbbee3dc-fe2b-11e7-93d9-2b17fa3c3c66.png">

**Comment by sjka** [comment]
This limitation is actually something that Xbase & Xtend inherit from Java and is nothing we can influence, neither in VSCode nor in Eclipse SmartHome. 

You can't do something like this in Java and would get a "Local variable index defined in an enclosing scope must be final or effectively final" compiler error. Xtext jumps some hoops to make it work nevertheless in the Xbase interpreter, but it actually this is highly discouraged that's why they issue this error. 

By the way, did you know that for your example there exists a "proper" way? There is a "secret" second parameter to the lambda, which already contains the index:

```xtend
val List<String> strings = Arrays.asList("a", "b", "c")
strings.forEach[entry, index |
	// Cannot refer to the non-final variable index inside a lambda expression
	logInfo("test", "Entry #" + index + " = " + entry)
]
```

(see e.g. https://www.eclipse.org/xtend/documentation/203_xtend_expressions.html)

**Comment by jewesta** [comment]
Thanks a lot for the clarification. I bookmarked the link to the Xtend doc, which is very helpful.
