### ISSUE TITLE
LSP ModelServer: potential Denial of service

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#4723]
As I reviewed #4722 I identified this line in the code: https://github.com/kaikreuzer/smarthome/blob/d893a85/bundles/model/org.eclipse.smarthome.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/ModelServer.java#L81

Do we really want to create a new thread for every incoming connection?
If I run a loop that opens a connection to that port and tries to keep the socket open then for every loop a new thread is started on the server.
Why don't we use a thread pool?

**Comment by sjka** [comment]
Very good question, indeed. We should!
