### ISSUE TITLE
MqttBrokerConnection.removeConsumer() is not removing the consumer

### ISSUE THREAD

**Issue by tobof** [eclipse/smarthome#4739]
I'm facing a problem while using org.eclipse.smarthome.io.transport.mqtt.

If I use addConsumer with a subscriber using the topic "+/+/+/+/+/+" and later on try to remove the same subscriber, the subscriber is not really removed from the list of consumers in MqttBrokerConnection.

In addConsumer() there is a conversion of the topic:
`String topic = StringUtils.replace(StringUtils.replace(subscriber.getTopic(), "+", "[^/]*"), "#", ".*");`

And later on `topic` is used, while in removeConsumer `subscriber.getTopic()` is used.

If the above conversion is added to removeConsumer() it seems to fix the problem.

**Comment by triller-telekom** [comment]
Thanks for reporting this issue. Indeed there was a bug, but in #4742 I changed the `addConsumer` method to use the original topic so the `removeConsumer` method can also use the original topic.
