### ISSUE TITLE
digitalstrom: massive amount of warnings detected by the code analysis

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4764]
This binding is the champion with 640 warnings detected. It represents around 30% of all the warnings detected in all ESH.
Maybe the author of this binding could have a look and enhance that.
There are 523 warnings of type ModifierOrderCheck and 464 are in one unique file.

**Comment by hmerk** [comment]
Are you talking of the released version, or the massive update provided with #3182

**Comment by lolodomo** [comment]
The current version in the master branch.

**Comment by hmerk** [comment]
So we will have to wait and see what number of errors the update will bring up.

**Comment by lolodomo** [comment]
After the merge of the mentioned PR, the number of warnings goes from 640 to 211 for this binding. Even if this is an improvment, this is still the part of ESH which has the biggest number of warnings detected by the code analysis.

**Comment by lolodomo** [comment]
There were 2081 warnings last weekend. We are now at 1278. Digitalstrom binding represents now 16,5% of all ESH warnings.

**Comment by sjka** [comment]
Thanks @lolodomo for joining the spring-cleaning efforts 👍

**Comment by lolodomo** [comment]
As only 65 warnings are now detected for the binding, I close my iossue. Most of them are "AuthorContributionDescriptionCheck".
This binding still represents 11.2% of all warnings detected in ESH.
