### ISSUE TITLE
fsinternetradio test: jetty packages with version hardcoded

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4781]
Is it expected that in the file MANIFEST.MF the imported Jetty packages are with a specific version ?

**Comment by kaikreuzer** [comment]
No!

**Comment by maggu2810** [comment]
Same here, I miss all the information and details why this should be done at all.
If we ever would do it @lolodomo which version should be used?
The one used by a randomly chosen product (you know that openHAB is not the only consumer of ESH)?

**Comment by lolodomo** [comment]
Yes, it should not but it is. Here is the issue.

**Comment by lolodomo** [comment]
https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.fsinternetradio.test/META-INF/MANIFEST.MF#L15

**Comment by maggu2810** [comment]
> The manifest must not have any version constraint on package imports, unless this is thoughtfully added.

This version constraint has been "thoughtfully added".
If we know, that something does not work with a lower version then (because it is broken, will not work, ...) ... it is okay to add that information.

**Comment by kaikreuzer** [comment]
We have meanwhile defined Jetty 9.3.15 as a minimal version for ESH anyhow, so I am not sure that we have to keep that information in place.

**Comment by maggu2810** [comment]
The intention of that section in the manifest (and all the other ones) is to add information to the OSGi runtime. The whole wiring depends on that correct information.
So, if we know that something does not work with a version lower or greater then, this information should be added to the manifest.
I don't know about a OSGi runtime that reads some ESH documentation :wink: 
Also if I as a product owner ensure that the correct Jetty bundles are present in the runtime I perhaps use also other third bundles in my runtime that depends on another Jetty version.
OSGi allows (as long as singleton is not declared) to use the same bundle in different versions in the runtime. It can choose the correct to use by respect the version constraints.

I could add e.g. jetty-client in two different versions to my runtime (to suffer the needs of some ESH 
bundles and a third party one), but without the version constraints (that are not added by the Eclipse IDE but by a developer that knows that it does not work with other ones) the wrong one could be chosen for wiring and stuff that could work is not working.

**Comment by lolodomo** [comment]
So it was intentional and required in the current case ?

**Comment by sjka** [comment]
Yes, and I'd like to second @maggu2810: In this particular case it should stay in there.

**Comment by kaikreuzer** [comment]
Sorry, but I do not agree with @maggu2810 and @sjka.
To be precise: I agree that providing minimal package version information can be helpful, but I do not agree that this is the agreement so far in ESH.

What we have done so far is to define the minimal version with which ESH is working in the target platform (or in the ESH documentation) and we deliberately decided against adding that information to the manifests due to the increased maintenance efforts.
We do NOT have any version constraints on OSGi framework imports, guava, Apache commons, Californium, etc pp. Nowhere.

I hence to not agree to make an exception for fsinternetradio for no specific reason. If you think we should start maintaining minimal required package versions, we should do that in general (but my hope would be that we can postpone this until we might have moved to BND one day).

**Comment by maggu2810** [comment]
> we deliberately decided against adding that information to the manifests due to the increased maintenance efforts

Hm, IIRC this has never been really discussed (perhaps the time before my involvement or I have don't remember anymore).

> If you think we should start maintaining minimal required package versions, we should do that in general

Yes, perhaps this is what should be done.

**Comment by maggu2810** [comment]
To be clear:
I don't want to have different version constraints for the same package in ESH bundles.
All ESH bundles should use the same version constraints for the same package.
So, I would like to have the constraints ESH defines (per documentation and target platform) in every bundle for the respective packages.

As long as we do use the manifest first approach, I could create a utility that helps us to manage this one.
I have already created a simple tool that reorders the manifest declarations (I assume you remember), fixes two long lines and use a pretty print for the imports etc.
This one should be easy to adapt to read a file with version constraints for packages and fix all the manifests.

**Comment by kaikreuzer** [comment]
I'm ok with that wish and I guess all further discussion can be done on https://github.com/eclipse/smarthome/issues/5140 (thanks for that).
This issue can therefore be closed.
