### ISSUE TITLE
IO Rest SSE: javax.servlet packages imported with a specific version

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4782]
Is it expected that a specific version is hardcoded in the file MANIFEST.MF for packages javax.servlet.http and javax.servlet for the bundle org.eclipse.smarthome.io.rest.sse ?

**Comment by kaikreuzer** [comment]
No!

**Comment by maggu2810** [comment]
@lolodomo Can you give some more details about your question? Why should we limit the version? What are the benefits? Why should the old ones be dropped (my reading of @kaikreuzer answer is, that the old servlet version is still used in some product).

**Comment by lolodomo** [comment]
I have just in mind that we should avoid mentioning versions in MANIFEST.MF and this is not the case.

**Comment by lolodomo** [comment]
https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sse/META-INF/MANIFEST.MF#L18

**Comment by maggu2810** [comment]
See also https://github.com/eclipse/smarthome/issues/4781#issuecomment-352880837

**Comment by lolodomo** [comment]
So it was intentional and still required in the precise case ?

**Comment by kaikreuzer** [comment]
The specific version has meanwhile been removed and with https://github.com/eclipse/smarthome/issues/4781#issuecomment-383533992, we will in future decide, which version constraints to add in bulk to which packages throughout ESH bundles.
