### ISSUE TITLE
Multi-Line item/sitemap text

### ISSUE THREAD

**Issue by michel53** [eclipse/smarthome#4789]
I would like to use multi-line text for items/sitemaps.
This could be added via special escape character like "\n".
F.e.
Switch Wall_Plug "Schaltbare Steckdose1 \n(Wohnzimmer) [%s]"
Number Shutter1_Power "Rollo Küchentür \nLeistung [%.1f W]"

To show in 2 lines in all UIs.

**Comment by Seb-Maier** [comment]
Same for me...
I use it as explanations a sitemap files. Like,
`Text label="Lüfter schalten an, sobald der Grenzwert überschritten ist.\nAbschaltung erfolgt bei Unterschreitung des Grenzwertes um die Hysterese"	 icon="info"`

With the current habdroid Version the line is cutted :-( and I can't use it as before

**Comment by kaikreuzer** [comment]
This would be a huge change, which I think is rather unrealistic, since so far all labels throughout ESH are not meant to carry any formatting information (otherwise, we might easily wish to also introduce bold, italic, identation and whatever).
In general, labels are anyhow only supposed to be as short as possible (1-2 words) and that's what clients expect.

I'd therefore suggest to close this issue.

**Comment by michel53** [comment]
> bold, italic, identation and whatever

**Comment by kaikreuzer** [comment]
> But when mixing items (in a graph or on different places in the sitemap), how would you identify location like floor and room?

Well, simply by context-specific labels, i.e. on a page of all my windows, the room information is just enough: http://demo.openhab.org:8080/basicui/app?w=020102&sitemap=demo

**Comment by Seb-Maier** [comment]
What I don't understand is, that in an older HabDroid Version it was possible to see more lines on an text label and to make a manuel line feed with a \n

**Comment by michel53** [comment]
As I understand, the \n was never officially supported (there was no entry in the documentation) and I copied it from an example somewhere. It only worked in HabDroid, not in the other UIs. With a code update, it is broken now. That's how distributed open source software development may go...
