### ISSUE TITLE
WeatherUnderground binding does not provide pressure_trend

### ISSUE THREAD

**Issue by bdleedy** [eclipse/smarthome#4803]
@lolodomo Awesome work on this binding! I'm missing the handling of icons but it seems as though that is being discussed and on it's way somehow.

I'm not a Java guy but tried to code the following. mvn install clean fails for me with a tools.jar issue I'm trying to figure out. I'm wondering if you would take a look at what I wrote and integrate it or a better version. I considered a converter but it seemed silly to handle what would probably be one case.

```
    private String pressure_trend;

    /**
     * Get the pressure trend
     *
     * Used to update the channel current#pressureTrend
     *
     * @return the pressure trend as "equal", "up", "down", or null if not defined
     */
    public static final String TREND_EQUAL = "equal";
    public static final String TREND_UP = "up";
    public static final String TREND_DOWN = "down";

    public String getPressureTrend() {
        if (pressure_trend == "0") {
            return TREND_EQUAL;
        } else if (pressure_trend == "+") {
            return TREND_UP;
        } else if (pressure_trend == "-") {
            return TREND_DOWN;
        } else {
            return null;
        }
    }
```

**Comment by lolodomo** [comment]
À simple MAP should work. But if you are sure of all possible values, this could be included in the binding.

**Comment by bdleedy** [comment]
Well you tell me! From all of the info I can find those are the only possible values (which makes sense). I guess it would make sense to have a map so you can convert it to whatever is required. I doubt anyone will use TREND_EQUAL and will map something else anyway.

**Comment by lolodomo** [comment]
@bdleedy : it is now implemented.
