### ISSUE TITLE
[Paper UI] Add links to (available) docs for all Add-Ons

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#4815]
On the "Add-ons" page the add-ons on tabs "BINDINGS" and "PERSISTENCE" have links to the corresponding documentation pages on docs.openhab.org.
For the add-ons on the other tabs (e.g. "TRANSFORMATIONS", "USER INTERFACES") the links are missing although the documentation exists.

**Comment by kaikreuzer** [comment]
Sorry, ESH must not link to openHAB documentation.
The links that you find on the addons are defined within the extension service of openHAB, see https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java#L109-L115

**Comment by MHerbst** [comment]
It's sometimes not so easy to figure out the correct Repo. Thanks for the hint and the link to implementation.
