### ISSUE TITLE
[sonos] clearqueue channel doesn't work

### ISSUE THREAD

**Issue by Dan1001** [eclipse/smarthome#4816]
Hi,

The clearqueue channel doesn't seem to work at all on the Sonos binding.

If I create a queue on a Sonos devices, then all other of the openHAB channels work perfectly on that device, but clearqueue does nothing. There are no log entries.

thank you!

Dan

**Comment by lolodomo** [comment]
Works well and as expected for me.

**Comment by lolodomo** [comment]
Is there someone else having a problem ?
@sjka @maggu2810  @kaikreuzer @kgoderis : can one of you make a try ?
If noone can reproduce the issue, I would suggest to close it.

**Comment by Dan1001** [comment]
I hadn't tested this for several months, but just tried again and it works fine on the 2.3 release. So I've closed it. Thank you all!
