### ISSUE TITLE
PaperUI is displaying configuration of channel-type rather than channel

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#4823]
Currently it seems that PaperUI is only displaying the configuration of the channel-type, and not the channel itself. 

For example -:
```
channel-type:zigbee:switch_level
```
and not
```
channel:zigbee:device:telegesis:0017880100dc880b:0017880100DC880B_11_switch_level
```

This means it's not possible to have channel specific configuration shown in PaperUI as the system supports. A direct call to the rest interface with the above config uri works fine.

I'm not sure if this is a bug in PaperUI, or maybe in the thing configure provider (or elsewhere).

**Comment by kaikreuzer** [comment]
I would assume that it is a bug in the Paper UI.
@htreu Could you check?

**Comment by htreu** [comment]
Hi @cdjackson, this is actually a bug in PaperUI only looking up the config description URI for the channel-type and not using the full channel URI.
