### ISSUE TITLE
Rules/Sitemaps/Scripts refreshed twice

### ISSUE THREAD

**Issue by cribskip** [eclipse/smarthome#4824]
When changing files (rules, scripts, sitemaps), this results in openHAB to Load and Refresh the file twice, causing unnecessary delays especially on embedded platforms.

**Expected behaviour**
When changing files, the ModelRepositoryImpl should only refresh known files. When a new file is added, it should be added and watched out for changes.

**Current behaviour**
When changing files (rules, scripts, sitemaps), this results in openHAB to Load and Refresh the file twice, causing unnecessary delays especially on embedded platforms.

**Possible solution**
None known. Workaround: Stop openhab, change files as needed, start openhab again.

**Steps to reproduce**
Change a configuration file (rule, sitemap, script) by using any editor. Look at the openhab.log and notice "Loading model XXX", "Refreshing model XXX", "Refreshing model XXX".

**My environment**
Debian 9.3 on raspberry pi 3 with openhab2 2.2.0-1 stable out of repo. 
root@openhab2:~# java -version
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)

**Additional notes**
The bug may be caused by one of these places: https://github.com/eclipse/smarthome/blob/36c9e2717e4f89cf60a0d885e7ecc6069b338f48/bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java#L242

https://github.com/eclipse/smarthome/blob/36c9e2717e4f89cf60a0d885e7ecc6069b338f48/bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java#L91

Also discussed in the community
https://community.openhab.org/t/rules-still-loading-running-twice/22183

**Comment by sjka** [comment]
The framework gets these events from the JVM, and the JVM gets them from the OS/FileSystem more or less directly. I have seen this a couple of times and apparently factors like OS, files system,  remote access method and used editor have an influence of this. 

I was thinking already of adding a grace period in FolderObserver, i.e. only load/refresh models after there hasn't been any such event for a certain amount of time (e.g. one or very few seconds).

**Comment by cribskip** [comment]
@sjka Thank you very much for implementing this workaround. However, I just found a quirk (I'm unsure if I should open a new issue):
Running on a Raspi 3, if a rule file compiles fast, your patch works just fine preventing a second reload. However, if the rule compilation is too time consuming, it still reloades twice still escalating the situation. It would be great if a ongoing compilation could be sensed and a reload canceled until this is done.

Here are two examples:
```
# Working fine: Compilation in approx. 5 seconds, no second reload:
2018-08-24 21:10:42.422 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model '99_program.rules'
2018-08-24 21:10:47.216 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model '99_program.rules'
```

```
# Troublesome: Compilation takes approx. 23 seconds, second reload occurs:
2018-08-24 21:17:09.896 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model '99_voice.rules'
2018-08-24 21:17:32.390 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model '99_voice.rules'
2018-08-24 21:17:42.240 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model '99_voice.rules'
2018-08-24 21:18:04.272 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model '99_voice.rules'
```
