### ISSUE TITLE
Date comparison with now inverted in sitemap attribute (visibility, valuecolor, ...)

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4828]
https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java#L887
The diff calculation between dates is done in the wrong way. It leads to unexpected behaviour when using date diff in sitemap attributes like visibility or valuecolor.
It is a major bug that was probably introduced with the refactoring of DateTime.

**Comment by lolodomo** [comment]
This issue is not critical but at least major.
I am not sure we can wait 6 months to make the fix available to all users. WDYT ?
Maybe we should think about a OH version 2.2.1 in few weeks ?

**Comment by martinvw** [comment]
@lolodomo could you elaborate on this? What is done is how and how should it have been done instead?

> The diff calculation between dates is done in the wrong way.

**Comment by lolodomo** [comment]
The code is computing a difference between the new value and "now". This difference must be positive and can be used in valuecolor for example.
Current code is between(now, val) while it should be between(val, now) to get a positive value.

**Comment by martinvw** [comment]
@lolodomo maybe a proper moment to make sure its covered by tests as well :-)

**Comment by lolodomo** [comment]
If someone wants to add a test, he is welcome. On my side, I am working on more important things (in my point of view).
But we need a quick fix for that issue, I think it should be included in the next ESH build for OH.
And I hope that the Datetime refactoring did not introduce other problems that this this one.

**Comment by kaikreuzer** [comment]
> Maybe we should think about a OH version 2.2.1 in few weeks ?

I have [cherry-picked it in a 2.2.x branch](https://github.com/openhab/smarthome/tree/2.2.x) in the openHAB fork, from which we could potentially build a patch release.

> If someone wants to add a test, he is welcome. On my side, I am working on more important things (in my point of view).

Please nonetheless consider helping to improve the test coverage on such parts in future. After all, if there would have been tests, such issues would not have popped up in the first place.
