### ISSUE TITLE
[Sonos] notificationvolume is not persistent

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#4832]
...as it is a pure "binding" feature and not backed by the real device at all (see https://github.com/eclipse/smarthome/pull/4830#issuecomment-354727202).

Question is: why is this a channel and not a configuration parameter? And if it is to remain a channel, shouldn't the handler persist the state somewhere itself rather than relying on the user to set the notificationvolume again and again after every restart?

**Comment by lolodomo** [comment]
I think it could be a thing setting rather than a thing channel.
We should keep the ability to have a different notification sound level for each Sonos device.

**Comment by cweitkamp** [comment]
What about using both? Instead of initializing the value for the `notificationvolume` from the original `volume` we can store and reinitialize it from a thing configuration/property? Wdyt?

Notice: There are some other bindings in OH2 e.g. Squeezebox (https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxPlayerHandler.java#L593) which handle it pretty much in the same way. If we find a proper solution we should transfer it into those bindings too.

For the record: imho the `notificationvolume` channel - and a channel for playing an URI - could be a good point to mention in a guideline for developing AudioSinks (#3757).

**Comment by JueBag** [comment]
I second the approach to have both. Having the notificationvolume only as a setting would hinder the use of different volumes (normal volume for standard notifications ["Breakfast is ready!"] and real loud for smergencies ["Get out of bed NOW!"]).

**Comment by mhilbush** [comment]
> Notice: There are some other bindings in OH2 e.g. Squeezebox 

Note that when I added the AudioSink feature for Squeezebox, I modeled it after the Sonos implementation -- thought it best to remain consistent

**Comment by cweitkamp** [comment]
> I modeled it after the Sonos implementation -- thought it best to remain consistent

Fair enough. I didn't want to blame you for that. Indeed I agree with you to be compliant in such cases.

**Comment by cweitkamp** [comment]
I made a proposal #4846

**Comment by kaikreuzer** [comment]
Thinking about it, I actually second @sjka & @lolodomo's opinion that this feature actually IS a configuration parameter and not a channel. Having it as both feels to be a hack and would imho only be acceptable for keeping backward compatibility, but not to have it as a recommendation for any AudioSink.

**Comment by mhilbush** [comment]
I disagree.  I would vote to keep the channel for notification volume.  I don't see where this is any different than any other volume setting.  I surely wouldn't set the music playback volume through a config parameter.

What about the scenario where you want to use different volume levels depending on the type of notification?  For a notification about a severe situation (e.g. water detected by a sensor) I want a higher volume level versus the doorbell versus my morning announcement of the outside weather conditions.  Being able to change the volume level in a rule allows me to do this.

If it's a choice between a channel and a config parameter, there's much more flexibility with it as a channel.  The config parameter simply is a convenience that avoids having to set the default volume level in a system startup rule.

**Comment by lolodomo** [comment]
True, the channel is appropriate if you want to adjust the notification volume in a rule.

**Comment by maggu2810** [comment]
Hm, IMHO a configuration value should be used and not a channel.

If rules would like to use different notification volumes for different notifications, then the global configuration parameter should be untouched and not used at all.

```Java
    /**
     * Play a given notification sound
     *
     * @param url in the format of //host/folder/filename.mp3
     */
    public void playNotificationSoundURI(Command notificationURL) {

        if (notificationURL != null && notificationURL instanceof StringType) {
```

Wouldn't it make more sense to add the notification volume as an option to the URL if another then the configured volume should be used?

**Comment by kaikreuzer** [comment]
The "clean" way to deal with features that require parameters (such as an other-than-default notification sound volume) would be to introduce a rule action. We still have to work out how to best combine bindings with actions (separate bundles or both in one?), see also https://github.com/openhab/openhab2-addons/pull/2926.

**Comment by maggu2810** [comment]
Perhaps a rule action would solve this one for rules but what about using the REST API to trigger notifications? If I want to use "normally" the default notification volume but want to trigger two notifications using a special (different) volume, wouldn't it make sense to enhance the URL to contain that a volume, too?

**Comment by kaikreuzer** [comment]
The interesting part of your question is that it nowhere ever refers to Sonos - it is completely independent of this. Which is a clear sign that we must not add anything specific to the Sonos binding for that.
Fact is that we currently do not have any REST endpoint for sending notifications as all (nor to do TTS or many other such things), but that all such things are done in rules.

**Comment by maggu2810** [comment]
Hm, okay then I am completely wrong.

My understanding has been:
Today the Sonos binding provides a channel "notificationsound" that could receive a string type that encodes an URL and it provides a channel "notificationvolume" to set the volume.
My reading of the arguments to keep the notification volume channel has been to play a notification sound using a special volume.

I second that the Sonos notification volume should be a configuration parameter.

I also think it make sense to trigger different notifications using different non-global volume as e.g. some guys used it in rules already.

**Comment by mhilbush** [comment]
Whatever the solution, it would be nice to retain the simplicity.
```
PlayerNotificationVolume.sendCommand(40)
playSound("sink", "doorbell.mp3")
```
or
```
PlayerNotificationVolume.sendCommand(70)
say("Water detected", "voicerss:enUS", "sink")
```
If something was playing before the notification, after the notification it resumes playing at the same volume level before the notification played.  It works very nicely.

This works nicely when you specify the sink.  Arguably, it can be confusing if you use the default sink, because it requires that in your rule you **know** what the default sink is in order to adjust the notification volume.

**Comment by kaikreuzer** [comment]
> it would be nice to retain the simplicity.

No, it should not retain it, it should improve it:
```
playSound("sink", "doorbell.mp3", 40)
```
or
```
say("Water detected", "voicerss:enUS", "sink", 70)
```
would imho be much simpler!

**Comment by mhilbush** [comment]
> it should not retain it, it should improve it

Yes, that would be even better!

**Comment by cweitkamp** [comment]
I thought about your opinions. At the beginning I was convinced the channel is necessary. Currently I changed my mind and think a property for a default notification sound volume should be enough.

At the moment the binding always changes the volume before playing the notification. We can manage to adjust this volume by setting it in a rule for different purposes. This won't be possible anymore if we remove the channel and use a property. I suggest to change the business logic of the binding a little bit. The volume for notifications should only be changed if the current volume of the device is less than the  value stored in the property. Regarding to this condition a user is allowed to set an even louder volume using the normal volume channel. I'm going to submit another proposal in the next days.

Beside this change I vote for the suggested improvements of the `playSound()` and `say()` methods. If we look forward to implement those features we have to ask the question if the handling of notification sound volume should be part of the audio API. In my opinion we shouldn't implement the volume adjustments in each binding. Instead the `AudioManagerImpl` or the `VoiceManagerImpl` have to take care of that. Wdyt?

**Comment by lolodomo** [comment]
Adding sound volume to the playSound and say commands make sense.

**Comment by lolodomo** [comment]
This should be even easy to change. The question is how many bindings have a similar handling to the Sonos binding and should be then updated to suppress the notificationVolume channel ?

**Comment by cweitkamp** [comment]
PR #4963 - Improvements in Audio and Voice API

**Comment by mhilbush** [comment]
> how many bindings have a similar handling to the Sonos binding and should be then updated to suppress the notificationVolume channel

I'll take care of the squeezebox changes.

**Comment by cweitkamp** [comment]
I'm working on the Kodi binding to introduce the new feature. :-D
