### ISSUE TITLE
tradfri: gateway crashes after ~10 minutes when OpenHAB accesses it

### ISSUE THREAD

**Issue by rralf** [eclipse/smarthome#4839]
Hi,

I encountered some strange bug. When the tradfri binding is active in OpenHAB, my tradfri GW crashes after 10 minutes. If OpenHAB is not active, everything works fine. Eventually I found some time to hunt that bug down.

First, I think this is rather an IKEA firmware bug, but apparently that one gets somehow triggered by OpenHAB.

If the tradfri binding is active, my GW stops working after 10 minutes. It's not pingable any longer, IKEA's official app isn't able to access my GW as well. All LEDs on the gateway are on.

To find out what's going on, I monitored the traffic of my gateway and compared bahaviour with and without OpenHAB. Here's a screenshot of the last few packets before the GW crashes.

![tradfri](https://user-images.githubusercontent.com/4509870/34503748-8bd15748-f01a-11e7-97d7-536e7b2eef5e.png)

172.16.2.1 is my OpenHAB server
172.16.2.34 is the Tradfri gateway
172.16.2.24 is the machine pinging the gateway

172.16.2.24 continuously pings the gateway, and after the last five (empty?) UDP packets from 172.16.2.1 (OpenHAB) my gateway is gone forever, and I have to powercycle it.

OpenHAB version: 2.2.0_20171216
Tradfri GW version: 1.2.42

Anyone similar issues?

Thanks

**Comment by rralf** [comment]
Update: I got myself a new gateway, to make sure that hardware isn't broken: Same again, gateway crashes after ~10 minutes, only if openhab's tradfri binding is active.

**Comment by maggu2810** [comment]
I am not own a Trådfri gateway myself. Perhaps some other guys using such a gateway could comment if it is working / not working for them.

**Comment by eiGelbGeek** [comment]
Same here ... now switched to HUE Bridge

**Comment by rralf** [comment]
Ok, so do you have the exact same issue? Then i'm not the only one, and I still don't know how to fix this.

**Comment by eiGelbGeek** [comment]
The New Tradfri Gateway Firmware solved my Problems. *First prognosis after 1 hour use*

**Comment by rralf** [comment]
Cool, thanks, let me check next week if this update is available for me and if so, if it fixes my issue.

**Comment by rralf** [comment]
So I updated my gateway updated to 1.3.14. My gateway still crashes after ~10 minutes after I start openhab.

**Comment by rralf** [comment]
Update: I think I was able to significantly narrow down the bug:

I tried to filter and drop those suspicious packets using iptables:
`iptables -I OUTPUT -p udp --destination-port 5353 --src 172.16.2.1 --dst 172.16.2.34 -j DROP`

No crash of the Tradfri gateway so far. Those packets are multicast DNS (Bonjour) packets and, apparently, crash the tradfri gateway.

To verify that, I used tcpreplay to reinject those packets. **Bingo!**

`tcpreplay --topspeed --intf1=enp0s25 ./replay.pcap`

will crash the gateway IMMEDIATELY!

Please find the capture [here](https://ramses-pyramidenbau.de/~ralf/IKEA-Tradfri-replay-Crash.pcap). Amend the IPs and MACs and try it on your own. IKEA, please fix your stuff.

**Comment by eiGelbGeek** [comment]
Yes .... Networkbinding for Ping iOS Devices.... Bonjour WakeUp ... 

The Tradfri Gateway need the Bonjour for Homekit i think..... bad Implementation in Firmware?

**Comment by rralf** [comment]
Yes, this is a firmware bug that should definitely be fixed. Additionaly this is a bug that can be used for a denial of service attack. At least the nasty iptables rule makes the gateway working for me again.

Maybe it's an idea to start fuzzing the device, I'm pretty sure this is not all :)

**Comment by triller-telekom** [comment]
I am wondering if this is still the right place for this issue. if the gateway crashes due to packets from the "Networkbinding for Ping iOS Devices" or a "Bonjour WakeUp", it is certainly not the fault of ESH or openHAB.

@rralf Did you report it to IKEA already? Can you/we close this this issue here, then?

**Comment by rralf** [comment]
Yep, contacted IKEA. What a hassle… Nevertheless, after i got in contact with the authors of the code, they were in deed able to reproduce this error and promised a fix. Maybe it's already fixed. I'll have to check this by reverting my local fix -- removing some firewall rules :-)

But yes -- this issue can be closed. Thanks.
