### ISSUE TITLE
[Basic UI] TypeError when loading Webview

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#4853]
I see this error in the Chrome (Mac and Windows) browser console when loading a sitemap with a Webview on the home page. It doesn't appear to impact functionality.  It occurs twice on the initial load of the sitemap (probably due to issue #4845), then once when returning to the page containing the Webview.

I see this on build 1160.

![typeerror](https://user-images.githubusercontent.com/19286354/34587225-6a429d60-f175-11e7-9433-2def446010e7.jpg)

Oddly, in Firefox on the Mac I see something slightly different on the initial load of the sitemap.
![ff](https://user-images.githubusercontent.com/19286354/34587664-44aa44b6-f177-11e7-86ea-fbc2eb0aa806.jpg)

**Comment by resetnow** [comment]
I think it's somehow related to sitemap. So if you have a development environment, first step to do it would be one of these:

1. Edit sitemap to get a minimal reproducible example
1.
    1. copy smarthome.js from web-src to web
    2. reload page. Stack trace should now have line numbers and function names and can be copy-pasted here

**Comment by mhilbush** [comment]
In the process of trying to narrow this down, the error stopped occurring.  Since I can no longer reproduce, I'm going to close the issue.
