### ISSUE TITLE
[PaperUI] Broken layout of the Inbox in Chrome

### ISSUE THREAD

**Issue by monnimeter** [eclipse/smarthome#4856]
Hello.

The layout of the Inbox is broken (PaperUI pulled yesterday from GitHub, 2.3.0-SNAPSHOT). In earlier versions everything was okay.

This is how it looks like now - the Label is cut:
![image](https://user-images.githubusercontent.com/12434126/34616353-4824fb24-f238-11e7-9f49-7f5c6fec3850.png)
I'm using the newes Chromw version (Version 63.0.3239.132 (Offizieller Build) (64-Bit)).

And this is how it's rendered by Edge:
![image](https://user-images.githubusercontent.com/12434126/34616415-75b40c6a-f238-11e7-8a64-18858508f8b3.png)

Thank you and regards,
Osman

**Comment by kaikreuzer** [comment]
Could you please fully clear your browser cache? Maybe this makes a difference to the layouting already. 
Your screenshots still show the old openHAB logo, which definitely should not there since a couple of months and definitely not on a 2.3.0-SNAPSHOT...

**Comment by monnimeter** [comment]
Yes, you're right - thank you.
It has something to do with the browser caching. Disabled the cache in dev. tools, et voilà: the layout is okay. But for some reason the logo remains the same...
![image](https://user-images.githubusercontent.com/12434126/34618796-366bccc0-f240-11e7-9636-49e1a01f3b73.png)
Same with browser cache cleared. 

Not showing the right logo is IMHO another issue. Hence I would like to close this ticket.
