### ISSUE TITLE
NTP binding: not at time

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4867]
I just discovered that my RPI is not at time at all but 11 minutes before the correct time.
The NTP binding is providing the server time as displayed in Basic UI.
Isn't it the role of the NTP binding to keep my server at time ?

**Comment by 9037568** [comment]
The NTP binding is for using/displaying time, not for setting it. The server's time isn't managed by the binding.

**Comment by lolodomo** [comment]
What is the usage done with the NTP server we set as thing parameter ?

**Comment by lolodomo** [comment]
Why does it return my wrong server date and time ?

**Comment by lolodomo** [comment]
So there is an issue somewhere.
I have now updated the time of my server but before that, my item was returning my server time and not the correct time.

**Comment by 9037568** [comment]
Guess it's time to dig into the logs, then... 😄

**Comment by sjka** [comment]
I can at least confirm that behavior

**Comment by maggu2810** [comment]
> I just had a quick look at the code:
>
> https://github.com/eclipse/smarthome/blob/4204ce06bb28c28e5f711e720f87ef83beff2e27/extensions/binding/org.eclipse.smarthome.binding.ntp/src/main/java/org/eclipse/smarthome/binding/ntp/handler/NtpHandler.java#L194-L202
>
> To me it looks like it is written (under the false assumption) that getTime(...) actually updates the computer's system clock. However, this clearly is not the case.
>
> With this logic, the binding gives you the correct time very refreshNtp times and the wrong computer clock's time on all the other cases.

Hm, I don't think so.

If it has been written under the assumption that `getTime(...)`
updates the computer's system clock, then the next line that uses
`System.currentTimeMillis()` to calculate the diff wouldn't make
sense.

```Java
networkTimeInMillis = getTime(hostname);
timeOffset = networkTimeInMillis - System.currentTimeMillis();
```

**Comment by sjka** [comment]
> Hm, I don't think so.

Yes, I noticed it the moment when I hit the button. Nevertheless, I think I found the problem: It only returned the _receive time_ and completely ignored the offset.
