### ISSUE TITLE
[Weather Underground] support the system locale setting

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#4892]
As it [turned out](https://github.com/eclipse/smarthome/pull/4875#issuecomment-355947353), the Weather Underground API has its own codes for the used locales, therefore it has to configured explicitly in the binding currently. It would be nice however it it would obey the system locale configuration as returned by the LocaleProvider. 

See #4875 for the discussion.

**Comment by lolodomo** [comment]
This would require a mapping table, that's all ?

**Comment by lolodomo** [comment]
Here is the conversion table to implement: https://www.wunderground.com/weather/api/d/docs?d=resources/country-to-iso-matching
I will add it.
