### ISSUE TITLE
[PaperUI] Allow options outside of min/max

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#4895]
see #4797 & #1282

**Comment by sjka** [comment]
Ha, just tested it: it works! 

PaperUI validates limits for plain integer parameters, but doesn't do so for integer values having "options" (i.e. where it renders a drop-down box)

**Comment by cdjackson** [comment]
> PaperUI validates limits for plain integer parameters, but doesn't do so for integer values having "options" (i.e. where it renders a drop-down)

Just a comment - I've not checked the implementation, but it should also check the limits when there are options. It needs to ensure the value is "min <> max || options" in this case.

**Comment by kaikreuzer** [comment]
@sjka Can you confirm this?

**Comment by htreu** [comment]
@cdjackson you are talking about an options list with `limitToOptions = false` right? So the user is able to enter own values which are not predefined in the drop down.

**Comment by htreu** [comment]
Besides, there are some other issues with drop downs and `limitToOptions` so when fixing this maybe its a good time to also fix the other problems:
* #2844
* #3556
* #4014

**Comment by sjka** [comment]
@kaikreuzer I understood the same and it is working as of today in the sense that it allows options outside of the min/max range and only those values which are predefined as an option. However, I fear this is mainly because of #4014 😉 
Nevertheless, @cdjackson's use-case is working as of today.
