### ISSUE TITLE
[Tradfri] Trådfri incorrectly reports old firmware on startup

### ISSUE THREAD

**Issue by EliasGabrielsson** [eclipse/smarthome#4904]
#### Symptom:

The binding reports firmware incorrect on startup of openhab.

```
2018-01-12 11:05:43.095 [WARN ] [radfri.handler.TradfriGatewayHandler] - Gateway with old firmware - please consider upgrading to the latest version.
```

#### Reproduce:

Watch the `/var/log/openhab/openhab.log` while starting the system.

#### Expected outcome:

As my Ikea phone app reports up updated on all devices including the gateway (currently: 1.2.42) I don't expect this warn log.

#### System:

Openhab 2.2 running on an Pine64 device.

[Related forum thread](https://community.openhab.org/t/tradfri-wrong-upgrade-message/36316)

**Comment by sjka** [comment]
Thanks for this report!

It indeed looks like the version check implementation is a little too simple:

https://github.com/eclipse/smarthome/blob/4204ce06bb28c28e5f711e720f87ef83beff2e27/extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/handler/TradfriGatewayHandler.java#L378-L381

**Comment by cweitkamp** [comment]
One question: Is it allowed to use the `org.apache.maven.artifact.versioning` bundle (e.g. the [DefaultArtifactVersion](https://maven.apache.org/ref/3.3.9/maven-artifact/apidocs/org/apache/maven/artifact/versioning/DefaultArtifactVersion.html) class)?

If not, do we have classes which can be used for the comparison?

**Comment by kaikreuzer** [comment]
I am afraid the answers are no and no.
Btw, we also have no clue what versioning scheme IKEA will use in future, so we probably best implement some custom logic anyhow.

**Comment by cweitkamp** [comment]
I made a proposal: PR #4930

I guess it can be enhanced a lot. Please tell me. Maybe we even can move it to some place in the ESH core framework.
