### ISSUE TITLE
Configuration normalisation not performed on channel configuration

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#4910]
When saving channel configuration, normalisation is not performed on the channel configuration. Additionally, it looks like the defaults may not be of the correct type - defaults are specified as a ```String``` (ie in ConfigDescriptionParameterBuilder) and should be normalised before being passed to the binding.

For example, the following -:

```
            options = new ArrayList<ParameterOption>();
            options.add(new ParameterOption("65535", "Use On/Off transition time"));
            parameters.add(ConfigDescriptionParameterBuilder.create(CONFIG_ONTRANSITIONTIME, Type.INTEGER)
                    .withLabel("On Transition Time")
                    .withDescription("Time in 10ms intervals to transition from OFF to ON").withDefault("65535")
                    .withMinimum(new BigDecimal(0)).withMaximum(new BigDecimal(60000)).withOptions(options)
                    .withLimitToOptions(false).build());
```

will provide a String when the configuration is read from the channel.

**Comment by sjka** [comment]
I just had a closer look through the code:

* I can confirm that at least [GenericThingProvider](https://github.com/eclipse/smarthome/blob/4204ce06bb28c28e5f711e720f87ef83beff2e27/bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend#L423) doesn't do any normalization on the channel configuration coming from the DSL files. That indeed needs fixing.
* PersitentInbox doesn't take any channel configuration from the discovery, so normalization can't be an issue there.

Regarding the channels' default values though I cannot confirm your suspicion (at least not in the code...):

* PersistentInbox does it through ThingFactory using [ThingFactoryHelper](https://github.com/eclipse/smarthome/blob/4204ce06bb28c28e5f711e720f87ef83beff2e27/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingFactoryHelper.java#L182)
* [GenericThingProvider](https://github.com/eclipse/smarthome/blob/4204ce06bb28c28e5f711e720f87ef83beff2e27/bundles/model/org.eclipse.smarthome.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend#L402) also does it by itself

Here I'd need some more guidance on how the thing/channel instance then is created - or at least how to reproduce it, then I can figure out the rest myself. Probably I'm just missing something...

**Comment by cdjackson** [comment]
Thanks @sjka. Re the default value, it’s possible I was wrong here and another possibility is that PaperUI is not doing normalisation on channel config (which I think it does on thing config).

I also just looked at the rest service, there is normalisation done there as well, but only on the thing. If I remember correctly, channel configuration is PUT in the ThingResource, and here it only focuses on the thing configuration - I’m not sure if this should also be resolved here or if there’s a central place it should be handled?

**Comment by sjka** [comment]
Thanks for the clarification. I will have a look.
