### ISSUE TITLE
[Astro] radiation group channels dimensions

### ISSUE THREAD

**Issue by emme-g** [eclipse/smarthome#4913]
Hello,
I recently found and set up some new channels of the Astro binding in my Openhab system, among all of them are the radiation group channels (direct, diffuse and total radiation).
I searched in the documentation and in Internet but I couldn't find any information about the dimensions of the numbers that these channels provide. In my place now is Winter (I'm in the North of Italy) and the binding, approximately at midday,  gives me these numbers:
- direct radiation - 149,32;
- diffuse radiation - 108,40;
- total radiation - 257,72.

I guess that these values are expressed in W/m2 (Watt / square Meters), but I would be happy if some of the people who know better this binding could confirm that and maybe insert this information in the documentation.
Bye.

**Comment by triller-telekom** [comment]
@gerrieg Could you please comment on that?

Also once we have proper unit support with PR #4818 this would be a good candidate to use the new `QuantityType` then.

**Comment by gerrieg** [comment]
@clinique Could you please comment? It was your PR https://github.com/openhab/openhab2-addons/pull/1588

**Comment by clinique** [comment]
@emme-g : yes, this is W/m2, channels are described that way and you're right, it's missing in documentation. Maybe you can make a small update on it ?

**Comment by emme-g** [comment]
Thank you clinique, I haven't seen the PR openhab/openhab2-addons#1588 before I created this issue.

I'll be happy to make the small update on the documentation, but actually would be the first time for me to amend an Openhab or Eclipse public document and I don't know how to do it. I'll try to find out how to modify the documentation file (or if you have time to give me a link to the information I need to understand how to do it) and I'll do it.

I've another little question about the radiation channels: I noticed that, for my system and location, at sun rise the value of the diffuse radiation channel changes suddenly from 0 to 20 W/m2 and later it keeps on changing with steps that are about 1 W/m2, instead the value of the direct radiation channel changes from 0 in a more smoothly way with steps that are about 0,02 W/m2 (at the sun set it happens the same but in the opposite direction). The issue is more clear if you look a chart of the three items persisted with the "every change" strategy. Do you think that could be possible, and would worth the effort, to modify the binding in order to avoid these jumps in the diffuse (and in the total) radiation value series?

**Comment by triller-telekom** [comment]
@emme-g Thank you that you volunteer to update the documentation.

Some hints to help you get started: https://www.eclipse.org/smarthome/documentation/community/contributing.html#conventions-for-pull-requests

You need an account at eclipse.org where you sign the CLA (Contributor license agreement) with an email address that you have to use in your commit message as a "Sign-Off" tag.

Then you can fork the repository and edit the documentation file which is [this one](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.astro/README.md)

After changing it you need to create a new branch in git: git checkout -b astroDocFix
then you commit with a signoff: git commit -s -m "Fixed astro documentation\n\nFixes #4913"

You can now push this branch to your fork via: git push

and then you can visit the https://github.com/eclipse/smarthome page and you should already see a message box where you can create a pull request out of your new branch.

Let me know if you need more help.

**Comment by emme-g** [comment]
@triller-telekom Hi Stefan, I tried yesterday to make the update but I guess the update process is not finished. This is what I did:
- I created my account at eclipse.org and signed the CLA;
- I forked the repository eclipse/smarthome (I did it directly on the github website using the fork button, I don't have git locally on my computer);
- I went down in my repository to smarthome/extensions/binding/org.eclipse.smarthome.binding.astro/README.md and edited the documentation file README.md (I did it directly on the github website using the edit (pencil) button);
- at the end of the modification I took the option "Create a new branch for this commit and start a pull request" and I insert the text "git checkout -b astroDocFix" in the field that appeared (I think here I made one mistake because it seems a command and not a name);
- finally I didn't know what is and how to "commit with a signoff: git commit -s -m "Fixed astro documentation\n\nFixes #4913"" and so I don't remember how I sign out from github.

Now I can see in this discussion there is a line showing that I made an update and it has the state "verified", but in the documentation my update doesn't appear. I know that I missed the last points of your suggestion too:
- push the branch to fork via: git push;
- create a pull request out of your new branch;

and I have to say that I don't know what they mean.
I'm not really an expert about Github, I'm really new, I started to use it some time ago because I was curious about Openhab. Can I make these update processes without installing git on my computer or is it necessary?
Thank you for your help.

**Comment by triller-telekom** [comment]
@emme-g Indeed I was referring to a local installation of git instead of the edit steps you did online on github.

Nevertheless I just had a look on what you did and you now have a branch with your changes in your github account, great!

Now you can visit: https://github.com/emme-g/smarthome/tree/git-checkout--b-astroDocFix

And click the "New pull request" button.

On this page you see your commit including your commit message.

Just append an empty line at the end and below that a line with:
`Signed-off-by: Firstname lastname <your@emailaddress.tld>`

where you replace the name and email with yours that you used to create your eclipse account.

This will create the pull request which will then appear in this list: https://github.com/eclipse/smarthome/pulls

**Comment by emme-g** [comment]
@triller-telekom  Hi Stefan, I tried to do what you wrote me but unfortunately I still have problems:
I did what you wrote me but I had problems with the sign-off, so I deleted what I did yesterday and started again from the beginning. I think now I succeded to update the README.md file in emme-g/smarthome but I can't update the README.md in eclipse/smarthome. My pull request #4949 is open with this problem: "The pull request did not pass Eclipse validation. The following users have invalid Signed-off-by footers. Please use the Signed-Off-By (git commit -s) mechanism to confirm the origin of the submission. The identity in the Signed-off-By must match the Author or the Committer. noreply@github.com".
Sorry for all this chaos.

**Comment by triller-telekom** [comment]
@emme-g It looks pretty good now, don't worry.

The only missing thing is that the commit you did was not signed-off with your email address (honestly I also do not know how to do that online on github). But since you wrote the "Signed-Off-By" footer into the github message we can manually check if you have signed the CLA.
