### ISSUE TITLE
Rest: Color codes instead of names

### ISSUE THREAD

**Issue by mueller-ma** [eclipse/smarthome#4916]
> However, in my opinion, this documentation is quite inaccurate. The color code is just implemented in core products of openHAB (eclipse smarthome), however, there's no guarantee, that these color codes are used by other clients, too. If the color codes are guaranteed, then the server should send us the color code and not the name of the color (where the assigned color code for this color name van vary from client to client). IMHO: When using the color name, instead of the code, the user should currently accept, that the exact color used can be different on different clients.

from https://github.com/openhab/openhab-android/issues/637#issuecomment-357466331

**Comment by lolodomo** [comment]
The conversion to a code should certainly be done at this place: https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java#L1033

It would then impact the color values set in the sitemap REST API, sitemap SSE and it would impact Basic UI and Classic UI servlets too.

**Comment by maniac103** [comment]
From my comment in the mentioned Android app issue:

>> wouldn't it be smarter to have this conversion from color names to color codes in the openHAB server itself?

> IMHO it would be smarter to do this in the client, because the client defines the environment the color needs to blend well into (first and foremost: the background color).

**Comment by htreu** [comment]
I second @maniac103´s comment: imho the client is responsible for rendering whatever color name is given by the REST interface. The UI may even render a completely different color then the name states when necessary for the current theme. The backend should not provide concrete color codes as those would again not fit every UI.

**Comment by mueller-ma** [comment]
You're right. Color names are better, so they can be adjusted to the current client theme.
