### ISSUE TITLE
Proxy service: video data transfer not stopped

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#4919]
In Basic UI, even when you leave the page with a video delivered through the proxy service, the proxy continues streaming the video.
The expected behaviour is that the connection should be stopped.
Maybe the issue is in Basic UI rather than the proxy service.

**Comment by lolodomo** [comment]
@resetnow: maybe you have an idea ?
I think the problem is that the JavaScript is not closing connections to the proxy server. When I close completely Basic UI, the proxy detects an exception "proxying failedorg.eclipse.jetty.io.EofException: null" and the data transfer ends.
How the JavaScript could close properly all opened connections to the proxy server from a page when exiting a page.

**Comment by resetnow** [comment]
I would guess there's a dangling reference somewhere that can't be garbage collected. Since we replace all the DOM nodes when navigating between the pages, it could be an event callback, a timer or something like that.

**Comment by resetnow** [comment]
I think the problem here is this — https://github.com/google/material-design-lite/issues/271

There are a lot of detached DOM nodes, some are keeping the video stream. Solution would be to call downgradeElements before leaving the page.

**Comment by lolodomo** [comment]
When a page change is requested, I have the idea to first go through all control nodes and call pause() for video nodes and load "" as source for image (if MJPEG) and video nodes. I hope it could break the connection and stop the data transfer in the proxy server.
@resetnow : WDYT ?

PS: we have the same problem in Classic UI so the idea would be to apply the same kind of procedure.

**Comment by resetnow** [comment]
@lolodomo this wouldn't prevent memory leaks via detached DOM nodes. Proper solution is to call downgradeElements; is it's implemented properly in MDL, all references to these DOM nodes should be removed after page navigation occurs.

**Comment by lolodomo** [comment]
@resetnow : could you propose a fix for that please ?

**Comment by resetnow** [comment]
Since I'm going to need to test it, could you please tell me how video is defined in a sitemap? Is it an image widget with continuous MJPEG stream?

**Comment by resetnow** [comment]
@lolodomo I have opened #5109, you could check if it solved the issue. If it didn't, I'll add some more explicit code as you mentioned.

**Comment by lolodomo** [comment]
This was fixed by @resetnow 's PR that is now merged.
