### ISSUE TITLE
[Paper UI] Inbox does not update entries upon "updated" event

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#4921]
When an inbox entry is updated there is no notification. This leads to the inbox display in UIs being wrong until the UI is refreshed.

DiscoveryListener should have an updated method to alert the UI that things have changed.

Alternatively, the added method could be called again (maybe) since the method called is always ```thingDiscovered``` in the discovery service.

**Comment by kaikreuzer** [comment]
Hm, I would have expected that this is already in place?

https://github.com/eclipse/smarthome/blob/4204ce06bb28c28e5f711e720f87ef83beff2e27/bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java#L472-L473

**Comment by kaikreuzer** [comment]
I do not see why the DiscoveryListener would need to be changed in order to notify UIs.

**Comment by cdjackson** [comment]
Ok, I assumed that this was the mechanism for updating the inbox. I didn't see an SSE event, and PaperUI doesn't update the inbox in this case.

Maybe I missed the SSE and the problem is just that PaperUI doesn't update.

**Comment by kaikreuzer** [comment]
@htreu Can you confirm that the Paper UI should receive those events and react on them?

**Comment by htreu** [comment]
We have at least this code on Paper UI which should display a message with the chance to redirect the user to the inbox:
```
eventService.onEvent('smarthome/inbox/*/added', function(topic, discoveryResult) {
    toastService.showDefaultToast('New Inbox Entry: ' + discoveryResult.label, 'Show Inbox', 'inbox/search');
});
```

I have to check what happens when the inbox is actually open when these events occur.

**Comment by kaikreuzer** [comment]
This only reacts on added events, but we are talking about `smarthome/inbox/{thingUID}/updated` here.

**Comment by htreu** [comment]
There is a second snippet listening for `smarthome/inbox/*` events:

```
eventService.onEvent('smarthome/inbox/*', function(topic, discoveryResult) {
        var index = repository.findByIndex(function(result) {
            return discoveryResult.thingUID == result.thingUID;
        });
        if (topic.indexOf("added") > -1 && index == -1) {
            repository.add(discoveryResult);
        }
        if (topic.indexOf("removed") > -1 && index != -1) {
            repository.remove(discoveryResult, index);
        }
});
```

This will currently only add/remove results to the Paper UI `discoveryResultRepository`. This seems to be the correct place to extend for `updated` events.

**Comment by cdjackson** [comment]
Thanks.
