### ISSUE TITLE
[LSP] Rule validation incorrectly identifies issue (The expression of type SwitchItem is already of type SwitchItem)

### ISSUE THREAD

**Issue by openhab-5iver** [eclipse/smarthome#4922]
ESH: 0.10.0.201712141004
OH: 2.3.0 snapshot 1181

This rule will recreate the problem when the rule file containing it is saved. But the rule will execute properly. This does not block any functionality, but is just incorrectly logging a validation issue that does not exist.
```
rule "Test"
when
    Item Test_Switch_1 changed
then
    if (Test_Switch_1 instanceof SwitchItem) {
        logDebug("Rules", "TEST: SwitchItem")
    }
end
```
The full error from the log is...
```
2018-01-14 15:40:07.860 [INFO ] [.smarthome.model.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'Test.rules', using it anyway:
The expression of type SwitchItem is already of type SwitchItem
```

**Comment by kaikreuzer** [comment]
Err, that the heck is a `MotionItem`? I would actually expect the validation to show an error on this before even coming to warnings afterwards...

**Comment by openhab-5iver** [comment]
Yeah, that is one of the most stupid and embarrassing things I've done in a while. lol. That's gonna leave a scar... 

OK, moving on... so there's still this other validation issue. Did I do something else ridiculously stupid here too? :)

**Comment by kaikreuzer** [comment]
Well, you seem to underestimate the rule syntax here.
`Test_Switch_1` is not just "any" variable name, but it is injected from the item definition, so indeed the system already knows that it is a SwitchItem and thus the if statement is superfluous. Cool, isn't it? 😎

**Comment by openhab-5iver** [comment]
Hmmm... I get the same with Virtual_Switch_1. Or is that another hidden gem?

**Comment by kaikreuzer** [comment]
You're welcome, glad I could help (and even more glad that there isn't a bug ;-))!
