### ISSUE TITLE
[BaseThingHandler] Discussion: check state of channel before update

### ISSUE THREAD

**Issue by mgeramb** [eclipse/smarthome#4923]
Hi community,
I have to poll the state for my Things in my binding. In the polling thread, I update all the channel states without checking the previous state. Now I recognized, that channel with the image control which is bound to a String channel with an url flicker after each update in the ios app, regardless if the url was the same as the previous. It seems that the update is done through all layers.
Should I check the previous state in my binding before I call the updateState function in the BaseThingHandler? If yes, maybe it is better to change the implementation in BaseThingHandler to do the check?
Regards,
Michael

**Comment by lolodomo** [comment]
Normally the framework is checking if there is a change of state so you can call update state in your binding without checking. The flicker in the iOS app is probably due to another reason. Check your file events.log to check if event is updated.

**Comment by kaikreuzer** [comment]
The iOS uses the long-polling mechanism in the SitemapResource, which should only reload, if there is a state change (not merely an update).
Thing handlers should update the state as often as they have an updated value. The framework then automatically determines whether a state change has happened and it uses different events for those.

**Comment by mgeramb** [comment]
@kaikreuzer : Hi Kai, I'am really sure now, that there is problem with the change check of channel, at least for String Items. In my binding I have a String channel which shows an text editor in the paperUI if you click in the field. Everytime, I my binding calls updateState with a new StringType instance, the editor closes, so it get a notification for a change. This happens regardless, if the String value has the same value or not. Maybe there is a bug in the comparing of the state for String, maybe the reference will be compared instead of the value? Regards, Michael

**Comment by kaikreuzer** [comment]
I'd rather suspect that the Paper UI reacts not only on change events, but also on update events.
@htreu Can you confirm this? If so, should it be considered as a bug?

**Comment by mgeramb** [comment]
Which layer should do the compare if the state is changed? The user interface or the backend which holds the state? Because I'am sure, that the UI gets an update (the iOS App and the PaperUI). Is there an event which is passed trough the layers regardless if the value of the state have changed which you described as "update event"?

**Comment by sjka** [comment]
Yes:

* [ItemStateEvent](https://www.eclipse.org/smarthome/documentation/javadoc/org/eclipse/smarthome/core/items/events/ItemStateEvent.html) <- on every state update, regardless if it changed or not
* [ItemStateChangedEvent](https://www.eclipse.org/smarthome/documentation/javadoc/org/eclipse/smarthome/core/items/events/ItemStateChangedEvent.html) <- on every state _change_

The item itself does the check:

https://github.com/eclipse/smarthome/blob/a711ae11d2c1b54ebee153ef4f4cb82857a0a644/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java#L204-L206

**Comment by mgeramb** [comment]
Thank's for the clarification!

**Comment by htreu** [comment]
Paper UI does indeed update the items state on the `smarthome/items/*/state` SSE topic, which is the `ItemStateEvent` SSE endpoint.
In the code history I could not find a hint on why this was done (its the main item update code base and part of Paper UI forever).
@kaikreuzer I would consider this a bug. I will create a new issue.
