### ISSUE TITLE
Bindings uninstall when installing new

### ISSUE THREAD

**Issue by Josar** [eclipse/smarthome#4925]
When a Binding was installed via Karaf and you try to add a new Binding via PaperUI all other Bingings get uninstalled. 

```
[INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'binding-astro' has been uninstalled.
[INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'binding-alarmdecoder1' has been installed.
```

Installing Bindings via PaperUI and then install one via Karaf, navigate to the PaperUI Binding Page and waiting some time leads to an uninstall of the installed Bining.

```
openhab> feature:install openhab-binding-amazondashbutton
```
```
[INFO ] [.core.karaf.internal.FeatureInstaller] - Uninstalled 'openhab-binding-amazondashbutton'
[INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'binding-amazondashbutton' has been uninstalled.
```

Sometimes a encountered that  a binding just uninstalled but could not find out why. Maybe this is related.

Others have also encountered this problem.
https://community.openhab.org/t/installing-binding-leads-to-automatic-uninstalling-another-binding/38777

**Comment by sjka** [comment]
I know this separation can be confusing sometimes: Eclipse SmartHome doesn't know anything about Karaf. The Karaf feature extension management is something which openHAB brings on top. So could you please open this very same issue in the https://github.com/openhab/openhab-core/issues project?

**Comment by Josar** [comment]
How should anyone be able to know what is where?

**Comment by sjka** [comment]
Didn't expect that you know - that's why I was telling you 😄

**Comment by kaikreuzer** [comment]
> How should anyone be able to know what is where?

Well, potentially by reading the docs: https://docs.openhab.org/appendix/contributing.html#reporting-issues

Feel free to improve it, if it isn't helpful enough.

**Comment by Josar** [comment]
But as the PaperUI is used to install and the event is smarthome it could also be a smarthome problem!
Using Paper UI  it uninstalls prevlously installed Bindings. I do not know 
> [INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'binding-astro' has been uninstalled.

@kaikreuzer  As the problem is not that i am not aware of the various project where it could possibly relate to. But i don´t know what code belongs to which and i don´t think i will ever be able to know.
