### ISSUE TITLE
Unable to remove properties from a thing

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#4943]
There is no ```removeProperty``` method in the BaseThingHandler to allow removal of a property. Additionally, the ```updateProperties``` method will not allow a property to be removed since it checks for changes by iterating over the new properties map.

```updateProperties``` should be updated to also iterate over the existing properties so that it can see if a property has been removed.

**Comment by kaikreuzer** [comment]
Would it maybe be a better idea to interpret a property with null value as not set and thus to be removed? This would make the intention more explicit and would avoid accidental removal of existing properties.

**Comment by htreu** [comment]
@cdjackson can you give an example of a volatile property of a thing?

**Comment by cdjackson** [comment]
My use case here was after changing the firmware of a device - I wanted to be able to remove some properties that weren’t applicable and to indicate that others needed to be refreshed when the handler restarts.  

If it is not allowed to remove properties, then at least this should be documented as I expect that updateProperties(newProperties) does just that - updates the properties with the new values I’m setting, and at the moment this is not the case.

**Comment by triller-telekom** [comment]
As far as I can see from

https://github.com/eclipse/smarthome/blob/8ba6df54cb73197c644a5c1d8a223802cab7ff3d/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java#L596-L616

if one provides a map where a property is set to `null` then this method is called:

https://github.com/eclipse/smarthome/blob/8ba6df54cb73197c644a5c1d8a223802cab7ff3d/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java#L175-L184

where the Javadoc says that of the value is `null`, the property will be removed. Isn't that what @cdjackson thought is missing? Or am I wrong here?

**Comment by htreu** [comment]
With @cdjackson 's approval and even @triller-telekom pointing out the relevant part of the API this can be closed.
/cc @maggu2810, @kaikreuzer
