### ISSUE TITLE
Improve ThingHandler API to allow easy addition of Channels

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4950]
In our [thing modelling FAQs](https://www.eclipse.org/smarthome/documentation/development/bindings/faq.html#structuring-things-and-thing-types), we suggest as (4) to dynamically add channels to a Thing within the handler.
As [discussed here](https://github.com/openhab/openhab2-addons/issues/2930#issuecomment-358709502), this is currently a bit cumbersome, though, as there isn't an easy way to construct a channel from a channel type, which means that the best code I could come up with is [this](https://github.com/eclipse/smarthome/pull/4535/files#diff-4cfd867ae80654e19a6695ee0d6b32c2R217).

We should simplify this either by improving the ChannelBuilder or possibly by directly supporting it in the ThingBuilder (not sure yet, what is the better option).

**Comment by sjka** [comment]
Another ~~victim~~ interested party: openhab/openhab2-addons#2859 (Denon/Marantz binding)
