### ISSUE TITLE
Higher precision for PercentType required for some actors

### ISSUE THREAD

**Issue by vasu1124** [eclipse/smarthome#4956]
Hello SmartHome Team,

the PercentType being used to represent many actors (Dimmer, Blinds, etc.) at first sight looks sufficient. Decimal values between 0 and 100 should give ample means to set any desired settings.

Unfortunately, there are certain actors, e.g. Rollershutter or Blinds which need higher precision to be set to a correct angle: 
![Window Blind](https://upload.wikimedia.org/wikipedia/commons/d/d2/VenetianBlindAiyaz.jpg)
(cf. [OpenHab Issue](https://community.openhab.org/t/switched-from-fhem-questions-around-rollershutter/38235/4) )

If you look at the precision of the underlay protocol of Rollershutter devices (e.g. Z-Wave or Homematic), you will also find that the devices pragmatically allow for two digit precision behind the comma. so e.g. you can set Blinds to values such as 1,2% to 1,7% in order follow the angle of the Sun. Users of the eclipse smarthome library are loosing semantic information imho.

My suggestion would be to either refactor the precision of PercentType (by changing its superclass DecimalType) which might have many undesired side effects, or to introduce a new PromilleType class (or similar).

Thanks for the great open source project!
Vasu

**Comment by kaikreuzer** [comment]
Hey Vasu,

Thanks for your input!
Please note that PercentType (as well as DecimalType) both allow fractions, so sending 1.2% as a command to a rollershutter should be perfectly possible. If this is not the case, I would rather consider it a bug in the respective binding.

**Comment by vasu1124** [comment]
Hi Kai,

ah ok, had to look up BigDecimal, that was my misunderstanding.

Yes, sending fractions is possible, but I think that is because the command is sent via a direct path to the underlay. I looked at java/org/openhab/binding/homematic/internal/converter/type/PercentTypeConverter.java:
```
protected Object commandToBinding(Command command, HmDatapoint dp) throws ConverterException {
...
            return super.commandToBinding(command, dp);
...
}
```

The then following sync/readout leads to the internal state of the PercentType object to be rounded to 1%, which is then what is shown in openHAB (can't use that to do e.g. incremental +0.1% changes). Maybe the classification as bug is right, and only a `java.math.MathContext` needs to be used ...

Cheers, Vasu

**Comment by kaikreuzer** [comment]
I'd recommend to open an issue about that for the Homematic binding at https://github.com/openhab/openhab2-addons/issues.
