### ISSUE TITLE
Enhance HSBType to add additional conversions

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#4957]
I'd like to suggest that ```HSBType``` is enhanced to provide conversions to/from XY, and potentially to/from CT.

A helper class for converting XY was recently added to the [ZigBee binding](https://github.com/openhab/org.openhab.binding.zigbee/blob/master/src/main/java/org/openhab/binding/zigbee/converter/ColorHelper.java), but I'm sure other bindings would also make use of this and I think it might be better suited as helpers in ```HSBType``` in the same way as I added for RGB some time back.

If this is acceptable I'll look to migrate this over

**Comment by kaikreuzer** [comment]
If it is similar to RGB, I don't see any reason against adding this as well to HSBType.

**Comment by cdjackson** [comment]
Closed by #4959
