### ISSUE TITLE
RFC: ThingType versioning

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#4958]
I would like to propose a mechanism for thing type versioning and updating. At least in ZWave, thing types change occasionally - channels get added or updated, and it would be good to provide the user with a notification that this has happened, and secondly provide a mechanism for updating to the latest definition. 

Currently there is no notification, and updating requires deleting the thing and adding it back again.  I'm considering adding this into the ZWave binding and since the binding already changes thing types, it would be relatively easy. However, I think it would be better if this were a general feature of the system and not part of any binding.

What I'd propose would work as follows...

* We add an (optional) ```<version>``` tag to the thing type XML. This is a number that is incremented each time the thing type definition is updated.
* When the thing is instantiated, the ```version``` is recorded in the thing.
* In the UI, it is therefore simple to show the user if the thing has an out of date definition with ```thingType.version > thing.version```.
* The user can then decide to update to the latest thing definition via an update REST endpoint.

**Comment by lolodomo** [comment]
This is something we could use each time a developer adds a new channel to a thing type for example ?

**Comment by cdjackson** [comment]
Yes - that's exactly the purpose - if the thing definition changes (new channels, changed channels...) then update the version and the system can tell the user.

I wouldn't personally advocate an automatic update to the latest thing type based on this as it will likely screw peoples systems if channels change, but they should at least be alerted and given the option to use the latest definition.

**Comment by MHerbst** [comment]
Such a mechanism could really be very helpful. E.g. with the Homematic binding it has been necessary to remove things an re-create them again a few times.

**Comment by kaikreuzer** [comment]
I would claim that https://github.com/eclipse/smarthome/issues/2555 would solve most of the issues without introducing yet another layer of complexity through versioning.

**Comment by cdjackson** [comment]
Yes - I’d not seen that. However if I understand the suggestion, it would automatically update the thing description each time the handler started (or something along those lines). This will have the downside of breaking peoples systems if channels have changed and they upgrade. It might lead to much unhappiness for this reason.

**Comment by kaikreuzer** [comment]
Could you comment that on #2555 so that discussions happen at the right place?
