### ISSUE TITLE
Add documentation about tile server usage for Locations

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4961]
#3730 introduced a mechanism that allows displaying maps for locations (both for items and configuration parameters).

ESH does not come with this feature enabled, but it is merely an extension point that can be used by solutions that can be used to plug in their tile server.

This extension mechanism should be documented. As long as this is only a feature of the Paper UI, the best location would probably be https://www.eclipse.org/smarthome/documentation/development/notes.html#paper-ui-development-jshtml.

**Comment by lolodomo** [comment]
Is this feature already available in openHAB ? Official 2.2 ?

**Comment by kaikreuzer** [comment]
Not yet, see https://github.com/openhab/openhab-core/pull/224.
