### ISSUE TITLE
Remove Firmware UID - Firmware provider should provide firmwares for things

### ISSUE THREAD

**Issue by tomhoefer** [eclipse/smarthome#4964]
In ESH, firmwares are identified by their FirmwareUID, which consists of the firmware's thing type UID, and the firmware version. The firmware UID must be unique amongst all firmwares. I.e., each firmware for a given thing type must have a unique version. This is not the case for the following scenario:

In our project there are two firmwares for a special thing type with version 1, and two firmwares for that thing type with version 2 (two firmwares because of two different models). In consequence, for each version only one firmware is considered (and displayed as result of the 'firmware list' console command). Hence the solution introduced by #4446 works only if the different models have also different firmware versions. 

For this reason we cannot consider the firmware UID as unique. I would like to remove the Firmware UID completely and refactor the firmware provider / registry in the manner that it provides firmwares for things instead of thing types. Then the provider can determine which firmware is to be provided for the given thing (even if there are multiple firmwares available for the same thing type and version). This would also fix the issue reported here https://www.eclipse.org/forums/index.php?t=rview&goto=1779174.

Should also fix #4647

**Comment by htreu** [comment]
Hi @tomhoefer. Your issue, as well as the linked discussions all seem to agree that a refactoring of the current firmware API makes sense. Since there are no other consumers (at least known) of the firmware API I guess we could change and go from thing-type to the thing entity here. This will even add more information available to the FirmwareProvider, so migrating should be quite simple.
It would be nice to see a PR proposing the changes.
Any objections @kaikreuzer, @sjka & @maggu2810?

**Comment by cdjackson** [comment]
> Since there are no other consumers (at least known) of the firmware API

Please note that any change here will break the ZigBee binding. I've no objection to this and had raised the same issue with @tomhoefer but I'd like to coordinate the release so as not to break the binding.

**Comment by tomhoefer** [comment]
@cdjackson I am aware of the FirmwareProvider inside the ZigBee binding. Currently I consider that provider as a development tool that we need to adapt accordingly. There are some more providers used in our project that need to be adapted, too.

**Comment by cdjackson** [comment]
Thanks @tomhoefer - I know you're aware, but I just wanted to comment here for everyone elses visibility...

**Comment by maggu2810** [comment]
> Any objections @kaikreuzer, @sjka & @maggu2810?

We don't use the firmware API currently in our products and there is no official ESH binding (or I missed it) that uses this feature (too bad). So it is more about the downstream projects that could get broken. I think we should give the product owner a few days if someone complains about that API break.

**Comment by sjka** [comment]
For the record: 👍 from DT side

**Comment by kaikreuzer** [comment]
Implemented by https://github.com/eclipse/smarthome/pull/5343.
