### ISSUE TITLE
ConfigDispatcher doesn't remove configuration variable in runtime

### ISSUE THREAD

**Issue by paulianttila** [eclipse/smarthome#4966]
When user remove configuration property from configuration file in runtime, property is not removed from the configuration existing in memory. So basically, when you want to remove configuration property, you need to restart environment. Is this a bug or feature?

I meet this problem in openHAB dashboard. User can add additional tiles to dashboard by configuration properties, but when user removes property from the file, tile is not removed as property still exist in configAdmin's memory and will be provided to bundle.

**Comment by kaikreuzer** [comment]
I have created https://github.com/eclipse/smarthome/issues/4968 so that it is easier to explain in future :-)
