### ISSUE TITLE
Document configuration dispatcher mechanism and feature

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4968]
We are lacking documentation about the logic of the ConfigDispatcher, with automatic pid prefixing, exclusive definitions, etc.

We should add a short section in the docs, possible to the page https://www.eclipse.org/smarthome/documentation/features/dsl.html (while it should be renamed to something other than dsl) or next to that one.

@htreu Could you come up with something for that?

**Comment by sjka** [comment]
+1 -> #4980
