### ISSUE TITLE
group membership not updated on every circumstances after group type change

### ISSUE THREAD

**Issue by HomeOfSourceCode** [eclipse/smarthome#4972]
I run into a problem in openHAB. 

First the group was defined as
Group:Switch:OR(ON, OFF)    gSwitchesAll
and works well.

I decided to changed it to
Group:Number:SUM            gSwitchesAll

and it looks like it is working too.

But the group did not get some updates from item changes and soem rule tigggers are not working. After restart of OH the error was gone.

It looks like the group update is not working correct sometimes.

**Comment by triller-telekom** [comment]
@HomeOfSourceCode Thanks for reporting this bug. I have created #4975 to fix it.
