### ISSUE TITLE
GenericItemProvider does not send updated event if StateDescription of an Item changes

### ISSUE THREAD

**Issue by triller-telekom** [eclipse/smarthome#4979]
The following test should [notify the listeners](https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java#L371) that an `Item` was changed if its `StateDescription` has been changed.

However the method [`hasItemChanged()`](https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java#L396) does not check that yet.

If one would implement it like this:

```
private boolean hasStateDescriptionChanged(Item item1, Item item2) {
        StateDescription sd1 = stateDescriptions.get(item1.getName());
        StateDescription sd2 = stateDescriptions.get(item2.getName());
        return !Objects.equals(sd1 != null ? sd1.getPattern() : null, sd2 != null ? sd2.getPattern() : null);
    }
```

It will always return `false`. This is because the `stateDescriptions` map has been updated **before** `hasItemChanged()` is called and this it will always fetch the description of the **new item** since the name stayed the same.

Changing the implementation to use the `Item` to obtain its `StateDescription`:

```
item1.getStateDescription();
```

will not work because [its implementation](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java#L381) loops over all `StateDescriptionProviders` and this `GenericItemProvider` will answer it from the [`stateDescriptions` map](https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java#L446).

The result of this is that no notification will be send to the listeners although the `StateDescription` of the `Item` has been successfully updated.

**Comment by sjka** [comment]
The state descriptions are not an integral part of the item entities and can change anytime (e.g. via a `DynamicStateDescriptionProvider`) without prior notice, therefore they are correctly are not considered to be a "change" of an item. A UI refresh though should (and I just tested that it actually does) show the new description.
