### ISSUE TITLE
Config not updating properly after changing cfg file

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#4980]
Not sure if this is the right repo, or if the issue has already been logged somewhere.  I wasn't able to find it after searching this and a couple other repos.

I was helping someone troubleshoot a problem they were having with the openhab1 gcal-persistence binding.  The forum discussion starts [here](https://community.openhab.org/t/presence-simulation-with-google-calendar-scheduler/19281/52).

I did some testing on OH build 1194 to try to recreate the behavior.  Here's what I found.

Let's say I start with a gcal-persistence.cfg config file containing this.
```
calendar_name=openHAB
offset=3
#executescript=
```
Then I change it to this, at which point, the binding is restarted and picks up the changed config.  All good so far.
```
calendar_name=openHAB
offset=3
executescript=junk
```
Now I want to revert that change, so I do this.
```
calendar_name=openHAB
offset=3
#executescript=
```
The result is that the binding still thinks `executescript=junk`.  It even survives a restart of OH.

It appears that the `userdata/config/org/openhab/gcal-persistence.cfg` file still contains this.
```
calendar_name="openHAB"
executescript="junk"
offset="3"
service.pid="org.openhab.gcal-persistence"
```

So, it appears to me that possibly ConfigDispatcher is not properly dealing with the case where a property is commented out?

**Comment by sjka** [comment]
If I'm not mistaken, it is the same "root-cause" (or rather: design decision) as in #4966. Could you try adding a pid to make it an exclusive configuration as suggested by @htreu [here](https://github.com/eclipse/smarthome/issues/4966#issuecomment-359515147)?

**Comment by htreu** [comment]
I guess @sjka is right: removing options is only provided when using an exclusive pid marker in the .cfg file. Otherwise the ConfigDispatcher is unable to decide if a configuration is removed since the configuration can possibly spread over separate files. Documentation is ongoing (see #4968).

**Comment by mhilbush** [comment]
> it is the same "root-cause" (or rather: design decision) as in #4966

Ah, yes, you're right! I searched only the open issues. :-(

Let me experiment with putting the pid marker as the first line in the cfg file.  Can you clarify which of these I should use?
```
pid:gcal-persistence
pid:org.openhab.gcal-persistence
```

**Comment by htreu** [comment]
`org.openhab.gcal-persistence` is the PID defined in the service xml, see https://github.com/openhab/openhab1-addons/blob/master/bundles/persistence/org.openhab.persistence.gcal/OSGI-INF/gcalpersistence.xml#L12

So `pid:org.openhab.gcal-persistence` is the correct entry.

**Comment by mhilbush** [comment]
Yes, that works.  Thank you for the help.

But how would someone know to do that. I realize it's being added to the documentation. However, it seems unlikely someone would know to look in the docs for that, as commenting something out in a config file to remove, or revert to default, is a well-accepted practice.  Should those cfg files be created containing the pid markers as that would seem to eliminate the confusion? Unless, of course, they already are created that way in more recent versions.

As an aside, I think there's a bug in gcal-persistence in the activate method here.
https://github.com/openhab/openhab1-addons/blob/master/bundles/persistence/org.openhab.persistence.gcal/src/main/java/org/openhab/persistence/gcal/internal/GCalPersistenceService.java#L97

After the config is changed to comment out a parameter, the binding is deactivated-activated; however, it retains the old value.  Doesn't the activate method need to explicity set the default values of `offset` and `executescript` before it tries to pull the values from the config file?  Currently the default is set only when the fields are declared.

**Comment by htreu** [comment]
> After the config is changed to comment out a parameter, the binding is deactivated-activated

You are configuring a persistence service. I don't think the component is deactivated during configuration update. The Configuration Admin will just try to pass the new configuration to the component's `modified` method.
I guess thats the problem here: The `GCalPersistenceService` does not define one. So its more of a missing feature than a bug ;-)

**Comment by mhilbush** [comment]
I can see (in the IDE) that deactivate/activate is running.  It runs every time I modify the cfg file.

**Comment by sjka** [comment]
Yes, "deactivate -> activate" is indeed the correct behavior for services which don't have a "modified" method - and entirely valid. 

OSGi however is not reusing any component instance, after "deactivate" it will discard the old instance and create a new one which then is going to be "activated". Therefore the behavior you described above in theory shouldn't occur. Nevertheless, if you still experience some wrong behavior there wrt its default values, then I'd suggest opening an issue for it in [openhab/openhab1-addons](https://github.com/openhab/openhab1-addons/issues/new).

**Comment by mhilbush** [comment]
> "deactivate -> activate" is indeed the correct behavior for services which don't have a "modified" method

Thanks. That's what I needed to know.

> after "deactivate" it will discard the old instance and create a new one which then is going to be "activated". Therefore the behavior you described above in theory shouldn't occur.

Thanks for that!  Your comment made me look a bit closer. It's because `executeScript` and `offset` are declared static.
```
    private static int offset = 14;
    private static String executeScript = "send %s %s";
```
