### ISSUE TITLE
Sitemap should include group members for location widgets

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#4989]
The location widget currently supports only a single location by taking a Location item name as its item parameter.
Technically, it is already possible to hand in a Group item name instead.
Using a Group might be a neat use case to show several locations on the same map - I'd therefore suggest that the sitemap should directly provide the group members (maybe filtered for only Location items?) in the response, so that UIs do not need to do the resolution by themselves.

**Comment by lolodomo** [comment]
Not sure how you would like this to be added.
I could add a new field of type `List<PointType>` in `WidgetDTO` (sitemap REST API) and in `SitemapWidgetEvent` (sitemap SSE) that will be set only when the widget is a mapview. This solution would avoid breaking the API.
Is it enough to have only the coordinates ?

PS: the proposal change is relatively easy to implement.

**Comment by kaikreuzer** [comment]
I was rather thinking of "provide the group members" of the group item. Afaik, the WidgetDTO already contains the GroupItem, but only shows an empty `members` field - so if this would be filled (at least with all location items), this should hopefully work without introducing any further fields.

**Comment by lolodomo** [comment]
Ok I see what you mean. The method used to fill this object is used by the REST item API too so we just have to take care to not impact this other API. A new parameter to this method should do the job.
