### ISSUE TITLE
[TRÅDFRI] New bulb support

### ISSUE THREAD

**Issue by Daronspence** [eclipse/smarthome#4998]
Hello, first time contributor here and new to openHAB, so apologies if the format is incorrect for your organization.

I got setup with a Tradfri starter kit and some extra bulbs and everything seems to be detected correctly in openHAB except for the smaller bulbs I bought. OpenHAB detects them fine after connecting the gateway, but the type is incorrect.

`TRADFRI bulb E12 WS opal 400lm ` 
is reported as being 
`Non-Colour Controller 0820` device

when it should be a `0220` device (white spectrum w/ dimming)

I can manually set it up as the 0220 type and send commands to it and it responds as expected. However, that leaves an un-adopted thing in the interface and obviously it makes more sense to fix the underlying issue.

I looked at the open/closed issues for the Tradfri Binding and didn't see anything about this bulb so hopefully it is not a duplicate.

Happy to provide anymore info as needed.

**Comment by kaikreuzer** [comment]
Thanks for your report!
There is indeed a problem that we cannot identify 0220 bulbs correctly on the gateway, so we have to maintain a list of those devices - the one that you mention seems to be new, I have created #4999 for it.

**Comment by sjka** [comment]
> the one that you mention seems to be new

...or at least unknown to us because E12 is common mainly in 110/20V areas, i.e. UK & US. I'd expect the same trouble with the E26 ones. We'd need somebody who owns one in order to find out how exactly they are named.

**Comment by Daronspence** [comment]
Since I'm new around here, what is the release schedule like for patches to be pushed on to openHAB? 

Thanks for the fix regardless :)

**Comment by kaikreuzer** [comment]
@Daronspence Check https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB - usually there is a stable build done every second week, which will then make the change become available in openHAB snapshots.
