### ISSUE TITLE
DateTimeType should also support dates and times separately

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#5001]
The valueOf method of `DateTimeType` currently requires a fully specified date+time combination.
This type is nonetheless also used for time-only use cases (e.g. an alarm clock for "08:00") or for date only use cases (e.g. next waste collection on "03.02.2018").

I do not see any strong reason why we should not support type creation with only date or time component, so I'd hope that this could be added.

**Comment by maggu2810** [comment]
I see your point (e.g. alarm at 8 am), but I assume it is not such a simple task.

Hm, all the date pattern and formatter use a date and time representation.
The member that stores the date time is a `ZonedDateTime` member.
So you do you suggest to implement the serialization and deserialization for e.g. a time only value?

**Comment by kaikreuzer** [comment]
No, I am talking only about the deserialisation, i.e. the `valueOf` method (or the constructor with String parameter). Internally, it should be a full Date/Time as today. If no date/time parts are provided, they would go for the default (is it 1/1/1970 and 00:00:00?). Serialization shouldn't be touched, we have the state descriptions for that, which can do the proper formatting (and leave out the parts that aren't relevant).
