### ISSUE TITLE
Mockito 2.13

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#5004]
As just seen in  #3918, openhab/org.openhab.binding.zwave#812 and others (and potentially in your IDE), it's been a struggle and required some luck to get plain unit tests running within the IDE. This whole mess can be solved with upgrading to mockito 2.x.

I will create CQs for it and its transitive dependencies:

* Mockito 2.13.0
* Byte-Buddy 1.7.9
* Byte-Buddy Agent 1.7.9
* Objenesis 2.6

(They'll be "Type B, full-review", so we can redistribute them via our own P2 update site)

**Comment by sjka** [comment]
For the record: 

| Library | Version | CQ |
|:---|:---|:---|
| Mockito | 2.13.0 | CQ 15481 |
| Objenesis | 2.6 | CQ 15482 |
| Byte Buddy | 1.7.9 | CQ 15483 |

**Comment by kaikreuzer** [comment]
FTR: CQ 15481 has been approved.

**Comment by sjka** [comment]
Update: CQ 15482 (objenesis) is approved and for the others (CQ 15481, CQ 15483 and CQ 15489) we got the preliminary check-in approval under the terms of "parallel IP".

Hence I will shortly create PRs to update the update-site and target platform.
