### ISSUE TITLE
Mapview label and icon are not displayed in basic UI

### ISSUE THREAD

**Issue by mueller-ma** [eclipse/smarthome#5030]
Hey,
I'm using oh 2.2 and the basic ui doesnt show label and icon for mapview elements. Both are supported according to the docs: https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/Sitemap.xtext#L80

**Comment by lolodomo** [comment]
That's right.
How do you imagine it could presented ?

**Comment by mueller-ma** [comment]
Like this
![map](https://user-images.githubusercontent.com/22525368/36036958-9afe0716-0dbb-11e8-8d5e-ea4c8559be5f.JPG)

**Comment by ThomDietrich** [comment]
I want to second this. It's probably often useful to add a Label to describe the purpose of the Map, e.g. "Current iPhone Location"

**Comment by lolodomo** [comment]
Ok I will try to add them.
