### ISSUE TITLE
ThingLinkManager should remove outdated links

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#5035]
If autoLinks is set to true, the ThingLinkManager automatically creates links for any non-advanced channels.
If a thing is updated and has less channels than before, it does not seem to remove those links, though.
Imho, it would make a lot of sense if it did.

**Comment by sjka** [comment]
Really, did you test it?

https://github.com/eclipse/smarthome/blob/4204ce06bb28c28e5f711e720f87ef83beff2e27/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java#L271-L278

**Comment by kaikreuzer** [comment]
It seems I have missed that piece of code when looking at the class.
Thanks for pointing it out, issue can be closed.
