### ISSUE TITLE
[SONOS] Alarm channels not working

### ISSUE THREAD

**Issue by spy0r** [eclipse/smarthome#5042]
Hi,

i am on the stable openhab 2.2 version and can't see any of the sonos alarm channels working. In the Documentation there are for example the following channels:

alarmproperties | String | R | Properties of the alarm currently running | all
alarmrunning | Switch | R | Set to ON if the alarm was triggered | all

I linked them to appropriate items but they never change. Can anyone confirm to have these channels working? 
Which more information do you need from me?

Thanks so much,
Stef

**Comment by lolodomo** [comment]
I think someone already mentioned in the forum that Sonos changed the API.
But thank you for declaring the issue.

**Comment by lolodomo** [comment]
I can confirm that GetRunningAlarmProperties UPnP call returns now an error.
I don't know how to retrieve the current running alarm.

**Comment by lolodomo** [comment]
Maybe we should suppress these channels if they are no more working and we don't know how to fix them ?

**Comment by maggu2810** [comment]
@kgoderis Do you know anything about the firmware changes and the affected alarm handling?

**Comment by kgoderis** [comment]
@maggu2810 No, I was not aware of any changes in the API. I do not think we should remove these, but rather "Wireshark" the LAN to see what they did change. It could be very well be something cosmetic, like a change of the some string.

**Comment by lolodomo** [comment]
In fact the used UPnP call is returning an error.

**Comment by lolodomo** [comment]
Please note that the channel alarmrunning is perfectly working.
We have a problem only with the channel alarmproperties.

**Comment by lolodomo** [comment]
Getting the list of alarms is possible.
We are still notified when an alarm is started or ended. That is why the channel alarmrunning is still updated.
I tried to identify the running alarm from the alarm list but there are too many cases to consider to identify the right one. So I am still in favor to suppress the channel alarmproperties.
By th way, we are currently running an UPnP call every minute that we are sure that it will fail. It is something to fix.

**Comment by sjka** [comment]
Apologize my stupid question, but what do I need to do in order to reproduce this? I have here a PLAY:1 with version 8.5 (Build 42251240) and the GetRunningAlarmProperties call still (or again?) appears to be working nicely.

**Comment by lolodomo** [comment]
?
I tried this weekend with a Play:5.
How did you reproduce the call ? With an UPnP tool ?

**Comment by sjka** [comment]
No, just plain ESH (without #5711, obviously). I set an alarm and put a breakpoint [here](https://github.com/eclipse/smarthome/blob/67b00dd297894022d2c9594048b2e18f90f06e83/extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java#L899).

It returned this map, while the alarm was active:

```
{AlarmID=1, LoggedStartTime=2018-06-11 09:26:00, GroupID=RINCON_949D9A260A3E02201:447271713}
```

**Comment by lolodomo** [comment]
Maybe I am so stupid that I did not run the call while an alarm was active !!!!!!
I will try again this evening.
If you are right, there is no bug.

PS: by the way, I see no reason to run this call every minute, it should be run only when an alarm is started or ended.

**Comment by sjka** [comment]
In that case there is no active alarm, I get an empty map, but still no error. You wrote above that

> [...] GetRunningAlarmProperties UPnP call returns now an error.

so you _must_ have seen something at that point in time! I'm just trying to understand if there really is an issue. I only have a PLAY:1 at hand, but I also wouldn't think there was a difference between the player types.  Maybe there was a bug in a specific firmware version? Anyway, I'm curious what you will see tonight. 

> PS: by the way, I see no reason to run this call every minute, it should be run only when an alarm is started or ended.

👍

**Comment by lolodomo** [comment]
Yes when I tried with UPnP Spy, I got an error code 800 if I correctly remember. Weird code. To be checked again later today.

**Comment by maggu2810** [comment]
If you instruct me what to do, I can check on a Play:1, Play:5 (first model), Play:5 (second model) and a Playbar.

**Comment by sjka** [comment]
Just set an alarm. Once it fires (i.e. while it is playing the nasty sound to wake you up) observe is the alarmproperties channel(s) get updated with a nice string containing the alarm "ID" and the UTC time it was set.

**Comment by lolodomo** [comment]
That is what is expected.
I must try again.

**Comment by lolodomo** [comment]
What a waste of time ! I can confirm that the action is succeeding when an alarm is active. It returns code 800 only when no alarm is active.
I will update my PR.

**Comment by lolodomo** [comment]
Please close this issue, there is finally no problem with alarm channels !

I kept a PR that is an optimization to change the channel alarmproperties only when needed, and no more every minute.
