### ISSUE TITLE
[Paper UI] Refresh should stay on same tab

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#5053]
When refreshing (F5) the Paper UI, it does not stay on the active tab, which can be pretty annoying. Examples are e.g. the tabs in the "Control" part, the "Services > Configuration" menu or the "Extensions" menu.

**Comment by htreu** [comment]
For this to achieve we have to add the tab name to the URL and select the tab after reload accordingly.

**Comment by kaikreuzer** [comment]
That would have been my naive assumption, too 😎
