### ISSUE TITLE
[PaperUI] JS error when creating Item

### ISSUE THREAD

**Issue by jasonparallel** [eclipse/smarthome#5065]
JS error when creating Item of type Group when basetype is not none and a function is not specified.

Error on
`var t = e.item["function"].name.split("_");`
TypeError: Cannot read property 'name' of undefined

in function
`function u() { if (e.item.groupType.indexOf("None") == -1) { var t = e.item["function"].name.split("_"); e.item["function"].name = t[0], t.length > 1 && (e.item["function"].params = [t[1], t[2]]) } e.item["function"] && !e.item["function"].name && (e.item["function"] = null) }`

No user notification is given.

**Comment by htreu** [comment]
Thanks for the report. The group function is required for any base type other then "None". The linked PR forces this through form validation.
