### ISSUE TITLE
Geofence service proposal

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5066]
Hi all.

I think we could define a new geofence service on the server side.
For this service, the user will be able to define geofence zones through its configuration (config file or Paper UI).

Then we could add a new `geofence` REST endpoint with an action to send a (device - like a phone) location. This will be a POST method with 3 entry parameters:

- a location (lat / long)
- a geofence id
- a switch item name

The service would then check if the location is inside the geofence zone or outside and will set the item state accordingly.

For any UI, getting the list of the server defined geofences would then be just a call to the `/rest/services/geofence/config` REST endpoint.
Using the new `/rest/geofence` REST endpoint, any UI will call the service with its current location to trigger the update of a switch item (inside or outside the geofence).

WDYT ?

PS: I am interested for implementing that new feature.

**Comment by lolodomo** [comment]
I would suggest the package org.eclipse.smarthome.io.rest.geofence for this new REST endpoint.

**Comment by lolodomo** [comment]
As configurations for the service, I imagine:

- 10 locations (lat,lon)
- A radius to apply to all locations to define the geofences

An alternative would be of course:

- 10 geofences (lat,lon,radius)

but I think the first option would allow to select easily locations inside a map when this feature will be available in Paper UI. Maybe it is already existing, I have not checked.

Fixing a number of geofences (10 for example) allows defining them in a config file and have them automatically displayed in Paper UI in `Configuration => MISC => Geofence`.

**Comment by lolodomo** [comment]
In addition to the switch item, I think we could have a location item. If provided, the service will set it with the provided location.

**Comment by lolodomo** [comment]
Rather than a POST request, I think a PUT request would even be better. We could provide as return whether the position is inside the zone or not. That means a client could use the service even with any items.

**Comment by mueller-ma** [comment]
When you add a field "hostname" the clients could autoconfigure their geofence. Or you add a human readable name, e.g. "John's phone", so it's easier to select the correct geofence.
Or you add both. On android devices it strongly depends on the rom whether you can change or even see the hostname.

**Comment by lolodomo** [comment]
I am not sure to understand.
A geofence is not directly linked to a device but can be used to geofencing several devices. For example, your house.
By the way, that looks like a good idea to add a name for each geofence.
But I don't understand what you want to do with "John's phone" or hostname. Can you explain a little more ?

**Comment by lolodomo** [comment]
We can also create a GET request that takes as input parameter a position and returns the geofence in which this position is inside.

**Comment by lolodomo** [comment]
If a client UI wants to check the device position against several geofences like for example "at home" and "at work", it will have to call the service several times, once for each geofence to check (one time for "at home" and one time for "at worrk").

**Comment by lolodomo** [comment]
For clients wanting to compute geofence status on client side (for battery saving reasons ?), we could define the geofence status as an additional optional parameter to the service call. If provided, the server will not compute it again but simply use it to set the switch item. So it would be a special mode that disables the distance computation by the service.

**Comment by kaikreuzer** [comment]
I do not see why a geofence should qualify as an own resource type (next to items, things and sitemaps).

You can have location items and rules that measure the distance between two of those items.
For me there isn't any real difference to having a temperature value and reacting when it passes a certain threshold - we don't treat such thresholds as dedicated resources either.

If you think it would be useful to describe locations not only as points, but also as areas (and a geofence is just that), you might want to revive the discussion of https://github.com/eclipse/smarthome/pull/1042.

**Comment by lolodomo** [comment]
The idea would be at least to share between clients a list of geofences or locations like the user home for example. The client could then choose amongst these geofences to do geofencing without the need to select a position in all devices/phones. How do you suggest to do that ?

**Comment by kaikreuzer** [comment]
As I said, areas such as discussed in #1042 could be a solution to it.
