### ISSUE TITLE
WeatherUnderground binding - iconUrl

### ISSUE THREAD

**Issue by BasvanH** [eclipse/smarthome#5068]
https://github.com/eclipse/smarthome/blob/e1f424af668aded560c0473791349acd392f41be/extensions/binding/org.eclipse.smarthome.binding.weatherunderground/src/main/java/org/eclipse/smarthome/binding/weatherunderground/internal/json/WeatherUndergroundJsonForecastDay.java#L95

There's a reference about the iconUrl in the source code, this is not mentiond in the documentation. #iconUrl does not work in 2.3.0.SNAPSHOT . Can this be confirmed iconUrl can;t be used?

If so, I would like an aditional channel to get it, or even better to get the 'Icon name' mentiond in the API documentation of [WeatherUnderground](https://www.wunderground.com/weather/api/d/docs?d=resources/phrase-glossary&_ga=2.210180819.719075492.1518269308-1261285835.1518092632&MR=1).

The reason for this I can use custom icons, and line them up against this [set of icons](https://www.npmjs.com/package/weather-underground-icons).

In retun I will create a Habpanel widget (almost finished).

**Comment by lolodomo** [comment]
The channel iconUrl of type String was replaced by a channel icon of type Image.

Your idea of a new channel should be possible.

**Comment by BasvanH** [comment]
Ok thank you, where can I view the most recent code? Perhaps I can make the fork/change myself.

**Comment by lolodomo** [comment]
Just here in this repo.

**Comment by lolodomo** [comment]
@BasvanH : I will try to do it, it would certainly be faster for me who created the code.

**Comment by BasvanH** [comment]
Thank you, much appreciated!

**Comment by lolodomo** [comment]
Done. The new channel is named iconKey.
WU even provides a specific field containing that information.

**Comment by BasvanH** [comment]
@lolodomo , thank you very much for this! 

Any idea when it will be pulled to master? Then I can finish my end of my promise.

**Comment by BasvanH** [comment]
@lolodomo I would like to update to this latest build of this binding. Normally I would go to [here](https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/) and download the .jar . But as this is eclipse/smarthome, how can I get the .jar file of this binding?

**Comment by lolodomo** [comment]
I see that a new ESH stable version has been built today and it includes this enhancement. So you should have the new version of the binding included in the next openHAB snapshot, maybe today or tomorrow morning.

**Comment by BasvanH** [comment]
I'm running build #1214, but can't get any value out of the #iconKey channel. None of the below seem to work:
`String		Weather_ConditionId_Current	"ConditionId [%s]"		{channel="weatherunderground:weather:local:current#iconKey"}
String		Weather_ConditionId0		"ConditionId [%s]"		{channel="weatherunderground:weather:local:forecastToday#iconKey"}
String		Weather_ConditionId1		"ConditionId [%s]"		{channel="weatherunderground:weather:local:forecastTomorrow#iconKey"}
String		Weather_ConditionId2		"ConditionId [%s]"		{channel="weatherunderground:weather:local:forecastDay2#iconKey"}
String		Weather_ConditionId3		"ConditionId [%s]"		{channel="weatherunderground:weather:local:forecastDay3#iconKey"}`

**Comment by lolodomo** [comment]
As the channels are new, you have to delete your thing and create it again.

**Comment by BasvanH** [comment]
Didn't knew that, it works. Moving forward with my widget. Thanks!

**Comment by BasvanH** [comment]
Here's my end of the promise. I have made an widget that uses the Weather Underground binding together with a [fitted icon set](https://github.com/manifestinteractive/weather-underground-icons).

Find the widget [here](https://community.openhab.org/t/weather-underground-widget/40260).
