### ISSUE TITLE
PaperUI: Show Full Version Number of Bindings

### ISSUE THREAD

**Issue by KidSquid1** [eclipse/smarthome#5108]
I would like to suggest in the Addons/Bindings page that the version numbers of available and installed bindings show the full version number. Currently the version shown is only the prefix, not the full version number. When working with snapshots and testing new features it would be nice to look at a GUI instead of querying the Karaf console for that information. This method would also be a visual confirmation when attempting to upgrade a binding, you could confirm the version number change once you have uninstalled and reinstalled the binding.

**Comment by kaikreuzer** [comment]
The Paper UI shows the version that is provided by the ExtensionService, so there is no need to change anything here.

I assume that you talk about extensions that are shown in openHAB: Those are provided by the KarafExtensionService (available in openhab-core) and their version is the version of the [Karaf feature](https://github.com/openhab/openhab-core/blob/5a21ca6b02e6d859fed430719df995d191b28ffa/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java#L107) - which corresponds to their Maven version; no other information is available here. It is the nature of Maven that you cannot differentiate two snapshot builds by their version.
