### ISSUE TITLE
Browser caching video

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5111]
Due to browser caching (Firefox, Chrome, ...), if you change the URL attached to a video element in your sitemap and save your sitemap, then when you reopen the page in Basic UI for example, it will display the old video. The reason is that the used URL by Basic UI is the proxied URL and this proxied URL is unchanged. So the browser is using the video it has already cached for this URL.
To get the new video, you need to clear the browser cache.

@resetnow : should we add a timestamp parameter to proxied video URL like it is done for proxied image URLs, in order to bypass browser caching ?

**Comment by resetnow** [comment]
I think it should be handled by serving appropriate HTTP headers for the video, something like 

```
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
```

**Comment by lolodomo** [comment]
Just to be clear for everybody, even a server restart does not allow getting the new video. The only solution is to clear the browser cache.


@resetnow : looks like a good idea. These headers have to be set by our proxy server ?

**Comment by resetnow** [comment]
Technically these headers should be provided by the source server, if there's a proxy it should send these headers and we should relay them.

**Comment by lolodomo** [comment]
Using Firefox debugger, I can confirm the caching done by the browser and I can confirm that there is no cache control inside the HTTP response headers.
This is not yet clear for me who and how to inject these headers.

**Comment by resetnow** [comment]
You can try accessing the source stream directly from your browser and see if there are any cache control headers. If it's a device providing streamed data, it should provide them.

**Comment by lolodomo** [comment]
After @maggu2810 proposal for issue #4873 , I was finally able to implement your suggestion to disabloe browser caching.
I will upodate my PR.
