### ISSUE TITLE
Basic UI: setting to avoid SSE for update

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5144]
More and more users are complaining about Basic UI not updating when using Firefox/Chrome.
While it is still not clear why few users have this problem and others (like us developers) have not, the problem is certainly linked to SSE.
I would suggest to add an advanced setting to Basic UI to prefer HTTP long polling over SSE for updates.

I am ok to implement this new setting.

@resetnow : we need to get in the frontend (smarthome.js) a new flag corresponding to this new setting. This flag will be set of course by the backend. Where to inject this flag ? What would be your suggestion ?

**Comment by resetnow** [comment]
I think first we need to try to fix SSE, because simply disabling it and saying “maybe it's unstable” isn't really a solution. Could you please provide a link where the users are actually complaining? Is there any technical info on the issue?

**Comment by maggu2810** [comment]
I agree with @resetnow that we should try to fix SSE instead of using long polling.

**Comment by lolodomo** [comment]
So no reason to keep this issue opened.
