### ISSUE TITLE
Discovery for USB devices with serial driver

### ISSUE THREAD

**Issue by hsudbrock** [eclipse/smarthome#5153]
**Issue**

Currently, there is no generic discovery for things that represent a USB device. Examples of such things that could be discovered are bridges for wireless protocols (like, e.g., Zigbee, Z-Wave, HomeMatic, or HomeMatic IP) using an USB dongle. Of course, each binding can provide its own discovery mechanism for things representing USB devices. However, since there are multiple bindings providing such USB-based things, it would be sensible to have a generic discovery for USB devices. Since bindings often use serial ports for talking to USB devices, this generic discovery should also support finding the serial port for a USB device.

**Ideas for implementation**

Such a generic discovery could be implemented similarly to the generic discoveries for mDNS and UPnP, which can be hooked into by a binding using _DiscoveryParticipants_. For mDNS and UPnP, the generic discovery provides information about discovered devices to the discovery participants, and those in turn check whether they can provide a thing for that device (cf. bundles `org.eclipse.smarthome.config.discovery.mdns` and `org.eclipse.smarthome.config.discovery.upnp`).

For USB, a generic discovery should provide information from the device descriptor of discovered USB devices (vendor ID, product ID, serial number, etc.) to the discovery participants, which would then check whether they support the device, and, if so, create a `DiscoveryResult` for it. As far as I have seen, bindings often communicate with USB dongles via a virtual serial port (and not directly via USB), thereby offloading logic for USB communication to an OS driver. Hence, the generic discovery should also provide information about this virtual serial port to the discovery participants.

How to get information about added/removed USB devices and the corresponding serial ports? There are two separate issues here: Getting information about available USB devices, and getting information about the corresponding virtual serial ports.

To simply get information about available USB devices, as well as notifications when new devices are plugged in or devices are removed, one could use JNI to access [libusb](http://libusb.info/) (a library for USB access written in C, available on various OSes). There is even an MIT-licensed Java library available for that ([usb4java](https://github.com/usb4java/usb4java)). However, this does not provide information about the virtual serial ports. An alternative for Linux-based systems would be to use JNI to access [udev](https://en.wikipedia.org/wiki/Udev), which also provides information about these serial ports. Another alternative for Linux-based systems is to scan the folder `/sys/bus/usb-serial/devices` provided by the [sysfs](https://en.wikipedia.org/wiki/Sysfs) file system. This folder contains one subfolder for each serial port provided for an USB device, from where the information from the USB device descriptor can be obtained.

I would go for scanning the sysfs file system, because it does not depend on JNI, which usually makes things more complex. I am not aware of a similar solution for other OSes (e.g., Windows or Mac), but maybe there is someone here who has a solution for that as well? (There is one approach described [here](https://todbot.com/blog/2012/03/02/listcomports-windows-command-line-tool-for-usb-to-serial/), using Windows' WMI infrastructure, which might be a starting point for Windows at least.)

Does this approach sound sensible? Or should something rather be done differently? I would be happy for any feedback.

**Credit**
Credit for suggesting such an improvement in Eclipse SmartHome goes to @tomhoefer.

**Comment by JochenHiller** [comment]
For macOS there are built-in tools like:
* `ioreg -p IOUSB -w0 -l` 
  * see https://apple.stackexchange.com/questions/170105/list-usb-devices-on-osx-command-line
  * see https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/ioreg.8.html
* `system_profiler SPUSBDataType`
  * data can easily be parsed, as a sample see https://github.com/jlhonora/lsusb how it provides a Linux similar `lsusb` tool

Note: this would work by querying for USB devices, but will not allow to be called back when USB devices have been plugged in.
For that I would only see a native implementation (like libusb, http://libusb.info/), even it is not clear from documentation if hotplug capability will be supported on macOS. Would need some testing.

**Comment by hsudbrock** [comment]
@JochenHiller I looked intoo the links you posted above, but could not find any information about how to get the serial port(s) provided by the OS via an USB-Serial-driver for a given USB device. Did I perhaps miss this somewhere?

(I believe that this information about the serial ports is crucial for the use case here, since all the bindings talking to USB devices I have seen so far do this via a serial interface.)

**Comment by maggu2810** [comment]
I like the idea, but it seems to be difficult if we want to support different OS.
For Linux itself I don't see a problem if we are fine with accessing sysfs.

**Comment by hsudbrock** [comment]
Let me quickly summarize the pros and cons of the approch "scan sys/bus/usb-serial for detecting USB devices with serial port" that I am aware of, since some of them are not apparent from my initial post:

Cons:
* Only for Linux (but I am simply not aware for solutions for the other main OSes)
* Only for USB devices with an associated serial port (could be seen as a pro point as well, imho)
* Needs regular scans of the directory in the sysfs (watching the directory for changes using, e.g., a `WatchService` from `java.nio` will not work, as this does not work for the sysfs file system)
* Requires the sysfs folder for the usb-serial drivers (typically /sys/bus/usb-serial). This folder is not necessarily enabled by default (e.g., on more recent versions of Ubuntu one has to enable it using a `modprobe option`)

Pros:
* No need for native code
* Quite simple to implement
* Works on Linux systems

Although there are some cons, I still think it would be a useful improvement, just not for all systems (and it would not be a problem for those other systems, and could be extended to those other systems if someone has a solution for those).

**Comment by maggu2810** [comment]
> * Needs regular scans of the directory in the sysfs (watching the directory for changes using, e.g., a `WatchService` from `java.nio` will not work, as this does not work for the sysfs file system)

What about using `dbus` to get informed about such events?
At least `systemd` emits signals IIRC.

**Comment by hsudbrock** [comment]
@maggu2810 Thanks for the hint to dbus. You are right, this could be used on Linux systems instead of polling the sysfs (using a fallback to polling for systems where dbus is not available). 

I just checked, there are signals `UnitNew` and `UnitRemoved` provided by systemd via dbus, and (at least on my machine) they signal plugging in/out of USB sticks. Great that there is already a dbus transport bundle in ESH!

**Comment by maggu2810** [comment]
Here an example for an plugged in EnOcean USB stick

```text
signal time=1519737592.903222 sender=:1.0 -> destination=(null destination) serial=22854 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=UnitNew
   string "sys-devices-pci0000:00-0000:00:14.0-usb1-1\x2d2-1\x2d2:1.0-ttyUSB0-tty-ttyUSB0.device"
   object path "/org/freedesktop/systemd1/unit/sys_2ddevices_2dpci0000_3a00_2d0000_3a00_3a14_2e0_2dusb1_2d1_5cx2d2_2d1_5cx2d2_3a1_2e0_2dttyUSB0_2dtty_2dttyUSB0_2edevice"

signal time=1519737592.903371 sender=:1.0 -> destination=(null destination) serial=22855 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=UnitNew
   string "dev-ttyUSB0.device"
   object path "/org/freedesktop/systemd1/unit/dev_2dttyUSB0_2edevice"

signal time=1519737592.903529 sender=:1.0 -> destination=(null destination) serial=22856 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=UnitNew
   string "dev-serial-by\x2did-usb\x2dEnOcean_GmbH_EnOcean_USB_300_DB_FTXGREW1\x2dif00\x2dport0.device"
   object path "/org/freedesktop/systemd1/unit/dev_2dserial_2dby_5cx2did_2dusb_5cx2dEnOcean_5fGmbH_5fEnOcean_5fUSB_5f300_5fDB_5fFTXGREW1_5cx2dif00_5cx2dport0_2edevice"

signal time=1519737592.903723 sender=:1.0 -> destination=(null destination) serial=22857 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=UnitNew
   string "dev-serial-by\x2dpath-pci\x2d0000:00:14.0\x2dusb\x2d0:2:1.0\x2dport0.device"
   object path "/org/freedesktop/systemd1/unit/dev_2dserial_2dby_5cx2dpath_2dpci_5cx2d0000_3a00_3a14_2e0_5cx2dusb_5cx2d0_3a2_3a1_2e0_5cx2dport0_2edevice"
```

There are new device units announced.

See: https://www.freedesktop.org/software/systemd/man/systemd.device.html

**Comment by hsudbrock** [comment]
I have looked into using the D-Bus system bus to avoid polling the sysfs file system. I think that this could indeed be used as an optimization of such a USB-Serial discovery on systems that provide both D-Bus and systemd/udev. Thanks for this suggestion, @maggu2810 ! 

Note: If D-Bus is not exposed via TCP but via unix socket only (which seems to be the default setting for D-Bus), then we would need native code, as the library that is used in the java dbus library for accessing the dbus is based on native code (cf. https://github.com/bdeneuter/matthew).

Side note: Before implementing such an optimization in ESH, I believe that some adaption needs to be done to the dbus transport bundle, since there might be some packages missing, this is discussed in https://github.com/eclipse/smarthome/issues/5159.

To have a first implementation for a generic discovery for USB devices accessed via serial port, I would like to provide a PR that implements this via retrieving information from the sysfs, as described above (using polling if background discovery is enabled). This would be for Linux only and background discovery might be optimized for some Linux systems using D-Bus later. Nevertheless, I think that such an implementation is worthwile, as it simplifies the pairing of devices like, e.g., Zigbee/Z-Wave/HomeMatic dongles on Linux systems.

If you have any objections, please let me know.
