### ISSUE TITLE
Any need for immediate activation of ThingHandlerFactory services

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#5163]
The archetype currently sets `immediate = true` for the component implementation of `ThingHandlerFactory`.
Why do a `ThingHandlerFactory` service requires to be activated if there is no one that is interested in?

If there exists "always" an instance in every solution using ESH that tracks that services there is still no need to set it explicit.

**Comment by sjka** [comment]
I can't help there as I never understood that...

**Comment by maggu2810** [comment]
> Only components which don't expose any services (or do that but by their nature require to have their own life even if they are not tracked) should require that.

> I can't help there as I never understood that...

WRT your comment it seems at least you understood it the same way as me.
