### ISSUE TITLE
 [Build Failure] Basic UI failed to build, depends on python version

### ISSUE THREAD

**Issue by svilenvul** [eclipse/smarthome#5171]
Running the ESH build on Jenkins resulted with build failure : 

```
mvn clean install 

....

[INFO] ------------------------------------------------------------------------
[INFO] Building Eclipse SmartHome Basic UI 0.10.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 

.....

[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (Install node and npm) @ org.eclipse.smarthome.ui.basic ---
[INFO] Node v5.4.0 is already installed.
[INFO] NPM 3.3.12 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ org.eclipse.smarthome.ui.basic ---
[INFO] Running 'npm install' in /var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic
[WARNING] npm WARN prefer global node-gyp@3.6.2 should be installed with -g
[INFO] 
[INFO] > node-sass@4.7.2 install /var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node_modules/node-sass
[INFO] > node scripts/install.js
[INFO] 
[INFO] Cached binary found at /var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/npm_cache/node-sass/4.7.2/linux-x64-47_binding.node
[INFO] 
[INFO] > node-sass@4.7.2 postinstall /var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node_modules/node-sass
[INFO] > node scripts/build.js
[INFO] 
[INFO] Binary found at /var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node_modules/node-sass/vendor/linux-x64-47/binding.node
[INFO] Testing binary
[INFO] Binary has a problem: [Error: /var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node_modules/node-sass/vendor/linux-x64-47/binding.node: ELF file OS ABI invalid]
[INFO] Building the binary locally
[INFO] Building: /var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node/node /var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[ERROR] gyp info it worked if it ends with ok
[ERROR] gyp verb cli [ '/var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node/node',
[ERROR] gyp verb cli   '/var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node_modules/node-gyp/bin/node-gyp.js',
[ERROR] gyp verb cli   'rebuild',
[ERROR] gyp verb cli   '--verbose',
[ERROR] gyp verb cli   '--libsass_ext=',
[ERROR] gyp verb cli   '--libsass_cflags=',
[ERROR] gyp verb cli   '--libsass_ldflags=',
[ERROR] gyp verb cli   '--libsass_library=' ]
[ERROR] gyp info using node-gyp@3.6.2
[ERROR] gyp info using node@5.4.0 | linux | x64
[ERROR] gyp verb command rebuild []
[ERROR] gyp verb command clean []
[ERROR] gyp verb clean removing "build" directory
[ERROR] gyp verb command configure []
[ERROR] gyp verb check python checking for Python executable "python2" in the PATH
[ERROR] gyp verb `which` succeeded python2 /usr/bin/python2
[ERROR] gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.4.3\n"
[ERROR] gyp ERR! configure error 
[ERROR] gyp ERR! stack Error: Python executable "/usr/bin/python2" is v2.4.3, which is not supported by gyp.
[ERROR] gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
[ERROR] gyp ERR! stack     at Object.failPythonVersion (/var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node_modules/node-gyp/lib/configure.js:492:19)
[ERROR] gyp ERR! stack     at Object.<anonymous> (/var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node_modules/node-gyp/lib/configure.js:474:14)
[ERROR] gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
[ERROR] gyp ERR! stack     at emitTwo (events.js:87:13)
[ERROR] gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
[ERROR] gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
[ERROR] gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
[ERROR] gyp ERR! stack     at emitOne (events.js:77:13)
[ERROR] gyp ERR! stack     at Socket.emit (events.js:169:7)
[ERROR] gyp ERR! stack     at Pipe._onclose (net.js:469:12)
[ERROR] gyp ERR! System Linux 2.6.18-194.3.1.el5xen
[ERROR] gyp ERR! command "/var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node/node" "/var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[ERROR] gyp ERR! cwd /var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node_modules/node-sass
[ERROR] gyp ERR! node -v v5.4.0
[ERROR] gyp ERR! node-gyp -v v3.6.2
[ERROR] gyp ERR! not ok 
[ERROR] Build failed with error code: 1
[WARNING] npm WARN EPEERINVALID ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
[WARNING] npm WARN EPACKAGEJSON org.eclipse.smarthome.ui.basic@0.10.0 No repository field.
[WARNING] npm WARN EPACKAGEJSON org.eclipse.smarthome.ui.basic@0.10.0 No license field.
[ERROR] npm ERR! Linux 2.6.18-194.3.1.el5xen
[ERROR] npm ERR! argv "/var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node/node" "/var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v5.4.0
[ERROR] npm ERR! npm  v3.3.12
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] 
[ERROR] npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the node-sass@4.7.2 postinstall script 'node scripts/build.js'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the node-sass package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node scripts/build.js
[ERROR] npm ERR! You can get their info via:
[ERROR] npm ERR!     npm owner ls node-sass
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /var/lib/jenkins/jobs/Test-Job/workspace/extensions/ui/org.eclipse.smarthome.ui.basic/npm-debug.log

...

[INFO] Eclipse SmartHome UI Extensions .................... SUCCESS [  0.045 s]
[INFO] Eclipse SmartHome Icon Sets ........................ SUCCESS [  0.059 s]
[INFO] Eclipse SmartHome Classic Icon Set ................. SUCCESS [  4.243 s]
[INFO] Eclipse SmartHome Basic UI ......................... FAILURE [01:06 min]
[INFO] Eclipse SmartHome Classic UI ....................... SKIPPED
[INFO] Eclipse SmartHome Paper UI ......................... SKIPPED
[INFO] Eclipse SmartHome Voice Services ................... SKIPPED

```

@kaikreuzer, do you know who can help with this issue ?

**Comment by triller-telekom** [comment]
@svilenvul Did you see the error message regarding the python version?

> [ERROR] gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.4.3\n"
[ERROR] gyp ERR! configure error 
[ERROR] gyp ERR! stack Error: Python executable "/usr/bin/python2" is v2.4.3, which is not supported by gyp.
[ERROR] gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.

If you have a newer python then 2.4.3 installed, maybe it is not on $PATH so npm cannot find it?

**Comment by svilenvul** [comment]
@triller-telekom , thanks for the advice.

I just did not expect the build to depend on Python version...

**Comment by svilenvul** [comment]
Thanks !

**Comment by kishoretangudu** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Building Eclipse SmartHome Basic UI 0.10.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ org.eclipse.smarthome.ui.basic ---
[INFO]
[INFO] --- tycho-packaging-plugin:1.1.0:build-qualifier (default-build-qualifier) @ org.eclipse.smarthome.ui.basic ---
[INFO] The project's OSGi version is 0.10.0.201807110813
[INFO]
[INFO] --- tycho-packaging-plugin:1.1.0:validate-id (default-validate-id) @ org.eclipse.smarthome.ui.basic ---
[INFO]
[INFO] --- tycho-packaging-plugin:1.1.0:validate-version (default-validate-version) @ org.eclipse.smarthome.ui.basic ---
[INFO]
[INFO] --- directory-maven-plugin:0.2:highest-basedir (directories) @ org.eclipse.smarthome.ui.basic ---
[INFO] Highest basedir set to: D:\source\smart-home\smarthome
[INFO]
[INFO] --- build-helper-maven-plugin:1.8:add-source (add-source) @ org.eclipse.smarthome.ui.basic ---
[INFO] Source directory: D:\source\smart-home\smarthome\extensions\ui\org.eclipse.smarthome.ui.basic\src\main\groovy added.
[INFO]
[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (Install node and npm) @ org.eclipse.smarthome.ui.basic ---
[INFO] Node v5.4.0 is already installed.
[INFO] NPM 3.3.12 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ org.eclipse.smarthome.ui.basic ---
[INFO] Running 'npm install' in D:\source\smart-home\smarthome\extensions\ui\org.eclipse.smarthome.ui.basic
[WARNING] npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[WARNING] npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[WARNING] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js


I am getting the above error while Building the ESH. Just as an info, I updated the node packages to the latest. Please pull-me out of this issue.

**Comment by triller-telekom** [comment]
There is no error in your pasted log, just warnings. It is also completely independent of what this issue was about. if you really have an **error** somewhere, feel free to open a new issue to discuss it.

**Comment by kishoretangudu** [comment]
My bad its now displaying any error at the same time execution not moving forward.

**Comment by kishoretangudu** [comment]
Hi,
When I am opening eclipse with smarthome, I am getting below errors. Could you please help me?






Repository http://download.eclipse.org/cbi/updates/license
Repository http://download.eclipse.org/tools/orbit/downloads/latest-R
Offline = false
Mirrors = true
Include All Platforms = false
Include All Requirements = true
Include Binary Equivalents = true
Include Sources = true
Adding repository http://download.eclipse.org/cbi/updates/license
Adding repository http://download.eclipse.org/tools/orbit/downloads/latest-R
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:787)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1167)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1033)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3332)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3275)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4502)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4496)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4494)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3266)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3141)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
  ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
    ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1531374113306
    ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1531374113306 requires 'org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group 0.0.0' but it could not be found

Took 39 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
