### ISSUE TITLE
Statechangelistener prevents GroupItem to be disposed

### ISSUE THREAD

**Issue by Maw-Jung** [eclipse/smarthome#5189]
When a GroupItem registers a StateChangeListener in form of another GroupItem, the deletion of the latter won't remove the StateChangeListener, because the toElement method in ManagedItemProvider creates a new instance of the GroupItem to perform the tidy up task on. Later the removeStateChangeListener of the newly created GroupItem will be called, but this will fail since there are none. The Java GarbageCollector will remove the GroupItem from the ItemRegistryImpl but stops at the old GroupItem, since it's still referenced from the GroupItem which holds the reference on it's listeners. When creating a new GroupItem with the same uid the GroupItem won't add the new GroupItem as a listener, since the overriden equals method of a GenericItem will state them the same, because the comparison isn't done by object id. Thus the listener of the old GroupItem will be used and the new GroupItem won't get updates.
If questions arise i'll be happy to provide additional informations.

Greetings,
maw

**Comment by htreu** [comment]
Hi @Maw-Jung thanks for the bug report, I will have a look.
