### ISSUE TITLE
Unable to use JSON structured mqtt message payload in the lwt property of MQTTService

### ISSUE THREAD

**Issue by doandzhi** [eclipse/smarthome#5197]
As Last Will Testament is configured with the `lwt` property of the MqttService it has a specific formatting that uses which doesn't allow JSON structured messages since the separation between parametters is done using `:`. I see it as a valid use case to use JSON structure in my LWT message but the property is split by `:` which makes it impossible. Does it make sense to change the `:` to something else or it is against some ESH guidelines that I don't know yet?

_example usage of lwt property:_ 
`org.eclipse.smarthome.mqtt:mosquitto.lwt=mqttTopic:mqttMessagePayload:QoS:retainFlag`

_wanted usage of lwt property:_ 
`org.eclipse.smarthome.mqtt:mosquitto.lwt=mqtt/clients/client1:{"clientID":"client1","status":"online"}:2:1`

It takes "client1" as Quality Of Service and throws Exception because it is not a number at all.

Any thoughts on this one?

**Comment by maggu2810** [comment]
AFAIK also the topic is allowed to contain `:`.

What about this one:
* If there is a property `lwt.topic`, use that topic
* If there is a property `lwt.message`, use that message
* If there is a property `lwt.qos`, use that QoS
* If there is a property `lwt.retain`, use that retain flag
* If some of the properties above are missing, try to parse the `lwt` property and use the missing part encoded in that property.

**Comment by doandzhi** [comment]
Thank you for the response @maggu2810 ! Having a look in the [MqttWillAndTestament](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttWillAndTestament.java) I see that this `fromString(String string)` method splits the given parameter by `:` .  Concerning the last will setting after the session has been started I already mentioned this in #5162 . So this is impossible to build any logic around this at the moment (parsing the parameter and setting the lwt later) since it is set when the connection is established.

   Sorry my ignorace if I don't understand something properly but at the moment it is impossible for me to use  the `:` in my message payload because the property is not processed properly and there seems to be no alternative to use instead of this configuration property.

**Comment by maggu2810** [comment]
But there is also a constructor that could be used:
```Java
public MqttWillAndTestament(String topic, byte[] payload, int qos, boolean retain)
```

I have just a very short look at the code, but IMHO it should be possible to change the "addBrokerConnection" method in the MqttService class to implement the above logic.

**Comment by doandzhi** [comment]
Yes, valid point @maggu2810 ! As I described in #5162 I tried to use this constructor at first but then it requires some connection handling and my thoughts are in the direction of using already implemented logic of ESH with configuring the MqttService and then getting the broker connection where I need it since it is working as required for almost everything I am doing till now.

Just to clear out, I opened this issue to concern only the lwt property parsing mechanism and propose a change to extend its use cases.

**Comment by maggu2810** [comment]
> Just to clear out, I opened this issue to concern only the lwt property parsing mechanism and propose a change to extend its use cases.

I am fine with a change similar to the above described one. At least if it is backward compatible and allows to use all allowed characters for topic and message.
