### ISSUE TITLE
Chart settings no more available in Paper UI

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5202]
I introduced the chart settings with the PR #5067.
They are available in Paper UI when I run the snapshot 1212.
Unfortunately, they are no more available when I run the snapshot 1224.

**Comment by lolodomo** [comment]
It looks like the file org.eclipse.smarthome.ui/OSGI-INF/chartservlet.xml has been removed ?

**Comment by kaikreuzer** [comment]
Indeed, right here: https://github.com/eclipse/smarthome/commit/55650b49d6109b052c53aed433de9adc70d8cbbf#diff-e965ab2b1de57477f40384dc5340ec0e

But the properties have been added in the DS annotations: https://github.com/eclipse/smarthome/commit/55650b49d6109b052c53aed433de9adc70d8cbbf#diff-27aabdd5469fc1197aa7a18dcfba1126R69

**Comment by lolodomo** [comment]
But it does not work anymore...

**Comment by kaikreuzer** [comment]
I think I know why... Give me a second for a PR.

**Comment by lolodomo** [comment]
It was reported too that chart settings in cfg file are now ignored. i have not yet tested but I will do it.
Can the fixed bug explain this other bug ?
