### ISSUE TITLE
Sitemap SSE channel doesn't emit events if 'sitemap' and 'pageid' parameters aren't given

### ISSUE THREAD

**Issue by maniac103** [eclipse/smarthome#5211]
Those parameters are marked as optional in the docs though.

Repro steps:
- `curl -X POST http://demo.openhab.org:8080/rest/sitemaps/events/subscribe`
- `curl http://demo.openhab.org:8080/rest/sitemaps/events/{subid from above}` -> change e.g. 'Ceiling' switch in 'Bathroom' and observe no event
- `curl http://demo.openhab.org:8080/rest/sitemaps/events/{subid from above}?sitemap=demo&pageid=FF_Bath` -> flip same switch and observe event
- `curl http://demo.openhab.org:8080/rest/sitemaps/events/{subid from above}` -> flip same switch and now observe events as well, despite sitemap and pageid not being given

For the OH Android app, it would be great to be able to actually omit the parameters, as it would allow getting away with a single SSE connection instead of one per shown page.

**Comment by lolodomo** [comment]
All the SSE stuff on the server side is managed per page.
When you provide sitemap/page as URL parameter, the server is linking your subscription to this page.
When you provide no sitemap/page as URL parameter, the server continue considering the previously page set.

**Comment by maniac103** [comment]
In that case, the docs should be updated to say that sitemap and pageid are mandatory.

**Comment by lolodomo** [comment]
Do you know if any documentation exists for that ?
Not at my knowledge.

**Comment by maniac103** [comment]
It's shipped with the distribution. Example: demo.openhab.org -> REST API -> sitemaps -> /sitemaps/events/subscribe

**Comment by lolodomo** [comment]
You mean we should update the REST docs ?

**Comment by kaikreuzer** [comment]
> For the OH Android app, it would be great to be able to actually omit the parameters, as it would allow getting away with a single SSE connection instead of one per shown page.

Could you elaborate on this? The sitemap event subscription had been specifically introduced to reduce the event stream to what is relevant for the client - sending events for potentially all pages of a huge sitemap pretty much contradicts its purpose....

**Comment by lolodomo** [comment]
The Android app is displaying a maximum of 2 pages at the same time so 2 SSE subscriptions should be enough.
In my current implementation, before the code was massively refactored, I was using more SSE subscriptions depending on the sitemap depth.

**Comment by maniac103** [comment]
> In my current implementation, before the code was massively refactored, I was using more SSE subscriptions depending on the sitemap depth.

After the refactoring I would suggest to keep it like that; the code is still structured that way (one long polling request / SSE subscription per page on the back stack).

> Could you elaborate on this? The sitemap event subscription had been specifically introduced to reduce the event stream to what is relevant for the client - sending events for potentially all pages of a huge sitemap pretty much contradicts its purpose....

Maybe I'm massively underestimating the amount of events potentially coming in; it just would have been very convenient. The new connection manager [1] operates only on page URLs, without any notion of sitemap or page ID. With that structure, for each event coming in we could just have looked through the loading widgets of all pages on the stack and update it on match. Now we have to either
- additionally track sitemap + page ID or
- parse sitemap + page ID from the page URL (last two segments of URL path)

The latter also works (for now?), so the additional inconvenience is not a problem at all; not sure how safe that approach is though.

But in any case, yes, I think the REST API docs should be updated to reflect that sitemap and page ID are mandatory.

[1] https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java

**Comment by maggu2810** [comment]
@maniac103 Suffers #5229 your needs?

**Comment by maggu2810** [comment]
Hm, perhaps the documentation needs to be changed (or at least one needs to be created), but I don't think (if I understand the code correctly) that sitemap name and page ID are required "all the time".

As already shown by the example in the first comment, we need to assign the sitemap name and the page ID to a subscription ID once. After that it is valid to omit that parameters, isn't it?

**Comment by lolodomo** [comment]
Yes in fact sitemap and page id are required only to set or change the page that must emit events.
So there is probably nothing to change in the REST doc.

**Comment by maniac103** [comment]
> As already shown by the example in the first comment, we need to assign the sitemap name and the page ID to a subscription ID once. After that it is valid to omit that parameters, isn't it?

That's correct, and it's technically also correct that those parameters aren't required. It's very surprising behavior though if you're not used to the internals. I'm also not the only one being surprised here; a random example after 5 seconds of googling e.g. is https://community.openhab.org/t/sse-for-sitemap/25615/2

So if we don't want to mark those parameters as required, is it e.g. possible to return a HTTP error (422? 424? 428?) when trying to get events and the page isn't set?

**Comment by maggu2810** [comment]
Hm, IIRC all that part has been written by @kaikreuzer. I don't know it in details just looked at it yesterday.
I am not sure if it is working if multiple connections are made to the same subscription ID and one is closed. This should (IMHO) call the onClose method. I am not sure if the remaining connections receive still events after that.

A check if a page ID and sitemap has been set can (IMHO) be implemented. I assume a event subscriber for "nothing" does not make sense.

**Comment by lolodomo** [comment]
I will add the check.

@maggu2810 : regarding your comment about multiple connections made to the same subscription ID, I don't think it is something expected. Each client should ask for a subscription ID.

**Comment by maggu2810** [comment]
Sure, it is not expected, But if another client could corrupt the event mechanism of another client, just by connect to that subscription ID and close that connection again, then it is not perfect design. WDYT? A client should not be able to collide with another client.

**Comment by lolodomo** [comment]
Any idea what could be done ? You would like that the server records something identifying a specific client ?

**Comment by maggu2810** [comment]
I don't get a reply by the original author, so I don't know if my reading and understanding of the code is fully correct.

> I am not sure if it is working if multiple connections are made to the same subscription ID and one is closed. This should (IMHO) call the onClose method. I am not sure if the remaining connections receive still events after that.

If a client connected to a subscription ID closes its connection (so `onClose` is called) and this closes the event transmission to all clients that connect to that subscription ID and it is not intended that multiple clients are using the same subscription ID...
Why not tracking if a client has already been using a subscription ID and don't allow another client to connect to the same subscription ID again.
