### ISSUE TITLE
[PaperUI] performance issue

### ISSUE THREAD

**Issue by vkolotov** [eclipse/smarthome#5232]
I'm not sure if this an issue or not. But I've got several "things" added in OH (72 channels in total for all of those things linked), one of the channels is constantly changing its value (every second, just a test) which causes a "items?recursive=false" request on every change. 

The problem is, all the responses for the "items?recursive=false" request contain ALL 72 links, e.g. even those 71 that never changes. 

I've been monitoring it for 1 hour, and it has downloaded 77mb of the "items?recursive=false" responses.

Is this something expected?

It is definitely making everything very slow, especially when the rest of the 72 channels start changing, because literally for every change PaperUI makes another request to get ALL 72 links.

Thanks

**Comment by vkolotov** [comment]
Here is that place where it is happening:
https://github.com/eclipse/smarthome/blob/d528161591298f1669b6e444cb1eea7bfdc39904/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/controllers.js#L92

Effectively, if any of the item changes, PaperUI downloads ALL items, including those that have not changed.

**Comment by vkolotov** [comment]
Looks like that piece of code was added quite recently (in Feb the 16th) by @htreu. 

Was it done on a purpose @htreu ? :)

**Comment by htreu** [comment]
Hi @vkolotov, thanks for the report!
The Paper UI `itemRepository` is supposed to cache all instances. I will have a look and refactor this part.

**Comment by htreu** [comment]
> I realise that PaperUI (which is actually great UI !) is not supposed to be used for monitoring and was designed to do some administration.

It should nevertheless run smoothly w/o this unnecessary data download. I submitted a fix.
