### ISSUE TITLE
Image item appears to be broken in the latest ESH stable

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#5245]
An Image item like this in an .items file results in the below error.
```
Image MyImage
```

```
2018-03-17 08:01:40.116 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'zoneminder.items' has errors, therefore ignoring it: [13,1]: missing EOF at 'Image'
```

I'm running OH build 1230.

Also see comments here.
https://community.openhab.org/t/unit-support-knx-2-karaf-4-1-5-upgrade-and-more/41904/13

**Comment by kaikreuzer** [comment]
@mhilbush Yes, this is obviously a regression - I have created #5250 to fix it and will release a new ESH stable asap!
