### ISSUE TITLE
System channels for weather data

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5249]
Now that support of units has been included, I would suggest to come back to the idea that was originally proposed in #2649 to define system channels covering main weather data like current temperature, humidity, pressure, ... This idea was stopped due the problem of units (which one to use) but this is now no more a problem.

**Comment by cweitkamp** [comment]
Duplicate of #3756?

**Comment by lolodomo** [comment]
Yes ok the other issue is covering more or less this one
