### ISSUE TITLE
Magic binding: Reference to developers local thing-description-1.0.0.xsd

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#5258]
See:

https://github.com/eclipse/smarthome/blob/f3a8a4f76534e9cc1e865e782c17e0899c315f3c/bundles/test/org.eclipse.smarthome.magic/ESH-INF/thing/thing-types.xml#L4

especially `/Users/henning/work/smarthome-master2/...`

Because I'd like to use the "extensible" feature as well for Mqtt, it would be nice to have an updated "thing-description-1.0.1.xsd" or so.

**Comment by htreu** [comment]
Hi guys, I submitted a fix in #5283.
