### ISSUE TITLE
Static Code Analysis Tool reports unaddressed TODO comments in ZoneTemperatureControlHandler

### ISSUE THREAD

**Issue by kssimova** [eclipse/smarthome#5259]
I'm currently fixing issues in Smarthome, found by [the Static Code Analysis Tool](https://github.com/openhab/static-code-analysis/blob/master/README.md). The included check from [Checkstyle](https://github.com/checkstyle/checkstyle/blob/master/README.md) - *TodoCommentCheck*, which checks for left `// todo comments` in javadoc, reports [ZoneTemperatureControlHandler](https://github.com/eclipse/smarthome/blob/c20c9a11f6de16678931941a94a65bd4cef984bd/extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/handler/ZoneTemperatureControlHandler.java#L301) and I can not find an open issue with discussion about it.

The comment had been introduced with [this](https://github.com/eclipse/smarthome/commit/1fa10bff711bb15473c0cbff2fbfcf906ec59463) commit.

@MichaelOchel Аs an author, do you think that it is still an issue or we can remove the TODO comment?

**Comment by MichaelOchel** [comment]
Sorry for the late answer.

I don’t think, that I would implement it in the next time. And if no one else are interested, it can be deleted.

Or would that be something for another project @maieralex ?
