### ISSUE TITLE
Static Code Analysis Tool reports unaddressed TODO comments in DeviceStatusManagerImpl

### ISSUE THREAD

**Issue by kssimova** [eclipse/smarthome#5263]
I'm currently fixing issues in Smarthome, found by [the Static Code Analysis Tool](https://github.com/openhab/static-code-analysis/blob/master/README.md). The included check from [Checkstyle](https://github.com/checkstyle/checkstyle/blob/master/README.md) - *TodoCommentCheck*, which checks for left `// todo comments` in javadoc, reports [DeviceStatusManagerImpl](https://github.com/eclipse/smarthome/blob/bd390a8829544b92be3246a73c5792607380da8e/extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/manager/impl/DeviceStatusManagerImpl.java#L256) and [DeviceStatusManagerImpl](https://github.com/eclipse/smarthome/blob/bd390a8829544b92be3246a73c5792607380da8e/extensions/binding/org.eclipse.smarthome.binding.digitalstrom/src/main/java/org/eclipse/smarthome/binding/digitalstrom/internal/lib/manager/impl/DeviceStatusManagerImpl.java#L283) and I can not find open issues with discussions about them.

Comments had been introduced with [this](https://github.com/eclipse/smarthome/commit/1fa10bff711bb15473c0cbff2fbfcf906ec59463) commit.

@MichaelOchel Аs an author, do you think that these are still issues or we can remove the TODO comments?

**Comment by MichaelOchel** [comment]
I don’t think, that I would implement it in the next time. And if no one else are interested, it can be deleted.

Or would that be something for another project @maieralex ?
