### ISSUE TITLE
OnOffType Enumeration Order 

### ISSUE THREAD

**Issue by Josar** [eclipse/smarthome#5267]
https://github.com/eclipse/smarthome/blob/bd390a8829544b92be3246a73c5792607380da8e/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/OnOffType.java#L24

Sorting the enumaretion so OFF matches 0 and ON matches 1 could increase the usability and would also be sorted logical.
```
public enum OnOffType implements PrimitiveType, State, Command {
    OFF,
    ON;
```

When the enumemaration is sorted you could use 
```
((OnOffType) command).ordinal()
```
to get the Number representation of OFF/ON.

**Comment by maggu2810** [comment]
I agree that 0 for off and 1 for on makes sense and is what we expect.
But the ordinal represents only the position in the enum declaration and should not be used at all as it is not (AFAIK) a requirement that we keep that stable at all.

**Comment by Josar** [comment]
When changing the order also the return value for DecimalType can also be reduced to
```
return new DecimalType(this);
```
Or not?

Yes the ordinal should not be used.

**Comment by maggu2810** [comment]
As we agree that the ordinal should not be used there is no reason to change that order. Correct?

**Comment by Josar** [comment]
But it could be used internally for the return value.

```
        if (target == DecimalType.class) {
            return new DecimalType(this.ordinal()); 
          // return  this == ON ? new DecimalType(1) : DecimalType.ZERO;
```

You could argue its not much, but workloads adds up.

**Comment by Josar** [comment]
And thinking further, i disagree that the ordinal should not be used. For the on off type I think it would be beneficial to state the ordinal type should be usable and match the expectation.

**Comment by Josar** [comment]
Hello @maggu2810, is this discussion over? 

I don't understand why you argue the ordinal should not be used. 

It can't be used as it is now, and when it is corrected there should be no reason to change it again. 

Besides that, what would be the fastest way to get the boolean representation of On/Off?

**Comment by maggu2810** [comment]
If you argue that ordinals are allowed to use and so supported (which is not what I -- personally -- want to do), you already provided an argument, why we should not change the order:
We would break the code (that does not need to be an open source one) that already use it.

**Comment by maggu2810** [comment]
But perhaps @kaikreuzer, @sjka and @htreu could join and provides their point of view.

**Comment by Josar** [comment]
Just to put it right, you say the ordinal might change so no one should use it. And in the next sentence you say the ordinal should not be change as someone might use it?

**Comment by maggu2810** [comment]
That is not correct!

IMHO the ordinal should not be used.

YOU argue that it should be supported. I just point to the fact, IF it i something we supported (so, if we support what you want, not what I want), THEN it needs to stay as it is, because we must not break the ones that use it.

**Comment by Josar** [comment]
Got your point, but nobody would use it like it is now, imho.
As he basically has to do the same.
```
if (command.equals(OnOffType.ON)) {
 comInt = 1;
} else {
 comInt = 0;
}

if ( ((OnOffType) command).ordinal() ) {
 comInt = 0;
} else {
 comInt = 1;
}
```

And if someone would have done it he would, hopefully, raised an issue for it.

**Comment by kaikreuzer** [comment]
> IMHO the ordinal should not be used.

I agree and I do not really see any use of it - especially, there should not be made any assumption that the ordinal has any semantical meaning.

**Comment by maggu2810** [comment]
My point has been, if someone think "ordinals are valid to use", he can write code like that (perhaps to write persist stuff to disc):

```Java
public static int serialze(final SomeEnum val) {
    return val.ordinal();
}

public static SomeEnum deserialize(final int val) {
    return SomeEnum.values()[val];
}
```

This guy that uses such a code does not care about the value itself, just that the value keeps stable.

Please get me right: I don't veto to switch ON and OFF. IMHO OFF=0, ON=1 makes more sense, I don't like to support ordinals -- in general -- at all.

And I don't know how we could argue (if we state the ordinal is perfect to use) that we break the usage above (which is broken IMHO with and without making it stable).

Wouldn't it be simpler (I assume you already know that you are working on an `OnOffType` -- or at least on an enumeration, because you rely on the ordinal method) to add a method `toBool()` and `fromBool()` or `toInt()` and `fromInt()` to the `OnOffType` that is stable?

**Comment by htreu** [comment]
> there should not be made any assumption that the ordinal has any semantical meaning

I would even say "must not". I completely agree with @maggu2810 & @kaikreuzer. And so does Sun/Oracle:

From the JavaDoc:

```
Most programmers will have no use for this method. It is designed for use by sophisticated enum-based data structures, such as java.util.EnumSet and java.util.EnumMap.
```

**Comment by Josar** [comment]
I was thinking about the same :adding a `toBool()`, but this would also benefit from a right ordinal arrangement. And using the ordinal in the `OnOffType` should be save. As when someone changes somthing in the class he has to ensure all functionality is kept working.

**Comment by sjka** [comment]
There already are

```java
DecimalType.as(OnOffType.class)
```

and 

```java
OnOffType.as(DecimalType.class)
```

No need to extend the public API just for that.

**Comment by Josar** [comment]
Thanks @sjka, that is what i was searching for. 

this works:
```
((OnOffType)command).as(DecimalType.class)
```

**Comment by htreu** [comment]
Its always a trade of between super fast code (which in the end makes no difference with todays magic JIT compiler, cache and other internal optimisations) and maintainable, readable and robust code.
I predict we would gain next to zero performance improvement by using `ordinal` but an ordering dependency in our code base. I consider the later being much worse.
And then there is the JavaDoc...
I suggest closing down here.

**Comment by htreu** [comment]
Oh right. Its already closed :-)

**Comment by Josar** [comment]
Nevertheless, thank you for taking the time getting me to a solution and a clear thing up for me.
