### ISSUE TITLE
Static Code Analysis Tool reports unaddressed TODO comments in SoftwareUpdate

### ISSUE THREAD

**Issue by kssimova** [eclipse/smarthome#5273]
I'm currently fixing issues in Smarthome, found by [the Static Code Analysis Tool](https://github.com/openhab/static-code-analysis/blob/master/README.md). The included check from [Checkstyle](https://github.com/checkstyle/checkstyle/blob/master/README.md) - *TodoCommentCheck*, which checks for left `// todo comments` in javadoc, reports [SoftwareUpdate](https://github.com/eclipse/smarthome/blob/4204ce06bb28c28e5f711e720f87ef83beff2e27/extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/SoftwareUpdate.java#L29) and I can not find an open issue with discussion or the documentation about it.

Comment had been introduced with [this](https://github.com/eclipse/smarthome/commit/0d2b3b8c88cdc5cfa4efe3b44584f67712e93e6b) commit.

@maggu2810 Аs an author, do you think that this is still an issue or we can remove the TODO comment?

**Comment by maggu2810** [comment]
> Comment had been introduced with [this](https://github.com/eclipse/smarthome/commit/0d2b3b8c88cdc5cfa4efe3b44584f67712e93e6b) commit.

Please have a look at the commit. It's message is "run Eclipse formatter rules on Hue binding (#3123)" and should also apply formatter changes. I am not the author of that TODO.

**Comment by kssimova** [comment]
Yes, I'm very sorry about that! It seems that it has been taken from https://github.com/Q42/Jue and it is still undocumented. Should I remove the TODO comment then?

**Comment by maggu2810** [comment]
No problem at all :wink: 

We could perhaps change it to:

```Java
    /**
     * Returns the state of the update.
     *
     * <p>
     * Actual meaning currently undocumented
     *
     * @return state of update
     */
```

**Comment by maggu2810** [comment]
Hi @kssimova,
thank you for fixing that issue yourself.

FYI if your PR or a commit message (I would prefer the commit message, as it is part of the Git log then) contains special keywords, the referenced issue will be closed automatically if the PR has been merged.

You can have a look at the documentation here: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by kssimova** [comment]
@maggu2810 Thank you! I will take a look at it. :)
