### ISSUE TITLE
Static Code Analysis Tool reports unaddressed TODO comments in XmlDocumentBundleTracker

### ISSUE THREAD

**Issue by kssimova** [eclipse/smarthome#5275]
I'm currently fixing issues in Smarthome, found by [the Static Code Analysis Tool](https://github.com/openhab/static-code-analysis/blob/master/README.md). The included check from [Checkstyle](https://github.com/checkstyle/checkstyle/blob/master/README.md) - *TodoCommentCheck*, which checks for left `// todo comments` in javadoc, reports [XmlDocumentBundleTracker](https://github.com/eclipse/smarthome/blob/d0dc116e1f58ce57663e9bdba490ac9c77a7a84b/bundles/config/org.eclipse.smarthome.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/XmlDocumentBundleTracker.java#L380) and I can not find an open issue with discussion about it.

Comment had been introduced with [this](https://github.com/eclipse/smarthome/commit/079515facb89ae2d5f51b8d0b3362e8802cc60e1) commit.

@sjka Аs an author, do you think that this is still an issue or we can remove the TODO comment?

**Comment by sjka** [comment]
Yes, it is - but it is also covered by #1896, therefore the comment can be removed from the code.
