### ISSUE TITLE
CronExpressionTest: Cannot find a time after

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#5294]
I cannot build the branch anymore.
It fails on the "core test".

```text
Results :

Failed tests: 
  CronExpressionTest.findNext:124 Cannot find a time after '2018-03-25 03:01:01.000' for expression '0 0 * ? * *'
```

Log: [log.txt](https://github.com/eclipse/smarthome/files/1834226/log.txt)

**Comment by maggu2810** [comment]
DST Starts in Europe Sunday, March 25, 2018, see https://www.timeanddate.com/news/time/europe-starts-dst-2018.html
So it seems that the change is not handled correctly.
@kgoderis Would it be possible that you have a look at?

**Comment by maggu2810** [comment]
@kaikreuzer Should we ignore that test until it is fixed?

**Comment by kaikreuzer** [comment]
Yes, ok to ignore it - although I fear that it might indeed hint at an issue that users might have (again) on March 25... But it would anyhow too late to roll out a fix now :-/
