### ISSUE TITLE
[Astro] Many channel groups have the same description

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#5310]
Continued from https://github.com/openhab/openhab2-addons/issues/1520.

The Astro binding has lots of channels and groups. But unfortunately many groups are shown with the same description. 

@lolodomo: 
> Looking at the code, there is now a label but no descriptions are defined.

Here is a screenshot showing the groups and channels for a Sun thing:

![astro](https://user-images.githubusercontent.com/12213581/37873968-c65c5a06-3026-11e8-894e-750a2d2b8b90.png)

**Comment by triller-telekom** [comment]
The question is if it is possible with the current modeling...
In [sun.xml](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/sun.xml#L11) the thing has various `channel-group`s, but ALL are of the same type: `sunRange`. If we override the label at this place we override it for this group, but NOT for its children.

The children are defined in [channels.xml](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.astro/ESH-INF/thing/channels.xml#L62).

So the question is whether we want to create multiple `group-channel`s where we override their children differently, or if we create a mechanism to override nested labels, i.e. the label of a channel in a `group-channel`.

**Comment by lolodomo** [comment]
The fix is technically extremely simple, you just have to add a description tag in addition to the label tag for each channel group.
The only difficulty is to define a correct description which means having a clear understanding of all the astro data... The minimum solution would be to duplicate the label into the description.

**Comment by wborn** [comment]
The binding also has references in the code and labels to "planet". Our sun and moon are not planets. Perhaps we can use something like "celestial body" instead? 

See also Wikipedia:
* [Planet](https://en.wikipedia.org/wiki/Planet)
* [Astronomical object](https://en.wikipedia.org/wiki/Astronomical_object)

**Comment by triller-telekom** [comment]
Oh I see, I thought you wanted to rename the "Start time", "End time" per channel group, but you guys were talking about the "Range for a sun event" description...
