### ISSUE TITLE
mDNS background discovery cannot be set dynamically by the config admin

### ISSUE THREAD

**Issue by hsudbrock** [eclipse/smarthome#5323]
The `o.e.sh.config.discovery.mdns.internal.MDNSDiscoveryService` extends the `org.eclipse.smarthome.config.discovery.AbstractDiscoveryService`, which provides a `modified` method to enable and disable background discovery at runtime using the config admin. In addition, the `MDNSDiscoveryService` has a `configurationPid`, which indicates that it is intended to be configurable using config admin. However, the `MDNSDiscoveryService` is missing a method annotated with `@Modified` (which could call the modified method of the `AbstractDiscoveryService`), and, hence, background discovery cannot be set dynamically by the config admin.

I guess that this method is just missing, since I do not see a reason why this dynamic config update should not be possible (as it is for other discovery services extending the `AbstractDiscoveryService`, e.g., the `UpnpDiscoveryService`).

(Without a modified method, the `MDNSDiscoveryService` can of course still be configured using the config admin, but the configuration must be in place before the `MDNSDiscoveryService` is activated.)

**Comment by kaikreuzer** [comment]
I would guess you are right, so I'll happily accept a PR that fixes this :-)

**Comment by kaikreuzer** [comment]
Fixed through #5324.
