### ISSUE TITLE
[Compact Profile 2] Javasound bundle depends on Full JRE

### ISSUE THREAD

**Issue by svilenvul** [eclipse/smarthome#5328]
Looking at the report generated by https://github.com/openhab/static-code-analysis/pull/283, I see that one package in `org.eclipse.smarthome.io.javasound` bundle depends on `javax.sound.sampled`.

This is a violation of C.1 in the ESH coding guidelines https://www.eclipse.org/smarthome/documentation/development/guidelines.html#c-language-levels-and-libraries.

**Comment by sjka** [comment]
@svilenvul  We'll need an exception for this bundle (`org.eclipse.smarthome.io.javasound`)
