### ISSUE TITLE
kWh are not recognized as Energy values

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#5341]
The recently introduced unit support has an "Energy" dimension defined, which uses by default the SI unit "J" (Joule).
In practice, the alternative "Wh" are used much more frequently and thus I would expect this unit to be usable for items with `Energy` dimension.

I defined an Item like this:
```
Number:Energy Energie			"Energie [%.1f kWh]"
```
Sending a value on the console
```
smarthome send Energie 123.456
```
results in
```
2018-04-03 13:27:05.491 [DEBUG] [.e.s.core.types.util.UnitUtils:108  ] - Unknown unit from pattern: kWh
```
and no unit being assigned to the item state.

As energy is likely the most common use case besides weather for units, I'd consider this a rather critical issue that needs to be addressed quickly. See also https://github.com/openhab/openhab2-addons/pull/2167#discussion_r178578851.

**Comment by J-N-K** [comment]
I have created a patch for that. Please note, that  `kW·h` is the correct notation, not `kWh`.

**Comment by ggzengel** [comment]
https://de.wikipedia.org/wiki/Wattstunde

**Comment by ggzengel** [comment]
I was a little bit more searching and found here https://en.wikipedia.org/wiki/Kilowatt_hour:
> The symbol "kWh" is commonly used in commercial, educational, scientific and media publications,[5][6] and is the usual practice in electrical power engineering.[7]

The main usage in OH2 is for reference of electrical power, so I would like to see (k)Wh.

**Comment by ggzengel** [comment]
Now the last one:
http://www.electropedia.org/iev/iev.nsf/display?openform&ievref=131-11-58

**Comment by kaikreuzer** [comment]
> Please note, that kW·h is the correct notation, not kWh

`kWh`, just like `Wh` and `Ws` must be supported. As @ggzengel rightly pointed out, these are also the officially used unit identifiers.

**Comment by J-N-K** [comment]
I‘ll see what can be done about that.

**Comment by ggzengel** [comment]
Does this help?
https://www.programcreek.com/java-api-examples/?code=unitsofmeasurement/uom-demos/uom-demos-master/domain/energy-se/src/main/java/tec/uom/demo/energy/se/HeatRequirementDemo.java

**Comment by J-N-K** [comment]
Thanks. I already found a solution.
