### ISSUE TITLE
[BasicUI] UI does not respond to events

### ISSUE THREAD

**Issue by dimalo** [eclipse/smarthome#5348]
Installed Version:
openhab2=2.3.0~20180331153334-1
Working on debian for armhf and zulu8 embedded.

Cleared website caches.
Loading sitemap in Firefox or Chrome (latest stable versions) results in not responding UI.
The UI loads, but no element can be clicked, nor can the sitemap be navigated.

Chrome Dev Tools console shows
<img width="665" alt="bildschirmfoto 2018-04-04 um 00 13 27" src="https://user-images.githubusercontent.com/26287094/38278707-707eeca6-379d-11e8-866a-f907d694e207.png">
Firefox shows:
<img width="466" alt="bildschirmfoto 2018-04-04 um 00 16 57" src="https://user-images.githubusercontent.com/26287094/38278730-83744680-379d-11e8-98f7-b1bf4f62993e.png">

Installed 2.3.0~20180325175928-1, cleared caches, still the same behaviour.

**Comment by sjka** [comment]
I can confirm this on latest master. 
@resetnow could you please have a look at this?
