### ISSUE TITLE
Item Colorpicker doesn't work on Sitemap-Top-Level (BasicUI)

### ISSUE THREAD

**Issue by michaeljoos72** [eclipse/smarthome#5366]
As soon as I place a Colorpicker on the Sitemap-Top-Level it doesn't work anymore. In addition BasicUI doesn't refresh automatically. Within another Text-Part everything is working as expected.

Working:

		Text label="Garage" icon="garage" {		
			Frame label="Licht" {
				Switch item=Light_GarageWest_Toggle
				Colorpicker item=Light_GarageWest_Dimmer
				Switch item=Light_GarageOst_Toggle
				Colorpicker item=Light_GarageOst_Dimmer
			}		
		}

Not working:

			Frame label="Licht" {
				Switch item=Light_GarageWest_Toggle
				Colorpicker item=Light_GarageWest_Dimmer
				Switch item=Light_GarageOst_Toggle
				Colorpicker item=Light_GarageOst_Dimmer
			}

I see following error-message in Chrome:

Uncaught TypeError: Cannot read property 'map' of undefined
    at new y (smarthome.js:1)
    at smarthome.js:1
    at NodeList.forEach (<anonymous>)
    at L.r.initControls (smarthome.js:1)
    at HTMLDocument.<anonymous> (smarthome.js:1)

openHAB 2.3.0 Build 1248

**Comment by triller-telekom** [comment]
This was fixed in PR #5357 and should be available in openhab snapshot 1250.

@sjka @htreu Can you please close this issue?

**Comment by michaeljoos72** [comment]
yes, it's working in 1250 :)
