### ISSUE TITLE
Basic UI: set label/value color for QuantityType states

### ISSUE THREAD

**Issue by htreu** [eclipse/smarthome#5368]
From this comment https://github.com/eclipse/smarthome/issues/5243#issuecomment-378665172:

> How does it work? I didn't find an example. What has to be changed in the following line?
`Text item=fritzWashingMachineDECT200Temperature label="FRITZ!DECT 200 (Waschmaschine) [%.1f %unit%]" valuecolor=[<15="blue", <=18="green", <=21="orange", >21="red"]`
// EDIT: Item type is Number:Temperature.

The label- and value-colors definitions are not matched correctly against QuantityType states.
Since the syntax leaves little room for an extension I suggest to compare to the scalar value of the widget unit (which falls back to the item unit if not explicitly defined, like in the example above).

**Comment by lolodomo** [comment]
I think we should be able to define the valuecolor attribute like that! `valuecolor=[<15°C="blue", <=18°F="green", <=21K="orange", >21="red"]`
Values are stupid but it is only to show the syntax.
If unit is not mentioned, I am not sure what unit tshould be considered.
The code that is doing these comparisons is here: https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java#L882

**Comment by lolodomo** [comment]
Please note that this problem is not specific to Basic UI but impacts all UIs.

@htreu: can you please fix the method I pointed ? That should be really easy for you who have a perfect knowledge of QuantityType.
A fix in this method will fix at the same time the 3 sitemap attributes labelcolor, valuecolor and visibility.

**Comment by J-N-K** [comment]
I don‘t think it makes much sense to put the units in the Sitemap (aside from the label). It is much more intuitive that the unit for the values is the same as used in the label.

Therefore I would vote for htreu‘s Suggestion.

**Comment by lolodomo** [comment]
It could complex in this case to identify the right unit because the label is only an option in the sitemap. If not defined in the sitemap, the label to be used is the item label. And if item label is not defined, the label to consider is the pattern is the channel type.

**Comment by J-N-K** [comment]
I don't think it's very difficult. At least from the code side. If the `state` is `QuantityType` it is converted to the displayed units before the state is passed to the color matching code. So we have it available in the unit that is displayed later on.

**Comment by lolodomo** [comment]
If this is easy and if the solution is not confusing for a normal user, let's go.
