### ISSUE TITLE
ClassicUI essentially blank

### ISSUE THREAD

**Issue by openhab-5iver** [eclipse/smarthome#5374]
All it displays is this…
```
<root><part><destination mode="replace" zone="timeout" create="false"/><data/></part></root>
```
No errors. BasicUI displays properly, and 1247 displayed properly too. Clearing the sitemap to display a single item did not help. Others are reporting this too.

https://community.openhab.org/t/2-3-0-snapshot-1250-classicui-essentially-blank/43252

OH 2.3.0 snapshot 1250
ESH 0.10.0.201804051647
Firefox, Chrome

**Comment by hr3** [comment]
I get this error
`2018-04-06 23:22:54.455 [ERROR] [clipse.smarthome.io.transport.serial] - Component descriptor entry 'OSGI-INF/*.xml' not found`

**Comment by bigbasec** [comment]
Same issue here, Classic UI is completely broken.
