### ISSUE TITLE
[core] Handle exceptions in constructor of e.g. DecimalType

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#5439]
From this comment https://github.com/eclipse/smarthome/issues/4104#issuecomment-361009347

> While testing #4963 I found another situation which could be handled in a different way:
> 
> https://github.com/eclipse/smarthome/blob/da57eda4edd9d41bbf41316f23e1b9b29687069b/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/DecimalType.java#L54-L56
> 
> The constructor [BigDecimal(String val)](https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#BigDecimal-java.lang.String) throws a `NumberFormatException` if `val` is not a valid representation of a `BigDecimal`. I suggest to catch the exception and return `DecimalType.ZERO` or `new DecimalType()`.

The different types are public API and can be used in rules. We should discuss about introducing an exception handling if a user passes a value with wrong format to one of them.

**Comment by kaikreuzer** [comment]
>  catch the exception and return DecimalType.ZERO

I don't think that this would be an adequate solution - from a Java API perspective, an exception is the right way to respond.

> We should discuss about introducing an exception handling

This is in the context of DSL rules then. Did you try whether [try-catch blocks](https://www.eclipse.org/xtend/documentation/203_xtend_expressions.html#xtend-expressions-try-catch) work for rules? If so, would that already solve the issue?

**Comment by kaikreuzer** [comment]
I just tried this:
```
    try {
        val x = new DecimalType("abc")
    } catch(Exception e) {
        logInfo("test", "Caught expected exception")
    }
```
And it works as expected - I would claim that this solves the issue.
