### ISSUE TITLE
Selectively auto-approve inbox entries

### ISSUE THREAD

**Issue by hsudbrock** [eclipse/smarthome#5483]
**Context**
Currently, the `o.e.sh.config.discovery.internal.AutomaticInboxProcessor` can be configured to automatically approve *all* added inbox entries (using the configuration flag `autoApprove`).

**Issue**
I would like to be able to automatically approve only selected inbox entries (in particular, only auto-approving inbox entries for selected thing types).

**Possible solutions**
I see two options for implementing this:
1. Adding configuration parameters for specifying which inbox entries should be auto-approved (E.g., a parameter specifying a whitelist of thing types for which inbox entries are auto-approved).
2. Providing a possibility to hook into the `AutomaticInboxProcessor`, so that bundles can participate in the decision whether an inbox result is automatically approved.

I prefer the second option, because it is quite flexible (unlike the first solution - unless one allows to encode complex expression for inbox entries in config parameters). 

**Suggested solution**
For the second solution, my proposal would be to:
* add an interface with a method `boolean autoApprove(discoveryResult)`;
* inject DS components implementing this interface into the `AutomaticInboxProcessor`;
* for each added inbox result, query each of these components whether the inbox result should be auto approved; auto approve it if at least one of the components votes for auto approval.

With this solution, the components implementing the interface specify a whitelist of discovery results that are to be automatically approved. 

These auto approvals would apply if the current property `autoApprove` is set to `false`; if `autoApprove` is set to `true`, all inbox entries will be auto-approved anyway. In consequence, the name `autoApprove` is not perfect anymore, as inbox entries can be auto approved even when this property is set to `false`. A better name for this property would then be `alwaysAutoApprove`, but this probably should not be changed as it would be API breaking.

**Comment by kaikreuzer** [comment]
I'm ok with option 2 as long as the docs of this interface clearly state that it is only meant to be implemented by solutions, but not by add-ons.

> add an interface with a method boolean autoApprove(discoveryResult);

My suggestion would be that this interface extends `Predicate<DiscoveryResult>` - that makes it easy to be used within closures.

>  the components implementing the interface specify a whitelist of discovery results that are to be automatically approved.

The alternative would be to veto auto-approval. In that case `autoApprove=false` would be the same as before and `autoApprove=true` would be slightly enhanced by giving solutions a chance to not apply it blindly to any result. This would imho be the smoother extension of the current feature.

**Comment by hsudbrock** [comment]
> I'm ok with option 2 as long as the docs of this interface clearly state that it is only meant to be implemented by solutions, but not by add-ons.

OK

> My suggestion would be that this interface extends Predicate<DiscoveryResult> - that makes it easy to be used within closures.

That's a good hint, thanks!

> The alternative would be to veto auto-approval. In that case autoApprove=false would be the same as before and autoApprove=true would be slightly enhanced by giving solutions a chance to not apply it blindly to any result. This would imho be the smoother extension of the current feature.

I thought so as well at first; the problem I see with vetoing auto-approval is that the "vetoing components" might be injected into the `AutomaticInboxProcessor` too late. On activation, the `AutomaticInboxProcessor` will auto-approve all inbox entries if `autoApprove=true`, and at that time, the "vetoing components" might not yet have been injected. (This problem could be solved by declaring the "vetoing components" as static dependencies, as those are registered before the `activate` method is called; however, this has the disadvantage that the vetoing can not be so easily changed at runtime anymore.) This is why I chose the "less smooth" extension of the current feature.

What do you think, @kaikreuzer ?

**Comment by kaikreuzer** [comment]
Ok, convinced ;-) A (temporary not present) blacklist is indeed pretty risky, so going for a whitelist is the better option.

**Comment by maggu2810** [comment]
Thanks for the fix.
Please use one of the "closing keywords" next time: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by kaikreuzer** [comment]
So I assume this can be closed, right?

**Comment by hsudbrock** [comment]
Yes, this can be closed. Thanks for the hint with the closing keywords, @maggu2810.
