### ISSUE TITLE
Missing Beaufort unit

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5504]
Beaufort is missing as unit for the wind speed.

**Comment by wborn** [comment]
We discussed adding it in https://github.com/openhab/openhab2-addons/pull/3497. It's not really a unit but a scale.

**Comment by lolodomo** [comment]
We might be not able to handle an entry speed in Beaufort and then convert it in km/h but we should certainly be able to display a wind speed in Beaufort when the entry value is in km/h.

Is it impossible to have a one direction conversion ?

I think the user should be able to use "Bft" as unit in iutem/sitemap. I remember this was asked by a user for the netatmo binding in the forum.
Note that the netatmo app is able to display values in Beaufort while the API is providing the speed in km/h.

**Comment by wborn** [comment]
> Is it impossible to have a one direction conversion ?

It's a scale with a lot of history and some peculiarities. 

See also "Conversion Of Anemometer Winds To Beaufort Numbers" on page 24 of this [PDF](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.543.440&rep=rep1&type=pdf).

Peculiarity: 

> If velocities expressed in m/s are used to determine the Beaufort wind force, the result
sometimes differs from the wind force when the equivalent value expressed in knots or
miles per hour was used.

**Comment by kaikreuzer** [comment]
I agree with @wborn that this won't work as a unit - I'd recommend that users use the [scale transformation](https://github.com/eclipse/smarthome/blob/master/extensions/transform/org.eclipse.smarthome.transform.scale/README.md) instead.
