### ISSUE TITLE
[test failures] MQTT: BrokerHandlerTest fails randomly

### ISSUE THREAD

**Issue by htreu** [eclipse/smarthome#5527]
The `BrokerHandlerTest#handlerInit` test case fails randomly. This may be due to timing issues.

**Comment by davidgraeff** [comment]
Yes. I did some work on io.mqtt, that's where the problem comes from. it's not finished yet. But I might come around to upload something in the evening.

**Comment by davidgraeff** [comment]
Fixed with a Future based API on `MqttBrokerConnection`. See #5535

**Comment by sjka** [comment]
How about this one?

```
testDiscovery(org.eclipse.smarthome.binding.mqtt.internal.discovery.NetworkDiscoveryServiceTest)  Time elapsed: 0.388 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <4>
     but: was <0>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.eclipse.smarthome.binding.mqtt.internal.discovery.NetworkDiscoveryServiceTest.testDiscovery(NetworkDiscoveryServiceTest.java:112)
```

Is it also covered by one of your PRs?

**Comment by davidgraeff** [comment]
Most likely. I touched the discovery class as well.
