### ISSUE TITLE
XPATH in label, when xml contains namespace

### ISSUE THREAD

**Issue by Josar** [eclipse/smarthome#5547]
The XPATH transformation in a label seems to make some problems, when the xml contains a namespace which has to be resolved.
```
String http_Info_1 "Info [%s]" {http="<[http://campulverde.info/liveStreams.xml:60000:XPATH(/*[name()='liveStreams']/*[name()='stream']/*[name()='label'])]"}
String http_Info_2 "Info [XPATH(/*[name()='liveStreams']/*[name()='stream']/*[name()='label']):%s]" {http="<[http://campulverde.info/liveStreams.xml:60000:REGEX((.*))]"}
```

The first one is working, the second one does not, probably as the XPATH contains `[ ]`.

**Comment by sjka** [comment]
The problem is this line in `GenericItemProvider`:

https://github.com/eclipse/smarthome/blob/b5d4e9884e9e3713ee48178ed5b71ad14b36cb35/bundles/model/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java#L283
