### ISSUE TITLE
Filtering for multiple ReadyMarkers

### ISSUE THREAD

**Issue by marQus3** [eclipse/smarthome#5563]
Having the ReadyMarkerFilter is nice, unfortunately it does not quite offer the functionality I need.
The requirement ist to filter for **multiple types of ReadyMarkers** (in my case two). But:
- ReadyMarkerFilter only allows one type
- registering a ReadyTracker at the ReadyService only allows one ReadyMarkerFilter
- one ReadyTracker cannot be registered twice with different filters

Please evaluate if changing one of the restrictions above would be worth implementing.

**Comment by sjka** [comment]
> the functionality I need

May I ask what you use-case is? The ReadyService stuff is meant to be used within the framework only, especially not for bindings...

**Comment by marQus3** [comment]
My binding needs to migrate things and adds channels that are defined in the thing type XMLs.
So it uses ThingTypeRegistry and ConfigDescriptionRegistry. For this, the registries don't just need to be available, they must have loaded all necessary XMLs, hence the waiting for "ready".
You could ask @FrankZimmer about this use case.

**Comment by kaikreuzer** [comment]
This conversation makes me quiver.

Binding MUST NOT use `ReadyService`, `ThingTypeRegistry` nor `ConfigDescriptionRegistry`.
All the things that you mention should be possible from within the `ThingHandler`.
If there is anything specific missing, please file an enhancement request and it can be discussed how the binding/handler API can be enhanced.

**Comment by marQus3** [comment]
OK, I'll change the concept.
However right now, I don't see a possibility for the binding to access even its "own" ThingType/Channel definitions loaded from XML other than via the ThingTypeRegistry.

**Comment by marQus3** [comment]
@kaikreuzer 
By the way (and no offense), you can find sentences like "All available configuration descriptions are accessible through the org.eclipse.smarthome.config.core.ConfigDescriptionRegistry service" in the "Binding development"(!) section of the documentation (http://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#configuration-descriptions).
