### ISSUE TITLE
Feature request: Auto-generated sitemaps

### ISSUE THREAD

**Issue by Tony-Hu** [eclipse/smarthome#5569]
I was inspired by the [issue#4942](https://github.com/eclipse/smarthome/issues/4942)
For now, the paper UI provides a way to prevent us from writing Things and Items configurations from scratch. I'm wondering that is that possible to do the same stuff in paper UI(or other UIs as well) to have an auto-generated sitemap file? 
And, perhaps the auto-generated sitemap has a special name like "auto_config.sitemap". In this case, people don't have to update their own sitemaps immediately when they finish configuring with paper UI. Whatsmore, people can do some part of copy&paste from part of the auto-generated sitemap.

In this case, the "auto_config.sitemap" will always available on basic UI and mobile clients.

**Comment by kaikreuzer** [comment]
Such a feature is [already implemented in openHAB](https://github.com/openhab/openhab-core/blob/47bfddeecdfdbd8b289bc6b7e2f34c0e1badb721/bundles/org.openhab.core/src/main/java/org/openhab/core/internal/item/DefaultSitemapProvider.java#L28-L29), but it honestly didn't proof to be very useful. (the only difference is that it does not physically write a sitemap file, such a feature is already supported by the [VS Code extension](https://github.com/openhab/openhab-vscode#features)).

The plan for ESH is rather to have [editable sitemaps](https://github.com/eclipse/smarthome/issues/5337) and for those an initial version could be automatically suggested.
