### ISSUE TITLE
NetworkAddressService listener

### ISSUE THREAD

**Issue by tmrobert8** [eclipse/smarthome#5581]
Not really sure if this in important enough to actually do - but if the consensus is that it's a good idea, I can add it pretty easily...

It would be nice if this interface included a listener for changes to the addresses (propertychangelistener or custom listener).  

If there is a binding (let's say the NEEO Brain binding) that registers a callback URL with the remote device and our primary address changes, that callback needs to be updated.  Currently, the only way to 'update' that callback is to restart the binding - but if there was a listener on the interface, then it can be done automatically.

Thoughts?

**Comment by maggu2810** [comment]
What is your plan that your implementation looks like?
AFAIK the JVM does not provide a method to watch for that changes.
Do you consider to schedule a job that checks the address of an interface every x seconds and identify the change yourself?
Then we should perhaps think about "interface gone" and "interface added", too (up / down, too?).

**Comment by garytse** [comment]
I have a need on something like this and is starting to work on it.  The API should be just a plain change listener.   The implementation is probably just scheduled polling.

**Comment by garytse** [comment]
With regards to #5581, you are right, I missed the last comment.  This is hardware level dectection of changed network address instead of the paper ui configuration.

**Comment by triller-telekom** [comment]
@tmrobert8 Did you have a look at #5802 yet? Does this suit your needs for a address change listener? I guess your use-case can be covered by that. Would you like to give it a try and close this issue afterwards, please?

**Comment by tmrobert8** [comment]
Yes it does.  I'll pull the latest and give it a try.  Will close afterwards

**Comment by tmrobert8** [comment]
@triller-telekom @garytse 
Actually this does NOT (atleast from what I was envisioning) - what I was hoping a listener that will notify me of **primary** ip address change (ie that is set via PaperUI->Configuration->System->Network Settings->Primary Address).  The design Gary put together would work however - just add a "onPrimaryAddressChange(String oldIpAddress, String new ipAddress)" then call it on the poll method if the address has changed since the last poll

**Comment by triller-telekom** [comment]
@garytse Such a method would be API breaking. Do you think its worth adding it to your interface?

**Comment by triller-telekom** [comment]
I think @tmrobert8 was planning to watch for changes on the `primaryAddress` field, i.e. notifying listeners once this is set.

Would you like to come up with a PR for that @tmrobert8 ?

**Comment by tmrobert8** [comment]
Will do

**Comment by tmrobert8** [comment]
@triller-telekom 
Ok - this is going to sound really stupid but I've forked the repository, created my new branch and made my changes locally (note: this is the first time I've tried to modify the smarthome stuff - so consider me a newbie here).  

I'm using the openHAB eclipse environment btw.  I've modified my binding to use the NetworkAddressChangeListener - everything in eclipse compiles fine but when I run it - I get
```
Scheduled runnable ended with an exceptionjava.lang.NoClassDefFoundError: org/eclipse/smarthome/core/net/NetworkAddressChangeListener
```
(btw - someone should add a space between exceptionjava in that message - but that's a different issue).

How do I expose the changes to the smarthome project to the openhab bindings?

**Comment by triller-telekom** [comment]
@tmrobert8 No worries, there are no dump questions :)

You have changed the `NetworkAddressChangeListener` which is in the bundle `org.eclipse.smarthome.core`. The openHAB IDE is configured to use pre-compiled bundles for all bundles which are from ESH. So what you ened to to to make it pick up your change is:

* open the run configuration of the openHAB instance that you want to run from your IDE
* go to the plug-ins tab
* search for `org.eclipse.smarthome.core` and remove it from the targetplatform branch and check its chekbox for the `workspace` branch.

If you run openHAB with this modified run configuration it will pick up all the changes you did in your workspace to that bundle. Hope that helps.

**Comment by tmrobert8** [comment]
@triller-telekom 
Thanks - that helped!  (also need to do that on the upnp and mdns ones since they reference it as well) - all good now.

Last question before I submit the PR - what's the naming standard (if there is one) for the branch name?

**Comment by tmrobert8** [comment]
Good enough - PR https://github.com/eclipse/smarthome/pull/5919
