### ISSUE TITLE
Thing type migration ignores thing type properties

### ISSUE THREAD

**Issue by hsudbrock** [eclipse/smarthome#5600]
*Context*: 
The method `o.e.sh.core.thing.internal.ThingManager.thingHandlerCallback#migrateThingType(...)` permits to migrate a thing from one thing type to another. This is, e.g., used when changing thing types in `o.e.sh.core.thing.binding.BaseThingHandler#changeThingType(...)`.

*Issue*:
The thing type migration currently ignores thing type properties. When, for instance, a thing is migrated to `thingTypeB`, and `thingTypeB` has a property `someProperty` with value `someValue`, I had expected that the thing will have this property set after thing type migration as well (similar to when a `Thing` is created from a `ThingType` in `ThingFactory#createThing(...)`; here thing type properties are also copied to the thing).

*Solution suggestion*:
When migrating a thing from thing type A to thing type B, add all properties of thing type B to the thing; this will keep all of the thing's properties that were there before the thing type migration (unless thing type B defines a property with the same name as a property of the thing).

This solution will be useful when specializing a thing type from the more generic to the more concrete, an example is the ZigBee binding: https://github.com/openhab/org.openhab.binding.zigbee/pull/169 wants to add static thing type definitions to the ZigBee binding, and the properties specified in those static thing types should end up as thing properties, in addition to the properties that are already defined before migrating to the new thing type.

Unless there is dissent on how this should be resolved, I could provide a PR implementing this solution.

**Comment by sjka** [comment]
No dissent on my side at least. I simply didn't think of the properties defined in thing types when implementing #768. It makes sense though from my point of view. Thanks for creating the fix!
