### ISSUE TITLE
Show channels grouped by their group

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#561]
When displaying the channels of a Thing, the Paper UI currently shows all channels as a flat list.
Instead, the channel groups should be made visible by grouping the according channels visually as well.

**Comment by maggu2810** [comment]
What is the indent style we should use for JavaScript files? The paper UI is using spaces and tabs mixed.

**Comment by kaikreuzer** [comment]
Probably spaces as well, wdyt?
Is there auto-formatting for Javascript in Eclipse?

**Comment by maggu2810** [comment]
There is a feature "JavaScript Development Tools" (org.eclipse.wst.jsdt.feature.feature.group) in the categories "Programming Languages" and "Web, XML, Java EE and OSGi Enterprise Development".

After installing that feature there are a JavaScript category in the properties.
This category contains e.g. code style - clean up, code style - formatter, editor - save actions, ...

**Comment by maggu2810** [comment]
For me it doesn't matter (using tabs or spaces), but perhaps we should use tabs.
The usage is currently mixed, but there are much more tabs as spaces.
The one argument that is really a good one for tabs is, that you use one tab for one indent (not 4 spaces for one indent). If you would like to see small / large indents, it is just a matter of the editor (the visualization of a tab).

**Comment by sjka** [comment]
I really don't want to start the famous tabs vs. spaces discussion here. But as we are using spaces in the java code already, shouldn't we simply do it the same everywhere and use spaces consistently no matter what kind of language it is?

**Comment by cdjackson** [comment]
Just one comment - javascript is interpreted, so this will directly impact file size and UI loading time unless the files are minified (which I don’t think is done now in Paper UI). How much difference this makes is a different matter, but as the code grows, it might become significant.

**Comment by sjka** [comment]
@cdjackson valid point - I'd count this as a vote to minify the Paper UI though. I therefore created #676.

**Comment by cdjackson** [comment]
I agree - it’s certainly the best approach.

**Comment by kaikreuzer** [comment]
@maggu2810 So indentation for HTML and XML is done with tabs? Than we could imho also do tabs for JS...

**Comment by maggu2810** [comment]
That are the current settings.

**Comment by kaikreuzer** [comment]
implemented in https://github.com/eclipse/smarthome/pull/987
