### ISSUE TITLE
[Paper UI] Control page keeps showing "No Things available"

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#5615]
The Control page in Paper UI shows the message "No Things available" when you navigate to the Control page from any another Paper UI page. When you reload the Control page this message disappears:

![selection_003](https://user-images.githubusercontent.com/12213581/40451923-7a9ac52e-5ee0-11e8-81fc-c40c5037f366.png)

CC @htreu

**Comment by sjka** [comment]
Looks to be a side-affect of the bug which gets fixed by #5608

**Comment by kaikreuzer** [comment]
Fixed by #5608.
