### ISSUE TITLE
Documentation about I18N is broken

### ISSUE THREAD

**Issue by afuechsel** [eclipse/smarthome#562]
The documentation page about i18n is broken. Jekyll generated output is not correct. https://www.eclipse.org/smarthome/documentation/features/internationalization.html

**Comment by maggu2810** [comment]
@afuechsel Is the documentation page still broken?

**Comment by afuechsel** [comment]
No. Looks good now.

**Comment by maggu2810** [comment]
Okay, then I will close this issue.
