### ISSUE TITLE
Metadata Information No Longer Available via REST API

### ISSUE THREAD

**Issue by jsetton** [eclipse/smarthome#5632]
I just updated to the latest openHAB 2.3.0-SNAPSHOT Build #&#xfeff;1288 and I am no longer able to get metadata information through the REST API. It looks like that this might be related to #5576.

**Item**
```
Switch TestSwitch "Test Switch" ["foobar"] {foo="bar" [baz=42]}
```

**Result**
```
curl -s -X GET --header "Accept: application/json" http://localhost:8080/rest/items/TestSwitch?metadata=foo | jq
{
  "link": "http://localhost:8080/rest/items/TestSwitch",
  "state": "NULL",
  "editable": false,
  "type": "Switch",
  "name": "TestSwitch",
  "label": "Test Switch",
  "tags": [
    "foobar"
  ],
  "groupNames": []
}
```

**Comment by sjka** [comment]
Yes, indeed, good analysis!It looks like #5576 broke it by only returning metadata which also has a config description.
