### ISSUE TITLE
openhab 2: Bose Soundtouch Binding: missing Source Type 'TUNEIN' and ALEXA

### ISSUE THREAD

**Issue by zr2002** [eclipse/smarthome#5636]
Because of missing Source Type 'TUNEIN' it will be log a warning in openhab.log
Tested devices: Soundtouch 10, 20, 30, 300
TuneIn and Alexa ist a default Source Type like Deezer, Amazon Music, etc.

Warning:
 [WARN ] [.bosesoundtouch.internal.ContentItem] - Unknown SourceType: 'TUNEIN' - needs to be defined!
[WARN ] [.bosesoundtouch.internal.ContentItem] - Unknown SourceType: 'ALEXA' - needs to be defined!

**Comment by kaikreuzer** [comment]
@tratho or @marvkis, could you please have a look at that?

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/eclipse/smarthome/pull/5639.
