### ISSUE TITLE
DateTime item-type not displaying consistently in classic UI / PaperUI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#564]
created a new binding for NTP in a OH2 way. However, having difficulties displaying the data.

When in the channel-type definition I define the channel with <item-type>DateTime</item-type>
and do the update updateState(c.getUID(), new DateTimeType(calendar));
It does not show consistently between the paper-UI and the classic UI.

If there is no <state>description, it displays fine in the paperUI, but it remains empty in the classic UI.
if I add <state readOnly="true" pattern="%1$tA, %1$td.%1$tm.%1$tY %1$tT"></state> it displays fine in classic UI, but in paperUI it shows {{getStateText(item)}}

Expected behavior is that the paperUI shows the date/time according to the pattern.

Note: transfered from issue https://github.com/openhab/openhab2/issues/374
Possibly related to https://github.com/openhab/openhab2/issues/229 as this shows the same error in the browser console
```
SyntaxError: [sprintf] unexpected placeholder
    at Function.b.parse (sprintf.js:151)
    at b (sprintf.js:17)
    at n.$scope.getStateText (controllers.control.js:77)
    at ib.functionCall (angular.min.js:199)
    at Object.<anonymous> (angular.min.js:107)
    at n.$get.n.$digest (angular.min.js:123)
    at n.$get.n.$apply (angular.min.js:126)
    at l (angular.min.js:81)
    at M (angular.min.js:85)
    at XMLHttpRequest.F.onload (angular.min.js:86)
```

**Comment by maggu2810** [comment]
#629 has been fixed, this one too?

**Comment by kaikreuzer** [comment]
Needs to be retested, I cannot tell.
