### ISSUE TITLE
[Paper UI] TypeError: Cannot read property 'metadata' of undefined

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#5646]
I got a JS error after I tried to edit the metadata of this new item in the Configuration -> Item section.

![bildschirmfoto vom 2018-05-25 20-45-33](https://user-images.githubusercontent.com/5131747/40561370-39966366-605d-11e8-83e5-4d14588f3bc0.png)
![bildschirmfoto vom 2018-05-25 20-45-38](https://user-images.githubusercontent.com/5131747/40561350-2517617e-605d-11e8-953c-5e83ded8f201.png)

**Comment by kaikreuzer** [comment]
@htreu I remember seeing this as well. Any easy fix for it?

**Comment by htreu** [comment]
I retested this. Should already be fixed by #5640.
