### ISSUE TITLE
weatherunderground binding - no more free APIs

### ISSUE THREAD

**Issue by Rob-VF** [eclipse/smarthome#5659]
For your information:

**To improve our services and enhance our relationship with our users, we will no longer provide free weather API keys as part of our program. If you have been directed to download our Weather Underground free API key by a third party provider, please contact your vendor for resolution**

Source: https://www.wunderground.com/weather/api/

**Comment by kaikreuzer** [comment]
Sounds like bad news 😞 .
@lolodomo What does that mean for our WU binding? Will it be of no use to any new user now?

**Comment by lolodomo** [comment]
Unfortunately I think it is what it means.
We should implement another weather binding based on another provider.

**Comment by triller-telekom** [comment]
That's a real pity :(
Some people on openHAB already make use of the [openweathermap API](https://openweathermap.org/API) via the old generic openhab1 weather binding. Would it be an option to have a specific openhab2 binding for it? Though they also use an API key and who knows if we might run into the same situation again...

Are there any free alternatives which also offer forecasts? @lolodomo since you have had a look on quite some weather providers, did you come across one without the need for such an API key?

**Comment by lolodomo** [comment]
I have not yet studied what could be a good candidate. But I remember that someone has already started implementing a new bidning but I don't remember what provider he chose. I have to search for his message.

**Comment by 9037568** [comment]
@lolodomo were you thinking of #4821?

**Comment by lolodomo** [comment]
No, I think it was with a provider we already handle in the 1.x weather binding.

**Comment by lolodomo** [comment]
I just found in another issue that my intention was to create a new binding using World Weather Online as provider.

**Comment by lolodomo** [comment]
I am not sure at all that World Weather Online API terms of use could be compatible with our usage.
https://developer.worldweatheronline.com/api/free-api-terms.aspx
WDYT ?

**Comment by lolodomo** [comment]
We can forget World Weather Online, free API was discontinued one year ago: http://discuss.worldweatheronline.com/t/free-api-has-now-been-discontinued/54

**Comment by cweitkamp** [comment]
I worked for a long time on a private version of a OpenWeatherMap binding. I finally did some progress to make it public. (See PR #5694).

**Comment by lolodomo** [comment]
With 2 new weather bindings in the pipe, openweathermap and meteoblue, I think we can now close this issue.

**Comment by sjka** [comment]
Indeed, doesn't look like we could do anything else about it. 
Thanks for bringing this up and thereby creating the momentum!

**Comment by lolodomo** [comment]
It looks like they stopped refreshing data since two days !!! Can someone confirm this very bad news ?
Note that I continue receiving data but unmodified data.

**Comment by lolodomo** [comment]
Am I alone with no more updated data by WU ?

**Comment by lolodomo** [comment]
I can see that it is working again since few days.

**Comment by triller-telekom** [comment]
![image](https://user-images.githubusercontent.com/26876013/42365636-546d7aae-80ff-11e8-8d5d-fe1318969517.png)

There were some hickups as I assume due to the straight horizontal lines, but except for that it was working fine for me.

**Comment by lolodomo** [comment]
Working again. It seems that the request sometimes failed.

**Comment by dk8pn** [comment]
Hello all,

they still provide a new type of API key for private weather stations (PWS) who upload their data to weatherunderground. But this key doesn't work out with the existing binding. Could the binding be changed at least for PWS users (assuming that there are anough running openHAB)? For me this binding was also the platform to access my Davis weather station data (is basically the source of my weatherunderground PWS data).

Best regards,
Willi

**Comment by openhab-5iver** [comment]
#6883

https://community.openhab.org/t/weatherunderground-replacement-for-pws-data-uploaders-only/69122
