### ISSUE TITLE
Support more configuration features

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#566]
At the moment the following configuration features are not yet supported, but the Paper UI should be able to use this information when rendering the configuration pages:
- min
- max
- advanced (hidden by default, shown only by pressing a "more" button)
- groupName (labeled frames that group parameters with the same groupName)
- limitToOptions (best by a free input field with auto-completion feature)

Let's leave the "multiple" stuff out of scope for now.

**Comment by kaikreuzer** [comment]
See https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-configuration-descriptions for all details, what a config-description can provide.

**Comment by aounhaider1** [comment]
I am working on this.

**Comment by maggu2810** [comment]
Hi @aounhaider1, could you comment which stuff is missing, which one has been implemented?

**Comment by aounhaider1** [comment]
Advanced and LimitToOptions features are not implemented yet.

**Comment by itheiss** [comment]
Just looking through the old issues in hope to get the number down.
As #2355 was merged, can we close this issue?

**Comment by kaikreuzer** [comment]
I think most of the suggestions above have indeed been implemented by now, so I am ok to close this issue (and open new specific ones for any further requirements).
