### ISSUE TITLE
[Paper UI] Not possible to link a number-with-dimension channel to a "plain" number item

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#5661]
When trying to link a "Number:Temperature" channel to an item in the Paper UI, no pure "Number" items are shown in the selection list, although those are valid targets for such channels.

**Comment by lolodomo** [comment]
Can you explain what would be the difference between using an item defined as "Number" and an item defined as "Number:Temperature" ?
My understanding was that it was necessary to update the items to add the dimension and this is even something I have mentioned in the release notes for the WU binding.
Does it mean that dimension is something that the final user should not care when defining items ?
Sorry but this is not clear for me now.

**Comment by kaikreuzer** [comment]
It simply means that we wanted to keep backward compatibility - if you have your items defined, you must not be forced to change them, just because one binding decides to now also support units.

**Comment by lolodomo** [comment]
Ok but does it mean that it is exactly the same thing to have dimension or not on the item ?
Are there differences for the user ?

**Comment by kaikreuzer** [comment]
@htreu Is there an easy way to fix this issue?
