### ISSUE TITLE
[core] Validation error in in DSL rules for unit 'km/h'

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#5663]
I run OH2 2.3 stable.

demo.items:
```
val windSpeedThreshold = 39|km/h
```

Warning in log file:
```
2018-06-01 14:45:09.841 [WARN ] [me.internal.engine.RuleContextHelper] - Variable 'windSpeedThreshold' on rule file 'wind.rules' cannot be initialized with value '<QuantityLiteralImpl> / <XFeatureCallImplCustom>': The name 'h' cannot be resolved to an item or type; line 13, column 39, length 1
```

Maybe related to #5621 

The following code snippet works fine - to make it clear, it doesn't log a warning. 
```
if( itemWindSpeed.state >= 39|km/h ) {
    ...
}
```

But it throws an error at the time the rule is executed:
```
2018-06-01 15:21:47.529 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'WindSpeedTest': The name 'h' cannot be resolved to an item or type; line 7, column 45, length 1
```

**Comment by kaikreuzer** [comment]
See https://www.openhab.org/docs/configuration/rules-dsl.html#scripts.

You need to put the unit in quotes, i.e. `39|"km/h"`, then it should work as expected.

**Comment by kaikreuzer** [comment]
FTR, I have created https://github.com/openhab/openhab-docs/pull/692 to fix the formatting on the referenced documentation page.

**Comment by cweitkamp** [comment]
> You need to put the unit in quotes, i.e. 39|"km/h", then it should work as expected.

Confirmed. Thanks. I missed that one completely.

Do you think it is possible to log a warning while parsing the rule file for the second example too?

**Comment by kaikreuzer** [comment]
> Do you think it is possible to log a warning while parsing the rule file for the second example too?

I do not think so. I assume this statement is interpreted as `(39|km) / h` and `h` could be the name of a variable/item/whatever and whether or not `h` exists is only found out during runtime, but not during parsing.
