### ISSUE TITLE
[REST API] MessageBodyWriter not found for media type=text/plain

### ISSUE THREAD

**Issue by openhab-5iver** [eclipse/smarthome#5674]
All the details can be found in this issue in the Habmin repo... https://github.com/cdjackson/HABmin/issues/323#issuecomment-394179178, but this occurs for all devices (not just zwave). Please let me know if more info is needed.

This call...
```
http://localhost:8080/rest/things/kodi:kodi:kodifamilyroom/config/status
```
... returns a 500 status and logs the following...
```
2018-06-03 16:28:58.816 [ERROR] [.jersey.message.internal.WriterInterceptorExecutor] - MessageBodyWriter not found for media type=text/plain, type=class java.util.Collections$UnmodifiableCollection, genericType=class java.util.Collections$UnmodifiableCollection.
```
Possibly a separate issue, but this call...
```
http://fedora01.rushworth.us:8080/rest/config-descriptions/channel:kodi:kodi:kodifamilyroom:control
```
... always returns a 404, but no error is logged.

**Comment by cdjackson** [comment]
The 404 is completely unrelated. It's caused by requesting config descriptions that don't exist. In one view, a 404 is correct - there is no description. Unfortunately the request I believe is correct in that the  channel is valid, so it's valid to make the request to find out if there are descriptions.

We had a similar issue in the past with #1268 which also used to return 404.

**Comment by SiggiFR** [comment]
Hi @cdjackson , I can confirm to see same as Scott for all bindings I use (network, airquality, zwave, systeminfo, ntp). And the error is shown in red in logfile, which is confusing as it seems not really to be an error:
![grafik](https://user-images.githubusercontent.com/36704892/40918336-47d4b332-6806-11e8-9fbe-eb5af1c0fd6a.png)
So it would really be a help if this dummy error (?) will disappear :-)

**Comment by maggu2810** [comment]
I assume there is only the produces annotation missing that declares that the media type is JSON.

```Java
    @Produces(MediaType.APPLICATION_JSON)
```

I will have a look at and if it is working create a PR.

**Comment by maggu2810** [comment]
@openhab-5iver, @cdjackson, @SiggiFR 
Can you have a look at if #5683 fixes your issue?

**Comment by SiggiFR** [comment]
Hi Markus,

 

I’m relatively new using OpenHAB. Can you give me a hint how I can test this change? Have I “only” to install the newest snapshot?

 

Thanks

Siggi

 

Von: Markus Rathgeb <notifications@github.com> 
Gesendet: Dienstag, 5. Juni 2018 11:19
An: eclipse/smarthome <smarthome@noreply.github.com>
Cc: Siegmar Immel <siggi@immels.de>; Mention <mention@noreply.github.com>
Betreff: Re: [eclipse/smarthome] [REST API] MessageBodyWriter not found for media type=text/plain (#5674)

 

@openhab-5iver <https://github.com/openhab-5iver> , @cdjackson <https://github.com/cdjackson> , @SiggiFR <https://github.com/SiggiFR> 
Can you have a look at if #5683 <https://github.com/eclipse/smarthome/pull/5683>  fixes your issue?

**Comment by maggu2810** [comment]
I cannot tell you about the "openHAB way". This would be a question for the openHAB community board.
openHAB itself is using Karaf, so after you have a JAR of the bundle containing the latest changes (e.g. from a build system or you build it yourself) you can use the `bundle:update` Karaf command to update the respective bundle.

**Comment by openhab-5iver** [comment]
Running OH snapshot 1298 w/ ESH 0.10.0.201806080647, the issue is resolved (no more 500s). Thank you!

**Comment by SiggiFR** [comment]
Hi, I was off for longer time. Currently running openHAB 2.4.0 Build #1400 and the issue does no longer appear. Many thanks!
