### ISSUE TITLE
[FEATURE REQUEST] Using other units than default in items inputs

### ISSUE THREAD

**Issue by vzorglub** [eclipse/smarthome#5678]
I have a binding that provides me with a speed in m/s
The item is defined as:

Number:Speed myItem { myBinding )

openHAB assumes that the unit is km/h which leads to erroneous conversions
I work around it with a JS transform but I was looking forward to use the units

Could the Item unit be specified by doing:

Number:Speed:ms myItem { myBinding } #Specific unit for this item
Number:Speed myOtherItem {myOtherBinding } #Default unit eg:kmh

**Comment by kaikreuzer** [comment]
That should imho work if you define `m/s` in your state description of the channel instead of `%unit%`.

**Comment by vzorglub** [comment]
What if it was an mqtt binding and there was no channel?

**Comment by kaikreuzer** [comment]
In that case you should specify the state description on your item:
```
Number:Speed:ms myItem "My Item [%.1f m/s] { myBinding } #Specific unit for this item
```

**Comment by vzorglub** [comment]
I assume that the Number:Speed:ms is a typo.
Kai, that would only convert km/h into m/s. My value input is in m/s. How
to I tell OH that it is not km/h. And then when I do [%. 1f% km/h] it will
get converted in km/h?

**Comment by lolodomo** [comment]
You just to create a QuantityType state in your binding with the value and the unit (m/s).

**Comment by triller-telekom** [comment]
@vzorglub Is your problem solved with @lolodomo's answer?

**Comment by vzorglub** [comment]
No,
Lolodomo answer involves changing the code of the binding. I don't know how
to to that. It's more an esh issue. Where we should be able to tell openHAB
in which unit the value is received. Imagine I am in Europe so I use
Celsius as default but I http in an American weather provider in
Fahrenheit. I should be able to tell OH that the value received is a
temperature in Fahrenheit.
Do you follow?

**Comment by kaikreuzer** [comment]
> . I should be able to tell OH that the value received is a temperature in Fahrenheit. Do you follow?

Not at all. What you can do is to tell openHAB, which unit you would like to have displayed in the UI. What else do you need?

**Comment by kaikreuzer** [comment]
> And then when I do [%.1f km/h] it will get converted in km/h?

Yes.

**Comment by vzorglub** [comment]
I am in the UK so openHAB assume that the default units received are SI.
What if I receive a value in a different unit. How do I tell openHAB what
unit the value is in?

**Comment by kaikreuzer** [comment]
> How do I tell openHAB what unit the value is in?

Again, why do you have to know? If you want a specific unit, just say so in the label and the framework will make sure that you get it.

**Comment by 9037568** [comment]
>Again, why do you have to know? If you want a specific unit, just say so in the label and the framework will make sure that you get it.

How can you convert from m/s to any other reference if you don't know you're starting from m/s ?

**Comment by lolodomo** [comment]
What binding are you using ?
Either your binding is using UoM and of course it has to know the source unit and it will create the item state with the right unit. Then you will be able to display the value in any unit in a sitemapo.
Either your binding is not using UoM and then it sets a Number value for the source unit. In this case, you must not use Number:Speed as item type but just Number and you have toi know which unit is used by your binding. You can probably convert your value to another unit inside a rule.

**Comment by vzorglub** [comment]
Because if I get a value in m/s for example and I define my item as Speed
unit, openhab will assume that is is kph, the default. So when I ask to
display the item as m/s, instead of getting my original value, openHAB will
try to convert what it thinks is kph into m/s.

**Comment by lolodomo** [comment]
Please tell us what binding you are using so that we can check if this binding is supporting UoM. If it does, it should set the value with an unit.

**Comment by vzorglub** [comment]
I am using MQTT and HTTP

**Comment by lolodomo** [comment]
Two bindings that don't implement UoM.
So IMHO you can't use number with dimension for items linked to channels from these bindings. Just do like before UoM was existing.

**Comment by lolodomo** [comment]
@htreu should comment as he knows exactly what was implemented.
Now I see that your issue is tagged as feature request and not issue, so of course it can be studied. I see your request as a general extension of UoM to items and so to bindings not dealing with UoM.

**Comment by vzorglub** [comment]
Thank you
That would enable us to take full advantage of uom across openHAB.

**Comment by htreu** [comment]
Hi guys, thanks for sorting out the little misunderstanding upfront.
@vzorglub when I understand your inquiry right you want to be able to tell which unit a none-uom binding provides on a specific channel so it behaves just like an already-uom-converted binding, right?
Conceptually it would be a configuration of the specific channel to always provide a QuantityType with a specific unit.
Maybe we can solve this issue by providing a special profile with unit parameter, which converts a DecimalType into a QuantityType and vice versa on the way back (when receiving QuantityType commands on an item for this channel).
wdyt? 

/cc @sjka & @triller-telekom.

**Comment by triller-telekom** [comment]
> Another option would be to implement this binding specific and let the user define the channel dimension and unit parameterised. This would again need framework support.

Shouldn't the binding rather be updated to properly support UOM, so such a "hack" is not necessary?

To sum this issue up: The feature request is that bindings should support UOM, right? Maybe we should adjust the topic of it to reflect this.

**Comment by htreu** [comment]
> Shouldn't the binding rather be updated to properly support UOM

Yes, thats what I actually wanted to say :-)

But for bindings like HTTP or MQTT the UoM support is not that obvious. So for these generic bindings there might be a config option to provide the UoM related information on the channel. Again, this would need further framework support to make a channel configured this way look like any channel with a channel-type. Not sure if we want to go this route...

**Comment by sjka** [comment]
As both, HTTP and MQTT binding you are referring to are openHAB1-bindings I think this is something beyond the scope of this project.

**Comment by htreu** [comment]
Back to the original issue:

> Kai, that would only convert km/h into m/s. My value input is in m/s. Howto I tell OH that it is not km/h. 

The item definition `Number:Speed myItem "My Item [%.1f m/s]" { myBinding }` like @kaikreuzer suggested would create a QuantityType with unit `m/s` and the scalar taken from the binding's DecimalType (w/o conversion). So actually you can define the input unit in the state description.

> And then when I do [%. 1f% km/h] it will get converted in km/h?

With the above notation the item's state would always be in the unit `m/s`. In case you want to display the value in `km/h` in the UI you could simply put `[%.1f km/h]` in the sitemap label for the corresponding widget. Paper UI would still show the value as `m/s` as it does not take sitemap state descriptions into account.

**Comment by lolodomo** [comment]
Good to know. That is probably something to explain in the documentation as not really obvious.

**Comment by vzorglub** [comment]
Yes indeed and a bit strange to do this in the label parameter.
Now if want to display another unit in habpanel I have to create another
item...
And mess up with the sitemaps

**Comment by vzorglub** [comment]
I have verified that it works as suggested. It's messy though.

**Comment by kaikreuzer** [comment]
I'd claim that it is absolutely straight forward and exactly as it always was - in the item file, you define a default label + value formatting, if nothing else is specified. For UIs, you can specify custom formats - what is probably mainly missing is to also allow a selection of the formatting within HABPanel.

**Comment by lolodomo** [comment]
All this is finally very powerful, even more than I have imagined. It is in fact possible to apply UoM to any number channel.
