### ISSUE TITLE
ScriptExecution throws "The TypeResolutionStateAdapter was removed while resolving"

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#569]
migrated from Bugzilla [#469189](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469189)
status UNCONFIRMED severity *normal* in component *Core* for *---*
Reported in version *0.8.0* on platform *PC*
Assigned to: Project Inbox

On 2015-06-02 14:29:47 -0400, karel goderis wrote:

> I get a lot of these 
> 
> 2015-06-02 20:26:38 [ERROR] [.e.s.c.s.ScriptExecutionThread:48   ] - Error during the execution of rule 'MultimediaPowerRule': The TypeResolutionStateAdapter was removed while resolving
> 
> 
> in my logs. It seems to be related to XText but I am a novice to the Xtext code to say what exactly is going on here
> 
> K

On 2015-06-02 14:31:54 -0400, karel goderis wrote:

> For completion, the code of the Rule is 
> 
> rule MultimediaPowerRule
> when
> 	Item KitchenTVCurrent received update or
> 	Item SamsungKitchenPing received update
> then
> 	if(KitchenTVCurrent.state > 100 || SamsungKitchenPing.state == ON) {
> 		KitchenMultimediaSwitch.postUpdate(ON)
> 	} else {
> 		KitchenMultimediaSwitch.postUpdate(OFF)
> 	}
> end

On 2015-06-13 14:41:17 -0400, Oliver Libutzki wrote:

> Hi Karel,
> 
> is it possible for you to provide the whole stacktrace? Often this exception is caused by another exception.
> 
> Thanks.

**Comment by kaikreuzer** [comment]
@kgoderis I would assume we can close this or is this still applicable?

**Comment by kgoderis** [comment]
Yes - it almost a year old - don't even remember the complete issue.
