### ISSUE TITLE
Basic UI: Colorpicker doesn't display value in label

### ISSUE THREAD

**Issue by mueller-ma** [eclipse/smarthome#5712]
Item:
````
Color RGBLight "RGB Light"
````

Sitemap:
````
Colorpicker item=RGBLight label="Color[%s]"
Slider item=RGBLight label="Color[%s]"
````

The brightness is displayed on the Slider element, but not on the color picker:
![colorpicker2](https://user-images.githubusercontent.com/22525368/41193612-b59fe97a-6c0e-11e8-8f03-c6efa8cd1ce8.JPG)

The data is available via rest api:
![colorpicker](https://user-images.githubusercontent.com/22525368/41193611-b56997ee-6c0e-11e8-9aa0-83291423c669.JPG)

**Comment by kaikreuzer** [comment]
The value of the light is a HSB value, not a percent value - so ideally, I would expect the color of it to be shown - and as there is usually VERY little space on phones left next to the buttons, I'd always rather wished the icon to reflect the color - that should normally suffice, don't you think?

**Comment by mueller-ma** [comment]
> I would expect the color of it to be shown

I was thinking about this as well, but most people won't know the color when they see an HSB value.

> I'd always rather wished the icon to reflect the color - that should normally suffice, don't you think?

Yes, that would be a lot better.

Anyway the user doesn't have to set the value there, so I would recommend to show it in the basic ui or remove it from the rest api.

**Comment by kaikreuzer** [comment]
> but most people won't know the color when they see an HSB value.

Fully agree - that's why I said the "color" not the "color value" 😆. E.g. the palette button could color the palette accordingly.

> remove it from the rest api.

Why? The REST API can be used for all other kind of clients, so just because some information is available there, it does not mean that it is applicable/useful for all clients.

What I am wondering though is that the REST API returns "44" as a stringified value - normally, I would expect "30,50,100" or something like this as the value there...

**Comment by lolodomo** [comment]
The state as an HSB value is present in the item sub-object in the response but the label and the state of the slider widget at the top level og the response are set with a percent value from the color item state, its brightness.

**Comment by lolodomo** [comment]
Displaying the HSB value in case of a colorpicler widget would be possible.

**Comment by maniac103** [comment]
> E.g. the palette button could color the palette accordingly.

I actually thought about doing this in the Android app, but what made me stop is the question 'What if the selected color (almost) matches the background color?' as I couldn't think of a good solution to that.

**Comment by wborn** [comment]
> What if the selected color (almost) matches the background color?

Most UIs seem to solve this by always adding a thin border around the color.

**Comment by mueller-ma** [comment]
I don't think it's a good idea since the state is always represented by the icon and never by a button.

**Comment by kaikreuzer** [comment]
I agree, having it on the icon would be the nicest and imho fully sufficient solution. But hence I would simply suggest to reject this issue here :-)

**Comment by sjka** [comment]
okay 😁

**Comment by mueller-ma** [comment]
Shouldn't the rest api changed to return the full HSB value and not just the brightness?

**Comment by lolodomo** [comment]
I just checked and as expected the HSB value is present in the item state. But that is true that for a Colorpicker widget the value in the label field of the API is not HSB but B only.
Having the brightness as value in the label makes sense when the widget type is a slider. When the widget type is a colorpicker, it would make sense to have the HSB value.
So I think @mueller-ma request makes sense.
But if this is changed, you can probably no more have the icon based on the brightness for such widget (example in the demo sitemap).
