### ISSUE TITLE
Basic UI: Roboto-Medium.svg and Roboto-Regular.svg

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5713]
After running Maven, two files in Basic UI are marke"d as modified!
* web/fonts/Roboto-Medium.svg
* web/fonts/Roboto-Regular.svg

Should they be added to ignored files ?

**Comment by sjka** [comment]
As they are copied there by the gulpfile I'd say: yes

**Comment by lolodomo** [comment]
Ok I will update the .gitignore file.
