### ISSUE TITLE
Basic UI: switch widget with buttons - button not correctly selected

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5718]
For a switch widget rendered with buttons (mappings), the selected button is not correctly updated when an item state is received. This is due to the fact that the JavaScript code is suing the value extracted from the label rather than the item state to search the right button to select.

This can be reproduced with the demo sitemap by replacing:
`Number Scene_General            "Scene"                             <sofa>`
with
`Number Scene_General            "Scene [MAP(scene.map):%s]"                             <sofa>`
with scene.map containing for example:
```
1=Scene 1
2=Scene 2
3=Scene 3
```

**Comment by sjka** [comment]
Fixed by #5719
