### ISSUE TITLE
Error state is sent when deleting a thing

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#572]
migrated from Bugzilla [#473674](https://bugs.eclipse.org/bugs/show_bug.cgi?id=473674)
status UNCONFIRMED severity _normal_ in component _Core_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Project Inbox

On 2015-07-27 12:18:30 -0400, Chris Jackson wrote:

> When deleting a thing, the UNITIALIZED state with HANDLER_MISSING_ERROR is sent. It seems that this probably should be suppressed.
> 
> {"topic":"smarthome/things/zwave:fibarosystem_fgs221_00_000:14e7e5d0c84:node8/status","payload":"{\"status\":\"REMOVING\",\"statusDetail\":\"NONE\"}","type":"ThingStatusInfoEvent"}
> 
> {"topic":"smarthome/things/zwave:fibarosystem_fgs221_00_000:14e7e5d0c84:node8/status","payload":"{\"status\":\"REMOVED\",\"statusDetail\":\"NONE\"}","type":"ThingStatusInfoEvent"}
> 
> {"topic":"smarthome/things/zwave:fibarosystem_fgs221_00_000:14e7e5d0c84:node8/status","payload":"{\"status\":\"UNINITIALIZED\",\"statusDetail\":\"HANDLER_MISSING_ERROR\"}","type":"ThingStatusInfoEvent"}

**Comment by itheiss** [comment]
@cdjackson  Just looking through the old issues in hope to get the number down. Is this still an open issue or can we close the issue?

**Comment by kaikreuzer** [comment]
At least I cannot reproduce this, so I assume it is fixed.
