### ISSUE TITLE
Problem with Sonos firmware 8.6

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#5752]
I discovered that TTS is no more working well, meaning not always. I am running the snapshot 1302.
I think it was working well with the snapshot 1297.
I am using the Sonos binding and VoiceRSS as TTS provider.
I have no error logged but the TTS rendering is only a silence.
I will probably go back to the snapshot 1297 due to this problem.

**Comment by lolodomo** [comment]
At the same time, I installed a new Sonos firmware (8.6). Could be related to that too.

**Comment by kaikreuzer** [comment]
I still had it working last week and I am not aware of any code changes.
So might be related to firmware update. I don't have a speaker with me right now for testing.

**Comment by kaikreuzer** [comment]
Could you try whether sending a notification sound still works? Just to identify whether it is related to TTS or purely to sending audio streams to Sonos.

**Comment by lolodomo** [comment]
Will do.

I think I moved to the firmxare 8.6 last weekend.

**Comment by lolodomo** [comment]
Yesterday morning I rebooted my Sonos and it was working again. This morning, nothing. So I suspect more OH than Sonos.

**Comment by thomasgregersen** [comment]
I'm seeing the same issue with both notifications sounds and TTL. 
I'm not sure if this happened after updating my Sonos to 8.6 yesterday or if it had to do with upgrading to latest OH2 release. I've just reinstalled the last stable release  (2.3.0-1) but still with no luck.
How do I see the snapshot number? from Bundle:list I can see the version 0.10.0.oh230.

**Comment by kaikreuzer** [comment]
@thomasgregersen That's the 2.3 release that you are using, no snapshot.

**Comment by thomasgregersen** [comment]
@kaikreuzer So the snapshot I guess would be shown instead of the .oh230 in the version?

**Comment by lolodomo** [comment]
There might be even more problems, my rule that groups my Sonos devices seems to not work anymore !
All this requires a deep investigation.

**Comment by lolodomo** [comment]
After OH restart, I have now only problems with TTS, and that is not 100% failing, it is just unreliable.
What seems to happen is that the Sonos takes too much time to start the playback of the audiop file and the OH server is proxying the audio file only during 10 seconds if I correctly remind. I think it is probably the reason why the file is not rendered.
Now I have no idea why this takes sometimes so much time to start the playback.

**Comment by lolodomo** [comment]
https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.sonos/src/main/java/org/eclipse/smarthome/binding/sonos/internal/handler/ZonePlayerHandler.java#L2362
It looks like coordinator.waitForNotTransportState(STATE_PLAYING) sometimes returns only after the default timeout of 20s. This is the reason why TTS is sometimes not working.

**Comment by lolodomo** [comment]
What's happening seems to be even worst than I imagined. At a certain time, the binding is no more receiving any update from the Sonos devices !

**Comment by lolodomo** [comment]
Apparently the subscriptions are automatically restored several minutes later by our 1 minute refresh job.
isUpnpDeviceRegistered() returns false after few minutes leading to new subscription requests.

That looks like an UPnP problem ! Maybe a new compatibility issue between Sonos and our JUPnP library.

**Comment by lolodomo** [comment]
@kaikreuzer : in which snapshot number did you introduce the last JUPnP library version ?

It would be interesting to have a feedback from someone who has not yet updated to Sonos firmware 8.6.

In fact, I am not sure what triggers the new subscriptions but onServiceSubscribed is called with true after several minutes for all subscriptions.
The problem is totally independent on TTS. The loose of GENA events occurs quickly even if the user is doing nothing.

Major problem as receiving of GENA events is now random.

**Comment by lolodomo** [comment]
When OH stops handling GENA events, I can still see GENA events arriving in UPnP Spy.
So apparently the problem is not the Sonos devices stopping notifying the clients but is ESH and/or JUPnP stopping handling them.

**Comment by J-N-K** [comment]
Could it be a timing issue? Sonos uses a TTL of 1, probably the packets are dropped before processing?

**Comment by kaikreuzer** [comment]
> @kaikreuzer : in which snapshot number did you introduce the last JUPnP library version ?

On openHAB side, there hasn't been any change in JUPnP this year, so this cannot be related.
Maybe things would behave better on a recent JUPnP snapshot, though; I cannot tell.

**Comment by lolodomo** [comment]
Ok I will continue my investigation and I will try with my fixed version of JUPnP.

**Comment by lolodomo** [comment]
@kaikreuzer : I see in November 2017 the merge of using the new JUPnP v2.3.
So we can conclude that the current problem was introduced with the new Sonos firmware and not with recent changes in ESH/OH.

**Comment by lolodomo** [comment]
It looks like using my fixed version of the JUPnP library, there is no problem. I was just able to test that inside Eclipse.
Unfortunately, I was not able to replace the JUPnP library in my production environment. When I stop the JUPnP v2.3 bundle and start the JUPnP v2.4 bundle, the UPnP transport bundle and the Sonos binding remain in a WAITING state. This is probably possible but I will be patient and I will wait for the JUPnP library to be packaged with ESH.

@kaikreuzer : can you please merge the PR https://github.com/jupnp/jupnp/pull/98 (PR was already reviewed and approved) and pushed the new version of the library in ESH ?

**Comment by lolodomo** [comment]
The Sonos binding is more or less unusable now. So if you can do it in a reasonable time, that would be cool.

**Comment by lolodomo** [comment]
Just to be clear, I am not saying that my PR for JUPnP is fixing the current problem. I am just saying that the master code + my fix for JUPnP seems to solve the problem. So that might be another merged PR that fixed the current problem.

**Comment by lolodomo** [comment]
The JUPnP library I used for my tests included the following PRs https://github.com/jupnp/jupnp/pull/94 + https://github.com/jupnp/jupnp/pull/95 + https://github.com/jupnp/jupnp/pull/98. I am not sure which PR fixed the current problem.
But since the time the version 2.3 of the library was released, there were not a lot of PRs merged.

**Comment by lolodomo** [comment]
I finally succeeded in updating my production envirinment by replacing the jar file ./runtime/system/org/jupnp/org.jupnp/2.3.0/org.jupnp-2.3.0.jar by the updated one.
Unfortunately, I can still reproduce the problem !!!

**Comment by lolodomo** [comment]
I can see in the logs that new subscriptions are established every 15 minutes without any request by the binding. It looks like a subscription renewal. Maybe this is not something new.

**Comment by lolodomo** [comment]
I just discovered that my way to replace the jupnp jar file in my production environment does not work ! The jar is probably taken elsewhere and so I am still running the jupnp library initially packaged with the snapshot.

**Comment by lolodomo** [comment]
I summarize:
* with the updated JUPnP library, it works apparently without any problem in Eclipse on my PC
* unfortunately I don"t know how to replace the JUPnP library in my production environment and so I am not able to validate that it would workj in this environment.

So I cannot be 100% sure that my fixed version of the JUPnP library IS the solution to the current problem but I am confident that it could be.

**Comment by kaikreuzer** [comment]
Ok, thanks for your analysis and testing. Sounds like a good reason for looking into doing a JUPnP release asap; will try to find some time to do so this week!

**Comment by kaikreuzer** [comment]
@lolodomo Latest openHAB distro 1305 contains the new JUPnP - please test and report back!

**Comment by lolodomo** [comment]
Excellent. I will deploy this version this night and report.

**Comment by lolodomo** [comment]
@kaikreuzer : big thank you for adding so quickly the new JUPnP library.
After my first tests with the snapshot 1305, everything looks good again.

We will never know what exactly was wrong in the JUPnP library. But the important point is that the issue is fixed.

I let the issue still open until Saturday to check that my rules including TTS messages are all working as expected and are reliable.

**Comment by kaikreuzer** [comment]
Thanks for the quick feedback, I am glad to hear that things seem to be working. Let's hope that it stays that way 👍 .

**Comment by lolodomo** [comment]
Still no problem this morning.
I close the issue as I am fully confident that the problem is solved.
