### ISSUE TITLE
RestResource implementation

### ISSUE THREAD

**Issue by pvpeev** [eclipse/smarthome#5757]
Hi,
I took a look at the classes which implement `RESTResource` and I found out that they are registered as `@Component` and they override the `RESTResource#isSatisfied()` to check if the services which they need are available. I am thinking if we need to do that, since we can say: `cardinality = ReferenceCardinality.MANDATORY` and in this way the component won't be registered until all services are available.

**Comment by kaikreuzer** [comment]
Please see https://github.com/eclipse/smarthome/pull/2320 to understand why it is done that way.
