### ISSUE TITLE
[Astro] Missing end of dusk and start of dawn

### ISSUE THREAD

**Issue by NorbertHD** [eclipse/smarthome#5774]
Depending on the time of the year and the latitude there are places on earth where there is no night or no astronomical, nautical or civial twilights. Now (24.6.) in middle germany there is no night and the astro binding shows no end of astronomical dusk and no start of astronomical dawn. Also the duration is empty (-1). I propose if the next deeper sun state is missing, that the end of dusk and the start of dawn should be set to solar midnight, in astro binding.

**Comment by kaikreuzer** [comment]
@gerrieg As our astro expert, could you comment?

**Comment by gerrieg** [comment]
When i set it to the next deeper state, it would be wrong. You said it yourself, there is **no** night or **no** astronomical, nautical or civial twilights. So there is also **no** value. Even sites like http://www.suncalc.net don't show a values.

**Comment by kaikreuzer** [comment]
Sounds plausible, so I'd suggest to close this issue.
