### ISSUE TITLE
[Homematic] HmIP Door Window Contact paired as String, not as Contact - corrected for HMIP-SWDO but not HMIP-SWDO-I

### ISSUE THREAD

**Issue by mdicke2s** [eclipse/smarthome#5786]
_From @mrehker on October 30, 2017 23:1_

This issue is related to #1564 where a virtual datapoint of type contact was added für HMIP-SWDO. Unfortunately, the StateContactVirtualDatapointHandler.java only recognises HMIP-SWDO and not the (newer) HMIP-SWDO-I, which currently only provides the status as a string. This again does not allow the contact to be used in openhab2, because updates are not recognised in the rules.

I would propose to modify 

private boolean isApplicable(HmDevice device) {
        return "HMIP-SWDO".equals(device.getType());
}

to 

private boolean isApplicable(HmDevice device) {
        return "HMIP-SWDO".equals(device.getType()) or "HMIP-SWDO-I".equals(device.getType()); 
}
so that it also returns true for HMIP-SWDO-I

_Copied from original issue: openhab/openhab2-addons#2817_

**Comment by mdicke2s** [comment]
_From @gerrieg on June 11, 2018 14:5_

I've overlooked this issue, sorry. This will be implemented in one of the next 2.4 snapshots.

**Comment by orificer** [comment]
Hi, 

I'm using  openHAB 2.4.0~20181118113913-1 (Build #1431) and want to implement some HmIP-SWDO-I, but the virtual datapoint STATE_CONTACT is not available.

Do I have to enable anything to be able to use the virtual datapoint?

**Comment by gerrieg** [comment]
Thank you for reminding me, implemented (see pull request)
