### ISSUE TITLE
Tags missing on new Item in 'updated' event on ItemRegistryChangeListener

### ISSUE THREAD

**Issue by pdegeus** [eclipse/smarthome#5803]
When receiving an update event in an ItemRegistryChangeListener, the tags seem to be missing from the second parameter, the new version of the item.

I'm testing with the APT package, 2.4.0-SNAPSHOT, build #1302 on Ubuntu. The issue exists for a while now, first reported by a user of an add-on I wrote, here: https://community.openhab.org/t/imperihome-binding-2-0.

You'll find an add-on to show the issue using logging here:
https://github.com/pdegeus/openhab2-addons/tree/master/addons/io/org.openhab.io.tagtest
I'm sorry not to provide a unit test or similar.

I'm using .items files. Item example:
`Number FanMode "Ventilatie"     ["iss:room:Attic", "iss:type:DevMultiSwitch", "iss:mapping:0=0, 1=I, 2=II, 3=III"]
`

Logging on a 'touch' of the items file:
```
2018-06-25 22:15:17.298 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'attic.items'
2018-06-25 22:15:17.306 [INFO ] [.openhab.io.tagtest.internal.TagTest] - Item updated: 'FanMode', old tags: [iss:room:Attic, iss:type:DevMultiSwitch, iss:mapping:0=0, 1=I, 2=II, 3=III], new tags: []
```

May be related to #5670, #5654, #5649

**Comment by Alpoy** [comment]
Hope someone can fix this soon, this completely breaks the imperihome binding and my whole alarm system functionality ;-)

**Comment by htreu** [comment]
I can confirm this is a bug. With #5431 the tags are now processed with other item bindings (like channel-binding, etc.) which is done in the GenericItemProvider _after_ the registry is informed about the update.

**Comment by kaikreuzer** [comment]
Btw, @pdegeus, now that we have https://github.com/eclipse/smarthome/pull/4390 in place, it might be worthwhile to refactor the Imperihome add-on to use the metadata infrastructure instead of custom tags (which is not advised anymore). This would also be a workaround for this bug for you as the registry change listeners should flawlessly work on the `MetaDataRegistry` 😎 .

**Comment by pdegeus** [comment]
@kaikreuzer Cool, didn't know that was being worked on. I'll refactor the add-on when I've got some spare time. Probably when the nice weather ends ;) 
In the meantime it would be great if somebody could fix this bug.
