### ISSUE TITLE
SSE subscriptions are not released when refreshing sitemap subpage

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#5804]
See my comments here relating to hitting the max SSE subscription limit.
https://github.com/eclipse/smarthome/pull/5648#issuecomment-400063555

Summary:
I started to see the message **SSE subscription failed: running in fallback mode** in Basic UI.

I turned on debug logging for org.eclipse.smarthome.io.rest.sitemap. Then I increased maxSubscriptions using the config parameter.

My initial observation is that when I refresh a subpage of the sitemap, a new subscription is created. However, I'm not seeing those subscriptions ever get removed.

In contrast, if I refresh the main sitemap page, a new subscription is created, and that subscription is removed sometime later.

**Comment by lolodomo** [comment]
I link to the issue #4809 .

**Comment by mhilbush** [comment]
Ah, sorry, I didn't realize there already was an open issue for this. I should close this one and add to that issue.

**Comment by lolodomo** [comment]
Your issue is very important as it shows for the first time a concrete case leading to an increase of subscriptions.
