### ISSUE TITLE
`Automatic-Module-Name` warning

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#5822]
The Eclipse IDE shows a log of warnings
```
'Automatic-Module-Name' header is required to be discoverable as a Java module in a Java modular setup (Java 9 and later)
```

Should we add an `Automatic-Module-Name` to the manifest using the `Bundle-SymbolicName` value (without the attributes like singleton, ...)?

**Comment by kaikreuzer** [comment]
I'd be all for it. Would be the right move towards support of more recent Java versions.
