### ISSUE TITLE
[test failures] ItemRegistryOSGiTest.testItemAddedEvent test sometimes fails

### ISSUE THREAD

**Issue by DaHoC** [eclipse/smarthome#5844]
We sometimes observe the ItemRegistryOSGiTest.testItemAddedEvent test inside org.eclipse.smarthome.core.test to fail with the following assertion:
```
Results :
16:39:52 
16:39:52 Failed tests: 
16:39:52   ItemRegistryOSGiTest.testItemAddedEvent:283->JavaTest.waitForAssert:69->JavaTest.waitForAssert:116->JavaTest.waitForAssert:154->lambda$2:283 
16:39:52 eventSubscriber.receive(
16:39:52     isA(org.eclipse.smarthome.core.items.events.ItemAddedEvent)
16:39:52 );
16:39:52 Wanted 1 time:
16:39:52 -> at org.eclipse.smarthome.core.items.ItemRegistryOSGiTest.lambda$2(ItemRegistryOSGiTest.java:283)
16:39:52 But was 5 times. Undesired invocation:
16:39:52 -> at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
```
One possibility for this happening might be that depending on the order of the test executions, there sometimes are tests executed beforehand which also add an item and don't clean up these events properly.

**Comment by maggu2810** [comment]
Since yesterday I run into that problem myself, too.

**Comment by DaHoC** [comment]
Thank you @htreu , looks good in our builds at the moment, closing issue

**Comment by htreu** [comment]
@DaHoC just reopen here if problems persist. We had the effect that this test failed once or twice a week.

**Comment by DaHoC** [comment]
And there this test is failing again for us...

**Comment by DaHoC** [comment]
According to my initial assumption, I compared the test execution order for the successful and failing builds: no differences here, so the test failing is not caused by a different test execution order.

**Comment by maggu2810** [comment]
I tried it three time now, but I cannot reproduce the error anymore (at least not at the moment).

```
mvn clean install \
    -Dmaven.repo.local="${HOME}"/.m2/repository_esh_snapshot \
    -DskipChecks=true \
    -o \
    -pl ./bundles/core/org.eclipse.smarthome.core.test
```

**Comment by FStolte** [comment]
I am not sure if this is worth a new issue, but I just had the same problem as described here, just for a different test (remove event instead of added event):
```
org.eclipse.smarthome.core.items.ItemRegistryOSGiTest.testItemRemovedEvent

eventSubscriber.receive(
    <Capturing argument>
);
Wanted 1 time:
-> at org.eclipse.smarthome.core.items.ItemRegistryOSGiTest.lambda$4(ItemRegistryOSGiTest.java:283)
But was 6 times. Undesired invocation:
-> at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
```

**Comment by htreu** [comment]
Thanks @FStolte I always wondered if only the added event test was affected. Maybe we can refactor the ItemRegistryOSGiTest into a plain Java Test w/o the OSGi framework buffering events...

**Comment by htreu** [comment]
another example from the master branch travis build:

```
Failed tests: 
  ItemRegistryOSGiTest.testItemRemovedEvent:281->JavaTest.waitForAssert:73->JavaTest.waitForAssert:120->JavaTest.waitForAssert:152->lambda$4:281 
eventSubscriber.receive(
    <Capturing argument>
);
Wanted 1 time:
-> at org.eclipse.smarthome.core.items.ItemRegistryOSGiTest.lambda$4(ItemRegistryOSGiTest.java:281)
But was 4 times. Undesired invocation:
-> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by GiovannaTheo** [comment]
Idk the statue of this issue, but Travis build 8773 failed again with the same issue. Also Travis build 8772 failed the same way but this time with the `RemovedEvent` test.

```
Failed tests: 
  ItemRegistryOSGiTest.testItemAddedEvent:266->JavaTest.waitForAssert:73->JavaTest.waitForAssert:120->JavaTest.waitForAssert:152->lambda$2:266 
eventSubscriber.receive(
    isA(org.eclipse.smarthome.core.items.events.ItemAddedEvent)
);
Wanted 1 time:
-> at org.eclipse.smarthome.core.items.ItemRegistryOSGiTest.lambda$2(ItemRegistryOSGiTest.java:266)
But was 6 times. Undesired invocation:
-> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
