### ISSUE TITLE
ScriptExtensionManager.get("voice") return NULL instead of VoiceManagerImpl

### ISSUE THREAD

**Issue by philippwaller** [eclipse/smarthome#5847]
Hi Folks,
I currently develop some libraries to write ESH and OpenHAB automation rules in groovy. In this process, I noticed an bug in the [ScriptExtensionWrapper](https://github.com/eclipse/smarthome/blob/4204ce06bb28c28e5f711e720f87ef83beff2e27/bundles/automation/org.eclipse.smarthome.automation.module.script/src/main/java/org/eclipse/smarthome/automation/module/script/internal/ScriptExtensionManagerWrapper.java) class. According to the getTypes() method, the following objects should be loadable via the ScriptExtensionManagerWrapper.get() method: 

- voice 
- audio
- DOWN 
- CLOSED 
- FileUtils 
- StringType 
- DECREASE 
- rules 
- OFF 
- StopMoveType 
- StringUtils 
- INCREASE 
- OpenClosedType 
- things 
- UP 
- URLEncoder 
- HSBType 
- events 
- ON 
- itemRegistry 
- STOP 
- ir 
- UpDownType 
- PercentType 
- FilenameUtils 
- OPEN 
- DateTimeType 
- Command 
- OnOffType
- MOVE 
- State 
- DecimalType 
- PointType 
- IncreaseDecreaseType 
- File 
- items
- Condition 
- TriggerType 
- Action 
- ActionType 
- Configuration 
- ActionHandlerFactory 
- ruleRegistry 
- SimpleActionHandler 
- automationManager 
- SimpleRule 
- ModuleType 
- Trigger 
- SimpleConditionHandler 
- ConditionHandlerFactory 
- Visibility 
- Rule 
- ConfigDescriptionParameter 
- SimpleTriggerHandler 
- TriggerHandlerFactory 

However, when I try to load the first two objects (voice or audio), NULL get returned instead the VoiceManagerImpl or AudioManagerImpl Class. For all other objects, the correct instance is given back. I am using openHAB 2.4.0 Build 1305.

Cheers,
Philipp

**Comment by sjka** [comment]
whoops, there is a nice typo that went unnoticed so far...
I quickly pushed a fix - too easy once identified. Thanks for the concise analysis!
Once merged, it will reach openHAB snapshots after the next [ESH stable](https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/changes) is built - as usual.
