### ISSUE TITLE
Simplify Thing configuration caching in classes extending BaseThingHandler

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#5886]
A lot of classes extending the BaseThingHandler cache the Thing configuration in `initialize()` in a property with a statement like:

```java
config = getConfigAs(SomeConfiguration.class);
```

For performance reasons it's a good idea to cache the configuration because `getConfigAs(..)` uses reflection which is an expensive operation.

The issue with this approach is that the `config` property should be annotated with `@Nullable` because it is only assigned a non-null value in `initialize()`. 

**Now to fix all potential NPEs:**
Wherever the `config` is used, first a local variable must be assigned before it can be checked for null. That's because the `config` property could be set to `null` at any moment in time by another thread. Then  when the local copy of `config` is null this must be handled, e.g. by throwing an exception or setting the ThingStatus.

Since `getConfigAs(..)` is guaranteed to be non-null it would be nice if we could use it anywhere without having to deal with the reflection overhead. Perhaps it's a good idea to cache the result of `getConfigAs(..)` in the BaseThingHandler so the value is reused after the first call?

Are there also other ways to simplify working with cached configurations? :-)

**Comment by htreu** [comment]
From what I see `initialize()` is called exactly when the configuration of the handler changed. The old handler is disposed and a new one created. You definitely want to get the new config with `getConfigAs`. And as long as the handler is alive the current config is (most of the time) hold in an instance field.
I don't see much room for improvement here. wdyt?

**Comment by wborn** [comment]
Take for instance the SamsungTvHandler which has a [configuration]( https://github.com/openhab/openhab2-addons/blob/a94888d8eb9420847925b4d5ee194616595d60f6/addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/handler/SamsungTvHandler.java#L62) property. 

If you would add `@NonNullByDefault` on the class the `configuration` property would need to get a `@Nullable` property. To fix all potential NPEs in the 4 methods where the property is used you would need to assign it to a local variable, do the null check and then add logic to handle the null case. That could all be extracted to some method that throws a non-checked exception but it all adds unnecessary complexity.

Another approach could be to simply remove the `configuration` property and use `getConfigAs` in each method. That saves a lot of warnings, code and potential NPEs. The only issue with that is that now everywhere reflection is used. Some handlers use the config everywhere for adding IDs to logging.

That reflection penalty could be solved by caching the result of `getConfigAs` in the BaseThingHandler.

**Comment by maggu2810** [comment]
Why not using this one in your classes:

```
private @Nullable MyConfig config = null;

...

public void initialize() {
    ...
    this.config = getConfigAs(SomeConfiguration.class);
    ...
}

public @NonNull MyConfig config() {
    final MyConfig config = this.config;
    if (config == null) {
        throw new IllegalStateException("life cycle violation");
    }
    return config;
}
```

I added `@NonNull` only to make it more readable -- should dropped in favor of `@NonNullByDefault`.

I am using some nullness utils myself e.g.

```
    /**
     * Check if an argument is non-null and throw an illegal state exception if null.
     *
     * @param <T> the object type
     * @param obj the object to check
     * @return the object if current value is non-null
     * @throws IllegalStateException if given argument is null
     */
    public static @EnsuresNonNull("#1") <T extends @Nullable Object> @NonNull T ifNullThrowIllegalState(final T obj)
            throws IllegalStateException {
        if (obj != null) {
            return obj;
        } else {
            throw new IllegalStateException("A null type is not expected here.");
        }
    }
```

but that are not available on plain ESH at the moment.

**Comment by htreu** [comment]
I also recommend to not optimise the reflection part with a cache. The `getConfig` and `getConfigAs` methods both operate on the `thing.configuration` property. Adding a cache in front of one of the methods in an abstract base will decouple from the thing instance. It also adds complexity in a place where its not expected.
Imho the nullness handling is also a not strong enough argument for such a move.

@sjka & @triller-telekom opinions?

**Comment by maggu2810** [comment]
And as we have updated to Java 8 for a while you can also use the functions provided by `Optional`

```java
Optional.ofNullable(myConfig).get();
Optional.ofNullable(myConfig).orElse(fallbackConfig);
Optional.ofNullable(myConfig).orElseGet(this::getNonNullConfig);
Optional.ofNullable(myConfig).orElseThrow(() -> new IllegalArgumentException("lifecycle violation"));
```

If you use the `Optional` for your local member it should be a little bit simpler to write:

```
private Optional<MyConfig> config = Optional.empty();

...

public void initialize() {
    ...
    this.config = Optional.of(getConfigAs(SomeConfiguration.class));
    ...
}


public void someMethodThatAccessTheConfig() {
    final int magic = config.get().magic;
}
```

**Comment by triller-telekom** [comment]
As long as this suggestion is only used within extensions, such as bindings, I am OK with it. But we agreed to not use `Optional` within the framework itself.

**Comment by maggu2810** [comment]
> As long as this suggestion is only used within extensions, such as bindings, I am OK with it. 

Sure, my suggestion has been for the bindings.

> But we agreed to not use `Optional` within the framework itself.

Can you point me to the discussion at which place "we" agreed?

**Comment by triller-telekom** [comment]
It was in this discussion https://github.com/eclipse/smarthome/issues/3624#issuecomment-311333536 where we said its not an option for our API. So, I am assuming the decision also is also valid for other places (correct me if I am wrong with that).

**Comment by maggu2810** [comment]
That is another topic, it has been about the nullness annotations.

> I think we all agree that Optionals are no option for the existing ESH APIs

IMHO it has been stated that for we don't like to change the existing ESH APIs to use `Optional` but I don't think this has been an agreement that we don't like to use `Optional` in the whole ESH code base.

But I don't see any changes the framework needs to implement here.
This could be done easily by the specific bindings.

**Comment by wborn** [comment]
```java
public @NonNull MyConfig config() {
    final MyConfig config = this.config;
    if (config == null) {
        throw new IllegalStateException("life cycle violation");
    }
    return config;
}
```

Yes it this is a nice workaround @maggu2810 but if each handler has to add such a construct it adds a lot of boiler plate code. Also I'm not too fond of throwing these unchecked exceptions. If people start using such constructs as workaround for each `@Nullable` property, you're replacing NullPointerExceptions with IllegalStateExceptions. The result of using null annotations would then be adding a lot of boiler plate code and getting ISEs instead of NPEs. ;-)

> Adding a cache in front of one of the methods in an abstract base will decouple from the thing instance. It also adds complexity in a place where its not expected.

The handlers with their own configuration properties are effectively reinventing their own (sometimes flawed) configuration caching mechanism. I'd rather have the framework solve this issue once and for all in a good reusable way.

**Comment by maggu2810** [comment]
@wborn If you access the configuration if your handler is not initialized or disposed again, you violate the lifecycle of the handler.
It is similar if you violate the lifecycle of OSGi services and access it if it is not activated.

There are options to make the whole handling less error prone:
the `initialize` methods could require to return a `InitializedThingHandler` instance. The `InitializedThingHandler` interface extends the `AutoCloseable` interface that is called instead of the previously used `dispose`.
Using such a construct you could ensure that all necessary references are supplied on object construction and are non null, etc.

I assume this would allow more static analysis as it will possible with OSGi R7 DS activtation using the constructor as the activation method.

But this would be such a big refactoring that I don't think someone will happy (as long as it is not finished and all existing code has been migrated).

**Comment by wborn** [comment]
> It is similar if you violate the lifecycle of OSGi services and access it if it is not activated.

I just re-read  [openHAB](https://www.openhab.org/docs/developer/development/conventions.html#null-annotations) and [ESH](https://www.eclipse.org/smarthome/documentation/development/conventions.html) Null Annotations Conventions and it states that fields of ThingHandlers that are initialized in in `initialize()` can also be annotated with `@NonNullByDefault({})`. 

Do you still agree with that? :-)

> Fields that get a static and mandatory reference injected through OSGi Declarative Services can be annotated with

```java
@NonNullByDefault({})
private MyService injectedService;
```

> to skip the nullevaluation for these fields.
>Fields within `ThingHandler` classes that are initialized within the `initialize()` method may also be annotated like this, because the framework ensures that `initialize()` will be called before any other method.
>However, please watch the scenario where the initialization of the handler fails, because fields might not have been initialized and using them should be prepended by a `null` check.

**Comment by maggu2810** [comment]
@wborn What do you mean?

The nullness annotations are for an additional hint for to developers that use the framework to explicit state if null is allowed or expected. The nullness annotations are also used for some static code checking.

`@NonNullByDefault({})` can be used to disable the code check for specific parts of a class that has been annotation with `@NonNullByDefault` by itself.

If the lifecycle is violated I personally don't care (ATM) which exception is thrown -- it is a violation regardless of the specific type.

My comment above should only point to some constructs that make it simpler for static code analysis and developers to ensure that the life-cycle is not violated, e.g. by constructing objects as soon as the lifecycle beings and close them as soon as it ends. It will make the framework more stable...
But it would involve a very big change and has not been a suggestion for backlog ticket at all. :wink:

**Comment by wborn** [comment]
I haven't seen `@NonNullByDefault({})` being used in handlers for suppressing potential NPE warnings with `@Nullable` handler fields. The `@Nullable` cached configuration fields in handlers would make a good candidate since these are assigned in `initialize()`. So there would be less reasons for using `getConfigAs` in other methods besides in `initialize()`. I.e. it makes less sense to start caching it.

The InitializedThingHandler approach might be even better but it would sure take some time to get that all implemented!

**Comment by htreu** [comment]
I'm okay with using `@NonNullByDefault({})` on the configuration fields. Especially when the official documentation says so ;-)
@wborn if this fixes it for you please close here. And for the future we should keep it in mind and offer the solution to binding developers during review.

**Comment by wborn** [comment]
Yes this fixes the issue for me.

I'll kickstart the proliferation of using `@NonNullByDefault({})` for such fields in handlers by adding some more null annotations to bindings. :-)
