### ISSUE TITLE
PointType, or DecimalType, (or BigDecimal) do not test for empty strings

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#589]
migrated from Bugzilla [#467612](https://bugs.eclipse.org/bugs/show_bug.cgi?id=467612)
status NEW severity *normal* in component *Core* for *---*
Reported in version *unspecified* on platform *PC*
Assigned to: Project Inbox

On 2015-05-19 14:58:46 -0400, karel goderis wrote:

> Feeding an "" string to either parameter in
> 
>     public PointType(StringType latitude, StringType longitude, StringType altitude) {
>         this(new DecimalType(latitude.toString()), new DecimalType(longitude.toString()), new DecimalType(
>                 altitude.toString()));
>     }
> 
> throws a NumberFormatException on line 545 of java.math.BigDecimal
> 
> IMO the ESH core should test for empty variables, and initialize to a default value, for example 0 inc case of DecimalType. Shortcut is for example to initialize with PointType("0","0","0")

On 2015-05-20 09:04:57 -0400, Kai Kreuzer wrote:

> My personal opinion is that it is terrible to have string-based constructors at all. Couldn't we just offer constructors that accept Numbers?

On 2015-05-20 09:09:55 -0400, Kai Kreuzer wrote:

> The normal way to use it should be
> PointType(52.52,13.38,36.1)
> 
> The only reason for strings might be to support degree formatting, i.e. instead
> PointType("52Â° 31' 7.05'' N", "13Â° 22' 34.30'' E", 36.1)

On 2015-05-20 09:16:14 -0400, karel goderis wrote:

> Ok, but what do you do if you are not able to provide the three parameters at the same time? In the case of the Tesla binding longitude etc are reported sequentially by the car, and on top, "0" is also a valid value.

On 2015-05-20 09:19:44 -0400, Markus Rathgeb wrote:

> In general (without knowing your special use case), I prefer not using a valid value for an unknown value.

On 2015-07-03 08:55:46 -0400, gael lhopital wrote:

> I submit these thoughts to yours :
> 
> https://github.com/eclipse/smarthome/compare/master...clinique:bug467612
> 
> An approach to handle NaN at DecimalType level.
> Didn't sort out how to handle it for intValue() and longValue()

On 2015-07-06 06:05:54 -0400, Kai Kreuzer wrote:

> > Ok, but what do you do if you are not able to provide the three parameters at the same time?
> 
> Not instantiating a type at all, because the content is simply not complete.
> 
> > An approach to handle NaN at DecimalType level.
> 
> Why not throw an IllegalArgumentException if a there is a NumberFormatException? Why pretend everything is fine and silently use null internally?

On 2015-07-07 10:30:45 -0400, gael lhopital wrote:

> (In reply to Kai Kreuzer from comment # 6)
> > > Ok, but what do you do if you are not able to provide the three parameters at the same time?
> > 
> > Not instantiating a type at all, because the content is simply not complete.
> > 
> > > An approach to handle NaN at DecimalType level.
> > 
> > Why not throw an IllegalArgumentException if a there is a
> > NumberFormatException? Why pretend everything is fine and silently use null
> > internally?
> 
> NaN was an option, but it clearly reaches its limits with intValue() and longValue(). Then I will dig the Exception approach.

On 2015-07-07 11:23:51 -0400, gael lhopital wrote:

> ...and raising an exception was the default behaviour - then what is the option ?

On 2015-07-08 03:21:13 -0400, Kai Kreuzer wrote:

> Which option?

On 2015-07-14 06:36:03 -0400, gael lhopital wrote:

> Updated the proposal made here https://github.com/eclipse/smarthome/compare/master...clinique:bug467612
> 
> in order to raise an IllegalArgumentException in DecimalType when the argument is wrong and also to clarify the fact that string argument passed to PointType must be in Degree Minute Second format, decimal degree must be passed to constructor as DecimalType.
> 
> Your thoughts ?
> 
> I mess a bit in determining wether arguments transferred to constructor must be String or StringType, DecimalType or BigDecimal... Can someone help me clarify this ?

On 2015-07-16 06:12:05 -0400, Kai Kreuzer wrote:

> Hm, in general I would suggest to align it with the HSBType, i.e.
> 1. There is one constructor that takes the "raw" constituants (i.e. 2 or 3 DecimalTypes  im this case)
> 2. There is another constructor that takes ONE String parameter, where the string is expected to be in the format that toString() returns.
> 
> I'd therefore expect it to still be PointType("48.8566140,2.3522219") and not PointType("N48Â° 51' 23.81\", E2Â° 21' 7.999\"").

On 2015-07-16 07:34:03 -0400, gael lhopital wrote:

> Ok, then I cleanup constructors, assuming that input are always and only decimal degrees and drop the option of inputing DMS format. right ?

On 2015-07-16 07:34:28 -0400, Kai Kreuzer wrote:

> Would be my suggestion, yes.

On 2015-07-16 10:47:37 -0400, gael lhopital wrote:

> Ok, then modified the code sample in this direction. If agreed, I'll then make a PR

On 2015-07-17 03:25:32 -0400, Kai Kreuzer wrote:

> Thanks, look pretty good to me.
> 
> @Karel, as you entered the issue, are you as well fine with the solution?

On 2015-07-20 08:19:59 -0400, Markus Rathgeb wrote:

> Just a question:
> 
> > 2. There is another constructor that takes ONE String parameter, where the string is expected to be in the format that toString() returns.
> 
> > I'd therefore expect it to still be PointType("48.8566140,2.3522219") and not PointType("N48Â° 51' 23.81\", E2Â° 21' 7.999\"").
> 
> In respect to # 434006 do we need to support different string representations for the same value? Are there already some thoughts about the toString and the creation from string using different units that codes the same value?

On 2015-07-20 08:32:14 -0400, Kai Kreuzer wrote:

> In general I would say, the String constructor should be able to parse any string that the class can potentially create through its toString() method. Whether two values with different string values can be considered to be equal of not is probably something to delegate to the equals() method.

**Comment by clinique** [comment]
The PR for this was ready since a while - sorry to have left it open. Pushing it.

**Comment by clinique** [comment]
This can be closed now then.
