### ISSUE TITLE
MQTT broker ignores secure settings

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#5896]
While 

https://github.com/eclipse/smarthome/blob/d28ea636733021512b9fff608432ac48f1f65570/extensions/binding/org.eclipse.smarthome.binding.mqtt/ESH-INF/thing/thing-types.xml#L26-L36

defines a `secure` config parameter, the handler ignores it when creating a connection

https://github.com/eclipse/smarthome/blob/d28ea636733021512b9fff608432ac48f1f65570/extensions/binding/org.eclipse.smarthome.binding.mqtt/src/main/java/org/eclipse/smarthome/binding/mqtt/handler/BrokerHandler.java#L180

Also, the corresponding type  in 

https://github.com/eclipse/smarthome/blob/d28ea636733021512b9fff608432ac48f1f65570/bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnectionConfig.java#L29

does not match the thing type definition.

@davidgraeff could you please have a look?

**Comment by davidgraeff** [comment]
True. I'll have a look.
