### ISSUE TITLE
Cannot link Items with Number type to Channels with Decimal Type

### ISSUE THREAD

**Issue by hexamer** [eclipse/smarthome#5904]
Version: openHAB 2.3.0 with Paper UI

Some Z Wave things (e.g. ZW056) create channels with type "Decimal".  This makes it impossible to create and link any items in Paper UI.  If a Number typed item is created then it will not show up in the UI for linking to the channel.  If an item is attempted to be auto-created, the new item is typed Decimal and then is refused to be created.  Details are available here: https://community.openhab.org/t/item-type-number-or-decimal/37610

Decimal and Number types should be compatible since I can workaround this issue by linking the items via items files.

**Comment by lolodomo** [comment]
Is Decimal a valid type ? I think it isn"t while Number is.

**Comment by cdjackson** [comment]
My bad - you are right, I’ve mixed up the item types and the states - Decimal is a valid state - Number is the item.

I’ll update the binding - This can be closed.

**Comment by cdjackson** [comment]
One interesting question here is why this worked within an item file? This is what caused the confusion (ie given it worked in the items file, and not in the UI, it seemed to be a UI issue)...
