### ISSUE TITLE
Tradfri GW <-> Osram Lightify Smart+ Plug

### ISSUE THREAD

**Issue by n30ngruu3n** [eclipse/smarthome#5935]
Hello,

I've managed to pair my 2 Lightify Smart+ Plugs (shipped on Monday) with my Tradfri GW to switch them with the remote and I'm also able to see them in the Tradfri App. Next idea was to integrate them via the Tradfri-Binding in my OH2 installation. With the TRACE Option I'm able to see the GW is telling OH2 that there are the Plugs:

`15:05:05.168 [DEBUG] [g.tradfri.internal.TradfriCoapHandler] - CoAP response
options: {"Content-Format":"application/json", "Max-Age":604800}
payload: {"9001":"Plug 2","9002":1532002054,"9020":1532003503,"9003":65566,"9054":0,"5750":3,"9019":1,"3":{"0":"OSRAM","1":"Plug 01","2":"","6":1,"3":"V1.04.12"},"3312":[{"5850":0,"9003":0}]}
15:05:05.183 [DEBUG] [tradfri.handler.TradfriGatewayHandler] - requestDeviceDetails response: {"9001":"Plug 2","9002":1532002054,"9020":1532003503,"9003":65566,"9054":0,"5750":3,"9019":1,"3":{"0":"OSRAM","1":"Plug 01","2":"","6":1,"3":"V1.04.12"},"3312":[{"5850":0,"9003":0}]}
15:05:05.196 [DEBUG] [g.tradfri.internal.TradfriCoapHandler] - CoAP response
options: {"Content-Format":"application/json", "Max-Age":604800}
payload: {"9001":"Plug 1","9002":1532002571,"9020":1532003495,"9003":65569,"9054":0,"5750":3,"9019":0,"3":{"0":"OSRAM","1":"Plug 01","2":"","6":1,"3":"V1.04.12"},"3312":[{"5850":0,"9003":0}]}
15:05:05.210 [DEBUG] [tradfri.handler.TradfriGatewayHandler] - requestDeviceDetails response: {"9001":"Plug 1","9002":1532002571,"9020":1532003495,"9003":65569,"9054":0,"5750":3,"9019":0,"3":{"0":"OSRAM","1":"Plug 01","2":"","6":1,"3":"V1.04.12"},"3312":[{"5850":0,"9003":0}]}` 

I've tried to add them in the *.items file with the IDs 65566 & 65569 and Type 0010 (referenced to the ZigBee documentation and the implementation in the Hue Binding) but the commands aren't forwarded to the GW by the CoAP Handler. 

Is it possible to add the behaviour for the Type 0010 by myself or is it quite impossible until IKEA releases their own Smart Plugs in the Tradfri environment?

I would be very thankful for every idea!

Greets 
n30ngruu3n

**Comment by n30ngruu3n** [comment]
Thank you for your hint with the ESH IDE; I've expected that the declaration in the items file only with the zigbee attributes (like with the HUE GW) won't be enough.. So maybe I'm going to find a way for add this behaviour with the IDE or I have to wait until IKEA releases their Plugs (as announced on the web in the same phase like the transformer..) or by the HUE GW.

The Plugs where recognised by the GW / App and are switchable with the remote but nothing more until now (see pic) and anyway the GW is still the opinion that the Battery is empty :D 

![img_5229](https://user-images.githubusercontent.com/16103596/42945311-5e26cf0a-8b68-11e8-9486-f7dfef198e53.jpg)

**Comment by kaikreuzer** [comment]
@n30ngruu3n I just bought myself an OSRAM Smart+ Plug and I was able to pair it with my IKEA remote. Unfortunately, I am failing to add it in the TRADFRI app as well. As what device type did you add it? I tried "LED-Lampe" and "Transformator", but nothing is happening. Any hints for me?

**Comment by n30ngruu3n** [comment]
@kaikreuzer I'm sorry about my late answer, but I was bound in tasks by my university. So here's what helped me:

I've also tried to pair them via the App as "LED-Lampe" and as a "Transformator" but no option of them worked really well (some times it worked with the first plug -> pairing the second crashed the gateway and so on..). What then worked was more a coincidence than really a planned workflow: I've removed the remote and the plugs from the Gateway via the App to start from scratch and then first paired the plugs with the remote before I've paired the remote with the GW which caused the plugs to be shown in the App. What also worked was just pairing the remote with the GW (with a "scratch" starting point); pair the remote with the plugs without the App; start the app, wait about 20 seconds to sync App & GW & remote and then restart the Gateway. 

You see, it's quite more taking a shot in the dark than having a plan..

Good Luck for pairing :)

n30ngruu3n

**Comment by n30ngruu3n** [comment]
by the way; as a starting point I've used this video: https://www.youtube.com/watch?v=ESufRs3m0Fw&frags=pl%2Cwn [in german.. but that may no problem as of your company affiliation 😃 ]

**Comment by kaikreuzer** [comment]
Thanks @n30ngruu3n. It just took me roughly 2 hours to get my plug paired with the gateway 😠 .

I have implemented https://github.com/eclipse/smarthome/pull/5973, which should bring support for those plugs. I just cannot test it right now, because my plug is shown as unreachable in the app/gateway now and thus it does not react to any commands. I'll try to re-pair it on the weekend, maybe a bit quicker this time. But I am pretty confident that my PR will actually work (assuming that there are no major bugs in the tradfri gateway firmware).
