### ISSUE TITLE
Color item does not act upon INCREASE/DECREASE command

### ISSUE THREAD

**Issue by powerpolly** [eclipse/smarthome#5938]
a HSBType Color item should increase/decrease its brightness by issueing command, but it doesn´t.
`Color LED_Office_Color_tasmota   "LED Licht"                    {mqtt=">[broker:cmnd/LED_Office/HSBColor:state:*:default]"}`

`LED_Office_Color_tasmota.sendCommand(DECREASE)`

full description with logs is found here:
[https://community.openhab.org/t/increase-decrease-brightness-on-hsbtype-led/48026/5](url)

**Comment by triller-telekom** [comment]
I am assuming the bug in the MQTT binding. From what you say the facts are:

An `INCREADE/DECREASE` to this item does not work.

```
Color LED_Office_Color_tasmota   "LED Licht"                    {mqtt=">[broker:cmnd/LED_Office/HSBColor:state:*:default]"}
```

But it does work for this item:

```
Dimmer LED_Office_Dimmer "Dimmer Office [%.0f %%]" {mqtt=">[broker:cmnd/LED_Office/DIMMER:command:*:default], <[broker:stat/LED_Office/RESULT:state:JSONPATH($.Dimmer)"}
```

However both items are linked to two **different channels**. Thus I am assuming the channel which you link against your `Color` item does not react on `INCREASE/DECREASE` commands.

Could you please post the relevant parts of your `.things` file. So we know which MQTT things and channels we are talking about? Also which MQTT binding are you using?

**Comment by triller-telekom** [comment]
Oh you are using the openHAB1 binding of mqtt, sorry I didn't see that... There is no `.things` file.

**Comment by kaikreuzer** [comment]
Items do not process commands at all - it is the duty of the binding to process those.

This is therefore no issue in ESH.
