### ISSUE TITLE
Date / Time handling

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#594]
migrated from Bugzilla [#479362](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479362)
status NEW severity _enhancement_ in component _Core_ for _---_
Reported in version _0.8.0_ on platform _All_
Assigned to: Project Inbox

On 2015-10-08 13:25:03 -0400, Markus Rathgeb wrote:

> I would like to remove some warnings and realized that the FilterCriteria (and so some tests) of core.persistence is using the Date object.
> 
> If there is no reason we have to use that, I would like (if there is some time) to move form Date to another class.
> 
> Using Date without a Time does not allow set a begin and end time.
> So, moving to a calendar object should allow an better filtering, too.
> 
> How does the persistence / the whole ESH framework handle time references?
> Are all time references handled in UTC or in local time (e.g. using a begin / end mark, an expression in the rules, ...)?
> 
> If the local time is used do you see any problems if I use a UI on a system that using a different timezone as the system running ESH?

On 2015-10-25 01:42:01 -0400, Kai Kreuzer wrote:

> Yes, currently the assumption is always "local time of runtime".
> 
> > If the local time is used do you see any problems if I use a UI on a system that using a different timezone as the system running ESH?
> 
> Well, the UI would show the time of the runtime (e.g. my charts look the same from whereever I am). They won't tell me the sun is shining at midnight, just because I (and the UI) am on the other side of the earth.
> 
> But in general, I am also fine with moving to Calendar.

On 2015-10-25 05:47:24 -0400, Markus Rathgeb wrote:

> - I would expect that the time (stored in the persistence) is an always increasing value
> - We have to ensure, that it is stored with all informations.
> - DST flag (handle transitions from 2:59 DST to 2:00 non-DST)
> - Timezone (handle changes of time zone correctly)
> - How to handle a decreasing time?
> 
> For the last point I used a monotonic timestamp and a offset in the past.
> But I do not know, what we need to solve / grant at all?
> 
> If there is a method to get data points between a range, IMHO we must ensure, that the time is increasing only (could be solved with the offset, but perhaps we could state, that this case is out of scope of the framework and must be granted by the system).

On 2015-10-26 20:46:31 -0400, Kai Kreuzer wrote:

> Doesn't "milliseconds since 1.1.1970" (i.e. the Date class) fulfill all your requirements, assuming that the runtime does not move and stays during its lifetime in the same time zone?

**Comment by kaikreuzer** [comment]
@maggu2810 Any answer on my last comment?

**Comment by maggu2810** [comment]
So I prefer to move (in relevant classes, needs to be checked) to Calendar on some places and we should also stop using deprecated API of the Date class.

Using "millis from Epoch" is ok for me using the system timezone, too.

I didn't realize, I missed an answer to your last comment.
I didn't close this issue because it is not done...

**Comment by hakan42** [comment]
Out of curiosity, would moving to joda time solve some of those problems? I must admit that I don't like the JDK Date very much :smile:

**Comment by kaikreuzer** [comment]
I would not want to introduce a dependency to joda in the core bundles, especially since joda is obsolete with Java 8.

**Comment by hakan42** [comment]
O.k. on the dependency part, but what is the target / minimum JDK for OH2 / ESH? OH1 is still 1.6 and higher, right?

**Comment by kaikreuzer** [comment]
OH1 is 1.5, ESH is 1.7, but aiming for Java 8 CP2.

**Comment by watou** [comment]
FTR, there are Java 1.7 dependencies in at least a few OH1 bindings, but perhaps no action is warranted on that at this point.

**Comment by kaikreuzer** [comment]
Well, Java 7 stuff should still run ok when using Java 8. And I wasn't talking about OH2 here, only about ESH.

**Comment by htreu** [comment]
This should be addressed by #4738.
