### ISSUE TITLE
Should tags be case-sensitive or case-insensitive? 

### ISSUE THREAD

**Issue by afuechsel** [eclipse/smarthome#5941]
In https://github.com/eclipse/smarthome/pull/5936#discussion_r203952339 we came up to a question I see as an issue: If we use tags on items to define specific semantics (see https://github.com/eclipse/smarthome/wiki/Semantic-Tag-Library for more info), should we compare tags case-sensitive or case-insensitive? 

IMHO a tag "capability:switchable" would be exactly the same like "Capability:Switchable". The current implementation of `GenericItem` (e.g. https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java#L343) does compare case-sensitive.

The question is: should we stick to that or change to case-insensitive?

**Comment by kaikreuzer** [comment]
I do not think that we will ever define two tags that have the same characters, but a different case - so imho it should be fine to treat the tags case-insensitive.
Nonetheless, we should make sure to only define the tag in one way, i.e. do not use different cases at different places of code/examples/documentation as this could confuse people as well.

**Comment by afuechsel** [comment]
I agree to what you said, @kaikreuzer. To implement a case insensitive tag matching, changes would be required on GenericItem. I will provide a PR.
