### ISSUE TITLE
SysfsUsbSerialScanner logs INFO on MacOS

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#5955]
Just found this in my logs:
```
12:52:06.231 [INFO ] [xsysfs.internal.SysfsUsbSerialScanner] - Cannot perform scans with this configuration: sysfsTtyDevicesDirectory: /sys/class/tty, devDirectory: /dev
12:52:06.235 [INFO ] [xsysfs.internal.SysfsUsbSerialScanner] - Cannot perform scans with this configuration: sysfsTtyDevicesDirectory: /sys/class/tty, devDirectory: /dev
12:52:06.241 [INFO ] [ysfs.internal.PollingUsbSerialScanner] - Do not start background scanning, as the configured USB-Serial scanner cannot perform scans on this system
12:52:06.242 [INFO ] [ysfs.internal.PollingUsbSerialScanner] - Do not start background scanning, as the configured USB-Serial scanner cannot perform scans on this system
```
First of all, it is weird that both messages appear twice.
But as I am running on MacOS, and the scanner is anyhow only supposed to work on Linux, I would actually expect to have no logging (meaning here DEBUG level) at all.

@hsudbrock Would you agree?

**Comment by hsudbrock** [comment]
First, I agree that, ideally, neither of the two messages should appear twice. Let me check later why this could happen, and how this could be prevented.

Regarding the log level: I think that it is superfluous to have both log messages on INFO level. I used INFO level when adding this in https://github.com/eclipse/smarthome/pull/5521, as it might happen also on a Linux system that scanning is not possible, e.g., if the user has not sufficient rights to read the required folders, or if the Linux system uses a non-standard directory layout. In this case, it is useful for the Linux user to see the log message. I would hence prefer leaving the log message for the `SysFsUsbSerialScanner` on INFO level, reducing the one for the `PollingUsbSerialScanner` to DEBUG. One could of course also argue that if scanning does not work on a Linux system, the user could increase the log level to DEBUG to get more infos on why it does not work - but I think it would be easier for the user to get the message on INFO level already. What do you think, @kaikreuzer ?

**Comment by hsudbrock** [comment]
Why do the log messages appear twice?

* `PollingUsbSerialScanner`: The `activate` method of the `UsbSerialDiscoveryService` starts the background discovery explicitly; moreover, when calling `super.activate()`, the `AbstractDiscoveryService` will also start it. This results in the two log messages. The explicit call in the `UsbSerialDiscoveryService` should be removed.
* `SysfsUsbSerialScanner`: The only way I could explain this is that the configuration is provided twice, e.g., once via a call of `activate` and a second time via a call of `modified`. An option is to only reconfigure and check the configuration when the configuration actually changes.

Thanks for hinting at these with your log messages, @kaikreuzer, I will add a PR for those two changes, and we can discuss there further.

**Comment by kaikreuzer** [comment]
Thanks for your analysis and the PR, that looks good!

> One could of course also argue that if scanning does not work on a Linux system, the user could increase the log level to DEBUG to get more infos on why it does not work - but I think it would be easier for the user to get the message on INFO level already. What do you think, @kaikreuzer?

I agree that INFO logging on a Linux system makes sense in that case (if not even WARN), but for any other OS, I would still expect the bundle to be silent (we are back at the discussion that the bundle should actually only become active on Linux and nowhere else).

As we are failing to determine the OS we are running on, the best compromise might be to log a warning if the user provided a configuration (in which case he definitely needs to be informed if that isn't working) and only do debug logging if we are using the defaults, which we know are anyhow only a best guess (as not applicable for anything else but Linux and not even necessarily applicable to all Linux distros). Wdyt?

**Comment by maggu2810** [comment]
> As we are failing to determine the OS we are running on

What about system property "os.name" and that values
https://www.osgi.org/developer/specifications/reference/#ReferenceOS

**Comment by maggu2810** [comment]
Do you know which OSGi started to provide osgi.native.osname?
https://osgi.org/specification/osgi.core/7.0.0/framework.namespaces.html

**Comment by kaikreuzer** [comment]
> What about system property "os.name"

Afair, we discussed this when introducing this feature (cannot find a reference right now, though), and we had to notice that `os.name` isn't necessarily always set - e.g. in openHAB with Karaf it wasn't available. And then again, the possible values are a long list, which also isn't easy to use as an input and also still won't tell you whether the USB feature is available at all or not.

**Comment by maggu2810** [comment]
I remember that "osgi.os" is not available, see #1416
"os.name" is AFAIK a property of the JVM itself

**Comment by kaikreuzer** [comment]
Hm, we probably would have to dig deeper into this to find a reliable way. But I'd suggest to leave this out of scope here and rather go for a logic as suggested above - especially as even if we find "linux" as an OS, we do not know whether this USB mechanism is compiled in or not.

**Comment by hsudbrock** [comment]
I have checked the `os.name` property on four systems (Laptop running Linux, three embedded gateways running Linux) - and the value of the property was actually always `Linux`. 

Nevertheless, I do not have a really good feeling about this property yet (in particular, as the website linked above writes: "This list was adapted from the list at http://www.tolstoy.com/samizdat/sysprops.html. If you have an operating system or processor not listed, please run the properties.jar bundle and send the webadmin the output."  - and the linked list does not exist anymore, and the suggestion to add missing values hints at that this list might not be complete).

I, hence, would also prefer @kaikreuzer's suggestion above, to use level `WARN` if a configuration differing from the defaults was provided, and to use level `DEBUG` otherwise. Would this be OK for you as well, @maggu2810?

**Comment by maggu2810** [comment]
Sure, on non Linux system the user does not care, on "standard" Linux systems it should work out of the box and on some special systems, the user can check the debug log.

**Comment by hsudbrock** [comment]
Ok, I updated the PR accordingly.
