### ISSUE TITLE
Add size()-Method to StringListType.

### ISSUE THREAD

**Issue by maihacke** [eclipse/smarthome#5969]
For some use cases it is useful to find out the number of elements in a StringList (e.g. https://community.openhab.org/t/fritzbox-binding-tr064-getting-and-staying-last-caller-in-openhab/37645/6?u=maihacke).
So please add a method to get the size of the list.

**Comment by kaikreuzer** [comment]
The underlying use case is addressed by https://github.com/eclipse/smarthome/pull/5994, so there should be no need for a size() method anymore.
