### ISSUE TITLE
Circular reference detected (ConfigDescriptionRegistry)

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#597]
migrated from Bugzilla [#483029](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483029)
status NEW severity *normal* in component *Core* for *---*
Reported in version *0.8.0* on platform *All*
Assigned to: Project Inbox

Original attachment names and IDs:
- _[org.eclipse.smarthome.config.core.log](https://bugs.eclipse.org/bugs//attachment.cgi?id=258281)_ (ID 258281)
- _[circular-1.txt](https://bugs.eclipse.org/bugs//attachment.cgi?id=258293)_ (ID 258293)
- _[circular-2.txt](https://bugs.eclipse.org/bugs//attachment.cgi?id=258296)_ (ID 258296)

On 2015-11-25 13:28:01 -0500, Markus Rathgeb wrote:

> I tried using the same start level for all org.eclipse.smarthome and the related Xtext bundles.
> 
> I get this message:
> 
> 2015-11-25 19:20:47,931 | ERROR | pool-23-thread-1 | core                             | 99 - org.eclipse.smarthome.config.core - 0.8.0.201511251757 | [ConfigDescriptionRegistry(0)] Circular reference detected, getService returning null
> 
> (the only logged error)
> 
> Dennis, you already solved such a problem here:
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=477482
> 
> Could you have a look at, that is the best approach?
> I will try to have a look at this, too, but I think you are much more familiar with this...

On 2015-11-25 17:32:37 -0500, Markus Rathgeb wrote:

> Created attachment 258281
> org.eclipse.smarthome.config.core.log
> 
> Add a more verbose log...

On 2015-11-26 05:29:31 -0500, Dennis Nobel wrote:

> Hi Markus,
> 
> I can not find an obvious circular dependency there. The tracker tracks the ConfigDescriptionRegistry, which only tracks ConfigDescriptionProvider. The only ConfigDescriptionProvider is the XMLConfigDescriptionProvider, which does NOT have a dependency to the ConfigDescriptionRegistry.
> 
> So I have no idea :(.
> 
> Do you have any additional bundles installed? Or a specific branch?
> 
> Regards
> 
> Dennis

On 2015-11-26 14:29:14 -0500, Markus Rathgeb wrote:

> Created attachment 258293
> circular-1.txt
> 
> Hi Dennis,
> 
> thank you, that you have a look at this.
> 
> I have added some informations I currently collected. Have to learn all that diagnostic command lines of Karaf.
> 
> Perhaps "org.eclipse.smarthome.io.rest.core" is involved in the circular dependencies...
> 
> If you want to play with this setup, I can give you a link.

On 2015-11-26 14:57:04 -0500, Markus Rathgeb wrote:

> Created attachment 258296
> circular-2.txt

**Comment by maggu2810** [comment]
This one has been solved already. It has been related to the swagger packages bundled in the rest bundles.
