### ISSUE TITLE
nrjavaserial rfc2217 needs org.apache.commons.net 3.3

### ISSUE THREAD

**Issue by msteigenberger** [eclipse/smarthome#5974]
ESH currently uses version 3.2 of org.apache.commons.net.
The rfc2217 support of nrjavaserial has an Import-Package to 
_org.apache.commons.net.telnet;resolution:=optional;version="**[3.3,4)**"_

As its an optional import, the bundle at least resolves. But at runtime the CNF occurs because of the version constraint.
Can we update this in the TP? Its needed for https://github.com/eclipse/smarthome/pull/5560

**Comment by kaikreuzer** [comment]
Sounds as if an upgrade of the minimal version requirement makes sense.
Unfortunately, version 3.3 is not available in Eclipse Orbit, so we will have to create a CQ. Luckily, it has already been approved for other projects, so that shouldn't be an issue.
@maggu2810 Wdyt, would you be fine with that upgrade?

**Comment by maggu2810** [comment]
I am fine with the upgrade.

With my TP feature changes in #5612 I tried to clean up the base TP feature already.

There has been still open tasks, see https://github.com/eclipse/smarthome/pull/5612#issuecomment-396267042
>An additional task that should / could be done some time is to reduce the base targetplatform as much as possible.
We could IMHO drop some of the Apache Commons as we don't use them anymore (at least it seems so).



AFAIK `org.apache.commons.net` is currently used by the MQTT binding and the NTP binding only.
No core package depends on it.

IMHO it should be moved from the `esh.tp-base` to a separate one, e.g. `esh.tp-commons-net` and the MQTT binding, the NTP binding and now also the rfc2217 feature should depend on it.

**Comment by kaikreuzer** [comment]
> IMHO it should be moved from the esh.tp-base to a separate one, e.g. esh.tp-commons-net and the MQTT binding, the NTP binding and now also the rfc2217 feature should depend on it.

Sounds reasonable to me. Shall I create the CQ and add it to the 3rd party p2 repo and you adapt the Karaf TP accordingly?

**Comment by maggu2810** [comment]
:+1:

**Comment by kaikreuzer** [comment]
Created CQ 17045.

**Comment by kaikreuzer** [comment]
CQ has already been approved - created https://github.com/eclipse/smarthome/pull/5983.

**Comment by kaikreuzer** [comment]
Next step: https://github.com/eclipse/smarthome/pull/5984 - the rest I leave to @maggu2810 :-)

**Comment by kaikreuzer** [comment]
I guess this can be closed now.
