### ISSUE TITLE
RestAPI get /items/{itemname} don't publish UoM-infos

### ISSUE THREAD

**Issue by hr3** [eclipse/smarthome#5977]
For HABPanel usw. it would be importand to get the UoM-infos of a item.
Please can you extend the output about
- used unit
- ggf. list with all valid units (for this item)

and add a optional parm target unit, for converting the state to the correct value

https://github.com/openhab/org.openhab.ui.habpanel/pull/310

**Comment by kaikreuzer** [comment]
The unit is already provided as part of the state destription -> pattern, see e.g. this response from the openHAB demo server http://demo.openhab.org:8080/rest/items/Temperature_GF_Living:

```
{
  "link": "http://demo.openhab.org:8080/rest/items/Temperature_GF_Living",
  "state": "20.1",
  "stateDescription": {
    "pattern": "%.1f °C",
    "readOnly": false,
    "options": []
  },
  "editable": false,
  "type": "Number",
  "name": "Temperature_GF_Living",
  "label": "Temperature",
  "category": "temperature",
  "tags": [],
  "groupNames": [
    "Temperature",
    "GF_Living"
  ]
}
```

**Comment by hr3** [comment]
I know, but it's only the first point and works only if there is a format with unit in the label.
`Number:Temperature Temp1`
![hc_368](https://user-images.githubusercontent.com/6402769/43382751-15c273c6-93d9-11e8-9f3b-cb2f917a3e91.jpg)
![hc_366](https://user-images.githubusercontent.com/6402769/43382759-1bb52c4c-93d9-11e8-8076-0b9c2c7fe8cf.jpg)
![hc_367](https://user-images.githubusercontent.com/6402769/43382766-2242dc44-93d9-11e8-9551-06561b8b70ee.jpg)
