### ISSUE TITLE
Persistence stopped after modifying items

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#5991]
Moved from openhab/openhab2-addons#3626.

> When I modify any item/rule or persist file, the persistence dont update anything to database. I need to restart the OH service.

> I have introduced JDBC MariaDB persistence in my live environment yesterday. I have similar issues for my items after changing their configuration.

This happens if you use e.g. a `everyChange` strategy only. A user defined cron based strategy (e.g. `everyMinute : "0 * * * * ?"`) continues working like expected.

**Comment by maggu2810** [comment]
As long as there is no official ESH persistence service it is difficult to judge if there is an error in the OH compat1x layer or the OH1 binding.

Perhaps I will find some time to test this without compat1x and a ESH persistence service the next days.

**Comment by cweitkamp** [comment]
See also: https://community.openhab.org/t/mysql-persistence-item-stopped-updating-after-adding-removing-from-group/26971
