### ISSUE TITLE
[UI / Charts] Consider default persistence configuration for drawing charts

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#5993]
Currently the `DefaultChartProvider` uses the first persistence service if one does not define a service for the Chart element. We have a configuration for a default persistence service in the `PersistenceServiceRegistry` which should be considered for querying the data in such case.

https://github.com/eclipse/smarthome/blob/fadc8ef4e5e8ba826bdb14105224086634ea8688/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java#L209-L215

**Comment by triller-telekom** [comment]
Good point. Looking at it, I am wondering why the `DefaultChartProvider` does not have a dependency to the `PersistenceServiceRegistry`, but collects the services via

```
@Reference(cardinality = ReferenceCardinality.MULTIPLE, policy = ReferencePolicy.DYNAMIC)
    public void addPersistenceService(PersistenceService service) {
```

by itself. So if you touch this class, maybe you can change this as well.

**Comment by cweitkamp** [comment]
I thought about that too, but it is not that easy. I assume the `DefaultChartProvider` collects the persistence services on its own because it only needs instances of `QueryablePersistenceService`.

Question is if we want to refactor this code shall it result in an APIBreaking change or shall it be backward compatible and preserve the "use first service" feature if no service is given or no default service is configured. 

My idea is to use the same logic like we use in the [PersistenceExtensions](org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensions.java): Use the given service or else the default service. Check if the result is an instance of `QueryablePersistenceService` afterwards and throw an exception if not. Skip the "use first service" logic completely.

**Comment by triller-telekom** [comment]
>  because it only needs instances of `QueryablePersistenceService`

I have seen that as well, but what prevents you from querying the `PersistenceServiceRegistry` for all services and filter the list for `QueryablePersistenceService` by yourself? At least then the collecting part would be removed from the `DefaultChartProvider` which is definitely not its job :)

Regarding the logic: Using the given service first and if not available try the configured default (if it is a `QueryablePersistenceService` sounds alright to me. To keep it somehow backward compatible, you could use the "first available `QueryablePersistenceService`" if the default one is not of type `QueryablePersistenceService`.

WDYT?

**Comment by cweitkamp** [comment]
Please have a look what I got so far: https://github.com/eclipse/smarthome/compare/master...cweitkamp:feature-5993-charts-consider-default-persistence
