### ISSUE TITLE
cannot connect to mqttembeddedbroker 

### ISSUE THREAD

**Issue by iot6466** [eclipse/smarthome#5999]
trying to connect to the MqttEmbeddedBroker always returns connection refused except if you connect from the localhost. 

Looking at the code I found that the setting for the "host" parameter is set to "127.0.0.1" which only allows local connection. Example in moquette shows a value for host of "0.0.0.0" to allow connection to anybody. 

Is there any reason why the broker is configured to accept only local connection, if not please change the setting to "0.0.0.0".

**Comment by kaikreuzer** [comment]
@davidgraeff Could you comment?

**Comment by davidgraeff** [comment]
Yes makes sense.

**Comment by kaikreuzer** [comment]
Anybody interested to create a PR for it?

**Comment by davidgraeff** [comment]
I would do it on the Webinterface, but the commit would not pass the eclipse contributor agreement because of missmatching commiter name/mail.

**Comment by iot6466** [comment]
I can try but I may need some help as it will be my first PR!

**Comment by kaikreuzer** [comment]
New contributors are always welcome :-) Just follow https://github.com/eclipse/smarthome/blob/master/CONTRIBUTING.md.

If you don't think you'll might ever do another PR, then I do not want to force you to bother with the whole process - but you guys would have to tell me which place needs to be changed exactly... But take this offer only as a fallback, a PR from yourself is preferred 👍 .

**Comment by davidgraeff** [comment]
@iot6466 Such a small change can be easily done in the webinterface of Github. Navigate to the file in question, click the edit button, edit and enter a reasonable commit message. Just don't forget the "Signed-off-by:" which is important for the Eclipse Contributor Agreement. 

Multiple file changes are better done by
* forking the Eclipse repository,
* `git clone`ing your fork,
* creating a new branch `git checkout -b patch_branch`,
* do your changes and commit them with `git commit -s` (to add the DCO line)
* and pushing your changes.

The Github webinterface on your fork as well as when you navigate the Smarthome repository will suggest to create a PR off your fork.

Cheers

**Comment by iot6466** [comment]
Hello,

I just wanted to do my first PR but thank you Kai you have been faster than
me.
You are making an incredible work on this project and it is a pleasure to
see your passion for it.

Thank YOU!

Best Regards

Jean-Claude Lugeon

**Comment by kaikreuzer** [comment]
Thanks @iot6466, but this time the kudos go to @davidgraeff as he was the one to create the PR 🥇
