### ISSUE TITLE
Provide a distribution of Eclipse SmartHome based on Concierge

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#602]
migrated from Bugzilla [#466633](https://bugs.eclipse.org/bugs/show_bug.cgi?id=466633)
status ASSIGNED severity *enhancement* in component *Core* for *---*
Reported in version *unspecified* on platform *All*
Assigned to: Jochen Hiller

On 2015-05-06 16:21:22 -0400, Jochen Hiller wrote:

> Eclipse SmartHome (ESH) is currently using Equinox as underlying OSGi framework. As more and more users are using ESH or a solution based on ESH (e.g. openHAB2) on embedded devices, e.g. Raspberry, BeagleBone, it makes sense to provide an ESH version optimized for embedded devices. To reduce footprint of the OSGi framework, Equinox can be replaced by Eclipse IoT Concierge, the OSGi R5 framework with a small footprint for IoT space.
> 
> I propose to provide a Eclipse SmartHome distribution which is based on Concierge.
> The pros are:
> * an optimized ESH distribution for embedded devices
> * lightweight OSGi framework underlying
> * provide a self-contained download of ESH 
> 
> I did some work on preparing a port of ESH to Concierge, which is the base for a contribution I plan to make. See more information at https://github.com/JochenHiller/concierge-tests/blob/master/docs/Concierge-EclipseSmartHome.md

**Comment by kaikreuzer** [comment]
Question: Where shall we put such a demo packaging?
My suggestion is to provide a fully stand-alone build, i.e. a pom.xml that does not depend on any of the other Maven projects in the repo, but instead assembles the runtime from the artifacts on repo.eclipse.org. This has several benefits:
- We only provide these files as an example, they are NOT executed as part of our build - we therefore do not publish binaries (so we do not need CQs for 3rd party libs) and it is not even a build-time dependency (so no CQ needed either).
- People wanting to build the package only need to run a Maven build on this folder, no need to run the full ESH build (which saves time and potential trouble).

We imho could either add these files as a new folder in distributions, but maybe it would be even more elegant to put them in a separate branch or even repo? @maggu2810 what's your opinion?

**Comment by maggu2810** [comment]
I would vote for a different repository as it has been done for the EnOcean driver already.
We have separate issue and pull request trackers, etc.

**Comment by kaikreuzer** [comment]
Any suggestion for its name?

**Comment by maggu2810** [comment]
Perhaps "smarthome-dist-concierge-demo"?

**Comment by kaikreuzer** [comment]
It isn't really that much about concierge, rather an example to show how to package an individual runtime. So maybe "smarthome-demo-packaging"?

**Comment by chrisschauer** [comment]
I thought it's a good idea add "minimal" to its name because it should catch some guys who want use it on a embedded device with minimal footprint.

**Comment by kaikreuzer** [comment]
@JochenHiller speaks in https://github.com/eclipse/smarthome/issues/602#issue-120137718 about "optimized ESH distribution" - imho "minimal" is relative. To me it would mean that it does not even include the Paper UI (as a UI is something optional), but this might be too minimal in order to be a demo package on which you can try out some stuff and see it working. Also, it might contain already one or two bindings.
The documentation can then explain that those things can be removed, if not needed.

**Comment by kaikreuzer** [comment]
Any further comments regarding the name? What is in common to all three suggestions is "smarthome-demo" - so we could take that as the intersection :-)

**Comment by kaikreuzer** [comment]
@maggu2810 Would "smarthome-demo" be a valid compromise for you? If so, I will enter a bug for the webmaster to create such a repo.

**Comment by maggu2810** [comment]
> It isn't really that much about concierge

If the setup is not related to Concierge only but allows different OSGi framework (e.g. Felix etc.), I assume it is okay to drop concierge from the name.

> rather an example to show how to package an individual runtime.

If it is a demo for packaging, why not keep "packaging" or "distro" or something similar in the name?

For a "smarthome-demo" I expect to demonstrate the possibilities of the Eclipse SmartHome system. This does not fit IMHO to a packaging demo with a small subset.

**Comment by kaikreuzer** [comment]
Ok, so "smarthome-demo-packaging" it is then?

**Comment by maggu2810** [comment]
"smarthome-demo-packaging" or "smarthome-packaging-demo"
I would prefer the second one but if you feel more comfortable with the first one, it is okay, too.

**Comment by kaikreuzer** [comment]
"smarthome-packaging-sample" maybe? Your comment above made me now dislike the word "demo" ;-)

**Comment by maggu2810** [comment]
:+1:

**Comment by kaikreuzer** [comment]
Ok, requested it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=501436

**Comment by kaikreuzer** [comment]
Repo has been created: https://github.com/eclipse/smarthome-packaging-sample

**Comment by chrisschauer** [comment]
I discovered some issues using concierge as runtime with non OSGi Bundles from maven repositories. I have a pom.xml with all required dependencies: https://github.com/chrisschauer/smarthome-demo/blob/master/pom.xml

For some Bundles/Jars Concierge throws a

```
Concierge> Exception in thread "main" org.osgi.framework.BundleException: Bundle with same symbolic name and same version is already installed
        at org.eclipse.concierge.Concierge.checkForCollision(Concierge.java:3743)
        at org.eclipse.concierge.BundleImpl.<init>(BundleImpl.java:231)
        at org.eclipse.concierge.Concierge.installNewBundle(Concierge.java:4003)
        at org.eclipse.concierge.Concierge.installNewBundle(Concierge.java:3966)
        at org.eclipse.concierge.Concierge$BundleContextImpl.installBundle(Concierge.java:4587)
        at org.eclipse.concierge.compat.service.XargsFileLauncher.processXargsInputStream(XargsFileLauncher.java:166)
        at org.eclipse.concierge.compat.service.XargsFileLauncher.processXargsFile(XargsFileLauncher.java:70)
        at org.eclipse.concierge.Concierge.doMain(Concierge.java:606)
        at org.eclipse.concierge.Concierge.main(Concierge.java:525)
```

The JARs does not always have a correct manifest and a defined Bundle-Name. I guess, if there is no bundle-name defined the exception occurs. Maybe if the second bundle without a name should be started. 

@kaikreuzer Using maven dependencies to create the packaging sample only works for the eclipse smarthome deps, because these are osgi bundles already. The problems affects most of the common libs e.g commons-*, guava, ibm.icu etc.

How can the eclipse orbit build help? Any idea to access the bundles inside the orbit? As i know it's a P2 Repo and not a maven repo. 

@maggu2810 How is this problem solved with karaf?

**Comment by kaikreuzer** [comment]
I doubt that there are SO many libs that are not already OSGi'fied. The message that you get rather suggests that you have the same bundle twice? If there's a jar without a manifest, I would expect concierge to simply ignore it.

We are not the only ones that need OSGi-compatible versions of these libs. Look e.g. at https://github.com/apache/camel/blob/master/platforms/karaf/features/src/main/resources/features.xml, where many of those libs are also taken from Maven (Central, I guess), and which also uses them within an OSGi container.

**Comment by chrisschauer** [comment]
O.K Let me check via the concierge mailing list how bundles without manifests are handled. Maybe it's a bug in concierge. I will ask after the mechanism to identify a bundle, if there is no manifest.

**Comment by kaikreuzer** [comment]
Better go and seek correct OSGi versions of the required bundles as stated above. After all, Karaf and others also manage to find them...

**Comment by chrisschauer** [comment]
Of course i seek the correct OSGi version. But isn't easy for commons-* libs. Karaf also uses these libs from maven central and is able to start it. concierge can't start it. Due to this i wrote to mailing list.

**Comment by maggu2810** [comment]
@chrisschauer There is a wrap feature in Karaf to create OSGi version of non OSGi bundles. But this feature is not used at all. Bnd could also transform non-OSGi bundles to OSGi ones. But also this one has not been used by us.

All bundles we are using are already OSGi ones.

**Comment by JochenHiller** [comment]
@chrisschauer Thanks for start working on that issue.
And @kaikreuzer @maggu2810 thanks for creating the demo repo.
As I am back from holidays I will also try out Christoph's branch now and investigate on that Concierge issues.
My assumption would be that the bundles created from the demo-package should be the same like in an openHAB2 build, as all these bundles are yet OSGi-fied in correct way.
Like @maggu2810 said: "All bundles we are using are already OSGi ones."

**Comment by JochenHiller** [comment]
@chrisschauer I cloned your project from https://github.com/chrisschauer/smarthome-demo and created a distribution (smarthome-demo-0.9.0-SNAPSHOT.zip). I then unpacked the distribution, and started the runtime (using JavaSE 8) by

```
cd smarthome-demo-0.9.0-SNAPSHOT/runtime/concierge
./start.sh
```
which does start without any issues. I can also connect to HTTP server via localhost:8080 and get immediately the PaperUI. There were 87 bundles running in ACTIVE state, so from a first check it looks good.
I will further tests with more bindings, but the described issues with Concierge did not happen for me.
Maybe you should check which Maven repos have been used: I had to change my settings.xml to make sure that no internal repos will be used (otherwise I had issues with jUPnP, all ESH bundles etc.).

**Comment by chrisschauer** [comment]
Hi all,

i updated my distro again. No exception - the startup works fine. I also updated the readme. In my opinion i could provide a PR against  https://github.com/eclipse/smarthome-packaging-sample.

@kaikreuzer Could you pls check why i can't fork the repo. Maybe because it's empty, or some permission thing! 

Thx

**Comment by kaikreuzer** [comment]
@chrisschauer This was apparently due to the repo not being yet initialized. I have just created a first commit in it and now it should be possible to fork it. Looking forward to your PR!

**Comment by chrisschauer** [comment]
I just created the PR: https://github.com/eclipse/smarthome-packaging-sample/pull/1
