### ISSUE TITLE
[homeatic] HM-PBI-4-FM not working 

### ISSUE THREAD

**Issue by sascha777** [eclipse/smarthome#6027]
Hi,

I am new to openhab 2.3.0-1 running on a pi 3 with an HM-MOD-RPI-PCB module and yahm 2.8.6.
I have some things and items from binding homeatic already up and running but struggle to get my new homeatic HM-PBI-4-FM (firmware 1.5) adressed.

The HM-PBI-4-FM is properly configured in yahm and successfully tested as well. The paperUi automatically detects the new thing without any error. In VS Code I also added a new item for channel 1 pressShort (tried in paperUi as well).

Switch HM_EG_WZ_Schliesskontakt_1_State {channel="homematic:HM-PBI-4-FM:PEQ01xxxxx:OEQ11xxxxx:1#PRESS_SHORT"}

Normally I see all my items state changes in the log and expected the HM-PBI-4-FM to do so too.
But when triggering the HM-PBI-4-FM I don't see any logs written nor does my rule fire.

I assume this is a bug in the binding. Could someone please check on that?

Regards,
Sascha

**Comment by sascha777** [comment]
Going to try a new hardware...

**Comment by SchrummSchrumm** [comment]
I have the same problem

**Comment by sascha777** [comment]
I didn't get it working. Sent it back and replaced it with another solution.

**Comment by z1c0** [comment]
I had the same problem and just wasted 3 hours of my life with it.
On the upside, I figured out the problem.

It's actually documented in the [Troubleshooting section](https://www.openhab.org/addons/bindings/homematic/#troubleshooting) of the OpenHab Homematic binding.

> It seems buttons like the HM-PB-2-WM55 do just send these kind of events to the CCU if they are mentioned in a CCU program. A simple workaround to make them send these events is, to create a program (rule inside the CCU) that does just have a "When" part and no "Then" part, in this "When" part each channel needs to be mentioned at least once.

So adding a dummy program in the CCU for these channels fixes the issue. Worked like a charm for me.
