### ISSUE TITLE
Lifx: wrong category for channel types ?

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#6038]
I am surprised to find the category `Temperature` for the channel types `temperature` and `temperaturezone`.
For the color temperature, the hue binding is using category `ColorLight`. Same thing for the system channel type.

PS: switching to the system channel types would not be possible for this binding because some channel settings are added to the channel type.

**Comment by kaikreuzer** [comment]
I agree that those are mistakes and should be removed.

**Comment by kaikreuzer** [comment]
> For the color temperature, the hue binding is using category ColorLight. Same thing for the system channel type.

I am actually not too sure whether this is a good idea or not. But this can be changed any time, once the bindings use the system channel types.
