### ISSUE TITLE
Inconsistent use of bundle properties in POMs

### ISSUE THREAD

**Issue by wborn** [eclipse/smarthome#6060]
There are about ~107 POM files that define the `bundle.namespace` and `bundle.symbolicName` properties. 

Should these these properties be deleted from POM files where they are defined or added to POM files where they are missing? Maybe there is a rationale why some POMs have them and others not?

I think they were once used with the maven-bundle-plugin, see this [example](http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#eclipsepde-integration).

**Comment by kaikreuzer** [comment]
We had those properties in the poms in the past, afair this derived from some skeletons that filled the MANIFEST based on those or whatever - probably linked to being used with maven-bundle-plugin as you suggest.

I do not see any reason to have them in the poms today, so I would say that they can all be safely removed.

**Comment by maggu2810** [comment]
Thank you for picking this up again.
I will be happy if we remove that properties.

**Comment by wborn** [comment]
OK great! Then I'll put in a PR later to remove them all. :-)

**Comment by maggu2810** [comment]
What has been changed, so it is not necessary anymore? Why do we want to inherit the parents configuration now and didn't it before?

**Comment by cweitkamp** [comment]
To be honest, I have no clue. But what I can tell you is that SAT tool is complaining about it all the time. For example:
```
[WARNING] ~/openhab2-master/git/smarthome/bundles/model/org.eclipse.smarthome.model.persistence.tests/pom.xml:[29]
Avoid overriding a configuration inherited by the parent pom.
```

**Comment by wborn** [comment]
> We had those properties in the poms in the past, afair this derived from some skeletons that filled the MANIFEST based on those or whatever - probably linked to being used with maven-bundle-plugin as you suggest.

You can see these (now unused) properties being used with the maven-bundle-plugin in [POM files](https://github.com/openhab/openhab1-addons/blob/70150375fd96e22e860ff5708dfd75e15b960d32/poms/compiled/pom.xml#L51-L72) that are part of the openHAB "Initial project codebase" commit.

**Comment by kaikreuzer** [comment]
Oh hell, that was long ago! 😆
