### ISSUE TITLE
Tradfri binding - Gateway looses settings (Security Code)

### ISSUE THREAD

**Issue by lukicsl** [eclipse/smarthome#6063]
During power loss and/or on network loss (physical layer) on gateway and/or on openhab server following behaviour experienced:
Gateway is offline.
Restarting bundle does not help nor rebooting openhab server.
During restart of bundle log shows communication errors and the gateway goes from unknown to offline.

When in the settings of the gateway the Security Code is re-entered the Gateway goes to ONLINE.

It seems that the gateway looses the parameter Security Code.

**Comment by kaikreuzer** [comment]
> It seems that the gateway looses the parameter Security Code.

Hm, this is not what I read from the description (first post) at https://community.openhab.org/t/tradfri-binding-loses-connection-after-power-failure-gateway-reboot/47833.
Config parameters are definitely not lost, unless you try to add them on a thing that is defined in a file and you changed the configuration through Paper UI.

**Comment by kaikreuzer** [comment]
Ok, then I think we should close this here in favor of #6065.
