### ISSUE TITLE
Mapview rendering in Classic UI not 100% correct

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#608]
migrated from Bugzilla [#469244](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469244)
status UNCONFIRMED severity _normal_ in component _UI_ for _---_
Reported in version _0.8.0_ on platform _PC_
Assigned to: Project Inbox

On 2015-06-03 05:20:37 -0400, karel goderis wrote:

> On the classic UI, the generated MapView widget in a sitemap seems to be 2-3 pixels wider left and right than the frame where it embodied into, and the frame label text is rendered is a smaller font than the other items

**Comment by triller-telekom** [comment]
I don't know who or what fixed this issue, but it doesn't exist anymore. The mapview site nicely inside the frame and the title `Location` is as large as the title `Demo items`

See my Screenshot:

![mapview](https://cloud.githubusercontent.com/assets/26876013/25805215/328075c0-33ff-11e7-8b0a-0ecfd9f8241b.jpg)


@kaikreuzer @sjka Can you please close this issue?
