### ISSUE TITLE
UoM: channel type definition

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#6080]
The state part of the channel type definition allows to set a step size, a minimum value and a maximum value.

How are the step, min and max parameters for a channel type related to the chosen unit?

Does a min / max make sense anymore if we do not know if e.g. Celsius or Kelvin is used?

**Comment by kaikreuzer** [comment]
This is more or less the same issue as it has been documented in https://github.com/eclipse/smarthome/issues/5243:

> The precision in state descriptions is currently static regardless of the chosen measurement system

The state description (which include format/min/max/step) would need to become dependent on a specific unit.

**Comment by lolodomo** [comment]
In fact, isn't it exactly a duplicate of #5541 ?

**Comment by maggu2810** [comment]
Yes it is.
