### ISSUE TITLE
Paper UI: config parameter of type integer with options not working as expected

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#6082]
The Z-Wave binding is defining such configuration parameters:
```
      <parameter name="config_6_2" type="integer" groupName="configuration"
                 min="0" max="1439">
        <label>6: Auto report time</label>
        <description><![CDATA[
Sets the time interval when a sensor report is sent<br /><h1>Overview</h1><p>0 = Disable</p> <p>1 min - 1439 min = Auto report periodically</p>
        ]]></description>
        <default>0</default>
        <options>
          <option value="0">Disable</option>
        </options>
        <limitToOptions>false</limitToOptions>
</parameter>
```
When opening the configuration page in Paper UI, I can enter 60 as value for this parameter. But then when I click on the save button, I can see in Firefox that the REST API is called with 0 for this parameter config_6_2. So my entered value is ignored by Paper UI.

Maybe it is relative to a combination of options, limitToOptions property and min/max definition ?

**Comment by lolodomo** [comment]
@cdjackson for information.

**Comment by htreu** [comment]
Thanks @lolodomo for the report. This is a known bug, see #4014.

**Comment by htreu** [comment]
Closing as duplicate.

**Comment by lolodomo** [comment]
The other issue looks to me as a different issue. But maybe that is linked.

Is there someone working on a solution ? Because it is a major issue with the Z-Wave binding.

**Comment by htreu** [comment]
The current multi-select component in Paper UI is "very" broken, so this is not an easy fix. I would love to see an alternative to the current self-made component.
Fell free to fix the current solution or suggest alternatives.
