### ISSUE TITLE
Saving item doesn't save groups

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#609]
migrated from Bugzilla [#474568](https://bugs.eclipse.org/bugs/show_bug.cgi?id=474568)
status UNCONFIRMED severity _normal_ in component _REST/SSE_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Project Inbox

On 2015-08-09 17:54:46 -0400, Chris Jackson wrote:

> Saving groups though /rest/items/{item} doesn't seem to save the groups.  The SSE event is sent, and it's not updated there either. If I restart ESH then it is updated ok.

On 2015-08-12 02:42:43 -0400, Dennis Nobel wrote:

> Well it should work. So you mean the problem only is, that the SSE event does not contain the changed values?

**Comment by kaikreuzer** [comment]
@cdjackson Does this still apply?

**Comment by htreu** [comment]
another ping @cdjackson: can you confirm this issue or ping the maintainers to close please?

**Comment by cdjackson** [comment]
Sorry - I don't remember this at all - it was 2 years ago. I'd suggest to close.
