### ISSUE TITLE
postUpdate/sendCommand not synchronous in Rules

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#610]
migrated from Bugzilla [#478435](https://bugs.eclipse.org/bugs/show_bug.cgi?id=478435)
status UNCONFIRMED severity _normal_ in component _DSL_ for _---_
Reported in version _0.8.0_ on platform _PC_
Assigned to: Project Inbox

On 2015-09-25 12:47:15 -0400, karel goderis wrote:

> With the following simple rule, and with the Item TeslaScheduledDeparture holding a valid value (e.g. not NULL or UNDEF):
> 
> rule "Tesla - initiate variables rule"
> when 
>   System started
> then
>   TeslaScheduledDeparture.postUpdate(UnDefType.UNDEF)
>   logInfo("org.openhab","System Started : TeslaScheduledDeparture "+TeslaScheduledDeparture.state)
> end
> 
> the following is written to the logs:
> 
> 2015-09-25 18:40:12 [DEBUG] [.m.r.r.i.engine.RuleEngineImpl:267  ] - Executing startup rule 'Tesla - initiate variables rule'
> 2015-09-25 18:40:14 [INFO ] [o.e.s.model.script.org.openhab:48   ] - System Started : TeslaScheduledDeparture 2015-09-26T08:30:00
> 
> Does this async behaviour stem from the introduction of the safeCall()s? 
> 
> This is imho undesired behaviour, and leads to adverse effects in Rules. The workaround is to copy over Item.state(s) to locally defined variables at the beginning of each, to do the necessary processing, and at the exit of a rule, write back/postUpdate() any values to the Item.state(s)
> 
> Therefore, should lock()s be introduced on the ItemRegistry?

On 2015-09-26 03:40:32 -0400, Dennis Nobel wrote:

> > Does this async behaviour stem from the introduction of the safeCall()s? 
> 
> No, the safeCalls are executed synchronously. Only if a call takes longer than 10 seconds, the thread will continue to work.
> 
> ItÂ´s because a postUpdate is by definition asynchronously. The whole eventing system only allows asynchronous events.

On 2015-09-26 04:34:11 -0400, karel goderis wrote:

> mhh... do you think this would not lead to problems then? like, you are never sure to have the latest value of an Item when you call .state 
> 
> Is there a recommended approach then for Rules?
> 
> Karel

On 2015-09-26 05:52:39 -0400, Dennis Nobel wrote:

> It depends. Do you really want to query the state of an item directly after you have updated it in a rule? If you sent a command you either donÂ´t know how long it will take before the binding changes the state. The behavior - independent from the eventing system - is just asynchronously.
> 
> What is your concrete use case?
> 
> If you want to get informed that a value was changed you can use the newly introduced ItemStateChangedEvent. This event is sent AFTER an item state was updated.

On 2015-09-26 05:59:06 -0400, karel goderis wrote:

> I understand, but in this case the binding is not the limiting factor. it also happens with Items that are not bound to a binding.
> 
> ItemStateChangedEvent is not yet exposed to the ScriptEngine right?
> 
> K

On 2015-09-26 06:08:40 -0400, Dennis Nobel wrote:

> No itÂ´s not. But I think we donÂ´t need it there, as the Rule engine already has something like "Item MyItem changed" as a trigger. Even if the state of an Item might not be changed at this time, I think usually there is no problem, because you just work with the value from the update event inside the rule.

On 2015-09-26 07:19:08 -0400, karel goderis wrote:

> Ah - that I am afraid does not hold true. At least in my case - you do not only need the value that has effectively changed, but also the latest value of all the there Items, either in or out "Item changed" clauses.
> 
> You either have to build very long complex Rules, with a trigger for every possible variable/Item you need in the rule, or you make a bunch of rules that are less complex, acting on a single Item. In such a constellation, if you update the value of an Item in Rule A, you do need that exact value maybe in Rule B. 
> 
> I can tell you from the use case I have here (automatic charging and pre-heating rules for my Tesla), that these "glitches" are very annoying and troublesome. And that is only relatively simple use case imho
> 
> Karel

**Comment by htreu** [comment]
@kgoderis this issue is quite old, do you want to add some input to the discussion? Otherwise please let the maintainers know to close it, thanks.

**Comment by kgoderis** [comment]
@kaikreuzer Let's close this one. I am not sure it if is still relevant after such a long time
