### ISSUE TITLE
Version bumps / releases

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#612]
migrated from Bugzilla [#478597](https://bugs.eclipse.org/bugs/show_bug.cgi?id=478597)
status UNCONFIRMED severity _normal_ in component _Infrastructure_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Project Inbox

On 2015-09-29 04:06:10 -0400, Markus Rathgeb wrote:

> Eclipse SmartHome is a framework to build end user solutions on top.
> 
> If an "end user" would like to use that framework an do a release of his software, the software should not depend on a SNAPSHOT at all.
> 
> The ESH framework themselves is not bound (AFAIK) to any consumer release cycles and this is IMHO fine.
> 
> But I think it would be fine if we could produce releases from time to time so it could used as a reference for custom products.
> I cannot depend on 0.8-SNAPSHOT all the time.
> 
> I do not mean a 1.0 stable framework release without API breaks anymore...
> I just want to use a fixed reference in my sources.
> 
> Using custom repositories are possible, but this mean for every reference a new repository. That is not good.
> 
> If the process for a release is a long task for Eclipse products, I will ask, if we could bump the snapshot version from time to time without a official release.
> So building a release could build by the consumers.
> 
> I cannot build a 0.8.0, 0.8.1, ... release myself if Eclipse releases an official 0.8[.0] some time.

On 2015-09-29 04:39:35 -0400, Kai Kreuzer wrote:

> I agree that fixed releases would definitely help to have a reliable way to reference a  specific code base from within a solution.
> 
> Note that I am currently preparing the 0.8.0 release, see https://projects.eclipse.org/projects/iot.smarthome/releases/0.8.0/
> 
> But creating such minor releases is some work; I would not expect more than 2-3 each year.
> 
> Nonetheless, we could maybe check if we do more regular service releases, which should be a bit simpler (but still means work).
> We will have to check how much this can be automated (update version in sources, have documentation generated and published, adapt the build plans and download locations etc.)

On 2015-09-29 04:55:04 -0400, Kai Kreuzer wrote:

> Probably a better option than regular service releases might be to create milestones, e.g. 0.9.0M1, 0.9.0M2 etc. This seems to be possible without following the release process and it I think we also would not need to publish documentation on the website for such milestones.

On 2015-09-29 07:38:43 -0400, Markus Rathgeb wrote:

> > Probably a better option than regular service releases might be to create
> > milestones, e.g. 0.9.0M1, 0.9.0M2 etc. This seems to be possible without
> > following the release process and it I think we also would not need to
> > publish documentation on the website for such milestones.
> 
> That would be enough. I just want fixed states we could point to. If this are alphas, betas, release candidates, milestones, releases, ... does not matter for me.
> As long as it is fixed for a specific code base.
> 
> If the qualifier (M) is chosen correctly, Maven should handle this correctly, too.
> https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN400

On 2015-11-03 12:50:36 -0500, Markus Rathgeb wrote:

> I started doing it for myself:
> https://github.com/maggu2810/smarthome/commit/SHA: 04f8c9477fb896f77718a377f972f7f91876c639
> 
> But is there something we can do to get a solution upstream?

**Comment by maggu2810** [comment]
@kaikreuzer Any answer on my last comment?

**Comment by kaikreuzer** [comment]
If your script work smoothly for setting a specific version throughout the code, we could define this as the tooling for creating a (milestone/rc) release.

So what we then have to agree on is how to organize the (milestone) release process: How often do we do it? Do we also publish the documentation / JavaDoc for such milestones or are the Maven artifacts and the p2 repo enough?

**Comment by maggu2810** [comment]
> If your script work smoothly for setting a specific version throughout the code, we could define this as the tooling for creating a (milestone/rc) release.

I have used tycho-versions:set-version to set the version.

<code>mvn tycho-versions:set-version -DnewVersion=0.8.0.a$(git show -s --format=format:"%ct")</code>
maggu2810/smarthome@6014461bec85b51fca032780aa16d2eac65b59ef

We have to define the version scheme we want to use for the "milestones".

See also: https://maven.apache.org/ref/3.0.3/maven-artifact/apidocs/org/apache/maven/artifact/versioning/ComparableVersion.html

IMHO the Maven artifacts and the p2 repo would be enough.
I would like to use that mechanism to provide fixed references.
I would not do any documentation etc. so we get in trouble if something works for m1 and not for m2.
It should be just a reference for something "still in development".

**Comment by kaikreuzer** [comment]
In https://github.com/eclipse/smarthome/commit/04f8c9477fb896f77718a377f972f7f91876c639 you also did some sed commands - I would assume these are necessary, since the tycho-version plugin does not catch all occurrences of version numbers.

> We have to define the version scheme we want to use for the "milestones".

I would go for 0.8.0.mX, i.e. speaking of milestones as this is what we have in Github available as well.
Ok with the "no documentation" part.

**Comment by maggu2810** [comment]
The sed is used to change the groupId, this is not needed for the upstream project :wink: 

> I would go for 0.8.0.mX

Fine

**Comment by kaikreuzer** [comment]
Still, we might something similar for the version as well, see e.g. https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.paper/bower.json#L3

**Comment by maggu2810** [comment]
Or we could use a maven plugin that replace a magic string in files in the prepare-packaging phase...

**Comment by kaikreuzer** [comment]
Magic strings are often a problem if you want to use the code within the IDE from the sources - it is much nicer to have the version in there already and rather replace it when changing the code version.
I think there aren’t too many places. So we could possibly maintain a simple list of files that need to be considered when running a search/replace of the version. This together with the Tycho version plugin should do the job.

**Comment by maggu2810** [comment]
This string is also a magic one and does work in the IDE and could be replaced easily: <code>"version": "0.8.15",</code>

But it is up to you. Using a script, that replaces the version in the files and does start the Tycho version plugin is fine, too.

**Comment by maggu2810** [comment]
In reply to https://github.com/eclipse/smarthome/pull/456#issuecomment-164246245

> Ok, I have just released a new ESH stable, so let's adapt openHAB accordingly. 

Why don't we use a milestone version number for such stuff?

As I can't believe that such a milestone will be bug free the hardcoded version string mismatches could be seen as a bug in the first milestone.

I could write a script (what do you prefer, Java, Python, bash) that replace the version string in special files (hard coded or config file).
But I would like to see this solved.

What can I do?

**Comment by kaikreuzer** [comment]
> Why don't we use a milestone version number for such stuff?

Looking at that case, we might actually better off with "b" stable releases here as we might end up with milestone mXXX one day... Probably the milestones should be rather feature-oriented, which makes sense to track on Github (while "b" builds would not be reflected in Github Issues).

> But I would like to see this solved.
Me too!

> What can I do? I could write a script 

Exactly this! I planned to do that, but didn't yet find the time. Bash would be fine for me, assuming that anyhow only a few committers will use it and none of them is using Windows...

Besides the script, we would have to define the process of doing such a release. What is needed is:
- run the script
- run a local build
- create a git tag
- commit and push (as a PR or directly to the main repo?)
- trigger Hudson
- run the script again and change the version back to snapshot (will these actually ever be considered to be newer than a "b" release...? Probably not, right?)
- commit and push the changes

Does that make sense? Or shall we avoid committing the version changes at all and have the script executed by a special Hudson build, which takes b/mXX as a parameter, checks out the sources from git and runs the script over the checked out files before building them?

**Comment by maggu2810** [comment]
I assume that origin is the upstream remote name.
The script should use the current HEAD as reference

run the script with one arguments: a number that defines the "b" number

The script should
* commit-base = save current SHA (git rev-parse HEAD)
* git clean -x -d -f
* read current version (e.g. 0.8.0-SNAPSHOT) from pom file
* generate new version number (e.g. remove SNAPSHOT and set ".b<nr>")
* change the version number strings in some files (list hard coded in the script) that contains the version as a text (e.g. a web page)
* use the tycho version goal to set the version in the pom and manifest files
* run a local build
* git add . && git commit -s -m "[beta] set version to <new-version>"
* set tag to beta - new version (e.g. beta-0.8.0.b3)
* push tag to remote (e.g. "origin")
* reset local copy to "commit-base"

Then we could trigger the build on hudson manually that should do the deploy to some repo.

Ok?

**Comment by kaikreuzer** [comment]
> a number that defines the "b" number

Why not directly allow "b7" or "m1" or "rc2" as parameter? Then we can use it for all such cases directly without changes.

> Then we could trigger the build on hudson manually 

What would we do afterwards? Since you have reset your copy to "commit-base" there is no changeset that could be pushed to origin - but we have to change the version back again there.

What do you think is bad about the "non-git" script that could simply be run on Hudson without having to add any changesets to the repo?

**Comment by maggu2810** [comment]
> Why not directly allow "b7" or "m1" or "rc2" as parameter?

ok

I am more familiar with Jenkins, don't know if all stuff I done with Jenkins could be done with Hudson, too.
For Jenkins I would create a parameterized Job.
Params:
* commit id that should be used as base
* version postfix (e.g. b7, m1, ...)

Then we could modify the above steps:
* clean checkout (no changes in working copy) of "commit-id"
* read current version (e.g. 0.8.0-SNAPSHOT) from pom file
* generate new version number using "postfix" (e.g. remove SNAPSHOT and set "postfix")
* change the version number strings in some files (list hard coded in the script) that contains the version as a text (e.g. a web page)
* use the tycho version goal to set the version in the pom and manifest files
* run a build, to see if all is fine
* git add . && git commit -s -m "[reference-release] set version to <new-version>"
* set tag to new version (e.g. 0.8.0.b3)
* push tag to remote (e.g. "origin")
* start a new maven with deploy

I think for such reference releases we do not need to track the changes (set to 0.8.0.b3, set back to 0.8.0-SNAPSHOT) in the master branch, a tag should be enough.

**Comment by kaikreuzer** [comment]
> I am more familiar with Jenkins, don't know if all stuff I done with Jenkins could be done with Hudson, too.

Can you actually log into the ESH Hudson at https://hudson.eclipse.org/smarthome/ ? If not, we should add you as an admin there.

> git add . && git commit -s -m "[reference-release] set version to "
> set tag to new version (e.g. 0.8.0.b3)
> push tag to remote (e.g. "origin")

I am probably not familiar enough with git, but wouldn't these steps create a detached HEAD and thus HEAD is not on the master branch anymore?

**Comment by maggu2810** [comment]
I can login on the Hudson.

As long as we create a tag that points to that commit, we are not in a detached head.
See: https://git-scm.com/docs/git-checkout#_detached_head
```text
3. creates a new tag foo, which refers to commit f, leaving HEAD detached.
```

**Comment by maggu2810** [comment]
I will close this one, after the first one has been created successful and is available in the maven repo (see https://github.com/eclipse/smarthome/pull/766#issuecomment-166287130).

**Comment by htreu** [comment]
> after the first one has been created successful and is available in the maven repo

@maggu2810 does the condition hold true by now? can this be closed or do we need to discuss this further?

**Comment by maggu2810** [comment]
Nothing to discuss anymore.
