### ISSUE TITLE
ClassicIconProvider : introduce rounding to generate icons

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#613]
migrated from Bugzilla [#480284](https://bugs.eclipse.org/bugs/show_bug.cgi?id=480284)
status UNCONFIRMED severity *normal* in component *UI* for *---*
Reported in version *0.8.0* on platform *PC*
Assigned to: Project Inbox

On 2015-10-21 05:29:53 -0400, karel goderis wrote:

> Hi all,
> Not really a nasty bug, what could be a suggested way forward in the following case?
> 
> In .sitemap
> 
> Slider item=BathroomKidsSonosVolume  label="Sonos - Volume [%.1f %%]" icon="volume"
> 
> (BathroomKidsSonosVolume  is of Dimmer Type)
> 
> This is rendered as follows by the UI, with the Dimmer set at "50%":
> 
> <img src="../icon/volume?format=%format%&amp;state=0.50000000" width="29" height="29" class="iFull">
> 
> Since the embedded icon set is rather limited, I have copied over all the icons to the /icons/classic folder. That folder obviously does not contain a variation of the "volume.png" icon for each possible % state. 
> 
> Hence the question, how to proceed is such a case?
>  - choose a different icon, with no gradation?
>  - extend ClassicIconProvider to round states to the nearest available "png" state?
>  - ...
> 
> Tx
> Karel

**Comment by clinique** [comment]
Isn't this already what AbstractResourceIconProvider does ?
In line #86, I see that it decrements the searched value until a match is found.

https://github.com/eclipse/smarthome/blob/713f9477b9ea49c9f6cf03e8b2af9a8d2d6793c3/bundles/ui/org.eclipse.smarthome.ui.icon/src/main/java/org/eclipse/smarthome/ui/icon/AbstractResourceIconProvider.java

**Comment by kaikreuzer** [comment]
Yes, you are right, this is already implemented since a while.
