### ISSUE TITLE
Paper UI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#615]
migrated from Bugzilla [#478812](https://bugs.eclipse.org/bugs/show_bug.cgi?id=478812)
status NEW severity *normal* in component *UI* for *---*
Reported in version *unspecified* on platform *PC*
Assigned to: Kai Kreuzer

On 2015-10-01 10:05:49 -0400, Kai Kreuzer wrote:

> The Paper UI (https://bugs.eclipse.org/bugs/show_bug.cgi?id=440012) should be moved from github.com/openhab to Eclipse.
> 
> Pull request https://github.com/eclipse/smarthome/pull/478 has been created for it.

**Comment by maggu2810** [comment]
Already merged.
