### ISSUE TITLE
Paper UI: select a location in the map

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#6164]
In Paper UI, it would be cool for a location setting to be able to select the location from the map rather than having the map only to display the position entered as a lat/lon.
Would it be possible ?

**Comment by kaikreuzer** [comment]
I actually believed that this is already possible, but you are right, it isn't working :-(

I consider that a regression as it was specified to work exactly this way in https://github.com/eclipse/smarthome/issues/3709.

@htreu Could you have a look?

**Comment by htreu** [comment]
Please test again with the current master. This was just recently fixed with by #6131.

**Comment by htreu** [comment]
Don't forget to rebuild Paper UI via maven or `Paper UI Setup.launch`.
