### ISSUE TITLE
Having multiple *.items configuration files results in duplicate item binding processing.

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#617]
migrated from Bugzilla [#423465](https://bugs.eclipse.org/bugs/show_bug.cgi?id=423465)
status NEW severity _normal_ in component _DSL_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Project Inbox

On 2013-12-06 12:58:15 -0500, Kai Kreuzer wrote:

> Moved from https://code.google.com/p/openhab/issues/detail?id=173

On 2015-04-27 10:54:12 -0400, Dennis Nobel wrote:

> Not sure if this might be solved already because of some GenericItemProvider refactorings?

**Comment by triller-telekom** [comment]
This issue still applies for the current version of ESH, see:

`demo.items` was there before and I added `test.items`. After adding `test.items` the `GenericItemProvider` read the items from the `demo.items` file again.

```
15:07:36.107 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:110] - Loading model 'test.items'
15:07:36.107 DEBUG o.e.s.m.i.i.GenericItemProvider[:143] - Read items from model 'test.items'
15:07:36.107 DEBUG o.e.s.m.i.i.GenericItemProvider[:164] - Processing binding configs for items from model 'test.items'
15:07:41.473 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:130] - Refreshing model 'test.items'
15:07:41.474 DEBUG o.e.s.m.i.i.GenericItemProvider[:143] - Read items from model 'demo.items'
15:07:41.474 DEBUG o.e.s.m.i.i.GenericItemProvider[:143] - Read items from model 'test.items'
```
