### ISSUE TITLE
Improving the UX of the designer (buttons, preferences, wizards, dsl assistence,...)

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#618]
migrated from Bugzilla [#423500](https://bugs.eclipse.org/bugs/show_bug.cgi?id=423500)
status NEW severity _enhancement_ in component _Designer_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Project Inbox

On 2013-12-07 15:33:08 -0500, Kai Kreuzer wrote:

> Moved from https://code.google.com/p/openhab/issues/detail?id=505.
> 
> Issue should include the following:
> - link button to link editor to "Configurations" tree view
> - save / save all buttons
> - menu button to get the file history
> - remove unused preferences from the preferences view
> - remove unused commands from the context menu
> - add "new file" commands
> - load new / changed files
> - multiple projects for "Configurations" view
> - wizard for adding a new configurations project
> - new "Browser View" based on javaFX webView (webkit based, needs java7u2x?)
> - Switch to eclipse4 with compatibility layer for the xtext editors, which means that the current "Configurations view" has to be reimplemented, because it uses the "common navigator framework", which is not yet ported to e4.

On 2014-01-02 10:35:51 -0500, Matthias Becker wrote:

> Regarding the e4-migration:
> It seams that there is a way to use the CMF-View also there.
> See: http://dirksmetric.wordpress.com/2012/08/01/tutorial-eclipse-rcp-e4-with-3-x-views-like-project-explorer-properties-etc/

**Comment by haltmann** [comment]
Hi,

I saw that stuff and it instantly filled me with energy and hope, just take a look here <http://amazing.prophecysecondcoming.com/e4jvjivj>

All the best, herbert.altmann@heal-it.info

**Comment by htreu** [comment]
The designer is not actively maintained anymore, please see https://github.com/eclipse/smarthome/issues/4139#issuecomment-325333205.

@sjka please close.
