### ISSUE TITLE
Creates file paths with double slashes

### ISSUE THREAD

**Issue by pkriens** [eclipse/smarthome#6183]
https://github.com/eclipse/smarthome/blob/9b92971e8c7e3226850ea9a3c8b118e271d1b193/bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/SyntheticBundleInstaller.java#L337 and https://github.com/eclipse/smarthome/blob/9b92971e8c7e3226850ea9a3c8b118e271d1b193/bundles/test/org.eclipse.smarthome.test/src/main/groovy/org/eclipse/smarthome/test/SyntheticBundleInstaller.java#L389 construct a path inside the bundle to access a resource. Both lines create a resource path that has 2 '/' characters since the `bundlePath` already ends with a slash. 
We found this by running on Apache Felix where this resulted in not finding the resource. Seems to indicate all tests are done on Equinox?

**Comment by kaikreuzer** [comment]
Yes, tests are executed through Tycho, which uses Equinox.
Can you come up with a PR that fixes this issue?
