### ISSUE TITLE
Xtext bump

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#6199]
Hi,

I just tried to use Xtext 2.14.0 for ESH (https://www.eclipse.org/Xtext/releasenotes.html).

What I have done so far:
* changed the ESH pom.xml file to use Xtext 2.14.0 (need to check which bundles are used on compiling because of p2 targetplatform)
* changed the ESH Karaf features for Xtext 2.14.0
* build ESH
* used my `smarthome-packaging-sample-karaf` to build a Karaf 4.2.1 based distribution using ESH with Xtext 2.14.0
* added the demo files (items, rules, things, ...) from the official ESH demo distribution
* inspect the log
* ...

It seems to be working...

What's missing:
* Eclipse IDE related stuff and p2 targetplatform

Does it make sense to proceed or is that bump a no go from product owner side of other ESH based products?

**Comment by maggu2810** [comment]
I updated also the targetplatform and the Oomph setup file.

After that I also tried to install a new Photon Eclipse IDE and using the changed setup file and the Eclipse Installer. I don't know if I had to iterate the "generate the model" and "clean + build" projects more then once, but IIRC users reported already that this does not work out of the box sometimes.

Also the Maven build succeeds with test execution.

**Comment by maggu2810** [comment]
A diff can be found here:
https://github.com/eclipse/smarthome/compare/master...maggu2810:xtext-bump?expand=1

The Manifest files has been changed by the Eclipse IDE or the model generation.

**Comment by maggu2810** [comment]
After the bump I can compile ESH with JDK 9 (keep in mind that the pom still forces source and target 1.8). Without the Xtext bump compilation with JDK 9 does not work.

* :ballot_box_with_check: `mvn clean install -DskipChecks=true -DskipTests=true`
* :negative_squared_cross_mark: `mvn clean install -DskipChecks=true`: (first) failed test: `I18nConfigOptionsProviderTest.testRegion:55`
* :negative_squared_cross_mark: `mvn clean install -DskipTests=true`: SAT seems not to be ready for Java 9.

**Comment by kaikreuzer** [comment]
Sound great, thanks for your efforts!

> SAT seems not to be ready for Java 9

@dstivanov That should probably be addressed asap - shall we enter an issue for it?

**Comment by lpapazow** [comment]
@maggu2810 I am currently working on [the issue about SAT supporting java9](https://github.com/openhab/static-code-analysis/issues/325).

I changed the `esh.java.version` property to 1.9 and my `JAVA_HOME` to point to Java9. However, when I try to run `mvn clean verify` in smarthome I get the error:

>[ERROR] Failed to execute goal org.apache.felix:maven-scr-plugin:1.24.0:scr (generate-scr-scrdescriptor) on project org.eclipse.smarthome.core: C:\oh2\git\smarthome\bundles\core\org.eclipse.smarthome.core\src\main\java\org\eclipse\smarthome\core\auth\Authentication.java : Unable to scan class files: org.eclipse.smarthome.core.auth.Authentication (Class file format probably not supported by ASM ?): IllegalArgumentException


Running `mvn clean compile` works fine though. In your [comment](https://github.com/eclipse/smarthome/issues/6199#issuecomment-421265410) you said that you can compile ESH with java9. I was wondering if you were able to complete the verify phase successfully with java9, or just the compile phase.

**Comment by maggu2810** [comment]
I tried `mvn clean install` only (without tests and SAT) and I kept source and target to 1.8
Didn't try `verify`.
