### ISSUE TITLE
Designer doesn't mark duplicate rule names as errors

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#620]
migrated from Bugzilla [#423511](https://bugs.eclipse.org/bugs/show_bug.cgi?id=423511)
status NEW severity _enhancement_ in component _Designer_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Project Inbox

On 2013-12-07 16:08:58 -0500, Kai Kreuzer wrote:

> Migrated from https://code.google.com/p/openhab/issues/detail?id=375

On 2014-03-03 07:14:47 -0500, Oliver Libutzki wrote:

> This seems to be a problem in general. It's possible to define item and sitemap duplicates as well.

On 2014-06-04 12:12:24 -0400, Kai Kreuzer wrote:

> **\* Bug 436533 has been marked as a duplicate of this bug. ***

**Comment by htreu** [comment]
The designer is not actively maintained anymore, please see https://github.com/eclipse/smarthome/issues/4139#issuecomment-325333205.

@sjka please close.
