### ISSUE TITLE
Pressing light switch causes embedded ip cam video to disappear

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#621]
migrated from Bugzilla [#423514](https://bugs.eclipse.org/bugs/show_bug.cgi?id=423514)
status NEW severity _normal_ in component _UI_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Project Inbox

On 2013-12-07 17:14:24 -0500, Kai Kreuzer wrote:

> Migrated from https://code.google.com/p/openhab/issues/detail?id=298

**Comment by triller-telekom** [comment]
This issue is about the old classicui interface and either has been fixed or won't be fixed in favor to the new basicui.

@kaikreuzer @sjka Can you please close this issue?
