### ISSUE TITLE
Color picker opened by direct link doesn't work

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#622]
migrated from Bugzilla [#423518](https://bugs.eclipse.org/bugs/show_bug.cgi?id=423518)
status NEW severity _normal_ in component _UI_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Project Inbox

On 2013-12-07 17:26:32 -0500, Kai Kreuzer wrote:

> Migrated from https://code.google.com/p/openhab/issues/detail?id=361

**Comment by triller-telekom** [comment]
If I leave the Colorpicker open in basicui and restart ESH the browser reestablishes the link and closes the Colorpicker automatically now. If I then set a color via `smarthome update DemoColor 50,50,50` and open the Colorpicker it shows these values. If I leave it open and send a different value via the console it updates immediately.

@kaikreuzer @sjka This bug can be closed.

**Comment by kaikreuzer** [comment]
This issue is about the Classic UI, not the Basic UI.
But I would tend to close it as a won't fix as it is imho a low prio and the Basic UI can be used as a replacement.
