### ISSUE TITLE
IDE setup instructions: Photon product

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#6225]
The "Product Version" shown on the IDE setup is "Oxygen".
https://www.eclipse.org/smarthome/documentation/development/ide.html

Should be changed to "Photon".

**Comment by maggu2810** [comment]
@kaikreuzer All the screenshots have been created on a MAC. Are you able to update the image?

**Comment by kaikreuzer** [comment]
@htreu is using a Mac as well - I asked him for this favor 😇

**Comment by htreu** [comment]
I will update the docs with new screenshots, hang on.
