### ISSUE TITLE
Add property to Text widget to allow optional editing

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#623]
migrated from Bugzilla [#423525](https://bugs.eclipse.org/bugs/show_bug.cgi?id=423525)
status NEW severity _enhancement_ in component _UI_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Project Inbox

On 2013-12-08 07:05:00 -0500, Kai Kreuzer wrote:

> Migrated from https://code.google.com/p/openhab/issues/detail?id=356

**Comment by htreu** [comment]
@kaikreuzer I guess this is already implemented in PaperUI, please close.
