### ISSUE TITLE
Eclipse IDE: 2018-09

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#6249]
The Eclipse IDE 2018-09 has been released.
Should we consider an update (as soon as all that annoying Xtext bump related stuff is solved)?

**Comment by kaikreuzer** [comment]
Better not for now, see https://twitter.com/henningtreu/status/1042694541390880768.

Let's wait for @htreu's change to the setup file and see whether that works as expected.

**Comment by htreu** [comment]
I'm running 2018-09 for nearly a week now w/o any issues. But with the new rolling release cycle with a new version every 13 weeks my suggestion is to stay on photon for "a while" and update "later". Maybe for us updating the official IDE once a year is enough?

**Comment by kaikreuzer** [comment]
I am also running 2018-09 and it works, so I guess, this issue can be closed.
I am not sure on what should be our strategy for future updates, though - having to test and adapt the IDE setup every 3 months sounds tedious to me; but we probably cannot avoid it and there'll always be people using the latest release (even if we might stay something different in the docs).
So maybe wait and see how the next round behaves...

**Comment by maggu2810** [comment]
Using 2018-09 I cannot edit the ESH formatter settings anymore.
If I press on "Edit..." no window is opened.

Can you confirm?

**Comment by htreu** [comment]
Confirmed.
