### ISSUE TITLE
LSP does not work when different GSON versions are present

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#6250]
Now this is nasty. As we know from https://github.com/eclipse/smarthome/issues/4440, we have situations where there are multiple GSON bundle versions are present - ESH core requires 2.3.1 and thus this comes with JAX-RS etc., while LSP required 2.7, which so far was no problem to additionally install.

But with the LSP 0.4.1 upgrade, the `org.eclipse.lsp4j` bundle has an import of `com.google.gson.internal.bind` without specifying a version constraint. This leads to being resolved against 2.3.1, while other packages are resolved against 2.7.0:
```
osgi.wiring.package; (&(osgi.wiring.package=com.google.gson)(&(version>=2.7.0)(!(version>=3.0.0)))) resolved by:
   osgi.wiring.package; com.google.gson 2.7.0 from com.google.gson_2.7.0 [22]
osgi.wiring.package; (&(osgi.wiring.package=com.google.gson.annotations)(&(version>=2.7.0)(!(version>=3.0.0)))) resolved by:
   osgi.wiring.package; com.google.gson.annotations 2.7.0 from com.google.gson_2.7.0 [22]
osgi.wiring.package; (osgi.wiring.package=com.google.gson.internal.bind) resolved by:
   osgi.wiring.package; com.google.gson.internal.bind 2.3.1 from com.google.gson_2.3.1 [21]
osgi.wiring.package; (&(osgi.wiring.package=com.google.gson.reflect)(&(version>=2.7.0)(!(version>=3.0.0)))) resolved by:
   osgi.wiring.package; com.google.gson.reflect 2.7.0 from com.google.gson_2.7.0 [22]
osgi.wiring.package; (&(osgi.wiring.package=com.google.gson.stream)(&(version>=2.7.0)(!(version>=3.0.0)))) resolved by:
   osgi.wiring.package; com.google.gson.stream 2.7.0 from com.google.gson_2.7.0 [22]
```
As a result, LSP fails at runtime.

What can we do about it? I can try to exclude 2.3.1 from openHAB, but as it isn't a singleton bundle, I am not sure if that works out easily...

**Comment by kaikreuzer** [comment]
> I can try to exclude 2.3.1 from openHAB

@maggu2810 Could that possibly be achieved by changing [this line](https://github.com/eclipse/smarthome/blob/master/features/karaf/esh-tp/src/main/feature/feature.xml#L34) to 2.7?

This should prevent 2.3.1 being installed first and if nobody explicitly requires something <2.7, this should be fine, wdyt?

**Comment by kaikreuzer** [comment]
It gets even worse: If I remove 2.3.1 from the openHAB distro, `org.eclipse.lsp4j` does not resolve at all anymore. The [GSON 2.7 from Maven Central](https://mvnrepository.com/artifact/com.google.code.gson/gson/2.7) does not export the `com.google.gson.internal.bind` package and this is most likely the reason why this package is resolved from 2.3.1 instead of 2.7 in the first place.
Only the GSON 2.7 from Eclipse Orbit exports that package (that's why everything looks ok in the ESH IDE).

**Comment by maggu2810** [comment]
So, Eclipse builds its own version of GSON with more relaxed exported packages? That's again very annoying.

**Comment by maggu2810** [comment]
We should not rely on such "special" versions that export packages that are not exported on the official one.
As a "short term" solution I could add the GSON 2.7 bundle from Eclipse Orbit to a Maven Repository and we could use that for the moment.
WDYT?

**Comment by kaikreuzer** [comment]
> We should not rely on such "special" versions that export packages that are not exported on the official one.

I agree, but it is not "us", but LSP4j that has that dependency.

> As a "short term" solution I could add the GSON 2.7 bundle from Eclipse Orbit to a Maven Repository and we could use that for the moment.

That's the only solution that would come to my mind, so unless anyone has a better one, let's go for it.

**Comment by htreu** [comment]
+1 for going the Orbit -> custom maven repo route.

**Comment by kaikreuzer** [comment]
will test right away, thanks!

**Comment by kaikreuzer** [comment]
Seems to work nicely!
Do you want to leave it there? It might make sense to change the group id to `de.maggu2810.p2redist`, so that it is inline with https://github.com/eclipse/smarthome/blob/master/features/karaf/esh-tp/src/main/feature/feature.xml#L187-L188, wdyt?

**Comment by maggu2810** [comment]
The group id and artifact id is taken from the POM included in the JAR.

**Comment by maggu2810** [comment]
The group id and artifact id is taken from the POM included in the JAR.
I assume it makes sense to use that group ID for bundles that are placed at Orbit's p2.
So it can be used for temporary availability on the Maven repo.

We should try to move away from them (and provide patch to 3rd party products like LSP) and swithch to the upstream provided once.

**Comment by kaikreuzer** [comment]
https://github.com/openhab/openhab-core/pull/403 solves this now, so I'm closing the issue.

**Comment by maggu2810** [comment]
> while LSP required 2.7

> But with the LSP 0.4.1 upgrade, the `org.eclipse.lsp4j` bundle has an import of `com.google.gson.internal.bind` without specifying a version constraint.

How can the issue been resolved (not worked around) in openHAB?
If we already know that `mvn:com.google.code.gson/gson/2.7` does not fulfill the requirements because it does not export the internal packages, then the feature definition is not correct.

``xml
  <feature name="esh.tp-lsp4j" description="Eclipse LSP4J" version="0.10.0-SNAPSHOT">
    <capability>esh.tp;feature=lsp4j;version=0.4.1</capability>
    <feature dependency="true">esh.tp-xtext</feature>
    <bundle dependency="true">mvn:com.google.code.gson/gson/2.7</bundle>

    <bundle dependency="true">mvn:org.eclipse.lsp4j/org.eclipse.lsp4j/0.4.1</bundle>
    <bundle dependency="true">mvn:org.eclipse.lsp4j/org.eclipse.lsp4j.jsonrpc/0.4.1</bundle>
  </feature>
```

Shouldn't we change `mvn:com.google.code.gson/gson/2.7` to `mvn:org.eclipse.orbit.bundles/com.google.gson/2.7.0.v20170129-0911` here?

**Comment by kaikreuzer** [comment]
Sure, you are clearly right, this should be addressed in the ESH feature definition.

**Comment by maggu2810** [comment]
> @maggu2810 Could that possibly be achieved by changing [this line](https://github.com/eclipse/smarthome/blob/master/features/karaf/esh-tp/src/main/feature/feature.xml#L34) to 2.7?

> This should prevent 2.3.1 being installed first and if nobody explicitly requires something <2.7, this should be fine, wdyt?

It is not the real cause of the problem as we learned, but IMHO things could be simpler if we use one Gson version at all and not this in the one case and that in the other...

Do you still agree to change 2.3.1 to 2.7.0?

We could switch to `mvn:org.eclipse.orbit.bundles/com.google.gson/2.7.0.v20170129-0911` in both cases.

**Comment by kaikreuzer** [comment]
> Do you still agree to change 2.3.1 to 2.7.0?

No, we should only change the LSP Karaf feature to require 2.7.
The question about our minimal requirement is discussed in #4440 and so far it is 2.2.4 for the core framework.

**Comment by maggu2810** [comment]
Perhaps I misinterpret https://github.com/eclipse/smarthome/issues/6250#issuecomment-423477913
My reading has been that you suggested to bump 2.3.1 to 2.7.0 for the whole ESH target platform (in Karaf).

**Comment by kaikreuzer** [comment]
Bit undecided there, probably again because I am not 100% sure of how Karaf works here.
If there is a way to only have 2.7 installed if a solution includes LSP (as a base feature) and keep that line, I would keep it. If it causes 2.3.1 being installed, this might be an issue though.

**Comment by maggu2810** [comment]
See #6259
