### ISSUE TITLE
GroupFunction name EQUAL or EQUALITY?

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#6257]
Found this in my log:
```
12:46:50.961 [INFO ] [smarthome.event.ItemStateChangedEvent] - Sun_Elevation changed from 32.911390868338536 to 32.82965662193761
12:46:51.096 [INFO ] [smarthome.event.ItemStateChangedEvent] - Moon_Azimuth changed from 54.55240850571265 to 54.80388014618922
12:46:51.099 [INFO ] [smarthome.event.ItemStateChangedEvent] - Moon_Elevation changed from -36.231753744300484 to -36.1101579166758
12:46:52.752 [ERROR] [re.internal.items.GroupFunctionHelper] - Unknown group function 'EQUALITY'. Using Equality instead.
12:46:54.390 [ERROR] [re.internal.items.GroupFunctionHelper] - Unknown group function 'EQUALITY'. Using Equality instead.
12:46:56.025 [ERROR] [re.internal.items.GroupFunctionHelper] - Unknown group function 'EQUALITY'. Using Equality instead.
```

Unfortunately, there is no stacktrace provided, so I cannot see where this might come from.

In `GroupFunctionHelper` I can see that only the name `EQUAL` is expected there, while [our documentation](https://github.com/eclipse/smarthome/blob/master/docs/documentation/concepts/items.md#derive-group-state-from-member-items) talks about `EQUALITY`. Something does not seem to be consistent here...

**Comment by maggu2810** [comment]
Hm, I don't know which one should be preferred `EQUAL` or `EQUALITY`.
But it must be consistent.

Any objections?

**Comment by htreu** [comment]
My suggestion is to just update the docs to EQUAL as the code and all "working" installations are using it. Installations using EQUALITY will see the warning nonetheless.

**Comment by htreu** [comment]
Also the xtext definition says `EQUAL`.

**Comment by htreu** [comment]
Unfortunately we accept `EQUAL` as a valid group function string, but when GroupItem is serialized with the default group function `Equality` we are not able to deserialize it back w/o the warning.
I added a commit to the proposed fix which accepts both `EQUAL` and `EQUALITY` in the GroupFunctionHelper.
