### ISSUE TITLE
[OneWire] Multiple error entries during OpenHab shutdown

### ISSUE THREAD

**Issue by mgwoj** [eclipse/smarthome#6265]
With the latest version of the OneWire binding, I got several (1000+) entries in the log file during system shutdown.

> [WARN ] [.core.thing.binding.BaseThingHandler] - Handler OwserverBridgeHandler tried updating the thing status although the handler was already disposed.

The issue is that amount of log entries caused the log to rotate.

**Comment by htreu** [comment]
@mgwoj please provide some more debug output from the logs. Set the log level of `org.eclipse.smarthome.binding.onewire` to `DEBUG` and paste the logs here. You may shorten them of cause. It would be interesting to see what happened right before shutdown.
Thanks.

**Comment by htreu** [comment]
Thanks for the feedback. I checked the code and couldn't find any suspicious lifecycle issues. I will close here. @mgwoj in case you see this again, please reopen.
