### ISSUE TITLE
REST interface for time series from persistence services

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#627]
migrated from Bugzilla [#423547](https://bugs.eclipse.org/bugs/show_bug.cgi?id=423547)
status NEW severity *enhancement* in component *REST/SSE* for *---*
Reported in version *unspecified* on platform *All*
Assigned to: Project Inbox

On 2013-12-08 15:14:37 -0500, Kai Kreuzer wrote:

> Migrated from https://code.google.com/p/openhab/issues/detail?id=419

On 2015-03-22 09:32:47 -0400, Chris Jackson wrote:

> A few thoughts on this from my side...
> 
> Currently in HABmin, I have a couple of interfaces related to time series data - the time series itself, but also an interface to get the list of persistence services. In openhab1 version of HABmin, I also had an interface to get the list of items that were being persisted through a specific interface so the user didn't have to guess what items went with each service (I've not tried to do this in OH2, but we do need some way to link services and items)....
> 
> So, to cover what I have now in OH2 HABmin -:
> GET /rest/habmin/persistence - returns a list of persistence services. This list is provided to the user when they are making charts
> GET /rest/habmin/persistence/%svc%/%item% - returns the data for item, from svc persistence service.
> 
> The time series itself also supports parameters starttime, endtime, pagelength and page (which should be self explanatory). Times are in milliseconds (standard unix epoch).
> 
> I did think about adding the persistence stores for each item into the itemshelper (I forget the exact class name) - currently this adds groups, and maybe some other stuff, but it's not easy to get hold of persistence information at this point. I think it's needed somewhere so that we can link items and services together (and somewhere I'd also like to see this writable as well - but that's another topic).

On 2015-05-29 04:43:09 -0400, Greg EVA wrote:

> A couple of my thoughts...
> 
> 1) it would be interesting in the REST request to be able to specify the data interval requested (or appreciated) - this way if a chart/trend only needs data every 10 minutes, yet the data is stored every 1 minute, their is no excess data transfer or excess data with which the client needs to deal with (and perhaps discard).
> 
> 2) one issue which comes up with time-series data is that their may not be data on the start/end times, in a trend this could show no data for a good part of the chart, or incorrectly drawing a line up from zero at the start of the chart to the first value.  This "problem" only gets worse with on-change type of persistence as there may not even be any data for the selected period.  So! It could be nice to start and end the returned data-series with the first/last values which are perhaps outside of the requested time frame.
> 
> These ideas may deviate from pure core functionality, but would likely simplify things for people working with the data which will be requested.

On 2015-05-29 05:16:26 -0400, Chris Jackson wrote:

> 1) I don't think this is a good idea. I tried this originally in HABmin, and it's not especially fast. It was quicker to return all data and let the client sort it out - remember that a lot of people are running on low powered machines (eg RPi) and sub sampling data on the server was slow. Doing this on the PC end was generally lot quicker.
> 
> There is however a trade to be made as it will get to a point somewhere where the above isn't true, but this point is variable as it depends on how often data is logged, which varies for different items.  However, doing the sub sampling in real-time isn't (I think) the right way. I have a bundle mostly coded which gathers metrics - similar to what RRD does. This creates min/max/avg data every 'period' and stores it separately. It is IMHO better to do this, and then if the client asks for a large duration of data, to return the filtered data (eg using a 3 hour statistic) rather than to try and down sample data on the fly. As the user zooms in, the higher resolution data can be selected. The additional storage is minimal, and this provides the user with a much better experience.
> 
> 2) The HABmin interface does this already. It gets the previous value from before the start time and returns this with the data. The end time is up to the client to propagate the chart.
> 
> I have a PR half done to move the current HABmin persistence interface across to ESH as an initial solution to this issue - it's just not quite got to the top of the list...

**Comment by cdjackson** [comment]
I guess this can be closed?

**Comment by kaikreuzer** [comment]
Yep.
FTR: Implemented in https://github.com/eclipse/smarthome/pull/549
