### ISSUE TITLE
[basic ui] Favicon on welcome page not working

### ISSUE THREAD

**Issue by CWempe** [eclipse/smarthome#6270]
I just discovered that the favicon does not work for the welkome page of basic ui.

![image](https://user-images.githubusercontent.com/1270359/46008735-dd5cd280-c0bd-11e8-88f7-95dd76033d16.png)

As soon as I ópen a sitemap it works.

![image](https://user-images.githubusercontent.com/1270359/46009314-717b6980-c0bf-11e8-8e10-399116e4fa52.png)

When I look into the source code of the page I see that the path of the favicon is incorrect.

```
<!doctype html>
<html class=" ui-icons-enabled  page-welcome-sitemaps page-static">
	<head>
		<title>BasicUI</title>
[..]
		<link rel="shortcut icon" href="images/favicon.ico" />
```

the path without images/ works.

Can anybody confirm this issue?

I am using openHAB 2.4.0.M3.

**Comment by htreu** [comment]
Thanks for the bug report, it is indeed only the sitemap list which is rendered from a different html snippet. should be fixed by #6273.
