### ISSUE TITLE
Bose Soundtouch binding ZoneAdd, ZoneInfo, ZoneRemove channels missing

### ISSUE THREAD

**Issue by DerGute** [eclipse/smarthome#6282]
Im looking for controlling my soundtouch devices multiroom via openhab. On https://community.openhab.org/t/bose-soundtouch-binding/5678/187 i have found some channels, that should make this possible. I tried to use this channels, but none works. Could it be , that this feature was removed? i also cant find any hints in the readme or documentation.
`String  Soundtouch300_ZoneAdd                    "Zone add: [%s]"       <text>        { channel="bosesoundtouch:300:C4F3129FF042:zoneAdd" }
String  Soundtouch300_ZoneControl                "Zone control: [%s]"    <text>        { channel="bosesoundtouch:300:Soundtouch300:zoneControl" }
String  Soundtouch300_ZoneRemove                 "Zone remove: [%s]"    <text>        { channel="bosesoundtouch:300:Soundtouch300:zoneRemove" }
String  Soundtouch10_ZoneInfo                   "Zone Info: [%s]"      <text>        { channel="bosesoundtouch:10:Soundtouch10:zoneInfo" }
`
Does this function exist? and if yes, what are their channel names?

**Comment by kaikreuzer** [comment]
No, those features do not exist. They might be added once it is possible to [add rule actions to bindings](https://github.com/eclipse/smarthome/projects/3#card-8298857).
