### ISSUE TITLE
Brightness issue in Hue binding (and others)

### ISSUE THREAD

**Issue by cweitkamp** [eclipse/smarthome#6299]
Some users reported an issue when changing the brightness via the `color` channel for Hue bulbs of thing type `210`. It automatically switched to a value of `100` even if a lower percentage was sent (e.g. `sendCommand(“0,60,62”)`).

See https://community.openhab.org/t/solved-brightness-issue-philips-hue/52075/ for more information.

My first guess was a connection to PR #5946. After some further testing I found a problem with the forward and reverse transformation from HSB to XY and back - which seem not to result in the origin values.

I wrote a small unit test:
```java
@Test
public void testHSBtoXYequalsXYtoHSB() {
    HSBType hsb = new HSBType("0,60,62");
    PercentType[] xy = hsb.toXY();
    assertEquals(new PercentType("50.27254"), xy[0]);
    assertEquals(new PercentType("32.956394"), xy[1]);
    assertEquals(hsb, HSBType.fromXY(xy[0].floatValue() / 100.0f, xy[1].floatValue() / 100.0f));
}
```

And it failed:
```java
Failed tests: 
  HSBTypeTest.testHSBtoXYequalsXYtoHSB:136 expected:<0,60,62> but was:<0,60,100>
```

As I am not an expert in color space conversions any kind of help is appreciated.

**Comment by NorbertHD** [comment]
When you convert to XY the brightness is lost. There is no brightness information in the XY values.

**Comment by cweitkamp** [comment]
Which leads to the assumption that this issue could be solved by sending a XY color command to then Hue API followed by a brightness command?

**Comment by cweitkamp** [comment]
I will give it a try - here is a test version which send the XY and the brightness:

[org.eclipse.smarthome.binding.hue-0.10.0-SNAPSHOT.jar.zip](https://github.com/eclipse/smarthome/files/2443343/org.eclipse.smarthome.binding.hue-0.10.0-SNAPSHOT.jar.zip)

**Comment by NorbertHD** [comment]
I have looked over the source code and I think that the fromXYtoHSBType function must also replace the brightness in the HSBType that was created by fromXY, with the value from lightState.getBrightness().

**Comment by cweitkamp** [comment]
I agree.

**Comment by cweitkamp** [comment]
I did some tests and it looks good. New test version:

[org.eclipse.smarthome.binding.hue-0.10.0-SNAPSHOT.jar.zip](https://github.com/eclipse/smarthome/files/2445477/org.eclipse.smarthome.binding.hue-0.10.0-SNAPSHOT.jar.zip)

**Comment by cweitkamp** [comment]
PR #6308
