### ISSUE TITLE
Bose Soundtouch: Not able to update notification through PaperUI

### ISSUE THREAD

**Issue by dominicdesu** [eclipse/smarthome#6304]
Hi,

for my Bose Soundtouch speaker, I can see the notification channel in the PaperUI Control panel, but I am not able to set a value, even though I should be able to send a URL to the speaker:
![grafik](https://user-images.githubusercontent.com/3878009/46371438-a6bc2480-c688-11e8-88d9-33a76ccf8132.png)

Shouldn't I be able to set a string value? The channel is not marked as readonly in the channels.xml.

Any idea what could be wrong?

**Comment by htreu** [comment]
Thanks @dominicdesu for the bug report. This got broken in Paper UI during refactoring the control ui.
