### ISSUE TITLE
[Tradfri Binding] Tradfri binding looses connection to gateway after a period of time

### ISSUE THREAD

**Issue by chriscolden** [eclipse/smarthome#6305]
I'm facing an issue where the Tradfri binding looses connection to the gateway after a period of time, usually within a 12 hour period.

I can solve the problem temporarily by changing the ip on the gateway and change it back to the original ip. I believe this is session issue. The session becomes stale and doesn't re initiate.

My tradfri gateway is on a static ip via dhcp reservation.

Gateway version 1.4.15

Additional note: The tradfri mobile app now has notes around this issue. They say if the app cannot connect to the gateway, swipe the app away and reopen. I believe I'm doing the equivalent by changing the ip, forcing the binding to re initiate the session with the gateway.

Please let me know if you need further information. This only started happening recently, possibly because the gateway was updated.

**Comment by htreu** [comment]
Closing this in favour of #6065. Let us continue the discussion there.
