### ISSUE TITLE
channel builder: derive info from channel type

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#6309]
The channel type builder contains a method to assign a channel type UID (`withType(@Nullable ChannelTypeUID channelTypeUID)`).

There is also a method (of the channel type builder) to set the acceptable item type for the channel.

If someone creates a channel for a specific channel type, shouldn't there be an option that this information is taken from the specific channel type?

Same for others information.

The `ThingHandlerFactory` contains a method `ChannelBuilder createChannelBuilder(ChannelUID channelUID, ChannelType channelType, ConfigDescriptionRegistry configDescriptionRegistry)` that takes information from the `ChannelType` to create a specific `ChannelBuilder` for the given `ChannelUID`.
Shouldn't such a logic already be present in the `ChannelBuilder` itself?

**Comment by htreu** [comment]
Imho the *Builders should not have additional logic for setting defaults or derived information. This should be done externally, like you already mentioned `ThingHandlerCallback` and `ThingFactoryHelper`.
I expect *Builders to only fill in the information which is explicitly given.

**Comment by maggu2810** [comment]
Hm isn't it supported that a thing creates channel dynamically?
Which method should be used to create a channel of a given type dynamically?

**Comment by maggu2810** [comment]
Oh, I missed that method of `ThingHandlerCallback` :wink:
