### ISSUE TITLE
Model content is processed by Generic*Provider even if the model resource has validation errors

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#633]
migrated from Bugzilla [#457353](https://bugs.eclipse.org/bugs/show_bug.cgi?id=457353)
status NEW severity _enhancement_ in component _DSL_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Project Inbox

On 2015-01-13 12:09:39 -0500, Alex Tugarev wrote:

> Currently the all ModelRepositoryChangeListener implementors process the model resources without checking for validation errors. The ModelRepositoryImp is not checking for validation errors neither.
> 
> It is highly recommended to omit model contents with validation errors. And perhaps it is a good idea to process only valid content instead of declining the whole model resource.

**Comment by triller-telekom** [comment]
I guess this issue is obsolete since the models are now checked and discarded if there are validation errors.

@kaikreuzer @sjka Can you please close this issue?

**Comment by sjka** [comment]
fixed by #2872
