### ISSUE TITLE
MQTT broker connection: custom persistence directory

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#6331]
The `start()` method if the `MqttBrokerConnection` contains currently this code:

```Java
// Storage
Path tmpDir = Paths.get(ConfigConstants.getUserDataFolder());
try {
    tmpDir = Files.createDirectories(tmpDir.resolve("mqtt").resolve(host));
} catch (IOException e) {
    future.completeExceptionally(new MqttException(e));
    return future;
}
MqttDefaultFilePersistence _dataStore = new MqttDefaultFilePersistence(tmpDir.toString());

// Create the client
MqttAsyncClient _client;
try {
    _client = createClient(serverURI.toString(), clientId, _dataStore);
} catch (org.eclipse.paho.client.mqttv3.MqttException e) {
    future.completeExceptionally(new MqttException(e));
    return future;
}
```

On client creation the method `open(String clientId, String theConnection)` of the used `MqttClientPersistence` implementation is called.
In our case it is the `MqttDefaultFilePersistence`.

This class contains this code :

```Java
try {
    fileLock = new FileLock(clientDir, LOCK_FILENAME);
} catch (Exception e) {
    throw new MqttPersistenceException(MqttPersistenceException.REASON_CODE_PERSISTENCE_IN_USE);
}
```

I had a system running on that the FileLock creation fails all the time (the `MqttPersistenceException(MqttPersistenceException.REASON_CODE_PERSISTENCE_IN_USE)` has been thrown all the time).
A system restart does not solve the problem.

I solved it by cleanup up the directory myself manually.

The consumer of the MQTT broker connection does not know which persistence file is currently used as the constructed path is an implementation detail.
So it cannot cleanup anything reliable.

WDYT about adding an optional argument (function overloading) to the start method so the caller can configure the data storage directory it wants to use?

**Comment by davidgraeff** [comment]
I fully agree.
