### ISSUE TITLE
PaperUI won't allow System settings save until latitude/longitude is entered

### ISSUE THREAD

**Issue by macdroid53** [eclipse/smarthome#6333]
Openhabian, openHAB 2.4.0~20181004001205-1 (Build #1380)

In firefox the PaperUI > Configuration > System > Regional Settings  after entering Language, Country, Time Zone, Measurement System the save button was inactive until I added my latitude and longitude.

**Comment by macdroid53** [comment]
I don't know if it worked before. I discovered this while trouble shooting issues with UoM display of temperature.
I entered the UoM and language, but, no Lat/Lon and it wouldn't save. I then entered Lat/Lon and it would.
I did not try it in another browser.

**Comment by htreu** [comment]
Confirmed. This was overlooked while implementing #6159.
