### ISSUE TITLE
ESH Designer slows down and hangs with large configuration files

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#634]
migrated from Bugzilla [#461416](https://bugs.eclipse.org/bugs/show_bug.cgi?id=461416)
status NEW severity _normal_ in component _Designer_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Project Inbox

On 2015-03-04 11:26:30 -0500, karel goderis wrote:

> When I start up the ESH Designer to edit OH2 configuration files, it tend to be a bit slow on contextual menus (ok, no big deal), but after a while, when you save a file, the hourglass/colorball starts spinning and they only way forward is a forced kill of the application. It seems that, and maybe this is due to the # of items, things etc in my config, that the parsing of syntax elements is a bit slow. For example, I very often have to wait quite some time before Items in .rules are not underscored in red anymore

On 2015-04-27 09:56:37 -0400, Dennis Nobel wrote:

> Can someone confirm this behavior? How many items and things do you have in your configuration files?

On 2015-04-27 10:01:08 -0400, karel goderis wrote:

> It was confirmed by someone on the mailinglist (OH2) I think. I have about 3000+ Items, and several '00 Things

**Comment by htreu** [comment]
The designer is not actively maintained anymore, please see https://github.com/eclipse/smarthome/issues/4139#issuecomment-325333205.

@sjka please close.
