### ISSUE TITLE
Paper UI: Configuration => Bindings is no more displaying the supported things

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#6356]
I just moved to OH snapshot 1389 and I discovered that in Paper UI, when clicking on a binding, it only displayed a description and the author. Until recently, I think we got the list of supported things.

**Comment by kaikreuzer** [comment]
@htreu Did anything break here?

**Comment by htreu** [comment]
This must have been broken for quite some time now. Thanks @lolodomo for reporting. Fixed with #6364.
