### ISSUE TITLE
Duplicate item when changing label in DSL

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#637]
migrated from Bugzilla [#477529](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477529)
status NEW severity _normal_ in component _UI_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Project Inbox

On 2015-09-16 03:33:23 -0400, Florian Klement wrote:

> I'm not sure if this belongs here or in the PaperUI repo, but if it does, just tell me and I'll move it!!!!!!!
> 
> If i have a item defined in my configs (conf/test.items), launch openHAB, then change the display label of the item in the config and reload the page, I have a second item with the new label.
> 
> For example using the network binding and having following item config:
> 
> Group Network       "Network"   [ "home-group" ]
> Number  D1_Time "Time"  (Network)   { channel="network:device:10_90_5_108:time" }
> and then change the label of D1_Time to "D1 Time", reloading the page in the browser results in having two items displayed ("Time" and "D1 Time" labeled) with values of both items being updated as it should be.
> 
> Already been analysed at openHAB2: https://github.com/openhab/openhab2/issues/380

On 2015-09-16 06:27:02 -0400, Kai Kreuzer wrote:

> The problem is not in the Paper UI but in the ItemRegistry/GenericItemProvider. The REST API returns:
> 
> {
>   "members": [
>     {
>       "link": "http://localhost:8080/rest/items/D1_Time",
>       "state": "NULL",
>       "type": "NumberItem",
>       "name": "D1_Time",
>       "label": "Time",
>       "tags": [],
>       "groupNames": [
>         "Network"
>       ]
>     },
>     {
>       "link": "http://localhost:8080/rest/items/D1_Time",
>       "state": "NULL",
>       "type": "NumberItem",
>       "name": "D1_Time",
>       "label": "Time D1",
>       "tags": [],
>       "groupNames": [
>         "Network"
>       ]
>     }

**Comment by htreu** [comment]
I can confirm this is fixed now. @kaikreuzer please close.
