### ISSUE TITLE
ChannelBuilder should allow building "state"

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#6372]
If I'm not mistaken, it's not currently possible to fully define a channel dynamically. Most data can be dynamically set through the ```ChannelBuilder```, but the state, and specifically the allowable options can not currently be defined.

**Comment by htreu** [comment]
In case by `state` you refer to the StateDescription, this is not a property of the Channel but either comes from the ChannelType or is defined from the linked Item.
If I misunderstood you, please make a short example.

**Comment by kaikreuzer** [comment]
@cdjackson You might want to implement a `DynamicStateDescriptionProvider` service.

**Comment by davidgraeff** [comment]
The documentation could be improved in this regard, especially about best practice patterns

**Comment by cdjackson** [comment]
@htreu I am referring to this - it is defined within the channel definition in the XML (ie to allow setting of the format, and options related to the channel).

@kaikreuzer thanks - I will take a look at this.

**Comment by cdjackson** [comment]
```DynamicStateDescriptionProvider``` does provide the facilities I need, so I'm happy to close this unless you wanted to leave it open for documentation updates as @davidgraeff suggested.

**Comment by htreu** [comment]
With the documentation update done in #6393 I will close here.
