### ISSUE TITLE
Add Swagger UI support for runtime as well as static documentation

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#638]
migrated from Bugzilla [#482451](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482451)
status NEW severity _normal_ in component _REST/SSE_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Project Inbox

On 2015-11-18 03:50:51 -0500, Kai Kreuzer wrote:

> With https://github.com/eclipse/smarthome/pull/510/files, we have added Swagger annotations to all ESH REST resources.
> What is missing though, is an optional bundle that can be deployed on a runtime, which reads these annotations and provides the Swagger UI.
> There is something similar in place for openHAB 2 at https://github.com/openhab/openhab2/tree/master/bundles/io/org.openhab.io.rest.docs, but this solution only reads JAX-RS annotations, but not the Swagger ones.
> 
> Additionally, we should enhance the Maven build to generate static resources that can be uploaded to the ESH website for documenting the REST interface.

On 2015-11-18 03:51:33 -0500, Kai Kreuzer wrote:

> FTR: This issue has moved from https://github.com/marinmitev/smarthome/issues/235, see the comments there as well.

**Comment by maggu2810** [comment]
I tried to migrate the openhab-core rest documentation.
There are some JS script libraries bundled, that need CQ.
After the Paper UI changes I would like to ask if you see any advance to use npm to fetch this files.
If we start using this approach for the web pages, it could be more easy to generate a list of all currently used third party web stuff.
What do you think? Perhaps we could also sync the versions of already used libraries and see what is still missing.

**Comment by kaikreuzer** [comment]
> There are some JS script libraries bundled, that need CQ.

Hm, doesn't the whole swagger code (HTML) stuff needs a CQ as well?
Since this is under a different license, needs modification and we would want to ship it as sources, this is actually a pretty nasty situation. Also, getting approval for the Swagger code itself might be hard - even the few lines for the annotations took very long, since there was an untraceable history of contributions and code owners on it...

I am hence not sure if it is really worth the effort; I am quite happy with the current solution that we have all annotations on the resources and that the Jax-rs Connector can be used to register the swagger.json servlet for providing the raw data.
Imho the rest is fine to have within the solutions. Anyhow, you would want to customize/theme it again and so there isn't too much value in having it inside ESH, don't you think?

**Comment by kaikreuzer** [comment]
This has been put in place long time ago -> closing issue.
