### ISSUE TITLE
Designer start fails with "executable launcher was unable to locate its companion shared library"

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#639]
migrated from Bugzilla [#482460](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482460)
status NEW severity *normal* in component *Designer* for *---*
Reported in version *unspecified* on platform *PC*
Assigned to: Project Inbox

On 2015-11-18 05:40:35 -0500, Kai Kreuzer wrote:

> The currently built Designer does not start up, but only displays "executable launcher was unable to locate its companion shared library" - at least on Mac OS X.

On 2015-11-18 07:12:16 -0500, Kai Kreuzer wrote:

> Update: On Windows 8, it seems to work fine, so problem might be Mac specific.

**Comment by idserda** [comment]
Looks like the designer won't start because the ini file is not in the same directory as the executable anymore. Other projects have issues with this too: https://bugs.eclipse.org/bugs/show_bug.cgi?id=446390#c11

For now adding this to the Info.plist (under ```<key>Eclipse</key>```) fixes it: 

``` <string>--launcher.ini</string><string>$APP_PACKAGE/Contents/Eclipse/SmartHome-Designer.ini</string> ```

I have no idea yet how to incorporate this into the build.

**Comment by kaikreuzer** [comment]
> I have no idea yet how to incorporate this into the build.

Me neither, but at least it is already an important info about what is the problem - thanks!

**Comment by hfanieng** [comment]
Where do i have to find or store the Info.plist under OS X?

**Comment by neffs** [comment]
This looks like it could help: https://github.com/buchen/fix-info-plist-maven-plugin

@hfanieng The Info.plist is inside the application bundle (/Applications/Eclipse SmartHome Designer.app/Contents/

**Comment by hfanieng** [comment]
Thank you @neffs, i found it out yesterday that i must right-click the Designer icon in my App-Folder, now the designer works for me +1:

**Comment by mastix** [comment]
Hey guys,

I've just downloaded v0.8.0 of the eclipse smarthome designer.

Ran into the same issue and fixed the plist file like mentioned above. Now the splash screen appears but then it fails with the following error message (creates log file in the configuration folder of the eclipse application):

> !SESSION 2016-05-25 17:45:33.836 -----------------------------------------------
> eclipse.buildId=unknown
> java.version=1.8.0_31
> java.vendor=Oracle Corporation
> BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
> Framework arguments:  -keyring /Users/mastixmc/.eclipse_keyring -showlocation
> Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/mastixmc/.eclipse_keyring -showlocation
> 
> !ENTRY org.eclipse.equinox.ds 1 0 2016-05-25 17:45:34.600
> !MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigOptionProvider, interface = org.eclipse.smarthome.config.core.ConfigOptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigOptionProvider, unbind = removeConfigOptionProvider]
> 
> !ENTRY org.eclipse.equinox.ds 1 0 2016-05-25 17:45:34.601
> !MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigDescriptionProvider, interface = org.eclipse.smarthome.config.core.ConfigDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigDescriptionProvider, unbind = removeConfigDescriptionProvider]
> 
> !ENTRY org.eclipse.equinox.ds 1 0 2016-05-25 17:45:34.725
> !MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.binding.BindingInfoRegistry. The reference is: Reference[name = BindingInfoProvider, interface = org.eclipse.smarthome.core.binding.BindingInfoProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addBindingInfoProvider, unbind = removeBindingInfoProvider]
> 
> [...]
> 
> Chain 1:
>   org.eclipse.xtext.junit4 [osgi.identity; osgi.identity="org.eclipse.xtext.junit4"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"]
>     require: (&(osgi.wiring.bundle=org.apache.log4j)(bundle-version>=1.2.15))
>      |
>     provide: osgi.wiring.bundle: org.apache.log4j
>   org.apache.log4j [osgi.identity; osgi.identity="org.apache.log4j"; type="osgi.bundle"; version:Version="1.2.15.v201012070815"]
> 
> Chain 2:
>   org.eclipse.xtext.junit4 [osgi.identity; osgi.identity="org.eclipse.xtext.junit4"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"]
>     require: (&(osgi.wiring.bundle=org.eclipse.xtext)(&(bundle-version>=2.9.0)(!(bundle-version>=3.0.0))))
>      |
>     provide: osgi.wiring.bundle; bundle-version:Version="2.9.2.v201603040440"; osgi.wiring.bundle="org.eclipse.xtext"; singleton:="true"
>   org.eclipse.xtext.util [osgi.identity; osgi.identity="org.eclipse.xtext.util"; type="osgi.bundle"; version:Version="2.9.2.v201603040440"]
>     import: (&(osgi.wiring.package=org.apache.log4j)(version>=1.2.15))
>      |
>     export: osgi.wiring.package: org.apache.log4j; uses:=org.apache.log4j.spi
>     export: osgi.wiring.package=org.apache.log4j.spi
>   org.slf4j.log4j [osgi.identity; osgi.identity="org.slf4j.log4j"; type="osgi.bundle"; version:Version="1.7.2.v20130115-1340"]
> 
> !ENTRY org.eclipse.osgi 4 0 2016-05-25 17:45:35.120
> !MESSAGE Application error
> !STACK 1
> java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
> 

OS: El Capitan
JDK: Java 8

Any ideas what might be causing this?

Regards and thx in advance,

Sascha

**Comment by mastix** [comment]
Ah, never mind: Just found this issue: https://github.com/eclipse/smarthome/issues/1442

**Comment by benjaminhofmann1** [comment]
What did you end up doing to fix it @mastix?  I looked at issue #1442 and it really doesn't tell me what was wrong and how to fix it.

Thanks!

**Comment by mastix** [comment]
Switched back to 0.7.0! Looks like 0.8.0 is pretty messed up! :)

**Comment by benjaminhofmann1** [comment]
Ahhhhhh, thanks.  I should've saved some time and asked sooner.
