### ISSUE TITLE
[HomeMatic] Connection lost to gateway

### ISSUE THREAD

**Issue by McLive** [eclipse/smarthome#6391]
Recently I had the issue that the homematic binding lost it's connection to the gateway.

I tried upading the binidng to 2.4.0 but I'm getting lots of errors with that version:
https://upl0ad.cloud/1SMu

I can't even change the settings for the homematic bridge. (Exception during HTTP PUT request for update config at 'things/homematic:bridge:fe7f373f/config')

The homematic log shows errors like these:
https://upl0ad.cloud/AP9fQ20eNcwbuzNqj0IQ-3RGigN8

What's going on here?

**Comment by McLive** [comment]
I've now configured the correct IP (192.168.178.28) in Network settings as it was using the wrong 192.168.50.2 from openVPN.

![image](https://user-images.githubusercontent.com/5620071/47247737-cd5ab900-d405-11e8-96c5-7c3facb4b7bc.png)

Now it says this:
https://upl0ad.cloud/wtHn

![image](https://user-images.githubusercontent.com/5620071/47247833-4823d400-d406-11e8-8c7f-34908fcdd5c6.png)

**Comment by McLive** [comment]
I updated openHab to 2.4.0 now and ran these commands: 

``feature:install openhab-transport-serial`` 
``feature:install esh-io-transport-upnp`` 
``feature:install openhab-transport-upnp`` 

& ``apt install openhab2-addons``

At least, the binding starts again now.

However, only the gateway turns ONLINE, it can't find the other things I had on the gateway :(

Getting these errors: https://upl0ad.cloud/9sqO

I'm really lost now
![image](https://user-images.githubusercontent.com/5620071/47258868-2c6e0b80-d4a2-11e8-9e1d-5840b649b8f2.png)

**Comment by McLive** [comment]
Downgraded OH to 2.3.0 stable and now everything is working again.

**Comment by kaikreuzer** [comment]
You seem to have a weird mix of bundles on your system after the upgrade. Your exceptions are coming from `org.openhab.binding.homematic`, while this binding in 2.4 now has the namespace `org.eclipse.smarthome.binding.homematic` - so the issues are coming from outdated code, which should not be there.

Afaik, there are no issues if you have a clean 2.4 snapshot installation, so I'd suggest to close this issue. If there are problems with the upgrade procedure, I'd suggest to discuss those at the openHAB forum.
