### ISSUE TITLE
Provenance Collector Framework

### ISSUE THREAD

**Issue by iamkeyur** [eclipse/smarthome#6394]
Hello,

I'm a Master of Computer Science student at Concordia University, Montreal. 

I was looking at this project and thought implementation of provenance Collector for this project would be good idea. 

The introduction of provenance tracing mechanism within IoT, will allow us to perform attribution of malicious behaviours or even actively prevent attacks through performing lineage based authorization of activities. 

I would love to receive feedback of authors on how to get started on this idea. 

Email- iamkeyur96@gmail.com

Looking forward to your response. 

Thanks.

**Comment by htreu** [comment]
Hi, please describe your idea in a more concrete way. Describe how such a framework will fit into the structure of Eclipse SmartHome and what problem it addresses.

**Comment by kaikreuzer** [comment]
Hi @iamkeyur, This is definitely an interesting topic and it could be a valuable feature for the framework. I agree with @htreu that it would be nice if you could elaborate on your ideas in some more detail and we will try the best to help you find your way through Eclipse SmartHome and how such features would best fit in.

**Comment by iamkeyur** [comment]
Hello,
I am trying to find something that is related to SmartHome security. If you see the second paper I mentioned they are trying to solve Smart Home security problems with provenance collections. 

I have also one idea in mind that is related to adaptive smarthome platform that learns from your daily activities. It tries to adapt to your daily habit. And this could be helpful to detect anomalies as well. 

Eclipse SmartHome is something that looks promising platform to implement this idea. So, I can discuss this ideas in more details.

http://web.eecs.umich.edu/~jackjia/material/contexiot_ndss17.pdf
http://seclab.illinois.edu/wp-content/uploads/2017/12/wang2018fear.pdf
