### ISSUE TITLE
Chained Transformations

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#6400]
It is currently possible to assign one transformation to an item.

There are some cases where you need to extract a value first from a structured data format (JSON, XML) and then map the value to one that is understood by ESH. This can be handled by a script transformation, but chained transformations might be easier to grasp (and are probably more efficient as well).

**Comment by kaikreuzer** [comment]
We had discussed those once as well and the outcome was that this won't be possible to support in the UI in any decent way. So the suggestion here would be to solve those complex use cases through a "ScriptedProfile" (we don't have that yet), which would allow to add a (jsr233) script snippet as a profile configuration from within which one can then easily call multiple transformations and do all kinds of nasty stuff ;-)
