### ISSUE TITLE
MQTT: Generic Things: Add command topic transformation

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#6402]
At the moment applying a transformation to incoming data before updating the channel state is supported.
Some people require to transform the channel state before publishing it to the MQTT command topic as well.

Also: Does it make sense to support chained transformations? Probably.

-- Assigned to myself :)

**Comment by kaikreuzer** [comment]
Fwiw, the transformation from channel->item are implemented as `StateProfile`s (e.g. the `JSonPathTransformationProfile`). Those implementations currently simply pass the values from item->channel without processing them. Maybe (I didn't think this through yet) it could make sense to have optionally a "reverse configuration" on the profiles to cover that case as well.

Wrt chained transformations: We had discussed those once as well and the outcome was that this won't be possible to support in the UI in any decent way. So the suggestion here would be to solve those complex use cases through a "ScriptedProfile" (we don't have that yet), which would allow to add a (jsr233) script snippet as a profile configuration from within which one can then easily call multiple transformations and do all kinds of nasty stuff ;-)
