### ISSUE TITLE
Console  commands in separate bundles?

### ISSUE THREAD

**Issue by hsudbrock** [eclipse/smarthome#6407]
I am wondering whether the console command implementations should be in the bundles that contain the implementation of the features addressed by the console commands (as is currently the case). Example: The console command implementations for things, firmware updates, and item channel links are in the bundle `org.eclipse.smarthome.core.thing`.

Advantages of having the console command implementations in separate bundles would be (using the above example):
1. Currently, when changing a console command for things/firmware updates, all bundles depending on the core thing bundle need  to be restarted (which can be many). If console commands were in a separate bundle, only that  bundle would have to be restarted.
2. With console commands  in a separate bundle, solutions could choose to not include console commands.

I open this issue mainly because of the first potential advantage.

Would it be a welcome contribution to extract the console commands into separate bundles? Or is it desired for some reason to keep the situation as is?

**Comment by maggu2810** [comment]
I think about the extraction some time ago, too.
Moving the console command to separate bundles also limit the stuff the console command could access (only exported packages). So a console command cannot reuse internal implementation.
Also it is IMHO more a problem on the development itself. For the normal consumer the available console commands will be changed by updating the bundle. I don't think commands will be changed frequently without any change of the implementation.

So, IMHO it would be much easier to maintain the console commands in the bundle itself.

**Comment by hsudbrock** [comment]
Thanks for the feedback, @maggu2810 . The console commands I checked do not access internal API, but I see your point, and maybe internal access is required in the future. I will close this issue.
