### ISSUE TITLE
eclipse runs old code

### ISSUE THREAD

**Issue by guitar9** [eclipse/smarthome#6426]
eclipse runs always old old, even if I saved it and clean, build project again. I tried also to reinstall eclipse.
I am using latest version stable release of eclipse and i have imported all openhab2 and eclipse smarthome repos when i installed it. (except openhab 1 addons)
I tried this:
 Window --> Preferences --> Run/ Debug --> Launing Window:
![eclipseerroroldcode](https://user-images.githubusercontent.com/25721108/47754685-ff88d800-dc9b-11e8-9ee4-919f144f5be5.png)

Here is the updated file:

![ichrasteaus1](https://user-images.githubusercontent.com/25721108/47754648-e4b66380-dc9b-11e8-8e90-88e58132039d.png)

When i debug it and breaks on a breakpoint. It opens a new tab with the old code.
![ichrasteaus2](https://user-images.githubusercontent.com/25721108/47754666-f0098f00-dc9b-11e8-8420-ed450583d821.png)

This is how i debug it:
![debugconfig](https://user-images.githubusercontent.com/25721108/47754815-68705000-dc9c-11e8-95d3-d25a0abe9fd7.png)

and then click on debug

**Comment by kaikreuzer** [comment]
As you seem to use the openHAB IDE and not the ESH IDE, this issue does not belong here. Better place to ask for support is at the openHAB forum at https://community.openhab.org/.

In your case, you need to look a the "Plug-ins" tab of the launch window and select the projects from your workspace that you want to use in the launch. By default, the launch config uses the officially released bundles from the target platform.

**Comment by guitar9** [comment]
@kaikreuzer thank you that was the problem
