### ISSUE TITLE
[lsp] Inline validation no longer works when using shared folder

### ISSUE THREAD

**Issue by mhilbush** [eclipse/smarthome#6430]
When using VS Code to access the conf directory on a shared (Samba) folder, the inline code validation and mouse-over error messages no longer work. Running VS Code on the same host as openHAB continues to work as expected.

This functionality broke somewhere between OH builds 1250 and 1404, possibly related to the recent Xtext upgrade? I realize this is a wide range between builds. If necessary, I could try to narrow it down a bit as I have several other system backups between 1250 and 1404.

In the two examples below, I'm running the same version of VS Code (v1.28.2) and the openHAB extension (v0.4.0).

Build 1250
![vsc](https://user-images.githubusercontent.com/19286354/47853339-cf812800-ddb4-11e8-9a54-a6a19fe87af3.gif)

Build 1404
![vsc-broken](https://user-images.githubusercontent.com/19286354/47853366-e45dbb80-ddb4-11e8-87ff-e36d96ce32a9.gif)

Validation problems still show in the VS Code Problems window, however clicking on a validation error message is not very helpful, as VS Code is unable to open the window of the configuration file that contains the error. It appears that VS Code is being supplied the wrong URI for the file (e.g. file:///opt/openhab2/conf/rules/test.rules).

I'm not sure if these two problems are related, but wanted to note them both in this issue.

Edit 1: Confirming that in build 1334 it **works correctly** for both problems described above.

Edit 2: Confirming in build 1374 that this build **has both problems** described above.

Edit 3: Confirming that in build 1357 it **works correctly** for both problems described above.

Therefore, it broke somewhere between builds 1357 and 1374. That's the closest I can get, as those are the only backups I have.

Edit 4: I confirmed that 1357 has the old versions of lsp and xtext, and that 1372 has the new versions of lsp and xtext.

**Comment by kaikreuzer** [comment]
Thanks - so it sounds very likely that the Xtext update caused that regression.
It might make sense to dig through changes that have been done there, which might have such an effect.

**Comment by mhilbush** [comment]
There were changes to MappingUriExtensions, which does the URI mapping to account for the client being remote. But I don't see how that would've caused the problem.

In xtext, there were a number of changes to how URIs are handled. That's all a bit over my head, but seems like a more likely cause?
https://github.com/eclipse/xtext-core/commits/master/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/UriExtensions.xtend

**Comment by mhilbush** [comment]
I took a look at the json messages flowing on port 5007.

For the case prior to the xtext upgrade, the messages returned from server always contain this element.
```
"uri": "file:///u:/openhab2/conf/rules/test.rules",
```

However, for the case after the xtext upgrade, the messages returned from the server always contain this element.
```
"uri": "file:///opt/openhab2/conf/rules/test.rules",
```

So, clearly, the server is no longer returning the URI for the client path.

Looking at the original [lsp4j bug report](https://github.com/eclipse/lsp4j/issues/134), it mentions a potential need to do outbound mapping.
> and you might need a uri mapping on the outbound way as well

> for the outbound mapping see org.eclipse.xtext.ide.server.UriExtensions.toUriString(URI)

However, in MappingUriExtensions, toUriString is not defined.

@sjka @kaikreuzer  WDYT?

**Comment by maggu2810** [comment]
I tried to work aroung the changes to get the tests working here:
https://github.com/eclipse/smarthome/pull/6211/files#diff-ec02a8fce88b94d55b7578298c415b74

Perhaps there are some other things to be fixed, too.

**Comment by mhilbush** [comment]
I was reading through the comments on @sjka's [lsp4j bug report,](https://github.com/eclipse/lsp4j/issues/134#issuecomment-344898954) and there were some comments about possibly needing a `toUriString` method to handle the outbound mapping. The workings of ESH, xtext, and lsp are a bit beyond my skill level, so I'm not even sure if that is relevant to this problem. Perhaps @sjka has some thoughts on this as he did the initial work with the previous versions of xtext and lsp to handle samba shares.

**Comment by sjka** [comment]
Thanks for taking car of this!
I also was just following the white rabbit when I implemented it, therefore I don't think I had any advantages here 😄
