### ISSUE TITLE
[OneWire] Missing iButtonLink MS-TL, MS-TPD, and MS-TC

### ISSUE THREAD

**Issue by kabili207** [eclipse/smarthome#6434]
The OneWire binding is missing support for several of iButtonLink's multisensor products, including the MS-TL (temp & luminance), MS-TC (temp & current), and MS-TPD (temp & air flow). The only one of the three I actually own is the MS-TL, but it'd be nice if all are supported.

**Comment by J-N-K** [comment]
I have some refactoring for the whole multisensor in mind. I'll add support for that.

**Comment by J-N-K** [comment]
That slipped out of my attention. I‘ll see what I can do in the next time.

**Comment by J-N-K** [comment]
I have implemented the MS-TL, please check if [this JAR](https://janessa.me/esh/org.eclipse.smarthome.binding.onewire-0.10.0-SNAPSHOT.jar) works for you. Thanks.

**Comment by kabili207** [comment]
It doesn't seem to be mapping the MS-TL during a discovery. 

```
2018-12-09 23:39:53.856 [INFO ] [nternal.discovery.OwDiscoveryService] - sensor-id 26.1C84E1010000: DS2438 cannot be mapped to thing type
2018-12-09 23:39:53.861 [INFO ] [nternal.discovery.OwDiscoveryService] - sensor-id 26.BB7EE1010000: DS2438 cannot be mapped to thing type
```

**Comment by J-N-K** [comment]
That's strange. Could you please
* check that you are running the correct bundle (bundle:list) and
* show the /pages of a MS-TL sensor (from the owfs https-service)?

**Comment by kabili207** [comment]
The version number seems very old, much older than what using `addons.conf` pulls down.
```
237 │ Active   │  80 │ 0.10.0.201810251625    │ Eclipse SmartHome OneWire Binding
```

pages.ALL
```
07A014D701000000CE7D3300000800FC00000000C67D33001B00000000000000
0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by J-N-K** [comment]
Pages looks good, the identifier 1B is where I would expect it. Will check if I uploaded the wrong file.

**Comment by kabili207** [comment]
Seems to be working perfectly now

**Comment by J-N-K** [comment]
I‘ll try to finish the other work as soon as possible. I‘ll leave out TPD until someone is able to test it.
