### ISSUE TITLE
Group itemtype "Percent" refused in openhab 2.3

### ISSUE THREAD

**Issue by vdanjean** [eclipse/smarthome#6436]
Hi,

  I just upgraded from openhap 2.2 to openhab 2.3 (I'm using Debian package at https://dl.bintray.com/openhab/apt-repo2 stable)
  One line of my previous config is now refused by openhab. It is this one:
```
Group:Percent:AVG      Volets_Salle    "Tous les volets grande salle"  (All)
```

  I get the following error:
```
2018-11-02 10:39:26.025 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'groups.items' has errors, therefore ignoring it: [28,7]: no viable alternative at input 'Percent'
[28,14]: missing EOF at ':'
```

  If I change 'Percent' to 'Switch' or 'Number', the config is accepted  but, of course, the behavior is not the same. In particular, my rule file that react to group command do not have the same kind of values with a switch for example.

  Is it a bug (that Percent is not accepted anymore) or is it a voluntary change? In the latter case, what kind of itemtype do you suggest for a group of RollerShuter that I want to manipulate all in one touch. In my sitemap, I have:
```
Switch item=Volets_Salle icon="rollershutter" mappings=[100="Tous fermés", 0="Tous ouverts"]
```

  Regards,
    Vincent

**Comment by kaikreuzer** [comment]
"Percent" has never been a valid item type, so if anything worked before, this was a bug.
See https://www.eclipse.org/smarthome/documentation/concepts/items.html for the list of existing item types.

**Comment by vdanjean** [comment]
Thanks. I changed the itemtype to Dimmer and it works as before (but with a correct config).
