### ISSUE TITLE
Upgrade Classic UI to Material Design

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#644]
migrated from Bugzilla [#479788](https://bugs.eclipse.org/bugs/show_bug.cgi?id=479788)
status ASSIGNED severity *normal* in component *UI* for *---*
Reported in version *unspecified* on platform *PC*
Assigned to: Kai Kreuzer

On 2015-10-14 15:09:06 -0400, Kai Kreuzer wrote:

> The classic UI's style comes from early versions of iOS, which is clearly outdated by now.
> Similar to the Paper UI, the UI should be modernized by using Material Design.
> At the same time, it could be refactored to make use of new SSE eventing of ESH.

On 2015-10-14 15:09:51 -0400, Kai Kreuzer wrote:

> A new "Basic UI" has been implemented with https://github.com/eclipse/smarthome/pull/411.

On 2015-10-14 15:11:05 -0400, Kai Kreuzer wrote:

> CQ10266 has been entered for it.

**Comment by kaikreuzer** [comment]
Merged with https://github.com/eclipse/smarthome/pull/536
