### ISSUE TITLE
ConfigMapper - multi value parameters with single value

### ISSUE THREAD

**Issue by fruggy83** [eclipse/smarthome#6448]
Thanks to #6386 we are now able to parse a multi value paramter with multiple values from a thing file. However if we provide just a single value for such a parameter (multi value optional), the ConfigMapper tries to map a String value onto an ArrayList/Collection property of the config class.

Proposal: The objectConvert function of the ConfigMapper should provide a special case for a String value and a collection type.

Best regards
Daniel

**Comment by kaikreuzer** [comment]
@htreu Sounds as if #6386 wasn't the optimal solution. Could you have a look?

**Comment by fruggy83** [comment]
@htreu thanks a lot, works perfectly now 👍
