### ISSUE TITLE
Formatter for item, sitemap and rule editor

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#645]
migrated from Bugzilla [#468938](https://bugs.eclipse.org/bugs/show_bug.cgi?id=468938)
status ASSIGNED severity _normal_ in component _Designer_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Philip Langer

On 2015-06-01 05:01:54 -0400, Philip Langer wrote:

> When the user hits Ctrl + Shift + F (or "Format" in the context menu) while editing *.items, *.sitemap or *.rules files, the format of those files gets unusable. This is because a dedicated formatter for those DSLs is missing.
> 
> It might also be necessary to slightly adapt the grammar in order to make appropriate formatting easier or even possible.

On 2015-06-01 07:53:23 -0400, Kai Kreuzer wrote:

> Item files are addressed with https://github.com/eclipse/smarthome/pull/328
> 
> Besides items, sitemap and rules, please note that there are also DSLs for persistence, scripts and things.

On 2015-06-01 08:20:07 -0400, Philip Langer wrote:

> Ok, thanks! I put these other DLSs on my todo list too.

**Comment by htreu** [comment]
The designer is not actively maintained anymore, please see https://github.com/eclipse/smarthome/issues/4139#issuecomment-325333205.

@sjka please close.
