### ISSUE TITLE
Classic UI: Fixes dimmer/rolershutter infinite request bug

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#646]
migrated from Bugzilla [#460320](https://bugs.eclipse.org/bugs/show_bug.cgi?id=460320)
status ASSIGNED severity _enhancement_ in component _UI_ for _---_
Reported in version _unspecified_ on platform _All_
Assigned to: Sebastian Janzen

On 2015-02-19 05:04:34 -0500, Sebastian Janzen wrote:

> On long presses, the dimmer widget does XHRs forever, because the touchend-Handler wasn't attached correctly.
> 
> This is based on a openhab 1 upstream change of pull request 2127 (https://github.com/openhab/openhab/pull/2127).

On 2015-02-20 09:33:00 -0500, Dennis Nobel wrote:

> I guess this bug is related to Classic UI? So I´ll change the title.

On 2015-02-22 15:46:36 -0500, Sebastian Janzen wrote:

> You're right, Dennis, thanks.
> 
> I created a PR: https://github.com/eclipse/smarthome/pull/207
> 
> Should I mark this as Resolved?

On 2015-02-23 02:16:12 -0500, Dennis Nobel wrote:

> Thanks. It will be marked as resolved, when the PR is merged.

On 2015-03-03 04:18:52 -0500, Kai Kreuzer wrote:

> There seem to be issues with this code, see https://github.com/openhab/openhab/issues/2210 and https://github.com/openhab/openhab/issues/2214.
> 
> I therefore cancel the CQ and will wait for a code update.

On 2015-04-27 09:57:29 -0400, Dennis Nobel wrote:

> Any updates here?

**Comment by kaikreuzer** [comment]
@sja What is the status here?

**Comment by triller-telekom** [comment]
With the current Classicui I cannot see any infinite loop once I click and hold up or down on a Dimmer.

@kaikreuzer @sjka Can you please close this issue?
