### ISSUE TITLE
[Tradfri] support power sockets

### ISSUE THREAD

**Issue by widhalmt** [eclipse/smarthome#6483]
Hi,

Tradfri now offers switchable power sockets which are not recognised by the binding. Could you add them to the binding?

Here's the link to the (Austrian) product page: https://www.ikea.com/at/de/catalog/products/90356166/?query=TR%C3%85DFRI+Steckdose%2C+funkgesteuert 

Cheers,
Thomas

**Comment by htreu** [comment]
There is already support for the power socket, see https://github.com/eclipse/smarthome/issues/6269.
