### ISSUE TITLE
[yahooweather] Yahoo had officially ended their free api

### ISSUE THREAD

**Issue by rkoshak** [eclipse/smarthome#6491]
See https://community.openhab.org/t/yahoo-weather-binding-free-weather-api-services-canceled/56172 and https://developer.yahoo.com/weather/?guccounter=2.

The API is no longer free and the ending used by the binding had been closed down. The Yahoo Weather binding needs to be removed

**Comment by Confectrician** [comment]
I f i am right, many documentation articles use the yahoo weather binding as reference.
So we would have to find a replacement for those articles too.

Looks like a bunch of work.

**Comment by kaikreuzer** [comment]
That's indeed bad news, just a short while after WeatherUndergrund stopped offering free services :-(.

But it indeed does not make much sense to keep the binding in place now. I'd suggest to remove it for the upcoming ESH 0.10.0 release (and openHAB 2.4).

> many documentation articles use the yahoo weather binding as reference.

Even Marianne's openHAB book uses it as a reference (after she first used WeatherUnderground)... So probably time for a second edition soon ;-)

> So we would have to find a replacement for those articles too.

We have OpenWeatherMap and MeteoBlue in the pipeline - not sure, which is the better and more future-proof service, I haven't used any of those yet.

**Comment by kaikreuzer** [comment]
> The API is no longer free and the ending used by the binding had been closed down.

According to the [latest comments](https://community.openhab.org/t/yahoo-weather-binding-free-weather-api-services-canceled/56172/10?u=kai), this is not correct - the service is still working and we do not know a date when it will be closed down.

Nevertheless, the end seems near, so we should be prepared for it.

**Comment by 9037568** [comment]
FYI, created a PR for OH1 to go along with this...

**Comment by kaikreuzer** [comment]
I just received an answer from Yahoo and they pointed me to updated info on https://developer.yahoo.com/weather/, which now states:

> As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired.

**Comment by MrBRB** [comment]
Hi,
webpage now states: 

_Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired.
To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service._

Can the binding be updated to the new adress?

**Comment by kaikreuzer** [comment]
> Can the binding be updated to the new adress?

No idea how much the new API resembles the old one and weather it is possible for users to get free OAuth credentials.
If anyone wants to work on this, this is very welcomed, but for now we should remove the current binding from the repo.

**Comment by yveshanoulle** [comment]
I see that the documentation of the yahooweather binding is also gone (at least I don't find it back)
I think it would be better to leave a read me page explaining that it's no longer supported, as now we have many questions on the forum because people don't find anything back in the documentation

**Comment by claell** [comment]
It took me a while to find this after seeing problems in my logs. Should this also be added to breaking changes in the 2.4 release notes?

**Comment by ghys** [comment]
I would suggest a blog post to keep things simple ("Important information about Yahoo Weather"), providing news is what they are for after all. Maybe changing the website's "alert" on the homepage too.
Note though that blog posts are not indexed for search.

**Comment by yveshanoulle** [comment]
I don't know if this is the first binding that gets deprecated. yet I do find it more logical that the readme page stays where the info of the binding was before. That is the place where I look when I have troubles with a binding. Might also work for bindings that are no longer maintained and no lonegr work for a technical reason.

**Comment by ghys** [comment]
I can try putting a page where the original binding readme was, but I don't know if the build script will like it.

**Comment by ghys** [comment]
Looks like we're good.

https://www.openhab.org/addons/bindings/yahooweather/

**Comment by yveshanoulle** [comment]
Great. At this moment it does not show up in the search, I guess it needs more time.

What is a bigger problem, is that three other links show up. That is in other documentation, the yahooweather is used as an example.  :-(

**Comment by ghys** [comment]
> Great. At this moment it does not show up in the search, I guess it needs more time.

The search index is indeed rebuilt every 24h and it's out of our control. I just back and it's back now.
