### ISSUE TITLE
[eclipse/smarthome] [Homematic] CUxD devices are not discovered in OpenHab 2.4 Snap due to CCU firmware 3.41.x

### ISSUE THREAD

**Issue by exo1987** [eclipse/smarthome#6493]
After upgrading my OpenHab firmware to 2.4 -Snap I was again able to discover my Homematic devices but the CUxD devices were not diplayed. I already read that this is beacause of the change of the BINRPC to XMLRPC protocol. But is there a way to set the CUxd back to BINRPC. And if yes, how should this work?

Kind regards
Chris

**Comment by gerrieg** [comment]
see https://github.com/eclipse/smarthome/pull/6494

**Comment by exo1987** [comment]
Cool, thank you! Will this change be part of a nightly build addon package or maybe the next snapshot version of OpenHab?

**Comment by kaikreuzer** [comment]
@exo1987 I've just pushed the change to openHAB, so the next snapshot 1419 will include it.
