### ISSUE TITLE
Additional states for Philips Hue lights

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#650]
migrated from Bugzilla [#469036](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469036)
status UNCONFIRMED severity *enhancement* in component *Binding* for *---*
Reported in version *unspecified* on platform *All*
Assigned to: Project Inbox

On 2015-06-01 15:24:48 -0400, Dominic Lerbs wrote:

> The Philips Hue API supports additional states, which are currently not implemented in openHAB: alert, effect and transitiontime. (see http://www.developers.meethue.com/documentation/lights-api)
>
> It would be great if these states could be also triggered from openHAB.
> Especially the transitiontime would be useful, as this allows smooth transitions of the light state (e.g. brightness) without manually programming loops in openHAB.
>
> Also an open ticket at openHAB: https://github.com/openhab/openhab/issues/2020

**Comment by sja** [comment]
This should be closed, as alert and effect are in now.

**Comment by kaikreuzer** [comment]
Indeed.

**Comment by polarathene** [comment]
> “effect” – this resource is for dynamic effects and currently only supports two values, but we’ll add more in the future. {"effect":"colorloop"} puts the lights in a color looping mode until it is stopped by sending {"effect":"none"}. - [Source](http://www.developers.meethue.com/documentation/core-concepts)

At present at least from what I see on Paper UI, `Effect` is not treated the same as `Alert`, and is named `Color Loop` despite the `effect` channel. I may not understand channels yet, if a new effect is released will this result in another effect name mapped to `effect`  channel, or would this need to be changed to be treated like `Alert`.

Transition time is also not supported yet? I see it was [added for LIFX](https://github.com/eclipse/smarthome/issues/1332), but cannot see it defined in the Hue binding.

**Comment by kaikreuzer** [comment]
Correct, transitions are not (yet) supported by the Hue binding. Feel free to create a new issue for it if you plan to implement this.
