### ISSUE TITLE
Documentation: Add modelling scheme for extended color bulbs

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#6501]
While working on the Hue Emulation binding in openHAB (https://github.com/openhab/openhab2-addons/pull/4216) I noticed that with the current design design of that binding it is impossible to make the cold white / warm white color temperature available to the user. 

I wonder if Eclipse Smarthome should have a dedicated Type, an extended Color Type or what the general idea is to handle basically all new bulbs with color and white temperature support.

**Comment by kaikreuzer** [comment]
We have the following modelling scheme in place for all "extended color" bulbs in the different bindings:
- 1 "color" channel for HSB commands/state
- 1 "color-temperature" dimmer channel, which controls the relative color temperature (0% cold, 100% warm), the scale depending on the physical possibilities of the bulb.
- If a color-temperature is set, the color channel state is updated accordingly. If a color is set, the color-temperature should be set to NULL as it does not really have a valid value.

In https://github.com/eclipse/smarthome/pull/6476#issuecomment-436738891, we are currently discussing to additionally add an advanced channel for absolute color temperature values.
