### ISSUE TITLE
LIFX Binding choosing Whites from cold to warm.

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#651]
migrated from Bugzilla [#470713](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470713)
status UNCONFIRMED severity _normal_ in component _Binding_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Project Inbox

On 2015-06-22 10:05:21 -0400, Vladislav Lebedev wrote:

> In iOS app LIFX i can choose whites from warm to cold, but in colorpicker trying choose white is useless.
> How can i choose white tone from OH2? Please add support for whites.

On 2015-06-25 16:15:57 -0400, Dennis Nobel wrote:

> Unfortunately not possible with the current binding, but it could be enhanced. I originally developed the LIFX binding. But I don´t have much time at the moment. So if you want to add to the feature to the binding, please feel free to do so.

**Comment by wborn** [comment]
I think this issue can be closed. The discussion on 2015-06-22 predates the creation of #483 (2015-10-07) in which the `temperature` channel was added to LIFX light Things. The `temperature` channel simplifies changing the color from a cool white to a warm white.
