### ISSUE TITLE
Timers / New rule engine timers

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#6519]
Disclaimer: I'm not sure if there is an issue already open for this, if so, please point me to it.

Currently there is not much time related functionality available for the new rule engine.
This issue is about timed triggering of a rule of the automation bundle.

## What use-cases should be targeted

To quote @rkoshak here: 

> Some example uses for Timers in Rules DSL include:

* Anti-flapping/debounce (see [Generic Presence Detection](https://community.openhab.org/t/generic-presence-detection/17878))
* Motion sensor timers/open door reminders (see [Design Pattern: Motion Sensor Timer](https://community.openhab.org/t/design-pattern-motion-sensor-timer/14954))
* Cascading timers (see [Design Pattern: Cascading Timers](https://community.openhab.org/t/design-pattern-cascading-timers/31791))
* Detecting and reacting to an Item that hasn’t reported in awhile (see [Design Patterns: Generic Is Alive](https://community.openhab.org/t/design-patterns-generic-is-alive/14869))

## Required Timer capabilities

A timer for the new rule engine should support these capabilities:
* Timers are named / have a unique id
* Relative time or absolute time support
* Any rule can create a timer. If there is already a timer with the same id, nothing happens (so that rule templates can establish their required timers)
* Any rule can delete any timer by id
* Any rule can set the remaining time / absolute time / enable/disable-state of any timer by id

## First proposal: Framework support for timers 
* A timer management service, like the current scheduler for the old rule engine
* A dedicated REST endpoint / PaperUI section for listing all currently active timers, create timers, delete timers.
* A timer can be used as trigger for a rule
* Can be used as condition (elapsed time, remaining time, absolute time)
* Can be modified in the action part of a rule (enable/disable, set remaining time, set absolute time).

Advantage: A dedicated UI for timers can be polished and concise
Disadvantage: Completely new bundles

## Second proposal: Use Trigger channels
* A new binding provides a Relative/Absolute Timer Thing. "Timer Trigger" channels can be added to it.
* The "Timer Trigger" channel has 2 configurations:
  - Enable/Disable
  - TargetTime 

Requires that a channel configuration can be modified from within a rule.

Advantage: Builds on existing concepts
Disadvantage: Not intuitive

WDYT?

Cheers,
David

**Comment by rkoshak** [comment]
Just to add a little bit of refinement, the timer should be create-able/deletable from within rules and the same timer should be accessible across multiple rules or multiple runs of the same rule. There needs to be some sort of ID or handle or linkage to an Item or something that persists after the rule exits.

I think both proposal can support that. I just don't want that to get lost in the discussion.

Thanks

Rich

**Comment by rkoshak** [comment]
There may be some existing work that should probably be reviewed and see if this fits with in #4295.
