### ISSUE TITLE
Wemo: motion sensor cannot be discovered

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#653]
migrated from Bugzilla [#482210](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482210)
status UNCONFIRMED severity *minor* in component *Binding* for *---*
Reported in version *0.8.0* on platform *PC*
Assigned to: Project Inbox

On 2015-11-14 21:29:03 -0500, Nick Ma wrote:

> The WeMo Motion sensor is not discoverable because the code is looking for a device name with "Motion" while the motion sensor device returns "Sensor" in the UPnP response.
>
> Fix:
> - Added a if statement to Look for "Sensor" type
> - Added a thing type called "sensor" to map to the new device name
>
> https://github.com/eclipse/smarthome/pull/516#discussion_r44864408

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/eclipse/smarthome/pull/516
