### ISSUE TITLE
Lifx binding opens too many UDP sockets

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#654]
migrated from Bugzilla [#464961](https://bugs.eclipse.org/bugs/show_bug.cgi?id=464961)
status NEW severity *major* in component *Binding* for *---*
Reported in version *0.8.0* on platform *Other*
Assigned to: Dennis Nobel

On 2015-04-19 16:49:14 -0400, Richard Lavoie wrote:

> There seem to be a leak when the binding is waiting for messages.
>
> [root@openhab openhab2]# netstat -nlp | grep 30921
> tcp        0      0 :::8443                     :::*                        LISTEN      30921/java
> tcp        0      0 :::8080                     :::*                        LISTEN      30921/java
> udp        0      0 :::49463                    :::*                                    30921/java
> udp        0      0 :::46013                    :::*                                    30921/java
> udp        0      0 :::43585                    :::*                                    30921/java
> udp        0      0 :::49866                    :::*                                    30921/java
> udp        0      0 :::41421                    :::*                                    30921/java
> udp        0      0 :::38733                    :::*                                    30921/java
> udp        0      0 :::42446                    :::*                                    30921/java
> udp        0      0 :::47056                    :::*                                    30921/java
> udp        0      0 :::39636                    :::*                                    30921/java
> udp        0      0 :::38612                    :::*                                    30921/java
> udp        0      0 :::43094                    :::*                                    30921/java
> udp        0      0 :::42077                    :::*                                    30921/java
> udp        0      0 ::ffff:10.7.0.41:34526      :::*                                    30921/java
> udp        0      0 :::50792                    :::*                                    30921/java
> udp        0      0 :::60777                    :::*                                    30921/java
> udp        0      0 :::5353                     :::*                                    30921/java
> udp        0      0 :::1900                     :::*                                    30921/java
> udp        0      0 :::37742                    :::*                                    30921/java
> udp        0      0 :::35056                    :::*                                    30921/java
> udp        0      0 :::57714                    :::*                                    30921/java
> udp        0      0 :::39410                    :::*                                    30921/java
> udp        0      0 :::39283                    :::*                                    30921/java
> udp        0      0 :::52343                    :::*                                    30921/java
> udp        0      0 :::39418                    :::*                                    30921/java
> udp        0      0 :::56700                    :::*                                    30921/java
> udp        0      0 :::35069                    :::*                                    30921/java
> udp        0      0 :::48767                    :::*                                    30921/java
> udp        0      0 :::41216                    :::*                                    30921/java
> udp        0      0 :::37889                    :::*                                    30921/java
> udp        0      0 :::55427                    :::*                                    30921/java
> udp        0      0 :::58373                    :::*                                    30921/java
> udp        0      0 :::52108                    :::*                                    30921/java
> udp        0      0 :::57231                    :::*                                    30921/java
> udp        0      0 :::48661                    :::*                                    30921/java
> udp        0      0 :::51606                    :::*                                    30921/java
> udp        0      0 :::58393                    :::*                                    30921/java
> udp        0      0 :::60571                    :::*                                    30921/java
> udp        0      0 :::42907                    :::*                                    30921/java
> udp        0      0 :::56095                    :::*                                    30921/java
> udp        0      0 :::47905                    :::*                                    30921/java
> udp        0      0 :::49444                    :::*                                    30921/java
> udp        0      0 :::43949                    :::*                                    30921/java
> udp        0      0 :::56750                    :::*                                    30921/java
> udp        0      0 :::60975                    :::*                                    30921/java
> udp        0      0 :::60080                    :::*                                    30921/java
> ...
> [root@openhab openhab2]# ps -ef | grep 30921
> openhab  30921 30914  7 22:17 ?        00:00:32 java -Dlogback.configurationFile=./runtime/etc/logback.xml -DmdnsName=openhab -Dopenhab.logdir=./userdata/logs -Dsmarthome.servicecfg=./runtime/etc/services.cfg -Dsmarthome.servicepid=org.openhab -Dsmarthome.userdata=./userdata -Dorg.quartz.properties=./runtime/etc/quartz.properties -Djetty.etc.config.urls=etc/jetty.xml,etc/jetty-ssl.xml,etc/jetty-deployer.xml,etc/jetty-https.xml,etc/jetty-selector.xml -Dosgi.clean=true -Declipse.ignoreApp=true -Dosgi.noShutdown=true -Djetty.home.bundle=org.openhab.io.jetty -Dorg.osgi.service.http.port=8080 -Dorg.osgi.service.http.port.secure=8443 -Dfelix.fileinstall.dir=addons -Djava.library.path=lib -Dequinox.ds.block_timeout=240000 -Dequinox.scr.waitTimeOnBlock=60000 -Dfelix.fileinstall.active.level=4 -Djava.awt.headless=true -jar runtime/server/plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar -console

On 2015-04-19 16:52:26 -0400, Richard Lavoie wrote:

> Github original report at https://github.com/openhab/openhab2/issues/192

On 2015-04-20 04:22:11 -0400, Dennis Nobel wrote:

> If there is such leak, it must be inside the used library (see https://github.com/besherman/lifx-sdk-java/releases/tag/1.0). Unfortunately the library is not maintained any more, because there is new version (2.0). But it seems that this version has problem with the new firmware: "The lifx firmware update 2.0 seems to break a few things, we are waiting for the LIFX team to update LIFXKit. In the meantime please try the old 1.0.1 release if you are having problems.".
>
> Also because of the performance issue I recommend to reimplement the binding maybe using the new library or implementing the full protocol manually. But I do not have time for that at the moment. If someone else wants to fix it, please feel free to create a PR.

On 2015-04-20 12:41:26 -0400, Richard Lavoie wrote:

> The problem is in the LFXSocketUDP object that opens a socket on line 61, but only closes it when there is an exception but not at the end of the method. I even believe the variable declaration should be outside of the loop. As I don't know much about the protocol either, I'll file a bug on their github with our findings.

On 2015-04-20 12:44:16 -0400, Richard Lavoie wrote:

> Another possibility would be to create a fork in openhab's github and work on fixes in this version.

On 2015-04-20 12:44:45 -0400, Richard Lavoie wrote:

> I meant to say smarthome's github, not openhab

On 2015-04-20 12:54:32 -0400, Dennis Nobel wrote:

> The version 1.0 of the used library is just a fork of the official LIFX Android library with minor adaptions to make it work in pure Java. So the bug should be fixed there, but LIFX stopped all their activities at github (https://github.com/LIFX/lifx-sdk-android/commits/master).
>
> But the CQ for the library was made based on my fork (https://github.com/dnobel/lifx-sdk-java). My fork again is a fork of of https://github.com/besherman/lifx-sdk-java. So the easiest way to fix this problem would be to create a PR against my fork, rebuild the library, replace it in the binding and create a PR against ESH. We can request another CQ for the updated library based on my fork.
>
> But on the long-term the binding should definitely make use of another library.

On 2015-04-20 12:56:17 -0400, Dennis Nobel wrote:

> (In reply to Richard Lavoie from comment # 5)
> > I meant to say smarthome's github, not openhab
>
> Unfortunately smarthome does not have an own github account. As it is an eclipse project, it is managed under the eclipse account and only eclipse projects can have their own repository their.

On 2015-04-20 13:12:45 -0400, Richard Lavoie wrote:

> I created an issue explaining the issue at the master lifx project : https://github.com/LIFX/lifx-sdk-android/issues/26
>
> I indeed found that it was a forked as the jar name was lifx-sdk-java and not lifx-sdk-android. We could probably work on your fork to fix this issue, but I don't own any lifx gadget to test the fix.

On 2015-04-27 09:15:01 -0400, Dennis Nobel wrote:

> I assume LIFX will not comment on the PR. I can test the fix in the near future with my LIFX bulbs.

On 2015-04-28 05:52:01 -0400, karel goderis wrote:

> FYI, I see a lot of these in my logs:
>
>
> 2015-04-28 11:49:48 [INFO ] [n.i.t.l.LFXLANTransportManager:99   ] - Connection State did change called.
> 2015-04-28 11:49:48 [INFO ] [n.i.t.l.LFXLANTransportManager:104  ] - LFXGatewayDescriptor - Host: 192.168.0.181, Port: 56700, Path: LFXSiteID: 4C4946585632/<LFXBinaryTargetID D073D501EB9F>, Protocol: LX_PROTOCOL_DEVICE_SERVICE_UDP : CONNECTED
> 2015-04-28 11:49:48 [INFO ] [n.i.t.l.LFXLANTransportManager:104  ] - LFXGatewayDescriptor - Host: 192.168.0.180, Port: 56700, Path: LFXSiteID: 4C4946585632/<LFXBinaryTargetID D073D501C593>, Protocol: LX_PROTOCOL_DEVICE_SERVICE_UDP : CONNECTED
> 2015-04-28 11:49:48 [WARN ] [lifx.java.android.util.LFXLog :45   ] - Idle timeout occured on UDP Connection lifx.java.android.network_context.internal.transport_manager.gateway_connection.LFXUDPGatewayConnection@49e8a025, disconnecting
> 2015-04-28 11:49:48 [INFO ] [n.i.t.l.LFXLANTransportManager:99   ] - Connection State did change called.
> 2015-04-28 11:49:48 [INFO ] [n.i.t.l.LFXLANTransportManager:104  ] - LFXGatewayDescriptor - Host: 192.168.0.181, Port: 56700, Path: LFXSiteID: 4C4946585632/<LFXBinaryTargetID D073D501EB9F>, Protocol: LX_PROTOCOL_DEVICE_SERVICE_UDP : CONNECTED
> 2015-04-28 11:49:48 [INFO ] [n.i.t.l.LFXLANTransportManager:104  ] - LFXGatewayDescriptor - Host: 192.168.0.180, Port: 56700, Path: LFXSiteID: 4C4946585632/<LFXBinaryTargetID D073D501C593>, Protocol: LX_PROTOCOL_DEVICE_SERVICE_UDP : CONNECTED

**Comment by kgoderis** [comment]
Fixed with https://github.com/eclipse/smarthome/pull/483
