### ISSUE TITLE
[mqtt-things] Add system triggers support for Homie devices

### ISSUE THREAD

**Issue by bodiroga** [eclipse/smarthome#6542]
Hi @davidgraeff!

This is a feature request, not a bug, but I would love if it could be implemented.

For Homie devices that report non-retained properties, if the datatype is enum, we could try to define the channel using the [system triggers](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#system-trigger-channel-types) provided by the framework. We could support three diferente cases:

- Datatype "enum" and format "PRESSED,RELEASED" -> system.rawbutton
- Datatype "enum" and format "SHORT_PRESSED,DOUBLE_PRESSED,LONG_PRESSED" -> system.button
- Datatype "enum" and format "DIR1_PRESSED,DIR1_RELEASED,DIR2_PRESSED,DIR2_RELEASED" -> system.rawrocker

Implementing this system triggers, users will be able to link the channel with an item very easily using profiles (no need to write rules). Supporting the whole chain will make building wireless remote controls (Simple buttons or multimedia remotes) easy peasy!

I could provide a PR if you agree with the proposal and technical details could be discussed in the PR. Anyway, we should try to fix first the current problems with system channels (#6529).

Best regards,

Aitor

**Comment by davidgraeff** [comment]
I'd approve this addition. Need to be documented in the Readme of course, because it is absolutely controller specific.
Mid-term plan is a Homie-Types convention where common buttons, lights and sensors are specified and I plan on supporting such a specification.
