### ISSUE TITLE
Introduce a modular automation rule concept

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#655]
migrated from Bugzilla [#451911](https://bugs.eclipse.org/bugs/show_bug.cgi?id=451911)
status NEW severity *enhancement* in component *Automation* for *---*
Reported in version *unspecified* on platform *All*
Assigned to: Kai Kreuzer

On 2014-11-17 09:15:24 -0500, Kai Kreuzer wrote:

> The current rule engine that derives from openHAB 1 has a couple of constraints:
> - it requires EMF/Xtext/Xbase on the runtime, which is not ideal for constrained devices
> - it does not allow to build rule GUIs on top as all rules are purely textually defined.
> - it does not allow to reuse and share rules or logic blocks between users / solutions.
>
> We therefore would like to introduce a new rule concept into Eclipse SmartHome. The overall idea is to have reusable rule components that are formally described, so that they can be handled in GUIs and combined into rules. These must be provided as a kind of template, that can easily be shared and instantiated by a user through a UI.
>
> This bugzilla entry is the umbrella for coordinating the different work packages of this new feature.

On 2014-11-17 12:31:36 -0500, Kai Kreuzer wrote:

> I have started the discussion about this new feature in the forum: https://www.eclipse.org/forums/index.php/m/1477164/

On 2015-03-11 11:23:58 -0400, Kai Kreuzer wrote:

> FTR, we have now an agreed initial API for the new rule infrastructure, contributed by ProSyst: https://github.com/eclipse/smarthome/pull/190.
>
> Implementation code will follow.

**Comment by kaikreuzer** [comment]
Implementation done with https://github.com/eclipse/smarthome/pull/317.
