### ISSUE TITLE
[mqtt binding] read only switches not possible

### ISSUE THREAD

**Issue by TBail** [eclipse/smarthome#6560]
Sometimes it is usefull to have a switch channel to display a status. Eg. Battery status or if the thing is reachable. 

These state switches are typically read only. 

Unfortunately the switch channel requires a command entry that is typically for read only switches not available. If we do not enter a command, the thing will stay after a restart in its initiualization phase and is not usable at all.

I see two options to solve this. Implement a readonly flag so that no command must be entered or just ignore empty command fields. I would prefer a flag

**Comment by htreu** [comment]
@davidgraeff this one is for you
