### ISSUE TITLE
Strip down core.scheduler to only contain Quartz classes that are really required

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#658]
migrated from Bugzilla [#483175](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483175)
status NEW severity *normal* in component *Automation* for *---*
Reported in version *unspecified* on platform *PC*
Assigned to: Project Inbox

On 2015-11-27 07:50:31 -0500, Kai Kreuzer wrote:

> In order to shrink the minimal runtime size, the bundle core.scheduler should be revisited to only contain Quartz classes that are required for ESH purposes.
> There are many parts about JDBC job persistence etc. that are definitely not required.

On 2015-11-27 08:41:57 -0500, Simon Kaufmann wrote:

> do you by any chance already know if there is anything to consider regarding IP/license in that case?
> I'm not sure if "stripping down" a jar technically creates some derived work, or if it's considered to be "unmodified" in the sense that the actual code won't be changed...

On 2015-11-27 08:45:51 -0500, Kai Kreuzer wrote:

> I am pretty certain that if you have the CQ approved for some code, you are free to take any subset of it as well. The class files stay "unmodified", it is only a different jar, but this is what is done with many things in Orbit as well by re-packaging the 3rd party content.

**Comment by sjka** [comment]
there is some work in progress to replace quartz with an own implementation, see #869

**Comment by kaikreuzer** [comment]
The new scheduler service has been merged with https://github.com/eclipse/smarthome/pull/1239, so my suggestion is to close this issue and have the timer module type adapted to use the new scheduler instead.

**Comment by kgoderis** [comment]
Yes, indeed
