### ISSUE TITLE
HTTP 502 on http://download.eclipse.org/smarthome/updates-stable/content.jar

### ISSUE THREAD

**Issue by cice** [eclipse/smarthome#6586]
I am not sure, if this is the right place, but i'm trying to install Eclipse with openHAB target platform and it results in a 502 for this URL http://download.eclipse.org/smarthome/updates-stable/content.jar .

Also, but i guess this should be a separate issue: Why doesn't it use https? 🤔

**Comment by maggu2810** [comment]
It seems to work now (at least on my machine).
Can you test again?

**Comment by kaikreuzer** [comment]
Yes, this was definitely only a temporary availability issue of the Eclipse infrastructure - happens from time to time :-/
