### ISSUE TITLE
Philips Hue Binding: unsupported light

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#659]
igrated from Bugzilla [#472963](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472963)
status ASSIGNED severity *normal* in component *Binding* for *---*
Reported in version *unspecified* on platform *PC*
Assigned to: Markus Mazurczak

On 2015-07-17 11:32:13 -0400, Funk Stille wrote:

> While testing Philips Hue Binding I got the following error message:
>
> 2015-07-17 16:49:27 [DEBUG] [h.i.d.HueLightDiscoveryService:109 ] - discovered unsupported light of type 'LWB001' with id 3
>
> Since the Living White Bulbs work perfectly with Philips Hue (http://www.everyhue.com/vanilla/discussion/229/10-adding-a-philips-living-whites-bulb-to-hue-network), they should be added as well.
>
> THX

On 2015-07-28 17:11:08 -0400, Jochen Hiller wrote:

> I run into a similar issue with other bulbs from
> https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/wireless-ballasts/fls-pp-lp/
> https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/wireless-ballasts/fls-h-lp/
>
> When looking into the Hue APIs I think we can extend the binding that way, that if a model is NOT found in the concrete list of supported thing-types, it will fall back to some generic thing-types.
>
> According to
> http://www.developers.meethue.com/documentation/supported-lights
> there are 4 different types of colors:
> - Color Light
> - Color Temperature Light
> - Dimmable Light
> - Extended Color Light (=Color+Color Temperature)
>
> which can be differentiated by the "type" attribute.
>
> So: why not add 4 new generic thing-types:
> - GenericColorLight
> - GenericColorTemperatureLight
> - GenericDimmableLight
> - GenericExtendedColorLight
> and use them if there is no model mapping to other thing types. Some information like vendor can NOT be derived, but at least the bulb would be directly supported.
>
> Any opinions?

On 2015-11-15 17:14:48 -0500, Markus Mazurczak wrote:

> How would you manage the supported channels while using that generic types? Every "bulb-type" is added using an specific [thing].xml where the channel configuration/mapping is done.

On 2015-11-16 04:55:29 -0500, Kai Kreuzer wrote:

> Markus, we would have these 4 different thing types, which would all have clearly defined channels that are always the same for any product of that generic type.
> We would then not need the individual thing types anymore (but could use the MODEL_ID property to still have the information at hand in case we need special workarounds ;-)).

On 2015-11-16 06:12:48 -0500, Markus Mazurczak wrote:

> (In reply to Kai Kreuzer from comment # 3)
> > Markus, we would have these 4 different thing types, which would all have
> > clearly defined channels that are always the same for any product of that
> > generic type.
> > We would then not need the individual thing types anymore (but could use the
> > MODEL_ID property to still have the information at hand in case we need
> > special workarounds ;-)).
>
> Ah, you're right :-)
> Is someone already working on this?

On 2015-11-17 02:58:00 -0500, Kai Kreuzer wrote:

> No, as far as I know, nobody is working on it yet. Are you interested?

On 2015-11-17 03:22:25 -0500, Markus Mazurczak wrote:

> I will give it a try. I will first finish that Osram thing, get a little bit more comfortable with that Git stuff (used SVN for years ;)) and after that start with refactoring that Hue stuff to Generic-Things.

On 2015-11-17 03:45:12 -0500, Kai Kreuzer wrote:

> Sounds good - I am sure you will get into git soon, like everybody else: http://www.xkcd.com/1597/

On 2015-12-02 14:13:24 -0500, Markus Mazurczak wrote:

> I am done with the changes. I've implemented no fallback in case of unsupported light. I just implemented 4 generic thing types so that there is no more need to add bulb specific [Thing].xml's.
> I've done some successful "real world" tests with my OSRAM Par16 50 bulbs and the test suite runs successful as well.
>
> There is one thing I am a bit unsure about and this is the "type" string that is saved in the Jue-FullLight structure for an "Extended Color light".
> I don't want to iterate over the SUPPORTED_THING_TYPES and use the "contains" check further on.
> Regarding the HUE-API documentation the following 4 types are supported:
>
> - Dimmable light
> - Color temperature light
> - Color light
> - Extended Color light
>
> What I am unsure about is the actual string for the "Extended Color light". Is "Color" saved with an uppercase C or not?
>
> Is there anyone with a bulb that is of type "Extended Color light" and can check the type string, just to clarify this before I open a Pull Request for that change?
>
> My branch including the changes can be found here: https://github.com/markusmazurczak/smarthome/tree/472963--Philips-Hue-Binding-unsupported-light

On 2015-12-02 14:43:29 -0500, Markus Mazurczak wrote:

> just a thought ... we can extend the Jue API to support the "manufacturername" field. For my OSRAM PAR16 50 I will get the following in this field:
>
> ...
> "type": "Color temperature light",
> "name": "Büro 2",
> "modelid": "PAR16 50 TW",
> "manufacturername": "OSRAM", <--
> "uniqueid": "LirumLarum",
> "swversion": "1131847"
> ...

**Comment by kaikreuzer** [comment]
#1652 now supports generic types, hence new models are automatically supported.
