### ISSUE TITLE
MQTT NetworkDiscoveryService spams log and creates an abundance of threads

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#6598]
@davidgraeff Just tried the MQTT binding for the first time.
First UX: My log is spammed with hundreds of lines like:

```
14:41:57.570 INFO  o.e.s.i.t.m.MqttBrokerConnection[:720] - Starting MQTT broker connection to '192.168.3.225' with clientid testssl and file store 'userdata/mqtt/192.168.3.225'
14:41:57.573 INFO  o.e.s.i.t.m.MqttBrokerConnection[:720] - Starting MQTT broker connection to '192.168.3.225' with clientid test and file store 'userdata/mqtt/192.168.3.225'
14:41:57.576 INFO  o.e.s.i.t.m.MqttBrokerConnection[:720] - Starting MQTT broker connection to '192.168.3.226' with clientid testssl and file store 'userdata/mqtt/192.168.3.226'
14:41:57.579 INFO  o.e.s.i.t.m.MqttBrokerConnection[:720] - Starting MQTT broker connection to '192.168.3.226' with clientid test and file store 'userdata/mqtt/192.168.3.226'
14:41:57.582 INFO  o.e.s.i.t.m.MqttBrokerConnection[:720] - Starting MQTT broker connection to '192.168.3.227' with clientid testssl and file store 'userdata/mqtt/192.168.3.227'
```

Could this be done as DEBUG...?

Next, it seems that the service does not use a thread pool:

![screenshot 2018-11-29 at 14 52 15](https://user-images.githubusercontent.com/3244965/49226270-6bb74280-f3e6-11e8-95fa-0714d4e4ed1d.png)

Could that be changed to be done through a named thread pool (using `ThreadPoolManager`)?

And the worst thing: All those threads keep running after a discovery. As a result, after the 3rd network scan (and >4000 live threads), I am getting
```
15:00:02.407 WARN  o.e.s.c.i.c.WrappedScheduledExecutorService[:67] - Scheduled runnable ended with an exception: 
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1587)
	at java.util.concurrent.ScheduledThreadPoolExecutor.reExecutePeriodic(ScheduledThreadPoolExecutor.java:350)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:296)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kaikreuzer** [comment]
FTR: It is additionally very annoying that the network scan is also triggered once an MQTT broker is approved in the inbox - so I cannot even avoid running in this issue.
One would only expect that the selected broker is queried for Things.
All in all, I am not a friend of doing full network scans for discovery at all. Imho it suffices if people provide the IP address manually - this avoids a lot of potential issues.

**Comment by kaikreuzer** [comment]
Imho only "real" connections might be logged as INFO - but those ones here are trials against some IP where there is no broker at all. So maybe just log successful connections and unauthorized accesses (where a broker actively rejected the connection).

**Comment by kaikreuzer** [comment]
But my main remark in this issue here was this:

**All in all, I am not a friend of doing full network scans for discovery at all. Imho it suffices if people provide the IP address manually - this avoids a lot of potential issues.**

**Comment by davidgraeff** [comment]
It helps the average user a lot to find his/her mosquitto installation, performs within 7 seconds, is no background scan but a manual one and soon™ will not spam logs anymore :)

**Comment by kaikreuzer** [comment]
The average user is going to use the embedded broker in future and this feature behaves like a naughty virus trying to scan your system for vulnerable hosts.
Additionally, it completely freezes and crashes the runtime as it has no control over the created threads.
Furthermore, it will only work in the "happy cases". What if you have special (large) subnets, VPNs, virtual interfaces, network intrusion detection devices, whatever. There are millions of reasons why such a blindly done full network scan can upset users.

**Comment by kaikreuzer** [comment]
> is no background scan

I hope you also read my other comment above: "the network scan is also triggered once an MQTT broker is approved in the inbox - so I cannot even avoid running in this issue."

**Comment by davidgraeff** [comment]
Yes, I'm still trying to figure out why. That is clearly not intended.
