### ISSUE TITLE
Sonos binding

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#660]
migrated from Bugzilla [#478340](https://bugs.eclipse.org/bugs/show_bug.cgi?id=478340)
status ASSIGNED severity *normal* in component *Binding* for *---*
Reported in version *unspecified* on platform *PC*
Assigned to: Kai Kreuzer

On 2015-09-24 14:44:51 -0400, Kai Kreuzer wrote:

> A Sonos binding has been developed at openHAB 2. It is rather stable now and should be migrated to Eclipse SmartHome.
>
> PR has been created: https://github.com/eclipse/smarthome/pull/463

**Comment by maggu2810** [comment]
Fixed by #548
