### ISSUE TITLE
[MQTT] brokerId must be a configuration parameter of a broker

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#6600]
In ESH, EVERY thing/bridge must have at least one configuration parameter. The instance must NOT be determined by the ThingUID.

The MQTT Broker type is incorrectly modelled. `AbstractBrokerHandler` does a
```
this.brokerID = thing.getUID().getId();
```
Instead, this id must be taken from the Thing configuration (and thus must be declared in the config descriptions).

**Comment by kaikreuzer** [comment]
@davidgraeff Another one for you.

**Comment by davidgraeff** [comment]
Thanks for the catch, must have slipped my eyes. `SystemBrokerHandler` is still relying on this.

**Comment by kaikreuzer** [comment]
Any chance to come up with a fix for this until tomorrow? We are about to finalise the 0.10.0 release and imho this must be fixed as it otherwise will lead to incorrectly set up brokers.

**Comment by davidgraeff** [comment]
I just checked:
1. The discovery is assigning a "brokerid" property.
2. The ESH-Inf/thing-types.xml misses a configuration parameter for "brokerid".
3. The `SystemBrokerHandler` class is not using configurations.

I have no eclipse installation available right now and will use the Github webeditor to fix each point individually. No 2 being the most crucial one.
