### ISSUE TITLE
[Automation] Binding-actions cannot be used by Paper UI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#6602]
Testing the MQTT Action in the Paper UI, I am presented with

<img width="764" alt="screenshot 2018-11-29 at 16 08 59" src="https://user-images.githubusercontent.com/3244965/49230943-22202500-f3f1-11e8-937b-0cc83371ab6b.png">

There is no way to configure the topic or the value to send as those are inputs to the module and no configuration parameters.
Unfortunately, Paper UI does not support setting/handling inputs at all, so it seems that those binding actions are rather useless so far.

@davidgraeff May I ask how you are actually using the action? Do you use jsr233 scripted rules? I was actually looking at building a bridge to make the actions available to DSL rules (so that they can be a proper replacement for the MQTT 1.x action).

**Comment by kaikreuzer** [comment]
@J-N-K I was just looking into this issue: Considering that we say the Paper UI won't be adapted anymore, is there actually anything missing?
Afaics, the thing actions are nicely available in the old and the new rule engine, which you also [already use e.g. for DMX](https://www.openhab.org/addons/bindings/dmx/#rule-actions).

So I assume we can simply close this issue?

**Comment by J-N-K** [comment]
I think this can be closed.

**Comment by kaikreuzer** [comment]
Wonderful 👍 .
