### ISSUE TITLE
Unable to add new things between software releases

### ISSUE THREAD

**Issue by llamahunter** [eclipse/smarthome#6608]
Some bindings, notably the zwave one, are unable to add new device types between software releases because the data driven database of known things is hard coded into the plugin release, rather than being something that can be dynamically updated at runtime.

The maintainer of the zwave binding says this is a shortcoming in ESH, not his plugin implementation.  It appears from looking at the code that the data driven xml files can only be read from a compile time location in the jar?  It really would be much more flexible if they could be read from a filepath, so that additions/updates were possible without rebuilding from source code.  Otherwise, why make it data driven at all?

**Comment by cdjackson** [comment]
While this is true, I am also not keen on making the database separate from the binding, as it is often not just the XML files that change. The XML files trigger features in the Java code - if we separate the two (XML and code) then we have the problem that people will expect to be able to update the XML files without changing the Java, and this is not always true. We then have a configuration nightmare to make sure people run the right versions of code and XML.

I think we have discussed this in the past.

So, even if ESH allowed the XML to be read from another place, I would not be keen to support this split - code, and configuration, should be maintained together IMHO.

**Comment by kaikreuzer** [comment]
In general, a binding can implement its own thing type provider and feed this from anywhere (even an online database), so I don't see a shortcoming in ESH here.
For the specific Z-Wave case, @cdjackson has spoken and I agree that it makes life much easier to keep database/XML and Java code in sync.
