### ISSUE TITLE
LIFX : TimerTask depedency

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#661]
migrated from Bugzilla [#478000](https://bugs.eclipse.org/bugs/show_bug.cgi?id=478000)
status ASSIGNED severity *enhancement* in component *Binding* for *---*
Reported in version *0.8.0* on platform *PC*
Assigned to: karel goderis

On 2015-09-21 17:03:50 -0400, karel goderis wrote:

> Just to re-open a discussion we had some time ago on the LIFX binding (but for which I can not find back the thread).
>
> the LIFX binding, or it's underlying lib to be precise, depends heavily on Timer and TimerTasks to get things done. It creates a ton of these, and a lot of them linger in the ESH core
>
> I just want to discuss if we should modify the existing library and remove all TimerTask depedencies, or, as ESH will most probably be the only instance using this modified library, do away with the underlying lib and integrate it into the ESH LIFX binding, piggy-backing directly on the ThreadPools that are in place and so forth.
>
> I looked at the LIFX lib code, and I find it quite complex, and I sense that some stuff can be simplified when integrating directly into the ESH LIFX binding.
>
> What do you all think?
>
> Karel

On 2015-09-22 03:01:06 -0400, Kai Kreuzer wrote:

> FTR, the discussion you were looking for is here: https://github.com/openhab/openhab2/issues/328
>
> I think implementing the LIFX protocol on our own might be very complicated and I am not sure if we should spend these efforts (are you really willing to do that...?).
>
> The current lib (https://github.com/besherman/lifx-sdk-java) is a port/wrapper around the Android SDK, which is no longer officially maintained, but there seems to be some activity nonetheless in the past weeks: https://github.com/LIFX/lifx-sdk-android/commits/master.
>
> Another option, if starting completely new might be to use https://github.com/timothyb89/lifx-java as a basis. But this project looks rather stale as well by now.
>
> I am personally quite indifferent regarding the approach. What I think so is that there are many other people using the Android lib (for their Android apps), so joining forces with them might be beneficial to all.

On 2015-09-22 04:21:12 -0400, karel goderis wrote:

> I read you well.
>
> I have noticed that the actual code in ESH is a fork of the besherman fork, modified by dennis, and that it' structure is slightly different.
>
> On the other hand, LIFX clearly states that the life-sdk-android will no longer be maintained, and they have put effort on a clear LAN protocol documentation, which might be the structure to follow for protocol changes and so forth. I mean, it will not involve a lot of reverse-engineering, so maintaining a new code base would be doable based on that document
>
> I have only spent an hour or so in the code base, but I would recuperate a large part of the auxiliary classes that define the protocol data units and so forth, but get rid of the network/router code.
>
> In any case, we need to get rid of those pesky Timer(Task) threads. I have now a stable alpha2 running at home, just adding LIFX cripples the runtime, and after a few days it falls apart. The day we go Beta with ESH/OH2 that needs to be resolved anyways
>
> And you know me, yes, I would take time to develop a revised binding ;-) But I am ok to follow the route we decide to take
>
> K

On 2015-09-22 04:33:42 -0400, Kai Kreuzer wrote:

> As I said, I am indifferent regarding the approach taken.
> So feel free to take the decision that you feel is best and you will have my support for it. Just make sure that code that you might draw into the binding itself as sources is fully compatible regarding the license; from an IP perspective it is often easier to keep it as a separate jar.
>
> Just for the sake of completeness:
>
> 1. LIFX seems to concentrate a lot on their Cloud API; Dennis already asked whether this might be an option for the binding as well. As I am a strong supporter of the "IntTRAnet of Things", I don't like this idea and would prefer a local connection very much.
>
> 2. LIFX is very active in the Allseen Alliance and their latest product already speaks AllJoyn natively: https://community.lifx.com/t/lifx-bulb-communication-with-alljoyn/313
> I would expect that future firmware versions will also make the color bulbs AllJoyn compatible. Btw, I have started working on an AllJoyn binding (see https://github.com/kaikreuzer/smarthome/commit/SHA: 9b397f5a284e67334000d51edc2f073eb24a3a85), so this might in future also be an option for the LIFX binding.
> Who knows, maybe the current LIFX protocol is even replaced one day by Alljoyn support in their firmware? Maybe it is worth to ask on their plans in their community before spending too much efforts on implementing the current protocol...

On 2015-09-22 07:27:14 -0400, Dennis Nobel wrote:

> Karel, I thought about adding Cloud API support as an alternative option to the binding. As this relies on simple HTTP Requests, there would be no problem with performance and it´s quite easy to implement.
>
> Then we could use the local connection for demos and the Cloud API for productive installations. But I understand Kais concerns about privacy.
>
> If you want to implement a Java LIFX library based on the protocol specification this would be much better. It does not make sense if we both work on refactoring the binding. So if you say you want to start with that, I will not add cloud support.

On 2015-09-22 07:35:04 -0400, karel goderis wrote:

> Well, personally I am also not a fan of using the cloud API, not only because of privacy reasons, but it requires a working internet connection for one, and you have potential security issues to take into account. I also rather prefer the intranet approach. But that being said, I am just polling for some thoughts in the first place.
>
> I have not read up either piece of documentation produced by LIFX on the LAN and HTTP protocols, so I do not even know if these can be combined in a single binding, and/or whether we should design it in such a way that either one can be configured, or switched to/from.
>
> I needs a bit more study from my part I guess.
>
> K

On 2015-09-22 08:15:02 -0400, karel goderis wrote:

> mmh... this is really a complicated situation.
>
> Besherman is what we use today, but it is broken for the 2.0 firmware, but it's rather clean/complete in terms of data structures required. btw, it does not resemble the official SDK at all, is it really a wrapper?
>
> Timothyb89 has parts of 2.0 working but it is not complete, and uses another external lib (EventBus) from the same author
>
> LIFX has the full API now published. Their SDK is under MIT
>
> They are all on the MIT license, is that ESH-wise OK?
>
> Ideal situation would be to take the Besherman data structures (is that OK), revise them for the 2.0 firmware, and use those directly in the ESH binding. They only thing I would potentially consider is to create an additional OSGi service for the network stuff, and that each LifxLightHandler can bind to.
>
> I feel that one day or another, whatever external non-maintained lib we use, we will run into problems with respect to compatibility. Do we want to support something that we do not have full control over?
>
> Pfff...
>
> Karel

On 2015-09-22 08:25:34 -0400, Dennis Nobel wrote:

> > have not read up either piece of documentation produced by LIFX on the LAN and HTTP protocols, so I do not even know if these can be combined in a single binding, and/or whether we should design it in such a way that either one can be configured,
>
> The protocols are completely different. The Cloud API is simple HTTP and the local API is complex low-level TCP connection with a Google Protocol buffer protocol. My idea how to combine both was with different ThingHandler implementation and an additional LIFX Cloud Connector Thing Type, which can be configured manually. A new discovery service can be added, which adds lamps from the Cloud and the factory can decide which handler it´s instantiates.
>
> > Besherman is what we use today, but it is broken for the 2.0 firmware, but it's rather clean/complete in terms of data structures required. btw, it does not resemble the official SDK at all, is it really a wrapper?
>
> The current LIFX binding uses Version 1.0 of besherman (https://github.com/besherman/lifx-sdk-java/tree/release-1.0). This is a pure java fork of the original LIFX Android SDK. For some reason this version still works with new firmware.
>
> With version 2.0 of the library besherman has completely rewritten the library. And it seems to have problems with new firmware.
>
> > They are all on the MIT license, is that ESH-wise OK?
>
> Yes of course, MIT license is fine
>
> > I feel that one day or another, whatever external non-maintained lib we use, we will run into problems with respect to compatibility. Do we want to support something that we do not have full control over?
>
> So the only way would be to implement and maintain and own library, as we did for hue.

On 2015-09-22 09:19:13 -0400, karel goderis wrote:

> Having looked at the LAN protocol specs, I can only state that the original lib implementations were built overly complex. The protocol is rather simple, and very straightforward. I would not hesitate to implement that directly in the ThingHandlers.
>
> As you indeed say, the HTTP part is completely different. Maybe part of the ThingHandler can be factored out in a common baseclass, with each type of handler implementing the protocol bit, but that is to be seen as the HTTP part uses an OAuth2 authentication.
>
> I will put that on my to-do list ;-)
>
> K

On 2015-09-23 04:08:21 -0400, Kai Kreuzer wrote:

> > The protocol is rather simple, and very straightforward. I would not hesitate to implement that directly in the ThingHandlers.
>
> Ok, then go ahead - the issue is assigned to you now :-)
>
> FTR: The answer from LIFX seems to indicate that their bulbs will continue to support this protocol, so there is only a low risk that these efforts could be in vain.

On 2015-09-26 07:21:27 -0400, karel goderis wrote:

> Thanks
>
> First fact I noticed is that the V2 protocol of LIFX is quite different from the V1 whereby nowadays there are no PANs anymore involved, and every bulb is now identified with a MAC Address on the LAN. Makes you wonder how this stuff held up, maybe LIFX have secretly all bulbs talk both protocols.
>
> I am making good progress ;-)
>
> Karel

On 2015-09-26 08:41:16 -0400, Kai Kreuzer wrote:

> Afaik, they indeed decided to give up on the dual-stack (Wifi+6LoWPAN) and have all bulbs hooked up to Wifi directly. This probably makes their routing and thus their protocol much simpler.

On 2015-09-30 10:04:16 -0400, karel goderis wrote:

> Just a practical question: Which copyright statement should go in a .java that is at the basis a piece of code coming from an external lib, but that has been changed so much that it is quite different from the original?
>
> The LIFX binding is almost ready, that is, it is now adapted to V2 firmwares, and it has the same functionality as the current binding. But a lot of features can/could be added if we want to, but I am not sure if there is a real demand for those in the community.
>
> Karel

On 2015-10-07 07:35:01 -0400, karel goderis wrote:

> https://github.com/eclipse/smarthome/pull/483

**Comment by kgoderis** [comment]
Fixed with https://github.com/eclipse/smarthome/pull/483
