### ISSUE TITLE
[Homematic] Can't convert type QuantityType with value to FLOAT

### ISSUE THREAD

**Issue by Kavakuo** [eclipse/smarthome#6612]
I am currently unable to set a temperature for my homematic items on the last two OpenHAB milestone builds (M7, M6).
M6 includes everything from e7b0c783e8bae3f0467718748cff1220d508cdbb to 0b476cb49b4e1ffe13aa7d457846b135bb069c24
M7 includes everything from f25eae514e59d56f782e8787ee30686956cff8a1 to 369582877ce4c1adeed22c6de0efbc7c37b55244

The M5 milestone build as well as the binding shipped with OpenHAB 2.3 worked with the following setup: 

Item definition:
```
Number HM_Wohnzimmer_RTherm_SetTemp "Set Temperature"    (gTemperatureSet)  {channel="homematic:HM-CC-RT-DN:ccu:OEQ2084718:4#SET_TEMPERATURE"}
```

Rule:
```
rule "TestSwitch"
when
    Item TestSwitch changed to ON
then
    TestSwitch.sendCommand(OFF)
    var test = 20.5
    logInfo("Test", "set " + test.toString + " " + test.class.toString)
    logInfo("Test", "get " + HM_Wohnzimmer_RTherm_SetTemp.state.toString + " " + HM_Wohnzimmer_RTherm_SetTemp.state.class.toString)
    HM_Wohnzimmer_RTherm_SetTemp.sendCommand(test);
end
```

Log output (no error):
```
2018-12-01 21:13:11.626 [INFO ] [.eclipse.smarthome.model.script.Test] - set 20.5 class java.lang.Double
2018-12-01 21:13:11.641 [INFO ] [.eclipse.smarthome.model.script.Test] - get 21.5 class org.eclipse.smarthome.core.library.types.DecimalType
```

**M7, M6, M5 fail with the following setup:**
Item definition:

    Number:Temperature HM_Wohnzimmer_RTherm_SetTemp "Set Temperature"    (gTemperatureSet)  {channel="homematic:HM-CC-RT-DN:ccu:OEQ2084718:4#SET_TEMPERATURE"}

Rule:
```
rule "TestSwitch"
when
    Item TestSwitch changed to ON
then
    TestSwitch.sendCommand(OFF)
    var test = 20.5|°C
    logInfo("Test", "set " + test.toString + " " + test.class.toString)
    logInfo("Test", "get " + HM_Wohnzimmer_RTherm_SetTemp.state.toString + " " + HM_Wohnzimmer_RTherm_SetTemp.state.class.toString)
    HM_Wohnzimmer_RTherm_SetTemp.sendCommand(test);
end
````
Log output:
```
2018-12-01 21:08:53.026 [INFO ] [.eclipse.smarthome.model.script.Test] - set 20.5 °C class org.eclipse.smarthome.core.library.types.QuantityType
2018-12-01 21:08:53.035 [INFO ] [.eclipse.smarthome.model.script.Test] - get 20.5 °C class org.eclipse.smarthome.core.library.types.QuantityType
2018-12-01 21:08:53.055 [WARN ] [ematic.handler.HomematicThingHandler] - Can't convert type QuantityType with value '20.5 °C' to FLOAT value with DecimalTypeConverter for 'OEQ2084718:4#SET_TEMPERATURE', please check the item type and the commands in your scripts
```

I installed the homematic binding included in the M5 build of OpenHAB into an M7 OpenHAB installation and everything worked as before. So the issue is definitely in the binding and not in other components of OpenHAB. I tried many things to get the newer versions of the homematic binding working, passing float, double, DecimalType, QuantityType values as argument to `sendCommand` and use a `Number` or `Number:Temperature` as item definition. Nothing worked so far. 

Am I using the binding in a wrong way or is this currently a bug?

For reference the thread in the OpenHAB forum: [https://community.openhab.org/t/homematic-quantitytype-in-m6-build-problem/57432](https://community.openhab.org/t/homematic-quantitytype-in-m6-build-problem/57432)

**Comment by Kavakuo** [comment]
Some additional info: Changing the temperature using PaperUI/BasicUI also doesn't work. There are also more users affected, take a look at the thread in the OpenHab forum.

**Comment by MHerbst** [comment]
That's strange, because I am using also M6 and I can change the temperatures of my thermostats.

**Comment by Kavakuo** [comment]
Is your configuration different to mine? Can you post your Item definition and `sendCommand` function call?

**Comment by MHerbst** [comment]
This ist probably the difference. I currently don't have any rules for thermostats and the values are directly set. I can post my item and sitemap definitions tomorrow, but If the error only occurs in executed rules, then this explains why I don't had this problem.

**Comment by KHOne23** [comment]
are you are sure that it work? or do you mean that you use Homematic to set you Setpoint? Because openhab wrote in the Log that item changed but when you look on the Thermostate nothing changed.

**Comment by MHerbst** [comment]
Yes it works with this configuration:

item Definition:
``` 
Number HM_Kueche_Temp_Set "Neue Temperatur  [%.1f °C]" <temperature>  {channel="homematic:HM-CC-RT-DN:3014f711a0001f58a992f7f2:MEQ0799103:4#SET_TEMPERATURE"}
```
sitemap definition for this item:
```
Setpoint item=HM_Kueche_Temp_Set   minValue=5 maxValue=20 step=0.5
```
When I change the temperature via the setpoint widget in BasicUI the temperature is immediately updated.

I did not test the update via a rule and sendCommand.

**Comment by Kavakuo** [comment]
With this version of the binding it works here too. But this is the build from 17th November, that means it only includes everything up to and including 3745c6336250ac744ea65b88ec098e714303fb1e. I think the breaking changes are introduced with the commits at 19th November (711aa391f36b04b2463b60b3b187d974eeca549b and 0b476cb49b4e1ffe13aa7d457846b135bb069c24) by @mdicke2s. These commits also are included by the M6 and M7 builds of OpenHAB.

You can find a nice history view of the homematic binding [here](https://github.com/eclipse/smarthome/commits/master/extensions/binding/org.eclipse.smarthome.binding.homematic).

**Comment by MHerbst** [comment]
Just tried the latest openHAB build from today and with my configuration (i.e. without any rules regarding temperatures) it works fine.

I also tried it with rules and it worked correctly with and without unit.

First test with unit:
```
   var newValue = 19.5|"°C"
   HM_Kueche_Temp_Set.sendCommand(newValue)
```
Log messages:
```
19:26:36.977 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'HM_Kueche_Temp_Set' received command 19.5 °C
19:26:36.978 [INFO ] [arthome.event.ItemStatePredictedEvent] - HM_Kueche_Temp_Set predicted to become 19.5 °C
19:26:36.980 [INFO ] [smarthome.event.ItemStateChangedEvent] - HM_Kueche_Temp_Set changed from 18.00 to 19.5 °C
```
Remark: I had to use quotes arount the unit because without them I got an error (seems to be a new bug).

Without unit:
```
   var newValue = 19.5
   HM_Kueche_Temp_Set.sendCommand(newValue)
```

```
19:30:00.188 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'HM_Kueche_Temp_Set' received command 19.5
19:30:00.192 [INFO ] [arthome.event.ItemStatePredictedEvent] - HM_Kueche_Temp_Set predicted to become 19.5
19:30:00.195 [INFO ] [smarthome.event.ItemStateChangedEvent] - HM_Kueche_Temp_Set changed from 18.00 to 19.5
```
Everything seems to work correctly. 

Binding version is now: 0.10.0.201812032218

**Comment by KHOne23** [comment]
Strange, I updated today also to the new snapshot and when I change temp via setpoint on sitemap I get this error
[WARN ] [ematic.handler.HomematicThingHandler] - Can't convert type QuantityType with value '23 °C' to FLOAT value with DecimalTypeConverter for 'OEQ0845709:4#SET_TEMPERATURE', please check the item type and the commands in your scripts

**Comment by Kavakuo** [comment]
Installed the same binding version and it definitely doesn't work, same setup as yours. Neither the first nor the second approach works. Setting a temperature with PaperUI/BasicUI results in the same error. 

@MHerbst Can you try to install the M7 build of OpenHAB with the same binding version? Unfortunately I don't have a good OpenHAB testing environment...

**Comment by MHerbst** [comment]
@khalil2535 did you install a Homematic some time into the AddOns folder? If yes then maybe this older version is used instead of the current one. Removing the binding from the AddOns folder is not sufficient. You also need to clean the cache and tmp folder.

@MHerbst I can do some more tests tomorrow. I have got a separate test environment where I can try it.

**Comment by khalil2535** [comment]
> @khalil2535 did you install a Homematic some time into the AddOns folder? If yes then maybe this older version is used instead of the current one. Removing the binding from the AddOns folder is not sufficient. You also need to clean the cache and tmp folder.
> 
> @Kavakuo I can do some more tests tomorrow. I have got a separate test environment where I can try it. Please also make sure that you don't have any older version somewhere in the cache.

I think you meant someone else @MHerbst

**Comment by MHerbst** [comment]
Ooops, sorry. Too many user names starting with a "K"...

**Comment by khalil2535** [comment]
Never mind ❤️️ thanks for eclipse

**Comment by Kavakuo** [comment]
To clarify, I only used the karaf console to install other binding versions into the system and always saw in the log that the binding restarted. 

Is there a simple way to just compile a single binding instead of the complete project? According to the error log message ([src](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/converter/type/AbstractTypeConverter.java#L96)),  I think one problem could be that the `sendCommand()` always passes a `QuantityType` Object to the binding, even if a float is passed to it. In addition the binding seems to select always the `DecimalTypeConverter`, even if the item is defined with `Number:Temperature` where it should select the `QuantityTypeConverter` ([src](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/internal/converter/ConverterFactory.java#L42)). At next it tries to convert a `QuantityType` with a ´DecimalTypeConverter` to a `float` ([src](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/handler/HomematicThingHandler.java#L281) which seems to fail.

**Comment by MHerbst** [comment]
Every binding has it's own maven pom file and you can execute the package goal for this pom. This will only build the binding.

**Comment by KHOne23** [comment]
found some new things. i deleted one of the Thermostates from Openhab and reinstall it and now it works fine!

**Comment by mdicke2s** [comment]
Mhhh, due to the content of the warning, it looks like `QuantityTypeConverter#toBindingValidation(..)` returned false. That means either the HmDatapoint (which is based on data from the CCU) was not of number type, or the command that was sent to the channel was not a QuantityType (which should not apply as long as you use `|°C` in the script).

I do not understand how re-pairing the thermostats solved the issue, but due to https://community.openhab.org/t/homematic-quantitytype-in-m6-build-problem/57432/22 it helped at least in two installations.

Unfortunately the warning doesn't contain much information about the datapoint (except for its name). I wonder if that changed somehow....

**Comment by MHerbst** [comment]
@KHOne23 This explains why I was not able to reproduce it. I used a completely fresh installation.

**Comment by KHOne23** [comment]
@MHerbst That is the reason i tryed to delete and readd the Thermostate. Maybe it comes because i did a CCU Update 2 Days before i see the Error the first time.

**Comment by Kavakuo** [comment]
That‘s good to know, but I think we should definitely find the reason for this problem and a way to avoid this annoying workaround. 

I can do some additional tests next week when I‘m back at home. My OpenHab installtion still has this problem after upgrading the binding.

**Comment by stsccl** [comment]
I'm facing this issue too with the current openhabian installation 2.4.

**Comment by mdicke2s** [comment]
@Kavakuo I cannot confirm your 2nd observation. It does not generally return `Number` but is dependent on how `Channel#acceptedItemType' was set when initializing the channel. For the homematic binding this is done at the following lines:
https://github.com/eclipse/smarthome/blob/1b83d4610c1604cd2e4faa859b0238e21dc04d87/extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/handler/HomematicThingHandler.java#L196-L199

What kind of configuration do you use?
I have plain eclipse smarthome connected to a CCU2. I used discovery / PaperUI to things/items and for instance the ChannelUID `homematic:HM-WDS40-TH-I-2_1_TEMPERATURE` comes with `acceptedItemType=="Number:Temperature"`

**Comment by Kavakuo** [comment]
@kaikreuzer This issue is not closed by b57bbb1 as I mentioned in the pull request. 

@mdicke2s I use OpenHAB and the problem occurs since M6, which includes everything up to 0b476cb regarding the homematic binding as mentioned in my opening post. 
The things are discovered by PaperUI and the items are defined inside a `.items` file. A channel which is faced by the problem is `channel="homematic:HM-CC-RT-DN:ccu:...:4#SET_TEMPERATURE` (see my first post).

To wrap it up, the problem only occurs after updating the OpenHAB installation from <2.4 M5 to >2.4 M6. After the update the things have to be removed with PaperUI and added back. If you do this, everything works as expected, but that is a pretty bad user experience.

>  It does not generally return Number but is dependent on how `Channel#acceptedItemType' was set when initializing the channel. 

When is a channel initialized? Only the first time when a thing is added to the installation or after every reboot? `acceptedItemType` is **ALWAYS** `Number` as long as you do not reinitialize the thing with PaperUI. I tried to reboot the installation, to change the item definition to `Number:Temperature` in the `.items` file, to clean the cache, to remove the item and add it back etc. Nothing of this triggered a refresh of the `acceptedItemType` property. 

That would not be a problem at all, but the `sendCommand()` function always passes a `QuantityType` command value to `HomematicThingHandler`. The `acceptedItemType` of the channel is still `Number` (because it is not somehow refreshed), that means the binding tries to convert a `QuantityType` to `float` using a `DecimalTypeConverter` which obviously don't work.

### Reproducing the problem
1. Install a binding version before 0b476cb
2. Add a thermostat thing with PaperUI and define a `SET_TEMPERATURE` channel inside a `.items` file
3. Update the binding to the newest version
4. Try to change the temperature
5. Error occurs

### Workaround to fix the problem
1. Remove the thing with PaperUI
2. Initialize the removed thing with PaperUI again

If you don't see a problem here, everything is good. But this has to be communicated somewhere in my opinion. 

 ## Possible solution
*Maybe* you should use the type of the command instead of `acceptedItemType` to choose the converter, because the converter should convert the command value type to the right type for `HmDataPoint`.
https://github.com/eclipse/smarthome/blob/b57bbb1f4346707912a37c2f2f358d952755b8cf/extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/handler/HomematicThingHandler.java#L280

**Comment by Kavakuo** [comment]
You can use OH2.4 together with an older working version of the binding. Look at [this post](https://community.openhab.org/t/solved-homematic-quantitytype-in-m6-build-problem/57432/17) in the OpenHAB forum.

**Comment by adahmen** [comment]
Thx a lot !!!
This solved my problems and homematic is back :-)

Do you know if there will be a fix in a coming version of this binding?

**Comment by lhurt** [comment]
@kaikreuzer This issue still exists with 2.5.0M4. Is it possible to reopen this ticket?

**Comment by MHerbst** [comment]
@lhurt The Homematic binding have moved back to the openHAB repo. Please create a new issue here: https://github.com/openhab/openhab2-addons/issues. It is possible that this is a duplicate to this issue: https://github.com/openhab/openhab2-addons/issues/6102?
