### ISSUE TITLE
[MQTT] implementation and documentation differ

### ISSUE THREAD

**Issue by J-N-K** [eclipse/smarthome#6614]
When configuring a channel in a `topic` thing, The description says 

> MQTT state topic 
An MQTT topic that this thing will subscribe to, to receive the state. This can be left empty, the channel will be state-less then and will publish values non-retained.

However, if this field is left empty, no connection is set for the `ChannelState` which results in the thing going to `OFFLINE` state after a `handleCommand` is called (`setValue` throws and exception if `connection` is `null`).   

Either the documentation or the code is wrong here.

**Comment by davidgraeff** [comment]
Thanks for the fix. I've not used a channel as a command only channel yet. I was waiting for #5131 to implement enum like string command channels correctly.
