### ISSUE TITLE
WeMo Binding : Enhancements for WeMo Bridge and UPnP Discovery / GENA Events

### ISSUE THREAD

**Issue by hmerk** [eclipse/smarthome#662]
I have actually implemented support for the WeMo Bridge to the Binding and thus being able to switch or dim the WeMo LED Bulbs.

Discovery of standalone devices and bridge is handeld by registering an UPnP discovery participant, the bulbs will be discovered by a custom discovery service.

Controlling the devices/bulbs is not done by using UPnP actions, due to some reliability issues with Belkins UPnP Implementation in combination with JUPnP.

GENA Events are also implemented to react better on device updates (very important for motion sensor), but this still has some issues on reliability. Therefore, device updates will still be polled every 60 seconds.

@kaikreuzer, like we discussed earlier, there is a need for custom UPnP serach methods. I don't really know how to implement this into the core. Anybody to step in ???

My next steps are : Clean up all my code changes and documentation, create a PR against JUPnP for the WeMo Service hydration (RecoveringUDA10ServiceDescriptorBinder), do some more testing and then reate a PR for my binding changes.

If all goes well, PR should be here before Christmas :-)

Best
Hans-Jörg

**Comment by kaikreuzer** [comment]
> @kaikreuzer, like we discussed earlier, there is a need for custom UPnP serach methods. I don't really know how to implement this into the core. Anybody to step in ???

I thought that Belkin reverted their changes in the firmware again, so that no custom search is required with current firmwares anymore. Is that a wrong assumption? Could you be so kind to summarize (or link to our old discussion) the exact requirements here?

**Comment by hmerk** [comment]
No,they did not. Please find our previous discussion here : 
Reimplement UPnP discovery to WeMo Binding #461

In my IDE, I added
+        ServiceType wemoBasicEvent = new ServiceType("Belkin", "basicevent");
+        upnpService.getControlPoint().search(new ServiceTypeHeader(wemoBasicEvent));
to org.eclipse.smarthome.config.discovery.internal.UpnpDiscoveryService.java
which is not a good solution, cause it implements Belkin specific code into core bundles.
You and Markus suggested to extend the UpnpDiscoveryParticipant.

**Comment by hmerk** [comment]
@kaikreuzer, sorry, I was absolutely wrong, Belkin indeed changed it back to RootDevice search.
So we only would have to add
        upnpService.getControlPoint().search(new RootDeviceHeader());
as a second search to UpnpDiscoveryService.

Would this be ok for you ????

**Comment by hmerk** [comment]
Closed cause of merge
