### ISSUE TITLE
Unit definition °C without quotes leads to rule parsing error

### ISSUE THREAD

**Issue by MHerbst** [eclipse/smarthome#6630]
Since openHAB M7 (resp. latest openHAB build from today) it is no longer possible to use the unit "°C" without quotes.

This assignment in a rule:
```
var newValue = 19.5|°C
```
leads to the following messages
```
19:41:52.864 [INFO ] [del.core.internal.ModelRepositoryImpl] - Refreshing model 'test.rules'
19:42:05.318 [WARN ] [del.core.internal.ModelRepositoryImpl] - Configuration model 'test.rules' has errors, therefore ignoring it: [7,24]: no viable alternative at input 'Â'
```
After changing the value to `19.5|"°C"` the rule is parsed without messages and the value is interpreted correctly.

I have tried it with OH Build 1443 and with this version both unit format worked.

**Comment by MHerbst** [comment]
Will check it again tomorrow. You are right, in this case I have used a different editor, but the encoding was UTF-8 and it looked ok in VSCode.

**Comment by htreu** [comment]
@MHerbst please close here if the issue is resolved for you. thanks.

**Comment by MHerbst** [comment]
@htreu I prefer to leave it open right now. I have tested it with 2.4 and the problem still occurs on Windows 10. The same rules file works on my Raspberry. So it seems that we have a different behaviour on Windows and Linux :-(. 

I assume the the cause of the problem lies in this call: https://github.com/eclipse/smarthome/blob/88f45523624dc45fe270f1bc50126a116c66946d/bundles/model/org.eclipse.smarthome.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java#L94
According to the Apache JavaDocs this method uses the platform's default encoding. This may be different on Linux and Windows. If this is true we should better explicitly use an encoding (preferably UTF-8). 

BTW: it seems that the documentation contains no hint about the encoding of the textual configuration files.

**Comment by MHerbst** [comment]
The problem is definitely caused by different default encodings. I have added `-Dfile.encoding=UTF-8` to the java parameter list and with this option it works correctly on windows.

Is there anything against requiring UTF-8 for all textual config files and setting the UTF-8 charset explicitly in this call? In this way, we would avoid problems caused by platform-specific default encodings.

WDYT? @htreu  @kaikreuzer

**Comment by MHerbst** [comment]
Unfortunately there is no real default encoding on Windows. It sometimes depends on the country. The VSCode editor uses UTF-8 by default. Therefore I would suggest that also on Windows we only support UTF-8 and document it.
BTW: I did not test it yet, but I assume that a sitemap that is not encoded in UTF-8 would cause display problems if special characters like ° or Umrlauts are used.

**Comment by kaikreuzer** [comment]
I don't remember the details, but I think we once decided to have config files always as UTF-8 and at the time we had the Eclipse SmartHome Designer, this was configured to always use UTF-8, which solved the issue for Windows.
Not sure if something similar is possible for the VS Code Extension - if so, this might be the best solution (and we should add a note to the documentation about expecting UTF-8).

**Comment by MHerbst** [comment]
> Not sure if something similar is possible for the VS Code Extension - if so, this might be the best solution (and we should add a note to the documentation about expecting UTF-8).

VSCode has a global setting for the encoding, which is by default UTF-8. Will check whether we can also add a file-specific encoding.

Where would you add the documentation node? Only once in the Configuration Overview ()https://www.openhab.org/docs/configuration/) or better adding a note to each file description (Things, Items. Sitemaps, ...).

**Comment by MHerbst** [comment]
Created a PR in openhab-distro. Documenation updates will follow. The issue can be closed here
