### ISSUE TITLE
Chart not showing historical values

### ISSUE THREAD

**Issue by Flole998** [eclipse/smarthome#6631]
I have a few charts at the URL /chart?groups=xxx&period=h&theme=bright&t=yyyy, I noticed in Milestone 7 that those charts (which are using the rrd4j database in the background) are no longer showing historical values, instead a constant line is plotted for the current value no matter how far I want to go back.

**Comment by derkens** [comment]
I had the same thing, after specifiying service="rrd4j" the historic values where used.

**Comment by Flole998** [comment]
Thanks, that's also fixing it for me. It somehow thinks it's a good idea to use the mapdb for that, could we somehow add "priorities" as a mapdb for a chart is kinda useless.

**Comment by derkens** [comment]
Could it be related to "default persistence"in paperui? Mine is set to mapdb..

**Comment by Flole998** [comment]
Mine is also set to mapdb, but the chart should know that and filter that like it did in previous versions somehow.

**Comment by tavalin** [comment]
@Flole998 without specifying how would the chart function know that you specifically wanted to use rrd4j and not one of the many other persistence services?

**Comment by Flole998** [comment]
@tavalin It shouldn't know that I want to use rrd4j but I should know that I don't want to use mapdb, on my installation there is only rrd4j available then so it could choose that one. It could also query all the persistence services until it finds one that has data (and is not mapdb), and if no better alternative is found try mapdb. But seriously, who would chart the last value only?

**Comment by tavalin** [comment]
Mapdb is perhaps a slightly odd persistence service but charting is only one consumer of the persisted data.  There are other use cases where mapdb is well suited such as restoreOnStartup.

The system picks the default persistence service unless you specify the service so it sounds like mapdb is selected as your default.  Why not change your default (to rrd4j) or simply specify the service in the URL?

**Comment by Flole998** [comment]
Restoreonstartup is exactly what I've been using mapdb for and that's also why I have it set as default persistence service (not sure if that's needed though).

The point is: It was working fine until I switched to the milestone releases, and as I wasn't the only one there will probably be more people affected during the release.
