### ISSUE TITLE
ClassicIconProvider- Consider min & max when determining the icon

### ISSUE THREAD

**Issue by marcelrv** [eclipse/smarthome#665]
When using the heating icons, these go nicely from heating-0 to heating-100
When rendering the set temperature with this icon, in most cases the icon looks rather cold as temperature is set to 10 or 20.

In the channel  a min & max level is defined `<state min="5" max="25" pattern="%.1f °C" readOnly="false">` would be good to calculate the icon not based on the direct state value, but instead on the % based on the rage. (e.g 25 would be equal to heating-100 icon, 20C would be  (20-5) /(25 - 5) = 75

**Comment by triller-telekom** [comment]
Even though the channel has `min` and `max` values we should not scale the value in an item's state.
For your use case I would rather propose to have a different temperature category, i.e. "room_temperature" that has different icons at a range between 0 and 50.

@kaikreuzer @sjka Can you please close this as "Won't fix"?

**Comment by kaikreuzer** [comment]
I agree that a general mapping from [min,max] to [0,100] for determining an item won't be valid solution - to cover such use cases, we would probably need a feature that allows more fine-grained control over the icon generation/selection.
