### ISSUE TITLE
Paper UI [RFC]: Change first page

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/smarthome#6653]
At the moment the first page on Paper UI is the control page.

I propose to have a ESH/Implementation installation details page as first/home page instead. I'll explain my reasons.

* Paper UI is supposed to be a management / maintenance UI. Controlling items, showing item states is not the main purpose and Paper UI is not really good at presenting controls.
* The control page is empty right after installation.
* There is no system / framework / java vm state page yet. It is of much interest though how much of the jvm ram is used, the processor usage, the framework version, a few links to documentation and legal information.
* The start page could also link into the different sections of PaperUI depending on the context. If no Things are setup yet, but something is in the Inbox, a note can be shown to the user.

An image to describe the idea of a system status page:

![s3](https://user-images.githubusercontent.com/66436/49689085-4fb94c80-fb1c-11e8-8553-d838b8987835.png)

WDYT?

**Comment by maggu2810** [comment]
IMHO in general good idea.
As the Paper UI is part of the framework the solution should be platform and product independent.
So, we should not depend on special platform architecture (caused by native code), JVM options that need to be set on startup, ...

**Comment by davidgraeff** [comment]
Paper UI is modified for openHAB and every implementor is free to modify it as well, I don't think it hurts to show the running (ESH) version by default for example.

Some jvm paramaters can be retrieved, like the memory:
```
public static void main(String [] args) {
	int mb = 1024*1024;
	Runtime runtime = Runtime.getRuntime();
	System.out.println("Used Memory:" + (runtime.totalMemory() - runtime.freeMemory()) / mb);
	System.out.println("Free Memory:" + runtime.freeMemory() / mb);
	System.out.println("Total Memory:" + runtime.totalMemory() / mb);
	System.out.println("Max Memory:" + runtime.maxMemory() / mb);
}
```
