### ISSUE TITLE
org.jupnp doesn't check all headers specified by UPnP Device Architecture  2.0 

### ISSUE THREAD

**Issue by TheTmirror** [eclipse/smarthome#6655]
Hey there,

right now I'm implementing a new binding for a custom device. I use upnp as the discovery method. To keep track of the upnp registry I registered a RegistryListener (org.jupnp.registry.RegistryListener). I want to act everytime one of the following methods get called:

1. remoteDeviceAdded(...)
2. remoteDeviceUpdated(...)
3. remoteDeviceRemoved(...)

Firstly inside these methods I want to check if the bootid changed, but I noticed a strange thing: org.jupnp doesn't accept the Upnp Headers BOOTID.UPNP.ORG , CONFIGID.UPNP.ORG and SEARCHPORT.UPNP.ORG . In the debugging it says: 

> 19:15:45.110 TRACE o.j.model.message.UpnpHeaders[:58] - Parsing all HTTP headers for known UPnP headers: 9
[some messages left out for clearity - this isn't part of the log]
19:15:45.110 TRACE o.j.model.message.UpnpHeaders[:65] - Ignoring non-UPNP HTTP header: Bootid.upnp.org

I thought it was a mistake on my side, like i spelled something wrong or such. But it seems to be a fault by jupnp. I digged a bit into the source code an I found the following (sry it's not possible to place the first half into the codeblock, I don't know why):

```
protected void parseHeaders() {
        // This runs as late as possible and only when necessary (getter called and map is dirty)
        parsedHeaders = new LinkedHashMap();
        log.trace("Parsing all HTTP headers for known UPnP headers: " + size());
        for (Entry<String, List<String>> entry : entrySet()) {

            if (entry.getKey() == null) continue; // Oh yes, the JDK has 'null' HTTP headers

            UpnpHeader.Type type = UpnpHeader.Type.getByHttpName(entry.getKey());
            if (type == null) {
                log.trace("Ignoring non-UPNP HTTP header: " + entry.getKey());
                continue;
            }

            for (String value : entry.getValue()) {
                UpnpHeader upnpHeader = UpnpHeader.newInstance(type, value);
                if (upnpHeader == null || upnpHeader.getValue() == null) {
                    log.trace(
                        "Ignoring known but irrelevant header (value violates the UDA specification?) '{}': {}", 
                            type.getHttpName(), value);
                } else {
                    addParsedValue(type, upnpHeader);
                }
            }
        }
    }
```

In this parseHeader Method is the method UpnpHeader.Type.getByHttpName(...) called. This returns all Upnp Headers that Jupnp knows. If a header should be parsed which Jupnp doesn't know, then it flags it as "non-UPNP" header and ignores it. But the above named ignored headers are specified as "required" by [Universal Plug and Play Device Architecture 2.0 Page 23-34](url). So these headers are defently needed UPnP headers.

These are the "known" UpnpHeader by jupnp (code view broken again -sry). You can find them in org.jupnp.model.message.header.UpnpHeader$Type:

```
USN("USN",
                USNRootDeviceHeader.class,
                DeviceUSNHeader.class,
                ServiceUSNHeader.class,
                UDNHeader.class
        ),
        NT("NT",
                RootDeviceHeader.class,
                UDADeviceTypeHeader.class,
                UDAServiceTypeHeader.class,
                DeviceTypeHeader.class,
                ServiceTypeHeader.class,
                UDNHeader.class,
                NTEventHeader.class
        ),
        NTS("NTS", NTSHeader.class),
        HOST("HOST", HostHeader.class),
        SERVER("SERVER", ServerHeader.class),
        LOCATION("LOCATION", LocationHeader.class),
        MAX_AGE("CACHE-CONTROL", MaxAgeHeader.class),
        USER_AGENT("USER-AGENT", UserAgentHeader.class),
        CONTENT_TYPE("CONTENT-TYPE", ContentTypeHeader.class),
        MAN("MAN", MANHeader.class),
        MX("MX", MXHeader.class),
        ST("ST",
                STAllHeader.class,
                RootDeviceHeader.class,
                UDADeviceTypeHeader.class,
                UDAServiceTypeHeader.class,
                DeviceTypeHeader.class,
                ServiceTypeHeader.class,
                UDNHeader.class
        ),
        EXT("EXT", EXTHeader.class),
        SOAPACTION("SOAPACTION", SoapActionHeader.class),
        TIMEOUT("TIMEOUT", TimeoutHeader.class),
        CALLBACK("CALLBACK", CallbackHeader.class),
        SID("SID", SubscriptionIdHeader.class),
        SEQ("SEQ", EventSequenceHeader.class),
        RANGE("RANGE", RangeHeader.class),
        CONTENT_RANGE("CONTENT-RANGE", ContentRangeHeader.class),
        PRAGMA("PRAGMA", PragmaHeader.class),
        
        EXT_IFACE_MAC("X-CLING-IFACE-MAC", InterfaceMacHeader.class),
        EXT_AV_CLIENT_INFO("X-AV-CLIENT-INFO", AVClientInfoHeader.class);
```

Any thoughts and opinions on this? Is there a way to correct the implementation?

**Comment by maggu2810** [comment]
@TheTmirror I fixed your comment formatting by using the correct code blocks mark.
A code block is marked by placing **triple** backticks.
See: https://help.github.com/articles/creating-and-highlighting-code-blocks/

I agree with @lolodomo that this problem should be reported and discussed upstream:
https://github.com/jupnp/jupnp/

**Comment by TheTmirror** [comment]
@maggu2810 thanks for the correction, I'm quite new to the issues forum.

@maggu2810 and @lolodomo . Wasn't sure about it due to the fact that jupnp is based on the external project [Cling](https://github.com/4thline/cling). Is it somehow possible to move an issue to another project (I guess not, would be dumb) or is it a good idea to start a new issue there and link this issue? Or should I create a completly new issue and don't link this one?

**Comment by maggu2810** [comment]
AFAIK jUPnP is a fork Cling as this one has been no longer maintained.
If you want to report a bug and create a fix for jUPnP the jUPnP repository (and so its issue tracker) is the right place for.
There is no "move issue to another project" in Github (at least I don't know about).
Just create a new issue at jUPnP.
I don't think you need to link the issue as there is no other information present in this issue except your first comment. Just report it upstream, add a comment here "moved to <link>" and close this issue.

**Comment by hmerk** [comment]
Cling is still maintained except the OSGI part....

**Comment by maggu2810** [comment]
Am Mo., 10. Dez. 2018 um 20:30 Uhr schrieb Hans-Jörg Merk <
notifications@github.com>:

> Cling is still maintained except the OSGI part....
>

Are you sure?
The README in the repository tells another story:
https://github.com/4thline/cling/blob/master/README.md

>
