### ISSUE TITLE
[mqtt] Wrong decimal representation in Number channels

### ISSUE THREAD

**Issue by bodiroga** [eclipse/smarthome#6662]
Hi @davidgraeff!

I don't know if I'm doing something wrong, but I'm seeing strange values in mqtt number channels. In my case I'm using a Homie device with latest ESH code base (I have done a git pull before the tests). Here you have what is being publish on the mqtt broker (using mosquitto_sub client):

```
homie/homie-3-temperature-sensor/temperature/temperature 24.49
homie/homie-3-temperature-sensor/temperature/humidity 57.70
```
And this is what is being received by the item (through the channel):

```
2018-12-11 13:57:32 - mqtt_homie300_embedded_mqtt_broker_homie_3_temperature_sensor_temperature_temperature updated to 0.24490000
2018-12-11 13:57:32 - mqtt_homie300_embedded_mqtt_broker_homie_3_temperature_sensor_temperature_temperature changed from 0.22350000 to 0.24490000
2018-12-11 13:57:32 - mqtt_homie300_embedded_mqtt_broker_homie_3_temperature_sensor_temperature_humidity updated to 0.57700000
2018-12-11 13:57:32 - mqtt_homie300_embedded_mqtt_broker_homie_3_temperature_sensor_temperature_humidity changed from 0.65640000 to 0.57700000
```
(Same values can be seen in Paper UI control tab, all values are 100 times smaller)

The configuration of the channel seems to be correct:

- Unit: %
- Settable: false
- Format: 0-100
- Name: Indoor humidity
- Retained: true
- Data type: float

I don't see anything wrong in the device, but something has changed recently, because a couple of weeks ago everything went smoothly. Any clue? :confused: 

Thanks for your support!

Aitor

**Comment by davidgraeff** [comment]
Someone has reported this on the forum as well.
Instead of parsing values myself I'm using the ESH core class TypeParser.
It seems to misinterpret values, but I wonder why the test suite didn't catch this.
This is show stopper for OH 2.4, bummer.

**Comment by maggu2810** [comment]
Need to look at the code but it looks like a mix of DecimalType and PercentType.

**Comment by davidgraeff** [comment]
TypeParser takes a list of possible types as an argument. In my list PercentageType appears before DecimalType. I guess what happens is that PercentageType grabs any value between 0 and 100 and outputs a value between 0-1 if converted to a string.

**Comment by maggu2810** [comment]
For `PercentType` the value must be in range `[0;100]`.
If the percent type value is requested as `DecimalType` (see `PercentType.as(...)` method, the value is diviced by 100.
Which item type is used?

**Comment by bodiroga** [comment]
I can confirm that the fix has solved the problem, that was really fast!

Thank you guys! :+1:

**Comment by vzorglub** [comment]
I have just upgraded to #1459
And it is not fixed
```
2018-12-12 10:57:07.319 [vent.ItemStateChangedEvent] - LargeBedroom_ThermostatAmbientTemp changed from 0.169 °C to 0.182 °C
```
Value sent `18.2`

**Comment by bodiroga** [comment]
Hi @vzorglub!

With "1459" you are talking about openHAB's snapshot version number, right? If that's the case, don't worry, as Kai pointed out [here](https://github.com/eclipse/smarthome/issues/6497#issuecomment-439368199), the openHAB snapshot version usually doesn't include the latest ESH repo code, a build has to be manually triggered. My test has been done using the Eclipse IDE and there everything works correctly now, so the issue is, in fact, fixed :wink: 

Please, delete your newly created issue :+1:

**Comment by vzorglub** [comment]
When can we expect the fix in the SNAPSHOT, please?

**Comment by bodiroga** [comment]
Ask @kaikreuzer, kindly, to build a new stable version of ESH and this fix will be included in the next snapshot :wink:
