### ISSUE TITLE
MQTT: implement transformationPattern for trigger channels

### ISSUE THREAD

**Issue by rachetfoot** [eclipse/smarthome#6679]
I have a button that send events in the form of:

{"battery":100,"voltage":3095,"linkquality":57,"click":"single"}

I would like to base rules on the kind of click, but there doesn't appear to be any way to process the json to match the click type. I expected to be able to process the trigger value in the rule, but this doesn't appear to be possible aside from exact string matching (not useful in this case). Using a transformation in the trigger would solve this nicely.

**Comment by davidgraeff** [comment]
Hm. Not sure about this. You can process the value in your rule anyway.
You mean, you want your rules to be simpler, by just reacting to this trigger. And the trigger channel itself would perform a transformation and payload comparison before even firing?

**Comment by rachetfoot** [comment]
Can I? I tried to look for a way to process the trigger value, but as far as I can see the trigger value is not accessible from the rule action.

I managed to solve this in a better manner anyway in a fork of zigbee2mqtt that publishes to /click instead of sending json, so this change is not necessary for my purposes.

**Comment by maggu2810** [comment]
> I managed to solve this in a better manner anyway in a fork of zigbee2mqtt that publishes to /click instead of sending json, so this change is not necessary for my purposes.

@rachetfoot Can you close this issue then?

**Comment by rachetfoot** [comment]
I'm hesitant to do so, since I still think this will be useful, but sure, here goes.
