### ISSUE TITLE
channel state options

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#669]
I want to use channel state options.

The astro binding already uses this one, so I first tried this one.
- adding a thing-type of id "moon".
- the thing-type moon contains the channel group moonPhase
- the channel-group-type moonPhase contains the channel phaseName
- the channel phaseName uses options

`````` text
    <channel-type id="phaseName">
        <item-type>String</item-type>
        <label>Moonphase name</label>
        <description>The name of the current moon phase</description>
        <state readOnly="true">
            <options>
                <option value="NEW">New moon</option>
                <option value="WAXING_CRESCENT">Waxing crescent</option>
                <option value="FIRST_QUARTER">First quarter</option>
                <option value="WAXING_GIBBOUS">Waxing gibbous</option>
                <option value="FULL">Full moon</option>
                <option value="WANING_GIBBOUS">Wanning gibbous</option>
                <option value="THIRD_QUARTER">Third quarter</option>
                <option value="WANING_CRESCENT">Waning crescent</option>
            </options>
        </state>
    </channel-type>```

The console log contains:
```text
2015-12-07 15:26:33 [INFO ] [smarthome.event.ItemStateEvent:43   ] - astro_moon_d6778ab2_phase_name updated to WANING_CRESCENT
``````

Current situation:
- the basic UI does not show a value for "Moonphase name"
- the classic UI does not show a value for "Moonphase name"

I changed the XML attributes of state to this one:

``` text
        <state pattern="%s" readOnly="true">
```

Now the two UIs show "WANING_CRESCENT" for "Moonphase name".

I inspected the function "public String getLabel(Widget w)" of org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl that looks for the pattern using the StateDescription.
But I cannot find any line in the rendering process that replaces the values by the correct option.

Could someone point me to the code that uses the option(s)?

Another question about the "getLabel(...)" function:
- getStateDescription is first called to check for null
- if not null: getStateDescription is called to check if the pattern is not null
- if not null: getStateDescription is called to fetch the pattern

Shouldn't we store the first result of getStateDescription? It seems that the process to build the return value of that function is not such trivial as there are many line of codes that are executed.
I will create a PR if you are fine with this changes, later...

So, what have I to do, to get the values of the options in the UI instead of the raw values?

**Comment by lolodomo** [comment]
@maggu2810  :  is ir an issue to be clised (PR merged(  ?

**Comment by maggu2810** [comment]
> is ir an issue to be clised (PR merged( ?

If you mean "Is this an issue to be closed (PR merged)?" then I need to check.
The issue that has been merged is only about the "store and reuse the result of ...".

If the issue itself -- handling of state options -- has been solved, needs to be checked.
I add it on my todo list.

**Comment by lolodomo** [comment]
Please take a look to issue #2729 that looks similar.

**Comment by maggu2810** [comment]
It looks very similar.
I assume @sjka or @kaikreuzer (both comment the related issue) can state if it is the same.

**Comment by kaikreuzer** [comment]
If I understand the issue here right, I would agree that it is a duplicate - so let's close this one here.
