### ISSUE TITLE
[Homematic] no automatic value update after upgrade to OpenHAB 2.4

### ISSUE THREAD

**Issue by macmeck** [eclipse/smarthome#6700]
After upgrading my OpenHAB 2.3 installation to 2.4, the Homematic items won't update their values any more. When I restart OpenHAB, the current (correct!) values are being retrieved from the CCU1 but they don't update during normal operation. Manually refreshing the datapoints works as well.

The log does not give any indication on what could be wrong. Am I missing an important step after the upgrade?

**Comment by macmeck** [comment]
Am I the only one having this issue? For all other Homematic users it's working fine?
@gerrieg, did you see something similar during testing?

**Comment by gerrieg** [comment]
Without more details it's hard to say what's wrong. There is no special upgrade step for Homematic. Did you set the callbackHost bridge parameter?

**Comment by macmeck** [comment]
Yes, the `Callback Network Address` is set and the configuration works fine in OpenHAB 2.3. 

I will try to strip down my setup to isolate the relevant parts and send a trace log in the next couple of days.

**Comment by macmeck** [comment]
Okay, here we go with a trace log: [openhab.log](https://github.com/eclipse/smarthome/files/2710255/openhab.log)

**Comment by gerrieg** [comment]
Set the callbackHost to 172.17.0.1 and not to openhab.xundheit, maybe the CCU can't resolve the name.

**Comment by macmeck** [comment]
Hm, that seems to do the trick, thanks! So this is something within core OH and not the binding. There seems to be a change somewhere that does the name resolution in a different way. As I said, OH2.3 was fine (also after downgrading) and OH2.4 seems to need the IP Address.
