### ISSUE TITLE
No “switch” channel for Dresden Elektronik FLS-CT Ip 

### ISSUE THREAD

**Issue by Max-1968** [eclipse/smarthome#6701]
I have several Dresden Elektronik FLS-CT Ip controllers. They are reported by the Hue bridge API as follows:

	"27": {
		"state": {
			"on": true,
			"bri": 25,
			"ct": 500,
			"alert": "none",
			"colormode": "ct",
			"reachable": true
		},
		"type": "Color temperature light",
		"name": "XXXXXXXXXXX",
		"modelid": "FLS-CT",
		"manufacturername": "dresden elektronik",
		"uniqueid": "XXXXXXXXXXXX",
		"swversion": "0214.201000CF"
	}
In PaperUI the channels for brightness and color temperature show up fine, however the channel to switch them on/off is missing, even under “extended” view. I guess it is because the modelid “FLS-CT” is not known yet to the Hue binding. Right now I get around this by changing brightness to 0/100 or such, but it would be nice to have the switch channel as well.

**Comment by kaikreuzer** [comment]
The brightness channel supports ON/OFF, therefore there is no need for an additional switch channel.
