### ISSUE TITLE
"API incompatibility" on model.core

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#6717]
It seems that some update on Eclipse dependencies causes our build to fail (see https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/3198/console):

```
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.14.0:compile (default) on project org.eclipse.smarthome.model.core: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.14.0:compile failed: An API incompatibility was encountered while executing org.eclipse.xtend:xtend-maven-plugin:2.14.0:compile: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.batch.FileSystem.getClasspath(Ljava/lang/String;Ljava/lang/String;ZLorg/eclipse/jdt/internal/compiler/env/AccessRuleSet;Ljava/lang/String;Ljava/util/Map;)Lorg/eclipse/jdt/internal/compiler/batch/FileSystem$Classpath;
```

**Comment by kaikreuzer** [comment]
Strangely, a local build of the latest master works for me. Where could be the difference for the Jenkins build?
https://github.com/eclipse/xtext-xtend/issues/493 looks like this problem.

**Comment by MHerbst** [comment]
I remember a similar strange problems in our company after we changed the Tycho version to 1.2.0. Maybe it could help to go back to 1.1.0.

**Comment by kaikreuzer** [comment]
@MHerbst I ran https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/3200/ with Tycho 1.1.0, didn't help either :-(

**Comment by MHerbst** [comment]
@kaikreuzer  I have found this issue in the XTEXT Repo: https://github.com/eclipse/xtext/issues/1373#issuecomment-449001543 According to this issue it helps to pin org.eclipse.emf.codegen to 2.11.0.

**Comment by kaikreuzer** [comment]
Thanks @MHerbst, I have created https://github.com/eclipse/smarthome/pull/6722.
