### ISSUE TITLE
Adjust hue binding for hue API whitelist changes

### ISSUE THREAD

**Issue by dominicdesu** [eclipse/smarthome#672]
The API of the username whitelist for the hue bridge will change in the coming months: http://www.developers.meethue.com/documentation/important-whitelist-changes

Starting in February 2016, it will probably not be possible anymore to whitelist custom users on the hue bridge. As the current binding implementation uses this functionality, it will be necessary to update the binding before the bridge update is rolled out.

Same as ticket openhab/openhab#3258.

**Comment by kaikreuzer** [comment]
Yes, that's a very important issue to work on indeed.
Any volunteers to implement it?

**Comment by dominicdesu** [comment]
I am currently looking into it if that is okay :-)

**Comment by kaikreuzer** [comment]
Definitely :-)

**Comment by dominicdesu** [comment]
One remark:
When a new Hue Bridge Thing is added to ESH, a username generated by the bridge is used. If the bridge thing is then deleted from ESH, the username remains on the whitelist of the bridge until it is manually removed. Rediscovering and adding the Hue bridge again will generate a new username.

It would be possible to automatically remove the username from the hue whitelist when the bridge thing is deleted from ESH. However, I didn't implement this in the current solution as this would also remove custom usernames (possibly used in other applications as well) from the whitelist (e.g. set via the settings page in PaperUI). Please let me know what you think about this, I can add the relevant code if necessary.
