### ISSUE TITLE
[mqtt 2] Contact not reacting on incoming message

### ISSUE THREAD

**Issue by gijbelsy** [eclipse/smarthome#6738]
I have the following setup:
Broker: Mosquitto
Openhab v2.4.0 on Raspbian
MQTT binding version: 0.10.0.oh240

Thing created via PaperUI, and added channel 'Contact'.
I'm receiving a string with TRUE or FALSE as payload.
When using the transformation "On/Open value" and "Off/Closed value" nothing happens.
The log outputs the following: 
`[WARN ] [generic.internal.generic.ChannelState] - Command 'FALSE' not supported by type 'OpenCloseValue': No enum constant org.eclipse.smarthome.core.library.types.OpenClosedType.FALSE`

When the item to wich the channel is linked has an 'undefined' state, the first update works. It changes to 'open' (TRUE), but remains in that state forever.

**Comment by gijbelsy** [comment]
Update:

This only happens when receiving the string message from my device.
When I publish the same message with MQTTspy, all functions normally.
I also investigated the payload with MQTTspy, but I can't find any difference.

**Comment by gijbelsy** [comment]
Solved: The payload was sending an illegal character at the end of the string.
Therefore TRUE and FALSE are not recognised.
It might be better to add the character count to the logging, since it's not showing the illegal character.

**Comment by maggu2810** [comment]
Feel free to add PRs with improvements of the current code base.
