### ISSUE TITLE
add a widget change event for UIs

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#674]
Through the REST+SSE API, transformation and formatting is lost for values on widgets, since the UI can only listen to ItemStateChangedEvents.
Although we plan to introduce a new sitemap concept, for the time being it would be helpful to have such events available for the current sitemaps, so that UIs can make use of it.
See also https://github.com/eclipse/smarthome/issues/640.

**Comment by lolodomo** [comment]
@kaikreuzer : isn't it something already implemented?

**Comment by kaikreuzer** [comment]
Yes, you are right, this has been implemented with https://github.com/eclipse/smarthome/pull/2030.
