### ISSUE TITLE
[onewire] Support for DS2409 MicroLan Coupler

### ISSUE THREAD

**Issue by Anders-Nielsen** [eclipse/smarthome#6754]
Hi @J-N-K 

As requested at the Openhab community site - [link](https://community.openhab.org/t/onewire-request-for-support-of-extended-deviceids/61398)

Support for the DS2409 device, which is used to segment the OneWire network into smaller networks - simple setup can be seen here - [Link](https://www.maximintegrated.com/en/images/appnotes/4930/4930Fig01.gif)

Relevant links:

- owfs.org man page for DS2409 -[Link](http://owfs.org/index.php?page=ds2409)
- owf.org man page for hubs based on DS2409 [Link](http://owfs.org/index.php?page=ds2409-microhub)
- Application note from Maxim, explaining the use of DS2409, as well as alternatives - [Link](https://www.maximintegrated.com/en/app-notes/index.mvp/id/4930)
- Datasheet - [Link](https://www.maximintegrated.com/en/ds/DS2409.pdf)

**Comment by J-N-K** [comment]
Can this be cascaded? So we can get `1F.xzy/main/1F.abc/aux/28.fgh`?

**Comment by Anders-Nielsen** [comment]
Yes they can, but I have not tried it myself - in my setup I only have one.

I have however a few DS2409's I can wire up for testing purposes, if needed?

**Comment by J-N-K** [comment]
I have an idea how this could be done, I‘ll go for that after #6626 has been merged. It makes no sense to do it before as it would take quite some effort to track all changes over different branches (I already have four development branches for OneWire).

**Comment by Anders-Nielsen** [comment]
Great, and thanks for taking time to look into this. Makes sense to get the other issues away first, and the old binding is working fine for now, so no rush as far as I am concerned.

**Comment by Anders-Nielsen** [comment]
..... sorry :-( I hit the wrong button
