### ISSUE TITLE
Command/State properties

### ISSUE THREAD

**Issue by t-8ch** [eclipse/smarthome#6755]
It would be nice to be able to attach additional properties to commands or states.
This would allow bindings and rules to add additional information to those entities and would allow them to provide more functionality.

### Usecases

* Attach a transitiontime to commands to a `Color` Channel

* Attach metadata to commands received by a `String` channel attached to a messaging protocol (for example sender information)

### Alternative

It would probably be possible to create custom commands for the combinations.
IMO this would get out of hand very fast and would introduce a lot of complexity for type conversions.

**Comment by cdjackson** [comment]
I fully agree. This is something I've raised a few times on the OH forum (although I can't find the links) and [ESH](https://www.eclipse.org/forums/index.php/m/1759688/#msg_1759688), but it's never really got anywhere.

**Comment by kaikreuzer** [comment]
This would make it RPCs and not events anymore. That would create huge issues with support in UIs etc.

The solution ESH provides for parametrised function calls are "actions", which allow to provide parameters on specific functions of a binding, see e.g. https://www.openhab.org/addons/bindings/mqtt.generic/#rule-actions.
