### ISSUE TITLE
Minify PaperUI sources during build

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#676]
In order to increase loading speed and reduce network traffic, the sources for the Paper UI should be minified in a build step.
Also, it makes sense to look into merging as many files together as possible, in order to reduce the number of HTTP requests.

**Comment by GradyD** [comment]
Is it possible to do this using gulp or grunt from nodeJS? Is this is a possible solution I can easily create this step.

**Comment by kaikreuzer** [comment]
I am not familiar with all this javascript tooling, so maybe @sjka, @dnobel, @sja or @aounhaider1 have an idea of what might be the best approach?

**Comment by sja** [comment]
Yes, I think gulp should provide the most transparent tasks. Or WebPack, but that one is full of conventions which have to be known. So gulp + uglify should do it.

**Comment by kaikreuzer** [comment]
>  So gulp + uglify should do it.

We would need to request them as a build-time dependency CQ, I guess.
Is it possibly to run these steps nicely within a Maven build?

@sja: Grady is struggling with setting up a suitable dev env for working on the Paper UI - if you have any good advice, please share it on https://www.eclipse.org/forums/index.php/t/1073385/ - thanks!

**Comment by sja** [comment]
Gulp and uglify is already in use by paperui. So the frontend-maven-plugin is the key to get this working.

**Comment by GradyD** [comment]
Looking at the pom.xml associated with the paper UI right after bower it just needs like,

```
<execution>
    <id>gulp build</id>
	<goals>
		<goal>gulp</goal>
	</goals>
	<configuration>
		<arguments>build</arguments>
	</configuration>
</execution>
```

I'm not showing gulp included in the `org.eclipse.smarthome.ui.paper` jar. It does look like the basic UI is using grunt to minify the files but it does not look to be apart of the maven build with `frontend-maven-plugin`. Both of these look pretty simple from a node build prospective. 

What would you consider the 'core' UIs that should be built and included with maven?

**Comment by kaikreuzer** [comment]
> What would you consider the 'core' UIs that should be built and included with maven?

Not sure what you exactly mean? Clearly all UIs need to be built with Maven, but none of them is 'core', since it is up to the solution which UIs are made available (therefore they all reside in https://github.com/eclipse/smarthome/tree/master/extensions/ui)

**Comment by kaikreuzer** [comment]
Implemented through https://github.com/eclipse/smarthome/issues/873
