### ISSUE TITLE
[astro] astro:sun:1411b2fa:morningNight#start incorrectly always at midnight

### ISSUE THREAD

**Issue by andrekoeln** [eclipse/smarthome#6774]
When I create an astro thing with coordinates not in my timezone but e.g. 9.7,99.9 in Asia the "morning night start" is set to midnight. See attached scrrenshot for two astro thing with locations in Asia (left) and Germany (right).

Expected Behavior:
It should be set to midnight in the other timezone which gets recalculated to time in my timezone.

Steps to Reproduce (for Bugs)
Just create an astro thing with above coordinates, add all items and check in Paper UI Control.
![astro-morning_night](https://user-images.githubusercontent.com/46106186/50591213-b0734500-0e8e-11e9-8ade-efd3b65b06f1.jpg)

**Comment by cweitkamp** [comment]
The code for the binding has been moved to the openHAB 2 Add-ons repositories a few months ago. From now on it will be maintained over there. This issue can be closed in favor of https://github.com/openhab/openhab2-addons/issues/4446.
