### ISSUE TITLE
Slider does not support minValue and maxValue (like Setpoint)

### ISSUE THREAD

**Issue by FlorianSW** [eclipse/smarthome#6776]
See the documentation on the openHAB (the open source reference implementation of Eclipse smarthome) regarding the slider and setpoint:
https://www.openhab.org/docs/configuration/sitemaps.html#element-type-setpoint

The example for both widgets uses the example of a temperature changer to change the temperature in the kitchen. While the setpoint allows the user to add a min and max value, when using the slider, the user of the UIs can make a mistake and, e.g., set the temperature to 100° C.

The way to solve this could be to use a setpoint in this case (which is not the only case where this issue applies[1]), however, in comparison of both does the setpoint allow a more exact setting of the target value with the disadvantage of less usability, while the slider allows a more useable way of setting the target value, which might not be as easy to set the exact value again (as the user has to "slide").

In my little opinion, I don't see a reason, why the slider should not allow to have a min and max value, like the setpoint, too. This would allow people to decide, what they want: a way to set the fine-grained value exactly with less usability (e.g. this might be useful for temperatures) or to use a slider when the value needs to be set faster and it doesn't matter if it is exactly a specific value (e.g. when setting the brightness, which is more or less a "feeling" of the user whilde setting it).

[1] Another scenario might be a binding, which exposes the brightness of a lamp as a number going from 0 to 255, instead of a percenttype from 0 to 100. A setpoint would be needed to set the brightness above of 100, which is not really useable compared with a slider (which unfortunately hardcodes to 100 as a max value).

**Comment by gnalbandian** [comment]
This should be ported to openhab-core. 
Max/Min values still not supported in OH2.5 snapshot

**Comment by timbms** [comment]
@gnalbandian: please check with the latest iOS beta build. It should work now

**Comment by gnalbandian** [comment]
It does! Thanks!
