### ISSUE TITLE
[MQTT]Feature-request: Percentage channel does not recognise ON and OFF state.

### ISSUE THREAD

**Issue by gijbelsy** [eclipse/smarthome#6789]
@davidgraeff :  ##The percentage channel of the Generic MQTT binding does not recognise the ON or OFF state, in contradiction to the Color channel.
Is it possible to add this with the next release?
It would be nice that you can define the value for the ON state, so we're able to store the previous state, and re-send it with the ON command.

**Comment by davidgraeff** [comment]
@maggu2810 that got fixed
