### ISSUE TITLE
Astro Binding "Thing Configuration" Description Incomplete

### ISSUE THREAD

**Issue by bgilmer77** [eclipse/smarthome#6814]
Problem description:  The documentation says, "All Things require the parameter `geolocation`".  But there is no information about where this parameter is entered.

Proposed solution:  Provide documentation on how to set the system geolocation, either through the Paper UI or through a `.things` file, e.g. with a specific example, such as an `astro.things` file containing the following:

`astro:sun:local [ geolocation="33.750960,-84.389731,100" ]`

**Comment by clinique** [comment]
Binding documentation already contains this example : 
`astro:sun:home  [ geolocation="52.5200066,13.4049540,100", interval=60 ]
`

I think this could be closed

**Comment by maggu2810** [comment]
Makes sense.
