### ISSUE TITLE
FS internet radio binding: Replace apache http client with jetty http client

### ISSUE THREAD

**Issue by paphko** [eclipse/smarthome#682]
The FS internet radio binding initially uses 'org.apache.commons.httpclient'.
As discussed in its initial pull request https://github.com/eclipse/smarthome/pull/429 this client should be replaced with the jetty http client. Discussion about http clients in ESH: https://www.eclipse.org/forums/index.php/t/1069192/

**Comment by triller-telekom** [comment]
Since PR #1864 is merged already this bug can be closed. I just had a look at the current master branch and I don't see any reference to Apache HttpClient anymore. All references have been replaced with Jetty.

@kaikreuzer can you please close this bug?

**Comment by kaikreuzer** [comment]
Indeed, thanks for noticing.
