### ISSUE TITLE
[Homematic] No error in case of a wrong gatewayAddress

### ISSUE THREAD

**Issue by itn3rd77** [eclipse/smarthome#6820]
In case you entered a wrong gatewayAddress inside the `homematic.things` file. The binding silently fails without any warning or error message logged. In my case a DNS record was not updated correctly and it took me ages to figure out what was wrong.

e.g.
```
Bridge homematic:bridge:homematic [ gatewayAddress="nonexisting.local.home" ...
```

A log message with priority error is highly appreciated.

**Comment by maggu2810** [comment]
There is already a log message and the description of the status already contains the message of the specific exception.

See: https://github.com/eclipse/smarthome/blob/f2a1f38/extensions/binding/org.eclipse.smarthome.binding.homematic/src/main/java/org/eclipse/smarthome/binding/homematic/handler/HomematicBridgeHandler.java#L127

Have a look at the log severity in the developer guidelines.
