### ISSUE TITLE
Using MQTT in a new Binding

### ISSUE THREAD

**Issue by JakobSpi** [eclipse/smarthome#6836]
Hi,

I want to connect a hardware (not important for you) to my openhab2 system over mqtt.
Therefore i would like to create a new Binding, which uses MQTT to communicate with the hardware. Am i importing the mqtt-binding in the dependencies for the new binding osgi-like, or coding the mqtt connection on my own?

Thanks

**Comment by maggu2810** [comment]
Please use the Eclipse SmartHome forum for such questions.
I don't see any issue with the current code base (this is what issue is used for).
