### ISSUE TITLE
[UOM] Avg group function with Dimensionless Items have unit 'one'

### ISSUE THREAD

**Issue by openhab-5iver** [eclipse/smarthome#6843]
I have [groups of OpenWeatherMap](https://github.com/OH-Jython-Scripters/openhab2-jython/blob/master/Community/OpenWeatherMap/automation/jsr223/community/openweathermap/owm_daily_forecast.py) Humidity and Cloudiness Items built with...
```
add_item("Forecast_Cloudiness_{:02d}".format(3 * index), item_type="Number:Dimensionless", label="Forecast ({:02d}): Cloudiness [%d %unit%]".format(3 * index), category="Sun_Clouds", tags=["OpenWeatherMap"])
```
The groups are built with...
```
add_item("gForecast_Cloudiness_" + str(index), item_type="Group", groups=["gForecast_" + str(index)], label=dayOfWeek + ": Cloudiness [%d %unit%]", category="Sun_Clouds", gi_base_type="Number:Dimensionless", group_function=ArithmeticGroupFunction.Max(), tags=["OpenWeatherMap"])
```
The Items display properly...
![image](https://user-images.githubusercontent.com/21967853/51085001-0a7ed080-1701-11e9-80d0-f653ec307243.png)
... but the groups have unit 'one'...
![image](https://user-images.githubusercontent.com/21967853/51084981-d60b1480-1700-11e9-84e2-849739bb3bfe.png)

**Comment by clinique** [comment]
I've written a unit test for this, it seems to be working as expected.

**Comment by maggu2810** [comment]
See openhab/openhab-core#588
