### ISSUE TITLE
Swipe support functionality for ZWave devices 

### ISSUE THREAD

**Issue by dastrix80** [eclipse/smarthome#6849]
HI All

Does anyone know when this will be added to ESH/OpenHab? It would be great to have swipe control for remote devices to control dimming switches and or volume controls using devices such as the Aeotec Wallmote

Im happy to help in anyway I can 

thanks
Kris

**Comment by kaikreuzer** [comment]
There is neither Z-Wave support at ESH nor is this the right place for questions - you'd rather want to ask at https://community.openhab.org/.
