### ISSUE TITLE
Hue binding: Workaround for Osram Lightify PAR16 is applied to all lights

### ISSUE THREAD

**Issue by dominicdesu** [eclipse/smarthome#686]
Recently, a workaround for Osram Lightify PAR16 has been added (#518). 
However, because [this check in HueLightHandler](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java#L91) always evaluates to true, this workaround is applied to all lights.

The tests do no catch this issue because in the tests the initialize() method is only called for the Osram Lightify PAR16.

**Comment by kaikreuzer** [comment]
Uh, wow, this is indeed a bug that I missed when reviewing. Thanks for noticing!
