### ISSUE TITLE
[homematic] Can't convert type DecimalType with value '3000.0' to FLOAT value with QuantityTypeConverter 

### ISSUE THREAD

**Issue by real-easy** [eclipse/smarthome#6868]
hello,

i try in english but, its not so good (im german..).

since i update my OH from an 2.4 snapshot (2.4.0.201811021724) to the 2.4 stable i had an problem with my analog output.
now i tested the last 2.5 snapshoot there is still the same problem.

i read something about this problem with setting temperatures, but i have not an problem with the termperatures. may be this is already fixed.

i think its an problem with the homematic binding.

my hardware is an wired homematic io modul (HMW-IO-12-Sw14-DR).
here is one output configured as analog.
the value must be set as frequency.

in paper-ui looks like this:
homematic:HMW-IO-12-Sw14-DR:ccu2:NEQxxxxxxx:7#FREQUENCY

if i try to set the frequency to an vale i get an error message like this:

[WARN ] [ematic.handler.HomematicThingHandler] - Can't convert type DecimalType with value '3000' to FLOAT value with QuantityTypeConverter for 'NEQ0308230:7#FREQUENCY', please check the item type and the commands in your scripts

now i removed the fixed value in script an change to an float-variable.
but i get the same error message:

[WARN ] [ematic.handler.HomematicThingHandler] - Can't convert type DecimalType with value '3000.0' to FLOAT value with QuantityTypeConverter for 'NEQ0308230:7#FREQUENCY', please check the item type and the commands in your scripts

if i try to set the value in the homematic gateay, there is no problem.

but by the way the value for the frequency still is only an integer in range from 0 to 65535 in the homematic gateway, not an float.

bevore the update to the 2.4.0 stable this was never a problem.
i dont change the script since the last 2 years.

can someone understand this ?

thx a lot...

ps: i tested something but post in the wrong repo, this can be read here:
https://github.com/openhab/openhab2-addons/issues/4611

**Comment by robbyb67** [comment]
Did you try to remove and re-add the thing in PaperUI ? I had to do this to make my thermostats and gateway-extras (for numeric HM variables) work again.

Nevertheless in my opinion its a design flaw in OH/ESH that many things have to be removed an re-added after an upgrade...

**Comment by real-easy** [comment]
thanks for answer...

my things are in  .thing files my items in a .item files. (like OH V1.8)

in my opinion it is not possible to add all the thing for a whole house every time again for a new version.

for my update i started the empty OH2.5.0 at first ime without my conf files.
then i added the bindings (homematic, mqtt, mysql ...) with the paper UI.
then i logged out and shutdown OH.
now i copied my things, items, rules and config files in the conf folder.
(i do this for the 2.4. stable and for the 2.5. snapshot, 17.01.2019.)

so i get all my things and items in OH without the discovery functionality of paper UI.

if i was right, then in this variant of config, it is not possible to delete the thing and re-add them.
i think with this update method, OH will generate the things/items after adding the files new.

**Comment by real-easy** [comment]
today i updated to buil 1512, this problem is still there ...

**Comment by real-easy** [comment]
today, update to build 1549 and the problem is still there.

is this the right place for this problem ???

**Comment by openhab-5iver** [comment]
No... ESH is no longer maintained. You'll find the homematic binding  here... https://github.com/openhab/openhab2-addons/issues.
