### ISSUE TITLE
[Tradfri] [Californium] Update to 1.0.7?

### ISSUE THREAD

**Issue by hreichert** [eclipse/smarthome#6880]
Recently californium 1.0.7 was released that contains a bugfix needed for Tradfri (#6065)

I can't find a way to integrate this new version in the ESH build.
Maybe this has to be done by a ESH maintainer; or please tell me what's the correct procedure.

**Comment by kaikreuzer** [comment]
Did you see https://github.com/eclipse/smarthome/issues/6065#issuecomment-457212591?
