### ISSUE TITLE
Network binding is not properly working with ARP tools

### ISSUE THREAD

**Issue by kpanchen** [eclipse/smarthome#6882]
Currently as of OH 2.4 Network Binding is not properly working with ARP tools and does not support windows tools and not displaying property status correctly.

Discussion is here:
[https://community.openhab.org/t/network-presence-binding-update/65461](url)

**Comment by kaikreuzer** [comment]
Please check https://github.com/openhab/openhab2-addons/issues for existing issues about this and if none is reported so far, create one with a proper description on how to reproduce and include log files. Thanks!
