### ISSUE TITLE
MQTT2.4:addon How to extend a autodetected Home300 node.

### ISSUE THREAD

**Issue by skoona** [eclipse/smarthome#6888]
@davidgraeff Thanks for all your work on this add-on.  It was the introduction of this add-on that offered me a look at the Homie convention, another excellent project.   

I have several Homie devices that provide motion, temperature, and humidity readings.  They were properly auto-detected and the channels respond as expected.  My question is: 'How to extend an auto-discovered device by defining more channels for the existing homie data elements?'

I'd like to show ip address, state, etc in my OpenHab2 sitemaps and I haven't found the `Home300` entitiy.  (I prefer text files)

James,

**Comment by davidgraeff** [comment]
Good question. The current state of affair is that Homie Things and Channels are independent, non-documented and automatically created entities.

My afterthoughts are that this decision was actually a bad design. For OH 2.5 I'm aiming at re-using the MQTT Generic Thing and Channel Types for all Homie discovered Things and Channels. And at this point it should be no issue to define those via textual configuration.

For now you would need to use your own generic mqtt think and remodel the Homie topic structure with self-defined channels.

**Comment by skoona** [comment]
Generic it is.  Thanks for the quick response.
