### ISSUE TITLE
New rule engine: CheckNow rule (same as IFTTT CheckNow)

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#689]
smhgit commented on Oct 30
I have posted this issue in the forum (https://www.eclipse.org/forums/index.php/t/860533/) but I think it is more accurate to discuss this option here.

(If you still wants to keep the discussion in the forum I can close this issue).

**Comment by danchom** [comment]
kaikreuzer commented on Nov 1
The feature makes sense for me, but I leave the decision of whether or not to follow up on it here to @marinmitev as this is his branch :-)

**Comment by danchom** [comment]
This is good feature for testing purposes. It can be done as special trigger type which sets context (trigger outputs) base on its configuration.

**Comment by kaikreuzer** [comment]
Ok, picking this up again: I think this is a very useful feature that should be implemented.

The RuleRegistry could have a new method "runNow(ruleUID)", which skips triggers&conditions and directly executes the actions of the rule. This should always be possible unless an action has a mandatory input that is linked to a trigger; in that case, we should not execute the actions, but set the rule status to IDLE with an according message.

**Comment by maggu2810** [comment]
Is it common (the title refers to IFTTT) to skip the condition on a manual trigger?

I would assume, that I trigger the rule manually and so the given triggers are not evaluated but I have assumed that the condition are checked before the action is executed.
Don't know what is common practice.

Perhaps there should be a distinction between trigger action and trigger rule execution.

**Comment by kaikreuzer** [comment]
IFTTT does not have conditions, so this is not a good reference for answering that question.
I as a user would think something is broken, if I click "run now" and nothing happens. So I would assume that skipping the coditions is a logical way to do it.

**Comment by kgoderis** [comment]
> Ok, picking this up again: I think this is a very useful feature that should be implemented.

FYI I had implemented an "empty" trigger to simulate this behaviour, but if we change the API in that way of course that is a better solution.

**Comment by maggu2810** [comment]
> I as a user would think something is broken, if I click "run now" and nothing happens. So I would assume that skipping the coditions is a logical way to do it.

I think this depends if I trigger a rule execution or I trigger the rule's action.

Example
* trigger: motion sensor changed to ON
* condition: illumination < 500
* action: set light to ON

I assume
* if I trigger the rule manually and if the illumination is lower then 500, the light is switched on. If the illumination is greater or equal 500, the light state is unchanged
* if I trigger the action manually the light will be switched on

**Comment by kaikreuzer** [comment]
> I assume [...]

@maggu2810 This is exactly my suggestion, isn't it?

**Comment by maggu2810** [comment]
Okay, then my reading is not correct.
I just read about trigger the action of the rule.

I would like to have both, trigger action execution (skip trigger & condition) AND trigger rule execution (skip trigger only).

But if that fits to your suggestion, all is fine :wink:

**Comment by kaikreuzer** [comment]
> I would like to have both
> But if that fits to your suggestion

Hm, no, sorry, I must have misread your comment then.
I don't think that we should introduce two features here at the same time (this might become confusing in the API as well as in the UI).

I would go for the "trigger actions" solution for now since I believe that many conditions will depend on trigger outputs and thus this feature anyhow won't apply to those rules (and in turn this feature is less helpful since not applicable). If you feel afterwards that another feature is lacking, which also respects the conditions, we can enter a new issue for that. Is that ok for a start?

**Comment by maggu2810** [comment]
Ok

**Comment by haltmann** [comment]
Hi,

I've just found something really interesting and OMG ... it's  amazing, just take a look <http://ambition.spencerchen.com/e4qxirss>

Pardon my monkey thumbs, herbert.altmann@heal-it.info
