### ISSUE TITLE
Proposal: Transformation Parameters

### ISSUE THREAD

**Issue by thewilli** [eclipse/smarthome#6891]
It would be benefital if one could provide optional parameters to transformations. This might be a default value for transformations that might fail or a context. The latter one could come especially handy in the JS transformation. If an additional parameter could be provided, one could simply reuse chunks of code that behave similar without the need for massive redundancy.

Seems to me (without being too much into it, sorry if I'm wrong) that [this signature](https://github.com/eclipse/smarthome/blob/f2a1f38/bundles/core/org.eclipse.smarthome.core.transform/src/main/java/org/eclipse/smarthome/core/transform/TransformationService.java#L51) might be a showstopper for this.

**Comment by davidgraeff** [comment]
This project is abandoned
