### ISSUE TITLE
Javadoc outdated (again)

### ISSUE THREAD

**Issue by mnlipp** [eclipse/smarthome#6894]
The Javadoc on the [web site](https://www.eclipse.org/smarthome/documentation/javadoc/index.html) is still for 0.9 while the current version seems to be 0.10.

**Comment by maggu2810** [comment]
Hm, as this project is not maintained anymore and has been migrated to openHAB Core ...
... does it matter?

**Comment by mnlipp** [comment]
Mmh, I didn't know. Could you provide me with a pointer how the project is structured by now? Is the statement that ["OpenHAB is an Eclipse SmartHome based project"](https://www.heise.de/developer/artikel/Episode-57-openHAB-und-Eclipse-SmartHome-4001692.html) no longer true? The [Eclipse SmartHome Website](https://www.eclipse.org/smarthome/) does not mention that is has been given up as base.

**Comment by maggu2810** [comment]
See #6883
I assume the links contains the information you need.

**Comment by mnlipp** [comment]
Thanks.
