### ISSUE TITLE
 [Bug] Rule Engine - enable/disable rules

### ISSUE THREAD

**Issue by itskeKs** [eclipse/smarthome#6895]
The Rule Engine within Version 2.4 and 2.5 (also within beta releases of 2.5) does not properly reenable Rules.

Expected Behavior

If a Rule is disabled and reenabled through another rule it should be active and working.

Current Behavior

When the Rule disables another rule it first changes to "uninitialized" state then switches to disabled. When such a rule gets executed it does not execute included commands for example turn on the lights.

Possible Solution

none btw. i had to downgrade oh to 2.3 to get it back to work as expected.

Steps to Reproduce (for Bugs)

Create a rule which disables another rule, Create a rule which enables the disabled rule. Execute the disabler then the enabler.
Execute the disabled and then reenblaed rule. This should end up with not executing the included actions.
Context

I have rules which disable rules for turning on lights during daytime. For example i disable rules which turn on the lights through movement detection after 8am and enable them back at 6pm.

Your Environment

RasPi 3, OpenHab 2.3.0 (at the moment) tried with 2.4.0 and above (including betas). Installed from the repo through apt-get.

**Comment by openhab-5iver** [comment]
#6883. ESH is no longer maintained, and has been reintegrated into openhab-core. Pleade open an issue in that repo, but please check to see if this has already been reported.
