### ISSUE TITLE
FR: BasicUI: Sort group items by item label

### ISSUE THREAD

**Issue by stefanhaustein** [eclipse/smarthome#6897]
Hi, I am quite happy with the Basic UI in general... However, it would be great if group items would be ordered by label by default. 

Supporting sorting by any property would be even better (I have seen a forum entry where somebody wanted to sort a group of 100 items by battery level), but label should be a very good starting point / default.

**Comment by openhab-5iver** [comment]
See #6883. For openHAB UIs, you want this... https://github.com/openhab/openhab-webui/issues.

**Comment by stefanhaustein** [comment]
Thanks for the pointer!

**Comment by stefanhaustein** [comment]
p.s. Wouldn't be bad to have this on the eclipse/smarhome page
