### ISSUE TITLE
[UoM] Absolute vs. Relative Temperature

### ISSUE THREAD

**Issue by keilw** [eclipse/smarthome#6898]
There was a discussion prior to https://github.com/unitsofmeasurement/indriya/issues/128 around absolute/relative `Temperature` values and how SmarHome should handle them. So far this was done in an application-specific way. JSR 385 (Units of Measurement 2.0) does provide a `Quantity` `Scale` that can be either `ABSOLUTE` or `RELATIVE`, but no implementation-specific operations are applied yet. It is not so easy, because the type `Temperature` cannot be kept hold of in Java due to Generics restrictions. 
What was done in SmartHome so far, and is there a branch or class we could use as inspiration for something that might work in a more general purpose manner? Or do you feel it's better to leave it up to individual solutions to react based on the new scale?

**Comment by maggu2810** [comment]
Please see https://github.com/eclipse/smarthome/pull/6883

**Comment by keilw** [comment]
@maggu2810 Sorry to hear the project may be archived or discontinued. We know, there is no demand from your side then or no resources to apply any changes including a 2.0 upgrade ;-/

**Comment by maggu2810** [comment]
This project is not continued anymore but the whole codebase has been migrated to openHAB and is further maintained at that place. So UoM is still a topic just for another project name.

**Comment by keilw** [comment]
Ok, does that mean there's also no more Eclipse SmartHome day at ECE since it looks like it's discontinued at Eclipse IoT?

**Comment by maggu2810** [comment]
I assume this question can be answered by @kaikreuzer

**Comment by kaikreuzer** [comment]
That's unfortunately very likely that there won't be a Smart Home Day at ECE - at least there is no such plan nor any sponsor for it yet...

**Comment by keilw** [comment]
Sorry to hear. I also pointed to the question about temperature calculations in the OpenHab tracker, and OpenHAB is also a downstream repo for Unit-API: https://github.com/unitsofmeasurement/unit-api/network/dependents.
