### ISSUE TITLE
New rule engine: Rule group

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#690]
smhgit commented on Oct 31
Are you going to add RuleGroup (Something like GroupItem)? If not, have you thought how to support rule grouping?

**Comment by danchom** [comment]
What do you want to do this group rule? If you want to execute more then one action you can put them into actions section.

**Comment by danchom** [comment]
smhgit commented on Nov 2
The idea behind the groups:

Add ability to disable / enable set of rules by one click
UI grouping.
E.g, you can combine all the switches rules of a room and disable the room rules just by enabling / disabling the group. Please note that in this case every switch have a different action.

**Comment by danchom** [comment]
dnobel commented on Nov 5
Even if this might be a nice feature, I think it is not essential for the moment. We are trying to finalize the initial PR for the rule engine. Maybe you can later add a feature request for ESH to introduce grouping. Is that OK?

**Comment by danchom** [comment]
smhgit commented on Nov 5
Sure.

**Comment by kaikreuzer** [comment]
> Add ability to disable / enable set of rules by one click
> UI grouping.

I would tend to say that we are able to do this by using tagging - so we can filter the list of rules for certain tags and have bulk operations on them. Similarly, we can provide Java API functions like "disableAllRulesTaggedWith(String tags...)".
