### ISSUE TITLE
openHAB does not update switch state in basicui after ESP reboots

### ISSUE THREAD

**Issue by ka-bro** [eclipse/smarthome#6917]
openHAB2:
.items
Switch	 relay1 "реле1" {channel="mqtt:topic:b0d2f1d2:relay1", autoupdate = "true"}

.things
Type switch : relay1 "On/Off switch" [ stateTopic="wroom-32/relay1/state", commandTopic="wroom-32/relay1/gpio/26" ]

.sitemap
Switch item=relay1 icon="wallswitch"

esp easy:
![switch](https://user-images.githubusercontent.com/57184236/70793772-237a8080-1dad-11ea-8e93-caebef74af4e.png)

It works good.. If I switch relay ON it is On in basicui. When I reboot ESP relay stete becomes OFF by default  but in basicui it is still ON even I refresh page in browser. I need to turn it OFF then ON and it works good again...
How can I get relay status to openHAB when ESP reboots?
Any guidance please?

**Comment by openhab-5iver** [comment]
openHAB no longer uses ESH. You should ask over here... https://github.com/openhab/openhab-webui/issues.
