### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by KleinDevDE** [eclipse/smarthome#6918]
Informations
-
**Branch:** master
**Java jre:** 1.8.0_221
**Eclipse version:** Photon Release 4.8.0 (Build id: 20180619-1200)
 
Failures in eclipse
-

Eclipse Smarthome cannot be installed with version 2020-03 or 2019-12.
According to some comments the installation works on Eclipse Photon.
Well, the installation itself worked fine, but some projects throw errors (616 errors and 302 warnings).
Most errors are about "cannot resolved to be a type".

I installed Eclipse Smarthome about an hour ago, nothing was changed by me.
```
Like: 
ModelItem cannot be resolved to a type.
/org.eclipse.smarthome.model.item/src/org/eclipse/smarthome/model/validation/ItemsValidator.xtend
````

Failures in maven
-
Used privatebin cause pastebin has a paste limit to 256kb.

**Try 1**
```sh
mvn clean install > log.txt
```
--> See log: https://privatebin.net/?e5563e52cf21c9b8#3V2DhqxKhV3U2FRxNgqoiedtqncEDk5SCqqx1pj1BbKF

---
**Try 2**  - Thank's to #4305
```sh
mvn clean install -DskipChecks=true -DskipTests=true > log2.txt
```
--> See log: https://privatebin.net/?848410a1507d799f#77PHVkWa8kxvCGeUbyLXzYGtPXAxtckHKvP4ww8EZkWz

---
**Try 3**
```sh
mvn clean install -e -X > log3.txt
```
--> See log: https://privatebin.net/?a79f06c59a999b43#ARfmNqeBfpfG27ewhYecyT4kG4yDhKBoab3zuKnTV48

Also the branch "0.10.x" gives me the same error like try1 and try2.

**Comment by openhab-5iver** [comment]
This repo is no longer maintained. See #6883 .

**Comment by KleinDevDE** [comment]
Okay thanks
