### ISSUE TITLE
New rule engine: Improve automation console commands

### ISSUE THREAD

**Issue by adimova** [eclipse/smarthome#703]
Improve the automation console commands:
 In the rules list that is returned as a result of command "listRules" following columns must be added: Name, Status. 
 Reimplement the code in the classes  : org.eclipse.smarthome.automation.internal.commands.Printer and org.eclipse.smarthome.automation.internal.commands.Utils

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/eclipse/smarthome/pull/704
