### ISSUE TITLE
BaseThingHandler.editThing() does not preserver State

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#713]
When calling this method somewhere in the Handler, then a new Thing is created, and assigned to handler.thing, but in the process the State of the original Thing is not preserved or copied over (but is set to the default UNINITIALIZED). Moreover, the Thing assigned to handler.thing is not the same object instance as the one that is tracked by the ThingManager. That means that for example in the osgi console, the Thing can be "ONLINE", but the Thing referenced by the handler will be UNINITIALIZED
(See also https://www.eclipse.org/forums/index.php/t/1072808/)

**Comment by kaikreuzer** [comment]
@sbussweiler, could you please have a look at this bug and make sure that it is fixed through your refactoring of the Thing lifecycle? Thanks :-)

**Comment by sbussweiler** [comment]
@kgoderis, please check your mentioned behavior after the thing life cycle PR (https://github.com/eclipse/smarthome/pull/769) is merged. 

If the issue still exists, give me a hint.

**Comment by kaikreuzer** [comment]
Assuming it is fixed by #769. If not, feel free to re-open.
