### ISSUE TITLE
Left-side menu on ESH homepage not displayed completely

### ISSUE THREAD

**Issue by dominicdesu** [eclipse/smarthome#728]
On the "Documenting a binding" page (https://www.eclipse.org/smarthome/documentation/development/bindings/docs.html), the menu is not displayed completely in Firefox and Chrome (1920x1080 Resolution) because it seems to overlap with the footer.
If necessary I can add a screenshot.

**Comment by maggu2810** [comment]
Thank you.
I already reported that one... :wink: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=483068

**Comment by dominicdesu** [comment]
I see... thanks for the info. In this case we can close this ticket.
