### ISSUE TITLE
No handler for command 'things' was found.

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#760]
osgi> smarthome things
No handler for command 'things' was found.

This just happened after a regular restart of the OH2/ESH runtime. What could be causing this? The runtime is operating correctly, all Things are instantiated (as well as ThingHandlers).

**Comment by kgoderis** [comment]
Oh... and the handler for "inbox" is also missing

**Comment by kgoderis** [comment]
ahum. solved by completely removing anything that is in ../userdata. 

Is this due to some stuff stored in mapdb, linked to inbox ?

**Comment by kaikreuzer** [comment]
No, this should not be related to anything in userdata...
Anyhow, as the problem is solved, I close this issue. If it occurs again (and best in a reproducible way), feel free to reopen.
