### ISSUE TITLE
Error in XML file causes UI to fail

### ISSUE THREAD

**Issue by cdjackson** [eclipse/smarthome#761]
If a thing-type XML file references a channel that doesn't exist, it causes the thing-type REST interface to fail - it may cause other problems as well I guess, since presumably there's something failing in the thing-type provider.

I don't see any exceptions being thrown though - it just fails silently!

**Comment by sjka** [comment]
I will have a look

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/eclipse/smarthome/pull/835
