### ISSUE TITLE
Basic UI: scenes cannot be selected multiple times

### ISSUE THREAD

**Issue by SuperOok** [eclipse/smarthome#784]
I have quite a few scenes with commands in the resulting drop down list like "close all rollershutters" and "open all rollershutters".

In basicui (as well as in greent if I remember correctly) I cannot select the same dropdown item successively. The second selection just has no effect. In the classicui as well as in the iOS-app, the same selection can be done multiple times and the effect is just executed.

Workaround is to select some other item in the list first and then select the former one again. However, this is often not what I want as the other item might trigger unwanted actions. Would have to create empty dummy entries that do nothing.

**Comment by kaikreuzer** [comment]
@resetnow I'll tag all issues about the Basic UI with an according label, so that it is easy to filter for them with https://github.com/eclipse/smarthome/labels/BasicUI.
