### ISSUE TITLE
PaperUI Angular Pretty URLs

### ISSUE THREAD

**Issue by GradyD** [eclipse/smarthome#791]
Currently URLs are in the form of `/ui/index.html#/setup/wizard`. Lets see if we can clean this up and remove the .html and # from the URL. 

To remove the # it looks like we just need to include `$locationProvider.html5Mode(true);` in the `angular.module().config`, https://scotch.io/quick-tips/pretty-urls-in-angularjs-removing-the-hashtag.

Not sure how to remove the .html at this time.

Does anyone feel that this would be worth while and we can safely support HTML5 browsers or do we need to be aware of limitations in older browsers?

**Comment by maggu2810** [comment]
I have no feeling about the usage of .html and '#'. HTML5 as a requirement for browsers is okay for me. Let's wait if someone wants support for older browsers.

**Comment by kaikreuzer** [comment]
Me neither.
@sja, @aounhaider1 Would you like to comment?

**Comment by sja** [comment]
1. Its completely unneccessary to have a 'beautiful' url. The beautiness is very objective.
2. HTML5 mode requires a backend change (always deliver the index, whitelist API calls and resources) which can get problematic. Yes, the angular docs promise a fallback but it can get problematic on edge cases.
So: I veto against Angular HTML5 mode!

**Comment by GradyD** [comment]
I think @sja brings up some good points so I will close this issue.
