### ISSUE TITLE
smarthome commands don't show help in Karaf

### ISSUE THREAD

**Issue by dvanherbergen** [eclipse/smarthome#802]
In the openhab2 console, there is no help displayed for the smarthome commands. 

```
openhab> man smarthome
openhab> man smarthome:status
Error: Item '--help' does not exist.
```

For openhab commands, this works:

```
openhab> man openhab
SUBSHELL
    openhab

COMMANDS
    openhab:install-service Install openHAB as a system service.
openhab> man openhab:install-service
DESCRIPTION
        openhab:install-service

    Install openHAB as a system service.

SYNTAX
        openhab:install-service
```

**Comment by triller-telekom** [comment]
Since this is the Eclipse SmartHome project, I just tried "man smarthome" in the OSGI console and it prints out the help as follows:

osgi> man smarthome
---SmartHome commands---
	smarthome discovery start <thingTypeUID|bindingID> - runs a discovery on a given thing type or binding
	smarthome discovery enableBackgroundDiscovery <PID> - enables background discovery for the discovery service with the given PID
	smarthome discovery disableBackgroundDiscovery <PID> - disables background discovery for the discovery service with the given PID
	smarthome links list - lists all links
	smarthome links addChannelLink <itemName> <channelUID> - links an item with a channel
	smarthome links removeChannelLink <itemName> <thingUID> - unlinks an item with a channel
	smarthome links clear - removes all managed links
	smarthome > <script to execute> - Executes a script
	smarthome firmware list <thingTypeUID> - lists the available firmwares for a thing type
	smarthome firmware status <thingUID> - lists the firmware status for a thing
	smarthome firmware cancel <thingUID> - cancels the update for a thing
	smarthome firmware update <thingUID> <firmware version> - updates the firmware for a thing
	smarthome inbox - lists all current inbox entries
	smarthome inbox listignored - lists all ignored inbox entries
	smarthome inbox approve <thingUID> <label> - creates a thing for an inbox entry
	smarthome inbox clear - clears all current inbox entries
	smarthome inbox ignore <thingUID> - ignores an inbox entry permanently
	smarthome things list - lists all things
	smarthome things clear - removes all managed things
	smarthome things remove <thingUID> - removes a thing
	smarthome update <item> <state> - sends a status update for an item
	smarthome audio play <sink> <filename> - plays a sound file from the sounds folder through the optionally specified audio sink(s)
	smarthome audio stream <sink> <url> - streams the sound from the url through the optionally specified audio sink(s)
	smarthome audio sources - lists the audio sources
	smarthome audio sinks - lists the audio sinks
	smarthome items list [<pattern>] - lists names and types of all items (matching the pattern, if given)
	smarthome items clear - removes all items
	smarthome items remove <itemName> - removes the given item
	smarthome voice say <text> - speaks a text
	smarthome voice interpret <command> - interprets a human language command
	smarthome voice voices - lists available voices of the active TTS service
	smarthome send <item> <command> - sends a command for an item
	smarthome status <item> - shows the current status of an item

So this is certainly not a bug in Eclipse SmartHome and thus this issue can be closed.

**Comment by kaikreuzer** [comment]
@triller-telekom Please note that ESH specifically contains an integration of the smarthome commands into the Karaf shell: https://github.com/eclipse/smarthome/tree/master/bundles/io/org.eclipse.smarthome.io.console.karaf

So this might need to be adjusted to also correctly show the help texts when being used in Karaf.
