### ISSUE TITLE
Label not displayed properly when it only contains a format pattern

### ISSUE THREAD

**Issue by doubled-ca** [eclipse/smarthome#810]
Creating a label like "[%s]" does not recognize the format pattern and displays the literal '%s' on the right were the value should be.  This is due to the behavior of the following check in ItemUIRegistryImpl.java:
if ((indexOpenBracket > 0) && (indexCloseBracket > indexOpenBracket))

Changing to 
if ((indexOpenBracket >= 0) && (indexCloseBracket > indexOpenBracket))

resolves the issue.

**Comment by maggu2810** [comment]
Can you create a PR?

**Comment by maggu2810** [comment]
Okay, you have already done it. It would be nice if you could create a cross-link.
This will be done automatically if you add a line to the commit message (in the footer, above the Signed-off-by line).
```text
Bug: https://github.com/eclipse/smarthome/issues/810
```

Related to: #811

**Comment by kaikreuzer** [comment]
lgtm
