### ISSUE TITLE
PaperUI support for Channel Configuration 

### ISSUE THREAD

**Issue by marcelrv** [eclipse/smarthome#827]
With the recent addition of configurable channels PaperUI should support this as well.

Suggested UI look & feel would be
1) to render on the right side of the channel an edit icon (pencil) similar to when going to the edit mode of a thing
2) Clicking the edit icon it will provide a popup, similar to the properties edit screen of the services., alternatively it would provide similar screen as the edit screen for thing configuration.

**Comment by kaikreuzer** [comment]
We should probably also introduce a new rest uri `/{thingUID}/channels/{channelID}/config` to which an HTTP PUT can directly update the configuration. For the moment, the Paper UI will have to send an update of the complete Thing.
