### ISSUE TITLE
Remove bower dependency 

### ISSUE THREAD

**Issue by GradyD** [eclipse/smarthome#833]
Per https://github.com/eclipse/smarthome/pull/800#issuecomment-170221083 we should look into converting bower over to npm.

**Comment by GradyD** [comment]
Please assign to me

**Comment by kaikreuzer** [comment]
I can only assign issues to committer, not to contributors - but your note is enough that we know that you are working on this.

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/eclipse/smarthome/issues/833
