### ISSUE TITLE
Hudson Build Failing due to network issue

### ISSUE THREAD

**Issue by GradyD** [eclipse/smarthome#844]
It looks like the changes made in https://github.com/eclipse/smarthome/pull/829 broke the nightly build, https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/749/console

Reading the error, `[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (Install node and npm) on project org.eclipse.smarthome.ui.paper: Could not download Node.js: Could not download https://nodejs.org/dist/v5.4.0/node-v5.4.0-linux-x64.tar.gz: Network is unreachable -> [Help 1]`. It looks like it was unable to reach the internet and download the requested nodeJS .gz. 

Is there something in Hudson that is blocking network calls?

**Comment by kaikreuzer** [comment]
This is weird, since it used to work before... Let me just try to restart to see if the problem remains or if it was just a temporary one.

**Comment by kaikreuzer** [comment]
Here is the log of the (old) build 747, so there is no general problem:
```
[INFO] c.g.e.m.p.f.l.DefaultNodeAndNPMInstaller - Downloading Node.js from http://nodejs.org/dist/v0.12.3/node-v0.12.3-linux-x64.tar.gz to /jobs/genie.smarthome/SmartHomeDistribution-Nightly/workspace/extensions/ui/org.eclipse.smarthome.ui.paper/node_tmp/node.tar.gz
[INFO] c.g.e.m.p.f.l.FileDownloader - Downloading via proxy ProxyConfig{protocol='http', host='proxy.eclipse.org', port=9898}
[INFO] c.g.e.m.p.f.l.DefaultNodeAndNPMInstaller - Extracting Node.js files in node_tmp
[INFO] c.g.e.m.p.f.l.DefaultNodeAndNPMInstaller - Unpacking /jobs/genie.smarthome/SmartHomeDistribution-Nightly/workspace/extensions/ui/org.eclipse.smarthome.ui.paper/node_tmp/node.tar.gz into /jobs/genie.smarthome/SmartHomeDistribution-Nightly/workspace/extensions/ui/org.eclipse.smarthome.ui.paper/node_tmp
[INFO] c.g.e.m.p.f.l.DefaultNodeAndNPMInstaller - Moving node binary to /jobs/genie.smarthome/SmartHomeDistribution-Nightly/workspace/extensions/ui/org.eclipse.smarthome.ui.paper/node/node
[INFO] c.g.e.m.p.f.l.DefaultNodeAndNPMInstaller - Deleting temporary directory /jobs/genie.smarthome/SmartHomeDistribution-Nightly/workspace/extensions/ui/org.eclipse.smarthome.ui.paper/node_tmp
[INFO] c.g.e.m.p.f.l.DefaultNodeAndNPMInstaller - Installed node locally.
[INFO] c.g.e.m.p.f.l.DefaultNodeAndNPMInstaller - Installing npm version 2.10.0
```

**Comment by kaikreuzer** [comment]
Ah, the difference is this one:
```
[INFO] c.g.e.m.p.f.l.ProxyConfig - Could not find matching proxy for protocol https
```
So Hudson only has a proxy for http, but not https. Is it possible to change the frontend plugin config to use http only?

**Comment by GradyD** [comment]
Looking at the plugin, https://github.com/eirslett/frontend-maven-plugin, it looks like it is doable by adding,
```
<nodeDownloadRoot>https://nodejs.org/nodejs/dist/</nodeDownloadRoot>
<npmDownloadRoot>https://registry.npmjs.org/npm/-/</npmDownloadRoot>
```
I will make this update and open a new PR this evening when I get home.

**Comment by Tavalin** [comment]
How difficult is it to add the https proxy? My thoughts are if there's another resource in the future that needs https it will fail again.

**Comment by GradyD** [comment]
I'm not well versed in maven so I'm not sure how to add the maven proxy. Odds are this is a pretty specific use case.

**Comment by kaikreuzer** [comment]
The proxy is imho not a Maven setting, but it needs to be configured on Hudson by the webmaster.
I can do a request to the webmaster, but I am not sure if he will do it and how long it might take. So for now, we should go with using http.

**Comment by maggu2810** [comment]
Just for your information: http://maven.apache.org/guides/mini/guide-proxies.html
