### ISSUE TITLE
Problems with binding hue and linking

### ISSUE THREAD

**Issue by jrcourtois** [eclipse/smarthome#855]
I installed beta version, and I tried demo version before going back to standard (in conf/addons.cfg).
I am trying to use Hue lamps and I got some issue with PaperUI.
It appears automatically, and when I checked in the interface, it did not seems I clicked so I clicked on it.
![screen shot 2016-01-14 at 5 40 13 pm](https://cloud.githubusercontent.com/assets/5859493/12330441/75be0792-bae5-11e5-8450-c035b70b4349.png)

I didn't manage to do anything on it and got the following traces

```
17:30:56.475 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'hue:LCT001:001788182930:2'  has been added.
17:30:56.492 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'hue:LCT001:001788182930:2' changed from INITIALIZING to ONLINE
17:30:56.493 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'hue:LCT001:001788182930:2' changed from UNINITIALIZED to INITIALIZING
17:30:56.495 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'hue:LCT001:001788182930:2' has been updated.
17:30:56.510 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'hue_LCT001_001788182930_2' has been added.
17:30:56.523 [INFO ] [rthome.event.ItemThingLinkAddedEvent] - Link 'hue_LCT001_001788182930_2-hue:LCT001:001788182930:2' has been added.
17:30:56.546 [INFO ] [smarthome.event.ItemUpdatedEvent    ] - Item 'hue_LCT001_001788182930_2' has been updated.
17:31:07.684 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'true-hue:LCT001:001788182930:1:color' has been added.
```

Which leads me to the major problem I faced when I tried to retrieve the item which should have been selected
```java
        Thing t = thingSetupManager.getThing(objIdentifier);
        if (t != null) {
            for (Channel c : t.getChannels()) {
                Set<String> channels = ItemChannelLinkRegistry().getLinkedItems(c.getUID());
```
```java
['RGBColor', 'value']
```
For the first issue, I can get through with it, but for the second one I would like to know if it is an expected behaviour or face by anyone else.

**Comment by kaikreuzer** [comment]
> It appears automatically, and when I checked in the interface, it did not seems I clicked so I clicked on it.

This is the normal setup in openHAB - you need to link your channel to some existing item (which has to be defined in an item file).
The fact that you can click "LINK" without selecting an item first is a bug, I have entered https://github.com/eclipse/smarthome/issues/857 for it.

```
        Thing t = thingSetupManager.getThing(objIdentifier);
```
What kind of code are you writing there?
I very much recommend to NOT use the ThingSetupManager in any way - this is code that I consider an internal helper for the Paper UI and which is likely to be heavily refactored in the future...

**Comment by jrcourtois** [comment]
> This is the normal setup in openHAB - you need to link your channel to some existing item (which has to be defined in an item file).

OK, for Hue lamp, in alpha release the items were defined 'automatically'.

> I very much recommend to NOT use the ThingSetupManager in any way

OK, I will avoid using setup manager. It allowed me to save some extra information for the things. But I am not sure, but the behaviour after that should be the same, I mean any way I retrieve the thing object, the rest should work fine, isn't it ?

**Comment by kaikreuzer** [comment]
> I mean any way I retrieve the thing object, the rest should work fine, isn't it ?

In general yes. But I wonder what you are implementing that you are creating things yourself? A binding at least should never ever do this...

**Comment by jrcourtois** [comment]
> But I wonder what you are implementing that you are creating things yourself ? 

I want to add extra information (such as a place and a name) that you can define through an interface, and I manage to do this using Thing (I do not create extra Thing, I add GroupItem). As you say this is not the good way to do this, I will do by implementing my own db system.
