### ISSUE TITLE
Allow the sonos binding to accept empty strings for text fields

### ISSUE THREAD

**Issue by xsnrg** [eclipse/smarthome#862]
Currently, when the sonos is not playing but is being polled by the binding, an error is produced:

    10:45:52.460 [ERROR] [inding.sonos.internal.SonosXMLParser] - Could not parse MetaData from string ''
    [Fatal Error] :1:1: Premature end of file.
    10:46:52.457 [ERROR] [inding.sonos.internal.SonosXMLParser] - Could not parse MetaData from string ''
    [Fatal Error] :1:1: Premature end of file.

As soon as the sonos starts playing, the field is populated and there is no error. This is a low priority request as everything still works, but if it works, it should not be an error :)

**Comment by kaikreuzer** [comment]
@kgoderis Could you have a look, please?

**Comment by kgoderis** [comment]
Fixed by https://github.com/eclipse/smarthome/pull/1364
