### ISSUE TITLE
Hue binding: missing channels (Paper UI) for Philips Living Colors Bloom

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#865]
Using PaperUI, I installed the hue binding; the bridge was correctly discovered and finally my two lights were discovered too.

My lights are identified as Philips Living Colors Bloom. That's correct. The stange thing is that only the color channel is then exposed. Why the brightness and color temperature channels are not exposed too ?

**Comment by kaikreuzer** [comment]
- Dimmer: There is no such channel, because you can dim your light also through the Color channel
-  ColorTemp: Simply because the Bloom does not support that functionality.
