### ISSUE TITLE
Paper UI - linking a channel to several items

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#867]
Paper UI allows to link a particular thing channel to a unique item.
The ability to link a channel to several items would be appreciated.

As an example, for any dimming light, I define a switch item + a dimmer item. It is more easy and reliable to use the switch in the UI. I put the dimmer item in a frame for advanced usage of my lights.

Waiting for this enhancement, of course, any link can be done by editing the item files.

**Comment by kaikreuzer** [comment]
> It is more easy and reliable to use the switch in the UI

You are aware that you can have a Switch widget in the UI referencing a Dimmer item?

**Comment by aounhaider1** [comment]
I was thinking about implementing this feature. Here is one idea about how it may be implemented: 
We can have a link button in channels list. Clicking on it can open a dialog box with all the currently linked channels and a Autocomplete input field. User can search an item there and can link it to current channel. The new item will then be added to the list. What do you think?

**Comment by aounhaider1** [comment]
Here it is how it currently looks like.
Channels list with expandable icon:
<img width="946" alt="screen shot 2016-09-15 at 16 30 41" src="https://cloud.githubusercontent.com/assets/5161937/18553750/e9db4922-7b61-11e6-9d1c-0060ffae0c5f.png">
Expanded channel:
<img width="947" alt="screen shot 2016-09-15 at 16 30 18" src="https://cloud.githubusercontent.com/assets/5161937/18553751/e9de2958-7b61-11e6-83c3-fff3bd2d6eee.png">

**Comment by kaikreuzer** [comment]
lgtm - @lolodomo I guess that would meet your needs?

**Comment by lolodomo** [comment]
lgtm. Just don't forget we should be able to delete a link too.

**Comment by kaikreuzer** [comment]
Didn't you see the trash bin icons on the right?

**Comment by lolodomo** [comment]
I see it now :)
very good.

**Comment by lolodomo** [comment]
@aounhaider1: will you consider the item type ?
