### ISSUE TITLE
Basic UI mapping issue

### ISSUE THREAD

**Issue by paulianttila** [eclipse/smarthome#875]
Basic UI does not support mappings which contains '.' (dot) character. Samsung TV contains web browser, which can be controlled via Samsung TV binding. Currently it's impossible to launch URL which contains dot characters.

```
Selection item=TV_Web_Browser_Url mappings=["www.google.com"=Google, "www.openhab.org"=openHAB]
```
Similar issue created for Classic UI #874

**Comment by kaikreuzer** [comment]
@resetnow Could you have a look at that? (and once you are at it, maybe fix #874 on the way)?

**Comment by resetnow** [comment]
Will do (next week most likely)

**Comment by resetnow** [comment]
@paulianttila could you please test it before merging? It appears to work, but I'm not sure whether the quotes should be the a part of the string value.

**Comment by kaikreuzer** [comment]
Regarding the quotes, there seems to be some problems with parsing the sitemaps (see e.g. https://github.com/eclipse/smarthome/pull/790). For the moment, simply expect the Sitemap Java objects to have the plain strings without any quotes. If there are situations, where the quotes end up in the string, this will hopefully be fixed through an Xtext upgrade soon.

**Comment by resetnow** [comment]
Fine, #966 is applicable then.

**Comment by kaikreuzer** [comment]
Thanks - lgtm.
Could you do the same for #874?

**Comment by resetnow** [comment]
Yes, I'll create a PR a bit later today.

**Comment by resetnow** [comment]
#974
