### ISSUE TITLE
Missing no-arg constructors for Gson

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#876]
* Creation of ESH-Event failed, because one of the registered event factories has thrown an exception: Unable to invoke no-args constructor for class org.eclipse.smarthome.core.items.events.ItemEventFactory$ItemEventPayloadBean. Register an InstanceCreator with Gson for this type may fix this problem.java.lang.RuntimeException: Unable to invoke no-args constructor for class org.eclipse.smarthome.core.items.events.ItemEventFactory$ItemEventPayloadBean. Register an InstanceCreator with Gson for this type may fix this problem.
* Creation of ESH-Event failed, because one of the registered event factories has thrown an exception: Unable to invoke no-args constructor for class org.eclipse.smarthome.core.thing.link.dto.ItemChannelLinkDTO. Register an InstanceCreator with Gson for this type may fix this problem.java.lang.RuntimeException: Unable to invoke no-args constructor for class org.eclipse.smarthome.core.thing.link.dto.ItemChannelLinkDTO. Register an InstanceCreator with Gson for this type may fix this problem.
* Creation of ESH-Event failed, because one of the registered event factories has thrown an exception: Unable to invoke no-args constructor for class org.eclipse.smarthome.core.thing.ThingStatusInfo. Register an InstanceCreator with Gson for this type may fix this problem.java.lang.RuntimeException: Unable to invoke no-args constructor for class org.eclipse.smarthome.core.thing.ThingStatusInfo. Register an InstanceCreator with Gson for this type may fix this problem.

**Comment by maggu2810** [comment]
I am a little bit irritated was has been changed.
I cannot remember about a PR that changed the Gson version and I didn't remember ThingStatusInfo etc. has been changed.

**Comment by maggu2810** [comment]
Okay, I played a little bit using no bootdelegation. So perhaps there is no sun.misc.Unsafe. But do we want to use such a unsafe construction?

**Comment by maggu2810** [comment]
* [Oracle will remove the internal sun.misc.Unsafe class in Java 9] (https://docs.google.com/document/d/1GDm_cAxYInmoHMor-AkStzWvwE9pw6tnz_CebJQxuUE/edit?pli=1)
* [Why Developers Should Not Write Programs
That Call 'sun' Packages] (http://www.oracle.com/technetwork/java/faq-sun-packages-142232.html)

**Comment by kaikreuzer** [comment]
How can this be reproduced? I am also not aware of any changes, nor of this bug...

**Comment by maggu2810** [comment]
Okay, this issue is thrown by disable the boot delegation.
There is no recent code change involved.
I am just a little but confused and irritated if we should rely on the presence of sun.misc.Unsafe.

> How can this be reproduced?

If you disable the boot delegation the sun packages are not available for the bundles and you will see this error.

**Comment by kaikreuzer** [comment]
>  if we should rely on the presence of sun.misc.Unsafe.

Probably not on the long run. Does GSON always require it, also in more recent versions?

**Comment by maggu2810** [comment]
> Does GSON always require it, also in more recent versions?

2.3.1:
https://github.com/google/gson/blob/gson-2.3.1/src/main/java/com/google/gson/internal/UnsafeAllocator.java#L39

There seems to be nothing changed...
https://github.com/google/gson/commits/master/gson/src/main/java/com/google/gson/internal/UnsafeAllocator.java

**Comment by maggu2810** [comment]
Some further reading:
http://stackoverflow.com/a/18645370

**Comment by kaikreuzer** [comment]
Ok, but it means by adding no-args constructors, we can avoid the use of Unsafe, right? So I agree that those constructors should be added whereever necessary.

**Comment by maggu2810** [comment]
> Ok, but it means by adding no-args constructors, we can avoid the use of Unsafe, right?

That is correct.

> So I agree that those constructors should be added whereever necessary.

I would add e.g. "for Gson only to avoid Unsafe usage" to the constructor JavaDoc.
This are a lot of classes, aren't it?
Is there an easy way to find all classes that are used by Gson?

**Comment by kaikreuzer** [comment]
> This are a lot of classes, aren't it?

I thought that we actually already added no-args constructors for that reason to most classes.

> Is there an easy way to find all classes that are used by Gson?

Hm, not really. It's a bit like with the missing javax-imports: You will only notice when the code is executed, which is rather annoying...

**Comment by kaikreuzer** [comment]
@maggu2810 Could you create a PR for the classes where you already noticed that the constructor is missing?

**Comment by maggu2810** [comment]
@kaikreuzer Yes, I will create one (have to finish a business trip before).

**Comment by maggu2810** [comment]
There are two Gson versions in the target platform, 2.2.4.v201311231704 and 2.3.1.
The Eclipse SmartHome launch configuration is using "2.2.4.v201311231704".
The openHAB-distro project is using "2.3.1".
Should we keep compatibility for 2.2.4 in the ESH project or could we use 2.3.1 for ESH, too.
At the moment I do not known if there are differences, but it would be nice to know.

**Comment by kaikreuzer** [comment]
I am also not aware of any functional differences (definitely none that we need).
It might reduce the risk to come across bugs (and spend time on them) that exist in 2.2.4 and which are fixed in 2.3.1. So while we might not need/want special functionality of 2.3, I am in favour of upgrading the launch config / target platform.

**Comment by maggu2810** [comment]
If the log is saved to /tmp/esh.log the following command could be used to get the classes that miss the no-arg constructor.

```bash
cat /tmp/esh.log | grep 'no-args' | sed 's:^.* for class \(.*\). Register an .*$:\1:g' | sort -u
```

@kaikreuzer If created a Gson jar that I am using in my workspace that skips the Unsafe allocation. If you want use this for your development, too, I can send it to you.

**Comment by kaikreuzer** [comment]
Sure, please send it, sounds useful.

**Comment by maggu2810** [comment]
@kaikreuzer A repository used in the target platform has changed its content (or it seems so). Now Gson 2.5.0 (and no more 2.3.1 as this afternoon) is part of the target platform.

**Comment by kaikreuzer** [comment]
That sounds pretty weird and like an unlikely coincidence... This is a bigger version change then and we should check if we really want this.

**Comment by kaikreuzer** [comment]
added through #953.
