### ISSUE TITLE
Missing constructor of rule without UID parameter.

### ISSUE THREAD

**Issue by danchom** [eclipse/smarthome#882]
Rule can be create without specifying rule's UID. In this case the rule engine has to calculate uid of added rule.  Following constructor should be added in org.eclipse.smarthome.automation.Rule class:
    public Rule(List<Trigger> triggers, List<Condition> conditions, List<Action> actions, 
            List<ConfigDescriptionParameter> configDescriptions, Map<String, ?> configurations)

**Comment by kaikreuzer** [comment]
@danchom Do you plan to create a PR for this?

**Comment by danchom** [comment]
A PR is created: https://github.com/eclipse/smarthome/pull/1022
