### ISSUE TITLE
Update Sonos control - state

### ISSUE THREAD

**Issue by s-simma** [eclipse/smarthome#883]
I took the repo from today and started OH2b in the eclipse IDE
My system is configured with 5 players. Everything was ok till mid december.

but now:
The sonos control-state (play/pause) in the OH-UI's will not be updated any more if i switch to play/pause in the Sonos-GUI. There is even no log-entry that something was received from sonos (if i press play/pause on the sonos-GUI). What i did by mistake was to update the sonos to the latest version (i know crazy)

What i have seen in the log-console during startup (no idea if this has a relation to the problem)
```
!ENTRY org.eclipse.equinox.ds 1 0 2016-01-19 09:05:33.592
!MESSAGE Could not bind a reference of component org.jupnp.upnpservice. The reference is: Reference[name = HttpService, interface = org.osgi.service.http.HttpService, policy = dynamic, cardinality = 0..1, target = null, bind = setHttpService, unbind = unsetHttpService]
Jan 19, 2016 9:05:33 AM org.jupnp.transport.impl.apache.StreamServerImpl init
INFO: Created socket (for receiving TCP streams) on: /192.168.1.88:55930
Jan 19, 2016 9:05:33 AM org.jupnp.transport.impl.apache.StreamServerImpl init
INFO: Created socket (for receiving TCP streams) on: /10.133.196.6:55931
```
And while play around i got this message (but only once)
```
Jan 19, 2016 8:54:38 AM org.jupnp.protocol.sync.ReceivingEvent executeSync
SEVERE: Invalid subscription ID, no active subscription: (IncomingEventRequestMessage) NOTIFY /upnpcallback/dev/RINCON_000E5851C84801400_MR/svc/upnp-org/AVTransport/event/cb SEQUENCE: 9
Jan 19, 2016 8:54:43 AM org.jupnp.protocol.sync.ReceivingEvent executeSync
SEVERE: Invalid subscription ID, no active subscription: (IncomingEventRequestMessage) NOTIFY /upnpcallback/dev/RINCON_000E5851C84801400_MR/svc/upnp-org/AVTransport/event/cb SEQUENCE: 9
```
If i use play/pause in OH-UI's everything work as expected.
It would help a lot, if someone, using the latest sonos-version could confirm this.

**Comment by kgoderis** [comment]
Hi, the messages you are seeing (invalid subscription id) are typically generated when you try to control a sonos device (with for example the Sonos Controller software), but you have restarted the OH runtime in the meantime. The sonos player keeps track of remote softwares that "subscribe" to certain events, but if you restart the OH runtime (in a non-graceful way), it has no way to know of the subscription is still valid or not. 

Does the problem persist when you restart the OH runtime?

**Comment by s-simma** [comment]
Hi, I have restarted several times (sonos GUI, OH, computer). If i press play/pause on the Sonos GUI i don't get any info/debug/error message, simply nothing.
Today i compiled the latest repo version. Still the same.
My feeling is, that i have the problem since the latest Sonos update (Have you installed the latest Sonos-Update ?). Before everything was ok.
It would be great, if you could tell me where is entry point for receiving data from the sonos. So i could set a breakpoint in the debugger.

**Comment by kgoderis** [comment]
I just verified at my end, and things are working. My Sonos devices are at FW v6.0
That being said, my setup is slightly different from OH Beta2, in the sense that I run a snapshot that is from just before the release with the Karaf OSGi container. @kaikreuzer jupnp is confirmed to be fully working on Karaf?

**Comment by kaikreuzer** [comment]
> @kaikreuzer jupnp is confirmed to be fully working on Karaf? 

Yes!

**Comment by s-simma** [comment]
This is what i did already. It doesn't triggers this point. (if i press play/pause on the sonos GUI).
And it is not Computer spezific. I have the same problem with windows7 + Ubuntu on an ARM.
My Sonos version is 6.0 Built:31322220.
It would realy be great if somebody could confirm that sonos is running on the latest repo.
I assume i need to set the breakpoint in the "...io.transport.upnp". But where can i get the source code ?

**Comment by kgoderis** [comment]
@JochenHiller Jochen, did you try/test the sonos binding on OH2b/Karaf?

I can not confirm the problem as I am not on a Karaf snapshot for now

**Comment by kgoderis** [comment]
@s-simma It is a bit strange you say that you can control the devices from the OH UI but not the other way around. The messages seem to indicate that something is wrong with the "subscriptions" the Sonos binding is taking with the remote Sonos device, as if they are lost for some reason. You are sure there are no potential hardware problems (e.g. network) that could be the root cause?
Does it happen with one specific device, or with all of them?

**Comment by s-simma** [comment]
To get not confused i started from scratch. took the openHAB2 from
https://openhab.ci.cloudbees.com/job/openHAB-Distribution/

Installed it on Windows7 (firewall disabled) (Java:1.8.0_66-b18)
Installed it on Linux ARM (Java:1.8.0_65-b17)
copied my "conf" directory to both installations. (In the xxxx.thing i have 5 players configured)

the result is hard to believe
on Windows:
from OH: i can play/pause all the players
from Sonos: play/pause will not change any status in OH

on ARM:
from OH: i can play/pause all the players
from Sonos: play/pause, 2 of the players CHANGE the status in OH

I startet both computers several times. The behavior is always the same.

I think you are right. The problem is the subsciption. Can you give me a little bit more details how this should work ? (I can't see any log entries regarding subscription generation.

**Comment by s-simma** [comment]
@kgoderis I finally found the reason. Or better YOU and wireshark helped me a lot. Recently i connected an ODROID u3 by DHCP to my network. And you wouldn't believe it has the same MAC Adress as another one i have in my network.These Hardkernel guys didn't spend a MAC-Adress generator for this board. And believe me, the only problem a had the last 3 weeks was this Sonos problem.
again thank you very much for your help !!!!!
