### ISSUE TITLE
Rule trigger / action / condition edit: empty fields

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#884]
If I press the edit button of a trigger, action or condition the already filled fields are empty.

**Comment by maggu2810** [comment]
I created a rule that contains a trigger only.
ItemStateEvent: item name = sw1

After saving that rule it get this message
```text
10:04:20.984 WARN  o.e.s.a.r.i.RuleResource[:114] - Creation of the rule is refused: Missing required parameter: itemName of type ItemStateChangeTrigger
```

So perhaps the values are not stored at all.

**Comment by danchom** [comment]
You can't create a module without filling required parameter for them. The itemName is required parameter for the trigger of type ItemStateChangeTrigger

**Comment by maggu2810** [comment]
See initial message of this issue.
I filled in the item name, but it seems to get lost.

**Comment by kaikreuzer** [comment]
I think I have seen this as well, but it should be fixed with https://github.com/eclipse/smarthome/pull/819, which I am just testing and which should be merged today.

**Comment by maggu2810** [comment]
I merged #819 locally. This seems to solve the problem.
Thank you.

**Comment by maggu2810** [comment]
I know it is not really part of this issue, but perhaps I could use this issue to ask one question:
Is it possible to create a rule that synchronize the state of two switch items?
* trigger = Item State Trigger, item name = sw1
* action = Post command to an item, item name = sw2, ...

Let's assume I want to link a switch of a rocker and a switch of a light...
How could this be handled?

**Comment by kaikreuzer** [comment]
I think the ItemStateChangeTrigger should not have an "event" as an output, but rather "newState" and "previousState".
This output could then be fed into the input of the post command action.

**Comment by marinmitev** [comment]
adding newState output to ItemStateChangeTrigger will solve a similar issue reported in the forum:
https://www.eclipse.org/forums/index.php?t=msg&th=1073673&goto=1719865&#msg_1719865
