### ISSUE TITLE
Change "Setup Wizard" to "Discovery Inbox" in Paper UI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#890]
I would suggest to rename the menu "Setup Wizard" to "Discovery Inbox" in the Paper UI, since the system setup is done through all of the main menu entries (configuration, extensions etc.) as well and the what is behind the "Setup Wizard" menu is merely the inbox (and a link to manually add a thing), which is rather misleading.

**Comment by kaikreuzer** [comment]
Alternatively, we could also simply go for "Inbox" if this is self-explanatory enough.

**Comment by teichsta** [comment]
> Alternatively, we could also simply go for "Inbox" if this is self-explanatory enough.

+1

**Comment by GradyD** [comment]
Currently the URL on that page is `/setup/wizard` should we look into changing that also or just change the name on page?

**Comment by kaikreuzer** [comment]
probably makes sense, I just do not know the impact of that...

**Comment by kaikreuzer** [comment]
Implemented with #970
