### ISSUE TITLE
ItemStateChangeTrigger must output a state, not an event

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#891]
In order to meaningfully use the output of the ItemStateChangeTrigger, it must output a State, not an Event.
For advanced use cases, the event could also be kept as a second output value, though.

See https://github.com/eclipse/smarthome/issues/884#issuecomment-172786745 and https://www.eclipse.org/forums/index.php?t=msg&th=1073673&goto=1719865&#msg_1719865

**Comment by BenediktNiehues** [comment]
The ItemStateChangeTrigger is a Composite trigger based on GenericEventTrigger, so the output is the event here. 
If we want to have a state as output, there has to be an additional handler implementation for trigger what originally was not the intention here.
Btw.: adding the itemState as output would not solve the problem mentioned in the forum, therefore an action would be needed which works with inputs and not with configurations as the ItemPostCommandAction does. 
Maybe this could then act similar as the GenericCompareCondition where you also can configure a property of the input to be compared.

**Comment by kaikreuzer** [comment]
This has been implemented with https://github.com/eclipse/smarthome/pull/2814
