### ISSUE TITLE
item context support for configuration parameters in Paper UI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#898]
According to https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-configuration-descriptions, config parameters can have a "context" attribute, which gives more information about their meaning.

For a start, supporting context=item would be very helpful, specifically for the Rule UI.
Instead of rendering a text box for such a string parameter, a selection box should be rendered, which lists all existing items. If possible, every entry in the selection box should have two lines: One with the item label and underneath in a smaller font the item name (as this is the unique technical identifier and might be necessary, if two items have the same label).

**Comment by watou** [comment]
> might be necessary, if two items have the same label

Would a tooltip or hover help be an alternative to showing the item name in a smaller font?  Might be cleaner in appearance.

**Comment by kaikreuzer** [comment]
I think hovers and tooltips are not really practical on selection boxes - remember that the stuff should also work on a phone with touch control only.
