### ISSUE TITLE
Cannot POST JSON using Rest API when CORS enabled

### ISSUE THREAD

**Issue by shry15harsh** [eclipse/smarthome#903]
Some apis like /rest/things need some JSON to be sent using POST method. For sending such requests, one needs to set header `"Content-Type":"application/json"`. It works fine when origin is same but browser sends a preflight request in case of different origin and CORS enabled. The Rest API server does not accept the header "content-type" and therefore does not return `"Access-Control-Allow-Headers":"content-type"`. Browser, therefore, does not send POST request.

I have fixed this in my application by modifying CorsFilter.java. I think this is an issue because it does not make any sense for not allowing some of the Rest API cross domain calls (having JSON to be sent). Correct me if I am wrong or any other way to do this if my approach in sending request was wrong.

**Comment by kaikreuzer** [comment]
@sja Can you comment?

**Comment by kaikreuzer** [comment]
Fixed through #926
