### ISSUE TITLE
Automation : Add possibility to add Rules to the fly to a RuleProvider, and have them register correctly with the RuleEngin

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#905]
I did not yet provide a PR for this, as it might need to be discussed first. Currently, RuleProviders are polled only once for their Rules (at initialisation), and never again thereafter. In my understanding, it should be possible to dynamically create rules in a RuleProvider (for example, for caching reasons), and serve them afterwards. So, when adding a Rule to a RuleProvider, the RuleRegistry should check the Rule and add it to the RuleEngine.

In the rule provider, when the rule is created, one can add:

        for (ProviderChangeListener<Rule> listener : listeners) {
            listener.added(this, newRule);
        }

just after the code the rule is created, and then the code here below should be added to RuleRegistryImpl:

    @Override
    protected void onAddElement(Rule rule) throws IllegalArgumentException {
        try {
            String rUID = rule.getUID();
            if (!ruleEngine.hasRule(rUID)) {
                if (rUID != null && disabledRulesStorage != null && disabledRulesStorage.get(rUID) != null) {
                    ruleEngine.addRule(rule, false);
                } else {
                    ruleEngine.addRule(rule, true);
                }
            }
        } catch (Exception e) {
            logger.error("Can't add rule: " + rule.getUID() + " into rule engine ", e);
        }
    }

**Comment by danchom** [comment]
>In my understanding, it should be possible to dynamically create rules in a RuleProvider 
Why do you want to add new rules through the rule provider instead of through the RuleRegistry? 
The normal flow is to use the registry interface to access providers. 
Of course you can create your own rule provider which will be tracked by the RuleRegistry and rules from it will be added into rule engine (RuleRegistryImpl.addedProvider() will be called). But rules from other providers are read only and they will not be persist by the rule engine.

**Comment by kgoderis** [comment]
Just for my understanding then, RuleProviders are not considered to be dynamic objects that can change the pool of Rules they provide? e.g. it is all static?

**Comment by kaikreuzer** [comment]
No, not all static. As the RuleRegistry extends AbstractRegistry I fully agree with you that a RuleProvider can at any time dynamically change the set of rule it provides and all it needs to do is to inform its ProviderChangeListeners about that.

So what you are saying is that the RuleRegistry currently does not support this? If this is the case, I would consider it a bug that needs to be fixed.

**Comment by marinmitev** [comment]
Yes, we agree that onAddElement method should be implemented in RuleRegistry similar to onUpdate
Element method

**Comment by kgoderis** [comment]
@marinmitev you provide the patch for this ? My initial comment is probably made on the basis of a code base that has certainly evolved in the mean time

**Comment by marinmitev** [comment]
@adimova will provide the patch

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/eclipse/smarthome/pull/1434

**Comment by danchom** [comment]
Implemented By PR #1500
