### ISSUE TITLE
Automation  :  RuleEngine.validateRules() too strict?

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#906]
I am struggling with the restrictions imposed by the above function. Rule id's can only contain [A-Za-z0-9_-]*, which forces us to be very creative with the naming of Rules. The obvious solution is to for something line UUID, and set the Description to something more meaningful. If this is the preferred route, then it would make a lot of sense to refactor all existing code so that Description is used instead of UID when outputting logs and so forth. Now it is very hard to debug whatsoever.

**Comment by kaikreuzer** [comment]
Note that besides UID and description there is also the "name" - which is imho the one that should be used for logging etc. Note that the UID is also used in the URL on the REST API, so there is a good reason to restrict it to a limited set of characters.

**Comment by kgoderis** [comment]
I agree, but only Rule has a Name field, not the Modules for example.... I went for the common here, but it is all cosmetics anyways

**Comment by kaikreuzer** [comment]
Modules have a "label" instead of a "name", which serves the same purpose (now please don't ask me, why it is called differently between the two, I have no clue...)
