### ISSUE TITLE
Automation : setName() on Rule generated by Template does not work

### ISSUE THREAD

**Issue by kgoderis** [eclipse/smarthome#911]
For example

        Rule newRule = new Rule(ruleUID, TEMPLATE_UID, config);
        newRule.setName("someName");

yields "null" for the name when doing a "smarthome automation listRules" in the OSGi console ?

**Comment by kaikreuzer** [comment]
Can you confirm that you are on the latest sources which include https://github.com/eclipse/smarthome/pull/879?

**Comment by kgoderis** [comment]
Nope I am not but thanks for pointing out

**Comment by kaikreuzer** [comment]
so I assume that #879 solves your problem. Feel free to re-open, if this is not the case.
