### ISSUE TITLE
Submit CQ for material icons

### ISSUE THREAD

**Issue by GradyD** [eclipse/smarthome#914]
Material Icons are included in the paperUI, or should be included, but are not currently included. I do see them included in [openhab2](https://github.com/openhab/openhab2-addons/tree/master/addons/ui/org.openhab.ui.paperui/patch/web/fonts/md-icons) but not in ESH. This means that running ESH on its own has some UI issues because it does not include the fonts so you often end up with empty buttons, 
![image](https://cloud.githubusercontent.com/assets/994964/12542058/553d60da-c2ec-11e5-99b9-17d45bff9fb6.png)

Is a CQ needed? If so, can you please submit one?

Since we are moving away from bower here is the NPM package, https://www.npmjs.com/package/material-design-icons and here is the source, https://github.com/google/material-design-icons. The current version is 2.1.3.

**Comment by maggu2810** [comment]
The CQ is already in progress.

**Comment by kaikreuzer** [comment]
FTR, the CQ is 10013.

**Comment by GradyD** [comment]
Is there a spot where I can see the CQ and its status?

**Comment by kaikreuzer** [comment]
No, it is only visible to committers. But be assured: Once it is approved, I will add the icons and notify you!

**Comment by kaikreuzer** [comment]
FYI: https://github.com/eclipse/smarthome/pull/1003
