### ISSUE TITLE
Duplicate code for i18n in automation.providers and config.core bundles

### ISSUE THREAD

**Issue by tomhoefer** [eclipse/smarthome#922]
Before the contribution of the automation bundles the config.core bundle was the single point in ESH to internationalize config descriptions and their parameters. Now the automation.providers bundle contains also an utility to internationalize config description parameters. This utility should be removed and the utility of the config.core bundle should be used instead.

One problem having two i18n utilities for the configuration description parameters is that is not possible to internationalize the unit and the unit label with the i18n utility of the automation.providers bundle. The reason for this is that the unit.properties is only available in the config.core bundle.

**Comment by kaikreuzer** [comment]
@danchom @marinmitev Could you have a look at this? Do we have a way to remove the duplicate code?

**Comment by marinmitev** [comment]
@adimova is working on this, it seems to be possible to avoid the duplication

**Comment by marinmitev** [comment]
using the URI objects from org.eclipse.smarthome.config.core.i18n.ConfigDescriptionI18nUtil adds limitation to the characters used in the rules/moduletypes/templates UIDs. Such an example is the '_' symbol which is used in several places: ItemStateEvent_ON_Condition in file /org.eclipse.smarthome.automation.module.core/ESH-INF/automation/moduletypes/ItemEventConditionModuleTypeDefinition.json
This leads to runtime exceptions URISyntaxException and we will need to validate the UID objects.
According the RFC 2396 the allowed symbols for URI scheme are
 scheme        = alpha *( alpha | digit | "+" | "-" | "." )
and we should use the same limitation for the UIDs. @kaikreuzer do you agree ?

**Comment by kaikreuzer** [comment]
So far, we defined UIDs to be of this pattern: https://github.com/eclipse/smarthome/blob/d0dde874a4e8024b9b4c075720a986d68587bf06/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/UID.java#L24
This is imho valid within URIs and I would not like to have "+" or "." as characters within a UID.

Where exactly do you come across exceptions when using underscores in the UID?

**Comment by adimova** [comment]
I defined keys for localization of the automation objects:
module-type.{moduleTypeUID}.label;
module-type.{moduleTypeUID}.description;
module-type.{moduleTypeUID}.output.{InputName}.label;
module-type.{moduleTypeUID}.output.{InputName}.description;
module-type.{moduleTypeUID}.output.{OutputName}.label;
module-type.{moduleTypeUID}.output.{OutputName}.description;
module-type.{moduleTypeUID}.config.param.{parameterName}.label;
module-type.{moduleTypeUID}.config.param.{parameterName}.description;
...
rule-template.{RuleTemplateUID}.label;
rule-template.{RuleTemplateUID}.description;
rule-template.{RuleTemplateUID}.config.param.{parameterName}.label;
rule-template.{RuleTemplateUID}.config.param.{parameterName}.description;
...

I construct the configDescriptionURI as module-type.{moduleTypeUID}:param to receive the keys:

module-type.{moduleTypeUID}.config.param.{parameterName}.label;
module-type.{moduleTypeUID}.config.param.{parameterName}.description;

and as rule-template.{RuleTemplateUID}:param  to receive the keys:

rule-template.{RuleTemplateUID}.config.param.{parameterName}.label;
rule-template.{RuleTemplateUID}.config.param.{parameterName}.description;

rule-template.{RuleTemplateUID} and module-type.{moduleTypeUID} are treated as scheme in ConfigDescriptionI18nUtil.inferKey(URI configDescriptionURI, String parameterName, String lastSegment) and this leads to runtime exceptions URISyntaxException

**Comment by tomhoefer** [comment]
Could you pls provide an example of {RuleTemplateUID} and {moduleTypeUID} which throws an URISyntaxException... I would like to reproduce it...

**Comment by adimova** [comment]
if you use the commit c0dc375a2e3c22931cd66f9de45a8088934d220e and run the configuration "SmartHome Runtime", use the console command "smarthome automation listModuleTypes", you will receive the exception message:
java.net.URISyntaxException: Illegal character in scheme name at index 26: module-type.ItemStateEvent_ON_Condition:param
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3048)
	at java.net.URI.<init>(URI.java:588)
	at org.eclipse.smarthome.automation.internal.core.provider.AbstractResourceBundleProvider.getLocalizedConfigurationDescription(AbstractResourceBundleProvider.java:425)
	at org.eclipse.smarthome.automation.internal.core.provider.ModuleTypeResourceBundleProvider.getPerLocale(ModuleTypeResourceBundleProvider.java:292)
	at org.eclipse.smarthome.automation.internal.core.provider.ModuleTypeResourceBundleProvider.getModuleTypes(ModuleTypeResourceBundleProvider.java:184)
	at org.eclipse.smarthome.automation.core.internal.type.ModuleTypeManager.getAll(ModuleTypeManager.java:145)
	at org.eclipse.smarthome.automation.core.internal.type.ModuleTypeRegistryImpl.getAll(ModuleTypeRegistryImpl.java:63)
	at org.eclipse.smarthome.automation.internal.commands.AutomationCommandsPluggable.getModuleTypes(AutomationCommandsPluggable.java:275)
	at org.eclipse.smarthome.automation.internal.commands.AutomationCommandList.listModuleTypes(AutomationCommandList.java:235)
	at org.eclipse.smarthome.automation.internal.commands.AutomationCommandList.execute(AutomationCommandList.java:80)
	at org.eclipse.smarthome.automation.internal.commands.AutomationCommands.executeCommand(AutomationCommands.java:471)
	at org.eclipse.smarthome.automation.internal.commands.AutomationCommandsPluggable.execute(AutomationCommandsPluggable.java:185)
	at org.eclipse.smarthome.io.console.ConsoleInterpreter.execute(ConsoleInterpreter.java:52)
...

which is in the file "ESH_INF/automation/moduletypes/ItemEventConditionModuleTypeDefinition.json" in bundle org.eclipse.smarthome.automation.module.core

**Comment by adimova** [comment]
and we still can use this pattern: https://github.com/eclipse/smarthome/blob/d0dde874a4e8024b9b4c075720a986d68587bf06/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/UID.java#L24, but without underscore

**Comment by kaikreuzer** [comment]
@tomhoefer I think the problem is if a module type UID contains an _ and we create a configDescriptionURI from that.
How do we do it for thing-types? How does the config description URI look like for them if they contain an underscore? The very same should imho then happen for the automation entities.

**Comment by tomhoefer** [comment]
I have to check....

**Comment by tomhoefer** [comment]
There is no special logic to build the config description URI from thing-types that consist of an underscore. So having an underscore in the thing-type will result in a config description URI with an underscore.

**Comment by kaikreuzer** [comment]
@tomhoefer As @marinmitev points out in https://github.com/eclipse/smarthome/issues/922#issuecomment-180346717, underscores are not a valid character for URIs, so you are hence doing it wrong, which needs to be fixed. Is your code not using the constructor of URI? If it does, it should also fail with an exception.

**Comment by tomhoefer** [comment]
According to chapter 2.3 of RFC 2396 the underscore belong to the unreserved characters that are allowed in URIs

Furthermore there is also no problem to execute the following simple main operation:

```
public static void main(String[] args) throws URISyntaxException {
    String string = "hello:world_1";
    System.out.println(new URI(string));

    string = "http://www.math_1.uio.no/faq/compression-faq/part1.html";
    System.out.println(new URI(string));
}
```
Maybe I still don´t get the issue....

**Comment by tomhoefer** [comment]
Ok... I see the problem now....

**Comment by adimova** [comment]
I made changes in the way I construct the keys for localization that fixes the problem for automation module

**Comment by tomhoefer** [comment]
The problem is the underscore in the scheme.... So

```
he_llo:world
```

cannot be parsed. Is it possible to exchange / replace the underscore in the module type ID?

**Comment by adimova** [comment]
This was my first proposition but Kai regect it, so I changed the way to construct the keys.  They are now:
module-type.{moduleTypeUID}.label;
module-type.{moduleTypeUID}.description;
module-type.input.{moduleTypeUID}.name.{InputName}.label;
module-type.input.{moduleTypeUID}.name.{InputName}.description;
module-type.output.{moduleTypeUID}.name.{OutputName}.label;
module-type.output.{moduleTypeUID}.name.{OutputName}.description;
module-type.config.{moduleTypeUID}.name.{parameterName}.label;
module-type.config.{moduleTypeUID}.name.{parameterName}.description;
...
rule-template.{RuleTemplateUID}.label;
rule-template.{RuleTemplateUID}.description;
rule-template.config.{RuleTemplateUID}.name.{parameterName}.label;
rule-template.config.{RuleTemplateUID}.name.{parameterName}.description;
...
Now the configDescriptionURI for module type looks like "module-type:{moduleTypeUID}.name" and for template - "rule-template:{RuleTemplateUID}.name"

**Comment by tomhoefer** [comment]
your change fixes the URISyntaxException, correct?

**Comment by kaikreuzer** [comment]
> This was my first proposition but Kai regect it, so I changed the way to construct the keys.

I am very confused now. @adimova, where did you ever have an underscore within the URI scheme? Can you give a concrete example?

**Comment by adimova** [comment]
yes, now Module Type UIDs participate only to the Scheme Specific Part and can contain "_"

**Comment by adimova** [comment]
in the first way the constructed URI was module-type.ItemStateEvent_ON_Condition:param and the scheme was "module-type.ItemStateEvent_ON_Condition" and Scheme Specific Part - "param", now the URI will be "module-type:ItemStateEvent_ON_Condition.name" where the scheme will be "module-type" and the Scheme Specific Part - "ItemStateEvent_ON_Condition.name"

**Comment by kaikreuzer** [comment]
Ok, so the "first way" never made sense, as the scheme should only be the entity type as it is given in https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-configuration-descriptions.
So there is no issue after all about underscores. Sorry @tomhoefer to have you bothered with that!
