### ISSUE TITLE
Reduce visibility of ConfigDescriptionParameter constructor

### ISSUE THREAD

**Issue by tomhoefer** [eclipse/smarthome#923]
There is one public constructor of ConfigDescriptionParameter that accepts all attributes. 

```java
public ConfigDescriptionParameter(String name, Type type, BigDecimal minimum, BigDecimal maximum,
            BigDecimal stepsize, String pattern, Boolean required, Boolean readOnly, Boolean multiple, String context,
            String defaultValue, String label, String description, List<ParameterOption> options,
            List<FilterCriteria> filterCriteria, String groupName, Boolean advanced, Boolean limitToOptions,
            Integer multipleLimit, String unit, String unitLabel) throws IllegalArgumentException {
...
}
```

If a new attribute is added or removed then there is a lot of code to be adapted in ESH (especially in test cases). I would prefer if this construnctor becomes package private. The instantiation of the parameter should only be possible by using the corresponding config description parameter builder.

For #889 I had to adapt a lot of test code to allow the two new attributes unit and unit label.

Would this change make also sense for you?

**Comment by kaikreuzer** [comment]
Yes, I thought the same when reviewing your #889.

**Comment by tomhoefer** [comment]
Ok... Then I will change it and contribute soon....

**Comment by kaikreuzer** [comment]
implemented through https://github.com/eclipse/smarthome/pull/925
