### ISSUE TITLE
automation java api demo broken by last commits

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#929]
The automation Java API demo (#859) has been broken by the constructor changes of ConfigDescriptionParameter (#889)

The constructor of the ConfigDescriptionParameter has been changed (added unit and unit label).

The code of org.eclipse.smarthome.automation.java.api.demo has not been changed, so compilation of this demo is broken.

**Comment by maggu2810** [comment]
Perhaps we could use the ConfigDescriptionParameterBuilder in the Java API demo for the automation (using the PR #925),

**Comment by kaikreuzer** [comment]
@tomhoefer, could you have a look?

**Comment by maggu2810** [comment]
I will create a PR, soon...

**Comment by maggu2810** [comment]
It is also broken by #912

**Comment by tomhoefer** [comment]
thanks @maggu2810 for the fix... Unfortunately I hadn´t the demo project in my workspace... And I am wondering why my maven build did not fail...

**Comment by maggu2810** [comment]
It seems that this project is not added to the automation pom. Perhaps it should be added, so we get build failures.

**Comment by tomhoefer** [comment]
yes... this would be nice
