### ISSUE TITLE
Some of the REST API documentation is incorrect/inaccurate

### ISSUE THREAD

**Issue by tavalin** [eclipse/smarthome#945]
I had a quick look at the REST API which states that a POST to /items/{itemname} should return:

| HTTP Status Code | Reason            |
|------------------|-------------------|
| 200              | OK                |
| 400              | Item command null |
| 404              | Item not found    |

I therefore coded my test client to only accept status 200 as a positive response.  However this call is returning 201 (CREATED).  Having done some research it seems that 201 is not an uncommon code for a POST but I can't find anything concrete on whether I should expect a 200 or 201 code.

**Comment by kaikreuzer** [comment]
Thanks for noticing, this is indeed a bug!
I would tend to say that the documentation is right and 200 is the better return value here, since we do not really create any new REST resource, but we rather only execute a command through it. Would you agree?

**Comment by watou** [comment]
201 is definitely incorrect for sending a command to an item, because it does not agree semantically with the meaning of 201.  It should be 200 (OK), or possibly 202 (Aceppted) if processing is asynchronous and it's not possible to know if the command was sent to the item.  I think 200 is correct.

> 10.2.2 201 Created

> The request has been fulfilled and resulted in a new resource being created. The newly created resource can be referenced by the URI(s) returned in the entity of the response, with the most specific URI for the resource given by a Location header field. The response SHOULD include an entity containing a list of resource characteristics and location(s) from which the user or user agent can choose the one most appropriate. The entity format is specified by the media type given in the Content-Type header field. The origin server MUST create the resource before returning the 201 status code. If the action cannot be carried out immediately, the server SHOULD respond with 202 (Accepted) response instead.

**Comment by tavalin** [comment]
@kai @watou is there any feedback on the above before I start work on submitting a PR?

**Comment by kaikreuzer** [comment]
No further feedback, the one line that you reference needs to be changed.
Be careful about the other occurrences of 201 - many of them are definitely correct.

**Comment by tavalin** [comment]
> Be careful about the other occurrences of 201 - many of them are definitely correct.

Thanks, that's the bit I was after. Will try and send the PR tonight then.
