### ISSUE TITLE
Paper UI - should be able to enter thing parameters when creating it

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#960]
When adding manually a thing using Paper UI, it is not (no more ?) possible to enter parameters immediately. You have to create the thing first without any parameters, then go into configuration => Things and here edit the thing and all its parameters.
Would it be possible to fill the parameters when creating the thing ?

**Comment by maggu2810** [comment]
You are right, this has been changed.
I don't know which commit has changed this and why.

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/eclipse/smarthome/pull/963
