### ISSUE TITLE
Show state on Switch widget for Rollershutters

### ISSUE THREAD

**Issue by s-simma** [eclipse/smarthome#976]
Hi,
Seting the Rollershutter state inside a binding e.g.:
this.updateState(new ChannelUID(getThing().getUID(), CHANNEL_POSITION), new DecimalType(position));
with item:
Rollershutter Shutter_GF_OfficeB    "Büro Balkon [%d %%]"       (GF_Office, Shutters)   {channel="siennapl:Sienna_SAM2:1:PL1:position"}
does not display any %-value left to the three buttons of the rollershutter.
The rollershutter icon shows the correct icon (depending on the %-value) - but only as long as you are on the page with the rollershutter.

Classic-UI: it displays either 0% or 100% but not the state value set.

**Comment by kaikreuzer** [comment]
If I get it right, this is about the slider widget in the Basic UI. The wish is that it shows the state as well, similar to how the Classic UI does it:
<img width="362" alt="screen shot 2016-02-04 at 08 28 54" src="https://cloud.githubusercontent.com/assets/3244965/12808747/9d9c88b2-cb19-11e5-8556-bc9ace2ccb66.png">
Currently, the Basic UI shows it like this:
<img width="411" alt="screen shot 2016-02-04 at 08 29 15" src="https://cloud.githubusercontent.com/assets/3244965/12808753/a91c8854-cb19-11e5-8dc7-5babd3aaa382.png">

I am not fully sure though, if the state as text is really needed as the slider position already reflects the current value as well.

**Comment by kaikreuzer** [comment]
This is about the switch widget for Rollershutter items in the Basic UI. The wish is that it shows the state as well, similar to how the Classic UI does it:
<img width="362" alt="screen shot 2016-02-04 at 08 28 54" src="https://cloud.githubusercontent.com/assets/3244965/12808747/9d9c88b2-cb19-11e5-8556-bc9ace2ccb66.png">
Currently, the Basic UI shows it like this:
<img width="495" alt="screen shot 2016-02-04 at 08 33 14" src="https://cloud.githubusercontent.com/assets/3244965/12808790/038ab522-cb1a-11e5-9306-2be3ed05c4ef.png">

@resetnow Could you have a look?

**Comment by kaikreuzer** [comment]
I am actually wrong - the Classic UI also shows it without a value:
<img width="472" alt="screen shot 2016-02-04 at 08 36 47" src="https://cloud.githubusercontent.com/assets/3244965/12808862/824288ae-cb1a-11e5-85da-ac2705aac36a.png">
So I wonder if this request really makes sense - after all, a percentage value does not tell much about a rollershutter and the icon should be good enough to give a hint about the current position.

**Comment by s-simma** [comment]
For sure, the classic-UI shows it with a value !!

**Comment by resetnow** [comment]
@s-simma The one with a value is not a rollerblind widget, it's most likely a setpoint. Rollerblind widget has 3 buttons,

**Comment by kaikreuzer** [comment]
> Rollerblind widget has 3 buttons.

Yes, see https://github.com/eclipse/smarthome/issues/976#issuecomment-179692763

**Comment by s-simma** [comment]
![screenshot - 04_02](https://cloud.githubusercontent.com/assets/15436483/12809402/025b18ae-cb1f-11e5-9a37-b44cd7cd6fcb.jpg)

**Comment by s-simma** [comment]
@kaikreuzer 
In my opinion it make sense for rollershutter and blinds. If you have heavy wind (> 8m/s) both shoud be open.

**Comment by kaikreuzer** [comment]
Ok, you are right - I missed that the demo.items does not define a pattern and thus no value is displayed:
```
Rollershutter DemoShutter "Roller Shutter"
```
If I change it to
```
Rollershutter DemoShutter "Roller Shutter [%d %%]"
```
It indeed displays a value as per your screenshot.
So yes, I agree that if we define a state pattern through `[]` in the label, this should also be picked up by the Basic UI.

**Comment by resetnow** [comment]
@kaikreuzer did you have an actual rollershutter controller when you were testing the sitemap item? I'm asking because I don't have one and when the item is not attached to the binding, the item state only changes to 0 and to 100. Is this normal?

**Comment by s-simma** [comment]
@resetnow 
in the classic-UI you can't set the value either from inside a binding. It shows only 0% or 100%.
In the Basic-UI it doesn't show any value.
All these problems with "don't showing/changing state values of a channel" arise when you set the state value from inside a binding handler such as:
this.updateState(new ChannelUID(getThing().getUID(), CHANNEL_POSITION), new DecimalType(position));

**Comment by kaikreuzer** [comment]
> @kaikreuzer did you have an actual rollershutter controller when you were testing the sitemap item?

No, I was merely using the demo setup and added the [%d %%] as described above.
It is correct that the state only changes to 0% and 100%, because it will simply assume it is UP or DOWN depending on the button you have pressed. But if the UI shows the 0 and 100, this is all that is asked for here - just the same way as the Setpoint widget already does:
<img width="495" alt="screen shot 2016-02-05 at 08 58 06" src="https://cloud.githubusercontent.com/assets/3244965/12840803/99fd6b68-cbe6-11e5-8881-b3dc761265c2.png">
