### ISSUE TITLE
Basic UI problem with Dimmer item

### ISSUE THREAD

**Issue by s-simma** [eclipse/smarthome#977]
Hi,
Setting the Dimmer status inside the binding, while you are on the page with the slider, sets the slider to the correct position.
this.updateState(new ChannelUID(getThing().getUID(), CHANNEL_VALUE), new DecimalType(value));

If i set the Dimmer state while i'm NOT on the page with this slider -> After switching to the page with the slider the position of the slider is not set correct.

**Comment by kaikreuzer** [comment]
Is this only with dimmers or with any item state (switches, numbers, etc.)?

**Comment by s-simma** [comment]
If you remember, i had the same problem with String items. It is solved in the meantime.
Number i have to check.
Switch -> is ok

**Comment by s-simma** [comment]
@kaikreuzer 
with the latest repo compiled:
The behvior is the same for Dimmer,String and Number items
Only Switch item is ok.

If you change Status while you are on the same basic-ui page as the item  -> Status values are displayed correct
If you are on a different page (change Status values). After switching to the page with the mentioned items noting is displayed.
I  thought this problem with String item has already been solved.sorry.

**Comment by kaikreuzer** [comment]
Ok, leaving it to @resetnow to have a look.

**Comment by resetnow** [comment]
I can't reproduce the issue. Here is what I did:

* Opened two browser windows with BasicUI
* In window 2 navigated to page 2
* In window 1 changed a selection widget on page 1
* In window 2 changed a value of a slider widget
* In window 2 navigated back to page 1
* In window 1 navigated to page 2
* Both windows represent the changes made in another window.

@s-simma could you please tell what browser are you using?

**Comment by s-simma** [comment]
@resetnow 
Hi,
I can reproduce it with:
1. Open Basic-UI
2. Stay on the main page
3. Set State from a binding e.g.
this.updateState(new ChannelUID(getThing().getUID(), CHANNEL_VALUE), new DecimalType(value));
4. Go to the page where the state value should be displayed (don't put the item with the value that should be displayed on the main page)

**Comment by s-simma** [comment]
@resetnow 
same with chrome and firefox (both latest version)

**Comment by resetnow** [comment]
@s-simma I'm not quite following you, sorry. If you are *developing* a binding and your binding updates do not show up in BasicUI, you can check if they make it to the SSE channel that BasicUI uses. I'm not very familiar with OH/ESH internal binding API so I can't tell if you're updating the item state correctly, but at least other bindings usually work.

**Comment by s-simma** [comment]
@resetnow 
in practice:
test 1:
1. I open Basic-UI, move to the page with the dimmer (slider) item
2. On the PHYSICAL Dimmer on the wall i increase/decrease the  brightness to e.g 50% 
3. The Slider item on the UI updates imediately to the CORRECT value  it jumps into the middle (50%) -> OK
 
test2:
1. I open Basic UI, STAY on the Main page
2. SAME AS in TEST 1
3. Now i move to the page with the slider item
3. The Slider item is on the very left position (0%) .. it should be in the middle as in is in test1..(refreshing the page will not help to show the correct value)

And i think you will 100% agree, this can't be a problem of my binding.

**Comment by resetnow** [comment]
@s-simma 

>refreshing the page will not help to show the correct value
>you will 100% agree, can't be a problem of my binding.

It's either a binding problem or a problem with rules / scripts. I don't have a physical dimmer to test it. Also, can you provide more details about your hardware? What model of dimmer do you use? What binding is used to connect is to ESH/OpenHAB?

**Comment by s-simma** [comment]
@resetnow 
I have implemented a binding for Sienna powerline devices. And everything is working fine. The following code line in the binding is responsible for updating the actual value of the Dimmer

this.updateState(new ChannelUID(getThing().getUID(), CHANNEL_VALUE), new DecimalType(value));

If it would help you i can write a test binding that simulates the problem.

**Comment by resetnow** [comment]
Ok, since we're talking about REST API and SSE usage, this could be tested in another way. Do you have an Android or iOS device? Could you please install the OpenHAB app and see if it reflects the changes you make with a physical dimmer?

**Comment by s-simma** [comment]
great idea,
i have both here. I'll come bak.
thank you very much.

**Comment by s-simma** [comment]
I did the test regarding reflecting the actual device state on the 3 UI's
Basic-UI:
Switch item -> OK
Number item -> OK
String item: -> OK 
Slider item -> OK if the page with the slider is visible at the time the value is changed (otherwise the value is lost)
Rollershutter item -> does not show any value at all

iOS:
Switch item  -> OK
Numer item -> OK
String item: -> OK
Slider item -> will never be reflected on the UI
Rollershutter item -> does not show any value at all

Android:
Switch item  -> OK
Number item -> OK
String item: -> OK
Slider item -> will never be refleced on the UI
Rollershutter item -> does not show any value at all

**Comment by kaikreuzer** [comment]
> this.updateState(new ChannelUID(getThing().getUID(), CHANNEL_VALUE), new DecimalType(value));

Guys, note that you do not need any binding or hardware available for such tests at all.
Simply use the openHAB demo setup (there is a "DimmedLight" defined) you can do a
```
smarthome update DimmedLight 50
````
in the IDE console (it currently does not work in the Karaf console, see https://github.com/eclipse/smarthome/issues/984) and the dimmer state is updated to 50%.

I can confirm @s-simma observations this way:

1. Launch the runtime in the IDE
2. Call `smarthome update DimmedLight 50` in the console
3. Navigate to the Basic UI -> Widget Overview

-> the "Dimmer" is still at 0%

1. Launch the runtime in the IDE
2. Navigate to the Basic UI -> Widget Overview
3. Call `smarthome update DimmedLight 50` in the console

-> the "Dimmer" is correctly at 50%

It seems that the Basic UI does not process the SSE events for DimmedLight as long as the page where this item is used has not yet been visited at least once.

**Comment by resetnow** [comment]
>smarthome update DimmedLight 50

Thanks, didn't know that. Anyway, it seems like there is a server-side sitemap rendering issue. When user navigates to a page in BasicUI, it requests the HTML content of the page from server and replaces the current content. The fact that the dimmer value is wrong means either the HTML is rendered incorrectly of somehow the value is updated... partially? I'll look into it. And what about Android and iOS applications?..

**Comment by kaikreuzer** [comment]
>  it requests the HTML content of the page from server

Good point, so maybe the problem is there. So the sitemap page is only requested the first time entering the page? Because if I enter it once, go back to the home page, update the state and re-enter the sub-page, it shows the correct state.

> And what about Android and iOS applications?

The do not use SSE at all, only retrieving the sitemap - so if they do not work either, this supports your assumption that the problem is on the server-side assembly of the sitemap page.

**Comment by resetnow** [comment]
>So the sitemap page is only requested the first time entering the page? 

No, it is requested every time the user navigates to the page. It's unlikely, but it might be some kind of caching issue.

**Comment by s-simma** [comment]
You guys are fantastic. I'm sure, if you continue this way, openHAB will become the best home automation system in the market.

**Comment by resetnow** [comment]
@kaikreuzer this is getting interesting because I can't reproduce the issue the way you described :)

However, it is possible that the problem you describe does exist, but is unrelated to this issue. Are you running the demo configuration from openhab-distro? If yes, there is a problem with the <a href="https://github.com/openhab/openhab-distro/blob/master/features/openhab-demo-resources/src/main/resources/rules/demo.rules">default rules</a>:

```
rule "Dimmed Light"
	when
		Item DimmedLight received command
	then
		var Number percent = 0
		if(DimmedLight.state instanceof DecimalType) percent = DimmedLight.state as DecimalType 
			
		if(receivedCommand==INCREASE) percent = percent + 5
		if(receivedCommand==DECREASE) percent = percent - 5

		if(percent<0)   percent = 0
		if(percent>100) percent = 100
		postUpdate(DimmedLight, percent);
end
```

When DimmedLight is updated with a new value, this rule gets triggered but the command is not `DECREASE` nor `INCREASE` so `postUpdate` is called with value 0. This creates some kind of race condition when sometimes this rule manages to update the value earlier than the REST request value is applied and sometimes it's the other way around. I ran into this when I was debugging BasicUI slider and was wondering why the hell 1 times out of 10 the slider jumps to 0 after change.

So the rule should be this way:

```
if ((receivedCommand==INCREASE) || (receivedCommand==DECREASE))
    postUpdate(DimmedLight, percent);
```

This is just a guess but I can say that without this rule I can't reproduce the issue. Also I should mention I run ESH, not OH2 + ESH — could this be the case?

**Comment by maggu2810** [comment]
> When DimmedLight is updated with a new value, this rule gets triggered but the command is not `DECREASE` nor `INCREASE` so `postUpdate` is called with value 0.

Do you mean this rule (using "recieved command") is called on an state update, too and not only an a command. Or do you mean that it is called on another command then increase, decrease.

If it is called on a state update, this is a bug in the rule handler.

There is already a "if(DimmedLight.state instanceof DecimalType)". I would add a test for IncreaseDecrease type as well and do nothing on another type (or log a message if it is a unexpected behaviour).

**Comment by resetnow** [comment]
>Do you mean this rule (using "recieved command") is called on an state update, too and not only an a command? Or do you mean that it is called on another command then increase, decrease?

As far as I understand, the former. This rule is being called when a POST request is made to `/rest/items/itemname` with the state as a parameter.

**Comment by kaikreuzer** [comment]
> When DimmedLight is updated with a new value, this rule gets triggered but the command is not DECREASE nor INCREASE so postUpdate is called with value 0.

Very valid observation! I have created https://github.com/openhab/openhab-distro/pull/123 to fix the rule, thanks!

But this now leaves me not being able to reproduce any problem either.
So the issue is back to @s-simma to come up with a detailed description and a simple way to reproduce it.

**Comment by s-simma** [comment]
@kaikreuzer 
I'm on the road this week. Next week i look for a simple way ( i think using your demo) to reproduce the problem for you.

**Comment by s-simma** [comment]
@kaikreuzer 
With a simple binding the problem can be reproduced very easy.
The attached zip-file include all informations.
[DimmerStatusProblem.zip](https://github.com/eclipse/smarthome/files/125438/DimmerStatusProblem.zip)

**Comment by s-simma** [comment]
As Kai posted in #1071, to set the actual state for rollershutters and dimmers from inside a binding the DataType "PercentType" has to be used. (DecimalType is not accepted).
