### ISSUE TITLE
invalid jmdns.org update-site

### ISSUE THREAD

**Issue by marinmitev** [eclipse/smarthome#978]
Recently I started receiving the following error when building with maven:
Failed to load p2 metadata repository from location http://www.jmdns.org/update-site/3.4.2/: Unable to read repository at http://www.jmdns.org/update-site/3.4.2. http://www.jmdns.org/update-site/3.4.2 is not a valid repository location.

**Comment by kaikreuzer** [comment]
I do not see this message and the repo at the url seems to be alright... Is it 100% reproducible or only happening from time to time?

**Comment by marinmitev** [comment]
it is 100% reproducable on my side, but I have just checked that @adimova has no such error...

**Comment by kaikreuzer** [comment]
So I guess it is some local problem on your machine - if you find that there is really something wrong in the ESH code base / build, feel free to reopen.
