### ISSUE TITLE
SCALE transform issue

### ISSUE THREAD

**Issue by lolodomo** [eclipse/smarthome#989]
I have a scale transform working well in OH 1.x but leading to an error in OH 2 beta 2.
Here is the scale file I am using:
```
[0,0]=0 %
[1,1]=11 %
[2,2]=22 %
[3,3]=33 %
[4,4]=44 %
[5,5]=56 %
[6,6]=67 %
[7,7]=78 %
[8,8]=89 %
[9,9]=100 %
```

And here are the logs:
```
12:25:06.519 [INFO ] [marthome.event.ItemStateChangedEvent] - BatterieTempHumVeranda changed from NULL to 0
12:25:11.927 [WARN ] [.internal.ScaleTransformationService] - Scale transform entry does not comply with syntax : '[7,7]', '78 %'
12:25:11.928 [WARN ] [.internal.ScaleTransformationService] - Scale transform entry does not comply with syntax : '[2,2]', '22 %'
12:25:11.942 [WARN ] [.internal.ScaleTransformationService] - Scale transform entry does not comply with syntax : '[5,5]', '56 %'
12:25:11.945 [WARN ] [.internal.ScaleTransformationService] - Scale transform entry does not comply with syntax : '[0,0]', '0 %'
12:25:11.948 [WARN ] [.internal.ScaleTransformationService] - Scale transform entry does not comply with syntax : '[8,8]', '89 %'
12:25:11.951 [WARN ] [.internal.ScaleTransformationService] - Scale transform entry does not comply with syntax : '[3,3]', '33 %'
12:25:11.954 [WARN ] [.internal.ScaleTransformationService] - Scale transform entry does not comply with syntax : '[6,6]', '67 %'
12:25:11.957 [WARN ] [.internal.ScaleTransformationService] - Scale transform entry does not comply with syntax : '[1,1]', '11 %'
12:25:11.959 [WARN ] [.internal.ScaleTransformationService] - Scale transform entry does not comply with syntax : '[9,9]', '100 %'
12:25:11.962 [WARN ] [.internal.ScaleTransformationService] - Scale transform entry does not comply with syntax : '[4,4]', '44 %'
12:25:11.965 [WARN ] [rm.AbstractFileTransformationService] - Could not transform '0' with the file 'batteryOregon.scale'.
12:25:14.262 [INFO ] [ome.event.GroupItemStateChangedEvent] - GFreebox changed from NULL to UNDEF through FreeboWifi
```

**Comment by clinique** [comment]
Will take a look at this

**Comment by clinique** [comment]
Done.
Sorry @lolodomo , this is not a bug but an undocumented feature :)
No, seriously, while porting scale to OH2, I took the opportunity to extend it a bit while using standard Range object (com.google.common...).
Adding the oppotunity to have open, closed ranges like this :

**Comment by kaikreuzer** [comment]
I would be ok with this breaking change as it is for the better, not too many users use the scale transformation system and their files can be easily manually adapted.

So my suggestion would be to add a note in https://github.com/openhab/openhab-distro/blob/master/docs/sources/migration.md for this.

@lolodomo, would you agree?

**Comment by lolodomo** [comment]
@kai @clinique: ok for the change.
How can you know that it is not used by nany users ?

**Comment by clinique** [comment]
Maybe because as of now y'oure the first and only one to have complained/notced :smile:

**Comment by clinique** [comment]
Pushed documentation update. This issue can be closed.

**Comment by lolodomo** [comment]
I am not sure that there are now a lot if OH2 users.

**Comment by kaikreuzer** [comment]
> How can you know that it is not used by nany users ?

You are right, I actually do not know... But still, it is easy for them to migrate, so all should be good :-)

**Comment by SergVM** [comment]
Hello! And what about the uncertain value?
19:14:22.578 [WARN ] [rm.AbstractFileTransformationService] - Could not transform '-' with the file 'humidex.scale' : Scale can only be used with numeric inputs
Thank you!

**Comment by watou** [comment]
> And what about the uncertain value?

It might make sense to special-case the `[..]` catchall to handle any input.  I can submit a PR if no one objects.

**Comment by SergVM** [comment]
I do not know what PR, but I do not mind ;)

**Comment by watou** [comment]
@SergVM: Reading the history further, it looks like your transform should have returned the empty string, in addition to having logged the warning you showed.  Did the transform return the empty string?  This was decided and changed back in February/March.  See https://github.com/eclipse/smarthome/issues/1107.  If the transform returned the empty string as intended, is that not sufficient for your needs?

**Comment by SergVM** [comment]
Hello! Yes, I figured out already!
[..] = Undef
you must make the last
[0..10] = test1
[11..20] = test2
[..] = Undef
As stated in the above example, all the fault of my bad English.
Now all is well, thank you!
