### ISSUE TITLE
Hue: ThingHandler: Stop copy the bridge status

### ISSUE THREAD

**Issue by maggu2810** [eclipse/smarthome#991]
Keep track of the comments here: https://github.com/eclipse/smarthome/pull/721/files#r52004560

https://github.com/eclipse/smarthome/blob/93b502790376880f28515ce01fef69446ff44f73/extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java#L93
We should not copy the status of the bridge with all the details (which might not make sense for the device).

**Comment by kaikreuzer** [comment]
@sbussweiler According to https://github.com/eclipse/smarthome/commit/907c9e116693294fe69295dbaba724d76870d6aa, this was introduced by you with the extended status handling. Do you agree that this is not the correct way of doing it? If so, could you provide a fix (not urgent)?

**Comment by sbussweiler** [comment]
The thing status of the bridge was already copied before 907c9e1.  But I agree. It make no sense to copy the status of the bridge. Especially the status detail and the description must be device specific. I can fix it in the HUE binding.

**Comment by maggu2810** [comment]
@sbussweiler Are you still planning to fix this for the Hue binding?

**Comment by sbussweiler** [comment]
Oh, I have forgotten it! Thanks for reminding me. I will fix it...

**Comment by kaikreuzer** [comment]
@sbussweiler Ping!

**Comment by sbussweiler** [comment]
This status handling has been fixed long time ago @kaikreuzer (but not from me ;-) ). You can close it. See [here](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java#L109)

**Comment by kaikreuzer** [comment]
Then we have an issue less, wonderful :-)
