### ISSUE TITLE
DateTimeType is not reconstructable from its String serialization

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse/smarthome#992]
For all Types, we have the general assumption that they should be reconstructable from their string representation, i.e. `typeX.equals(new TypeX(typeX.toString()))` should be true.

This is currently not the case for the DateTimeType, since the toString methods cuts off the milliseconds, which are contained within the internal Calendar object.

**Comment by watou** [comment]
> For all Types, we have the general assumption that they should be reconstructable from their string representation, i.e. typeX == new TypeX(typeX.toString()) should be true.

Do you mean `typeX.equals(new TypeX(typeX.toString())`?

> This is currently not the case for the DateTimeType, since the toString methods cuts off the milliseconds, which are contained within the internal Calendar object.

Other DateTime information is also not preserved in the string format.  It's worth considering fixing the omission of time zone as well as milliseconds in the string format using ISO8601 formatting.  Currently no time zone is serialized, so DateTimeType is unusable by itself for use with multiple timezones.

**Comment by kaikreuzer** [comment]
> Do you mean typeX.equals(new TypeX(typeX.toString())?

Of course, corrected it above now!

**Comment by clinique** [comment]
This would mean changing the actual contract (and according tests) of DateTimeType.toString() - right ?

**Comment by kaikreuzer** [comment]
Right.

**Comment by kaikreuzer** [comment]
Fixed with https://github.com/eclipse/smarthome/pull/1050

**Comment by marcelrv** [comment]
as @watou indicated:
> Other DateTime information is also not preserved in the string format. It's worth considering fixing the omission of time zone as well as milliseconds in the string format using ISO8601 formatting. Currently no time zone is serialized, so DateTimeType is unusable by itself for use with multiple timezones.

This is indeed an issue for other bindings as well... see e.g. 
https://github.com/eclipse/smarthome/issues/1666
